### ISSUE TITLE
White border on PDF output

### ISSUE THREAD

**Issue by vmx** [ariya/phantomjs#10061]
_**[volker.m...@gmail.com](http://code.google.com/u/101958613052344638213/) commented:**_
> <b>What steps will reproduce the problem?</b>
1. Save the attached HTML
> 2. Run current HEAD with: phantomjs examples/rasterize.js borderbug.html out.pdf &quot;800*600&quot;
> 3. View out.pdf
> 
> <b>What is the expected output? What do you see instead?</b>
Expected is a page which is fully red. But on the left and the bottom there's some white border.
> 
> 
> <b>What version of the product are you using? On what operating system?</b>
Debian testing/unstable hybrid. Checkout from about 2 hours ago.
> 
> I've attached a fix for the bug. Though I this only cures the problem and I think there should be a better fix (perhaps upstream?).

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #61](http://code.google.com/p/phantomjs/issues/detail?id=61).
:star2: &nbsp; **8** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
This bug was reported against PhantomJS 1.x, which is no longer being developed.  We'll test it with 2.0, but if you have time to download the current version from http://phantomjs.org/download.html and try it, that would be helpful.

**Comment by vmx** [comment]
Thanks for caring about such an old issue. I've tried to reproduce the original issue with PhantomJS 1.9.0 (installed on Debian testing) as well as current master. I couldn't see a white border anymore. Hence closing the issue.

**Comment by motoservo** [comment]
I've got this same issue with phantomjs 1.9.7 AND phantomjs 2.0 (via mac ports build). In the CSS channel somebody suggesting it may be from a Mac OS dependency?
