### ISSUE TITLE
Default WebKit Accept header causes problems with some web services/servers

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10112]
_**[timfar...@gmail.com](http://code.google.com/u/100616152580105910025/) commented:**_
> <b>What steps will reproduce the problem?</b>
1. Run the following script:
> 
> if (phantom.state.length == 0) {
>     phantom.state = '1';
>     phantom.open( 'http://gdata.youtube.com/feeds/api/videos?author=geologicrecords&amp;v=2&amp;prettyprint=true&amp;start-index=1&amp;max-results=5' );
> } else {
>     console.log( phantom.content );
>     phantom.exit();
> }
> 
> 2. Fetch the same URL using another tool such as WGET or a recent build of Firefox to see correct results.
> 
> <b>What is the expected output? What do you see instead?</b>
Should show a pretty-printed ATOM feed of the data about 5 videos on YouTube.  Instead, the data is all HTML-escaped for literal display and is surrounded by &lt;html&gt; and &lt;body&gt; tags.
> 
> <b>What version of the product are you using? On what operating system?</b>
PhantomJS 1.1 Mac OS/X 10.6.7
> 
> <b>Please provide any additional information below.</b>
I was able to isolate the problem to the Accept: header being sent by WebKit.  If you Google WebKit Accept header you will see there has been considerable complaints that WebKit is using a bad default, taken from an old build of Firefox.  WGET works correctly because it sends Accept: */*.
> 
> WebKit is prioritizing text/plain too high (and making other errors), so in this case Google's servers sends the result back as &quot;text/plain&quot; and WebKit tries to escape it for easy display.
> 
> At the very least, we should update the default for the Accept: header that is used by default in PhantomJS.  If &lt;a href=&quot;http://code.google.com/p/phantomjs/issues/detail?id=77&quot;&gt;Issue 77&lt;/a&gt; is resolved in a way that allows setting the Accept: header, it should fix this bug as well.  (But I think it would be best to change the default as well).

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #112](http://code.google.com/p/phantomjs/issues/detail?id=112).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
PhantomJS 2.0's `Accept:` header for top-level documents is consistent with that generated by Chromium and Firefox.
