### ISSUE TITLE
phantomjs fails to load any page that does not set a Content-Type header

### ISSUE THREAD

**Issue by Nthalk** [ariya/phantomjs#10128]
_**[pho...@gmail.com](http://code.google.com/u/101084751341114253841/) commented:**_
> <b>What steps will reproduce the problem?</b>
1. Set up a server that does not specify a Content-Type header, but does everything else right ( I used jetty-server, so I could craft everything )
> 2. Try to have a phantom script open a page with new WebPage().open(function(status){console.log(status);phantom.exit()});
> 3. Watch it ALWAYS say fail
> 
> <b>What is the expected output? What do you see instead?</b>
I always see fail, and I really wanted to see success.
> 
> <b>What version of the product are you using? On what operating system?</b>
Linux, git tag 1.1.0, then head (da34ca2d04cdf5ae519fd1515b2c24e84fd47c16)
> 
> <b>Please provide any additional information below.</b>
On all of my testing, the only thing that REALLY mattered was that I sent  the Content-Type header -- It was not being sent by a service of mine, and it took me a long while to figure out why curl was happy and phantomjs was not.
> 
> Workaround: Add a Content-Type header to your service.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #128](http://code.google.com/p/phantomjs/issues/detail?id=128).
:star2: &nbsp; **14** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
Oh dear, I wish I had known about this six months ago.  If it's still an issue in PJS 2.0 it is very likely to have invalidated a huge chunk of my scraping. :frowning:

That said, I'm unable to reproduce the problem-as-described in PJS 2.0, using `https://httpbin.org/response-headers?Content-Type=` which sends back a minimal page with no Content-Type header.

@ariya Do you know to what extent this is still relevant?
