### ISSUE TITLE
Multibyte characters being omitted in HTML

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10126]
_**[lilmuck...@gmail.com](http://code.google.com/u/103083543656221181369/) commented:**_
> I'm using phantomJS to monitor various pages (both mine, and third party) and dump out specific sections of HTML to a file using console.log
> 
> I can't really rely upon particular formats on all the pages, and due to the nature of the pages i can't just use curl and suchlike (some of them employ a heavy amount of JS)
> 
> Anyway - multibyte characters such as  &amp;reg; &amp;copy;  etc (although not the htmlentities, obviously) seem to be completely omitted from the html that's output, however they are visible if i render the page to PNG.
> 
> This is an issue because  Stick&amp;reg;  is different from Stick in the contexts i'm working within.
> 
> Steps to recreate:
> 1:  get a page with a multibyte - non HTML entity character.
> 2: console.log()  the specific part of the page to the terminal.
> 
> I would expect to see something as described above:
> &lt;h1&gt;Stick&amp;reg;&lt;/h1&gt;, but i get  &lt;h1&gt;Stick&lt;/h1&gt;
> 
> This only appears to be an issue on Linux, as it works as expected upon my OSX boxes.
> 
> I'm running it on Debian Squeeze, on a headless server, via xvfb-run 
> using the git version at  1.1

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #126](http://code.google.com/p/phantomjs/issues/detail?id=126).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
I am unable to reproduce this bug with either 1.9 or 2.0 on Debian.  I strongly suspect that this was an issue of terminal encoding, as suggested above, and am going to go ahead and close it.  Original reporter: if you are still experiencing the problem in PhantomJS 2.0, please supply a self-contained HTML page and PhantomJS script that demonstrates the problem.  Note that you should see, e.g., `<h1>Stick®</h1>`, not `<h1>Stick&reg;</h1>`, when the HTML contains a literal U+00AE REGISTERED SIGN.
