### ISSUE TITLE
Trouble opening pages with complex URLs

### ISSUE THREAD

**Issue by tchaymore** [ariya/phantomjs#10130]
_**[thomas.h...@gmail.com](http://code.google.com/u/107661373977080213319/) commented:**_
> <b>What steps will reproduce the problem?</b>
1. Use code below to try and load URL
> 2. Enter one of these URLs: 1) http://www.regulations.gov/#!contactUs; 2) http://www.regulations.gov/#!contactUs
> 3. Never loads
> 
> <b>What is the expected output? What do you see instead?</b>
I expect to see a &quot;result.png&quot; render of the site and also the text output in Terminal of the HTML.  This works just fine with &quot;http://www.regulations.gov&quot;, but not with any of the subordinate links.
> 
> <b>What version of the product are you using? On what operating system?</b>
just downloaded phantomjs today (6/18/11).  On Mac 10.6.
> 
> <b>Please provide any additional information below.</b>
Like I said above, I can download http://www.regulations.gov perfectly.  Works like a charm.  But for any other links, doesn't work -- just hangs and never produces any output.
> 
> Code:
> 
> if (phantom.state.length === 0) {
>      if (phantom.args.length === 0) {
>              var address = &quot;http://www.regulations.gov/&quot;
> 
>      } else {
>              var address = phantom.args[0];
>              
>      }
>      console.log(address)
>      phantom.state = Date.now().toString();
>      phantom.open(address);
> } else {
>      var elapsed = Date.now() - new Date().setTime(phantom.state);
>      if (phantom.loadStatus === 'success') {
>              if (!first_time) {
>                      var first_time = true;
>                      if (!document.addEventListener) {
>                              console.log('Not SUPPORTED!');
>                      }
>                      phantom.render('result.png');
>                      var markup = document.documentElement.innerHTML;
>                      console.log(markup);
>                      phantom.exit();
>              }
>      } else {
>              console.log('FAIL to load the address');
>              phantom.exit();
>      }
> }

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #130](http://code.google.com/p/phantomjs/issues/detail?id=130).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
With 2.0, rasterize.js successfully renders http://www.regulations.gov/#!contactUs provided I increase the timeout to two seconds (otherwise it rasterizes the loading screen instead of the actual page).  Closing.
