### ISSUE TITLE
URL fails to load

### ISSUE THREAD

**Issue by paraschopra** [ariya/phantomjs#10138]
_**[paras1...@gmail.com](http://code.google.com/u/106658522110700319306/) commented:**_
> <b>Which version of PhantomJS are you using?</b>

> 1.20
> 
> <b>What steps will reproduce the problem?</b>
1. Try doing phantomjs rasterize.js &quot;&quot;http://visualwebsiteoptimizer.com/pricing.php?_vis_test_id=69&amp;_vis_opt_preview_combination=2&quot;
> 
> 
> <b>What is the expected output? What do you see instead?</b>

> It says &quot;Unable to load&quot; even though URL is a valid address. (Though note this URL involves a redirect and it finally redirects to http://visualwebsiteoptimizer.com/?_vis_test_id=69&amp;_vis_opt_preview_combination=2
> 
> <b>Which operating system are you using?</b>

> Ubuntu 10.04
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> Compiled from source

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #138](http://code.google.com/p/phantomjs/issues/detail?id=138).
:star2: &nbsp; **6** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
I still get "Unable to load the address!" from

    $ ./bin/phantomjs examples/rasterize.js 'https://vwo.com/?_vis_test_id=69&amp;_vis_opt_preview_combination=2' test.png

with 2.0.

**Comment by zackw** [comment]
... If I hadda guess, though, I'd guess this is somewhere down in the network layer, hence Qt's fault.

**Comment by Vitallium** [comment]
Works for me in 2.1.1
