### ISSUE TITLE
Automate the packaging of Windows build

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10141]
_**[ariya.hi...@gmail.com](http://code.google.com/u/103266860731871773002/) commented:**_

> We shall have a script (maybe batch file?) which automates the process of creating both the static and dynamic builds for Windows.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #141](http://code.google.com/p/phantomjs/issues/detail?id=141).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
Whatever technique is used, probably the users would appreciate it if the builds were Authenticode-signed.  (Maybe that should be a separate issue, though?)

**Comment by ariya** [comment]
Deprioritized for now, see #15398.
