### ISSUE TITLE
loaded image saving

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10159]
_**[comple...@gmail.com](http://code.google.com/u/106019902710675350160/) commented:**_

> may be for the future releases it would be nice to have function to save loaded images from &lt;img src=&quot;...&quot;&gt; tag to disk. It would be very helpfull to save images by some criteria defined in the script excluding double loading the same content first to find images second to retrieve it.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #159](http://code.google.com/p/phantomjs/issues/detail?id=159).
:star2: &nbsp; **10** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
@eni9889 Looks like nobody's had a chance to sit down and figure out exactly how it should work.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
