### ISSUE TITLE
Synchronous mode

### ISSUE THREAD

**Issue by huntc** [ariya/phantomjs#10157]
_**[hunt...@gmail.com](http://code.google.com/u/115752705221915385164/) commented:**_

> In a recent project of mine that uses Phantomjs (1), I found that I had to use recursion to execute multiple tests. The project calls upon Phantomjs to load a list of html pages that represent QUnit pages. The list of test urls is passed as a csv argument to the script. I prefer this mode of operation as opposed to invoking PhantomJS multiple times as it is faster.
> 
> I was wondering if it would be useful if WebPage provided a version of its open method that executed synchronously. In my case I would then be able to call the open method within a loop and then do away with recursion.
> 
> The entire script can be found at (2).
> 
> Thanks.
> 
> (1) http://js-testrunner.codehaus.org/ (at present largely undocumented)
> (2) http://git.codehaus.org/gitweb.cgi?p=js-testrunner.git;a=blob;f=src/main/js/org/codehaus/jstestrunner/run-qunit.js

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #157](http://code.google.com/p/phantomjs/issues/detail?id=157).
:star2: &nbsp; **13** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
It's not clear to me whether this is something that should be in core, but I note that a great many of the test cases in our own test suite contain race conditions because the asynchrony of the API isn't fully handled.

**Comment by huntc** [comment]
I'm ok that this is closed now given the use of promises. I don't think I understood how promises could solve this four years back. Thanks.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
