### ISSUE TITLE
Adding support for getting body of requests or responses

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#10158]
_**[saleh...@gmail.com](http://code.google.com/u/116151630419619723642/) commented:**_
> Adding support for accessing body of requests (useful for http post requests) in the onResourceRequested call back.
> 
> Which version of PhantomJS are you using? 1.2

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #158](http://code.google.com/p/phantomjs/issues/detail?id=158).
:star2: &nbsp; **31** people had starred this issue at the time of migration.

**Comment by vic-cw** [comment]
@bshamric thanks a lot for the tip on checking the cache. Did you find a way to decompress the files after you get their contents ?

**Comment by zackw** [comment]
Retagging -- it sounds like there's several patches floating around and it's a "simple matter" of getting them unified and tested and committed?

**Comment by Paxa** [comment]
Common dude, it's been almost 4 years, people need this feature. And it's 3 years since my first pull request, and I refreshed 2 years ago.

If you really don't like my code (and any other pull requests if there are any), just sit and code it by yourself. It took for me just couple hours without any experience with C++ before. Or you want to wait another couple years? :)

I always wonder why people like to reject pull requests instead of fix it and merge it if code not perfect.

**Comment by zackw** [comment]
@Paxa I'm just digging through old bugs and figuring out which still need something done, I haven't looked at your code at all.  We _will_ get to it eventually.

**Comment by diorray** [comment]
Any updates about this issue?

**Comment by madelson** [comment]
:+1:

**Comment by Paxa** [comment]
:+1:

**Comment by jonatascastro12** [comment]
:+1:

**Comment by shlomis** [comment]
+1

**Comment by eperez84** [comment]
Anxiously awaiting the addition of this feature!

**Comment by Vitallium** [comment]
Landed in 434d4e0101a540525e8f89a657ea553fb38b040b

**Comment by Noiwex** [comment]
```Response (#1, stage "start"): {"body":"","bodySize":169...```
```Response (#1, stage "end"): {"body":"","bodySize":0```
what the hell

**Comment by alexdrk** [comment]
@Noiwex I had the same problem, if you change  "shouldCaptureResponse(req.url().toString())" to just "true" ( https://github.com/ariya/phantomjs/blob/54a54dc0687a4b93562285d4f632dcafe2c7bf4f/src/networkaccessmanager.cpp#L388 ) without the double quotes it should return every response. Apparently this is just a quick (and probably wrong) hack to get the responses. There must be some way to set the pattern for the urls to match in javascript, but I haven't figured it out.

**Comment by rockswang** [comment]
Are there any documentation about this feature?

**Comment by vanillycpp** [comment]
I didn`n find documentation
just this http://stackoverflow.com/questions/22058321/status-of-phantomjs-onresourcereceived-response-body-work

**Comment by arrowing** [comment]
How long I can use reponse body in released version?

**Comment by Noiwex** [comment]
https://github.com/ariya/phantomjs/issues/10158#issuecomment-126271458

or make changes in cpp and compile

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://whitetiemusic.hu/category.php?1l23>

 

klaus@hebsgaard.dk

**Comment by Noiwex** [comment]
Whoever wrote that spam bot — you're a moron.

**Comment by MichalBu** [comment]
This fix was removed from 2.1.1 - why? 
How can I get the build with this feature?

**Comment by Vitallium** [comment]
@MichalBu You can find more information here https://github.com/ariya/phantomjs/pull/13922

**Comment by jbruggeman** [comment]
I was able to hack together some code together to re-add this functionality. Basically I edited QNetworkReply to overload read/readAll, intercept the data, and dump it to a QByteArray. I then exposed and Base64 encoded it. 

It's not nice (one might even call it terrible), but it works. I will open source my work if there's interest.

**Comment by jksecurity** [comment]
@jbruggeman As I really need this feature urgently, could you explain how to set this up using the sources you provided? I am not sure how I would get the build to pick up the recompiled qtbase for example.

**Comment by jbruggeman** [comment]
Hi,

Just clone the repos and follow the normal build steps for phantom.

**Comment by Frogmouth** [comment]
@jbruggeman ... Can you explain the process however? I'm not skilled in "build process" but I need the "body response" :( I have already build the Ariya's version with the method that i find i this page: http://phantomjs.org/build.html... but I don't think it's correct also for yours release.

**Comment by lifuchao** [comment]
@jbruggeman  would you please supply a compiled phantomjs with onResourceReceived response.body?thanks a lot.my e-mail is :126820822@qq.com

**Comment by lifuchao** [comment]
@MichalBu can you use onResourceReceived response.body now ? I encountered this issue,can you help me ?

**Comment by artemeus** [comment]
@ariya @Paxa Could anyone please help me understand why we have been unable to add this feature to master in 5+ years? Really need it (and less mature frameworks like SlimerJs already have it), yet can't make myself commit to hacking together a build..

**Comment by Paxa** [comment]
I don't know, this situation feels weird to me. I already switched to slimerjs, it's also faster and not require few hours to compile

**Comment by Vitallium** [comment]
The problem is that this feature broke AJAX requests. That's why we reverted it.

**Comment by artemeus** [comment]
@Paxa @Vitallium Thank you for quick replies gentlemen!
I guess it is a dead end then.
I will try replacing PhantomJS executable with SlimerJs in Java with Selenium WebDriver code and see whether I can execute all the same unit tests. Hoping I don't have to jump extra hoops to get headless experience on Linux with it.

**Comment by developez** [comment]
Hello. I also need the body with the content overhere to download some pdf from website. This is an obvious comment but here on file 'networkaccessmanager.cpp' on line 454 (https://github.com/ariya/phantomjs/blob/master/src/networkaccessmanager.cpp#L454) the body property is assigned to emtpy string so how can we expect that be filled? Why can't we take the content from QNetworkReply or that object hasn't got the content?

**Comment by tasoss** [comment]
Can somebody pretty please update on this issue?

**Comment by dmitriyse** [comment]
I also require this "must have" feature.

**Comment by tasoss** [comment]
I don't understand why don't you answer.Because you believe that the answer is already mentioned above?
Which means that it can't be implemented.It breaks ajax requests so you can't fix it right?Can you please lock the thread please?

**Comment by amanda94** [comment]
I find that I can get postData in requestData for POST requests by listening the event onResourceRequested.But for PUT or PATCH  methods, postData do not exist , is there anyway I can get the data for PUT or PATCH？or I should add some extra settings ?  Also when I find  the method is a "?" when I try to send PATCH or DELETE  Ajax requests

**Comment by artemeus** [comment]
Set up ChromeDriver with headless Chrome. PhantomJS is dead.
