### ISSUE TITLE
chinese charset not show right

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10164]
_**[coley...@gmail.com](http://code.google.com/u/102164358569349162579/) commented:**_
> <b>Which version of PhantomJS are you using?</b>
  1.2
> 
> <b>What steps will reproduce the problem?</b>
1.phanthomjs examples/render_multi_url.js www.sohu.com
> 2.see generated www.sohu.com.cn.png
> 3.can't not render chinese charset
> 
> <b>What is the expected output? What do you see instead?</b>
  render chinese charset right
> <b>Which operating system are you using?</b>
  windows xp sp3
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
  1.2
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #164](http://code.google.com/p/phantomjs/issues/detail?id=164).
:star2: &nbsp; **10** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
PhantomJS 2.0 includes a major update to Webkit that may well have solved this problem, and I cannot reproduce it (on Debian) with any of the suggested test URLs.  It's possible that there is still a problem with some combination of character encodings and fonts, but I'm going to go ahead and close this issue.  If you are still having this problem, please file a new issue and be specific about what website, what characters, and what fonts are involved.

**Comment by vaneri** [comment]
Had a similar issue on Ubuntu; installing the Chinese fonts such as described in this link, helped me out
https://en.wikipedia.org/wiki/Help:Multilingual_support_(East_Asian)

sudo apt-get install fonts-arphic-ukai fonts-arphic-uming fonts-ipafont-mincho fonts-ipafont-gothic fonts-unfonts-core

**Comment by zackw** [comment]
@vaneri Yes, PhantomJS doesn't bundle any fonts.

**Comment by vaneri** [comment]
Is there a way to bundle font in phantomjs ?

**Comment by zackw** [comment]
@vaneri We don't have any way to do that right now.  I think it's *possible*, but it would be a big chunk of new code to write.  I don't think any of us has time to do it anytime soon, sorry.

**Comment by vaneri** [comment]
thanks for the info @zackw ;)

**Comment by Vitallium** [comment]
I think we can extend our qpa plugin with this feature (or by this http://doc.qt.io/qt-5/qfontdatabase.html#addApplicationFont). i.e. add a custom option to specify font folders. But this is a just my guess.

**Comment by alex88** [comment]
I've the same issue, no system chinese fonts, but even when i import some custom fonts including chinese glyphs it doesn't work.
E.g. I import 2 fonts from typekit, regular alphabet works fine, chinese doesn't

**Comment by koodalingam** [comment]
Hi, While being export to pdf using phantomJS, some of the Chinese characters are missing. Can you help on this?

**Comment by vaneri** [comment]
The best is to check if the font are installed on your OS; it must be the
issue ;)

**Comment by koodalingam** [comment]
Thanks for the reply. Required fonts are installed on my OS. Example, the HTML content has 

> Simple 中国是东亚人口众多的国家，其广阔的景观包括草原。

Its output was Simple 中国是东  人口众多的国家，其广阔的景观包括草. Here **亚** is replaced by space.
