### ISSUE TITLE
bodySize wrong values

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10169]
_**[peniz...@gmail.com](http://code.google.com/u/106904910648942447482/) commented:**_
> Used version: PhantomJS 1.2.0 Windows executable 
> Operating system: WinXP, Win7
> 
> There are very often not correct values of &quot;bodySize&quot; which did not correspond with real sizes of downloaded elements.
> 
> Optimal would to report by &quot;bodySize&quot; values information about sizes of elements as are comming into browser from server. That means e.g. size of gzipped elemnts for http/text.
> 
> Radek Penizek

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #169](http://code.google.com/p/phantomjs/issues/detail?id=169).
:star2: &nbsp; **5** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
This seems likely to be the same as issue #10156.
