### ISSUE TITLE
window.showModalDialog()

### ISSUE THREAD

**Issue by Fonrus** [ariya/phantomjs#10172]
_**[pconi...@gmail.com](http://code.google.com/u/107403726985815812267/) commented:**_
> window.showModalDialog() needs to be implemented. Including how it handles scoping and semi blocking other code execution in browser.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #172](http://code.google.com/p/phantomjs/issues/detail?id=172).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
This would have to be implemented in Webkit.  It is not clear to me whether it ever *was* implemented in Webkit, but it is deprecated and is in the process of being removed from Chrome, Firefox, and IE:

* http://tjvantoll.com/2012/05/02/showmodaldialog-what-it-is-and-why-you-should-never-use-it/ 
* https://blog.chromium.org/2014/07/disabling-showmodaldialog.html
* https://developer.mozilla.org/en-US/docs/Web/API/Window/showModalDialog
* https://twitter.com/jacobrossi/status/588353411168346113

I am therefore inclined to say that it is not a feature PhantomJS should add.
