### ISSUE TITLE
Rasterizing a page image where page changes size is failing

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10179]
_**[si_pars...@hotmail.com](http://code.google.com/u/109251422944011130992/) commented:**_

> 1.1
> 
> <b>What steps will reproduce the problem?</b>
> 1. I have a web page that i load with phantom.open() that contains a number of divs which by default have a style of display:none;
> 1. Once the page has been loaded by phantomjs I have a small loop which sets the display style for each of these divs to block (I want the rasterized image to include the contents of these otherwise hidden divs)
> 2. When I rasterize the page the size of the image is the size of the page before any of the divs were expanded and as a result the image is not tall enough to contain the entire content of the page.
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> I expected to see an image containing the entire web page, including the contents of the divs i set to display:block. Unfortunately is seems that the size of the rasterized image is calculated based on the height of the page when it is loaded, and does not take into account the fact that the page will be taller once all of the hidden content is displayed on it.
> 
> <b>Which operating system are you using?</b>
> 
> Windows 7
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> binary
> 
> <b>Please provide any additional information below.</b>
> 
> is there way of recalculating the height of the image which is rendered?

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #179](http://code.google.com/p/phantomjs/issues/detail?id=179).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
This is the script that was posted as an attachment on Google Code.

~~~~
var stateMachine;

if (phantom.state.length === 0) {
	stateMachine = new Object();
	stateMachine.currentStep = 0;
	
	if (phantom.args.length != 4) {
		console.log ("Usage: PhantomJs.exe [{scriptOptions}] [scriptName] [pageUrl] [outputFolder] [outputFilename]");
		console.log ("       where [{scriptOptions}) : Optional: phantom execution options, see phantom documentation");
		console.log ("             [scriptName]      : The name of this script");
		console.log ("             [pageUrl]         : The url of the page to capture");
		console.log ("             [controlId]       : The id of the control leading to the next screen");
		console.log ("             [outputFolder]    : The folder where captured images should be stored");
		console.log ("             [outputFilename]  : The name of the output file");
		console.log ("");
		console.log ("Example:");
		console.log ("        PhantomJs --load-images=no ScreenShot.js http://marabouStork.co.uk c:\\crawlers.output\\pagecache\\images abc123.png");
		
		phantom.exit();
	}
	else {	
		stateMachine.url = phantom.args[0].replace(/(?:^\"|\"$)/g, "");
		stateMachine.controlId = phantom.args[1];
		stateMachine.outputDir = phantom.args[2].replace(/(?:^\"|\"$)/g, "").replace(/\\/g, "/").replace(/\/$/, "") + "/";
		stateMachine.outputFile = phantom.args[3];
		
		phantom.state = JSON.stringify(stateMachine);
	}
}
else {
	stateMachine = JSON.parse(phantom.state);
}

var IncrementStep = function() {
	stateMachine.currentStep ++;
	phantom.state = JSON.stringify(stateMachine);
}

var getDocHeight = function() {
    var D = document;
    return Math.max(
        Math.max(D.body.scrollHeight, D.documentElement.scrollHeight),
        Math.max(D.body.offsetHeight, D.documentElement.offsetHeight),
        Math.max(D.body.clientHeight, D.documentElement.clientHeight)
    );
}

var getDocWidth = function() {
    var D = document;
    return Math.max(
        Math.max(D.body.scrollWidth, D.documentElement.scrollWidth),
        Math.max(D.body.offsetWidth, D.documentElement.offsetWidth),
        Math.max(D.body.clientWidth, D.documentElement.clientWidth)
    );
}

console.log("current Step: " + stateMachine.currentStep);

switch (stateMachine.currentStep){
    case 0:
		IncrementStep();
		
        phantom.viewportSize = { width: 1024, height: 768 };
        phantom.open(stateMachine.url);
    break;

	case 1:
		IncrementStep();
		
		phantom.sleep(1000);
		
		var button = document.querySelectorAll("input[name='"  + stateMachine.controlId + "']")[0];
		console.log("button:" + button.name);
		button.click();
		
	break;
	
	case 2:
	
		var docHeight = getDocHeight();
		var docWidth = getDocWidth();
	
		phantom.clipRect = { top: 0, left: 0, width: docWidth, height: docHeight }
		phantom.render(stateMachine.outputDir + stateMachine.outputFile);
		
		console.log("<output>");
		console.log("\tfile://images/" + stateMachine.outputFile);
		console.log("</output>");
		
        phantom.exit();
    break;
}

~~~~

**Comment by zackw** [comment]
Based on other, newer bugs, it seems quite likely that this is still an issue in 2.0, but I can't test it because the script is for the old API and the website referenced seems to have changed substantially in the interim.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
