### ISSUE TITLE
when more than one page is opened, that resources for each new page are requested more times than they should

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10183]
_**[*mark.cu...@scrazzl.com](http://code.google.com/u/111822502563497831867/) commented:**_
> Note: This might be related to https://groups.google.com/group/phantomjs/browse_thread/thread/3f7a76c88c4dbca7
> but i doubt it. 
> 
> <b>Which version of PhantomJS are you using?</b>

> Version 1.2.0
> 
> <b>What steps will reproduce the problem?</b>
1. Follow my code on http://pastebin.com/3AbWMGZz
> 2. uncomment the lines at the top starting with urlList as specified to 
> test with multiple urls
> 3. run the code phantomjs mycode.js
> 
> <b>What is the expected output? What do you see instead?</b>
Expected:
> Report for http://www.chrischiu.com/testblank1 Load time 118 RequestsTotal : 1
> Report for http://www.chrischiu.com/testblank2 Load time 117 RequestsTotal : 1
> 
> Result:
> Report for http://www.chrischiu.com/testblank1 Load time 118 RequestsTotal : 2
> Report for http://www.chrischiu.com/testblank2 Load time 117 RequestsTotal : 1
> 
> So to summarise, if you have 1 url. that url gets requested once. 
> If you have 2 urls, the first one gets requested once, the second one gets requested twice. (it continues on, the third 3 times and so on)
> 
> Try this on any page with just a blank html content. if you try this on the same page multiple times you can see this however when printing the address, you won't be able to tell the difference between the page counts
> 
> 
> 
> 
> <b>Which operating system are you using?</b>
Tested on : 
> ubuntu 11.04 phantom 1.2.0
> OSX 10.7 (from brew) phantom 1.2.0
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
ubuntu:
> source via: http://code.google.com/p/phantomjs/wiki/BuildInstructions
> sudo apt-get install libqt4-dev libqtwebkit-dev qt4-qmake
>   git clone git://github.com/ariya/phantomjs.git &amp;&amp; cd phantomjs
>   git checkout 1.2
>   qmake-qt4 &amp;&amp; make
> 
> OSX - brew
> 
> <b>Please provide any additional information below.</b>

> I'm fairly sure this is a problem with phantomjs but it could be a misunderstanding of the code. This is just one example of where something is definitely wrong.
> 
> Originally the problem stemmed from trying to access 
> resource.endReply.status;
> after loading has completed by doing a foreach on resources.
> resource.endReply was null on some of them which caused the script to stop.
> I wrote the example code to try and debug if something odd was happening somewhere.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #183](http://code.google.com/p/phantomjs/issues/detail?id=183).
:star2: &nbsp; **6** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
With phantomjs 2.0 each page is loaded only once.
