### ISSUE TITLE
Resources statistics

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10189]
_**[faort...@gmail.com](http://code.google.com/u/110703876810567162830/) commented:**_
> I see people speak about status code, body size and others resource properties, maybe is a good idea integrate in phantomjs some script of WebInspector they provide all this information and more. If you want to try open a WebInspector window, in some webkit browser based like chromium, and then inspect this window and in the javascript console type WebInspector en press &quot;enter&quot; to see all the object properties

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #189](http://code.google.com/p/phantomjs/issues/detail?id=189).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
Closing this as a duplicate of #10006.  Please file new bugs for any functionality that is missing from the remote-debugger interface.
