### ISSUE TITLE
Have PhantomJS return the status code

### ISSUE THREAD

**Issue by fdb** [ariya/phantomjs#10185]
_**[frede...@burocrazy.com](http://code.google.com/u/102319527505493489896/) commented:**_

> 1.2.0 (development)
> 
> It would be useful to see the status code of a page request. status is now a string which returns 'success' if the request fails, even if the web server encountered an error or the page was not found. 
> 
> Here's how this might look:
> 
> ```
> page.onLoadFinished = function(status) {
>   if (status === 200) {
>     console.log('Page found.');
>   } else if (status === 404) {
>      console.log('Page not found.');
>   } else {
>      console.log('Other error: ' + status);
>   }
> }
> ```

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #185](http://code.google.com/p/phantomjs/issues/detail?id=185).
:star2: &nbsp; **21** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
I have this problem too -- my crawler script ( https://github.com/zackw/tbbscraper/blob/master/scripts/pj-trace-redir.js ) goes to considerable length to figure out the "right" status for the top-level page, and I'm still not sure it's 100% accurate.

**Comment by zackw** [comment]
Issue #10188, which I've just closed as a duplicate of this one, proposes to attach the resource object for the current page (that is, the information passed to `onResourceReceived`) to the `WebPage` object.  I think that's enough design that someone could sit down and try to crank out some code.  It might even be me, if no one gets to it first.

**Comment by Zertz** [comment]
@mbrio Clever! Seems to work great in my own testing.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
