### ISSUE TITLE
Allow WebPage to access resource details for the opened page

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10188]
_**[nick.rab...@gmail.com](http://code.google.com/u/118261822197534781054/) commented:**_
> There doesn't seem to be an easy way of  identifying a 404 response (or other response code) in PhantomJS. Ideally there would be an easy way within the page.open() callback to get the resource details for the URL I just opened, including the HTTP status.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #188](http://code.google.com/p/phantomjs/issues/detail?id=188).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
I like the idea of attaching the resource object for the current page, to the WebPage object somehow.  It seems to me that that would be not *too* hard to implement and would resolve #10185.  I'm inclined to say that the dev work should be tracked there, though.
