### ISSUE TITLE
Consider not using alert in includeJS

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10203]
_**[ariya.hi...@gmail.com](http://code.google.com/u/103266860731871773002/) commented:**_

> It's a possible leak of our abstraction.
> 
> Maybe we can use other method to notify the script loading is completed.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #203](http://code.google.com/p/phantomjs/issues/detail?id=203).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
That sure is a convoluted way of injecting a script into a page and then learning that it's loaded, boy howdy.  And I'm pretty sure a page can detect it.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
