### ISSUE TITLE
windows-1251 codepage incorrectly recognized as cp1252

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10208]
_**[nikolay....@gmail.com](http://code.google.com/u/105999886700224735730/) commented:**_
> <b>Which version of PhantomJS are you using?</b>

> 1.2
> 
> <b>What steps will reproduce the problem?</b>

> trying to load page http://a.mod-site.net/gb/u/shumil-1.html which is cp1251 encoded
> 
> <b>What is the expected output? What do you see instead?</b>

> I expect to get correct unicode text, instead I got cp1252 decoded to unicode text.
> 
> <b>Which operating system are you using?</b>

> Debian GNU/Linux 6.0
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> compile
> 
> <b>Please provide any additional information below.</b>

> The page has the following tag:
> &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=windows-1251&quot;&gt;
> 
> which means that the content encoding is cp1251 (not cp1252).

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #208](http://code.google.com/p/phantomjs/issues/detail?id=208).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
http://a.mod-site.net/gb/u/shumil.html appears still to be encoded in Windows-1251, and PhantomJS 2.0 rasterizes it correctly (as far as I can tell, not speaking Russian -- there's no mojibake anyway) provided Cyrillic fonts are installed.
