### ISSUE TITLE
Disabling or working around Same-Origin-Policy

### ISSUE THREAD

**Issue by n1k0** [ariya/phantomjs#10213]
_**[nperria...@gmail.com](http://code.google.com/u/107199586764019623299/) commented:**_

> It would be great to be able to operate on pages embedding (i)frames which contents are loaded from another domain, eg.:
> 
> &lt;!-- location: http://foo.bar/ --&gt;
> &lt;frameset&gt;
>     &lt;!-- ... --&gt;
>     &lt;frame src=&quot;http://baz.bar/&quot; /&gt;
> &lt;/frameset&gt;
> 
> Following the standard cross-domain-policy behavior of the browser, it's impossible to retrieve the DOM contents of the frame using JavaScript, so it would be cool to be able to disable this behavior (eg. with some configuration flasg), or at least to access the (i)frame DOM contents.
> 
> Discussion: https://groups.google.com/d/topic/phantomjs/sMH7W_5V8wE/discussion

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #213](http://code.google.com/p/phantomjs/issues/detail?id=213).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
Disabling web security is a big command-line hammer, and it might actually break webpages that are relying on the silent-failure behavior of cross-domain scripting.  I don't know if this is even possible with the Qt/Webkit API, but something like the Firefox Add-On SDK's notion of "content scripts" [ https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Content_Scripts ], which run in the context of a webpage and have an intermediate level of privilege between regular page JS and extension JS, might address this and a number of other problems (e.g. #10203).

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
