### ISSUE TITLE
Load or rasterizing http://www.zappos.com results in a hanging process

### ISSUE THREAD

**Issue by st3fan** [ariya/phantomjs#10215]
_**[stefan.a...@gmail.com](http://code.google.com/u/115601708255812202489/) commented:**_
> <b>Which version of PhantomJS are you using?</b>

> 1.2
> 
> <b>What steps will reproduce the problem?</b>
1. bin/phantomjs examples/rasterize.js http://www.zappos.com /tmp/image.png
> 
> <b>What is the expected output? What do you see instead?</b>

> Expected: a png image.
> 
> Got: a hanging phantomjs process that did not return an error or time out.
> 
> <b>Which operating system are you using?</b>

> Ubuntu 11.04
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> Compile from source. Other sites work ok.
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #215](http://code.google.com/p/phantomjs/issues/detail?id=215).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
With 2.0, both of the links mentioned above appear to rasterize correctly.
