### ISSUE TITLE
Feature Request: Support Fork() syscall (on supported platforms)

### ISSUE THREAD

**Issue by DanielHeath** [ariya/phantomjs#10222]
_**[daniel.r.heath@gmail.com](http://code.google.com/u/daniel.r.heath/) commented:**_
> I use PhantomJS to load up the same document many times, each time loading a different test script. It would be awesome to be able to load a page object, then use fork to include each extra script in a separate process.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #222](http://code.google.com/p/phantomjs/issues/detail?id=222).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
Regrettably, I expect that calling `fork` after loading a page will cause Webkit to malfunction, and we do not have the resources to pin down and fix -- and *keep* fixing -- all of the reasons for that.
