### ISSUE TITLE
IPC for pages

### ISSUE THREAD

**Issue by SamuraiJack** [ariya/phantomjs#10224]
_**[nickol...@gmail.com](http://code.google.com/u/101802769418898004152/) commented:**_

> Would be great to have an IPC for pages (a-la WebWorkers may be?)
> 
> The poor-man workaround can be:
> 
> page.onConsoleMessage = function (msg) {
>     var match
> 
> ```
> if (match = msg.match(/^__PHANTOMJS__:(.+)/)) {
>     var command     = match[ 1 ]
> 
>     if (match = command.match(/exit\((\d+)?\)/)) {
>         phantom.exit(match[ 1 ] || 0)
>     }
> 
> } else
>     console.log(msg);
> ```
> 
> };

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #224](http://code.google.com/p/phantomjs/issues/detail?id=224).
:star2: &nbsp; **12** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
Definitely desirable; internally we have kludged around its absence in a few places, in fact.

**Comment by ptandler** [comment]
Any news here? What is the current state?
http://phantomjs.org/inter-process-communication.html doe not talk about Js callbacks

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
