### ISSUE TITLE
Unit test for JSON config

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10221]
_**[ariya.hi...@gmail.com](http://code.google.com/u/103266860731871773002/) commented:**_

> Related to issue 180.
> 
> We need to have several tests which create WebPage with different options and check that the config is applied properly.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #221](http://code.google.com/p/phantomjs/issues/detail?id=221).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
I believe this is still a gap in the current automated test suite.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
