### ISSUE TITLE
Unable to send any headers to site using https connection.

### ISSUE THREAD

**Issue by DChistyakov** [ariya/phantomjs#10233]
_**[chistyak...@gmail.com](http://code.google.com/u/112700405721582146703/) commented:**_

> Hello,
> first of all let me please thank you for such a greate job! It`s really very useful and cool!
> 
> Have just downloaded and compilled current master e960279ff26048fd7a366b86bae82ed178564127.
> 
> I`ve tried the same script with https and http hosts usind proxy. Here is the example of headers using https (dump from proxy server):
> 
> array(4) {
>   [&quot;_requst&quot;]=&gt;
>   string(35) &quot;CONNECT www.google.com:443 HTTP/1.1&quot;
>   [&quot;proxy-connection&quot;]=&gt;
>   string(10) &quot;keep-alive&quot;
>   [&quot;user-agent&quot;]=&gt;
>   string(11) &quot;Mozilla/5.0&quot;
>   [&quot;host&quot;]=&gt;
>   string(14) &quot;www.google.com&quot;
> }
> 
> And here the same script headers but using http (dump from proxy server):
> 
> array(10) {
>   [&quot;_requst&quot;]=&gt;
>   string(60) &quot;GET http://www.google.com/accounts/ServiceLoginAuth HTTP/1.1&quot;
>   [&quot;user-agent&quot;]=&gt;
>   string(117) &quot;Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7; en-us) AppleWebKit/533.4 (KHTML, like Gecko) Version/4.1 Safari/533.4&quot;
>   [&quot;proxy-authorization&quot;]=&gt;
>   string(86) &quot;Basic ............................&quot;
>   [&quot;............&quot;]=&gt;
>   string(12) &quot;............&quot;
>   [&quot;expect&quot;]=&gt;
>   string(0) &quot;&quot;
>   [&quot;accept&quot;]=&gt;
>   string(90) &quot;application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,_/_;q=0.5&quot;
>   [&quot;connection&quot;]=&gt;
>   string(10) &quot;Keep-Alive&quot;
>   [&quot;accept-encoding&quot;]=&gt;
>   string(4) &quot;gzip&quot;
>   [&quot;accept-language&quot;]=&gt;
>   string(4) &quot;en,*&quot;
>   [&quot;host&quot;]=&gt;
>   string(14) &quot;www.google.com&quot;
> }
> 
> Please make it works the same with http and https. Or at least add on opportunity to set a useragent or headers at all.
> Thanks a lot for such great code!
> 
> FreeBSD serv233.sp 8.2-RELEASE FreeBSD 8.2-RELEASE #0: Thu Feb 17 02:41:51 UTC 2011     root@mason.cse.buffalo.edu:/usr/obj/usr/src/sys/GENERIC  amd64
> 
> QMake version 2.01a
> Using Qt version 4.7.3 in /usr/local/lib/qt4

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #233](http://code.google.com/p/phantomjs/issues/detail?id=233).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
On behalf of the PhantomJS team, I apologize for letting this bug linger unaddressed for years.

I think what's going on here is, PhantomJS will send custom headers to an *origin* server over proxied HTTPS just fine -- at least, I assume it will -- but the CONNECT command sent to the *proxy* doesn't get any of those headers.  I do not know what is supposed to happen here; I'm unfamiliar with explicit HTTPS proxies.  (It would be entirely plausible to me if the proxy was NOT supposed to receive any but the most generic of request headers under these conditions.)

To do anything about this, we need to figure out:

* What the relevant Web standards say about this.
* Whether the situation is still the same in PhantomJS 2.0.
* Whether it makes sense to be able to specify custom headers *for the proxy* independent of custom headers *for the origin server*, and if so, what the API for that should look like.

I think this is all stuff that we (the PhantomJS devs) *can* figure out for ourselves, but we may not get to it anytime soon; if you have time to investigate it even a little, that would be helpful.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
