### ISSUE TITLE
Settings to control network capture

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10236]
_**[ariya.hi...@gmail.com](http://code.google.com/u/103266860731871773002/) commented:**_

> Network capture introduces performance penalty.
> 
> The page settings should have some config variables to
> - disable the capture completely
> - capture everything
> - capture only the metadata (without the data/body)

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #236](http://code.google.com/p/phantomjs/issues/detail?id=236).
:star2: &nbsp; **5** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
@ariya I'm not sure what you mean by "network capture" here.  Is this even still relevant?

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
