### ISSUE TITLE
Support more console methods

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10232]
_**[Termthom...@extjs.com](http://code.google.com/u/110152297210373073600/) commented:**_

> http://getfirebug.com/wiki/index.php/Console_API
> 
> console.log, console.info &amp; console.debug should write to STDOUT
> console.warn &amp; console.error should write to STDERR
> 
> console.group &amp; console.groupCollapsed should prepend whitespace to all console messages until a console.groupEnd.
> 
> support console.count &amp; console.time ... console.timeEnd, etc…

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #232](http://code.google.com/p/phantomjs/issues/detail?id=232).
:star2: &nbsp; **5** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
It looks to me like there are a bunch of improvement requests tangled up in here:

- [x] Support the full Console API in controller scripts; this appears to be done in 2.0, although perhaps the *output* could be better...

  ~~~~
  phantomjs> console.__proto__
  {
     "assert": "[Function]",
     "clear": "[Function]",
     "count": "[Function]",
     "debug": "[Function]",
     "dir": "[Function]",
     "dirxml": "[Function]",
     "error": "[Function]",
     "group": "[Function]",
     "groupCollapsed": "[Function]",
     "groupEnd": "[Function]",
     "info": "[Function]",
     "log": "[Function]",
     "profile": "[Function]",
     "profileEnd": "[Function]",
     "table": "[Function]",
     "time": "[Function]",
     "timeEnd": "[Function]",
     "timeStamp": "[Function]",
     "trace": "[Function]",
     "warn": "[Function]"
  }
  ~~~~

- [x] Support the full Console API in `page.evaluate` JS; again, this seems to be done in 2.0, at least insofar as the full API is *visible* to `page.evaluate` scripts -- I haven't tested them all.
- [ ] A controller script that hooks `page.onConsoleMessage` should be able to distinguish the various types of console messages.  If this has already happened, it's not in the documentation.
- [ ] possibly more stuff?

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
