### ISSUE TITLE
segmentation fault on history.pushState()

### ISSUE THREAD

**Issue by jedahu** [ariya/phantomjs#10244]
_**[jed...@gmail.com](http://code.google.com/u/108725710963348730353/) commented:**_
> Which version of PhantomJS are you using?
> 
>     1.3.0
> 
> <b>What steps will reproduce the problem?</b>

>     window.history.pushState(1, null, &quot;#foo&quot;);
>     console.log(location.hash);
> 
> What is the expected output?
> 
>     &quot;#foo&quot; on stdout
> 
> What do you see instead?
> 
>     segmentation fault
> 
> <b>Which operating system are you using?</b>

>     Linux 2.6.39-ARCH SMP PREEMPT x86_64
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

>     source

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #244](http://code.google.com/p/phantomjs/issues/detail?id=244).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
This appears to work fine in PhantomJS 2.0:

~~~~
$ cat issue10244.html
<!doctype html>
<h2 id="foo">
<script>
window.onload = function () {
  if (location.hash !== 'foo') {
    window.history.pushState(1, null, "#foo");
  }
  console.log(location.hash);
}
</script>
$ cat issue10244.js
var page = require("webpage").create();
var sys = require("system");
page.onConsoleMessage = function (msg) {
  console.log("C: " + msg);
}
page.open(sys.args[1], function (stat) {
  if (stat !== 'success') {
    console.error(stat);
    phantom.exit(1);
  }
  setTimeout(function () { phantom.exit(0); }, 200);
});
$ ./bin/phantomjs issue10244.js issue10244.html
C: #foo
$
~~~~
