### ISSUE TITLE
Fail to load some pages on shop.bruunsbazaar.dk/

### ISSUE THREAD

**Issue by kesla** [ariya/phantomjs#10242]
_**[david.bjorklund@gmail.com](http://code.google.com/u/david.bjorklund/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.3.0 (development)
> <b>What steps will reproduce the problem?</b>
1. ./bin/phantomjs examples/netlog.js http://shop.bruunsbazaar.com/showmodel/?model=23651B4250\&amp;addbread=\&amp;addbread2=JACKET\&amp;color=0\&amp;currentimage=1\&amp;selectedmi= &gt; fail.txt
> <b>2.</b>
<b>3.</b>

> <b>What is the expected output? What do you see instead?</b>
There are a lot of files loaded, but at the end I'll see an &quot;FAIL to load the address&quot;
> 
> <b>Which operating system are you using?</b>
Ubuntu 11.04 64-bit
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Compile from source
> 
> <b>Please provide any additional information below.</b>
Not all sites fail, some work. For example, http://shop.bruunsbazaar.com/showlist/?saitemtype=D-BA&amp;collection=BB&amp;gender=W&amp;addbread=BAG&amp;selectedmi=a1_INDEX_0 work.
> 
> Attached is the failing output that comes as a result of running the netlog.js example above.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #242](http://code.google.com/p/phantomjs/issues/detail?id=242).
:star2: &nbsp; **5** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
We apologize for letting this slide for ages.  With PhantomJS 2.0, netlog.js appears to work fine on the URL given in the original problem report.  Given the amount of time elapsed, it could be that the *site* has changed in a way that masks the problem, so please file a new bug if there is still a problem somewhere.  (But only if there is still a problem with 2.0.  1.x is not being developed anymore.)
