### ISSUE TITLE
Feature Req: Provide DNS lookup times and time to first byte metrics

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10245]
_**[vvuk...@escconf.com](http://code.google.com/u/103014586929594702198/) commented:**_

> Using netsniff.js I can get the HAR file with resources timing which is valuable. If possible I would like to also get DNS lookup times and time to first byte of the response.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #245](http://code.google.com/p/phantomjs/issues/detail?id=245).
:star2: &nbsp; **8** people had starred this issue at the time of migration.

**Comment by codehate** [comment]
Can we expect this in PhantomJS 2?

**Comment by zackw** [comment]
Unfortunately, no, this is not in 2.0 and we don't have any timeframe for when it *will* be added, either.  If Qt5 exposes the information needed, we don't know about it.

**Comment by peterstory** [comment]
Has any progress been made towards getting window performance timings? It appears that there is code that implements some of this functionality. For example, `PerformanceTiming::connectStart()`
https://github.com/Vitallium/qtwebkit/blob/phantomjs/Source/WebCore/page/PerformanceTiming.cpp

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
