### ISSUE TITLE
Japanese web pages not rendered properly by static Mac binary

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10249]
_**[mason.at...@gmail.com](http://code.google.com/u/115651105576791670497/) commented:**_

> Which version of PhantomJS are you using? 
> 
> 1.3.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. Download the static Mac build of 1.3 (http://code.google.com/p/phantomjs/downloads/detail?name=phantomjs-1.3.0-macosx-static-x86.zip&amp;can=2&amp;q=)
> 2. Load the test URL below with phantomjs.
>    
>    http://masonmark.com/stuff/euc/
> 
> There's a test script to do this and output the results here:
> 
>   https://gist.github.com/1260734
> 1. See whether the page has Japanese text in it, or jumbled garbage text instead,
> 
> (The test script will print the output to the console, write it to a file, and render it as an image, for easy verification.)
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> The page should contain Japanese text. But instead it contains garbage text.
> 
> <b>Which operating system are you using?</b>
> 
> Mac OS X 10.7.1
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> This problem only exists for me with the binary. When I compile it from source, the problem is gone, and Japanese text correctly appears in script output, web page content, and rendered image.
> 
> <b>Please provide any additional information below.</b>
> 
> The gist above also includes sample output to illustrate the problem. I have not tested on Windows or Linux.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #249](http://code.google.com/p/phantomjs/issues/detail?id=249).
:star2: &nbsp; **6** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
PhantomJS 2.0 on Linux renders the test case at http://masonmark.com/stuff/euc/ correctly.  I am going to leave this open until someone gets a chance to test it on OSX.

**Comment by mbykovskyy** [comment]
v2.0 (built from source) doesn't work on Ubuntu 12.04.

**Comment by mbykovskyy** [comment]
Ok, got it to work on Ubuntu 12.04. I was just missing a font. Installing `fonts-ipafont-gothic` fixed it. In fact both 1.9.8 and 2.0 worked on Ubuntu and OSX.

**Comment by soulteary** [comment]
@mbykovskyy And i test 2.0 on Ubuntu 14.04.3 success, :D

Here is the debian font package list, maybe @ariya should put it in FAQ docs.

https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=fonts-

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
