### ISSUE TITLE
segmentation fault error

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10255]
_**[dfilato...@gmail.com](http://code.google.com/u/112366180731945629034/) commented:**_

> Which version of PhantomJS are you using? 1.3
> 
> Which operating system are you using? linux lucid
> 
> Did you use binary PhantomJS or did you compile it from source? compiled from source
> 
> I have a segmentation fault error on page.evaluate(function() { ... })
> 
> Stacktrace:
> Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff7077e96 in ?? () from /usr/lib/libQtWebKit.so.4
> (gdb) where
> # 0  0x00007ffff7077e96 in ?? () from /usr/lib/libQtWebKit.so.4
> # 1  0x00007ffff71029ff in ?? () from /usr/lib/libQtWebKit.so.4
> # 2  0x00007ffff75eade2 in ?? () from /usr/lib/libQtWebKit.so.4
> # 3  0x00007ffff6d6d8a1 in ?? () from /usr/lib/libQtWebKit.so.4
> # 4  0x00007ffff6d74aa3 in ?? () from /usr/lib/libQtWebKit.so.4
> # 5  0x00007ffff6dad797 in ?? () from /usr/lib/libQtWebKit.so.4
> # 6  0x00007ffff6d831c0 in ?? () from /usr/lib/libQtWebKit.so.4
> # 7  0x00007ffff6e63849 in ?? () from /usr/lib/libQtWebKit.so.4
> # 8  0x00007ffff6e775d6 in ?? () from /usr/lib/libQtWebKit.so.4
> # 9  0x00007ffff6e77e35 in ?? () from /usr/lib/libQtWebKit.so.4
> # 10 0x00007ffff71058e9 in ?? () from /usr/lib/libQtWebKit.so.4
> # 11 0x00007ffff718da76 in ?? () from /usr/lib/libQtWebKit.so.4
> # 12 0x00007ffff5744a63 in QObject::event(QEvent*) () from /usr/lib/libQtCore.so.4
> # 13 0x00007ffff5f3622c in QApplicationPrivate::notify_helper(QObject_, QEvent_) () from /usr/lib/libQtGui.so.4
> # 14 0x00007ffff5f3c6fb in QApplication::notify(QObject_, QEvent_) () from /usr/lib/libQtGui.so.4
> # 15 0x00007ffff573506c in QCoreApplication::notifyInternal(QObject_, QEvent_) () from /usr/lib/libQtCore.so.4
> # 16 0x00007ffff5761d42 in ?? () from /usr/lib/libQtCore.so.4
> # 17 0x00007ffff575e848 in ?? () from /usr/lib/libQtCore.so.4
> # 18 0x00007ffff30f28c2 in g_main_context_dispatch () from /lib/libglib-2.0.so.0
> # 19 0x00007ffff30f6748 in ?? () from /lib/libglib-2.0.so.0
> # 20 0x00007ffff30f68fc in g_main_context_iteration () from /lib/libglib-2.0.so.0
> # 21 0x00007ffff575e513 in QEventDispatcherGlib::processEvents(QFlags&lt;QEventLoop::ProcessEventsFlag&gt;) () from /usr/lib/libQtCore.so.4
> # 22 0x00007ffff5fe646e in ?? () from /usr/lib/libQtGui.so.4
> # 23 0x00007ffff5733992 in QEventLoop::processEvents(QFlags&lt;QEventLoop::ProcessEventsFlag&gt;) () from /usr/lib/libQtCore.so.4
> # 24 0x00007ffff5733d6c in QEventLoop::exec(QFlags&lt;QEventLoop::ProcessEventsFlag&gt;) () from /usr/lib/libQtCore.so.4
> # 25 0x00007ffff5737aab in QCoreApplication::exec() () from /usr/lib/libQtCore.so.4
> # 26 0x000000000041658d in main ()
> 
> Phantomjs 1.2 has no this error

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #255](http://code.google.com/p/phantomjs/issues/detail?id=255).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
We apologize for neglecting this bug report for years.

This bug was reported against a very old version of PhantomJS.  The current version, 2.0, includes a major update to both Qt and Webkit, which we believe is quite likely to have fixed this problem.  However, since the original report includes neither any information about the website that was being accessed via PhantomJS, nor the controller script in use, we are unable to test this ourselves.

Please get the current version from http://phantomjs.org/download.html and test it.  Because this bug is very old and we don't have enough information to do anything about it as is, we will close it if we don't hear back from you in one month.
