### ISSUE TITLE
TCP connections are kept open after page is loaded

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10253]
_**[joniscoo...@googlemail.com](http://code.google.com/u/107035513554942447369/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 
> $ phantomjs --version
> 1.3.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. Run this script:
> 
> for (var i = 1; i &lt; 100; i++) {
>   page = new WebPage();
>   page.open('http://google.com')
> }
> 1. Grep for the PID of the phantomjs process
> 2. Run &quot;lsof -p &lt;pid&gt;&quot;
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> I expect that the TCP connection should be closed once the page has been loaded.
> 
> <b>Which operating system are you using?</b>
> 
> Fedora 15
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> Compiled
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #253](http://code.google.com/p/phantomjs/issues/detail?id=253).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
There might still be a bug here.  Yes, PhantomJS should keep *some* connections open in case it is about to be asked to load more pages from the same site, just as "normal" browsers do.  But it shouldn't be possible to exhaust the client-side limit on the number of open sockets that way, and there should be a limit on the number of connections held open to the same server (again, just as "normal" browsers do).

This may or may not have been addressed by the upgrade to Qt 5 in PhantomJS 2.0.
