### ISSUE TITLE
Support for HTML5 multiple file upload

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10256]
_**[joniscoo...@googlemail.com](http://code.google.com/u/107035513554942447369/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 
> 1.3.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. Run the following script:
> 
> page = new WebPage();
> page.content = &quot;&lt;html&gt;&lt;body&gt;&lt;input type='file' multiple&gt;&lt;/body&gt;&lt;/html&gt;&quot;
> page.uploadFile('input', '/path/to/some/file')
> phantom.exit()
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> I expect to be able to upload the file from the code, but instead a file selector window pops up.
> 
> <b>Which operating system are you using?</b>
> 
> Fedora 15.
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> Compiled.
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #256](http://code.google.com/p/phantomjs/issues/detail?id=256).
:star2: &nbsp; **6** people had starred this issue at the time of migration.

**Comment by fabn** [comment]
Is there any way to simulate a drag and drop upload in phantomjs?
