### ISSUE TITLE
Request feature: Different network interfaces support (some IP).

### ISSUE THREAD

**Issue by DChistyakov** [ariya/phantomjs#10269]
_**[chistyak...@gmail.com](http://code.google.com/u/112700405721582146703/) commented:**_

> Please, make a support of different network interfaces like:
> phantomjs -iface=192.168.0.2 ...
> 
> Qt webkit supports it.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #269](http://code.google.com/p/phantomjs/issues/detail?id=269).
:star2: &nbsp; **6** people had starred this issue at the time of migration.

**Comment by amalagaura** [comment]
Is this feature available with 2.0? I checked the documentation and do not find it.

**Comment by amalagaura** [comment]
I see that feature needed qtwebkit 5.0 in PhantomJS 2.0. @Vitallium, if you have any code to start it looks like there may be people who are willing to work on this.

**Comment by mandb** [comment]
Doesn't look like this is going to get implemented unless somebody does it and submits a pull request.

**Comment by Julienh** [comment]
Any news about this feature?

**Comment by zackw** [comment]
@Vitallium Do you have an update on the implementation you were working on?

**Comment by Vitallium** [comment]
@zackw this feature is not possible to implement without modifying QtWebkit code.

**Comment by zackw** [comment]
I was afraid of that.

**Comment by XiaoChenMa** [comment]
@Vitallium  Can tell me how to modify QtWebkit code  to implement this feature?

**Comment by zackw** [comment]
@XiaoChenMa I'm pretty sure that *figuring out* how to modify QtWebkit code to implement this feature would be at least 90% of the work.  Therefore, if we knew what to tell you, we would already have implemented it ourselves.

I can get you started, though: read the code in `src/qt/qtbase/src/network`.  Yes, there's an awful lot of it.  You're looking for calls to the system primitives `socket`, `connect`, and `bind`.  You need to figure out how to make Qt call `bind` on a *client* TCP socket *before* calling `connect` on it.

If you don't know how the low-level socket API works, read *all of* chapter 16 of the GNU C Library manual: https://www.gnu.org/software/libc/manual/html_node/Sockets.html

**Comment by hydtek** [comment]
Has there been any movement on this issue. I really don't want to have to manage an IPTABLE when phantomjs can bind the interface for me.

**Comment by DChistyakov** [comment]
Guys... After 4 year.. I advise to use sqiud. I live 4 years with 32k ips and squid. Everything is ... yofi!

**Comment by seliquity** [comment]
If you can use LD_PRELOAD just use something like fixsrcip to overwrite connect() and bind to whatever IP you want. A bit of a hacky solution but less overhead than running everything through squid.

**Comment by DChistyakov** [comment]
Well.. Single instace of squid could accept more connections with less memory use. But everything depends on the task body.

**Comment by seliquity** [comment]
Sorry, I was suggesting fixsrcip as a potential generic workaround. I didn't mean you specifically. There's no need to run a whole proxy server just to bind to an interface as long as you're not running it as root.

**Comment by DChistyakov** [comment]
I got it. Sorry too. I mean I have some servers with phantom and one gate.

Anyway this feature could be implemented with much ease than overcoding QT engine. So closing is the optimal option for this task for now.

**Comment by zackw** [comment]
Please don't close issues just because you have found a workaround.  We will get to this - eventually.

**Comment by DChistyakov** [comment]
But the implementation is impossible. Okay, it you play, I`m out.

**Comment by arya6000** [comment]
Has anyone tried this with forcebindip? With forcebindip I am able to bind any program to any interface. I don't know if it would work with Selenium and Phantomks https://r1ch.net/projects/forcebindip

**Comment by blandman** [comment]
My solution in theory would work, but in practice has been hit or miss. Using Docker containers you can bind to a specific interface using Docker networks. In practice I haven't had much luck, maybe this would help somebody down the road. 
(I'm doing this on a Raspberry Pi, using PhantomJS to auto join an open wireless network with accept screen)

`/etc/systemd/system/docker.service.d/docker.conf`
```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -b=wlan1 --ip=10.0.0.151 -H fd://
```
This binds all of Docker under that specific interface, sometimes I had to do this for it to work.

Using compose to create a network
```
version: "2"

networks:
  open_network_2:
    driver: bridge
    driver_opts:
      com.docker.network.host_binding_ipv4: "10.0.0.151"

services:
   open_wifi_phantom:
     image: https://github.com/ollihoo/phantomjs-docker-rpi
     networks: 
       - open_network_2
```

Often I've had to create an IP tables rule, to route the docker bridge traffic to the interface's IP
`iptables -t nat -A POSTROUTING -s 172.16.0.0/16 -j SNAT --to-source 10.0.0.151`

I use Puppet to place the wlan1 IP address in these files. 

Documentation on this functionality is also very vague, or I don't understand lower level networking.
https://docs.docker.com/engine/userguide/networking/#the-default-bridge-network-in-detail
http://serverfault.com/questions/696747/routing-from-docker-containers-using-a-different-physical-network-interface-and
