### ISSUE TITLE
Support for paged media

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10268]
_**[joern.h...@gmail.com](http://code.google.com/u/102346025474285000503/) commented:**_

> Discussion: https://groups.google.com/group/phantomjs/browse_thread/thread/b16c8799e68b1843
> 
> A great way to use PhantomJS is IMHO to use it for printable documents from HTML pages, e.g. using a XSLT transformation to generate a printable HTML document which will be rendered as PDF (e.g. instead of Jasperreports). I used XHTMLRenderer (http://code.google.com/p/flying-saucer/) for that but it's HTML/CSS features are very limited. But it supports a subset of a feature that is needed to greater documents: Paged Media (http://www.w3.org/TR/CSS2/page.html).
> 
> So, it would be nice if PhantomJS would support this. I think that current webkit implementations do not support it yet.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #268](http://code.google.com/p/phantomjs/issues/detail?id=268).
:star2: &nbsp; **9** people had starred this issue at the time of migration.

**Comment by itajaja** [comment]
:+1: This would be awesome to automate pdf generation!
