### ISSUE TITLE
Support WebGL

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10273]
_**[ariya.hi...@gmail.com](http://code.google.com/u/103266860731871773002/) commented:**_

> This enables PhantomJS as a headless WebGL renderer.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #273](http://code.google.com/p/phantomjs/issues/detail?id=273).
:star2: &nbsp; **21** people had starred this issue at the time of migration.

**Comment by cecilemuller** [comment]
+1

**Comment by doriansmiley** [comment]
+1

**Comment by maxdunn** [comment]
+1

**Comment by mattermachine** [comment]
+1

**Comment by s-a** [comment]
:+1:

**Comment by bnolan** [comment]
A server-side software based renderer would be awesome for [SceneVR](//client.scenevr.com).

**Comment by meeron** [comment]
+1

**Comment by joshpangell** [comment]
+1

**Comment by lalomartins** [comment]
Honestly, I can't understand the reasoning behind commenting “+1” on Github. Does anyone seriously think that makes a difference? It only annoys the maintainer and people who are subscribed. If this has been sitting for three and a half years, a comment won't make it happen.

**Comment by boyravikumar** [comment]
When can we expect WebGL support for the phantom js.?? I need to capture the screen when a web gl has rendered it?

**Comment by cecilemuller** [comment]
I don't know when/if it's going to be added in Phantom, but in the meantime you could use [SlimerJS](https://www.npmjs.com/package/slimerjs) to render pages that might contain WebGL.

If you just need to render WebGL, you could even use packages [gl](https://www.npmjs.com/package/gl) or [node-webgl](https://www.npmjs.com/package/node-webgl) instead.

**Comment by zackw** [comment]
This *could* be as simple as adding

    m_customWebPage->settings()->setAttribute(QWebSettings::WebGLEnabled, true);

to webpage.cpp near the existing block of similar settings.  But I have no way of testing that, and it could cause the binary to not work at all in the absence of some specific graphics chip, or something.

**Comment by Vitallium** [comment]
That's not that easy. WebGL requires OpenGL. OpenGL requires XCB on Linux. That means that you not be able to use PhantomJS in full headless environment.

**Comment by hwhelchel** [comment]
There is a project https://github.com/mapbox/headless-gl. Could this be adapted to solve this problem? It says it has a dependency on OpenGL so my suspicion is no.

**Comment by ariya** [comment]
@hwhelchel Your suspicion is correct, thus you answered your own question.

**Comment by andreasrosdal** [comment]
+1

**Comment by ClickSimply** [comment]
+!

**Comment by r3mafe** [comment]
+100500

**Comment by MissAnichka** [comment]
Yasss! 👍 💯

**Comment by ariya** [comment]
Implementing this is a major undertaking and currently beyond the scope of the project.
You are however free to work on it on your own or sponsor someone to implement it. Once it is in a state where we can consider it for inclusion, please reopen this issue and submit a pull request of the implementation. Thank you!
