### ISSUE TITLE
Loading multiple pages with jQuery (or possibly any heavier JS) concurrently doesn't work

### ISSUE THREAD

**Issue by jgonera** [ariya/phantomjs#10298]
_**[jgon...@gmail.com](http://code.google.com/u/102015851724140065310/) commented:**_

> Ubuntu 11.04, PhantomJS 1.3. Let's say we have a server that returns this HTML:
> 
> &lt;!DOCTYPE html&gt;
> &lt;html&gt;
>   &lt;head&gt;
>     &lt;title&gt;test&lt;/title&gt;
>     &lt;meta charset=&quot;utf-8&quot;&gt;
>     &lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js&quot;&gt;&lt;/script&gt;
>   &lt;/head&gt;
>   &lt;body&gt;
>     hello
>   &lt;/body&gt;
> &lt;/html&gt;
> 
> Now, we run the following PhantomJS script:
> 
> var page1 = require('webpage').create();
> var page2 = require('webpage').create();
> var url = encodeURI('http://localhost:4567');
> 
> function getContent() {
>   return document.querySelector('body').textContent;
> };
> 
> page1.open(url, function() {
>   console.log(page1.evaluate(getContent));
> });
> page2.open(url, function() {
>   console.log(page2.evaluate(getContent));
> });
> 
> The result should be:
> 
> ```
> hello
> hello
> ```
> 
> But is:
> 
> null
>     hello
> 
> If you remove the &lt;script&gt; tag, it works.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #298](http://code.google.com/p/phantomjs/issues/detail?id=298).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by arsonik** [comment]
+1

**Comment by zackw** [comment]
@arsonik This bug is very old.  What version are you seeing it with?
