### ISSUE TITLE
clicking listbox does not work

### ISSUE THREAD

**Issue by kajala** [ariya/phantomjs#10310]
_**[kajala@gmail.com](http://code.google.com/u/kajala/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 
> <b>What steps will reproduce the problem?</b>
> 1. open http://www.kajala.com/temp/box.html
> 2. sendEvent( 'click', 150, 25 );
> 3. the item list does not appear
> 
> <b>What is the expected output? What do you see instead?</b>
> List box items should become visible
> 
> <b>Which operating system are you using?</b>
> Windows 7
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> Binary
> 
> <b>Please provide any additional information below.</b>
> This source code replicates the issue:
> 
> var page = new WebPage();
> page.settings.javascriptEnabled = true;
> page.settings.loadImages = true;
> page.clipRect = { top: 0, left: 0, width: 1024, height: 1024 };
> page.viewportSize = { width: 1024, height: 1024 };
> page.pageCount = 0;
> page.state = '1';
> 
> page.onLoadFinished = function(status) {
>   page.render( (page.pageCount++)+&quot;.jpg&quot; );
>   console.log( &quot;page.state=&quot;+page.state );
> 
>   switch (page.state)
>   {
>   case '1':
>       page.state = '2';
>       page.sendEvent( 'mousemove', 150, 25 );
>       setTimeout( function() {
>           page.sendEvent( 'click', 150, 25 );
>           setTimeout( function() {
>               page.render( (page.pageCount++)+&quot;.jpg&quot; );
>           }, 1000 );
>       }, 1000 );
>       break;
>   case '2':
>       break;
>   }
> };
> 
> page.open( &quot;http://www.kajala.com/temp/box.html&quot; );

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #310](http://code.google.com/p/phantomjs/issues/detail?id=310).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Fixed a long time ago.
