### ISSUE TITLE
Turkish character encoding problem for console

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#10316]
_**[ozhan...@gmail.com](http://code.google.com/u/115364900320619474685/) commented:**_

> Which version of PhantomJS are you using?
> 1.3.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. Create an example javascript as below
> 
> console.log('Turkish character encoding test, öÖçÇşŞiİğĞüÜ');
> phantom.exit();
> 
> What is the expected output?
> Turkish character encoding test, öÖçÇşŞiİğĞüÜ
> 
> What do you see instead?
> Turkish character encoding test, ´┐¢´┐¢´┐¢´┐¢´┐¢´┐¢i´┐¢´┐¢´┐¢´┐¢´┐¢
> 
> <b>Which operating system are you using?</b>
> Win7 Pro. En.
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> Binary

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #316](http://code.google.com/p/phantomjs/issues/detail?id=316).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
