### ISSUE TITLE
Local paths, relative to current directory, not working.

### ISSUE THREAD

**Issue by StefanLiebenberg** [ariya/phantomjs#10330]
_**[siga.fredo@gmail.com](http://code.google.com/u/siga.fredo/) commented:**_
> In 1.3.0 I could run:
> 
>   page = new Webpage()
>   page.open( 'tests/test-runner.html', function ( status ) {} )
> 
> with status being 'success'.
> 
> But in 1.4.0 I get 'fail' instead, unless I put in the complete filepath.
> 
>   page.open( 'file:///path/to/project/test/test-runner.html' )
> 
> I really need relative paths here.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #330](http://code.google.com/p/phantomjs/issues/detail?id=330).
:star2: &nbsp; **6** people had starred this issue at the time of migration.

**Comment by olsonpm** [comment]
@positlabs - that still doesn't allow for opening a relative file path from what I can gather of the documentation.  It just reloads the opened site with that new content.

My use-case is trying to open an html page local to the test directory.

**Comment by vbauer** [comment]
:+1:

**Comment by Vitallium** [comment]
Fixed in 2.0.

**Comment by shuge** [comment]
try this 
http://phantomjs.org/api/fs/property/working-directory.html
