### ISSUE TITLE
PhantomJS fails nearly all of my jasmine unit tests

### ISSUE THREAD

**Issue by blairvanderhoof** [ariya/phantomjs#10338]
_**[bla...@gmail.com](http://code.google.com/u/109105014541000086420/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.4.1
> 
> <b>What steps will reproduce the problem?</b>
1. Running this test runner here https://github.com/larrymyers/jasmine-reporters/blob/master/test/phantomjs-testrunner.js 
> 2. html input includes various jasmine unit tests
> 3. when it produces the junit xml report files, they all state various jasmine failures
> 
> <b>What is the expected output? What do you see instead?</b>
I expect none of my tests to fail.  They work fine when run in MacOSX command line with same commands.  Also works fine in the browser.
> 
> <b>Which operating system are you using?</b>
debian squeeze
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
compile it from source
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #338](http://code.google.com/p/phantomjs/issues/detail?id=338).
:star2: &nbsp; **5** people had starred this issue at the time of migration.

**Comment by ariya** [comment]
Closing this due to lack of further information.
