### ISSUE TITLE
phantomjs pretends to be a touch browser

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10375]
_**[brian.bu...@gmail.com](http://code.google.com/u/114626865518829568394/) commented:**_

> Which version of PhantomJS are you using? 1.4.1
> 
> <b>What steps will reproduce the problem?</b>
> 
> Run this phantomjs script:
> 
> var page = new WebPage();
> 
> page.open('http://modernizr.github.com/Modernizr/touch.html', function(status) {
>     page.render(&quot;output.png&quot;);
>     phantom.exit(0);
> });
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> Expected:
> 
> Modernizr should not detect PhantomJS as a touch browser.
> document.documentElement.ontouchstart (etc.) should be undefined
> 
> Actual:
> 
> Modernizr is detecting PhantomJS as a touch browser because it appears to implement several touch events.
> 
> <b>Which operating system are you using?</b>
> 
> Mac OS X 10.7
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> Binary
> 
> <b>Please provide any additional information below.</b>
> 
> Perhaps phantomjs should accept a configuration option to select whether it emulates a mouse browser or a touch browser.  Currently, it seems that it pretends to be both, and this breaks Highcharts.js mouseover events / tooltips, because highcharts detects a touch browser and disables the mouse events.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #375](http://code.google.com/p/phantomjs/issues/detail?id=375).
:star2: &nbsp; **20** people had starred this issue at the time of migration.

**Comment by mathiasschopmans** [comment]
As a workaround you can detect the phantomjs browser and disable the touch test:

```
if ('callPhantom' in window) {
  Modernizr.touch = false;
}
```

**Comment by rdefeo** [comment]
If I dont have control over the website, how can I disable touch as far as modernizr is concerned, is the only option to recompile? This would mean I would need two different binaries for different websites, one touch and one not?

**Comment by reidcooper** [comment]
I would love to be able to optionally stub out the touchevents/touch to return true or false, to my liking for my Rspec feature specs.

**Comment by prahladyeri** [comment]
Needs this to be resolved.

**Comment by Vitallium** [comment]
Starting from 2.5 version PhantomJS no more pretends itself as a browser with touch events support.

**Comment by karthik289** [comment]
Can any one provide 2.1.1  version for Ubuntu 14.04 which is disabled the touch events.
