### ISSUE TITLE
Basic HTTP Authentication causes phantomjs to repeatedly fire off requests

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10380]
_**[g...@usabilla.com](http://code.google.com/u/110069778984791196824/) commented:**_

> Running PhantomJS compiled from source (tag 1.4.1) on Ubuntu 10.04 server and 11.04 desktop
> 
> When using the rasterize.js example (other scripts also cause the same problem) on an url which uses Basic HTTP authentication and responds with a 401 Status code causes PhantomJS to become stuck in an infinite loop firing off requests to the url.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #380](http://code.google.com/p/phantomjs/issues/detail?id=380).
:star2: &nbsp; **6** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Fixed a long time ago.
