### ISSUE TITLE
CSS from external style sheet not applied to div on debian squeeze

### ISSUE THREAD

**Issue by dfrankow** [ariya/phantomjs#10392]
_**[dfran...@gmail.com](http://code.google.com/u/111614080747601215849/) commented:**_

> Which version of PhantomJS are you using?
> 
> 1.4.1
> 
> <b>What steps will reproduce the problem?</b>
> 1. Build phantomjs.
> 2. Untar the attached tarball.
> 3. cd flotbug2.
> 4. phantomjs rasterize.js flot1b.htm flot1b.png
> 
> There is an error message to the console:
> 
> &quot;undefined:0: Invalid dimensions for plot, width = 584, height = 0&quot;
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> Expected: flot1b.png should have a bar chart
> 
> In fact, flot1b.htm shows a bar chart in Firefox and Chromium.
> 
> Actual: Blank white png.
> 
> <b>Which operating system are you using?</b>
> 
> debian squeeze
> 
> $ uname -a
> Linux dandebian 2.6.32-5-amd64 #1 SMP Mon Jan 16 16:22:28 UTC 2012 x86_64 GNU/Linux
> 
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:   Debian
> Description:  Debian GNU/Linux 6.0.4 (squeeze)
> Release:  6.0.4
> Codename: squeeze
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> Compiled from source.
> 
> <b>Please provide any additional information below.</b>
> 
> flot1.htm and flot1a.htm both convert properly to png.
> 
> The difference is that flot1b.htm is referring to an external stylesheet (graph.css). For flot1b.htm, the width and height from graph.css is not being applied to the div with class &quot;graph_class&quot;. When Flot encounters a div with height 0, it doesn't know how to plot to it, and errors out.
> 
> This bug does NOT show up on OS X (i.e. I see the graph, though with an unexpected background color). So there is probably something broken about applying external stylesheet on debian squeeze.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #392](http://code.google.com/p/phantomjs/issues/detail?id=392).
:star2: &nbsp; **6** people had starred this issue at the time of migration.

**Comment by anvilvapre** [comment]
Same problem here. 
Compiled from source.
Version 1.9.1
RH 6.6
Screenshot of page shows a plain html page with no css styling.
