### ISSUE TITLE
throwing a JavaScript error causes PhantomJS to freeze rather than exit with error code

### ISSUE THREAD

**Issue by ananelson** [ariya/phantomjs#10398]
_**[nelson....@gmail.com](http://code.google.com/u/107024797064185129338/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.4.1
> 
> <b>What steps will reproduce the problem?</b>
ubuntu@ip-10-114-133-16$ cat error.js 
> throw &quot;this is an error&quot;;
> phantom.exit();
> ubuntu@ip-10-114-133-16:$ phantomjs error.js 
> undefined:0 this is an error
> 
> At this point the script just hangs and has to be killed via ctrl+c.
> 
> <b>What is the expected output? What do you see instead?</b>

> I would expect the phantomjs interpreter to exit immediately when the script it is running throws an error. Certainly it should not hang.
> 
> e.g.
> 
> ubuntu@ip-10-114-133-16$ rhino error.js 
> js: &quot;error.js&quot;, line 1: exception from uncaught JavaScript throw: this is an error
> 
> <b>Which operating system are you using?</b>

> Ubuntu (oneiric)
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> Compiled from source.
> 
> <b>Please provide any additional information below.</b>

> I want to be able to throw errors so that it's obvious when something has gone strong in a script.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #398](http://code.google.com/p/phantomjs/issues/detail?id=398).
:star2: &nbsp; **6** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Duplicated. Please see #12973
