### ISSUE TITLE
Better build steps

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10415]
_**[ariya.hi...@gmail.com](http://code.google.com/u/103266860731871773002/) commented:**_
> We have minimalistic Qt source imported (see issue 226). Right now, building it involves running a shell script.
> 
> For better build workflow (incremental build, installation, uninstallation), the ideal step will be:
> 
>   ./configure
>   make
> 
> and with targets allowing both:
>   make install
>   make uninstall

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #415](http://code.google.com/p/phantomjs/issues/detail?id=415).
:star2: &nbsp; **1** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
We have now the unified Python script for all platforms to build PhantomJS.
