### ISSUE TITLE
Allow spoofing a location to get around about: restrictions when just using evaluate

### ISSUE THREAD

**Issue by ericallam** [ariya/phantomjs#10417]
_**[rubymave...@gmail.com](http://code.google.com/u/114931647518879408198/) commented:**_
> Using 1.4.1 with qt 4.8.  
> 
> When running this example script: https://gist.github.com/2002953  A security exception is raised because Qt is basically in &quot;file&quot; mode, aka it will raise a Dom Exception Security error when trying to use window.history.pushState.   The only way to get Qt in a state where window.history is usable is to hit a URI with open.  I'd really like the ability to tell Qt to &quot;spoof&quot; a location so window.history is usable. 
> 
> 
> <b>What steps will reproduce the problem?</b>
1. Run `phantomjs phantom-demo.coffee`
> 
> <b>What is the expected output? What do you see instead?</b>

> Excepted to be able to use window.history.pushState without having to open a webpage, but instead a DOM Exception Security error was raised.
> 
> <b>Which operating system are you using?</b>

> Mac OS X Lion
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> Compiled from source.
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #417](http://code.google.com/p/phantomjs/issues/detail?id=417).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by ariya** [comment]
Due to the lack of a concrete follow-up possibility, this issue will be closed.
