### ISSUE TITLE
Streamline the included copy of Qt

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10414]
_**[ariya.hi...@gmail.com](http://code.google.com/u/103266860731871773002/) commented:**_
> We have minimalistic Qt source imported (see issue 226). Now it's time to streamline the build even further.
> 
> Example: we don't need to build most of the legacy widgets (QDial, QLCDNumber), as well as unrelated modules like state machine, graphics view, etc.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #414](http://code.google.com/p/phantomjs/issues/detail?id=414).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Not applicable anymore.
