### ISSUE TITLE
Thai chars are messed up in page rendering

### ISSUE THREAD

**Issue by ttudor** [ariya/phantomjs#10420]
_**[ttu...@gmail.com](http://code.google.com/u/108923150986034474662/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 
> 1.4.1
> 
> <b>What steps will reproduce the problem?</b>
> 1. Launch phantomjs render.js http://www.thaiairways.com/homepage/th/home.htm thaw.jpg
> 
> (render.js is attached).
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> See the above page in a Chrome browser and compare with the rendering. Most of the glyphs are messed up (but not all). 
> 
> <b>Which operating system are you using?</b>
> 
> Linux and OSX
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> Both on OSX, binary on Linux.
> 
> <b>Please provide any additional information below.</b>
> 
> Proper fonts are installed on both Linux and OSX. Other pages render with Thai glyphs render ok. Capture is from OSX (first) and Linux (second).

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #420](http://code.google.com/p/phantomjs/issues/detail?id=420).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by wyattbenno777** [comment]
Any updates on this? Why it happens or planned fix?
