### ISSUE TITLE
[Regression] Phantom 1.3.0 -> 1.4.1: DOMParser does not return error documents when parsing malformed XML

### ISSUE THREAD

**Issue by aashay** [ariya/phantomjs#10428]
_**[Aash...@gmail.com](http://code.google.com/u/114187701272372339291/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
OS X 1.4.1
> 
> <b>What steps will reproduce the problem?</b>
1. Run the attached script using both Phantom 1.4.1 and 1.3.0.
> 2. Notice the output of 1.3.0 produces an actual &quot;parsererror&quot; document but 1.4.1 does not.
> 
> <b>What is the expected output? What do you see instead?</b>

> Expected output (output with Phantom 1.3.0 which I've named phantomjs13):
> 
> $ ./Lib/phantomjs13 ~/phantomtest.js 
> Is result an empty string?false
> Result is &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;body&gt;&lt;parsererror style=&quot;display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black&quot;&gt;&lt;h3&gt;This page contains the following errors:&lt;/h3&gt;&lt;div style=&quot;font-family:monospace;font-size:12px&quot;&gt;error on line 2 at column 23: Expected ''' or '&quot;', but got '='.&lt;/div&gt;&lt;h3&gt;Below is a rendering of the page up to the first error.&lt;/h3&gt;&lt;/parsererror&gt;&lt;/body&gt;&lt;/html&gt;
> 
> Instead:
> ./Lib/phantomjs14 ~/phantomtest.js 
> 
> Is result an empty string? true
> Result is 
> 
> <b>Which operating system are you using?</b>
Mac OS X Lion 10.7.2
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Binary.
> 
> <b>Please provide any additional information below.</b>

> Run my attached script using both OS X versions of phantom (1.4.1 and 1.3.0).  The output should be the same.
> 
> NOTE:  Yes it's quite probable that this is a qt bug of some sort, but I've scoured the internets trying to find any references to this to no avail.   If it is indeed a Qt bug, some sort of workaround would be appreciated.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #428](http://code.google.com/p/phantomjs/issues/detail?id=428).
:star2: &nbsp; **8** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
