### ISSUE TITLE
element.webkitMatchesSelector in phantomjs does not report ":focus" accurately

### ISSUE THREAD

**Issue by ryangreenberg** [ariya/phantomjs#10427]
_**[ryangree...@gmail.com](http://code.google.com/u/117555447869601069550/) commented:**_

> Which version of PhantomJS are you using? 1.4.1
> 
> <b>What steps will reproduce the problem?</b>
> 1. Run the provided test script with the test HTML (below).
> 
> <b>What is the expected output? What do you see instead?</b>
> I expect :focus to be true after triggering a focus event on an element. Instead it is false.
> 
> Which operating system are you using? OS X 10.7.3
> 
> Did you use binary PhantomJS or did you compile it from source? Compiled.
> 
> Here is the output of my test script in Chrome, Safari, and PhantomJS:
> ## Chrome
> 
> navigator.userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.54 Safari/535.19
> $('#some-input').is(':focus'): true
> $input[0].webkitMatchesSelector(':focus'): true
> $input[0] == document.activeElement: true
> ## Safari
> 
> navigator.userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/534.54.16 (KHTML, like Gecko) Version/5.1.4 Safari/534.54.16
> $('#some-input').is(':focus'): true
> $input[0].webkitMatchesSelector(':focus'): true
> $input[0] == document.activeElement: true
> ## PhantomJS 1.4.1
> 
> navigator.userAgent: Mozilla/5.0 (Macintosh; PPC Mac OS X) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.4.1 Safari/534.34
> $('#some-input').is(':focus'): false
> $input[0].webkitMatchesSelector(':focus'): false
> $input[0] == document.activeElement: true
> 
> Test HTML
> &lt;!DOCTYPE html&gt;
> &lt;html&gt;
> &lt;head&gt;
> &lt;title&gt;:focus check&lt;/title&gt;
> &lt;script src=&quot;http://code.jquery.com/jquery.js&quot;&gt;&lt;/script&gt;
> &lt;script&gt;
>   $(function(){
>     console.log(&quot;navigator.userAgent: &quot; + navigator.userAgent);
> 
> ```
> // Simple case
> $input = $('#some-input');
> $input.focus();
> console.log(&quot;$('#some-input').is(':focus'): &quot; + $('#some-input').is(':focus'));
> 
> // Similar case
> $input.focus();
> console.log(&quot;$input[0].webkitMatchesSelector(':focus'): &quot; + $input[0].webkitMatchesSelector(':focus'));
> 
> // When a native matchesSelector isn't available, jQuery uses:
> // 
> //  focus: function( elem ) {
> //     return elem === elem.ownerDocument.activeElement;
> //  }
> // 
> // The input == document.activeElement, which suggests that the bug is in webkitMatchesSelector
> console.log(&quot;$input[0] == document.activeElement: &quot; + ($input[0] == document.activeElement));
> ```
> 
>   });
> &lt;/script&gt;
> &lt;/head&gt;
> &lt;body&gt;
>   &lt;form&gt;
>     &lt;input id=&quot;some-input&quot;&gt;
>   &lt;/form&gt;
> &lt;/body&gt;
> &lt;/html&gt;
> 
> Test script:
> var page = require('webpage').create();
> page.onConsoleMessage = function(msg) { console.log(msg); };
> 
> page.open('file:///' + phantom.libraryPath + '/focus_test.html', function (status) {
>   if (status !== 'success') {
>     console.log('Could not open URL');
>   }
>   phantom.exit();
> });

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #427](http://code.google.com/p/phantomjs/issues/detail?id=427).
:star2: &nbsp; **16** people had starred this issue at the time of migration.

**Comment by Nr9** [comment]
+1

**Comment by mhluska** [comment]
+1

**Comment by alexanderbartels** [comment]
+1

**Comment by bierik** [comment]
+1

**Comment by pat841** [comment]
+1

**Comment by Eyesonly88** [comment]
+1

**Comment by pzuraq** [comment]
+1

**Comment by zackw** [comment]
This appears still to be an issue in 2.0, using the test case from the original report:

~~~~
$ ./bin/phantomjs focus_test.js 
navigator.userAgent: Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.0.0 (development) Safari/538.1
$('#some-input').is(':focus'): false
$input[0].webkitMatchesSelector(':focus'): false
$input[0] == document.activeElement: true
~~~~

I presume the expectation is for all three test cases to report 'true'.

This is almost certainly a Webkit bug.  Can anyone reproduce it in Safari, Chrome, or the web browser formerly known as Epiphany?

**Comment by pzuraq** [comment]
@zackw Interestingly I get the same/similar bugs when and only when using livereload. If I manually start the tests in Chrome they pass, but if they are started by a livereload as I change files they fail.

**Comment by dlants** [comment]
+1

**Comment by SebCourvoisier4D** [comment]
+1

**Comment by Charlotteis** [comment]
Just to say, I am still having this issue.
I have solved it by doing what has been said above;
`assertEqual(true, element === document.activeElement);`

**Comment by nlaplume** [comment]
+1

**Comment by renehamburger** [comment]
As @zackw pointed out, this bug is still present in PhantomJS 2.0. It is not merely an issue with the pseudo selector `:focus` accessed through jQuery, but the page renders incorrectly, if any styles depend on `:focus` (as documented by #11432). That means that it's impossible to use PhantomJS for testing  pages that contain any logic that's dependent on focussed elements.

Here are two screenshots that demonstrate the issue:

![chrome](https://cloud.githubusercontent.com/assets/4340524/11184587/e6c7d288-8c78-11e5-8129-d9d0a9327274.png)

![phantomjs](https://cloud.githubusercontent.com/assets/4340524/11184586/e6c6fde0-8c78-11e5-9833-448756529b7a.png)

Here's the protractor snippet used for these screenshots:
```
  browser.get('http://s.codepen.io/rh/debug/epbQRm');
  browser.driver.switchTo().activeElement().sendKeys('focus is here...');
  return browser.takeScreenshot().then(...)
```
The content in the input proofs that the focus really is there in both cases.

**Comment by myplacedk** [comment]
I agree with @renehamburger. I don't see any workaround for testing styling.

And this is only a problem in phantomjs, not in Chrome. So it doesn't look like a webkit-problem.

**Comment by panthony** [comment]
+1

**Comment by fliot** [comment]
I agree with @renehamburger & @myplacedk. I don't see any workaround for testing styling.

**Comment by sgress454** [comment]
I think the problem here is that in Webkit, the `:focus` selector only matches elements if the _document itself_ has focus--that is, if `document.hasFocus()` returns true.  You can test this yourself in Chrome:

```
setTimeout(
	function(){
		var e = document.createEvent('Event');
		e.initEvent("focus", true, true);
		document.getElementById('id-of-some-focusable-element').dispatchEvent(e);
		console.log(document.querySelectorAll(':focus'));
	},
	2000
);
```

If you run this from the Chrome dev tools console, you'll see an empty array returned two seconds later.  However, if you run it and then click inside the document within two seconds, the log will spit out the expected element.  

While researching this, I found a [jQuery patch from a few years ago](https://github.com/mattheworiordan/jquery-focus-selenium-webkit-fix/blob/master/README.md) made when someone using Selenium ran into the same issue; unfortunately that patch doesn't work for the current jQuery version but it pointed me in this direction.

So it would seem that the only fix would be to patch the Webkit that PhantomJS is using to not expect the document to be focused when querying `:focus`, or to allow some way to "focus" the document in PhantomJS so that `document.hasFocus()` returns `true`.

**Comment by Jedidiah** [comment]
+1

Good investigation @sgress454 :smile: 
It would be great to see this finally fixed!

**Comment by capturecadet** [comment]
+1

**Comment by albinekb** [comment]
+1

**Comment by tiffanywei** [comment]
+1

**Comment by emilioplatzer** [comment]
+1

**Comment by garex** [comment]
**Another possible patch (rude)**

```
// it's for casperjs, but I think you will catch the idea
this.evaluate(function() { document.hasFocus = function() { return true } })
```

**Comment by workmanw** [comment]
+1

**Comment by sgress454** [comment]
@garex I tried something like that at one point without much luck -- I don't think the `:focus` selector just relies on `document.hasFocus()` returning true, but rather that whatever underlying conditions cause `hasFocus()` to return true must be met in order for the `:focus` selector to work.

**Comment by biterika-node** [comment]
+1

**Comment by Jevin23** [comment]
+1

**Comment by kryptan** [comment]
I experimented with this a bit using a 2.1 branch (master crashes for me).

First I tried to fix it in PhantomJS itself, but calling `QWebFrame::setFocus()` on `m_currentFrame` or any other frame in [webpage.cpp](https://github.com/ariya/phantomjs/blob/2.1/src/webpage.cpp) does not have any effect.

Next I looked into WebKit sources, the `:focus` pseudo class is checked [here](https://github.com/Vitallium/qtwebkit/blob/e7b74331d695bfa8b77e39cdc50fc2d84a49a22a/Source/WebCore/css/SelectorChecker.cpp#L943). `SelectorChecker::matchesFocusPseudoClass` function calls `SelectorChecker::isFrameFocused` which in turn calls [FrameSelection::isFocusedAndActive](https://github.com/Vitallium/qtwebkit/blob/e7b74331d695bfa8b77e39cdc50fc2d84a49a22a/Source/WebCore/editing/FrameSelection.cpp#L1750). Changing `FrameSelection::isFocusedAndActive` to always return `true` fixes this issue although it feels like a hack, I don't know what a proper solution here would be.

P.S. I suggest owner of this repo to remove all junk +1 comments and block their authors.

**Comment by Vitallium** [comment]
Can someone check it with recently released 2.5 version? Thanks!

**Comment by cleforwen** [comment]
+1

**Comment by jameswomack** [comment]
@Vitallium Where can I download a version of 2.5 that will work with Selenium/Nightwatch.js? What I downloaded from https://bitbucket.org/ariya/phantomjs/downloads/ wasn't recognized by Selenium.

**Comment by DustinAshley** [comment]
+1

**Comment by Vishwaas** [comment]
+1

**Comment by srescio** [comment]
+1
