### ISSUE TITLE
evaluate returns "" instead of null

### ISSUE THREAD

**Issue by abesto** [ariya/phantomjs#10434]
_**[abes...@gmail.com](http://code.google.com/u/103008650922952787597/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.4.1
> 
> <b>What steps will reproduce the problem?</b>
> Run this script:
> p = new WebPage
> p.open 'http://google.com', -&gt;
>   ret = p.evaluate -&gt; null
>   console.log &quot;isnull: &quot; + (ret is null)
>   console.log &quot;typeof: &quot; + (typeof ret)
> 
> <b>What is the expected output? What do you see instead?</b>
> Expected:
>   isnull: true
>   typeof: object
> Actual:
>   isnull: false
>   typeof: string
> 
> <b>Which operating system are you using?</b>
> Arch Linux
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> I use the version from the Arch package repository.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #434](http://code.google.com/p/phantomjs/issues/detail?id=434).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by chenzww** [comment]
No way to hack it? It occurred at 2.1.1.
