### ISSUE TITLE
Improve remote debugger wrapper

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10431]
_**[ariya.hi...@gmail.com](http://code.google.com/u/103266860731871773002/) commented:**_

> Now that we have imported Qt + WebKit code (issue 226), it should be possible to tweak the debugging infrastructure. Depending on how it turns out, we may not need __run() wrapper and friends anymore.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #431](http://code.google.com/p/phantomjs/issues/detail?id=431).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by tgifriday** [comment]
Unsubscribe
