### ISSUE TITLE
Page clipRect is ignored if output is PDF

### ISSUE THREAD

**Issue by leplatrem** [ariya/phantomjs#10465]
_**[leplat...@gmail.com](http://code.google.com/u/106965745149150173373/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.5.0 (development)
> 
> Reproductible with the following snippet :
> 
> ```
> var page = new WebPage(),
>     address, output, size;
> 
> if (phantom.args.length &lt; 2 || phantom.args.length &gt; 3) {
>     console.log('Usage: rasterize.js URL filename');
>     phantom.exit();
> } else {
>     address = phantom.args[0];
>     output = phantom.args[1];
>     page.viewportSize = { width: 1600, height: 1200 };
>     page.open(address, function (status) {
>         if (status !== 'success') {
>             console.log('Unable to load the address!');
>         } else {
>             window.setTimeout(function () {
>                 page.clipRect = {top: 100, left: 100, 
>                                  width: 200, height: 200};
>                 page.render(output);
>                 phantom.exit();
>             }, 200);
>         }
>     });
> }
> ```
> 
> <b>Which operating system are you using?</b>
> 
> Ubuntu 11.10
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> Using antono ppa : https://launchpad.net/~antono/+archive/phantomjs
> 
> <b>Please provide any additional information below.</b>
> 
> Similar issue was marked as invalid : http://code.google.com/p/phantomjs/issues/detail?id=134

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #465](http://code.google.com/p/phantomjs/issues/detail?id=465).
:star2: &nbsp; **6** people had starred this issue at the time of migration.

**Comment by Friedel-Castor** [comment]
I have the same problem. I want to select a DOM-Element and render only those to a pdf.
This solution helped me to find a workaround: 
http://stackoverflow.com/questions/1535331/how-to-hide-all-elements-except-one-using-jquery

It hides all elements except the element that i want to render.
The only thing i changed was the order of the commands.
Here is my Code:
```javascript
page.includeJs(jquery, function(){
       page.evaluate(function (element){
        $(element).appendTo('body');
        $('body > :not(' + element + ')').hide(); 
       }, element);       
      });
window.setTimeout(function(){
        page.render("page.pdf");
      },1000);
```

Maybe it helps someone

**Comment by eranimo** [comment]
This issue is now three years old and many people are having this problem. Maybe it should be a higher priority?

**Comment by cabralmartin** [comment]
+1

**Comment by mrmarktyy** [comment]
+1

**Comment by ugoertz** [comment]
+1

**Comment by sunyang213** [comment]
+1

**Comment by juazemar** [comment]
+1

**Comment by datskevichsergey** [comment]
+1

**Comment by angelim** [comment]
+1

**Comment by szakharchenko** [comment]
+1

**Comment by D-Feng** [comment]
+1

**Comment by alex7egli** [comment]
+1

**Comment by ggevgg** [comment]
+1

**Comment by MirrorC** [comment]
+1

**Comment by bulinutza** [comment]
It would be a life saver if page.clipRect behaved the same in .pdf as in the image formats. Please please add this :-)

**Comment by leplatrem** [comment]
If it is a matter of life maybe it would be worth considering providing some help to the maintainers of this project #justsaying

**Comment by bulinutza** [comment]
@leplatrem I really would if I have the knowledge required or the time. My company is heavily relying on phantomjs and we would be willing to pay for a phanomjs license is funding was something that would help the development efforts.

**Comment by sreejithz** [comment]
+1 :+1: 
me too waiting for this.

**Comment by Jeff-14159** [comment]
+100 need this fixed too. on 2.1.1

**Comment by leplatrem** [comment]
Add +1* here won't have much impact. AFAIK it is clearly stated that the program is *distributed as-is and without any warrantee*.

Maybe relying on a funding platform (like http://www.fixthatbug.com or whatever) could help. If several companies need that bug fixed, they could gather funds to attract developers with the right skillset.

(my 2 cents)

**Comment by szakharchenko** [comment]
@leplatrem , I suppose those who really needed the functionality just wrote a simple ghostscript-based workaround like me:).

**Comment by leplatrem** [comment]
@szakharchenko now you can start a company that sells the script to those who seem to really need it ;)

**Comment by rlsz** [comment]
+1

**Comment by rubystar** [comment]
+1

**Comment by whoooah** [comment]
+1

**Comment by Hamza-324** [comment]
@szakharchenko mind sharing ? I really need it !

**Comment by rlsz** [comment]
@Hamza-324 
I inject jquery, hide all other tags, then print the area. 
```
var width=$('.print').width();
var offset=20;
$('.print').parents().each(function(index,item){
	$(item).siblings().hide();
	$(item).css("margin", "0").css("border", "0px").css("padding", "0px").css("overflow","hidden");
});
$('.print').css("margin", offset+"px").css("border", "0px").css("padding", "0px").width(width);
```
