### ISSUE TITLE
[webserver] Request.url converts all // into /

### ISSUE THREAD

**Issue by fzaninotto** [ariya/phantomjs#10480]
_**[FZaninotto@gmail.com](http://code.google.com/u/FZaninotto/) commented:**_

> PhantomJS 1.5.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. Create a server with require('webserver')
> 2. Create a service simply outputting request.url
> 3. Call the service like so: 
> 
> ```
> GET /foo/bar//foo///bar
> ```
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> The result is
> 
> /foo%2Fbar%2Ffoo%2Fbar
> 
> I expect 
> 
> /foo%2Fbar%2F%2Ffoo%2F%2F%2Fbar
> 
> <b>Which operating system are you using?</b>
> 
> Centos
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> compile from source
> 
> <b>Please provide any additional information below.</b>
> 
> The support for double slash is required in order to support passing an URI as parameter.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #480](http://code.google.com/p/phantomjs/issues/detail?id=480).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by silkentrance** [comment]
Other servers like nginx or apache2 will also normalize the path.

Additionally, when passing in urls as request parameters or as part of the URL, the User Agent a/o client side app is responsible for encoding the extraneous forward slashes.

For my part, phantomjs behaves correctly in that it will normalize the path, thus making request handling more easier.

**Comment by silkentrance** [comment]
@fzaninotto please see above comment
