### ISSUE TITLE
Each font load reloads the native font database (slow on OSX 10.6)

### ISSUE THREAD

**Issue by sparecycles** [ariya/phantomjs#10488]
_**[adam.freidin@gmail.com](http://code.google.com/u/adam.freidin@gmail.com/) commented:**_

> phantomjs --version
> a customized 1.6.0 (development) with a functionally unmodified src/qt directory.
> 
> <b>What steps will reproduce the problem?</b>
> 1. use @font-face rules with phantomjs
> 2. observe slow loading times
> 
> Through the insertion of tracing statements in the webkit and qt sources, I found that each insertion of a new font causes a revalidation of the 400+ fonts installed on my system.  A document with 20 fonts becomes painfully slow to load (over 15 seconds).  Safari and chrome can consume the exact same request in ~500ms and ~800ms respectively.
> 
> <b>Which operating system are you using?</b>
> OSX 10.6.8
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> source
> ---
> 
> I've identified the slow code as loadFromDatabase, and the problem is that the database is invalidated with each font insertion.  Getting QRawFont working might be the solution here, or switching away from native font rendering for loaded fonts.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #488](http://code.google.com/p/phantomjs/issues/detail?id=488).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by jamesshore** [comment]
Just confirmed that this issue still exists on PhantomJS 1.9.8 on Mac OS "Yosemite" 10.10.1.

**Comment by bcarpenter** [comment]
Seeing this issue as well.  PhantomJS 1.9.7.0 on OSX 10.9.5.

**Comment by dustinblackman** [comment]
Confirmed still an issue on OSX 10.11

**Comment by bcarpenter** [comment]
Not really a fix, but a workaround I use is as follows (i.e. don't load Typekit during automated tests):

```haml
    - unless Rails.env.test? # Typekit slows down phantomjs https://github.com/ariya/phantomjs/issues/10488
      = javascript_include_tag "//use.typekit.net/ppd2bsh.js"
      :javascript
        try{Typekit.load();}catch(e){}
```

**Comment by Vitallium** [comment]
Could someone try again with 2.5 binary? Thanks!
