### ISSUE TITLE
Add support for mouseover and mouseout events

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10491]
_**[nick.rab...@gmail.com](http://code.google.com/u/118261822197534781054/) commented:**_

> The WebPage#sendEvent() method currently only supports mouseup, mousedown, mousemove, and click events. If the functionality is available in WebKit, it would be desirable to add mouseover and mouseout events as well.
> 
> Example use-case: Testing Javascript that unobtrusively adds mouseover and mouseout functionality. Synthetic DOM events are insufficient to trigger the desired effect.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #491](http://code.google.com/p/phantomjs/issues/detail?id=491).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by rafa-aguilar** [comment]
No news?

**Comment by u2718** [comment]
Just wondering if this is still scheduled to be fixed?
