### ISSUE TITLE
PhantomJS 1.5 64 Dynamic Build: Segmentation fault

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10493]
_**[deMo...@gmail.com](http://code.google.com/u/115124307820357870874/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.5.0
> 
> <b>What steps will reproduce the problem?</b>
1. Download PhantomJS 1.5.0 Linux x86_64 (Dynamic build)
> 2. Run phantomjs on fresh installation of Ubuntu 11.04
> 3. Will print Segmentation fault 
> 
> <b>Which operating system are you using?</b>
Fresh installation of Ubuntu 11.04 64 bit server
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Binary PhantomJS
> 
> <b>Please provide any additional information below.</b>

> If I run phantomjs -v it works and prints the version. Same with -h.
> When I try to run a script or without argument is crashes.
> 
> From strace:
> 
> mmap(NULL, 1073741824, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = -1 ENOMEM (Cannot allocate memory)
> --- SIGSEGV (Segmentation fault) @ 0 (0) ---
> +++ killed by SIGSEGV +++

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #493](http://code.google.com/p/phantomjs/issues/detail?id=493).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
