### ISSUE TITLE
multiple page objects causes unexpected (non deterministic?) calls to onLoadFinished

### ISSUE THREAD

**Issue by hackerhasid** [ariya/phantomjs#10515]
_**[n...@statichippo.com](http://code.google.com/u/112186880142633030439/) commented:**_
> Which version of PhantomJS are you using? 1.5.0
> 
> <b>What steps will reproduce the problem?</b>
1. run script at https://gist.github.com/2512685 as is, notice it works as expected
> 2. set MAX_PAGES=5 and run it again.  you almost certainly get more than 5 'success' outputs.  also you may find that the rendered images for the calls before the last call to onLoadFinished (for each page that screwed up) seem to indicate that the site was not actually finished loading by the time the render call was made (which in turn means before onLoadFinished was made too)
> 
> <b>What is the expected output? What do you see instead?</b>
I would expect to see only 5 outputs of 'success'.  I would expect all the rendered images to be complete.
> 
> <b>Which operating system are you using?</b>
Ubuntu 11.10 x86, Ubuntu 11.10 x64, Ubuntu 12.04 x86
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
binary
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #515](http://code.google.com/p/phantomjs/issues/detail?id=515).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Fixed in PhantomJS 2 version.
