### ISSUE TITLE
page.onError not used when page.evaluate is called in page.open callback

### ISSUE THREAD

**Issue by milianw** [ariya/phantomjs#10511]
_**[m...@milianw.de](http://code.google.com/u/116199627754761246570/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 
> current git master
> 
> <b>What steps will reproduce the problem?</b>
> testcase for webpage-spec.js:
> 
> ```
> it(&quot;reports unhandled errors in page open&quot;, function() {
>     var hadError = false;
> 
>     runs(function() {
>         page = new require('webpage').create();
>         page.onError = function() { hadError = true };
>         page.open(&quot;about:blank&quot;, function() {
>           page.evaluate(function() {
>             referenceError;
>           });
>         });
>     });
> 
>     waits(0);
> 
>     runs(function() {
>         expect(hadError).toEqual(true);
>     });
> })
> ```
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> page.onError is not used in the above code, one apparently has to use phantom.onError (see also: https://groups.google.com/forum/#!searchin/phantomjs/onerror/phantomjs/BBfcI4az5KU/9vCjeJie8VoJ%29)
> 
> <b>Which operating system are you using?</b>
> 
> Linux milian-kdab2 3.0.0-17-generic #30-Ubuntu SMP Thu Mar 8 20:45:39 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> self compiled
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #511](http://code.google.com/p/phantomjs/issues/detail?id=511).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by Kinyi** [comment]
sorry i don't know
