### ISSUE TITLE
Background color and quality for JPEG rendering

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10519]
_**[downch...@gmail.com](http://code.google.com/u/115424359274750685835/) commented:**_

> JPEG rendering with page.render could use a quality argument as well as a setting to set the background color used when compositing a page with transparency. Current default behavior is correct: it uses black.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #519](http://code.google.com/p/phantomjs/issues/detail?id=519).
:star2: &nbsp; **7** people had starred this issue at the time of migration.

**Comment by adeodhar-quark** [comment]
I agree with @Synchro, just got black jpegs. phantomjs should mimic/use same defaults as browsers do.
Which is black on white.

![sample](https://cloud.githubusercontent.com/assets/13519993/13807219/1b45ffd2-eb86-11e5-80ad-e5128d3b132c.jpg)
![sample](https://cloud.githubusercontent.com/assets/13519993/13807220/1b469bcc-eb86-11e5-97c8-d191e68826ec.png)

**Comment by JustinYi922** [comment]
请问这个问题解决了吗？
