### ISSUE TITLE
PhantomJS should support user certificates (*.pem, *.pfx)

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10524]
_**[frst...@googlemail.com](http://code.google.com/u/117131303763989232225/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.5
> 
> <b>What steps will reproduce the problem?</b>
1. Open any webpage which requires user authentication via a user certificate (instead of login + password).
> <b>2.</b>
<b>3.</b>

> <b>What is the expected output? What do you see instead?</b>
Expected: One should be able to configure a file which stores the user certificate
> Instead: The API doesn't provide this functionality
> 
> <b>Which operating system are you using?</b>
WinXP, Linux
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Binary (on both OS)
> 
> <b>Please provide any additional information below.</b>
If the user has more than one applicable certificate in his/her certificate store the major web browsers start a dialog to select a certificate.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #524](http://code.google.com/p/phantomjs/issues/detail?id=524).
:star2: &nbsp; **11** people had starred this issue at the time of migration.

**Comment by smoelker** [comment]
+1

**Comment by surebert** [comment]
+1

**Comment by sperlich** [comment]
+1

**Comment by adriannier** [comment]
+1

**Comment by Vitallium** [comment]
Implemented in 37a3c2d!

**Comment by abekroenem** [comment]
+1

**Comment by avandrevitor** [comment]
+1
