### ISSUE TITLE
Support Solaris (and also Joyent SmartOS)

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10521]
_**[ariya.hi...@gmail.com](http://code.google.com/u/103266860731871773002/) commented:**_

> Currently Solaris, and hence also Solaris-based SmartOS from Joyent, is not supported.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #521](http://code.google.com/p/phantomjs/issues/detail?id=521).
:star2: &nbsp; **5** people had starred this issue at the time of migration.

**Comment by mamash** [comment]
Here's a purely static 32bit binary built on SmartOS. I can keep maintaining this for coming 1.9.x releases too. Wonder if we can have this included as a download option on the official site.

https://us-east.manta.joyent.com/pkgsrc/public/packages/SmartOS/phantomjs/phantomjs-1.9.8-smartos-i386.tgz

**Comment by JDougherty** [comment]
mamash- do you have up to date build instructions for 1.9.x? What dependencies must be installed, and does the PhantomJS source need to be patched as discussed above? 

I appreciate the help!

**Comment by mamash** [comment]
Joseph, please have a look at the pkgsrc recipe here:

https://github.com/joyent/pkgsrc-wip/tree/master/phantomjs

as that's how we build the package. The static version is slightly different (not by much):

https://github.com/joyent/pkgsrc-joyent/tree/master/phantomjs-static

It's full of pkgsrc mark-up, the dependencies and patches can be inspected clearly though.

**Comment by joelclipperton** [comment]
Has anyone figured out the issue with compiling on 64bit SmartOS images?

**Comment by arunnalla16** [comment]
I am trying to compile phantomjs 1.9.2 from source. When I start building it, I encounter missing header files errors. eg: wayland-client.h etc., Can any one point me to complete bundle of phantomjs 1.9.2 source code where all the header files are in place.
Link to the source code I downloaded:https://github.com/ariya/phantomjs/archive/1.9.2.tar.gz

**Comment by ariya** [comment]
Due to limited resources, I think realistically we will never support other operating systems beyond the usual consumer ones (Windows, macOS, Linux) unless there is a significant help coming our way.

We will close this for now. If there is a new update on the subject, let's have it reopened again.
Thank you!
