### ISSUE TITLE
Problem with persistent cookies and domain wildcards

### ISSUE THREAD

**Issue by soywiz** [ariya/phantomjs#10529]
_**[soywiz@gmail.com](http://code.google.com/u/soywiz/) commented:**_

> Problem (only when --cookies-file specified):
> 
> open : htttp://domain.com/
> set a cookie for &quot;.domain.com&quot; (that includes all subdomains)
> 
> then open http://sub.domain.com/
> try to access the cookie ser for &quot;.domain.com&quot;
> 
> You won't get the cookies for the wildcard.
> 
> Related file:
> https://github.com/soywiz/phantomjs/blob/master/src/cookiejar.cpp

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #529](http://code.google.com/p/phantomjs/issues/detail?id=529).
:star2: &nbsp; **8** people had starred this issue at the time of migration.

**Comment by keolo** [comment]
We also wish this was supported.
