### ISSUE TITLE
page.onError and window.onerror do not fire on Javascript parse errors

### ISSUE THREAD

**Issue by lostplan** [ariya/phantomjs#10537]
_**[sol.pl...@gmail.com](http://code.google.com/u/116729172855378116686/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> 1.5.0
> 
> 
> <b>What steps will reproduce the problem?</b>

> 1. Create a basic QUnit test suite
> 2. Add a syntax error to one of your test modules
> 3. Run the suite using https://github.com/ariya/phantomjs/blob/1.2/examples/run-qunit.js
>     E.g. `phantomjs run-qunit.js file://$(PWD)/tests/all.html`
> 
> 
> <b>What is the expected output? What do you see instead?</b>

> Expected:
> - QUnit should detect the failed load (via window.onerror) and report a failure.
> - Within phantom script, page.onError should fire.
> 
> Observed:
> - Neither window.onerror or page.onError fire (causing QUnit to erroneously report 0 failed tests)
> 
> 
> <b>Which operating system are you using?</b>

> OS X.
> 
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> Binary.
> 
> 
> <b>Please provide any additional information below.</b>

> This was working fine in 1.4.1

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #537](http://code.google.com/p/phantomjs/issues/detail?id=537).
:star2: &nbsp; **9** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Fixed in 2.
