### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10531]
_**[scottsw...@gmail.com](http://code.google.com/u/109610248088082198752/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.5.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. Download phantomjs-1.5.0-linux-x86-dynamic.tar.gz
> 2. Untar
> 3. link downloaded phantomjs binary to /usr/local/bin/phantomjs
> 4. phantomjs --version
> 
> <b>What is the expected output? What do you see instead?</b>
> expect to see the version 1.5.0, but get this instead
> phantomjs: error while loading shared libraries: /root/installs/phantomjs/bin/../lib/libQtWebKit.so.4: ELF file OS ABI invalid
> 
> <b>Which operating system are you using?</b>
> uname -a
> Linux 2.6.9-023stab048.6-enterprise #1 SMP Mon Nov 17 19:09:18 MSK 2008 i686 i686 i386 GNU/Linux
> 
> file /sbin/init
> /sbin/init: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), for GNU/Linux 2.6.9, dynamically linked (uses shared libs), for GNU/Linux 2.6.9, stripped
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> binary
> 
> <b>Please provide any additional information below.</b>
> OS is running on a media temple VPS

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #531](http://code.google.com/p/phantomjs/issues/detail?id=531).
:star2: &nbsp; **5** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Not relevant anymore.
