### ISSUE TITLE
Rasterizing to pdf produces unclean page breaks, splitting lines in half

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10551]
_**[Sphaerod...@gmail.com](http://code.google.com/u/106509287448234044053/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.5.1 (development)
> 
> <b>What steps will reproduce the problem?</b>
> 1. Use the example command from the Quick Start guide to rasterize a web page and append &quot;A4&quot;:
> 
>  phantomjs rasterize.js 'http://en.wikipedia.org/w/index.php?title=Jakarta&amp;printable=yes' jakarta.pdf &quot;A4&quot;
> 
> What is the expected output?
> A nice rendering, page by page of the article.
> 
> What do you see instead?
> Page breaks are unclean, lines are often cut in the middle and can't be read anymore. See the attached screenshot and pdf.
> 
> <b>Which operating system are you using?</b>
> Linux openSUSE 11.4 (x86_64)
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> Compiled from source on May 15 following the compilation guide by the dot. No modifications.
> 
> <b>Please provide any additional information below.</b>
> Even using \* { page-break-inside: avoid } in CSS has no effect. It doesn't matter what the content is.
> 
> Related: Not appending &quot;A4&quot; to the example command produces an extremely long, ugly page without borders just like in issue  523 or 471 which have been marked as fixed.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #551](http://code.google.com/p/phantomjs/issues/detail?id=551).
:star2: &nbsp; **8** people had starred this issue at the time of migration.

**Comment by stlouisweb** [comment]
I have been experiencing a similar issue, line-break rules seeming to be ignored, and lines splitting in half. I updated my print CSS with the following:
```css
* {
  overflow: hidden;
}
```
And the page breaks are looking a lot more clean.

**Comment by eliavmaman** [comment]
sorry mate but this one not working

**Comment by Dyktus** [comment]
How about this issue? Is there any good way to handle page breaks with rasterizeJS?
