### ISSUE TITLE
QEventDispatcherUNIXPrivate(): Unable to create thread pipe: Too many open files

### ISSUE THREAD

**Issue by xprudhomme** [ariya/phantomjs#10560]
_**[xavier.p...@gmail.com](http://code.google.com/u/114635163454871055102/) commented:**_

> Which version of PhantomJS are you using? 
> 1.6.0 (development)
> 
> <b>What steps will reproduce the problem?</b>
> 1.  Write the following script (saved as phantomServer.js) :
> 
> var service;
> var server = require('webserver').create();
> 
> // Start WebServer and listen on port 8585
> service = server.listen(8585, function (request, response) {
> 
> ```
>  // Retrieve url to browse
>  var url = request.url.replace(/[^?]+\?url=(.+)/g, '$1');
> 
> page = new WebPage();
> 
> // On load finished, send processed contents to Webserver's HTTP response
> page.onLoadFinished = function (status) {
> 
>     console.log(&quot;Loading finished: url - Status: &quot;+status);
> 
>   var src = page.content;
> 
>   // Release page handle
>   page.release();
> 
>   //@TODO implement IF status is OK 
> 
>   // Return processed content
>   response.statusCode = 200;
>   response.write(src);
>   response.close();
> };
> 
> // Request url and load its content
> page.open(url);
> ```
> 
> });
> 1. Start this script as follows: phantomjs --load-images=no --disk-cache=yes phantomServer.js
> 2. Write a php script (or in any other language) that simply crawl a large set or urls and display their pages contents (let's say more than an hundred) using a for loop, using curl, building the urls strings as follows: 
>    $url = 'http://localhost:8585/?url=http://www.example.com'
> 
> <b>What is the expected output? What do you see instead?</b>
> The expected output should be the urls pages contents.
> 
> Everything went fine until some random moment, the phantomServer.js scrit crashes and I got the following error messages:
> 
> QEventDispatcherUNIXPrivate(): Unable to create thread pipe: Too many open files
> QEventDispatcherUNIXPrivate(): Can not continue without a thread pipe
> 
> <b>Which operating system are you using?</b>
> Ubuntu 10.04 LTS
> 
> I compiled PhantomJS from source.
> 
> It seems that the WebPage ressource is never really released, even with the &quot;page.release()&quot; piece of code used. Thus, when requesting the PhantomJS WebServer to crawl a large set or URLs, we end with too many thread pipe opened. I would say it has something to do with Qt.
> 
> (See:
> https://bugreports.qt-project.org/browse/QTBUG-20148?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel#issue-tabs
> 
> http://sourceforge.net/projects/wally/forums/forum/848087/topic/3496445
> 
> http://stackoverflow.com/questions/10013094/does-the-qt-event-listener-occupy-a-file-handle)

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #560](http://code.google.com/p/phantomjs/issues/detail?id=560).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by alexspeller** [comment]
I have found this workaround to work for me on MRI ruby: http://jonstokes.com/2014/07/07/monkey-patching-poltergeist-for-web-scraping-with-jruby/
