### ISSUE TITLE
setTimeout causes a method to be invoked multiple times

### ISSUE THREAD

**Issue by hownowstephen** [ariya/phantomjs#10567]
_**[stephen....@gmail.com](http://code.google.com/u/107142235609197780836/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 
> <b>What steps will reproduce the problem?</b>
> 1. Write a script that calls setTimeout recursively (so a timeout exists in the callback)
> 2. Add trace to show which method is being called in which order
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> Expected each method to be called once, but I get a cascade of both methods being called
> 
> <b>Which operating system are you using?</b>
> 
> OSX Lion
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> PhantomJS from brew, had same issue on previous versions of Phantom on both OSX and Ubuntu
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #567](http://code.google.com/p/phantomjs/issues/detail?id=567).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by rcaveda1** [comment]
Is anyone else still experiencing this issue? 

I am using version 2.0.0 and I am getting the same result as @hownowstephen
