### ISSUE TITLE
incredibility slow to run a simple command

### ISSUE THREAD

**Issue by samccone** [ariya/phantomjs#10577]
_**[samcc...@gmail.com](http://code.google.com/u/116273588483603342582/) commented:**_

> V 1.5 
> 
> OSX Lion 
> 
> -- program --
> console.log(&quot;ello&quot;);
> ## phantom.exit();
> 
> it takes around 20 seconds to run this..
> 
> phantomjs code.js
> 
> I downloaded the bin file

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #577](http://code.google.com/p/phantomjs/issues/detail?id=577).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by chriwup** [comment]
With PhantomJS 2.1.1 on mac os X 10.11 (high spec laptop), I did the same test as @samccone : simple console.log then phantom.exit

Sometimes it's rather fast, but most of the time it's weirdly slow (3.7 s) -- see below with 3 consecutive runs:

```shell
MacBookPro$ time phantomjs exit.js 
ello

real	0m0.587s
user	0m0.390s
sys	0m0.114s

MacBookPro$ time phantomjs exit.js 
ello

real	0m3.742s
user	0m0.396s
sys	0m0.119s

MacBookPro$ time phantomjs exit.js 
ello

real	0m3.728s
user	0m0.395s
sys	0m0.118s
```

No issue when running just `phantomjs --version`.

Any idea??

**Comment by chriwup** [comment]
I've just compiled the phantomjs binary from source (current master), same issue.

My `exit.js` file:

```javascript
console.log('ello');
phantom.exit(0);
```

**Comment by sickill** [comment]
I'm experiencing similar slow exit (about 4 seconds) with the above `exit.js` with PhantomJS 2.1.1 on macOS Sierra.

I also checked it on Ubuntu 14.04 and it exits immediately there.

**Comment by tlxpro** [comment]
A simple exit script like the one defined above always take 5 seconds and more to exit on my version of OS X Sierra. I haven't figured out why this is happening, but I can temporary fix this issue by adding "std::exit(retVal);" between "delete phantom;" and "return retVal;" of main.cpp
