### ISSUE TITLE
-webkit-hypens: auto; not supported?

### ISSUE THREAD

**Issue by pkcpkc** [ariya/phantomjs#10572]
_**[paul.hac...@gmail.com](http://code.google.com/u/100196822067086835204/) commented:**_

> Which version of PhantomJS are you using?
> 1.5
> 
> <b>What steps will reproduce the problem?</b>
> 1. Load a page with specifying following html:
> &lt;div style=&quot;width:100px;-webkit-hypens:auto;hypens:auto;&quot;&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.&lt;/div&gt;
> 
> <b>What is the expected output? What do you see instead?</b>
> Expected output would be hyphenated - but it was not...
> 
> <b>Which operating system are you using?</b>
> MacOS 10.7.4
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> Binary
> 
> <b>Please provide any additional information below.</b>
> Maybe those experimental CSS3 features are not enable in the webkit branch that you are using?
> 
> Really love your phantomjs! :)
> The icon looks like PacMan - maybe switch to a more PacMan-Style ghost?
> PKC

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #572](http://code.google.com/p/phantomjs/issues/detail?id=572).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
2.5 release will support this feature. Right now only Linux binary has it.
