### ISSUE TITLE
Would be nice if there was a __dirname & __filename like in nodejs

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#10578]
_**[chris.k...@gmail.com](http://code.google.com/u/103566034452138441665/) commented:**_

> This is useful in case you want to run test scripts from other working directories (usually for convenience).

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #578](http://code.google.com/p/phantomjs/issues/detail?id=578).
:star2: &nbsp; **5** people had starred this issue at the time of migration.

**Comment by JamesMGreene** [comment]
I still think this is worth of implementation, so I'm reopening the issue.

**Comment by Andrey-Pavlov** [comment]
Any updates?

**Comment by ethaizone** [comment]
At current I must call phantomjs via nodejs and send absolute path as arguments. I hope this one can implement.
