### ISSUE TITLE
Redered IFRAME content has incorrect dimensions

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10581]
_**[pod...@gmail.com](http://code.google.com/u/113302274672938371847/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 
> 1.5.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. Render the page http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe into a png file
> 
> <b>What is the expected output? What do you see instead?</b>
> The Expected output is in the attached picture file (correct.png). The actual output is in the picture file (incorrect.png).
> 
> <b>Which operating system are you using?</b>
> OSX 10.6.8
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> binary
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #581](http://code.google.com/p/phantomjs/issues/detail?id=581).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by wrvdklooster** [comment]
I have the same issue in version 2.0.0. Any news on this?

**Comment by worldsense-tms** [comment]
I think I ran into this today, using 1.9.7. I can make the iframe a bit taller, but not shorter than it initially is.
