### ISSUE TITLE
Investigate memory usage with concurrent users in the same web page

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10594]
_**[ariya.hi...@gmail.com](http://code.google.com/u/103266860731871773002/) commented:**_

> See https://twitter.com/HeadlessPhantom/status/211089661882413056 (150 users, 800 MB).

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #594](http://code.google.com/p/phantomjs/issues/detail?id=594).
:star2: &nbsp; **1** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Closing this one in favor of https://github.com/ariya/phantomjs/issues/11390
