### ISSUE TITLE
Implement Callback API to notify when a Frame is created (same as new page is created) (was "onInitialized doesn't work with frames")

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10608]
_**[persianp...@gmail.com](http://code.google.com/u/107866158856821173760/) commented:**_

> Global variables set in onInitialized are not visible inside FRAMEs and IFRAMEs. There's no way to override global objects in a frame before the frame is loaded.
> 
> Which version of PhantomJS are you using?
> 
> 1.5
> 
> <b>What steps will reproduce the problem?</b>
> ## index.html
> 
> &lt;html&gt;
>   &lt;head&gt;&lt;script&gt;console.log('parent', Math.random());&lt;/script&gt;&lt;/head&gt;
>   &lt;body&gt;&lt;iframe src=&quot;frame.html&quot;&gt;&lt;/iframe&gt;&lt;/body&gt;
> &lt;/html&gt;
> ## frame.html
> 
> &lt;html&gt;&lt;head&gt;&lt;script&gt;console.log('frame', Math.random());&lt;/script&gt;&lt;/head&gt;&lt;/html&gt;
> ## phantom.coffee
> 
> p = require('webpage').create()
> p.onConsoleMessage = (args...) -&gt; console.log args...
> p.onInitialized = -&gt; p.evaluate -&gt; Math.random = -&gt; 0.42
> p.open 'file:///my/path/index.html'
> 
> What is the expected output?
> 
> parent 0.42
> frame 0.42
> 
> What do you see instead?
> 
> parent 0.42
> frame 0.8671746770851314
> 
> <b>Which operating system are you using?</b>
> 
> Linux
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> source

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #608](http://code.google.com/p/phantomjs/issues/detail?id=608).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by Niek** [comment]
+1

**Comment by wisec** [comment]
Hello,
What's the status on this? 
Is it ever going to be fixed?
All major browser by now do implement a mechanism that allows to do that for frames as well - also for about:blank ones.
Is there any hack/point of interest to get this working?
Thanks.

**Comment by Mello-Yello** [comment]
+1

**Comment by evger** [comment]
+1

**Comment by jsoldi** [comment]
+1
