### ISSUE TITLE
page.cookies not working in 1.6.0

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10616]
_**[hel...@gmail.com](http://code.google.com/u/107647427892722145766/) commented:**_
> Running the following code (modified from tweet.js):
> 
> page.open(encodeURI(&quot;http://mobile.twitter.com/baudehlo&quot;), function (status) {
>     // Check for page load success
>     if (status !== &quot;success&quot;) {
>         console.log(&quot;Unable to access network&quot;);
>     } else {
>         console.log(&quot;Cookies: &quot; + JSON.stringify(page.cookies));
>         console.log(&quot;Document.cookie: &quot; + page.evaluate(function () { return document.cookie}));
>     }
>     phantom.exit();
> });
> 
> The page.cookies output should equal the document.cookie output. Instead we get:
> 
> Cookies: []
> Document.cookie: k=208.124.218.243.1340643756484334; guest_id=v1%3A134064375648874627; _mobile_sess=BAh7BzoQX2NzcmZfdG9rZW4iGTM2NmE1NjcyMTNlODBkZWFiNjYyOg9zZXNzaW9uX2lkIiU5NGQ2OTdjNDdhNWE4MjA3Yzg4MDI1MTk3N2JlMWU2NQ%3D%3D--879e0d525ee6b43ebfcad5355f191a05f7d7b96e
> 
> Tested on Mac OS X, binary distribution.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #616](http://code.google.com/p/phantomjs/issues/detail?id=616).
:star2: &nbsp; **7** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Fixed in PhantomJS 2 :-)
