### ISSUE TITLE
Table headers (thead) do not repeat across pages.

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10615]
_**[tkamb...@gmail.com](http://code.google.com/u/116048507494647305308/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 
> 1.6.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. From within the 'examples' folder, execute the following command:
> 
> ../bin/phantomjs ./rasterize.js http://sidekick.webhop.net/temp/table.html table.pdf A4
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> Table headers (&quot;Column 1&quot;, &quot;Column2&quot;, etc...) should reappear at the top of subsequent pages. They do not.
> 
> <b>Which operating system are you using?</b>
> 
> OS X - 10.7.4
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> Binary
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #615](http://code.google.com/p/phantomjs/issues/detail?id=615).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by johnnyelwailer** [comment]
What is the status on this? I still have the issue with current version 2.1.
