### ISSUE TITLE
phantomjs 1.6.0 crashes on Lion, maybe SSL-related

### ISSUE THREAD

**Issue by rmoriz** [ariya/phantomjs#10629]
_**[rmo...@gmail.com](http://code.google.com/u/114943965992773269912/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> 1.6.0
> 
> &gt;&gt; What steps will reproduce the problem?
> 1. using poltergeist (phantomjs adapter for capybara)
> 2. run a couple(!) of requests against a ssl server using &quot;--ignore-ssl-errors=yes&quot; switch
> 3. phantomjs will crash
> 
> https://github.com/jonleighton/poltergeist
> 
> &gt;&gt;What is the expected output? What do you see instead?
> 
> PhantomJS has crashed. Please file a bug report at https://code.google.com/p/phantomjs/issues/entry and attach the crash dump file: /tmp/3F28F46C-9BF1-4A6E-AB2D-16E13BDDB180.dmp
> 
> &gt;&gt; Which operating system are you using?
> 
> 10.7 64bit osx
> 
> &gt;&gt;Did you use binary PhantomJS or did you compile it from source?
> 
> 1.6.0 via homebrew
> 
> &gt;&gt; Please provide any additional information below.
> 
> I have attached 5 dumps that may help you to debug.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #629](http://code.google.com/p/phantomjs/issues/detail?id=629).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
7Fixed in PhantomJS 2 version.
