### ISSUE TITLE
crashed by using casperjs

### ISSUE THREAD

**Issue by hannyu** [ariya/phantomjs#10637]
_**[han...@gmail.com](http://code.google.com/u/103946040433656671470/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.6.0
> 
> <b>What steps will reproduce the problem?</b>
1. Acturelly, I use CasperJS, and execute `casperjs file_not_exist`. I get
> 
> $casperjs file_not_exist
> Unable to open file: fklejfe
> PhantomJS has crashed. Please file a bug report at https://code.google.com/p/phantomjs/issues/entry and attach the crash dump file: /tmp/37a71907-60b4-f72f-5af2a55c-5c7dccee.dmp
> 
> 
> 2. I debug it ,and find casperjs running this behind 
> 
> `phantomjs /home/space/tools/ruby/lib/ruby/gems/1.9.1/gems/casperjs-1.0.0.RC1/bin/bootstrap.js --casper-path=/home/space/tools/ruby/lib/ruby/gems/1.9.1/gems/casperjs-1.0.0.RC1 --cli file_not_exist`
> 
> 
> <b>What is the expected output? What do you see instead?</b>
Just like 'file not find', but the core file.
> 
> <b>Which operating system are you using?</b>
Linux  2.6.9-52bs
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
compile
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #637](http://code.google.com/p/phantomjs/issues/detail?id=637).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
