### ISSUE TITLE
Bus Error in Snow Leo 10.6.8

### ISSUE THREAD

**Issue by andreychernih** [ariya/phantomjs#10633]
_**[andrey.c...@gmail.com](http://code.google.com/u/106076502472837795797/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> 1.6.0
> 
> <b>What steps will reproduce the problem?</b>

> Download static build or install from homebrew. Try to run it without arguments.
> 
> [andrey-mbp ~]$ /usr/local/bin/phantomjs
> Bus error

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #633](http://code.google.com/p/phantomjs/issues/detail?id=633).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by ariya** [comment]
Due to the lack of a concrete follow-up possibility, this issue will be closed.
