### ISSUE TITLE
Stack trace line numbers are inaccurate

### ISSUE THREAD

**Issue by benquarmby** [ariya/phantomjs#10639]
_**[ben.quar...@callmeqube.com](http://code.google.com/u/104685721594020211940/) commented:**_
> Which version of PhantomJS are you using?
>  - 1.6.0
> 
> <b>What steps will reproduce the problem?</b>
1. Create a function that throws a handled error and emits the stack
> 2. Invoke the function, spreading the statement across multiple lines
> 3. Observe that the line number in the stack does not match the beginning of the call.
> 
> <b>What is the expected output? What do you see instead?</b>
 - Expect that line number matches beginning of invocation, as it does in other browsers such as Chrome. Instead it shows a number at or near the end of the statement.
> 
> <b>Which operating system are you using?</b>
 - Windows 7 x64
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
 - binary
> 
> <b>Please provide any additional information below.</b>
 - Failing Jasmine spec (attached) shows the expected behavior.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #639](http://code.google.com/p/phantomjs/issues/detail?id=639).
:star2: &nbsp; **9** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Fixed in PhantomJS 2 version.
