### ISSUE TITLE
PhantomJS 1.6.0 crashes on everything

### ISSUE THREAD

**Issue by jumski** [ariya/phantomjs#10644]
_**[jum...@gmail.com](http://code.google.com/u/105611767941907564582/) commented:**_
> $ phantomjs -v
> 1.6.0
> 
> $ cat /etc/lsb-release 
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=12.04
> DISTRIB_CODENAME=precise
> DISTRIB_DESCRIPTION=&quot;Ubuntu 12.04 LTS&quot;
> 
> $ cat /tmp/test.js 
> console.log('Loading a web page');
> var page = new WebPage();
> var url = &quot;http://www.phantomjs.org/&quot;;
> page.open(url, function (status) {
>   //Page is loaded!
>  console.log('haxy');
>  phantom.exit();
> });
> 
> $ phantomjs /tmp/test.js 
> PhantomJS has crashed. Please file a bug report at https://code.google.com/p/phantomjs/issues/entry and attach the crash dump file: /tmp/75c2c075-c72e-001d-74b2a710-6feba682.dmp
> Segmentation fault (core dumped)
> 
> I have tried it on several examples also.
> Used this distribution: http://code.google.com/p/phantomjs/downloads/detail?name=phantomjs-1.6.0-linux-x86_64-dynamic.tar.bz2&amp;can=2&amp;q=
> 
> I got segfault everytime.
> 
> Good luck!
> Wojtek

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #644](http://code.google.com/p/phantomjs/issues/detail?id=644).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
