### ISSUE TITLE
navigator.onLine is always false, but shouldn't be

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10647]
_**[ditesh.k...@gmail.com](http://code.google.com/u/100652478138331938389/) commented:**_
> 1. Which version of PhantomJS are you using?
> 
> Phantom v1.6.0
> 
> 2. What steps will reproduce the problem?
> 
> Consider this js file:
> ```js
> var page = require(&quot;webpage&quot;).create();
> 
> page.open(&quot;http://localhost/test.html&quot;, function (status) {
> 
>     var online = page.evaluate(function () {
>         return window.navigator.onLine;
>     });
> 
>     console.log(online);
>     page.render(&quot;/tmp/test.png&quot;);
>     phantom.exit();
> 
> });
> ```
> 
> And this is the HTML file (&quot;test.html&quot;):
> 
> ```html
> <!DOCTYPE html>
> <html>
>     <body>
>         <div id="divid">initial</div>
>         <script>
>             var elem = document.getElementById("divid");
>             if (navigator.onLine === false) elem.innerHTML = "offline";
>             else elem.innerHTML = "online";
>         </script>
>     </body>
> </html>
> ```
> 
> The output is:
> 
> `<div id="divid">offline</div>`
> 
> but expected output is:
> 
> `<div id="divid">online</div>`
> 
> <b>What is the expected output? What do you see instead?</b>

> `navigator.onLine` should be `true`. `navigator.onLine` is `false`.
> 
> 3. Which operating system are you using?
> 
> Tested on Fedora 16 and Mac OS X (Lion)
> 
> 
> 4. Did you use binary PhantomJS or did you compile it from source?
> 
> Binary.
> 
> 5. Please provide any additional information below.
> 
> No additional information.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #647](http://code.google.com/p/phantomjs/issues/detail?id=647).
:star2: &nbsp; **14** people had starred this issue at the time of migration.

**Comment by senayar** [comment]
same problem with phonegap Application, we are testing if the browser is Online to display a message and as PhantomJS navigator.onLine is always false, I used @turadg condition to force the condition for my tests.

**Comment by Vitallium** [comment]
Fixed in 2.0.
