### ISSUE TITLE
Ubuntu 12.04 64bit from tarball - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lsv** [ariya/phantomjs#10656]
_**[martin.a...@gmail.com](http://code.google.com/u/111112019049106948193/) commented:**_
> Using Ubuntu 12.04 64bit
> 
> Installed phantomjs as this
> http://code.google.com/p/phantomjs/wiki/Installation
> (downloaded the phantomjs-1.6.0-linux-x86_64-dynamic.tar.bz2 tarball)
> 
> phantomjs --help and phantomjs --version works perfect
> 
> if I just try phantomjs without any parameters I get this
> 
> PhantomJS has crashed
> Segmentation fault (core dumped)
> (attached as withoutparams.dmp)
> 
> Now I would try to run twitter bootstrap make test
> 
> jshint js/*.js --config js/.jshintrc
> jshint js/tests/unit/*.js --config js/.jshintrc
> node js/tests/server.js &amp;
> phantomjs js/tests/phantom.js &quot;http://localhost:3000/js/tests&quot;
> 
> node.js:201
>         throw e; // process.nextTick error, or 'error' event on first tick
>               ^
> Error: addListener only takes instances of Function
>     at Server.&lt;anonymous&gt; (events.js:101:11)
>     at new Server (http.js:1321:10)
>     at Object.createServer (http.js:1338:10)
>     at Object.&lt;anonymous&gt; (/media/sdc3/wwwroot/scandesigns.domain.my/public/fileadmin/templates/page/bootstrap/js/tests/server.js:12:6)
>     at Module._compile (module.js:432:26)
>     at Object..js (module.js:450:10)
>     at Module.load (module.js:351:31)
>     at Function._load (module.js:310:12)
>     at Array.0 (module.js:470:10)
>     at EventEmitter._tickCallback (node.js:192:40)
> PhantomJS has crashed. Please file a bug report at https://code.google.com/p/phantomjs/issues/entry and attach the crash dump file: /tmp/32ef6e45-2ff8-5f5a-7fa87a65-3cf4feef.dmp
> Segmentation fault (core dumped)
> make: *** [test] Error 139
> 
> dmp file attached as tbootstrap.dmp
> 
> phantomjs --version reports 1.6.0
> 
> I could have used apt-get install phantomjs but thats version 1.4.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #656](http://code.google.com/p/phantomjs/issues/detail?id=656).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
