### ISSUE TITLE
PhantomJS has crashed

### ISSUE THREAD

**Issue by randypuro** [ariya/phantomjs#10655]
_**[ra...@goodeggs.com](http://code.google.com/u/109946508870797804146/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> 1.6.0
> 
> <b>What steps will reproduce the problem?</b>

> Indeterminate, but regular.
> 
> <b>What is the expected output? What do you see instead?</b>

> PhantomJS has crashed. Please file a bug report at https://code.google.com/p/phantomjs/issues/entry and attach the crash dump file: /tmp/598e080c-58dd-e183-12fb7ba8-29a93fff.dmp
> 
> <b>Which operating system are you using?</b>

> Ubuntu 11.10 i686
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> binary
> 
> <b>Please provide any additional information below.</b>

> crash dump attached

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #655](http://code.google.com/p/phantomjs/issues/detail?id=655).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
