### ISSUE TITLE
phantomjs occasionally hangs when opening a page with many dependents

### ISSUE THREAD

**Issue by mozbhearsum** [ariya/phantomjs#10652]
_**[bhear...@gmail.com](http://code.google.com/u/100416685062684753912/) commented:**_

> I'm using phantomjs + qunit to do some automated testing of some client side Javascript. While doing so, I found that phantom would sometimes hang in page.open(), a behaviour I was unable to reproduce by hand in Firefox. I tried using a Python-based web server as well as Apache - neither changed the behaviour. I tried different versions of QUnit, which also didn't affect behaviour. I was originally running with Phantom 1.4.0, and after upgrading to 1.6.0 is greatly reduced the rate at which I hit the hang, so I _think_ this is a Phantom bug (or maybe a Webkit one). All my tests were done on Linux.
> 
> When the tests are run successfully, the output from the web server looks like this:
> 2012-07-11 15:38:29,402 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:29] &quot;GET /tests.html HTTP/1.1&quot; 401 -
> 2012-07-11 15:38:29,404 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:29] &quot;GET /tests.html HTTP/1.1&quot; 200 -
> 2012-07-11 15:38:29,406 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:29] &quot;GET /static/jquery-1.6.4.js HTTP/1.1&quot; 200 -
> 2012-07-11 15:38:29,408 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:29] &quot;GET /static/qunit-1.9.0.js HTTP/1.1&quot; 401 -
> 2012-07-11 15:38:29,408 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:29] &quot;GET /static/ausadmin.js HTTP/1.1&quot; 401 -
> 2012-07-11 15:38:29,409 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:29] &quot;GET /static/test/test_ausadmin.js HTTP/1.1&quot; 401 -
> 2012-07-11 15:38:29,411 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:29] &quot;GET /static/test/test_ausadmin.js HTTP/1.1&quot; 200 -
> 2012-07-11 15:38:29,412 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:29] &quot;GET /static/qunit-1.9.0.js HTTP/1.1&quot; 200 -
> 2012-07-11 15:38:29,414 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:29] &quot;GET /static/ausadmin.js HTTP/1.1&quot; 200 -
> 2012-07-11 15:38:29,450 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:29] &quot;GET /reset HTTP/1.1&quot; 401 -
> 2012-07-11 15:38:29,640 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:29] &quot;GET /reset HTTP/1.1&quot; 200 -
> 2012-07-11 15:38:29,678 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:29] &quot;PUT /users/foo/permissions/admin HTTP/1.1&quot; 201 -
> 2012-07-11 15:38:29,682 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:29] &quot;GET /users/foo/permissions/admin?format=html HTTP/1.1&quot; 200 -
> 
> When I hit the hang, it's only:
> 2012-07-11 15:38:30,487 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:30] &quot;GET /tests.html HTTP/1.1&quot; 401 -
> 2012-07-11 15:38:30,489 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:30] &quot;GET /tests.html HTTP/1.1&quot; 200 -
> 2012-07-11 15:38:30,492 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:30] &quot;GET /static/jquery-1.6.4.js HTTP/1.1&quot; 200 -
> 2012-07-11 15:38:30,493 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:30] &quot;GET /static/qunit-1.9.0.js HTTP/1.1&quot; 401 -
> 2012-07-11 15:38:30,494 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:30] &quot;GET /static/test/test_ausadmin.js HTTP/1.1&quot; 401 -
> 2012-07-11 15:38:30,495 - werkzeug._log#116: 127.0.0.1 - - [11/Jul/2012 15:38:30] &quot;GET /static/ausadmin.js HTTP/1.1&quot; 401 -
> 
> If I attach strace to phantom 1.4.0, I see that it's poll()'ing 3 different file descriptors:
> read(3, 0x7fff9192e500, 16)             = -1 EAGAIN (Resource temporarily unavailable)
> recvfrom(6, &quot;\10\2\255\0\30\303\31\16\257\0\0\0\257\0\0\0\0\0\0\0\215\5z\3\215\5z\3\0\0\0\2&quot;, 4096, 0, NULL, NULL) = 32
> recvfrom(6, 0x1b14884, 4096, 0, 0, 0)   = -1 EAGAIN (Resource temporarily unavailable)
> recvfrom(6, 0x1b14884, 4096, 0, 0, 0)   = -1 EAGAIN (Resource temporarily unavailable)
> recvfrom(6, 0x1b14884, 4096, 0, 0, 0)   = -1 EAGAIN (Resource temporarily unavailable)
> poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN}, {fd=8, events=POLLIN}], 3, -1) = 1 ([{fd=8, revents=POLLIN}])
> read(3, 0x7fff9192e500, 16)             = -1 EAGAIN (Resource temporarily unavailable)
> recvfrom(6, 0x1b14884, 4096, 0, 0, 0)   = -1 EAGAIN (Resource temporarily unavailable)
> recvmsg(8, {msg_name(0)=NULL, msg_iov(1)=[{&quot;l\4\1\1\31\0\0\0\256\23\30\0\265\0\0\0\1\1o\0000\0\0\0/org/fre&quot;..., 2048}], msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_CMSG_CLOEXEC) = 225
> recvmsg(8, 0x7fff9192db30, MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
> write(3, &quot;\1\0\0\0\0\0\0\0&quot;, 8)         = 8
> write(7, &quot;\1\0\0\0\0\0\0\0&quot;, 8)         = 8
> recvfrom(6, 0x1b14884, 4096, 0, 0, 0)   = -1 EAGAIN (Resource temporarily unavailable)
> poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN}, {fd=8, events=POLLIN}], 3, 0) = 1 ([{fd=3, revents=POLLIN}])
> 
> Sometimes it appears to hit the poll() timeout, other times not. Those fds are:
> phantomjs 18082 bhearsum    3u  0000                0,9        0     6821 anon_inode
> phantomjs 18082 bhearsum    6u  unix 0xffff88006e80bdc0      0t0  2180614 socket
> phantomjs 18082 bhearsum    8u  unix 0xffff880074358680      0t0  2181568 socket
> 
> I'm not quite sure how to figure out precisely what sockets it's looking at.
> 
> In phantom 1.6.0 it's slightly different, it's stuck in select():
> select(4, [3], [], [], NULL)            = ? ERESTARTNOHAND (To be restarted)
> --- SIGWINCH (Window changed) @ 0 (0) ---
> select(4, [3], [], [], NULL)            = ? ERESTARTNOHAND (To be restarted)
> --- SIGWINCH (Window changed) @ 0 (0) ---
> select(4, [3], [], [], NULL)            = ? ERESTARTNOHAND (To be restarted)
> --- SIGWINCH (Window changed) @ 0 (0) ---
> select(4, [3], [], [], NULL
> 
> I tried to reduce this to a minimal non-python test case, but I was unable to reproduce that way. I have attached the script that I run with Phantom and the rendered output of tests.html. If there's anything else I can do to help figure out the root cause of this, please let me know.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #652](http://code.google.com/p/phantomjs/issues/detail?id=652).
:star2: &nbsp; **12** people had starred this issue at the time of migration.

**Comment by voor** [comment]
Is this issue back in 2.0?  Heavy Javascript pages, especially ones using AngularJS or latest browser features, are causing my load to hang indefinitely.  I'm not entirely sure how to troubleshoot it -- I've been trying to add timeouts inside the javascript:
```javascript
var endScript = function(message, code) {
  console.log(message);
  phantom.exit(code);
};

window.setTimeout(function() {
  endScript('ERROR: Timeout', 2);
}, 60000);
```

But I'm only able to initiate the timeout outside of phantomjs.

**Comment by codehate** [comment]
@voor  +1 same here. @ariya any update on this (Why PhantomJS freezes)?

**Comment by voor** [comment]
A temporary fix I've found is making sure you don't have any script tags in the header, and then render the page anyway on timeout.

**Comment by himleyb85** [comment]
+1 

using casperjs v1.9.8, it's almost half the time it hangs for me

**Comment by eojthebrave** [comment]
I've been seeing this issue in CasperJS as well. Adding the following to my tests at least allows PhantomJS to timeout instead of just hang forever.

`casper.options.pageSettings.resourceTimeout = 20000;`

**Comment by q0rban** [comment]
OCD alert: Can someone with access fix the typo in the title on this issue? :smile:

**Comment by Bluestart83** [comment]
page.settings.resourceTimeout = 10000;

Solve my issue, but not all data loaded...

**Comment by Malenconiaprincep** [comment]
+1

**Comment by amerikan** [comment]
+1

**Comment by telemmaite** [comment]
+1 version 2.1.1. Random timeouts different files every time. On my end it is 50:50 between success and fail.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://awojnar.com/mean.php?n>

 

klaus@hebsgaard.dk

**Comment by wenerme** [comment]
Hang forever, v2.1.1 OS X 10.11.3

__01.js__

```
var page = require('webpage').create();
console.log('The default user agent is ' + page.settings.userAgent);
page.settings.userAgent = 'SpecialAgent';

var endScript = function(message, code) {
  console.log(message);
  phantom.exit(code);
};

window.setTimeout(function() {
  endScript('ERROR: Timeout', 2);
}, 5000);


page.onConsoleMessage = function(message) {
  console.log('-> ' + message);
};

page.onCallback = function() {
  phantom.exit();
};


page.open('http://www.httpuseragent.org', function(status) {
  if (status !== 'success') {
    console.log('Unable to access network');
  } else {
    var ua = page.evaluate(function() {
      return document.getElementById('myagent').textContent;
    });
    console.log(ua);
  }
  phantom.exit();
});
```

```
$ phantomjs --debug=true --cookies-file=cookie.txt 01.js
2016-05-03T11:38:37 [DEBUG] CookieJar - Created and will store cookies in: "cookie.txt"
2016-05-03T11:38:38 [DEBUG] Set  "http"  proxy to:  "" : 1080
2016-05-03T11:38:38 [DEBUG] Phantom - execute: Configuration
2016-05-03T11:38:38 [DEBUG]      0 objectName : ""
2016-05-03T11:38:38 [DEBUG]      1 cookiesFile : "cookie.txt"
2016-05-03T11:38:38 [DEBUG]      2 diskCacheEnabled : "false"
2016-05-03T11:38:38 [DEBUG]      3 maxDiskCacheSize : "-1"
2016-05-03T11:38:38 [DEBUG]      4 diskCachePath : ""
2016-05-03T11:38:38 [DEBUG]      5 ignoreSslErrors : "false"
2016-05-03T11:38:38 [DEBUG]      6 localUrlAccessEnabled : "true"
2016-05-03T11:38:38 [DEBUG]      7 localToRemoteUrlAccessEnabled : "false"
2016-05-03T11:38:38 [DEBUG]      8 outputEncoding : "UTF-8"
2016-05-03T11:38:38 [DEBUG]      9 proxyType : "http"
2016-05-03T11:38:38 [DEBUG]      10 proxy : ":1080"
2016-05-03T11:38:38 [DEBUG]      11 proxyAuth : ":"
2016-05-03T11:38:38 [DEBUG]      12 scriptEncoding : "UTF-8"
2016-05-03T11:38:38 [DEBUG]      13 webSecurityEnabled : "true"
2016-05-03T11:38:38 [DEBUG]      14 offlineStoragePath : ""
2016-05-03T11:38:38 [DEBUG]      15 localStoragePath : ""
2016-05-03T11:38:38 [DEBUG]      16 localStorageDefaultQuota : "-1"
2016-05-03T11:38:38 [DEBUG]      17 offlineStorageDefaultQuota : "-1"
2016-05-03T11:38:38 [DEBUG]      18 printDebugMessages : "true"
2016-05-03T11:38:38 [DEBUG]      19 javascriptCanOpenWindows : "true"
2016-05-03T11:38:38 [DEBUG]      20 javascriptCanCloseWindows : "true"
2016-05-03T11:38:38 [DEBUG]      21 sslProtocol : "default"
2016-05-03T11:38:38 [DEBUG]      22 sslCiphers : "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-RC4-SHA:ECDHE-RSA-RC4-SHA:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:RC4-SHA:RC4-MD5"
2016-05-03T11:38:38 [DEBUG]      23 sslCertificatesPath : ""
2016-05-03T11:38:38 [DEBUG]      24 sslClientCertificateFile : ""
2016-05-03T11:38:38 [DEBUG]      25 sslClientKeyFile : ""
2016-05-03T11:38:38 [DEBUG]      26 sslClientKeyPassphrase : ""
2016-05-03T11:38:38 [DEBUG]      27 webdriver : ":"
2016-05-03T11:38:38 [DEBUG]      28 webdriverLogFile : ""
2016-05-03T11:38:38 [DEBUG]      29 webdriverLogLevel : "INFO"
2016-05-03T11:38:38 [DEBUG]      30 webdriverSeleniumGridHub : ""
2016-05-03T11:38:38 [DEBUG] Phantom - execute: Script & Arguments
2016-05-03T11:38:38 [DEBUG]      script: "01.js"
2016-05-03T11:38:38 [DEBUG] Phantom - execute: Starting normal mode
2016-05-03T11:38:38 [DEBUG] WebPage - setupFrame ""
2016-05-03T11:38:38 [DEBUG] FileSystem - _open: ":/modules/fs.js" QMap(("mode", QVariant(QString, "r")))
2016-05-03T11:38:38 [DEBUG] FileSystem - _open: ":/modules/system.js" QMap(("mode", QVariant(QString, "r")))
2016-05-03T11:38:38 [DEBUG] FileSystem - _open: ":/modules/webpage.js" QMap(("mode", QVariant(QString, "r")))
The default user agent is Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1
2016-05-03T11:38:38 [DEBUG] WebpageCallbacks - getGenericCallback
2016-05-03T11:38:38 [DEBUG] WebPage - updateLoadingProgress: 10
```

**Comment by EvgeniySpinovSell** [comment]
I'm also having the same with Apache backend. In parallel testing this becomes a nightmare, as single hanged instance of phantomJS leads to a test failure.

**Comment by czettnersandor** [comment]
Same problem with 2.1.1 for me. We have a 30 minutes long test suite, so a hang on one step is really annoying as the whole test should be started again.

**Comment by EvgeniySpinovSell** [comment]
As a work around I've reduced number of external resources, i.e. js, css files from 50-60 to 5. It reduced number of hangs dramatically. 

Looks like it hangs somewhere during loading this resources.

**Comment by czettnersandor** [comment]
Not an option for me, I'm testing a JavaScript widget in Magento and every dependency should be there for a valid test.

**Comment by blaskovicz** [comment]
In [my linked commit](https://github.com/blaskovicz/MagicStick/commit/c1c0eb73218df7bf0c88d8d3d9dd38ca1b1139b3), I:
- run my tests with a 5 second timeout and call `phantom.exit()` if reached
- launch `phantomjs` with a local file (`file:///path/to/view.html`)
- use 18 javascript tags that are absolute paths (eg: `/js/foo.js`)

In my case, the hang was similar in that it was related to the script tags. I was getting all script tags on the document via `document.querySelectorAll('script')`; when checking the `src` property of each, `phantomjs` would choke after the first item, with `strace` results similar to those mentioned.

**Comment by 0x59R11** [comment]
Guys, I have a Web-page from I need parsing specified data, and draw it like at picture below. The main point, this is JS scripts on this web-site that will update that data each 10–30 seconds, and I'm going to take it and draw. But Idk why this is work only once on start, after first render it won't render again. As you can see on the picture, there is only one render of data, if data were updated it'll re-render. Maybe **PhantomJS** has any options to solve my question.
P.S.  I use .NET **WebDriver**. For take needed data I use `IWebElement`
Thank you!

![image](https://user-images.githubusercontent.com/41921371/219261755-07f0c824-9e81-43c5-acdc-30e7af286f0a.png)
