### ISSUE TITLE
PNG output is perfect, but PDF output doesn't seem to respect CSS styles

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10669]
_**[si...@thenextbigsound.com](http://code.google.com/u/105773985312764404241/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.6.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. Using rasterize.js (from the example documentation) to render html to a PDF or PNG
> <b>2.</b>
> <b>3.</b>
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> Not sure if this is exactly a bug - the PNG output renders perfectly, but the PDF output doesn't seem to use the CSS styles specified in the page. Is PDF just not capable of rendering with all CSS rules?
> 
> <b>Which operating system are you using?</b>
> 
> Ubuntu Linux
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> Binary
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #669](http://code.google.com/p/phantomjs/issues/detail?id=669).
:star2: &nbsp; **5** people had starred this issue at the time of migration.

**Comment by dinatih** [comment]
> add media: "all", phantomjs will render just fine

Hello @michelson, where did you put media: "all" please ? Is it in rasterize.js as ```page.settings.media = all;``` ?

**Comment by michelson** [comment]
@dinatih add media="all" to your css, like:

<link href="my.css" media="all" rel="stylesheet" />

best!

**Comment by dinatih** [comment]
Oh alright! But I have some inline css style for printing :s, so this doesn't works. I think it was a solution for tell phantomjs to not use some css rules.

Thank you anyway !

**Comment by shaneparsons** [comment]
@hawkerboy7 +1 Works for me!

**Comment by sunyang213** [comment]
Adding media='all' instead of media='screen' saves my life.

Thanks all

**Comment by pomirleanu** [comment]
Just remove <b>"!important"</b> from all the @media print sections css and will work!
 <b>PHNATOMJS first reanders the @media print css and if you have important he will omit the rest of the css....</b>

**Comment by shaidams64** [comment]
@hawkerboy7 where do I find my bootstrap file?

**Comment by hawkerboy7** [comment]
Just the file you downloaded from http://getbootstrap.com/ I don't know where you placed it. But if you have sublime text editor you can try the following:
- Open your whole project folder with sublime (you can drag and drop the folder onto sublime)
-  Right click the folder and press 'Find in Folder'
- Then type "@media print {" and press

**Comment by shaidams64** [comment]
@hawkerboy7 sorry but what do you mean by "project folder" ? I don't think i ever downloaded bootstrap. I'm actually trying to convert ipython notebooks in my local host to pdf... I am passing customized themes to my notebook which shows up when I open it in the browser but it's like phantomjs disregards them

**Comment by shaidams64** [comment]
I thought you were talking about editing phantomjs source files some how...

**Comment by hawkerboy7** [comment]
Are you creating a pdf from a website (html and css)?
Then a problem you may be facing is that phantom when phantom creates a pdf the media query @media print {} is used, which can override some of your own styling.

If I understand you correctly you have a html page with css which has a customized theme?
Then when you make the pdf, the phantom disregards your custom theme?
This could be occurring because of what I wrote just above.
Removing the !important from all properties in your css file inside the @media print {} might help

**Comment by shaidams64** [comment]
you understood it right, Thank you I will try that

**Comment by shaidams64** [comment]
@hawkerboy7 +1 it worked!! Thank you! removing the !important tag was the trick! I just had too many css files but I finally found the right one to edit! :)

**Comment by hawkerboy7** [comment]
Great I am happy it worked! =D

**Comment by toppa** [comment]
@hawkerboy7 - worked for me too. For anyone else using the boostrap-sass gem, I forked it, and removed the import of the bootstrap print styles. It was forcing everything to black & white (including table background colors, etc), which is too presumptuous for my taste.

https://github.com/poka-yoke-design/bootstrap-sass

**Comment by dulcedilip** [comment]
It worked for me after removing _print.sass from _bootstrap.sass, but still some of the web page content is not capturing, due to this capturing of the screen i cant remove !important from all @media queries. Any help to solve this problem.

**Comment by blakebeaupain** [comment]
+1 on this. What about printing websites that we do not own/maintain to PDF?

**Comment by dulcedilip** [comment]
I am not bother much on other websites on pdf generation as of now.. i am targeting for my website which is not rendering properly as pdf.

**Comment by katrotz** [comment]
@hawkerboy7 Nice catch, I thought that this is a problem of the phantomjs, but actually the bootstrap print media was screwing my background colours

**Comment by ZachMilne** [comment]
@hawkerboy7 Thanks for catching this. It was indeed the bootstrap print styles for me causing the colors to be changed to black in the PDF but not the PNG.

**Comment by luisaoba** [comment]
@hawkerboy7 perfect! It Works! The best solution is the simple solution! Thank you!

**Comment by juhguu** [comment]
@hawkerboy7 Your save my life! Thank you. :)

**Comment by pratheekhegde** [comment]
@hawkerboy7 Thanks a lot. I removed all the occurrence of !important from my bootstrap source. I was getting my CSS in the PDF.

**Comment by gunzip** [comment]
see also https://github.com/ariya/phantomjs/issues/10374#issuecomment-267044771

**Comment by flexelektro** [comment]
@hawkerboy7 thanks a lot.

**Comment by pouu69** [comment]
i'm used "only screen" in css media
above i did read a solve problem
so i changed link tag like below
````
<link href="" media="all" rel="stylesheet"/>
````
but not working.

**Comment by shenkev** [comment]
@hawkerboy7 removing !important from @media print didn't seem to work for me, the fonts are still messed up. Especially the math I render with MathJax, the font sizes/styles are definitely not right. Any ideas?

![test_pdf](https://cloud.githubusercontent.com/assets/5405172/26390474/89efda6a-4013-11e7-9ca0-7ca6a61b6c85.PNG)
![test_html](https://cloud.githubusercontent.com/assets/5405172/26390477/8edd291a-4013-11e7-967e-217127bd586e.PNG)

**Comment by hawkerboy7** [comment]
The following may help you see the differences in the inspector.
`F12`
`open the rendering tab`
`Emulate CSS Media` There you can change `screen` to `print`.
This may help you see what the page would like like if printed.

**Comment by medusar** [comment]
@hawkerboy7 it works for me too, thanks
