### ISSUE TITLE
PhantomJS has crashed.

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10675]
_**[eugene.m...@gmail.com](http://code.google.com/u/105310361067299319588/) commented:**_
> &gt; Which version of PhantomJS are you using? 
> 1.6.0
> 
> &gt; What steps will reproduce the problem?
> 1. Run &quot;phantomjs test.js&quot; in your terminal. Find test.js file in attach.
> 
> &gt; What is the expected output? What do you see instead?
> Expected output is html page.
> &quot;Segmentation fault (core dumped)&quot; I see instead of it.
> 
> &gt; Which operating system are you using?
> Ubuntu Desktop 12.04
> 
> &gt; Did you use binary PhantomJS or did you compile it from source?
> Binary
> 
> &gt; Please provide any additional information below.
> 
> See the crash dump file in attach.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #675](http://code.google.com/p/phantomjs/issues/detail?id=675).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
Supposedly this was fixed with commit 40a14b72b132468f4bbdfc6ff2dca30407cf866e.
