### ISSUE TITLE
Tried to use casperjs.

### ISSUE THREAD

**Issue by callen23dc** [ariya/phantomjs#10670]
_**[callen.2...@gmail.com](http://code.google.com/u/116236745508958555165/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> <b>What steps will reproduce the problem?</b>
1. Install phantomjs
> 2. Install casperjs
> 3. Try to run casperjs...anything.
> 
> <b>What is the expected output? What do you see instead?</b>

> All I did was run &quot;casperjs&quot;, I can't even get the version.
> 
> PhantomJS has crashed. Please file a bug report at https://code.google.com/p/phantomjs/issues/entry and attach the crash dump file: /tmp/590ccef3-8037-e8fb-4d8feb79-586d8c83.dmp
> Segmentation fault (core dumped)
> 
> <b>Which operating system are you using?</b>

> Linux odin 3.2.0-26-generic #41-Ubuntu SMP Thu Jun 14 17:49:24 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> binary, from you guys.
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #670](http://code.google.com/p/phantomjs/issues/detail?id=670).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
