### ISSUE TITLE
Phantomjs crashes with a top 1Kadplanning website

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10689]
_**[eazymand...@gmail.com](http://code.google.com/u/114168613477264959071/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.6.1
> 
> <b>What steps will reproduce the problem?</b>
1. get and install phantomjs-1.6.1-macosx-static
> 2. ./phantomjs-1.6.1-macosx-static/bin/phantomjs ./phantomjs-1.6.1-macosx-static/examples/netlog.js http://www.softpedia.com
> <b>3.</b>

> <b>What is the expected output? What do you see instead?</b>

> I expected all requested/received messages
> I see PhantomJS crash message, after some requested/received lines were printed (attached file phantomjs_crash_printed_lines.txt).
> 
> <b>Which operating system are you using?</b>
OS X 10.7.4
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
I used binary PhantomJS.
> 
> <b>Please provide any additional information below.</b>
I obtained same result with PhantomJS 1.6.1 on Linux Ubuntu 11.04, compiled from source.
> I obtained similar crash results with old Phantomjs version on OS X 10.7.4

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #689](http://code.google.com/p/phantomjs/issues/detail?id=689).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
Supposedly this was fixed in commit 40a14b72b132468f4bbdfc6ff2dca30407cf866e.
