### ISSUE TITLE
Phantom crashing on CentOS even when linked against local QT

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10699]
_**[sa...@pivotallabs.com](http://code.google.com/u/105663441621740193392/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.6.1
> 
> <b>What steps will reproduce the problem?</b>
N/A - occurs when running the test suite for our closed source application.
> 
> <b>What is the expected output? What do you see instead?</b>
N/A
> 
> <b>Which operating system are you using?</b>
CentOS release 5.6 (Final)
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Compiled from source - downloaded zip file, unzip, cd in, run build.sh. Compile completed with no errors. ldd shows that the binary is linking against the right version of qt (the one within the phantomjs build directory).
> 
> <b>Please provide any additional information below.</b>

> I am running poltergeist which uses phantom.js as a capybara driver. When I run the specs, random specs will fail with the &quot;PhantomJS has crashed. Please file a bug report at https://code.google.com/p/phantomjs/issues/entry and attach the crash dump file&quot; error. When I run it multiple times, different specs fail each time, but always the same way.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #699](http://code.google.com/p/phantomjs/issues/detail?id=699).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Not applicable anymore. We use our own patched copy of Qt.
