### ISSUE TITLE
Enhancement: Add response data to resourceReceived

### ISSUE THREAD

**Issue by chiefcll** [ariya/phantomjs#10702]
_**[chief...@gmail.com](http://code.google.com/u/100860601130618125503/) commented:**_
> I'd like to have access to the raw response data on resourceReceived callback. This would be useful for AJAX requests that have a JSON response to have raw access to the JSON to validate a proper response.
> 
> Furthermore, it would be great if we could make an AJAX call, and return mock data or modify it before the browser gets the data.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #702](http://code.google.com/p/phantomjs/issues/detail?id=702).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Implemented in master. See 434d4e0101a540525e8f89a657ea553fb38b040b

**Comment by BordenJardine** [comment]
This hasn't made it into a release yet, correct?

**Comment by stackflows** [comment]
It even seems to have been "redacted" back out of the current revision of the source code. :(
