### ISSUE TITLE
Problem to run Rails specs

### ISSUE THREAD

**Issue by lucascaton** [ariya/phantomjs#10707]
_**[lucasca...@gmail.com](http://code.google.com/u/118268867722221722464/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.6.1
> 
> <b>What steps will reproduce the problem?</b>
1. Run integration specs using Ruby + Rails + Rspec + Capybara + poltergeist gem + PhantomJS.
> 
> <b>Which operating system are you using?</b>
Mac OSX 10.8 (Mountain Lion)
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
I used homebrew tool to install.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #707](http://code.google.com/p/phantomjs/issues/detail?id=707).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by ariya** [comment]
Closing for the lack of further follow-up.
