### ISSUE TITLE
Antialiased fonts in rasterized output although antialiasing is disabled

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10705]
_**[marek.kn...@gmail.com](http://code.google.com/u/117148466277586041574/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.6.1/1.6.0/1.5.0 compiled from the source and also all binary downloads with the same versions.
> 
> <b>What steps will reproduce the problem?</b>
> 1. run ./build script
> 2. run bin/phantomjs examples/rasterize.js http://en.wikipedia.org output.png
> 3. look at the output. fonts in the image are using antialiasing, although antialias is disabled.
> 
> my ~/.fonts.conf file in my home directory contains:
> 
>  &lt;match target=&quot;font&quot;&gt;
>   &lt;edit mode=&quot;assign&quot; name=&quot;antialias&quot;&gt;
>    &lt;bool&gt;false&lt;/bool&gt;
>   &lt;/edit&gt;
>  &lt;/match&gt;
> 
> <b>What is the expected output? What do you see instead?</b>
> Text in output image will NOT be antialiased, same as in output1.4.1.png - created using phantomjs 1.4.1
> 
> <b>Which operating system are you using?</b>
> Linux 32bit openSUSE 11.4
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> both
> 
> <b>Please provide any additional information below.</b>
> I think, QT/webkit src distributed with the phantomjs code contains some bug which ignore user's fontconfig settings. The phantomjs version 1.4.1 is distributed without any QT/webkit specific code and this version works correctly.
> 
> please, let me know, if you need more info.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #705](http://code.google.com/p/phantomjs/issues/detail?id=705).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by tlightsky** [comment]
I meet this problem too
