### ISSUE TITLE
Pervasive crashes

### ISSUE THREAD

**Issue by tysontate** [ariya/phantomjs#10701]
_**[ty...@stovepipestudios.com](http://code.google.com/u/109498726185435884564/) commented:**_
> PhantomJS version 1.6.1 using capybara 1.1.2 + poltergeist 0.7.0 (via Ruby 1.9.3p194) on MacOS X Mountain Lion.
> 
> I get consistent crashes when trying to navigate to URLs and click on things. The JavaScript code on the page I'm attempting to visit does not raise errors (confirmed in all browsers).

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #701](http://code.google.com/p/phantomjs/issues/detail?id=701).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.6.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
