### ISSUE TITLE
--local-storage-path does not work in win32 binary

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10716]
_**[exp....@gmail.com](http://code.google.com/u/100086556860407475193/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> D:\Program Files\phantomjs&gt;_phantomjs.exe --version
> 1.6.1
> 
> <b>What steps will reproduce the problem?</b>
EXEC: _phantomjs.exe --cookies-file=tmp/cookie/52.txt --disk-cache=no --web-security=no --local-to-remote-url-access=no --local-storage-path=&quot;D:\Program Files\phantomjs\tmp\storage/52&quot; --local-storage-quota=1024 alipromo.js 52
> 
> &quot;D:\Program Files\phantomjs\tmp\storage/52&quot; is existent directory.
> but still the program saves localstorage data to current user's profile directory like &quot;C:\Documents and Settings\(USER)\Local Settings\Application Data\Ofi Labs\PhantomJS&quot;
> 
> slash direction in localstorage path (\ or /) does not affects to result
> 
> <b>Which operating system are you using?</b>
winxp 32bit
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
binary
> 
> <b>Please provide any additional information below.</b>
it is not an ntfs-right issue

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #716](http://code.google.com/p/phantomjs/issues/detail?id=716).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Duplicate. See #11596
