### ISSUE TITLE
fonts from @font-face are improperly being referenced

### ISSUE THREAD

**Issue by filmjbrandon** [ariya/phantomjs#10713]
_**[filmjbra...@gmail.com](http://code.google.com/u/104431293783160044626/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 
> 1.6.1
> 
> <b>What steps will reproduce the problem?</b>
> 1.Using the attached bug_test.html file.
> 2. &quot;phantomjs rasterize.js bug_test.html bug_out.png&quot;
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> Expected(screenshot from Chrome): 
> See expected_out.png
> 
> Actual(actual rendered image:
> See bug_out.png
> 
> <b>Which operating system are you using?</b>
> CentOS 6
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> binary
> 
> <b>Please provide any additional information below.</b>
> It appears that when using mutliple @font-face declarations, the fonts get mixed up, or it uses the &quot;lightest&quot; known font.  I was trying to find an easy to re-produce example with more than just the two bold/light styles as it is more pronounced, I had tried with Helvetica Neue but I can not find that publically referenced anywhere so this will have to do.
> 
> It even appears that in some cases, fonts that are not even referenced in the HTML/CSS, but that are part of the server installed fonts may show up instead of what is intended - i was hoping to track this down to a bad reference/pointer in the version of webkit used, but i was unable to compile phantomjs on either my Mac (OS 10.8) or CentOS to explore further.
> 
> Other ways to test - change the font-family in the @font-face to individual names and the result is the same.
> 
> In all cases I tested, Chrome renders properly and can be used as the base case.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #713](http://code.google.com/p/phantomjs/issues/detail?id=713).
:star2: &nbsp; **9** people had starred this issue at the time of migration.

**Comment by jackblackCH** [comment]
Exactly same problem here.

Tested with  Helvetica Neue Webfont, self hosted, bought from fonts.com

We have 3 TypeFaces of Helvetica in CSS:
- The generated PDF contains always only 1 fontface of the "Helvetica Neue".
- The generated PDF can contain another font-face of a different font. For example it shoes correctly the IconFont and Helvetica.
