### ISSUE TITLE
PhantomJS crashes - after a number of steps (num steps seem to vary)

### ISSUE THREAD

**Issue by ThisIsAKhan** [ariya/phantomjs#10717]
_**[sadi.k...@gmail.com](http://code.google.com/u/115884846699467598930/) commented:**_
> Which version of PhantomJS are you using? 
> 1.6.1
> 
> <b>What steps will reproduce the problem?</b>
1. I run a phantomJS script (uses CasperJS libraries)
> 2. Run it - usually if it has a large number of steps that it performs, it seems to crash - even though there is a lot of free memory on the machine
> 
> <b>What is the expected output? What do you see instead?</b>
Didn't expect a crash :)  - Saw the following: 
> ---------
> pure virtual method called
> terminate called without an active exception
> PhantomJS has crashed. Please file a bug report at https://code.google.com/p/phantomjs/issues/entry and attach the crash dump file: /tmp/0f9e6e8b-e1cb-9ba1-706166ca-78449fd7.dmp
> Aborted
> 
> 
> 
> <b>Which operating system are you using?</b>
Ubuntu 10.04 LTS
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Binary
> 
> <b>Please provide any additional information below.</b>
This seems to happen whenever i run a fairly long running code on PhantomJS - not sure why. 
> 
> Attached is the crashdump.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #717](http://code.google.com/p/phantomjs/issues/detail?id=717).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
