### ISSUE TITLE
Crashing unexpectedly in cucumber

### ISSUE THREAD

**Issue by gjastrab** [ariya/phantomjs#10725]
_**[gjast...@gmail.com](http://code.google.com/u/107265771831452311603/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> 1.6.1
> 
> <b>What steps will reproduce the problem?</b>
1. I'm running cucumber w/ capybara &amp; poltergeist and had a test running fine, but after changing one line (just testing whether content is present in an &lt;p class=&quot;description&quot;&gt; tag.
> <b>2.</b>
<b>3.</b>

> <b>What is the expected output? What do you see instead?</b>

> I'm expecting just green dots from cucumber.  Here is the error:
> 
> PhantomJS has crashed. Please file a bug report at https://code.google.com/p/phantomjs/issues/entry and attach the crash dump file: /tmp/1B20D38D-5AB2-42A0-B9B3-0BFF5D73816A.dmp
> 
> The PhantomJS client died while processing {&quot;name&quot;:&quot;visit&quot;,&quot;args&quot;:[&quot;http://127.0.0.1:51973/dashboard&quot;,{}]} (Capybara::Poltergeist::DeadClient)
> ./features/step_definitions/user_steps.rb:26:in `/^at &quot;([^&quot;]+)&quot;$/'
> 
> <b>Which operating system are you using?</b>

> OS X 10.8
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> Used homebrew
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #725](http://code.google.com/p/phantomjs/issues/detail?id=725).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by ariya** [comment]
Closing, due to lack of follow-up.
