### ISSUE TITLE
Windows build exe using MS VS 2009 (solution is small patch to define missing var)

### ISSUE THREAD

**Issue by peterabarry** [ariya/phantomjs#10738]
_**[peteraba...@gmail.com](http://code.google.com/u/113647378366247470221/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
HEAD
> 
> <b>What steps will reproduce the problem?</b>
1. try building following instructions on wiki for windows exe.
> 
> <b>What is the expected output? What do you see instead?</b>
Build works 
> 
> <b>Which operating system are you using?</b>
Windows Server 2003 x64
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
source
> <b>Please provide any additional information below.</b>

> FIX for me copied from :http://code.google.com/p/google-breakpad/issues/detail?id=465
> 
> src/client/windows/handler/exception_handler.cc
> 
> #if _MSC_VER &gt;= 1400  // MSVC 2005/8
> +#ifndef STATUS_INVALID_PARAMETER    
> +#define STATUS_INVALID_PARAMETER            ((DWORD   )0xC000000DL)
> +#endif
>  // static
>  void ExceptionHandler::HandleInvalidParameter(const wchar_t* expression, const wchar_t* function

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #738](http://code.google.com/p/phantomjs/issues/detail?id=738).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Outdated. Minimal supported versions are MSVC2012 and above.
