### ISSUE TITLE
PhantomJS has crashed

### ISSUE THREAD

**Issue by denispeplin** [ariya/phantomjs#10749]
_**[Denis.Pe...@gmail.com](http://code.google.com/u/110889772875829836769/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> 1.6.1
> 
> <b>What steps will reproduce the problem?</b>
1. Build PhantomJS
> 2. Copy to /usr/local, ln -s to binary
> 3. Run rspec using Capybara with Poltergeist driver
> 
> <b>What is the expected output? What do you see instead?</b>

> Passing tests
> 
> <b>Which operating system are you using?</b>

> Kubuntu 12.04
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> Compiled. (apt-get version only 1.4, binary not working).
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #749](http://code.google.com/p/phantomjs/issues/detail?id=749).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
