### ISSUE TITLE
Linux Redhat6 Enterprize version 1. 6 install... Korean site font broken

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10742]
_**[yan...@mz.co.kr](http://code.google.com/u/109652123093259324656/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> /root/phantomjs-1.6.1/bin/phantomjs /root/phantomjs-1.6.1/examples/rasterize.js http://www.daum.net daum.png
> 
> <b>What steps will reproduce the problem?</b>
1. Hangul some broken
> <b>2.</b>
<b>3.</b>

> <b>What is the expected output? What do you see instead?</b>

> <b>Which operating system are you using?</b>

> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #742](http://code.google.com/p/phantomjs/issues/detail?id=742).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by ariya** [comment]
This is an outdated problem. CJK characters on newer Linux distributions work just fine.

**Comment by zackw** [comment]
For anyone experiencing a problem with CJK rendering on a current Linux distribution, make sure you have all the necessary fonts installed from the distribution.  PhantomJS does not bundle any fonts.

**Comment by zackw** [comment]
whoops, didn't mean to reopen it
