### ISSUE TITLE
Setting User-Agent header doesn't work

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10745]
_**[joniscoo...@googlemail.com](http://code.google.com/u/107035513554942447369/) commented:**_

> To reproduce:
> 
> page.open('...', { method: 'get', headers: { 'User-Agent': 'foo' } })
> 
> As a workaround, the user agent can be set via page.settings.userAgent, but the above should really work too.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #745](http://code.google.com/p/phantomjs/issues/detail?id=745).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by NekoNova** [comment]
is there any update on this? Because I'm running into the same problem right now, that our web-application recognises the Capybara-Poltegeist test as invalid browser due the header not set properly.

**Comment by fleck** [comment]
This issue still seems to be present. I'm using version 2.1.1.
