### ISSUE TITLE
--local-storage-path does not work on OS X

### ISSUE THREAD

**Issue by kcbanner** [ariya/phantomjs#10757]
_**[kcbanner@gmail.com](http://code.google.com/u/kcbanner/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> 1.6.1
> 
> <b>What steps will reproduce the problem?</b>
1. Start phantomjs using --local-storage-path=/some/path
> 
> <b>What is the expected output? What do you see instead?</b>

> Items will be written to /Users/&lt;username&gt;/Library/Application Support/Ofi Labs/PhantomJS instead of the specified path
> 
> <b>Which operating system are you using?</b>

> OS X 10.7.4
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> Binary.
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #757](http://code.google.com/p/phantomjs/issues/detail?id=757).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by mattbailey** [comment]
This is pretty annoying, has there been any fix for this yet? This still appears to be happening on 1.9.8

**Comment by Vitallium** [comment]
The fix has been landed to current `master`. We will not backport this fix to 1.x version. Please, use 2.x version instead. Thanks.
