### ISSUE TITLE
Error in polgeist

### ISSUE THREAD

**Issue by tibastral** [ariya/phantomjs#10759]
_**[thib...@milesrock.com](http://code.google.com/u/108320276335710110092/) commented:**_
> 1.6.1

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #759](http://code.google.com/p/phantomjs/issues/detail?id=759).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by ariya** [comment]
Due to the lack of a concrete follow-up possibility, this issue will be closed.
