### ISSUE TITLE
send keypress/keydown/keyup does not send the actual keycode to the javascript engine.

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10760]
_**[Nathanae...@gmail.com](http://code.google.com/u/115088735673786570727/) commented:**_

> Which version of PhantomJS are you using? 
> 1.7 (Trunk)
> 
> <b>What steps will reproduce the problem?</b>
> 1. page.evaluate(function() { var item = document.querySelector('id'); item.focus(); });
> 2. page.sendEvent('keypress', 'a');
> 3. HTML: &lt;input type=text name='id' id='id' onkeydown=&quot;check()&quot;&gt; &lt;script&gt;function check(e) { console.log(e.keyCode, e.charCode, e.which); }
> 
> What is the expected output? 
> 65, a, (65/'a')
> 
> What do you see instead?
> 0, 0, 0
> 
> <b>Which operating system are you using?</b>
> Windows
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> Source
> 
> <b>Please provide any additional information below.</b>
> This issue maybe related to:
> https://bugs.webkit.org/show_bug.cgi?id=16735

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #760](http://code.google.com/p/phantomjs/issues/detail?id=760).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by japgolly** [comment]
> all keyup events return 0 for keyCode, which, and charCode.

Same with PhantomJS 2.0.

**Comment by johnloringpollard** [comment]
Is there a solution for this?
