### ISSUE TITLE
Cannot retrieve true viewport size of page when pageSize set to "A4", etc.

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10762]
_**[wak...@gmail.com](http://code.google.com/u/110659472403376287251/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.6.1
> 
> <b>What steps will reproduce the problem?</b>
> 1. Using rasterize.js, render to PDF a page that contains the following JavaScript:
>         function pageHeight() {
>             return window.innerHeight != null? window.innerHeight :
>                 document.documentElement &amp;amp;&amp;amp; document.documentElement.clientHeight ?
>                 document.documentElement.clientHeight : document.body != null ?
>                 document.body.clientHeight : null;
>         }
>         function addtext(tonode, text){
>             if (document.createTextNode){
>                 var mytext = document.createTextNode(text)
>                 tonode.appendChild(mytext)
>             }
>         }
> 
> // Somewhere in body's onLoad:
> addtext(someDOMNode, 'pageHeight: ' + pageHeight() + 'pageWidth: ' + pageWidth());
> <b>2.</b>
> <b>3.</b>
> 
> <b>What is the expected output? What do you see instead?</b>
> The width/height of the page size, be it A4, A3, or whatever.
> 
> <b>Which operating system are you using?</b>
> Windows XP
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> Binary
> 
> <b>Please provide any additional information below.</b>
> I am trying to write a script to automatically rotate and resize images to fit printed media. This works fine in, e.g., Chrome, which knows its viewport's width and height, but using rasterize.js the pageWidth() and pageHeight() functions always return 600. This is the value that is set in rasterize.js, but it does not appear possible to replace these with the true values as page.paperSize is capable of returning only the information supplied in the command line (i.e., A4, A3, whatever was passed  - information you know anyway), and not the actual size of the viewport when printed to media of that size.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #762](http://code.google.com/p/phantomjs/issues/detail?id=762).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by roblillack** [comment]
Here you go: https://code.google.com/p/phantomjs/issues/attachmentText?id=762&aid=7620001000&name=rasterize.js&token=ABZ6GAfiPNqI-Ket-z9suecQJSBJR-8tKA%3A1424894652068
