### ISSUE TITLE
phantonjs crashed with casperjs

### ISSUE THREAD

**Issue by mborecki** [ariya/phantomjs#10766]
_**[borec...@gmail.com](http://code.google.com/u/109839071486017421670/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.6.1
> 
> <b>What steps will reproduce the problem?</b>
1. Fresh phantomjs install
> 2. Fresh casperjs install
> 3. Run casperjs --version
> 
> <b>What is the expected output? What do you see instead?</b>
expect:
> Anything (casperjs version)
> see:
> PhantomJS has crashed. Please file a bug report at https://code.google.com/p/phantomjs/issues/entry and attach the crash dump file: /tmp/42b2e233-b302-91d9-68654c9e-7b65c2f4.dmp
> Naruszenie ochrony pamięci (core dumped)
> 
> 
> <b>Which operating system are you using?</b>
Ubuntu 12.04
> 
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
binary from phantomjs site
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #766](http://code.google.com/p/phantomjs/issues/detail?id=766).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
