### ISSUE TITLE
Phantom JS Crashed when running Rspec on a Rails 3.1 application on Linux

### ISSUE THREAD

**Issue by kandalf** [ariya/phantomjs#10786]
_**[leonardo...@gmail.com](http://code.google.com/u/113659809489700978285/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.6.0
> 
> <b>What steps will reproduce the problem?</b>
I cannot really tell, I was running my whole test suite and it's a big one so I have supressed the doc output
> 
> <b>What is the expected output? What do you see instead?</b>
The expected output is either a . (dot) if the spec pass or an F if it fails.
> What I got is:
> PhantomJS has crashed. Please file a bug report at https://code.google.com/p/phantomjs/issues/entry and attach the crash dump file: /tmp/316f9fd8-8250-6a62-068f8668-409765e4.dmp
> 
> And it hanged up there not responding to ^C 
>  
> <b>Which operating system are you using?</b>
Linux (Arch) Qt 4.8.2
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Compiled from source

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #786](http://code.google.com/p/phantomjs/issues/detail?id=786).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
