### ISSUE TITLE
Callback parameter to page.open() is not getting fired

### ISSUE THREAD

**Issue by dsimil** [ariya/phantomjs#10780]
_**[dsi...@gmail.com](http://code.google.com/u/105631739704610099527/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.5.1 (development)
> 
> <b>What steps will reproduce the problem?</b>
> 1. phantomjs.exe rasterize.js &quot;http://latimesblogs.latimes.com/world_now/2012/09/two-killed-as-tunisia-protest-against-film-spiraled-into-violence.html&quot; test1.png
> 2. phantomjs.exe rasterize.js &quot;http://www.huffingtonpost.com/sanjay-sanghoee/romney-versus-bloomberg_b_1881218.html?utm_hp_ref=elections-2012&quot; test2.png
> 
> <b>What is the expected output? What do you see instead?</b>
> The aforementioned webpages aren't getting captured. The callback to page.open() never gets fired and the script never exits. 
> 
> <b>Which operating system are you using?</b>
> Windows 7
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> Binary
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #780](http://code.google.com/p/phantomjs/issues/detail?id=780).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by atwellpub** [comment]
I am having this issue when I run phantom JS on a local page from PHP using shell_exec():

PHP Script:

```
<?php
error_reporting(E_ALL);
session_write_close();
$result = shell_exec('phantomjs server.js ' . $_GET['url'] ); 
echo $result;
```

JS script
```
/**
 *  PhantomJs server for calling webpages & processing JS
 *  returns page content
 */

var args = require('system').args;
var address = args[1];
address = 'http://local.wordpress.dev/';

console.log('PhantomJs is accessing ' + address);
var page = new WebPage();

/**
 *  
 */
page.onResourceError = function(resourceError) {
    page.reason = resourceError.errorString;
    page.reason_url = resourceError.url;
};

/**
 *  
 */
phantom.onError = function(msg, trace) {
  var msgStack = ['PHANTOM ERROR: ' + msg];
  if (trace && trace.length) {
    msgStack.push('TRACE:');
    trace.forEach(function(t) {
      msgStack.push(' -> ' + (t.file || t.sourceURL) + ': ' + t.line + (t.function ? ' (in function ' + t.function +')' : ''));
    });
  }
  console.error(msgStack.join('\n'));
  phantom.exit(1);
};

/**
 *  
 */
page.onError = function(msg, trace) {

  var msgStack = ['ERROR: ' + msg];

  if (trace && trace.length) {
    msgStack.push('TRACE:');
    trace.forEach(function(t) {
      msgStack.push(' -> ' + t.file + ': ' + t.line + (t.function ? ' (in function "' + t.function +'")' : ''));
    });
  }

  console.error(msgStack.join('\n'));

};

/**
 *  
 */
console.log( typeof address );
page.open( address , function (status) {
	console.log('here5');
    if ('success' !== status) {
        console.log(
			"Error opening url \"" + page.reason_url
			+ "\": " + page.reason
		);
		phantom.exit( 1 );
    } else {
		console.log('here');
		console.log(page.content);      
        phantom.exit();
    }
});
```

If I change the URL to a live remote server rather than a local server; for example if I set the URL to twitter.com then I have no trouble getting a response body back from the PHP method.

**Comment by atwellpub** [comment]
https://github.com/ariya/phantomjs/issues/13273
