### ISSUE TITLE
phantomJS has crashed

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10787]
_**[math...@5gl.org](http://code.google.com/u/104795386047769087093/) commented:**_
> Which version of PhantomJS are you using?
> 1.6.1
> 
> my rails app has 2300+ cucumber scenarios, I am trying to replace selenium/firefox by poltergeist/phantomjs
> 
> phantomjs has crashed and recommended me I enter an issue to this address
> 
> <b>Which operating system are you using?</b>
ubuntu server 12.04 64bit
> 
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
binary, recently downloaded and installed from website
> simple extract + symlink method
> 
> <b>Please provide any additional information below.</b>

> I am also using parallel_test with 4 thread wide

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #787](http://code.google.com/p/phantomjs/issues/detail?id=787).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Inactive! And no info. :)
