### ISSUE TITLE
Error while running Phantomjs

### ISSUE THREAD

**Issue by komex** [ariya/phantomjs#10791]
_**[kom...@gmail.com](http://code.google.com/u/108757720226832077806/) commented:**_
> PhantomJS 1.6.1.
> 
> <b>What steps will reproduce the problem?</b>
1. Exec ./bin/phantomjs
> 
> <b>What is the expected output? What do you see instead?</b>
Phantomjs shell
> 
> <b>Which operating system are you using?</b>
Linux
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
phantomjs-1.6.1-linux-x86_64-dynamic

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #791](http://code.google.com/p/phantomjs/issues/detail?id=791).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
