### ISSUE TITLE
Object.freeze exists but does not work on Arrays

### ISSUE THREAD

**Issue by karenliu1** [ariya/phantomjs#10817]
_**[ka...@squareup.com](http://code.google.com/u/107139510695280723923/) commented:**_
> Which version of PhantomJS are you using? 1.7.0
> 
> <b>What steps will reproduce the problem?</b>
1. Run phantomjs REPL.
> 2. Run &quot;a=[]; Object.freeze(a); a.push(1); a.length&quot;.
> 
> What is the expected output?
> 0
> 
> What do you see instead?
> 1
> 
> <b>Which operating system are you using?</b>
Mac OS X 10.7.5
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
binary via &quot;brew install phantomjs&quot;
> 
> <b>Please provide any additional information below.</b>
Object.freeze works on Objects (i.e. &quot;o={}; Object.freeze(o)&quot;), but does not work on arrays.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #817](http://code.google.com/p/phantomjs/issues/detail?id=817).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by ariya** [comment]
This is solved in PhantomJS 2. Also, it throws an exception:

```
> bin/phantomjs freeze_test.js 
TypeError: Attempted to assign to readonly property.

  freeze_test.js:3 in push
```

I believe the exception in this case is the correct behavior.
