### ISSUE TITLE
CSS filters not supported

### ISSUE THREAD

**Issue by jarben** [ariya/phantomjs#10814]
_**[jaroslav...@gmail.com](http://code.google.com/u/117670017722819924657/) commented:**_

> 1.7.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. load page with using css filters, e.g. -webkit-filter: hue-rotate(158deg);
> 
> <b>What is the expected output? What do you see instead?</b>
> should render with augmented color
> 
> <b>Which operating system are you using?</b>
> W7
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> binary 1.7.0 from the website
> 
> <b>Please provide any additional information below.</b>
> might be fixes when webkit is updated to latest versions

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #814](http://code.google.com/p/phantomjs/issues/detail?id=814).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by flesler** [comment]
+1, it's been so long. This opens up many opportunities when using PhantomJS to generate images

**Comment by annam** [comment]
+1 support for this would be great!

**Comment by keithics** [comment]
+ 2016

**Comment by joshualambert** [comment]
+1 Has there been any movement on this ticket? I'm also having problems with basic CSS filters, even with a -webkit prefix in the CSS.

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thanks!

**Comment by huadong** [comment]
2017...

**Comment by KakashiSensei** [comment]
Filters not supported till now?
