### ISSUE TITLE
Allow PhantomJS scripts to listen for and respond to UNIX signals

### ISSUE THREAD

**Issue by trevordixon** [ariya/phantomjs#10818]
_**[trevordi...@gmail.com](http://code.google.com/u/107543690554752918733/) commented:**_

> Maybe make the API similar to node.js's (http://nodejs.org/api/process.html#process_signal_events). In node, you can do:
> 
> process.on('SIGINT', function() {
>     // shutdown things
>     process.exit();
> });

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #818](http://code.google.com/p/phantomjs/issues/detail?id=818).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by sdimkov** [comment]
+1

**Comment by artisdom** [comment]
+1

**Comment by jchamberlain** [comment]
+1

**Comment by scr4bble** [comment]
+1
