### ISSUE TITLE
history.pushState + location.href issue

### ISSUE THREAD

**Issue by indigolookup** [ariya/phantomjs#10833]
_**[amdfc...@gmail.com](http://code.google.com/u/100956466445259803460/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> <b>What steps will reproduce the problem?</b>
1. history.pushState({}, '', '(teste%25');
> 2. console.log(location.href)
> 
> <b>What is the expected output? What do you see instead?</b>
Expected: teste%25
> Actual result: teste%
> 
> <b>Which operating system are you using?</b>
Windows 7
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Binary
> 
> <b>Please provide any additional information below.</b>

> location.href is expected to contain the original undecoded string.
> This is how every browser works, expect on safari &lt;= 5 that also had this bug.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #833](http://code.google.com/p/phantomjs/issues/detail?id=833).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
