### ISSUE TITLE
can not load http://forbes.com

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10837]
_**[wayne....@gmail.com](http://code.google.com/u/110270563721024274797/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.5 and 1.7
> 
> <b>What steps will reproduce the problem?</b>
1. phantomjs phantomjs/examples/loadspeed.js http://forbes.com
> <b>2.</b>
<b>3.</b>

> <b>What is the expected output? What do you see instead?</b>
load speed and everything with this example
> 
> <b>Which operating system are you using?</b>
centos 5.x
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
used both versions (binary and compiled from source) 
> 
> <b>Please provide any additional information below.</b>

> [user@portal_dev Wayne]$ phantomjs phantomjs/examples/loadspeed.js http://forbes.com
> FAIL to load the address
> [user@portal_dev Wayne]$
> 
> I'm able to load http://google.com. Not sure what's special about http://forbes.com. I do have some other pages that share the same problem.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #837](http://code.google.com/p/phantomjs/issues/detail?id=837).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by akashnimare** [comment]
I am getting the same error for a url.
> Fail to load undefined
Does anybody know the solution of this problem?

**Comment by qa2015** [comment]
project abandoned? no progress and yslow seems broken with firefox latest version..

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
