### ISSUE TITLE
Support Proxy Auto Config (PAC)

### ISSUE THREAD

**Issue by ariesb** [ariya/phantomjs#10834]
_**[aries.be...@gmail.com](http://code.google.com/u/112999637473289141293/) commented:**_

> PhantomJS to support proxy auto config files as part of proxy settings.
> 
> Which version of PhantomJS are you using? 
> 1.7
> 
> <b>What is the expected output? What do you see instead?</b>
> Provide filtering of network access based on proxy settings via Proxy Auto Config. (http://en.wikipedia.org/wiki/Proxy_auto-config)
> 
> <b>Which operating system are you using?</b>
> Linux

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #834](http://code.google.com/p/phantomjs/issues/detail?id=834).
:star2: &nbsp; **5** people had starred this issue at the time of migration.

**Comment by JeremyMarshall** [comment]
Is there any update to this? I was thinking this could be a way of writing a proxy for people in corporate environments where they can download with a browser but not download via scripts/curl/wget from a command line due to not being able to pass through credentials.

So this piece could be the proxy which in turn calls the actual proxy after authorizing. then passes the downloaded file back

**Comment by ariesb** [comment]
Yes, this was implemented, but I left the company. Ill ask someone to do a
PR on this. Sorry about no updates.

Cheers,
Aries

**Comment by clockrun** [comment]
Hi Ariesb,
any update? I am lucky enough to see somebody implement this feature. I am facing the same requirement.

**Comment by raghulraj** [comment]
Hi @ariesb ,
Any update on this?

**Comment by dplin** [comment]
Any update? Would be great if we can have support for .pac on phantomJS.  This is the only thing that prevent our team from using it behind a corporate firewall.

**Comment by stubarlow** [comment]
While waiting for .pac support in PhantomJS I found a way around it. I just run a program called fiddler locally. You can configure it to run as a proxy on your local machine. 

Fiddler retrieves proxy settings from your system (in Fiddler go to Tools -> Fiddler Options -> Gateway Tab and select 'Use System Proxy'

`caps.setCapability(PhantomJSDriverService.PHANTOMJS_CLI_ARGS, new String[]{"--web-security=no", "--ignore-ssl-errors=yes", "--webdriver-loglevel=ERROR", "--proxy=localhost:8888", "--proxy-type=http", "--proxy-auth=myuser:mypassword"});`

**Comment by MonsieurBon** [comment]
Hi @ariesb 
Is there any chance you can still provide the patch for your change?
