### ISSUE TITLE
phantomjs crashed o Lion 10.7.5, .dmp attached

### ISSUE THREAD

**Issue by horaceho** [ariya/phantomjs#10857]
_**[hora...@gmail.com](http://code.google.com/u/106972801875058279253/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> <b>What steps will reproduce the problem?</b>
1. /usr/local/bin/phantomjs iphonereserve.coffee &quot;firstname&quot; &quot;lastname&quot; &quot;name@mail.com&quot; &quot;X123456(7)&quot; &quot;MD297ZP/A&quot; &quot;R485&quot;
> 2. phantomJS has crashed. Please file a bug report at https://code.google.com/p/phantomjs/issues/entry and attach the crash dump file: /tmp/603D7C51-6E9F-4C84-8E82-BA8EE05046B2.dmp
> <b>3.</b>

> What is the expected output? What do you see instead? crashed
> 
> Which operating system are you using? OSX Lion 10.7.5
> 
> Did you use binary PhantomJS or did you compile it from source? brew install phantomjs
> 
> <b>Please provide any additional information below.</b>

> $ /usr/local/bin/phantomjs iphonereserve.coffee &quot;firstname&quot; &quot;lastname&quot; &quot;name@mail.com&quot; &quot;X123456(7)&quot; &quot;MD297ZP/A&quot; &quot;R485&quot;
> 
> - iphonereserve.coffee script attached
> - dmp file attached

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #857](http://code.google.com/p/phantomjs/issues/detail?id=857).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Fixed in PhantomJS 2 version.
