### ISSUE TITLE
document.cookie adds double-quotes around cookie values containing double-quotes

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10869]
_**[mikko.ko...@gmail.com](http://code.google.com/u/113766226002215504178/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 
> 1.7.0
> 
> <b>What steps will reproduce the problem?</b>
> 
> Run:
> 
> var page = require('webpage').create()
> page.open('http://www.this-page-intentionally-left-blank.org/', function(status) {
>   if (status !== 'success') throw Error('Unable to access network')
>   var x = page.evaluate(function() {
>     document.cookie = &quot;key=val&quot;ue&quot;
>     return document.cookie
>   })
>   console.log(x)
>   phantom.exit()
> })
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> Expected output would be
> key=val&quot;ue
> 
> Actual is
> key=&quot;val&quot;ue&quot;
> 
> <b>Which operating system are you using?</b>
> 
> OSX 10.8.2
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> Binary
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #869](http://code.google.com/p/phantomjs/issues/detail?id=869).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by Enzo90910** [comment]
Above code still gives output
key="val\"ue"
actually breaking many JavaScripts which (improperly) put the " character in cookie values without encoding it.
Mac OS X 10.10.1 // PhantomJS 1.9.8 // Binary

**Comment by makbol** [comment]
+1
