### ISSUE TITLE
Rasterize (print) to PDF no background images

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10879]
_**[r.sw...@gmail.com](http://code.google.com/u/113902657203516049580/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.7.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. Create a HTML page with an element and link to print.css (media=print)
> 2. Style the element with a background image
> 3. Rasterize to an PDF file, the background image is not rendered
> 
> <b>What is the expected output? What do you see instead?</b>
> It looks as &quot;expected&quot;, since most browser do not print background images by default, but I think it must be possible to enable it. (As webkitwebsettings has a print-backgrounds option?)
> 
> <b>Which operating system are you using?</b>
> linux (debian squeeze)
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> binary
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #879](http://code.google.com/p/phantomjs/issues/detail?id=879).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by powerpete** [comment]
its a little bit strange.

this will NOT work as excepted:
```
<!DOCTYPE html>
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            @media print {
                h1 {
                    background-image: url('meinlogo.png');
                }
            }
        </style>
    </head>
    <body>
        <h1>Test</h1>
    </body>
</html>
```

But when i' preload the image in the html, it's working as excepted:
```
<!DOCTYPE html>
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            @media print {
                h1 {
                    background-image: url('meinlogo.png');
                }
            }
        </style>
    </head>
    <body>
        <img style="display: none;" src="meinlogo.png" />
        <h1>Test</h1>
    </body>
</html>
```
