### ISSUE TITLE
Redirects from http requests to "file:" URLs are allowed

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10876]
_**[jamespi...@googlemail.com](http://code.google.com/u/108329492225048509443/) commented:**_

> If PhantomJS can be sent to arbitrary &quot;http:&quot; URLs by an untrusted user (for example, if PhantomJS is used to render web site previews), an attacker can send it to a maliciously crafted web site, which redirects it to a &quot;file:&quot; URL. If the URL requested is a system file, and the attacker can see the output (as in the preview renderer scenario), they can obtain system files.
> 
> It is not sufficient to use input validation to prevent the user requesting &quot;file:&quot; URLs, as PhantomJS allows redirects to &quot;file:&quot; URLs.
> 
> Which version of PhantomJS are you using? 1.7
> 
> <b>What steps will reproduce the problem?</b>
> 1. Set up a web server that redirects requests to a &quot;file:&quot; URL
> 2. Ask PhantomJS to visit the server
> 
> Alternatively, run the attached script in PhantomJS (which, on Linux machines, will redirect requests to /etc/passwd).
> 
> Expected output: PhantomJS refuses to obey the malicious redirect
> Actual output: PhantomJS follows the redirect
> 
> Which operating system are you using? Linux
> 
> Did you use binary PhantomJS or did you compile it from source? Binary

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #876](http://code.google.com/p/phantomjs/issues/detail?id=876).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by hackvertor** [comment]
If anyone else is wondering, this seems fixed to me on phantom 2.1.1. I tried a server side, meta and javascript redirects all failed.
