### ISSUE TITLE
body/data not sent in HTTP DELETE

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10873]
_**[Travis.G...@gmail.com](http://code.google.com/u/114510609752042367163/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.7.0 &amp; HEAD at 40a14b72b132468f4bbdfc6ff2dca30407cf866e
> 
> <b>What steps will reproduce the problem?</b>
1.  Configure a web server with an appropriate route and log parameters received.
> <b>2.</b>
                $.ajax({
>                     contentType: 'application/json',
>                     url: &quot;/posts/destroy&quot;,
>                     type: 'DELETE',
>                     dataType: 'json',
>                     data: '{&quot;subs&quot;:[{&quot;c_id&quot;:2,&quot;c_list_id&quot;:2}]}',                                                                                                                                                       
>                     modal: self
>                 }); 
>  
> 3.   observe that on the server, it is received but the data (subs) is missing.
> 4.   Running this as a POST instead of DELETE observe that the data is received.
>    4a   e.g. in rails change your route to post and the type above to 'POST'
>    4b   observe receipt of data
> 
> 
> <b>What is the expected output? What do you see instead?</b>
The data component should be included and received by the server for DELETE.
> 
> <b>Which operating system are you using?</b>
OSX 10.7.4 &amp; Centos 6.2
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
binary 1.7.0  &amp; compiled HEAD
> 
> <b>Please provide any additional information below.</b>

> It looks like the entityBody is stripped when using DELETE.  From what I can tell, it's legal to send data using DELETE.  
> Additionally this works in latest firefox, chrome, ie9, and safari.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #873](http://code.google.com/p/phantomjs/issues/detail?id=873).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by tomconroy** [comment]
Argh! Came here after debugging for hours. Our API accepts authorization in the request body. Moving it to the header for now.

**Comment by markdwhite** [comment]
+1 on this one which also cost me a lot of debugging time. On  v2.0 compiled from source.

Managed to work round this be setting headers in the AJAX DELETE call rather than passing the data in the body, but in my case I was only passing a CSRF token. Details given here in case it helps anyone else.

Laravel 5, using jQuery:

   data: { _token: token }, // Will fail
   headers: { 'X-CSRF-TOKEN': token }, // Will work

**Comment by karlingen** [comment]
+1

Not fixed in `v2.0.0`.
The workaround seems to be switching to `POST` instead of `DELETE` but that sucks for our design.

**Comment by shi-314** [comment]
+1

**Comment by redthor** [comment]
+1

**Comment by KevP** [comment]
+1024

**Comment by sarahjschultz** [comment]
:raised_hands: Praise the lawd for this thread! :pray: 

Still an issue and the quick solution still seems to be swapping POSTs in for DELETEs (a la @jamesotron and @karlingen).

**Comment by flyHe** [comment]
same issue in 2.0.0,but fixed in v2.1.1

**Comment by Vitallium** [comment]
Fixed in 2.1.1
