### ISSUE TITLE
PDF meta data for title, author, keywords not set with page.render()

### ISSUE THREAD

**Issue by simplegroupware** [ariya/phantomjs#10883]
_**[thb...@gmail.com](http://code.google.com/u/112169312225612282195/) commented:**_
> 1.7.0 (win32)
> 
> Code:
> var page = new WebPage();
> var system = require(&quot;system&quot;);
> page.open(&quot;http://www.spiegel.de&quot;, function (status) {
>   page.render(&quot;test.pdf&quot;);
>   phantom.exit();
> });
> 
> Result: open test.pdf in Foxit Reader: PDF meta data for Title, Subject, Author, Creator, Keywords are empty. Producer gets correctly filled.
> 
> The page has:
> &lt;title&gt;SPIEGEL ONLINE - Nachrichten&lt;/title&gt;
> &lt;meta name=&quot;author&quot; content=&quot;SPIEGEL ONLINE, Hamburg, Germany&quot; /&gt;
> &lt;meta name=&quot;keywords&quot; content=&quot;SPIEGEL ONLINE, DER SPIEGEL, Nachrichten, News,Home&quot; /&gt;
> &lt;meta name=&quot;copyright&quot; content=&quot;SPIEGEL ONLINE, Hamburg, Germany&quot; /&gt;
> &lt;meta name=&quot;description&quot; content=&quot;Deutschlands führende Nachrichtenseite. Alles Wichtige aus Politik, Wirtschaft, Sport, ...
> 
> Had used html2ps before, but phantomjs is much greater for PDF export!

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #883](http://code.google.com/p/phantomjs/issues/detail?id=883).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by piprog** [comment]
Any news on implementing this, or any other way to set the metadata?

**Comment by cryptocompress** [comment]
I use pdftk like this:
```/usr/bin/pdftk [infile] update_info_utf8 [meta_data] output [outfile] encrypt_128bit dont_ask owner_pw [pass] allow Printing DegradedPrinting ModifyAnnotations```

**Comment by piprog** [comment]
thx crypto for the tip :)

**Comment by ariya** [comment]
The scope of PhantomJS should not include a more sophisticated PDF generation. In all cases (and following the Unix principle), such a tweak can be done as a post-processing step (e.g. using pdftk as mentioned earlier).
