### ISSUE TITLE
phantom.cookies is empty when accessing remote host and do ajax request

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10886]
_**[ser...@dorogin.com](http://code.google.com/u/117107762633526958142/) commented:**_

> Env: PhantomJS 1.7 (binary release), OS: Windows 7 x64.
> 
> Steps to reproduce the problem:
> 1. create and open a remote page (http://domain.com)
> 2. loaded page contains code which does an ajax request
> 3. server response for the ajax request contains cookies (it was a httponly cookie in my case)
> 
> I expected that the recieved cookies should be set as page and the browser cookies (in page.cookies and phantom.cookies). But instead theay are totally ignored (page.cookies and phantom.cookies are empty arrays).
> When I access a page on localhost evetything works as expected.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #886](http://code.google.com/p/phantomjs/issues/detail?id=886).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by chrismaxim** [comment]
There is indeed still a bug in phantomjs related to this.  Once the page response has been received, the cookiejar gets destroyed and it takes all of its session cookies with it.  See src/cookiejar.cpp, in particular in the destructor with the call to "purgeSessionCookies();".
