### ISSUE TITLE
Incorrect TypeError thrown when setting property with no setter

### ISSUE THREAD

**Issue by by-example** [ariya/phantomjs#10889]
_**[stui...@gmail.com](http://code.google.com/u/118297382881350535276/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.7.0
> 
> <b>What steps will reproduce the problem?</b>
1. Start PhantomJS
> 2. At the REPL type:
> var page = require('webpage').create();
> page.evaluate(function() { x = {}; Object.defineProperty(x, &quot;test&quot;, { get: function() { return 5; } }); return x.test = 3; })
> 
> <b>What is the expected output? What do you see instead?</b>
Expected to see 3. 
> Actually see &quot;TypeError: setting a property that has only a getter&quot;
> 
> <b>Which operating system are you using?</b>
Mac OS X 10.8.2
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Binary from site
> 
> <b>Please provide any additional information below.</b>
All other browsers (Chrome, Firefox, Opera, Safari) return 3.
> 
> The ES spec says that setting a property with no setter should throw a TypeError only in strict mode http://www.ecma-international.org/ecma-262/5.1/#sec-8.7.2. Outside of strict mode it should fail silently. Doing a quick check with the answer from SO http://stackoverflow.com/questions/10480108/is-there-any-way-to-check-if-strict-mode-is-enforced indicates that Phantom is not running in strict mode.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #889](http://code.google.com/p/phantomjs/issues/detail?id=889).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by navels** [comment]
Wow, this bug is a real pain in the neck.  Why is it marked closed?  Still happening with 1.9.2 on OS X.

**Comment by ariya** [comment]
@navels Closed? It's not, scroll to the top and look at the big green "Open" label.

**Comment by navels** [comment]
Ah yeah, thanks . . . saw these Closed tags just above and got confused, thanks :)

**Comment by ariya** [comment]
This is working as expected with PhantomJS 2.0.

**Comment by navels** [comment]
fantastic, thanks.
