### ISSUE TITLE
PhantomJS 1.7 random crash with EventSource

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10887]
_**[bigbou...@gmail.com](http://code.google.com/u/105824566137332740947/) commented:**_
> Which version of PhantomJS are you using?
> 1.7.0
> 
> <b>What steps will reproduce the problem?</b>
I can't reproduce it easily, it's randomly crashing on my CI (running specs with poltergeist)
> here is the tested page: https://gist.github.com/4153433#file_test.html
> The server just accept the connection and send one message. PhantomJS crash every ~2/3 run randomly, but not if run a lot of time sequentially (like a lot of SIGSEGV issue, it looks like it's depending on memory state)
> 
> <b>What is the expected output? What do you see instead?</b>
The expected output is no crash ;)
> 
> <b>Which operating system are you using?</b>
Ubuntu 10.04 x86_64 GNU/Linux 3.2.13-grsec-xxxx-grs-ipv6-64 #1 SMP
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
I use 1.7.0 x86_64 official binary, but I couldn't manage to get a stacktrace, see: https://gist.github.com/4153433#file_stacktrace%20recovery%20attempt
> 
> I'm sorry I can't really help more, if you need any more informations feel free to ask ;).
> I've attached multiple dumps of different runs. The issue should be the same, but just in case it helps.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #887](http://code.google.com/p/phantomjs/issues/detail?id=887).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
