### ISSUE TITLE
Phantomjs unable to load the address! status = fail

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10896]
_**[MikeyMag...@gmail.com](http://code.google.com/u/117182056049085814100/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 
> <b>What steps will reproduce the problem?</b>
> 1.download the js file and run
> 2.can't load the address and the page is empty
> 
> <b>What is the expected output? What do you see instead?</b>
> Expected output: page loaded. It can be loaded in the browser.
> Result: Unable to load the address! status = fail
> 
> <b>Which operating system are you using?</b>
> Windows
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> binary phantomjs:PhantomJS 1.7.0 Windows (Static build)
> 
> <b>Please provide any additional information below.</b>
> result of testing via netlog.js:
> requested: {
>     &quot;headers&quot;: [
>         {
>             &quot;name&quot;: &quot;User-Agent&quot;,
>             &quot;value&quot;: &quot;Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.34 (KH
> TML, like Gecko) PhantomJS/1.7.0 Safari/534.34&quot;
>         },
>         {
>             &quot;name&quot;: &quot;Accept&quot;,
>             &quot;value&quot;: &quot;text/html,application/xhtml+xml,application/xml;q=0.9,_/_;
> q=0.8&quot;
>         }
>     ],
>     &quot;id&quot;: 1,
>     &quot;method&quot;: &quot;GET&quot;,
>     &quot;time&quot;: &quot;2012-12-01T04:40:34.445Z&quot;,
>     &quot;url&quot;: &quot;https://login.a.com/&quot;
> }
> received: {
>     &quot;contentType&quot;: null,
>     &quot;headers&quot;: [],
>     &quot;id&quot;: 1,
>     &quot;redirectURL&quot;: null,
>     &quot;stage&quot;: &quot;end&quot;,
>     &quot;status&quot;: null,
>     &quot;statusText&quot;: null,
>     &quot;time&quot;: &quot;2012-12-01T04:40:34.566Z&quot;,
>     &quot;url&quot;: &quot;https://login.a.com/&quot;
> }
> FAIL to load the address

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #896](http://code.google.com/p/phantomjs/issues/detail?id=896).
:star2: &nbsp; **5** people had starred this issue at the time of migration.

**Comment by enuggetry** [comment]
I got this error running on windows version 2.0.0 with the rasterize.js script.

**Comment by warlock** [comment]
Same problem in version 2.1.1. Using debian 8.7
