### ISSUE TITLE
phantomjs 139 segmentation fault.

### ISSUE THREAD

**Issue by nasy** [ariya/phantomjs#10902]
_**[ignasi.t...@gmail.com](http://code.google.com/u/112178480962125604589/) commented:**_
> phantomjs-1.7.0-linux-x86_64.tar.bz2	 PhantomJS 1.7.0 Linux x86-64
> 
> If I execute the command via command line using ssh it works fine. Just displays this error 
> Fontconfig error: Cannot load default config file
> but creates the image correctly. 
> 
> However when the application executes the command:
> 
>  $output = array();
>  $return_var=0;
>  $command = &quot;./../phantom/phantomjs ../phantom/rasterize.js http://www.nfl.com ../phantom/2.png&quot;;
>  exec($command,$output,$return_var);
> 
> The return var is 139 segmentation fault. 
> Why is this happenig? I contacted with my hosting provider and they say me that its the binary problem. They say:
> 
> 
>  I did notice that the program attempts to open some non-existant files and this may be hard coded in the binary: 
> 
> 13:09:41 open(&quot;/lib64/ld-linux-x86-64.so.2&quot;, O_RDONLY) = 3 
> 13:09:41 open(&quot;/home/vagrant/phantomjs/src/qt/lib/tls/x86_64/libfreetype.so.6&quot;, O_RDONLY) = -1 ENOENT (No such file or directory) 
> 13:09:41 open(&quot;/home/vagrant/phantomjs/src/qt/lib/tls/libfreetype.so.6&quot;, O_RDONLY) = -1 ENOENT (No such file or directory) 
> 13:09:41 open(&quot;/home/vagrant/phantomjs/src/qt/lib/x86_64/libfreetype.so.6&quot;, O_RDONLY) = -1 ENOENT (No such file or directory) 
> 13:09:41 open(&quot;/home/vagrant/phantomjs/src/qt/lib/libfreetype.so.6&quot;, O_RDONLY) = -1 ENOENT (No such file or directory) 
> 13:09:41 open(&quot;/etc/ld.so.cache&quot;, O_RDONLY) = 3 
> 13:09:41 open(&quot;/usr/lib64/libfreetype.so.6&quot;, O_RDONLY) = 3 
> 13:09:41 open(&quot;/usr/lib64/libfontconfig.so.1&quot;, O_RDONLY) = 3 
> 13:09:41 open(&quot;/lib64/libdl.so.2&quot;, O_RDONLY) = 3 
> 13:09:41 open(&quot;/lib64/librt.so.1&quot;, O_RDONLY) = 3 
> 13:09:41 open(&quot;/lib64/libpthread.so.0&quot;, O_RDONLY) = 3 
> 13:09:41 open(&quot;/usr/lib64/libstdc++.so.6&quot;, O_RDONLY) = 3 
> 13:09:41 open(&quot;/lib64/libm.so.6&quot;, O_RDONLY) = 3 
> 13:09:41 open(&quot;/lib64/libgcc_s.so.1&quot;, O_RDONLY) = 3 
> 13:09:41 open(&quot;/lib64/libc.so.6&quot;, O_RDONLY) = 3 
> 13:09:41 open(&quot;/lib64/libexpat.so.1&quot;, O_RDONLY) = 3 
> 13:09:41 open(&quot;/usr/lib/locale/locale-archive&quot;, O_RDONLY) = 3 
> 13:09:41 open(&quot;/etc/fonts/fonts.conf&quot;, O_RDONLY) = 7 
> 13:09:41 open(&quot;/etc/fonts/conf.d&quot;, O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 8 
> 13:09:41 open(&quot;/etc/fonts/conf.d/20-fix-globaladvance.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/20-unhint-small-dejavu-lgc-sans-mono.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/20-unhint-small-dejavu-sans-mono.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/20-unhint-small-vera.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/25-no-bitmap-fedora.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/25-unhint-nonlatin.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/30-metric-aliases.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/30-urw-aliases.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/40-nonlatin.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/45-latin.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/49-sansserif.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/50-user.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/51-local.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/57-dejavu-sans-mono.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/58-dejavu-lgc-sans-mono.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/60-latin.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/65-fonts-persian.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/65-nonlatin.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/69-unifont.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/80-delicious.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/etc/fonts/conf.d/90-synthetic.conf&quot;, O_RDONLY) = 9 
> 13:09:41 open(&quot;/var/cache/fontconfig/3830d5c3ddfd5cd38a049b759396e72e-le64.cache-3&quot;, O_RDONLY) = 7 
> 13:09:41 open(&quot;/var/cache/fontconfig/0251a5afa6ac727a1e32b7d4d4aa7cf0-le64.cache-3&quot;, O_RDONLY) = 7 
> 13:09:41 open(&quot;/var/cache/fontconfig/12b26b760a24f8b4feb03ad48a333a72-le64.cache-3&quot;, O_RDONLY) = 7 
> 13:09:41 open(&quot;/var/cache/fontconfig/b79f3aaa7d385a141ab53ec885cc22a8-le64.cache-3&quot;, O_RDONLY) = 7 
> 13:09:41 open(&quot;/var/cache/fontconfig/87f5e051180a7a75f16eb6fe7dbd3749-le64.cache-3&quot;, O_RDONLY) = 7 
> 
> You will need to contact the developer to help resolve this issue. 
> 
> Please help!

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #902](http://code.google.com/p/phantomjs/issues/detail?id=902).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
