### ISSUE TITLE
Invalid date string phantom.cookies if system locale i not English

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10919]
_**[webmas...@webmaster.ms](http://code.google.com/u/109998186952188761609/) commented:**_

> PhantomJS 1.7, Windows 2008 Server
> 
> If locale is not English, &quot;expires&quot; field in `phantom.cookies` are broken.
> Perhaps `phantom.cookies` should not use locale at all for formating time string
> 
>  {
>   &quot;domain&quot;: &quot;.facebook.com&quot;,
>   &quot;expires&quot;: &quot;__, 14 ___ 2013 03:00:25 GMT&quot;,  // Characters marked '_' are actually \0.
>   &quot;expiry&quot;: 1358132425,
>   &quot;httponly&quot;: false,
>   &quot;name&quot;: &quot;c_user&quot;,
>   &quot;path&quot;: &quot;/&quot;,
>   &quot;secure&quot;: false,
>   &quot;value&quot;: &quot;100004861293884&quot;
>  }
> 
> <b>What steps will reproduce the problem?</b>
> <b>1.</b>
> <b>2.</b>
> <b>3.</b>
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> <b>Which operating system are you using?</b>
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #919](http://code.google.com/p/phantomjs/issues/detail?id=919).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by cleancoderocker** [comment]
Just wanted to ask what is the status on this issue, in the current version of PhantomJS this still happens. Is there any plan to change this behavior?

**Comment by Vitallium** [comment]
@cleancoderocker I think it should be fixed in 2.x.

**Comment by cleancoderocker** [comment]
@Vitallium It isn't. I'm using 2.0 and it still happens.

**Comment by cleancoderocker** [comment]
Does anybody know how PhantomJS does get the locale information? Based on the LANG environment variable?

**Comment by Vitallium** [comment]
@cleancoderocker could you please provide a small example to illustrate the problem?
On POSIX systems, PhantomJS (Qt) uses these environment variables to get the system locale: `LC_ALL `-> `LC_NUMERIC ` -> `LANG`

**Comment by cleancoderocker** [comment]
The problem is the following: we are calling PhantomJS as a child process from Node.js. On systems where the LANG environment variable is set to "en_US.UTF-8" the date string for cookies is correct (e.g. "cookieTest=b29c0580.525eb95c5d0a8; Expires=Wed, 02 Dec 2015 15:09:04 GMT; Domain=.example.com; Path=/"). On systems where the LANG environment variable is set to another locale (e.g. "de_DE.UTF-8") the date string for cookies is incorrect because the date is localized as well (e.g. "cookieTest=3fb6347.525eb4e902505; Expires=Mi., 02 Dez. 2015 14:49:09 GMT; Domain=.example.com; Path=/").

**Comment by cleancoderocker** [comment]
My idea is to pass the LANG environment variable as option to to child_process.spawn() (https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) but this somehow has no effect on PhantomJS.

**Comment by cleancoderocker** [comment]
I just verified, that inside the PhantomJS script that we call all of the mentioned environment variables are available and set to english locale. Anyway the cookie dates are still not formatted in english.

**Comment by Vitallium** [comment]
@cleancoderocker Thanks for the info! I'll have a look into it.

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thanks!
