### ISSUE TITLE
can't connect through socks5 proxy

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10915]
_**[johannes...@gmail.com](http://code.google.com/u/104701932682263849043/) commented:**_
> Which version of PhantomJS are you using? 
> 1.7.0 and 1.8.0
> 
> <b>What steps will reproduce the problem?</b>
phantomjs --proxy-type=socks5 --proxy=127.0.0.1:9050 loadspeed.js http://check.torproject.com
> 
> 
> <b>What is the expected output? What do you see instead?</b>
phantomjs does not connect through socks5 proxies.
> The same happens with some other socks5 proxies I tried
> If I ommit the --proxy-type switch (e.g. use http proxy) 
> it works (not for tor though)
> 
> 
> <b>Which operating system are you using?</b>
Ubuntu 12.04 x86_64
> 
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
1.7.0 - precompiled binary
> 1.8.0 - from source

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #915](http://code.google.com/p/phantomjs/issues/detail?id=915).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by e6nian** [comment]
socks5 not working still on 2.0.1

**Comment by Vitallium** [comment]
SOCKS5 works in PhantomJS 2. It's confirmed.

**Comment by zackw** [comment]
SOCKS5 works for me using current development trunk, and DNS lookups *are* handed to the proxy.  I tested as follows:

* `ssh -v -D 8080 -N remotehost` in one shell window
* start tcpdump in another shell window
* from a development tree, run `./bin/phantomjs --proxy-type=socks5 --proxy=127.0.0.1:8080 examples/rasterize.js http://httpbin.org dummy.png` in yet a third shell window

tcpdump sees only ssh traffic, and ssh spits out a whole bunch of logs with the general pattern

    debug1: Connection to port 8080 forwarding to socks port 0 requested.
    debug1: channel 1: new [dynamic-tcpip]
    debug1: channel 1: free: direct-tcpip: listening port 8080 for httpbin.org port 80, connect from 127.0.0.1 port 15020 to 127.0.0.1 port 8080, nchannels 2

ssh would not know the name of the server if phantomjs were doing its own DNS lookups.

@e6nian If you still have a problem, please explain exactly what you are doing in at least this much detail.

**Comment by timest** [comment]
@e6nian  Pay a attention , if you put `--proxy-type` and `--proxy` after you  `demo.js ` code file , it can't be work , using ` phantomjs --proxy-type=socks5 --proxy=127.0.0.1:8080  demo.js ` instead !

**Comment by phuongnd08** [comment]
Could I instead route DNS request outside of the proxy?

**Comment by Vitallium** [comment]
No response. Closing.
