### ISSUE TITLE
Table header overlaps table content when page breaks

### ISSUE THREAD

**Issue by goddabuzz** [ariya/phantomjs#10927]
_**[buz.i...@gmail.com](http://code.google.com/u/103399255148585376955/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.8.0 development
> 
> <b>What steps will reproduce the problem?</b>
> 1. execute `phantomjs rasterize.js multi_headers.html table_test.pdf &quot;a4&quot;`
> <b>2.</b>
> <b>3.</b>
> 
> <b>What is the expected output? What do you see instead?</b>
> Table headers without pagebreaks and headers not overlapping content.
> 
> <b>Which operating system are you using?</b>
> OSX Mountain Lion &amp; CentOS 6.3
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> Compiled from source
> 
> <b>Please provide any additional information below.</b>
> See attachments
> 
> related to issue 880
> http://code.google.com/p/phantomjs/issues/detail?id=880

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #927](http://code.google.com/p/phantomjs/issues/detail?id=927).
:star2: &nbsp; **7** people had starred this issue at the time of migration.

**Comment by CindyConway** [comment]
Yikes, this is a bear. My solution is far from ideal, but workarounds tend to be that way. Sometimes you just need to make it works.  The only reliable fix I found was to put the table header in the header for the page itself; using pageSize. So basically I:

* created an HTML table that has no <thead> because anything in thead was repeating on each page.
* I did, however, put the headings in the HTML, I just did it right in <table>
* I return a string in the pageSize header that repeated the table header on each page

With a little styling, it looked pretty good.

###Original HTML table
```html
    <table class="grey-border">
          <tr>
            <th class="small p1">Division</th>
            <th class="small p1">Division Contract</th>
            <th class="small p1">Record Category</th>
            <th class="small p1">Record Title/ Description</th>
            <th class="small p1">Document Link</th>
            <th class="small p1">Retention Category</th>
            <th colspan="3" class="center small p1">Retention Period</th>
            <th class="small p1">Remarks</th>
          </tr>
          <tr ng-repeat="record in scheduleCtrl.draft.record | orderBy:['division','category']"  ng-class-even="'grey-background'" ng-class="'grey-border'">
            <td class="p1 grey-border small">{{record.division}}</td>
            <td class="p1 grey-border small">{{record.division_contact}}</td>
            <td class="p1 grey-border small">{{record.category}}</td>
            <td class="p1 grey-border small">{{record.title}}</td>
            <td class="p1 grey-border small">{{record.link}}</td>
            <td class="p1 grey-border small">{{record.retention}}</td>
            <td class="p1 grey-border small">{{record.total}}</td>
            <td class="p1 grey-border small">{{record.on_site}}</td>
            <td class="p1 grey-border small">{{record.off_site}}</td>
            <td class="p1 grey-border small">{{record.remarks}}</td>
          </tr>
      </table>
```
###On the phantomjs side:
```javascript
var paperConfig = {
        format: 'legal',
        orientation: 'landscape',
        margin:'0.75cm',
        header: {
          height: "2cm",
          contents: ph.callback(function(pageNum, numPages) {
            if(pageNum == 1) {return;}

            var style = '<style> \
                          td{border: solid 1px #eee;}\
                          table{table-layout:fixed; \
                                width: 100%; \
                                border:none; \
                                border-collapse:collapse; \
                                font-size:80%; \
                                font-weight:bold; \
                                font-family: "Raleway"; \
                                margin:0px;} \
                          tr{border-right: 1px solid #eee;} \
                          .p1{padding:1em;} \
                          body{margin:0px;} \
                        </style>'
            var header = '<table> \
                      <tr> \
                      <td class="p1">Division</td> \
                      <td class="p1">Division Contract</td> \
                      <td class="p1">Record Category</td> \
                      <td class="p1">Record Title/ Description</td> \
                      <td class="p1">Document Link</td> \
                      <td class="p1">Retention Category</td> \
                      <td class="p1"colspan="3">Retention Period</td> \
                      <td class="p1">Remarks</td> \
                      </tr> \
                      <tr> \
                      <td></td> \
                      <td></td> \
                      <td></td> \
                      <td></td> \
                      <td></td> \
                      <td></td> \
                      <td>Total</td> \
                      <td>On-site</td> \
                      <td>Off-site</td> \
                      <td></td> \
                      </tr>\
                      </table>'

            return style+header;
          })
        }
      };

      page.set('paperSize', paperConfig, function() {
        var fileName = 'test_' +  Math.floor((Math.random() * 100) + 1) + '.pdf';
        page.render(fileName, function() {
          page.close();
          ph.exit();
        });
      });
```

**Comment by brycepj** [comment]
I was having this issue, and just got rid of `thead` and moved its content into a new row in `tbody`. You can still style it differently than other tabular data by hooking into `tr:first-of-type` and `th`'s. May not work for everyone who stumbles onto this page, but it worked for me.

**Comment by agairing** [comment]
an additional element at the top of the page - before the table - did solve my issue.

**Comment by ChaseJ** [comment]
I solved the issue by adding the following class to my table.

```
.table-fix {
    margin-left: 1px;
}
```

**Comment by Levino** [comment]
I "fixed" this by removing the font size css attribute for my <p>'s.

**Comment by vjchem** [comment]
In case it helps anyone, I just "fixed" an occurrence of this by specifying a width and min-height on the first column. We had one table where this never happened and one where it always happened, was able to narrow it down to that. We're using bootstrap, so in our case it was adding class `col-sm-1` to the first `th` in the header.

**Comment by giaosudau** [comment]
@chrispbailey thanks.
It works for me too.
But tfoot has the same problem so I do 
thead, tfoot {display: table-row-group;}

**Comment by b-malone** [comment]
Thanks @brycepj -- that fix of switching out the table-header worked well for me, too.

**Comment by jasonb-vbt** [comment]
@giaosudau's `thead, tfoot {display: table-row-group;}` worked for me, too. Thanks!

**Comment by walter-psjr** [comment]
I had the same problem and solved by replacing the blanks by & nbsp;

**Comment by johnhyde** [comment]
I had the same problem until I added `<br/>` into `thead` after my actual headings:
```html
<table>
    <thead>
        <tr>
            <th>Heading 1</th><th>Heading 2</th><th>Etc.</th>
        </tr>
        <br/> <!-- Fixes everything somehow -->
    </thead>
    <tbody>
        <!--rows-->
    </tbody>
</table>
```

**Comment by RobMaple** [comment]
For me, removing `line-height` from `body` fixed it.
