### ISSUE TITLE
Ensure a consistent 72 dpi for Windows headless rendering

### ISSUE THREAD

**Issue by JamesMGreene** [ariya/phantomjs#10934]
_**[james.m....@gmail.com](http://code.google.com/u/101963681963300214110/) commented:**_
> See details in Issue #659. Apparently Windows is more unpredictable in its resolution defaults so this will take extra efforts to nail down.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #934](http://code.google.com/p/phantomjs/issues/detail?id=934).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
This issue is fairly old and there hasn't been much activity on it.
