### ISSUE TITLE
PhantomJS does not like GZIP compression in some scenarios

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10930]
_**[sahab.ya...@gmail.com](http://code.google.com/u/108797383767824179514/) commented:**_

> Which version of PhantomJS are you using? 1.7.0 for Windows stock from the web-page.
> 
> <b>What steps will reproduce the problem?</b>
> Run PhantomJS against a web server with a slightly malformed GZIP response stream (attached a sample VS 2010 project hooking into IIS Express 8.0 that demonstrates this problem) and watch PhantomJS fall over itself every now and then. I think this is because of two distinct WebKit related bugs:
> 
> 1) https://bugs.webkit.org/show_bug.cgi?id=58727
> 2) https://bugreports.qt-project.org/browse/QTBUG-16022
> 
> But both of them seem to be fixed, so not sure if they are truly related.
> 
> I've attached a Visual Studio project which demonstrates the problem. I've configured it such that the server (IIS Express must be installed as well) sends back GZIPped content if the &quot;X-Test-Runner&quot; request header is _not_ present and send back GZIPped content if the &quot;X-Test-Runner&quot; request header _is_ present. When the content is GZIPed, then PhantomJS will _sometimes_ throw an &quot;$ is undefined&quot; exception but sometimes work correctly. When the content is _not_ GZIPed, then PhantomJS will work correctly.
> 
> Sorry if this bug report isn't exactly the clearest, I've had a hell of a time tracking down the problem and if you need any further details please do let me know.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #930](http://code.google.com/p/phantomjs/issues/detail?id=930).
:star2: &nbsp; **5** people had starred this issue at the time of migration.

**Comment by adrianheine** [comment]
@paulyoung I'm using the following (took it from localnerve/html-snapshots@f99ddc59545ede1e8744ba0cad5c05c0a0ccbdab):
```
page.customHeaders = {
  "Accept-Encoding": "identity"
};
```

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://risk-management979.tk/arm.php?j2s8>

 

klaus@hebsgaard.dk
