### ISSUE TITLE
Crash address: 0xffffffffffffffc8

### ISSUE THREAD

**Issue by DelvarWorld** [ariya/phantomjs#10931]
_**[delvarwo...@gmail.com](http://code.google.com/u/112611400229986693375/) commented:**_
> phantomjs --version
> 1.7.0
> 
> Crash dump attached

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #931](http://code.google.com/p/phantomjs/issues/detail?id=931).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
