### ISSUE TITLE
Letter spacing in the rendered PDF

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10944]
_**[pr8...@gmail.com](http://code.google.com/u/106941535087310883738/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 
> 1.8.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. Capturing a webpage which has &quot;Trebuchet MS&quot; font face.
> 
> <b>What is the expected output? What do you see instead?</b>
> 1. Properly spaced.
> 
> <b>Which operating system are you using?</b>
> Windows 7 HP 64bit
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> Binary
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #944](http://code.google.com/p/phantomjs/issues/detail?id=944).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by mapodev** [comment]
The solution here https://github.com/wkhtmltopdf/wkhtmltopdf/issues/45 solved the problem. So you need to update the .conf file and change the update rate from server. I used CentOS 6 and it worked.
