### ISSUE TITLE
onConsoleMessage handler get undefined lineNum and SourceId

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10957]
_**[ipqu...@googlemail.com](http://code.google.com/u/118013346855725537692/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.8.0
> 
> <b>What steps will reproduce the problem?</b>
1. Write a onConsoleMessage handler in your phantom script, and have it output lineNum and SourceId
> 2. Load a webpage that calls console.log
> 3. Observe the undefined values for those arguments
> 
> <b>What is the expected output? What do you see instead?</b>
Expect LineNum and SourceId; observe instead undefined.
> 
> <b>Which operating system are you using?</b>
Debian Squeeze
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Binary
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #957](http://code.google.com/p/phantomjs/issues/detail?id=957).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by pyriand3r** [comment]
self compiled version 1.9.8 still having this.

**Comment by Vitallium** [comment]
Fixed in 2.1.1.

**Comment by hjain-spcg** [comment]
It does not appear to be resolved
$ phantomjs --version
2.1.1

**script**
page.onConsoleMessage = function(msg, lineNum, sourceId) {
	console.log('onConsoleMessage: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
};

**Result:** 
onConsoleMessage: 4 (from line # in "")

**Comment by jhard** [comment]
+1 this is not fixed, and is very annoying.

**Comment by ashvaibhav** [comment]
+1
This is not resolved on:
$ phantomjs --version
2.1.1

**Comment by thomasneirynck** [comment]
+1

**Comment by wiverson** [comment]
+1, still seeing in 2.1.1
