### ISSUE TITLE
Element removing is failing.

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10970]
_**[johannes...@softgames.de](http://code.google.com/u/107604769934475163439/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.8.1
> 
> <b>What steps will reproduce the problem?</b>
> I'm using the konacha gem for testing js in rails via mocha. (https://github.com/jfirebaugh/konacha)
> There are some tests running, but each test hitting this line is failing in pjs 1.8.1
> 
> element = document.getElementById(&quot;softgames-payment&quot;);
> element.parentNode.removeChild(element);
> 
> I checked also, whether the element exists, but this didn't solve the problem. I couldn't extract the problem into not running example code.
> 
> <b>What is the expected output? What do you see instead?</b>
> Using version 1.7 of phantomjs all tests were passing. With version 1.8.1 (and 1.8) tests are crashing now.
> 
> <b>Which operating system are you using?</b>
> OS X 10.8.2
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> mac homebrew binary

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #970](http://code.google.com/p/phantomjs/issues/detail?id=970).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by zachlysobey** [comment]
I'm experiencing a similar issue trying to write a test (phantomJS 1.9.7). Seems that there is no `remove` function on `Element.prototype`. It is present in Chrome & Firefox, etc.. 

```js
phantomjs> typeof Element.prototype.remove
"undefined"
```

Interestingly `removeChild` does seem to exist, though I haven't explicitly used it in my tests.

```js
phantomjs> typeof Element.prototype.removeChild
"function"
```

**Comment by IngwiePhoenix** [comment]
Yup.

```javascript
var div = document.createElement("div");
if(!(div instanceof HTMLDivElement)) console.error("Fail.");
document.body.appendChild(div);
div.remove(); // Fails
```

OS X 10.11.1, pjs 1.9.8 though `phantomjs-npm`.

Pretty annoying, to be honest. This is rather natural but...appearently, not in PhantomJS. I need to find an alternative, now.

**Comment by xonixx** [comment]
This one affected me too. I solved like so
```javascript
var _rmCemetery = document.createElement('remove');
function removeWrap(e) {
    if (e.remove)
        e.remove();
    else
        _rmCemetery.appendChild(e)
}
```
