### ISSUE TITLE
Create a non-blocking `system.stdin` implementation

### ISSUE THREAD

**Issue by JamesMGreene** [ariya/phantomjs#10980]
_**[james.m....@gmail.com](http://code.google.com/u/101963681963300214110/) commented:**_

> A person by the GitHub username of @burlito brought up that he/she would like to have a non-blocking `stdin` implementation available, which I agree makes sense.
> 
> @burlito's comment:
> https://github.com/ariya/phantomjs/commit/f6c87221a775bb6dc3d5102951b4f333d714af8b#commitcomment-2423252
> 
> A non-blocking/asynchronous `stdin` should probably be the default but we can consider providing both implementations if there is value (more than just convenience) in maintaining the blocking/synchronous version.
> 
> This would also align with how Node.js `stdin` works as well: http://nodejs.org/api/process.html#process_process_stdin
> 
> Some implementation notes:
> - http://stackoverflow.com/questions/1271784/using-qtextstream-to-read-stdin-in-a-non-blocking-fashion
> - http://stackoverflow.com/questions/6878507/using-qsocketnotifier-to-select-on-a-char-device/7389622#7389622
> - http://stackoverflow.com/questions/9741259/reading-asynchronously-from-stdin-in-qt (provides alternative but likely less good implementation ideas)
> 
> Also should include some example scripts and, if possible, tests.
> 
> Thanks!

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #980](http://code.google.com/p/phantomjs/issues/detail?id=980).
:star2: &nbsp; **4** people had starred this issue at the time of migration.

**Comment by sotownsend** [comment]
I have an asynchronous implementation of `stdin` in my project. It relies on the server and multiplexing the $stdin into a socket.  The `setInterval` is used as any exceptions thrown on the server's context of execution do not call `onError`, so I defer the exceptions into a queue which *does* execute on a context that does properly calls `onError`.

https://github.com/sotownsend/BooJS/blob/6a8ec85d1979a8c5a4c2e38ad3fb6ba2cb43b6c8/lib/boojs.rb

**Comment by zackw** [comment]
This seems closely related to #13970 - but that's about the child_process API, whereas if I understand correctly this is about phantomjs's own stdin?

**Comment by DawidaWina** [comment]
How far are you with solution to this problem? As everyone here mentioned, there should be any solution asap, because it makes a lot problems not only with communication, but even events listeners.
