### ISSUE TITLE
unicode chars not visible in the rendered page

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10988]
_**[lbene...@googlemail.com](http://code.google.com/u/115414621070888235336/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.8.1
> 
> <b>What steps will reproduce the problem?</b>
> 1. phantomjs --output-encoding=utf8 examples/rasterize.js http://www.wikidata.org/wiki/Q560 helium.png
> 2. look at the picture
> 3. be surprised about the missing unicode characters
> 
> <b>What is the expected output? What do you see instead?</b>
> in the line with code=bn i expect to see: &quot;বাংলা bn  হিলিয়াম&quot;
> 
> <b>Which operating system are you using?</b>
> ubuntu precise
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> binary
> 
> <b>Please provide any additional information below.</b>
> 
> here is a screenshot, made from chrome: http://upload.wikimedia.org/wikipedia/commons/7/75/Wikidata_1.PNG
> 
> the rendering with phantomjs
> http://upload.wikimedia.org/wikipedia/commons/3/39/Wikidata_2.png

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #988](http://code.google.com/p/phantomjs/issues/detail?id=988).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by adborden** [comment]
If I install the correct font, it works for me. This is a cjk font.

    $ apt-get install ttf-wqy-microhei
