### ISSUE TITLE
IndexedDB support

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10992]
_**[rektide@gmail.com](http://code.google.com/u/rektide/) commented:**_

> Greetings. IndexedDB support would be stellar. Thanks much, keep up the great work.
> 
> Historical note, there was a forum post from June 2012 on this, and the reply was to create a ticket. I have not found that ticket, and am creating it thusly. Thanks again.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #992](http://code.google.com/p/phantomjs/issues/detail?id=992).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by schmod** [comment]
Any progress on this?

**Comment by kristofdegrave** [comment]
I'm currently writting my own indexeddbmock because I wanted to use PhantomJS for automating my tests. Currently I'm only able to mock the structure, but I'm working on the data now. If you are interested have a look at https://github.com/kristofdegrave/indexedDBmock

**Comment by cherrydev** [comment]
@JamesMGreene, I'm a little confused about the mention of waiting on WebKit, since as far as I can see, WebKit supports indexeddb.

**Comment by cherrydev** [comment]
Looks like indexeddb works now in phantomjs 2.0 and this can be closed.  I haven't tested it extensively, but it looks like as long as you set local-storage-path and local-storage-quota you can create, insert and query data properly.
