### ISSUE TITLE
Phantomjs 1.8.0 Crash

### ISSUE THREAD

**Issue by Rebolon** [ariya/phantomjs#11005]
_**[richard....@gmail.com](http://code.google.com/u/105799783715052437755/) commented:**_
> Which version of PhantomJS are you using? 1.8.0
> 
> <b>What steps will reproduce the problem?</b>
1. Ran some casper js tests
> 
> Sometimes, phantomjs will crash but mot of the time it won't. It seems to be randomly so it 's not easy to understand on my side.
> 
> Which operating system are you using? Linux 3.2.0-27-generic #43-Ubuntu
> 
> 
> Did you use binary PhantomJS or did you compile it from source? binary PhantomJs from your googlecode repository
> 
> <b>Please provide any additional information below.</b>
Here are info from dump file (even if it seems to be useless for you) :
> Operating system: Linux
>                   0.0.0 Linux 3.2.0-27-generic #43-Ubuntu SMP Fri Jul 6 14:25:57 UTC 2012 x86_64
> CPU: amd64
>      family 16 model 8 stepping 1
>      4 CPUs
> 
> Crash reason:  SIGSEGV
> Crash address: 0x38
> 
> Thread 0 (crashed)
>  0  0x469968
>     rbx = 0x00007fff35a46380   r12 = 0x00007fff35a46380
>     r13 = 0x0000000002fe6450   r14 = 0x0000000002d04d4c
>     r15 = 0x0000000002fe6450   rip = 0x0000000000469968
>     rsp = 0x00007fff35a462f0   rbp = 0x0000000003d1a420
>     Found by: given as instruction pointer in context
>  1  libc-2.15.so + 0x82fb4
>     rip = 0x00007fc00605ffb5   rsp = 0x00007fff35a46330
>     Found by: stack scanning
> 
> Thread 1
>  0  libc-2.15.so + 0xbf83d
>     rbx = 0x00007fc005254cf0   r12 = 0x0000000000000001
>     r13 = 0x00000000000000ff   r14 = 0x0000000000000001
>     r15 = 0x00000000026bf3c0   rip = 0x00007fc00609c83d
>     rsp = 0x00007fc005254c40   rbp = 0x00000000ffffffff
>     Found by: given as instruction pointer in context
>  1  libc-2.15.so + 0xbf6db
>     rip = 0x00007fc00609c6dc   rsp = 0x00007fc005254c50
>     Found by: stack scanning
>  2  libc-2.15.so + 0x109f7
>     rip = 0x00007fc005fed9f8   rsp = 0x00007fc005254c70
>     Found by: stack scanning
>  3  ld-2.15.so + 0xa522
>     rip = 0x00007fc0076c2523   rsp = 0x00007fc005254cc8
>     Found by: stack scanning
>  4  libc-2.15.so + 0xbf848
>     rip = 0x00007fc00609c849   rsp = 0x00007fc005254cd8
>     Found by: stack scanning
>  5  libpthread-2.15.so + 0xfcaf
>     rip = 0x00007fc006bbfcb0   rsp = 0x00007fc005254ce8
>     Found by: stack scanning
>  6  libpthread-2.15.so + 0xb103
>     rip = 0x00007fc006bbb104   rsp = 0x00007fc005254d90
>     Found by: stack scanning
>  7  libc-2.15.so + 0xe54f
>     rip = 0x00007fc005feb550   rsp = 0x00007fc005254d98
>     Found by: stack scanning
>  8  libpthread-2.15.so + 0x1187f
>     rip = 0x00007fc006bc1880   rsp = 0x00007fc005254dc0
>     Found by: stack scanning
>  9  ld-2.15.so + 0x15234
>     rip = 0x00007fc0076cd235   rsp = 0x00007fc005254dd0
>     Found by: stack scanning
> 10  libpthread-2.15.so + 0xe9f9
>     rip = 0x00007fc006bbe9fa   rsp = 0x00007fc005254de0
>     Found by: stack scanning
> 11  libpthread-2.15.so + 0xbe17
>     rip = 0x00007fc006bbbe18   rsp = 0x00007fc005254df0
>     Found by: stack scanning
> 12  libc-2.15.so + 0x977f
>     rip = 0x00007fc005fe6780   rsp = 0x00007fc005254e28
>     Found by: stack scanning
> 13  ld-2.15.so + 0x15234
>     rip = 0x00007fc0076cd235   rsp = 0x00007fc005254e60
>     Found by: stack scanning
> 14  libpthread-2.15.so + 0x1187f
>     rip = 0x00007fc006bc1880   rsp = 0x00007fc005254e80
>     Found by: stack scanning
> 15  libpthread-2.15.so + 0x7e99
>     rip = 0x00007fc006bb7e9a   rsp = 0x00007fc005254eb0
>     Found by: stack scanning
> 16  libpthread-2.15.so + 0x1187f
>     rip = 0x00007fc006bc1880   rsp = 0x00007fc005254f58
>     Found by: stack scanning
> 17  libc-2.15.so + 0xf3cbc
>     rip = 0x00007fc0060d0cbd   rsp = 0x00007fc005254fc0
>     Found by: stack scanning
> 
> Thread 2
>  0  libc-2.15.so + 0xed023
>     rbx = 0x00007fc000000d30   r12 = 0x0000000000000000
>     r13 = 0x00007fc000000a98   r14 = 0x0000000000000008
>     r15 = 0x00007fc000000a98   rip = 0x00007fc0060ca023
>     rsp = 0x00007fc00493bb90   rbp = 0x00007fc000000fc8
>     Found by: given as instruction pointer in context
>  1  librt-2.15.so + 0x415c
>     rip = 0x00007fc006dd115d   rsp = 0x00007fc00493bbb0
>     Found by: stack scanning
>  2  libpthread-2.15.so + 0x2d2f
>     rip = 0x00007fc006bb2d30   rsp = 0x00007fc00493bbf8
>     Found by: stack scanning
>  3  librt-2.15.so + 0x415c
>     rip = 0x00007fc006dd115d   rsp = 0x00007fc00493bc70
>     Found by: stack scanning
> 
> Thread 3
>  0  libpthread-2.15.so + 0xbd84
>     rbx = 0x00000000031c7780   r12 = 0xffffffffffffffff
>     r13 = 0x004189374bc6a7ef   r14 = 0x0000000000000000
>     r15 = 0x00000000031c77a8   rip = 0x00007fc006bbbd84
>     rsp = 0x00007fbfbea12d50   rbp = 0x00000000031c7710
>     Found by: given as instruction pointer in context
>  1  linux-gate.so + 0xa1a
>     rip = 0x00007fff35b38a1b   rsp = 0x00007fbfbea12dc0
>     Found by: stack scanning
>  2  libpthread-2.15.so + 0x7e99
>     rip = 0x00007fc006bb7e9a   rsp = 0x00007fbfbea12eb0
>     Found by: stack scanning
> 
> Thread 4
>  0  libc-2.15.so + 0xed023
>     rbx = 0x00007fbfb0000d30   r12 = 0x00007fbfbe171d50
>     r13 = 0x00007fbfb0000a98   r14 = 0x000000000000005e
>     r15 = 0x00000000004b3fa2   rip = 0x00007fc0060ca023
>     rsp = 0x00007fbfbe171b90   rbp = 0x00007fbfb0000fc8
>     Found by: given as instruction pointer in context
>  1  librt-2.15.so + 0x415c
>     rip = 0x00007fc006dd115d   rsp = 0x00007fbfbe171bb0
>     Found by: stack scanning
>  2  librt-2.15.so + 0x415c
>     rip = 0x00007fc006dd115d   rsp = 0x00007fbfbe171c70
>     Found by: stack scanning
> 
> Thread 5
>  0  libpthread-2.15.so + 0xc0fe
>     rbx = 0x00007fbfb00053a0   r12 = 0x000000000000005d
>     r13 = 0x00007fbfb7ffeda0   r14 = 0xffffffffffffff92
>     r15 = 0x0000000000000000   rip = 0x00007fc006bbc0fe
>     rsp = 0x00007fbfb7ffed20   rbp = 0x00007fbfb0005348
>     Found by: given as instruction pointer in context
> 
> Thread 6
>  0  libpthread-2.15.so + 0xc0fe
>     rbx = 0x00007fbfb00053a0   r12 = 0x000000000000005f
>     r13 = 0x00007fbfbd32eda0   r14 = 0xffffffffffffff92
>     r15 = 0x0000000000000000   rip = 0x00007fc006bbc0fe
>     rsp = 0x00007fbfbd32ed20   rbp = 0x00007fbfb0005348
>     Found by: given as instruction pointer in context
> 
> Thread 7
>  0  libpthread-2.15.so + 0xc0fe
>     rbx = 0x00007fbfb00053a0   r12 = 0x0000000000000061
>     r13 = 0x00007fbfbcb2dda0   r14 = 0xffffffffffffff92
>     r15 = 0x0000000000000000   rip = 0x00007fc006bbc0fe
>     rsp = 0x00007fbfbcb2dd20   rbp = 0x00007fbfb0005348
>     Found by: given as instruction pointer in context
> 
> Thread 8
>  0  libpthread-2.15.so + 0xc0fe
>     rbx = 0x00007fbfb00053a0   r12 = 0x000000000000005b
>     r13 = 0x00007fbfb77fdda0   r14 = 0xffffffffffffff92
>     r15 = 0x0000000000000000   rip = 0x00007fc006bbc0fe
>     rsp = 0x00007fbfb77fdd20   rbp = 0x00007fbfb0005348
>     Found by: given as instruction pointer in context
> 
> Thread 9
>  0  libpthread-2.15.so + 0xc0fe
>     rbx = 0x00007fbfb00053a0   r12 = 0x0000000000000063
>     r13 = 0x00007fbfb6925da0   r14 = 0xffffffffffffff92
>     r15 = 0x0000000000000000   rip = 0x00007fc006bbc0fe
>     rsp = 0x00007fbfb6925d20   rbp = 0x00007fbfb0005348
>     Found by: given as instruction pointer in context
> 
> Loaded modules:
> 0x7fbfb4355000 - 0x7fbfb437cfff  LiberationSans-Italic.ttf  ???  (main)
> 0x7fbfb5999000 - 0x7fbfb59b3fff  LiberationMono-Regular.ttf  ???
> 0x7fbfb60f8000 - 0x7fbfb6109fff  n019004l.pfb  ???
> 0x7fbfbc05e000 - 0x7fbfbc07ffff  LiberationSans-Regular.ttf  ???
> 0x7fbfbc080000 - 0x7fbfbc0a1fff  LiberationSans-Bold.ttf  ???
> 0x7fbfbc0a2000 - 0x7fbfbc146fff  DejaVuSans-Bold.ttf  ???
> 0x7fbfbc147000 - 0x7fbfbc1f6fff  DejaVuSans.ttf  ???
> 0x7fbfbc2b5000 - 0x7fbfbc2c8fff  n019003l.pfb  ???
> 0x7fbfbd330000 - 0x7fbfbd537fff  libnss_dns-2.15.so  ???
> 0x7fbfbd549000 - 0x7fbfbd755fff  libnss_files-2.15.so  ???
> 0x7fbfbd756000 - 0x7fbfbd96ffff  libresolv-2.15.so  ???
> 0x7fc005266000 - 0x7fc0054c0fff  libssl.so.1.0.0  ???
> 0x7fc0054c2000 - 0x7fc005885fff  libcrypto.so.1.0.0  ???
> 0x7fc005894000 - 0x7fc00589afff  gconv-modules.cache  ???
> 0x7fc00589b000 - 0x7fc0058bffff  libc.mo  ???
> 0x7fc0058c0000 - 0x7fc0058c8fff  945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-3  ???
> 0x7fc0058c9000 - 0x7fc005b96fff  locale-archive  ???
> 0x7fc005b9c000 - 0x7fc005dc5fff  libexpat.so.1.5.2  ???
> 0x7fc005dc6000 - 0x7fc005fdcfff  libz.so.1.2.3.4  ???
> 0x7fc005fdd000 - 0x7fc006396fff  libc-2.15.so  ???
> 0x7fc00639d000 - 0x7fc0065b2fff  libgcc_s.so.1  ???
> 0x7fc0065b3000 - 0x7fc0068aefff  libm-2.15.so  ???
> 0x7fc0068af000 - 0x7fc006b99fff  libstdc++.so.6.0.16  ???
> 0x7fc006bb0000 - 0x7fc006dc8fff  libpthread-2.15.so  ???
> 0x7fc006dcd000 - 0x7fc006fd4fff  librt-2.15.so  ???
> 0x7fc006fd5000 - 0x7fc0071d8fff  libdl-2.15.so  ???
> 0x7fc0071da000 - 0x7fc00740ffff  libfontconfig.so.1.4.4  ???
> 0x7fc007410000 - 0x7fc0076abfff  libfreetype.so.6.8.0  ???
> 0x7fc0076ad000 - 0x7fc0076b0fff  6d41288fd70b0be22e8c3a91e032eec0-le64.cache-3  ???
> 0x7fc0076b1000 - 0x7fc0076b5fff  3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-3  ???
> 0x7fc0076b8000 - 0x7fc0076d9fff  ld-2.15.so  ???
> 0x7fff35b38000 - 0x7fff35b38fff  linux-gate.so  ???

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1005](http://code.google.com/p/phantomjs/issues/detail?id=1005).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
