### ISSUE TITLE
Segmentation Fault in PhantomJS 1.8.1

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#11003]
_**[andi.sus...@sofialys.com](http://code.google.com/u/104865424750278735626/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
phantomjs-1.8.1-linux-x86_64
> 
> <b>What steps will reproduce the problem?</b>
1. Running the test will resulted in segmentation fault. Previously, sometimes it worked and sometimes it didn't. However, the crashing has become more and more frequent
> <b>2.</b>
<b>3.</b>

> <b>What is the expected output? What do you see instead?</b>
Expected to see the test result along with the time.
> This is the output instead:
> ----------------------------------------------------------------------------------
> PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://code.google.com/p/phantomjs/issues/entry with the crash dump file attached: /tmp/5429afef-be99-a011-54934923-11e3d6e6.dmp
> test: line 19:  2592 Segmentation fault      (core dumped) phantomjs /app/assets/javascripts/tests/runner/runner.js $1 $2 $3
> 
> <b>Which operating system are you using?</b>
Ubuntu Linux 64-bit
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Using binary PhantomJS
> 
> <b>Please provide any additional information below.</b>
There is no additional information yet. Will post one as soon as there is a respond or resolution, whichever comes first.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1003](http://code.google.com/p/phantomjs/issues/detail?id=1003).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Closing this. Track the progress of ES2015 here https://github.com/ariya/phantomjs/issues/14506

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
