### ISSUE TITLE
PhantomJS 1.8.1 crashes upon attempting to open a webpage

### ISSUE THREAD

**Issue by Scyntherei** [ariya/phantomjs#11027]
_**[Scynthe...@gmail.com](http://code.google.com/u/112138986776564978642/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.8.1
> 
> <b>What steps will reproduce the problem?</b>
1. cd to the phantom binary
> 2. phantomjs --proxy-type=none --ignore-ssl-errors=true ../examples/loadspeed.js http://walmart.com/
> 3. crash dump
> 
> <b>What is the expected output? What do you see instead?</b>
The page to open and a loadspeed to be given. Instead, a crash dump is created.
> 
> <b>Which operating system are you using?</b>
Mac OSX 10.7.5
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Binary
> 
> <b>Please provide any additional information below.</b>
We upgraded from phantom 1.7 to 1.8.1 and noticed that out of thousands of runs and about 100 different webpages, some crash when attempting to open the webpage.
> 1.7 would open any page fine, but 1.8 wants to be picky.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1027](http://code.google.com/p/phantomjs/issues/detail?id=1027).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Outdated.
