### ISSUE TITLE
NTLM auth support

### ISSUE THREAD

**Issue by arthurva** [ariya/phantomjs#11037]
_**[Arthu...@gmail.com](http://code.google.com/u/110509968427207403392/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.8
> 
> <b>Please provide any additional information below.</b>
> There is currently no support for NTLM authentication. 
> (NTLM is common in the Enterprise field and this is a must in my project)
> 
> also see https://groups.google.com/forum/#!topic/phantomjs/EoZ10-9puMk
> 
> thanks.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1037](http://code.google.com/p/phantomjs/issues/detail?id=1037).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by mkliu** [comment]
just tried https://github.com/sdesalas/trifleJS and windows auth works since it's using IE.

**Comment by rajeshpaddy** [comment]
I'm using Phantomjs v2.0. Is there any example of passing username, password and domain for the NTLM authentication. So far, I'm not able to get a screen capture working for NTLM using phantomjs.

**Comment by clockwisemusic** [comment]
Hi @rajeshpaddy , just use: "http://username:password@localhost/myapp" as the URL for your request. Worked for me.

**Comment by darkterra** [comment]
Hi, I have the same problem that @pkbharigopal :

In my enterprise I am behind a firewall with NTLM/Kerberos authentication configured. None of the options --proxy-auth, --proxy worked for me. I am using PhantomJS 2.0.

**Comment by rajeshpaddy** [comment]
Checkout triflejs. It solved my authentication problem.

**Comment by darkterra** [comment]
Sorry @rajeshpaddy,

I do not understand if I have to use the "triflejs" project or watch the piece of code to solve the connection problem

**Comment by darkterra** [comment]
Hi Everyone,

Nobody knows answer to my problem (or question ) ?

**Comment by vaishali33** [comment]
You can manipulate request header to send Kerberos token to hit Kerberized web pages from PhantomJS. Using below -
page.customHeaders = {"Authorization": "Negotiate " + [token]};

Also I had to change cli args to --ignore-ssl-error = true to get it working.

Use https://docs.oracle.com/javase/7/docs/api/org/ietf/jgss/GSSManager.html and https://docs.oracle.com/javase/7/docs/api/org/ietf/jgss/GSSContext.html to generate Kerberos token.

**Comment by itslittlejohn** [comment]
I've gotten phantomjs to work with ntlm authentication using the cntlm proxy. The method that I used is detailed below if that would be helpful to anyone else encountering this issue. http://stackoverflow.com/questions/31209449/cntlm-proxy-with-phantomjs

**Comment by rogeriopradoj** [comment]
@itslittlejohn :+1: Thanks for sharing!

**Comment by SgtPooki** [comment]
This is more than possible to implement kerberos authentication in phantomJS using https://github.com/christkv/kerberos.

And I haven't tried it, but @vaishali33's solution looks like the only straightforward one.
