### ISSUE TITLE
frameUrl returns nothing

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#11035]
_**[descarta...@gmail.com](http://code.google.com/u/113790823219340300996/) commented:**_
> was using a compiled 1.7
> then compiled the latest trunk (e6ae4cca6dfc2819ea99c5575bcaf94eec6686cb) 1.9 (development)
> and ultimately used the 1.8 official binary
> 
> <b>What steps will reproduce the problem?</b>
1. read page.frameUrl
> 
> <b>What is the expected output? What do you see instead?</b>
i expect the frame's Url.
> I get an empty string
> 
> <b>Which operating system are you using?</b>
linux
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Both.
> 
> <b>Please provide any additional information below.</b>
&quot;&quot;&quot;
> page.switchToMainFrame()
> frames = page.framesCount;
> for (var i=0; i &lt; frames; i++){
>   page.switchToFrame(i);
>   console.log('A'+page.frameUrl);
>   console.log('B'+page.evaluate(function() { return window.location.href; }));
> }
> &quot;&quot;&quot;
> 
> this will result in
> A
> Bhttp://localhost/test1.html
> A
> Bhttp://localhost/test2.html

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1035](http://code.google.com/p/phantomjs/issues/detail?id=1035).
:star2: &nbsp; **1** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
Fixed by #12233, mostly.  (There may still be a problem with HTML documents that use `<base href>`.)
