### ISSUE TITLE
Does not respect margin: 0 auto; centering on buttons

### ISSUE THREAD

**Issue by benogle** [ariya/phantomjs#11030]
_**[ogle....@gmail.com](http://code.google.com/u/100753951203012649968/) commented:**_

> Which version of PhantomJS are you using? 1.8.1 from brew
> 
> <b>What steps will reproduce the problem?</b>
> 1. Center a &lt;button&gt; in a container with display:block; margin: 0 auto;
> 2. Screen Capture with phantom. 
> 3. Notice the button is left aligned
> 
> Example: http://jsfiddle.net/HsmTw/
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> Expected button to be centered. Button is left aligned.
> 
> <b>Which operating system are you using?</b>
> 
> OSX 10.8
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> From Homebrew
> 
> <b>Please provide any additional information below.</b>
> 
> Attached are images of the issue. Centered button is in chrome. Left aligned is same page in phantom. Safari 6, Firefox (latest) and Chrome all display the button centered.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1030](http://code.google.com/p/phantomjs/issues/detail?id=1030).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by Bechrissed** [comment]
Can i bump this? Issue is still active and i'm experiencing the same problem

**Comment by arult** [comment]
Any improvement or work around for this issue?
