### ISSUE TITLE
phantomjs 1.8.1 crash

### ISSUE THREAD

**Issue by nuc** [ariya/phantomjs#11039]
_**[nucho...@gmail.com](http://code.google.com/u/114950714740839778604/) commented:**_
> Version 1.8.1
> 
> <b>What steps will reproduce the problem?</b>
accessing a js heavy page (backbone app)
> 
> <b>Which operating system are you using?</b>
Linux 3.2.0-36-generic #57-Ubuntu
> 
> Converted stacktrace included!

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1039](http://code.google.com/p/phantomjs/issues/detail?id=1039).
:star2: &nbsp; **1** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Outdated.
