### ISSUE TITLE
Page breaks occur in table rows with rowspan > 1

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#11038]
_**[watsonj...@gmail.com](http://code.google.com/u/103744454948904221804/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.8.1
> 
> <b>What steps will reproduce the problem?</b>
> 1. Run the attached test cases with `phantomjs examples/rasterize.js bigtable.html bigtable.pdf A4`
> 2. View the resulting PDF file.
> 
> <b>What is the expected output? What do you see instead?</b>
> Table should not cut a row in half if one dosen't fill remaining space on a page.
> 
> Table will cut a row in half, making it unreadable because one half is on the bleeding edge of a page and the remainder is printer on the top of the next page.
> 
> <b>Which operating system are you using?</b>
> Windows 7
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> binary
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1038](http://code.google.com/p/phantomjs/issues/detail?id=1038).
:star2: &nbsp; **1** people had starred this issue at the time of migration.

**Comment by eliavmaman** [comment]
looking for solution please .... have the same problem .

**Comment by alne4294** [comment]
Anyone find a workaround?
