### ISSUE TITLE
Crash: pure virtual method called

### ISSUE THREAD

**Issue by moshev** [ariya/phantomjs#11047]
_**[Mo6e...@gmail.com](http://code.google.com/u/105163383354325995842/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.8.1
> 
> <b>What steps will reproduce the problem?</b>
> It's hard to say how to reproduce the problem, it happens sometimes while interacting with some sites, but I couldn't manage to write a simple example. It doesn't happen always with the same site, though.
> 
> <b>What is the expected output? What do you see instead?</b>
> Phantomjs crashes with the message
> pure virtual method called
> terminate called without active exception
> 
> <b>Which operating system are you using?</b>
> Arch Linux
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> binary
> 
> I've attached a crash report generated by minidump, but stripped the minidump log from the beginning to make it fit in under 10MB

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1047](http://code.google.com/p/phantomjs/issues/detail?id=1047).
:star2: &nbsp; **1** people had starred this issue at the time of migration.

**Comment by tigerfz** [comment]
I meet this problem when using phantomjs-1.9.7

**Comment by dnachev** [comment]
Experiencing the problem with 1.9.8 Linux x86.
