### ISSUE TITLE
Feature - new command option to enable/disable local storage

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#11055]
_**[InsFocus@gmail.com](http://code.google.com/u/InsFocus/) commented:**_
> I need to control local storage to do some scraping work. Currently i found i cannot control it.
> it will always write something to $HOME/.qws/...., i need the command option to enable/disable it. 
> default to enable. 
> 
> I'm working on this issue. once i done it, i will send new pull request, then you can review the codes.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1055](http://code.google.com/p/phantomjs/issues/detail?id=1055).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Landed in master.

**Comment by jakub-g** [comment]
@Vitallium what is the commit in which this landed? What would be the command line param to disable local storage?

**Comment by Vitallium** [comment]
Whoops. My bad! Sorry.

Looks like we don't an option to control: https://github.com/ariya/phantomjs/blob/master/src/webpage.cpp#L415

Then we will implement it shortly.

**Comment by Vitallium** [comment]
Landed in https://github.com/ariya/phantomjs/commit/fc57497166b85678d5a6616019c8c21139b74d05
