### ISSUE TITLE
Sytem Proxy "http_proxy" variable not parsed correctly

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#11052]
_**[nilsk...@gmail.com](http://code.google.com/u/113178154616381540450/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
>   1.8.1
> 
> <b>What steps will reproduce the problem?</b>
> 1. set system env variable &quot;http_proxy&quot; to a proxy with authentication like
>    export http_proxy=&quot;http://username:pw@proxyhost:3128&quot;
> 2. start a phantomjs script in debug mode like
>    phantomjs --debug=yes --ignore-ssl-errors=yes loadspeed.coffee http://www.google.com
> 
> <b>What is the expected output? What do you see instead?</b>
>   EXPECTED:
>   output should reflect the system proxy settings (something like)
>   2013-02-07T09:59:37 [DEBUG]      7 proxyType : &quot;http&quot;
>   2013-02-07T09:59:37 [DEBUG]      8 proxy : &quot;proxyhost:3128&quot;
>   2013-02-07T09:59:37 [DEBUG]      9 proxyAuth : &quot;username:pw&quot;
> 
>   WHAT I SEE
>   2013-02-07T09:59:37 [DEBUG]      7 proxyType : &quot;http&quot;
>   2013-02-07T09:59:37 [DEBUG]      8 proxy : &quot;:8&quot;
>   2013-02-07T09:59:37 [DEBUG]      9 proxyAuth : &quot;:&quot;
> 
> <b>Which operating system are you using?</b>
>   Linux Suse Enterprise 11
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
>   binaries
> 
> <b>Please provide any additional information below.</b>
> 
> FULL OUTPUT:
> 
> 2013-02-07T09:59:37 [DEBUG] CookieJar - Created but will not store cookies (use option '--cookies-file=&lt;filename&gt;' to enable persisten cookie storage)
> 2013-02-07T09:59:37 [DEBUG] Phantom - execute: Configuration
> 2013-02-07T09:59:37 [DEBUG]      0 objectName : &quot;&quot;
> 2013-02-07T09:59:37 [DEBUG]      1 cookiesFile : &quot;&quot;
> 2013-02-07T09:59:37 [DEBUG]      2 diskCacheEnabled : &quot;false&quot;
> 2013-02-07T09:59:37 [DEBUG]      3 maxDiskCacheSize : &quot;-1&quot;
> 2013-02-07T09:59:37 [DEBUG]      4 ignoreSslErrors : &quot;true&quot;
> 2013-02-07T09:59:37 [DEBUG]      5 localToRemoteUrlAccessEnabled : &quot;false&quot;
> 2013-02-07T09:59:37 [DEBUG]      6 outputEncoding : &quot;UTF-8&quot;
> 2013-02-07T09:59:37 [DEBUG]      7 proxyType : &quot;http&quot;
> 2013-02-07T09:59:37 [DEBUG]      8 proxy : &quot;:8&quot;
> 2013-02-07T09:59:37 [DEBUG]      9 proxyAuth : &quot;:&quot;
> 2013-02-07T09:59:37 [DEBUG]      10 scriptEncoding : &quot;UTF-8&quot;
> 2013-02-07T09:59:37 [DEBUG]      11 webSecurityEnabled : &quot;true&quot;
> 2013-02-07T09:59:37 [DEBUG]      12 offlineStoragePath : &quot;&quot;
> 2013-02-07T09:59:37 [DEBUG]      13 offlineStorageDefaultQuota : &quot;-1&quot;
> 2013-02-07T09:59:37 [DEBUG]      14 printDebugMessages : &quot;true&quot;
> 2013-02-07T09:59:37 [DEBUG]      15 javascriptCanOpenWindows : &quot;true&quot;
> 2013-02-07T09:59:37 [DEBUG]      16 javascriptCanCloseWindows : &quot;true&quot;
> 2013-02-07T09:59:37 [DEBUG]      17 sslProtocol : &quot;sslv3&quot;
> 2013-02-07T09:59:37 [DEBUG]      18 webdriver : &quot;&quot;
> 2013-02-07T09:59:37 [DEBUG]      19 webdriverSeleniumGridHub : &quot;&quot;
> 2013-02-07T09:59:37 [DEBUG] Phantom - execute: Script &amp; Arguments
> 2013-02-07T09:59:37 [DEBUG]      script: &quot;/internal-tools/phantomjs-1.8.1-linux-x86_64/examples/loadspeed.coffee&quot;
> 2013-02-07T09:59:37 [DEBUG]      0 arg: &quot;http://locahost&quot;
> 2013-02-07T09:59:37 [DEBUG] Phantom - execute: Starting normal mode
> 2013-02-07T09:59:37 [DEBUG] WebPage - setupFrame &quot;&quot;
> 2013-02-07T09:59:37 [DEBUG] FileSystem - _open: &quot;:/modules/fs.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:37 [DEBUG] FileSystem - _open: &quot;:/modules/system.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:37 [DEBUG] FileSystem - _open: &quot;:/modules/_coffee-script.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:37 [DEBUG] FileSystem - _open: &quot;:/modules/../coffee-script/package.json&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:37 [DEBUG] FileSystem - _open: &quot;:/modules/../coffee-script/./lib/coffee-script/coffee-script.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:37 [DEBUG] FileSystem - _open: &quot;:/modules/../coffee-script/./lib/coffee-script/./lexer.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:37 [DEBUG] FileSystem - _open: &quot;:/modules/../coffee-script/./lib/coffee-script/././rewriter.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:37 [DEBUG] FileSystem - _open: &quot;:/modules/../coffee-script/./lib/coffee-script/././helpers.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:37 [DEBUG] FileSystem - _open: &quot;:/modules/../coffee-script/./lib/coffee-script/./parser.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:38 [DEBUG] FileSystem - _open: &quot;:/modules/../coffee-script/./lib/coffee-script/./helpers.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:38 [DEBUG] FileSystem - _open: &quot;:/modules/../coffee-script/./lib/coffee-script/./nodes.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:38 [DEBUG] FileSystem - _open: &quot;:/modules/../coffee-script/./lib/coffee-script/././scope.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:38 [DEBUG] FileSystem - _open: &quot;:/modules/../coffee-script/./lib/coffee-script/./././helpers.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:38 [DEBUG] FileSystem - _open: &quot;:/modules/../coffee-script/./lib/coffee-script/././lexer.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:38 [DEBUG] FileSystem - _open: &quot;:/modules/../coffee-script/./lib/coffee-script/./././rewriter.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )
> 2013-02-07T09:59:38 [DEBUG] FileSystem - _open: &quot;:/modules/webpage.js&quot; QMap((&quot;mode&quot;, QVariant(QString, &quot;r&quot;) ) )

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1052](http://code.google.com/p/phantomjs/issues/detail?id=1052).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by dzhus** [comment]
I can still reproduce the original issue on macOS 10.12.6 with PhantomJS 2.1.1:
```
$ phantomjs --version
2.1.1
$ http_proxy="http://127.0.0.1:31337" phantomjs --debug=yes                                                                                                            
2017-12-01T13:59:28 [DEBUG] CookieJar - Created but will not store cookies (use option '--cookies-file=<filename>' to enable persistent cookie storage)
2017-12-01T13:59:29 [DEBUG] Set  "http"  proxy to:  "" : 1080
```

**Comment by tanandy** [comment]
Hello,

same problem here.
