### ISSUE TITLE
Unable to compile phantomjs 1.5+ on armhf build

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#11064]
_**[brendan....@gmail.com](http://code.google.com/u/106680562535541964315/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
trying to compile 1.8,1.7,1.6 or 1.5
> 
> <b>What steps will reproduce the problem?</b>

> 1.sudo apt-get install build-essential chrpath git-core libssl-dev libfontconfig1-dev
> 2. git clone git://github.com/ariya/phantomjs.git
> 3. cd phantomjs
> 4. git checkout 1.8
> 5. ./build.sh
> 
> <b>What is the expected output? What do you see instead?</b>
1.8,1.7, and 1.6 all return immediately to the command prompt with no error. 1.5 attempts to compile. Output attached. 
> 
> From what I can see the errors that might mean something are:
> * WARNING: /usr/local/src/phantomjs/src/qt/src/gui/gui.pro:44: Unable to find file for inclusion egl/egl.pri
> * WARNING: Failure to find: ../3rdparty/pixman/pixman-arm-neon-asm.S
> * collect2: ld returned 1 exit status
> * make[1]: *** [../bin/phantomjs] Error 1
> * make[1]: Leaving directory `/usr/local/src/phantomjs/src'
> * make: *** [sub-src-phantomjs-pro-make_default-ordered] Error 2
> 
> <b>Which operating system are you using?</b>
Bodhilinux armhf on an efikamx 
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Trying to compile.
> 
> <b>Please provide any additional information below.</b>
Sorry this is my first experience with attempting to compile from source and I'm pretty new to linux fullstop. I've been using phantomjs on a windows dev box I have but trying to set up phantomjs to work on my linux webserver.
> 
> Any ideas with the errors? Or why I don't even seem to be able to initiate the script for 1.6-1.8?
> 
> Thanks,
> Brendan

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1064](http://code.google.com/p/phantomjs/issues/detail?id=1064).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
