### ISSUE TITLE
PDF Output Produces Malformed PDF

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#11069]
_**[Wilsonbr...@gmail.com](http://code.google.com/u/111780073351492936674/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.8.1
> 
> <b>What steps will reproduce the problem?</b>
1. Export any webpage as pdf like so:
> 
> var system = require('system');
> if (system.args.length !== 2) {
>     phantom.exit();
> } else {
>     var url = system.args[1];
> }
> 
> var page = require('webpage').create();
> //page.viewportSize = { width: 240, height: 320 };
> page.paperSize = { format: 'Letter', orientation: 'portrait', margin: '.5in' };
> page.open(url, function () {
> 	var random = Math.floor(Math.random()*11234724357);
> 	var filename = 'temp' + random + '.pdf';
>     page.render(filename);
> 	console.log(filename);
>     phantom.exit();
> });
> 
> <b>What is the expected output? What do you see instead?</b>
PDF opens but in acrobat, document properties such as page size show blank, and pdf is not able to be saved again from acrobat pro. The following error shows: The document could not be saved. There was a problem reading this document (135).
> 
> <b>Which operating system are you using?</b>
Centos 6.3
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Binary
> 
> <b>Please provide any additional information below.</b>
All other non-phantomjs pdf's work fine. Behavior is also present on windows 7 64-bit.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1069](http://code.google.com/p/phantomjs/issues/detail?id=1069).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Duplicate.
