### ISSUE TITLE
Crashing on phantom.exit()

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#11073]
_**[ditesh.k...@gmail.com](http://code.google.com/u/100652478138331938389/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> 1.8.1
> 
> <b>What steps will reproduce the problem?</b>
1. Calling phantom.exit() in page.onError(). Try the following code:
> 
> console.log('Loading a web page');
> var page = require('webpage').create();
> var url = 'http://www.phantomjs.org/';
> page.open(url, function (status) {
>     a   
>     phantom.exit();
> });
> 
> page.onError = function(msg, trace) {
>     console.log(JSON.stringify(trace));
>     phantom.exit();
> };
> 
> 
> <b>What is the expected output? What do you see instead?</b>

> It shouldn't crash.
> 
> <b>Which operating system are you using?</b>

> Fedora Linux 16
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> Official binary PhantomJS
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1073](http://code.google.com/p/phantomjs/issues/detail?id=1073).
:star2: &nbsp; **6** people had starred this issue at the time of migration.

**Comment by NicBright** [comment]
The error still occurs (with 1.9.8 for Windows 7)

**Comment by Steeze** [comment]
I'm running into this as well, (Windows 7) using PhantomJS (1.9.13) for headless unit tests using Jasmine 2. I'm running about 1500 unit tests. If I delete about 300 unit tests it will complete, add a few more back, then it fails every time.

**Comment by Vitallium** [comment]
Fixed in 2.0
