### ISSUE TITLE
comments at end of module create Parse Error

### ISSUE THREAD

**Issue by conoverm** [ariya/phantomjs#11081]
_**[conov...@gmail.com](http://code.google.com/u/102131800942130866717/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.8.1 (windows 7)
> 
> <b>What steps will reproduce the problem?</b>
> 1. create a simple script that uses require.
> 
> var test = require('./pleasework.js');
> test.start();
> console.log('test.astring: ' + test.astring);
> phantom.exit();
> 1. have a &quot;double slash&quot; comment at the end of the 'require'd file
> 
> exports.astring = 1;
> 
> exports.start = function () {
> console.log('pleasework.js: exports.start');
> };
> 
> // THIS IS A COMMENT.
> 1. Run your module.js with module 'pleasework.js' and get:
>    Syntax Error: ParseError.
> 
> I call this an issue because comments can be anywhere else in the module: the top, between objects, among objects. Just not as the last characters.
> 
> JavaScript comments in the form /\* */ do not cause this error. Only two slashes.
> 
> <b>Which operating system are you using?</b>
> Win 7.
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> binary

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1081](http://code.google.com/p/phantomjs/issues/detail?id=1081).
:star2: &nbsp; **null** people had starred this issue at the time of migration.

**Comment by alxwest** [comment]
Just to let anyone else who finds this. This issue is fixed in PhantomJs 2+

https://github.com/ariya/phantomjs/commit/42ff1de6bbb027040797f65344c3727d5c7c4843
