### ISSUE TITLE
Allow callback for Webpage.render function

### ISSUE THREAD

**Issue by elis** [ariya/phantomjs#11084]
_**[eli.sk...@gmail.com](http://code.google.com/u/112111331968977501330/) commented:**_

> Why isn't there a callback for the render function?
> 
> Right now I'm generating a screenshot of a webpage and then create a bunch of thumbnails from it, but I have to create a large setTimeout delay so I don't get an empty or partial file when I use it to resize the image for a thumbnail.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1084](http://code.google.com/p/phantomjs/issues/detail?id=1084).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by weisjohn** [comment]
@ariya would you be able to add support for an optional callback when the file contents have flushed?

**Comment by ariya** [comment]
@weisjohn I don't see how that can be implemented.

**Comment by weisjohn** [comment]
@ariya ok, thanks for the info! I'm totally unaware of the internals of Qt, so thanks for that info!

**Comment by hao-opentown** [comment]
Is this issue fixed? I see page.render can accept a callback [here](https://github.com/ajam/banquo/blob/master/src/banquo.js#L87-L89), but no update in official document

**Comment by natostanco** [comment]
in these issue there are two problems:
- render is blocking when it comes to page load
- render is non blocking when it comes to file saving 

for file saving this works around
```js
var fs = require("fs");
ivl = setInterval(function(){
  if(fs.isFile(filePath)){
      clearInterval(ivl);
      var file = fs.read(filePath, "b");
  }
}, 300);
```

**Comment by maxdonetsk** [comment]
Guys, what if I'll add a helper element with a specific id when page which has to be rendered is fully loaded, and render() runs only after this? In this case a function which requests on this specific id with some interval will return true, and after this true render can be executed. Does that make sense?
