### ISSUE TITLE
Use HTTP proxy for FTP connections

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#11083]
_**[moen...@gmail.com](http://code.google.com/u/107965890118155911678/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.8.1 (phantomjs-1.8.1-linux-x86_64)
> 
> <b>What steps will reproduce the problem?</b>
> 1. Invoke with &quot;--proxy=host:ip&quot; to point at a proxy of your choice and retrieve a FTP url using page.open();
> 
> <b>What is the expected output? What do you see instead?</b>
> I'd like FTP connections to go through the HTTP proxy as well, but the proxy is only used for HTTP connections.
> 
> <b>Which operating system are you using?</b>
> linux 2.6.32-5-amd64
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> Binary.
> 
> <b>Please provide any additional information below.</b>
> I don't necessarily expect PhantomJS to automagically use the defined HTTP proxy for FTP connections, but I would like to have the choice to enable it (or specify a FTP proxy separately).

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1083](http://code.google.com/p/phantomjs/issues/detail?id=1083).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by haobole** [comment]
:+1:
