### ISSUE TITLE
Add ability to specify cache directory

### ISSUE THREAD

**Issue by bsenyk** [ariya/phantomjs#11102]
_**[borys.se...@gmail.com](http://code.google.com/u/103079945447845810951/) commented:**_

> Currently only local storage and cookie directories can be specified, but it would be very useful to also be able to specify a cache directory.  That way, multiple processes could be running (each with their own cache directory) and they would each have more realistic caching behavior.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1102](http://code.google.com/p/phantomjs/issues/detail?id=1102).
:star2: &nbsp; **3** people had starred this issue at the time of migration.

**Comment by CSchulz** [comment]
:+1:
