### ISSUE TITLE
Sporadic phantomjs crashes

### ISSUE THREAD

**Issue by fredoche** [ariya/phantomjs#11115]
_**[fredo...@gmail.com](http://code.google.com/u/113323373920601384491/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.7.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. Open several phantomjs process concurrently and use them through the nodejs-phantom bridge. PhantomJS should however not crash.
> 
> <b>What is the expected output? What do you see instead?</b>
> The url is not loaded, I see an error message instead
> 
> <b>Which operating system are you using?</b>
> centos 5 - 2.6.32-279.22.1.el6.x86_64
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> binary

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1115](http://code.google.com/p/phantomjs/issues/detail?id=1115).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by ariya** [comment]
Can you try it again with PhantomJS 2.1?
