### ISSUE TITLE
Page did not load (status = fail)

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#11116]
_**[GalusMar...@gmail.com](http://code.google.com/u/103311033341342736511/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 1.8.2
> <b>What steps will reproduce the problem?</b>
> 1.page.open https://webpartners.arval.co.uk/
> 
> <b>What is the expected output? What do you see instead?</b>
> No output
> <b>Which operating system are you using?</b>
> Windows
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> binary
> <b>Please provide any additional information below.</b>
> When i open source in browser I see only title tag and frame. But when i open page from frame the same result.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1116](http://code.google.com/p/phantomjs/issues/detail?id=1116).
:star2: &nbsp; **1** people had starred this issue at the time of migration.

**Comment by rineez** [comment]
Why would anyone need to do scraping of a page that is in their control and ownership!
Such invalid HTML must not fail a scraper.
 Is this issue fixed now? I see that this still has "open" status.

**Comment by galusmarcin87** [comment]
I dont know because  i dont work at this project now. We used selenium for
few pages - it worked beause selenium allow for selecting frame.

2015-11-17 7:22 GMT+01:00 Rineez <notifications@github.com>:
