### ISSUE TITLE
Add an example script for the new request redirecting functionality

### ISSUE THREAD

**Issue by JamesMGreene** [ariya/phantomjs#11123]
_**[james.m....@gmail.com](http://code.google.com/u/101963681963300214110/) commented:**_
> Add an example script for the new request redirecting functionality.
> 
> Related to Issue #539, which was address in PR 407.
> 
> https://github.com/ariya/phantomjs/pull/407

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1123](http://code.google.com/p/phantomjs/issues/detail?id=1123).
:star2: &nbsp; **1** people had starred this issue at the time of migration.

**Comment by ariya** [comment]
Likely won't happen unless someone volunteers.
