### ISSUE TITLE
Crash when opening a page

### ISSUE THREAD

**Issue by coding-idiot** [ariya/phantomjs#11136]
_**[nitin.co...@gmail.com](http://code.google.com/u/117907144223534027934/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.8
> 
> <b>What steps will reproduce the problem?</b>
1. Open http://www.fresnobee.com/2013/03/13/3212516/valley-jobs-go-so-does-growth.html using phantomJS and it'll crash
> 
> <b>What is the expected output? What do you see instead?</b>
Crash
> 
> <b>Which operating system are you using?</b>
Windows 7 64-bit
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Binary
> 
> <b>Please provide any additional information below.</b>
Crash Dump File Attached.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1136](http://code.google.com/p/phantomjs/issues/detail?id=1136).
:star2: &nbsp; **1** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
