### ISSUE TITLE
OnBeforeUnload handling not properly implemented

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#11130]
_**[ahkjeld...@gmail.com](http://code.google.com/u/110599209422854607330/) commented:**_

> Which version of PhantomJS are you using?
> 1.8.2
> 
> <b>What steps will reproduce the problem?</b>
> 1. Using phantomJS open any webpage with onbeforeunload set.
> 2. Goto another page.
> 
> <b>What is the expected output? What do you see instead?</b>
> I expect to be able to control whether or not to leave the page. The event do get caught, but it's sent as a onConfirm. If I choose to return true in the onConfirm it goes to the other page, if I select false the entire scripts stops running.
> 
> <b>Which operating system are you using?</b>
> Windows 7 x64
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> Binary
> 
> <b>Please provide any additional information below.</b>
> I use phantomJS to evaluate pages, some which include user supplied content, which in some cases contains redirects/reloads and I wish to be able to force phantomJS to stay on the page - I dont want to use the navigationLocked property.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #1130](http://code.google.com/p/phantomjs/issues/detail?id=1130).
:star2: &nbsp; **1** people had starred this issue at the time of migration.

**Comment by gdscei** [comment]
Hello,

Is this issue still in the pipeline to being fixed? We are experiencing problems with it here, where Phantom is not willing to go to a different page because of our usage of beforeunload events.

**Comment by zackw** [comment]
@gdscei Are you experiencing this problem with PhantomJS 2.0?  If you're still using an older version, please test 2.0.

**Comment by synaq** [comment]
We are experiencing it in 1.9.8, we can't test in 2.0.0 as we rely on composer to import PhantomJS into our CI projects, and no 2.0.0 binary is available for Linux.

**Comment by erikdubbelboer** [comment]
Looks like this issue can be closed as it's working with 2.0.

[This test script](https://gist.github.com/erikdubbelboer/0be59bb0f7612107d75d) returns:
```
$ ./phantomjs beforeunload.js 
confirm: onbeforeunload
```
Indicating the `onbeforeunload` callback was called and triggered the `page.onConfirm` callback.

**Comment by erikdubbelboer** [comment]
I just noticed it does have a major difference from all the major browsers. In webkit only iframes with the same origin as the main page can use the `onbeforeunload` callback. See [FrameLoader.cpp#L2792](https://github.com/Vitallium/qtwebkit/blob/05eafbe51c6c0b1a2e2d7e2c26ce67260a6759ce/Source/WebCore/loader/FrameLoader.cpp#L2792) This is not the case in Chrome, Firefox or Opera (also Opera Next). I didn't have IE to test with.

**Comment by cgatesman** [comment]
@erikdubbelboer, I'm not sure your test script tests the case where the `window.location.href` may be programmatically changed.  I believe your test is only testing changing the webpage externally.

**Comment by erikdubbelboer** [comment]
@cgatesman How the location is changed doesn't seem to matter. Using [this test script](https://gist.github.com/erikdubbelboer/50c3bc6efaf6fab74bd21f958441a7f5) has the exact same result.

**Comment by 1600** [comment]
looks like in phantomjs 2.1.1 the problem still exists.   all subsequent webpage will not be opened while the onbeforeunload confirmation is not "confirmed"

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
