### ISSUE TITLE
ReferenceError not being caught by page.onError and phantom.onError

### ISSUE THREAD

**Issue by malexmave** [ariya/phantomjs#11144]
Consider the following code:

``` javascript
var page = require('webpage').create(),
    system = require('system'),
    address, set = {};
try {   

        if (system.args.length === 1) {
            console.log('Usage: netdomain.js <some URL>');
            phantom.exit(1);
        } else {
            address = system.args[1];

            page.onResourceReceived = function (res) {
                var data = JSON.stringify(res.url, undefined, 4).split("/")[2];
                if (~data.indexOf(".")) {  // Check if String contains "." (if not, it is a false positive)
                    if (data.substring(0,4) == "www.") { // Remove www., if it is there
                        data = data.substring(4);
                    }
                    set[data] = true; // Save data
                }
            };
            page.onError = function(err) {
            };
            phantom.onError = function(err) {
            };

            page.open(address, function (status) {
                if (status !== 'success') {
                    console.log('FAIL to load the address');
                    phantom.exit(1);
                }
                console.log(Object.keys(set).toString());
                phantom.exit();
            });
        }
        // END Modified netlog.js example
}
catch(err) {
        console.log(Object.keys(set).toString());
        phantom.exit();
}
```

It works well on many pages (almost 50 000 tried so far) but on very few pages (victoriassecret.com, hsamuel.co.uk and a few others, I can provide a full list, if needed) it will still throw errors that are not caught. The error type that still comes through is a  ReferenceErrors ("Can't find variable: [varname]" on victoriassecret.com, for example).

This might be related to #10511, although the user over there theorized that `phantom.onError` should work for this, which it does not.

Please let me know if you need any further information.

**Comment by twilly86** [comment]
Also seeing this for TypeError error.  Not being caught by phantomjs onerror.

example script that is nosense.
document.xxxx.indexOf(234).jerry;

I see a TypeError in the logs but OnError is not catching it.

**Comment by pardery** [comment]
I too am experiencing this issue with a few select sites.  They are internally hosted sites, so there is no use in me providing the extra examples.  But, if it helps, I have duplicated the issues with my specific examples in 1.9.1, 1.9.2, 1.9.7, 1.9.8.  These are the only versions I currently have set up to test.

**Comment by MichielDeMey** [comment]
Yup, same issue here.

It's not capturing the following error message as an error:
```
ReferenceError: Can't find variable: MutationObserver
```

It is however displaying this when you set a `onConsoleMessage`, but there is no way of knowing if it's actually an error or not.

**Comment by skantipudi19** [comment]
I am getting page.onError 

[ERROR - 2016-02-29T15:24:34.204Z] Session [8948d0-def8-11e5-a2ac-398cdabea00d] - page.onError - msg: SyntaxError: Parse error
[ERROR - 2016-02-29T15:24:34.204Z] Session [8948d0-def8-11e5-a2ac-398cdabea00d] - page.onError - stack:
[WARNING] JavaScript Console Errors:

  * SyntaxError: Parse error

i don't have any console error while running my app or tests.

I figured issue is coming from jQuery extend in my case which i am using for adding functions into shared object inside closure.

$.extend(shared,{a,b,c,d});
I am not getting this error while i am updated extend to this.
shared.a = a;
shared.b= b;
...

I'm using jQuery 1.7.2. Jasmine 2.0 for tests and phantom version 1.9.8. 

Any help appreciated.

**Comment by skantipudi19** [comment]
Never mind. It seems phantom js doesn't have prototype in version 1.9.8 that i was using.
[(https://github.com/ariya/phantomjs/issues/10522)](#10522)

**Comment by swiezak** [comment]
Hello,
I don't know if this is the right place, but I get the following error when I enter for example this url
http://www.ihg.com/destinations/us/en/united-states/texas/texas-city-hotels
```
[ERROR - 2016-03-28T20:49:42.576Z] Session [02315ce0-f526-11e5-94b3-bda7c3a7e7f9] - page.onError - msg: ReferenceError: Can't find variable: TEXT_FIND_HOTEL

  phantomjs://platform/console++.js:263 in error
[ERROR - 2016-03-28T20:49:42.576Z] Session [02315ce0-f526-11e5-94b3-bda7c3a7e7f9] - page.onError - stack:
  (anonymous function) (http://www.ihg.com/destinations/us/en/wro/scripts-city-page.js?BUILD_TIME=1458232780943:1)

  phantomjs://platform/console++.js:263 in error
```
