### ISSUE TITLE
Rewrite REPL implementation

### ISSUE THREAD

**Issue by detro** [ariya/phantomjs#11180]
The REPL I implemented for PhantomJS is showing loads of limits. This issue aims at being a "grab all" issue where REPL issue should be redirected.

The aim of this is to do the work once, as I believe the overall "architecture" of the REPL should be revamped (it can't just be "patched").

I take ownership for this, but feel free to beat me to it.
I'll go around the repo and link them to this and close those issues.
### What's the issue

The "evaluation" of JS code is broken. I should rewrite that and the fact that we are moving to Qt5 and (I hope) to QJSEngine should make for a much better implementation.

The REPL history endling and the auto-completion I think are NOT broken and that, at least, will not need to be rewritten :)

**Comment by paulcalabro** [comment]
Ditto on Alec's comment.

**Comment by colmsjo** [comment]
Dito

**Comment by zhangw** [comment]
Unfortunately this issue is still around.

**Comment by zackw** [comment]
As far as I know, no one is working on this right now.  We would be glad to collaborate with anyone who has the time to tackle it.

**Comment by hxhxd** [comment]
Is there any workaround? Really hope someone would fix this, thanks!

**Comment by G3zz** [comment]
Still in an issue in 2017
