### ISSUE TITLE
Feature request : Support PDF to the existing renderBase64 method.

### ISSUE THREAD

**Issue by toramanan** [ariya/phantomjs#11192]
The below changes provide us to render in different image formats. Can we have PDF along with this, since many of us want to generate PDF of a web page. Thanks.

https://github.com/ariya/phantomjs/commit/51ab11c6d95178037f1e53013cb50bb3ce4fdfb8

**Comment by JSHARP-** [comment]
I would also like to request this feature. I do not want to write to disc so being able to pipe down the string of encoded PDF data would be great! Is this something that is part of the roadmap?

**Comment by howardroark** [comment]
:+1: Looks like there has been some discussion here... #12392

**Comment by Selectorrr** [comment]
+1

**Comment by robatron** [comment]
:+1:

**Comment by Vitallium** [comment]
Now available since https://github.com/ariya/phantomjs/commit/7d7e5f345b646ef18d23138781ae94197335b342
