### ISSUE TITLE
catching the jQuery parseXML exception

### ISSUE THREAD

**Issue by repinel** [ariya/phantomjs#11208]
I'm not sure if it's an issue, but shouldn't the following code throw an exception and reach the catch block?

try {
    jQuery.parseXML('foo');
} catch(e) {
    console.log(e.message);
}

**Comment by stijnvn** [comment]
I'm also experiencing this issue. Is there any workaround for this?

 - [x] What OS? What version? Linux Mint 16
 - [x]  What version of PhantomJS? PhantomJS 1.9.8
  - [x] What version of jQuery? jQuery 2.1.4
  - [x] What is the context of this script? An existing script on an existing page: running a Jasmine spec suite

**Comment by LeMoussel** [comment]
Code working properly

- [x] What OS? What version? Windows 7
- [x] What version of PhantomJS? PhantomJS 2.0.0
- [x] What version of jQuery? jQuery 2.1.4
- [x] What is the context of this script? An existing script

**Result:**

    Started
    Loaded jQuery
    Parsing XML
    XML is valid? false`
