### ISSUE TITLE
Allow outer context to access arbitrary URLs

### ISSUE THREAD

**Issue by cburgmer** [ariya/phantomjs#11217]
Accessing arbitrary domains from PhantomJS' outer context is currently only possible through a dirty workaround (e.g. https://gist.github.com/cburgmer/5339864). For sandboxed webpages this is however easily doable by passing `--web-security=no` to phantom on the console.

I believe that the outer context should be able to access any resources without restrictions, similar to e.g. Node.js.

Relevant discussion in the phantomjs group: https://groups.google.com/forum/#!topic/phantomjs/Kb06DuqIoxw

**Comment by Vitallium** [comment]
Fixed in https://github.com/ariya/phantomjs/commit/d938eddaf2039cc4d8a90704f736129edb8e1260
