### ISSUE TITLE
should change method to GET when following 303 redirect

### ISSUE THREAD

**Issue by wkruszewski** [ariya/phantomjs#11214]
When my server responds to PUT/DELETE with 303 redirect, PhantomJS follows the redirect with original request method. It correctly changes request method to GET after POST requests. Here's a snippet from my server log:

```
[127.0.0.1] Started DELETE "/clients/809315521/workflow_instances/122797022" for 127.0.0.1 at 2013-04-08 05:21:27 +0200
[127.0.0.1] Redirected to http://127.0.0.1:57228/clients/809315521/workflow_instances
[127.0.0.1] Completed 303 See Other in 24ms (ActiveRecord: 5.2ms)
[127.0.0.1] Started DELETE "/clients/809315521/workflow_instances" for 127.0.0.1 at 2013-04-08 05:21:28 +0200
```

RFC2616 states that:
The response to the request can be found under a different URI and SHOULD be retrieved using a GET method on that resource.
http://tools.ietf.org/html/rfc2616#section-10.3.4

**Comment by schmilblick** [comment]
@WojtekKruszewski Haha, I stumbled over this issue when Googling for redirect issues with PhantomJS, you are not alone! :+1: :)

**Comment by WojtekKruszewski** [comment]
@schmilblick :D https://xkcd.com/979/

**Comment by jprince** [comment]
:+1:

**Comment by villesundberg** [comment]
:+1:

**Comment by asok** [comment]
Yup I have the same when using [poltergeist](https://github.com/teampoltergeist/poltergeist) which is based on phantomjs.

**Comment by maxjustus** [comment]
👍

**Comment by liebig** [comment]
Issue still exists!

**Comment by osgrob** [comment]
...and still exists

**Comment by jonathanpa** [comment]
and still still exists ...
