### ISSUE TITLE
SSL Error on https://thimble.webmaker.org/ - SNI Issue?

### ISSUE THREAD

**Issue by st3fan** [ariya/phantomjs#11239]
Running with --debug=true I see the following:

```
2013-04-15T14:29:15 [DEBUG] Network - SSL Error: "The host name did not match any of the valid hosts for this certificate"
2013-04-15T14:29:15 [DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://thimble.webmaker.org/"
```

I suspect that PhantomJS is not supporting Server Name Indication properly. If the SNI extension is not used for TLS servers that require it, a (fatal) hostname mismatch will happen.

Is it possible that my version of PhantomJS is linked against an OpenSSL version that does not implement it?

I am using phantomjs-1.9.0-linux-x86_64

See http://en.wikipedia.org/wiki/Server_Name_Indication for more info about SNI. This is getting more and more common. All modern browsers support it.

**Comment by dbrgn** [comment]
Still no SNI support? I also ran into this.

**Comment by camaleo** [comment]
same problem here, no way to use it on a site using CloudFlare and ssl

**Comment by ilyaevseev** [comment]
Is it fixed in 2.0?

**Comment by stefanfoulis** [comment]
Is there a fix for this now?
Using ``--ssl-protocol=TLSv1`` is not an option, since ``TLSv1`` is insecure and disabled at an infrastructure level.

**Comment by stefanfoulis** [comment]
This seems to be fixed in 2.x. IMHO this issue can be closed.
