### ISSUE TITLE
PhantomJS crash report

### ISSUE THREAD

**Issue by tpetsas** [ariya/phantomjs#11247]
Operating system: Linux
                  0.0.0 Linux 3.2.0-34-generic-pae #53-Ubuntu SMP Thu Nov 15 11:11:12 UTC 2012 i686
CPU: x86
     GenuineIntel family 6 model 42 stepping 7
     8 CPUs

Crash reason:  SIGSEGV
Crash address: 0xb8

Thread 0 (crashed)
 0  phantomjs + 0x18d368a
    eip = 0x0991b68a   esp = 0xbfa98c0c   ebp = 0xbfa98e08   ebx = 0x0a54add0
    esi = 0x0b542a80   edi = 0x00000000   eax = 0x00000000   ecx = 0x0b62aff8
    edx = 0x0b62aff8   efl = 0x00210216
    Found by: given as instruction pointer in context
 1  phantomjs + 0x6f525b
    eip = 0x0873d25c   esp = 0xbfa98e10   ebp = 0xbfa98e48
    Found by: previous frame's frame pointer
 2  phantomjs + 0x6f5426
    eip = 0x0873d427   esp = 0xbfa98e50   ebp = 0xbfa98e58
    Found by: previous frame's frame pointer
 3  phantomjs + 0x6f2687
    eip = 0x0873a688   esp = 0xbfa98e60   ebp = 0xbfa98e78
    Found by: previous frame's frame pointer
 4  phantomjs + 0x5860a0
    eip = 0x085ce0a1   esp = 0xbfa98e80   ebp = 0xbfa98ea8
    Found by: previous frame's frame pointer
 5  phantomjs + 0x493160
    eip = 0x084db161   esp = 0xbfa98eb0   ebp = 0xbfa98f88
    Found by: previous frame's frame pointer
 6  phantomjs + 0x4826de
    eip = 0x084ca6df   esp = 0xbfa98f90   ebp = 0xbfa99158
    Found by: previous frame's frame pointer
 7  phantomjs + 0x44dfdc
    eip = 0x08495fdd   esp = 0xbfa99160   ebp = 0xbfa99188
    Found by: previous frame's frame pointer
 8  phantomjs + 0x45c8b6
    eip = 0x084a48b7   esp = 0xbfa99190   ebp = 0xbfa991b8
    Found by: previous frame's frame pointer
 9  phantomjs + 0x508f0e
    eip = 0x08550f0f   esp = 0xbfa991c0   ebp = 0xbfa991d8
    Found by: previous frame's frame pointer
10  phantomjs + 0x517786
    eip = 0x0855f787   esp = 0xbfa991e0   ebp = 0xbfa99208
    Found by: previous frame's frame pointer
11  phantomjs + 0x4ac5f4
    eip = 0x084f45f5   esp = 0xbfa99210   ebp = 0xbfa99288
    Found by: previous frame's frame pointer
12  phantomjs + 0x11cef3
    eip = 0x08164ef4   esp = 0xbfa99290   ebp = 0xbfa99298
    Found by: previous frame's frame pointer
13  phantomjs + 0xc70659
    eip = 0x08cb865a   esp = 0xbfa992a0   ebp = 0xbfa992d8
    Found by: previous frame's frame pointer
14  phantomjs + 0xbdddd1
    eip = 0x08c25dd2   esp = 0xbfa992e0   ebp = 0xbfa99318
    Found by: previous frame's frame pointer
15  0x6b2fb69f
    eip = 0x6b2fb6a0   esp = 0xbfa99320   ebp = 0xbfa99368
    Found by: previous frame's frame pointer
16  phantomjs + 0xbb1474
    eip = 0x08bf9475   esp = 0xbfa99370   ebp = 0xbfa99468
    Found by: previous frame's frame pointer
17  phantomjs + 0xc0003b
    eip = 0x08c4803c   esp = 0xbfa99470   ebp = 0xbfa994b8
    Found by: previous frame's frame pointer
18  phantomjs + 0xca4fd1
    eip = 0x08cecfd2   esp = 0xbfa994c0   ebp = 0xbfa996c8
    Found by: previous frame's frame pointer
19  phantomjs + 0x247156
    eip = 0x0828f157   esp = 0xbfa996d0   ebp = 0xbfa99728
    Found by: previous frame's frame pointer
20  phantomjs + 0x24837b
    eip = 0x0829037c   esp = 0xbfa99730   ebp = 0xbfa99758
    Found by: previous frame's frame pointer
21  phantomjs + 0x25d193
    eip = 0x082a5194   esp = 0xbfa99760   ebp = 0xbfa99788
    Found by: previous frame's frame pointer
22  phantomjs + 0x2454e9
    eip = 0x0828d4ea   esp = 0xbfa99790   ebp = 0xbfa99838
    Found by: previous frame's frame pointer
23  phantomjs + 0x2425d5
    eip = 0x0828a5d6   esp = 0xbfa99840   ebp = 0xbfa99868
    Found by: previous frame's frame pointer
24  phantomjs + 0x246cda
    eip = 0x0828ecdb   esp = 0xbfa99870   ebp = 0xbfa998b8
    Found by: previous frame's frame pointer
25  phantomjs + 0x257be8
    eip = 0x0829fbe9   esp = 0xbfa998c0   ebp = 0xbfa998f8
    Found by: previous frame's frame pointer
26  phantomjs + 0x214cda
    eip = 0x0825ccdb   esp = 0xbfa99900   ebp = 0xbfa99948
    Found by: previous frame's frame pointer
27  phantomjs + 0x3de52f
    eip = 0x08426530   esp = 0xbfa99950   ebp = 0xbfa99958
    Found by: previous frame's frame pointer
28  phantomjs + 0x3c1b52
    eip = 0x08409b53   esp = 0xbfa99960   ebp = 0xbfa99988
    Found by: previous frame's frame pointer
29  phantomjs + 0x3c142b
    eip = 0x0840942c   esp = 0xbfa99990   ebp = 0xbfa999b8
    Found by: previous frame's frame pointer
30  phantomjs + 0x3c6b09
    eip = 0x0840eb0a   esp = 0xbfa999c0   ebp = 0xbfa999e8
    Found by: previous frame's frame pointer
31  phantomjs + 0x3c67ba
    eip = 0x0840e7bb   esp = 0xbfa999f0   ebp = 0xbfa99a08
    Found by: previous frame's frame pointer
32  phantomjs + 0x5a3d1a
    eip = 0x085ebd1b   esp = 0xbfa99a10   ebp = 0xbfa99a48
    Found by: previous frame's frame pointer
33  phantomjs + 0x5a3e0e
    eip = 0x085ebe0f   esp = 0xbfa99a50   ebp = 0xbfa99a78
    Found by: previous frame's frame pointer
34  phantomjs + 0x718923
    eip = 0x08760924   esp = 0xbfa99a80   ebp = 0xbfa99a98
    Found by: previous frame's frame pointer
35  phantomjs + 0x1ab974e
    eip = 0x09b0174f   esp = 0xbfa99aa0   ebp = 0xbfa99ba8
    Found by: previous frame's frame pointer
36  phantomjs + 0x1305ffe
    eip = 0x0934dfff   esp = 0xbfa99bb0   ebp = 0xbfa99bc8
    Found by: previous frame's frame pointer
37  phantomjs + 0x130dfd0
    eip = 0x09355fd1   esp = 0xbfa99bd0   ebp = 0xbfa99f88
    Found by: previous frame's frame pointer
38  phantomjs + 0x1aa6f2a
    eip = 0x09aeef2b   esp = 0xbfa99f90   ebp = 0xbfa99fb8
    Found by: previous frame's frame pointer
39  phantomjs + 0x1ad30af
    eip = 0x09b1b0b0   esp = 0xbfa99fc0   ebp = 0xbfa9a018
    Found by: previous frame's frame pointer
40  phantomjs + 0x1ad31b8
    eip = 0x09b1b1b9   esp = 0xbfa9a020   ebp = 0xbfa9a028
    Found by: previous frame's frame pointer
41  phantomjs + 0x1ad3a6f
    eip = 0x09b1ba70   esp = 0xbfa9a030   ebp = 0xbfa9a068
    Found by: previous frame's frame pointer
42  phantomjs + 0x136b2d9
    eip = 0x093b32da   esp = 0xbfa9a070   ebp = 0xbfa9a0a8
    Found by: previous frame's frame pointer
43  phantomjs + 0x1aa5dbc
    eip = 0x09aeddbd   esp = 0xbfa9a0b0   ebp = 0xbfa9a0d8
    Found by: previous frame's frame pointer
44  phantomjs + 0x1aa62a0
    eip = 0x09aee2a1   esp = 0xbfa9a0e0   ebp = 0xbfa9a128
    Found by: previous frame's frame pointer
45  phantomjs + 0x1aa811c
    eip = 0x09af011d   esp = 0xbfa9a130   ebp = 0xbfa9a168
    Found by: previous frame's frame pointer
46  phantomjs + 0x1305916
    eip = 0x0934d917   esp = 0xbfa9a170   ebp = 0xbfa9a178
    Found by: previous frame's frame pointer
47  phantomjs + 0x25958
    eip = 0x0806d959   esp = 0xbfa9a180   ebp = 0xbfa9a238
    Found by: previous frame's frame pointer
48  libc-2.15.so + 0x194d2
    eip = 0xb73dc4d3   esp = 0xbfa9a240   ebp = 0x00000000
    Found by: previous frame's frame pointer
49  phantomjs + 0x1b301df
    eip = 0x09b781e0   esp = 0xbfa9a244   ebp = 0x00000000
    Found by: stack scanning
50  libc-2.15.so + 0x194d2
    eip = 0xb73dc4d3   esp = 0xbfa9a250   ebp = 0x00000000
    Found by: stack scanning
51  phantomjs + 0x1bff
    eip = 0x08049c00   esp = 0xbfa9a274   ebp = 0x00000000
    Found by: stack scanning
52  libc-2.15.so + 0x1a5ff3
    eip = 0xb7568ff4   esp = 0xbfa9a278   ebp = 0x00000000
    Found by: stack scanning
53  phantomjs + 0x590f
    eip = 0x0804d910   esp = 0xbfa9a2a0   ebp = 0x00000000
    Found by: stack scanning
54  ld-2.15.so + 0x1469f
    eip = 0xb77c06a0   esp = 0xbfa9a2a8   ebp = 0x00000000
    Found by: stack scanning
55  libc-2.15.so + 0x193e8
    eip = 0xb73dc3e9   esp = 0xbfa9a2ac   ebp = 0x00000000
    Found by: stack scanning
56  ld-2.15.so + 0x20ff3
    eip = 0xb77ccff4   esp = 0xbfa9a2b0   ebp = 0x00000000
    Found by: stack scanning
57  phantomjs + 0x590f
    eip = 0x0804d910   esp = 0xbfa9a2b8   ebp = 0x00000000
    Found by: stack scanning
58  phantomjs + 0x5930
    eip = 0x0804d931   esp = 0xbfa9a2c0   ebp = 0x00000000
    Found by: stack scanning
59  phantomjs + 0x2571f
    eip = 0x0806d720   esp = 0xbfa9a2c4   ebp = 0x00000000
    Found by: stack scanning
60  phantomjs + 0x1b301df
    eip = 0x09b781e0   esp = 0xbfa9a2d0   ebp = 0x00000000
    Found by: stack scanning
61  phantomjs + 0x1b301cf
    eip = 0x09b781d0   esp = 0xbfa9a2d4   ebp = 0x00000000
    Found by: stack scanning
62  ld-2.15.so + 0xf26f
    eip = 0xb77bb270   esp = 0xbfa9a2d8   ebp = 0x00000000
    Found by: stack scanning
63  ld-2.15.so + 0x21917
    eip = 0xb77cd918   esp = 0xbfa9a2e0   ebp = 0x00000000
    Found by: stack scanning

Thread 1
 0  linux-gate.so + 0x424
    eip = 0xb77ab424   esp = 0xb6f2d278   ebp = 0x00000215   ebx = 0x0a560214
    esi = 0x00000000   edi = 0x0a5601f8   eax = 0xfffffe00   ecx = 0x00000080
    edx = 0x00000215   efl = 0x00200206
    Found by: given as instruction pointer in context
 1  libpthread-2.15.so + 0xa96a
    eip = 0xb76a796b   esp = 0xb6f2d288   ebp = 0x00000215
    Found by: stack scanning
 2  phantomjs + 0x2502dcf
    eip = 0x0a54add0   esp = 0xb6f2d2a0   ebp = 0x00000215
    Found by: stack scanning
 3  phantomjs + 0xd8961
    eip = 0x08120962   esp = 0xb6f2d2b0   ebp = 0x00000215
    Found by: stack scanning
 4  ld-2.15.so + 0xe28a
    eip = 0xb77ba28b   esp = 0xb6f2d2c8   ebp = 0x00000215
    Found by: stack scanning
 5  libpthread-2.15.so + 0x2417
    eip = 0xb769f418   esp = 0xb6f2d2f4   ebp = 0x00000215
    Found by: stack scanning
 6  phantomjs + 0xd887a
    eip = 0x0812087b   esp = 0xb6f2d30c   ebp = 0x00000215
    Found by: stack scanning
 7  libpthread-2.15.so + 0x17ff3
    eip = 0xb76b4ff4   esp = 0xb6f2d310   ebp = 0x00000215
    Found by: stack scanning
 8  phantomjs + 0xd8b30
    eip = 0x08120b31   esp = 0xb6f2d320   ebp = 0x00000215
    Found by: stack scanning
 9  ld-2.15.so + 0x1469f
    eip = 0xb77c06a0   esp = 0xb6f2d328   ebp = 0x00000215
    Found by: stack scanning
10  libpthread-2.15.so + 0x6d4b
    eip = 0xb76a3d4c   esp = 0xb6f2d330   ebp = 0x00000215
    Found by: stack scanning

Thread 2
 0  linux-gate.so + 0x424
    eip = 0xb77ab424   esp = 0xb660401c   ebp = 0xb6604098   ebx = 0x0000000e
    esi = 0xb5d00994   edi = 0x00000000   eax = 0xfffffdfe   ecx = 0xb5d0056c
    edx = 0xb5d00780   efl = 0x00200292
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1ad1c18
    eip = 0x09b19c19   esp = 0xb66040a0   ebp = 0xb66040b8
    Found by: previous frame's frame pointer
 2  phantomjs + 0x1ad35d6
    eip = 0x09b1b5d7   esp = 0xb66040c0   ebp = 0xb66041c8
    Found by: previous frame's frame pointer
 3  phantomjs + 0x1ad3a46
    eip = 0x09b1ba47   esp = 0xb66041d0   ebp = 0xb6604208
    Found by: previous frame's frame pointer
 4  phantomjs + 0x1aa5dbc
    eip = 0x09aeddbd   esp = 0xb6604210   ebp = 0xb6604238
    Found by: previous frame's frame pointer
 5  phantomjs + 0x1aa62a0
    eip = 0x09aee2a1   esp = 0xb6604240   ebp = 0xb6604288
    Found by: previous frame's frame pointer
 6  phantomjs + 0x1995959
    eip = 0x099dd95a   esp = 0xb6604290   ebp = 0xb66042d8
    Found by: previous frame's frame pointer
 7  phantomjs + 0x1995aa0
    eip = 0x099ddaa1   esp = 0xb66042e0   ebp = 0xb66042e8
    Found by: previous frame's frame pointer
 8  phantomjs + 0x1998b7f
    eip = 0x099e0b80   esp = 0xb66042f0   ebp = 0xb6604328
    Found by: previous frame's frame pointer
 9  libpthread-2.15.so + 0x6d4b
    eip = 0xb76a3d4c   esp = 0xb6604330   ebp = 0xb6604428
    Found by: previous frame's frame pointer
10  libc-2.15.so + 0xeed3d
    eip = 0xb74b1d3e   esp = 0xb6604430   ebp = 0x00000000
    Found by: previous frame's frame pointer

Thread 3
 0  linux-gate.so + 0x424
    eip = 0xb77ab424   esp = 0xb4c5001c   ebp = 0xb4c50098   ebx = 0x0000003c
    esi = 0xb4300994   edi = 0xb4c50080   eax = 0xfffffdfe   ecx = 0xb430056c
    edx = 0xb4300780   efl = 0x00200292
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1ad1c18
    eip = 0x09b19c19   esp = 0xb4c500a0   ebp = 0xb4c500b8
    Found by: previous frame's frame pointer
 2  phantomjs + 0x1ad35d6
    eip = 0x09b1b5d7   esp = 0xb4c500c0   ebp = 0xb4c501c8
    Found by: previous frame's frame pointer
 3  phantomjs + 0x1ad3a46
    eip = 0x09b1ba47   esp = 0xb4c501d0   ebp = 0xb4c50208
    Found by: previous frame's frame pointer
 4  phantomjs + 0x1aa5dbc
    eip = 0x09aeddbd   esp = 0xb4c50210   ebp = 0xb4c50238
    Found by: previous frame's frame pointer
 5  phantomjs + 0x1aa62a0
    eip = 0x09aee2a1   esp = 0xb4c50240   ebp = 0xb4c50288
    Found by: previous frame's frame pointer
 6  phantomjs + 0x1995959
    eip = 0x099dd95a   esp = 0xb4c50290   ebp = 0xb4c502d8
    Found by: previous frame's frame pointer
 7  phantomjs + 0x1995aa0
    eip = 0x099ddaa1   esp = 0xb4c502e0   ebp = 0xb4c502e8
    Found by: previous frame's frame pointer
 8  phantomjs + 0x1998b7f
    eip = 0x099e0b80   esp = 0xb4c502f0   ebp = 0xb4c50328
    Found by: previous frame's frame pointer
 9  libpthread-2.15.so + 0x6d4b
    eip = 0xb76a3d4c   esp = 0xb4c50330   ebp = 0xb4c50428
    Found by: previous frame's frame pointer
10  libc-2.15.so + 0xeed3d
    eip = 0xb74b1d3e   esp = 0xb4c50430   ebp = 0x00000000
    Found by: previous frame's frame pointer

Loaded modules:
0x08048000 - 0x0a55afff  phantomjs  ???  (main)
0xb3742000 - 0xb3753fff  Umpush.ttf  ???
0xb3754000 - 0xb3781fff  MuktiNarrow.ttf  ???
0xb3782000 - 0xb37c2fff  KhmerOS.ttf  ???
0xb37c3000 - 0xb37d5fff  Garuda.ttf  ???
0xb37d6000 - 0xb37eafff  Umpush-Oblique.ttf  ???
0xb37eb000 - 0xb37fcfff  n019004l.pfb  ???
0xb37fd000 - 0xb380efff  Loma.ttf  ???
0xb380f000 - 0xb3824fff  Garuda-Oblique.ttf  ???
0xb4122000 - 0xb4137fff  Waree.ttf  ???
0xb4138000 - 0xb4150fff  Waree-Oblique.ttf  ???
0xb4151000 - 0xb4164fff  n019003l.pfb  ???
0xb4165000 - 0xb4175fff  n019023l.pfb  ???
0xb4176000 - 0xb420bfff  DejaVuSans-Oblique.ttf  ???
0xb4243000 - 0xb4257fff  Loma-Oblique.ttf  ???
0xb4dbb000 - 0xb4e58fff  DejaVuSansCondensed.ttf  ???
0xb4e60000 - 0xb4efafff  DejaVuSansCondensed-Bold.ttf  ???
0xb6f36000 - 0xb6f8bfff  libssl.so.1.0.0  ???
0xb6f8c000 - 0xb7133fff  libcrypto.so.1.0.0  ???
0xb714b000 - 0xb714bfff  c05880de57d1f5e948fdfacc138775d9-le32d4.cache-3  ???
0xb714c000 - 0xb7151fff  945677eb7aeaf62f1d50efc3fb3ec7d8-le32d4.cache-3  ???
0xb7152000 - 0xb7153fff  99e8ed0e538f840c565b6ed5dad60d56-le32d4.cache-3  ???
0xb7154000 - 0xb7156fff  2cd17615ca594fa2959ae173292e504c-le32d4.cache-3  ???
0xb7157000 - 0xb7157fff  e7071f4a29fa870f4323321c154eba04-le32d4.cache-3  ???
0xb7158000 - 0xb7158fff  0d8c3b2ac0904cb8a57a757ad11a4a08-le32d4.cache-3  ???
0xb7159000 - 0xb715cfff  a755afe4a08bf5b97852ceb7400b47bc-le32d4.cache-3  ???
0xb715d000 - 0xb7163fff  6d41288fd70b0be22e8c3a91e032eec0-le32d4.cache-3  ???
0xb7164000 - 0xb716efff  04aabc0a78ac019cf9454389977116d2-le32d4.cache-3  ???
0xb716f000 - 0xb7171fff  385c0604a188198f04d133e54aba7fe7-le32d4.cache-3  ???
0xb7172000 - 0xb7172fff  4794a0821666d79190d59a36cb4f44b5-le32d4.cache-3  ???
0xb7173000 - 0xb7175fff  8801497958630a81b71ace7c5f9b32a8-le32d4.cache-3  ???
0xb7176000 - 0xb7179fff  3047814df9a2f067bd2d96a2b9c36e5a-le32d4.cache-3  ???
0xb717a000 - 0xb717afff  56cf4f4769d0f4abc89a4895d7bd3ae1-le32d4.cache-3  ???
0xb717b000 - 0xb717bfff  b9d506c9ac06c20b433354fa67a72993-le32d4.cache-3  ???
0xb717c000 - 0xb717ffff  b47c4e1ecd0709278f4910c18777a504-le32d4.cache-3  ???
0xb7180000 - 0xb737ffff  locale-archive  ???
0xb7383000 - 0xb73acfff  libexpat.so.1.5.2  ???
0xb73ad000 - 0xb73c2fff  libz.so.1.2.3.4  ???
0xb73c3000 - 0xb7569fff  libc-2.15.so  ???
0xb756d000 - 0xb758afff  libgcc_s.so.1  ???
0xb758c000 - 0xb75b7fff  libm-2.15.so  ???
0xb75b8000 - 0xb7695fff  libstdc++.so.6.0.16  ???
0xb769d000 - 0xb76b5fff  libpthread-2.15.so  ???
0xb76b8000 - 0xb76c0fff  librt-2.15.so  ???
0xb76c1000 - 0xb76c5fff  libdl-2.15.so  ???
0xb76c7000 - 0xb76fafff  libfontconfig.so.1.4.4  ???
0xb76fb000 - 0xb7794fff  libfreetype.so.6.8.0  ???
0xb7796000 - 0xb77a2fff  d52a8644073d54c13679302ca1180695-le32d4.cache-3  ???
0xb77a3000 - 0xb77a4fff  e13b20fdb08344e0e664864cc2ede53d-le32d4.cache-3  ???
0xb77a5000 - 0xb77a7fff  7ef2298fde41cc6eeb7af42e48b7d293-le32d4.cache-3  ???
0xb77ab000 - 0xb77abfff  linux-gate.so  ???
0xb77ac000 - 0xb77cdfff  ld-2.15.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
