### ISSUE TITLE
PhantomJS 1.9 crash on OSX

### ISSUE THREAD

**Issue by benjolitz** [ariya/phantomjs#11253]
Version: 1.9.0 (Official). Installed via Brew.

UName/Version:
Darwin mac 12.3.0 Darwin Kernel Version 12.3.0: Sun Jan  6 22:37:10 PST 2013; root:xnu-2050.22.13~1/RELEASE_X86_64 x86_64
OSX 10.8.3

Stack trace:
https://gist.github.com/benjolitz/5424197

DMP File:
http://www.sendspace.com/file/b662qi

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
