### ISSUE TITLE
Running phantomjs on command line immediately Seg faults

### ISSUE THREAD

**Issue by anandvc** [ariya/phantomjs#11274]
Just installed phantomjs 1.9 for 64-bit Linux from the pre-packaged binary. Trying to start it in interactive mode crashes with a seg fault.

-bash-4.1# phantomjs -v
1.9.0

-bash-4.1# ../phantomjs-1.9.0-linux-x86_64/bin/phantomjs
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/2816757d-f562-7461-17fe084a-19b50fe7.dmp
Segmentation fault

-bash-4.1# ./minidump_stackwalk  /tmp/2816757d-f562-7461-17fe084a-19b50fe7.dmp . 2>/dev/null
Operating system: Linux
                  0.0.0 Linux 2.6.32-042stab061.2 #1 SMP Fri Aug 24 09:07:21 MSK 2012 x86_64
CPU: amd64
     family 15 model 65 stepping 2
     4 CPUs

Crash reason:  SIGSEGV
Crash address: 0xbbadbeef

Thread 0 (crashed)
 0  phantomjs!WTF::OSAllocator::reserveUncommitted [OSAllocatorPosix.cpp : 107 + 0x7]
    rbx = 0xffffffffffffffff   r12 = 0x0000000002e20bc0
    r13 = 0x000000000000007f   r14 = 0x00007f1552336820
    r15 = 0x00007f1552336720   rip = 0x00000000004ef417
    rsp = 0x00007fff602472f0   rbp = 0x7ff8000000000000
    Found by: given as instruction pointer in context
 1  phantomjs!JSC::ExecutableAllocator::isValid [PageReservation.h : 107 + 0x18]
    rbx = 0x0000000002e20ba0   r12 = 0x0000000002e20bc0
    r13 = 0x000000000000007f   r14 = 0x00007f1552336820
    r15 = 0x00007f1552336720   rip = 0x0000000000f28951
    rsp = 0x00007fff60247300   rbp = 0x7ff8000000000000
    Found by: call frame info
 2  phantomjs!JSC::ExecutableAllocator::ExecutableAllocator [ExecutableAllocator.h : 185 + 0x7]
    rbx = 0x0000000002af3ad8   r12 = 0x0000000002ea76b0
    r13 = 0x000000000000007f   r14 = 0x00007f1552336820
    r15 = 0x00007f1552336720   rip = 0x0000000000f7f6e6
    rsp = 0x00007fff60247350   rbp = 0x7ff8000000000000
    Found by: call frame info
 3  phantomjs!JSC::JSGlobalData::JSGlobalData [JSGlobalData.cpp : 170 + 0x9]
    rbx = 0x00007f1552335000   r12 = 0x0000000002ea76b0
    r13 = 0x000000000000007f   r14 = 0x0000000000000085
    r15 = 0x00007f1552336720   rip = 0x0000000000f804ae
    rsp = 0x00007fff602473c0   rbp = 0x7ff8000000000000
    Found by: call frame info
 4  phantomjs!JSC::JSGlobalData::createLeaked [JSGlobalData.cpp : 326 + 0x9]
    rbx = 0x0000000000000000   r12 = 0x00007fff60247660
    r13 = 0x0000000002e1c370   r14 = 0x00007fff60247700
    r15 = 0x0000000002ee3760   rip = 0x0000000000f81f31
    rsp = 0x00007fff60247640   rbp = 0x00007f1552335000
    Found by: call frame info
 5  phantomjs!WebCore::JSDOMWindowBase::commonJSGlobalData [JSDOMWindowBase.cpp : 159 + 0x9]
    rbx = 0x00007fff60247750   r12 = 0x00007fff60247820
    r13 = 0x0000000002e1c370   r14 = 0x00007fff60247700
    r15 = 0x0000000002ee3760   rip = 0x0000000000514742
    rsp = 0x00007fff60247660   rbp = 0x00007f1552329000
    Found by: call frame info
 6  phantomjs!WebCore::FrameLoaderClientQt::createDocumentLoader [FrameLoaderClientQt.cpp : 990 + 0x4]
    rbx = 0x00007fff60247750   r12 = 0x00007fff60247820
    r13 = 0x0000000002e1c370   r14 = 0x00007fff60247700
    r15 = 0x0000000002ee3760   rip = 0x00000000004b03cd
    rsp = 0x00007fff60247690   rbp = 0x00007f1552329000
    Found by: call frame info
 7  phantomjs!WebCore::FrameLoader::load [FrameLoader.cpp : 1460 + 0x13]
    rbx = 0x0000000000000000   r12 = 0x00007f155232c478
    r13 = 0x0000000002e20b00   r14 = 0x0000000002f55940
    r15 = 0x0000000002ee3760   rip = 0x000000000085c047
    rsp = 0x00007fff602476c0   rbp = 0x0000000000000001
    Found by: call frame info
 8  phantomjs!QWebFrame::setHtml [qwebframe.cpp : 976 + 0x1d]
    rbx = 0x0000000000000000   r12 = 0x00007f1552366440
    r13 = 0x0000000002e20b00   r14 = 0x0000000002f55940
    r15 = 0x0000000002ee3760   rip = 0x0000000000479b91
    rsp = 0x00007fff60247750   rbp = 0x0000000000000001
    Found by: call frame info
 9  phantomjs!WebPage::WebPage [webpage.cpp : 323 + 0x12]
    rbx = 0x0000000002f55920   r12 = 0x00007fff60247af0
    r13 = 0x00007fff60247ae0   r14 = 0x0000000002f55940
    r15 = 0x0000000002f55948   rip = 0x000000000041832e
    rsp = 0x00007fff602479e0   rbp = 0x0000000002f556f0
    Found by: call frame info
10  phantomjs!Phantom::init [phantom.cpp : 102 + 0x40]
    rbx = 0x0000000002f556f0   r12 = 0x0000000002f06bd0
    r13 = 0x0000000002f06b70   r14 = 0x00007fff602480b0
    r15 = 0x0000000000000000   rip = 0x0000000000409be3
    rsp = 0x00007fff60247b40   rbp = 0x00007fff60247db0
    Found by: call frame info
11  phantomjs!Phantom::instance [phantom.cpp : 154 + 0x4]
    rbx = 0x00007fff602481c0   r12 = 0x00007fff60248140
    r13 = 0x00007fff602482e8   r14 = 0x00007fff602480b0
    r15 = 0x0000000000000000   rip = 0x000000000040b566
    rsp = 0x00007fff60248080   rbp = 0x0000000002f06b70
    Found by: call frame info
12  phantomjs!main [main.cpp : 114 + 0x4]
    rbx = 0x00007fff602481c0   r12 = 0x00007fff60248140
    r13 = 0x00007fff602482e8   r14 = 0x00007fff602480b0
    r15 = 0x0000000000000000   rip = 0x0000000000427c2e
    rsp = 0x00007fff602480a0   rbp = 0x00007fff602482d8
    Found by: call frame info
13  libc-2.12.so + 0x1ecdc
    rbx = 0x0000000000000000   r12 = 0x0000000000407cc0
    r13 = 0x00007fff602482d0   r14 = 0x0000000000000000
    r15 = 0x0000000000000000   rip = 0x00007f1550c05cdd
    rsp = 0x00007fff60248200   rbp = 0x0000000000000000
    Found by: call frame info
14  phantomjs + 0x279ef
    rip = 0x00000000004279f0   rsp = 0x00007fff60248220
    Found by: stack scanning

Thread 1
 0  libpthread-2.12.so + 0xb43c
    rbx = 0x0000000002ad9088   r12 = 0x0000000002acafe0
    r13 = 0x00007f154f0199c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007f155172543c
    rsp = 0x00007f154f018de0   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  phantomjs!WTF::TCMalloc_PageHeap::scavengerThread [FastMalloc.cpp : 2495 + 0x7]
    rip = 0x00000000004d4ebc   rsp = 0x00007f154f018e10
    Found by: stack scanning
 2  phantomjs!WTF::TCMalloc_PageHeap::runScavengerThread [FastMalloc.cpp : 1618 + 0x4]
    rbx = 0x0000000000000000   r12 = 0x00007f155172b200
    r13 = 0x00007f154f0199c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00000000004d5059
    rsp = 0x00007f154f018e90   rbp = 0x0000000000000000
    Found by: call frame info
 3  libpthread-2.12.so + 0x7850
    rbx = 0x0000000000000000   r12 = 0x00007f155172b200
    r13 = 0x00007f154f0199c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007f1551721851
    rsp = 0x00007f154f018ea0   rbp = 0x0000000000000000
    Found by: call frame info
 4  libpthread-2.12.so + 0x111ff
    rip = 0x00007f155172b200   rsp = 0x00007f154f018f48
    Found by: stack scanning
 5  libpthread-2.12.so + 0x111ff
    rip = 0x00007f155172b200   rsp = 0x00007f154f018fc0
    Found by: stack scanning
 6  libc-2.12.so + 0xe811c
    rip = 0x00007f1550ccf11d   rsp = 0x00007f154f018fe0
    Found by: stack scanning

Thread 2
 0  libc-2.12.so + 0xe0d03
    rbx = 0x0000000000000000   r12 = 0x00007f154e617d70
    r13 = 0x0000000000000008   r14 = 0x00007f1548000a98
    r15 = 0x00007f1548000d30   rip = 0x00007f1550cc7d03
    rsp = 0x00007f154e617b40   rbp = 0x00007f15480008e0
    Found by: given as instruction pointer in context
 1  phantomjs!qt_safe_select [qcore_unix.cpp : 83 + 0x15]
    rip = 0x0000000001cfcf27   rsp = 0x00007f154e617b50
    Found by: stack scanning
 2  phantomjs!QEventDispatcherUNIXPrivate::doSelect [qeventdispatcher_unix.cpp : 223 + 0xd]
    rbx = 0x00007f15480012b0   r12 = 0x00007f154e617d70
    r13 = 0x00007f15480008e0   r14 = 0x0000000000000000
    r15 = 0x00007f1548000d30   rip = 0x0000000001cfe1e7
    rsp = 0x00007f154e617be0   rbp = 0x00007f15480008e0
    Found by: call frame info
 3  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 937 + 0x4]
    rbx = 0x00007f15480012b0   r12 = 0x00007f154e617d70
    r13 = 0x00007f15480008c0   r14 = 0x0000000000000001
    r15 = 0x0000000002e11d18   rip = 0x0000000001cfec92
    rsp = 0x00007f154e617d20   rbp = 0x00007f15480008e0
    Found by: call frame info
 4  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x00007f15480012b0   r12 = 0x00007f154e617e00
    r13 = 0x00007f154e617e10   r14 = 0x0000000002bfe230
    r15 = 0x0000000002e11d18   rip = 0x0000000001cd40b5
    rsp = 0x00007f154e617d70   rbp = 0x00007f154e617db0
    Found by: call frame info
 5  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x00007f15480012b0   r12 = 0x00007f154e617e00
    r13 = 0x00007f154e617e10   r14 = 0x0000000002bfe230
    r15 = 0x0000000002e11d18   rip = 0x0000000001cd4518
    rsp = 0x00007f154e617da0   rbp = 0x00007fff60248140
    Found by: call frame info
 6  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
    rbx = 0x0000000002e11c90   r12 = 0x0000000002e11d18
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000000001bd69f6
    rsp = 0x00007f154e617e00   rbp = 0x0000000002e11d18
    Found by: call frame info
 7  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x0000000002e11d18   r12 = 0x0000000002e11d90
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000000001bd98c2
    rsp = 0x00007f154e617e50   rbp = 0x0000000002ea8ea0
    Found by: call frame info
 8  libpthread-2.12.so + 0x7850
    rbx = 0x0000000000000000   r12 = 0x00007fff60247620
    r13 = 0x00007f154e6189c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007f1551721851
    rsp = 0x00007f154e617ea0   rbp = 0x0000000000000000
    Found by: call frame info

Loaded modules:
0x00400000 - 0x026e3fff  phantomjs  ???  (main)
0x7f154f01a000 - 0x7f154f237fff  libselinux.so.1  ???
0x7f154f239000 - 0x7f154f450fff  libresolv-2.12.so  ???
0x7f154f453000 - 0x7f154f655fff  libkeyutils.so.1.3  ???
0x7f154f656000 - 0x7f154f860fff  libkrb5support.so.0.1  ???
0x7f154f861000 - 0x7f154fa8cfff  libk5crypto.so.3.1  ???
0x7f154fa8d000 - 0x7f154fc90fff  libcom_err.so.2.1  ???
0x7f154fc91000 - 0x7f154ff6ffff  libkrb5.so.3.3  ???
0x7f154ff70000 - 0x7f15501b1fff  libgssapi_krb5.so.2.2  ???
0x7f15501b2000 - 0x7f155040efff  libssl.so.1.0.0  ???
0x7f155040f000 - 0x7f1550624fff  libz.so.1.2.3  ???
0x7f1550625000 - 0x7f15509bafff  libcrypto.so.1.0.0  ???
0x7f15509bf000 - 0x7f1550be6fff  libexpat.so.1.5.2  ???
0x7f1550be7000 - 0x7f1550f74fff  libc-2.12.so  ???
0x7f1550f7a000 - 0x7f155118ffff  libgcc_s-4.4.7-20120601.so.1  ???
0x7f1551190000 - 0x7f1551413fff  libm-2.12.so  ???
0x7f1551414000 - 0x7f1551704fff  libstdc++.so.6.0.13  ???
0x7f155171a000 - 0x7f1551932fff  libpthread-2.12.so  ???
0x7f1551937000 - 0x7f1551b3efff  librt-2.12.so  ???
0x7f1551b3f000 - 0x7f1551d42fff  libdl-2.12.so  ???
0x7f1551d43000 - 0x7f1551f78fff  libfontconfig.so.1.4.4  ???
0x7f1551f79000 - 0x7f1552215fff  libfreetype.so.6.3.22  ???
0x7f1552216000 - 0x7f1552235fff  ld-2.12.so  ???
0x7fff603ae000 - 0x7fff603affff  linux-gate.so  ???
-bash-4.1# ./minidump_stackwalk  /tmp/2816757d-f562-7461-17fe084a-19b50fe7.dmp . 2>/dev/null > dump.txt
-bash-4.1# more<dump.txt
Operating system: Linux
                  0.0.0 Linux 2.6.32-042stab061.2 #1 SMP Fri Aug 24 09:07:21 MSK 2012 x86_64
CPU: amd64
     family 15 model 65 stepping 2
     4 CPUs

Crash reason:  SIGSEGV
Crash address: 0xbbadbeef

Thread 0 (crashed)
 0  phantomjs!WTF::OSAllocator::reserveUncommitted [OSAllocatorPosix.cpp : 107 + 0x7]
    rbx = 0xffffffffffffffff   r12 = 0x0000000002e20bc0
    r13 = 0x000000000000007f   r14 = 0x00007f1552336820
    r15 = 0x00007f1552336720   rip = 0x00000000004ef417
    rsp = 0x00007fff602472f0   rbp = 0x7ff8000000000000
    Found by: given as instruction pointer in context
 1  phantomjs!JSC::ExecutableAllocator::isValid [PageReservation.h : 107 + 0x18]
    rbx = 0x0000000002e20ba0   r12 = 0x0000000002e20bc0
    r13 = 0x000000000000007f   r14 = 0x00007f1552336820
    r15 = 0x00007f1552336720   rip = 0x0000000000f28951
    rsp = 0x00007fff60247300   rbp = 0x7ff8000000000000
    Found by: call frame info
 2  phantomjs!JSC::ExecutableAllocator::ExecutableAllocator [ExecutableAllocator.h : 185 + 0x7]
    rbx = 0x0000000002af3ad8   r12 = 0x0000000002ea76b0
    r13 = 0x000000000000007f   r14 = 0x00007f1552336820
    r15 = 0x00007f1552336720   rip = 0x0000000000f7f6e6
    rsp = 0x00007fff60247350   rbp = 0x7ff8000000000000
    Found by: call frame info
 3  phantomjs!JSC::JSGlobalData::JSGlobalData [JSGlobalData.cpp : 170 + 0x9]
    rbx = 0x00007f1552335000   r12 = 0x0000000002ea76b0
    r13 = 0x000000000000007f   r14 = 0x0000000000000085
    r15 = 0x00007f1552336720   rip = 0x0000000000f804ae
    rsp = 0x00007fff602473c0   rbp = 0x7ff8000000000000
    Found by: call frame info
 4  phantomjs!JSC::JSGlobalData::createLeaked [JSGlobalData.cpp : 326 + 0x9]
    rbx = 0x0000000000000000   r12 = 0x00007fff60247660
    r13 = 0x0000000002e1c370   r14 = 0x00007fff60247700
    r15 = 0x0000000002ee3760   rip = 0x0000000000f81f31
    rsp = 0x00007fff60247640   rbp = 0x00007f1552335000
    Found by: call frame info
 5  phantomjs!WebCore::JSDOMWindowBase::commonJSGlobalData [JSDOMWindowBase.cpp : 159 + 0x9]
    rbx = 0x00007fff60247750   r12 = 0x00007fff60247820
    r13 = 0x0000000002e1c370   r14 = 0x00007fff60247700
    r15 = 0x0000000002ee3760   rip = 0x0000000000514742
    rsp = 0x00007fff60247660   rbp = 0x00007f1552329000
    Found by: call frame info
 6  phantomjs!WebCore::FrameLoaderClientQt::createDocumentLoader [FrameLoaderClientQt.cpp : 990 + 0x4]
    rbx = 0x00007fff60247750   r12 = 0x00007fff60247820
    r13 = 0x0000000002e1c370   r14 = 0x00007fff60247700
    r15 = 0x0000000002ee3760   rip = 0x00000000004b03cd
    rsp = 0x00007fff60247690   rbp = 0x00007f1552329000
    Found by: call frame info
 7  phantomjs!WebCore::FrameLoader::load [FrameLoader.cpp : 1460 + 0x13]
    rbx = 0x0000000000000000   r12 = 0x00007f155232c478
    r13 = 0x0000000002e20b00   r14 = 0x0000000002f55940
    r15 = 0x0000000002ee3760   rip = 0x000000000085c047
    rsp = 0x00007fff602476c0   rbp = 0x0000000000000001
    Found by: call frame info
 8  phantomjs!QWebFrame::setHtml [qwebframe.cpp : 976 + 0x1d]
    rbx = 0x0000000000000000   r12 = 0x00007f1552366440
    r13 = 0x0000000002e20b00   r14 = 0x0000000002f55940
    r15 = 0x0000000002ee3760   rip = 0x0000000000479b91
    rsp = 0x00007fff60247750   rbp = 0x0000000000000001
    Found by: call frame info
 9  phantomjs!WebPage::WebPage [webpage.cpp : 323 + 0x12]
    rbx = 0x0000000002f55920   r12 = 0x00007fff60247af0
    r13 = 0x00007fff60247ae0   r14 = 0x0000000002f55940
    r15 = 0x0000000002f55948   rip = 0x000000000041832e
    rsp = 0x00007fff602479e0   rbp = 0x0000000002f556f0
    Found by: call frame info
10  phantomjs!Phantom::init [phantom.cpp : 102 + 0x40]
    rbx = 0x0000000002f556f0   r12 = 0x0000000002f06bd0
    r13 = 0x0000000002f06b70   r14 = 0x00007fff602480b0
    r15 = 0x0000000000000000   rip = 0x0000000000409be3
    rsp = 0x00007fff60247b40   rbp = 0x00007fff60247db0
    Found by: call frame info
11  phantomjs!Phantom::instance [phantom.cpp : 154 + 0x4]
    rbx = 0x00007fff602481c0   r12 = 0x00007fff60248140
    r13 = 0x00007fff602482e8   r14 = 0x00007fff602480b0
    r15 = 0x0000000000000000   rip = 0x000000000040b566
    rsp = 0x00007fff60248080   rbp = 0x0000000002f06b70
    Found by: call frame info
12  phantomjs!main [main.cpp : 114 + 0x4]
    rbx = 0x00007fff602481c0   r12 = 0x00007fff60248140
    r13 = 0x00007fff602482e8   r14 = 0x00007fff602480b0
    r15 = 0x0000000000000000   rip = 0x0000000000427c2e
    rsp = 0x00007fff602480a0   rbp = 0x00007fff602482d8
    Found by: call frame info
13  libc-2.12.so + 0x1ecdc
    rbx = 0x0000000000000000   r12 = 0x0000000000407cc0
    r13 = 0x00007fff602482d0   r14 = 0x0000000000000000
    r15 = 0x0000000000000000   rip = 0x00007f1550c05cdd
    rsp = 0x00007fff60248200   rbp = 0x0000000000000000
    Found by: call frame info
14  phantomjs + 0x279ef
    rip = 0x00000000004279f0   rsp = 0x00007fff60248220
    Found by: stack scanning

Thread 1
 0  libpthread-2.12.so + 0xb43c
    rbx = 0x0000000002ad9088   r12 = 0x0000000002acafe0
    r13 = 0x00007f154f0199c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007f155172543c
    rsp = 0x00007f154f018de0   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  phantomjs!WTF::TCMalloc_PageHeap::scavengerThread [FastMalloc.cpp : 2495 + 0x7]
    rip = 0x00000000004d4ebc   rsp = 0x00007f154f018e10
    Found by: stack scanning
 2  phantomjs!WTF::TCMalloc_PageHeap::runScavengerThread [FastMalloc.cpp : 1618 + 0x4]
    rbx = 0x0000000000000000   r12 = 0x00007f155172b200
    r13 = 0x00007f154f0199c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00000000004d5059
    rsp = 0x00007f154f018e90   rbp = 0x0000000000000000
    Found by: call frame info
 3  libpthread-2.12.so + 0x7850
    rbx = 0x0000000000000000   r12 = 0x00007f155172b200
    r13 = 0x00007f154f0199c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007f1551721851
    rsp = 0x00007f154f018ea0   rbp = 0x0000000000000000
    Found by: call frame info
 4  libpthread-2.12.so + 0x111ff
    rip = 0x00007f155172b200   rsp = 0x00007f154f018f48
    Found by: stack scanning
 5  libpthread-2.12.so + 0x111ff
    rip = 0x00007f155172b200   rsp = 0x00007f154f018fc0
    Found by: stack scanning
 6  libc-2.12.so + 0xe811c
    rip = 0x00007f1550ccf11d   rsp = 0x00007f154f018fe0
    Found by: stack scanning

Thread 2
 0  libc-2.12.so + 0xe0d03
    rbx = 0x0000000000000000   r12 = 0x00007f154e617d70
    r13 = 0x0000000000000008   r14 = 0x00007f1548000a98
    r15 = 0x00007f1548000d30   rip = 0x00007f1550cc7d03
    rsp = 0x00007f154e617b40   rbp = 0x00007f15480008e0
    Found by: given as instruction pointer in context
 1  phantomjs!qt_safe_select [qcore_unix.cpp : 83 + 0x15]
    rip = 0x0000000001cfcf27   rsp = 0x00007f154e617b50
    Found by: stack scanning
 2  phantomjs!QEventDispatcherUNIXPrivate::doSelect [qeventdispatcher_unix.cpp : 223 + 0xd]
    rbx = 0x00007f15480012b0   r12 = 0x00007f154e617d70
    r13 = 0x00007f15480008e0   r14 = 0x0000000000000000
    r15 = 0x00007f1548000d30   rip = 0x0000000001cfe1e7
    rsp = 0x00007f154e617be0   rbp = 0x00007f15480008e0
    Found by: call frame info
 3  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 937 + 0x4]
    rbx = 0x00007f15480012b0   r12 = 0x00007f154e617d70
    r13 = 0x00007f15480008c0   r14 = 0x0000000000000001
    r15 = 0x0000000002e11d18   rip = 0x0000000001cfec92
    rsp = 0x00007f154e617d20   rbp = 0x00007f15480008e0
    Found by: call frame info
 4  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x00007f15480012b0   r12 = 0x00007f154e617e00
    r13 = 0x00007f154e617e10   r14 = 0x0000000002bfe230
    r15 = 0x0000000002e11d18   rip = 0x0000000001cd40b5
    rsp = 0x00007f154e617d70   rbp = 0x00007f154e617db0
    Found by: call frame info
 5  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x00007f15480012b0   r12 = 0x00007f154e617e00
    r13 = 0x00007f154e617e10   r14 = 0x0000000002bfe230
    r15 = 0x0000000002e11d18   rip = 0x0000000001cd4518
    rsp = 0x00007f154e617da0   rbp = 0x00007fff60248140
    Found by: call frame info
 6  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
    rbx = 0x0000000002e11c90   r12 = 0x0000000002e11d18
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000000001bd69f6
    rsp = 0x00007f154e617e00   rbp = 0x0000000002e11d18
    Found by: call frame info
 7  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x0000000002e11d18   r12 = 0x0000000002e11d90
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000000001bd98c2
    rsp = 0x00007f154e617e50   rbp = 0x0000000002ea8ea0
    Found by: call frame info
 8  libpthread-2.12.so + 0x7850
    rbx = 0x0000000000000000   r12 = 0x00007fff60247620
    r13 = 0x00007f154e6189c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007f1551721851
    rsp = 0x00007f154e617ea0   rbp = 0x0000000000000000
    Found by: call frame info

Loaded modules:
0x00400000 - 0x026e3fff  phantomjs  ???  (main)
0x7f154f01a000 - 0x7f154f237fff  libselinux.so.1  ???
0x7f154f239000 - 0x7f154f450fff  libresolv-2.12.so  ???
0x7f154f453000 - 0x7f154f655fff  libkeyutils.so.1.3  ???
0x7f154f656000 - 0x7f154f860fff  libkrb5support.so.0.1  ???
0x7f154f861000 - 0x7f154fa8cfff  libk5crypto.so.3.1  ???
0x7f154fa8d000 - 0x7f154fc90fff  libcom_err.so.2.1  ???
0x7f154fc91000 - 0x7f154ff6ffff  libkrb5.so.3.3  ???
0x7f154ff70000 - 0x7f15501b1fff  libgssapi_krb5.so.2.2  ???
0x7f15501b2000 - 0x7f155040efff  libssl.so.1.0.0  ???
0x7f155040f000 - 0x7f1550624fff  libz.so.1.2.3  ???
0x7f1550625000 - 0x7f15509bafff  libcrypto.so.1.0.0  ???
0x7f15509bf000 - 0x7f1550be6fff  libexpat.so.1.5.2  ???
0x7f1550be7000 - 0x7f1550f74fff  libc-2.12.so  ???
0x7f1550f7a000 - 0x7f155118ffff  libgcc_s-4.4.7-20120601.so.1  ???
0x7f1551190000 - 0x7f1551413fff  libm-2.12.so  ???
0x7f1551414000 - 0x7f1551704fff  libstdc++.so.6.0.13  ???
0x7f155171a000 - 0x7f1551932fff  libpthread-2.12.so  ???
0x7f1551937000 - 0x7f1551b3efff  librt-2.12.so  ???
0x7f1551b3f000 - 0x7f1551d42fff  libdl-2.12.so  ???
0x7f1551d43000 - 0x7f1551f78fff  libfontconfig.so.1.4.4  ???
0x7f1551f79000 - 0x7f1552215fff  libfreetype.so.6.3.22  ???
0x7f1552216000 - 0x7f1552235fff  ld-2.12.so  ???
0x7fff603ae000 - 0x7fff603affff  linux-gate.so  ???
-bash-4.1#
-bash-4.1#

**Comment by dasAnderl** [comment]
for me the problem was missing npm weak dependency. fix:

sudo apt-get install build-essential
sudo npm install weak
sudo npm install phantomjs
