### ISSUE TITLE
'[object EventConstructor]' is not a constructor

### ISSUE THREAD

**Issue by davidcelis** [ariya/phantomjs#11289]
This seems like a PhantomJS bug, but feel free to educate me if otherwise.

If I put `new Event(message)` in a Jasmine test and run it under PhantomJS's headless browser, I get an error saying `'[object EventConstructor]' is not a constructor`. This is weird, considering EventConstructor is probably really a constructor. If I run the Jasmine test normally (i.e. fire up a Jasmine server and let the test run in my actual browser), it works.

To fix the test on Phantom, I have to change `new Event();` to `document.createEvent();`, which is deprecated.

**Comment by blesh** [comment]
"Fixed in 2.0" ... 6 months later, no 2.0. :(

**Comment by Robdel12** [comment]
^ I ended up applying a hacky polyfill just to keep Travis CI building.

**Comment by blesh** [comment]
same.

**Comment by Drahakar** [comment]
An [announcement was made on the mailing list](https://groups.google.com/d/msg/phantomjs-dev/4lu3FeGjCvE/9SCODuEPWmcJ), the version 2.0 is supposed to happen on Jan 23th.

**Comment by Robdel12** [comment]
Woop!

**Comment by aviynw** [comment]
UM...wasn't this supposed to be fixed in the 2.0 release?  I'm still getting 
MouseEventConstructor is not a constructor (evaluating 'new MouseEvent')

**Comment by ahri** [comment]
I compiled 2.0 for linux, and I find that I still experience this exception when using the "new" keyword to construct a MouseEvent.

**Comment by fabiosussetto** [comment]
same here...

**Comment by sukima** [comment]
@Vitallium please re-open this issue.

**Comment by ourmaninamsterdam** [comment]
I'm using [this shim](https://github.com/Raynos/DOM-shim/blob/master/src/all/interfaces/Event.js) until support comes to Phantom.

**Comment by JamesMGreene** [comment]
Reopened for now.

**Comment by Ajedi32** [comment]
So to clarify, the `'[object EventConstructor]' is not a constructor` error in particular is fixed in 2.0 right? It's just `MouseEventConstructor is not a constructor (evaluating 'new MouseEvent')` that's still a problem, correct?

**Comment by zackw** [comment]
Confirming that the "new" way to create synthetic events is still not supported in 2.0.  I guess the newer Webkit in 2.0 is not new *enough*.  (We are painfully aware of how slow we are at picking up new iterations of Webkit.)

**Comment by zackw** [comment]
@Ajedi32 Yes, `new Event(...)` seems to be accepted without error in 2.0, but not `new MouseEvent(...)`.

**Comment by evandavis** [comment]
`MouseEventConstructor is not a constructor (evaluating 'new MouseEvent')` just bit me.

**Comment by bucaran** [comment]
What is the solution?

**Comment by bucaran** [comment]
@ariya Hi. Is there a solution for this already or am I missing something?

**Comment by mmahalwy** [comment]
Any updates on this?

**Comment by lazylester** [comment]
this may not work for everyone, but as a workaround jQuery seems to provide a cross-browser (including phantomjs) Event object constructor: $.Event(event)

**Comment by xldenis** [comment]
Any recent news on this issue?

**Comment by bucaran** [comment]
Well, I had to quit that company because I couldn't solve the issue. Just kidding, maybe.

**Comment by Vitallium** [comment]
Here is the list of all supported events in 2.x version:
```
BeforeLoadEvent
CloseEvent
CompositionEvent
CustomEvent
ErrorEvent
FocusEvent
HashChangeEvent
KeyboardEvent
KeyboardEvents
MessageEvent
MouseEvent
MouseEvents
MutationEvent
MutationEvents
OverflowEvent
PageTransitionEvent
PopStateEvent
ProgressEvent
TextEvent
TransitionEvent
WebKitAnimationEvent
WebKitTransitionEvent
WheelEvent
XMLHttpRequestProgressEvent
StorageEvent
SVGEvents
SVGZoomEvent
SVGZoomEvents
TouchEvent
CSSFontFaceLoadEvent
SecurityPolicyViolationEvent
```

**Comment by Robdel12** [comment]
Is there an easy way to install 2.x yet?

**Comment by ortexx** [comment]
`new WheelEvent.contructor is not contructor`

v 2.0

**Comment by sirLisko** [comment]
I resolved using [`simulant`](https://www.npmjs.com/package/simulant).

```javascript
var fakeEvent = require('simulant');
fakeEvent.fire(ghost, fakeEvent('mousemove'));
```

 It nicely wraps around the event API and it works also with phantom 1.9.x.

**Comment by wzhscript** [comment]
@sirLisko thx, simulant solved my problem too.

**Comment by ortexx** [comment]
WheelEvent is not working, with <simulant> too (v 2.1, ubuntu)

**Comment by inf3rno** [comment]
+1, I still have to use `document.createEvent('MouseEvent');` instead of `new MouseEvent()`.

**Comment by bttf** [comment]
I'm also getting this error, using v2.1.7, after the following call:

` let event = new window.Event('mousedown', { bubbles: true, cancelable: true, view: window });`

**Comment by perrin4869** [comment]
Same problem with phantomjs@2.1.1 (using npm's `phantomjs-prebuilt`):

```
KeyboardEventConstructor is not a constructor (evaluating 'new KeyboardEvent('keydown', {
                      key: 'a',
                      keyCode: 65,
                      which: 65
                    })')
```

**Comment by aem** [comment]
also on 2.1.1, still seeing `TypeError: KeyboardEventConstructor is not a constructor`

**Comment by astrotim** [comment]
My workaround to get tests working in both browsers and PhantomJS:

```javascript
var clickEvent;
var keyupEvent;

// check if Event() is a constructor function
// usage as per the spec, if true
if (typeof(Event) === 'function') {

	clickEvent = new MouseEvent('click');
	clickEvent.initMouseEvent('click');

	keyupEvent = new Event('keyup');

// the deprecated way for PhantomJS
} else {

	clickEvent = document.createEvent('CustomEvent');
	clickEvent.initCustomEvent('click', false, false, null);

	keyupEvent = document.createEvent('CustomEvent');
	keyupEvent.initCustomEvent('keyup', false, false, null);

}
```

*Usage:*

```javascript
submitButton.dispatchEvent(click);
textInput.dispatchEvent(keyup);
```

**Comment by dwightdegroff** [comment]
Any progress here? Still running into" 
`TypeError: MouseEventConstructor is not a constructor (evaluating 'new MouseEvent("click")')`

On PhantomJS 2.1.1

**Comment by evandavis** [comment]
@dwightdegroff I switched to jsDOM 6 months ago and have never been happier.

**Comment by cantonic** [comment]
we have failing tests because of `TypeError: MouseEventConstructor is not a constructor (evaluating 'new MouseEvent("click")')` and tried using PhantomJS 2.5.0-beta on TravisCI. Now all tests that were failing with the mentioned error are now failing with this:
```
Capybara::Poltergeist::DeadClient:
        PhantomJS client died while processing {"id":"9600aa3c-0be5-40f3-9010-018c39322890","name":"visit","args":["http://127.0.0.1:35752/messages/conversations",30]}
```

**Comment by cantonic** [comment]
Not sure if this will help anyone else, but we were able to solve the issue by tracking it down to `opal-browser` gem. This commit fixes it for us: https://github.com/opal/opal-browser/commit/6791db2dc63ea9bbe3b01444c4360813534d601d

**Comment by runarberg** [comment]
This short shim worked for me:

```js
function keyboardEvent(eventType, init) {
  try {
    return new KeyboardEvent(eventType, init);
  } catch (error) {
    const modKeys = [
      init.ctrlKey ? 'Control' : '',
      init.shiftKey ? 'Shift' : '',
      init.altKey ? 'Alt' : '',
      init.altGrKey ? 'AltGr' : '',
      init.metaKey ? 'Meta' : '',
    ].join(' ');
    const keyEvent = document.createEvent('KeyboardEvent');
    keyEvent.initKeyboardEvent(
      eventType,
      false,
      false,
      window,
      init.char || '',
      init.keyCode || 0,
      modKeys,
      init.repeat || false,
    );
    keyEvent.key = init.key;

    return keyEvent;
  }
}
```
And using it like so:

```js
document.body.dispatchEvent(keyboardEvent('keydown', { key: 'Escape' }));
```

**Comment by inf3rno** [comment]
@astrotim Creating some kind of polyfill would be better.

**Comment by bertofer** [comment]
We have faced this problem as well. In our case, we were using angular 2 testing and doing some MouseEvent with clientX and clientY properties. All the tests were working until we changed to PhantomJS instead of Chrome for CI, then we faced this. 

We could fix it for PhantomJS, instead of creating a MouseEvent, creating an Event passing clientX and clientY properties, but then the typescript compiler complained that clientX and clientY are not properties expected on the properties passed to the event. 

We ended up just doing:
```typescript
const evtOpts = {
      clientX: component.menuContainer.nativeElement.offsetLeft + 1,
      clientY: component.menuContainer.nativeElement.offsetTop + 1
};
window.dispatchEvent(new Event('mousedown', evtOpts));
```
This way, evtOpts gets an implicit any, so when passed to Event constructor, TS does not complain, and PhantomJS works.

**Comment by justingrayston** [comment]
@runarberg I hope you don't mind, but I created your function into a phantomJS polyfil. As above, I wanted to test in Angular2+ in Typescript and it type checking complained about the assignment of readonly properties. Being able to load it in via yarn or npm means it is outside of the linted code. It also makes it easily available to all.

https://github.com/justingrayston/basic-keyboard-event-polyfill

**Comment by runarberg** [comment]
@justingrayston Sure, go ahead.

FYI: I extracted the vital bits from https://github.com/termi/DOM-Keyboard-Event-Level-3-polyfill.

**Comment by ghiscoding** [comment]
In order to fix the 

```javascript
MouseEventConstructor is not a constructor (evaluating 'new MouseEvent')
```

I used the `Polyfill` from the [MSDN MouseEvent docs](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent#Polyfill) and that finally worked.

**Comment by inf3rno** [comment]
Probably creating a repo including both polyfills, and publishing it on npm as phantomjs-event-polyfill would be a wise idea until this is fixed.

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!

**Comment by lechu1985** [comment]
For the same reasons as @justingrayston I created a npm package for helping PhantomJS with Mouse Events. It is based on the solution provided by: @ghiscoding 

https://github.com/lechu1985/basic-mouse-event-polyfill-phantomjs

**Comment by fgc29** [comment]
I been experiencing a sort of similar problem. TypeError: undefined is not a constructor (evaluating 'targetElement.closest('tr')'). The arg 'targetElement' is the supposed to be the DOM target element retrieved from event.target. But event.target is only returning the href in a string. Has anyone had this happen and if so, were you able to resolve it? This is for a rails 5 system test using poltergeist to run the headless test.

**Comment by inf3rno** [comment]
Great, so a 6 years old confirmed bug was not fixed. Is this repo even maintained?

**Comment by HolgerJeromin** [comment]
Cleanup is a very strong sign of restart of maintenance. 
There are no recources to check every 1400 issues if they are still valid. If they are still valid and important they can be reopened.
