### ISSUE TITLE
1.9 not rendering SVG at all

### ISSUE THREAD

**Issue by Yermo** [ariya/phantomjs#11281]
I am trying to take screenshots of a Leaflet based Map with SVG polylines drawn on it. No SVG elements are rendered in the resulting png.

What steps will reproduce the problem?
1. phantomjs examples/rasterize.js http://leafletjs.com/examples/geojson-example.html test.png
2. look at test.png
3. Note that none of the SVG elements are present

What is the expected output? What do you see instead?
Expected: The map to be what's viewed in Chrome/FireFox/etc.
Actual: No SVG rendered.

What version of the product are you using? On what operating system?
Tested version 1.9:
   binary for Windows under Windows 7
   binary for Linux 32bit under Fedora Core 15
   source for Linux 32bit under Fedora Core 15

Please provide any additional information below.

I have read through the issue list and it seems some people are getting some success with rendering SVG but I am unable to get SVG to render at all.

**Comment by Frozenfire92** [comment]
@cesarvarela Want to give a huge thank you and then add some tags to this issue for people who have been googling away with no results

###Tags for google
casperjs no png no svg no render no capture not capturing not rendering svg

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
