### ISSUE TITLE
URI's are encoded as Latin-1

### ISSUE THREAD

**Issue by pieter** [ariya/phantomjs#11294]
In general, URL's with non-ASCII code points are encoded to UTF-8, and the resulting bytes are then percent-encoded:

http://www.w3.org/TR/html40/appendix/notes.html#non-ascii-chars

Mongoose by default decodes percent-encoded characters, but is not encoding aware. In PhantomJS the uri's are percent-encoded again, but with a Latin-1 charset:

https://github.com/detro/phantomjs/blob/master/src/webserver.cpp#L183

This means that URI's containing non-ASCII characters are re-encoded in the wrong way, since we interpret the utf-8 bytes as latin-1 characters.

We should either change the `fromLatin1` to `fromUtf8` to correspond with standard web practices, or get the non-decoded uri out of mongoose somehow.

**Comment by silkentrance** [comment]
In HTTP all protocol level information such as headers, paths etc. are encoded using standard US-ASCII. 
All other data such as request bodies/response bodies and header field values and also get query parameters might be encoded differently, most prominently here the url encoding scheme.

There is no UTF8 in HTTP, just plain old US-ASCII.
