### ISSUE TITLE
Support Content-Encoding: X-Gzip 

### ISSUE THREAD

**Issue by baudehlo** [ariya/phantomjs#11296]
Some web sites (notably Scotiabank) return gzipped content with:

    Content-Encoding: x-gzip

Which I realise is completely invalid, but it works with client browsers.

Here's a patch to support it:

    @@ -320,7 +320,7 @@ qint64 QHttpNetworkReplyPrivate::bytesAvailable() const
     bool QHttpNetworkReplyPrivate::isGzipped()
     {
         QByteArray encoding = headerField("content-encoding");
    -    return qstricmp(encoding.constData(), "gzip") == 0;
    +    return (qstricmp(encoding.constData(), "gzip") == 0 || qstricmp(encoding.constData(), "x-gzip") == 0);
     }
     
     void QHttpNetworkReplyPrivate::removeAutoDecompressHeader()

**Comment by siboulet** [comment]
I also need support for x-gzip.

As per RFC http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.5

>  Use of program names for the identification of encoding formats
        is not desirable and is discouraged for future encodings. Their
        use here is representative of historical practice, not good
        design. For compatibility with previous implementations of HTTP,
        applications SHOULD consider "x-gzip" and "x-compress" to be
        equivalent to "gzip" and "compress" respectively.

**Comment by siboulet** [comment]
Any chances we can get this fix in for 2.1?

**Comment by ariya** [comment]
We just rely on Qt network stack. Please file this as a report to the upstream project: https://bugreports.qt.io/browse/QTBUG.
