### ISSUE TITLE
Content-Security-Policy prevents resource loading?

### ISSUE THREAD

**Issue by arielschwartz** [ariya/phantomjs#11337]
When trying to load http://github.com , I get the following warning for several resources:

[info] [remote] Refused to load style from 'https://a248.e.akamai.net/assets.github.com/assets/github-fdebe8d3f60746fb87c763a59741ff520ae3d8e8.css' because of Content-Security-Policy.
It seems to be related to the CSP header in the server's response:

Content-Security-Policy:default-src *; script-src https://github.com https://a248.e.akamai.net https://jobs.github.com https://ssl.google-analytics.com https://secure.gaug.es https://collector.githubapp.com https://gist.github.com; style-src https://github.com https://a248.e.akamai.net 'unsafe-inline'; object-src https://github.com https://a248.e.akamai.net
Interestedly, the CSP header should allow loading resources from the domains specified in the CSP header, but for some reason, they can't be loaded.
https://github.com/blog/1477-content-security-policy

I'm using phantomjs 1.9. Also, setting --web-security=no does not help as well.

Should this be the normal behavior?
Is there any way to remove/filter a response header (i.e. remove the CSP header) and then reload (without making an actual http request) the page, or any other advice to mitigate this?

**Comment by brimsey** [comment]
I'm experiencing the same problem.  The tests work fine in Chrome and Firefox but fail in PhantomJS.  Curiously, the PhantomJS tests run fine on OSX but fail on Windows.  The Content-Security-Policy is preventing PhantomJS from retrieving css and javascript resources so my automated tests are failing.  Any chance we can get this fixed?  Please let me know if you need further details.

**Comment by SorX14** [comment]
I was having the same issue with phantomjs version 1.9.0; updated to version 2.0.0 and it works perfectly

**Comment by PiotrMachner** [comment]
If I remember correctly I did experiment with 2.0.0 and it did not help in my case.

Upvoting this issue: +1:

**Comment by eugenesia** [comment]
Still having this problem with PhantomJS 2.0.0 , run with a CasperJS 1.1.0-beta3 script. Upvoting as well.

**Comment by andrewmunro** [comment]
Having this issue too. Any workarounds?

**Comment by whit537** [comment]
I believe this should be closed as a duplicate of #13114.

**Comment by fipso** [comment]
Anything new here ?

**Comment by msaleh83** [comment]
PhantomJS latest stable version 2.1.1 has a bug when it tries to get a webpage that has the following response header:
content-security-policy: default-src 'none'

The Fix:
Branch 2.1.1, **File: \phantomjs\src\qt\qtwebkit\Source\WebCore\page\ContentSecurityPolicy.cpp**, Change line 354:

> , m_allowEval(false)

To:

> , m_allowEval(true)

Then build.py -r ... Enjoy!
