### ISSUE TITLE
CSS 3 -webkit-writing-mode: vertical-rl; not render 

### ISSUE THREAD

**Issue by luutuong** [ariya/phantomjs#11348]
I working with HTML page have Japan Style and Font, and I using CSS 
-webkit-writing-mode: vertical-rl; >>> when i view page with safari and chrome, this working
but when render to PNG image file this css not working

Please Help 

Thanks All

**Comment by taizan** [comment]
I met same problem

**Comment by KuroGuo** [comment]
+1

**Comment by katapad** [comment]
+1

**Comment by hao-opentown** [comment]
+1

**Comment by hao-opentown** [comment]
Try [node-webkit-screenshot](https://github.com/FWeinb/node-webkit-screenshot), behind the scene is [node-webkit](https://github.com/nwjs/nw.js)
