### ISSUE TITLE
Phantomjs crashes randomly.

### ISSUE THREAD

**Issue by ilafaf** [ariya/phantomjs#11346]
Multiple concurrent phantomjs processes make it crash randomly.

Linux x 3.2.0-43-generic #68-Ubuntu SMP Wed May 15 03:35:24 UTC 2013 i686 i686 i386 GNU/Linux
node  v0.6.12
phantomjs@1.9.0-4

Linux justitia 3.2.0-43-generic #68-Ubuntu SMP Wed May 15 03:33:33 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
node  v0.6.12
phantomjs@1.9.0-4

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
