### ISSUE TITLE
Click a link, except ajax response Dom, but there is no response Dom

### ISSUE THREAD

**Issue by kernel8liang** [ariya/phantomjs#11350]
Reproduce:
1 Get a link.
link = document.querySelector() .( this link is an ajax request,  and except response some data to modify the dom, add new element in dom.)
2 create mouse event: 
var ev = document.createEvent("MouseEvents");                                                                          ev.initMouseEvent("click", true, true)
3 link.dispatchEvent(ev)

And there is no new element create. I try in chrome console the same step, it work correcly.
I found the ajax request was sent, but will follow a page.onNavigationRequested. It seems the page was reopened.

use ubuntu server 12.04, without graphics.

**Comment by lovedboy** [comment]
I have the same problem at ubuntu server 12.04 without graphics. Both 1.9.8 and 2.0 version.
I try the solution https://newspaint.wordpress.com/2013/04/05/waiting-for-page-to-load-in-phantomjs/,but it not works. 

But 2.0 version for mac work perfect.
