### ISSUE TITLE
Url decoding

### ISSUE THREAD

**Issue by ardlema** [ariya/phantomjs#11379]
We are trying to run our Angularjs e2e tests using PhantomJS.

We have a very simple test that just calls one url and checks the path, see following:

---
describe 'Search', ->

  beforeEach ->
    browser().navigateTo('/whatever/10.1007%2F978-3-642-17078-2_1')

  it 'should be in whatever url', ->
    expect(browser().window().path()).toEqual '/whatever/10.1007%2F978-3-642-17078-2_1'
 
---

This test passes with Chrome and Firefox but is failing with PhantomJS because PhantomJS is decoding the url as following: /whatever/10.1007/978-3-642-17078-2_1.

Let me know if you need more information about my configuration files or the way I am running the tests.

Thank you in advance.

**Comment by ismyrnow** [comment]
I am also seeing this issue with 1.9.8 on Windows 8.1.

Any progress or recognition of the issue?

**Comment by knownasilya** [comment]
Also seeing this issue with 1.9.8 on OSX 10.10.4.

**Comment by zackw** [comment]
I believe this to be the same issue as #12216.  I have patches for that in my branch [zackw:phantomjs/encode-all-the-urls](https://github.com/zackw/phantomjs/tree/encode-all-the-urls).  I hope to get back around to finalizing and landing those Real Soon Now; if you would like to test them, that would be helpful.  (Sorry, I cannot provide you with binaries.)

**Comment by zackw** [comment]
(I am closing this issue as a duplicate; please subscribe to #12216 and report your results there.)
