### ISSUE TITLE
Asynchronous Sessions cleanup phase starting NOW, using Ghostdriver

### ISSUE THREAD

**Issue by biz786** [ariya/phantomjs#11378]
When I run my test suit on win7 using ghost driver, I find that intermittently some of the texts will hang for a very long time (15 mins to half an hour) with PhantomJS constantly reporting:

Asynchronous Sessions cleanup phase starting NOW
Asynchronous Sessions cleanup phase starting NOW

What does this error mean?

**Comment by eallik** [comment]
Also experiencing this issue.

**Comment by niraj7848** [comment]
Observed the same issue with the following driver version
{"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.7 Safari/534.34","webSecurityEnabled":true}

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://www.miperquin.com/row.php?lf>

 

klaus@hebsgaard.dk

**Comment by kapilko** [comment]
+1

**Comment by IamMsir** [comment]
+1 Also experiencing this issue.

**Comment by alihesari** [comment]
Any fix for this issue yet? I have same problem.

**Comment by IamMsir** [comment]
@alihesari 
hey ,i got the solution by using webdrivermanager
<dependency> <groupId>io.github.bonigarcia</groupId> <artifactId>webdrivermanager</artifactId> <version>1.6.2</version> </dependency>
and i dont know why...sorry
