### ISSUE TITLE
Can't assign useragent for windows opened through window.open

### ISSUE THREAD

**Issue by coofrog3** [ariya/phantomjs#11387]
PhantomJS does not assign useragent for new opened windows in onPageCreated callback

example code:

{

    var page = require('webpage').create();
    page.settings.userAgent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3';

    page.onPageCreated = function(newPage) {
        newPage.settings.userAgent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3';

        newPage.onInitialized = function() {
            newPage.settings.userAgent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3';
        };

        newPage.onLoadStarted = function() {
            newPage.settings.userAgent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3';
        };
        newPage.onLoadFinished = function() {
            var ua = newPage.evaluate(function() {
                return document.getElementsByClassName('ua thin success')[0].getElementsByTagName('a')[0].innerHTML;
            });
            console.log(ua);
            phantom.exit();
        }
    }
    page.evaluate(function() {
        window.open('http://whatsmyua.com/');
    });
}

result is always with all callbacks: "Mozilla/5.0 (Unknown; Linux i686) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.10.0 (development) Safari/534.34"  
but expected 

"Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3"

**Comment by ChairmanMeow** [comment]
Has this been patched yet? 
I am encountering the same problem. 
attempting to open a link that has: target = "_blank"

**Comment by zackw** [comment]
This is the same as #12547. Everything in `page.settings` is affected.
