### ISSUE TITLE
Expose Content Security Policy violations

### ISSUE THREAD

**Issue by DavidBruant** [ariya/phantomjs#11396]
Webkit implements [Content Security Policy (CSP)](https://dvcs.w3.org/hg/content-security-policy/raw-file/tip/csp-specification.dev.html).
It'd be good if PhantomJS had an API to expose this information to make it part of continuous integration (and keep track of when a resource isn't loaded because of CSP which may be a sign of a broken page)

**Comment by jimpo** [comment]
+1
