### ISSUE TITLE
Expose which resources have been blocked by Mixed Content restrictions

### ISSUE THREAD

**Issue by DavidBruant** [ariya/phantomjs#11397]
Chrome implements [Mixed Content Blocking](http://googleonlinesecurity.blogspot.com/2011/06/trying-to-end-mixed-scripting.html) (I'm not entirely sure whether it's part of Webkit. Feel free to close if it's not available to what PhantomJS uses under the hood).

In essence, it means that in some case (scripts, styles, iframe, etc.), Chrome doesn't load HTTP resources if they're loaded from an HTTPS page. This could lead to broken pages.
Also, some [Mixed Content is considered passive](https://developer.mozilla.org/en-US/docs/Security/MixedContent#Mixed_passive.2Fdisplay_content). It's loaded to the page, but may be subject to rewriting in the case of a Man-In-The-Middle attack. It would be helpful to automate the auditing of a page.

It would be interesting if PhantomJS exposed what is blocked by the Mixed Content policy implemented in Webkit.

**Comment by mlhamel** [comment]
Any idea about this one. Is it now possible to extract those informations or is it a work in progress ?
