### ISSUE TITLE
concurrent page loads are not possible?

### ISSUE THREAD

**Issue by ijx33** [ariya/phantomjs#11408]
Attempting to have more than 1 require("webpage")create() objects doesn't seem to work - eg trying something like

``` javascript
pageload (require("webpage")create(), "http://url1")
```

and

``` javascript
pageload (require("webpage")create(), "http://url2")
```

when pageload is a function of general type:

``` javascript
pageload (page, url){
   page.open(url, function (){
     //do some page.evaluate stuff ...
   });
```

I've tried fully closing over the pageload functions so that they should definately be separate instances including separate page instances.

What I appear to get is one of the pages returning null or empty (but the page.onLoadFinished reports "success").

I didn't find any documentation about this - it's possible that I am still doing something wrong  -or is this not supported (yet?).

Ask if full examples are needed.

**Comment by lab101** [comment]
+1 same issue here 1.9.8 on osx 
Loading two pages from localhost only one get loaded correctly.
The multiurl sample does work https://github.com/ariya/phantomjs/blob/master/examples/render_multi_url.js probably because its more synchronously

**Comment by msk86** [comment]
I found it is possible that keep watching `</body>` via `page.evaluate`.

At least it can return full html text to you.

**Comment by JonnyBGod** [comment]
+1 I am having the same problem with version 1.9.15.

Any idea if this is fixed on 2.x?

**Comment by Xychun** [comment]
+1

**Comment by byaka** [comment]
Is this bug actual on phantomJS2?

**Comment by azev** [comment]
I'm also having the same issue! this is definetly a bug:


```
var page1 = require('webpage').create();
page1.open('http://...', function(status) {
	var ret1 = page1.evaluate(function() {		
		return  document.body.outerHTML;
	});
});

var page2 = require('webpage').create();
page2.open('http://...', function(status) {
	var ret2 = page2.evaluate(function() {		
		return  document.body.outerHTML;
	});
});
```
page1: `document` will be always null

**Comment by Vitallium** [comment]
It works with PhantomJS 2:
This is my test script:
```
var webpage = require('webpage');

var page1 = webpage.create();
page1.open('http://google.com', function(status) {
    var ret1 = page1.evaluate(function() {      
        return  document.title;
    });
    console.log('WEBPAGE 1: ' + ret1);
});

var page2 = webpage.create();
page2.open('http://bing.com', function(status) {
    var ret2 = page2.evaluate(function() {      
        return  document.title;
    });
    console.log('WEBPAGE 2: ' + ret2);
});
```

And the output:
```
> phantomjs.exe test.js
WEBPAGE 1: Google
WEBPAGE 2: Bing
```

**Comment by azev** [comment]
document.title works. but try this:
`document.querySelectorAll('div.tab-detail li a[href*="/important/"]')[5].textContent;`
It only works if page1 **OR** page2 is running but **NOT IF both are running**

**Comment by Vitallium** [comment]
What PhantomJS are you using?

**Comment by azev** [comment]
my version is 2.1.1.
As I wrote:
`document.title` works. but try this:
`document.querySelectorAll('div.tab-detail li a[href*="/important/"]')[5].textContent;`
It only works if page1 OR page2 is running but NOT IF both are running
If I comment page2 block then page1 works the desired result (return). Otherwise it returns null.

**Comment by Vitallium** [comment]
Please attach the sample script which reproduces your problem.

**Comment by azev** [comment]
```
	var page1 = webpage.create();	
	page1.open('http://.../', function(status) {
		var ret1 = page1.evaluate(function() {      
			//return document.title;
			return document.querySelectorAll('div.tab-detail li a[href*="/torrent/"]')[1].textContent;
		});
		console.log('WEBPAGE 1: ' + ret1);
	});

	var page2 = webpage.create();	
	page2.open('http://..../', function(status) {
		var ret2 = page2.evaluate(function() {      
			//return document.title;
			return document.querySelectorAll('div.tab-detail li a[href*="/torrent/"]')[5].textContent;
		});
		console.log('WEBPAGE 2: ' + ret2);
	});
```

**Comment by Vitallium** [comment]
Are you running them on the same URL?

**Comment by azev** [comment]
either way... same url or different.
Now this is interesting...

the code above returns:
```
WEBPAGE 1: null
WEBPAGE 2: (my result2 ok)
```

and if i call it twice in the same run-time , it works both only the 2nd time.
```
WEBPAGE 1: null
WEBPAGE 2: (my result2 ok)

WEBPAGE 1: (my result1 ok)
WEBPAGE 2: (my result2 ok)
```

**Comment by azev** [comment]
and for 3 pages concurrently:

```
WEBPAGE 1: null
WEBPAGE 2: null
WEBPAGE 3: (my result3 ok)

WEBPAGE 1: (my result1 ok)
WEBPAGE 2: (my result2 ok)
WEBPAGE 3: (my result3 ok)
```

**Comment by dynamite-ready** [comment]
@azev - Can confirm that I've encountered very similar behaviour on my application.
Could PhantomJS be merely rendering the last URL rendered?
