### ISSUE TITLE
Can't get contents of invisible (display: none; or visibility: hidden;) elements

### ISSUE THREAD

**Issue by mmdm** [ariya/phantomjs#11416]
I am using PhantomJS with Selenium Web Driver in Java to do some scraping for testing purposes. I am having problems with invisible elements (display: none; or visibility: hidden;) - the css selectors aren't returning any elements. When I make the element visible in the HTML, I am getting back elements.

Below is the test HTML extract:

``` html
<div style="display: none;" id="tab2">Test content.</div>
```

and this is the CSS selector I am using:

``` html
#tab2
```

Thanks

**Comment by jesg** [comment]
i'm unable to reproduce this on selenium 2.53.1 and phantomjs 2.1.1.

```python
import selenium.webdriver as wd
driver = wd.PhantomJS()
driver.get('http://localhost:8888/hidden-elm.html')
assert len(driver.find_elements_by_css_selector('#tab1')) > 0
assert len(driver.find_elements_by_css_selector('#tab2')) > 0
```
