### ISSUE TITLE
Separate CookieJar objects for WebPages

### ISSUE THREAD

**Issue by jrollinson** [ariya/phantomjs#11417]
Currently, there exists a single CookieJar object for all web pages. This is in line with the usual behaviour of web pages, but causes difficulty when treating pages as separate entities.

To fix: CookieJar should not be a singleton, and objects that use a CookieJar should have one passed in on construction.

**Comment by yelizariev** [comment]
This issue is closed, I guess

**Comment by Vitallium** [comment]
It's not closed and this problem is in out TODO list. I believe this is a crucial feature and it should be implemented.

**Comment by yelizariev** [comment]
@Vitallium have you tried 2.0.0+ version? https://github.com/ariya/phantomjs/commit/244cf251cd767db3ca72d1f2ba9432bda0b0ba7d

**Comment by Vitallium** [comment]
The problem is that in the current state this feature requires some work to do. For example. it can't handle when the user closes a web page. We need to improve it and fix some nasty bugs.
