### ISSUE TITLE
Font kerning issue when rendering to PDF on Ubuntu

### ISSUE THREAD

**Issue by antonholmquist** [ariya/phantomjs#11413]
Setup:
Ubuntu 12.04 LTS
PhantomJS 1.9.1

It happens for all fonts with the same letters combinations rendering completely off. The fonts are Microsoft Core Fonts. 

When I render to PNG it renders fine. Also when I run the same code on my Mac it renders fine.

I've tried modifying ~/.fonts.conf according to https://wiki.ubuntu.com/Fonts but it makes no difference.

![screen shot 2013-06-17 at 9 33 42 pm](https://f.cloud.github.com/assets/505089/664493/803ea54a-d786-11e2-834f-a0bad32ee67e.png)

**Comment by carlosacp** [comment]
If some desperate with this problem reach this topic, I was using phantom-html2pdf on linux ubuntu and having this issue. Installing ttf-mscorefonts-installer and migrate to phantomjs 2.0 (https://github.com/Pyppe/phantomjs2.0-ubuntu14.04x64) solve the problem

**Comment by erikverheij** [comment]
I had the same issue with phantomjs 2.1.1 and AWS Linux AMI (based on CentOS/RHEL). 

This suggestion saved my life; https://github.com/wkhtmltopdf/wkhtmltopdf/issues/45#issuecomment-108649125

**Comment by moodysalem** [comment]
@erikverheij I'm also having this issue
http://moodysalem.github.io/react-page-div/

When you click download PDF, the html of the page is pushed to a server and the server uses phantomjs 2.1.1 to render it.

When you print from the browser it seems to have different kerning than when the server renders to PDF

I tried adding the .conf file to the /etc/fonts/conf.d directory on the EC2 instance but it didn't seem to change anything. Also can't find much information about reloading those files but I did an fc-cache call after that. Every server request starts a new phantomjs process so I'm not sure what I'm doing differently

**Comment by isuvorov** [comment]
I have the same issue

ubuntu, debian  from docker image
phantomjs 1.9.2 & 2.1.1
fixed:  **apt-get install libfontconfig1**

**Comment by abombelli** [comment]
Has this been solved? 
When generating a PDF with SVG fonts kerning is Ok. But the generated file is huge as each letter is vectorized.

**Comment by notatestuser** [comment]
@abombelli Not to mention the user is unable to select any text!

**Comment by olegsfinest** [comment]
I had the same issues and I tend not to believe it but @billschaller 's comment solved it indeed. But I have the same problem like @bazitov, it does not work for several font-faces (for bold, italic etc). Has anyone come to a solution?
