### ISSUE TITLE
Floating exception ./phantomjs

### ISSUE THREAD

**Issue by ancaniz** [ariya/phantomjs#11439]
Hi!
I have this server platform:
SUSE Linux Enterprise Server 10 (i586)
VERSION = 10
PATCHLEVEL = 1

When I run the bin it crash:

open("/usr/lib/libexpat.so.1", O_RDONLY) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0\3\0\1\0\0\0\0!\0\000"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0755, st_size=126496, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb7c77000
mmap2(NULL, 124956, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb7c58000
madvise(0xb7c58000, 124956, MADV_SEQUENTIAL|0x1) = 0
mmap2(0xb7c75000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1d) = 0xb7c75000
close(3)                                = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb7c57000
set_thread_area({entry_number:-1 -> 6, base_addr:0xb7c578e0, limit:1048575, seg_32bit:1, contents:0, read_exec_only:0, limit_in_pages:1, seg_not_present:0, useable:1}) = 0
--- SIGFPE (Floating point exception) @ 0 (0) ---
+++ killed by SIGFPE +++
Process 30633 detached

The ldd comand I get:
 ldd ./phantomjs 
        linux-gate.so.1 =>  (0xffffe000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0xb7eca000)
        libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0xb7e91000)
        libdl.so.2 => /lib/libdl.so.2 (0xb7e8d000)
        librt.so.1 => /lib/librt.so.1 (0xb7e84000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xb7e6e000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xb7d8a000)
        libm.so.6 => /lib/libm.so.6 (0xb7d65000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb7d5a000)
        libc.so.6 => /lib/libc.so.6 (0xb7c38000)
        /lib/ld-linux.so.2 (0xb7f44000)
        libz.so.1 => /lib/libz.so.1 (0xb7c26000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0xb7c06000)

The trouble is the libexpat.so.1?
This binary is compatible with Suse enterprise?
Regards.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
