### ISSUE TITLE
Crash report - stackwalked trace

### ISSUE THREAD

**Issue by Camusensei** [ariya/phantomjs#11431]
Hello.
Sorry for the crude paste, I can't find a way to upload the text files :/

>>> stackwalked trace

Operating system: Linux
                  0.0.0 Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64
CPU: amd64
     family 6 model 23 stepping 10
     2 CPUs

Crash reason:  SIGABRT
Crash address: 0x3e8000075c8

Thread 0 (crashed)
 0  libc-2.13.so + 0x32475
    rbx = 0x00000000040a65f0   r12 = 0x0000000004086db0
    r13 = 0x00000000040a65c0   r14 = 0x0000000004087570
    r15 = 0x00000000040a33d0   rip = 0x00007fb9e5096475
    rsp = 0x00007fff6eb47018   rbp = 0x00000000040a6608
    Found by: given as instruction pointer in context
 1  libc-2.13.so + 0x356ef
    rip = 0x00007fb9e50996f0   rsp = 0x00007fff6eb47020
    Found by: stack scanning
 2  ld-2.13.so + 0x55f
    rip = 0x00007fb9e668b560   rsp = 0x00007fff6eb47040
    Found by: stack scanning
 3  libc-2.13.so + 0x6b9f
    rip = 0x00007fb9e506aba0   rsp = 0x00007fff6eb47058
    Found by: stack scanning
 4  libm-2.13.so + 0x281fff
    rip = 0x00007fb9e5886000   rsp = 0x00007fff6eb470a8
    Found by: stack scanning
 5  ld-2.13.so + 0xd9f1
    rip = 0x00007fb9e66989f2   rsp = 0x00007fff6eb470b0
    Found by: stack scanning
 6  libstdc++.so.6.0.17 + 0x6589c
    rip = 0x00007fb9e58eb89d   rsp = 0x00007fff6eb47150
    Found by: stack scanning
 7  libpthread-2.13.so + 0xe12c
    rip = 0x00007fb9e5b9b12d   rsp = 0x00007fff6eb47160
    Found by: stack scanning
 8  libstdc++.so.6.0.17 + 0x63995
    rip = 0x00007fb9e58e9996   rsp = 0x00007fff6eb47180
    Found by: stack scanning
 9  libstdc++.so.6.0.17 + 0x639c2
    rip = 0x00007fb9e58e99c3   rsp = 0x00007fff6eb47190
    Found by: stack scanning
10  libstdc++.so.6.0.17 + 0x644de
    rip = 0x00007fb9e58ea4df   rsp = 0x00007fff6eb471a0
    Found by: stack scanning
11  phantomjs!QCoreApplication::postEvent [qcoreapplication.cpp : 1392 + 0x8]
    rip = 0x0000000001cdebcc   rsp = 0x00007fff6eb471b0
    Found by: stack scanning
12  phantomjs!QMetaMethod::invoke [qmetaobject.cpp : 1703 + 0x5a]
    rbx = 0x0000000004087570   r12 = 0x00007fff6eb47850
    r13 = 0x000000000000000b   r14 = 0x0000000000000000
    r15 = 0x00000000040a33d0   rip = 0x0000000001ce8b09
    rsp = 0x00007fff6eb47260   rbp = 0x0000000000000001
    Found by: call frame info
13  phantomjs!QMetaObject::invokeMethod [qmetaobject.cpp : 1179 + 0x1ba]
    rbx = 0x000000000000000f   r12 = 0x0000000000000000
    r13 = 0x00000000040a33d0   r14 = 0x00007fff6eb475d0
    r15 = 0x0000000000000000   rip = 0x0000000001ce99de
    rsp = 0x00007fff6eb474b0   rbp = 0x00007fff6eb477f0
    Found by: call frame info
14  phantomjs!QNetworkConfigurationManagerPrivate::enablePolling [qobjectdefs.h : 434 + 0xc3]
    rbx = 0x00000000040a33f0   r12 = 0x00000000040a33f1
    r13 = 0x00007fff6eb47bf0   r14 = 0x00000000040a3860
    r15 = 0x00000000040a38a0   rip = 0x0000000001b4e59d
    rsp = 0x00007fff6eb478b0   rbp = 0x00000000040a33d0
    Found by: call frame info
15  phantomjs!QNetworkConfigurationManager::QNetworkConfigurationManager [qnetworkconfigmanager.cpp : 243 + 0x7]
    rbx = 0x00000000040a33d0   r12 = 0x00007fb9e3ce2270
    r13 = 0x00007fff6eb47bf0   r14 = 0x00000000040a3860
    r15 = 0x00000000040a38a0   rip = 0x0000000001b4aa29
    rsp = 0x00007fff6eb47a20   rbp = 0x00000000040a56a0
    Found by: call frame info
16  phantomjs!WebCore::NetworkStateNotifierPrivate::NetworkStateNotifierPrivate [NetworkStateNotifierQt.cpp : 34 + 0x2a]
    rbx = 0x00000000040a56a0   r12 = 0x00007fb9e3ce2270
    r13 = 0x00007fff6eb47bf0   r14 = 0x00000000040a3860
    r15 = 0x00000000040a38a0   rip = 0x0000000000b57e36
    rsp = 0x00007fff6eb47a40   rbp = 0x000000000409cf10
    Found by: call frame info
17  phantomjs!WebCore::NetworkStateNotifier::NetworkStateNotifier [NetworkStateNotifierQt.cpp : 79 + 0x17]
    rbx = 0x00007fb9e3ce2270   r12 = 0x00000000040a3790
    r13 = 0x00007fff6eb47bf0   r14 = 0x00000000040a3860
    r15 = 0x00000000040a38a0   rip = 0x0000000000b57ed4
    rsp = 0x00007fff6eb47a60   rbp = 0x000000000409cf10
    Found by: call frame info
18  phantomjs!WebCore::networkStateNotifier [NetworkStateNotifier.cpp : 37 + 0x7]
    rbx = 0x00007fb9e3ce2270   r12 = 0x00000000040a3790
    r13 = 0x00007fff6eb47bf0   r14 = 0x00000000040a3860
    r15 = 0x00000000040a38a0   rip = 0x0000000000975e0c
    rsp = 0x00007fff6eb47a80   rbp = 0x00000000040a3790
    Found by: call frame info
19  phantomjs!WebCore::Page::Page [Page.cpp : 170 + 0x4]
    rbx = 0xbff0000000000000   r12 = 0x00000000040a3790
    r13 = 0x00007fff6eb47bf0   r14 = 0x00000000040a3860
    r15 = 0x00000000040a38a0   rip = 0x00000000008fff9d
    rsp = 0x00007fff6eb47aa0   rbp = 0x00000000040a3790
    Found by: call frame info
20  phantomjs!QWebPagePrivate::QWebPagePrivate [qwebpage.cpp : 349 + 0x17]
    rbx = 0x000000000409ddb0   r12 = 0x00000000040a6700
    r13 = 0x00007fff6eb47bf0   r14 = 0x000000000409ddd8
    r15 = 0x000000000409de58   rip = 0x000000000048d51f
    rsp = 0x00007fff6eb47bc0   rbp = 0x00000000040a3790
    Found by: call frame info
21  phantomjs!QWebPage::QWebPage [qwebpage.cpp : 1970 + 0x2b]
    rbx = 0x000000000409ddb0   r12 = 0x00000000040a6700
    r13 = 0x00000000040a56c0   r14 = 0x00007fff6eb48390
    r15 = 0x0000000000000000   rip = 0x00000000004903c5
    rsp = 0x00007fff6eb47ca0   rbp = 0x000000000409e190
    Found by: call frame info
22  phantomjs!WebPage::WebPage [webpage.cpp : 96 + 0xa]
    rbx = 0x000000000409e190   r12 = 0x00000000040a5720
    r13 = 0x00000000040a56c0   r14 = 0x00007fff6eb48390
    r15 = 0x0000000000000000   rip = 0x0000000000418267
    rsp = 0x00007fff6eb47cc0   rbp = 0x00000000040a6700
    Found by: call frame info
23  phantomjs!Phantom::init [phantom.cpp : 102 + 0x40]
    rbx = 0x00000000040a6700   r12 = 0x00000000040a5720
    r13 = 0x00000000040a56c0   r14 = 0x00007fff6eb48390
    r15 = 0x0000000000000000   rip = 0x0000000000409bf3
    rsp = 0x00007fff6eb47e20   rbp = 0x00007fff6eb48090
    Found by: call frame info
24  phantomjs!Phantom::instance [phantom.cpp : 154 + 0x4]
    rbx = 0x00007fff6eb484a0   r12 = 0x00007fff6eb48420
    r13 = 0x00007fff6eb485e0   r14 = 0x00007fff6eb48390
    r15 = 0x0000000000000000   rip = 0x000000000040b576
    rsp = 0x00007fff6eb48360   rbp = 0x00000000040a56c0
    Found by: call frame info
25  phantomjs!main [main.cpp : 117 + 0x4]
    rbx = 0x00007fff6eb484a0   r12 = 0x00007fff6eb48420
    r13 = 0x00007fff6eb485e0   r14 = 0x00007fff6eb48390
    r15 = 0x0000000000000000   rip = 0x0000000000427c9e
    rsp = 0x00007fff6eb48380   rbp = 0x00007fff6eb485b8
    Found by: call frame info
26  libc-2.13.so + 0x1eeac
    rbx = 0x0000000000000000   r12 = 0x0000000000407cc0
    r13 = 0x00007fff6eb485b0   r14 = 0x0000000000000000
    r15 = 0x0000000000000000   rip = 0x00007fb9e5082ead
    rsp = 0x00007fff6eb484e0   rbp = 0x0000000000000000
    Found by: call frame info
27  phantomjs + 0x27a5f
    rip = 0x0000000000427a60   rsp = 0x00007fff6eb48500
    Found by: stack scanning

Thread 1
 0  libpthread-2.13.so + 0xb2d4
    rbx = 0x0000000002ade208   r12 = 0x0000000002ad0160
    r13 = 0x00007fb9e45df9c0   r14 = 0x00007fb9e68ab040
    r15 = 0x0000000000000003   rip = 0x00007fb9e5b982d4
    rsp = 0x00007fb9e45dee10   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  phantomjs!WTF::TCMalloc_PageHeap::scavengerThread [FastMalloc.cpp : 2495 + 0x7]
    rip = 0x00000000004ddafc   rsp = 0x00007fb9e45dee40
    Found by: stack scanning
 2  phantomjs!WTF::TCMalloc_PageHeap::runScavengerThread [FastMalloc.cpp : 1618 + 0x4]
    rbx = 0x0000000000000000   r12 = 0x00007fb9e5b9e1a0
    r13 = 0x00007fb9e45df9c0   r14 = 0x00007fb9e68ab040
    r15 = 0x0000000000000003   rip = 0x00000000004ddc99
    rsp = 0x00007fb9e45deec0   rbp = 0x0000000000000000
    Found by: call frame info
 3  libpthread-2.13.so + 0x6b4f
    rbx = 0x0000000000000000   r12 = 0x00007fb9e5b9e1a0
    r13 = 0x00007fb9e45df9c0   r14 = 0x00007fb9e68ab040
    r15 = 0x0000000000000003   rip = 0x00007fb9e5b93b50
    rsp = 0x00007fb9e45deed0   rbp = 0x0000000000000000
    Found by: call frame info
 4  libpthread-2.13.so + 0x1119f
    rip = 0x00007fb9e5b9e1a0   rsp = 0x00007fb9e45def78
    Found by: stack scanning
 5  libc-2.13.so + 0xdaa7c
    rip = 0x00007fb9e513ea7d   rsp = 0x00007fb9e45defe0
    Found by: stack scanning

Thread 2
 0  libc-2.13.so + 0xd72f9
    rbx = 0x00000000040a2fd0   r12 = 0xfffffffffff0bdc0
    r13 = 0x000000000404dab0   r14 = 0x00000000040a6608
    r15 = 0x0000000004087570   rip = 0x00007fb9e513b2f9
    rsp = 0x00007fb9e3cdd498   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  phantomjs!QMutexPrivate::wait [qmutex_unix.cpp : 99 + 0x22]
    rip = 0x0000000001be1de3   rsp = 0x00007fb9e3cdd4a0
    Found by: stack scanning
 2  phantomjs!QMutex::lock [qmutex.cpp : 164 + 0xc]
    rbx = 0x00000000040a2fd0   r12 = 0x0000000000000000
    rip = 0x0000000001bddf7c   rsp = 0x00007fb9e3cdd4f0
    rbp = 0x00007fb9e3cde700
    Found by: call frame info
 3  phantomjs!QNetworkConfigurationManagerPrivate::startPolling [qmutex.h : 188 + 0x7]
    rbx = 0x00000000040a33f0   r12 = 0x0000000000000000
    rip = 0x0000000001b4c548   rsp = 0x00007fb9e3cdd510
    rbp = 0x00000000040a33d0
    Found by: call frame info
 4  phantomjs!QNetworkConfigurationManagerPrivate::qt_static_metacall [moc_qnetworkconfigmanager_p.cpp : 85 + 0x4]
    rbx = 0x00000000040a33d0   r12 = 0x0000000004087570
    r13 = 0x000000000404dab0   rip = 0x0000000001ba86a6
    rsp = 0x00007fb9e3cdd560   rbp = 0x0000000000000000
    Found by: call frame info
 5  phantomjs!QObject::event [qobject.cpp : 1191 + 0x8]
    rbx = 0x00000000040a33d0   r12 = 0x0000000004087570
    r13 = 0x000000000404dab0   rip = 0x0000000001cefc08
    rsp = 0x00007fb9e3cdd5a0   rbp = 0x0000000000000000
    Found by: call frame info
 6  phantomjs!QApplicationPrivate::notify_helper [qapplication.cpp : 4562 + 0xc]
    rbx = 0x00007fff6eb48420   r12 = 0x0000000004087570
    r13 = 0x000000000404dab0   rip = 0x00000000015decaf
    rsp = 0x00007fb9e3cdd740   rbp = 0x00000000040a33d0
    Found by: call frame info
 7  phantomjs!QApplication::notify [qapplication.cpp : 4423 + 0x17]
    rbx = 0x00007fff6eb48420   r12 = 0x0000000004087570
    r13 = 0x00007fff6eb48420   rip = 0x00000000015e793b
    rsp = 0x00007fb9e3cdd770   rbp = 0x00000000040a33d0
    Found by: call frame info
 8  phantomjs!QCoreApplication::notifyInternal [qcoreapplication.cpp : 946 + 0x2]
    rbx = 0x00000000040a65c0   r12 = 0x0000000004087570
    r13 = 0x00007fff6eb48420   r14 = 0x00000000040a6608
    r15 = 0x00000000040a65fc   rip = 0x0000000001cde3b4
    rsp = 0x00007fb9e3cddc40   rbp = 0x00000000040a33d0
    Found by: call frame info
 9  phantomjs!QCoreApplicationPrivate::sendPostedEvents [qcoreapplication.h : 231 + 0x1f]
    rbx = 0x0000000004087570   r12 = 0x00000000040a65c0
    r13 = 0x00000000040a33d0   r14 = 0x00000000040a6608
    r15 = 0x00000000040a65fc   rip = 0x0000000001cdf314
    rsp = 0x00007fb9e3cddc90   rbp = 0x0000000004292cd0
    Found by: call frame info
10  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 909 + 0xc]
    rbx = 0x0000000004291480   r12 = 0x00007fb9e3cddda0
    r13 = 0x00000000040a1b60   r14 = 0x0000000000000000
    r15 = 0x00000000040a6578   rip = 0x0000000001d08003
    rsp = 0x00007fb9e3cddd50   rbp = 0x00000000040a6b90
    Found by: call frame info
11  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x0000000004291480   r12 = 0x00007fb9e3cdde30
    r13 = 0x00007fb9e3cdde40   r14 = 0x000000000404b230
    r15 = 0x00000000040a6578   rip = 0x0000000001cdd495
    rsp = 0x00007fb9e3cddda0   rbp = 0x00007fb9e3cddde0
    Found by: call frame info
12  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x0000000004291480   r12 = 0x00007fb9e3cdde30
    r13 = 0x00007fb9e3cdde40   r14 = 0x000000000404b230
    r15 = 0x00000000040a6578   rip = 0x0000000001cdd8f8
    rsp = 0x00007fb9e3cdddd0   rbp = 0x00007fff6eb48420
    Found by: call frame info
13  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
    rbx = 0x00000000040a64f0   r12 = 0x00000000040a6578
    r13 = 0x0000000000000001   r14 = 0x00007fb9e68ab040
    r15 = 0x0000000000000003   rip = 0x0000000001bdfdd6
    rsp = 0x00007fb9e3cdde30   rbp = 0x00000000040a6578
    Found by: call frame info
14  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x00000000040a6578   r12 = 0x00000000040a65c0
    r13 = 0x0000000000000001   r14 = 0x00007fb9e68ab040
    r15 = 0x0000000000000003   rip = 0x0000000001be2ca2
    rsp = 0x00007fb9e3cdde80   rbp = 0x0000000004086eb0
    Found by: call frame info
15  libpthread-2.13.so + 0x6b4f
    rbx = 0x0000000000000000   r12 = 0x00007fff6eb47900
    r13 = 0x00007fb9e3cde9c0   r14 = 0x00007fb9e68ab040
    r15 = 0x0000000000000003   rip = 0x00007fb9e5b93b50
    rsp = 0x00007fb9e3cdded0   rbp = 0x0000000000000000
    Found by: call frame info

Loaded modules:
0x00400000 - 0x026e7fff  phantomjs  ???  (main)
0x7fb9e45e0000 - 0x7fb9e483efff  libssl.so.1.0.0  ???
0x7fb9e483f000 - 0x7fb9e4c1efff  libcrypto.so.1.0.0  ???
0x7fb9e4c23000 - 0x7fb9e4e4cfff  libexpat.so.1.6.0  ???
0x7fb9e4e4d000 - 0x7fb9e5063fff  libz.so.1.2.7  ???
0x7fb9e5064000 - 0x7fb9e53e8fff  libc-2.13.so  ???
0x7fb9e53ee000 - 0x7fb9e5603fff  libgcc_s.so.1  ???
0x7fb9e5604000 - 0x7fb9e5885fff  libm-2.13.so  ???
0x7fb9e5886000 - 0x7fb9e5b77fff  libstdc++.so.6.0.17  ???
0x7fb9e5b8d000 - 0x7fb9e5da4fff  libpthread-2.13.so  ???
0x7fb9e5da9000 - 0x7fb9e5fb0fff  librt-2.13.so  ???
0x7fb9e5fb1000 - 0x7fb9e61b4fff  libdl-2.13.so  ???
0x7fb9e61b5000 - 0x7fb9e63ebfff  libfontconfig.so.1.5.0  ???
0x7fb9e63ec000 - 0x7fb9e668afff  libfreetype.so.6.8.1  ???
0x7fb9e668b000 - 0x7fb9e66aafff  ld-2.13.so  ???
0x7fb9e6725000 - 0x7fb9e689bfff  locale-archive  ???
0x7fb9e68a4000 - 0x7fb9e68a7fff  6d41288fd70b0be22e8c3a91e032eec0-le64.cache-3  ???
0x7fff6ebff000 - 0x7fff6ebfffff  linux-gate.so  ???
<<< stackwalked trace end

Tell me if you need something else.
Regards,
Camusensei

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
