### ISSUE TITLE
crash with 1.9.1 when running a qunit test

### ISSUE THREAD

**Issue by stupenrose** [ariya/phantomjs#11434]
With some of our tests, we're experiencing an intermittent phantomjs crash.  The crash message directs me to file a bug, and I'm doing so in accordance with the instructions at https://github.com/ariya/phantomjs/wiki/Crash-Reporting

Thanks in advance!

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
