### ISSUE TITLE
onResourceReceived callbacks not being called (at times) on urls that redirect with status 302

### ISSUE THREAD

**Issue by sethbridges** [ariya/phantomjs#11441]
I have been doing some resource counting inside of phantomjs, and I have recently come across a bug involving page.onResourceReceived callbacks not being called consistently when the response from the server is a 302. 

I am seeing two failure cases:
1. For some URLs, the callback is never being called when request.stage === 'start', yet it is being called when stage === 'end'.  This behavior seems to be deterministic and a function of the URL being requested.

Here is a test script that exposes this behavior:

https://gist.github.com/sethbridges/5879484
1. For some URLs, the callback is called consistently except for 1 in 20 times where the callback is only called when request.stage === 'start', but not when request.stage === 'end'. This behavior is hard to pin down, and so I don't have a consistent repro currently.

**Comment by Karo7** [comment]
thanks
I was facing the same problem yesterday
because this problem still exists is there a plan
to solve this glitch
