### ISSUE TITLE
Any chance for 'stdin' functionality for child_process?

### ISSUE THREAD

**Issue by Morgon** [ariya/phantomjs#11446]
In #10219, basic child_process was implemented. In that thread, it looks like stdin was specifically mentioned as not yet available. Is that something that could be ported over from the main node.js child_process module?

Taking examples from here: http://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options I can execute the first example within PhantomJS, but not the second.

My personal use-case is that I'd like to save some information from a phantomjs-fetched page into memcache. Since we can't use any memcache modules, my next thought was to use the child_process functions to echo out the raw wire commands to a target memcached instance via nc (netcat). 

Thank you!

**Comment by abnerlee** [comment]
+1

**Comment by zackw** [comment]
We'd like to get this into 2.2.  It's being worked on in pull request  #13945.

**Comment by Morgon** [comment]
Beautiful. Thank you so much for the followup!

**Comment by zackw** [comment]
Pull request #13945 has been merged.
