### ISSUE TITLE
PHP exec issues

### ISSUE THREAD

**Issue by JamesMGreene** [ariya/phantomjs#11463]
I've noticed an increase in the number of issues reported that have to do with PHP `exec`, `shell_exec`, etc. crashing, hanging, etc. when trying to execute PhantomJS.  I'm not certain that there _isn't_ a problem with PhantomJS's execution wrapper login that could be causing issues.  However, when I started researching this scenario on the web, I found a _massive_ number of hits mentioning similar problems with binary execution in general—let alone for PhantomJS—for PHP.

I'm creating this issue to centralize those other issues into one so that we can perhaps work together to verify some of the potential configuration fixes that are _outside_ of PhantomJS.

I've tried to sort what I've found from the most promising/easy to the least. If you were suffering from PHP `exec` problems with PhantomJS, please let us know if any of the following resolve your issues in part or in whole.  Thanks!

**PHP `exec` issues and potential workarounds:**
1. [Corrupted binary if uploaded via FTP without enabling binary transfer mode](http://stackoverflow.com/questions/16099278/executing-a-binary-on-linux-web-server-through-phps-exec)
2. Apache permissions issues: normal chmod permissions do not cover it! [[1]](http://stackoverflow.com/questions/11216839/phantomjs-doesnt-work-in-php-through-browser-but-does-via-command-line-and-ev), [[2]](http://stackoverflow.com/questions/6913403/running-command-line-application-from-php-as-specific-user), [[3]](http://devlup.com/programming/php/capture-webpage-screenshot-using-php-and-phantomjs/4484/)
3. [Unhandled `stdin`, `stdout`, and `stderr` lead to Apache timeouts](http://www.php.net/manual/en/function.exec.php#102342)
4. [Non-executable invocation will return `126` exit code](http://www.php.net/manual/en/function.exec.php#83030)
5. [To avoid hangs, call `session_write_close()` before the call to `exec("phantomjs ...")`](http://michielve.blogspot.com/2013/04/phantomjs-cookie.html)
6. [Environment variables missing](http://phponlinesupport.com/topic115550.html)
7. [`shell_exec` garbles input](http://www.php.net/manual/en/function.exec.php#11317)
8. [Remember to use unix `exit(0);` on unix calls that use Unix redirection operator `>`](http://www.php.net/manual/en/function.exec.php#13379)
9. [Remove the `SIGCHLD` signal handler to avoid `-1` exit code](http://www.php.net/manual/en/function.exec.php#76687)
10. PHP manual special notes on [`exec`](http://www.php.net/manual/en/function.exec.php):  
    
    > _**Note:**_ If a program is started with this function, in order for it to continue running in the background, the output of the program must be redirected to a file or another output stream. Failing to do so will cause PHP to hang until the execution of the program ends.  
    > 
    > _**Note:**_ When [safe mode](http://www.php.net/manual/en/features.safe-mode.php) is enabled, you can only execute files within the [`safe_mode_exec_dir`](http://www.php.net/manual/en/ini.sect.safe-mode.php#ini.safe-mode-exec-dir). For practical reasons, it is currently not allowed to have _.._ components in the path to the executable.
11. PHP manual special notes on [`shell_exec`](http://www.php.net/manual/en/function.shell-exec.php):
    
    > _**Note:**_ This function is disabled when PHP is running in [safe mode](http://www.php.net/manual/en/features.safe-mode.php).

**Comment by ScaredyCat** [comment]
If you're running Linux, use the 32 bit version not the 64 bit one. The 32bit one does not suffer from this issue and works fine. 

I already have little hair, I don't need help removing what's left.

**Comment by Petah** [comment]
So is there a work around for this?

**Comment by billshander** [comment]
Yes - if you look at my comment from August 14, 2013 above, this worked for me:
Proc_Close (Proc_Open ("/path/to/phantomjs /path/to/render.js param1 param2 &", Array (), $foo));

And this code is on a production machine and still working today. FYI, it's on PHP 5.3 (Ubuntu 12.04) so I can't attest to newer OS/PHP workability.

**Comment by Petah** [comment]
@billschaller I get the same error:

```
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
```

Using this:

```
proc_close(proc_open('/var/app/bin/phantomjs --web-security=false --local-to-remote-url-access=true --local-url-access=true --ignore-ssl-errors=true  --debug=true /var/app/render-svg.js http://127.0.0.1:8440/path-to-file.svg /var/app/logs/order-line-99.log 2>&1', [], $foo));
```

**Comment by billshander** [comment]
Unfortunately, we've hit the limit of what I know about this. You sure it's supposed to work with SVG? And you're sure the paths are correct? And the folder permissions are setup properly? That's all I can think of...

**Comment by Petah** [comment]
Works fine when I run the command directly. Only fails when calling from PHP.

**Comment by billshander** [comment]
Man that's frustrating. Check the logs for any specific error and Google if anything useful. Wish I could offer more help!


on the go (from my mobile)
=======================
Bill Shander
Beehive Media
http://beehivemedia.com

On Jul 11, 2016, at 7:50 PM, David Neilsen <notifications@github.com<mailto:notifications@github.com>> wrote:


Works fine when I run the command directly. Only fails when calling from PHP.

-

**Comment by linkinkin** [comment]
I'm having the same problem. Running perfectly from terminal but when using exec from PHP, Phantom crash, really strange..

**Comment by jv2222** [comment]
Was able to get this working by using `&` to spawn a background process in the shell like this:

```
$imageName = tempnam("/tmp", "link-image").'.png';
$phantomJsScript = base_path()."/resources/assets/js/phantom.js";
exec("phantomjs $phantomJsScript $link $imageName &");
while (!file_exists($imageName)) { sleep(1); }
```

**Comment by zuojj** [comment]
Execute page.render(), return false;  https://github.com/ariya/phantomjs/issues/14485

**Comment by zuojj** [comment]
**phantomjs: 2.1.1
Red Hat Enterprise Linux Server release 6.6 (Santiago)
PHP 5.3.3**

## Problem
```
$ phantomjs /workspace/js/screenshot.js
```
Execute above script ,the result is right, can create a image;

**But**:  PHP exec()
```php
<?php  
    $command = "phantomjs /workspace/js/screenshot.js"; 

    $response = exec($command, $ouput, $return_var);  
    
    print_r($return_var);  // print  0;
?>
```
screenshot.js
```
var webpage = require('webpage'),
    page = webpage.create();

page.open('http://m.baidu.com', function(status) {
    if('success' !== status) {
        console.log('Open Fail');
    }else {
        console.log('Open success');
        window.setTimeout(function () {
            var rendered = page.render('xxxx.jpg');
            console.log(rendered);
            phantom.exit();
        }, 2000);
    }
});
```
The result is wrong, rendered always return false;

**Comment by jasewells** [comment]
I’ve been having trouble with PHP exec() and PhantomJS, too, but in my case there was no crash. Instead, it just took forever to finish, and meanwhile my PHP page was waiting and waiting.

In PHP I’m creating a local on-disk HTML file, then I use PhantomJS to convert that page to PDF. It worked fine and generated the PDF, but it took 40 seconds to finish! So meanwhile, my PHP page was just waiting and waiting… Some console logging in my PhantomJS script revealed that there was a 20 second delay before the script even started execution, then another 20 second delay in page.open(). The actual page.render() returned right away. So it was just those two delays adding up to 40 seconds of nothing happening. (I don’t know if 20 seconds each is specific to the speed of my VM, some timeout limit in CentOS, or what…)

I couldn’t reproduce it on the command-line — the exact same command finished right away with no delays.

Eventually I figured out one difference between my fast command line and slow PHP exec: my shell had the $HOME environment variable set, but the PHP exec environment did not. Adding that to my exec command seems to make PhantomJS happy and run at the normal (fast) speed:

`exec("HOME=/tmp phantomjs /path/to/script file:///path/to/source /path/to/target");
`

Hoping this comment might help others running into this slow/hanging behavior and save them a lot of time and frustration!

**Comment by Franchu-tk** [comment]
I having problems executing phantomjs through PHP. It crashes everytime. crash report:

1 0x1b67967 /path/to/phantomjs() [0x1b67967]
2 0x1baaaf5 /path/to/phantomjs() [0x1baaaf5]
3 0x198c463 /path/to/phantomjs() [0x198c463]
4 0x1ab3982 /path/to/phantomjs() [0x1ab3982]
5 0x79abb9 /path/to/phantomjs() [0x79abb9]
6 0x76b6f9 /path/to/phantomjs() [0x76b6f9]
7 0x750a5d /path/to/phantomjs() [0x750a5d]
8 0x41cd89 /path/to/phantomjs() [0x41cd89]
9 0x41f5c4 /path/to/phantomjs() [0x41f5c4]
10 0x415b86 /path/to/phantomjs() [0x415b86]
11 0x7f0f64eacd1d /lib64/libc.so.6(__libc_start_main+0xfd) [0x7f0f64eacd1d]
12 0x4176a1 /path/to/phantomjs() [0x4176a1]
PhantomJS has crashed. Please read the bug reporting guide at and file a bug report. 

Some information about my case:
I am trying to run it at a shared server running on Linux 64. It works perfectly throuth SHH_SHELL, both running it directly and running the php file. now if I try to run it with the browser, it crashes.

exec ('/path/to/phantomjs -v') works fine, it returns 2.1.1

But if I try to run a script it crashes. the PHP file is right as it works if I run it on SHH_shell.

I have tried PHP 7.0, 5.6 and 5.4, it crashes everytime. I have tried every solution that I could from this page.

I thought it could be related to the appache permission issue, but I know little to nothing about Linux, so I talked to the hosting support and they told me it was ok ( my hosting is Bluehost, the support there is sometimes weak)

Anyway, I've tried everything I could. Please can anyone help me? my project is stopped because of this and I really need this working.

Thank you in advance.
