### ISSUE TITLE
Getting segmentation fault error while working in ubuntu

### ISSUE THREAD

**Issue by booma** [ariya/phantomjs#11467]
I am able run my application in windows 7.0 without any issues  but in linux version i am getting error as segmentation fault 

Attaching the dump

Operating system: Linux
                  0.0.0 Linux 3.2.0-24-virtual #37-Ubuntu SMP Wed Apr 25 10:17:19 UTC 2012 x86_64
CPU: amd64
     family 6 model 15 stepping 11
     1 CPU

Crash reason:  SIGSEGV
Crash address: 0x0

Thread 0 (crashed)
 0  phantomjs + 0x172aab9
    rbx = 0x000000007fffffff   r12 = 0x000000007fffffff
    r13 = 0x000000000448c600   r14 = 0x000000000448c600
    r15 = 0x0000000000000000   rip = 0x0000000001b2aab9
    rsp = 0x00007fff38080eb0   rbp = 0x00007fff38081210
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17a96ca
    rip = 0x0000000001ba96cb   rsp = 0x00007fff38080ed0
    rbp = 0x00007fff38081210
    Found by: stack scanning
 2  phantomjs + 0x17a9860
    rip = 0x0000000001ba9861   rsp = 0x00007fff38080f00
    rbp = 0x00007fff38081210
    Found by: stack scanning
 3  phantomjs + 0x17ce825
    rip = 0x0000000001bce826   rsp = 0x00007fff38080f20
    rbp = 0x00007fff38081210
    Found by: stack scanning
 4  phantomjs + 0x17aa60d
    rip = 0x0000000001baa60e   rsp = 0x00007fff38080f60
    rbp = 0x00007fff38081210
    Found by: stack scanning
 5  phantomjs + 0x3128d
    rip = 0x000000000043128e   rsp = 0x00007fff38080f70
    rbp = 0x00007fff38081210
    Found by: stack scanning
 6  phantomjs + 0xcec4a
    rip = 0x00000000004cec4b   rsp = 0x00007fff38080f90
    rbp = 0x00007fff38081210
    Found by: stack scanning
 7  phantomjs + 0xa55484
    rip = 0x0000000000e55485   rsp = 0x00007fff38080fb0
    rbp = 0x00007fff38081210
    Found by: stack scanning
 8  phantomjs + 0x119ab1b
    rip = 0x000000000159ab1c   rsp = 0x00007fff38081010
    rbp = 0x00007fff38081210
    Found by: stack scanning
 9  libc-2.15.so + 0x3b671f
    rip = 0x00007ffbe029d720   rsp = 0x00007fff38081098
    rbp = 0x00007fff38081210
    Found by: stack scanning
10  libc-2.15.so + 0x8174f
    rip = 0x00007ffbdff68750   rsp = 0x00007fff380810c0
    rbp = 0x00007fff38081210
    Found by: stack scanning
11  libc-2.15.so + 0x3b671f
    rip = 0x00007ffbe029d720   rsp = 0x00007fff380810d8
    rbp = 0x00007fff38081210
    Found by: stack scanning
12  libc-2.15.so + 0x831fd
    rip = 0x00007ffbdff6a1fe   rsp = 0x00007fff38081100
    rbp = 0x00007fff38081210
    Found by: stack scanning
13  libc-2.15.so + 0x3b671f
    rip = 0x00007ffbe029d720   rsp = 0x00007fff38081110
    rbp = 0x00007fff38081210
    Found by: stack scanning
14  libc-2.15.so + 0x3b671f
    rip = 0x00007ffbe029d720   rsp = 0x00007fff38081170
    rbp = 0x00007fff38081210
    Found by: stack scanning
15  libc-2.15.so + 0x82a44
    rip = 0x00007ffbdff69a45   rsp = 0x00007fff380811a0
    rbp = 0x00007fff38081210
    Found by: stack scanning
16  phantomjs + 0x167b8a9
    rip = 0x0000000001a7b8aa   rsp = 0x00007fff380811d0
    rbp = 0x00007fff38081210
    Found by: stack scanning
17  phantomjs + 0x1842167
    rip = 0x0000000001c42168   rsp = 0x00007fff38081200
    rbp = 0x00007fff38081210
    Found by: stack scanning
18  libc-2.15.so + 0x3b671f
    rip = 0x00007ffbe029d720   rsp = 0x00007fff38081210
    rbp = 0x00007fff38081210
    Found by: stack scanning
19  libc-2.15.so + 0x82a44
    rip = 0x00007ffbdff69a45   rsp = 0x00007fff38081240
    Found by: stack scanning
20  phantomjs + 0x17c9fae
    rip = 0x0000000001bc9faf   rsp = 0x00007fff380812a0
    Found by: stack scanning
21  libc-2.15.so + 0x3b671f
    rip = 0x00007ffbe029d720   rsp = 0x00007fff38081320
    Found by: stack scanning
22  libc-2.15.so + 0x82a44
    rip = 0x00007ffbdff69a45   rsp = 0x00007fff38081350
    Found by: stack scanning
23  phantomjs + 0x167e525
    rip = 0x0000000001a7e526   rsp = 0x00007fff38081380
    Found by: stack scanning
24  phantomjs + 0x1660644
    rip = 0x0000000001a60645   rsp = 0x00007fff380813e0
    Found by: stack scanning
25  phantomjs + 0x64ab39
    rip = 0x0000000000a4ab3a   rsp = 0x00007fff380813f0
    Found by: stack scanning
26  phantomjs + 0x167e525
    rip = 0x0000000001a7e526   rsp = 0x00007fff38081410
    Found by: stack scanning
27  phantomjs + 0x647864
    rip = 0x0000000000a47865   rsp = 0x00007fff38081480
    Found by: stack scanning
28  phantomjs + 0xe4c4d
    rip = 0x00000000004e4c4e   rsp = 0x00007fff380814b0
    Found by: stack scanning
29  phantomjs + 0x1c400f4
    rip = 0x00000000020400f5   rsp = 0x00007fff380814b8
    Found by: stack scanning
30  libc-2.15.so + 0x3b671f
    rip = 0x00007ffbe029d720   rsp = 0x00007fff380814c0
    Found by: stack scanning
31  phantomjs + 0x181a7e8
    rip = 0x0000000001c1a7e9   rsp = 0x00007fff380814e0
    Found by: stack scanning
32  phantomjs + 0x64af6f
    rip = 0x0000000000a4af70   rsp = 0x00007fff38081500
    Found by: stack scanning
33  phantomjs + 0x64afbc
    rip = 0x0000000000a4afbd   rsp = 0x00007fff38081510
    Found by: stack scanning
34  phantomjs + 0x64af6f
    rip = 0x0000000000a4af70   rsp = 0x00007fff38081548
    Found by: stack scanning
35  phantomjs + 0x64801a
    rip = 0x0000000000a4801b   rsp = 0x00007fff38081550
    Found by: stack scanning
36  libc-2.15.so + 0x82a44
    rip = 0x00007ffbdff69a45   rsp = 0x00007fff38081560
    Found by: stack scanning
37  phantomjs + 0x6498e6
    rip = 0x0000000000a498e7   rsp = 0x00007fff380815b0
    Found by: stack scanning
38  phantomjs + 0x645390
    rip = 0x0000000000a45391   rsp = 0x00007fff38081600
    Found by: stack scanning
39  phantomjs + 0xcf97d
    rip = 0x00000000004cf97e   rsp = 0x00007fff38081620
    Found by: stack scanning
40  phantomjs + 0x4f36ac
    rip = 0x00000000008f36ad   rsp = 0x00007fff38081660
    Found by: stack scanning
41  phantomjs + 0xde75d
    rip = 0x00000000004de75e   rsp = 0x00007fff38081680
    Found by: stack scanning
42  phantomjs + 0x4013cd
    rip = 0x00000000008013ce   rsp = 0x00007fff380816c0
    Found by: stack scanning
43  phantomjs + 0xda352d
    rip = 0x00000000011a352e   rsp = 0x00007fff380816d0
    Found by: stack scanning
44  phantomjs + 0x17cae49
    rip = 0x0000000001bcae4a   rsp = 0x00007fff38081760
    Found by: stack scanning
45  phantomjs + 0xcec00
    rip = 0x00000000004cec01   rsp = 0x00007fff38081780
    Found by: stack scanning
46  phantomjs + 0xcec4a
    rip = 0x00000000004cec4b   rsp = 0x00007fff380817d0
    Found by: stack scanning
47  phantomjs + 0x401a56
    rip = 0x0000000000801a57   rsp = 0x00007fff38081850
    Found by: stack scanning

Thread 1
 0  libpthread-2.15.so + 0xbd84
    rbx = 0x0000000000000001   r12 = 0x00000000000000ff
    r13 = 0x0000000000000001   r14 = 0x0000000000000001
    r15 = 0x0000000002a89560   rip = 0x00007ffbe0abfd84
    rsp = 0x00007ffbdf470e00   rbp = 0x0000000002a89530
    Found by: given as instruction pointer in context
 1  phantomjs + 0xcc07b
    rip = 0x00000000004cc07c   rsp = 0x00007ffbdf470e30
    Found by: stack scanning
 2  libpthread-2.15.so + 0x1187f
    rip = 0x00007ffbe0ac5880   rsp = 0x00007ffbdf470e80
    Found by: stack scanning
 3  phantomjs + 0xcc1a8
    rip = 0x00000000004cc1a9   rsp = 0x00007ffbdf470ea0
    Found by: stack scanning
 4  libpthread-2.15.so + 0x7e99
    rip = 0x00007ffbe0abbe9a   rsp = 0x00007ffbdf470eb0
    Found by: stack scanning
 5  libpthread-2.15.so + 0x1187f
    rip = 0x00007ffbe0ac5880   rsp = 0x00007ffbdf470f58
    Found by: stack scanning
 6  libc-2.15.so + 0xf24bc
    rip = 0x00007ffbdffd94bd   rsp = 0x00007ffbdf470fc0
    Found by: stack scanning

Thread 2
 0  libc-2.15.so + 0xeb823
    rbx = 0x00007ffbd8000d30   r12 = 0x0000000000000000
    r13 = 0x00007ffbd8000a98   r14 = 0x0000000000000008
    r15 = 0x00007ffbd8000a98   rip = 0x00007ffbdffd2823
    rsp = 0x00007ffbdeb57b50   rbp = 0x00007ffbd8000fc8
    Found by: given as instruction pointer in context
 1  phantomjs + 0x183b215
    rip = 0x0000000001c3b216   rsp = 0x00007ffbdeb57b60
    Found by: stack scanning
 2  ld-2.15.so + 0x15234
    rip = 0x00007ffbe15c4235   rsp = 0x00007ffbdeb57b90
    Found by: stack scanning
 3  phantomjs + 0x5430c
    rip = 0x000000000045430d   rsp = 0x00007ffbdeb57bb0
    Found by: stack scanning
 4  phantomjs + 0x183d066
    rip = 0x0000000001c3d067   rsp = 0x00007ffbdeb57bf0
    Found by: stack scanning
 5  libpthread-2.15.so + 0x2d2f
    rip = 0x00007ffbe0ab6d30   rsp = 0x00007ffbdeb57bf8
    Found by: stack scanning
 6  phantomjs + 0x18269e7
    rip = 0x0000000001c269e8   rsp = 0x00007ffbdeb57c20
    Found by: stack scanning
 7  phantomjs + 0x17460a4
    rip = 0x0000000001b460a5   rsp = 0x00007ffbdeb57c30
    Found by: stack scanning
 8  phantomjs + 0x5430c
    rip = 0x000000000045430d   rsp = 0x00007ffbdeb57c38
    Found by: stack scanning
 9  librt-2.15.so + 0x415c
    rip = 0x00007ffbe0cd515d   rsp = 0x00007ffbdeb57c50
    Found by: stack scanning
10  phantomjs + 0x177be03
    rip = 0x0000000001b7be04   rsp = 0x00007ffbdeb57c60
    Found by: stack scanning
11  phantomjs + 0x181832d
    rip = 0x0000000001c1832e   rsp = 0x00007ffbdeb57c80
    Found by: stack scanning
12  phantomjs + 0x5430c
    rip = 0x000000000045430d   rsp = 0x00007ffbdeb57c88
    Found by: stack scanning
13  phantomjs + 0xbfffff
    rip = 0x0000000001000000   rsp = 0x00007ffbdeb57ca0
    Found by: stack scanning
14  phantomjs + 0x177bda8
    rip = 0x0000000001b7bda9   rsp = 0x00007ffbdeb57cb0
    Found by: stack scanning
15  phantomjs + 0x183b77c
    rip = 0x0000000001c3b77d   rsp = 0x00007ffbdeb57cc0
    Found by: stack scanning
16  phantomjs + 0x5430c
    rip = 0x000000000045430d   rsp = 0x00007ffbdeb57cc8
    Found by: stack scanning
17  phantomjs + 0x183b7e0
    rip = 0x0000000001c3b7e1   rsp = 0x00007ffbdeb57ce0
    Found by: stack scanning
18  phantomjs + 0x5430c
    rip = 0x000000000045430d   rsp = 0x00007ffbdeb57ce8
    Found by: stack scanning
19  phantomjs + 0x183d4a2
    rip = 0x0000000001c3d4a3   rsp = 0x00007ffbdeb57d20
    Found by: stack scanning
20  phantomjs + 0x1813911
    rip = 0x0000000001c13912   rsp = 0x00007ffbdeb57d80
    Found by: stack scanning
21  phantomjs + 0x1813f64
    rip = 0x0000000001c13f65   rsp = 0x00007ffbdeb57d90
    Found by: stack scanning
22  phantomjs + 0x1813b6e
    rip = 0x0000000001c13b6f   rsp = 0x00007ffbdeb57db0
    Found by: stack scanning
23  libstdc++.so.6.0.16 + 0xb5dec
    rip = 0x00007ffbe0869ded   rsp = 0x00007ffbdeb57de0
    Found by: stack scanning
24  phantomjs + 0x1725af6
    rip = 0x0000000001b25af7   rsp = 0x00007ffbdeb57e20
    Found by: stack scanning
25  phantomjs + 0xbfffff
    rip = 0x0000000001000000   rsp = 0x00007ffbdeb57e58
    Found by: stack scanning
26  phantomjs + 0x17288bb
    rip = 0x0000000001b288bc   rsp = 0x00007ffbdeb57e70
    Found by: stack scanning
27  libpthread-2.15.so + 0x7e99
    rip = 0x00007ffbe0abbe9a   rsp = 0x00007ffbdeb57eb0
    Found by: stack scanning

Thread 3
 0  libc-2.15.so + 0xeb823
    rbx = 0x00007ffb90000d30   r12 = 0x00007ffbdd318d30
    r13 = 0x00007ffb90000a98   r14 = 0x0000000000000024
    r15 = 0xfffffffffff0bdc0   rip = 0x00007ffbdffd2823
    rsp = 0x00007ffbdd318b50   rbp = 0x00007ffb90000fc8
    Found by: given as instruction pointer in context
 1  phantomjs + 0x183b1be
    rip = 0x0000000001c3b1bf   rsp = 0x00007ffbdd318b60
    Found by: stack scanning
 2  phantomjs + 0x177be03
    rip = 0x0000000001b7be04   rsp = 0x00007ffbdd318b70
    Found by: stack scanning
 3  phantomjs + 0x54370
    rip = 0x0000000000454371   rsp = 0x00007ffbdd318b78
    Found by: stack scanning
 4  phantomjs + 0x54370
    rip = 0x0000000000454371   rsp = 0x00007ffbdd318b88
    Found by: stack scanning
 5  phantomjs + 0x183b3e2
    rip = 0x0000000001c3b3e3   rsp = 0x00007ffbdd318bb0
    Found by: stack scanning
 6  phantomjs + 0x183d066
    rip = 0x0000000001c3d067   rsp = 0x00007ffbdd318bf0
    Found by: stack scanning
 7  phantomjs + 0x18269e7
    rip = 0x0000000001c269e8   rsp = 0x00007ffbdd318c20
    Found by: stack scanning
 8  phantomjs + 0x174606c
    rip = 0x0000000001b4606d   rsp = 0x00007ffbdd318c30
    Found by: stack scanning
 9  phantomjs + 0x54370
    rip = 0x0000000000454371   rsp = 0x00007ffbdd318c38
    Found by: stack scanning
10  librt-2.15.so + 0x415c
    rip = 0x00007ffbe0cd515d   rsp = 0x00007ffbdd318c50
    Found by: stack scanning
11  phantomjs + 0x177be03
    rip = 0x0000000001b7be04   rsp = 0x00007ffbdd318c60
    Found by: stack scanning
12  phantomjs + 0x181832d
    rip = 0x0000000001c1832e   rsp = 0x00007ffbdd318c80
    Found by: stack scanning
13  phantomjs + 0x54370
    rip = 0x0000000000454371   rsp = 0x00007ffbdd318c88
    Found by: stack scanning
14  phantomjs + 0x54370
    rip = 0x0000000000454371   rsp = 0x00007ffbdd318c98
    Found by: stack scanning
15  phantomjs + 0xc0d002
    rip = 0x000000000100d003   rsp = 0x00007ffbdd318ca0
    Found by: stack scanning
16  phantomjs + 0x177bda8
    rip = 0x0000000001b7bda9   rsp = 0x00007ffbdd318cb0
    Found by: stack scanning
17  phantomjs + 0x183b77c
    rip = 0x0000000001c3b77d   rsp = 0x00007ffbdd318cc0
    Found by: stack scanning
18  phantomjs + 0x54370
    rip = 0x0000000000454371   rsp = 0x00007ffbdd318cc8
    Found by: stack scanning
19  phantomjs + 0x183b7e0
    rip = 0x0000000001c3b7e1   rsp = 0x00007ffbdd318ce0
    Found by: stack scanning
20  phantomjs + 0x54370
    rip = 0x0000000000454371   rsp = 0x00007ffbdd318ce8
    Found by: stack scanning
21  phantomjs + 0x183d4a2
    rip = 0x0000000001c3d4a3   rsp = 0x00007ffbdd318d20
    Found by: stack scanning
22  phantomjs + 0x1813911
    rip = 0x0000000001c13912   rsp = 0x00007ffbdd318d80
    Found by: stack scanning
23  phantomjs + 0x1813f64
    rip = 0x0000000001c13f65   rsp = 0x00007ffbdd318d90
    Found by: stack scanning
24  phantomjs + 0x1813b6e
    rip = 0x0000000001c13b6f   rsp = 0x00007ffbdd318db0
    Found by: stack scanning
25  libstdc++.so.6.0.16 + 0xb5dec
    rip = 0x00007ffbe0869ded   rsp = 0x00007ffbdd318de0
    Found by: stack scanning
26  phantomjs + 0x1725af6
    rip = 0x0000000001b25af7   rsp = 0x00007ffbdd318e20
    Found by: stack scanning
27  phantomjs + 0x17288bb
    rip = 0x0000000001b288bc   rsp = 0x00007ffbdd318e70
    Found by: stack scanning
28  libpthread-2.15.so + 0x7e99
    rip = 0x00007ffbe0abbe9a   rsp = 0x00007ffbdd318eb0
    Found by: stack scanning

Thread 4
 0  libpthread-2.15.so + 0xbd84
    rbx = 0x00000000042d6290   r12 = 0xffffffffffffffff
    r13 = 0x004189374bc6a7ef   r14 = 0x0000000000000000
    r15 = 0x00000000042d62b8   rip = 0x00007ffbe0abfd84
    rsp = 0x00007ffb977fdd60   rbp = 0x00000000042d6e90
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1728e2a
    rip = 0x0000000001b28e2b   rsp = 0x00007ffb977fdd90
    Found by: stack scanning
 2  phantomjs + 0x183c11c
    rip = 0x0000000001c3c11d   rsp = 0x00007ffb977fddb0
    Found by: stack scanning
 3  phantomjs + 0xd6fb2
    rip = 0x00000000004d6fb3   rsp = 0x00007ffb977fde00
    Found by: stack scanning
 4  phantomjs + 0xc7c922
    rip = 0x000000000107c923   rsp = 0x00007ffb977fde30
    Found by: stack scanning
 5  phantomjs + 0xd6a6a
    rip = 0x00000000004d6a6b   rsp = 0x00007ffb977fde60
    Found by: stack scanning
 6  phantomjs + 0x17288bb
    rip = 0x0000000001b288bc   rsp = 0x00007ffb977fde70
    Found by: stack scanning
 7  libpthread-2.15.so + 0x7e99
    rip = 0x00007ffbe0abbe9a   rsp = 0x00007ffb977fdeb0
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x026a1fff  phantomjs  ???  (main)
0x7ffbdc1b5000 - 0x7ffbdc1d6fff  LiberationSans-Bold.ttf  ???
0x7ffbdc1de000 - 0x7ffbdc28dfff  DejaVuSans.ttf  ???
0x7ffbdc28e000 - 0x7ffbdc2affff  LiberationSans-Regular.ttf  ???
0x7ffbdc2b8000 - 0x7ffbdc2cbfff  n019003l.pfb  ???
0x7ffbdc2d5000 - 0x7ffbdc4dcfff  libnss_dns-2.15.so  ???
0x7ffbdc4dd000 - 0x7ffbdc6dffff  libnss_mdns4_minimal.so.2  ???
0x7ffbdc6e0000 - 0x7ffbdc8ecfff  libnss_files-2.15.so  ???
0x7ffbdc8ed000 - 0x7ffbdcb06fff  libresolv-2.15.so  ???
0x7ffbdf482000 - 0x7ffbdf6dcfff  libssl.so.1.0.0  ???
0x7ffbdf6de000 - 0x7ffbdfaa1fff  libcrypto.so.1.0.0  ???
0x7ffbdfaa6000 - 0x7ffbdfccffff  libexpat.so.1.5.2  ???
0x7ffbdfcd0000 - 0x7ffbdfee6fff  libz.so.1.2.3.4  ???
0x7ffbdfee7000 - 0x7ffbe029efff  libc-2.15.so  ???
0x7ffbe02a4000 - 0x7ffbe04b9fff  libgcc_s.so.1  ???
0x7ffbe04ba000 - 0x7ffbe07b3fff  libm-2.15.so  ???
0x7ffbe07b4000 - 0x7ffbe0a9efff  libstdc++.so.6.0.16  ???
0x7ffbe0ab4000 - 0x7ffbe0cccfff  libpthread-2.15.so  ???
0x7ffbe0cd1000 - 0x7ffbe0ed8fff  librt-2.15.so  ???
0x7ffbe0ed9000 - 0x7ffbe10dcfff  libdl-2.15.so  ???
0x7ffbe10dd000 - 0x7ffbe1312fff  libfontconfig.so.1.4.4  ???
0x7ffbe1313000 - 0x7ffbe15aefff  libfreetype.so.6.8.0  ???
0x7ffbe15af000 - 0x7ffbe15d0fff  ld-2.15.so  ???
0x7ffbe15e6000 - 0x7ffbe15e6fff  c05880de57d1f5e948fdfacc138775d9-le64.cache-3  ???
0x7ffbe15e7000 - 0x7ffbe15effff  945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-3  ???
0x7ffbe15f0000 - 0x7ffbe15f1fff  99e8ed0e538f840c565b6ed5dad60d56-le64.cache-3  ???
0x7ffbe15f2000 - 0x7ffbe15f5fff  2cd17615ca594fa2959ae173292e504c-le64.cache-3  ???
0x7ffbe15f6000 - 0x7ffbe15f6fff  e7071f4a29fa870f4323321c154eba04-le64.cache-3  ???
0x7ffbe15f7000 - 0x7ffbe15f7fff  0d8c3b2ac0904cb8a57a757ad11a4a08-le64.cache-3  ???
0x7ffbe15f8000 - 0x7ffbe15fdfff  a755afe4a08bf5b97852ceb7400b47bc-le64.cache-3  ???
0x7ffbe15fe000 - 0x7ffbe1601fff  6d41288fd70b0be22e8c3a91e032eec0-le64.cache-3  ???
0x7ffbe1602000 - 0x7ffbe1611fff  04aabc0a78ac019cf9454389977116d2-le64.cache-3  ???
0x7ffbe1612000 - 0x7ffbe1614fff  385c0604a188198f04d133e54aba7fe7-le64.cache-3  ???
0x7ffbe1615000 - 0x7ffbe1615fff  4794a0821666d79190d59a36cb4f44b5-le64.cache-3  ???
0x7ffbe1616000 - 0x7ffbe1618fff  8801497958630a81b71ace7c5f9b32a8-le64.cache-3  ???
0x7ffbe1619000 - 0x7ffbe161dfff  b47c4e1ecd0709278f4910c18777a504-le64.cache-3  ???
0x7ffbe161e000 - 0x7ffbe162dfff  d52a8644073d54c13679302ca1180695-le64.cache-3  ???
0x7ffbe162e000 - 0x7ffbe17b6fff  locale-archive  ???
0x7ffbe17c1000 - 0x7ffbe17c5fff  3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-3  ???
0x7ffbe17c6000 - 0x7ffbe17c6fff  56cf4f4769d0f4abc89a4895d7bd3ae1-le64.cache-3  ???
0x7ffbe17c7000 - 0x7ffbe17c7fff  b9d506c9ac06c20b433354fa67a72993-le64.cache-3  ???
0x7ffbe17c8000 - 0x7ffbe17cafff  e13b20fdb08344e0e664864cc2ede53d-le64.cache-3  ???
0x7ffbe17cb000 - 0x7ffbe17cefff  7ef2298fde41cc6eeb7af42e48b7d293-le64.cache-3  ???
0x7fff381ff000 - 0x7fff381fffff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
