### ISSUE TITLE
PhantomJS crashes : Segmentation fault, rasterize.js and PHP

### ISSUE THREAD

**Issue by gquincy** [ariya/phantomjs#11461]
Which version of PhantomJS are you using?
    1.9.0

    What steps will reproduce the problem?
    1. Download binary or compile phantomjs per instructions.
    2. Extract from tar
    3. Run rasterize.js and phantomJS with PHP command line

    Which operating system are you using?

Linux vps20545 2.6.32-042stab078.27 #1 SMP Mon Jul 1 20:48:07 MSK 2013 x86_64 x86_64 x86_64 GNU/Linux

    Did you use binary PhantomJS or did you compile it from source?

    Have tried both.

    Misc information:

    
2013-07-05 12:07:48: minidump.cc:3747: INFO: Minidump closing minidump
Operating system: Linux
                  0.0.0 Linux 2.6.32-042stab078.27 #1 SMP Mon Jul 1 20:48:07 MSK 2013 x86_64
CPU: amd64
     family 16 model 2 stepping 3
     1 CPU

Crash reason:  SIGSEGV
Crash address: 0xbbadbeef

Thread 0 (crashed)
 0  phantomjs + 0xef417
    rbx = 0xffffffffffffffff   r12 = 0x0000000002f4cd80
    r13 = 0x000000000000007f   r14 = 0x00007f527e8b8820
    r15 = 0x00007f527e8b8720   rip = 0x00000000004ef417
    rsp = 0x00007fff16458800   rbp = 0x7ff8000000000000
    Found by: given as instruction pointer in context
 1  phantomjs + 0xb28950
    rip = 0x0000000000f28951   rsp = 0x00007fff16458810
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 2  phantomjs + 0xb7f6e5
    rip = 0x0000000000f7f6e6   rsp = 0x00007fff16458860
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 3  phantomjs + 0x109378f
    rip = 0x0000000001493790   rsp = 0x00007fff16458890
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 4  phantomjs + 0xb804ad
    rip = 0x0000000000f804ae   rsp = 0x00007fff164588d0
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 5  phantomjs + 0x1ce8bfd
    rip = 0x00000000020e8bfe   rsp = 0x00007fff164589b8
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 6  phantomjs + 0xed776
    rip = 0x00000000004ed777   rsp = 0x00007fff164589f0
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 7  phantomjs + 0xd7dff
    rip = 0x00000000004d7e00   rsp = 0x00007fff16458a00
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 8  phantomjs + 0x43cc2a
    rip = 0x000000000083cc2b   rsp = 0x00007fff16458a10
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 9  phantomjs + 0x188c3ff
    rip = 0x0000000001c8c400   rsp = 0x00007fff16458a20
    rbp = 0x7ff8000000000000
    Found by: stack scanning
10  phantomjs + 0x43d9d4
    rip = 0x000000000083d9d5   rsp = 0x00007fff16458a80
    rbp = 0x7ff8000000000000
    Found by: stack scanning
11  phantomjs + 0xd7dff
    rip = 0x00000000004d7e00   rsp = 0x00007fff16458ad0
    rbp = 0x7ff8000000000000
    Found by: stack scanning
12  phantomjs + 0xb81f30
    rip = 0x0000000000f81f31   rsp = 0x00007fff16458b50
    rbp = 0x7ff8000000000000
    Found by: stack scanning
13  phantomjs + 0x114741
    rip = 0x0000000000514742   rsp = 0x00007fff16458b70
    rbp = 0x7ff8000000000000
    Found by: stack scanning
14  phantomjs + 0xb03cc
    rip = 0x00000000004b03cd   rsp = 0x00007fff16458ba0
    rbp = 0x7ff8000000000000
    Found by: stack scanning
15  phantomjs + 0x45c046
    rip = 0x000000000085c047   rsp = 0x00007fff16458bd0
    rbp = 0x7ff8000000000000
    Found by: stack scanning
16  phantomjs + 0xe6506
    rip = 0x00000000004e6507   rsp = 0x00007fff16458be0
    rbp = 0x7ff8000000000000
    Found by: stack scanning
17  phantomjs + 0x19588ef
    rip = 0x0000000001d588f0   rsp = 0x00007fff16458c08
    rbp = 0x7ff8000000000000
    Found by: stack scanning
18  phantomjs + 0xe657f
    rip = 0x00000000004e6580   rsp = 0x00007fff16458c20
    rbp = 0x7ff8000000000000
    Found by: stack scanning
19  phantomjs + 0x79b90
    rip = 0x0000000000479b91   rsp = 0x00007fff16458c60
    rbp = 0x7ff8000000000000
    Found by: stack scanning

Thread 1
 0  libpthread-2.15.so + 0xbd84
    rbx = 0x0000000002ad9088   r12 = 0x0000000002acafe0
    r13 = 0x00007f527c66b9c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007f527dcc2d84
    rsp = 0x00007f527c66adf0   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  phantomjs + 0xd4ebb
    rip = 0x00000000004d4ebc   rsp = 0x00007f527c66ae20
    Found by: stack scanning
 2  libc-2.15.so + 0x977f
    rip = 0x00007f527d0ef780   rsp = 0x00007f527c66ae28
    Found by: stack scanning
 3  libpthread-2.15.so + 0x1187f
    rip = 0x00007f527dcc8880   rsp = 0x00007f527c66ae50
    Found by: stack scanning
 4  ld-2.15.so + 0x15234
    rip = 0x00007f527e7c7235   rsp = 0x00007f527c66ae60
    Found by: stack scanning
 5  libpthread-2.15.so + 0x1187f
    rip = 0x00007f527dcc8880   rsp = 0x00007f527c66ae80
    Found by: stack scanning
 6  phantomjs + 0xd5058
    rip = 0x00000000004d5059   rsp = 0x00007f527c66aea0
    Found by: stack scanning
 7  libpthread-2.15.so + 0x7e99
    rip = 0x00007f527dcbee9a   rsp = 0x00007f527c66aeb0
    Found by: stack scanning
 8  libpthread-2.15.so + 0x1187f
    rip = 0x00007f527dcc8880   rsp = 0x00007f527c66af58
    Found by: stack scanning
 9  libc-2.15.so + 0xf3ccc
    rip = 0x00007f527d1d9ccd   rsp = 0x00007f527c66afc0
    Found by: stack scanning

Thread 2
 0  libc-2.15.so + 0xed033
    rbx = 0x0000000000000000   r12 = 0x00007f527bc69d80
    r13 = 0x0000000000000008   r14 = 0x00007f5274000a98
    r15 = 0x00007f5274000d30   rip = 0x00007f527d1d3033
    rsp = 0x00007f527bc69b50   rbp = 0x00007f52740008e0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x18fcf26
    rip = 0x0000000001cfcf27   rsp = 0x00007f527bc69b60
    Found by: stack scanning
 2  ld-2.15.so + 0xa29d
    rip = 0x00007f527e7bc29e   rsp = 0x00007f527bc69ba0
    Found by: stack scanning
 3  phantomjs + 0x18fe1e6
    rip = 0x0000000001cfe1e7   rsp = 0x00007f527bc69bf0
    Found by: stack scanning
 4  phantomjs + 0x18ed6b6
    rip = 0x0000000001ced6b7   rsp = 0x00007f527bc69c10
    Found by: stack scanning
 5  phantomjs + 0x17f85c2
    rip = 0x0000000001bf85c3   rsp = 0x00007f527bc69c20
    Found by: stack scanning
 6  linux-gate.so + 0x828
    rip = 0x00007fff164e9829   rsp = 0x00007f527bc69c50
    Found by: stack scanning
 7  librt-2.15.so + 0x415c
    rip = 0x00007f527ded815d   rsp = 0x00007f527bc69c60
    Found by: stack scanning
 8  phantomjs + 0x1837773
    rip = 0x0000000001c37774   rsp = 0x00007f527bc69c70
    Found by: stack scanning
 9  phantomjs + 0x1837678
    rip = 0x0000000001c37679   rsp = 0x00007f527bc69cb0
    Found by: stack scanning
10  phantomjs + 0x18fdba5
    rip = 0x0000000001cfdba6   rsp = 0x00007f527bc69cc0
    Found by: stack scanning
11  phantomjs + 0x18fec91
    rip = 0x0000000001cfec92   rsp = 0x00007f527bc69d30
    Found by: stack scanning
12  phantomjs + 0x18d40b4
    rip = 0x0000000001cd40b5   rsp = 0x00007f527bc69d80
    Found by: stack scanning
13  phantomjs + 0x18d48a8
    rip = 0x0000000001cd48a9   rsp = 0x00007f527bc69d90
    Found by: stack scanning
14  phantomjs + 0x18d4517
    rip = 0x0000000001cd4518   rsp = 0x00007f527bc69db0
    Found by: stack scanning
15  phantomjs + 0x17d69f5
    rip = 0x0000000001bd69f6   rsp = 0x00007f527bc69e10
    Found by: stack scanning
16  phantomjs + 0x17d98c1
    rip = 0x0000000001bd98c2   rsp = 0x00007f527bc69e60
    Found by: stack scanning
17  libpthread-2.15.so + 0x7e99
    rip = 0x00007f527dcbee9a   rsp = 0x00007f527bc69eb0
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x026e3fff  phantomjs  ???  (main)
0x7f527c66c000 - 0x7f527c8c8fff  libssl.so.1.0.0  ???
0x7f527c8ca000 - 0x7f527cca0fff  libcrypto.so.1.0.0  ???
0x7f527cca5000 - 0x7f527cecefff  libexpat.so.1.5.2  ???
0x7f527cecf000 - 0x7f527d0e5fff  libz.so.1.2.3.4  ???
0x7f527d0e6000 - 0x7f527d49ffff  libc-2.15.so  ???
0x7f527d4a5000 - 0x7f527d6bafff  libgcc_s.so.1  ???
0x7f527d6bb000 - 0x7f527d9b6fff  libm-2.15.so  ???
0x7f527d9b7000 - 0x7f527dca1fff  libstdc++.so.6.0.16  ???
0x7f527dcb7000 - 0x7f527decffff  libpthread-2.15.so  ???
0x7f527ded4000 - 0x7f527e0dbfff  librt-2.15.so  ???
0x7f527e0dc000 - 0x7f527e2dffff  libdl-2.15.so  ???
0x7f527e2e0000 - 0x7f527e515fff  libfontconfig.so.1.4.4  ???
0x7f527e516000 - 0x7f527e7b1fff  libfreetype.so.6.8.0  ???
0x7f527e7b2000 - 0x7f527e7d3fff  ld-2.15.so  ???
0x7f527e9ac000 - 0x7f527e9b4fff  945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-3  ???
0x7f527e9c4000 - 0x7f527e9ccfff  6d41288fd70b0be22e8c3a91e032eec0-le64.cache-3  ???
0x7f527e9cd000 - 0x7f527e9d1fff  3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-3  ???
0x7fff164e9000 - 0x7fff164eafff  linux-gate.so  ???

I can't see where the problem is but I hope you will.

Grég

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
