### ISSUE TITLE
PhantomJs crashes loading Page with BlanketJS

### ISSUE THREAD

**Issue by FoxGit** [ariya/phantomjs#11462]
Hi I have a project, which uses BlanketJS to create coverage reports für my client side unit tests. I like to run the test via PhantomJS so I can automate them. Unfortunately it fails.

    Which version of PhantomJS are you using?
    1.9.1

    Which operating system are you using?
    Linux 3.8.0-26-generic #38-Ubuntu

    Did you use binary PhantomJS or did you compile it from source?
    Installed via npm.

## test.html
    <!doctype html>
    <html>
    <head>
    	<meta charset="utf-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    	<title>Mocha Spec Runner</title>
    	<link rel="stylesheet" href="../../components/mocha/mocha.css">
    	<script src="../../components/mocha/mocha.js" type="text/javascript" charset="utf-8"></script>
    	<script src="../../components/sinon/index.js" type="text/javascript" charset="utf-8"></script>
    	<link rel="stylesheet" type="text/css" href="../../styles/aktionsmenue.css">
    </head>
    <body>
    	<div id="mocha"></div>   
    	<script type="text/javascript" src="../../components/requirejs/require.js" data-main="../runner/specRunner.js"></script>
    	<script src="../../components/blanket/dist/qunit/blanket.js" 
	        data-cover-adapter="../../components/blanket/src/adapters/mocha-blanket.js" 
	        data-cover-flags="debug branchTracking" 
	        data-cover-only="../../scripts/"
	        data-cover-reporter="lib/blanketLcovReporter.js"></script>
    </body>
    </html>

## Error:
Operating system: Linux
                  0.0.0 Linux 3.8.0-26-generic #38-Ubuntu SMP Mon Jun 17 21:43:33 UTC 2013 x86_64
CPU: amd64
     family 6 model 60 stepping 3
     1 CPU

Crash reason:  SIGSEGV
Crash address: 0x10

Thread 0 (crashed)
 0  phantomjs!WebCore::QNetworkReplyHandler::release [OwnPtr.h : 65 + 0x0]
    rbx = 0x0000000000000000   r12 = 0x00000000004b9170
    r13 = 0x00007f9f76d5ada8   r14 = 0x00007f9f76d5ae80
    r15 = 0x00007f9f76d5ad90   rip = 0x0000000000ada471
    rsp = 0x00007fffbc1bdc50   rbp = 0x0000000004307d40
    Found by: given as instruction pointer in context
 1  phantomjs!WebCore::FrameLoaderClientQt::download [FrameLoaderClientQt.cpp : 1007 + 0xf]
    rbx = 0x0000000004307d50   r12 = 0x00000000004b9170
    r13 = 0x00007f9f76d5ada8   r14 = 0x00007f9f76d5ae80
    r15 = 0x00007f9f76d5ad90   rip = 0x00000000004b91a8
    rsp = 0x00007fffbc1bdc70   rbp = 0x0000000004307d40
    Found by: call frame info
 2  phantomjs!WebCore::MainResourceLoader::continueAfterContentPolicy [MainResourceLoader.cpp : 277 + 0x23]
    rbx = 0x0000000004307d50   r12 = 0x00000000004b9170
    r13 = 0x00007f9f76d5ada8   r14 = 0x00007f9f76d5ae80
    r15 = 0x00007f9f76d5ad90   rip = 0x00000000008737b8
    rsp = 0x00007fffbc1bdcb0   rbp = 0x00007f9f76d5ad80
    Found by: call frame info
 3  phantomjs!WebCore::MainResourceLoader::continueAfterContentPolicy [MainResourceLoader.cpp : 333 + 0xd]
    rbx = 0x00007f9f76d5ad80   r12 = 0x0000000000000001
    r13 = 0x0000000000000000   r14 = 0x0000000004307d40
    r15 = 0x0000000000000000   rip = 0x0000000000873dde
    rsp = 0x00007fffbc1bddb0   rbp = 0x0000000000000001
    Found by: call frame info
 4  phantomjs!WebCore::PolicyChecker::continueAfterContentPolicy [PolicyChecker.cpp : 187 + 0xa]
    rbx = 0x00007f9f81152998   r12 = 0x0000000000000001
    r13 = 0x0000000000000000   r14 = 0x0000000004307d40
    r15 = 0x0000000000000000   rip = 0x000000000087f9ce
    rsp = 0x00007fffbc1bddd0   rbp = 0x00007f9f76d5ada8
    Found by: call frame info
 5  phantomjs!WebCore::FrameLoaderClientQt::dispatchDecidePolicyForResponse [FrameLoaderClientQt.cpp : 245 + 0x50]
    rbx = 0x00000000004bdc20   r12 = 0x000000000087f990
    r13 = 0x0000000000000000   r14 = 0x0000000004307d40
    r15 = 0x0000000000000000   rip = 0x00000000004bd641
    rsp = 0x00007fffbc1bdf40   rbp = 0x00007f9f76d5ada8
    Found by: call frame info
 6  phantomjs!WebCore::MainResourceLoader::didReceiveResponse [MainResourceLoader.cpp : 428 + 0x21]
    rbx = 0x00007f9f76d5ad88   r12 = 0x0000000000003dbf
    r13 = 0x00007f9f75c86638   r14 = 0x0000000003972200
    r15 = 0x00007f9f75c86650   rip = 0x00000000008758a3
    rsp = 0x00007fffbc1bdfa0   rbp = 0x00007f9f76d5ada8
    Found by: call frame info
 7  phantomjs!WebCore::BlobResourceHandle::notifyResponseOnSuccess [BlobResourceHandle.cpp : 555 + 0x16]
    rbx = 0x00007fffbc1be170   r12 = 0x0000000000003dbf
    r13 = 0x00007f9f75c86638   r14 = 0x0000000003972200
    r15 = 0x00007f9f75c86650   rip = 0x0000000000968700
    rsp = 0x00007fffbc1be070   rbp = 0x00007f9fc92e36c0
    Found by: call frame info
 8  phantomjs!WebCore::BlobResourceHandle::getSizeForNext [BlobResourceHandle.cpp : 245 + 0xb]
    rbx = 0x00007f9f75c86670   r12 = 0x0000000000000000
    r13 = 0x00007fffbc1be220   r14 = 0x0000000003972208
    r15 = 0x00000000043564a0   rip = 0x0000000000968dbb
    rsp = 0x00007fffbc1be1e0   rbp = 0x00007f9f75c86630
    Found by: call frame info
 9  phantomjs!WebCore::BlobResourceHandle::didGetSize [BlobResourceHandle.cpp : 294 + 0x4]
    rbx = 0x00007f9f75c86630   r12 = 0x0000000000000000
    r13 = 0x00007fffbc1be220   r14 = 0x0000000003972208
    r15 = 0x00000000043564a0   rip = 0x0000000000968f20
    rsp = 0x00007fffbc1be220   rbp = 0x00007f9f75c86688
    Found by: call frame info
10  phantomjs!WebCore::BlobResourceHandle::getSizeForNext [BlobResourceHandle.cpp : 255 + 0x9]
    rbx = 0x00007f9f75c86630   r12 = 0x00007f9f75c86650
    r13 = 0x0000000000000000   r14 = 0x0000000003972208
    r15 = 0x00000000043564a0   rip = 0x0000000000968d74
    rsp = 0x00007fffbc1be280   rbp = 0x00007f9f75c86630
    Found by: call frame info
11  phantomjs!WebCore::BlobResourceHandle::doStart [BlobResourceHandle.cpp : 229 + 0x7]
    rbx = 0x00007f9f75c86630   r12 = 0x00007f9f75c86650
    r13 = 0x0000000000000000   r14 = 0x0000000003972208
    r15 = 0x00000000043564a0   rip = 0x0000000000969146
    rsp = 0x00007fffbc1be2c0   rbp = 0x00007f9f75c86630
    Found by: call frame info
12  phantomjs!WebCore::delayedStartBlobResourceHandle [BlobResourceHandle.cpp : 190 + 0x4]
    rbx = 0x00007f9f75c86630   r12 = 0x00000000009691a0
    r13 = 0x0000000000000000   r14 = 0x0000000003972208
    r15 = 0x00000000043564a0   rip = 0x00000000009691b6
    rsp = 0x00007fffbc1be2f0   rbp = 0x00007f9f75c86630
    Found by: call frame info
13  phantomjs!WTF::dispatchFunctionsFromMainThread [MainThread.cpp : 155 + 0x5]
    rbx = 0x00007f9fcd8750e0   r12 = 0x00000000009691a0
    r13 = 0x0000000000000000   r14 = 0x0000000003972208
    r15 = 0x00000000043564a0   rip = 0x00000000004e5a85
    rsp = 0x00007fffbc1be310   rbp = 0x00007f9f75c86630
    Found by: call frame info
14  phantomjs!QObject::event [qobject.cpp : 1191 + 0x8]
    rbx = 0x00000000041e0790   r12 = 0x00000000043564a0
    r13 = 0x0000000003974ab0   r14 = 0x0000000003972208
    r15 = 0x00000000043564a0   rip = 0x0000000001cefc08
    rsp = 0x00007fffbc1be340   rbp = 0x0000000000000000
    Found by: call frame info
15  phantomjs!QApplicationPrivate::notify_helper [qapplication.cpp : 4562 + 0xc]
    rbx = 0x00007fffbc1beca0   r12 = 0x00000000043564a0
    r13 = 0x0000000003974ab0   r14 = 0x0000000003972208
    r15 = 0x00000000043564a0   rip = 0x00000000015decaf
    rsp = 0x00007fffbc1be4e0   rbp = 0x00000000041e0790
    Found by: call frame info
16  phantomjs!QApplication::notify [qapplication.cpp : 4423 + 0x17]
    rbx = 0x00007fffbc1beca0   r12 = 0x00000000043564a0
    r13 = 0x00007fffbc1beca0   r14 = 0x0000000003972208
    r15 = 0x00000000043564a0   rip = 0x00000000015e793b
    rsp = 0x00007fffbc1be510   rbp = 0x00000000041e0790
    Found by: call frame info
17  phantomjs!QCoreApplication::notifyInternal [qcoreapplication.cpp : 946 + 0x2]
    rbx = 0x00000000039721c0   r12 = 0x00000000043564a0
    r13 = 0x00007fffbc1beca0   r14 = 0x0000000003972208
    r15 = 0x00000000039721fc   rip = 0x0000000001cde3b4
    rsp = 0x00007fffbc1be9e0   rbp = 0x00000000041e0790
    Found by: call frame info
18  phantomjs!QCoreApplicationPrivate::sendPostedEvents [qcoreapplication.h : 231 + 0x1f]
    rbx = 0x00000000043564a0   r12 = 0x00000000039721c0
    r13 = 0x00000000041e0790   r14 = 0x0000000003972208
    r15 = 0x00000000039721fc   rip = 0x0000000001cdf314
    rsp = 0x00007fffbc1bea30   rbp = 0x0000000003eea750
    Found by: call frame info
19  phantomjs!QEventDispatcherQPA::processEvents [qcoreapplication.h : 236 + 0xb]
    rbx = 0x0000000003c0bb60   r12 = 0x0000000000000000
    r13 = 0x0000000003971560   r14 = 0x00007fffbc1beb30
    r15 = 0x00000000039722d8   rip = 0x000000000163a623
    rsp = 0x00007fffbc1beaf0   rbp = 0x0000000003976030
    Found by: call frame info
20  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x0000000003c0bb60   r12 = 0x00007fffbc1bebc0
    r13 = 0x00007fffbc1bebd0   r14 = 0x0000000003972230
    r15 = 0x00000000039722d8   rip = 0x0000000001cdd495
    rsp = 0x00007fffbc1beb30   rbp = 0x00007fffbc1beb70
    Found by: call frame info
21  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x0000000003c0bb60   r12 = 0x00007fffbc1bebc0
    r13 = 0x00007fffbc1bebd0   r14 = 0x0000000003972230
    r15 = 0x00000000039722d8   rip = 0x0000000001cdd8f8
    rsp = 0x00007fffbc1beb60   rbp = 0x00007fffbc1beca0
    Found by: call frame info
22  phantomjs!QCoreApplication::exec [qcoreapplication.cpp : 1218 + 0x4]
    rbx = 0x00000000039721c0   r12 = 0x00007fffbc1beca0
    r13 = 0x00007fffbc1bee50   r14 = 0x00007fffbc1bec10
    r15 = 0x0000000000000000   rip = 0x0000000001cdf7ab
    rsp = 0x00007fffbc1bebc0   rbp = 0x00000000039721c0
    Found by: call frame info
23  phantomjs!main [main.cpp : 121 + 0x4]
    rbx = 0x00000000039f4ee0   r12 = 0x00007fffbc1beca0
    r13 = 0x00007fffbc1bee50   r14 = 0x00007fffbc1bec10
    r15 = 0x0000000000000000   rip = 0x0000000000427cb2
    rsp = 0x00007fffbc1bec00   rbp = 0x00007fffbc1bee38
    Found by: call frame info
24  libc-2.17.so + 0x21ea4
    rbx = 0x0000000000000000   r12 = 0x0000000000407cc0
    r13 = 0x00007fffbc1bee30   r14 = 0x0000000000000000
    r15 = 0x0000000000000000   rip = 0x00007f9fcc13eea5
    rsp = 0x00007fffbc1bed60   rbp = 0x0000000000000000
    Found by: call frame info
25  phantomjs + 0x27a5f
    rip = 0x0000000000427a60   rsp = 0x00007fffbc1bed80
    Found by: stack scanning

Thread 1
 0  libc-2.17.so + 0xc0d3d
    rbx = 0x00007f9fcae4ec60   r12 = 0x0000000002ad0160
    r13 = 0x00007f9f821a4710   r14 = 0x0000000002ad81a0
    r15 = 0x0000000002ad8170   rip = 0x00007f9fcc1ddd3d
    rsp = 0x00007f9fcae4ec40   rbp = 0x00000000ffffffff
    Found by: given as instruction pointer in context
 1  libc-2.17.so + 0xc0be0
    rip = 0x00007f9fcc1ddbe1   rsp = 0x00007f9fcae4ec50
    Found by: stack scanning

Thread 2
 0  libc-2.17.so + 0xf2233
    rbx = 0x0000000000000000   r12 = 0x00007f9fca64dd80
    r13 = 0x0000000000000008   r14 = 0x00007f9fc4000a98
    r15 = 0x00007f9fc4000d30   rip = 0x00007f9fcc20f233
    rsp = 0x00007f9fca64db50   rbp = 0x00007f9fc40008e0
    Found by: given as instruction pointer in context
 1  phantomjs!qt_safe_select [qcore_unix.cpp : 83 + 0x15]
    rip = 0x0000000001d06307   rsp = 0x00007f9fca64db60
    Found by: stack scanning
 2  phantomjs!QEventDispatcherUNIXPrivate::doSelect [qeventdispatcher_unix.cpp : 223 + 0xd]
    rbx = 0x00007f9fc40012b0   r12 = 0x00007f9fca64dd80
    r13 = 0x00007f9fc40008e0   r14 = 0x0000000000000000
    r15 = 0x00007f9fc4000d30   rip = 0x0000000001d075c7
    rsp = 0x00007f9fca64dbf0   rbp = 0x00007f9fc40008e0
    Found by: call frame info
 3  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 937 + 0x4]
    rbx = 0x00007f9fc40012b0   r12 = 0x00007f9fca64dd80
    r13 = 0x00007f9fc40008c0   r14 = 0x0000000000000001
    r15 = 0x00000000039f6348   rip = 0x0000000001d08072
    rsp = 0x00007f9fca64dd30   rbp = 0x00007f9fc40008e0
    Found by: call frame info
 4  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x00007f9fc40012b0   r12 = 0x00007f9fca64de10
    r13 = 0x00007f9fca64de20   r14 = 0x0000000003972230
    r15 = 0x00000000039f6348   rip = 0x0000000001cdd495
    rsp = 0x00007f9fca64dd80   rbp = 0x00007f9fca64ddc0
    Found by: call frame info
 5  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x00007f9fc40012b0   r12 = 0x00007f9fca64de10
    r13 = 0x00007f9fca64de20   r14 = 0x0000000003972230
    r15 = 0x00000000039f6348   rip = 0x0000000001cdd8f8
    rsp = 0x00007f9fca64ddb0   rbp = 0x00007fffbc1beca0
    Found by: call frame info
 6  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
    rbx = 0x00000000039f62c0   r12 = 0x00000000039f6348
    r13 = 0x0000000000000001   r14 = 0x00007fffbc1be180
    r15 = 0x0000000000001000   rip = 0x0000000001bdfdd6
    rsp = 0x00007f9fca64de10   rbp = 0x00000000039f6348
    Found by: call frame info
 7  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x00000000039f6348   r12 = 0x00000000039bf5e0
    r13 = 0x0000000000000001   r14 = 0x00007fffbc1be180
    r15 = 0x0000000000001000   rip = 0x0000000001be2ca2
    rsp = 0x00007f9fca64de60   rbp = 0x0000000003a09f80
    Found by: call frame info
 8  libpthread-2.17.so + 0x7f8d
    rbx = 0x0000000000000000   r12 = 0x0000000000000000
    r13 = 0x00007f9fcda26060   r14 = 0x00007fffbc1be180
    r15 = 0x0000000000001000   rip = 0x00007f9fccd0af8e
    rsp = 0x00007f9fca64deb0   rbp = 0x0000000000000000
    Found by: call frame info

Thread 3
 0  libc-2.17.so + 0xf2233
    rbx = 0x00007f9fc8e31d30   r12 = 0x0000000000002d3a
    r13 = 0x0000000000000013   r14 = 0x00007f9f7c000a98
    r15 = 0x00007f9f7c000d30   rip = 0x00007f9fcc20f233
    rsp = 0x00007f9fc8e31b50   rbp = 0x0000000000006783
    Found by: given as instruction pointer in context
 1  phantomjs!qt_safe_select [qcore_unix.cpp : 93 + 0x16]
    rip = 0x0000000001d06208   rsp = 0x00007f9fc8e31b60
    Found by: stack scanning
 2  phantomjs!QEventDispatcherUNIXPrivate::doSelect [qeventdispatcher_unix.cpp : 223 + 0xd]
    rbx = 0x00007f9f7c0012b0   r12 = 0x00007f9fc8e31d80
    r13 = 0x00007f9f7c0008e0   r14 = 0x00007f9fc8e31d30
    r15 = 0x00007f9f7c000d30   rip = 0x0000000001d075c7
    rsp = 0x00007f9fc8e31bf0   rbp = 0x00007f9f7c0008e0
    Found by: call frame info
 3  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 937 + 0x4]
    rbx = 0x00007f9f7c0012b0   r12 = 0x00007f9fc8e31d80
    r13 = 0x00007f9f7c0008c0   r14 = 0x0000000000000001
    r15 = 0x0000000003c441a8   rip = 0x0000000001d08072
    rsp = 0x00007f9fc8e31d30   rbp = 0x00007f9f7c0008e0
    Found by: call frame info
 4  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x00007f9f7c0012b0   r12 = 0x00007f9fc8e31e10
    r13 = 0x00007f9fc8e31e20   r14 = 0x0000000003972230
    r15 = 0x0000000003c441a8   rip = 0x0000000001cdd495
    rsp = 0x00007f9fc8e31d80   rbp = 0x00007f9fc8e31dc0
    Found by: call frame info
 5  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x00007f9f7c0012b0   r12 = 0x00007f9fc8e31e10
    r13 = 0x00007f9fc8e31e20   r14 = 0x0000000003972230
    r15 = 0x0000000003c441a8   rip = 0x0000000001cdd8f8
    rsp = 0x00007f9fc8e31db0   rbp = 0x00007fffbc1beca0
    Found by: call frame info
 6  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
    rbx = 0x0000000003c44120   r12 = 0x0000000003c441a8
    r13 = 0x0000000000000001   r14 = 0x00007fffbc1ba930
    r15 = 0x0000000000001000   rip = 0x0000000001bdfdd6
    rsp = 0x00007f9fc8e31e10   rbp = 0x0000000003c441a8
    Found by: call frame info
 7  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x0000000003c441a8   r12 = 0x0000000003c441f0
    r13 = 0x0000000000000001   r14 = 0x00007fffbc1ba930
    r15 = 0x0000000000001000   rip = 0x0000000001be2ca2
    rsp = 0x00007f9fc8e31e60   rbp = 0x0000000003c44100
    Found by: call frame info
 8  libpthread-2.17.so + 0x7f8d
    rbx = 0x0000000000000000   r12 = 0x0000000000000000
    r13 = 0x00007f9fcda26060   r14 = 0x00007fffbc1ba930
    r15 = 0x0000000000001000   rip = 0x00007f9fccd0af8e
    rsp = 0x00007f9fc8e31eb0   rbp = 0x0000000000000000
    Found by: call frame info

Thread 4
 0  libpthread-2.17.so + 0xbca4
    rbx = 0x0000000003fa6cc0   r12 = 0x004189374bc6a7ef
    r13 = 0xffffffffffffffff   r14 = 0x0000000003fa6ce8
    r15 = 0x0000000003c60b20   rip = 0x00007f9fccd0eca4
    rsp = 0x00007f9f837fdd10   rbp = 0x00007f9fc9819a10
    Found by: given as instruction pointer in context
 1  phantomjs!QWaitCondition::wait [qwaitcondition_unix.cpp : 86 + 0xa]
    rip = 0x0000000001be39d5   rsp = 0x00007f9f837fdd40
    rbp = 0x00007f9fc9819a10
    Found by: stack scanning
 2  phantomjs!WTF::ThreadCondition::timedWait [ThreadingQt.cpp : 253 + 0x12]
    rbx = 0x00007f9fc9819a08   r12 = 0x0000000000000002
    r13 = 0x00007f9fc9819a08   r14 = 0x00007f9fc9819a10
    r15 = 0x00007f9f837fde20   rip = 0x00000000004e70ea
    rsp = 0x00007f9f837fddc0   rbp = 0x00007f9fc9819a10
    Found by: call frame info
 3  phantomjs!WTF::MessageQueue<WebCore::LocalStorageTask>::waitForMessage [MessageQueue.h : 137 + 0x12]
    rbx = 0x0000000000000002   r12 = 0x0000000000000002
    r13 = 0x00007f9fc9819a08   r14 = 0x00007f9fc9819a10
    r15 = 0x00007f9f837fde20   rip = 0x0000000001185269
    rsp = 0x00007f9f837fdde0   rbp = 0x00007f9fc9819a18
    Found by: call frame info
 4  phantomjs!WebCore::LocalStorageThread::threadEntryPoint [LocalStorageThread.cpp : 68 + 0xa]
    rbx = 0x00007f9f820e1258   r12 = 0x0000000003ff9050
    r13 = 0x0000000000000001   r14 = 0x00007fffbc1bd9f0
    r15 = 0x0000000000000011   rip = 0x0000000001185493
    rsp = 0x00007f9f837fde20   rbp = 0x00007f9fc9819a08
    Found by: call frame info
 5  phantomjs!WTF::ThreadPrivate::run [ThreadingQt.cpp : 66 + 0x6]
    rbx = 0x0000000003ec1ce0   r12 = 0x0000000003ff9050
    r13 = 0x0000000000000001   r14 = 0x00007fffbc1bd9f0
    r15 = 0x0000000000000011   rip = 0x00000000004e68fb
    rsp = 0x00007f9f837fde50   rbp = 0x0000000003ec1ce0
    Found by: call frame info
 6  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x0000000003e881e8   r12 = 0x0000000003ff9050
    r13 = 0x0000000000000001   r14 = 0x00007fffbc1bd9f0
    r15 = 0x0000000000000011   rip = 0x0000000001be2ca2
    rsp = 0x00007f9f837fde60   rbp = 0x0000000003ec1ce0
    Found by: call frame info
 7  libpthread-2.17.so + 0x7f8d
    rbx = 0x0000000000000000   r12 = 0x0000000000000000
    r13 = 0x0000000003c98320   r14 = 0x00007fffbc1bd9f0
    r15 = 0x0000000000000011   rip = 0x00007f9fccd0af8e
    rsp = 0x00007f9f837fdeb0   rbp = 0x0000000000000000
    Found by: call frame info

Thread 5
 0  libpthread-2.17.so + 0xbca4
    rbx = 0x000000000434d6b0   r12 = 0x004189374bc6a7ef
    r13 = 0xffffffffffffffff   r14 = 0x000000000434d6d8
    r15 = 0x0000000003f42510   rip = 0x00007f9fccd0eca4
    rsp = 0x00007f9f83ffed00   rbp = 0x00007f9f76982ce8
    Found by: given as instruction pointer in context
 1  phantomjs!QWaitCondition::wait [qwaitcondition_unix.cpp : 86 + 0xa]
    rip = 0x0000000001be39d5   rsp = 0x00007f9f83ffed30
    Found by: stack scanning
 2  phantomjs!WTF::ThreadCondition::timedWait [ThreadingQt.cpp : 253 + 0x12]
    rbx = 0x00007f9f76982ce0   r12 = 0x0000000000000001
    r13 = 0x00007f9f76982ce0   r14 = 0x00007f9f76982ce8
    r15 = 0x00007f9f83ffee10   rip = 0x00000000004e70ea
    rsp = 0x00007f9f83ffedb0   rbp = 0x00007f9f76982ce8
    Found by: call frame info
 3  phantomjs!WTF::MessageQueue<WebCore::FileThread::Task>::waitForMessage [MessageQueue.h : 137 + 0x12]
    rbx = 0x0000000000000001   r12 = 0x0000000000000001
    r13 = 0x00007f9f76982ce0   r14 = 0x00007f9f76982ce8
    r15 = 0x00007f9f83ffee10   rip = 0x000000000073fc19
    rsp = 0x00007f9f83ffedd0   rbp = 0x00007f9f76982cf0
    Found by: call frame info
 4  phantomjs!WebCore::FileThread::runLoop [FileThread.cpp : 102 + 0xa]
    rbx = 0x000000000434f670   r12 = 0x0000000004356260
    r13 = 0x00007f9f76982cd0   r14 = 0x00007fffbc1bc250
    r15 = 0x0000000000000011   rip = 0x000000000073fd34
    rsp = 0x00007f9f83ffee10   rbp = 0x00007f9f76982ce0
    Found by: call frame info
 5  phantomjs!WTF::ThreadPrivate::run [ThreadingQt.cpp : 66 + 0x6]
    rbx = 0x00000000042f0970   r12 = 0x0000000004356260
    r13 = 0x0000000000000001   r14 = 0x00007fffbc1bc250
    r15 = 0x0000000000000011   rip = 0x00000000004e68fb
    rsp = 0x00007f9f83ffee50   rbp = 0x00000000042f0970
    Found by: call frame info
 6  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x0000000004339bf8   r12 = 0x0000000004356260
    r13 = 0x0000000000000001   r14 = 0x00007fffbc1bc250
    r15 = 0x0000000000000011   rip = 0x0000000001be2ca2
    rsp = 0x00007f9f83ffee60   rbp = 0x00000000042f0970
    Found by: call frame info
 7  libpthread-2.17.so + 0x7f8d
    rbx = 0x0000000000000000   r12 = 0x0000000000000000
    r13 = 0x00007f9f7c005cc0   r14 = 0x00007fffbc1bc250
    r15 = 0x0000000000000011   rip = 0x00007f9fccd0af8e
    rsp = 0x00007f9f83ffeeb0   rbp = 0x0000000000000000
    Found by: call frame info

Loaded modules:
0x00400000 - 0x026e7fff  phantomjs  ???  (main)
0x7f9f7615e000 - 0x7f9f7616efff  n019023l.pfb  ???
0x7f9f76838000 - 0x7f9f7685afff  LiberationSans-Regular.ttf  ???
0x7f9f77337000 - 0x7f9f77348fff  n019004l.pfb  ???
0x7f9f77349000 - 0x7f9f7735cfff  n019003l.pfb  ???
0x7f9f7751a000 - 0x7f9f7756efff  DejaVuSans-ExtraLight.ttf  ???
0x7f9f82f68000 - 0x7f9f82ffdfff  DejaVuSans-Oblique.ttf  ???
0x7f9fc8056000 - 0x7f9fc80f3fff  DejaVuSansCondensed.ttf  ???
0x7f9fc81f7000 - 0x7f9fc8403fff  libnss_files-2.17.so  ???
0x7f9fc8404000 - 0x7f9fc861bfff  libresolv-2.17.so  ???
0x7f9fcae50000 - 0x7f9fcb0abfff  libssl.so.1.0.0  ???
0x7f9fcb0ad000 - 0x7f9fcb483fff  libcrypto.so.1.0.0  ???
0x7f9fcb488000 - 0x7f9fcbcdcfff  locale-archive  ???
0x7f9fcbcdd000 - 0x7f9fcbf05fff  libexpat.so.1.6.0  ???
0x7f9fcbf06000 - 0x7f9fcc11cfff  libz.so.1.2.7  ???
0x7f9fcc11d000 - 0x7f9fcc4dffff  libc-2.17.so  ???
0x7f9fcc4e5000 - 0x7f9fcc6fafff  libgcc_s.so.1  ???
0x7f9fcc6fb000 - 0x7f9fcc9fffff  libm-2.17.so  ???
0x7f9fcca00000 - 0x7f9fcccedfff  libstdc++.so.6.0.17  ???
0x7f9fccd03000 - 0x7f9fccf1bfff  libpthread-2.17.so  ???
0x7f9fccf20000 - 0x7f9fcd127fff  librt-2.17.so  ???
0x7f9fcd128000 - 0x7f9fcd32bfff  libdl-2.17.so  ???
0x7f9fcd32c000 - 0x7f9fcd564fff  libfontconfig.so.1.6.2  ???
0x7f9fcd566000 - 0x7f9fcd802fff  libfreetype.so.6.10.0  ???
0x7f9fcd803000 - 0x7f9fcd825fff  ld-2.17.so  ???
0x7f9fcd98c000 - 0x7f9fcd992fff  gconv-modules.cache  ???
0x7f9fcd993000 - 0x7f9fcd9b8fff  libc.mo  ???
0x7f9fcd9b9000 - 0x7f9fcd9b9fff  c05880de57d1f5e948fdfacc138775d9-le64.cache-3  ???
0x7f9fcd9ba000 - 0x7f9fcd9c2fff  945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-3  ???
0x7f9fcd9c3000 - 0x7f9fcd9c4fff  99e8ed0e538f840c565b6ed5dad60d56-le64.cache-3  ???
0x7f9fcd9c5000 - 0x7f9fcd9c9fff  2cd17615ca594fa2959ae173292e504c-le64.cache-3  ???
0x7f9fcd9ca000 - 0x7f9fcd9cafff  e7071f4a29fa870f4323321c154eba04-le64.cache-3  ???
0x7f9fcd9cb000 - 0x7f9fcd9cbfff  0d8c3b2ac0904cb8a57a757ad11a4a08-le64.cache-3  ???
0x7f9fcd9cc000 - 0x7f9fcd9d1fff  a755afe4a08bf5b97852ceb7400b47bc-le64.cache-3  ???
0x7f9fcd9d2000 - 0x7f9fcd9dafff  6d41288fd70b0be22e8c3a91e032eec0-le64.cache-3  ???
0x7f9fcd9db000 - 0x7f9fcd9eafff  04aabc0a78ac019cf9454389977116d2-le64.cache-3  ???
0x7f9fcd9eb000 - 0x7f9fcd9ebfff  1ac9eb803944fde146138c791f5cc56a-le64.cache-3  ???
0x7f9fcd9ec000 - 0x7f9fcd9eefff  385c0604a188198f04d133e54aba7fe7-le64.cache-3  ???
0x7f9fcd9ef000 - 0x7f9fcd9effff  dc05db6664285cc2f12bf69c139ae4c3-le64.cache-3  ???
0x7f9fcd9f0000 - 0x7f9fcd9f1fff  767a8244fc0220cfb567a839d0392e0b-le64.cache-3  ???
0x7f9fcd9f2000 - 0x7f9fcd9f2fff  4794a0821666d79190d59a36cb4f44b5-le64.cache-3  ???
0x7f9fcd9f3000 - 0x7f9fcd9f5fff  8801497958630a81b71ace7c5f9b32a8-le64.cache-3  ???
0x7f9fcd9f6000 - 0x7f9fcda06fff  d52a8644073d54c13679302ca1180695-le64.cache-3  ???
0x7f9fcda0f000 - 0x7f9fcda13fff  3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-3  ???
0x7f9fcda14000 - 0x7f9fcda14fff  56cf4f4769d0f4abc89a4895d7bd3ae1-le64.cache-3  ???
0x7f9fcda15000 - 0x7f9fcda15fff  b9d506c9ac06c20b433354fa67a72993-le64.cache-3  ???
0x7f9fcda16000 - 0x7f9fcda1afff  b47c4e1ecd0709278f4910c18777a504-le64.cache-3  ???
0x7f9fcda1b000 - 0x7f9fcda1bfff  0c9eb80ebd1c36541ebe2852d3bb0c49-le64.cache-3  ???
0x7f9fcda1c000 - 0x7f9fcda1efff  e13b20fdb08344e0e664864cc2ede53d-le64.cache-3  ???
0x7f9fcda1f000 - 0x7f9fcda22fff  7ef2298fde41cc6eeb7af42e48b7d293-le64.cache-3  ???
0x7fffbc1fe000 - 0x7fffbc1fffff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
