### ISSUE TITLE
Font substitution fails on Debian 7 (wheezy)

### ISSUE THREAD

**Issue by chrisd-indicee** [ariya/phantomjs#11468]
_Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.
1.9.1, 1.6.1 from source, and another build from github master_

_What steps will reproduce the problem?_
1. Set up stock Debian 7 system
1. Install some fonts (as well as fontconfig, freetype, etc (which fonts is not important, I include below the ones I installed):
   apt-get -y install unifont xfonts-unifont ttf-aenigma ttf-ancient-fonts ttf-arphic-bkai00mp ttf-arphic-bsmi00lp ttf-arphic-gbsn00lp ttf-arphic-gkai00mp ttf-arphic-ukai ttf-arphic-uming ttf-bitstream-vera ttf-bpg-georgian-fonts ttf-dejavu ttf-freefont ttf-bengali-fonts ttf-devanagari-fonts ttf-gujarati-fonts ttf-indic-fonts ttf-kannada-fonts ttf-malayalam-fonts ttf-oriya-fonts ttf-punjabi-fonts ttf-tamil-fonts ttf-telugu-fonts ttf-kiloji ttf-kochi-gothic ttf-kochi-mincho ttf-manchufont ttf-sazanami-gothic ttf-sazanami-mincho ttf-sil-yi ttf-takao ttf-umefont ttf-unfonts-core ttf-unfonts-extra ttf-unifont
2. Run rasterize.js against trivial HTML page:
   ./phantomjs ../examples/rasterize.js test.html o.png
   <html><body>
   
   <p style="font-family: Helvetica, Helvetica Neue, Arial,sans-serif">
   This is a test.</p>

<h2 style="font-family: Helvetica, Helvetica Neue, Arial,sans-serif">
I said this is only a test</h2>

<p style="font-family: Helvetica, Helvetica Neue, Arial,sans-serif">
This is a third test.</p>

</body></html>

*What is the expected output? *
![correct](https://f.cloud.github.com/assets/1134027/778606/0f16f3e0-e9b5-11e2-9339-fb0cdecd3276.png)

_What do you see instead?_
![wrong](https://f.cloud.github.com/assets/1134027/778666/1cb654d0-e9b7-11e2-9094-fa8a5e637298.png)

_Which operating system are you using?_
Debian 7 (wheezy) x86_64
Debian 6 (squeeze) x86_64

_Did you use binary PhantomJS or did you compile it from source?_
Both. Same results.

_Please provide any additional information below._
Using strace, I noticed that phantomJS was selecting a font alphabetically. If I removed the font it selected, it would proceed to choose the alphabetically next font. Using fontconfig's debug mode, I was able to see it was interrogating fontconfig.

The two systems went through identical setup steps (including fontconfig rules, tested by copying the /etc/fonts directory from debian 6 system to debian 7 system).

I also tried rendering the test HTML using chromium and konqueror, which are both webkit browsers (konq uses QT also), but both rendered it fine on the debian 7 system.

I haven't yet been able to get an answer from the debian channel on freenode about what may have changed to expose this problem.

**Comment by jglapa** [comment]
Similar, phantom 1.9.8, Ubuntu 12.04 and 14.04. Despite correct `fc-match Arial`, phantomjs chooses a completely different font.
