### ISSUE TITLE
PhantomJS Crash in phantomjs!QTimerInfoList::activateTimers

### ISSUE THREAD

**Issue by jsodini** [ariya/phantomjs#11471]
This crash was found with phantomjs 1.9.1 using Async.js (https://github.com/caolan/async). I was using async.eachLimit of 100, each performing the basic webpage.create().open() with only one callback: onResourceReceived.

Thread 165 (crashed)
 0  phantomjs!QTimerInfoList::activateTimers [qlist.h : 99 + 0x0]
    rbx = 0x000000007f940077   r12 = 0x00007f9377e62d80
    r13 = 0x00007f93f801e852   r14 = 0x0000000000000001
    r15 = 0x0000000006da4d58   rip = 0x0000000001d07c7d
    rsp = 0x00007f9377e62ca0   rbp = 0x00007f93f80fd410
    Found by: given as instruction pointer in context
 1  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 941 + 0x7]
    rbx = 0x0000000000000000   r12 = 0x00007f9377e62d80
    r13 = 0x00007f93f801e852   r14 = 0x0000000000000001
    r15 = 0x0000000006da4d58   rip = 0x0000000001d080c0
    rsp = 0x00007f9377e62d30   rbp = 0x00007f93f80fd410
    Found by: call frame info
 2  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x00007f93f80a1e00   r12 = 0x00007f9377e62e10
    r13 = 0x00007f9377e62e20   r14 = 0x0000000003fe3230
    r15 = 0x0000000006da4d58   rip = 0x0000000001cdd495
    rsp = 0x00007f9377e62d80   rbp = 0x00007f9377e62dc0
    Found by: call frame info
 3  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x00007f93f80a1e00   r12 = 0x00007f9377e62e10
    r13 = 0x00007f9377e62e20   r14 = 0x0000000003fe3230
    r15 = 0x0000000006da4d58   rip = 0x0000000001cdd8f8
    rsp = 0x00007f9377e62db0   rbp = 0x00007fff5aa1a590
    Found by: call frame info
 4  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
    rbx = 0x0000000006da4cd0   r12 = 0x0000000006da4d58
    r13 = 0x0000000000000001   r14 = 0x00007fff5aa15a90
    r15 = 0x0000000000001000   rip = 0x0000000001bdfdd6
    rsp = 0x00007f9377e62e10   rbp = 0x0000000006da4d58
    Found by: call frame info
 5  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x0000000006da4d58   r12 = 0x000000000cd9e660
    r13 = 0x0000000000000001   r14 = 0x00007fff5aa15a90
    r15 = 0x0000000000001000   rip = 0x0000000001be2ca2
    rsp = 0x00007f9377e62e60   rbp = 0x000000000c8ad8e0
    Found by: call frame info
 6  libpthread-2.17.so + 0x7f8d
    rbx = 0x0000000000000000   r12 = 0x0000000000000000
    r13 = 0x00007f9479afd060   r14 = 0x00007fff5aa15a90
    r15 = 0x0000000000001000   rip = 0x00007f9478de1f8e
    rsp = 0x00007f9377e62eb0   rbp = 0x0000000000000000
    Found by: call frame info

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
