### ISSUE TITLE
Timeout when running QUnit test

### ISSUE THREAD

**Issue by nikhilbhatnagar** [ariya/phantomjs#11489]
I am using Jenking to build and run quint test on my project.

4 out of 5 times my build fails because of test failures. Below is the log for your information:

<b>Tests in error: </b>
  checkbox\/4.1-3.2-InsurancesWithDefaultPortfolio.html: Timed out waiting for test
  checkbox\/checkbox.html: Timed out waiting for test
  clock\/footerClockTest.html: Timed out waiting for test
  commonutil\/tlxJsTest.html: Timed out waiting for test
  contactinfo\/changecontactinfo.html: Timed out waiting for test
  ellipsis\/3.0-3.1-OverviewPage.html: Timed out waiting for test
  fundlist\/fundlist-plugin-Checkbox.html: Timed out waiting for test
  fundlist\/fundlist-plugin.html: Timed out waiting for test
  fundsallocation\/changeMultipleFunds.html: Timed out waiting for test

I am using phantomjs-1.9.1 and qunit-1.11.0

One more thing I want to mention is the qunit test always pass when run locally but it fail most of the time when run through jenkins.

**Comment by ariya** [comment]
No more response, closing this for not being action-able.
