### ISSUE TITLE
PhantomJS crashing

### ISSUE THREAD

**Issue by ashwinr** [ariya/phantomjs#11485]
We use phantomjs for running a lot of unit tests against our app (currently ~400 tests), and it crashes sometimes. Please find a stack trace attached. It'll be helpful to figure out why it's crashing. Thanks!

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
