### ISSUE TITLE
Crash report - stackwalked trace (v3)

### ISSUE THREAD

**Issue by Camusensei** [ariya/phantomjs#11482]
Another crash report. Still no new for the old ones (https://github.com/ariya/phantomjs/issues/11431). I don't even know if posting this is useful at all !!!!
(this is Phantomjs-1.9.1-linux-x86_64)

Operating system: Linux
0.0.0 Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.46-1 x86_64
CPU: amd64
     family 6 model 23 stepping 10
     2 CPUs

Crash reason:  SIGABRT
Crash address: 0x3e800004d10

Thread 0 (crashed)
 0  libc-2.13.so + 0x32475
    rbx = 0x000000000459ae10   r12 = 0x000000000459a690
    r13 = 0x000000000459ade0   r14 = 0x0000000004783130
    r15 = 0x000000000477bcd0   rip = 0x00007f279c384475
    rsp = 0x00007fff0d942fa8   rbp = 0x000000000459ae28
    Found by: given as instruction pointer in context
 1  libc-2.13.so + 0x356ef
    rip = 0x00007f279c3876f0   rsp = 0x00007fff0d942fb0
    Found by: stack scanning
 2  ld-2.13.so + 0x55f
    rip = 0x00007f279d979560   rsp = 0x00007fff0d942fd0
    Found by: stack scanning
 3  libc-2.13.so + 0x6b9f
    rip = 0x00007f279c358ba0   rsp = 0x00007fff0d942fe8
    Found by: stack scanning
 4  libm-2.13.so + 0x281fff
    rip = 0x00007f279cb74000   rsp = 0x00007fff0d943038
    Found by: stack scanning
 5  ld-2.13.so + 0xd9f1
    rip = 0x00007f279d9869f2   rsp = 0x00007fff0d943040
    Found by: stack scanning
 6  libstdc++.so.6.0.17 + 0x6589c
    rip = 0x00007f279cbd989d   rsp = 0x00007fff0d9430e0
    Found by: stack scanning
 7  libpthread-2.13.so + 0xe12c
    rip = 0x00007f279ce8912d   rsp = 0x00007fff0d9430f0
    Found by: stack scanning
 8  libstdc++.so.6.0.17 + 0x63995
    rip = 0x00007f279cbd7996   rsp = 0x00007fff0d943110
    Found by: stack scanning
 9  libstdc++.so.6.0.17 + 0x639c2
    rip = 0x00007f279cbd79c3   rsp = 0x00007fff0d943120
    Found by: stack scanning
10  libstdc++.so.6.0.17 + 0x644de
    rip = 0x00007f279cbd84df   rsp = 0x00007fff0d943130
    Found by: stack scanning
11  phantomjs!QCoreApplication::postEvent [qcoreapplication.cpp : 1392 + 0x8]
    rip = 0x0000000001cdebcc   rsp = 0x00007fff0d943140
    Found by: stack scanning
12  phantomjs!QMetaMethod::invoke [qmetaobject.cpp : 1703 + 0x5a]
    rbx = 0x0000000004783130   r12 = 0x00007fff0d9437e0
    r13 = 0x000000000000000b   r14 = 0x0000000000000000
    r15 = 0x000000000477bcd0   rip = 0x0000000001ce8b09
    rsp = 0x00007fff0d9431f0   rbp = 0x0000000000000001
    Found by: call frame info
13  phantomjs!QMetaObject::invokeMethod [qmetaobject.cpp : 1179 + 0x1ba]
    rbx = 0x000000000000000f   r12 = 0x0000000000000000
    r13 = 0x000000000477bcd0   r14 = 0x00007fff0d943560
    r15 = 0x0000000000000000   rip = 0x0000000001ce99de
    rsp = 0x00007fff0d943440   rbp = 0x00007fff0d943780
    Found by: call frame info
14  phantomjs!QNetworkConfigurationManagerPrivate::enablePolling [qobjectdefs.h : 434 + 0xc3]
    rbx = 0x000000000477bcf0   r12 = 0x000000000477bcf1
    r13 = 0x00007fff0d943b80   r14 = 0x0000000004599ef0
    r15 = 0x0000000004599f30   rip = 0x0000000001b4e59d
    rsp = 0x00007fff0d943840   rbp = 0x000000000477bcd0
    Found by: call frame info
15  phantomjs!QNetworkConfigurationManager::QNetworkConfigurationManager [qnetworkconfigmanager.cpp : 243 + 0x7]
    rbx = 0x000000000477bcd0   r12 = 0x00007f279afd0270
    r13 = 0x00007fff0d943b80   r14 = 0x0000000004599ef0
    r15 = 0x0000000004599f30   rip = 0x0000000001b4aa29
    rsp = 0x00007fff0d9439b0   rbp = 0x000000000458b3a0
    Found by: call frame info
16  phantomjs!WebCore::NetworkStateNotifierPrivate::NetworkStateNotifierPrivate [NetworkStateNotifierQt.cpp : 34 + 0x2a]
    rbx = 0x000000000458b3a0   r12 = 0x00007f279afd0270
    r13 = 0x00007fff0d943b80   r14 = 0x0000000004599ef0
    r15 = 0x0000000004599f30   rip = 0x0000000000b57e36
    rsp = 0x00007fff0d9439d0   rbp = 0x0000000004593f90
    Found by: call frame info
17  phantomjs!WebCore::NetworkStateNotifier::NetworkStateNotifier [NetworkStateNotifierQt.cpp : 79 + 0x17]
    rbx = 0x00007f279afd0270   r12 = 0x0000000004599e20
    r13 = 0x00007fff0d943b80   r14 = 0x0000000004599ef0
    r15 = 0x0000000004599f30   rip = 0x0000000000b57ed4
    rsp = 0x00007fff0d9439f0   rbp = 0x0000000004593f90
    Found by: call frame info
18  phantomjs!WebCore::networkStateNotifier [NetworkStateNotifier.cpp : 37 + 0x7]
    rbx = 0x00007f279afd0270   r12 = 0x0000000004599e20
    r13 = 0x00007fff0d943b80   r14 = 0x0000000004599ef0
    r15 = 0x0000000004599f30   rip = 0x0000000000975e0c
    rsp = 0x00007fff0d943a10   rbp = 0x0000000004599e20
    Found by: call frame info
19  phantomjs!WebCore::Page::Page [Page.cpp : 170 + 0x4]
    rbx = 0xbff0000000000000   r12 = 0x0000000004599e20
    r13 = 0x00007fff0d943b80   r14 = 0x0000000004599ef0
    r15 = 0x0000000004599f30   rip = 0x00000000008fff9d
    rsp = 0x00007fff0d943a30   rbp = 0x0000000004599e20
    Found by: call frame info
20  phantomjs!QWebPagePrivate::QWebPagePrivate [qwebpage.cpp : 349 + 0x17]
    rbx = 0x0000000004594db0   r12 = 0x00000000047809f0
    r13 = 0x00007fff0d943b80   r14 = 0x0000000004594dd8
    r15 = 0x0000000004594e58   rip = 0x000000000048d51f
    rsp = 0x00007fff0d943b50   rbp = 0x0000000004599e20
    Found by: call frame info
21  phantomjs!QWebPage::QWebPage [qwebpage.cpp : 1970 + 0x2b]
    rbx = 0x0000000004594db0   r12 = 0x00000000047809f0
    r13 = 0x000000000459c6c0   r14 = 0x00007fff0d944320
    r15 = 0x0000000000000000   rip = 0x00000000004903c5
    rsp = 0x00007fff0d943c30   rbp = 0x0000000004595150
    Found by: call frame info
22  phantomjs!WebPage::WebPage [webpage.cpp : 96 + 0xa]
    rbx = 0x0000000004595150   r12 = 0x000000000459c720
    r13 = 0x000000000459c6c0   r14 = 0x00007fff0d944320
    r15 = 0x0000000000000000   rip = 0x0000000000418267
    rsp = 0x00007fff0d943c50   rbp = 0x00000000047809f0
    Found by: call frame info
23  phantomjs!Phantom::init [phantom.cpp : 102 + 0x40]
    rbx = 0x00000000047809f0   r12 = 0x000000000459c720
    r13 = 0x000000000459c6c0   r14 = 0x00007fff0d944320
    r15 = 0x0000000000000000   rip = 0x0000000000409bf3
    rsp = 0x00007fff0d943db0   rbp = 0x00007fff0d944020
    Found by: call frame info
24  phantomjs!Phantom::instance [phantom.cpp : 154 + 0x4]
    rbx = 0x00007fff0d944430   r12 = 0x00007fff0d9443b0
    r13 = 0x00007fff0d944578   r14 = 0x00007fff0d944320
    r15 = 0x0000000000000000   rip = 0x000000000040b576
    rsp = 0x00007fff0d9442f0   rbp = 0x000000000459c6c0
    Found by: call frame info
25  phantomjs!main [main.cpp : 117 + 0x4]
    rbx = 0x00007fff0d944430   r12 = 0x00007fff0d9443b0
    r13 = 0x00007fff0d944578   r14 = 0x00007fff0d944320
    r15 = 0x0000000000000000   rip = 0x0000000000427c9e
    rsp = 0x00007fff0d944310   rbp = 0x00007fff0d944548
    Found by: call frame info
26  libc-2.13.so + 0x1eeac
    rbx = 0x0000000000000000   r12 = 0x0000000000407cc0
    r13 = 0x00007fff0d944540   r14 = 0x0000000000000000
    r15 = 0x0000000000000000   rip = 0x00007f279c370ead
    rsp = 0x00007fff0d944470   rbp = 0x0000000000000000
    Found by: call frame info
27  phantomjs + 0x27a5f
    rip = 0x0000000000427a60   rsp = 0x00007fff0d944490
    Found by: stack scanning

Thread 1
 0  libpthread-2.13.so + 0xb2d4
    rbx = 0x0000000002ade208   r12 = 0x0000000002ad0160
    r13 = 0x00007f279b8cd9c0   r14 = 0x00007f279db99040
    r15 = 0x0000000000000003   rip = 0x00007f279ce862d4
    rsp = 0x00007f279b8cce10   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  phantomjs!WTF::TCMalloc_PageHeap::scavengerThread [FastMalloc.cpp : 2495 + 0x7]
    rip = 0x00000000004ddafc   rsp = 0x00007f279b8cce40
    Found by: stack scanning
 2  phantomjs!WTF::TCMalloc_PageHeap::runScavengerThread [FastMalloc.cpp : 1618 + 0x4]
    rbx = 0x0000000000000000   r12 = 0x00007f279ce8c1a0
    r13 = 0x00007f279b8cd9c0   r14 = 0x00007f279db99040
    r15 = 0x0000000000000003   rip = 0x00000000004ddc99
    rsp = 0x00007f279b8ccec0   rbp = 0x0000000000000000
    Found by: call frame info
 3  libpthread-2.13.so + 0x6b4f
    rbx = 0x0000000000000000   r12 = 0x00007f279ce8c1a0
    r13 = 0x00007f279b8cd9c0   r14 = 0x00007f279db99040
    r15 = 0x0000000000000003   rip = 0x00007f279ce81b50
    rsp = 0x00007f279b8cced0   rbp = 0x0000000000000000
    Found by: call frame info
 4  libpthread-2.13.so + 0x1119f
    rip = 0x00007f279ce8c1a0   rsp = 0x00007f279b8ccf78
    Found by: stack scanning
 5  libc-2.13.so + 0xdaa7c
    rip = 0x00007f279c42ca7d   rsp = 0x00007f279b8ccfe0
    Found by: stack scanning

Thread 2
 0  libc-2.13.so + 0xd72f9
    rbx = 0x0000000004598d00   r12 = 0xfffffffffff0bdc0
    r13 = 0x0000000004544ab0   r14 = 0x000000000459ae28
    r15 = 0x0000000004783130   rip = 0x00007f279c4292f9
    rsp = 0x00007f279afcb498   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  phantomjs!QMutexPrivate::wait [qmutex_unix.cpp : 99 + 0x22]
    rip = 0x0000000001be1de3   rsp = 0x00007f279afcb4a0
    Found by: stack scanning
 2  phantomjs!QMutex::lock [qmutex.cpp : 164 + 0xc]
    rbx = 0x0000000004598d00   r12 = 0x0000000000000000
    rip = 0x0000000001bddf7c   rsp = 0x00007f279afcb4f0
    rbp = 0x00007f279afcc700
    Found by: call frame info
 3  phantomjs!QNetworkConfigurationManagerPrivate::startPolling [qmutex.h : 188 + 0x7]
    rbx = 0x000000000477bcf0   r12 = 0x0000000000000000
    rip = 0x0000000001b4c548   rsp = 0x00007f279afcb510
    rbp = 0x000000000477bcd0
    Found by: call frame info
 4  phantomjs!QNetworkConfigurationManagerPrivate::qt_static_metacall [moc_qnetworkconfigmanager_p.cpp : 85 + 0x4]
    rbx = 0x000000000477bcd0   r12 = 0x0000000004783130
    r13 = 0x0000000004544ab0   rip = 0x0000000001ba86a6
    rsp = 0x00007f279afcb560   rbp = 0x0000000000000000
    Found by: call frame info
 5  phantomjs!QObject::event [qobject.cpp : 1191 + 0x8]
    rbx = 0x000000000477bcd0   r12 = 0x0000000004783130
    r13 = 0x0000000004544ab0   rip = 0x0000000001cefc08
    rsp = 0x00007f279afcb5a0   rbp = 0x0000000000000000
    Found by: call frame info
 6  phantomjs!QApplicationPrivate::notify_helper [qapplication.cpp : 4562 + 0xc]
    rbx = 0x00007fff0d9443b0   r12 = 0x0000000004783130
    r13 = 0x0000000004544ab0   rip = 0x00000000015decaf
    rsp = 0x00007f279afcb740   rbp = 0x000000000477bcd0
    Found by: call frame info
 7  phantomjs!QApplication::notify [qapplication.cpp : 4423 + 0x17]
    rbx = 0x00007fff0d9443b0   r12 = 0x0000000004783130
    r13 = 0x00007fff0d9443b0   rip = 0x00000000015e793b
    rsp = 0x00007f279afcb770   rbp = 0x000000000477bcd0
    Found by: call frame info
 8  phantomjs!QCoreApplication::notifyInternal [qcoreapplication.cpp : 946 + 0x2]
    rbx = 0x000000000459ade0   r12 = 0x0000000004783130
    r13 = 0x00007fff0d9443b0   r14 = 0x000000000459ae28
    r15 = 0x000000000459ae1c   rip = 0x0000000001cde3b4
    rsp = 0x00007f279afcbc40   rbp = 0x000000000477bcd0
    Found by: call frame info
 9  phantomjs!QCoreApplicationPrivate::sendPostedEvents [qcoreapplication.h : 231 + 0x1f]
    rbx = 0x0000000004783130   r12 = 0x000000000459ade0
    r13 = 0x000000000477bcd0   r14 = 0x000000000459ae28
    r15 = 0x000000000459ae1c   rip = 0x0000000001cdf314
    rsp = 0x00007f279afcbc90   rbp = 0x00000000045e8a60
    Found by: call frame info
10  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 909 + 0xc]
    rbx = 0x0000000004595910   r12 = 0x00007f279afcbda0
    r13 = 0x0000000004597540   r14 = 0x0000000000000000
    r15 = 0x0000000004788f28   rip = 0x0000000001d08003
    rsp = 0x00007f279afcbd50   rbp = 0x000000000459db90
    Found by: call frame info
11  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x0000000004595910   r12 = 0x00007f279afcbe30
    r13 = 0x00007f279afcbe40   r14 = 0x0000000004542230
    r15 = 0x0000000004788f28   rip = 0x0000000001cdd495
    rsp = 0x00007f279afcbda0   rbp = 0x00007f279afcbde0
    Found by: call frame info
12  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x0000000004595910   r12 = 0x00007f279afcbe30
    r13 = 0x00007f279afcbe40   r14 = 0x0000000004542230
    r15 = 0x0000000004788f28   rip = 0x0000000001cdd8f8
    rsp = 0x00007f279afcbdd0   rbp = 0x00007fff0d9443b0
    Found by: call frame info
13  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
    rbx = 0x0000000004788ea0   r12 = 0x0000000004788f28
    r13 = 0x0000000000000001   r14 = 0x00007f279db99040
    r15 = 0x0000000000000003   rip = 0x0000000001bdfdd6
    rsp = 0x00007f279afcbe30   rbp = 0x0000000004788f28
    Found by: call frame info
14  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x0000000004788f28   r12 = 0x000000000459ade0
    r13 = 0x0000000000000001   r14 = 0x00007f279db99040
    r15 = 0x0000000000000003   rip = 0x0000000001be2ca2
    rsp = 0x00007f279afcbe80   rbp = 0x000000000457e940
    Found by: call frame info
15  libpthread-2.13.so + 0x6b4f
    rbx = 0x0000000000000000   r12 = 0x00007fff0d943890
    r13 = 0x00007f279afcc9c0   r14 = 0x00007f279db99040
    r15 = 0x0000000000000003   rip = 0x00007f279ce81b50
    rsp = 0x00007f279afcbed0   rbp = 0x0000000000000000
    Found by: call frame info

Loaded modules:
0x00400000 - 0x026e7fff  phantomjs  ???  (main)
0x7f279b8ce000 - 0x7f279bb2cfff  libssl.so.1.0.0  ???
0x7f279bb2d000 - 0x7f279bf0cfff  libcrypto.so.1.0.0  ???
0x7f279bf11000 - 0x7f279c13afff  libexpat.so.1.6.0  ???
0x7f279c13b000 - 0x7f279c351fff  libz.so.1.2.7  ???
0x7f279c352000 - 0x7f279c6d6fff  libc-2.13.so  ???
0x7f279c6dc000 - 0x7f279c8f1fff  libgcc_s.so.1  ???
0x7f279c8f2000 - 0x7f279cb73fff  libm-2.13.so  ???
0x7f279cb74000 - 0x7f279ce65fff  libstdc++.so.6.0.17  ???
0x7f279ce7b000 - 0x7f279d092fff  libpthread-2.13.so  ???
0x7f279d097000 - 0x7f279d29efff  librt-2.13.so  ???
0x7f279d29f000 - 0x7f279d4a2fff  libdl-2.13.so  ???
0x7f279d4a3000 - 0x7f279d6d9fff  libfontconfig.so.1.5.0  ???
0x7f279d6da000 - 0x7f279d978fff  libfreetype.so.6.8.1  ???
0x7f279d979000 - 0x7f279d998fff  ld-2.13.so  ???
0x7f279da13000 - 0x7f279db89fff  locale-archive  ???
0x7f279db92000 - 0x7f279db95fff  6d41288fd70b0be22e8c3a91e032eec0-le64.cache-3  ???
0x7fff0d9b5000 - 0x7fff0d9b5fff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
