### ISSUE TITLE
PhantomJS has crashed.

### ISSUE THREAD

**Issue by sonyboy232** [ariya/phantomjs#11498]
I couldn't tell you how to reproduce the error, since the error message is poor, and has nothing distinguishable about it. I can provide more information as you need.

Operating system: Linux
                  0.0.0 Linux 3.2.0-49-generic #75-Ubuntu SMP Tue Jun 18 17:39:32 UTC 2013 x86_64
CPU: amd64
     family 6 model 23 stepping 10
     4 CPUs

Crash reason:  SIGSEGV
Crash address: 0x60

Thread 0 (crashed)
 0  phantomjs!QMetaObject::activate [qobject_p.h : 239 + 0x18]
    rbx = 0x0000000000000005   r12 = 0x0000000004d38f80
    r13 = 0x0000000004d389e0   r14 = 0x0000000004a71208
    r15 = 0x00007fadec03c360   rip = 0x0000000001cf6abf
    rsp = 0x00007fffaf112440   rbp = 0x000000000000000b
    Found by: given as instruction pointer in context
 1  phantomjs!QNetworkReply::downloadProgress [moc_qnetworkreply.cpp : 194 + 0x4]
    rbx = 0x0000000004d38b40   r12 = 0x0000000004d38f80
    r13 = 0x0000000004d389e0   r14 = 0x0000000004a71208
    r15 = 0x00007fadec03c360   rip = 0x0000000001ba73fb
    rsp = 0x00007fffaf112560   rbp = 0x00007fffaf112660
    Found by: call frame info
 2  phantomjs!QNetworkReplyImplPrivate::appendDownstreamDataSignalEmissions [qnetworkreplyimpl.cpp : 626 + 0x2e]
    rbx = 0x0000000004d38b40   r12 = 0x0000000004d38f80
    r13 = 0x0000000004d389e0   r14 = 0x0000000004a71208
    r15 = 0x00007fadec03c360   rip = 0x0000000001b30d5e
    rsp = 0x00007fffaf1125a0   rbp = 0x00007fffaf112660
    Found by: call frame info
 3  phantomjs!QNetworkAccessHttpBackend::replyDownloadData [qnetworkaccesshttpbackend.cpp : 743 + 0xa]
    rbx = 0x0000000004d38f00   r12 = 0x0000000004d38f80
    r13 = 0x0000000004a73ab0   r14 = 0x0000000004a71208
    r15 = 0x00007fadec03c360   rip = 0x0000000001b1c72a
    rsp = 0x00007fffaf112600   rbp = 0x00007fffaf112660
    Found by: call frame info
 4  phantomjs!QNetworkAccessHttpBackend::qt_static_metacall [moc_qnetworkaccesshttpbackend_p.cpp : 95 + 0x9]
    rbx = 0x00007fadec03c320   r12 = 0x00007fadec03c360
    r13 = 0x0000000004a73ab0   r14 = 0x0000000004a71208
    r15 = 0x00007fadec03c360   rip = 0x0000000001ba6f31
    rsp = 0x00007fffaf112630   rbp = 0x0000000004d38f00
    Found by: call frame info
 5  phantomjs!QObject::event [qobject.cpp : 1191 + 0x8]
    rbx = 0x0000000004d38f00   r12 = 0x00007fadec03c360
    r13 = 0x0000000004a73ab0   r14 = 0x0000000004a71208
    r15 = 0x00007fadec03c360   rip = 0x0000000001cefc08
    rsp = 0x00007fffaf1126c0   rbp = 0x0000000000000000
    Found by: call frame info
 6  phantomjs!QApplicationPrivate::notify_helper [qapplication.cpp : 4562 + 0xc]
    rbx = 0x00007fffaf113070   r12 = 0x00007fadec03c360
    r13 = 0x0000000004a73ab0   r14 = 0x0000000004a71208
    r15 = 0x00007fadec03c360   rip = 0x00000000015decaf
    rsp = 0x00007fffaf112860   rbp = 0x0000000004d38f00
    Found by: call frame info
 7  phantomjs!QApplication::notify [qapplication.cpp : 4423 + 0x17]
    rbx = 0x00007fffaf113070   r12 = 0x00007fadec03c360
    r13 = 0x00007fffaf113070   r14 = 0x0000000004a71208
    r15 = 0x00007fadec03c360   rip = 0x00000000015e793b
    rsp = 0x00007fffaf112890   rbp = 0x0000000004d38f00
    Found by: call frame info
 8  phantomjs!QCoreApplication::notifyInternal [qcoreapplication.cpp : 946 + 0x2]
    rbx = 0x0000000004a711c0   r12 = 0x00007fadec03c360
    r13 = 0x00007fffaf113070   r14 = 0x0000000004a71208
    r15 = 0x0000000004a711fc   rip = 0x0000000001cde3b4
    rsp = 0x00007fffaf112d60   rbp = 0x0000000004d38f00
    Found by: call frame info
 9  phantomjs!QCoreApplicationPrivate::sendPostedEvents [qcoreapplication.h : 231 + 0x1f]
    rbx = 0x00007fadec03c360   r12 = 0x0000000004a711c0
    r13 = 0x0000000004d38f00   r14 = 0x0000000004a71208
    r15 = 0x0000000004a711fc   rip = 0x0000000001cdf314
    rsp = 0x00007fffaf112db0   rbp = 0x00007fadec03c3c0
    Found by: call frame info
10  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 909 + 0xc]
    rbx = 0x0000000004d38100   r12 = 0x00007fffaf112ec0
    r13 = 0x0000000004a70560   r14 = 0x0000000000000000
    r15 = 0x0000000004a712d8   rip = 0x0000000001d08003
    rsp = 0x00007fffaf112e70   rbp = 0x0000000004a75030
    Found by: call frame info
11  phantomjs!QEventDispatcherQPA::processEvents [qeventdispatcher_qpa.cpp : 246 + 0x4]
    rbx = 0x0000000004d38100   r12 = 0x0000000000000000
    r13 = 0x0000000004a70560   r14 = 0x00007fffaf112f00
    r15 = 0x0000000004a712d8   rip = 0x000000000163a6a4
    rsp = 0x00007fffaf112ec0   rbp = 0x0000000004a75030
    Found by: call frame info
12  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x0000000004d38100   r12 = 0x00007fffaf112f90
    r13 = 0x00007fffaf112fa0   r14 = 0x0000000004a71230
    r15 = 0x0000000004a712d8   rip = 0x0000000001cdd495
    rsp = 0x00007fffaf112f00   rbp = 0x00007fffaf112f40
    Found by: call frame info
13  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x0000000004d38100   r12 = 0x00007fffaf112f90
    r13 = 0x00007fffaf112fa0   r14 = 0x0000000004a71230
    r15 = 0x0000000004a712d8   rip = 0x0000000001cdd8f8
    rsp = 0x00007fffaf112f30   rbp = 0x00007fffaf113070
    Found by: call frame info
14  phantomjs!QCoreApplication::exec [qcoreapplication.cpp : 1218 + 0x4]
    rbx = 0x0000000004a711c0   r12 = 0x00007fffaf113070
    r13 = 0x00007fffaf113240   r14 = 0x00007fffaf112fe0
    r15 = 0x0000000000000000   rip = 0x0000000001cdf7ab
    rsp = 0x00007fffaf112f90   rbp = 0x0000000004a711c0
    Found by: call frame info
15  phantomjs!main [main.cpp : 121 + 0x4]
    rbx = 0x0000000004ac6460   r12 = 0x00007fffaf113070
    r13 = 0x00007fffaf113240   r14 = 0x00007fffaf112fe0
    r15 = 0x0000000000000000   rip = 0x0000000000427cb2
    rsp = 0x00007fffaf112fd0   rbp = 0x00007fffaf113208
    Found by: call frame info
16  libc-2.15.so + 0x2176c
    rbx = 0x0000000000000000   r12 = 0x0000000000407cc0
    r13 = 0x00007fffaf113200   r14 = 0x0000000000000000
    r15 = 0x0000000000000000   rip = 0x00007fae3ba3076d
    rsp = 0x00007fffaf113130   rbp = 0x0000000000000000
    Found by: call frame info
17  phantomjs + 0x27a5f
    rip = 0x0000000000427a60   rsp = 0x00007fffaf113150
    Found by: stack scanning

Thread 1
 0  libc-2.15.so + 0xbf84d
    rbx = 0x00007fae3a8b0cf0   r12 = 0x0000000002ad0160
    r13 = 0x00007fae3a8b19c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007fae3bace84d
    rsp = 0x00007fae3a8b0c40   rbp = 0x00000000ffffffff
    Found by: given as instruction pointer in context
 1  libc-2.15.so + 0xbf6eb
    rip = 0x00007fae3bace6ec   rsp = 0x00007fae3a8b0c50
    Found by: stack scanning
 2  phantomjs + 0x18b5c4f
    rip = 0x0000000001cb5c50   rsp = 0x00007fae3a8b0c58
    Found by: stack scanning
 3  libc-2.15.so + 0x109f7
    rip = 0x00007fae3ba1f9f8   rsp = 0x00007fae3a8b0c70
    Found by: stack scanning
 4  ld-2.15.so + 0xa522
    rip = 0x00007fae3d0e5523   rsp = 0x00007fae3a8b0cc8
    Found by: stack scanning
 5  libpthread-2.15.so + 0xfcaf
    rip = 0x00007fae3c5efcb0   rsp = 0x00007fae3a8b0ce8
    Found by: stack scanning
 6  ld-2.15.so + 0xe773
    rip = 0x00007fae3d0e9774   rsp = 0x00007fae3a8b0d80
    Found by: stack scanning
 7  libc-2.15.so + 0xe54f
    rip = 0x00007fae3ba1d550   rsp = 0x00007fae3a8b0d98
    Found by: stack scanning
 8  ld-2.15.so + 0x15234
    rip = 0x00007fae3d0f0235   rsp = 0x00007fae3a8b0dd0
    Found by: stack scanning
 9  libpthread-2.15.so + 0xe9f9
    rip = 0x00007fae3c5ee9fa   rsp = 0x00007fae3a8b0de0
    Found by: stack scanning
10  phantomjs!WTF::TCMalloc_PageHeap::scavengerThread [FastMalloc.cpp : 2499 + 0x4]
    rip = 0x00000000004dda2e   rsp = 0x00007fae3a8b0e20
    Found by: stack scanning
11  phantomjs!WTF::TCMalloc_PageHeap::runScavengerThread [FastMalloc.cpp : 1618 + 0x4]
    rbx = 0x0000000000000000   r12 = 0x00007fae3c5f1880
    r13 = 0x00007fae3a8b19c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00000000004ddc99
    rsp = 0x00007fae3a8b0ea0   rbp = 0x0000000000000000
    Found by: call frame info
12  libpthread-2.15.so + 0x7e99
    rbx = 0x0000000000000000   r12 = 0x00007fae3c5f1880
    r13 = 0x00007fae3a8b19c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007fae3c5e7e9a
    rsp = 0x00007fae3a8b0eb0   rbp = 0x0000000000000000
    Found by: call frame info
13  libpthread-2.15.so + 0x1187f
    rip = 0x00007fae3c5f1880   rsp = 0x00007fae3a8b0f58
    Found by: stack scanning
14  libc-2.15.so + 0xf3ccc
    rip = 0x00007fae3bb02ccd   rsp = 0x00007fae3a8b0fc0
    Found by: stack scanning

Thread 2
 0  libc-2.15.so + 0xed033
    rbx = 0x0000000000000000   r12 = 0x00007fae3a0afd80
    r13 = 0x0000000000000008   r14 = 0x00007fae34000a98
    r15 = 0x00007fae34000d30   rip = 0x00007fae3bafc033
    rsp = 0x00007fae3a0afb50   rbp = 0x00007fae340008e0
    Found by: given as instruction pointer in context
 1  phantomjs!qt_safe_select [qcore_unix.cpp : 83 + 0x15]
    rip = 0x0000000001d06307   rsp = 0x00007fae3a0afb60
    Found by: stack scanning
 2  phantomjs!QEventDispatcherUNIXPrivate::doSelect [qeventdispatcher_unix.cpp : 223 + 0xd]
    rbx = 0x00007fae340012b0   r12 = 0x00007fae3a0afd80
    r13 = 0x00007fae340008e0   r14 = 0x0000000000000000
    r15 = 0x00007fae34000d30   rip = 0x0000000001d075c7
    rsp = 0x00007fae3a0afbf0   rbp = 0x00007fae340008e0
    Found by: call frame info
 3  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 937 + 0x4]
    rbx = 0x00007fae340012b0   r12 = 0x00007fae3a0afd80
    r13 = 0x00007fae340008c0   r14 = 0x0000000000000001
    r15 = 0x0000000004aa9bf8   rip = 0x0000000001d08072
    rsp = 0x00007fae3a0afd30   rbp = 0x00007fae340008e0
    Found by: call frame info
 4  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x00007fae340012b0   r12 = 0x00007fae3a0afe10
    r13 = 0x00007fae3a0afe20   r14 = 0x0000000004a71230
    r15 = 0x0000000004aa9bf8   rip = 0x0000000001cdd495
    rsp = 0x00007fae3a0afd80   rbp = 0x00007fae3a0afdc0
    Found by: call frame info
 5  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x00007fae340012b0   r12 = 0x00007fae3a0afe10
    r13 = 0x00007fae3a0afe20   r14 = 0x0000000004a71230
    r15 = 0x0000000004aa9bf8   rip = 0x0000000001cdd8f8
    rsp = 0x00007fae3a0afdb0   rbp = 0x00007fffaf113070
    Found by: call frame info
 6  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
    rbx = 0x0000000004aa9b70   r12 = 0x0000000004aa9bf8
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000000001bdfdd6
    rsp = 0x00007fae3a0afe10   rbp = 0x0000000004aa9bf8
    Found by: call frame info
 7  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x0000000004aa9bf8   r12 = 0x0000000004ad43d0
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000000001be2ca2
    rsp = 0x00007fae3a0afe60   rbp = 0x0000000004ab2940
    Found by: call frame info
 8  libpthread-2.15.so + 0x7e99
    rbx = 0x0000000000000000   r12 = 0x00007fffaf112550
    r13 = 0x00007fae3a0b09c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007fae3c5e7e9a
    rsp = 0x00007fae3a0afeb0   rbp = 0x0000000000000000
    Found by: call frame info

Thread 3
 0  libpthread-2.15.so + 0xc0fe
    rbx = 0x00007fadec006b00   r12 = 0x0000000000000001
    r13 = 0x00007fadf3ffedc0   r14 = 0xffffffffffffff92
    r15 = 0x0000000000000000   rip = 0x00007fae3c5ec0fe
    rsp = 0x00007fadf3ffed40   rbp = 0x00007fadec006e30
    Found by: given as instruction pointer in context
 1  phantomjs!QWaitCondition::wait [qwaitcondition_unix.cpp : 84 + 0x7]
    rip = 0x0000000001be39b7   rsp = 0x00007fadf3ffeda0
    Found by: stack scanning
 2  phantomjs!QThreadPoolThread::run [qthreadpool.cpp : 141 + 0x1d]
    rbx = 0x00007fadec006a20   r12 = 0x00007fadec006aa9
    r13 = 0x0000000000000002   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000000001bd781d
    rsp = 0x00007fadf3ffee20   rbp = 0x00007fadec006e30
    Found by: call frame info
 3  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x00007fade80012b0   r12 = 0x00007fadec006fd0
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000000001be2ca2
    rsp = 0x00007fadf3ffee60   rbp = 0x00007fadec006e30
    Found by: call frame info
 4  libpthread-2.15.so + 0x7e99
    rbx = 0x0000000000000000   r12 = 0x00007fae38885ce0
    r13 = 0x00007fadf3fff9c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007fae3c5e7e9a
    rsp = 0x00007fadf3ffeeb0   rbp = 0x0000000000000000
    Found by: call frame info

Loaded modules:
0x00400000 - 0x026e7fff  phantomjs  ???  (main)
0x7fadf2fcb000 - 0x7fadf31d2fff  libnss_dns-2.15.so  ???
0x7fadf31d3000 - 0x7fadf33d5fff  libnss_mdns4_minimal.so.2  ???
0x7fadf33d6000 - 0x7fadf35e2fff  libnss_files-2.15.so  ???
0x7fadf35e3000 - 0x7fadf37fcfff  libresolv-2.15.so  ???
0x7fae3a8b2000 - 0x7fae3ab0efff  libssl.so.1.0.0  ???
0x7fae3ab10000 - 0x7fae3aee6fff  libcrypto.so.1.0.0  ???
0x7fae3aeeb000 - 0x7fae3b5cdfff  locale-archive  ???
0x7fae3b5ce000 - 0x7fae3b7f7fff  libexpat.so.1.5.2  ???
0x7fae3b7f8000 - 0x7fae3ba0efff  libz.so.1.2.3.4  ???
0x7fae3ba0f000 - 0x7fae3bdc8fff  libc-2.15.so  ???
0x7fae3bdce000 - 0x7fae3bfe3fff  libgcc_s.so.1  ???
0x7fae3bfe4000 - 0x7fae3c2dffff  libm-2.15.so  ???
0x7fae3c2e0000 - 0x7fae3c5cafff  libstdc++.so.6.0.16  ???
0x7fae3c5e0000 - 0x7fae3c7f8fff  libpthread-2.15.so  ???
0x7fae3c7fd000 - 0x7fae3ca04fff  librt-2.15.so  ???
0x7fae3ca05000 - 0x7fae3cc08fff  libdl-2.15.so  ???
0x7fae3cc09000 - 0x7fae3ce3efff  libfontconfig.so.1.4.4  ???
0x7fae3ce3f000 - 0x7fae3d0dafff  libfreetype.so.6.8.0  ???
0x7fae3d0db000 - 0x7fae3d0fcfff  ld-2.15.so  ???
0x7fae3d27a000 - 0x7fae3d27afff  c05880de57d1f5e948fdfacc138775d9-le64.cache-3  ???
0x7fae3d27b000 - 0x7fae3d283fff  945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-3  ???
0x7fae3d284000 - 0x7fae3d285fff  99e8ed0e538f840c565b6ed5dad60d56-le64.cache-3  ???
0x7fae3d286000 - 0x7fae3d28dfff  a6d8cf8e4ec09cdbc8633c31745a07dd-le64.cache-3  ???
0x7fae3d28e000 - 0x7fae3d291fff  2cd17615ca594fa2959ae173292e504c-le64.cache-3  ???
0x7fae3d292000 - 0x7fae3d292fff  e7071f4a29fa870f4323321c154eba04-le64.cache-3  ???
0x7fae3d293000 - 0x7fae3d293fff  0d8c3b2ac0904cb8a57a757ad11a4a08-le64.cache-3  ???
0x7fae3d294000 - 0x7fae3d299fff  a755afe4a08bf5b97852ceb7400b47bc-le64.cache-3  ???
0x7fae3d29a000 - 0x7fae3d2a2fff  6d41288fd70b0be22e8c3a91e032eec0-le64.cache-3  ???
0x7fae3d2a3000 - 0x7fae3d2b2fff  04aabc0a78ac019cf9454389977116d2-le64.cache-3  ???
0x7fae3d2b3000 - 0x7fae3d2b5fff  385c0604a188198f04d133e54aba7fe7-le64.cache-3  ???
0x7fae3d2b6000 - 0x7fae3d2b6fff  4794a0821666d79190d59a36cb4f44b5-le64.cache-3  ???
0x7fae3d2b7000 - 0x7fae3d2b9fff  8801497958630a81b71ace7c5f9b32a8-le64.cache-3  ???
0x7fae3d2ba000 - 0x7fae3d2befff  3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-3  ???
0x7fae3d2bf000 - 0x7fae3d2bffff  56cf4f4769d0f4abc89a4895d7bd3ae1-le64.cache-3  ???
0x7fae3d2c0000 - 0x7fae3d2c0fff  b9d506c9ac06c20b433354fa67a72993-le64.cache-3  ???
0x7fae3d2c1000 - 0x7fae3d2d0fff  d52a8644073d54c13679302ca1180695-le64.cache-3  ???
0x7fae3d2d9000 - 0x7fae3d2ddfff  b47c4e1ecd0709278f4910c18777a504-le64.cache-3  ???
0x7fae3d2de000 - 0x7fae3d2e5fff  52f7bdb7ce746bfd7eaa1985bd9cfa93-le64.cache-3  ???
0x7fae3d2e6000 - 0x7fae3d2ebfff  3f7329c5293ffd510edef78f73874cfd-le64.cache-3  ???
0x7fae3d2ec000 - 0x7fae3d2f6fff  e13b20fdb08344e0e664864cc2ede53d-le64.cache-3  ???
0x7fae3d2f7000 - 0x7fae3d2fafff  7ef2298fde41cc6eeb7af42e48b7d293-le64.cache-3  ???
0x7fffaf1ff000 - 0x7fffaf1fffff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
