### ISSUE TITLE
Status 'fail' on loading css 

### ISSUE THREAD

**Issue by Natalie-Dunice** [ariya/phantomjs#11501]
I'm using 1.9.1 version of PhantomJS. And also tried to use 1.9.0 version of PhantomJS and a fresh build of latest master. Phantom does not load css and has status 'fail'. I also tried to use local and other servers like apache.
For testing I use this code:

```
var page = require('webpage').create();

var cssUrl = 'http://31.31.201.139:8001/download/any.css';
var otherUrl = 'http://31.31.201.139:8001/download/any.other';

page.open(cssUrl, function (status) {
    console.log('css status', status)
    page.open(otherUrl, function (status) {
        console.log('other status', status)
        phantom.exit();
    });
});
```

I've launched this on different operation systems and result was the same.

**Comment by Vitallium** [comment]
You can't load a CSS file with PhantomJS. This is not supported.
