### ISSUE TITLE
Is there any way to get the final URL after redirect ?

### ISSUE THREAD

**Issue by more-free** [ariya/phantomjs#11507]
I am using phantomjs to analyze page content, and I have to get the final URL for pages that contain something like "window.location = 'new url'", which triggers a redirect.  Is there any approach to get it ?  thanks !!  
I am using the following code now, but I don't want to use the timer since it indicates a high latency.

var givenUrl = "http://snowplay.com";
var urls = [];
getUrls(givenUrl, urls);
setTimeout(print, 3000);

// get all potential redirected urls 
function getUrls(givenUrl, urls) {
  var page = require('webpage').create();

  page.onUrlChanged = function(newUrl)  {
       urls.push(newUrl); 
  }

  page.open(givenUrl);
}

function print() {
  // ...
}

**Comment by jmendelson** [comment]
Hi guys, 
I had a similar problem where I was trying to record bitly redirects and found that they weren't recording. Found out that it had nothing to do with timeouts and everything to do with simply defining the proper user agent.  Once I added this code to my script, it all worked.

Kudos to:
http://www.redirect-checker.org/index.php
https://www.sitepoint.com/headless-webkit-and-phantomjs/

`var page = require("webpage").create();
var homePage = "http://bitly.com/XXXXX";
page.settings.userAgent = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.$
page.settings.javascriptEnabled = false;
page.settings.loadImages = false;
page.open(homePage);
page.onLoadFinished = function(status) {
  var url = page.url;

  console.log("Status:  " + status);
  console.log("Loaded:  " + url);
  page.render("google.png");
  phantom.exit();
};
`

**Comment by timlib** [comment]
It's a multifaceted issue really, specifying a non-PhantomJS user-agent helps in general (and is in the code above), but for redirects it's only part of the problem.

**Comment by grantkemp** [comment]
@jmendelson  just tidied up the code:  you missed off the ending for your user agent
```var page = require("webpage").create();
var homePage = "http://bitly.com/XXXXX";
page.settings.userAgent = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.$'
page.settings.javascriptEnabled = false;
page.settings.loadImages = false;
page.open(homePage);
page.onLoadFinished = function(status) {
var url = page.url;

console.log("Status: " + status);
console.log("Loaded: " + url);
page.render("google.png");
phantom.exit();
};

```
