### ISSUE TITLE
crash opening a specific page on CentOs

### ISSUE THREAD

**Issue by kritwn** [ariya/phantomjs#11502]
I am using phatomJs for screenshot capturing.
It crashes when I try to open this page: http://www.hertz.co.uk/

The crash does not happen on my mac, but happens CentOs 6.3 VMs in Azure. I have not tested on other unix environments. I was using pahtomJS 1.8 but upgraded to 1.9.1 and the error persists. I've installed it using the binary download from the homepage.

I've tested many sites, and the error only appears on this one.

It crashes with a 35147 Segmentation fault.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
