### ISSUE TITLE
Crash Report - Phantom 1.9.1 on Windows 7

### ISSUE THREAD

**Issue by TimOrme** [ariya/phantomjs#11503]
Hello,

Tried to follow the directions in the wiki, but it didn't have directions for Windows.

Trying to run a test of links on a page through Casper, but after testing about 5 of the pages it fails with a Phantom crash.

Test looks something like:

```javascript
var i = 0;
		casper.repeat(links.length, function(){
			casper.open(links[i]).then(function(){
				casper.echo("####Requesting Url: " + this.getCurrentUrl());
				var statusCode = this.currentHTTPStatus;
				this.test.assertMatch(statusCode, /(200|301|302)/, "Page is up w/ Status code: " + statusCode);
			});
			i++;
		});
```

I'll attach the dump file as well.

Thanks,
Tim

**Comment by Vitallium** [comment]
Doesn't crash in 2.0.
