### ISSUE TITLE
Strange document.cookie behaviour when using curved brackets and quotes

### ISSUE THREAD

**Issue by deazurain** [ariya/phantomjs#11518]
The following code works as I would expect:

     document.cookie = 'a="{}' // document.cookie equals 'a="{}', correct

This however does not:

     document.cookie = 'a={"}' // document.cookie equals 'a=\"{\"}\"', strange

I'm not sure why the escaped quotes are inserted. Google Chrome does not do this. Haven't tested in other browsers.

**Comment by zackw** [comment]
My tests indicate that this has been fixed in the current development sources.  It may also have been fixed in 2.0.

We are no longer developing the 1.9.x series.
