### ISSUE TITLE
Is there a memory leak when running the webserver module ?  

### ISSUE THREAD

**Issue by more-free** [ariya/phantomjs#11528]
I am running  phantomjs as a web server. Here is my server-side code : 

var system = require('system');
var server = require('webserver').create();
var port = system.args[1];

var listening = server.listen(port, function(request, response) {
    var url = request['post'].url;
    fire(url, request, response);
})

var fire = function(url, request, response) {
    var page = require('webpage').create();
    page.onLoadFinished = function(status) {
           page.close();
           response.close();
    }

```
page.open(url);
```

}

In case concurrent requests, I create a new page for each request, and invoke page.close() to release the memory.
For test, I send different urls one by one (not concurrently) to the server,
and monitor the memory usage. 
I found that the memory usage keeps increasing, and never drops even after I stopped sending requests. 
does it indicate a memory leak, or just because I wrote the code improperly ?
thanks !

**Comment by dhwaneetbhatt** [comment]
@quanghoc release() has been marked deprecated. Does this issue still exist?
