### ISSUE TITLE
PhantomJS not properly loading javascripts

### ISSUE THREAD

**Issue by rhoot** [ariya/phantomjs#11529]
This affects both **1.9.0** and **1.9.1**. I have not tried **master**.

I have noticed that many pure javascript sites aren't loaded properly in PhantomJS (https://www.imprev.net/ui/#login and https://login.serverdensity.io/, to name just a couple). I quickly looked into it and it seems PhantomJS isn't loading all javascripts on the page. In the case of serverdensity, it actually doesn't load a single one.

Example script:

``` coffeescript
page = require('webpage').create()

page.onResourceRequested = (request) ->
    console.log "#{request.method}\t#{request.url}"

page.onResourceReceived = (data) ->
    console.log "#{data.status}\t#{data.url}"

page.open 'https://login.serverdensity.io/', ->
    setTimeout ->
        phantom.exit()
    , 10000
```

The output from this script is:

```
GET https://login.serverdensity.io/
200 https://login.serverdensity.io/
200 https://login.serverdensity.io/
```

Looking at the source, there's nothing to suggest that they shouldn't load. So the question is, why aren't they?

**Comment by johnbburg** [comment]
Sorry to resurrect an old thread (it is still open). I think I am running into this issue on 2.1.1. I haven't reliably recreated it from a scratch setup yet, but it seems like it may be related to including javascript via protocol-relative URLs. E.g. //my.domain/myJavascript.js
