### ISSUE TITLE
PhantomJS server module not able to receive POST data from Apache Bench

### ISSUE THREAD

**Issue by eerootsus** [ariya/phantomjs#11541]
We wanted to perform some load testing on our PhantomJS script, but somewhere along the road the POST data is lost.

I've tested on PHP - the data is properly sent by AB. PhantomJS recognizes the POST request, but post or postRaw are not populated.

There is no issue using cURL - POST data is properly received by the PhantomJS script.

**Comment by tenuki** [comment]
Great work @dshulepov, it took me all day yesterday to figure out that it was not a problem of nodejs proxies (I've tried about 8 (!) thinking I was using it wrong or theirs code was not complete to support post requests).

Do you know if there's a version 1 branch/fork with the fix?

thanks!!

**Comment by dshulepov** [comment]
Hey, I haven't been following the project for a long while, so I don't know if they released a version, which contains a fix. See my comment above. The trunk already contained (at the time of my check) the fix.
