### ISSUE TITLE
API docs needs some updating

### ISSUE THREAD

**Issue by F21** [ariya/phantomjs#11551]
I am new to PhantomJS and am using it to convert html to pdfs.

The WebPage's API page in the wiki should have some things updated. I was trying to see if I could set margins, headers and footers to the output and was only able to get second hand information from place around the web.

It would be immensely useful if the API docs are updated to show that these parameters/settings do exist.

**Comment by JamieMason** [comment]
Could you provide an example of what it was you were doing and the information you found please @F21?

**Comment by F21** [comment]
Hi @JamieMason 

They were things like `zoomFactor`, `border` and custom footers and headers. I haven't had a chance to check the API docs since I opened the issue, so it is possible someone else might have added them.
