### ISSUE TITLE
phantomjs-1.9.1 document.querySelector('option:checked') does not work

### ISSUE THREAD

**Issue by stephencattaneo** [ariya/phantomjs#11550]
In a browser the following code finds a node. In phantomjs, no node is found.

checked_test.html -

```
 <!doctype html>
 <html>
 <head></head>
 <body>
 <select><option value='1'>1</option></select>
 <script>
   var node = document.querySelector('option:checked');
   window.console.log(node);
 </script>
 </body>
 <html>
```

---

Here's my page wrapper for phantomjs.  I'd expect to get something like "PAGE>> [object HTMLOptionElement" but instead I get "PAGE>> null".

```
 var page = require('webpage').create();
 page.onConsoleMessage = function (msg) {
     console.log('PAGE>> ' + msg);
 };
 page.open('checked_test.html', function (status) {
 });
```

---

Edit: my formatting was poor.

**Comment by quachc** [comment]
This is still a problem on PhantomJS 1.9.13.
Suggested workaround (option[selected=selected]) didn't work, managed to get the selected item by using `selectedIndex` from the select element

**Comment by acdcjunior** [comment]
`option[selected=selected]` is not a reliable workaround. It only works if the "selection" of the `<option>` is being set by adding the `selected` attribute. But that's not always the case.

Here are two scenarios where `:checked` would be `true`, but `option[selected=selected]` would be `false`:
- The example in the first post of this issue, `<select><option value='1'>1</option></select>`, has no `selected` attribute, but the `<option value='1'>1</option>` is truly `:checked`
  - To make matters worse, if that `<select>` was a `<select multiple=true>`, that `option` would, on the other hand, not be `:checked`.
- If the `selected` of any given `<option>` has been set through `.prop()`, as in `$("#myOption").prop('selected', true)`, then it'd be `:checked`, but no `selected` attribute would be added.

**Comment by SGD1953** [comment]
I have a potentially related issue where we have radio buttons with div blocks that carry some detail information and their visibility is controlled via a CSS3 selector like this:

`.list .radio:checked+.label+.details { display: block }`

This works fine in Chrome & Firefox but in phantomjs the section will not be shown (by default it is `display : none`). If anyone has an idea for a workaround it would be much appreciated.

**Comment by acdcjunior** [comment]
@SGD1953 I think (at least I was under the impression) the newest version of phantomJS fixes the `:checked` bug. I suggest you give it a try.

**Comment by SGD1953** [comment]
I'm on phantomjs-prebuilt@2.1.7 which appears to be the latest (released) version and it is not working.

**Comment by hartsick** [comment]
I'm on 2.1.1 and experiencing the same issue.
