### ISSUE TITLE
PhantomJS rewriting URL in backgroundImage property to local file system

### ISSUE THREAD

**Issue by rtm** [ariya/phantomjs#11567]
I am using PhantomJS to do some rewriting of HTML. I'm adding a `background-image` property to an element. But when I write out the resulting DOM, the URL has been rewritten to a local URL. I've boiled this down to the following test case:

**JS**

```
var page = require('webpage').create();
page.open("test.html",function(){
    setTimeout(function(){
        page.evaluate(function(){
            document.getElementById("test").style.backgroundImage="url(test.png)";
        });
        console.log(page.content);
        phantom.exit();
   },1000);
});
```

**HTML**

```
<html>
    <body>
        <div id="test"></div>
    </body>
</html>
```

**Output**

```
$ phantomjs test.js
<html><head></head><body>
    <div id="test" style="background-image: url(file:///C:/cygwin/tmp/test.png); ">
    </div>  
</body></html>
```

**UPDATE**
1. The problem remains if you specify `./test.png` or `//test.png`. However, `http://example.com/test.png` is left unchanged, as might be expected.
2. If this HTML document is opened in Chrome, and the `background-image` property added to the `div` element in the style inspector, the URL is unmodified, whether the document is inspected in the Elements tab in devtools, or via `document.body.innerHTML` displayed in the console, or copying the HTML.

Obviously, I don't want this URL to be rewritten in this fashion, and I don't understand why PhantomJS feels the need to do this. Ideas?

[cross-post of StackOverflow question]

**Comment by grav** [comment]
Same problem in v2.5.0 beta (downloaded from https://bitbucket.org/ariya/phantomjs/downloads/)
