### ISSUE TITLE
Empty dmp file

### ISSUE THREAD

**Issue by rosrosros** [ariya/phantomjs#11566]
We're are running PhantomJs on a windows 2008 R2 server and it crashes after 1-5 hours of services.

The error is:

PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: C:\Users\xxxxxx\AppData\Local\Temp\514388ea-d8b8-40a9-9df2-a0f004bf5e5b.dmp

But the dmp file is 0KB every time.

Executing phantomjs like this:
F:\PhantomJS\phantomjs-1.9.1-windows>phantomjs.exe --ignore-ssl-errors=yes --webdriver=8891 > phantom.log

Provides me with at log file but there is no errors on that log file. The last entries in there is:
[INFO  - 2013-08-16T16:37:36.312Z] Session [285667b0-0692-11e3-8191-991b5f3717fb] - CONSTRUCTOR - Desired Capabilities: {"browserName":"chrome","version":"","platform":"WINDOWS","javascriptEnabled":true}
[INFO  - 2013-08-16T16:37:36.312Z] Session [285667b0-0692-11e3-8191-991b5f3717fb] - CONSTRUCTOR - Negotiated Capabilities: {"browserName":"phantomjs","version":"1.9.1","driverName":"ghostdriver","driverVersion":"1.0.3","platform":"windows-7-32bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2013-08-16T16:37:36.312Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 285667b0-0692-11e3-8191-991b5f3717fb
[INFO  - 2013-08-16T16:37:42.982Z] Session [2c502a90-0692-11e3-8191-991b5f3717fb] - CONSTRUCTOR - Desired Capabilities: {"browserName":"chrome","version":"","platform":"WINDOWS","javascriptEnabled":true}
[INFO  - 2013-08-16T16:37:42.982Z] Session [2c502a90-0692-11e3-8191-991b5f3717fb] - CONSTRUCTOR - Negotiated Capabilities: {"browserName":"phantomjs","version":"1.9.1","driverName":"ghostdriver","driverVersion":"1.0.3","platform":"windows-7-32bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2013-08-16T16:37:42.982Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 2c502a90-0692-11e3-8191-991b5f3717fb

How can I determine what crashes the phantomjs process?

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
