### ISSUE TITLE
Webfonts not working from Ubuntu Only

### ISSUE THREAD

**Issue by thetutlage** [ariya/phantomjs#11569]
Great project first of all.

I know this issue have been addressed couple of times earlier but they all seems to be related to older versions of PhantomJs.

Now i got Phantom installed on my local computer running windows8 where it works absolutely fine and create 99% accurate screenshots. 

But when i installed the same version on linux from ( https://phantomjs.googlecode.com/files/phantomjs-1.9.1-linux-i686.tar.bz2 ) webfonts are not working properly.

I copied all of my windows fonts to my linux server inside /urs/share/fonts and got them ready for applications to use after running sudo fc-cache -f -v command.

I have attached two screenshots of techcrunch one taken from my local computer ( which seems to be fine ) to other one is from the amazon ec2 ubuntu machine.

**WINDOWS 8**

![52ab27563021a4da7f9f856f642069f0a19ff0e4](https://f.cloud.github.com/assets/1706381/994986/919dd926-09b5-11e3-8d10-f3a2f2688ca7.png)

**UBUNTU SERVER**

![c56369d06495d87275dbb28549a675a878fd7be0](https://f.cloud.github.com/assets/1706381/995001/c1552f8e-09b5-11e3-8d1c-c22d2f1961e8.png)

I am trying to understand is Phantom also dependent on fonts installed on the machine or what's the real thing breaking fonts on Ubuntu but not on windows.

**Comment by Vitallium** [comment]
PhantomJS 2.0 supports Web Fonts now. So, please upgrade to PhantomJS 2.0. Also, 1.9.x is no longer supported.
