### ISSUE TITLE
Links in .render()'d PDF

### ISSUE THREAD

**Issue by davesidious** [ariya/phantomjs#11576]
Everything's working fine except links in the PDF document have their link styles removed, and the URL is outputted next to the link.  The URL itself is clickable, but the original link text itself is not.

I take it this is a problem with QT, but I have no idea where to look to fix it.  This is with version 1.9.1.

**Comment by alsemany** [comment]
This issue from 2013 and still opened !!
in 2017 I'm  using version 2.1.1 in the end of 2017 and I have the same issue 
did you find a solution ?

**Comment by davesidious** [comment]
I did not - I stopped looking years ago!  I wish you luck on your journey!
