### ISSUE TITLE
Crash in evaluateJavaScript 

### ISSUE THREAD

**Issue by nkovacs** [ariya/phantomjs#11578]
I'm using phpunit and selenium with phantomjs to test a facebook app.

I'm executing the following js snippet inside an iframe after clicking the like button.

    return (document.readyState != 'complete' &&
    window.location.href.indexOf(arguments[0]) != -1)

I suspect that the cause is that I switch to an iframe, but then the parent page removes the iframe and inserts a new one shortly after clicking the like button (triggered by javascript, slightly delayed), and I try to execute the snippet inside the previous iframe. If I wait for a while before switching to the frame, everything works fine.

PhantomJS 1.9.1 linux x86-64 official binary

**Comment by azolotko** [comment]
Should already be fixed in 2.0.0 with update to Qt 5. At least it no longer has the exact same line that caused the crash.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
