### ISSUE TITLE
[WebSQL] Wrong error code returned for constraint error

### ISSUE THREAD

**Issue by fatso83** [ariya/phantomjs#11572]
According to [W3 WebDatabase spec](http://www.w3.org/TR/webdatabase/#errors-and-exceptions) the SqlError code for Constraint errors is 6. Node+PhantomJS returns 1. 

{"code":1,"message":"constraint failed"}

This specific error was caused on INSERTing a duplicate entry into a table. All browsers return { code : 6, ...} .

**Comment by dbaba** [comment]
I've got the similar error saying `{"code":1,"message":"could not execute statement (1555 UNIQUE constraint failed: TABLE_NAME.COLUMN_NAME)"}`.
PhantomJS should return code:6 (CONSTRAINT_ERR) rather than 1.
