### ISSUE TITLE
Enable sending touch events

### ISSUE THREAD

**Issue by potmo** [ariya/phantomjs#11571]
Since phantomjs sees itself as a touch enabled browser it would be nice to be able to fire off touch events.
We have a page that attaches touch events for mobile browsers  (i.e. when (`'ontouchend' in window) == true`) and click events for desktop. 

When automating tests with mocha/jasmine and phantomjs touch events are attached but I can't dispatch any touch events from phantom so I'm a bit stuck.

So please add the possibility to send
- touchstart
- touchend 
- touchmove

and possibly
- touchcenter
- touchleave
- touchcancel 

to page.sendEvent()

I'm not sure on how multi touch would fit into all of this.

Maybe this would be a nice workaround for #10375 [phantomjs pretends to be a touch browser]

**Comment by fancsali** [comment]
I know, this is an age old ticket, but I believe as time goes by this gets more and more important.

**Comment by 82antu** [comment]
Hi,

Same Issue Here;

I found the workaround for MouseEvent:

`var evt: MouseEvent = document.createEvent("MouseEvent");`

instead of

```
var evt = new MouseEvent("click", {
    bubbles: true,
    cancelable: true,
    view: window
  });
```

and both Chrome and PhantomJs work, but, the first one doesn t work on PhantomJs for TouchEvent,
and, the second one, doesn t work on Chrome
