### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by timscott** [ariya/phantomjs#11582]
I just started using phantomjs.  I installed it with homebrew today.  It's my first script.  

Basically just navigates to a login page, fills in the username and password and submits.  I get the error whether I submit by clicking the button or submitting the form directly.  If I use incorrect login credentials, the crash does not happen.

I have the dmp file, but it's too big to submit here.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
