### ISSUE TITLE
Crash while reusing phantomjs webdriver instance

### ISSUE THREAD

**Issue by marcelofarias** [ariya/phantomjs#11586]
1 - get
2 - execute scripts
3 - get
4 - execute scripts
5 - get - BANG! it crashes

![8b58bda0-da70-440c-bb00-9d0343105cb1](https://f.cloud.github.com/assets/1028286/1039422/ce248136-0f84-11e3-9fa2-a6f73f2b160c.png)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
