### ISSUE TITLE
phantom.createWebServer requestListener

### ISSUE THREAD

**Issue by deshawnbw** [ariya/phantomjs#11598]
When using phantom.createWebServer(), it would be nice to be able to send in a global request listener kind of like (http://nodejs.org/api/http.html#http_http_createserver_requestlistener)

phantom.createWebServer(myGlobalListener),

I wanted to be able to use a router module and this was the missing piece. Although I think i can found a way around it.

**Comment by silkentrance** [comment]
@deshawnbw can this then be closed? feel free to do it :grin:
