### ISSUE TITLE
Stop Query String from Being Decoded prior to being sent to server

### ISSUE THREAD

**Issue by curtisturner** [ariya/phantomjs#11592]
I need to pass an encoded **URL with a query string** to the server as part of the query string of the main request

PhantomJS decodes everything before it goes out therefore confusing the server as to what the query string is.

Thanks.

**Comment by orthecreedence** [comment]
Note I got around this by double-encoding the URL being passed.

Here's an example of my problem:

    phantomserver.com/scrape?page=<pageurl>

If `pageurl` is `/path/to/article?page=2&per_page=2` (`%2Fpath%2Fto%2Farticle%3Fpage%3D2%26per_page%3D2` encoded) then in Phantom's `request` object passed, `request.url` is:

    phantomserver.com/scrape?page=%2Fpath%2Fto%2Farticle%3Fpage%3D2%26per_page%3D2

but it decodes it before giving access to `request.url` so the only value given is

    phantomserver.com/scrape?page=/path/to/article?page=2&per_page=2

So is `per_page` part of the `page=` variable or is it part of the main phantom request querystring? Impossible to tell.

Note that I worked around this by double-encoding the `page`, so it's actually `%252Fpath%252Fto%252Farticle%253Fpage%253D2%2526per_page%253D2` when it gets passed to phantom, and then decodes into `%2Fpath%2Fto%2Farticle%3Fpage%3D2%26per_page%3D2`.
