### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Aevin1387** [ariya/phantomjs#11595]
Random phantomJS crashes.

Operating system: Mac OS X
                  10.8.4 12E55
CPU: x86
     GenuineIntel family 6 model 42 stepping 7
     4 CPUs

Crash reason:  EXC_BAD_ACCESS / KERN_PROTECTION_FAILURE
Crash address: 0x18

Thread 0 (crashed)
 0  0x4dd34cf
    eip = 0x04dd34cf   esp = 0xbfff8b30   ebp = 0xbfff8b78   ebx = 0x0015ac81
    esi = 0x00000200   edi = 0x0966c678   eax = 0x04dd3468   ecx = 0x00000000
    edx = 0x0966c6f0   efl = 0x00210246
    Found by: given as instruction pointer in context
 1  phantomjs!__ZN3JSC11Interpreter11executeCallEPNS_9ExecStateEPNS_8JSObjectENS_8CallTypeERKNS_8CallDataENS_7JSValueERKNS_7ArgListE + 0x4a1
    eip = 0x0015b112   esp = 0xbfff8b80   ebp = 0xbfff8c78
    Found by: previous frame's frame pointer
 2  phantomjs!__ZN3JSC4callEPNS_9ExecStateENS_7JSValueENS_8CallTypeERKNS_8CallDataES2_RKNS_7ArgListE + 0x4c
    eip = 0x001f5a8d   esp = 0xbfff8c80   ebp = 0xbfff8ca8
    Found by: previous frame's frame pointer
 3  phantomjs!__ZN3JSC8Bindings18QtConnectionObject7executeEPPv + 0x64f
    eip = 0x00336550   esp = 0xbfff8cb0   ebp = 0xbfff8ec8
    Found by: previous frame's frame pointer
 4  phantomjs!__ZN3JSC8Bindings18QtConnectionObject11qt_metacallEN11QMetaObject4CallEiPPv + 0x4b
    eip = 0x0033722c   esp = 0xbfff8ed0   ebp = 0xbfff8ef8
    Found by: previous frame's frame pointer
 5  phantomjs!__ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 0x7a1
    eip = 0x0003e572   esp = 0xbfff8f00   ebp = 0xbfff9008
    Found by: previous frame's frame pointer
 6  phantomjs!__ZN7WebPage19navigationRequestedERK4QUrlRK7QStringbb + 0x5b
    eip = 0x000a8d3c   esp = 0xbfff9010   ebp = 0xbfff9058
    Found by: previous frame's frame pointer

Thread 1
 0  libsystem_kernel.dylib + 0x159ae
    eip = 0x94ffb9ae   esp = 0xb00805ac   ebp = 0xb0080718   ebx = 0xb0080700
    esi = 0x91bd08a1   edi = 0x00000000   eax = 0x0000016b   ecx = 0xb00805ac
    edx = 0x94ffb9ae   efl = 0x00000246
    Found by: given as instruction pointer in context
 1  libdispatch.dylib + 0x47a8
    eip = 0x91bd07a9   esp = 0xb0080720   ebp = 0xb0080f28
    Found by: previous frame's frame pointer

Thread 2
 0  libsystem_kernel.dylib + 0x150ee
    eip = 0x94ffb0ee   esp = 0xb0184f6c   ebp = 0xb0184f88   ebx = 0x98200cc7
    esi = 0xb0185000   edi = 0xb0185000   eax = 0x00100170   ecx = 0xb0184f6c
    edx = 0x94ffb0ee   efl = 0x00000282
    Found by: given as instruction pointer in context
 1  libsystem_c.dylib + 0x18e78
    eip = 0x98200e79   esp = 0xb0184f90   ebp = 0xb0184fc8
    Found by: previous frame's frame pointer
 2  libsystem_c.dylib + 0xd29
    eip = 0x981e8d2a   esp = 0xb0184fd0   ebp = 0xb0184fec
    Found by: previous frame's frame pointer

Thread 3
 0  libsystem_kernel.dylib + 0x128e6
    eip = 0x94ff88e6   esp = 0xb030ae7c   ebp = 0xb030aec8   ebx = 0x00000000
    esi = 0x80d4dab3   edi = 0x00002460   eax = 0xffffffa6   ecx = 0xb030ae7c
    edx = 0x94ff88e6   efl = 0x00000246
    Found by: given as instruction pointer in context
 1  libsystem_c.dylib + 0xa76b5
    eip = 0x9828f6b6   esp = 0xb030aed0   ebp = 0xb030aef8
    Found by: previous frame's frame pointer
 2  phantomjs!__ZN3WTF17TCMalloc_PageHeap15scavengerThreadEv + 0xb2
    eip = 0x000db4d3   esp = 0xb030af00   ebp = 0xb030af78
    Found by: previous frame's frame pointer
 3  phantomjs!__ZN3WTF17TCMalloc_PageHeap18runScavengerThreadEPv + 0x10
    eip = 0x000db741   esp = 0xb030af80   ebp = 0xb030af98
    Found by: previous frame's frame pointer
 4  libsystem_c.dylib + 0x165b6
    eip = 0x981fe5b7   esp = 0xb030afa0   ebp = 0xb030afc8
    Found by: previous frame's frame pointer
 5  libsystem_c.dylib + 0xd4d
    eip = 0x981e8d4e   esp = 0xb030afd0   ebp = 0xb030afec
    Found by: previous frame's frame pointer

Thread 4
 0  libsystem_kernel.dylib + 0x14c02
    eip = 0x94ffac02   esp = 0xb038cc1c   ebp = 0xb038cc48   ebx = 0x0178ce31
    esi = 0x03c104f4   edi = 0x00000008   eax = 0x00140197   ecx = 0xb038cc1c
    edx = 0x94ffac02   efl = 0x00000246
    Found by: given as instruction pointer in context
 1  phantomjs!__Z14qt_safe_selectiP6fd_setS0_S0_PK7timeval + 0x13f
    eip = 0x0178b6d0   esp = 0xb038cc50   ebp = 0xb038cca8
    Found by: previous frame's frame pointer
 2  phantomjs!__ZN27QEventDispatcherUNIXPrivate8doSelectE6QFlagsIN10QEventLoop17ProcessEventsFlagEEP7timeval + 0x189
    eip = 0x0178cfaa   esp = 0xb038ccb0   ebp = 0xb038cdc8
    Found by: previous frame's frame pointer
 3  phantomjs!__ZN20QEventDispatcherUNIX13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 0xae
    eip = 0x0178d43f   esp = 0xb038cdd0   ebp = 0xb038ce08
    Found by: previous frame's frame pointer
 4  phantomjs!__ZN10QEventLoop13processEventsE6QFlagsINS_17ProcessEventsFlagEE + 0x40
    eip = 0x0176a311   esp = 0xb038ce10   ebp = 0xb038ce38
    Found by: previous frame's frame pointer
 5  phantomjs!__ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 0x149
    eip = 0x0176a6da   esp = 0xb038ce40   ebp = 0xb038cea8
    Found by: previous frame's frame pointer
 6  phantomjs!__ZN7QThread4execEv + 0x10e
    eip = 0x0169f20f   esp = 0xb038ceb0   ebp = 0xb038cf18
    Found by: previous frame's frame pointer
 7  phantomjs!__ZN14QThreadPrivate5startEPv + 0x159
    eip = 0x016a038a   esp = 0xb038cf20   ebp = 0xb038cf98
    Found by: previous frame's frame pointer
 8  libsystem_c.dylib + 0x165b6
    eip = 0x981fe5b7   esp = 0xb038cfa0   ebp = 0xb038cfc8
    Found by: previous frame's frame pointer
 9  libsystem_c.dylib + 0xd4d
    eip = 0x981e8d4e   esp = 0xb038cfd0   ebp = 0xb038cfec
    Found by: previous frame's frame pointer

Thread 5
 0  libsystem_kernel.dylib + 0x14be6
    eip = 0x94ffabe6   esp = 0xb0395aac   ebp = 0xb039df98   ebx = 0x02df1860
    esi = 0x955e6001   edi = 0xac8d8c08   eax = 0x0014005d   ecx = 0xb0395aac
    edx = 0x94ffabe6   efl = 0x00000246
    Found by: given as instruction pointer in context
 1  libsystem_c.dylib + 0x165b6
    eip = 0x981fe5b7   esp = 0xb039dfa0   ebp = 0xb039dfc8
    Found by: previous frame's frame pointer
 2  libsystem_c.dylib + 0xd4d
    eip = 0x981e8d4e   esp = 0xb039dfd0   ebp = 0xb039dfec
    Found by: previous frame's frame pointer

Thread 6
 0  libsystem_kernel.dylib + 0x148e2
    eip = 0x94ffa8e2   esp = 0xb04a1d8c   ebp = 0xb04a1e18   ebx = 0x00000a00
    esi = 0x00000800   edi = 0x00000800   eax = 0x00000131   ecx = 0xb04a1d8c
    edx = 0x94ffa8e2   efl = 0x00000246
    Found by: given as instruction pointer in context
 1  libsystem_c.dylib + 0xa8b23
    eip = 0x98290b24   esp = 0xb04a1e20   ebp = 0xb04a1e38
    Found by: previous frame's frame pointer
 2  phantomjs!__ZN14QWaitCondition4waitEP6QMutexm + 0x103
    eip = 0x0000cfd4   esp = 0xb04a1e40   ebp = 0xb04a1ea8
    Found by: previous frame's frame pointer
 3  phantomjs!__ZN17QThreadPoolThread3runEv + 0x1bb
    eip = 0x0169807c   esp = 0xb04a1eb0   ebp = 0xb04a1f18
    Found by: previous frame's frame pointer
 4  phantomjs!__ZN14QThreadPrivate5startEPv + 0x159
    eip = 0x016a038a   esp = 0xb04a1f20   ebp = 0xb04a1f98
    Found by: previous frame's frame pointer
 5  libsystem_c.dylib + 0x165b6
    eip = 0x981fe5b7   esp = 0xb04a1fa0   ebp = 0xb04a1fc8
    Found by: previous frame's frame pointer
 6  libsystem_c.dylib + 0xd4d
    eip = 0x981e8d4e   esp = 0xb04a1fd0   ebp = 0xb04a1fec
    Found by: previous frame's frame pointer

Thread 7
 0  libsystem_kernel.dylib + 0x148e2
    eip = 0x94ffa8e2   esp = 0xb0523d8c   ebp = 0xb0523e18   ebx = 0x00000900
    esi = 0x00000700   edi = 0x00000700   eax = 0x00000131   ecx = 0xb0523d8c
    edx = 0x94ffa8e2   efl = 0x00000246
    Found by: given as instruction pointer in context
 1  libsystem_c.dylib + 0xa8b23
    eip = 0x98290b24   esp = 0xb0523e20   ebp = 0xb0523e38
    Found by: previous frame's frame pointer
 2  phantomjs!__ZN14QWaitCondition4waitEP6QMutexm + 0x103
    eip = 0x0000cfd4   esp = 0xb0523e40   ebp = 0xb0523ea8
    Found by: previous frame's frame pointer
 3  phantomjs!__ZN17QThreadPoolThread3runEv + 0x1bb
    eip = 0x0169807c   esp = 0xb0523eb0   ebp = 0xb0523f18
    Found by: previous frame's frame pointer
 4  phantomjs!__ZN14QThreadPrivate5startEPv + 0x159
    eip = 0x016a038a   esp = 0xb0523f20   ebp = 0xb0523f98
    Found by: previous frame's frame pointer
 5  libsystem_c.dylib + 0x165b6
    eip = 0x981fe5b7   esp = 0xb0523fa0   ebp = 0xb0523fc8
    Found by: previous frame's frame pointer
 6  libsystem_c.dylib + 0xd4d
    eip = 0x981e8d4e   esp = 0xb0523fd0   ebp = 0xb0523fec
    Found by: previous frame's frame pointer

Thread 8
 0  libsystem_kernel.dylib + 0x14c02
    eip = 0x94ffac02   esp = 0xb0206c1c   ebp = 0xb0206c48   ebx = 0x0178ce31
    esi = 0x0546a2f4   edi = 0x0000001a   eax = 0x00140197   ecx = 0xb0206c1c
    edx = 0x94ffac02   efl = 0x00000206
    Found by: given as instruction pointer in context
 1  phantomjs!__Z14qt_safe_selectiP6fd_setS0_S0_PK7timeval + 0x56
    eip = 0x0178b5e7   esp = 0xb0206c50   ebp = 0xb0206ca8
    Found by: previous frame's frame pointer
 2  phantomjs!__ZN27QEventDispatcherUNIXPrivate8doSelectE6QFlagsIN10QEventLoop17ProcessEventsFlagEEP7timeval + 0x189
    eip = 0x0178cfaa   esp = 0xb0206cb0   ebp = 0xb0206dc8
    Found by: previous frame's frame pointer
 3  phantomjs!__ZN20QEventDispatcherUNIX13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 0xae
    eip = 0x0178d43f   esp = 0xb0206dd0   ebp = 0xb0206e08
    Found by: previous frame's frame pointer
 4  phantomjs!__ZN10QEventLoop13processEventsE6QFlagsINS_17ProcessEventsFlagEE + 0x40
    eip = 0x0176a311   esp = 0xb0206e10   ebp = 0xb0206e38
    Found by: previous frame's frame pointer
 5  phantomjs!__ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 0x149
    eip = 0x0176a6da   esp = 0xb0206e40   ebp = 0xb0206ea8
    Found by: previous frame's frame pointer
 6  phantomjs!__ZN7QThread4execEv + 0x10e
    eip = 0x0169f20f   esp = 0xb0206eb0   ebp = 0xb0206f18
    Found by: previous frame's frame pointer
 7  phantomjs!__ZN14QThreadPrivate5startEPv + 0x159
    eip = 0x016a038a   esp = 0xb0206f20   ebp = 0xb0206f98
    Found by: previous frame's frame pointer
 8  libsystem_c.dylib + 0x165b6
    eip = 0x981fe5b7   esp = 0xb0206fa0   ebp = 0xb0206fc8
    Found by: previous frame's frame pointer
 9  libsystem_c.dylib + 0xd4d
    eip = 0x981e8d4e   esp = 0xb0206fd0   ebp = 0xb0206fec
    Found by: previous frame's frame pointer

Loaded modules:
0x00001000 - 0x01d1efff  phantomjs  ???  (main)
0x029e4000 - 0x029f1fff  Librarian  ???
0x02f00000 - 0x02f24fff  csparser  ???
0x04c00000 - 0x04cbefff  ColorSyncDeprecated.dylib  ???
0x9000d000 - 0x90118fff  libJP2.dylib  ???
0x90149000 - 0x901b1fff  IOKit  ???
0x901b2000 - 0x901b2fff  libsystem_blocks.dylib  ???
0x901b3000 - 0x90473fff  Security  ???
0x90474000 - 0x90475fff  TrustEvaluationAgent  ???
0x90476000 - 0x90477fff  libquarantine.dylib  ???
0x90478000 - 0x90482fff  SpeechRecognition  ???
0x90483000 - 0x9048cfff  DiskArbitration  ???
0x9048d000 - 0x9049bfff  libsystem_network.dylib  ???
0x9049c000 - 0x9049cfff  vecLib  ???
0x9049d000 - 0x904a1fff  OpenDirectory  ???
0x904a6000 - 0x904aefff  libcopyfile.dylib  ???
0x905d1000 - 0x905dbfff  libCSync.A.dylib  ???
0x905dc000 - 0x90608fff  libsystem_info.dylib  ???
0x90609000 - 0x90683fff  SecurityFoundation  ???
0x90684000 - 0x906f3fff  Heimdal  ???
0x906f9000 - 0x907cdfff  Backup  ???
0x907ce000 - 0x907f0fff  libc++abi.dylib  ???
0x9082e000 - 0x90870fff  RemoteViewServices  ???
0x908ef000 - 0x908f2fff  Help  ???
0x908f3000 - 0x90910fff  libresolv.9.dylib  ???
0x90b80000 - 0x90d09fff  vImage  ???
0x91016000 - 0x9101afff  IOSurface  ???
0x9142b000 - 0x91454fff  libxslt.1.dylib  ???
0x91455000 - 0x91455fff  libOpenScriptingUtil.dylib  ???
0x91486000 - 0x9148dfff  liblaunch.dylib  ???
0x9148e000 - 0x9148efff  Accelerate  ???
0x914d0000 - 0x914d7fff  libsystem_dnssd.dylib  ???
0x915af000 - 0x915f1fff  libcups.2.dylib  ???
0x915f2000 - 0x91605fff  MultitouchSupport  ???
0x91606000 - 0x9166efff  libvDSP.dylib  ???
0x9166f000 - 0x9167ffff  LangAnalysis  ???
0x91680000 - 0x91684fff  CommonPanels  ???
0x91685000 - 0x916a9fff  libJPEG.dylib  ???
0x916aa000 - 0x9170efff  DataDetectorsCore  ???
0x917ab000 - 0x917b1fff  Print  ???
0x917b2000 - 0x917b3fff  libremovefile.dylib  ???
0x917b4000 - 0x917c1fff  AppleFSCompression  ???
0x91819000 - 0x91a30fff  CoreData  ???
0x91a31000 - 0x91a35fff  libcache.dylib  ???
0x91a36000 - 0x91a5bfff  CoreVideo  ???
0x91a5c000 - 0x91a5efff  libRadiance.dylib  ???
0x91a5f000 - 0x91ab9fff  AE  ???
0x91aba000 - 0x91abdfff  libpam.2.dylib  ???
0x91abe000 - 0x91bcbfff  libobjc.A.dylib  ???
0x91bcc000 - 0x91bdefff  libdispatch.dylib  ???
0x91bdf000 - 0x91bedfff  libxar.1.dylib  ???
0x91bee000 - 0x91c3afff  libcorecrypto.dylib  ???
0x91c3b000 - 0x91c3efff  libCGXType.A.dylib  ???
0x9245d000 - 0x92469fff  libkxld.dylib  ???
0x9246a000 - 0x9246dfff  libcompiler_rt.dylib  ???
0x924d5000 - 0x924d5fff  libSystem.B.dylib  ???
0x927af000 - 0x92ab4fff  CarbonCore  ???
0x92ab5000 - 0x92ac7fff  libbsm.0.dylib  ???
0x92ac8000 - 0x92be4fff  DesktopServicesPriv  ???
0x92be5000 - 0x92bfcfff  GenerationalStorage  ???
0x92bfd000 - 0x92c21fff  PerformanceAnalysis  ???
0x92c29000 - 0x92c45fff  libPng.dylib  ???
0x92c46000 - 0x92c66fff  ChunkingLibrary  ???
0x92c67000 - 0x92cc9fff  libc++.1.dylib  ???
0x92cca000 - 0x92cd8fff  OpenGL  ???
0x92ce5000 - 0x92d49fff  libstdc++.6.dylib  ???
0x92d4a000 - 0x92d53fff  CarbonSound  ???
0x92d54000 - 0x93171fff  FaceCoreLight  ???
0x93172000 - 0x9317efff  CrashReporterSupport  ???
0x9317f000 - 0x932d8fff  AudioToolbox  ???
0x932da000 - 0x932e4fff  libsystem_notify.dylib  ???
0x932e5000 - 0x93433fff  CFNetwork  ???
0x93434000 - 0x934e8fff  CoreUI  ???
0x93d75000 - 0x93d8afff  SpeechSynthesis  ???
0x93d8b000 - 0x93e98fff  ImageIO  ???
0x93e99000 - 0x93f31fff  OSServices  ???
0x93f32000 - 0x93f89fff  HIServices  ???
0x93f8a000 - 0x93fbdfff  libssl.0.9.8.dylib  ???
0x93fbe000 - 0x94003fff  NavigationServices  ???
0x94053000 - 0x94c0ffff  AppKit  ???
0x94c10000 - 0x94c1bfff  libcommonCrypto.dylib  ???
0x94e4d000 - 0x94e4efff  libunc.dylib  ???
0x94e8f000 - 0x94ef0fff  CoreAudio  ???
0x94fe6000 - 0x95000fff  libsystem_kernel.dylib  ???
0x95001000 - 0x95058fff  ScalableUserInterface  ???
0x95059000 - 0x95082fff  libRIP.A.dylib  ???
0x95083000 - 0x95084fff  liblangid.dylib  ???
0x95085000 - 0x95117fff  libvMisc.dylib  ???
0x95118000 - 0x9511bfff  TCC  ???
0x9511c000 - 0x9511cfff  CoreServices  ???
0x9514e000 - 0x9514efff  Carbon  ???
0x953cd000 - 0x95427fff  Symbolication  ???
0x954ca000 - 0x9556afff  QD  ???
0x9556b000 - 0x95753fff  CoreFoundation  ???
0x95754000 - 0x9583dfff  libxml2.2.dylib  ???
0x9583e000 - 0x95863fff  FamilyControls  ???
0x95893000 - 0x958dbfff  OpenCL  ???
0x958dc000 - 0x9591bfff  Bom  ???
0x959a3000 - 0x959a5fff  libdyld.dylib  ???
0x959a6000 - 0x959d3fff  CoreServicesInternal  ???
0x959d4000 - 0x95e16fff  CoreGraphics  ???
0x95e17000 - 0x95f08fff  libiconv.2.dylib  ???
0x95f09000 - 0x95fc7fff  ColorSync  ???
0x95fe0000 - 0x960d8fff  libsqlite3.dylib  ???
0x960d9000 - 0x960effff  CFOpenDirectory  ???
0x960f0000 - 0x9611dfff  libsystem_m.dylib  ???
0x9611e000 - 0x9616cfff  SystemConfiguration  ???
0x9616d000 - 0x96179fff  libbz2.1.0.dylib  ???
0x9617a000 - 0x96211fff  Ink  ???
0x96212000 - 0x96212fff  AudioUnit  ???
0x96213000 - 0x9621cfff  CommonAuth  ???
0x9621d000 - 0x9623cfff  Ubiquity  ???
0x9623d000 - 0x96241fff  libGIF.dylib  ???
0x962fa000 - 0x96348fff  libFontRegistry.dylib  ???
0x96349000 - 0x9634afff  libDiagnosticMessagesClient.dylib  ???
0x9634b000 - 0x9634efff  libCoreVMClient.dylib  ???
0x9634f000 - 0x9666ffff  Foundation  ???
0x967a4000 - 0x967d5fff  DictionaryServices  ???
0x96bdc000 - 0x96bdcfff  libkeymgr.dylib  ???
0x96bdd000 - 0x96cdbfff  libFontParser.dylib  ???
0x96cdc000 - 0x96e98fff  libicucore.A.dylib  ???
0x96e99000 - 0x96ea7fff  libz.1.dylib  ???
0x96ea8000 - 0x96f2dfff  SearchKit  ???
0x96f2e000 - 0x96f7dfff  libTIFF.dylib  ???
0x96f7e000 - 0x96f84fff  libGFXShared.dylib  ???
0x96fcf000 - 0x97002fff  GSS  ???
0x97003000 - 0x9713efff  libBLAS.dylib  ???
0x977cc000 - 0x977cefff  libCVMSPluginSupport.dylib  ???
0x977cf000 - 0x977cffff  ApplicationServices  ???
0x97b0a000 - 0x97b23fff  Kerberos  ???
0x97b24000 - 0x97b99fff  ATS  ???
0x97b9a000 - 0x97bd0fff  DebugSymbols  ???
0x97bd1000 - 0x97bd2fff  libsystem_sandbox.dylib  ???
0x97bd3000 - 0x97c2efff  HTMLRendering  ???
0x97cac000 - 0x97d5bfff  CoreText  ???
0x97d5c000 - 0x97d5cfff  vecLib  ???
0x97d5d000 - 0x97da1fff  libGLU.dylib  ???
0x9803d000 - 0x9805afff  libxpc.dylib  ???
0x9805f000 - 0x981d7fff  QuartzCore  ???
0x981de000 - 0x981e7fff  CommerceCore  ???
0x981e8000 - 0x982a5fff  libsystem_c.dylib  ???
0x982a6000 - 0x9830cfff  PrintCore  ???
0x9830d000 - 0x98348fff  libGLImage.dylib  ???
0x98349000 - 0x98366fff  libCRFSuite.dylib  ???
0x983aa000 - 0x98454fff  LaunchServices  ???
0x98455000 - 0x984f0fff  CoreSymbolication  ???
0x984f1000 - 0x984fbfff  ServiceManagement  ???
0x99252000 - 0x99259fff  libunwind.dylib  ???
0x9925a000 - 0x99612fff  libLAPACK.dylib  ???
0x99674000 - 0x996f0fff  Metadata  ???
0x996f1000 - 0x996f3fff  SecurityHI  ???
0x996f4000 - 0x996fbfff  NetFS  ???
0x996fc000 - 0x99711fff  ImageCapture  ???
0x99712000 - 0x99721fff  libGL.dylib  ???
0x99b99000 - 0x99b9dfff  libmacho.dylib  ???
0x99b9e000 - 0x99c7ffff  libcrypto.0.9.8.dylib  ???
0x99c83000 - 0x99c8ffff  NetAuth  ???
0x99cf4000 - 0x99f97fff  CoreImage  ???
0x9a247000 - 0x9a265fff  OpenScripting  ???
0x9a266000 - 0x9a2a8fff  libauto.dylib  ???
0x9a2a9000 - 0x9a68cfff  HIToolbox  ???
0x9a68d000 - 0x9a68efff  libdnsinfo.dylib  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
