### ISSUE TITLE
--local-storage-path is ignored

### ISSUE THREAD

**Issue by rgauny** [ariya/phantomjs#11596]
I am using Phantomjs version 1.9.1 on linux (tried also in windows with no luck). After running the below example, the storage is saved in .qws/share/data/Ofi\ Labs/PhantomJS/https_delicious.com_0.localstorage

instead of in ./mylocal

am I doing something wrong here? Or is this a bug? 

my command:
phantomjs  --local-storage-path=./mylocal sample.js

my sample script:
page.open('https://delicious.com', function (){
    phantom.exit();
});

**Comment by zeroedin-bill** [comment]
This appears to be resolved in 2.0

**Comment by Vitallium** [comment]
Landed in https://github.com/ariya/phantomjs/commit/bc294d38d2618a24acc420f2da7a49061da82f5d

**Comment by PatrickHuetter** [comment]
I integrated this bugfix into the 1.9.x branch since it's only in 2.0 branch at this time. Pull request can be found here: https://github.com/ariya/phantomjs/pull/13825
