### ISSUE TITLE
This core happened when we used phantomjs for Screenshot

### ISSUE THREAD

**Issue by luxuechao** [ariya/phantomjs#11604]
We use phantomjs for Screenshot, but  this core happened occasionally. We look forward to resolving this core quickly. Please contact us if you have any question or need dmp file. We used captureSelector function to capture website 'http://v.360.cn/ct/O0DncMDbLYC2DD.html'.
![gdb](https://f.cloud.github.com/assets/5043711/1094800/2e3ca718-16d5-11e3-934c-00f4449f51c9.JPG)

**Comment by ariya** [comment]
Can you try again quickly with the latest version 2.1?
