### ISSUE TITLE
Ignore --proxy/--proxy-type when --webdriver 

### ISSUE THREAD

**Issue by a0s** [ariya/phantomjs#11619]
Hi! Phantomjs 1.9.1 ignore cli proxy settings (--proxy and --proxy-type) when in --webdriver mode. Is it a bug?
I override this by using --config file.

**Comment by ggnet** [comment]
@OndraM +1. I did not found any solution

**Comment by orangeudav** [comment]
After 3 years i found that '--config' trick works with http-proxy only, socks5 proxy not works in that way :(
