### ISSUE TITLE
SVG circle with stroke-dasharray style crashes phantomjs

### ISSUE THREAD

**Issue by alexspeller** [ariya/phantomjs#11621]
`<svg><circle style="stroke-dasharray: 6,3;"></svg>` seems to cause phantomjs to crash. Using version 1.9.2

**Comment by gogiii** [comment]
Same behavior for huge pathes in 2.1, seems like it's not a circle only problem:
`var webpage = require('webpage');`
`var p = webpage.create();`
`p.content = '<html><body><svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink"><path stroke="red" stroke-width="1" stroke-dasharray="5, 5" d="M -99999999 -99999999 L 99999999 99999999"></path></svg></body></html>';`
`phantom.exit();`
It either dies on rendering or by calling native functions like getScreenCTM() inside p.evaluate(function() {});
Neither chrome nor firefox crash. Removing "stroke-dasharray" fixes the crash.
