### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by mrgordon** [ariya/phantomjs#11639]
PhantomJS frequently crashes while running our Rails test suite.

Here is the crash dump:
http://www.2shared.com/file/c6QyC4sg/B78577F5-EA2A-4D57-8ECE-1E9DA2.html

This was produced on OS X using PhantomJS 1.9.1 from homebrew. I am upgrading to 1.9.2 now but we have seen these issues across various versions of PhantomJS.

Hope this helps!

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
