### ISSUE TITLE
querySelector(:nth-child) fails on second call

### ISSUE THREAD

**Issue by marksteward** [ariya/phantomjs#11632]
This can be reproduced by querying for nth-child with a descendant, where the descendant doesn't exist for the first matching nth-child.

This should alert "http://fiddle.jshell.net/1, http://fiddle.jshell.net/1", but actually alerts "http://fiddle.jshell.net/1, null" on Phantom:

  http://jsfiddle.net/GKb2g/5/

Probably something not being cleared up after the query.

**Comment by erikmontes** [comment]
Just came across this bug. I'm using 1.9.8.

**Comment by smpaq** [comment]
In 1.9.8, querying something like "ul > li:nth-child(1), ul > li:nth-child(2)" returns only the first child.

**Comment by EmilStenstrom** [comment]
Also cam across this bug: .dashboard_item .title:nth-of-type(1) returns more than one element.

**Comment by kylewelsby** [comment]
I can confirm PhantomJS 2.0.0 doesn't contain this bug anymore, and this can be marked as resolved.

**Comment by dgreene1** [comment]
But it is occurring in PhantomJS 2.1.1.
