### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Fresa** [ariya/phantomjs#11638]
Phantomjs is crashing leaving this dump.

http://fresa.se/50e45d7a-af9b-759d-0bd36376-5ff9a6d1.dmp

UPDATE: I get this dump everytime I try to run my local mocha script which starts phantomjs which loads pages over https.

http://fresa.se/3f6e4f5c-0842-4cb4-b07c-498983201d8c.dmp
"Exception Information: The thread tried to read from or write to a virtual address for which it does not have the appropriate access."

When I run the same script with phantomjs opening the same pages but on localhost and over http, it does not seem to crash. Could this be a SSL issue with phantom?

//Fredrik

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
