### ISSUE TITLE
phantom.js on windows retuns blank page of https://www.tumblr.com

### ISSUE THREAD

**Issue by skov555** [ariya/phantomjs#11647]
I tested it on linux and it works correctly but I run that simple 
one url page https://www.tumblr.com on 3 different windows instances and they all return
about:blank page, no content.

What is even more strange when I used fiddler as a proxy, trying to trace requests
it works but as soon as I exit fiddler it again returns blank page.

**Comment by Vitallium** [comment]
Fixed in 2.0. Please upgrade to PhantomJS 2.0.
