### ISSUE TITLE
Error message "SyntaxError: Parse error" doesn't help to find its source

### ISSUE THREAD

**Issue by AlexzAK** [ariya/phantomjs#11640]
As you know when one of files has invalid syntax PhantomJs provides us just with message:
"SyntaxError: Parse error"

If your file have many lines of if you have multiple files it is painful to search for error cause.
The Jshint tool can help, but it is possible to solve this task using only PhantomJs

if the cpp file src/webpage.cpp at line 160 there is the function javaScriptError
```
    void javaScriptError(const QString &message, int lineNumber, const QString &sourceID, const QString &stack) {
        Q_UNUSED(lineNumber);
        Q_UNUSED(sourceID);
        emit m_webPage->javaScriptErrorSent(message, stack);
    }
```

As you can see, arguments `lineNumber` and `sourceID` are not used and throwed away.
But them contains valid information about SyntaxError source file and line.
I've check it using debug output

So,
Can you, please, forward arguments `lineNumber` and `sourceID` into the `javaScriptErrorSent` handler and make those arguments available in the javascript `onError` handler?

It seems that many people find this error message confusing.
It can be far easier to understand and handle error when source of the error is shown

**Comment by a-x-** [comment]
i have current issue

**Comment by Vitallium** [comment]
Fixed in 2.0. Please upgrade to PhantomJS 2.0.

**Comment by mao73a** [comment]
Just downloaded phantom.js v 2.1.1 and now syntax error causes phantom to stop responding. No error message at all.

**Comment by shellscape** [comment]
@mao73a normally I wouldn't suggest another project, but given that the last maintainer has stepped down (https://www.infoq.com/news/2017/04/Phantomjs-future-uncertain) and this project won't be maintained anymore, I'd suggest using Headless Chrome (check out the chromy module) or Electron.
