### ISSUE TITLE
setContent not working when HTML has assets

### ISSUE THREAD

**Issue by tamlyn** [ariya/phantomjs#11656]
This script works:

```
var page = require('webpage').create(); 

var html = '<h1>Test</h1><img>'; //works with page.setContent and page.content
//var html = '<h1>Test</h1><img src=".">'; //only works with page.content

page.setContent(html, 'http://github.com');
//page.content = html;

page.render('test.png');
phantom.exit();
```

but adding a `src` attribute to the `img` makes it fail silently (`page.render` returns `false` and no image is generated).

Setting `page.content` directly works in both cases but then relative URLs don't. The same thing happens with other tags that load a resource such as `link`. It doesn't matter whether the linked resource exists or not. Tested in 1.8.1 and 1.9.2.

Is this a bug or have I misunderstood the API?

**Comment by r4j4h** [comment]
Wanted to add there is now a setContent function that attempts to also set a url.

What we had to do though was make sure the url given to it starts with a protocol, e.g. `http://` or `file://` for requests to trigger.

**Comment by r4j4h** [comment]
Wanted to add there is now a setContent function that attempts to also set a url.

What we had to do though was make sure the url given to it starts with a protocol, e.g. http:// or file:// for requests to trigger.

Also see #12271
