### ISSUE TITLE
PhantomJS crashes every time

### ISSUE THREAD

**Issue by zenhuman** [ariya/phantomjs#11654]
For several months, I've used phantomjs daily.  Yesterday, using Process Explorer, I killed a second instance of phantom that I'd started accidentally.  Now, I can start scripts, but at a certain point in the script I need to run, phantomjs crashes every time.  I'm running 1.09.02 on a Windows 8 machine.  Any help would be greatly appreciated.  Here's the crash dump:

<

Show DivPrimary Analysis

Crash Dump Analysis provided by OSR Open Systems Resources, Inc. (http://www.osr.com)
Online Crash Dump Analysis Service
See http://www.osronline.com for more information
Windows 8 Version 9200 MP (4 procs) Free x86 compatible
Product: WinNt, suite: SingleUserTS Personal
kernel32.dll version: 6.2.9200.16627 (win8_gdr.130530-1548)
Machine Name:
Debug session time: Fri Sep 27 18:01:14.000 2013 (UTC - 4:00)
System Uptime: not available
Process Uptime: 0 days 0:01:07.000
  Kernel time: 0 days 0:00:02.000
  User time: 0 days 0:00:51.000
TRIAGER: Could not open triage file : e:\dump_analysis\program\triage\oca.ini, error 2
TRIAGER: Could not open triage file : e:\dump_analysis\program\winxp\triage.ini, error 2
TRIAGER: Could not open triage file : e:\dump_analysis\program\triage\user.ini, error 2

---
-                                                                             *
-                        Exception Analysis                                   *
-                                                                             *
  *******************************************************************************

TRIAGER: Could not open triage file : e:\dump_analysis\program\triage\guids.ini, error 2
TRIAGER: Could not open triage file : e:\dump_analysis\program\triage\modclass.ini, error 2

FAULTING_IP: 
phantomjs+a4bdc8
00b7bdc8 897004          mov     dword ptr [eax+4],esi

EXCEPTION_RECORD:  ffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 00b7bdc8 (phantomjs+0x00a4bdc8)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000001
   Parameter[1]: 00000004
Attempt to write to address 00000004

DEFAULT_BUCKET_ID:  NULL_CLASS_PTR_WRITE

PROCESS_NAME:  phantomjs.exe

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at "0x%08lx" referenced memory at "0x%08lx". The memory could not be "%s".

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at "0x%08lx" referenced memory at "0x%08lx". The memory could not be "%s".

EXCEPTION_PARAMETER1:  00000001

EXCEPTION_PARAMETER2:  00000004

WRITE_ADDRESS:  00000004 

FOLLOWUP_IP: 
phantomjs+a4bdc8
00b7bdc8 897004          mov     dword ptr [eax+4],esi

FAULTING_THREAD:  00000054

PRIMARY_PROBLEM_CLASS:  NULL_CLASS_PTR_WRITE

BUGCHECK_STR:  APPLICATION_FAULT_NULL_CLASS_PTR_WRITE

LAST_CONTROL_TRANSFER:  from 772f3711 to 00b7bdc8

STACK_TEXT:  
WARNING: Stack unwind information not available. Following frames may be wrong.
0166bb00 772f3711 00002000 00000002 01ac0000 phantomjs+0xa4bdc8
0166bb8c 773199ab 01ac0000 77302a3a 773199c3 ntdll!RtlAllocateHeap+0x115
0166bccc 00000000 00000000 00d228e0 00000002 ntdll!RtlpReAllocateHeap+0x219

STACK_COMMAND:  ~0s; .ecxr ; kb

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  phantomjs+a4bdc8

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: phantomjs

IMAGE_NAME:  phantomjs.exe

DEBUG_FLR_IMAGE_TIMESTAMP:  514ec5fb

FAILURE_BUCKET_ID:  NULL_CLASS_PTR_WRITE_c0000005_phantomjs.exe!Unknown

BUCKET_ID:  APPLICATION_FAULT_NULL_CLASS_PTR_WRITE_phantomjs+a4bdc8

WATSON_IBUCKET:  -720598223

WATSON_IBUCKETTABLE:  1

WATSON_STAGEONE_URL:  http://watson.microsoft.com/StageOne/phantomjs_exe/1_9_0_0/514ec5fb/phantomjs_exe/1_9_0_0/514ec5fb/c0000005/00a4bdc8.htm?Retriage=1
## Followup: MachineOwner

This free analysis is provided by OSR Open Systems Resources, Inc.
Want a deeper understanding of crash dump analysis? Check out our Windows Kernel Debugging and Crash Dump Analysis Seminar (opens in new tab/window)
Hide DivLoaded Module List

start    end        module name
00130000 014e9000   phantomjs phantomjs.exe
6c4c0000 6c542000   winhttp  winhttp.dll 
6da50000 6da8f000   powrprof powrprof.dll
6da90000 6daa0000   dhcpcsvc6 dhcpcsvc6.DLL
6e430000 6e559000   dbghelp  dbghelp.dll 
71ef0000 720e8000   comctl32 comctl32.dll
720f0000 72159000   tiptsf   tiptsf.dll  
72ad0000 72ae2000   dhcpcsvc dhcpcsvc.dll
72ef0000 72f78000   uxtheme  uxtheme.dll 
73290000 732a9000   dwmapi   dwmapi.dll  
732b0000 73310000   winspool winspool.drv
73860000 7389e000   rsaenh   rsaenh.dll  
738a0000 738ba000   cryptsp  cryptsp.dll 
73960000 7399f000   FWPUCLNT FWPUCLNT.DLL
739a0000 739a7000   rasadhlp rasadhlp.dll
739b0000 739d1000   mdnsNSP  mdnsNSP.dll 
739e0000 73a55000   dnsapi   dnsapi.dll  
73b90000 73b98000   winnsi   winnsi.dll  
73d50000 73d70000   IPHLPAPI IPHLPAPI.DLL
740a0000 740ea000   mswsock  mswsock.dll 
741d0000 74245000   SHCore   SHCore.dll  
74250000 7427b000   WINMMBASE WINMMBASE.dll
74280000 742a1000   winmm    winmm.dll  
74870000 748c1000   bcryptPrimitives bcryptPrimitives.dll
748d0000 748d9000   CRYPTBASE CRYPTBASE.dll
748e0000 748fc000   sspicli  sspicli.dll 
74900000 7491e000   devobj   devobj.dll  
74920000 74a36000   user32   user32.dll  
74a40000 74a52000   msasn1   msasn1.dll  
74a60000 74ae9000   comdlg32 comdlg32.dll
74b00000 74b08000   nsi      nsi.dll  
74b10000 74b50000   shlwapi  shlwapi.dll 
74d50000 74d84000   sechost  sechost.dll 
74d90000 74dd6000   cfgmgr32 cfgmgr32.dll
74e50000 74e70000   imm32    imm32.dll  
75010000 750c1000   msvcrt   msvcrt.dll  
750d0000 75251000   crypt32  crypt32.dll 
75260000 75379000   ole32    ole32.dll  
75380000 7542c000   rpcrt4   rpcrt4.dll  
75650000 756a0000   ws2_32   ws2_32.dll  
75730000 75860000   kernel32 kernel32.dll
75860000 76926000   shell32  shell32.dll 
76930000 76a66000   combase  combase.dll 
76a70000 76b16000   KERNELBASE KERNELBASE.dll
76b20000 76bfd000   msctf    msctf.dll  
76db0000 76ead000   gdi32    gdi32.dll  
76f40000 76fee000   advapi32 advapi32.dll
76ff0000 7707b000   oleaut32 oleaut32.dll
772b0000 77407000   ntdll    ntdll.dll   

Hide DivRaw Stack Contents

Memory access error at 'StackLimit) @@(((ntdll!_NT_TIB *)@$teb)->StackBase)'

Hide DivDump Header Information

----- User Mini Dump Analysis

MINIDUMP_HEADER:
Version         A793 (62F0)
NumberOfStreams 9
Flags           0
                0000 MiniDumpNormal

Streams:
Stream 0: type ThreadListStream (3), size 00000244, RVA 000004AC
  12 threads
  RVA 000004B0, ID 54, Teb:000000007EF9E000
  RVA 000004E0, ID 143C, Teb:000000007EF99000
  RVA 00000510, ID 1C60, Teb:000000007EF96000
  RVA 00000540, ID 1024, Teb:000000007EE6F000
  RVA 00000570, ID F88, Teb:000000007EE6C000
  RVA 000005A0, ID 1A3C, Teb:000000007EE69000
  RVA 000005D0, ID 1FCC, Teb:000000007EE66000
  RVA 00000600, ID 1D0C, Teb:000000007EE63000
  RVA 00000630, ID 1C78, Teb:000000007EE5D000
  RVA 00000660, ID 1B54, Teb:000000007EE5A000
  RVA 00000690, ID 1FA0, Teb:000000007EE54000
  RVA 000006C0, ID 1A44, Teb:000000007EE51000
Stream 1: type ModuleListStream (4), size 000014B0, RVA 000006FC
  49 modules
  RVA 00000700, 00130000 - 014e9000: 'C:__IDX\PJS3\phantomjs_v1_09\phantomjs.exe'
  RVA 0000076C, 772b0000 - 77407000: 'C:\Windows\System32\ntdll.dll'
  RVA 000007D8, 75730000 - 75860000: 'C:\Windows\System32\kernel32.dll'
  RVA 00000844, 76a70000 - 76b16000: 'C:\Windows\System32\KERNELBASE.dll'
  RVA 000008B0, 76f40000 - 76fee000: 'C:\Windows\System32\advapi32.dll'
  RVA 0000091C, 74a60000 - 74ae9000: 'C:\Windows\System32\comdlg32.dll'
  RVA 00000988, 750d0000 - 75251000: 'C:\Windows\System32\crypt32.dll'
  RVA 000009F4, 76db0000 - 76ead000: 'C:\Windows\System32\gdi32.dll'
  RVA 00000A60, 74e50000 - 74e70000: 'C:\Windows\System32\imm32.dll'
  RVA 00000ACC, 75260000 - 75379000: 'C:\Windows\System32\ole32.dll'
  RVA 00000B38, 76ff0000 - 7707b000: 'C:\Windows\System32\oleaut32.dll'
  RVA 00000BA4, 75860000 - 76926000: 'C:\Windows\System32\shell32.dll'
  RVA 00000C10, 74920000 - 74a36000: 'C:\Windows\System32\user32.dll'
  RVA 00000C7C, 74280000 - 742a1000: 'C:\Windows\System32\winmm.dll'
  RVA 00000CE8, 732b0000 - 73310000: 'C:\Windows\System32\winspool.drv'
  RVA 00000D54, 75650000 - 756a0000: 'C:\Windows\System32\ws2_32.dll'
  RVA 00000DC0, 75010000 - 750c1000: 'C:\Windows\System32\msvcrt.dll'
  RVA 00000E2C, 74d50000 - 74d84000: 'C:\Windows\System32\sechost.dll'
  RVA 00000E98, 75380000 - 7542c000: 'C:\Windows\System32\rpcrt4.dll'
  RVA 00000F04, 74b10000 - 74b50000: 'C:\Windows\System32\shlwapi.dll'
  RVA 00000F70, 71ef0000 - 720e8000: 'C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9200.16579_none_8937eec6860750f5\comctl32.dll'
  RVA 00000FDC, 74a40000 - 74a52000: 'C:\Windows\System32\msasn1.dll'
  RVA 00001048, 76b20000 - 76bfd000: 'C:\Windows\System32\msctf.dll'
  RVA 000010B4, 76930000 - 76a66000: 'C:\Windows\System32\combase.dll'
  RVA 00001120, 74250000 - 7427b000: 'C:\Windows\System32\WINMMBASE.dll'
  RVA 0000118C, 74b00000 - 74b08000: 'C:\Windows\System32\nsi.dll'
  RVA 000011F8, 748e0000 - 748fc000: 'C:\Windows\System32\sspicli.dll'
  RVA 00001264, 74d90000 - 74dd6000: 'C:\Windows\System32\cfgmgr32.dll'
  RVA 000012D0, 74900000 - 7491e000: 'C:\Windows\System32\devobj.dll'
  RVA 0000133C, 748d0000 - 748d9000: 'C:\Windows\System32\CRYPTBASE.dll'
  RVA 000013A8, 741d0000 - 74245000: 'C:\Windows\System32\SHCore.dll'
  RVA 00001414, 74870000 - 748c1000: 'C:\Windows\System32\bcryptPrimitives.dll'
  RVA 00001480, 6e430000 - 6e559000: 'C:\Windows\System32\dbghelp.dll'
  RVA 000014EC, 72ef0000 - 72f78000: 'C:\Windows\System32\uxtheme.dll'
  RVA 00001558, 720f0000 - 72159000: 'C:\Program Files (x86)\Common Files\microsoft shared\Ink\tiptsf.dll'
  RVA 000015C4, 73290000 - 732a9000: 'C:\Windows\System32\dwmapi.dll'
  RVA 00001630, 738a0000 - 738ba000: 'C:\Windows\System32\cryptsp.dll'
  RVA 0000169C, 73860000 - 7389e000: 'C:\Windows\System32\rsaenh.dll'
  RVA 00001708, 6c4c0000 - 6c542000: 'C:\Windows\System32\winhttp.dll'
  RVA 00001774, 73d50000 - 73d70000: 'C:\Windows\System32\IPHLPAPI.DLL'
  RVA 000017E0, 73b90000 - 73b98000: 'C:\Windows\System32\winnsi.dll'
  RVA 0000184C, 6da90000 - 6daa0000: 'C:\Windows\System32\dhcpcsvc6.DLL'
  RVA 000018B8, 72ad0000 - 72ae2000: 'C:\Windows\System32\dhcpcsvc.dll'
  RVA 00001924, 740a0000 - 740ea000: 'C:\Windows\System32\mswsock.dll'
  RVA 00001990, 739e0000 - 73a55000: 'C:\Windows\System32\dnsapi.dll'
  RVA 000019FC, 739b0000 - 739d1000: 'C:\Program Files (x86)\Bonjour\mdnsNSP.dll'
  RVA 00001A68, 739a0000 - 739a7000: 'C:\Windows\System32\rasadhlp.dll'
  RVA 00001AD4, 73960000 - 7399f000: 'C:\Windows\System32\FWPUCLNT.DLL'
  RVA 00001B40, 6da50000 - 6da8f000: 'C:\Windows\System32\powrprof.dll'
Stream 2: type MemoryListStream (5), size 00000114, RVA 00005558
  17 memory ranges
  range#    RVA      Address      Size
       0 0000566C    0397dd50   000022b0
       1 0000791C    0613f928   000006d8
       2 00007FF4    064ff940   000006c0
       3 000086B4    05def5f8   00000a08
       4 000090BC    772ddbb4   00000150
       5 0000920C    772de124   00000100
       6 0000930C    772de964   00000100
       7 0000940C    772df634   00000100
       8 0000950C    0431f6d0   00000930
       9 00009E3C    00b7bd48   00000100
      10 00009F3C    0166b314   00004cec
      11 0000EC28    06acfa6c   00000594
      12 0000F1BC    041df788   00000878
      13 0000FA34    0627f63c   000009c4
      14 000103F8    01abf280   00000d80
      15 00011178    069cfc3c   000003c4
      16 0001153C    0663db58   000024a8
  Total memory: e378
Stream 3: type ExceptionStream (6), size 000000A8, RVA 00000404
  ThreadID 84
  ExceptionCode C0000005
  ExceptionRecord 0
  ExceptionAddress b7bdc8
  Context record RVA 29e6, size 2cc
Stream 4: type SystemInfoStream (7), size 00000038, RVA 0000008C
  ProcessorArchitecture   0000 (PROCESSOR_ARCHITECTURE_INTEL)
  ProcessorLevel          0006
  ProcessorRevision       3A09
  NumberOfProcessors      04
  MajorVersion            00000006
  MinorVersion            00000002
  BuildNumber             000023F0 (9200)
  PlatformId              00000002 (VER_PLATFORM_WIN32_NT)
  CSDVersionRva           00001BAC
                            Length: 0
  Product: WinNt, suite: SingleUserTS Personal
Stream 5: type MiscInfoStream (15), size 00000340, RVA 000000C4
Stream 6: type ??? (1197932545), size 0000000C, RVA 0000554C
Dir entry 6, ??? stream has unknown stream type 1197932545
Stream 7: type UnusedStream (0), size 00000000, RVA 00000000
Stream 8: type UnusedStream (0), size 00000000, RVA 00000000

Hide DivStrings

GenuineIntel 
Pacific Standard Time 
Pacific Daylight Time 
6.2.9200.16384 (win8_rtm.120725-1247) 
dbghelp.i386,6.2.9200.16384 
/5vPf$ 
C:__IDX\PJS3\phantomjs_v1_09\phantomjs.exe 
C:\Windows\System32\ntdll.dll 
C:\Windows\System32\kernel32.dll 
C:\Windows\System32\KERNELBASE.dll 
C:\Windows\System32\advapi32.dll 
C:\Windows\System32\comdlg32.dll 
C:\Windows\System32\crypt32.dll 
C:\Windows\System32\gdi32.dll 
C:\Windows\System32\imm32.dll 
C:\Windows\System32\ole32.dll 
C:\Windows\System32\oleaut32.dll 
C:\Windows\System32\shell32.dll 
C:\Windows\System32\user32.dll 
C:\Windows\System32\winmm.dll 
C:\Windows\System32\winspool.drv 
C:\Windows\System32\ws2_32.dll 
C:\Windows\System32\msvcrt.dll 
C:\Windows\System32\sechost.dll 
C:\Windows\System32\rpcrt4.dll 
C:\Windows\System32\shlwapi.dll 
C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9200.16579_none_8937eec6860750f5\comctl32.dll 
C:\Windows\System32\msasn1.dll 
C:\Windows\System32\msctf.dll 
C:\Windows\System32\combase.dll 
C:\Windows\System32\WINMMBASE.dll 
C:\Windows\System32\nsi.dll 
C:\Windows\System32\sspicli.dll 
C:\Windows\System32\cfgmgr32.dll 
C:\Windows\System32\devobj.dll 
C:\Windows\System32\CRYPTBASE.dll 
C:\Windows\System32\SHCore.dll 
C:\Windows\System32\bcryptPrimitives.dll 
C:\Windows\System32\dbghelp.dll 
C:\Windows\System32\uxtheme.dll 
C:\Program Files (x86)\Common Files\microsoft shared\Ink\tiptsf.dll 
C:\Windows\System32\dwmapi.dll 
C:\Windows\System32\cryptsp.dll 
C:\Windows\System32\rsaenh.dll 
C:\Windows\System32\winhttp.dll 
C:\Windows\System32\IPHLPAPI.DLL 
C:\Windows\System32\winnsi.dll 
C:\Windows\System32\dhcpcsvc6.DLL 
C:\Windows\System32\dhcpcsvc.dll 
C:\Windows\System32\mswsock.dll 
C:\Windows\System32\dnsapi.dll 
C:\Program Files (x86)\Bonjour\mdnsNSP.dll 
C:\Windows\System32\rasadhlp.dll 
C:\Windows\System32\FWPUCLNT.DLL 
C:\Windows\System32\powrprof.dll 
/537.4 ( 
/537.4 ( 
\file__0.localst 
1.1.utmcsr=idp.nwmls.com|utmccn= 
wntdll.pdb 
wkernel32.pdb 
wkernelbase.pdb 
advapi32.pdb 
comdlg32.pdb 
crypt32.pdb 
wgdi32.pdb 
RSDS8q 
wimm32.pdb 
ole32.pdb 
oleaut32.pdb 
shell32.pdb 
wuser32.pdb 
RSDSg` 
winmm.pdb 
winspool.pdb 
ws2_32.pdb 
msvcrt.pdb 
sechost.pdb 
wrpcrt4.pdb 
shlwapi.pdb 
RSDSd5 
comctl32.pdb 
msasn1.pdb 
msctf.pdb 
combase.pdb 
winmmbase.pdb 
nsi.pdb 
wsspicli.pdb 
cfgmgr32.pdb 
devobj.pdb 
cryptbase.pdb 
RSDS+] 
shcore.pdb 
RSDS&p 
bcryptprimitives.pdb 
dbghelp.pdb 
wuxtheme.pdb 
RSDS_3erf 
tiptsf.pdb 
dwmapi.pdb 
cryptsp.pdb 
rsaenh.pdb 
winhttp.pdb 
iphlpapi.pdb 
o5]!~H 
winnsi.pdb 
dhcpcsvc6.pdb 
dhcpcsvc.pdb 
mswsock.pdb 
dnsapi.pdb 
C:\bwa\BonjourWin-86\srcroot\mDNSWindows\mdnsNSP\Win32\Release\mdnsNSP.pdb 
rasadhlp.pdb 
fwpuclnt.pdb 
powrprof.pdb 
En0[RP 
*_w@=0w 
-w$E-wl 
-w$E-w 
-w$E-w 
/537.4 ( 
H7/w8^; 
0wS@(t 
-w$E-w 
-w$E-wl 
"0wd&0w 
\StringFileInfo\040904b0\FileVersion 
Pacific Standard Time 
Pacific Daylight Time 
6.2.9200.16384 (win8_rtm.120725-1247)

**Comment by snuggles08** [comment]
Can confirm I have this issue.
