### ISSUE TITLE
Add different proxies support

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#11667]
We can set single proxy in command line like:
phantomjs example.js --proxy="ip:port"

But it would be useful to set (or change) proxy "on fly" for specific page objects:

var page1 = require('webpage').create();
page1.settings.proxy ="ip1:port";

var page2 = require('webpage').create();
page2.settings.proxy ="ip2:port";

Sometimes it's far better than launching different phantomjs processes (as we should do now to use different proxies).

**Comment by zackw** [comment]
This is now implemented via `page.setProxy()`, see 985175ee2262d6c313aa730d561168dc126abae2.

**Comment by soda-wy** [comment]
@zackw this featrue do not have any doc or test, how do a new guy know it?

**Comment by zinkovskiy** [comment]
I learned about this opportunity to read the source code)) can i help with writing documentation?

**Comment by arfianadam** [comment]
and what's the parameter for `page.setProxy()` ? is it like `phantom.setProxy(host, port)` ?
