### ISSUE TITLE
Element is not currently interactable and may not be manipulated

### ISSUE THREAD

**Issue by fraogongi** [ariya/phantomjs#11662]
I get a problem while running Selenium tests (Python) with PhantomJS. I have a form with just two input fields. Works perfectly OK in Firefox and other browsers, but when using PhantomJS, I get the following error regarding element with id=id_name

```
     "InvalidElementStateException: Message: u'Error Message => \'Element is not currently interactable and may not be manipulated"
```

I can clearly see the the input elements are present when I take a screenshot via selenium functions. And my code is as simple as the following:

```
    driver.find_element_by_id("id_name").clear()
    driver.find_element_by_id("id_name").send_keys("Frosinone")
    driver.find_element_by_id("id_code").clear()
    driver.find_element_by_id("id_code").send_keys("FR")
```

Is this an issue with PhantomJS itself?

As an example script to test, see the following python file "login_test.py"

```
import unittest
from selenium import webdriver

class TestOne(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.PhantomJS()

    def test_url(self):
        self.driver.get("https://signup.live.com/")
        self.driver.find_element_by_id('iFirstName').send_keys("realpython")
        self.driver.find_element_by_id("iLastName").send_keys("realpython")
        #self.driver.find_element_by_id("loginsubmit").click()

    def tearDown(self):
        self.driver.quit

if __name__ == '__main__':
    unittest.main()
```

To run this, simply type "python login_test.py ". You will notice that the input elements are not found yet they are there on the page.

**Comment by maxko87** [comment]
I am also having this issue.

**Comment by ConstantinSco** [comment]
I meet this problem too,have you soluted it now?
