### ISSUE TITLE
document.querySelector inexplicably returns null for some websites.

### ISSUE THREAD

**Issue by jdwilliams15** [ariya/phantomjs#11679]
It was suggested i bring this issue up for phantomJS as well: Here's the most recent thread: 

A current issue I'm having is that for some webpages I try to scrape, for some reason, getElementsInfo, and evaluate... document.querySelectorAll returns null for any inquiry.

The current page I'm seeing this problem with is www.solesociety.com. I've tried using the selectors *, form, and form#mini_search_form for this page and all return null.

Example code I used:

var casper = require('casper').create();

casper.start('http://www.amazon.com');
casper.then(function() {
    var elements = this.getElementsInfo("*");
    casper.echo('Num elements: ' + elements.length);
});

casper.run();
Current casper version is 1.1.0-DEV
Current phantom version 1.9.1 

 n1k0 commented an hour ago
Scratch that, I reproduced your issue using the url you suggested in the description. I have no idea what's going on here.

 n1k0 commented an hour ago
For the records, this native PhantomJS fails as well:

var page = require('webpage').create();

page.open("http://www.solesociety.com", function() {
  console.log(page.evaluate(function() {
    return document.querySelector("*").length;
  }));
  phantom.exit();
});
Gives:

$ phantomjs test.js
null

**Comment by PankajVK1993** [comment]
I tested with querySelector and this code works fine fa me...

setTimeout(function() {
    console.log("");
    console.log("### STEP 1: Click on Signup button");
        page.evaluate(function(value) {
        var ev = document.createEvent("MouseEvents");
        ev.initEvent("click", true, true);
        document.querySelector("footer > button[type='submit']").dispatchEvent(ev);
    });
    page.render('screenshot_test001_' + Date.now()+'.png');
}, 5000);

**Comment by crossmax** [comment]
I've the same problem with querySelectorAll function when I want to select 5 differents span with aleatories id attributes. I get 4/5 objects null and I can't onclick over them
