### ISSUE TITLE
1.9.2 linux x86_64 crash

### ISSUE THREAD

**Issue by carols10cents** [ariya/phantomjs#11687]
Hi, PhantomJS just crashed for me with this error message:

>> pure virtual method called
>> terminate called without an active exception
>> PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/3e8d7caa-e21a-26b6-1c8910d9-2f459d24.dmp
>> Exited with code: 1.

Here's the stack trace: https://gist.github.com/carols10cents/7045258

The next time we ran the same set of tests, PhantomJS didn't crash, so I'm not sure how to reliably reproduce this.

Thank you for all your hard work!! <3 <3 <3

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
