### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by peterkappus** [ariya/phantomjs#11708]
Hi Gang, This is my first bug report so I hope I'm doing it right. I wasn't able to extract a stack trace (I'm on OSX exclusively) but Phantom JS is crashing on me pretty consistently now. Using Cucumber, Capybara, and Poltergeist to drive it. I was trying to temporarily ignore JS errors by doing the following in my test setup:

Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, {:js_errors => false})
end

I think that's what caused the error (or else one of those JS errors I ignored was throwing Phantom JS for a loop...)

Thanks for a great tool! Happy debugging...

Peter

**Comment by Vitallium** [comment]
You should try 2.0 version. It has many improvements and fixes.
