### ISSUE TITLE
phantomjs get page content fail when I try some special url

### ISSUE THREAD

**Issue by luocanrao** [ariya/phantomjs#11724]
most case, phantomjs get page content work fine.
but when I try urls as follows, it failed all the time. But chrome, ie works fine

http://ytn111.tape160.com/w/  
http://wewkw.oss-cn-hangzhou.aliyuncs.com/io8.htm

my js code is as follows

var fs = require('fs');

page.viewportSize = { width: 900, height: 600 };

page.open(url, function () {
    window.setTimeout(function () {
      fs.write('save.html', page.content, 'w');
      page.render('save.png');
      phantom.exit();
    },800);

});

**Comment by RameshSundar** [comment]
phantomjs --ssl-protocol=any test.js 

may be this one helps...
