### ISSUE TITLE
PhantomJS can't use some CSS selectors twice

### ISSUE THREAD

**Issue by n1k0** [ariya/phantomjs#11737]
I know, that sounds crazy, but oddly the Webkit version PhantomJS ships with can't perform some CSS queries _twice_.

Here's a minimal sample script reproducing the issue (I'm using PhantomJS 1.9.2 on OSX Mavericks):

``` js
var page = require('webpage').create();

page.content = [
  '<div class="box">',
  '  <form><input type="text" name="a" id="a"></form>',
  '</div>',
  '<div class="box">',
  '  <form><input type="text" name="b" id="b" value="42"></form>',
  '</div>'
].join('');

function get42() {
  return document.querySelector('.box:nth-child(2) form [name="b"]').value;
}

console.log(page.evaluate(get42));
console.log(page.evaluate(get42));
phantom.exit();
```

Execution:

```
$ phantomjs p.js
42
TypeError: 'null' is not an object (evaluating 'document.querySelector('.box:nth-child(2) form [name="b"]').value')

  phantomjs://webpage.evaluate():2 in get42
  phantomjs://webpage.evaluate():3
  phantomjs://webpage.evaluate():3
null
```

See? Am I getting insane or the second operation failed while the first ran smoothly bringing the expected result?

**Comment by soundstep** [comment]
Having the same problem here with phantomjs v2.1.1, any news on that?

**Comment by dgreene1** [comment]
Yea, this is still happening in v2.1.1

**Comment by wmurmann** [comment]
I just ran into the same problem. Same page, same xpath but my selector returns null. Found a workaround by using waitForSelector('selector') to timeout and calling a page reload. After the reload the selector works again.
