### ISSUE TITLE
PhantomJS Crash In CloudLinux with CageFS

### ISSUE THREAD

**Issue by metasanjaya** [ariya/phantomjs#11757]
Operating system: Linux
                  0.0.0 Linux 2.6.32-458.18.1.lve1.2.41.el6.x86_64 #1 SMP Wed Oct 9 09:34:17 EDT 2013 x86_64
CPU: amd64
     family 6 model 58 stepping 9
     1 CPU

Crash reason:  SIGSEGV
Crash address: 0xbbadbeef

Thread 0 (crashed)
 0  phantomjs!WTF::OSAllocator::reserveUncommitted [OSAllocatorPosix.cpp : 107 + 0x7]
    rbx = 0xffffffffffffffff   r12 = 0x000000000445d840
    r13 = 0x000000000000007f   r14 = 0x00007f74a0191820
    r15 = 0x00007f74a0191720   rip = 0x00000000004f8057
    rsp = 0x00007fff77520b20   rbp = 0x7ff8000000000000
    Found by: given as instruction pointer in context
 1  phantomjs!JSC::ExecutableAllocator::isValid [PageReservation.h : 107 + 0x18]
    rbx = 0x000000000445d820   r12 = 0x000000000445d840
    r13 = 0x000000000000007f   r14 = 0x00007f74a0191820
    r15 = 0x00007f74a0191720   rip = 0x0000000000f31fd1
    rsp = 0x00007fff77520b30   rbp = 0x7ff8000000000000
    Found by: call frame info
 2  phantomjs!JSC::ExecutableAllocator::ExecutableAllocator [ExecutableAllocator.h : 185 + 0x7]
    rbx = 0x0000000002acac58   r12 = 0x00000000044e9cd0
    r13 = 0x000000000000007f   r14 = 0x00007f74a0191820
    r15 = 0x00007f74a0191720   rip = 0x0000000000f88d66
    rsp = 0x00007fff77520b80   rbp = 0x7ff8000000000000
    Found by: call frame info
 3  phantomjs!JSC::JSGlobalData::JSGlobalData [JSGlobalData.cpp : 170 + 0x9]
    rbx = 0x00007f74a0190000   r12 = 0x00000000044e9cd0
    r13 = 0x000000000000007f   r14 = 0x0000000000000085
    r15 = 0x00007f74a0191720   rip = 0x0000000000f89b2e
    rsp = 0x00007fff77520bf0   rbp = 0x7ff8000000000000
    Found by: call frame info
 4  phantomjs!JSC::JSGlobalData::createLeaked [JSGlobalData.cpp : 326 + 0x9]
    rbx = 0x0000000000000000   r12 = 0x00007fff77520e90
    r13 = 0x0000000004459140   r14 = 0x00007fff77520f30
    r15 = 0x0000000004552eb0   rip = 0x0000000000f8b5b1
    rsp = 0x00007fff77520e70   rbp = 0x00007f74a0190000
    Found by: call frame info
 5  phantomjs!WebCore::JSDOMWindowBase::commonJSGlobalData [JSDOMWindowBase.cpp : 159 + 0x9]
    rbx = 0x00007fff77520f80   r12 = 0x00007fff77521050
    r13 = 0x0000000004459140   r14 = 0x00007fff77520f30
    r15 = 0x0000000004552eb0   rip = 0x000000000051d382
    rsp = 0x00007fff77520e90   rbp = 0x00007f74a0184000
    Found by: call frame info
 6  phantomjs!WebCore::FrameLoaderClientQt::createDocumentLoader [FrameLoaderClientQt.cpp : 990 + 0x4]
    rbx = 0x00007fff77520f80   r12 = 0x00007fff77521050
    r13 = 0x0000000004459140   r14 = 0x00007fff77520f30
    r15 = 0x0000000004552eb0   rip = 0x00000000004b900d
    rsp = 0x00007fff77520ec0   rbp = 0x00007f74a0184000
    Found by: call frame info
 7  phantomjs!WebCore::FrameLoader::load [FrameLoader.cpp : 1460 + 0x13]
    rbx = 0x0000000000000000   r12 = 0x00007f74a0187478
    r13 = 0x000000000445d780   r14 = 0x000000000444c350
    r15 = 0x0000000004552eb0   rip = 0x0000000000864b57
    rsp = 0x00007fff77520ef0   rbp = 0x0000000000000001
    Found by: call frame info
 8  phantomjs!QWebFrame::setHtml [qwebframe.cpp : 976 + 0x1d]
    rbx = 0x0000000000000000   r12 = 0x00007f74a01c0400
    r13 = 0x000000000445d780   r14 = 0x000000000444c350
    r15 = 0x0000000004552eb0   rip = 0x00000000004827d1
    rsp = 0x00007fff77520f80   rbp = 0x0000000000000001
    Found by: call frame info
 9  phantomjs!WebPage::WebPage [webpage.cpp : 323 + 0x12]
    rbx = 0x000000000444c330   r12 = 0x00007fff77521320
    r13 = 0x00007fff77521310   r14 = 0x000000000444c350
    r15 = 0x000000000444c358   rip = 0x000000000041833e
    rsp = 0x00007fff77521210   rbp = 0x0000000004529280
    Found by: call frame info
10  phantomjs!Phantom::init [phantom.cpp : 102 + 0x40]
    rbx = 0x0000000004529280   r12 = 0x0000000004575580
    r13 = 0x0000000004575520   r14 = 0x00007fff775218e0
    r15 = 0x0000000000000000   rip = 0x0000000000409bf3
    rsp = 0x00007fff77521370   rbp = 0x00007fff775215e0
    Found by: call frame info
11  phantomjs!Phantom::instance [phantom.cpp : 154 + 0x4]
    rbx = 0x00007fff775219f0   r12 = 0x00007fff77521970
    r13 = 0x00007fff77521b18   r14 = 0x00007fff775218e0
    r15 = 0x0000000000000000   rip = 0x000000000040b576
    rsp = 0x00007fff775218b0   rbp = 0x0000000004575520
    Found by: call frame info
12  phantomjs!main [main.cpp : 117 + 0x4]
    rbx = 0x00007fff775219f0   r12 = 0x00007fff77521970
    r13 = 0x00007fff77521b18   r14 = 0x00007fff775218e0
    r15 = 0x0000000000000000   rip = 0x0000000000427c9e
    rsp = 0x00007fff775218d0   rbp = 0x00007fff77521b08
    Found by: call frame info
13  libc-2.12.so + 0x1ecdc
    rbx = 0x0000000000000000   r12 = 0x0000000000407cc0
    r13 = 0x00007fff77521b00   r14 = 0x0000000000000000
    r15 = 0x0000000000000000   rip = 0x00007f749ea6dcdd
    rsp = 0x00007fff77521a30   rbp = 0x0000000000000000
    Found by: call frame info
14  phantomjs + 0x27a5f
    rip = 0x0000000000427a60   rsp = 0x00007fff77521a50
    Found by: stack scanning

Thread 1
 0  libpthread-2.12.so + 0xb43c
    rbx = 0x0000000002ab0208   r12 = 0x0000000002aa2160
    r13 = 0x00007f749ce789c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007f749f58d43c
    rsp = 0x00007f749ce77de0   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  phantomjs!WTF::TCMalloc_PageHeap::scavengerThread [FastMalloc.cpp : 2495 + 0x7]
    rip = 0x00000000004ddafc   rsp = 0x00007f749ce77e10
    Found by: stack scanning
 2  phantomjs!WTF::TCMalloc_PageHeap::runScavengerThread [FastMalloc.cpp : 1618 + 0x4]
    rbx = 0x0000000000000000   r12 = 0x00007f749f593200
    r13 = 0x00007f749ce789c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00000000004ddc99
    rsp = 0x00007f749ce77e90   rbp = 0x0000000000000000
    Found by: call frame info
 3  libpthread-2.12.so + 0x7850
    rbx = 0x0000000000000000   r12 = 0x00007f749f593200
    r13 = 0x00007f749ce789c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007f749f589851
    rsp = 0x00007f749ce77ea0   rbp = 0x0000000000000000
    Found by: call frame info
 4  libpthread-2.12.so + 0x111ff
    rip = 0x00007f749f593200   rsp = 0x00007f749ce77f48
    Found by: stack scanning
 5  libpthread-2.12.so + 0x111ff
    rip = 0x00007f749f593200   rsp = 0x00007f749ce77fc0
    Found by: stack scanning
 6  libc-2.12.so + 0xe892c
    rip = 0x00007f749eb3792d   rsp = 0x00007f749ce77fe0
    Found by: stack scanning

Thread 2
 0  libc-2.12.so + 0xe1513
    rbx = 0x0000000000000000   r12 = 0x00007f749c676d70
    r13 = 0x000000000000000a   r14 = 0x00007f7494000a98
    r15 = 0x00007f7494000d30   rip = 0x00007f749eb30513
    rsp = 0x00007f749c676b40   rbp = 0x00007f74940008e0
    Found by: given as instruction pointer in context
 1  phantomjs!qt_safe_select [qcore_unix.cpp : 83 + 0x15]
    rip = 0x0000000001d062f7   rsp = 0x00007f749c676b50
    Found by: stack scanning
 2  phantomjs!QEventDispatcherUNIXPrivate::doSelect [qeventdispatcher_unix.cpp : 223 + 0xd]
    rbx = 0x00007f74940012b0   r12 = 0x00007f749c676d70
    r13 = 0x00007f74940008e0   r14 = 0x0000000000000000
    r15 = 0x00007f7494000d30   rip = 0x0000000001d075b7
    rsp = 0x00007f749c676be0   rbp = 0x00007f74940008e0
    Found by: call frame info
 3  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 937 + 0x4]
    rbx = 0x00007f74940012b0   r12 = 0x00007f749c676d70
    r13 = 0x00007f74940008c0   r14 = 0x0000000000000001
    r15 = 0x000000000444de58   rip = 0x0000000001d08062
    rsp = 0x00007f749c676d20   rbp = 0x00007f74940008e0
    Found by: call frame info
 4  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x00007f74940012b0   r12 = 0x00007f749c676e00
    r13 = 0x00007f749c676e10   r14 = 0x000000000435f230
    r15 = 0x000000000444de58   rip = 0x0000000001cdd485
    rsp = 0x00007f749c676d70   rbp = 0x00007f749c676db0
    Found by: call frame info
 5  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x00007f74940012b0   r12 = 0x00007f749c676e00
    r13 = 0x00007f749c676e10   r14 = 0x000000000435f230
    r15 = 0x000000000444de58   rip = 0x0000000001cdd8e8
    rsp = 0x00007f749c676da0   rbp = 0x00007fff77521970
    Found by: call frame info
 6  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
    rbx = 0x000000000444ddd0   r12 = 0x000000000444de58
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000000001bdfdd6
    rsp = 0x00007f749c676e00   rbp = 0x000000000444de58
    Found by: call frame info
 7  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x000000000444de58   r12 = 0x000000000444ded0
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000000001be2ca2
    rsp = 0x00007f749c676e50   rbp = 0x0000000004508c60
    Found by: call frame info
 8  libpthread-2.12.so + 0x7850
    rbx = 0x0000000000000000   r12 = 0x00007fff77520e50
    r13 = 0x00007f749c6779c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007f749f589851
    rsp = 0x00007f749c676ea0   rbp = 0x0000000000000000
    Found by: call frame info

Loaded modules:
0x00400000 - 0x026b9fff  phantomjs  ???  (main)
0x7f749ce79000 - 0x7f749d096fff  libselinux.so.1  ???
0x7f749d098000 - 0x7f749d2affff  libresolv-2.12.so  ???
0x7f749d2b2000 - 0x7f749d4b4fff  libkeyutils.so.1.3  ???
0x7f749d4b5000 - 0x7f749d6bffff  libkrb5support.so.0.1  ???
0x7f749d6c0000 - 0x7f749d8eafff  libk5crypto.so.3.1  ???
0x7f749d8ec000 - 0x7f749daeffff  libcom_err.so.2.1  ???
0x7f749daf0000 - 0x7f749ddd5fff  libkrb5.so.3.3  ???
0x7f749ddd6000 - 0x7f749e019fff  libgssapi_krb5.so.2.2  ???
0x7f749e01a000 - 0x7f749e276fff  libssl.so.1.0.0  ???
0x7f749e277000 - 0x7f749e48cfff  libz.so.1.2.3  ???
0x7f749e48d000 - 0x7f749e822fff  libcrypto.so.1.0.0  ???
0x7f749e827000 - 0x7f749ea4efff  libexpat.so.1.5.2  ???
0x7f749ea4f000 - 0x7f749eddcfff  libc-2.12.so  ???
0x7f749ede2000 - 0x7f749eff7fff  libgcc_s-4.4.7-20120601.so.1  ???
0x7f749eff8000 - 0x7f749f27bfff  libm-2.12.so  ???
0x7f749f27c000 - 0x7f749f56cfff  libstdc++.so.6.0.13  ???
0x7f749f582000 - 0x7f749f79afff  libpthread-2.12.so  ???
0x7f749f79f000 - 0x7f749f9a6fff  librt-2.12.so  ???
0x7f749f9a7000 - 0x7f749fbaafff  libdl-2.12.so  ???
0x7f749fbab000 - 0x7f749fde0fff  libfontconfig.so.1.4.4  ???
0x7f749fde1000 - 0x7f74a007dfff  libfreetype.so.6.3.22  ???
0x7f74a007e000 - 0x7f74a009dfff  ld-2.12.so  ???
0x7f74a027d000 - 0x7f74a0280fff  87f5e051180a7a75f16eb6fe7dbd3749-le64.cache-3  ???
0x7f74a0281000 - 0x7f74a0289fff  b79f3aaa7d385a141ab53ec885cc22a8-le64.cache-3  ???
0x7f74a029a000 - 0x7f74a029bfff  b67b32625a2bb51b023d3814a918f351-le64.cache-3  ???
0x7fff775fe000 - 0x7fff775fffff  linux-gate.so  ???

**Comment by muhzak** [comment]
Every solve this?
