### ISSUE TITLE
PhantonJS keeps crashing (almost) consistently

### ISSUE THREAD

**Issue by explorer2309** [ariya/phantomjs#11753]
We have an internal application, which has a user journey consisting of several pages. After running through the first 4 pages, Phantom JS crashes on 5th page. Only occassional it can get past the 5th page.

Phantom version: 1.9.2
OS: Windows 7

I have the dump file, but I do not know how to convert it to stack trace on windows.

Thanks!

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
