### ISSUE TITLE
about page.render "jpg"

### ISSUE THREAD

**Issue by liutianyu** [ariya/phantomjs#11758]
test.html ：
< !DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
< html xmlns="http://www.w3.org/1999/xhtml">
< head>
< meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
< title>title< /title>
< /head>
< body>
test< br />
test
< /body>
< /html>

phantomjs：
var page = require('webpage').create();
page.open('http://127.0.0.1/test.html', function () {
    page.render('test.png'); // ok
    page.render('test.jpg');  // background = black ?
    phantom.exit();
});

test.png ↓
![test](https://f.cloud.github.com/assets/2558510/1555802/758d7038-4e8a-11e3-9810-0000a0755070.png)
test.jpg ↓
![test](https://f.cloud.github.com/assets/2558510/1555804/81f8c020-4e8a-11e3-86b0-4751630d8cb9.jpg)

**Comment by JustinYi922** [comment]
亲们,我都2.1.1版本了， 为啥还是黑屏？
