### ISSUE TITLE
Mink's WebDriver doesn't remove all cookies between tests

### ISSUE THREAD

**Issue by HenkPoley** [ariya/phantomjs#11768]
Before this gets closed as invalid ("not my problem"), at the Behat/Mink side they appear to say that this is a bug/problem with PhantomJS. That it's impossible to remove all cookies via the WebDriver interface on this headless browser.

The reset() function here appears to try to remove all cookies: 
https://github.com/Behat/MinkSeleniumDriver/blob/master/src/Behat/Mink/Driver/SeleniumDriver.php

I'd really like to know where the bug lies. Cutting up my tests and restarting PhantomJS to work around the failures is very suboptimal.

**Comment by robingram** [comment]
I'm also battling with this, Makes automated testing awkward because features are not isolated.

**Comment by victorCas** [comment]
Same issue here.

**Comment by docteurklein** [comment]
just realized the same issue appears here.

**Comment by davidmpaz** [comment]
I came into this while testing some use cases. 

I stop having this issue after updating to phantomjs version 2.2.1

**Comment by gabbsmo** [comment]
@davidmpaz The latest version on the download page is 2.1.1. How did you update to 2.2.1? http://phantomjs.org/download.html
