### ISSUE TITLE
Page loaded from local filesystem will not load resources

### ISSUE THREAD

**Issue by merrill77** [ariya/phantomjs#11762]
When a file from the local filesystem is loaded into PhantomJS using a file path (rather than a proper URI), the page content appears to load fine, but resources referenced in the page that are relative to the page (and thus on the local filesystem) will not be loaded.

This problem was experienced on Win7/64 with PhantomJS 1.9.0.

PhantomJS should either locate those resources correctly or it should fail fast - by refusing to load a file using a filesystem path (preferably with a message indicating that a proper URI is required). In the current lazy failure mode, a lot of time can be wasted by the user trying to determine why the page doesn't function correctly.

**Comment by Vitallium** [comment]
It now runs successfully with 2.0 version.
