### ISSUE TITLE
Crash while doing cross-domain ajax

### ISSUE THREAD

**Issue by JeffAMcGee** [ariya/phantomjs#11772]
I'm using prerender, which is built on top of phantom, to generate static pages of my ember application. (http://prerender.io) The ember application does cross-domain requests to our api by setting `document.domain` in an iframe as described here: http://engineering.foursquare.com/2011/12/08/web-sites-are-clients-too/ .  Phantomjs usually crashes when I do the first cross-domain request.  The crash happens after the iframe loads, and before our first ajax request is sent.  When I run phantomjs with the flag `--web-security=no`, phantomjs does not crash.

Here's the backtrace of the thread that crashed:

    Operating system: Mac OS X
                      10.9.0 13A603
    CPU: x86
         GenuineIntel family 6 model 58 stepping 9
         4 CPUs
     
    Crash reason:  EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
    Crash address: 0xffffffffffffffc8
     
    Thread 0 (crashed)
     0  0xa5b2125
        eip = 0x0a5b2125   esp = 0xbfffc130   ebp = 0xbfffc178   ebx = 0x09128300
        esi = 0x00000200   edi = 0x09207758   eax = 0x03ff8120   ecx = 0x00000000
        edx = 0xfffffffb   efl = 0x00210282
        Found by: given as instruction pointer in context
     1  phantomjs!__ZN3JSC11Interpreter11executeCallEPNS_9ExecStateEPNS_8JSObjectENS_8CallTypeERKNS_8CallDataENS_7JSValueERKNS_7ArgListE + 0x533
        eip = 0x000d85a6   esp = 0xbfffc180   ebp = 0xbfffc208
        Found by: previous frame's frame pointer
     2  phantomjs!__ZN3JSC4callEPNS_9ExecStateENS_7JSValueENS_8CallTypeERKNS_8CallDataES2_RKNS_7ArgListE + 0x48
        eip = 0x00150359   esp = 0xbfffc210   ebp = 0xbfffc238
        Found by: previous frame's frame pointer
     3  phantomjs!__ZN3JSC8Bindings18QtConnectionObject7executeEPPv + 0x7bd
        eip = 0x00224632   esp = 0xbfffc240   ebp = 0xbfffc3c8
        Found by: previous frame's frame pointer
     4  phantomjs!__ZN3JSC8Bindings18QtConnectionObject11qt_metacallEN11QMetaObject4CallEiPPv + 0x45
        eip = 0x00221618   esp = 0xbfffc3d0   ebp = 0xbfffc3f8
        Found by: previous frame's frame pointer
     5  phantomjs!__ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 0x638
        eip = 0x011eb24f   esp = 0xbfffc400   ebp = 0xbfffc4a8
        Found by: previous frame's frame pointer
     6  phantomjs!__ZN7WebPage28javaScriptConsoleMessageSentERK7QString + 0x3c
        eip = 0x0005d93b   esp = 0xbfffc4b0   ebp = 0xbfffc4c8
        Found by: previous frame's frame pointer

 The full crash log is here: https://gist.github.com/JeffAMcGee/7587744

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
