### ISSUE TITLE
Segmentation fault - error 

### ISSUE THREAD

**Issue by ssv5088** [ariya/phantomjs#11778]
Hi,

I did get "Segmentation fault" while reading the entire content of http://www.rantsports.com/nfl/2013/11/21/tom-coughlin-proving-hes-one-of-all-time-greats/ - the main page and all iframe content - and making an image of this page.

I did test the code in a Centos server.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
