### ISSUE TITLE
phantomjs crash on linux when using webserver

### ISSUE THREAD

**Issue by orlylevf** [ariya/phantomjs#11785]
The crash is after complete process the request, write the response and close the response

The dump file:
Operating system: Linux
                  0.0.0 Linux 3.5.0-36-generic #57~precise1-Ubuntu SMP Thu Jun 20 18:21:09 UTC 2013 x86_64
CPU: amd64
     family 6 model 58 stepping 9
     8 CPUs

Crash reason:  SIGSEGV
Crash address: 0x0

Thread 0 (crashed)
 0  phantomjs + 0xd86f0
    rbx = 0x00007fff2efbc740   r12 = 0x0000000004b0cba0
    r13 = 0x00000000048485c0   r14 = 0x0000000004af5f00
    r15 = 0x0000000004b0cd20   rip = 0x00000000004d86f0
    rsp = 0x00007fff2efbc700   rbp = 0x0000000004b26de0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x6b0c4
    rip = 0x000000000046b0c5   rsp = 0x00007fff2efbc710
    Found by: stack scanning
 2  phantomjs + 0x1d4b7
    rip = 0x000000000041d4b8   rsp = 0x00007fff2efbc720
    Found by: stack scanning
 3  phantomjs + 0x17d25df
    rip = 0x0000000001bd25e0   rsp = 0x00007fff2efbc7a0
    Found by: stack scanning
 4  phantomjs + 0x22f844
    rip = 0x000000000062f845   rsp = 0x00007fff2efbc7b0
    Found by: stack scanning
 5  libc-2.15.so + 0x3b871f
    rip = 0x00007f6928026720   rsp = 0x00007fff2efbc7c0
    Found by: stack scanning
 6  phantomjs + 0x65436
    rip = 0x0000000000465437   rsp = 0x00007fff2efbc810
    Found by: stack scanning
 7  phantomjs + 0x82d80
    rip = 0x0000000000482d81   rsp = 0x00007fff2efbc820
    Found by: stack scanning
 8  phantomjs + 0x18c816e
    rip = 0x0000000001cc816f   rsp = 0x00007fff2efbc840
    Found by: stack scanning
 9  phantomjs + 0x18d4217
    rip = 0x0000000001cd4218   rsp = 0x00007fff2efbc870
    Found by: stack scanning
10  phantomjs + 0x18dd4f1
    rip = 0x0000000001cdd4f2   rsp = 0x00007fff2efbc8a0
    Found by: stack scanning
11  phantomjs + 0x18d4217
    rip = 0x0000000001cd4218   rsp = 0x00007fff2efbc930
    Found by: stack scanning
12  phantomjs + 0x135cab
    rip = 0x0000000000535cac   rsp = 0x00007fff2efbc950
    Found by: stack scanning
13  phantomjs + 0x18d4217
    rip = 0x0000000001cd4218   rsp = 0x00007fff2efbc980
    Found by: stack scanning
14  phantomjs + 0xb45b30
    rip = 0x0000000000f45b31   rsp = 0x00007fff2efbc9e0
    Found by: stack scanning
15  phantomjs + 0x86747
    rip = 0x0000000000486748   rsp = 0x00007fff2efbca10
    Found by: stack scanning
16  phantomjs + 0x86747
    rip = 0x0000000000486748   rsp = 0x00007fff2efbca60
    Found by: stack scanning
17  phantomjs + 0xb1d9aa
    rip = 0x0000000000f1d9ab   rsp = 0x00007fff2efbca90
    Found by: stack scanning
18  phantomjs + 0x11d02fe
    rip = 0x00000000015d02ff   rsp = 0x00007fff2efbcad0
    Found by: stack scanning
19  phantomjs + 0x11d8f8a
    rip = 0x00000000015d8f8b   rsp = 0x00007fff2efbcb00
    Found by: stack scanning
20  phantomjs + 0x11d02fe
    rip = 0x00000000015d02ff   rsp = 0x00007fff2efbcb20
    Found by: stack scanning
21  phantomjs + 0x11d8f8a
    rip = 0x00000000015d8f8b   rsp = 0x00007fff2efbcb50
    Found by: stack scanning
22  phantomjs + 0x11b5b3
    rip = 0x000000000051b5b4   rsp = 0x00007fff2efbcbc0
    Found by: stack scanning
23  phantomjs + 0x11b741
    rip = 0x000000000051b742   rsp = 0x00007fff2efbccb0
    Found by: stack scanning
24  phantomjs + 0x14023b
    rip = 0x000000000054023c   rsp = 0x00007fff2efbccf0
    Found by: stack scanning
25  phantomjs + 0x18e484d
    rip = 0x0000000001ce484e   rsp = 0x00007fff2efbcd10
    Found by: stack scanning
26  phantomjs + 0x71f42
    rip = 0x0000000000471f43   rsp = 0x00007fff2efbcd30
    Found by: stack scanning

Thread 1
 0  libc-2.15.so + 0xbf84d
    rbx = 0x00007f6926f29cf0   r12 = 0x0000000002ab39c0
    r13 = 0x00007f6929552500   r14 = 0x0000000002abba00
    r15 = 0x0000000002abb9d0   rip = 0x00007f6927d2d84d
    rsp = 0x00007f6926f29c40   rbp = 0x00000000ffffffff
    Found by: given as instruction pointer in context
 1  libc-2.15.so + 0xbf6eb
    rip = 0x00007f6927d2d6ec   rsp = 0x00007f6926f29c50
    Found by: stack scanning
 2  phantomjs + 0x193fbaf
    rip = 0x0000000001d3fbb0   rsp = 0x00007f6926f29c58
    Found by: stack scanning
 3  phantomjs + 0x2e2c
    rip = 0x0000000000402e2d   rsp = 0x00007f6926f29c68
    Found by: stack scanning
 4  libc-2.15.so + 0x109f7
    rip = 0x00007f6927c7e9f8   rsp = 0x00007f6926f29c70
    Found by: stack scanning
 5  phantomjs + 0x24c7
    rip = 0x00000000004024c8   rsp = 0x00007f6926f29c78
    Found by: stack scanning
 6  ld-2.15.so + 0xa522
    rip = 0x00007f6929344523   rsp = 0x00007f6926f29cc8
    Found by: stack scanning
 7  libc-2.15.so + 0xbf858
    rip = 0x00007f6927d2d859   rsp = 0x00007f6926f29cd8
    Found by: stack scanning
 8  libpthread-2.15.so + 0xfcaf
    rip = 0x00007f692884ecb0   rsp = 0x00007f6926f29ce8
    Found by: stack scanning
 9  libpthread-2.15.so + 0xb103
    rip = 0x00007f692884a104   rsp = 0x00007f6926f29d90
    Found by: stack scanning
10  libc-2.15.so + 0xe54f
    rip = 0x00007f6927c7c550   rsp = 0x00007f6926f29d98
    Found by: stack scanning
11  ld-2.15.so + 0x15234
    rip = 0x00007f692934f235   rsp = 0x00007f6926f29dd0
    Found by: stack scanning
12  libpthread-2.15.so + 0xe9f9
    rip = 0x00007f692884d9fa   rsp = 0x00007f6926f29de0
    Found by: stack scanning
13  libpthread-2.15.so + 0xbe17
    rip = 0x00007f692884ae18   rsp = 0x00007f6926f29df0
    Found by: stack scanning
14  phantomjs + 0xcfcbd
    rip = 0x00000000004cfcbe   rsp = 0x00007f6926f29e20
    Found by: stack scanning
15  libpthread-2.15.so + 0x1187f
    rip = 0x00007f6928850880   rsp = 0x00007f6926f29e80
    Found by: stack scanning
16  phantomjs + 0xcff28
    rip = 0x00000000004cff29   rsp = 0x00007f6926f29ea0
    Found by: stack scanning
17  libpthread-2.15.so + 0x7e99
    rip = 0x00007f6928846e9a   rsp = 0x00007f6926f29eb0
    Found by: stack scanning
18  libpthread-2.15.so + 0x1187f
    rip = 0x00007f6928850880   rsp = 0x00007f6926f29f58
    Found by: stack scanning
19  libc-2.15.so + 0xf3ccc
    rip = 0x00007f6927d61ccd   rsp = 0x00007f6926f29fc0
    Found by: stack scanning

Thread 2
 0  libc-2.15.so + 0xed033
    rbx = 0x0000000000000000   r12 = 0x00007f6926728d80
    r13 = 0x0000000000000008   r14 = 0x00007f6920000a98
    r15 = 0x00007f6920000d30   rip = 0x00007f6927d5b033
    rsp = 0x00007f6926728b50   rbp = 0x00007f69200008e0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x18ea916
    rip = 0x0000000001cea917   rsp = 0x00007f6926728b60
    Found by: stack scanning
 2  phantomjs + 0x1d13db
    rip = 0x00000000005d13dc   rsp = 0x00007f6926728b88
    Found by: stack scanning
 3  ld-2.15.so + 0xa29d
    rip = 0x00007f692934429e   rsp = 0x00007f6926728ba0
    Found by: stack scanning
 4  phantomjs + 0x18ebbd6
    rip = 0x0000000001cebbd7   rsp = 0x00007f6926728bf0
    Found by: stack scanning
 5  phantomjs + 0x18db0a6
    rip = 0x0000000001cdb0a7   rsp = 0x00007f6926728c10
    Found by: stack scanning
 6  phantomjs + 0x17f3332
    rip = 0x0000000001bf3333   rsp = 0x00007f6926728c20
    Found by: stack scanning
 7  linux-gate.so + 0x8a3
    rip = 0x00007fff2efff8a4   rsp = 0x00007f6926728c30
    Found by: stack scanning
 8  phantomjs + 0x1d13db
    rip = 0x00000000005d13dc   rsp = 0x00007f6926728c38
    Found by: stack scanning
 9  librt-2.15.so + 0x415c
    rip = 0x00007f6928a6015d   rsp = 0x00007f6926728c60
    Found by: stack scanning
10  phantomjs + 0x18324f3
    rip = 0x0000000001c324f4   rsp = 0x00007f6926728c70
    Found by: stack scanning
11  phantomjs + 0x1d13db
    rip = 0x00000000005d13dc   rsp = 0x00007f6926728c88
    Found by: stack scanning
12  phantomjs + 0x18323f8
    rip = 0x0000000001c323f9   rsp = 0x00007f6926728cb0
    Found by: stack scanning
13  phantomjs + 0x18eb595
    rip = 0x0000000001ceb596   rsp = 0x00007f6926728cc0
    Found by: stack scanning
14  phantomjs + 0x1d13db
    rip = 0x00000000005d13dc   rsp = 0x00007f6926728cd8
    Found by: stack scanning
15  phantomjs + 0x1d13db
    rip = 0x00000000005d13dc   rsp = 0x00007f6926728cf8
    Found by: stack scanning
16  phantomjs + 0x18ec681
    rip = 0x0000000001cec682   rsp = 0x00007f6926728d30
    Found by: stack scanning
17  phantomjs + 0x18c1aa4
    rip = 0x0000000001cc1aa5   rsp = 0x00007f6926728d80
    Found by: stack scanning
18  phantomjs + 0x18c2298
    rip = 0x0000000001cc2299   rsp = 0x00007f6926728d90
    Found by: stack scanning
19  phantomjs + 0x18c1f07
    rip = 0x0000000001cc1f08   rsp = 0x00007f6926728db0
    Found by: stack scanning
20  phantomjs + 0x17d1765
    rip = 0x0000000001bd1766   rsp = 0x00007f6926728e10
    Found by: stack scanning
21  phantomjs + 0x17d4631
    rip = 0x0000000001bd4632   rsp = 0x00007f6926728e60
    Found by: stack scanning
22  libpthread-2.15.so + 0x7e99
    rip = 0x00007f6928846e9a   rsp = 0x00007f6926728eb0
    Found by: stack scanning

Thread 3
 0  libc-2.15.so + 0xed033
    rbx = 0x0000000000000200   r12 = 0x0000000004ac4f60
    r13 = 0x0000000004ac5040   r14 = 0x0000000004ac55d0
    r15 = 0x00007f6924ec1da0   rip = 0x00007f6927d5b033
    rsp = 0x00007f6924ec1d80   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  phantomjs + 0x4d345
    rip = 0x000000000044d346   rsp = 0x00007f6924ec1d90
    Found by: stack scanning
 2  phantomjs + 0xc0007e
    rip = 0x000000000100007f   rsp = 0x00007f6924ec1e50
    Found by: stack scanning
 3  libpthread-2.15.so + 0x7e99
    rip = 0x00007f6928846e9a   rsp = 0x00007f6924ec1eb0
    Found by: stack scanning

Thread 4
 0  libpthread-2.15.so + 0xbd84
    rbx = 0x0000000004ac55a0   r12 = 0x00007fff2efbb4a0
    r13 = 0x0000000004ac4f60   r14 = 0x0000000000000000
    r15 = 0x0000000004ac5040   rip = 0x00007f692884ad84
    rsp = 0x00007f68dfffc9f0   rbp = 0x00007f68c80008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x4d8e7
    rip = 0x000000000044d8e8   rsp = 0x00007f68dfffca20
    Found by: stack scanning

Thread 5
 0  libpthread-2.15.so + 0xbd84
    rbx = 0x0000000004ac55a0   r12 = 0x00007fff2efbb4a0
    r13 = 0x0000000004ac4f60   r14 = 0x0000000000000000
    r15 = 0x0000000004ac5040   rip = 0x00007f692884ad84
    rsp = 0x00007f68df7fb9f0   rbp = 0x00007f68ac0008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x4d8e7
    rip = 0x000000000044d8e8   rsp = 0x00007f68df7fba20
    Found by: stack scanning

Thread 6
 0  libpthread-2.15.so + 0xbd84
    rbx = 0x0000000004ac55a0   r12 = 0x00007fff2efbb4a0
    r13 = 0x0000000004ac4f60   r14 = 0x0000000000000000
    r15 = 0x0000000004ac5040   rip = 0x00007f692884ad84
    rsp = 0x00007f68deffa9f0   rbp = 0x00007f68b80008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x4d8e7
    rip = 0x000000000044d8e8   rsp = 0x00007f68deffaa20
    Found by: stack scanning

Thread 7
 0  libpthread-2.15.so + 0xbd84
    rbx = 0x0000000004ac55a0   r12 = 0x00007fff2efbb4a0
    r13 = 0x0000000004ac4f60   r14 = 0x0000000000000000
    r15 = 0x0000000004ac5040   rip = 0x00007f692884ad84
    rsp = 0x00007f68de7f99f0   rbp = 0x00007f68b40008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x4d8e7
    rip = 0x000000000044d8e8   rsp = 0x00007f68de7f9a20
    Found by: stack scanning

Thread 8
 0  libpthread-2.15.so + 0xbd84
    rbx = 0x0000000004ac55a0   r12 = 0x00007fff2efbb4a0
    r13 = 0x0000000004ac4f60   r14 = 0x0000000000000000
    r15 = 0x0000000004ac5040   rip = 0x00007f692884ad84
    rsp = 0x00007f68ddff89f0   rbp = 0x00007f68bc0008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x4d8e7
    rip = 0x000000000044d8e8   rsp = 0x00007f68ddff8a20
    Found by: stack scanning

Thread 9
 0  libpthread-2.15.so + 0xbd84
    rbx = 0x0000000004ac55a0   r12 = 0x00007f68d40008c8
    r13 = 0x0000000004ac4f60   r14 = 0x0000000000000000
    r15 = 0x0000000004ac5040   rip = 0x00007f692884ad84
    rsp = 0x00007f68dd7f79f0   rbp = 0x00007f68d40008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x4d8e7
    rip = 0x000000000044d8e8   rsp = 0x00007f68dd7f7a20
    Found by: stack scanning

Thread 10
 0  libpthread-2.15.so + 0xbd84
    rbx = 0x0000000004ac55a0   r12 = 0x00007fff2efbb4a0
    r13 = 0x0000000004ac4f60   r14 = 0x0000000000000000
    r15 = 0x0000000004ac5040   rip = 0x00007f692884ad84
    rsp = 0x00007f68dcff69f0   rbp = 0x00007f68c00008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x4d8e7
    rip = 0x000000000044d8e8   rsp = 0x00007f68dcff6a20
    Found by: stack scanning

Thread 11
 0  libpthread-2.15.so + 0xbd84
    rbx = 0x0000000004ac55a0   r12 = 0x00007fff2efbb4a0
    r13 = 0x0000000004ac4f60   r14 = 0x0000000000000000
    r15 = 0x0000000004ac5040   rip = 0x00007f692884ad84
    rsp = 0x00007f68dc7f59f0   rbp = 0x00007f68d00008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x4d8e7
    rip = 0x000000000044d8e8   rsp = 0x00007f68dc7f5a20
    Found by: stack scanning

Thread 12
 0  libpthread-2.15.so + 0xbd84
    rbx = 0x0000000004ac55a0   r12 = 0x00007fff2efbb4a0
    r13 = 0x0000000004ac4f60   r14 = 0x0000000000000000
    r15 = 0x0000000004ac5040   rip = 0x00007f692884ad84
    rsp = 0x00007f68dbff49f0   rbp = 0x00007f68c40008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x4d8e7
    rip = 0x000000000044d8e8   rsp = 0x00007f68dbff4a20
    Found by: stack scanning

Thread 13
 0  libpthread-2.15.so + 0xbd84
    rbx = 0x0000000004ac55a0   r12 = 0x00007fff2efbb4a0
    r13 = 0x0000000004ac4f60   r14 = 0x0000000000000000
    r15 = 0x0000000004ac5040   rip = 0x00007f692884ad84
    rsp = 0x00007f68db7f39f0   rbp = 0x00007f68cc0008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x4d8e7
    rip = 0x000000000044d8e8   rsp = 0x00007f68db7f3a20
    Found by: stack scanning

Thread 14
 0  libc-2.15.so + 0xed033
    rbx = 0x00007f68daff4d30   r12 = 0x00000000005d13f9
    r13 = 0x0000000000000027   r14 = 0x00007f68b0000a98
    r15 = 0x00007f68b0000d30   rip = 0x00007f6927d5b033
    rsp = 0x00007f68daff4b50   rbp = 0x00000000000c663d
    Found by: given as instruction pointer in context
 1  phantomjs + 0x18ea817
    rip = 0x0000000001cea818   rsp = 0x00007f68daff4b60
    Found by: stack scanning
 2  phantomjs + 0x1d13f8
    rip = 0x00000000005d13f9   rsp = 0x00007f68daff4b78
    Found by: stack scanning
 3  phantomjs + 0x1d13f8
    rip = 0x00000000005d13f9   rsp = 0x00007f68daff4b88
    Found by: stack scanning
 4  phantomjs + 0x1d13f8
    rip = 0x00000000005d13f9   rsp = 0x00007f68daff4ba8
    Found by: stack scanning
 5  phantomjs + 0x18ebbd6
    rip = 0x0000000001cebbd7   rsp = 0x00007f68daff4bf0
    Found by: stack scanning
 6  phantomjs + 0x18db0a6
    rip = 0x0000000001cdb0a7   rsp = 0x00007f68daff4c10
    Found by: stack scanning
 7  phantomjs + 0x17f3363
    rip = 0x0000000001bf3364   rsp = 0x00007f68daff4c20
    Found by: stack scanning
 8  linux-gate.so + 0x8a3
    rip = 0x00007fff2efff8a4   rsp = 0x00007f68daff4c30
    Found by: stack scanning
 9  phantomjs + 0x1d13f8
    rip = 0x00000000005d13f9   rsp = 0x00007f68daff4c38
    Found by: stack scanning
10  librt-2.15.so + 0x415c
    rip = 0x00007f6928a6015d   rsp = 0x00007f68daff4c60
    Found by: stack scanning
11  phantomjs + 0x18324f3
    rip = 0x0000000001c324f4   rsp = 0x00007f68daff4c70
    Found by: stack scanning
12  phantomjs + 0x1d13f8
    rip = 0x00000000005d13f9   rsp = 0x00007f68daff4c88
    Found by: stack scanning
13  phantomjs + 0x1d13f8
    rip = 0x00000000005d13f9   rsp = 0x00007f68daff4c98
    Found by: stack scanning
14  phantomjs + 0x18ec2dd
    rip = 0x0000000001cec2de   rsp = 0x00007f68daff4ca0
    Found by: stack scanning
15  phantomjs + 0x18323f8
    rip = 0x0000000001c323f9   rsp = 0x00007f68daff4cb0
    Found by: stack scanning
16  phantomjs + 0x18eb595
    rip = 0x0000000001ceb596   rsp = 0x00007f68daff4cc0
    Found by: stack scanning
17  phantomjs + 0x1d13f8
    rip = 0x00000000005d13f9   rsp = 0x00007f68daff4cd8
    Found by: stack scanning
18  phantomjs + 0x1d13f8
    rip = 0x00000000005d13f9   rsp = 0x00007f68daff4cf8
    Found by: stack scanning
19  phantomjs + 0x18ec681
    rip = 0x0000000001cec682   rsp = 0x00007f68daff4d30
    Found by: stack scanning
20  phantomjs + 0x18c1aa4
    rip = 0x0000000001cc1aa5   rsp = 0x00007f68daff4d80
    Found by: stack scanning
21  phantomjs + 0x18c2298
    rip = 0x0000000001cc2299   rsp = 0x00007f68daff4d90
    Found by: stack scanning
22  phantomjs + 0x18c1f07
    rip = 0x0000000001cc1f08   rsp = 0x00007f68daff4db0
    Found by: stack scanning
23  phantomjs + 0x17d1765
    rip = 0x0000000001bd1766   rsp = 0x00007f68daff4e10
    Found by: stack scanning
24  phantomjs + 0x17d4631
    rip = 0x0000000001bd4632   rsp = 0x00007f68daff4e60
    Found by: stack scanning
25  libpthread-2.15.so + 0x7e99
    rip = 0x00007f6928846e9a   rsp = 0x00007f68daff4eb0
    Found by: stack scanning

Thread 15
 0  libpthread-2.15.so + 0xc0fe
    rbx = 0x00007f68b0005580   r12 = 0x0000000000000002
    r13 = 0x00007f68da7f3dc0   r14 = 0xffffffffffffff92
    r15 = 0x0000000000000000   rip = 0x00007f692884b0fe
    rsp = 0x00007f68da7f3d40   rbp = 0x00007f68b0005850
    Found by: given as instruction pointer in context
 1  linux-gate.so + 0x9ec
    rip = 0x00007fff2efff9ed   rsp = 0x00007f68da7f3d70
    Found by: stack scanning
 2  phantomjs + 0x17d5346
    rip = 0x0000000001bd5347   rsp = 0x00007f68da7f3da0
    Found by: stack scanning
 3  phantomjs + 0x17c91ac
    rip = 0x0000000001bc91ad   rsp = 0x00007f68da7f3e20
    Found by: stack scanning
 4  phantomjs + 0x17d4631
    rip = 0x0000000001bd4632   rsp = 0x00007f68da7f3e60
    Found by: stack scanning
 5  libpthread-2.15.so + 0x7e99
    rip = 0x00007f6928846e9a   rsp = 0x00007f68da7f3eb0
    Found by: stack scanning

Thread 16
 0  libpthread-2.15.so + 0xc0fe
    rbx = 0x00007f68b0005580   r12 = 0x0000000000000001
    r13 = 0x00007f68d9deadc0   r14 = 0xffffffffffffff92
    r15 = 0x0000000000000000   rip = 0x00007f692884b0fe
    rsp = 0x00007f68d9dead40   rbp = 0x00007f68b000afd0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17d5346
    rip = 0x0000000001bd5347   rsp = 0x00007f68d9deada0
    Found by: stack scanning
 2  phantomjs + 0x17c91ac
    rip = 0x0000000001bc91ad   rsp = 0x00007f68d9deae20
    Found by: stack scanning
 3  phantomjs + 0x17d4631
    rip = 0x0000000001bd4632   rsp = 0x00007f68d9deae60
    Found by: stack scanning
 4  libpthread-2.15.so + 0x7e99
    rip = 0x00007f6928846e9a   rsp = 0x00007f68d9deaeb0
    Found by: stack scanning

Thread 17
 0  libpthread-2.15.so + 0xc0fe
    rbx = 0x00007f68b0005580   r12 = 0x0000000000000003
    r13 = 0x00007f68d95e9dc0   r14 = 0xffffffffffffff92
    r15 = 0x0000000000000000   rip = 0x00007f692884b0fe
    rsp = 0x00007f68d95e9d40   rbp = 0x00007f68b000cfb0
    Found by: given as instruction pointer in context
 1  linux-gate.so + 0x9ec
    rip = 0x00007fff2efff9ed   rsp = 0x00007f68d95e9d70
    Found by: stack scanning
 2  phantomjs + 0x17d5346
    rip = 0x0000000001bd5347   rsp = 0x00007f68d95e9da0
    Found by: stack scanning
 3  phantomjs + 0x17c91ac
    rip = 0x0000000001bc91ad   rsp = 0x00007f68d95e9e20
    Found by: stack scanning
 4  phantomjs + 0x17d4631
    rip = 0x0000000001bd4632   rsp = 0x00007f68d95e9e60
    Found by: stack scanning
 5  libpthread-2.15.so + 0x7e99
    rip = 0x00007f6928846e9a   rsp = 0x00007f68d95e9eb0
    Found by: stack scanning

Thread 18
 0  libpthread-2.15.so + 0xc0fe
    rbx = 0x00007f68b0005580   r12 = 0x0000000000000004
    r13 = 0x00007f68d8de8dc0   r14 = 0xffffffffffffff92
    r15 = 0x0000000000000000   rip = 0x00007f692884b0fe
    rsp = 0x00007f68d8de8d40   rbp = 0x00007f68b0015020
    Found by: given as instruction pointer in context
 1  linux-gate.so + 0x9ec
    rip = 0x00007fff2efff9ed   rsp = 0x00007f68d8de8d70
    Found by: stack scanning
 2  phantomjs + 0x17d5346
    rip = 0x0000000001bd5347   rsp = 0x00007f68d8de8da0
    Found by: stack scanning
 3  phantomjs + 0x17c91ac
    rip = 0x0000000001bc91ad   rsp = 0x00007f68d8de8e20
    Found by: stack scanning
 4  phantomjs + 0x17d4631
    rip = 0x0000000001bd4632   rsp = 0x00007f68d8de8e60
    Found by: stack scanning
 5  libpthread-2.15.so + 0x7e99
    rip = 0x00007f6928846e9a   rsp = 0x00007f68d8de8eb0
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x026cbfff  phantomjs  ???  (main)
0x7f68d83b0000 - 0x7f68d844afff  DejaVuSansCondensed-Bold.ttf  ???
0x7f68d844b000 - 0x7f68d84e8fff  DejaVuSansCondensed.ttf  ???
0x7f68d9dec000 - 0x7f68d9ff3fff  libnss_dns-2.15.so  ???
0x7f692404d000 - 0x7f692405efff  n019004l.pfb  ???
0x7f69240e1000 - 0x7f69242edfff  libnss_files-2.15.so  ???
0x7f69242ee000 - 0x7f6924507fff  libresolv-2.15.so  ???
0x7f692451e000 - 0x7f6924531fff  n019003l.pfb  ???
0x7f6925769000 - 0x7f692576ffff  gconv-modules.cache  ???
0x7f6926f2b000 - 0x7f6927187fff  libssl.so.1.0.0  ???
0x7f6927189000 - 0x7f692755ffff  libcrypto.so.1.0.0  ???
0x7f6927564000 - 0x7f692782cfff  locale-archive  ???
0x7f692782d000 - 0x7f6927a56fff  libexpat.so.1.5.2  ???
0x7f6927a57000 - 0x7f6927c6dfff  libz.so.1.2.3.4  ???
0x7f6927c6e000 - 0x7f6928027fff  libc-2.15.so  ???
0x7f692802d000 - 0x7f6928242fff  libgcc_s.so.1  ???
0x7f6928243000 - 0x7f692853efff  libm-2.15.so  ???
0x7f692853f000 - 0x7f6928829fff  libstdc++.so.6.0.16  ???
0x7f692883f000 - 0x7f6928a57fff  libpthread-2.15.so  ???
0x7f6928a5c000 - 0x7f6928c63fff  librt-2.15.so  ???
0x7f6928c64000 - 0x7f6928e67fff  libdl-2.15.so  ???
0x7f6928e68000 - 0x7f692909dfff  libfontconfig.so.1.4.4  ???
0x7f692909e000 - 0x7f6929339fff  libfreetype.so.6.8.0  ???
0x7f692933a000 - 0x7f692935bfff  ld-2.15.so  ???
0x7f69294ea000 - 0x7f69294eafff  c05880de57d1f5e948fdfacc138775d9-le64.cache-3  ???
0x7f69294eb000 - 0x7f69294f3fff  945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-3  ???
0x7f69294f4000 - 0x7f69294f5fff  99e8ed0e538f840c565b6ed5dad60d56-le64.cache-3  ???
0x7f69294f6000 - 0x7f69294f9fff  2cd17615ca594fa2959ae173292e504c-le64.cache-3  ???
0x7f69294fa000 - 0x7f69294fafff  e7071f4a29fa870f4323321c154eba04-le64.cache-3  ???
0x7f69294fb000 - 0x7f69294fbfff  0d8c3b2ac0904cb8a57a757ad11a4a08-le64.cache-3  ???
0x7f69294fc000 - 0x7f6929501fff  a755afe4a08bf5b97852ceb7400b47bc-le64.cache-3  ???
0x7f6929502000 - 0x7f692950afff  6d41288fd70b0be22e8c3a91e032eec0-le64.cache-3  ???
0x7f692950b000 - 0x7f692951afff  04aabc0a78ac019cf9454389977116d2-le64.cache-3  ???
0x7f692951b000 - 0x7f692951dfff  385c0604a188198f04d133e54aba7fe7-le64.cache-3  ???
0x7f692951e000 - 0x7f692951efff  4794a0821666d79190d59a36cb4f44b5-le64.cache-3  ???
0x7f692951f000 - 0x7f6929521fff  8801497958630a81b71ace7c5f9b32a8-le64.cache-3  ???
0x7f6929522000 - 0x7f6929526fff  3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-3  ???
0x7f6929527000 - 0x7f6929527fff  56cf4f4769d0f4abc89a4895d7bd3ae1-le64.cache-3  ???
0x7f6929528000 - 0x7f6929528fff  b9d506c9ac06c20b433354fa67a72993-le64.cache-3  ???
0x7f6929529000 - 0x7f692952dfff  b47c4e1ecd0709278f4910c18777a504-le64.cache-3  ???
0x7f692952e000 - 0x7f692953dfff  d52a8644073d54c13679302ca1180695-le64.cache-3  ???
0x7f6929553000 - 0x7f6929555fff  e13b20fdb08344e0e664864cc2ede53d-le64.cache-3  ???
0x7f6929556000 - 0x7f6929559fff  7ef2298fde41cc6eeb7af42e48b7d293-le64.cache-3  ???
0x7fff2efff000 - 0x7fff2effffff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
