### ISSUE TITLE
PhantomJS1.9.2 - Phantomdriver 1.0.4 crash on mac. 

### ISSUE THREAD

**Issue by Karim-Nabli** [ariya/phantomjs#11799]
When I create the webDriver object like : 
 
_log.info("Launching a Headless PhantomJS browser");
                Capabilities caps = new DesiredCapabilities();
                ((DesiredCapabilities) caps).setJavascriptEnabled(true);                
                ((DesiredCapabilities) caps).setCapability("takesScreenshot", true);  
                File phantomjs = new File( automationContext.getString("webdriver.phantom.driver"));
                if(phantomjs.exists() && phantomjs.isFile()){
                	_log.info("PhantomJs webdriver found:"+phantomjs.getAbsolutePath());
                }else{
                	_log.error("unable to locate the phantomjs webdriver.\n"
                			+ "Read readme.md for more detaisl.");
                	System.exit(-1);
                }
                ((DesiredCapabilities) caps).setCapability(
                		PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY,
                		phantomjs.getAbsolutePath());
                webDriver = new PhantomJSDriver(caps);

And try webDriver.get("http://www.google.com")

I get: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/9E5E1976-0E8A-4330-9209-3A8899957751.dmp

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
