### ISSUE TITLE
PhantomJS Crash - but - weirdly works when alternating between 1.3 and 1.9.2 

### ISSUE THREAD

**Issue by parsonss** [ariya/phantomjs#11800]
I am using phantom 1.9.2 as downloaded from the site for the Windows platform.

I am also testing this problem with phantom 1.3.

Here is the script I am trying to execute:

````
var page = require('webpage').create();

page.open("https://www.hertz.co.uk", function(status)
{
	console.log("I am here");
	phantom.exit();
});
````

When I run this script on the command line (using no command line arguments) using Phantom 1.9.2 it works fine, and I get the message "I am here".

However, If I run exactly the same script again I get the usual "PhantomJS has crashed" message.

From this point on it does not matter how many times I run the script it will always fail with the same error.

Now for the weird bit.....

If I now run the same script using Phantom 1.3 it works first time.

Run it again with phantom 1.3 and it fails with a critical error (dialog pops up) and this will continue to happen every time.

Try 1.9.2 again and it works!!!

In fact - If you run the script using 1.9.2 then 1.3 then 1.9.2 then 1.3 etc etc etc you never see the problem.

I cannot find any help on how to retrieve the stacktrace for a windows installation (I am using Window 7 64 bit btw) so have attached the crash dump file instead.

I hope someone can shed some light on the issue.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
