### ISSUE TITLE
[bug] CLI param webdriver

### ISSUE THREAD

**Issue by alekciy** [ariya/phantomjs#11801]
IP addr set in webdriver command line option not work in Ubuntu 12.04 LTS x86_64. Example:

[alekciy@phantom_test]$ phantomjs --ignore-ssl-errors=true --webdriver=127.0.0.1:8910 &
[1] 21591
[alekciy@phantom_test]$ PhantomJS is launching GhostDriver...
[INFO  - 2013-11-29T14:31:32.581Z] GhostDriver - Main - running on port 8910

[alekciy@phantom_test]$ netstat -lnap | grep phantom
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:8910            0.0.0.0:*               LISTEN      21591/phantomjs 
[alekciy@phantom_test]$

**Comment by alekciy** [comment]
Phantom not usered IP adress:

alex@SUNDUKOV:~$ strace -o ~/strace.log -s 2000 ~/phantomjs --load-images=false --webdriver=127.0.1.1:8910
[INFO  - 2015-03-11T12:20:13.529Z] GhostDriver - Main - running on port 8910
^C
alex@SUNDUKOV:~$ grep bind ~/strace.log | grep 8910
bind(8, {sa_family=AF_INET, sin_port=htons(8910), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
alex@SUNDUKOV:~$ ~/phantomjs -v
2.0.0

**Comment by ariya** [comment]
Can you first check with the Ghost Driver project?

**Comment by alekciy** [comment]
Confirm. It is GhostDriver bug.
