### ISSUE TITLE
element.validationMessage is empty

### ISSUE THREAD

**Issue by binarykitchen** [ariya/phantomjs#11809]
It looks like PhantomJS comes without native validation messages.

For example I have this:

```
var self = this;

this.form.addEventListener('invalid', function(e) {
    // I do not want to see the ugly native validation popups
    e.preventDefault();

    self.updateHintFor(e.target);

}, true);
```

and further down I customise the way validation messages are rendered. All I am doing is to grab the default error text from the browser like that:

```
updateHintFor: function(element) {
    ...
    text = element.validationMessage;

   // render that text in DOM my way but in PhantomJS it's an empty string = fail
}
```

Looking at https://github.com/ariya/phantomjs/blob/master/src/qt/src/3rdparty/webkit/Source/WebCore/html/ValidationMessage.cpp it seems to be incomplete, am I right?

Any clues?

**Comment by dominicbarnes** [comment]
This appears to still be broken as of v2.1.1, not sure if it was fixed in 2.0+ and has just regressed or if it was never actually fixed.
