### ISSUE TITLE
CSS3 Columns Support Missing with PDF

### ISSUE THREAD

**Issue by slominskir** [ariya/phantomjs#11821]
The CSS3 Columns feature only works with images, not PDF.  It would be a nice enhancement if this also worked when exporting a PDF.  See discussion in mailing list:

https://groups.google.com/forum/#!searchin/phantomjs/columns/phantomjs/y7pZrl27qDQ/cyhVXwXijGAJ

**Comment by sethvoltz** [comment]
Ditto on this being very useful.

**Comment by colemip** [comment]
I'd also love to see this issue addressed.

**Comment by paolocorti** [comment]
+1

**Comment by miso440** [comment]
+1

**Comment by mheesters** [comment]
+1

**Comment by zackw** [comment]
This is a feature request that would need to be implemented inside Webkit.  We do not have the manpower to make this happen ourselves.  It _may_ have already been implemented in 2.0 or the coming-Real-Soon 2.1; if someone who needs this could test the latest development sources and report here whether it _has_ been implemented, that would be great.

However, if it hasn't been implemented, we're going to have to ask y'all to work with the Webkit project directly to get it implemented.

**Comment by maroun-baydoun** [comment]
+1

**Comment by caleblloyd** [comment]
I just tried in PhantomJS 2.1, still doesn't seem to be working.

**Comment by Andargor** [comment]
2.1.1 does not support this yet.

**Comment by Benew** [comment]
+1

**Comment by IoannesPaulus** [comment]
+1

**Comment by tamdao** [comment]
+1

**Comment by mskrzypek** [comment]
+1

**Comment by ZwaarContrast** [comment]
+1

**Comment by Losses** [comment]
+1

**Comment by pistacchio** [comment]
+1

**Comment by oorooroot** [comment]
+1
But if it works with image output, is it still webkit problem?

**Comment by aggiejosh06** [comment]
+1

**Comment by andyburton** [comment]
+1

**Comment by woutersamaey** [comment]
+1

**Comment by raghu185** [comment]
+1
Its been more then since issue reported has there been any update on this/

**Comment by dbburgess** [comment]
It looks to me as if that's unlikely. With the release of [headless Chrome](https://news.ycombinator.com/item?id=14101233), it looks like PhantomJS (in it's current form, at least) [will not be](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE) developed or maintained much further.

**Comment by Andargor** [comment]
I've done some testing with the 2.5 beta, and it seems to finally support CSS columns. However, I did not extensively test all use cases, and the 2.5 beta is in a pretty early and bugged state at this time. Binaries: https://bitbucket.org/ariya/phantomjs/downloads/    More info: https://groups.google.com/forum/#!topic/phantomjs/AefOuwkgBh0

No sources yet sadly. Praying to the Vitallium God. :)

**Comment by Benew** [comment]
+1
