### ISSUE TITLE
JMeter does not run PhantomJS test case

### ISSUE THREAD

**Issue by OlivierBOEL** [ariya/phantomjs#11832]
Hello,

Please forgive me in advance : I'm a newcomer in GitHub and phantomjs.
My problem is simple : I've created a JUnit Test Case that uses the jphantomjs driver but JMeter just seems to ignore my test ; it is not executed (see code and log below). However, if I enable the HtmlUnitDriver (instead of PhantomJSDriver), the test runs successfully.
Any help would be appreciated.

TIA,

Olivier

JUnit Test Case that uses the jphantomjs
package migration;

import java.util.regex.Pattern;
import java.util.concurrent.TimeUnit;
import org.junit._;
import static org.junit.Assert._;
import static org.hamcrest.CoreMatchers._;
import org.openqa.selenium._;
import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.openqa.selenium.phantomjs.PhantomJSDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.Select;

public class Pjcms {
  private WebDriver driver;
  private String baseUrl;
  private boolean acceptNextAlert = true;
  private StringBuffer verificationErrors = new StringBuffer();

  @Before
  public void setUp() throws Exception {
//    driver = new FirefoxDriver();
//  driver = new HtmlUnitDriver(true); // true = load Javascript files
    System.setProperty("phantomjs.binary.path", "C:/phantomjs-1.9.2-windows/phantomjs.exe"); // Adapt this path to your configuration
    driver = new PhantomJSDriver(new DesiredCapabilities());
    baseUrl = "http://pjcms-dev:8080/";
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
  }

  @Test
  public void testPjcms() throws Exception {
    driver.get(baseUrl + "/pjcms/");
    driver.findElement(By.name("pjcms_username")).clear();
    driver.findElement(By.name("pjcms_username")).sendKeys("karolews");
    driver.findElement(By.name("pjcms_password")).clear();
    driver.findElement(By.name("pjcms_password")).sendKeys("Serapis01");
    driver.findElement(By.cssSelector("input.largeButton")).click();
    driver.findElement(By.cssSelector("li.myprofile > div.subtitle > a")).click();
    driver.findElement(By.name("pjCmsUser.bfax")).clear();
    driver.findElement(By.name("pjCmsUser.bfax")).sendKeys("16:23");
    driver.findElement(By.cssSelector("input.largeButton")).click();
    driver.findElement(By.linkText("Log out")).click();
  }

  @After
  public void tearDown() throws Exception {
    driver.quit();
    String verificationErrorString = verificationErrors.toString();
    if (!"".equals(verificationErrorString)) {
      fail(verificationErrorString);
    }
  }

  private boolean isElementPresent(By by) {
    try {
      driver.findElement(by);
      return true;
    } catch (NoSuchElementException e) {
      return false;
    }
  }

  private boolean isAlertPresent() {
    try {
      driver.switchTo().alert();
      return true;
    } catch (NoAlertPresentException e) {
      return false;
    }
  }

  private String closeAlertAndGetItsText() {
    try {
      Alert alert = driver.switchTo().alert();
      String alertText = alert.getText();
      if (acceptNextAlert) {
        alert.accept();
      } else {
        alert.dismiss();
      }
      return alertText;
    } finally {
      acceptNextAlert = true;
    }
  }
}
JMeter log
2013/12/13 16:09:52 INFO  - jmeter.engine.StandardJMeterEngine: Listeners will be started after enabling running version 
2013/12/13 16:09:52 INFO  - jmeter.engine.StandardJMeterEngine: To revert to the earlier behaviour, define jmeterengine.startlistenerslater=false 
2013/12/13 16:09:52 INFO  - jmeter.engine.StandardJMeterEngine: Running the test! 
2013/12/13 16:09:52 INFO  - jmeter.gui.util.JMeterMenuBar: setRunning(true,_local_) 
2013/12/13 16:09:52 INFO  - jmeter.engine.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group 
2013/12/13 16:09:52 INFO  - jmeter.engine.StandardJMeterEngine: Starting 1 threads for group Thread Group. 
2013/12/13 16:09:52 INFO  - jmeter.engine.StandardJMeterEngine: Thread will continue on error 
2013/12/13 16:09:52 INFO  - jmeter.threads.ThreadGroup: Starting thread group number 1 threads 1 ramp-up 1 perThread 1000.0 delayedStart=false 
2013/12/13 16:09:52 INFO  - jmeter.threads.JMeterThread: jmeterthread.startearlier=true (see jmeter.properties) 
2013/12/13 16:09:52 INFO  - jmeter.threads.JMeterThread: Running PostProcessors in forward order 
2013/12/13 16:09:52 INFO  - jmeter.threads.ThreadGroup: Started thread group number 1 
2013/12/13 16:09:52 INFO  - jmeter.engine.StandardJMeterEngine: All thread groups have been started 
2013/12/13 16:09:52 INFO  - jmeter.threads.JMeterThread: Thread started: Thread Group 1-1 
2013/12/13 16:09:52 INFO  - jmeter.protocol.java.sampler.JUnitSampler: String constructor:: migration.Pjcms.<init>(java.lang.String) 
2013/12/13 16:09:52 INFO  - jmeter.threads.JMeterThread: Thread finished: Thread Group 1-1 
2013/12/13 16:09:52 INFO  - jmeter.engine.StandardJMeterEngine: Notifying test listeners of end of test 
2013/12/13 16:09:52 INFO  - jmeter.gui.util.JMeterMenuBar: setRunning(false,_local_)

**Comment by vladimir-vernus** [comment]
Hi, I have a similar problem, tests are run phantomjs falling, do not tell me what could be the problem?

**Comment by vijay-hexaview** [comment]
Faced the same issue: Found that it was caused due to multiple phantomjsdriver.jar files in /bin folder
