### ISSUE TITLE
Add render to Blob and ArrayBuffer

### ISSUE THREAD

**Issue by Downchuck** [ariya/phantomjs#11835]
Allow the render() option to output to a Blob object and/or an ArrayBuffer object.
ArrayBuffers are in memory; blob is managed by whatever webkit wants to do, though it's typically going to wind up in a temp dir.

**Comment by gabrielcaires** [comment]
+1

**Comment by zackw** [comment]
This is essentially the same as #12084 and therefore I am going to close it as a duplicate.  Further discussion of this feature should take place in that bug report and/or pull request #13345.
