### ISSUE TITLE
Crash on Ubuntu x64 when loading certain pages

### ISSUE THREAD

**Issue by ssafejava** [ariya/phantomjs#11839]
The occasional page will crash, every time (Ubuntu 13.10 x86_64). PhantomJS 1.9.2.

I'm running PhantomJS concurrently (usually 4 at a time).

[Crash dump](https://gist.github.com/ssafejava/bbc10f95c7ee9c344992)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
