### ISSUE TITLE
Crash when trying to enable debugger along webdriver

### ISSUE THREAD

**Issue by nadav-dav** [ariya/phantomjs#11862]
im using **Ghostdriver** + **Scala** to create a _phantomJs_ instance that enabled remote debugging: **--remote-debugger-port=9000**

but unfortunately it fails and crash every time :(

dumpfile can be found [here](https://docs.google.com/a/wix.com/file/d/0B47-jsUvx3qGdGhpMHhISEhEd3c/edit)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (233/200 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:50655 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkRA-003NhW-RE
	for andre@castonguay.org; Mon, 11 Apr 2016 18:36:05 -0400
Date: Mon, 11 Apr 2016 15:35:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460414124;
	bh=Ej0mdWQPEk2bsGrvA4TtETJ4gVLQW1cE7GMfb6nwDJI=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=mWXUaZkxL2z1PsT0X2o4tU1yME/q6muP/X6icpNxTqpVoHMReS8KEePUjAupl81Dj
	 XnHdhHqmelmATCSHFf7zHHnoTse8el0XjHlOIeVS/n1ndz4LErciWv2JJVUEgNpWXy
	 vcGBZK3XxGWrYvBQFrtSgn9vs/q1Y+RpefDmmHFQ=

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (234/200 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:50797 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkRB-003Ni2-4A
	for andre@castonguay.org; Mon, 11 Apr 2016 18:36:05 -0400
Date: Mon, 11 Apr 2016 15:35:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460414124;
	bh=dK2jZ8wOuLgA/ggzkFY6wL62zpJvs+jig649I9knRNM=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=e+bcdLShNKDiPZ3wWwD3GLvz6D7W1Sr1dwf4ACX1TL6iOvZ/gZBnZkJ3OC2bMPfFz
	 I0A9pZW4l0iinCFVEebAsywnIurjTl0PCnCnhRggSevNZ5cTtEuP/x0TM2nA/DWS4T
	 8JrBcUPf/0gXj1m28vuPbrS40RWU0dJhgYHJwfd4=
