### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by laurencecao** [ariya/phantomjs#11865]
CentOS release 5.7 (Final)
Linux server14 2.6.18-274.el5 #1 SMP Fri Jul 22 04:43:29 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux

what should i do if dumps file needs upload?

-------------------------------------
I upload dump file here, thanks
http://speedy.sh/DYSqQ/7411bc2b-0e07-b58c-169a59f4-0d5f780c.dmp.gz

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (232/200 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:49086 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkR8-003Nfb-W6
	for andre@castonguay.org; Mon, 11 Apr 2016 18:36:03 -0400
Date: Mon, 11 Apr 2016 15:35:22 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460414122;
	bh=3P+n1qghITR10C96TV2u37+rE0EaTsW+WMDKfoBtu5E=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=j9j+r+Y3Mkc6iWizBdhtr/8dvzbWfPrOG8TWO0f6mMRQQyVa7IvTp1xg4gcUIe6wZ
	 1Hij+6KKO2BeS4xezBg1+2FhHNLMZj3ehEVbKgFeThGgTUkBJCqrufGVAMFtas1Cov
	 SyZT/K72GnLYfbLGMEetirTIKA6yE+ZWNQBKckLY=

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (238/200 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:41945)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-cf68-andre=castonguay.org@sgmail.github.com>)
	id 1apkRs-003OkH-Le
	for andre@castonguay.org; Mon, 11 Apr 2016 18:36:49 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=qkm14N/MZMrPb6Fwm4GbPKWl81I=; b=Efsj4SZN24QdM61/
	jFx6GoW0zXXWeq7BjnFQADbn1gbu9B3MSApENcuyR1PQaQ1njYRs4xFJioBIBIyX
	xtlp10St8Fu4EFG/mSv2gQvdS+kJYOQICpfCOVt8XMwu/9LoMlabP2KO0RwONluU
	KWOQYrPCDU3V68UYwhy9oppSmmA=
Received: by filter0551p1mdw1.sendgrid.net with SMTP id filter0551p1mdw1.18345.570C26AB38
        2016-04-11 22:35:23.471199872 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id 1LFjQPNuR7uIkDtyWWYtNg
	for <andre@castonguay.org>; Mon, 11 Apr 2016 22:35:23.242 +0000 (UTC)
Date: Mon, 11 Apr 2016 15:35:23 -0700
