### ISSUE TITLE
Different results (screenshot) depending on Environment

### ISSUE THREAD

**Issue by novito** [ariya/phantomjs#11871]
I have the following script:

``` javascript
var page = require('webpage').create();
var args = require('system').args;
var viewportSize = {width: 1400, height: 768};

var url = args[1];
var destination = args[2];
page.viewportSize = viewportSize;

page.open(url, function() {
   page.render(destination);
   phantom.exit();
});
```

When launching this script from Heroku I get the following image:

Heroku: http://postimg.org/image/lbvpesnpx/full/
Local (Ubuntu 12.04): http://postimg.org/image/euwyw1q2z/full/

Notice the differences between the fonts, and also with the fact that the top left logo is moved down 100px in Heroku environment.

When checking the version of PhantomJS, in both environment I get 1.9.2.

Shouldn't the result be the same if the Phantom versions are the same?

**Comment by xuanchien** [comment]
I wonder if there is any update for this issue. In my case, I am using phantom 2.1.1 on both local and Heroku. But the HTML returns by Heroku is always different to when running with my local phantomjs. No JS is executed in case I run phantomjs on Heroku.

**Comment by yanivlllev** [comment]
+1

I'm having the same issue here...  have the same phantom js version and the same code... 
the desirable output PDF on local environment is different than the live one on the server...
![1st_frame](https://cloud.githubusercontent.com/assets/12447235/15098042/97e57c8e-1539-11e6-90e5-a42004027beb.jpg)

**Comment by evertondanilo** [comment]
I'm also having the same issue, any solution?
