### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by rrrus** [ariya/phantomjs#11876]
Platform: Mac OS X 10.9.1
Phantom: 1.9.2 from MacPorts
Driver/wrapper: phantomjs-node 0.5.4, node.js 0.10.22 

Phantom works pretty well when working with a single page at a time, but when i create multiple pages running at the same time, it will occasionally crash, about 1 out of 10 times in my current test case, which creates a total of 32 pages, each loads a site page, evaluate is called to extract html as setup by the page's running javascript, then the pages are closed().  This setup limits to 16 concurrent pages and queues the rest.  I've seen the crashes with as few as 2 concurrent pages.

I have a pile of crashlogs I've symbolized:  

https://dl.dropboxusercontent.com/u/82811377/phantom-symbolized.zip

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (227/200 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:43106 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkQY-003MpP-Oa
	for andre@castonguay.org; Mon, 11 Apr 2016 18:35:27 -0400
Date: Mon, 11 Apr 2016 15:34:46 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460414086;
	bh=XJn954jsunoIdLftATHd7hDWDHJE7tSIYtq+xPLQw7k=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=vFYQwsUPng228i22fIqqMI2RiIawnwjkSOJUupTOKxIuKbEFOF0w1F7v0Ihu93swu
	 kkhroLuHftaOExTPKj6E1y7sbB/mzuhSfrfT87VdBs6vwCqi3u3stRyt5y14YBnWLS
	 kDX1/+83sFjHnbavpUi2Qoxn5oYgPO2zg8tgpSVE=

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (228/200 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:19651)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-cf68-andre=castonguay.org@sgmail.github.com>)
	id 1apkQd-003Mtv-4l
	for andre@castonguay.org; Mon, 11 Apr 2016 18:35:31 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=60wHsJ2SB5hUhB78MS39ZYt3LX8=; b=O206de1E397qsEzZ
	UxNsqrn9yTHrYAgmVWh5R6KKvd3ML1nBO3Vq7658MqwmMPjayEqA30vhJbZY0n/f
	WKvazJBqyUuTr4zVjXNMmTCt9KSpOFvleOBT7O9RAvEk71sDuN1ZP37ccUiOX5hg
	6v2Md9a1fOV+9ZTQgpB3tEgMJG8=
Received: by filter0419p1mdw1.sendgrid.net with SMTP id filter0419p1mdw1.22863.570C268667
        2016-04-11 22:34:46.942915044 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id zELLemyQSL2O9uF9MxeUZQ
	for <andre@castonguay.org>; Mon, 11 Apr 2016 22:34:46.831 +0000 (UTC)
Date: Mon, 11 Apr 2016 15:34:46 -0700
