### ISSUE TITLE
Header 'content-type' on XHR GET request is removed

### ISSUE THREAD

**Issue by jkrugler** [ariya/phantomjs#11885]
When loading a page that makes an XHR GET request that sets a 'content-type' header in phantom the header is removed from the request.  Loading the same page in Chrome or Firefox does not remove the header from the request.

For example:
![phantom-xxxxx](https://f.cloud.github.com/assets/1452426/1872614/06ed3bf6-78a9-11e3-81fa-aba8d0ac6bf2.png)

Phantom makes the request with the 'foobar' header and without the 'content-type' header.

Here is the same page loaded in a browser:
![phantom-11885-2](https://f.cloud.github.com/assets/1452426/1872690/8ed2361a-78aa-11e3-8dc0-9b87850e6e78.png)

phantomjs --version
1.9.2

**Comment by jsenjoy** [comment]
It stuck me to solve one problem, because server gave back 415 for the content-type. Any good solution?
