### ISSUE TITLE
phantom crash: code -1073740791

### ISSUE THREAD

**Issue by fjhub** [ariya/phantomjs#11883]
I am using phantomjs version 1.9.2 on Windows 7.

I get this crash code when I try rendering an SVG file using node.js.  I am using node module jsgui-node-render-svg which uses node-phantom.  I performed a search on the entire disk for anything ending in .dmp but did not find anything that would have been tied to phantoms based on the sample .dmp file name or with phantoms in the name.

I have been able to render many SVG files but have come across a few cases where I get this message.  I believe it is tied to one or more of the "x", "y", "width" or "height" values of an SVG image element as I can modify the value and re-render the SVG file and it renders fine.

An example image tag which causes the crash (where I've excluded the delimiters):

image xlink:href="http://localhost:8000/foo.jpg" class="someClass" src="http://localhost:8000/foo.jpg" id="someId" height="2475" width="3719.765166" y="0" x="-229"

And if I change the width from "3719.765166" to "3718.765166" and re-render, the SVG file is rendered fine.

thank you

I did not include the fact that the SVG width is 2925 and height is 2475.  A couple more data points.  I did not get a crash with the preserveAspectRatio="none" (on the image tag).  I also ran phantomjs.exe via command line using rasterize.js and the resulting command did not crash--with or without the preserveAspcetRastio attribute.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (225/200 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:33261 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkQH-003MMw-E8
	for andre@castonguay.org; Mon, 11 Apr 2016 18:35:10 -0400
Date: Mon, 11 Apr 2016 15:34:28 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460414069;
	bh=vqgOAvyqESpke1hRZCgXnenXojuRzrUuTqT6RTc8BpA=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=k5md9SBtir7x1FOoy6bblEsEsabWDBqBlXdHcIdH/+xMr6YH+Lx7TIqcjMW+RXXqm
	 vRpmb0Hw6sA/QBv61NDISDhw89fCiB/50rb9Q92CXl2vmYSN5t2ehXmA+UCIVoNCeM
	 iaSgmHf3hp0H2TfVYN/rzpiVyX2sJejpTPFOmGdA=

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (226/200 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:33451 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkQH-003MO9-OD
	for andre@castonguay.org; Mon, 11 Apr 2016 18:35:10 -0400
Date: Mon, 11 Apr 2016 15:34:29 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460414069;
	bh=2g8BNotsN1s7pmu9aR8uizYESi6rbfGJi4Si0Mj69bo=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Un1fe8x1kUPBHMFWwLk9SM0Q783vVj6likfKzXkFXHfjZK1dSmbTFjsm2ZCSpi2B4
	 mmkNAb0UrMRoAfKvF5KH6AwLkuO3fzYLJo3kBQrKyqwgMFJ5R4cnch8l6f/kqKdRED
	 A58v1DCgPgK48OW4f+tR9yVqP81eVX+QLZOU9RRM=
