### ISSUE TITLE
PhantomJS 1.9.2 crash running via Protractor/Selenium on Debian

### ISSUE THREAD

**Issue by tfnico** [ariya/phantomjs#11909]
I'm testing an angular app using Protractor with PhantomJS. 

This happens about every 4th time or so I run the test. 

I'm running on Debian 6.0.8 with PhantomJS 1.9.2.

<pre>
12:06:09.319 INFO - Executing: [find element: By.id: importServerFileBtn] at URL: /session/ad8b0db2-89d0-45c1-993d-ce139a23a5ec/element)
12:06:09.337 INFO - Done: /session/ad8b0db2-89d0-45c1-993d-ce139a23a5ec/element
12:06:09.348 INFO - Executing: [execute async script: return (function () {
  var el = document.querySelector(arguments[0]);
  var callback = arguments[1];
  try {
    angular.element(el).injector().get('$browser').
        notifyWhenNoOutstandingRequests(callback);
  } catch (e) {
    callback(e);
  }
}).apply(null, arguments);, [body]] at URL: /session/ad8b0db2-89d0-45c1-993d-ce139a23a5ec/execute_async)
12:06:09.355 INFO - Done: /session/ad8b0db2-89d0-45c1-993d-ce139a23a5ec/execute_async
12:06:09.365 INFO - Executing: [click: 6 [[PhantomJSDriver: phantomjs on LINUX (daa28790-81c2-11e3-b990-51de5eea2349)] -> id: importServerFileBtn]] at URL: /session/ad8b0db2-89d0-45c
1-993d-ce139a23a5ec/element/6/click)
12:06:09.404 INFO - Done: /session/ad8b0db2-89d0-45c1-993d-ce139a23a5ec/element/6/click
12:06:09.509 INFO - Executing: [get: about:blank] at URL: /session/ad8b0db2-89d0-45c1-993d-ce139a23a5ec/url)
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/is
sues/new with the crash dump file attached: /tmp/6791aacc-b6a8-68fc-1979d8a9-30e0bbb6.dmp
12:06:11.619 INFO - Executing: [delete session: ad8b0db2-89d0-45c1-993d-ce139a23a5ec] at URL: /session/ad8b0db2-89d0-45c1-993d-ce139a23a5ec)

Attempting to shut down selenium nicely
12:08:43.024 INFO - Checking Resource aliases
12:08:43.026 INFO - Command request: shutDownSeleniumServer[, ] on session null
12:08:43.026 INFO - Shutdown command received
12:08:43.027 INFO - initiating shutdown
12:08:43.027 INFO - Got result: OK on session null
Selenium Standalone has exited with code 0
</pre>

Dump file is here: 

https://gist.github.com/tfnico/ded96ddf04e3edec4bc3

Here's the protractor/npm dependencies:

<pre>
├─┬ protractor@0.16.1
│ ├── adm-zip@0.4.3
│ ├─┬ glob@3.2.8
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.5.0
│ │   └── sigmund@1.0.0
│ ├── minijasminenode@0.2.7
│ ├─┬ optimist@0.6.0
│ │ ├── minimist@0.0.5
│ │ └── wordwrap@0.0.2
│ ├── saucelabs@0.1.1
│ └── selenium-webdriver@2.39.0
</pre>

Unfortunately, I cannot provide a simple code sample that recreates the problem. So, I won't be offended if you close this issue, as there seems to be plenty of other crash reports to look at. I just got the crash dump, and figured I'd post it somewhere.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
