### ISSUE TITLE
Segfault using phantomjs 1.9.0 with casperjs 1.0.3 (stack trace)

### ISSUE THREAD

**Issue by Alives** [ariya/phantomjs#11916]
Operating system: Linux
                  0.0.0 Linux 3.11.0-13-generic #20-Ubuntu SMP Wed Oct 23 07:38:26 UTC 2013 x86_64
CPU: amd64
     family 6 model 42 stepping 7
     4 CPUs

Crash reason:  SIGSEGV
Crash address: 0xb00000001

Thread 0 (crashed)
 0  phantomjs + 0x1685b76
    rbx = 0x00007fff0dcb1fc0   r12 = 0x00007fff0dcb1fb0
    r13 = 0x0000000000000001   r14 = 0x0000000002cd61a9
    r15 = 0x0000000000000000   rip = 0x0000000001a85b76
    rsp = 0x00007fff0dcb1f50   rbp = 0x0000000002e0af40
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1a055e8
    rip = 0x0000000001e055e9   rsp = 0x00007fff0dcb1f80
    Found by: stack scanning
 2  phantomjs + 0x3b7eda
    rip = 0x00000000007b7edb   rsp = 0x00007fff0dcb1fc0
    Found by: stack scanning
 3  phantomjs + 0x1a055e8
    rip = 0x0000000001e055e9   rsp = 0x00007fff0dcb1ff0
    Found by: stack scanning
 4  phantomjs + 0x5f6fac
    rip = 0x00000000009f6fad   rsp = 0x00007fff0dcb2030
    Found by: stack scanning
 5  phantomjs + 0x3eb0ff
    rip = 0x00000000007eb100   rsp = 0x00007fff0dcb2048
    Found by: stack scanning
 6  phantomjs + 0x5f4188
    rip = 0x00000000009f4189   rsp = 0x00007fff0dcb2050
    Found by: stack scanning
 7  phantomjs + 0x3df184
    rip = 0x00000000007df185   rsp = 0x00007fff0dcb2060
    Found by: stack scanning
 8  phantomjs + 0x3eb0ff
    rip = 0x00000000007eb100   rsp = 0x00007fff0dcb2068
    Found by: stack scanning
 9  phantomjs + 0x3eb186
    rip = 0x00000000007eb187   rsp = 0x00007fff0dcb2080
    Found by: stack scanning
10  phantomjs + 0x3eb0ff
    rip = 0x00000000007eb100   rsp = 0x00007fff0dcb2088
    Found by: stack scanning
11  phantomjs + 0x3df757
    rip = 0x00000000007df758   rsp = 0x00007fff0dcb20a0
    Found by: stack scanning
12  phantomjs + 0x3df443
    rip = 0x00000000007df444   rsp = 0x00007fff0dcb20f0
    Found by: stack scanning
13  phantomjs + 0x3a81dd
    rip = 0x00000000007a81de   rsp = 0x00007fff0dcb2140
    Found by: stack scanning
14  phantomjs + 0x3a837b
    rip = 0x00000000007a837c   rsp = 0x00007fff0dcb2180
    Found by: stack scanning
15  phantomjs + 0x3b404a
    rip = 0x00000000007b404b   rsp = 0x00007fff0dcb2210
    Found by: stack scanning
16  phantomjs + 0x3b8a41
    rip = 0x00000000007b8a42   rsp = 0x00007fff0dcb2230
    Found by: stack scanning
17  phantomjs + 0x3b8bab
    rip = 0x00000000007b8bac   rsp = 0x00007fff0dcb2270
    Found by: stack scanning
18  phantomjs + 0x3b887d
    rip = 0x00000000007b887e   rsp = 0x00007fff0dcb22d0
    Found by: stack scanning
19  phantomjs + 0x82f46
    rip = 0x0000000000482f47   rsp = 0x00007fff0dcb2310
    Found by: stack scanning
20  phantomjs + 0x25b2f
    rip = 0x0000000000425b30   rsp = 0x00007fff0dcb2330
    Found by: stack scanning
21  phantomjs + 0x16894a7
    rip = 0x0000000001a894a8   rsp = 0x00007fff0dcb2350
    Found by: stack scanning
22  phantomjs + 0x168b281
    rip = 0x0000000001a8b282   rsp = 0x00007fff0dcb2380
    Found by: stack scanning
23  phantomjs + 0x19dc8
    rip = 0x0000000000419dc9   rsp = 0x00007fff0dcb2410
    Found by: stack scanning
24  phantomjs + 0x119f0
    rip = 0x00000000004119f1   rsp = 0x00007fff0dcb2420
    Found by: stack scanning
25  phantomjs + 0x11a89
    rip = 0x0000000000411a8a   rsp = 0x00007fff0dcb2450
    Found by: stack scanning
26  phantomjs + 0x6b1ba
    rip = 0x000000000046b1bb   rsp = 0x00007fff0dcb2480
    Found by: stack scanning
27  libc-2.17.so + 0x3c173f
    rip = 0x00007f3e76e45740   rsp = 0x00007fff0dcb2488
    Found by: stack scanning
28  libc-2.17.so + 0x3c173f
    rip = 0x00007f3e76e45740   rsp = 0x00007fff0dcb24a0
    Found by: stack scanning
29  phantomjs + 0x6b62e
    rip = 0x000000000046b62f   rsp = 0x00007fff0dcb24e0
    Found by: stack scanning
30  phantomjs + 0x12a714
    rip = 0x000000000052a715   rsp = 0x00007fff0dcb24f0
    Found by: stack scanning
31  phantomjs + 0x135662
    rip = 0x0000000000535663   rsp = 0x00007fff0dcb2540
    Found by: stack scanning
32  phantomjs + 0x16ea9bf
    rip = 0x0000000001aea9c0   rsp = 0x00007fff0dcb2560
    Found by: stack scanning
33  phantomjs + 0xc92f8
    rip = 0x00000000004c92f9   rsp = 0x00007fff0dcb2620
    Found by: stack scanning
34  phantomjs + 0xcbfa1
    rip = 0x00000000004cbfa2   rsp = 0x00007fff0dcb2660
    Found by: stack scanning
35  phantomjs + 0xcb484
    rip = 0x00000000004cb485   rsp = 0x00007fff0dcb2680
    Found by: stack scanning
36  phantomjs + 0xcb30a
    rip = 0x00000000004cb30b   rsp = 0x00007fff0dcb2690
    Found by: stack scanning
37  phantomjs + 0xcbfa1
    rip = 0x00000000004cbfa2   rsp = 0x00007fff0dcb26a0
    Found by: stack scanning
38  phantomjs + 0x9a06dc
    rip = 0x0000000000da06dd   rsp = 0x00007fff0dcb2730
    Found by: stack scanning
39  phantomjs + 0xcbfa1
    rip = 0x00000000004cbfa2   rsp = 0x00007fff0dcb27b0
    Found by: stack scanning
40  phantomjs + 0xcb30a
    rip = 0x00000000004cb30b   rsp = 0x00007fff0dcb27d0
    Found by: stack scanning
41  phantomjs + 0xcb30a
    rip = 0x00000000004cb30b   rsp = 0x00007fff0dcb27e0
    Found by: stack scanning
42  phantomjs + 0xcbfa1
    rip = 0x00000000004cbfa2   rsp = 0x00007fff0dcb27f0
    Found by: stack scanning
43  phantomjs + 0xcbfa1
    rip = 0x00000000004cbfa2   rsp = 0x00007fff0dcb2810
    Found by: stack scanning
44  phantomjs + 0x16ea9bf
    rip = 0x0000000001aea9c0   rsp = 0x00007fff0dcb2828
    Found by: stack scanning
45  phantomjs + 0xcbfa1
    rip = 0x00000000004cbfa2   rsp = 0x00007fff0dcb28a0
    Found by: stack scanning
46  phantomjs + 0xcb30a
    rip = 0x00000000004cb30b   rsp = 0x00007fff0dcb28c0
    Found by: stack scanning
47  phantomjs + 0x9d6cc5
    rip = 0x0000000000dd6cc6   rsp = 0x00007fff0dcb28d0
    Found by: stack scanning
48  libc-2.17.so + 0x3c173f
    rip = 0x00007f3e76e45740   rsp = 0x00007fff0dcb28e0
    Found by: stack scanning
49  phantomjs + 0x9fb302
    rip = 0x0000000000dfb303   rsp = 0x00007fff0dcb2940
    Found by: stack scanning
50  phantomjs + 0x129a52
    rip = 0x0000000000529a53   rsp = 0x00007fff0dcb29f0
    Found by: stack scanning
51  libc-2.17.so + 0x834cf
    rip = 0x00007f3e76b074d0   rsp = 0x00007fff0dcb2a20
    Found by: stack scanning
52  libc-2.17.so + 0x834cf
    rip = 0x00007f3e76b074d0   rsp = 0x00007fff0dcb2a60
    Found by: stack scanning
53  phantomjs + 0x159202c
    rip = 0x000000000199202d   rsp = 0x00007fff0dcb2a80
    Found by: stack scanning
54  phantomjs + 0xa9dd13
    rip = 0x0000000000e9dd14   rsp = 0x00007fff0dcb2ad0
    Found by: stack scanning
55  phantomjs + 0x16ea9bf
    rip = 0x0000000001aea9c0   rsp = 0x00007fff0dcb2b38
    Found by: stack scanning
56  phantomjs + 0x139528
    rip = 0x0000000000539529   rsp = 0x00007fff0dcb2ba0
    Found by: stack scanning
57  phantomjs + 0x9ddd51
    rip = 0x0000000000dddd52   rsp = 0x00007fff0dcb2c50
    Found by: stack scanning
58  phantomjs + 0x9e0a05
    rip = 0x0000000000de0a06   rsp = 0x00007fff0dcb2c70
    Found by: stack scanning
59  phantomjs + 0x9def0e
    rip = 0x0000000000ddef0f   rsp = 0x00007fff0dcb2cc0
    Found by: stack scanning
60  phantomjs + 0x134baf
    rip = 0x0000000000534bb0   rsp = 0x00007fff0dcb2cd8
    Found by: stack scanning
61  phantomjs + 0x9b587f
    rip = 0x0000000000db5880   rsp = 0x00007fff0dcb2dc0
    Found by: stack scanning
62  phantomjs + 0x9f487c
    rip = 0x0000000000df487d   rsp = 0x00007fff0dcb2e50
    Found by: stack scanning
63  phantomjs + 0x109ef8
    rip = 0x0000000000509ef9   rsp = 0x00007fff0dcb2e60
    Found by: stack scanning
64  phantomjs + 0xa903d5
    rip = 0x0000000000e903d6   rsp = 0x00007fff0dcb2e70
    Found by: stack scanning
65  phantomjs + 0xcbfa1
    rip = 0x00000000004cbfa2   rsp = 0x00007fff0dcb2f20
    Found by: stack scanning
66  phantomjs + 0xa90a5b
    rip = 0x0000000000e90a5c   rsp = 0x00007fff0dcb2f70
    Found by: stack scanning
67  phantomjs + 0x40b37a
    rip = 0x000000000080b37b   rsp = 0x00007fff0dcb2fb0
    Found by: stack scanning
68  phantomjs + 0x4d4558
    rip = 0x00000000008d4559   rsp = 0x00007fff0dcb3020
    Found by: stack scanning
69  phantomjs + 0x1684c80
    rip = 0x0000000001a84c81   rsp = 0x00007fff0dcb3050
    Found by: stack scanning
70  phantomjs + 0x1684e5d
    rip = 0x0000000001a84e5e   rsp = 0x00007fff0dcb30a0
    Found by: stack scanning
71  phantomjs + 0x882e7
    rip = 0x00000000004882e8   rsp = 0x00007fff0dcb30b0
    Found by: stack scanning
72  phantomjs + 0x14f3837
    rip = 0x00000000018f3838   rsp = 0x00007fff0dcb30e0
    Found by: stack scanning
73  phantomjs + 0x14f021c
    rip = 0x00000000018f021d   rsp = 0x00007fff0dcb3110
    Found by: stack scanning
74  phantomjs + 0x1640e83
    rip = 0x0000000001a40e84   rsp = 0x00007fff0dcb3120
    Found by: stack scanning
75  phantomjs + 0x104ac0b
    rip = 0x000000000144ac0c   rsp = 0x00007fff0dcb3160
    Found by: stack scanning
76  phantomjs + 0x1050676
    rip = 0x0000000001450677   rsp = 0x00007fff0dcb3190
    Found by: stack scanning
77  phantomjs + 0x104ac0b
    rip = 0x000000000144ac0c   rsp = 0x00007fff0dcb31b0
    Found by: stack scanning
78  phantomjs + 0x1050676
    rip = 0x0000000001450677   rsp = 0x00007fff0dcb31e0
    Found by: stack scanning
79  libc-2.17.so + 0x85d38
    rip = 0x00007f3e76b09d39   rsp = 0x00007fff0dcb3200
    Found by: stack scanning
80  libc-2.17.so + 0x85d38
    rip = 0x00007f3e76b09d39   rsp = 0x00007fff0dcb3220
    Found by: stack scanning
81  libc-2.17.so + 0x10f96c
    rip = 0x00007f3e76b9396d   rsp = 0x00007fff0dcb3270
    Found by: stack scanning
82  phantomjs + 0x15e1ba6
    rip = 0x00000000019e1ba7   rsp = 0x00007fff0dcb3280
    Found by: stack scanning
83  libc-2.17.so + 0xf2dee
    rip = 0x00007f3e76b76def   rsp = 0x00007fff0dcb32a0
    Found by: stack scanning
84  phantomjs + 0x1697e2a
    rip = 0x0000000001a97e2b   rsp = 0x00007fff0dcb32b0
    Found by: stack scanning
85  phantomjs + 0x15880a4
    rip = 0x00000000019880a5   rsp = 0x00007fff0dcb32c0
    Found by: stack scanning
86  phantomjs + 0x167359c
    rip = 0x0000000001a7359d   rsp = 0x00007fff0dcb3310
    Found by: stack scanning
87  phantomjs + 0x1699bb2
    rip = 0x0000000001a99bb3   rsp = 0x00007fff0dcb3370
    Found by: stack scanning
88  phantomjs + 0x169a547
    rip = 0x0000000001a9a548   rsp = 0x00007fff0dcb3410
    Found by: stack scanning
89  phantomjs + 0x109dae9
    rip = 0x000000000149daea   rsp = 0x00007fff0dcb3460
    Found by: stack scanning
90  phantomjs + 0x167254e
    rip = 0x0000000001a7254f   rsp = 0x00007fff0dcb34a0
    Found by: stack scanning
91  phantomjs + 0x1672875
    rip = 0x0000000001a72876   rsp = 0x00007fff0dcb34d0
    Found by: stack scanning
92  libstdc++.so.6.0.18 + 0x5ef4c
    rip = 0x00007f3e773c4f4d   rsp = 0x00007fff0dcb34f0
    Found by: stack scanning
93  phantomjs + 0xfc5b
    rip = 0x000000000040fc5c   rsp = 0x00007fff0dcb3510
    Found by: stack scanning
94  phantomjs + 0x16772ac
    rip = 0x0000000001a772ad   rsp = 0x00007fff0dcb3530
    Found by: stack scanning
95  phantomjs + 0x131b679
    rip = 0x000000000171b67a   rsp = 0x00007fff0dcb3540
    Found by: stack scanning
96  phantomjs + 0xfc5b
    rip = 0x000000000040fc5c   rsp = 0x00007fff0dcb3568
    Found by: stack scanning
97  phantomjs + 0xe4f9
    rip = 0x000000000040e4fa   rsp = 0x00007fff0dcb3570
    Found by: stack scanning
98  libc-2.17.so + 0x3c173f
    rip = 0x00007f3e76e45740   rsp = 0x00007fff0dcb3578
    Found by: stack scanning
99  libc-2.17.so + 0x83ae1
    rip = 0x00007f3e76b07ae2   rsp = 0x00007fff0dcb35a0
    Found by: stack scanning
100  phantomjs + 0x15087af
    rip = 0x00000000019087b0   rsp = 0x00007fff0dcb35e0
    Found by: stack scanning
101  phantomjs + 0x158e915
    rip = 0x000000000198e916   rsp = 0x00007fff0dcb35f0
    Found by: stack scanning
102  phantomjs + 0x2cd9f
    rip = 0x000000000042cda0   rsp = 0x00007fff0dcb3610
    Found by: stack scanning
103  libc-2.17.so + 0x21de4
    rip = 0x00007f3e76aa5de5   rsp = 0x00007fff0dcb36b0
    Found by: stack scanning
104  phantomjs + 0xe33f
    rip = 0x000000000040e340   rsp = 0x00007fff0dcb36d0
    Found by: stack scanning
105  phantomjs + 0xfc5b
    rip = 0x000000000040fc5c   rsp = 0x00007fff0dcb36e8
    Found by: stack scanning
106  phantomjs + 0x16e322f
    rip = 0x0000000001ae3230   rsp = 0x00007fff0dcb3730
    Found by: stack scanning
107  phantomjs + 0xfc5b
    rip = 0x000000000040fc5c   rsp = 0x00007fff0dcb3758
    Found by: stack scanning
108  phantomjs + 0xfc84
    rip = 0x000000000040fc85   rsp = 0x00007fff0dcb3770
    Found by: stack scanning

Thread 1
 0  libpthread-2.17.so + 0xbc84
    rbx = 0x00000000029388e8   r12 = 0x0000000000000000
    r13 = 0x00000000000000ff   r14 = 0x000000000292a840
    r15 = 0x0000000002932880   rip = 0x00007f3e77675c84
    rsp = 0x00007f3e75f55df0   rbp = 0x0000000002932850
    Found by: given as instruction pointer in context
 1  phantomjs + 0xc7f21
    rip = 0x00000000004c7f22   rsp = 0x00007f3e75f55e20
    Found by: stack scanning
 2  ld-2.17.so + 0x15724
    rip = 0x00007f3e7881a725   rsp = 0x00007f3e75f55e60
    Found by: stack scanning
 3  libpthread-2.17.so + 0x1171f
    rip = 0x00007f3e7767b720   rsp = 0x00007f3e75f55e90
    Found by: stack scanning
 4  phantomjs + 0xc7f58
    rip = 0x00000000004c7f59   rsp = 0x00007f3e75f55ea0
    Found by: stack scanning
 5  libpthread-2.17.so + 0x7f6d
    rip = 0x00007f3e77671f6e   rsp = 0x00007f3e75f55eb0
    Found by: stack scanning
 6  libpthread-2.17.so + 0x1171f
    rip = 0x00007f3e7767b720   rsp = 0x00007f3e75f55ee8
    Found by: stack scanning
 7  libc-2.17.so + 0xfa9cc
    rip = 0x00007f3e76b7e9cd   rsp = 0x00007f3e75f55fc0
    Found by: stack scanning

Thread 2
 0  libc-2.17.so + 0xf2de3
    rbx = 0x0000000000000008   r12 = 0x00007f3e70000d30
    r13 = 0x00007f3e70000fc8   r14 = 0x00007f3e75754d40
    r15 = 0x0000000000000000   rip = 0x00007f3e76b76de3
    rsp = 0x00007f3e75754bd0   rbp = 0x00007f3e70000a98
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1697e6a
    rip = 0x0000000001a97e6b   rsp = 0x00007f3e75754be0
    Found by: stack scanning
 2  phantomjs + 0x169a0b3
    rip = 0x0000000001a9a0b4   rsp = 0x00007f3e75754c40
    Found by: stack scanning
 3  phantomjs + 0x1677ed6
    rip = 0x0000000001a77ed7   rsp = 0x00007f3e75754c70
    Found by: stack scanning
 4  libc-2.17.so + 0x10f96c
    rip = 0x00007f3e76b9396d   rsp = 0x00007f3e75754cd0
    Found by: stack scanning
 5  phantomjs + 0x169872d
    rip = 0x0000000001a9872e   rsp = 0x00007f3e75754ce0
    Found by: stack scanning
 6  phantomjs + 0x169a4b1
    rip = 0x0000000001a9a4b2   rsp = 0x00007f3e75754d40
    Found by: stack scanning
 7  phantomjs + 0x167254e
    rip = 0x0000000001a7254f   rsp = 0x00007f3e75754d90
    Found by: stack scanning
 8  phantomjs + 0x1672875
    rip = 0x0000000001a72876   rsp = 0x00007f3e75754dc0
    Found by: stack scanning
 9  libstdc++.so.6.0.18 + 0x5ef4c
    rip = 0x00007f3e773c4f4d   rsp = 0x00007f3e75754de0
    Found by: stack scanning
10  phantomjs + 0x158db6e
    rip = 0x000000000198db6f   rsp = 0x00007f3e75754e20
    Found by: stack scanning
11  phantomjs + 0x158ffae
    rip = 0x000000000198ffaf   rsp = 0x00007f3e75754e70
    Found by: stack scanning
12  libpthread-2.17.so + 0x7f6d
    rip = 0x00007f3e77671f6e   rsp = 0x00007f3e75754eb0
    Found by: stack scanning

Thread 3
 0  libc-2.17.so + 0xf2de3
    rbx = 0x000000000000006c   r12 = 0x00007f3e28000d30
    r13 = 0x00007f3e28000fc8   r14 = 0x00007f3e2fdf0bf0
    r15 = 0x00007f3e2fdf0d50   rip = 0x00007f3e76b76de3
    rsp = 0x00007f3e2fdf0bd0   rbp = 0x00007f3e28000a98
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1697e2a
    rip = 0x0000000001a97e2b   rsp = 0x00007f3e2fdf0be0
    Found by: stack scanning
 2  phantomjs + 0x169a0b3
    rip = 0x0000000001a9a0b4   rsp = 0x00007f3e2fdf0c40
    Found by: stack scanning
 3  phantomjs + 0x1677ed6
    rip = 0x0000000001a77ed7   rsp = 0x00007f3e2fdf0c70
    Found by: stack scanning
 4  libc-2.17.so + 0x10f96c
    rip = 0x00007f3e76b9396d   rsp = 0x00007f3e2fdf0cd0
    Found by: stack scanning
 5  phantomjs + 0x169872d
    rip = 0x0000000001a9872e   rsp = 0x00007f3e2fdf0ce0
    Found by: stack scanning
 6  phantomjs + 0x169a4b1
    rip = 0x0000000001a9a4b2   rsp = 0x00007f3e2fdf0d40
    Found by: stack scanning
 7  phantomjs + 0x167254e
    rip = 0x0000000001a7254f   rsp = 0x00007f3e2fdf0d90
    Found by: stack scanning
 8  phantomjs + 0x1672875
    rip = 0x0000000001a72876   rsp = 0x00007f3e2fdf0dc0
    Found by: stack scanning
 9  libstdc++.so.6.0.18 + 0x5ef4c
    rip = 0x00007f3e773c4f4d   rsp = 0x00007f3e2fdf0de0
    Found by: stack scanning
10  phantomjs + 0x158db6e
    rip = 0x000000000198db6f   rsp = 0x00007f3e2fdf0e20
    Found by: stack scanning
11  phantomjs + 0x16990cc
    rip = 0x0000000001a990cd   rsp = 0x00007f3e2fdf0e30
    Found by: stack scanning
12  phantomjs + 0x158ffae
    rip = 0x000000000198ffaf   rsp = 0x00007f3e2fdf0e70
    Found by: stack scanning
13  libpthread-2.17.so + 0x7f6d
    rip = 0x00007f3e77671f6e   rsp = 0x00007f3e2fdf0eb0
    Found by: stack scanning

Thread 4
 0  libpthread-2.17.so + 0xbc84
    rbx = 0x0000000002c97770   r12 = 0x0000000002c97798
    r13 = 0x004189374bc6a7ef   r14 = 0x0000000000096258
    r15 = 0x0000000002c9ae60   rip = 0x00007f3e77675c84
    rsp = 0x00007f3e2e5bdd60   rbp = 0xffffffffffffffff
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1590485
    rip = 0x0000000001990486   rsp = 0x00007f3e2e5bdd90
    rbp = 0xffffffffffffffff
    Found by: stack scanning
 2  phantomjs + 0xd36a2
    rip = 0x00000000004d36a3   rsp = 0x00007f3e2e5bde00
    rbp = 0xffffffffffffffff
    Found by: stack scanning
 3  phantomjs + 0xbc7a4c
    rip = 0x0000000000fc7a4d   rsp = 0x00007f3e2e5bde30
    rbp = 0xffffffffffffffff
    Found by: stack scanning
 4  phantomjs + 0xd327a
    rip = 0x00000000004d327b   rsp = 0x00007f3e2e5bde60
    rbp = 0xffffffffffffffff
    Found by: stack scanning
 5  phantomjs + 0x158ffae
    rip = 0x000000000198ffaf   rsp = 0x00007f3e2e5bde70
    rbp = 0xffffffffffffffff
    Found by: stack scanning
 6  phantomjs + 0x3fafff
    rip = 0x00000000007fb000   rsp = 0x00007f3e2e5bde80
    rbp = 0xffffffffffffffff
    Found by: stack scanning
 7  libpthread-2.17.so + 0x7f6d
    rip = 0x00007f3e77671f6e   rsp = 0x00007f3e2e5bdeb0
    rbp = 0xffffffffffffffff
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x0254ffff  phantomjs  ???  (main)
0x7f3e1655d000 - 0x7f3e165adfff  DejaVuSerifCondensed.ttf  ???
0x7f3e165ae000 - 0x7f3e165fffff  DejaVuSansMono.ttf  ???
0x7f3e16b1f000 - 0x7f3e16b6bfff  DejaVuSansMono-Bold.ttf  ???
0x7f3e2c013000 - 0x7f3e2c0b0fff  DejaVuSansCondensed.ttf  ???
0x7f3e2c0b1000 - 0x7f3e2c14bfff  DejaVuSansCondensed-Bold.ttf  ???
0x7f3e2d542000 - 0x7f3e2d55afff  n021003l.pfb  ???
0x7f3e2d55b000 - 0x7f3e2d56cfff  n019004l.pfb  ???
0x7f3e2d5ac000 - 0x7f3e2d5bcfff  n019023l.pfb  ???
0x7f3e2e5bf000 - 0x7f3e2e7c5fff  libnss_dns-2.17.so  ???
0x7f3e2e7c6000 - 0x7f3e2e9c8fff  libnss_mdns4_minimal.so.2  ???
0x7f3e2e9c9000 - 0x7f3e2ebd5fff  libnss_files-2.17.so  ???
0x7f3e2ebd6000 - 0x7f3e2ededfff  libresolv-2.17.so  ???
0x7f3e7400e000 - 0x7f3e74021fff  n019003l.pfb  ???
0x7f3e75f57000 - 0x7f3e761b3fff  libssl.so.1.0.0  ???
0x7f3e761b5000 - 0x7f3e7658cfff  libcrypto.so.1.0.0  ???
0x7f3e76591000 - 0x7f3e76859fff  locale-archive  ???
0x7f3e7685a000 - 0x7f3e76a83fff  libexpat.so.1.6.0  ???
0x7f3e76a84000 - 0x7f3e76e46fff  libc-2.17.so  ???
0x7f3e76e4c000 - 0x7f3e77061fff  libgcc_s.so.1  ???
0x7f3e77062000 - 0x7f3e77365fff  libm-2.17.so  ???
0x7f3e77366000 - 0x7f3e77654fff  libstdc++.so.6.0.18  ???
0x7f3e7766a000 - 0x7f3e77882fff  libpthread-2.17.so  ???
0x7f3e77887000 - 0x7f3e77a8efff  librt-2.17.so  ???
0x7f3e77a8f000 - 0x7f3e77c92fff  libdl-2.17.so  ???
0x7f3e77c93000 - 0x7f3e77eabfff  libz.so.1.2.8  ???
0x7f3e77eac000 - 0x7f3e780d1fff  libpng12.so.0.49.0  ???
0x7f3e780d2000 - 0x7f3e7830dfff  libfontconfig.so.1.7.0  ???
0x7f3e7830e000 - 0x7f3e785affff  libfreetype.so.6.10.1  ???
0x7f3e785b0000 - 0x7f3e787f4fff  libjpeg.so.8.0.2  ???
0x7f3e78805000 - 0x7f3e78827fff  ld-2.17.so  ???
0x7f3e789ef000 - 0x7f3e789f9fff  945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-4  ???
0x7f3e789fa000 - 0x7f3e78a05fff  6d41288fd70b0be22e8c3a91e032eec0-le64.cache-4  ???
0x7f3e78a06000 - 0x7f3e78a11fff  d589a48862398ed80a3d6066f4f56f4c-le64.cache-4  ???
0x7fff0ddd8000 - 0x7fff0ddd9fff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
