### ISSUE TITLE
force phantomJs page content to use absolute url instead of relative url for images and css?

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#11920]
when I render a page on phantomjs, if there's relative images and css files, it does not show up when I open the page on my hard drive. Is it possible to force phantomjs to replace all the relative url paths with an absolute one so that when I open the outputted html file, all the css and images will correctly be displayed?

**Comment by ariya** [comment]
Implementing this is a major undertaking and currently beyond the scope of the project.
You are however free to work on it on your own or sponsor someone to implement it. Once it is in a state where we can consider it for inclusion, please reopen this issue and submit a pull request of the implementation. Thank you!
