### ISSUE TITLE
can t download phantomjs from china anymore

### ISSUE THREAD

**Issue by maboiteaspam** [ariya/phantomjs#11929]
Hi,

since the move to bibucket, or the cn government mind change, it is no more possible to download phantomjs from china mainland anymore.
the technical reason is cdn.bitbucket does not works here, the political reason dunno.

I was wondering if it would be possible to mirror with google code ?

Actually i m kinda stuck as node registry does not reference version 1.9.2 anymore (404 err), because of that i can not event lock my dependency version anymore :s

**Comment by ariya** [comment]
I'm afraid not much we can do here unless someone volunteers to setup a mirror site.

**Comment by maboiteaspam** [comment]
yeah. Put sown some ideas, node pre gyp over bittorrent. HAve plain JS implementation of bittorrent. Needs to update node pre gyp. Needs to update the project to take advantage of npgyp, if not yet the case.
Let s keep this close for the moment.
