### ISSUE TITLE
Can't render webpage that has 100% height and width in css properly. 

### ISSUE THREAD

**Issue by ManashRaja** [ariya/phantomjs#11923]
Using Phantomjs, I cannot render screenshot of website which have divs with 100% height and width. 
For example: The website <http://www.slidor.fr> (just for learning purpose, I am not related in any way)
has the following html markup for its header, which is a background image filling the viewport and with logo and call to action button.

    
        <div id="top" class="header">
            <div class="vert-text">
                <h1 itemprop="name"><a href="http://www.slidor.fr"><img itemprop="image" src="img/Logo-Slidor.png" class="fullWidth max800" alt="Slidor - Agence PowerPoint" /></a></h1>
                <h3 class="logoText">High Impact Presentations</h3>
                <a href="#about" class="toplink btn fullWidth">See Our Work</a>
            </div>
        </div>
        

They are also using bootstrap and custom css(shown below)

    .header {
    display: table;
    height: 100%;
    width: 100%;
    position: relative;
    color: #fff;
    background: url(../img/background.jpg) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    }
 
    html, body {
    height: 100%;
    width: 100%;
    }
    
    .vert-text {
    display: table-cell;
    vertical-align: middle;
    text-align: center;
    }

    .fullWidth {
    width: 100%;
    }
    .max800 {
    max-width: 800px;
    }

What I understand is that the following css properties are our concern

    .header {
    height: 100%;
    width: 100%;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    }
 
    html, body {
    height: 100%;
    width: 100%;
    }

These 100% are making the header stretch the whole viewport. It looks good for us but it doesn't seem to behave well with phantomjs.

Screenshot
![slidor](https://f.cloud.github.com/assets/6487572/1995544/babc83bc-8506-11e3-9ea0-2195f05352c8.jpg)

Which you can see that the header is stretching completely and hiding rest of the web page in the image. I don't know much about phantomjs and I am using its simplest code called by php

    var page = require('webpage').create();
    page.viewportSize = { width: 1024, height: 786};
    page.open('http://slidor.fr', function() {
    page.render('slidor.jpg');
    phantom.exit();
    });

So, please anybody help me with phantomjs so that it works correctly with such webpages. I don't want any modifications regarding the webpage. I want to know how we can use phantomjs in such webpages.

Thanks

**Comment by freddy-dev** [comment]
+1

**Comment by jpopecreative** [comment]
+1
tried using a table and tried with flexbox
html and body can be set to 100% height but nothing inside will scale to match

**Comment by zackw** [comment]
We are sorry for not responding to this bug for so long.

1. Everyone with this problem should try PhantomJS 2.0 if they aren't already using it.  PhantomJS 1.9.x is no longer developed, and 2.0 has a much newer (although still somewhat out of date) version of Webkit that may resolve the problem.

1. If there is still a problem with PhantomJS 2, then it is because of a bug in Webkit.  We do not have the manpower to fix Webkit bugs ourselves.  Please follow the instructions at https://www.webkit.org/quality/reporting.html to determine whether the bug exists in upstream Webkit and, if so, report it directly to the Webkit developers.
