### ISSUE TITLE
Background Color for Header / Footer

### ISSUE THREAD

**Issue by 19Gerhard85** [ariya/phantomjs#11930]
How can I define / override the white background color for header and footer?

**Comment by andrebaresel** [comment]
The white box of header and footer is the real problem. It's not possible to make the header and footer transparent. Which is important for post processing (e.g. add a watermark / letter head with another pdf file).

**Comment by willemmulder** [comment]
Also a problem for us, where on the front page we don't want a header, but even if we make the header empty, it will still show as a white box that overwrites whatever that is already on the page.

**Comment by abdelilah** [comment]
Also annoying for me as I try to add a background to the whole PDF document. Header and Footer always get a white background.

Has anyone found a fix for this ?

**Comment by chrise86** [comment]
@abdelilah I know this is old, but did you manage to resolve this issue?

**Comment by abdelilah** [comment]
@chrise86 unfortunately this could not be resolved, however I much better luck with puppeteer as an alternative.

**Comment by chrise86** [comment]
@abdelilah I thought that might be the case. Thanks for replying so quickly!
