### ISSUE TITLE
How could I get response status code 304 ?

### ISSUE THREAD

**Issue by siemenliu** [ariya/phantomjs#11936]
Why request resources response status code allways 200 ?

I modified the netsniff.js, request a url, in the callback function, use page.reload() to reload page, I want to see static resource like image and css response status code 304(not modify), but there always 200.

The same url in the chrome, if reload the page, many static resource response code in 304, but phantomjs alway 200.

How could I get response status code 304 ?

There is my netsniff.js code
https://gist.github.com/siemenliu/8680488

My command line config.json

``` json
{
    "cookiesFile": "./data/data-cookie.txt",
    "diskCache": true,
    "localStoragePath": "./data/data-localstorage.txt",
    "localStorageQuota": 5120,
    "maxDiskCacheSize": 51200
}
```

My command line

``` bash
phantomjs --config=./config.json netsniff.js http://<url>/ > test.har
```

**Comment by LinkeyZ** [comment]
hehe
