### ISSUE TITLE
Dynamic height for header and footer

### ISSUE THREAD

**Issue by crashbtz** [ariya/phantomjs#11931]
Hello,

Everything is in the title, I would want to know if it's possible to make the height of the header and footer dynamic with the pageNum.
I would like the header of the first page bigger than the others.

Thanks

**Comment by fnicollet** [comment]
Might be a bit late but I am also interested. If you ever found a solution ...

**Comment by CitizenInsane** [comment]
Yep dynamic height would be great (i.e. height automatically recomputed upon header/footer contents for current page)

**Comment by sunil007** [comment]
Hello,

Is this issue resolved ?
does phantom provides capability for dynamic height for header and footer ?
Is there any alternate way to customize first and last page header/footer height of my document 

Thanks
