### ISSUE TITLE
Rasterize.js renders black below a specific height when screen capture a long web page.

### ISSUE THREAD

**Issue by larryzhao** [ariya/phantomjs#11934]
Friends.

I am new to `phantomjs`, I am using it to create screenshots of web pages with user created content. It works fine with most of the pages, but I just found it doesn't work well with a quite long web page. The lower part of the image created by `phantomjs` is totally black.

I changed several parameters like `page.viewPort.height` / `page.clipRect.height`, but every time the black part starts at the same place, so I am curious why phantomjs can't render correctly below a certain height? Are there any parameters I need to tweak accordingly?

The problematic webpage is http://jianshu.io/notes/83391/snap_view and you could see an example of the output image here: http://prod-jianshu-cwb.b0.upaiyun.com/notes/images/83391/weibo/image_622f51e887bb.jpeg

I am using phantomjs 1.9.2, the way creating the image is `phantomjs rasterize.js [webpage url] [destination file]` and the `rasterize.js` I am using is here:

```
var page = require('webpage').create(),
    system = require('system'),
    address, output, size;

if (system.args.length < 3 || system.args.length > 5) {
  console.log('Usage: rasterize.js URL filename [paperwidth*paperheight|paperformat] [zoom]');
  console.log('  paper (pdf output) examples: "5in*7.5in", "10cm*20cm", "A4", "Letter"');
  phantom.exit(1);
} else {
  address = system.args[1];
  output = system.args[2];
  page.viewportSize = { width: 640, height: 600 };
  if (system.args.length > 3 && system.args[2].substr(-4) === ".pdf") {
    size = system.args[3].split('*');
    page.paperSize = size.length === 2 ? { width: size[0], height: size[1], margin: '0px' }
    : { format: system.args[3], orientation: 'portrait', margin: '1cm' };
  }
  if (system.args.length > 4) {
    page.zoomFactor = system.args[4];
  }

  page.open(address, function (status) {
    if (status !== 'success') {
      console.log('Unable to load the address!');
      phantom.exit();
    } else {
      window.setTimeout(function () {
        page.render(output);
        phantom.exit();
      }, 1000);
    }
  });
}
```

**Comment by matAtWork** [comment]
Same issue here. This would be great to fix

**Comment by sunrisela** [comment]
This bug is still in 2.0.0.

**Comment by danielsarin** [comment]
I am having this issue as well. Any workarounds?

**Comment by MrP** [comment]
This just happened to me in version 2.1.1 in Ubuntu

**Comment by MrP** [comment]
I found a workaround. Take several screenshots with the right clipRect, then stitch them together with imagemagick.  Of course, because we are talking about huge images, everything is difficult.  

Assuming you have more disk than memory and CPU, convert to imagemagick's mpc format first, then manipulate.  It reduces the risk of your process getting killed.

I'll clean up the code a bit and post it somewhere, but I'm afraid it's one of those things that are fiddly and you'll have to fiddle with it yourself until it works.

**Comment by MrP** [comment]
Well, I've gone and done it.  https://www.npmjs.com/package/phantomjs-render-large-page  let me know if it's useful, has any bugs, etc.  All feedback is welcome.

**Comment by sfrazer** [comment]
I can confirm this is still an issue with version 2.1.1 (latest)

I've tried MrP's workaround and it doesn't work for me. Fails silently, no final PNG output, though I do see a temp file being created.

**Comment by MrP** [comment]
Hi, @sfrazer  thanks for trying my workaround.  What's your setup?  How big is your page?  I'll give it a try if you can point to a public URL.

**Comment by nicewahson** [comment]
It happened to me just now, also i can not evaluate my page size correctly, my phantomjs version is 2.1.1

**Comment by emascarinas** [comment]
I'm having the same issue. Im using version 2.1.16
