### ISSUE TITLE
The Google Directions example breaches Google's Terms of Service

### ISSUE THREAD

**Issue by susi** [ariya/phantomjs#11949]
In https://github.com/ariya/phantomjs/blob/master/examples/direction.js#L30 there seems to be some regexp which removes the copyright statements. Please remove that.

Removing copyright info is against the Google Maps Terms of Service[0].
The aforementioned piece of code would lead developers into violating these Terms of Service, without even knowing it.

[0] Google Maps Terms of Service:
https://developers.google.com/maps/terms
§ 9.4 (a), (b) and (c)
§ 10.1.1. (f)

**Comment by ariya** [comment]
The entire example script will be removed.
