### ISSUE TITLE
Incorrect HTTP status returned with AngularJS application

### ISSUE THREAD

**Issue by sthomp** [ariya/phantomjs#11943]
In angularjs I can make an http GET request as follows:

```
$http.get('http://localhost:9000/getdata/123',{withCredentials: true})
  .success(function(data, status, headers, config) {
    console.log("Success! Got this http response code: " + status);
  })
  .error(function(data, status, headers, config) {
    console.log("Failed. Got this http response code: " + status);
  });
```

When I run this code in Chrome and my REST server returns an HTTP 404 this will print the following:

```
Failed. Got this http response code: 404
```

When I run this same code in phantomjs this will print the following:

```
Failed. Got this http response code: 0
```

It seems there is a difference in how phantomjs executes the javascript compared to how chrome executes it. Here is the phantomjs code I am using to execute this:

```
var page = require('webpage').create();

page.onConsoleMessage = function(msg) {
  console.log('Here is a page message ' + msg);
};

page.open('http://localhost:8080', function ( status ) {
  if ( status === 'fail' ) {
    phantom.exit( 1 );
    return; // essential, if you don't, below will be executed
  }

  window.setTimeout(
    function () {
      var result = page.evaluate(
        function () {
          var html = document.documentElement.outerHTML;
          return html;
        }
      );
      console.log(result);
    },
    1000 // wait 1,000ms (1s)
  );
});

```

**Comment by amatriain** [comment]
Same here. In phantomjs the value passed to the ```status``` argument of the ```error``` callback of ```$http``` is always zero, regardless of the actual HTTP status received. It doesn't only fail with a 404, any other error status also triggers this bug.

When using selenium or a full browser (I've tested with firefox and chrome) instead of phantomjs it works as expected, the actual HTTP status is passed in the ```status``` argument.
