### ISSUE TITLE
Phantomjs crashing while trying to load multiple links

### ISSUE THREAD

**Issue by Karela** [ariya/phantomjs#11959]
Versions tried - 1.7.0 and 1.9.2
OS - windows 7 and 2008 server R2

I am crawling though all the links on a web page (one level only), loading them and saving the content. When number of links reach more than around 27, phantomjs crashes abruptly. If this is not a valid issue, any guidance to overcome this is greatly appreciated.
Here is my partial code:

 var mainPageLoadCallBack = function (status, page) {
		counter++;
		try{
			console.log('main page loaded with status: ');
			console.log(status);
			if (status !== 'success') {
				console.error("Pageload status is " + status+".\n Exiting with return code 1");
				phantom.exit(1);
			} 
			page.evaluate(function(){					
					$("body").addClass("exportfriendly");					
				});
			var links=[];
				links = page.evaluate(function(){
					console.log("Getting followForExport links from main page:");
					$("body").addClass("exportfriendly");
					var allLinks = $(".followForExport");
					var retVal = [];
					$.each(allLinks, function(index, value){
						if(index<=27){ //defensive check as it doesn't scale beyond 28 links.										
							retVal.push(value.href);
							$(value).attr("href", "#crawled"+index);
							$(value).addClass("crawledLink");
						}
					});
					return retVal;
				});
			console.log("Got links from main page:"+links.length);
			var heights=[];			
			links.forEach(function(value, index, a){  //create html file for each followforlink url
				loadPage(value, function(status, otherPage){
						console.log(value + " loaded with "+ status);
						if (status !== 'success') {
							console.error("Error while loading " + value);
							console.error("Pageload status is " + status+".\n Exiting with return code 1");
							phantom.exit(1);
						} 																
						waitFor(function(){
								console.log('evaluating waitfor condition...');
							return otherPage.evaluate(function() {
							var retVal = true;
							if(!window.jQuery) //Wait for jquery to load - Requires that target page has jquery
								return false;
							if(!window.allOnReadiesExecuted) 
								return false;
							if($.active>0) //any active ajax requests pending?
								return false;
							var loadmask=$(".loadmask:visible");
							retVal=retVal&& loadmask.length==0;          		
							console.log('waitfor condition is...'+retVal);
							return retVal; 
							});
							}, function(){
								window.setTimeout(function(){
									heights[index] = otherPage.evaluate(function(){
										console.log('getting height');
										return document.body.scrollHeight;
									});
									var otherFileName = outputFileName+"test"+index;
									var content = otherPage.content;
									console.log('writing html file at ' + "temp\\"+otherFileName+".html");
									fs.write("temp\\"+otherFileName+".html", content, "w");
									linksLoaded++;
								}, 500); //end settimeout
						}, 2*60*1000); //1 min. timeout - end waitfor
				}); //end loadpage
		});//end links.foreach
		... //some more processing
		...
	}
	catch(e){
		console.error("Error on pageload " + e);
		console.error("Exiting with error code 1");
		phantom.exit(1);
	}
};
page = loadPage(screenshot.url, mainPageLoadCallBack);

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (220/200 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:22398)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-cf68-andre=castonguay.org@sgmail.github.com>)
	id 1apkP3-003KVg-6Z
	for andre@castonguay.org; Mon, 11 Apr 2016 18:33:54 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=0bBX/zvdTAIP/ZXtKZ94+LMM3Qg=; b=hhLO1GccpMT+8yBl
	BDQsc6cl7jwLrVsj5HCBkmLytcD1/5Pg4RzPpoobl0j/0Et9/yNCxmYT8upoJzFk
	I1eTM2NexYUorU70PYAtD98TDTWYR3FCY/X0U0YsSbD/VTrz6BbRnmICW9lXNuuz
	mPyzs2PanJOoeYlhjrzMcOT/RPQ=
Received: by filter0432p1mdw1.sendgrid.net with SMTP id filter0432p1mdw1.9284.570C26283B
        2016-04-11 22:33:12.677710314 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id YA66M_pHSpmV0VZAAzAQmg
	for <andre@castonguay.org>; Mon, 11 Apr 2016 22:33:12.538 +0000 (UTC)
Date: Mon, 11 Apr 2016 15:33:12 -0700

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (219/200 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:54093 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkP3-003KWL-5f
	for andre@castonguay.org; Mon, 11 Apr 2016 18:33:53 -0400
Date: Mon, 11 Apr 2016 15:33:12 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460413993;
	bh=TNueJT67wZKnlTEPINXY6E0YZTY1Mh6VwiXvmMQB0p8=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ovU+M6/4S93EYw6HYGxH+JJBGb5fz6hCbw8bqHBIobhC6UALQRfq5UrG1Ml1UTEPf
	 +AX0V/QYIXgvrI0y6S1VRbQKztvXYmwI1qZ7KyLzp9Gk+FO6Ta3I3RDjzf0gOw8omx
	 OHwbwN3qn8m7gF80asg8DNYTLtKUY86nLnV5IL6k=
