### ISSUE TITLE
SVG Not Scaling. 

### ISSUE THREAD

**Issue by asymptotik** [ariya/phantomjs#11956]
When loading SVG via an <object> in Chrome or Safari, the SVG content is scaled to fit the width and height of the <object> though it appears to maintain aspect ratio. This only appears to happen when the <svg> tag contains a viewBox. Without the viewBox, the SVG is rendered the size specified in the <svg> tag and in the case of my sample, it is clipped to the <object> size. This scaling does not happen in phantomjs whether or not a viewBox attribute is set. Code:

``` html
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="content-type"/>
  <title>Title</title>
  <style type="text/css">
  </style>
</head>
<body>
  <object data="simple.svg" width="100" height="200" />
  <script type="text/javascript">
  </script>  
</body>
</html>
```

simple.svg

``` xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     width="612px" height="792px" viewBox="0 0 612 792" >
<rect x="8" y="8" fill="#FFFFFF" stroke="#000000" stroke-miterlimit="10" width="596" height="778"/>
</svg>
```

**Comment by kubosador** [comment]
Have you tried to replace your object tag by an img tag ? 
That did the trick for me.
