### ISSUE TITLE
PhantomJS 1.9.7 with Ruby 2.1 always crashes when I try to upload a file via web interface

### ISSUE THREAD

**Issue by Konstantinusz** [ariya/phantomjs#11954]
I try to upload images to a popular website via its web interface. I am using Ruby 2.1 and Watir-Webdriver gem, Arch linux 3.12.9. When clicking submit button I always get an error message "EOFError: end of file reached" and PhantomJS eventually crashes. Minidump generated by minidump_stackwalk: http://pastebin.com/ZupsBhTV
dmp file: http://pvlv5wptjx.1fichier.com/2aeb91c8-2bd8-8393-0bd747db-3849daf3.dmp

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
