### ISSUE TITLE
Letter-spacing and otf fonts

### ISSUE THREAD

**Issue by sarink** [ariya/phantomjs#11950]
Running PhantomJS 1.9.7 pre-compiled

When rendering to PDF my page looks great. I have successfully @font-faced some OTF fonts, and Phantom handles them perfectly. However, if I try to apply some CSS letter-spacing to any element that is using one of my OTF fonts, the rendered PDF does not look correct.

I can't really explain what happens, it appears to disregard the letter-spacing completely, but somehow it screws up the rest of the text. The PNG output looks correct. I've attached two images.

PNG output:
![png](https://f.cloud.github.com/assets/1881761/2093819/527d4f4e-8ebf-11e3-9081-b1d5ced2e5ec.png)

PDF output:
![pdf](https://f.cloud.github.com/assets/1881761/2093821/549ca2a2-8ebf-11e3-8ac3-f2d3bc8ee7cd.png)

If anyone has any ideas of what I might try, or even a possible workaround, that would be greatly appreciated!

Thanks!

**Comment by mapodev** [comment]
The solution here https://github.com/wkhtmltopdf/wkhtmltopdf/issues/45 solved the problem. So you need to update the .conf file and change the update rate from server. I used CentOS 6 and it worked.

**Comment by UnquietCode** [comment]
I just wanted to mention that I had problems in phantom with CSS letter spacing less than or equal to 0.01em. For me, the minimum spacing to get a rendered effect was 0.02em.
