### ISSUE TITLE
Cannot access SVG children

### ISSUE THREAD

**Issue by DavidSouther** [ariya/phantomjs#11958]
I'm trying to run tests in Karma asserting that our code has correctly put some DOM inside an SVG element. The tests case is

``` coffee
describe 'Phantom Bugs', ->
    chartHtml = """
        <div class="nv-chart"> <svg> <g class="nvd3 nv-wrap
        nv-scatterChart nv-chart-81413" transform="translate(75,30)"> </g>
        </svg> </div>
    """

    element = null
    beforeEach ->
        element = document.createElement 'div'
        element.innerHTML = chartHtml

    it 'can look at svg elements', ->
        svgKids = element.children[0].children[0]
        svgKids.children.length.should.equal 1

    it 'can querySelector svg elements', ->
        svg = element.querySelector 'svg'
        svg.children.length.should.equal 1
```

These pass in Chrome and Firefox, but fail in Phantom.
https://github.com/DavidSouther/phantomsjs_bugs/blob/master/build/reports/karma.xml

The full test project is at
https://github.com/DavidSouther/phantomsjs_bugs

**Comment by duncanmeech** [comment]
Still broken 5/27/2015 e.g. 
.childElementCount returns say 3 but .children is null !!!

**Comment by nathanbowser** [comment]
Has anyone figured out a workaround for this?

**Comment by franciscop** [comment]
I also found this issue for a [library I created that I'm testing with PhantomJS](http://umbrellajs.com/) when it seems to also affect [DocumentFragment](https://developer.mozilla.org/en/docs/Web/API/DocumentFragment):

```js
console.log("A", u('<div>').append('<a>Test</a>').first().children);
console.log("B", u([document.createDocumentFragment()]).append('<a>Test</a>').first().children);
```

This shows:

```js
A [object HTMLCollection]
B undefined
```

Version 1.9.8 also

**Comment by franciscop** [comment]
@nathanbowser I just fixed it by creating a shim based [on this one](https://github.com/termi/ES5-DOM-SHIM/blob/0.8/__SRC/a.ie8.js) specific for my library tests:

```js
if(u(document.createDocumentFragment()).append('<div>').children().length == 0) {
	Object.defineProperty(DocumentFragment.prototype, "children", {"get" : function() {
		var arr = [],
			child = this.firstChild;

		while(child) {
			if(child.nodeType == 1)arr.push(child);
			child = child.nextSibling;
		}

		return arr;
	}});
};
```

You might want to do something similar for SVG.

**Comment by nathanbowser** [comment]
@franciscop Thanks for the update. Fortunately I was able to get off phantom, though.

**Comment by sbogdaniuk** [comment]
Don't use `children`, use `childNodes`

```javascript
// output all elements that have tagName
function getChildren(element) { return element.childNodes.filter(child => child.tagName)  };
```

**Comment by amatiasq** [comment]
No updates, isn't it?
