### ISSUE TITLE
Chinese chars not displayed, even with correct fonts

### ISSUE THREAD

**Issue by ondras** [ariya/phantomjs#11965]
Hi,

I am using PhantomJS to screenshot my mindmapping webapp. Chinese characters are an issue here.

Version: 1.9.7 (pre-build Debian binary)
Correct in-browser rendering:
![good1](https://f.cloud.github.com/assets/192172/2123970/6d10384c-9236-11e3-8bf2-2966e8b1acd5.png)

Incorrect PhantomJS rendering (fonts probably missing):
![bad1](https://f.cloud.github.com/assets/192172/2123971/7516335c-9236-11e3-82ad-edb08019b8c1.png)

Incorrect PhantomJS rendering (a lot of font packages installed):
![bad2](https://f.cloud.github.com/assets/192172/2123980/852745f6-9236-11e3-82a1-b30936ef8eb0.png)

**Comment by limTeTE** [comment]
Hi, do you guys solve this one? @ondras @mghaynes, I have this issue on windows
