### ISSUE TITLE
Page renders blank as PDF but renders complete as JPG

### ISSUE THREAD

**Issue by bmiller59** [ariya/phantomjs#11968]
This page renders blank when using rasterize to PDF, BUT renders fine when rendered to JPG.

http://www.skechersdsa.com/#!/login

**Comment by JamesRBrown** [comment]
This appears to still be a problem in phantomjs v2.1.1.  

I encountered a site which uses heavy Angular (181 scripts load). That I'll create a png first the line prior to PDF creation, and the png is good, but the PDF is emtpy.  
I'll save you from the details of the my troubleshooting efforts, but the short and sweet is, that once the CSS was removed the PDF creates properly.  It may be linked to the height attribute like Aaronius said, but I haven't gotten far enough to confirm that (it's a big page, and I didn't write it).  

I see there hasn't been an update on this bug in over a year, and just wanted to make sure it's not forgotten.

**Comment by mbalonso** [comment]
I'll second @JamesRBrown, has there been any update on this?  Everything was working just fine for me for 15-20min of testing and then, w/out changing any code on the site itself, I started getting blank pdfs - png renders just fine.

**Comment by mbalonso** [comment]
Well I did not see that coming.  

Looks like this might have been an issue w/firefox. I checked the filesize and it was essentially the same as the ones that had been working.  Tried to open the pdf in chrome and it worked fine.  Closed a bunch of tabs in FF and it magically started working again.

**Comment by jshin49** [comment]
I guess I will third @JamesRBrown .

I'm using the Windows version of PhantomJS, so I am not sure if it is only a Windows issue.

**Comment by chuan9** [comment]
@mbalonso I encountered the same thing, the page "https://www.wengold.net/test/report-pdf/src/layoutshow.html" can be rendered to png perfectly but the pdf is blank, my environment is : phantomjs v2.1.1, ubuntu 16.04LTS.  Can anyone help me?

**Comment by atljoseph** [comment]
Does anybody read or act on this issue thread? I'm about tired of messing with me and MJ ass because of this very issue and no information or workarounds available

**Comment by atljoseph** [comment]
Oops messing with phantomjs

**Comment by atljoseph** [comment]
Using v2.1.1  on windows 10 and restaurant Seshan works perfectly when it writes to the file system, however the Paige produced by streaming to the browser is blank with no graphics. It is extremely interesting to note that the blank white PDF representation of Google.com contained all the links that Google.com contained, but no text or input fields or graphics

**Comment by markstos** [comment]
Restaurant Seshan?

**Comment by atljoseph** [comment]
hahaha! voice-to-text!

Rasterization

**Comment by atljoseph** [comment]
sorry!

**Comment by atljoseph** [comment]
When output is raw binary:
[image: Inline image 1]

When the output is base64:
<<< Failed to load the document. >>> (error)

PDF in the filesystem:
[image: Inline image 2]

I call the following code with this batch file code.  The pdf on the
filesystem is perfectly intact when opened in Adobe Reader, but displays as
a blank white sheet with no text or gaphics.  Also, if I mouse over the
page slowly and watch the pointer and the bottom left hand corner of the
page, I see that there are links included from the webpage...just that the
webpage image is not there! :(
-------------------------------------------------------------------------
@echo on &set local
..\bin\phantomjs.exe pdf-stream.js 8081
pause

pdf-stream.js:
///////////////////////////////////////////////////////////////////////////////
// helpers
///////////////////////////////////////////////////////////////////////////////
var Guid = function () {
    function S4() {
        return (((1 + Math.random()) * 0x10000) |
0).toString(16).substring(1);
    }

    // then to call it, plus stitch in '4' in the third group
    return (S4() + S4() + "-" + S4() + "-4" + S4().substr(0, 3) + "-" +
S4() + "-" + S4() + S4() + S4()).toLowerCase();
}

var keyStr = "ABCDEFGHIJKLMNOP" +
              "QRSTUVWXYZabcdef" +
              "ghijklmnopqrstuv" +
              "wxyz0123456789+/" +
              "=";

function encode64(input) {
    input = escape(input);
    var output = "";
    var chr1, chr2, chr3 = "";
    var enc1, enc2, enc3, enc4 = "";
    var i = 0;

    do {
        chr1 = input.charCodeAt(i++);
        chr2 = input.charCodeAt(i++);
        chr3 = input.charCodeAt(i++);

        enc1 = chr1 >> 2;
        enc2 = ((chr1 & 3) << 4) | (chr2 >> 4);
        enc3 = ((chr2 & 15) << 2) | (chr3 >> 6);
        enc4 = chr3 & 63;

        if (isNaN(chr2)) {
            enc3 = enc4 = 64;
        } else if (isNaN(chr3)) {
            enc4 = 64;
        }

        output = output +
           keyStr.charAt(enc1) +
           keyStr.charAt(enc2) +
           keyStr.charAt(enc3) +
           keyStr.charAt(enc4);
        chr1 = chr2 = chr3 = "";
        enc1 = enc2 = enc3 = enc4 = "";
    } while (i < input.length);

    return output;
}

///////////////////////////////////////////////////////////////////////////////
// config
///////////////////////////////////////////////////////////////////////////////
var server = require('webserver').create(),
system = require('system'),
fs     = require('fs'),
    page = require('webpage').create(),
port   = system.args[1] || 8080;
// port   = system.env.PORT || 8080;

///////////////////////////////////////////////////////////////////////////////
// listen
///////////////////////////////////////////////////////////////////////////////
var service = server.listen(port, function (request, response) {
    // console.log('Request received at ' + new Date());

    // simulate a request
    request.headers.url = 'http://google.com';

    console.log('URL to convert ==>');
    console.log(request.headers.url);

    page.open(request.headers.url, function (status) {
        if (status !== 'success') {
            console.log('Unspecified Error ...');
        } else {

            // var filename = '02eea1c7-3c95-4111-4dea-2d0de4e881b6.pdf';
            var filename = 'f7a345b6-3041-4638-69aa-6133b0f23068.pdf';
            var raw = fs.read(filename);
            var base64 = encode64(raw);

            var data = raw;
            response.statusCode = 200;
            response.headers = {
                'Cache': 'no-cache',
                'Content-Type': 'application/pdf; charset=utf-8',
            };
            response.write(data);
            response.close();

            console.log('hello!');
            console.log(data.length);
        }
    });
});

if(service) console.log("server started on " + server.port);

**Comment by markstos** [comment]
This may be an inherent or difficult to solve problem with Phantom. Given that the the [future of PhantomJS is uncertain](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), consider evaluating headless Chromium or Nightmare.js as alternate solutions.
