### ISSUE TITLE
Large files

### ISSUE THREAD

**Issue by tobiasBora** [ariya/phantomjs#11973]
Hello,

I need to download a page with lot's of pictures which is really long (between 50 and 150 screens) and with this code:
    var page = require('webpage').create();
    output="out.png";
    address = 'page.html';
    nb_pages = 30;
    zoom = 1;
    width = 1804
    height = (768+(2334+0)*nb_pages);
    page.viewportSize = { width: width, height: height };
    page.zoomFactor = zoom;
    page.open(address, function (status) {
        if (status !== 'success') {
            console.log('Unable to load the address!');
        } else {
            console.log('Crop to: '+width+"x"+height);
            page.clipRect = { top: 0, left: 0, width: width, height: height };
            window.setTimeout(function () {
                page.render(output);
                phantom.exit();
            }, 200);
        }
    });
When the number of page is too high I've a cut after something like 35000px with the second part of the picture which is transparent:
![bug](https://f.cloud.github.com/assets/2164118/2143087/a6aa1fae-936d-11e3-991b-eb3cd5f407bb.png)

How could I render big pages ?

Thank you for your work.

Tobias.

**Comment by emascarinas** [comment]
I'm having this same exact issue. I'm using:

  "name": "phantomjs-prebuilt",
  "description": "Headless WebKit with JS API",
  "version": "2.1.16",
