### ISSUE TITLE
phantom crash: code -1073741819 on setting view port

### ISSUE THREAD

**Issue by majuansari** [ariya/phantomjs#11988]
Hi,

I am using phantomjs 1.9.1 along with node-phantom.
[OS: Windows 7]

I am getting "phantom crash: code -1073741819" on setting view port width to a value greater 600 .

Following is the code i use [data.html is the html of the entire page]

	 var phantom = require('node-phantom');
				phantom.create(function (err, ph) {
            ph.createPage(function (err, page) {
        page.get('viewportSize',function(err,value){
            console.log(value);
            page.set('viewportSize',{width:800,height:600},function(err){
                 page.set('content',data.html, function (err, status) {
				setTimeout(function() {
                    page.render('capture.png',function(err){
					console.log("created image");
                    //    ph.exit();
                    });
									}, 10000);
                });
            });
        });
			});
          });

If here i set height to 600 it will work fine . 
//page.set('viewportSize',{width:600,height:600},function(err){

Can any body please help me out on this issue ?
Thanks

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (218/200 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:3094)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-cf68-andre=castonguay.org@sgmail.github.com>)
	id 1apkOf-003K07-D4
	for andre@castonguay.org; Mon, 11 Apr 2016 18:33:30 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=yvT8mRBJpGMnnqqCcIR34mJtgmw=; b=PdNO/6OTDvhB+0Rj
	VxRgySOByRs0z4zxFNvwaiizPHhGyb+QSQEcSiOY8gcW8bChwiQ18KQYc3T8l+31
	NYl7tnQl7K+syfRuhxLNc16NQhO8zKYACN7521+MrOoowZp3EtZ+KpOnarNrQK48
	5DrgEiKa29d+omvnYNzlxIKvDgg=
Received: by filter0918p1mdw1.sendgrid.net with SMTP id filter0918p1mdw1.6226.570C260E47
        2016-04-11 22:32:46.821459757 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id ds9UFGZeRuOtPQaD1LSWsQ
	for <andre@castonguay.org>; Mon, 11 Apr 2016 22:32:46.697 +0000 (UTC)
Date: Mon, 11 Apr 2016 15:32:46 -0700

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (217/200 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:47033 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkOc-003JxM-Kb
	for andre@castonguay.org; Mon, 11 Apr 2016 18:33:27 -0400
Date: Mon, 11 Apr 2016 15:32:46 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460413966;
	bh=eOId6hU6p6PQJSeMEpHfU8vTUUu4hGEhHbsX1nKBwwI=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=x6GEn8rAwjYQ0FOfJF9TmNXWh0fABkNxaADIC956xUgb1JPhYSLmDud+/xdiI3a1L
	 cGRJhaSW69XI74hUGS84RaHoObL2DQADtT6+M8zLG9rCf01aNYoT3oEEFFO4ca2Dki
	 Z5hzL9Vc47RignsytpoRfQPGsw1lvSfowAdQ17IE=
