### ISSUE TITLE
Crash of PhantomJS 1.9.7 on Linux x86_64

### ISSUE THREAD

**Issue by zittix** [ariya/phantomjs#11981]
Here is the stack trace:

	Operating system: Linux
	                  0.0.0 Linux 3.8.0-32-generic #47~precise1-Ubuntu SMP Wed Oct 2 16:19:35 UTC 2013 x86_64
	CPU: amd64
	     family 6 model 58 stepping 9
	     4 CPUs

	Crash reason:  SIGSEGV
	Crash address: 0x18

	Thread 0 (crashed)
	 0  phantomjs!JSC::MarkStack::drain [Bitmap.h : 85 + 0x0]
	    rbx = 0x00007f0fd4fa0bc8   r12 = 0x00007f0fd4fa0868
	    r13 = 0x00007f0f8a4c4ec0   r14 = 0x00007f0f8a4c4800
	    r15 = 0x00007f0fd4fa0bd0   rip = 0x0000000000f286bd
	    rsp = 0x00007fff0a8d0170   rbp = 0x00007f0f8a132870
	    Found by: given as instruction pointer in context
	 1  phantomjs!JSC::Heap::markRoots [Heap.cpp : 225 + 0x7]
	    rbx = 0x0000000000000001   r12 = 0x00007f0fd4fa0868
	    r13 = 0x000000000000008d   r14 = 0x00007f0f8a4c4800
	    r15 = 0x00007fff0a8d01e0   rip = 0x0000000000f25738
	    rsp = 0x00007fff0a8d01c0   rbp = 0x00007f0fd4fa0bc8
	    Found by: call frame info
	 2  phantomjs!JSC::Heap::reset [Heap.cpp : 397 + 0x4]
	    rbx = 0x0000000000000001   r12 = 0x00007f0fd4fa0870
	    r13 = 0x000000000000008d   r14 = 0x00007f0f8a4c4800
	    r15 = 0x00000000000000d4   rip = 0x0000000000f25a31
	    rsp = 0x00007fff0a8d0a70   rbp = 0x00007f0fd4fa0868
	    Found by: call frame info
	 3  phantomjs!JSC::Heap::reportExtraMemoryCostSlowCase [Heap.cpp : 389 + 0xc]
	    rbx = 0x00007f0fd4fa0868   r12 = 0x00007f0f8a189a00
	    r13 = 0x000000000000008d   r14 = 0x00007f0f8a4c4800
	    r15 = 0x00000000000000d4   rip = 0x0000000000f25ba1
	    rsp = 0x00007fff0a8d0aa0   rbp = 0x0000000000000240
	    Found by: call frame info
	 4  phantomjs!JSC::JSArray::increaseVectorPrefixLength [Heap.h : 169 + 0x4]
	    rbx = 0x0000000000000460   r12 = 0x00007f0f8a189a00
	    r13 = 0x000000000000008d   r14 = 0x00007f0f8a4c4800
	    r15 = 0x00000000000000d4   rip = 0x0000000000f7ac4d
	    rsp = 0x00007fff0a8d0ac0   rbp = 0x00007f0f8a140000
	    Found by: call frame info
	 5  phantomjs!JSC::JSArray::unshiftCount [JSArray.cpp : 856 + 0x10]
	    rbx = 0x000000000000008c   r12 = 0x00007f0f8a142850
	    r13 = 0x00007f0fd16884e8   r14 = 0x00007f0f8a142850
	    r15 = 0x000000000000008c   rip = 0x0000000000f80a2c
	    rsp = 0x00007fff0a8d0b10   rbp = 0x000000000000008c
	    Found by: call frame info
	 6  phantomjs!JSC::arrayProtoFuncUnShift [ArrayPrototype.cpp : 640 + 0xa]
	    rbx = 0x000000000000008c   r12 = 0x00007f0fd16884e8
	    r13 = 0x0000000000000001   r14 = 0x00007f0f8a142850
	    r15 = 0x000000000000008c   rip = 0x0000000001498353
	    rsp = 0x00007fff0a8d0bc0   rbp = 0x000000000000008c
	    Found by: call frame info
	 7  0x7f0f8c0001e7
	    rbx = 0x00007f0f8c60e985   r12 = 0x00000000000000af
	    r13 = 0x00007f0fd1688488   r14 = 0xffff000000000000
	    r15 = 0xffff000000000002   rip = 0x00007f0f8c0001e8
	    rsp = 0x00007fff0a8d0c80   rbp = 0x00007fff0a8d0d30
	    Found by: call frame info
	 8  phantomjs!JSC::Interpreter::executeCall [JITCode.h : 77 + 0x16]
	    rip = 0x0000000000f2e376   rsp = 0x00007fff0a8d0d40
	    Found by: stack scanning
	 9  phantomjs!JSC::call [CallData.cpp : 38 + 0x21]
	    rbx = 0x00007f0fd1688070   r12 = 0x00007f0fd16880a0
	    r13 = 0x00007f0fd1688038   r14 = 0xffff000000000000
	    r15 = 0xffff000000000002   rip = 0x0000000000f7291d
	    rsp = 0x00007fff0a8d0e10   rbp = 0x00007fff0a8d1080
	    Found by: call frame info
	10  phantomjs!JSC::functionProtoFuncApply [FunctionPrototype.cpp : 132 + 0x20]
	    rbx = 0x00007f0fd1688070   r12 = 0x00007f0fd16880a0
	    r13 = 0x00007f0fd1688038   r14 = 0xffff000000000000
	    r15 = 0xffff000000000002   rip = 0x00000000014ab77d
	    rsp = 0x00007fff0a8d0e20   rbp = 0x00007fff0a8d1080
	    Found by: call frame info
	11  0x7f0f8c0001e7
	    rbx = 0x00007f0fd1688038   r12 = 0x0000000000000200
	    r13 = 0x00007f0fd1688038   r14 = 0xffff000000000000
	    r15 = 0xffff000000000002   rip = 0x00007f0f8c0001e8
	    rsp = 0x00007fff0a8d0fd0   rbp = 0x00007fff0a8d1080
	    Found by: call frame info
	12  phantomjs!JSC::Interpreter::executeCall [JITCode.h : 77 + 0x16]
	    rip = 0x0000000000f2e376   rsp = 0x00007fff0a8d1090
	    Found by: stack scanning
	13  phantomjs!JSC::call [CallData.cpp : 38 + 0x21]
	    rbx = 0x0000000002a9ed10   r12 = 0x00007f0fd0f931b8
	    r13 = 0x00007f0fd0f931b0   r14 = 0x00007f0fd4f483d0
	    r15 = 0x00007fff0a8d11b0   rip = 0x0000000000f7291d
	    rsp = 0x00007fff0a8d1160   rbp = 0x0000000000000000
	    Found by: call frame info
	14  phantomjs!WebCore::ScheduledAction::executeFunctionInContext [JSMainThreadExecState.h : 48 + 0xb]
	    rbx = 0x0000000002a9ed10   r12 = 0x00007f0fd0f931b8
	    r13 = 0x00007f0fd0f931b0   r14 = 0x00007f0fd4f483d0
	    r15 = 0x00007fff0a8d11b0   rip = 0x00000000010130f9
	    rsp = 0x00007fff0a8d1170   rbp = 0x0000000000000000
	    Found by: call frame info
	15  phantomjs!WebCore::ScheduledAction::execute [ScheduledAction.cpp : 132 + 0x29]
	    rbx = 0x00007f0fd1161200   r12 = 0x00007f0fd0f931b0
	    r13 = 0x00007f0fd0e56c00   r14 = 0x0000000000000001
	    r15 = 0x00007f0fd0e56cd0   rip = 0x00000000010137cd
	    rsp = 0x00007fff0a8d12e0   rbp = 0x00007f0fd4f483d0
	    Found by: call frame info
	16  phantomjs!WebCore::DOMTimer::fired [DOMTimer.cpp : 148 + 0xa]
	    rbx = 0x00007f0fd0d0caf8   r12 = 0x00007f0fd0f931b0
	    r13 = 0x0000000002a9bb08   r14 = 0x0000000000000032
	    r15 = 0x00007fff0a8d1380   rip = 0x00000000008b46e9
	    rsp = 0x00007fff0a8d1340   rbp = 0x00007f0fd0e56cd0
	    Found by: call frame info
	17  phantomjs!WebCore::ThreadTimers::sharedTimerFiredInternal [ThreadTimers.cpp : 112 + 0x8]
	    rbx = 0x00007f0fd0d0caf8   r12 = 0x0000000000000000
	    r13 = 0x0000000003700ab0   r14 = 0x00000000000046d9
	    r15 = 0x00007fff0a8d1b10   rip = 0x0000000000993983
	    rsp = 0x00007fff0a8d13d0   rbp = 0x00007f0fd4fb57a8
	    Found by: call frame info
	18  phantomjs!QObject::event [qobject.cpp : 1156 + 0x8]
	    rbx = 0x0000000003759a60   r12 = 0x00007fff0a8d1b10
	    r13 = 0x0000000003700ab0   r14 = 0x00000000000046d9
	    r15 = 0x00007fff0a8d1b10   rip = 0x0000000001cefbc4
	    rsp = 0x00007fff0a8d1410   rbp = 0x0000000003759a60
	    Found by: call frame info
	19  phantomjs!QApplicationPrivate::notify_helper [qapplication.cpp : 4562 + 0xc]
	    rbx = 0x00007fff0a8d1d90   r12 = 0x00007fff0a8d1b10
	    r13 = 0x0000000003700ab0   r14 = 0x00000000000046d9
	    r15 = 0x00007fff0a8d1b10   rip = 0x00000000015decaf
	    rsp = 0x00007fff0a8d15b0   rbp = 0x0000000003759a60
	    Found by: call frame info
	20  phantomjs!QApplication::notify [qapplication.cpp : 4423 + 0x17]
	    rbx = 0x00007fff0a8d1d90   r12 = 0x00007fff0a8d1b10
	    r13 = 0x00007fff0a8d1d90   r14 = 0x00000000000046d9
	    r15 = 0x00007fff0a8d1b10   rip = 0x00000000015e793b
	    rsp = 0x00007fff0a8d15e0   rbp = 0x0000000003759a60
	    Found by: call frame info
	21  phantomjs!QCoreApplication::notifyInternal [qcoreapplication.cpp : 946 + 0x2]
	    rbx = 0x00000000036fe1c0   r12 = 0x00007fff0a8d1b10
	    r13 = 0x00007fff0a8d1d90   r14 = 0x00000000000046d9
	    r15 = 0x00007fff0a8d1b10   rip = 0x0000000001cde3d4
	    rsp = 0x00007fff0a8d1ab0   rbp = 0x0000000003759a60
	    Found by: call frame info
	22  phantomjs!QTimerInfoList::activateTimers [qcoreapplication.h : 231 + 0x14]
	    rbx = 0x0000000003702898   r12 = 0x0000000000000000
	    r13 = 0x0000000000000000   r14 = 0x00000000000046d9
	    r15 = 0x00007fff0a8d1b10   rip = 0x0000000001d07ecd
	    rsp = 0x00007fff0a8d1b00   rbp = 0x00000000000aa76c
	    Found by: call frame info
	23  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 941 + 0x7]
	    rbx = 0x0000000000000000   r12 = 0x00007fff0a8d1be0
	    r13 = 0x00000000036fd560   r14 = 0x0000000000000001
	    r15 = 0x00000000036fe2d8   rip = 0x0000000001d080e0
	    rsp = 0x00007fff0a8d1b90   rbp = 0x0000000003702030
	    Found by: call frame info
	24  phantomjs!QEventDispatcherQPA::processEvents [qeventdispatcher_qpa.cpp : 246 + 0x4]
	    rbx = 0x00000000039455a0   r12 = 0x0000000000000000
	    r13 = 0x00000000036fd560   r14 = 0x00007fff0a8d1c20
	    r15 = 0x00000000036fe2d8   rip = 0x000000000163a6a4
	    rsp = 0x00007fff0a8d1be0   rbp = 0x0000000003702030
	    Found by: call frame info
	25  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
	    rbx = 0x00000000039455a0   r12 = 0x00007fff0a8d1cb0
	    r13 = 0x00007fff0a8d1cc0   r14 = 0x00000000036fe230
	    r15 = 0x00000000036fe2d8   rip = 0x0000000001cdd4b5
	    rsp = 0x00007fff0a8d1c20   rbp = 0x00007fff0a8d1c60
	    Found by: call frame info
	26  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
	    rbx = 0x00000000039455a0   r12 = 0x00007fff0a8d1cb0
	    r13 = 0x00007fff0a8d1cc0   r14 = 0x00000000036fe230
	    r15 = 0x00000000036fe2d8   rip = 0x0000000001cdd918
	    rsp = 0x00007fff0a8d1c50   rbp = 0x00007fff0a8d1d90
	    Found by: call frame info
	27  phantomjs!QCoreApplication::exec [qcoreapplication.cpp : 1218 + 0x4]
	    rbx = 0x00000000036fe1c0   r12 = 0x00007fff0a8d1d90
	    r13 = 0x00007fff0a8d1f78   r14 = 0x00007fff0a8d1d00
	    r15 = 0x0000000000000000   rip = 0x0000000001cdf7cb
	    rsp = 0x00007fff0a8d1cb0   rbp = 0x00000000036fe1c0
	    Found by: call frame info
	28  phantomjs!main [main.cpp : 121 + 0x4]
	    rbx = 0x0000000003742be0   r12 = 0x00007fff0a8d1d90
	    r13 = 0x00007fff0a8d1f78   r14 = 0x00007fff0a8d1d00
	    r15 = 0x0000000000000000   rip = 0x0000000000427cb2
	    rsp = 0x00007fff0a8d1cf0   rbp = 0x00007fff0a8d1f28
	    Found by: call frame info
	29  libc-2.15.so + 0x2176c
	    rbx = 0x0000000000000000   r12 = 0x0000000000407cc0
	    r13 = 0x00007fff0a8d1f20   r14 = 0x0000000000000000
	    r15 = 0x0000000000000000   rip = 0x00007f0fd37ee76d
	    rsp = 0x00007fff0a8d1e50   rbp = 0x0000000000000000
	    Found by: call frame info
	30  phantomjs + 0x27a5f
	    rip = 0x0000000000427a60   rsp = 0x00007fff0a8d1e70
	    Found by: stack scanning

	Thread 1
	 0  libpthread-2.15.so + 0xbd84
	    rbx = 0x0000000002a84208   r12 = 0x0000000002a76160
	    r13 = 0x00007f0fd2a899c0   r14 = 0x0000000000000000
	    r15 = 0x0000000000000003   rip = 0x00007f0fd43aad84
	    rsp = 0x00007f0fd2a88df0   rbp = 0x0000000002a76160
	    Found by: given as instruction pointer in context
	 1  phantomjs!WTF::TCMalloc_PageHeap::scavengerThread [FastMalloc.cpp : 2495 + 0x7]
	    rip = 0x00000000004ddafc   rsp = 0x00007f0fd2a88e20
	    Found by: stack scanning
	 2  phantomjs!WTF::TCMalloc_PageHeap::runScavengerThread [FastMalloc.cpp : 1618 + 0x4]
	    rbx = 0x0000000000000000   r12 = 0x00007f0fd43b0880
	    r13 = 0x00007f0fd2a899c0   r14 = 0x0000000000000000
	    r15 = 0x0000000000000003   rip = 0x00000000004ddc99
	    rsp = 0x00007f0fd2a88ea0   rbp = 0x0000000000000000
	    Found by: call frame info
	 3  libpthread-2.15.so + 0x7e99
	    rbx = 0x0000000000000000   r12 = 0x00007f0fd43b0880
	    r13 = 0x00007f0fd2a899c0   r14 = 0x0000000000000000
	    r15 = 0x0000000000000003   rip = 0x00007f0fd43a6e9a
	    rsp = 0x00007f0fd2a88eb0   rbp = 0x0000000000000000
	    Found by: call frame info
	 4  libpthread-2.15.so + 0x1187f
	    rip = 0x00007f0fd43b0880   rsp = 0x00007f0fd2a88f58
	    Found by: stack scanning
	 5  libc-2.15.so + 0xf43fc
	    rip = 0x00007f0fd38c13fd   rsp = 0x00007f0fd2a88fc0
	    Found by: stack scanning

	Thread 2
	 0  libc-2.15.so + 0xed763
	    rbx = 0x0000000000000000   r12 = 0x00007f0fd2287d80
	    r13 = 0x0000000000000008   r14 = 0x00007f0fcc000a98
	    r15 = 0x00007f0fcc000d30   rip = 0x00007f0fd38ba763
	    rsp = 0x00007f0fd2287b50   rbp = 0x00007f0fcc0008e0
	    Found by: given as instruction pointer in context
	 1  phantomjs!qt_safe_select [qcore_unix.cpp : 83 + 0x15]
	    rip = 0x0000000001d06327   rsp = 0x00007f0fd2287b60
	    Found by: stack scanning
	 2  phantomjs!QEventDispatcherUNIXPrivate::doSelect [qeventdispatcher_unix.cpp : 223 + 0xd]
	    rbx = 0x00007f0fcc0012b0   r12 = 0x00007f0fd2287d80
	    r13 = 0x00007f0fcc0008e0   r14 = 0x0000000000000000
	    r15 = 0x00007f0fcc000d30   rip = 0x0000000001d075e7
	    rsp = 0x00007f0fd2287bf0   rbp = 0x00007f0fcc0008e0
	    Found by: call frame info
	 3  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 937 + 0x4]
	    rbx = 0x00007f0fcc0012b0   r12 = 0x00007f0fd2287d80
	    r13 = 0x00007f0fcc0008c0   r14 = 0x0000000000000001
	    r15 = 0x0000000003937ea8   rip = 0x0000000001d08092
	    rsp = 0x00007f0fd2287d30   rbp = 0x00007f0fcc0008e0
	    Found by: call frame info
	 4  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
	    rbx = 0x00007f0fcc0012b0   r12 = 0x00007f0fd2287e10
	    r13 = 0x00007f0fd2287e20   r14 = 0x00000000036fe230
	    r15 = 0x0000000003937ea8   rip = 0x0000000001cdd4b5
	    rsp = 0x00007f0fd2287d80   rbp = 0x00007f0fd2287dc0
	    Found by: call frame info
	 5  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
	    rbx = 0x00007f0fcc0012b0   r12 = 0x00007f0fd2287e10
	    r13 = 0x00007f0fd2287e20   r14 = 0x00000000036fe230
	    r15 = 0x0000000003937ea8   rip = 0x0000000001cdd918
	    rsp = 0x00007f0fd2287db0   rbp = 0x00007fff0a8d1d90
	    Found by: call frame info
	 6  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
	    rbx = 0x0000000003937e20   r12 = 0x0000000003937ea8
	    r13 = 0x0000000000000001   r14 = 0x0000000000000000
	    r15 = 0x0000000000000003   rip = 0x0000000001bdfdf6
	    rsp = 0x00007f0fd2287e10   rbp = 0x0000000003937ea8
	    Found by: call frame info
	 7  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
	    rbx = 0x0000000003937ea8   r12 = 0x00000000037500f0
	    r13 = 0x0000000000000001   r14 = 0x0000000000000000
	    r15 = 0x0000000000000003   rip = 0x0000000001be2cc2
	    rsp = 0x00007f0fd2287e60   rbp = 0x0000000003939440
	    Found by: call frame info
	 8  libpthread-2.15.so + 0x7e99
	    rbx = 0x0000000000000000   r12 = 0x00007fff0a8d1270
	    r13 = 0x00007f0fd22889c0   r14 = 0x0000000000000000
	    r15 = 0x0000000000000003   rip = 0x00007f0fd43a6e9a
	    rsp = 0x00007f0fd2287eb0   rbp = 0x0000000000000000
	    Found by: call frame info

	Thread 3
	 0  libcrypto.so.1.0.0 + 0xbe16d
	    rbx = 0x00007f0fd09ddb80   r12 = 0x0000000000000054
	    r13 = 0x00007f0f842dbfa8   r14 = 0x00007f0f842dad30
	    r15 = 0x00007f0f842dbf90   rip = 0x00007f0fd2da616d
	    rsp = 0x00007f0fd09dd840   rbp = 0x00007f0fd09ddbc0
	    Found by: given as instruction pointer in context
	 1  libcrypto.so.1.0.0 + 0xbec3f
	    rip = 0x00007f0fd2da6c40   rsp = 0x00007f0fd09dd860
	    rbp = 0x00007f0fd09ddbc0
	    Found by: stack scanning

	Thread 4
	 0  libpthread-2.15.so + 0xc0fe
	    rbx = 0x00007f0f84006930   r12 = 0x000000000000000d
	    r13 = 0x00007f0f8bffedc0   r14 = 0xffffffffffffff92
	    r15 = 0x0000000000000000   rip = 0x00007f0fd43ab0fe
	    rsp = 0x00007f0f8bffed40   rbp = 0x00007f0f84006c00
	    Found by: given as instruction pointer in context
	 1  phantomjs!QWaitCondition::wait [qwaitcondition_unix.cpp : 84 + 0x7]
	    rip = 0x0000000001be39d7   rsp = 0x00007f0f8bffeda0
	    Found by: stack scanning
	 2  phantomjs!QThreadPoolThread::run [qthreadpool.cpp : 141 + 0x1d]
	    rbx = 0x00007f0f84006850   r12 = 0x00007f0f840068d9
	    r13 = 0x0000000000000002   r14 = 0x00007f0f841c7910
	    r15 = 0x0000000000000003   rip = 0x0000000001bd783d
	    rsp = 0x00007f0f8bffee20   rbp = 0x00007f0f84006c00
	    Found by: call frame info
	 3  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
	    rbx = 0x00007f0f800012b0   r12 = 0x00007f0f84006da0
	    r13 = 0x0000000000000001   r14 = 0x0000000000000000
	    r15 = 0x0000000000000003   rip = 0x0000000001be2cc2
	    rsp = 0x00007f0f8bffee60   rbp = 0x00007f0f84006c00
	    Found by: call frame info
	 4  libpthread-2.15.so + 0x7e99
	    rbx = 0x0000000000000000   r12 = 0x00007f0fd09ddce0
	    r13 = 0x00007f0f8bfff9c0   r14 = 0x0000000000000000
	    r15 = 0x0000000000000003   rip = 0x00007f0fd43a6e9a
	    rsp = 0x00007f0f8bffeeb0   rbp = 0x0000000000000000
	    Found by: call frame info

	Loaded modules:
	0x00400000 - 0x0268dfff  phantomjs  ???  (main)
	0x7f0f8af4f000 - 0x7f0f8af60fff  n019004l.pfb  ???
	0x7f0f8afcb000 - 0x7f0f8b1d2fff  libnss_dns-2.15.so  ???
	0x7f0f8b1d3000 - 0x7f0f8b3d5fff  libnss_mdns4_minimal.so.2  ???
	0x7f0f8b3d6000 - 0x7f0f8b5e2fff  libnss_files-2.15.so  ???
	0x7f0f8b5e3000 - 0x7f0f8b7fcfff  libresolv-2.15.so  ???
	0x7f0fd0011000 - 0x7f0fd00abfff  DejaVuSansCondensed-Bold.ttf  ???
	0x7f0fd00ac000 - 0x7f0fd0149fff  DejaVuSansCondensed.ttf  ???
	0x7f0fd0171000 - 0x7f0fd0184fff  n019003l.pfb  ???
	0x7f0fd2a8a000 - 0x7f0fd2ce6fff  libssl.so.1.0.0  ???
	0x7f0fd2ce8000 - 0x7f0fd30befff  libcrypto.so.1.0.0  ???
	0x7f0fd30c3000 - 0x7f0fd338bfff  locale-archive  ???
	0x7f0fd338c000 - 0x7f0fd35b5fff  libexpat.so.1.5.2  ???
	0x7f0fd35b6000 - 0x7f0fd37ccfff  libz.so.1.2.3.4  ???
	0x7f0fd37cd000 - 0x7f0fd3b87fff  libc-2.15.so  ???
	0x7f0fd3b8d000 - 0x7f0fd3da2fff  libgcc_s.so.1  ???
	0x7f0fd3da3000 - 0x7f0fd409efff  libm-2.15.so  ???
	0x7f0fd409f000 - 0x7f0fd4389fff  libstdc++.so.6.0.16  ???
	0x7f0fd439f000 - 0x7f0fd45b7fff  libpthread-2.15.so  ???
	0x7f0fd45bc000 - 0x7f0fd47c3fff  librt-2.15.so  ???
	0x7f0fd47c4000 - 0x7f0fd49c7fff  libdl-2.15.so  ???
	0x7f0fd49c8000 - 0x7f0fd4bfdfff  libfontconfig.so.1.4.4  ???
	0x7f0fd4bfe000 - 0x7f0fd4e99fff  libfreetype.so.6.8.0  ???
	0x7f0fd4e9a000 - 0x7f0fd4ebbfff  ld-2.15.so  ???
	0x7f0fd5094000 - 0x7f0fd509cfff  945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-3  ???
	0x7f0fd50a8000 - 0x7f0fd50b0fff  6d41288fd70b0be22e8c3a91e032eec0-le64.cache-3  ???
	0x7f0fd50b1000 - 0x7f0fd50b9fff  e13b20fdb08344e0e664864cc2ede53d-le64.cache-3  ???
	0x7fff0a9fe000 - 0x7fff0a9fffff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
