### ISSUE TITLE
Investigate 64-bit Windows build

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#11991]
For 1.x we always build the Windows executable in 32-bit mode. For 2.x, let's take a look at the possibility of providing the 64-bit version.

**Comment by Vitallium** [comment]
Next version (2.5) will have a 64-bit version.

**Comment by jameysiddiqui** [comment]
I m looking or PhantomJs 64 bit version for windows, It seems 64 bit version will be available in 2.5 version of PhantomJs, Please let me know when i can expect the release.
