### ISSUE TITLE
Crashes when running mocha tests

### ISSUE THREAD

**Issue by theghostbel** [ariya/phantomjs#11993]
Our project has over 3500 tests. When running all of them under phantomjs it crashes. I couldn't get any data from crash dump, because it's empty. Here is "problem details" which windows 7 produces:

```
  Problem Event Name:	APPCRASH
  Application Name:	phantomjs.exe
  Application Version:	1.9.7.0
  Application Timestamp:	52e6936f
  Fault Module Name:	phantomjs.exe
  Fault Module Version:	1.9.7.0
  Fault Module Timestamp:	52e6936f
  Exception Code:	c0000005
  Exception Offset:	00057686
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1059
  Additional Information 1:	9b43
  Additional Information 2:	9b431b0c90e83ec68d3d9c2ff7e024e8
  Additional Information 3:	feb7
  Additional Information 4:	feb7fc1b4ccfe33f19ad35c220a990e4
```

If i try running only some test cases - it pass.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (215/200 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:58467 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkOa-003Jtk-66
	for andre@castonguay.org; Mon, 11 Apr 2016 18:33:24 -0400
Date: Mon, 11 Apr 2016 15:32:43 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460413964;
	bh=jQvik2/TBDpJGQQvhIkiRaawxkgz8vbasr1GKMppopw=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=pXJJNCRHPZjTdCqP0pg/Vovf36izrf1Ff32d35f/WAEQbyeJcfnP8M7Xn8IZYxalK
	 vfsxvA40wbrERrkrIkhTC/dvb5gk/IbSCzKs9vx08L2ps5d2SHVjtuz6BAeEBeLEdY
	 0FI4KFMf3QSpMX3SmANkgKvoIknUVm6PEEzvGXWw=

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (216/200 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:19378)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-cf68-andre=castonguay.org@sgmail.github.com>)
	id 1apkOa-003JtW-5e
	for andre@castonguay.org; Mon, 11 Apr 2016 18:33:25 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=BHXGHMyRDKY7S+GXVvoNv/sqNI8=; b=OqYgXIE1qQfrwYL/
	b6p1YokOM1viG1+Tn3nwHvWcu3i62abKdERULUJsc6rNx5H7f7JNUnAvlhZgBZWB
	5px03i6nFh9FymUJNz0b09eFr9F758POghbqlsqIT8vCDrRXN5OlAhwJVhKj4I80
	1p57qYdbTeMNScADe+83B5AZWEg=
Received: by filter0444p1mdw1.sendgrid.net with SMTP id filter0444p1mdw1.22280.570C260B48
        2016-04-11 22:32:43.778929899 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id jHephhC_RmKgaePuZfXP3g
	for <andre@castonguay.org>; Mon, 11 Apr 2016 22:32:43.628 +0000 (UTC)
Date: Mon, 11 Apr 2016 15:32:43 -0700
