### ISSUE TITLE
WOFF font support issues

### ISSUE THREAD

**Issue by benjigreig** [ariya/phantomjs#11992]
Have been testing cases this against recent builds of PhantomJS on Mac OS X and linux. We've discovered that PhantomJS seems to have an issue with OTF and/or Postscript data in WOFF files. WOFFs compiled from TTF data display fine however.

For us this has implications in being able to use commercially available web fonts which frequently have OTF and even Postscript encapsulated in them. At the moment PhantomJS seems not to handle these. :-( We'll keep trucking for a solution.

We have many test screenshots that bare this out. Hassle me if you'd like to see them.

**Comment by carlblock** [comment]
This issue seem to persist on phantom 2.0, compiled and run on Ubuntu x64 14.04 LTS

Here is an example of the Google font "Montserrat" in Google Chrome
![screen shot 2015-04-22 at 15 38 08](https://cloud.githubusercontent.com/assets/5603121/7275703/b868d57a-e905-11e4-98d6-496ab94fc3f9.png)

Here is the same in phantomjs 2.0
![Uploading Screen Shot 2015-04-22 at 15.37.55.png . . .]()
On the image you see that the P is cut on the right corner, same thing happens with other letters.

Also the google font "Oswald" doesn't render at all.

**Comment by istr** [comment]
For 2.0.0 this is probably [an issue with the build script only](https://github.com/ariya/phantomjs/issues/12682#issuecomment-160453120).

When building 2.0.0 [using this hint](https://github.com/ariya/phantomjs/issues/12682#issuecomment-68453670) @jory s regression test passes and works.

You might want to try out your own build with that tweak or use [my experimental pre-release builds](https://github.com/istr/phantomjs/releases/tag/2.0.1-regression-12506-testing) to verify.

**Comment by Vitallium** [comment]
@istr support for WOFF fonts has been landed to the master recently.

**Comment by istr** [comment]
@Vitallium Nice. :+1: Will try to build from master with the python based build script. Thanks for the hint.

**Comment by Vitallium** [comment]
PJS 2.5 has full support for WOFF and WOFF2 now
