### ISSUE TITLE
Always crashes from PHP, Perl, etc.

### ISSUE THREAD

**Issue by dmyshkin** [ariya/phantomjs#11999]
On our CentOS 6.5 system, PhantomJS always crashes when executed with a simple 'hello world' script when executed via PHP or Perl triggered from Apache. If the php or perl script is run from the command line, it works. Note that this problem does NOT happen on our Ubuntu 8.04 machine. We have tried both building from source and the binaries. We are using the 64 bit version. The 32 bit version does not run at all, gives ELF error.

Crash message:
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/7be7b6c1-232b-ad26-0bdc14c8-692edb4b.dmp

Perl script:
#!/usr/bin/perl
print "Content-type:text/html\r\n\r\n";
my $phantomjs = "/var/www/phantomjs /var/www/perl/testphantom.js";
$output = `$phantomjs`;
print($output);

PHP script:
<?
$result = system("/var/www/phantomjs testphantom.js");
    echo $result;
?>

testphantom.js:
console.log("hello world");
phantom.exit();

After trying to dump the symbols, this happens:
[root@prsgce-1 phantomjs-1.9.7-linux-x86_64-symbols]# ./minidump_stackwalk /tmp/7be7b6c1-232b-ad26-0bdc14c8-692edb4b.dmp .
2014-02-21 00:37:35: minidump_processor.cc:264: INFO: Processing minidump in file /tmp/7be7b6c1-232b-ad26-0bdc14c8-692edb4b.dmp
2014-02-21 00:37:35: minidump.cc:3775: INFO: Minidump opened minidump /tmp/7be7b6c1-232b-ad26-0bdc14c8-692edb4b.dmp
2014-02-21 00:37:35: minidump.cc:4046: ERROR: ReadBytes: read 0/32
2014-02-21 00:37:35: minidump.cc:3794: ERROR: Minidump cannot read header
2014-02-21 00:37:35: minidump_processor.cc:268: ERROR: Minidump /tmp/7be7b6c1-232b-ad26-0bdc14c8-692edb4b.dmp could not be read
2014-02-21 00:37:35: minidump.cc:3747: INFO: Minidump closing minidump

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (204/200 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:38822)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-cf68-andre=castonguay.org@sgmail.github.com>)
	id 1apkNf-003IMW-SK
	for andre@castonguay.org; Mon, 11 Apr 2016 18:32:29 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=OaReN4OlR1AK1hGcc365HUkisuc=; b=JPdtYqnjb2xa+rUe
	SZY7fb7QANXsC91ReAVNyjLprgtVaq7MBdId2qWSekvao0sH8T0LQ381q3+bIybJ
	729Fbha95DdosOgg8P3mV7PyZxjoriQzv7JWwoXwElLRNDFaNo5FDEZUytgMjNIK
	Y2LwwlIA1cbKeK0r49WEjjjoQWw=
Received: by filter0650p1mdw1.sendgrid.net with SMTP id filter0650p1mdw1.31451.570C25CE26
        2016-04-11 22:31:42.997621844 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id eoOm-AXKRvWd03hB7lfAXA
	for <andre@castonguay.org>; Mon, 11 Apr 2016 22:31:42.815 +0000 (UTC)
Date: Mon, 11 Apr 2016 15:31:42 -0700

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (202/200 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:36896)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-cf68-andre=castonguay.org@sgmail.github.com>)
	id 1apkNf-003IOM-Gz
	for andre@castonguay.org; Mon, 11 Apr 2016 18:32:28 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=66EXf87TpXpwaXp9vYXTCb02kr4=; b=uqFN4WJD2xzZskz8
	IfXN2ViQkSu2VyGRryqmmViD1CffKj9AfOQailLgpRaaA/SjQQSB3jJwNCd8MeuY
	Ju73nbdaMHhBf/sR0HlY4zf+kl+4fsYwEdPumBh4HeMWtw5nhkIwGYSyjA2VwTLc
	kI5t3MRN9EiNnOCE7SoLhfYDctA=
Received: by filter0828p1mdw1.sendgrid.net with SMTP id filter0828p1mdw1.26974.570C25D23A
        2016-04-11 22:31:46.675851303 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id SoVo4FurSN6-FPfeTrqumw
	for <andre@castonguay.org>; Mon, 11 Apr 2016 22:31:46.581 +0000 (UTC)
Date: Mon, 11 Apr 2016 15:31:43 -0700
