### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by eoftedal** [ariya/phantomjs#12007]
Crash reason:  SIGSEGV
Crash address: 0x0

Thread 0 (crashed)
 0  phantomjs!JSC::Yarr::YarrPatternConstructor::setupDisjunctionOffsets [YarrPattern.cpp : 734 + 0x0]
    eip = 0x08bb10f4   esp = 0xbff49200   ebp = 0xbff49298   ebx = 0x0a4f62bc
    esi = 0xb66f0c80   edi = 0xb4f19a20   eax = 0xbff49618   ecx = 0x00000000
    edx = 0xbff49480   efl = 0x00010282
    Found by: given as instruction pointer in context
 1  phantomjs!JSC::Yarr::YarrPatternConstructor::setupDisjunctionOffsets [YarrPattern.cpp : 701 + 0x16]
    eip = 0x08bb17ee   esp = 0xbff492a0   ebp = 0xbff49338   ebx = 0x0a4f62bc
    esi = 0xb66f0c80   edi = 0xb4f19a20
    Found by: call frame info
 2  phantomjs!JSC::Yarr::YarrPattern::compile [YarrPattern.cpp : 701 + 0x16]
    eip = 0x08bbabec   esp = 0xbff49340   ebp = 0xbff495a8   ebx = 0x0a4f62bc
    esi = 0xb554a500   edi = 0xb4f19a20
    Found by: call frame info
 3  phantomjs!JSC::Yarr::YarrPattern::YarrPattern [YarrPattern.cpp : 1008 + 0xe]
    eip = 0x08bbb758   esp = 0xbff495b0   ebp = 0xbff495e8   ebx = 0x0a4f62bc
    esi = 0xbff49654   edi = 0xbff49648
    Found by: call frame info
 4  phantomjs!JSC::RegExp::compile [RegExp.cpp : 105 + 0x30]
    eip = 0x08cac276   esp = 0xbff495f0   ebp = 0xbff49688   ebx = 0x0a4f62bc
    esi = 0x00000000   edi = 0xb54e0f00
    Found by: call frame info
 5  phantomjs!JSC::RegExp::create [RegExp.cpp : 87 + 0xe]
    eip = 0x08cac887   esp = 0xbff49690   ebp = 0xbff496d8   ebx = 0x0a4f62bc
    esi = 0xb54e0f00   edi = 0xb54e0f18
    Found by: call frame info
 6  phantomjs!JSC::RegExpCache::create [RegExpCache.cpp : 48 + 0x1f]
    eip = 0x08cb0dcd   esp = 0xbff496e0   ebp = 0xbff49748   ebx = 0x0a4f62bc
    esi = 0xbff49830   edi = 0xb5791394
    Found by: call frame info
 7  phantomjs!JSC::RegExpCache::lookupOrCreate [RegExpCache.cpp : 41 + 0x33]
    eip = 0x08cb16cc   esp = 0xbff49750   ebp = 0xbff497d8   ebx = 0x0a4f62bc
    esi = 0xbff49830   edi = 0xb5791394
    Found by: call frame info
8  phantomjs!JSC::constructRegExp [RegExpConstructor.cpp : 320 + 0x25]
    eip = 0x08cab2ff   esp = 0xbff497e0   ebp = 0xbff49848   ebx = 0x0a4f62bc
    esi = 0xb4d2d9c8   edi = 0xb4414550
    Found by: call frame info
 9  phantomjs!JSC::constructWithRegExpConstructor [RegExpConstructor.cpp : 329 + 0x12]
    eip = 0x08cab735   esp = 0xbff49850   ebp = 0xbff49888   ebx = 0x0a4f62bc
    esi = 0xb58001b0   edi = 0xb4414550
    Found by: call frame info
10  phantomjs!JSC::cti_op_construct_NotJSConstruct [JITStubs.cpp : 2325 + 0x5]
    eip = 0x08c37a44   esp = 0xbff49890   ebp = 0xbff49908   ebx = 0x0a4f62bc
    esi = 0xb4414550   edi = 0xb4414550
    Found by: call frame info
11  0xb4d0d4ea
    eip = 0xb4d0d4eb   esp = 0xbff49910   ebp = 0xbff49958   ebx = 0xb4c85960
    esi = 0x000001fc   edi = 0xb5800158
    Found by: call frame info
12  phantomjs!JSC::Interpreter::execute [JITCode.h : 77 + 0x25]
    eip = 0x08c02b41   esp = 0xbff49960   ebp = 0xbff499e8
    Found by: previous frame's frame pointer
13  phantomjs!JSC::evaluate [Completion.cpp : 64 + 0x2d]
    eip = 0x08147943   esp = 0xbff499f0   ebp = 0xbff49a48   ebx = 0x0a4f62bc
    esi = 0xb4c3d2c8   edi = 0xb5db4910
    Found by: call frame info
14  phantomjs!WebCore::ScriptController::evaluateInWorld [JSMainThreadExecState.h : 54 + 0x20]
    eip = 0x0817ade9   esp = 0xbff49a50   ebp = 0xbff49af8   ebx = 0x0a4f62bc
    esi = 0x0a51a354   edi = 0x00000000
    Found by: call frame info
15  phantomjs!WebCore::ScriptController::evaluate [ScriptController.cpp : 167 + 0x1e]
    eip = 0x0817b0d9   esp = 0xbff49b00   ebp = 0xbff49b18   ebx = 0x0a4f62bc
    esi = 0xbff49b44   edi = 0xb6631388
    Found by: call frame info
16  phantomjs!WebCore::ScriptElement::executeScript [ScriptElement.cpp : 283 + 0x1a]
    eip = 0x08d645ed   esp = 0xbff49b20   ebp = 0xbff49b58   ebx = 0x0a4f62bc
    esi = 0xb55cb984   edi = 0xb6631388
    Found by: call frame info
phantomjs!WebCore::HTMLScriptRunner::executePendingScriptAndDispatchEvent [HTMLScriptRunner.cpp : 139 + 0xe]
    eip = 0x0841b8dc   esp = 0xbff49b60   ebp = 0xbff49be8   ebx = 0x0a4f62bc
    esi = 0xb54d8200   edi = 0xb54d81f8
    Found by: call frame info
18  phantomjs!WebCore::HTMLScriptRunner::executeParsingBlockingScript [HTMLScriptRunner.cpp : 118 + 0x14]
    eip = 0x0841cf91   esp = 0xbff49bf0   ebp = 0xbff49cb8   ebx = 0x0a4f62bc
    esi = 0x00000000   edi = 0xb54d81f8
    Found by: call frame info
19  phantomjs!WebCore::HTMLScriptRunner::execute [HTMLScriptRunner.cpp : 195 + 0x7]
    eip = 0x0841d523   esp = 0xbff49cc0   ebp = 0xbff49cd8   ebx = 0x0a4f62bc
    esi = 0xb54d8200   edi = 0xb54d81f8
    Found by: call frame info
20  phantomjs!WebCore::HTMLDocumentParser::runScriptsForPausedTreeBuilder [HTMLDocumentParser.cpp : 205 + 0x15]
    eip = 0x08411bd3   esp = 0xbff49ce0   ebp = 0xbff49d18   ebx = 0x0a4f62bc
    esi = 0xb5448000   edi = 0xbff49cfc
    Found by: call frame info
21  phantomjs!WebCore::HTMLDocumentParser::canTakeNextToken [HTMLDocumentParser.cpp : 223 + 0x7]
    eip = 0x08411cda   esp = 0xbff49d20   ebp = 0xbff49d38   ebx = 0x0a4f62bc
    esi = 0xb5448000   edi = 0xbff49d8c
    Found by: call frame info
22  phantomjs!WebCore::HTMLDocumentParser::pumpTokenizer [HTMLDocumentParser.cpp : 261 + 0x15]
    eip = 0x08412f4c   esp = 0xbff49d40   ebp = 0xbff49db8   ebx = 0x0a4f62bc
    esi = 0xb544805c   edi = 0xb5448000
    Found by: call frame info
23  phantomjs!WebCore::HTMLDocumentParser::notifyFinished [HTMLDocumentParser.cpp : 175 + 0xf]
    eip = 0x08413b5d   esp = 0xbff49dc0   ebp = 0xbff49de8   ebx = 0x0a4f62bc
    esi = 0xb5448000   edi = 0x00000001
    Found by: call frame info
24  phantomjs!WebCore::CachedResource::checkNotify [CachedResource.cpp : 144 + 0xb]
    eip = 0x0848c81c   esp = 0xbff49df0   ebp = 0xbff49e38   ebx = 0x0a4f62bc
    esi = 0xb55cdd80   edi = 0xbff49e18
    Found by: call frame info
25  phantomjs!WebCore::CachedScript::data [CachedScript.cpp : 104 + 0x7]
    eip = 0x0848f42e   esp = 0xbff49e40   ebp = 0xbff49e58   ebx = 0x0a4f62bc
    esi = 0x00000000   edi = 0xb55cdd80
    Found by: call frame info
26  phantomjs!WebCore::CachedResourceRequest::didFinishLoading [CachedResourceRequest.cpp : 166 + 0x36]
    eip = 0x08e324e3   esp = 0xbff49e60   ebp = 0xbff49e98   ebx = 0x0a4f62bc
    esi = 0x0848f3a0   edi = 0xb55c8570
    Found by: call frame info

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
