### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by avant1** [ariya/phantomjs#12006]
Got message like 
<pre>
pure virtual method called
PhantomJS has crashed. Please file a bug report at...
</pre>

so, i'm here.

I have converted crush dump file and seems like it contains stack trace. Hope this will be helpful:
http://textuploader.com/1us6

P.S. Your product is awesome

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
