### ISSUE TITLE
Support window.outerHeight and window.outerWidth

### ISSUE THREAD

**Issue by stof** [ariya/phantomjs#12010]
While trying [MinkSelenium2Driver](https://github.com/Behat/MinkSelenium2Driver/) tests against PhantomJS/Ghostdriver, I discovered that `window.outerHeight` and `window.outerWidth` are not implemented (evaluating them returns `0`) while `window.innerHeight` and `window.innerWidth` are working properly.
Could it be possible to support them (potentially with the same values if you consider that the browser is chromeless) ?

**Comment by rbolton240** [comment]
I am seeing this issue and as a result the responsive nature of the website I am trying to screen capture is not adjusting (because the outwidth is being incorrectly detected).
