### ISSUE TITLE
font-family fallback fonts not respected -- default font used if first one not found

### ISSUE THREAD

**Issue by dlopuch** [ariya/phantomjs#12011]
The font-family CSS definition can list a few fonts.  The browser [is supposed to](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) "select the first font on the list that is installed on the computer"

I've noticed that when the first font can't be loaded, none of the fallback fonts are attempted either.  Possibly related to #10592 ("Web Fonts do not render, use fallback fonts instead"), but that one seems to be focused on webfont support whereas this issue is pointing out that phantom is not doing what it should on a font-family CSS definition, regardless of webfont or not.

Reproduced on ubuntu and os-x using Phantom 1.9.7.

**REPRODUCE:**
- Make sure you have a unique font installed, for example the beautiful and open [Gentium](http://scripts.sil.org/cms/scripts/page.php?item_id=Gentium_download)
  - On ubuntu, verify it's installed with `$ fc-list | grep -i gentium`
- Create a demo HTML file with a font-family list to rasterize with phantom:

phantom-no-fallback-demo.html

``` html
<html>
  <head> <title>Testing Phantom Font Support</title> </head>
  <style>
.family-with-fallback {
  font-family: "some font that does not exist", "Gentium", arial;
}
.size-36 {  font-size: 36; }
.size-28 {  font-size: 28; }
  </style>
  <body style="background-color: white;">
    <div class="size-36">Default font @ 36.  Next line Gentium.</div>
    <div class="size-36 family-with-fallback">
      The Quick Brown Fox Jumped Over the Lazy Dog
    </div>
    <div class="size-28 family-with-fallback">
      0123456789 <br/>
      ABCDEFGHIJKLMNOPQRSTUVWXYZ<br/>
      abcdefghijklmnopqrstuvwxyz
    </div>
  </body>
</html>
```

phantom-no-fallback-demo.js:

``` javascript
var system = require("system"),
    page = require("webpage").create();

page.viewportSize = {
  width:  1000,
  height: 100
};

page.open("./phantom-no-fallback-demo.html", function(status) {
    if ("fail" == status) {
        console.log("error Cannot load service page.");
    } else {
        page.render("font-test.png");
        console.log("Screen grab success.  Look for 'font-test.png' to see output.");
    }
    phantom.exit();
});
```
- Run the script: `$ phantomjs phantom-no-fallback-demo.js` and look at `font-test.png`

**EXPECTED:**
- Phantom should have fallen back to the second font in the font-family list (Gentium in this example)
- In Chrome, it looks as expected:
  ![screen shot 2014-02-25 at 3 11 54 pm](https://f.cloud.github.com/assets/1427329/2264440/3e4534fc-9e72-11e3-8f37-f750e0993461.png)

**ACTUAL:**
- Phantom just uses a default font after it can't find the first one:
  ![font-test](https://f.cloud.github.com/assets/1427329/2264459/7a0dfeb0-9e72-11e3-9b99-11a0429deb4b.png)
- If you change the `.family-with-fallback` definition to make Gentium or whatever the first font in your list, it works:
  ![font-test-right](https://f.cloud.github.com/assets/1427329/2264479/cb924ca0-9e72-11e3-9129-7fc4171bf4fa.png)

Conclusion is that phantom only tries the first font-family item instead of falling back across the entire list.

**Comment by LeonardoGentile** [comment]
+1
getting the same problem

**Comment by kamalbennani** [comment]
+1

**Comment by qiushengxy** [comment]
+1

**Comment by alex88** [comment]
This still exists, I've tried to include Source Han Sans and it doesn't work properly.
For example if the font family is:

```
font-family: 'Titillium Web,source-han-sans-simplified-c,sans-serif'
```

it works fine on the browser, in phantomjs it doesn't, if I use instead

```
font-family: 'source-han-sans-simplified-c'
```

it works fine on phantomjs too

**Comment by gildonei** [comment]
+1 
and I partially solved this problem installing the font in Linux under /usr/share/fonts/truetype/font-name/file.ttf and cleaning up cache with fc-cache -fv

**Comment by hudhaifas** [comment]
+1
I am using a custom font that covers a specific letters cases, and need the fallback font to be used with other cases.
