### ISSUE TITLE
random error

### ISSUE THREAD

**Issue by satistest** [ariya/phantomjs#12019]
I get these error sometimes while trying to use phantoms rasterize.js to output html page to pdf, meanwhile it still outputs the pdf correctly.   I am using phantoms 1.9.6

2014-02-28 13:52:00.643 phantomjs[13070:d07] **\* WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
Feb 28 13:52:01  phantomjs[13070] <Error>: CGContextSetShouldAntialias: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 28 13:52:01  phantomjs[13070] <Error>: CGContextSetShouldSmoothFonts: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 28 13:52:01 phantomjs[13070] <Error>: CGContextSetFillColorSpace: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 28 13:52:01 phantomjs[13070] <Error>: CGContextSetFillColor: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by MichaelMallett** [comment]
I'm getting this on Yosemite using v2.0.0 of phantomjs

Attempting to use Wraith visual diff capture
