### ISSUE TITLE
Crash report: pure virtual method called (v1.9.1)

### ISSUE THREAD

**Issue by sniemetz** [ariya/phantomjs#12026]
version 1.9.1
running on EC2 ubuntu 12.04 SMP (2 procs)

happens randomly

pure virtual method called
terminate called without an active exception

dump file
https://dl.dropboxusercontent.com/u/81807220/5a75210f-9fa3-72c8-5b100f1c-5b2ae003.dmp

not sure this helps (sorry not a C dev)
http://www.artima.com/cppsource/pure_virtual.html

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
