### ISSUE TITLE
Crash in RSpec

### ISSUE THREAD

**Issue by hamchapman** [ariya/phantomjs#12031]
Link to the crash dump: http://www.sendspace.com/file/tv6mss

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (203/200 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:41267 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkNg-003IPj-4E
	for andre@castonguay.org; Mon, 11 Apr 2016 18:32:28 -0400
Date: Mon, 11 Apr 2016 15:31:47 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460413907;
	bh=8nUTLZJtvS4LmQJi0m8R/GA9Odz8pzvaMN+qPtWgySY=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=cBOLsemJeYwI9uMyk0LUXgK/t6427H3gdyTXYcGUn3znCNk78DBNz1MvwzOi63/Bp
	 GmTAVazTINQGTLA6aHq4isGRMtOMo4rM44vZX9HI1NWVggW267ZXXl4UwuwX4nfaPD
	 3elSdpE5yODK3G2GthEGl4EIMn1Chs5xMHEDvgSk=

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (205/200 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:26777)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-cf68-andre=castonguay.org@sgmail.github.com>)
	id 1apkNi-003IQu-0l
	for andre@castonguay.org; Mon, 11 Apr 2016 18:32:31 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=OMvP6kbJ4AG0KUR+AZ5EMziPJkM=; b=CQj0EciVrkN0h0NC
	KXl3jL2byvSVnxcSr9xhdqSlipWW5sURekqKxKdEea1j+gJ2Arx0ev4t782S0/0c
	GXrzblgF9vGGSH4lbOSwfEKdwGcfd1RJCqOiGl20vr0yBaRdR3vjFOAvycRb5O3C
	BwswjAQ4nqH9pfb95n1AUYzgEz8=
Received: by filter0502p1mdw1.sendgrid.net with SMTP id filter0502p1mdw1.12434.570C25D44A
        2016-04-11 22:31:48.655936757 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id CKCltDZYQwqXx4jWPwnn-w
	for <andre@castonguay.org>; Mon, 11 Apr 2016 22:31:48.527 +0000 (UTC)
Date: Mon, 11 Apr 2016 15:31:48 -0700
