### ISSUE TITLE
PhantomJS has crashed : Too many open files

### ISSUE THREAD

**Issue by Siltaar** [ariya/phantomjs#12037]
Hello,

I'm using PhantomJS to test the scalability of a web site, simulating 200 users. Trying to simulate more, I get such messages at arround 230 spawn phantomjs from a master phantomjs thread :

ExceptionHandler::GenerateDump                                        sys_pipe failed:Trop de fichiers ouverts (Too many open files)
ExceptionHandler::SendContinueSignalToChild                                sys_write failed:Mauvais descripteur de fichier (Bad file descriptor)
ExceptionHandler::WaitForContinueSignal                                sys_read failed:Mauvais descripteur de fichier (Bad file descriptor)
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/7da0bcb0-5337-a83a-1c48c10f-6ca94666.dmp

(Translations between parenthesis are mine)

Unfortunately, I have nothing new in my /tmp file after that, while many giga bytes are available on the disk.

All in all, I would be happy to be able to launch 1024 sub-phantomjs-threads  for instance.

**Comment by PatrickHuetter** [comment]
+1 Same problem here!

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (206/200 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:43075 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkNm-003Icb-Qs
	for andre@castonguay.org; Mon, 11 Apr 2016 18:32:35 -0400
Date: Mon, 11 Apr 2016 15:31:54 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460413914;
	bh=0ZALVdErvXj5SiC/i8fTlJfzAji+RNv2D+qdQ7vdwsM=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=1yzRG1irxMmsxoc2Q19u5hYcKT2h6C6lYXNdBmcWchyPg6lqwRHzsIt4I9/U2EVjS
	 /KtWiF1FMao67HSCqto7IblqvFOCp+I/ie3PyJUyOgp2dx5Bk6/FL/Pg4AoWn0LppS
	 HUej2Gg/gD4nkw6kO+eeOV3ZggPPJZZzfShDvGqg=

**Comment by Toybreak** [comment]
why closed?

**Comment by matths** [comment]
just a guess, but it could be also dependent on the "open file limit" set for your main thread / sub threads? see http://stackoverflow.com/questions/15005830/phantomjs-using-too-many-threads
