### ISSUE TITLE
Phantom crash 

### ISSUE THREAD

**Issue by judax** [ariya/phantomjs#12038]
While performing an automated navigation on 'http://www.laredoute.com/' using casperjs that uses over phantomjs, I got this error on the console:

phantomjs(20989,0xac632a28) malloc: *** mmap(size=536870912) failed (error code=12)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/36E910D4-9848-4B54-AC0A-2A21F9EBE2EC.dmp

Attached the dump file with the extension changed to PNG (github does not allow me to attach the DMP file).

![36e910d4-9848-4b54-ac0a-2a21f9ebe2ec dmp](https://f.cloud.github.com/assets/5706282/2347171/283adbec-a54a-11e3-9d13-5df03a6c6d88.png)

Thank you.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (207/200 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:36129 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkNo-003IgO-6Q
	for andre@castonguay.org; Mon, 11 Apr 2016 18:32:36 -0400
Date: Mon, 11 Apr 2016 15:31:55 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460413916;
	bh=lzTmNRGx5Vszt3L0GHr8ZybjEJb5ST8wbPo0h+od5DY=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=q4sYA6to9TeWkNLnj1ekQThmM0eJV+8FcrNMpqLBAs7tAnHjXOCfNC/jjTEotAGo/
	 vXtMvxb9ttP8HOHgsKSTDJGsT0FMzQGyqTcnJz78H46mcoNIh+56/69Q2EuDzMq/z9
	 mhZe6Ama68ClK4Fu2DBZy/zfX4yYniAszaBVIHHI=

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (208/200 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:43832 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkNp-003IhT-J7
	for andre@castonguay.org; Mon, 11 Apr 2016 18:32:38 -0400
Date: Mon, 11 Apr 2016 15:31:57 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460413917;
	bh=0WKMJpFTfs4hnVvY3Lh+1Lqg7Xi0zVliVswL3IaZJ0g=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=b/GN+C8W9R3MavcDjGQCIyNjA/8AzHZUrPdwdoshmDHiORGbtsBhl1ePIB59WWOwK
	 vm2eM1Vm0udvDxe7ZhIycHGtaaSKc7JZoq1KuTCGhluo9h84RfN8mJPDppvknkaP1H
	 w72bMYo/e7HVGj+FIeT1mnXD/3Rxqr1HbHliuUAg=
