### ISSUE TITLE
(1.9.1 Linux) GLib-ERROR **: Creating pipes for GWakeup: Too many open files

### ISSUE THREAD

**Issue by sniemetz** [ariya/phantomjs#12036]
Hi all

I've never seen this error before: 

Phantom crashed but without the usual crash message. Instead I see

(phantomjs:7980): GLib-ERROR **: Creating pipes for GWakeup: Too many open files

I tried searching but found nothing related to PhantomJS - Can someone point me in the right direction? Am I doing something wrong here? Do I have a non-phantom problem on my EC2 instance?

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
