### ISSUE TITLE
xfonts break webfont-rendering

### ISSUE THREAD

**Issue by tholu** [ariya/phantomjs#12049]
Environment:
- Debian 7.4 Server
- PhantomJS 1.9.0-1.9.7 and built from current source

Test page:
- https://www.google.com/fonts/specimen/Droid+Sans

Expected result:
- Webfonts renders properly

Actual result:
- Webfont text was rendered as squares/boxes (see screenshot).

Fixed by:
- Removing xfonts-100dpi, xfonts-base, xfonts-75dpi

![droid](https://f.cloud.github.com/assets/316763/2387104/7e950b2e-a933-11e3-8ae2-f66bad44b17e.png)

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thanks!
