### ISSUE TITLE
Unable to specify localStoragePath

### ISSUE THREAD

**Issue by allbinmani** [ariya/phantomjs#12041]
The path passed to QWebSettings->setLocalStoragePath() in webpage.cpp is hardcoded to QDesktopServices::DataLocation

This prevents setting any localStoragePath in a config file or specifying --local-storage-path on the cmdline.

The pull request #12042  I have created allows specifying localStoragePath properly

**Comment by Vitallium** [comment]
Fixed in https://github.com/ariya/phantomjs/commit/bc294d38d2618a24acc420f2da7a49061da82f5d
