### ISSUE TITLE
Cannot stub window.matchMedia / inconsistent behavior

### ISSUE THREAD

**Issue by PVince81** [ariya/phantomjs#12069]
Running PhantomJS 1.9.2 (Linux) with Sinon, it looks like it's not possible to properly overwrite the function window.matchMedia.

Try this:

```
var matchMediaStub = sinon.stub();
window.matchMedia = matchMediaStub;
matchMediaStub.returns(false);

console.log(window.matchMedia());
console.log(window.matchMedia().matches);

var mq = window.matchMedia();
console.log(mq);
console.log(mq.matches);

```

This returns:

```
LOG: {media: '(max-width: 600px)', matches: true}
LOG: true
LOG: {media: 'undefined', matches: false}
LOG: false
```

The stub itself doesn't define "media" but yet it automatically defines itself.
Also, assigning the result of "matchMedia()" to a variable has a different result.

Weird stuff!

Note: I suppose sinon.stub() could be replaced with function() { return {matches: true;} };

**Comment by mrchief** [comment]
Your stub is not right (as you noted later). Here's the correct stub

```js
matchMediaStub().returns({
    matches : false,
    addListener : spy(),  // or stub as per need
    removeListener: spy()  // or stub as per need
})
```
