### ISSUE TITLE
Encoding of external scripts not necessarily consistent with host page

### ISSUE THREAD

**Issue by nanodeath** [ariya/phantomjs#12065]
Here's the gist of the problem.  The first time you load a script, it appears to be decoded by the host page's encoding and then cached in a charset-indifferent way.  If you load another page that references the same script, but has a different encoding, the script isn't re-decoded; it's served as is, with the original decoding, which results in encoding inconsistencies.  This has noticeable adverse effects when the script contains UTF-8 (or any other non-ASCII) characters and it's used in either the host page directly or in another script that's not running in the same encoding, or vice versa (page has UTF-8 character and script tries to use it).

Here is my simple, if somewhat verbose, test case:

``` javascript
// bootstrap.js
// Just a little PhantomJS script to load the test pages
var system = require('system');
var args = system.args;

var webPage = require('webpage');

function loadPage(idx) {
        if(idx >= args.length) {
                phantom.exit(0);
        }
        var filename = args[idx];
        var page = webPage.create();

        page.onConsoleMessage = function(msg, lineNum, sourceId) {
          console.log('  CONSOLE: ' + msg);
        };

        console.log(filename);
        page.open(filename, function(status) {
          page.close();
          loadPage(++idx);
        });
}

loadPage(1);
```

``` javascript
// test.js - We want this to always emit "Yes"
console.log("Symbol matches? " + ("¤" === symbol ? "Yes :)" : "No :("));
```

``` html
<!DOCTYPE html>
<html class="no-js">
    <!-- with_charset.html -->
    <head>
        <meta charset="utf-8">
        <title></title>
        <script>
                symbol = "¤";
        </script>
        <script src="test.js"></script>
    </head>
    <body>
    </body>
</html>
```

``` html
<!DOCTYPE html>
<html class="no-js">
    <!-- without_charset.html -->
    <head>
        <title></title>
        <script>
                symbol = "¤";
        </script>
        <script src="test.js"></script>
    </head>
    <body>
    </body>
</html>
```

If you run `phantomjs bootstrap.js without_charset.html`, you get this output:

```
without_charset.html
  CONSOLE: Symbol matches? Yes :)
```

If you run `phantomjs bootstrap.js without_charset.html`, you get this output:

```
with_charset.html
  CONSOLE: Symbol matches? Yes :)
```

But run them both `phantomjs bootstrap.js with_charset.html without_charset.html`, you get this output:

```
with_charset.html
  CONSOLE: Symbol matches? Yes :)
without_charset.html
  CONSOLE: Symbol matches? No :(
```

or in the other order `phantomjs bootstrap.js without_charset.html with_charset.html`

```
without_charset.html
  CONSOLE: Symbol matches? Yes :)
with_charset.html
  CONSOLE: Symbol matches? No :(
```

I've verified this in PhantomJS 1.9.7, f3cd4ecfa9 (tip of the 1.9 branch), and e9a47eddee (tip of master).

**Comment by tinyx** [comment]
Running into exactly the same issue here. Any thoughts?
