### ISSUE TITLE
Handling of className in SVG nodes

### ISSUE THREAD

**Issue by fforw** [ariya/phantomjs#12072]
In a real browser, the className attribute is not a simple string for all the SVG elements, but an SVGAnimatedString which has to be read by reading elem.className.baseVal and written to by using setAttribute (property write access is either ignored or throws a TypeError in browsers)

I'm not sure this is something you would consider within the scope of phantomjs, but it is a clear deviation from standardized browser behavior.

**Comment by Spaxe** [comment]
FYI: Mocha-Phantomjs (v3.5.8) seems to handle className properly, that is, when you write to `className`, it does nothing.

**Comment by zackw** [comment]
The code responsible for `className` is part of Webkit; the version of Webkit in PhantomJS 1.x is rather old and won't be updated further. PhantomJS 2.0 has a much newer Webkit which may have fixed these problems, but without a self-contained test case, I can't easily check. Would any of you mind testing PhantomJS 2.0 and letting us know whether it resolves these problems?

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thanks!
