### ISSUE TITLE
capture not showing radio/checkboxes on forms when outputting pdf on os x

### ISSUE THREAD

**Issue by brianyoungblood** [ariya/phantomjs#12083]
PDF version of screen capture not showing radio or checkboxes on os x.

phantomjs 1.9.7
OS X 10.9.2 (13C64)

```
#shows checkbox and radios
phantomjs rasterize.js 'http://www.w3schools.com/html/html_forms.asp' formtest.png

#does not show checkbox and radios
phantomjs rasterize.js 'http://www.w3schools.com/html/html_forms.asp' formtest.pdf
```

**Comment by coryfklein** [comment]
As mentioned [here](https://github.com/ariya/phantomjs/issues/10601), styling select controls with css (by adding a border, for example) causes them to be rendered correctly. This may work with checkboxes, if you have control over the rendered content.

**Comment by fbernhard** [comment]
Thanks, coryfklein. 

Adding a border with CSS does not fix my particular issue.

We want to create "retina display" screenshots using the following style injection on page.evaluate()

```
document.body.style.webkitTransformOrigin = "0% 0%";
document.body.style.webkitTransform = "scale(2)";
document.body.style.width = "50%";
```

The "scale(2)" property causes the checkboxes and radio buttons to be displayed at the wrong place, i.e. they are not transformed. Without these transformations it works fine.

**Comment by cmdcolin** [comment]
The radio buttons do seem to show up using phantoms 2.0 with pdf output. I'm using osx and phantomjs 2.0 binaries downloaded from the site.

**Comment by brianyoungblood** [comment]
Tested with phantom 2.0 on OS X Yosemite 10.10.5. Radio is rendering now.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://jungesleben.com/oversee.php?xiw>

 

klaus@hebsgaard.dk
