### ISSUE TITLE
UTF-8 characters not displaying 1.9.7 Centos 6.5 32bit

### ISSUE THREAD

**Issue by dmeagor** [ariya/phantomjs#12118]
Downloaded 1.9.7 and installed the prerequisites as instructed (successfully, no errors.)  

sudo yum install fontconfig freetype libfreetype.so.6 libfontconfig.so.1 libstdc++.so.6

Then run the rasterize script

/home/phantomjs-1.9.7-linux-i686/bin/phantomjs /home/phantomjs-1.9.7-linux-i686/examples/rasterize.js "http://www.yahoo.jp/" test.png A4

The result is an output with all non-english characters missing or replaces with junk.
![yahoo_jp](https://cloud.githubusercontent.com/assets/714902/2622605/eae60804-bcbc-11e3-945c-5bfd40bf01dc.png)

**Comment by inhumantsar** [comment]
We ran into this issue on CentOS 6.5 x86_64 and found that installing ImageMagick resolved this problem.
