### ISSUE TITLE
1.9.7 consistently crashes while loading wikipedia search page

### ISSUE THREAD

**Issue by reinpk** [ariya/phantomjs#12119]
I'm running Mac OSX 10.9.2 with a standard build. I tried to extract the stack trace, but the instructions for minidump_stackwalk didn't produce any hash to continue with the instructions, sorry about that!

Here's the dump:
https://dl.dropboxusercontent.com/u/682022/C53A30B8-C38B-40C1-86EC-8D3F413DE31B.dmp

The fastest way to reproduce is just call `.open("http://en.wikipedia.org/wiki/Special:Search?search=&go=Go")`

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
