### ISSUE TITLE
Unicode space characters like thin-space are rendered as boxes

### ISSUE THREAD

**Issue by gthb** [ariya/phantomjs#12111]
See list of the various unicode space characters at https://www.cs.tut.fi/~jkorpela/chars/spaces.html

Rendering that page using:

`phantomjs examples/rasterize.js https://www.cs.tut.fi/~jkorpela/chars/spaces.html A4 1`

... yields missing-glyph squares in place of almost all the space characters (all but the first two, SPACE and NO-BREAK SPACE):

![phantom-spaces](https://cloud.githubusercontent.com/assets/153580/2605434/4dfd2640-bb44-11e3-81f3-e9b9b613a672.png)

Instead, phantomjs should treat these spaces like browsers do; e.g. here's Chrome:

![screen shot 2014-04-03 at 15 28 34](https://cloud.githubusercontent.com/assets/153580/2605471/b18ceeac-bb44-11e3-8715-46e4c2aaab44.png)

**Comment by bekicot** [comment]
+1
