### ISSUE TITLE
Phantomjs : a real Web Browser Network Configuration ?

### ISSUE THREAD

**Issue by jefleponot** [ariya/phantomjs#12131]
When I use firefox, Midori, Opera or Chrome (Not IE :-p), I don't mind of the network configurations.
Why ?
Because Browsers know if proxy is required (with automatic detection or manual detection). The best configuration can be done with a pas file.

Phamtonjs don't do that.

So I add just a file called "networkproxyfactory.cpp" who forks if a "no-proxy" option is enable .
I have to tests in a scenario web intranet application with internet javascript and jsonp.

Usage:
   phantomjs [switchs] [options] [script] [argument [argument [...]]]

Options:
  --no-proxy=<val>                     Specifies the proxy exceptions, '127.0.0.1, localhost' (default)

phantomjs --proxy="http://dirproxy.gouv.eu:8080" --no-proxy=".intranet" script.js

**Comment by jefleponot** [comment]
not at all. just filters proxy : *.test, *.intranet

**Comment by jairoiglesias** [comment]
no-proxy command line not avaible in version 2.1.1 ??

**Comment by kriegaex** [comment]
We also need this feature, is there any problem or concern against merging it into master?
