### ISSUE TITLE
click button and crashed

### ISSUE THREAD

**Issue by thomas-lkf** [ariya/phantomjs#12146]
* I click "Create Post"

                                                                                                                          
  [WebDriverCurlException]                                                                                                
  Curl error thrown for http GET to http://127.0.0.1:4444/wd/hub/session/99a8d040-c24b-11e3-88df-83f81cb67fb9/screenshot  
                                                                                                                          
  Failed connect to 127.0.0.1:4444; Connection refused                                                                    
                                                                                                                          

Exception trace:
 () at /home/luhya/thomas/business/popsugar/dev/web/vendor/facebook/webdriver/lib/WebDriverExceptions.php:39
 WebDriverException::throwException() at /home/luhya/thomas/business/popsugar/dev/web/vendor/facebook/webdriver/lib/remote/HttpCommandExecutor.php:230
 HttpCommandExecutor::curl() at /home/luhya/thomas/business/popsugar/dev/web/vendor/facebook/webdriver/lib/remote/HttpCommandExecutor.php:153
 HttpCommandExecutor::remoteExecute() at /home/luhya/thomas/business/popsugar/dev/web/vendor/facebook/webdriver/lib/remote/HttpCommandExecutor.php:117
 HttpCommandExecutor->execute() at /home/luhya/thomas/business/popsugar/dev/web/vendor/facebook/webdriver/lib/remote/RemoteWebDriver.php:240
 RemoteWebDriver->takeScreenshot() at /home/luhya/thomas/business/popsugar/dev/web/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:161
 Codeception\Module\WebDriver->_saveScreenshot() at /home/luhya/thomas/business/popsugar/dev/web/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:115
 Codeception\Module\WebDriver->_failed() at /home/luhya/thomas/business/popsugar/dev/web/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:48
 Codeception\Subscriber\Module->failed() at n/a:n/a
 call_user_func() at /home/luhya/thomas/business/popsugar/dev/web/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:164
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /home/luhya/thomas/business/popsugar/dev/web/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:53
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /home/luhya/thomas/business/popsugar/dev/web/vendor/codeception/codeception/src/Codeception/PHPUnit/Listener.php:73
 Codeception\PHPUnit\Listener->fire() at /home/luhya/thomas/business/popsugar/dev/web/vendor/codeception/codeception/src/Codeception/PHPUnit/Listener.php:30
 Codeception\PHPUnit\Listener->addError() at /home/luhya/thomas/business/popsugar/dev/web/vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php:259
 PHPUnit_Framework_TestResult->addError() at /home/luhya/thomas/business/popsugar/dev/web/vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php:694
 PHPUnit_Framework_TestResult->run() at /home/luhya/thomas/business/popsugar/dev/web/vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php:783
 PHPUnit_Framework_TestCase->run() at /home/luhya/thomas/business/popsugar/dev/web/vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php:775
 PHPUnit_Framework_TestSuite->runTest() at /home/luhya/thomas/business/popsugar/dev/web/vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php:745
 PHPUnit_Framework_TestSuite->run() at /home/luhya/thomas/business/popsugar/dev/web/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:65
 Codeception\PHPUnit\Runner->doEnhancedRun() at /home/luhya/thomas/business/popsugar/dev/web/vendor/codeception/codeception/src/Codeception/SuiteManager.php:149
 Codeception\SuiteManager->run() at /home/luhya/thomas/business/popsugar/dev/web/vendor/codeception/codeception/src/Codeception/Codecept.php:153
 Codeception\Codecept->runSuite() at /home/luhya/thomas/business/popsugar/dev/web/vendor/codeception/codeception/src/Codeception/Codecept.php:142
 Codeception\Codecept->run() at /home/luhya/thomas/business/popsugar/dev/web/vendor/codeception/codeception/src/Codeception/Command/Run.php:88
 Codeception\Command\Run->execute() at /home/luhya/thomas/business/popsugar/dev/web/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:241
 Symfony\Component\Console\Command\Command->run() at /home/luhya/thomas/business/popsugar/dev/web/vendor/symfony/console/Symfony/Component/Console/Application.php:881
 Symfony\Component\Console\Application->doRunCommand() at /home/luhya/thomas/business/popsugar/dev/web/vendor/symfony/console/Symfony/Component/Console/Application.php:191
 Symfony\Component\Console\Application->doRun() at /home/luhya/thomas/business/popsugar/dev/web/vendor/symfony/console/Symfony/Component/Console/Application.php:121
 Symfony\Component\Console\Application->run() at /home/luhya/thomas/business/popsugar/dev/web/vendor/codeception/codeception/codecept:29

run [-c|--config="..."] [--report] [--html] [--xml] [--tap] [--json] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage] [--no-exit] [--defer-flush] [-g|--group="..."] [-s|--skip="..."] [--skip-group="..."] [--env="..."] [suite] [test]

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
