### ISSUE TITLE
remote debugger port of config.json isn't used

### ISSUE THREAD

**Issue by jhnns** [ariya/phantomjs#12149]
When I run `phantomjs --config ./config.json example.js` with `config.json` being

``` javascript
{
    "remoteDebuggerPort": 10000
}
```

there is nothing bound to the port `10000`. Running `phantomjs --remote-debugger-port=10000 ./example.js` instead works.

Using phantomjs version `1.9.7`.

**Comment by tecfu** [comment]
I see that this option simply hasn't been added in the source. See:
https://github.com/ariya/phantomjs/blob/master/src/config.h
