### ISSUE TITLE
phantomjs crash

### ISSUE THREAD

**Issue by AnFengDe** [ariya/phantomjs#12145]
>> 2014-04-12 11:14:21.005 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API. 0 [ '2014-04-12 11:14:21.005 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   '2014-04-12 11:14:21.006 phantomjs[5133:507] CoreText performance note: Set a breakpoint on CTFontLogSuboptimalRequest to debug.',
>>   '2014-04-12 11:14:23.989 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   '2014-04-12 11:14:25.029 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   'PhantomJS has crashed. Please read the crash reporting guide at https://code.google.com/p/phantomjs/wiki/CrashReporting and file a bug report at https://code.google.com/p/phantomjs/issues/entry with the crash dump file attached: /tmp/53DE0C51-09B2-44FD-89D3-3DAB07AA6C68.dmp' ]
>> 2014-04-12 11:14:21.006 phantomjs[5133:507] CoreText performance note: Set a breakpoint on CTFontLogSuboptimalRequest to debug. 1 [ '2014-04-12 11:14:21.005 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   '2014-04-12 11:14:21.006 phantomjs[5133:507] CoreText performance note: Set a breakpoint on CTFontLogSuboptimalRequest to debug.',
>>   '2014-04-12 11:14:23.989 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   '2014-04-12 11:14:25.029 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   'PhantomJS has crashed. Please read the crash reporting guide at https://code.google.com/p/phantomjs/wiki/CrashReporting and file a bug report at https://code.google.com/p/phantomjs/issues/entry with the crash dump file attached: /tmp/53DE0C51-09B2-44FD-89D3-3DAB07AA6C68.dmp' ]
>> 2014-04-12 11:14:23.989 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API. 2 [ '2014-04-12 11:14:21.005 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   '2014-04-12 11:14:21.006 phantomjs[5133:507] CoreText performance note: Set a breakpoint on CTFontLogSuboptimalRequest to debug.',
>>   '2014-04-12 11:14:23.989 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   '2014-04-12 11:14:25.029 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   'PhantomJS has crashed. Please read the crash reporting guide at https://code.google.com/p/phantomjs/wiki/CrashReporting and file a bug report at https://code.google.com/p/phantomjs/issues/entry with the crash dump file attached: /tmp/53DE0C51-09B2-44FD-89D3-3DAB07AA6C68.dmp' ]
>> 2014-04-12 11:14:25.029 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API. 3 [ '2014-04-12 11:14:21.005 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   '2014-04-12 11:14:21.006 phantomjs[5133:507] CoreText performance note: Set a breakpoint on CTFontLogSuboptimalRequest to debug.',
>>   '2014-04-12 11:14:23.989 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   '2014-04-12 11:14:25.029 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   'PhantomJS has crashed. Please read the crash reporting guide at https://code.google.com/p/phantomjs/wiki/CrashReporting and file a bug report at https://code.google.com/p/phantomjs/issues/entry with the crash dump file attached: /tmp/53DE0C51-09B2-44FD-89D3-3DAB07AA6C68.dmp' ]
>> PhantomJS has crashed. Please read the crash reporting guide at https://code.google.com/p/phantomjs/wiki/CrashReporting and file a bug report at https://code.google.com/p/phantomjs/issues/entry with the crash dump file attached: /tmp/53DE0C51-09B2-44FD-89D3-3DAB07AA6C68.dmp 4 [ '2014-04-12 11:14:21.005 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   '2014-04-12 11:14:21.006 phantomjs[5133:507] CoreText performance note: Set a breakpoint on CTFontLogSuboptimalRequest to debug.',
>>   '2014-04-12 11:14:23.989 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   '2014-04-12 11:14:25.029 phantomjs[5133:507] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.',
>>   'PhantomJS has crashed. Please read the crash reporting guide at https://code.google.com/p/phantomjs/wiki/CrashReporting and file a bug report at https://code.google.com/p/phantomjs/issues/entry with the crash dump file attached: /tmp/53DE0C51-09B2-44FD-89D3-3DAB07AA6C68.dmp' ]

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
