### ISSUE TITLE
Crash in CI on Debian Wheezy

### ISSUE THREAD

**Issue by felixbuenemann** [ariya/phantomjs#12148]
The following crash happened once on our ci server running wheezy x86_64 and phantomjs 1.9.7:

https://gist.github.com/felixbuenemann/99c460d0199d015ff5fe

I can embed the stacktrace if you prefer.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
