### ISSUE TITLE
dmp file from crash using local server of prerender.io

### ISSUE THREAD

**Issue by AlexCppns** [ariya/phantomjs#12167]
phantom stderr: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/4F4E51A8-AA1E-4268-BE9E-1FDA40DAB319.dmp

I can't attach the dmp file because github wont allow me. There are also no instructions on how to deal with errors coming from phantomJS in prerender.io.

**Comment by Jack-Alden** [comment]
Having the same problem, has any solution been found to this?
