### ISSUE TITLE
PhantomJS (1.9.7, x32, Ubuntu Linux 12.04 LTS) dies

### ISSUE THREAD

**Issue by Hainish** [ariya/phantomjs#12161]
Related: https://github.com/efforg/congress-forms/issues/9

When filling out the form here https://lowey.house.gov/contact-form/ PhantomJS dies most of the time with the following:

PhantomJS client died while processing {"name":"click","args":[1,2]}

Even when :js_errors => false is set

Dump is available here:
http://ec2-54-215-28-56.us-west-1.compute.amazonaws.com:3000/60535c36-69b6-1492-24ef6d14-61bafd96.dmp

Try it out here:
http://efforg.github.io/congress-forms-test/?bioguide_id=L000480

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
