### ISSUE TITLE
Phantomjs crashes with remote-webdriver

### ISSUE THREAD

**Issue by alonisser** [ariya/phantomjs#12164]
consistently happening with both 1.9.7 (posted) and 1.9.3 (I had before and tried upgrading)
ubuntu 14.04 lts
happens when I use phantomjs through remote-webdriver
with ```webdriver-manger start"

stack trace (according to the rules posted)
Operating system: Linux
                  0.0.0 Linux 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64
CPU: amd64
     family 6 model 69 stepping 1
     1 CPU

Crash reason:  SIGSEGV
Crash address: 0xffffffffffffffc8

Thread 0 (crashed)
 0  0x7fada050e806
    rbx = 0x00007fade442a048   r12 = 0x0000000000000200
    r13 = 0x00007fade442a048   r14 = 0xffff000000000000
    r15 = 0xffff000000000002   rip = 0x00007fada050e806
    rsp = 0x00007fff3ec35720   rbp = 0x00007fff3ec357c0
    Found by: given as instruction pointer in context
 1  libc-2.19.so + 0x3bf75f
    rip = 0x00007fade6b56760   rsp = 0x00007fff3ec35740
    rbp = 0x00007fff3ec357c0
    Found by: stack scanning
 2  phantomjs + 0xb2e375
    rip = 0x0000000000f2e376   rsp = 0x00007fff3ec357d0
    Found by: stack scanning
 3  phantomjs + 0xb7291c
    rip = 0x0000000000f7291d   rsp = 0x00007fff3ec358a0
    Found by: stack scanning
 4  phantomjs + 0x142ecd
    rip = 0x0000000000542ece   rsp = 0x00007fff3ec358b0
    Found by: stack scanning
 5  phantomjs + 0x195fd3f
    rip = 0x0000000001d5fd40   rsp = 0x00007fff3ec35918
    Found by: stack scanning
 6  phantomjs + 0xe2245
    rip = 0x00000000004e2246   rsp = 0x00007fff3ec35960
    Found by: stack scanning
 7  phantomjs + 0x4864ac
    rip = 0x00000000008864ad   rsp = 0x00007fff3ec359a0
    Found by: stack scanning
 8  phantomjs + 0xb8214f
    rip = 0x0000000000f82150   rsp = 0x00007fff3ec359a8
    Found by: stack scanning
 9  phantomjs + 0x195fd3f
    rip = 0x0000000001d5fd40   rsp = 0x00007fff3ec35a18
    Found by: stack scanning
10  phantomjs + 0x18e935a
    rip = 0x0000000001ce935b   rsp = 0x00007fff3ec35a50
    Found by: stack scanning
11  phantomjs + 0x18f4801
    rip = 0x0000000001cf4802   rsp = 0x00007fff3ec35ab0
    Found by: stack scanning
12  phantomjs + 0x1c8e7f0
    rip = 0x000000000208e7f1   rsp = 0x00007fff3ec35ac0
    Found by: stack scanning
13  phantomjs + 0x14390b
    rip = 0x000000000054390c   rsp = 0x00007fff3ec35b30
    Found by: stack scanning
14  phantomjs + 0x18f715f
    rip = 0x0000000001cf7160   rsp = 0x00007fff3ec35b60
    Found by: stack scanning
15  libc-2.19.so + 0x835ef
    rip = 0x00007fade681a5f0   rsp = 0x00007fff3ec35bd0
    Found by: stack scanning
16  libc-2.19.so + 0x3bf75f
    rip = 0x00007fade6b56760   rsp = 0x00007fff3ec35c30
    Found by: stack scanning
17  phantomjs + 0x6a162
    rip = 0x000000000046a163   rsp = 0x00007fff3ec35c80
    Found by: stack scanning
18  phantomjs + 0x12bd1
    rip = 0x0000000000412bd2   rsp = 0x00007fff3ec35ca0
    Found by: stack scanning
19  phantomjs + 0x6a2b4
    rip = 0x000000000046a2b5   rsp = 0x00007fff3ec35cc0
    Found by: stack scanning
20  phantomjs + 0x18f2545
    rip = 0x0000000001cf2546   rsp = 0x00007fff3ec35ce0
    Found by: stack scanning
21  phantomjs + 0x18f8f01
    rip = 0x0000000001cf8f02   rsp = 0x00007fff3ec35d50
    Found by: stack scanning
22  phantomjs + 0x18efc27
    rip = 0x0000000001cefc28   rsp = 0x00007fff3ec35df0
    Found by: stack scanning
23  phantomjs + 0x18dd3ee
    rip = 0x0000000001cdd3ef   rsp = 0x00007fff3ec35e00
    Found by: stack scanning
24  phantomjs + 0x18efc27
    rip = 0x0000000001cefc28   rsp = 0x00007fff3ec35e40
    Found by: stack scanning
25  phantomjs + 0x177b289
    rip = 0x0000000001b7b28a   rsp = 0x00007fff3ec35e60
    Found by: stack scanning
26  phantomjs + 0x1784450
    rip = 0x0000000001b84451   rsp = 0x00007fff3ec35ea0
    Found by: stack scanning
27  phantomjs + 0x944d7
    rip = 0x00000000004944d8   rsp = 0x00007fff3ec35ed0
    Found by: stack scanning
28  phantomjs + 0x11e793a
    rip = 0x00000000015e793b   rsp = 0x00007fff3ec35ee0
    Found by: stack scanning
29  phantomjs + 0x173552f
    rip = 0x0000000001b35530   rsp = 0x00007fff3ec35f10
    Found by: stack scanning
30  phantomjs + 0x944d7
    rip = 0x00000000004944d8   rsp = 0x00007fff3ec35f20
    Found by: stack scanning
31  phantomjs + 0x11decae
    rip = 0x00000000015decaf   rsp = 0x00007fff3ec35f90
    Found by: stack scanning
32  phantomjs + 0x11e793a
    rip = 0x00000000015e793b   rsp = 0x00007fff3ec35fc0
    Found by: stack scanning
33  phantomjs + 0x11decae
    rip = 0x00000000015decaf   rsp = 0x00007fff3ec35fe0
    Found by: stack scanning
34  phantomjs + 0x11e793a
    rip = 0x00000000015e793b   rsp = 0x00007fff3ec36010
    Found by: stack scanning
35  phantomjs + 0x129343
    rip = 0x0000000000529344   rsp = 0x00007fff3ec36090
    Found by: stack scanning
36  phantomjs + 0x1882d46
    rip = 0x0000000001c82d47   rsp = 0x00007fff3ec36100
    Found by: stack scanning
37  phantomjs + 0x1294d1
    rip = 0x00000000005294d2   rsp = 0x00007fff3ec36180
    Found by: stack scanning
38  phantomjs + 0x14de9b
    rip = 0x000000000054de9c   rsp = 0x00007fff3ec361c0
    Found by: stack scanning
39  phantomjs + 0x190025d
    rip = 0x0000000001d0025e   rsp = 0x00007fff3ec361e0
    Found by: stack scanning
40  phantomjs + 0x7fcb2
    rip = 0x000000000047fcb3   rsp = 0x00007fff3ec36200
    Found by: stack scanning

Thread 1
 0  libc-2.19.so + 0xc1d7d
    rbx = 0x00007fade582ac80   r12 = 0x00007fade582ad00
    r13 = 0x00007fade4030480   r14 = 0x0000000002a7f5e0
    r15 = 0x0000000002a7f5b0   rip = 0x00007fade6858d7d
    rsp = 0x00007fade582ac60   rbp = 0x00000000ffffffff
    Found by: given as instruction pointer in context
 1  libc-2.19.so + 0xc1c13
    rip = 0x00007fade6858c14   rsp = 0x00007fade582ac70
    Found by: stack scanning
 2  phantomjs + 0x2e2c
    rip = 0x0000000000402e2d   rsp = 0x00007fade582ad10
    Found by: stack scanning
 3  ld-2.19.so + 0xa990
    rip = 0x00007fade7e90991   rsp = 0x00007fade582ad20
    Found by: stack scanning
 4  libc-2.19.so + 0xe89f
    rip = 0x00007fade67a58a0   rsp = 0x00007fade582ad28
    Found by: stack scanning
 5  phantomjs + 0x18b5c6f
    rip = 0x0000000001cb5c70   rsp = 0x00007fade582ad88
    Found by: stack scanning
 6  libc-2.19.so + 0x3d27
    rip = 0x00007fade679ad28   rsp = 0x00007fade582ad98
    Found by: stack scanning
 7  libc-2.19.so + 0xe89f
    rip = 0x00007fade67a58a0   rsp = 0x00007fade582ada8
    Found by: stack scanning
 8  phantomjs + 0x173d7
    rip = 0x00000000004173d8   rsp = 0x00007fade582adb0
    Found by: stack scanning
 9  phantomjs + 0x2e2c
    rip = 0x0000000000402e2d   rsp = 0x00007fade582ade0
    Found by: stack scanning
10  libc-2.19.so + 0x10d77
    rip = 0x00007fade67a7d78   rsp = 0x00007fade582ade8
    Found by: stack scanning
11  phantomjs + 0x24c7
    rip = 0x00000000004024c8   rsp = 0x00007fade582adf0
    Found by: stack scanning
12  libpthread-2.19.so + 0x1033f
    rip = 0x00007fade738d340   rsp = 0x00007fade582ae18
    Found by: stack scanning
13  libpthread-2.19.so + 0xc4a3
    rip = 0x00007fade73894a4   rsp = 0x00007fade582ae20
    Found by: stack scanning
14  phantomjs + 0xdda2d
    rip = 0x00000000004dda2e   rsp = 0x00007fade582ae50
    Found by: stack scanning
15  phantomjs + 0xddc98
    rip = 0x00000000004ddc99   rsp = 0x00007fade582aed0
    Found by: stack scanning
16  libpthread-2.19.so + 0x8181
    rip = 0x00007fade7385182   rsp = 0x00007fade582aee0
    Found by: stack scanning
17  libc-2.19.so + 0xfb30c
    rip = 0x00007fade689230d   rsp = 0x00007fade582af80
    Found by: stack scanning

Thread 2
 0  libc-2.19.so + 0xf2c33
    rbx = 0x0000000000000000   r12 = 0x00007fade5029db0
    r13 = 0x0000000000000008   r14 = 0x00007fade0000a98
    r15 = 0x00007fade0000d30   rip = 0x00007fade6889c33
    rsp = 0x00007fade5029b80   rbp = 0x00007fade00008e0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906326
    rip = 0x0000000001d06327   rsp = 0x00007fade5029b90
    Found by: stack scanning
 2  ld-2.19.so + 0x9e9b
    rip = 0x00007fade7e8fe9c   rsp = 0x00007fade5029be0
    Found by: stack scanning
 3  phantomjs + 0x19075e6
    rip = 0x0000000001d075e7   rsp = 0x00007fade5029c20
    Found by: stack scanning
 4  phantomjs + 0x18f6ab6
    rip = 0x0000000001cf6ab7   rsp = 0x00007fade5029c40
    Found by: stack sc
    rip = 0x00007fade68a07bd   rsp = 0x00007fad867fbc90
    Found by: stack scanning
 7  phantomjs + 0x1840b73
    rip = 0x0000000001c40b74   rsp = 0x00007fad867fbca0
    Found by: stack scanning
 8  phantomjs + 0x7851bf
    rip = 0x0000000000b851c0   rsp = 0x00007fad867fbcc0
    Found by: stack scanning
 9  phantomjs + 0x1907ced
    rip = 0x0000000001d07cee   rsp = 0x00007fad867fbcd0
    Found by: stack scanning
10  phantomjs + 0x1840a78
    rip = 0x0000000001c40a79   rsp = 0x00007fad867fbce0
    Found by: stack scanning
11  phantomjs + 0x1906fa5
    rip = 0x0000000001d06fa6   rsp = 0x00007fad867fbcf0
    Found by: stack scanning
12  phantomjs + 0x1908091
    rip = 0x0000000001d08092   rsp = 0x00007fad867fbd60
    Found by: stack scanning
13  phantomjs + 0x18dd4b4
    rip = 0x0000000001cdd4b5   rsp = 0x00007fad867fbdb0
    Found by: stack scanning
14  phantomjs + 0x18ddca8
    rip = 0x0000000001cddca9   rsp = 0x00007fad867fbdc0
    Found by: stack scanning
15  phantomjs + 0x18dd917
    rip = 0x0000000001cdd918   rsp = 0x00007fad867fbde0
    Found by: stack scanning
16  phantomjs + 0x17dfdf5
    rip = 0x0000000001bdfdf6   rsp = 0x00007fad867fbe40
    Found by: stack scanning
17  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007fad867fbe90
    Found by: stack scanning
18  libpthread-2.19.so + 0x8181
    rip = 0x00007fade7385182   rsp = 0x00007fad867fbee0
    Found by: stack scanning
19  libc-2.19.so + 0xfb30c
    rip = 0x00007fade689230d   rsp = 0x00007fad867fbf80
    Found by: stack scanning

Thread 15
 0  libpthread-2.19.so + 0xc7ce
    rbx = 0x00007fad6c005490   r12 = 0x0000000000000019
    r13 = 0x00007fad857f9df0   r14 = 0xffffffffffffff92
    r15 = 0x00007fad6c005400   rip = 0x00007fade73897ce
    rsp = 0x00007fad857f9d70   rbp = 0x00007fad6c027c10
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39d6
    rip = 0x0000000001be39d7   rsp = 0x00007fad857f9dd0
    Found by: stack scanning
 2  phantomjs + 0x17d783c
    rip = 0x0000000001bd783d   rsp = 0x00007fad857f9e50
    Found by: stack scanning
 3  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007fad857f9e90
    Found by: stack scanning
 4  libpthread-2.19.so + 0x8181
    rip = 0x00007fade7385182   rsp = 0x00007fad857f9ee0
    Found by: stack scanning
 5  libc-2.19.so + 0xfb30c
    rip = 0x00007fade689230d   rsp = 0x00007fad857f9f80
    Found by: stack scanning

Thread 16
 0  libpthread-2.19.so + 0xc414
    rbx = 0x00000000048b1c00   r12 = 0x004189374bc6a7ef
    r13 = 0xffffffffffffffff   r14 = 0x00000000048b1c28
    r15 = 0x0000000004894860   rip = 0x00007fade7389414
    rsp = 0x00007fad5762ad40   rbp = 0x00007fad57f9e910
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39f4
    rip = 0x0000000001be39f5   rsp = 0x00007fad5762ad70
    rbp = 0x00007fad57f9e910
    Found by: stack scanning
 2  phantomjs + 0xe70e9
    rip = 0x00000000004e70ea   rsp = 0x00007fad5762adf0
    rbp = 0x00007fad57f9e910
    Found by: stack scanning
 3  phantomjs + 0xd85268
    rip = 0x0000000001185269   rsp = 0x00007fad5762ae10
    rbp = 0x00007fad57f9e910
    Found by: stack scanning
 4  phantomjs + 0xd85492
    rip = 0x0000000001185493   rsp = 0x00007fad5762ae50
    rbp = 0x00007fad57f9e910
    Found by: stack scanning
 5  phantomjs + 0xe68fa
    rip = 0x00000000004e68fb   rsp = 0x00007fad5762ae80
    rbp = 0x00007fad57f9e910
    Found by: stack scanning
 6  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007fad5762ae90
    rbp = 0x00007fad57f9e910
    Found by: stack scanning
 7  libpthread-2.19.so + 0x8181
    rip = 0x00007fade7385182   rsp = 0x00007fad5762aee0
    rbp = 0x00007fad57f9e910
    Found by: stack scanning
 8  libc-2.19.so + 0xfb30c
    rip = 0x00007fade689230d   rsp = 0x00007fad5762af80
    rbp = 0x00007fad57f9e910
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x0268dfff  phantomjs  ???  (main)
canningc51d000 - 0x7fad7c5b7fff  DejaVuSans-Oblique.ttf  ???
 5  phantomjs + 0x18019c2
    rip = 0x0000000001c019c3   rsp = 0x00007fade5029c50
    Found by: stack scanning
 6  libc-2.19.so + 0x1097bc
    rip = 0x00007fade68a07bd   rsp = 0x00007fade5029c90
    Found by: stack scanning
 7  phantomjs + 0x1840b73
    rip = 0x0000000001c40b74   rsp = 0x00007fade5029ca0
    Found by: stack scanning
 8  phantomjs + 0x1840a78
    rip = 0x0000000001c40a79   rsp = 0x00007fade5029ce0
    Found by: stack scanning
 9  phantomjs + 0x1906fa5
    rip = 0x0000000001d06fa6   rsp = 0x00007fade5029cf0
    Found by: stack scanning
10  phantomjs + 0x1908091
    rip = 0x0000000001d08092   rsp = 0x00007fade5029d60
    Found by: stack scanning
11  phantomjs + 0x18dd4b4
    rip = 0x0000000001cdd4b5   rsp = 0x00007fade5029db0
    Found by: stack scanning
12  phantomjs + 0x18ddca8
    rip = 0x0000000001cddca9   rsp = 0x00007fade5029dc0
    Found by: stack scanning
13  phantomjs + 0x18dd917
    rip = 0x0000000001cdd918   rsp = 0x00007fade5029de0
    Found by: stack scanning
14  phantomjs + 0x17dfdf5
    rip = 0x0000000001bdfdf6   rsp = 0x00007fade5029e40
    Found by: stack scanning
15  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007fade5029e90
    Found by: stack scanning
16  libpthread-2.19.so + 0x8181
    rip = 0x00007fade7385182   rsp = 0x00007fade5029ee0
    Found by: stack scanning
17  libc-2.19.so + 0xfb30c
    rip = 0x00007fade689230d   rsp = 0x00007fade5029f80
    Found by: stack scanning

Thread 3
 0  libc-2.19.so + 0xf2c33
    rbx = 0x0000000000000200   r12 = 0x0000000003745460
    r13 = 0x0000000003745540   r14 = 0x0000000003745ad0
    r15 = 0x00007fad9fffedd0   rip = 0x00007fade6889c33
    rsp = 0x00007fad9fffedb0   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  phantomjs + 0x52135
    rip = 0x0000000000452136   rsp = 0x00007fad9fffedc0
    Found by: stack scanning
 2  phantomjs + 0xc0007e
    rip = 0x000000000100007f   rsp = 0x00007fad9fffee80
    Found by: stack scanning
 3  libpthread-2.19.so + 0x8181
    rip = 0x00007fade7385182   rsp = 0x00007fad9fffeee0
    Found by: stack scanning
 4  libc-2.19.so + 0xfb30c
    rip = 0x00007fade689230d   rsp = 0x00007fad9fffef80
    Found by: stack scanning

Thread 4
 0  libpthread-2.19.so + 0xc414
    rbx = 0x0000000003745aa0   r12 = 0x00007fad980008c8
    r13 = 0x0000000003745460   r14 = 0x00007fad9f7fe9c0
    r15 = 0x0000000003745540   rip = 0x00007fade7389414
    rsp = 0x00007fad9f7fba20   rbp = 0x00007fad980008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x526d7
    rip = 0x00000000004526d8   rsp = 0x00007fad9f7fba50
    Found by: stack scanning

Thread 5
 0  libpthread-2.19.so + 0xc414
    rbx = 0x0000000003745aa0   r12 = 0x0000000000000000
    r13 = 0x0000000003745460   r14 = 0x00007fad9effd9c0
    r15 = 0x0000000003745540   rip = 0x00007fade7389414
    rsp = 0x00007fad9effaa20   rbp = 0x00007fad900008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x526d7
    rip = 0x00000000004526d8   rsp = 0x00007fad9effaa50
    Found by: stack scanning

Thread 6
 0  libpthread-2.19.so + 0xc414
    rbx = 0x00007fad94005900   r12 = 0x004189374bc6a7ef
    r13 = 0xffffffffffffffff   r14 = 0x00007fad94005928
    r15 = 0x00007fad94004ea0   rip = 0x00007fade7389414
    rsp = 0x00007fad9e7f6010   rbp = 0x00007fad94004ea0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39f4
    rip = 0x0000000001be39f5   rsp = 0x00007fad9e7f6040
    Found by: stack scanning
 2  phantomjs + 0x17deb2c
    rip = 0x0000000001bdeb2d   rsp = 0x00007fad9e7f60c0
    Found by: stack scanning
 3  phantomjs + 0x2520b
    rip = 0x000000000042520c   rsp = 0x00007fad9e7f60f0
    Found by: stack scanning
 4  phantomjs + 0x195ba7b
    rip = 0x0000000001d5ba7c   rsp = 0x00007fad9e7f6140
    Found by: stack scanning
 5  phantomjs + 0x195ba83
    rip = 0x0000000001d5ba84   rsp = 0x00007fad9e7f6158
    Found by: stack scanning
 6  phantomjs + 0x19612af
    rip = 0x0000000001d612b0   rsp = 0x00007fad9e7f6188
    Found by: stack scanning

Thread 7
 0  libpthread-2.19.so + 0xc414
    rbx = 0x0000000003745aa0   r12 = 0x0000000000000000
    r13 = 0x0000000003745460   r14 = 0x00007fad9dffb9c0
    r15 = 0x0000000003745540   rip = 0x00007fade7389414
    rsp = 0x00007fad9dff8a20   rbp = 0x00007fad880008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x526d7
    rip = 0x00000000004526d8   rsp = 0x00007fad9dff8a50
    Found by: stack scanning

Thread 8
 0  libpthread-2.19.so + 0xc414
    rbx = 0x0000000003745aa0   r12 = 0x0000000000000000
    r13 = 0x0000000003745460   r14 = 0x00007fad9d7fa9c0
    r15 = 0x0000000003745540   rip = 0x00007fade7389414
    rsp = 0x00007fad9d7f7a20   rbp = 0x00007fad8c0008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x526d7
    rip = 0x00000000004526d8   rsp = 0x00007fad9d7f7a50
    Found by: stack scanning

Thread 9
 0  libpthread-2.19.so + 0xc414
    rbx = 0x0000000003745aa0   r12 = 0x0000000000000000
    r13 = 0x0000000003745460   r14 = 0x00007fad9cff99c0
    r15 = 0x0000000003745540   rip = 0x00007fade7389414
    rsp = 0x00007fad9cff6a20   rbp = 0x00007fad800008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x526d7
    rip = 0x00000000004526d8   rsp = 0x00007fad9cff6a50
    Found by: stack scanning

Thread 10
 0  libpthread-2.19.so + 0xc414
    rbx = 0x0000000003745aa0   r12 = 0x0000000000000000
    r13 = 0x0000000003745460   r14 = 0x00007fad87fff9c0
    r15 = 0x0000000003745540   rip = 0x00007fade7389414
    rsp = 0x00007fad87ffca20   rbp = 0x00007fad780008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x526d7
    rip = 0x00000000004526d8   rsp = 0x00007fad87ffca50
    Found by: stack scanning

Thread 11
 0  libpthread-2.19.so + 0xc414
    rbx = 0x0000000003745aa0   r12 = 0x0000000000000000
    r13 = 0x0000000003745460   r14 = 0x00007fad7f7fe9c0
    r15 = 0x0000000003745540   rip = 0x00007fade7389414
    rsp = 0x00007fad7f7fba20   rbp = 0x00007fad700008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x526d7
    rip = 0x00000000004526d8   rsp = 0x00007fad7f7fba50
    Found by: stack scanning

Thread 12
 0  libpthread-2.19.so + 0xc414
    rbx = 0x0000000003745aa0   r12 = 0x0000000000000000
    r13 = 0x0000000003745460   r14 = 0x00007fad877fe9c0
    r15 = 0x0000000003745540   rip = 0x00007fade7389414
    rsp = 0x00007fad877fba20   rbp = 0x00007fad740008c0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x526d7
    rip = 0x00000000004526d8   rsp = 0x00007fad877fba50
    Found by: stack scanning

Thread 13
 0  libpthread-2.19.so + 0xc414
    rbx = 0x0000000003745aa0   r12 = 0x0000000000000000
    r13 = 0x0000000003745460   r14 = 0x00007fad86ffd9c0
    r15 = 0x0000000003745540   rip = 0x00007fade7389414
    rsp = 0x00007fad86ffaa20   rbp = 0x00007fad680008c0
    Found by: given as instruction pointer in context
Comments are parsed with GitHub Flavored Markdown
  1  phantomjs + 0x526d7
    rip = 0x00000000004526d8   rsp = 0x00007fad86ffaa50
    Found by: stack scanning

Thread 14
 0  libc-2.19.so + 0xf2c33
    rbx = 0x00007fad867fbd60   r12 = 0x000000000000c9c7
    r13 = 0x0000000000000030   r14 = 0x00007fad6c000a98
    r15 = 0x00007fad6c000d30   rip = 0x00007fade6889c33
    rsp = 0x00007fad867fbb80   rbp = 0x0000000000002f30
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906227
    rip = 0x0000000001d06228   rsp = 0x00007fad867fbb90
    Found by: stack scanning
 2  phantomjs + 0x78544c
    rip = 0x0000000000b8544d   rsp = 0x00007fad867fbbc0
    Found by: stack scanning
 3  phantomjs + 0x19075e6
    rip = 0x0000000001d075e7   rsp = 0x00007fad867fbc20
    Found by: stack scanning
 4  phantomjs + 0x18f6ab6
    rip = 0x0000000001cf6ab7   rsp = 0x00007fad867fbc40
    Found by: stack scanning
 5  phantomjs + 0x18019f3
    rip = 0x0000000001c019f4   rsp = 0x00007fad867fbc50
    Found by: stack scanning
 6  libc-2.19.so + 0x1097beb80ebd1c36541ebe2852d3bb0c49-le64.cache-4  ???
0x7fade8099000 - 0x7fade809bfff  e13b20fdb08344e0e664864cc2ede53d-le64.cache-4  ???
0x7fade809c000 - 0x7fade809ffff  7ef2298fde41cc6eeb7af42e48b7d293-le64.cache-4  ???
0x7fade80a0000 - 0x7fade80a5fff  b1f2745c341ccb4127296efa70379551-le64.cache-4  ???
0x7fff3ed8a000 - 0x7fff3ed8bfff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
