### ISSUE TITLE
'User-Agent' header value does not change when using setContent

### ISSUE THREAD

**Issue by devaroop** [ariya/phantomjs#12169]
If we set user-agent using
`page.settings.userAgent = "someagent"`
and then try to load page using
`page.setContent("some_html_string", "http://someuri")`, 
then the user-agent change does not reflect and takes the default PhantomJs user-agent. 

However, it works great while used before `page.open(xxx...`

A way around is to set it thru:

`    page.customHeaders = {
        'User-Agent': 'someagent'
    }; ` which overwrites the user-agent.

Kindly look into it, though we have a workaround as of now. Thanks

**Comment by wyongzhi** [comment]
+1

**Comment by ChairmanMeow** [comment]
+2

**Comment by zackw** [comment]
Also a duplicate of #12547.
