### ISSUE TITLE
Doesn't finish redirecting to an unexisting URL

### ISSUE THREAD

**Issue by janko** [ariya/phantomjs#12162]
I have a webpage, which has a `<script>` tag with JavaScript that (conditionally) redirects to an URL, via `window.location = "..."`. I'm transfering Selenium tests to Phantom.js, and there are some tests which are testing that this redirect happens.

The catch is that the page this URL points to doesn't exist (I'm new to this project, so I have not understood yet why), so after I sleep wait for enough time (so that the redirected page can load), Phantom.js tells me that I'm still on the previous page. This doesn't happen if I just swap that URL with an existing one (or with Selenium).

I think it would make sense that Phantom.js still shows that URL, even though it didn't load anything (since the page doesn't exist), because that's the behaviour of regular browsers. Is this behaviour difficult to make?

**Comment by tit** [comment]
+1
