### ISSUE TITLE
Core dumped when trying to render a site homepage

### ISSUE THREAD

**Issue by mastershifu** [ariya/phantomjs#12171]
Using phantomjs-1.9.7-linux-x86_64, trying to page.open('http://www.aspectiva.com/'), got the following error:

phantomjs: ../3rdparty/harfbuzz/src/harfbuzz-shaper.cpp:484: void HB_HeuristicSetGlyphAttributes(HB_ShaperItem*): Assertion `glyph_pos == item->num_glyphs' failed.
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/0f29188c-0469-75ff-7a86c9c3-244de9d1.dmp
Aborted (core dumped)

I was trying to extract the trace from the dump as described in the site, but it contains no addresses. The process is running on CentOS6.5

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
