### ISSUE TITLE
Intermittent Crash on Linux Jenkins -  phantomjs@1.9.7-1 

### ISSUE THREAD

**Issue by geekdave** [ariya/phantomjs#12178]
Started getting this crash intermittently in our CI environment.  Possibly started happening around the same time we introduced some custom icon fonts.

We are running a large mocha test suite, instrumented with BlanketJS for code coverage.

Gist of stack trace:
https://gist.github.com/geekdave/dbe9e3cfdeeb7f9d4266

We have had several updates to icon fonts recently which may be related.  I've seen lots of issues about fonts and phantom crashes, but supposedly they were fixed in this version (and also they were reported on OSX while this issue is only on Linux)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
