### ISSUE TITLE
A lot of requests to web pages -> phantom crashes

### ISSUE THREAD

**Issue by frankred** [ariya/phantomjs#12189]
I'm writing a tool to automate a sitemap creation for webpages. 
If the webpage has many subpages (> ~100) phantomjs crashes every time. Is there a problem with the memory and request amount?

Is it possible to limit the request amount, or to queue the requests?

Phantom.JS is AWESOME!

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
