### ISSUE TITLE
Cookies changed erroneously when escape characters included

### ISSUE THREAD

**Issue by CookieManager** [ariya/phantomjs#12186]
Configuration:PhantomJS 1.9.7 on Windows 7.

Issue: Using PhantomJS with persistent cookies and noticed that when cookies have escape characters in the cookie value, Phantom is sending out and displaying erroneous values. As an example, using this simple code to add the cookie below. 

phantom.addCookie({'name': '__cmbCk','value': '{"eid":"ABJeb1-s8l6W8JOT87xagJlSuyGwONvjx3gt6u32hD3q1lFP4K8i1ki3DthK-BzjQJDKzzrP2u4yr4HsDLFeEZV6SJXqrRoAoA","slt":1398702997037,"cbt":99,"tp":3877}','domain': '.crateandbarrel.com','path': '/','httponly': false,'secure': false,'expires': 1399307801704});

Once added and use Phantom to go to www.crateandbarrel.com, the value of the cookie that is sent looks like this:

"{\"eid\":\"ABJeb19qcuajKdR-JhUHjs9oMGYQXBMbouJG6vy9FvdBmTEYyVsolFF5_qlAaR_Z1oHNdZLquKU4OH95zqvUBVOOgDTtNPNfTA\",\"slt\":1398730389778,\"cbt\":108,\"tp\":6864}"

Not only are there escape characters in the string, but also there are double quotes added to the ends of the cookie. I am no expert, but one way to deal with this could be to encode the values within PhantomJS and decode them when outputting them or sending them with requests.

**Comment by jfbrennan** [comment]
+1

**Comment by zackw** [comment]
My tests indicate that this has been fixed in the current development sources.  It may also have been fixed in 2.0.

We are no longer developing the 1.9.x series.
