### ISSUE TITLE
Floating point exception when calculating modulus

### ISSUE THREAD

**Issue by gzm0** [ariya/phantomjs#12198]
The following crashes phantom.js `1.9.0` on Ubuntu 13.10 (saucy)

```javascript
var x = -2147483648; // uint32 min value
var y = -1;
console.log(x % y);
```
`Floating point exception (core dumped)`

Core dump will follow asap.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
