### ISSUE TITLE
Segmentation fault on webpage script opening wired.com

### ISSUE THREAD

**Issue by peterbe** [ariya/phantomjs#12200]
I get one of those:
```
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/51CFD23F-B88D-483E-83A8-0BB98E8A846A.dmp
```
I'm starting the script like this:
```
phantomjs --ignore-ssl-errors=true  peterbecom/apps/nodomains/count.js http://www.wired.com/2014/05/an-amazing-shock-absorbing-wheel-for-bikes-and-wheelchairs/
```
You can download [count.js here](https://github.com/peterbe/django-peterbecom/blob/master/peterbecom/apps/nodomains/count.js)
This is reproducible every time in 1.9.7 on OSX (homebrew install).

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
