### ISSUE TITLE
PhantomJS crashes trying to load script - PHP exec()

### ISSUE THREAD

**Issue by riyunoa** [ariya/phantomjs#12201]
Here's another PHP exec() issue. 

Doing "phantomjs -v" in a PHP exec() / shell_exec() works fine, but doing "phantomjs script.js" causes a crash. It works fine in command prompt, and is fine running on a local Apache server. 

Here's my .dmp file. Thanks in advance. :)

-----

Operating system: Linux
                  0.0.0 Linux 2.6.18-238.19.1.el5 #1 SMP Sun Jul 10 08:43:41 EDT 2011 x86_64
CPU: amd64
     family 6 model 23 stepping 10
     8 CPUs

Crash reason:  SIGSEGV
Crash address: 0xbbadbeef

Thread 0 (crashed)
 0  phantomjs!WTF::OSAllocator::reserveUncommitted [OSAllocatorPosix.cpp : 107 + 0x7]
    rbx = 0xffffffffffffffff   r12 = 0x00000000113d7b40
    r13 = 0x000000000000007f   r14 = 0x00002aaaaaad7820
    r15 = 0x00002aaaaaad7720   rip = 0x00000000004f8057
    rsp = 0x00007fff8d672740   rbp = 0x7ff8000000000000
    Found by: given as instruction pointer in context
 1  phantomjs!JSC::ExecutableAllocator::isValid [PageReservation.h : 107 + 0x18]
    rbx = 0x00000000113d7b20   r12 = 0x00000000113d7b40
    r13 = 0x000000000000007f   r14 = 0x00002aaaaaad7820
    r15 = 0x00002aaaaaad7720   rip = 0x0000000000f31fd1
    rsp = 0x00007fff8d672750   rbp = 0x7ff8000000000000
    Found by: call frame info
 2  phantomjs!JSC::ExecutableAllocator::ExecutableAllocator [ExecutableAllocator.h : 185 + 0x7]
    rbx = 0x0000000002a9ec58   r12 = 0x0000000011446300
    r13 = 0x000000000000007f   r14 = 0x00002aaaaaad7820
    r15 = 0x00002aaaaaad7720   rip = 0x0000000000f88d66
    rsp = 0x00007fff8d6727a0   rbp = 0x7ff8000000000000
    Found by: call frame info
 3  phantomjs!JSC::JSGlobalData::JSGlobalData [JSGlobalData.cpp : 170 + 0x9]
    rbx = 0x00002aaaaaad6000   r12 = 0x0000000011446300
    r13 = 0x000000000000007f   r14 = 0x0000000000000085
    r15 = 0x00002aaaaaad7720   rip = 0x0000000000f89b2e
    rsp = 0x00007fff8d672810   rbp = 0x7ff8000000000000
    Found by: call frame info
 4  phantomjs!JSC::JSGlobalData::createLeaked [JSGlobalData.cpp : 326 + 0x9]
    rbx = 0x0000000000000000   r12 = 0x00007fff8d672ab0
    r13 = 0x00000000113d3690   r14 = 0x00007fff8d672b50
    r15 = 0x00000000114a9b30   rip = 0x0000000000f8b5b1
    rsp = 0x00007fff8d672a90   rbp = 0x00002aaaaaad6000
    Found by: call frame info
 5  phantomjs!WebCore::JSDOMWindowBase::commonJSGlobalData [JSDOMWindowBase.cpp : 159 + 0x9]
    rbx = 0x00007fff8d672ba0   r12 = 0x00007fff8d672c70
    r13 = 0x00000000113d3690   r14 = 0x00007fff8d672b50
    r15 = 0x00000000114a9b30   rip = 0x000000000051d382
    rsp = 0x00007fff8d672ab0   rbp = 0x00002aaaaaaca000
    Found by: call frame info
 6  phantomjs!WebCore::FrameLoaderClientQt::createDocumentLoader [FrameLoaderClientQt.cpp : 990 + 0x4]
    rbx = 0x00007fff8d672ba0   r12 = 0x00007fff8d672c70
    r13 = 0x00000000113d3690   r14 = 0x00007fff8d672b50
    r15 = 0x00000000114a9b30   rip = 0x00000000004b900d
    rsp = 0x00007fff8d672ae0   rbp = 0x00002aaaaaaca000
    Found by: call frame info
 7  phantomjs!WebCore::FrameLoader::load [FrameLoader.cpp : 1460 + 0x13]
    rbx = 0x0000000000000000   r12 = 0x00002aaaaaacd478
    r13 = 0x00000000113d7a80   r14 = 0x0000000011480bd0
    r15 = 0x00000000114a9b30   rip = 0x0000000000864b57
    rsp = 0x00007fff8d672b10   rbp = 0x0000000000000001
    Found by: call frame info
 8  phantomjs!QWebFrame::setHtml [qwebframe.cpp : 976 + 0x1d]
    rbx = 0x0000000000000000   r12 = 0x00002aaaaab06400
    r13 = 0x00000000113d7a80   r14 = 0x0000000011480bd0
    r15 = 0x00000000114a9b30   rip = 0x00000000004827d1
    rsp = 0x00007fff8d672ba0   rbp = 0x0000000000000001
    Found by: call frame info
 9  phantomjs!WebPage::WebPage [webpage.cpp : 323 + 0x12]
    rbx = 0x0000000011480bb0   r12 = 0x00007fff8d672f40
    r13 = 0x00007fff8d672f30   r14 = 0x0000000011480bd0
    r15 = 0x0000000011480bd8   rip = 0x000000000041833e
    rsp = 0x00007fff8d672e30   rbp = 0x00000000113c74c0
    Found by: call frame info
10  phantomjs!Phantom::init [phantom.cpp : 102 + 0x40]
    rbx = 0x00000000113c74c0   r12 = 0x00000000114b33f0
    r13 = 0x00000000114b3390   r14 = 0x00007fff8d673500
    r15 = 0x0000000000000000   rip = 0x0000000000409bf3
    rsp = 0x00007fff8d672f90   rbp = 0x00007fff8d673200
    Found by: call frame info
11  phantomjs!Phantom::instance [phantom.cpp : 154 + 0x4]
    rbx = 0x00007fff8d673610   r12 = 0x00007fff8d673590
    r13 = 0x00007fff8d673740   r14 = 0x00007fff8d673500
    r15 = 0x0000000000000000   rip = 0x000000000040b576
    rsp = 0x00007fff8d6734d0   rbp = 0x00000000114b3390
    Found by: call frame info
12  phantomjs!main [main.cpp : 117 + 0x4]
    rbx = 0x00007fff8d673610   r12 = 0x00007fff8d673590
    r13 = 0x00007fff8d673740   r14 = 0x00007fff8d673500
    r15 = 0x0000000000000000   rip = 0x0000000000427c9e
    rsp = 0x00007fff8d6734f0   rbp = 0x00007fff8d673728
    Found by: call frame info
13  libc-2.5.so + 0x1d993
    rbx = 0x0000003110c1cbc0   r12 = 0x0000000000000000
    r13 = 0x00007fff8d673720   r14 = 0x0000000000000000
    r15 = 0x0000000000000000   rip = 0x0000003110e1d994
    rsp = 0x00007fff8d673650   rbp = 0x0000000000000000
    Found by: call frame info
14  phantomjs + 0x27a5f
    rip = 0x0000000000427a60   rsp = 0x00007fff8d673670
    Found by: stack scanning

Thread 1
 0  libpthread-2.5.so + 0xaee9
    rbx = 0x0000000002a84208   r12 = 0x0000000000000001
    r13 = 0x0000000000000003   r14 = 0x000000004177e000
    r15 = 0x0000000000001000   rip = 0x000000311160aee9
    rsp = 0x000000004177d040   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  libpthread-2.5.so + 0xad3f
    rip = 0x000000311160ad40   rsp = 0x000000004177d068
    Found by: stack scanning
 2  phantomjs!WTF::TCMalloc_PageHeap::scavengerThread [FastMalloc.cpp : 2495 + 0x7]
    rip = 0x00000000004ddafc   rsp = 0x000000004177d090
    Found by: stack scanning
 3  phantomjs!WTF::TCMalloc_PageHeap::runScavengerThread [FastMalloc.cpp : 1618 + 0x4]
    rbx = 0x0000000000000000   r12 = 0x0000000000000000
    r13 = 0x0000000000000003   r14 = 0x000000004177e000
    r15 = 0x0000000000001000   rip = 0x00000000004ddc99
    rsp = 0x000000004177d110   rbp = 0x0000000000000000
    Found by: call frame info
 4  libpthread-2.5.so + 0x673c
    rbx = 0x0000000000000000   r12 = 0x0000000000000000
    r13 = 0x0000000000000003   r14 = 0x000000004177e000
    r15 = 0x0000000000001000   rip = 0x000000311160673d
    rsp = 0x000000004177d120   rbp = 0x0000000000000000
    Found by: call frame info

Thread 2
 0  libc-2.5.so + 0xcd722
    rbx = 0x0000000000000000   r12 = 0x000000004217dff0
    r13 = 0x000000000000000a   r14 = 0x00000000113d8718
    r15 = 0x00000000113d89b0   rip = 0x0000003110ecd722
    rsp = 0x000000004217dd90   rbp = 0x00000000113d8560
    Found by: given as instruction pointer in context
 1  phantomjs!qt_safe_select [qcore_unix.cpp : 83 + 0x15]
    rip = 0x0000000001d06327   rsp = 0x000000004217ddd0
    Found by: stack scanning
 2  phantomjs!QEventDispatcherUNIXPrivate::doSelect [qeventdispatcher_unix.cpp : 223 + 0xd]
    rbx = 0x00000000113d7d60   r12 = 0x000000004217dff0
    r13 = 0x00000000113d8560   r14 = 0x0000000000000000
    r15 = 0x00000000113d89b0   rip = 0x0000000001d075e7
    rsp = 0x000000004217de60   rbp = 0x00000000113d8560
    Found by: call frame info
 3  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 937 + 0x4]
    rbx = 0x00000000113d7d60   r12 = 0x000000004217dff0
    r13 = 0x00000000113d7a30   r14 = 0x0000000000000001
    r15 = 0x00000000113c9428   rip = 0x0000000001d08092
    rsp = 0x000000004217dfa0   rbp = 0x00000000113d8560
    Found by: call frame info
 4  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x00000000113d7d60   r12 = 0x000000004217e080
    r13 = 0x000000004217e090   r14 = 0x00000000112f9200
    r15 = 0x00000000113c9428   rip = 0x0000000001cdd4b5
    rsp = 0x000000004217dff0   rbp = 0x000000004217e030
    Found by: call frame info
 5  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x00000000113d7d60   r12 = 0x000000004217e080
    r13 = 0x000000004217e090   r14 = 0x00000000112f9200
    r15 = 0x00000000113c9428   rip = 0x0000000001cdd918
    rsp = 0x000000004217e020   rbp = 0x00007fff8d673590
    Found by: call frame info
 6  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
    rbx = 0x00000000113c93a0   r12 = 0x00000000113c9428
    r13 = 0x0000000000000001   r14 = 0x000000004217f000
    r15 = 0x0000000000001000   rip = 0x0000000001bdfdf6
    rsp = 0x000000004217e080   rbp = 0x00000000113c9428
    Found by: call frame info
 7  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x00000000113c9428   r12 = 0x00000000113c94e0
    r13 = 0x0000000000000001   r14 = 0x000000004217f000
    r15 = 0x0000000000001000   rip = 0x0000000001be2cc2
    rsp = 0x000000004217e0d0   rbp = 0x000000001145c4a0
    Found by: call frame info
 8  libpthread-2.5.so + 0x673c
    rbx = 0x0000000000000000   r12 = 0x0000000000000000
    r13 = 0x0000000000000003   r14 = 0x000000004217f000
    r15 = 0x0000000000001000   rip = 0x000000311160673d
    rsp = 0x000000004217e120   rbp = 0x0000000000000000
    Found by: call frame info

Loaded modules:
0x00400000 - 0x0268dfff  phantomjs  ???  (main)
0x3110a00000 - 0x3110a1bfff  ld-2.5.so  ???
0x3110e00000 - 0x3111152fff  libc-2.5.so  ???
0x3111200000 - 0x3111403fff  libdl-2.5.so  ???
0x3111600000 - 0x3111816fff  libpthread-2.5.so  ???
0x3111a00000 - 0x3111c82fff  libm-2.5.so  ???
0x3111e00000 - 0x3112013fff  libz.so.1.2.3  ???
0x3112200000 - 0x3112416fff  libselinux.so.1  ???
0x3112600000 - 0x311283bfff  libsepol.so.1  ???
0x3112e00000 - 0x3113008fff  librt-2.5.so  ???
0x3113200000 - 0x3113412fff  libresolv-2.5.so  ???
0x3113600000 - 0x311394cfff  libcrypto.so.0.9.8e  ???
0x3113a00000 - 0x3113c01fff  libcom_err.so.2.1  ???
0x3114200000 - 0x3114407fff  libkrb5support.so.0.1  ???
0x3114600000 - 0x311482dfff  libgssapi_krb5.so.2.2  ???
0x3114a00000 - 0x3114c01fff  libkeyutils-1.2.so  ???
0x3114e00000 - 0x3115024fff  libk5crypto.so.3.1  ???
0x3115200000 - 0x3115494fff  libkrb5.so.3.3  ???
0x3115600000 - 0x311584bfff  libssl.so.0.9.8e  ???
0x3115a00000 - 0x3115c0dfff  libgcc_s-4.1.2-20080825.so.1  ???
0x3115e00000 - 0x31160edfff  libstdc++.so.6.0.8  ???
0x3117e00000 - 0x3118083fff  libfreetype.so.6.3.10  ???
0x3118200000 - 0x3118421fff  libexpat.so.0.5.0  ???
0x3119200000 - 0x3119432fff  libfontconfig.so.1.1.0  ???
0x2ae2262b2000 - 0x2ae2262b4fff  e3ead4b767b8819993a6fa3ae306afa9-x86-64.cache-2  ???
0x2ae2262b5000 - 0x2ae2262bcfff  b79f3aaa7d385a141ab53ec885cc22a8-x86-64.cache-2  ???
0x2ae2262c2000 - 0x2ae2262c3fff  87f5e051180a7a75f16eb6fe7dbd3749-x86-64.cache-2  ???
0x7fff8d72b000 - 0x7fff8d72efff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
