### ISSUE TITLE
page.url not round-trippable when URL is non-ASCII

### ISSUE THREAD

**Issue by zackw** [ariya/phantomjs#12216]
The implementation of `page.url` calls `QUrl::toString()` with no special options, which produces a Unicode string, with all non-ASCII characters decoded assuming UTF-8.  This is fine when what you want is to display the URL to an end-user, but it's broken when you want to be able to store the URL and re-access the same webpage later. Many websites still use ISO-8859-n, KOI8-R, or other "legacy" encodings in their URL structure; when such a URL is decoded as if it were UTF-8, you get a bunch of U+FFFDs and information is lost.

Please add a way to get the string that `QUrl::toEncoded()` would return.  (I'm not sure this is *enough* for my purposes, but to the extent it isn't, it's a problem with QUrl itself and you probably can't do anything about it. :-/ )

**Comment by knownasilya** [comment]
Is there any way you can rebase your version up to at least the latest 1.x version?

**Comment by zackw** [comment]
It's 2.x as of a couple weeks ago, is that not new enough?

**Comment by knownasilya** [comment]
Does 2.x change any user APIs from 1.9.8?

**Comment by knownasilya** [comment]
Is there any way to build this for osx/linux and windows (without having to be on each machine)?

**Comment by zackw** [comment]
@knownasilya I am not aware of any significant user-visible API changes between 1.9.8 and 2.0.  The main reason for the major version bump is a *huge* upgrade to Webkit.

Regrettably, I don't think our build system can handle cross-compilation.

**Comment by Vitallium** [comment]
Fixed in https://github.com/ariya/phantomjs/commit/1c203a39279ae556f84bf7b525415e50845419b3

**Comment by knownasilya** [comment]
:+1: excellent!
