### ISSUE TITLE
cannot capture www.hertz.co.uk due to crash of PhantomJS

### ISSUE THREAD

**Issue by cordial666** [ariya/phantomjs#12213]
Using version phantomjs-1.9.7-linux-x86_64 (on a linux machine obviously) and using our own rasterize JS file OR the example.js rasterise file inside /phantomjs-1.9.7-linux-x86_64/examples/, I am unable to capture the page of hertz.co.uk (or .it, .de etc). When I attempt this (by example executing "sudo /opt/cm2/bin/phantomjs ./phantomjs-1.9.7-linux-x86_64/examples/rasterize.js http://www.hertz.co.uk dummy.png dummy.html")   
phantomJs crashes. I have attached the .dmp file. Although I had to rename the extension to be a jpg so i could upload the file!

cheers
david
![6ab4a494-5c79-7fe7-0c344390-35426f1e dmp](https://cloud.githubusercontent.com/assets/419896/2929207/c371fd5c-d786-11e3-95e6-374bcf1a84b2.jpg)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
