### ISSUE TITLE
PhantomJS crash

### ISSUE THREAD

**Issue by dfelippa** [ariya/phantomjs#12221]
PhantomJS crashes for the situation I describe bellow.
I uploaded the relevant files (my script, dependent files, and the crash dump) to:
http://www.infologika.com.br/public/nfeWeb.zip

Steps to reproduce:
1) Unzip the files to a path, put phantomjs.exe in this path. Run my script
2) When a dialog box shows disable your network card
3) fill the dialog the any numbers and click on ok

I'm using latest phantom  1.9.7 but also crashes with previous versions (1.9.1)

Thank you,
Dennis

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
