### ISSUE TITLE
Resource needlessly timing out causing crash

### ISSUE THREAD

**Issue by xathien** [ariya/phantomjs#12223]
OS: CentOS 6
PhantomJS Version: 1.9.1 and 1.9.7

Stacktrace at http://pastebin.com/Qw1yApSA

Full .dmp file available upon request.

Thanks!

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
