### ISSUE TITLE
PhantomJS crashed regularly

### ISSUE THREAD

**Issue by domtirendo** [ariya/phantomjs#12226]
From time to time PhantomJS crashes while executing our CasperJS test suites (randomly in all test suites). PhantomJS version 1.9.7 binary on Linux.

Error Log:

Operating system: Linux
                  0.0.0 Linux 2.6.32-5-amd64 #1 SMP Mon Sep 23 22:14:43 UTC 2013 x86_64
CPU: amd64
     family 6 model 2 stepping 3
     8 CPUs

Crash reason:  SIGSEGV
Crash address: 0x18

Thread 0 (crashed)
 0  phantomjs + 0xafef9f
    rbx = 0x0000000000000070   r12 = 0x0000000000000001
    r13 = 0x00007f2284094980   r14 = 0x00007f228c37af20
    r15 = 0x00007f22d95dabc8   rip = 0x0000000000efef9f
    rsp = 0x00007fff7e2c7d70   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  phantomjs + 0xe0a3f
    rip = 0x00000000004e0a40   rsp = 0x00007fff7e2c7e10
    Found by: stack scanning
 2  phantomjs + 0xafa946
    rip = 0x0000000000efa947   rsp = 0x00007fff7e2c7e80
    Found by: stack scanning
 3  phantomjs + 0xfa983
    rip = 0x00000000004fa984   rsp = 0x00007fff7e2c7f30
    Found by: stack scanning
 4  phantomjs + 0xb27e66
    rip = 0x0000000000f27e67   rsp = 0x00007fff7e2c7f70
    Found by: stack scanning
 5  phantomjs + 0xb28782
    rip = 0x0000000000f28783   rsp = 0x00007fff7e2c8020
    Found by: stack scanning
 6  phantomjs + 0xb25737
    rip = 0x0000000000f25738   rsp = 0x00007fff7e2c8070
    Found by: stack scanning

Thread 1
 0  libc-2.11.3.so + 0xa0c5d
    rbx = 0x00007f22d0cead80   r12 = 0x00000000ffffffff
    r13 = 0x00007f228572f4b0   r14 = 0x0000000002a7e680
    r15 = 0x0000000002a7e650   rip = 0x00007f22d7f87c5d
    rsp = 0x00007f22d0ceac50   rbp = 0x00007f22d0cead00
    Found by: given as instruction pointer in context
 1  libc-2.11.3.so + 0xa0acf
    rip = 0x00007f22d7f87ad0   rsp = 0x00007f22d0ceac60
    rbp = 0x00007f22d0cead00
    Found by: stack scanning
 2  phantomjs + 0x18b5c6f
    rip = 0x0000000001cb5c70   rsp = 0x00007f22d0ceac68
    rbp = 0x00007f22d0cead00
    Found by: stack scanning
 3  ld-2.11.3.so + 0x9009
    rip = 0x00007f22d94e300a   rsp = 0x00007f22d0ceaca0
    rbp = 0x00007f22d0cead00
    Found by: stack scanning
 4  ld-2.11.3.so + 0x982b
    rip = 0x00007f22d94e382c   rsp = 0x00007f22d0ceace0
    rbp = 0x00007f22d0cead00
    Found by: stack scanning
 5  libpthread-2.11.3.so + 0xefef
    rip = 0x00007f22d8a03ff0   rsp = 0x00007f22d0ceacf8
    rbp = 0x00007f22d0cead00
    Found by: stack scanning
 6  ld-2.11.3.so + 0x9af1
    rip = 0x00007f22d94e3af2   rsp = 0x00007f22d0cead00
    rbp = 0x00007f22d0cead00
    Found by: stack scanning
 7  libc-2.11.3.so + 0xe217
    rip = 0x00007f22d7ef5218   rsp = 0x00007f22d0cead48
    Found by: stack scanning
 8  libpthread-2.11.3.so + 0xb295
    rip = 0x00007f22d8a00296   rsp = 0x00007f22d0ceae18
    Found by: stack scanning
 9  phantomjs + 0xdda2d
    rip = 0x00000000004dda2e   rsp = 0x00007f22d0ceae40
    Found by: stack scanning
10  libpthread-2.11.3.so + 0x10fbf
    rip = 0x00007f22d8a05fc0   rsp = 0x00007f22d0ceae70
    Found by: stack scanning
11  libpthread-2.11.3.so + 0x10fbf
    rip = 0x00007f22d8a05fc0   rsp = 0x00007f22d0ceaea0
    Found by: stack scanning
12  phantomjs + 0xddc98
    rip = 0x00000000004ddc99   rsp = 0x00007f22d0ceaec0
    Found by: stack scanning
13  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f22d89fb8ca   rsp = 0x00007f22d0ceaed0
    Found by: stack scanning
14  libpthread-2.11.3.so + 0x10fbf
    rip = 0x00007f22d8a05fc0   rsp = 0x00007f22d0ceaf78
    Found by: stack scanning
15  libc-2.11.3.so + 0xcfb6c
    rip = 0x00007f22d7fb6b6d   rsp = 0x00007f22d0ceafe0
    Found by: stack scanning

Thread 2
 0  libc-2.11.3.so + 0xc93e3
    rbx = 0x0000000000000000   r12 = 0x00007f22d04e9da0
    r13 = 0x0000000000000008   r14 = 0x0000000003ddf2b8
    r15 = 0x0000000003ddf550   rip = 0x00007f22d7fb03e3
    rsp = 0x00007f22d04e9b70   rbp = 0x0000000003ddf100
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906326
    rip = 0x0000000001d06327   rsp = 0x00007f22d04e9b80
    Found by: stack scanning
 2  ld-2.11.3.so + 0x9009
    rip = 0x00007f22d94e300a   rsp = 0x00007f22d04e9ba0
    Found by: stack scanning
 3  phantomjs + 0x136119
    rip = 0x000000000053611a   rsp = 0x00007f22d04e9ba8
    Found by: stack scanning
 4  phantomjs + 0x19075e6
    rip = 0x0000000001d075e7   rsp = 0x00007f22d04e9c10
    Found by: stack scanning
 5  phantomjs + 0x18f6ab6
    rip = 0x0000000001cf6ab7   rsp = 0x00007f22d04e9c30
    Found by: stack scanning
 6  phantomjs + 0x18019c2
    rip = 0x0000000001c019c3   rsp = 0x00007f22d04e9c40
    Found by: stack scanning
 7  phantomjs + 0x136119
    rip = 0x000000000053611a   rsp = 0x00007f22d04e9c58
    Found by: stack scanning
 8  librt-2.11.3.so + 0x3e7e
    rip = 0x00007f22d8c14e7f   rsp = 0x00007f22d04e9c70
    Found by: stack scanning
 9  phantomjs + 0x1840b73
    rip = 0x0000000001c40b74   rsp = 0x00007f22d04e9c90
    Found by: stack scanning
10  phantomjs + 0x136119
    rip = 0x000000000053611a   rsp = 0x00007f22d04e9ca8
    Found by: stack scanning
11  phantomjs + 0x1840a78
    rip = 0x0000000001c40a79   rsp = 0x00007f22d04e9cd0
    Found by: stack scanning
12  phantomjs + 0x1906fa5
    rip = 0x0000000001d06fa6   rsp = 0x00007f22d04e9ce0
    Found by: stack scanning
13  phantomjs + 0x136119
    rip = 0x000000000053611a   rsp = 0x00007f22d04e9cf8
    Found by: stack scanning
14  phantomjs + 0x136119
    rip = 0x000000000053611a   rsp = 0x00007f22d04e9d18
    Found by: stack scanning
15  phantomjs + 0x1908091
    rip = 0x0000000001d08092   rsp = 0x00007f22d04e9d50
    Found by: stack scanning
16  phantomjs + 0x18dd4b4
    rip = 0x0000000001cdd4b5   rsp = 0x00007f22d04e9da0
    Found by: stack scanning
17  phantomjs + 0x18ddca8
    rip = 0x0000000001cddca9   rsp = 0x00007f22d04e9db0
    Found by: stack scanning
18  phantomjs + 0x18dd917
    rip = 0x0000000001cdd918   rsp = 0x00007f22d04e9dd0
    Found by: stack scanning
19  phantomjs + 0x17dfdf5
    rip = 0x0000000001bdfdf6   rsp = 0x00007f22d04e9e30
    Found by: stack scanning
20  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f22d04e9e80
    Found by: stack scanning
21  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f22d89fb8ca   rsp = 0x00007f22d04e9ed0
    Found by: stack scanning

Thread 3
 0  libc-2.11.3.so + 0xc93e3
    rbx = 0x00007f228ec32d50   r12 = 0x0000000000536130
    r13 = 0x0000000000000045   r14 = 0x0000000003e4e3c8
    r15 = 0x0000000003e4e660   rip = 0x00007f22d7fb03e3
    rsp = 0x00007f228ec32b70   rbp = 0x00000000000d6728
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906227
    rip = 0x0000000001d06228   rsp = 0x00007f228ec32b80
    Found by: stack scanning
 2  phantomjs + 0x13612f
    rip = 0x0000000000536130   rsp = 0x00007f228ec32b98
    Found by: stack scanning
 3  phantomjs + 0x13612f
    rip = 0x0000000000536130   rsp = 0x00007f228ec32ba8
    Found by: stack scanning
 4  phantomjs + 0x13612f
    rip = 0x0000000000536130   rsp = 0x00007f228ec32bc8
    Found by: stack scanning
 5  phantomjs + 0x19075e6
    rip = 0x0000000001d075e7   rsp = 0x00007f228ec32c10
    Found by: stack scanning
 6  phantomjs + 0x18f6ab6
    rip = 0x0000000001cf6ab7   rsp = 0x00007f228ec32c30
    Found by: stack scanning
 7  phantomjs + 0x18019f3
    rip = 0x0000000001c019f4   rsp = 0x00007f228ec32c40
    Found by: stack scanning
 8  phantomjs + 0x13612f
    rip = 0x0000000000536130   rsp = 0x00007f228ec32c58
    Found by: stack scanning
 9  librt-2.11.3.so + 0x3e7e
    rip = 0x00007f22d8c14e7f   rsp = 0x00007f228ec32c70
    Found by: stack scanning
10  phantomjs + 0x1840b73
    rip = 0x0000000001c40b74   rsp = 0x00007f228ec32c90
    Found by: stack scanning
11  phantomjs + 0x13612f
    rip = 0x0000000000536130   rsp = 0x00007f228ec32ca8
    Found by: stack scanning
12  phantomjs + 0x13612f
    rip = 0x0000000000536130   rsp = 0x00007f228ec32cb8
    Found by: stack scanning
13  phantomjs + 0x1907ced
    rip = 0x0000000001d07cee   rsp = 0x00007f228ec32cc0
    Found by: stack scanning
14  phantomjs + 0x1840a78
    rip = 0x0000000001c40a79   rsp = 0x00007f228ec32cd0
    Found by: stack scanning
15  phantomjs + 0x1906fa5
    rip = 0x0000000001d06fa6   rsp = 0x00007f228ec32ce0
    Found by: stack scanning
16  phantomjs + 0x13612f
    rip = 0x0000000000536130   rsp = 0x00007f228ec32cf8
    Found by: stack scanning
17  phantomjs + 0x13612f
    rip = 0x0000000000536130   rsp = 0x00007f228ec32d18
    Found by: stack scanning
18  phantomjs + 0x1908091
    rip = 0x0000000001d08092   rsp = 0x00007f228ec32d50
    Found by: stack scanning
19  phantomjs + 0x18dd4b4
    rip = 0x0000000001cdd4b5   rsp = 0x00007f228ec32da0
    Found by: stack scanning
20  phantomjs + 0x18ddca8
    rip = 0x0000000001cddca9   rsp = 0x00007f228ec32db0
    Found by: stack scanning
21  phantomjs + 0x18dd917
    rip = 0x0000000001cdd918   rsp = 0x00007f228ec32dd0
    Found by: stack scanning
22  phantomjs + 0x17dfdf5
    rip = 0x0000000001bdfdf6   rsp = 0x00007f228ec32e30
    Found by: stack scanning
23  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f228ec32e80
    Found by: stack scanning
24  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f22d89fb8ca   rsp = 0x00007f228ec32ed0
    Found by: stack scanning

Thread 4
 0  libpthread-2.11.3.so + 0xb569
    rbx = 0x0000000003e68bc0   r12 = 0x000000000000003d
    r13 = 0x00007f228e431de0   r14 = 0x0000000003e68be8
    r15 = 0x0000000000000000   rip = 0x00007f22d8a00569
    rsp = 0x00007f228e431d68   rbp = 0x0000000003e4fd30
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39d6
    rip = 0x0000000001be39d7   rsp = 0x00007f228e431dc0
    Found by: stack scanning
 2  phantomjs + 0x17d783c
    rip = 0x0000000001bd783d   rsp = 0x00007f228e431e40
    Found by: stack scanning
 3  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f228e431e80
    Found by: stack scanning
 4  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f22d89fb8ca   rsp = 0x00007f228e431ed0
    Found by: stack scanning

Thread 5
 0  libpthread-2.11.3.so + 0xb569
    rbx = 0x0000000003e68bc0   r12 = 0x0000000000000037
    r13 = 0x00007f228d3a3de0   r14 = 0x0000000003e68be8
    r15 = 0x0000000000000000   rip = 0x00007f22d8a00569
    rsp = 0x00007f228d3a3d68   rbp = 0x00007f2288018200
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39d6
    rip = 0x0000000001be39d7   rsp = 0x00007f228d3a3dc0
    Found by: stack scanning
 2  phantomjs + 0x17d783c
    rip = 0x0000000001bd783d   rsp = 0x00007f228d3a3e40
    Found by: stack scanning
 3  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f228d3a3e80
    Found by: stack scanning
 4  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f22d89fb8ca   rsp = 0x00007f228d3a3ed0
    Found by: stack scanning

Thread 6
 0  libpthread-2.11.3.so + 0xb569
    rbx = 0x0000000003e68bc0   r12 = 0x0000000000000035
    r13 = 0x00007f228cba2de0   r14 = 0x0000000003e68be8
    r15 = 0x0000000000000000   rip = 0x00007f22d8a00569
    rsp = 0x00007f228cba2d68   rbp = 0x00007f228801c2b0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39d6
    rip = 0x0000000001be39d7   rsp = 0x00007f228cba2dc0
    Found by: stack scanning
 2  phantomjs + 0x17d783c
    rip = 0x0000000001bd783d   rsp = 0x00007f228cba2e40
    Found by: stack scanning
 3  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f228cba2e80
    Found by: stack scanning
 4  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f22d89fb8ca   rsp = 0x00007f228cba2ed0
    Found by: stack scanning

Thread 7
 0  libpthread-2.11.3.so + 0xb569
    rbx = 0x0000000003e68bc0   r12 = 0x0000000000000039
    r13 = 0x00007f2287ffede0   r14 = 0x0000000003e68be8
    r15 = 0x0000000000000000   rip = 0x00007f22d8a00569
    rsp = 0x00007f2287ffed68   rbp = 0x0000000003f37fd0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39d6
    rip = 0x0000000001be39d7   rsp = 0x00007f2287ffedc0
    Found by: stack scanning
 2  phantomjs + 0x17d783c
    rip = 0x0000000001bd783d   rsp = 0x00007f2287ffee40
    Found by: stack scanning
 3  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f2287ffee80
    Found by: stack scanning
 4  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f22d89fb8ca   rsp = 0x00007f2287ffeed0
    Found by: stack scanning

Thread 8
 0  libpthread-2.11.3.so + 0xb569
    rbx = 0x0000000003e68bc0   r12 = 0x000000000000003b
    r13 = 0x00007f22877fdde0   r14 = 0x0000000003e68be8
    r15 = 0x0000000000000000   rip = 0x00007f22d8a00569
    rsp = 0x00007f22877fdd68   rbp = 0x00007f228800bf10
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39d6
    rip = 0x0000000001be39d7   rsp = 0x00007f22877fddc0
    rbp = 0x00007f228800bf10
    Found by: stack scanning
 2  phantomjs + 0x17d783c
    rip = 0x0000000001bd783d   rsp = 0x00007f22877fde40
    rbp = 0x00007f228800bf10
    Found by: stack scanning
 3  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f22877fde80
    rbp = 0x00007f228800bf10
    Found by: stack scanning
 4  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f22d89fb8ca   rsp = 0x00007f22877fded0
    rbp = 0x00007f228800bf10
    Found by: stack scanning

Thread 9
 0  libpthread-2.11.3.so + 0xb1fc
    rbx = 0x0000000003f13250   r12 = 0x004189374bc6a7ef
    r13 = 0xffffffffffffffff   r14 = 0x0000000003f13278
    r15 = 0x0000000003f13210   rip = 0x00007f22d8a001fc
    rsp = 0x00007f2286ffcd38   rbp = 0x00007f228ef64190
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39f4
    rip = 0x0000000001be39f5   rsp = 0x00007f2286ffcd60
    rbp = 0x00007f228ef64190
    Found by: stack scanning
 2  phantomjs + 0xe70e9
    rip = 0x00000000004e70ea   rsp = 0x00007f2286ffcde0
    rbp = 0x00007f228ef64190
    Found by: stack scanning
 3  phantomjs + 0xd85268
    rip = 0x0000000001185269   rsp = 0x00007f2286ffce00
    rbp = 0x00007f228ef64190
    Found by: stack scanning
 4  phantomjs + 0xd85492
    rip = 0x0000000001185493   rsp = 0x00007f2286ffce40
    rbp = 0x00007f228ef64190
    Found by: stack scanning
 5  phantomjs + 0xe68fa
    rip = 0x00000000004e68fb   rsp = 0x00007f2286ffce70
    rbp = 0x00007f228ef64190
    Found by: stack scanning
 6  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f2286ffce80
    rbp = 0x00007f228ef64190
    Found by: stack scanning
 7  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f22d89fb8ca   rsp = 0x00007f2286ffced0
    rbp = 0x00007f228ef64190
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x0268dfff  phantomjs  ???  (main)
0x7f227f99d000 - 0x7f227f9b3fff  z003034l.pfb  ???
0x7f227f9bc000 - 0x7f227f9d6fff  p052003l.pfb  ???
0x7f227fde6000 - 0x7f227fdfdfff  n022003l.pfb  ???
0x7f2284de3000 - 0x7f2284dfbfff  n021003l.pfb  ???
0x7f2285316000 - 0x7f228532dfff  c059036l.pfb  ???
0x7f228532e000 - 0x7f2285345fff  c059033l.pfb  ???
0x7f2285706000 - 0x7f2285711fff  d050000l.pfb  ???
0x7f2285712000 - 0x7f228572bfff  c059013l.pfb  ???
0x7f2285812000 - 0x7f228581afff  s050000l.pfb  ???
0x7f228c1fe000 - 0x7f228c218fff  c059016l.pfb  ???
0x7f228c219000 - 0x7f228c231fff  b018012l.pfb  ???
0x7f228c232000 - 0x7f228c243fff  n019004l.pfb  ???
0x7f228c244000 - 0x7f228c253fff  a010015l.pfb  ???
0x7f228d400000 - 0x7f228d605fff  libnss_dns-2.11.3.so  ???
0x7f228d606000 - 0x7f228d807fff  libnss_mdns4_minimal.so.2  ???
0x7f228d808000 - 0x7f228da14fff  libnss_files-2.11.3.so  ???
0x7f228da15000 - 0x7f228dc28fff  libresolv-2.11.3.so  ???
0x7f228f477000 - 0x7f228f48afff  n019003l.pfb  ???
0x7f22d0cec000 - 0x7f22d0f42fff  libssl.so.0.9.8  ???
0x7f22d0f43000 - 0x7f22d12dffff  libcrypto.so.0.9.8  ???
0x7f22d12e4000 - 0x7f22d7aa7fff  locale-archive  ???
0x7f22d7aa8000 - 0x7f22d7ccffff  libexpat.so.1.5.2  ???
0x7f22d7cd0000 - 0x7f22d7ee6fff  libz.so.1.2.3.4  ???
0x7f22d7ee7000 - 0x7f22d8243fff  libc-2.11.3.so  ???
0x7f22d8249000 - 0x7f22d845efff  libgcc_s.so.1  ???
0x7f22d845f000 - 0x7f22d86e0fff  libm-2.11.3.so  ???
0x7f22d86e1000 - 0x7f22d89dffff  libstdc++.so.6.0.13  ???
0x7f22d89f5000 - 0x7f22d8c0cfff  libpthread-2.11.3.so  ???
0x7f22d8c11000 - 0x7f22d8e18fff  librt-2.11.3.so  ???
0x7f22d8e19000 - 0x7f22d901cfff  libdl-2.11.3.so  ???
0x7f22d901d000 - 0x7f22d9251fff  libfontconfig.so.1.4.4  ???
0x7f22d9252000 - 0x7f22d94d9fff  libfreetype.so.6.6.0  ???
0x7f22d94da000 - 0x7f22d94f7fff  ld-2.11.3.so  ???
0x7f22d96ce000 - 0x7f22d96d4fff  gconv-modules.cache  ???
0x7f22d96d5000 - 0x7f22d96ddfff  945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-3  ???
0x7f22d96de000 - 0x7f22d96e6fff  e13b20fdb08344e0e664864cc2ede53d-le64.cache-3  ???
0x7f22d96f4000 - 0x7f22d96f4fff  libc.mo  ???
0x7fff7e3ff000 - 0x7fff7e3fffff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
