### ISSUE TITLE
PhantomJS 1.9.7 (Windows 7) crashes in WebKit JavaScript GC code

### ISSUE THREAD

**Issue by brandonjacob** [ariya/phantomjs#12238]
We are using PhantomJS to execute our QUnit-based test suites.  One of our test suites is crashing infrequently in what appears to be WebKit JavaScript GC code.  It is crashing more consistently against a debug build of the phantomjs binary.

I used the instructions on http://phantomjs.org/build.html and additional help on https://groups.google.com/forum/#!topic/phantomjs/qgcpXILe-_0 to build the debug phantomjs binary based on the 1.9 branch from your git repository (I think this amounts to 1.9.7 + a few additional commits).  All executions were on Windows 7.

At first I just tried to use windbg to examine a crash dump file that is generated from the google breakpad library that is linked into the phantomjs executable. But I quickly found that the thread stacks weren't as helpful because they represented the state of the process _after_ the access violation.  I ran the phantomjs process inside windbg so that windbg could break at the point where the access violation occurs. 

Unfortunately I cannot provide a nice, easily reproducible test case at this time.  The test suite that triggers the crash requires a large number of internally developed JS libraries that I cannot distribute (intellectual property concerns).  Because I'm not sure what conditions and steps are necessary to trigger this crash, it's difficult to come up with a reproducible test case that doesn't depend our corporate JS libs.  The best I can do is provide you with the thread stacks at the time of the crash. 

If you have any further questions, I'll do my best to help.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by zabihimayvan** [comment]
I am using Phantomjs 2.1.1 and have similar issue (crashing) frequently. In fact, I have a crawler to extract all hyper links of web pages. But, Phantomjs does crash in most cases. I would be appreciative if you let me know the solution!
