### ISSUE TITLE
Call phantom.exit() in onUrlChanged will crash phantomjs.

### ISSUE THREAD

**Issue by ownwaterloo** [ariya/phantomjs#12232]
The minimal program which causes this issue is:

``` javascript
var args = require('system').args
var page = require('webpage').create()
page.onUrlChanged = phantom.exit
page.open(args[1] || 'http://phantomjs.org/crash-reporting.html')
```

The original and simplified program is:

``` javascript
var args = require('system').args
var page = require('webpage').create()
page.open
( 'https://github.com/login'
, function(status){
    if (status !== 'success') phantom.exit()
    console.log(status)
    page.onUrlChanged = phantom.exit
    page.sendEvent('keypress', args[1])
    page.sendEvent('keypress', page.event.key.Tab)
    page.sendEvent('keypress', args[2])
    page.sendEvent('keypress', page.event.key.Enter)
})
```

Environment:
- OS: Ubuntu 12.04 TLS x64
- PhantomJS:  
  https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
- Symbol files:  
  https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64-symbols.tar.bz2

Couldn't get the stack trace from the crash dump. Is this another issue?

**Comment by glenselle** [comment]
I was about to open an issue when I noticed there was already one that matched exactly what I was seeing. This seems like a serious issue. If I want to end my automation in the `onUrlChanged` handler, it crashes PhantomJS. All you need to do to repro this is open a page and `exit()` PhantomJS from within the 'onUrlChanged` handler. 

System:
OS: Mac OSX 10.11.6
PhantomJS: Homebrew install (version 2.1.1)

```
page.open('https://google.com')
page.onUrlChanged = function() {
  phantom.exit()
}
```

```
1   0x106a31ad8
2   0x106a31660
3   0x106a3517a
4   0x106a35280
5   0x106a49d74
6   0x106a670a0
7   0x106a69362
8   0x1068f1d04
9   0x106a68602
10  0x106a492f0
11  0x106a464eb
12  0x106a48f7e
13  0x106903c83
14  0x1068bc2aa
15  0x1068bc253
16  0x10685bb5f
17  0x1068b28cd
18  0x106935824
19  0x1076faf30
20  0x1077c0d7c
21  0x52ce9482bba7
22  0x107853ad4
23  0x1079666e5
24  0x1077064c3
25  0x10693a8e1
26  0x10693a9a1
27  0x10836b440
28  0x1068b5868
29  0x10686e642
30  0x10836b4f3
31  0x1068bba0c
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault: 11
```

Is this issue being addressed or should I avoid doing `exit()` within 'onUrlChanged`?

**Comment by glenselle** [comment]
Just to followup, I believe wrapping the exit in a `setTimeout` of 0 seconds resolves the issue. Must be an event loop thing. 

```
page.open('https://google.com')
page.onUrlChanged = function() {
  setTimeout(function() { 
    phantom.exit()
  }, 0)
}
```
