### ISSUE TITLE
OS X 10.9.3 crash

### ISSUE THREAD

**Issue by lsfalimis** [ariya/phantomjs#12242]
I installed phantomjs via `brew update && brew install phantomjs`.

**github.js**
```
var page = require('webpage').create();
page.open('http://github.com/', function() {
  page.render('github.png');
  phantom.exit();
});
```

Running `phantomjs github.js`, get the following output:

```
PhantomJS has crashed. Please read the crash reporting guide at 
https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at 
https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: 
/tmp/FA3281F5-C074-43A1-83DC-B4284244CD30.dmp
```

Please see crash dump file here
http://cl.ly/1D440i3z3k3l

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
