### ISSUE TITLE
Cookie header does not get sent

### ISSUE THREAD

**Issue by snetface** [ariya/phantomjs#12259]
Ok, so I tried to give it multiple ways to go, but I could not find a solution. Maybe somebody can help me with this: I am trying to add Cookies to the my request.

I am running phatomjs1.9.7 in Windows7 Home Basic 64bit.

First I tried the dedicated methods: phantom.addCookie, and page.addCookie. 
Both functions return true, but there is no Cookie header neither when I print request headers to the consol in the onResourceRequested callback, neither if I try to check within a php script among the headers it got.
If I check back the added cookies in the end like: 

page.open(url, function (status) {
    for (var i = 0; i < page.cookies.length; i++) {
        console.log(page.cookies[i].name + "=" + page.cookies[i].value);
    }
});

All the cookies I added are there. Yet there is no cookie header in the request.

Then I tried modifying with networkRequest.setHeader method, that seems to be undefined. 

Than I tried modifying page.customheades upon every requested resource.
This is needed as cookies get updated during the request.

Page.customheaders does actually modify the headers, the only problem is, that the cookies set are actually not getting sent with the current request from onResourceRequested, but only with the following. This is obviously not sufficient.

I am totally clueless regarding what else can I actully do to get those cookies sent and why are phatnom.addCookies, page.addCookies and networkRequest.addHeader not working.

Please give me some help or look into this issue! If you need any more of the code or some additional information I have not thought of, just leave a reply and I will post it!

**Comment by elliotatRetireup** [comment]
I have the same problem. I set a cookie, then check that the cookie is in the phantom instance. Then when I request on the same domain the cookie is not sent.
