### ISSUE TITLE
consistent crash - 1.9.7, OSX 1.9.2, test cases with CucumberJS, WebDriverJS, Protractor

### ISSUE THREAD

**Issue by aabes** [ariya/phantomjs#12256]
I have a 100% reproducible crash scenario, but alas the 
The debug output on the console is here: https://gist.github.com/aabes/b40e071936bcb92c6ec5

The scenario is a cucumberJS test against a local server, and it consistently crashes at the same location (which is part of an end-to-end webdriver test)

My fallback option for now is to use Chrome via selenium, but would love to have the speed that phantomJS brings...

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
