### ISSUE TITLE
Behavior different between cmdline and --config

### ISSUE THREAD

**Issue by bronson** [ariya/phantomjs#12265]
Using --load-images, defaultPageSettings.loadImages gets set to false as expected:

```
~$ phantomjs --load-images=false
phantomjs> console.log(phantom.defaultPageSettings.loadImages)
false
undefined
phantomjs> phantom.exit(0)
```

but putting this config in a json file and calling with --config doesn't work:

```
~$ cat config.json 
{"autoLoadImages": false, "loadImages": false}
~$ phantomjs --config=config.json
phantomjs> console.log(phantom.defaultPageSettings.loadImages)
true                                            <===  ?!
undefined
phantomjs> phantom.exit(0)
```

Am I missing something?

Update: config.json contains both the expected name and the name suggested by https://github.com/ariya/phantomjs/issues/11775

Update2: This is in both 1.9.2 and 1.9.7 on mac.

**Comment by branneman** [comment]
This is still an issue **2 years later** with PhantomJS 2.1.1. Any plans on getting this fixed?
