### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by farnabaz** [ariya/phantomjs#12263]
why i'm getting this error?
phantomjs 1.9.7 on centos 6.3
Operating system: Linux
                  0.0.0 Linux 2.6.32-042stab081.3 #1 SMP Mon Sep 9 20:07:47 MSK 2013 x86_64
CPU: amd64
     family 6 model 60 stepping 3
     1 CPU

Crash reason:  SIGSEGV
Crash address: 0xbbadbeef

Thread 0 (crashed)
 0  phantomjs!WTF::OSAllocator::reserveUncommitted [OSAllocatorPosix.cpp : 107 + 0x7]
    rbx = 0xffffffffffffffff   r12 = 0x000000000388e760
    r13 = 0x000000000000007f   r14 = 0x00007f5ebbf84820
    r15 = 0x00007f5ebbf84720   rip = 0x00000000004f8057
    rsp = 0x00007fffbd6cfc30   rbp = 0x7ff8000000000000
    Found by: given as instruction pointer in context
 1  phantomjs!JSC::ExecutableAllocator::isValid [PageReservation.h : 107 + 0x18]
    rbx = 0x000000000388e740   r12 = 0x000000000388e760
    r13 = 0x000000000000007f   r14 = 0x00007f5ebbf84820
    r15 = 0x00007f5ebbf84720   rip = 0x0000000000f31fd1
    rsp = 0x00007fffbd6cfc40   rbp = 0x7ff8000000000000
    Found by: call frame info
 2  phantomjs!JSC::ExecutableAllocator::ExecutableAllocator [ExecutableAllocator.h : 185 + 0x7]
    rbx = 0x0000000002a9ec58   r12 = 0x0000000003613d00
    r13 = 0x000000000000007f   r14 = 0x00007f5ebbf84820
    r15 = 0x00007f5ebbf84720   rip = 0x0000000000f88d66
    rsp = 0x00007fffbd6cfc90   rbp = 0x7ff8000000000000
    Found by: call frame info
 3  phantomjs!JSC::JSGlobalData::JSGlobalData [JSGlobalData.cpp : 170 + 0x9]
    rbx = 0x00007f5ebbf83000   r12 = 0x0000000003613d00
    r13 = 0x000000000000007f   r14 = 0x0000000000000085
    r15 = 0x00007f5ebbf84720   rip = 0x0000000000f89b2e
    rsp = 0x00007fffbd6cfd00   rbp = 0x7ff8000000000000
    Found by: call frame info
 4  phantomjs!JSC::JSGlobalData::createLeaked [JSGlobalData.cpp : 326 + 0x9]
    rbx = 0x0000000000000000   r12 = 0x00007fffbd6cffa0
    r13 = 0x000000000388a4a0   r14 = 0x00007fffbd6d0040
    r15 = 0x00000000036851b0   rip = 0x0000000000f8b5b1
    rsp = 0x00007fffbd6cff80   rbp = 0x00007f5ebbf83000
    Found by: call frame info
 5  phantomjs!WebCore::JSDOMWindowBase::commonJSGlobalData [JSDOMWindowBase.cpp : 159 + 0x9]
    rbx = 0x00007fffbd6d0090   r12 = 0x00007fffbd6d0160
    r13 = 0x000000000388a4a0   r14 = 0x00007fffbd6d0040
    r15 = 0x00000000036851b0   rip = 0x000000000051d382
    rsp = 0x00007fffbd6cffa0   rbp = 0x00007f5ebbf77000
    Found by: call frame info
 6  phantomjs!WebCore::FrameLoaderClientQt::createDocumentLoader [FrameLoaderClientQt.cpp : 990 + 0x4]
    rbx = 0x00007fffbd6d0090   r12 = 0x00007fffbd6d0160
    r13 = 0x000000000388a4a0   r14 = 0x00007fffbd6d0040
    r15 = 0x00000000036851b0   rip = 0x00000000004b900d
    rsp = 0x00007fffbd6cffd0   rbp = 0x00007f5ebbf77000
    Found by: call frame info
 7  phantomjs!WebCore::FrameLoader::load [FrameLoader.cpp : 1460 + 0x13]
    rbx = 0x0000000000000000   r12 = 0x00007f5ebbf7a478
    r13 = 0x000000000388e6a0   r14 = 0x0000000003a2b930
    r15 = 0x00000000036851b0   rip = 0x0000000000864b57
    rsp = 0x00007fffbd6d0000   rbp = 0x0000000000000001
    Found by: call frame info
 8  phantomjs!QWebFrame::setHtml [qwebframe.cpp : 976 + 0x1d]
    rbx = 0x0000000000000000   r12 = 0x00007f5ebbfb4440
    r13 = 0x000000000388e6a0   r14 = 0x0000000003a2b930
    r15 = 0x00000000036851b0   rip = 0x00000000004827d1
    rsp = 0x00007fffbd6d0090   rbp = 0x0000000000000001
    Found by: call frame info
 9  phantomjs!WebPage::WebPage [webpage.cpp : 323 + 0x12]
    rbx = 0x0000000003a2b910   r12 = 0x00007fffbd6d0430
    r13 = 0x00007fffbd6d0420   r14 = 0x0000000003a2b930
    r15 = 0x0000000003a2b938   rip = 0x000000000041833e
    rsp = 0x00007fffbd6d0320   rbp = 0x000000000387ccd0
    Found by: call frame info
10  phantomjs!Phantom::init [phantom.cpp : 102 + 0x40]
    rbx = 0x000000000387ccd0   r12 = 0x0000000003a4cb40
    r13 = 0x0000000003a4cae0   r14 = 0x00007fffbd6d09f0
    r15 = 0x0000000000000000   rip = 0x0000000000409bf3
    rsp = 0x00007fffbd6d0480   rbp = 0x00007fffbd6d06f0
    Found by: call frame info
11  phantomjs!Phantom::instance [phantom.cpp : 154 + 0x4]
    rbx = 0x00007fffbd6d0b00   r12 = 0x00007fffbd6d0a80
    r13 = 0x00007fffbd6d0c28   r14 = 0x00007fffbd6d09f0
    r15 = 0x0000000000000000   rip = 0x000000000040b576
    rsp = 0x00007fffbd6d09c0   rbp = 0x0000000003a4cae0
    Found by: call frame info
12  phantomjs!main [main.cpp : 117 + 0x4]
    rbx = 0x00007fffbd6d0b00   r12 = 0x00007fffbd6d0a80
    r13 = 0x00007fffbd6d0c28   r14 = 0x00007fffbd6d09f0
    r15 = 0x0000000000000000   rip = 0x0000000000427c9e
    rsp = 0x00007fffbd6d09e0   rbp = 0x00007fffbd6d0c18
    Found by: call frame info
13  libc-2.12.so + 0x1ed1c
    rbx = 0x0000000000000000   r12 = 0x0000000000407cc0
    r13 = 0x00007fffbd6d0c10   r14 = 0x0000000000000000
    r15 = 0x0000000000000000   rip = 0x00007f5eba855d1d
    rsp = 0x00007fffbd6d0b40   rbp = 0x0000000000000000
    Found by: call frame info
14  phantomjs + 0x27a5f
    rip = 0x0000000000427a60   rsp = 0x00007fffbd6d0b60
    Found by: stack scanning

Thread 1
 0  libc-2.12.so + 0xe8b41
    rbx = 0x00007f5eb2d7a700   r12 = 0x00007f5ebb587360
    r13 = 0x00007f5eb2d7a9c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007f5eba91fb41
    rsp = 0x00007f5eb2d79fd0   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  libpthread-2.12.so + 0x78ff
    rip = 0x00007f5ebb372900   rsp = 0x00007f5eb2d79fd8
    Found by: stack scanning

Thread 2
 0  libc-2.12.so + 0xe15f3
    rbx = 0x0000000000000000   r12 = 0x00007f5eb2378d70
    r13 = 0x000000000000000a   r14 = 0x00007f5eac000a98
    r15 = 0x00007f5eac000d30   rip = 0x00007f5eba9185f3
    rsp = 0x00007f5eb2378b40   rbp = 0x00007f5eac0008e0
    Found by: given as instruction pointer in context
 1  phantomjs!qt_safe_select [qcore_unix.cpp : 83 + 0x15]
    rip = 0x0000000001d06327   rsp = 0x00007f5eb2378b50
    Found by: stack scanning
 2  phantomjs!QEventDispatcherUNIXPrivate::doSelect [qeventdispatcher_unix.cpp : 223 + 0xd]
    rbx = 0x00007f5eac0012b0   r12 = 0x00007f5eb2378d70
    r13 = 0x00007f5eac0008e0   r14 = 0x0000000000000000
    r15 = 0x00007f5eac000d30   rip = 0x0000000001d075e7
    rsp = 0x00007f5eb2378be0   rbp = 0x00007f5eac0008e0
    Found by: call frame info
 3  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 937 + 0x4]
    rbx = 0x00007f5eac0012b0   r12 = 0x00007f5eb2378d70
    r13 = 0x00007f5eac0008c0   r14 = 0x0000000000000001
    r15 = 0x00000000035f9118   rip = 0x0000000001d08092
    rsp = 0x00007f5eb2378d20   rbp = 0x00007f5eac0008e0
    Found by: call frame info
 4  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x00007f5eac0012b0   r12 = 0x00007f5eb2378e00
    r13 = 0x00007f5eb2378e10   r14 = 0x00000000035a5230
    r15 = 0x00000000035f9118   rip = 0x0000000001cdd4b5
    rsp = 0x00007f5eb2378d70   rbp = 0x00007f5eb2378db0
    Found by: call frame info
 5  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x00007f5eac0012b0   r12 = 0x00007f5eb2378e00
    r13 = 0x00007f5eb2378e10   r14 = 0x00000000035a5230
    r15 = 0x00000000035f9118   rip = 0x0000000001cdd918
    rsp = 0x00007f5eb2378da0   rbp = 0x00007fffbd6d0a80
    Found by: call frame info
 6  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
    rbx = 0x00000000035f9090   r12 = 0x00000000035f9118
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000000001bdfdf6
    rsp = 0x00007f5eb2378e00   rbp = 0x00000000035f9118
    Found by: call frame info
 7  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x00000000035f9118   r12 = 0x00000000035f9200
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000000001be2cc2
    rsp = 0x00007f5eb2378e50   rbp = 0x0000000003630da0
    Found by: call frame info
 8  libpthread-2.12.so + 0x79d0
    rbx = 0x0000000000000000   r12 = 0x00007fffbd6cff60
    r13 = 0x00007f5eb23799c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x00007f5ebb3729d1
    rsp = 0x00007f5eb2378ea0   rbp = 0x0000000000000000
    Found by: call frame info

Loaded modules:
0x00400000 - 0x0268dfff  phantomjs  ???  (main)
0x7f5eb2d7b000 - 0x7f5eb2f98fff  libselinux.so.1  ???
0x7f5eb2f9a000 - 0x7f5eb31b1fff  libresolv-2.12.so  ???
0x7f5eb31b4000 - 0x7f5eb33b6fff  libkeyutils.so.1.3  ???
0x7f5eb33b7000 - 0x7f5eb35c1fff  libkrb5support.so.0.1  ???
0x7f5eb35c2000 - 0x7f5eb37ecfff  libk5crypto.so.3.1  ???
0x7f5eb37ee000 - 0x7f5eb39f1fff  libcom_err.so.2.1  ???
0x7f5eb39f2000 - 0x7f5eb3cd7fff  libkrb5.so.3.3  ???
0x7f5eb3cd8000 - 0x7f5eb3f1bfff  libgssapi_krb5.so.2.2  ???
0x7f5eb3f1c000 - 0x7f5eb4187fff  libssl.so.1.0.1e  ???
0x7f5eb4188000 - 0x7f5eb439dfff  libz.so.1.2.3  ???
0x7f5eb439e000 - 0x7f5eb4779fff  libcrypto.so.1.0.1e  ???
0x7f5eb477e000 - 0x7f5eba60efff  locale-archive-rpm  ???
0x7f5eba60f000 - 0x7f5eba836fff  libexpat.so.1.5.2  ???
0x7f5eba837000 - 0x7f5ebabc5fff  libc-2.12.so  ???
0x7f5ebabcb000 - 0x7f5ebade0fff  libgcc_s-4.4.7-20120601.so.1  ???
0x7f5ebade1000 - 0x7f5ebb064fff  libm-2.12.so  ???
0x7f5ebb065000 - 0x7f5ebb355fff  libstdc++.so.6.0.13  ???
0x7f5ebb36b000 - 0x7f5ebb583fff  libpthread-2.12.so  ???
0x7f5ebb588000 - 0x7f5ebb78ffff  librt-2.12.so  ???
0x7f5ebb790000 - 0x7f5ebb993fff  libdl-2.12.so  ???
0x7f5ebb994000 - 0x7f5ebbbc9fff  libfontconfig.so.1.4.4  ???
0x7f5ebbbca000 - 0x7f5ebbe66fff  libfreetype.so.6.3.22  ???
0x7f5ebbe67000 - 0x7f5ebbe86fff  ld-2.12.so  ???
0x7fffbd7fe000 - 0x7fffbd7fffff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
