### ISSUE TITLE
On Windows 8 creates a folder "C:\Ofi Labs\PhantomJs" for local storage

### ISSUE THREAD

**Issue by napernik** [ariya/phantomjs#12272]
We're using PhantomJs for screen capturing.
When running on Windows 8 it creates a folder in the root folder of C:\ drive:

"C:\Ofi Labs\PhantomJs"

PhantomJs puts *.localstorage files there.
I tried to use "--local-storage-path=<some other folder path>" command line argument, but it seem to have no effect.

Not reproducible on Windows 7.

**Comment by Vitallium** [comment]
Duplicate. See #11596
