### ISSUE TITLE
page.render /dev/stdout requires --web-security=no but writing to file doesn't

### ISSUE THREAD

**Issue by rosstuck** [ariya/phantomjs#12292]
As discussed on IRC with @Vitallium, there seems to be some slightly inconsistent behavior around page.render and security.

Rendering a local HTML file with external secure AJAX calls should(?) fail without --web-security=no. However, this works when writing to a file such as page.render("/tmp/foo.pdf"). 

Stranger though, when the render destination is changed to "/dev/stdout", the command fails and outputs nothing, unless the --web-security=no is added. (As an aside, an error message would be very useful in this case).

It seems like both cases should either require the flag or not, as the the behavior was very confusing.

In both cases, I'm running with "--ignore-ssl-errors=true" as my local dev environment is using a self signed certificate. Debug log: http://pastebin.com/Q9KQakCc

**Comment by shishir-kumar** [comment]
Even i am facing the same problem. Do we have a solution for this issue?
