### ISSUE TITLE
SVG clipPath error when taking screenshot

### ISSUE THREAD

**Issue by mforkin** [ariya/phantomjs#12295]
I have an svg with two lines and two clipPath elements to show the difference between the lines. The clipPath elements are not rendered. Seems like it is probably related to this bug that was recently patched in chrome:

https://code.google.com/p/chromium/issues/detail?id=349701

The workaround solution mentioned in that post (wrapping the clipPath tag in svg tags) fixes the issue here as well.

**Comment by enjalot** [comment]
I ran into this as well, and the same workaround worked for me.
