### ISSUE TITLE
Crashed when trying to render a huge webpage

### ISSUE THREAD

**Issue by Swanty** [ariya/phantomjs#12293]
I'm trying to save the whole webpage as image.
The webpage contains a map built from smaller image tiles and it renders fine in chrome even if i fake the screen size as 15000x15000 (which is the full size of the map I want to save as image).
(I put the page with map in an iframe and set width and height to 15000 and it loaded the whole map)

I use this screenshot.js:

var page = require('webpage').create();
page.open('http://mywebsitewithhugemap.com', function () {
    page.render('mymap.png');
    phantom.exit();
});

and this screenshot.bat:

phantomjs --ignore-ssl-errors=yes --cookies-file=cookies.txt --web-security=no screenshot.js

I noticed the crash happened when PhantomJS.exe was at 1.8GB ram usage.
If you're wondering how much ram I have then I have 16 GB and 50% of the memory was used before I ran PhantomJS.

My OS is Windows 7 Ultimate (64-bit)

The crash dump file is 0B for some reason.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
