### ISSUE TITLE
PhantomJs crashing after 42 Instances running 5 clients per Instance (240) - pure virtual method called

### ISSUE THREAD

**Issue by weltonrussell** [ariya/phantomjs#12309]
Hi,

I have tried running a modified version of phantomjs (disable caching each open) to simulate load testing on one of my servers. After running 42 Instances with 5 Clients per instance hitting about 240 - 260 clients it crashes saying pure virtual method called.

I have tried to debug using gdb after re-compiling using the command 
./build.sh --qmake-args CONFIG+=debug

however once installed and using gdb I get the message 
Reading symbols from /usr/bin/phantomjs...(no debugging symbols found)...done. And only get thread debugging.

I was wondering if anyone would know the root cause of these two problems

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
