### ISSUE TITLE
Memory leak even when using webpage.close()

### ISSUE THREAD

**Issue by Golmote** [ariya/phantomjs#12317]
I'm using phantomjs to open many pages, one after the other, and even when I close every webpage, I keep seeing the memory grow bigger and bigger... until it crashes.

Here is the test I ended up with :

``` javascript
var process = function() {
    var page = require('webpage').create();
    page.open('http://www.google.com', function(status) {
        page.close();
        process();
    });
};
process();
```

I'm using phantomjs 1.9.7 on Windows 7.

**Comment by lostthetrail** [comment]
I believe I am also experiencing this with while running Jasmine tests.
I can run the suite in a real browser and see no memory leak, but when ran in phantomjs, it continues to grow.

PhantomJS 1.9.17

**Comment by Vitallium** [comment]
Let's track this in https://github.com/ariya/phantomjs/issues/11390
