### ISSUE TITLE
Array.prototype.indexOf does not behave similar to other browers

### ISSUE THREAD

**Issue by vyrak** [ariya/phantomjs#12310]
If I called `Array.prototype.indexOf.call(null, 'something')` or `[].indexOf.call(null, 'something')`, the returned value is `-1`.  In Chrome (v35.0.1916.114) & Safari (v7.0.4 (9537.76.4)), both raises an exception.

I ran into this case when using CoffeeScript's `in` keyword to check if an item existed within an reference thought to be an array.  This snippet of CoffeeScript compiled down to `[].indexOf.call`.  I had tests passing against PhantomJS, which I would consider a false positive in this case, because errors were raised in the other browsers.

I believe it makes the most sense to keep the behavior consistent with those other browsers.  It should raise an exception if `Array.prototype.indexOf` is invoked with a context set to `null` or `undefined`.

Edit:  The same can be said of `String.prototype.indexOf` as well.

**Comment by ariya** [comment]
This is fixed in PhantomJS 2. It throws an exception with `null` as the first parameter.
