### ISSUE TITLE
phantomjs susceptible to XML expansion attack

### ISSUE THREAD

**Issue by dys** [ariya/phantomjs#12328]
I use phantomjs as part of the test automation suite for our product's backend. I used phantom to run the http://en.wikipedia.org/wiki/Billion_laughs attack through our product's scanners, which handled it fine--but phantomjs hung and eventually exploded with a segfault.

To reproduce, copy the sample XML from the wikipedia page into a file and try to open it with phantomjs. Kaboom!

**Comment by CarlAmbroselli** [comment]
This issue still persists! Is it planned to fix this in near future? 

With this I can kill every phantom.js server if I can make it somehow load an arbitrary page.
