### ISSUE TITLE
Crash report: pure virtual method called

### ISSUE THREAD

**Issue by subwindow** [ariya/phantomjs#12325]
This appears to be exactly the same as #11293  and #10666. Apparently at random (less than 1 in 100 calls to phantomjs), phantomjs will crash and give the output:

```
pure virtual method called
terminate called without active exception
```

This is happening on phantomjs 1.9.1 on Debian Wheezy. I have the phantomjs.dmp file, but unfortunately I can't attach it to the ticket for some reason.

**Comment by sylvinus** [comment]
Having this issue as well with 1.9.8 in our unit tests, on a local static URL, randomly. No proxy involved.

**Comment by catharsis** [comment]
Feel free to try the patch out and see if it solves your problems - let me know if you find any issues with it.
https://github.com/ariya/phantomjs/issues/12869

**Comment by tigerfz** [comment]
i also met this problem when using phantomjs-1.9.7.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
