### ISSUE TITLE
phantomjs crash dump

### ISSUE THREAD

**Issue by fbaligand** [ariya/phantomjs#12330]
Hi,

I use phantomjs through selenium, and have very often a phantomjs crash, after about 15-30 minutes (never on the same test).

Here's the crash dump : https://www.dropbox.com/s/687bhg6tr6sfgy6/27ec3fd2-a04b-d97f-604cd384-565a9021.dmp
Can you tell me what is the problem ?

Hope it can help you enhance phantomjs.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
