### ISSUE TITLE
PhantomJS Crash Dump ~ 1.9.7

### ISSUE THREAD

**Issue by daviscabral** [ariya/phantomjs#12333]
I'm using PhantomJS with Protractor and Selenium and I'm getting this crash all the time with the GhostDriver.
```
Operating system: Mac OS X
                  10.9.3 13D65
CPU: amd64
     family 6 model 23 stepping 10
     2 CPUs
 
Crash reason:  EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
Crash address: 0x8 
```
https://gist.github.com/daviscabral/04e840de9f952e91945e

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
