### ISSUE TITLE
Crash on taking screenshot using ratersize.js

### ISSUE THREAD

**Issue by madhatter42** [ariya/phantomjs#12348]
PhantomJS is crashing intermittently when trying to take screenshots of webpages using rasterize.js. Here's the output that we're getting from Phantom:

pure virtual method called
terminate called without an active exception
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/08ab8c5a-241f-3a05-4b34cf7a-57306429.dmp
Aborted

The crash report can be found at http://d.pr/f/w177

Would appreciate your help in resolving this issue. Thanks!

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
