### ISSUE TITLE
Phantom crashing on my CI environment.

### ISSUE THREAD

**Issue by jamesotron** [ariya/phantomjs#12343]
Just following the instructions by raising an issue and attaching the dump file here: https://www.dropbox.com/s/1hmxcrbfhsan1nc/042ada2b-957a-57bc-15f2f0f5-05195f1c.dmp

Testing an (old) Ember.js app with cucumber and capybara using poltergeist. I'll do more investigation.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
