### ISSUE TITLE
SVG style manipulation causes freeze and 100% CPU on load

### ISSUE THREAD

**Issue by chrisirhc** [ariya/phantomjs#12358]
To reproduce:
1. Load a page with the following d3 code to generate a path on an svg:
   
   ``` js
   var svg = d3.select(document.body).append("svg:svg")
       .attr("width", 960)
       .attr("height", 500)
   ;
   
   var path = svg.append('svg:path')
       // Comment out any of the following four lines and PhantomJS won't freeze
       .attr('d', 'M448,25L801,25')
       .style('stroke', '#666')
       .style('stroke-width', 0)
       .style('stroke-dasharray', '2 1')
   ;
   ```
2. PhantomJS hangs indefinitely and uses 100% of CPU. The done callback is also never called.

---

For convenience I've provided a script to test this easily:

``` js
var page = require('webpage').create();

console.log('loading the page');
page.open('http://codepen.io/chrisirhc/full/xfhbo', function() {
    console.log('never reaches here');
    phantom.exit();
});
```

Gist of all code is here: https://gist.github.com/chrisirhc/8889dd642fd8d646c5b2

P.S. This took me hours to narrow down to those four magic lines.

**Comment by zhaiyun** [comment]
we also find this problem.
