### ISSUE TITLE
Flexbox centering doesn't work

### ISSUE THREAD

**Issue by tiborsaas** [ariya/phantomjs#12367]
I've tried many approaches, none seems to work, like: display: flex, display: -webkit-flex;

Problem is that the text appears at the top of the page instead of the middle. 

Example files:
http://pastebin.com/2hx9e7yT
http://pastebin.com/H7uRKjYV

I'm using PhantomJS 1.9

**Comment by 1le** [comment]
It seems that the current version (2.1.1) still doesn't support proper flexbox porperties. I'm using a simple container with:
```
 display: flex;
 align-items: center;
```
which appear perfectly well across browsers, but will not be centered after rendering from Phantom.

**Comment by JacksonGariety** [comment]
On phantom 2.1.1 and neither syntax works at all.

**Comment by enpfeff** [comment]
on 2.1.1 linux x64 build flex-direction column isn't working as expected

**Comment by chadsaun** [comment]
Same problem here.

**Comment by tuxayo** [comment]
See  #14365

**Comment by aliatsis** [comment]
+1

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thanks!

**Comment by attiks** [comment]
Manual work-around works, download from https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.5.0-beta-linux-ubuntu-xenial-x86_64.tar.gz and extract phantomjs to node_modules/phantomjs-prebuilt/bin/phantomjs
