### ISSUE TITLE
phantomjs 1.9.7 crashes with segfault

### ISSUE THREAD

**Issue by konstantinov** [ariya/phantomjs#12372]
PhantomJS crashes on my server. It write instructions to make bugreport. May be anything else can helps?

Operating system: Linux
                  0.0.0 Linux 2.6.18.8-xenU #1 SMP Tue May 26 09:07:46 CDT 2009 i686
CPU: x86
     GenuineIntel family 6 model 58 stepping 9
     1 CPU

Crash reason:  SIGSEGV
Crash address: 0x0

Thread 0 (crashed)
 0  phantomjs + 0x1ad3203
    eip = 0x09b1b203   esp = 0xbff9ae90   ebp = 0xbff9aec8   ebx = 0x0a4f62bc
    esi = 0xbff9af40   edi = 0xbff9b080   eax = 0x00000000   ecx = 0x0a412ca0
    edx = 0x0b0d2390   efl = 0x00010246
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1ada8bf
    eip = 0x09b228c0   esp = 0xbff9aed0   ebp = 0xbff9b0d8
    Found by: previous frame's frame pointer
 2  phantomjs + 0x1341b5f
    eip = 0x09389b60   esp = 0xbff9b0e0   ebp = 0xbff9b498
    Found by: previous frame's frame pointer
 3  phantomjs + 0x1ad9bc7
    eip = 0x09b21bc8   esp = 0xbff9b4a0   ebp = 0xbff9b4e8
    Found by: previous frame's frame pointer
 4  phantomjs + 0xc863
    eip = 0x08054864   esp = 0xbff9b4f0   ebp = 0xbff9b548
    Found by: previous frame's frame pointer
 5  phantomjs + 0xcefc
    eip = 0x08054efd   esp = 0xbff9b550   ebp = 0xbff9b578
    Found by: previous frame's frame pointer
 6  phantomjs + 0xcfce
    eip = 0x08054fcf   esp = 0xbff9b580   ebp = 0xbff9b5a8
    Found by: previous frame's frame pointer
 7  phantomjs + 0x1ab7e4a
    eip = 0x09affe4b   esp = 0xbff9b5b0   ebp = 0xbff9b5c8
    Found by: previous frame's frame pointer
 8  phantomjs + 0x15f907
    eip = 0x081a7908   esp = 0xbff9b5d0   ebp = 0xbff9c028
    Found by: previous frame's frame pointer
 9  phantomjs + 0xbefcd3
    eip = 0x08c37cd4   esp = 0xbff9c030   ebp = 0xbff9c0a8
    Found by: previous frame's frame pointer
10  0xb0d9a9f3
    eip = 0xb0d9a9f4   esp = 0xbff9c0b0   ebp = 0xbff9c0f8
    Found by: previous frame's frame pointer
11  phantomjs + 0xbbb9a4
    eip = 0x08c039a5   esp = 0xbff9c100   ebp = 0xbff9c1f8
    Found by: previous frame's frame pointer
12  phantomjs + 0xc0a56b
    eip = 0x08c5256c   esp = 0xbff9c200   ebp = 0xbff9c248
    Found by: previous frame's frame pointer
13  phantomjs + 0xcbfc34
    eip = 0x08d07c35   esp = 0xbff9c250   ebp = 0xbff9c358
    Found by: previous frame's frame pointer
14  phantomjs + 0xcc021a
    eip = 0x08d0821b   esp = 0xbff9c360   ebp = 0xbff9c3b8
    Found by: previous frame's frame pointer
15  phantomjs + 0xcc1c7f
    eip = 0x08d09c80   esp = 0xbff9c3c0   ebp = 0xbff9c3d8
    Found by: previous frame's frame pointer
16  phantomjs + 0x4cb43a
    eip = 0x0851343b   esp = 0xbff9c3e0   ebp = 0xbff9c468
    Found by: previous frame's frame pointer
17  phantomjs + 0x5ada1a
    eip = 0x085f5a1b   esp = 0xbff9c470   ebp = 0xbff9c4a8
    Found by: previous frame's frame pointer
18  phantomjs + 0x5adb0e
    eip = 0x085f5b0f   esp = 0xbff9c4b0   ebp = 0xbff9c4d8
    Found by: previous frame's frame pointer
19  phantomjs + 0x722e53
    eip = 0x0876ae54   esp = 0xbff9c4e0   ebp = 0xbff9c4f8
    Found by: previous frame's frame pointer
20  phantomjs + 0x1ac395e
    eip = 0x09b0b95f   esp = 0xbff9c500   ebp = 0xbff9c608
    Found by: previous frame's frame pointer
21  phantomjs + 0x131048e
    eip = 0x0935848f   esp = 0xbff9c610   ebp = 0xbff9c628
    Found by: previous frame's frame pointer
22  phantomjs + 0x1318460
    eip = 0x09360461   esp = 0xbff9c630   ebp = 0xbff9c9e8
    Found by: previous frame's frame pointer
23  phantomjs + 0x1ab113a
    eip = 0x09af913b   esp = 0xbff9c9f0   ebp = 0xbff9ca18
    Found by: previous frame's frame pointer
24  phantomjs + 0x1add2bf
    eip = 0x09b252c0   esp = 0xbff9ca20   ebp = 0xbff9ca78
    Found by: previous frame's frame pointer
25  phantomjs + 0x1add3c8
    eip = 0x09b253c9   esp = 0xbff9ca80   ebp = 0xbff9ca88
    Found by: previous frame's frame pointer
26  phantomjs + 0x1addc7f
    eip = 0x09b25c80   esp = 0xbff9ca90   ebp = 0xbff9cac8
    Found by: previous frame's frame pointer
27  phantomjs + 0x13755f9
    eip = 0x093bd5fa   esp = 0xbff9cad0   ebp = 0xbff9cb08
    Found by: previous frame's frame pointer
28  phantomjs + 0x1aaffcc
    eip = 0x09af7fcd   esp = 0xbff9cb10   ebp = 0xbff9cb38
    Found by: previous frame's frame pointer
29  phantomjs + 0x1ab04b0
    eip = 0x09af84b1   esp = 0xbff9cb40   ebp = 0xbff9cb88
    Found by: previous frame's frame pointer
30  phantomjs + 0x1ab232c
    eip = 0x09afa32d   esp = 0xbff9cb90   ebp = 0xbff9cbc8
    Found by: previous frame's frame pointer
31  phantomjs + 0x130fda6
    eip = 0x09357da7   esp = 0xbff9cbd0   ebp = 0xbff9cbd8
    Found by: previous frame's frame pointer
32  phantomjs + 0x259b8
    eip = 0x0806d9b9   esp = 0xbff9cbe0   ebp = 0xbff9cc98
    Found by: previous frame's frame pointer
33  libc-2.9.so + 0x166a4
    eip = 0xb7c5c6a5   esp = 0xbff9cca0   ebp = 0xbff9cd08
    Found by: previous frame's frame pointer
34  phantomjs + 0x5930
    eip = 0x0804d931   esp = 0xbff9cd10   ebp = 0x00000000
    Found by: previous frame's frame pointer
35  phantomjs + 0x2577f
    eip = 0x0806d780   esp = 0xbff9cd14   ebp = 0x00000000
    Found by: stack scanning
36  phantomjs + 0x1b33b1f
    eip = 0x09b7bb20   esp = 0xbff9cd20   ebp = 0x00000000
    Found by: stack scanning
37  phantomjs + 0x1b33b0f
    eip = 0x09b7bb10   esp = 0xbff9cd24   ebp = 0x00000000
    Found by: stack scanning
38  ld-2.9.so + 0xfebf
    eip = 0xb7fa2ec0   esp = 0xbff9cd28   ebp = 0x00000000
    Found by: stack scanning

Thread 1
 0  libpthread-2.9.so + 0x9e20
    eip = 0xb7ecde20   esp = 0xb7a39320   ebp = 0xb7a393a8   ebx = 0x0a50b774
    esi = 0x00000000   edi = 0x00000007   eax = 0xfffffffc   ecx = 0x00000000
    edx = 0x00000007   efl = 0x00000206
    Found by: given as instruction pointer in context
 1  phantomjs + 0xe2960
    eip = 0x0812a961   esp = 0xb7a393b0   ebp = 0xb7a393b8
    Found by: previous frame's frame pointer
 2  libpthread-2.9.so + 0x6375
    eip = 0xb7eca376   esp = 0xb7a393c0   ebp = 0xb7a394a8
    Found by: previous frame's frame pointer
 3  libc-2.9.so + 0xe4edd
    eip = 0xb7d2aede   esp = 0xb7a394b0   ebp = 0x00000000
    Found by: previous frame's frame pointer

Thread 2
 0  libc-2.9.so + 0xdd217
    eip = 0xb7d23217   esp = 0xb71110bc   ebp = 0xb7111128   ebx = 0x00000008
    esi = 0x0a55f87c   edi = 0x00000000   eax = 0xfffffdfe   ecx = 0x0a55f454
    edx = 0x0a55f668   efl = 0x00000246
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1adbe28
    eip = 0x09b23e29   esp = 0xb7111130   ebp = 0xb7111148
    Found by: previous frame's frame pointer
 2  phantomjs + 0x1add7e6
    eip = 0x09b257e7   esp = 0xb7111150   ebp = 0xb7111258
    Found by: previous frame's frame pointer
 3  phantomjs + 0x1addc56
    eip = 0x09b25c57   esp = 0xb7111260   ebp = 0xb7111298
    Found by: previous frame's frame pointer
 4  phantomjs + 0x1aaffcc
    eip = 0x09af7fcd   esp = 0xb71112a0   ebp = 0xb71112c8
    Found by: previous frame's frame pointer
 5  phantomjs + 0x1ab04b0
    eip = 0x09af84b1   esp = 0xb71112d0   ebp = 0xb7111318
    Found by: previous frame's frame pointer
 6  phantomjs + 0x199fb69
    eip = 0x099e7b6a   esp = 0xb7111320   ebp = 0xb7111368
    Found by: previous frame's frame pointer
 7  phantomjs + 0x199fcb0
    eip = 0x099e7cb1   esp = 0xb7111370   ebp = 0xb7111378
    Found by: previous frame's frame pointer
 8  phantomjs + 0x19a2d8f
    eip = 0x099ead90   esp = 0xb7111380   ebp = 0xb71113b8
    Found by: previous frame's frame pointer
 9  libpthread-2.9.so + 0x6375
    eip = 0xb7eca376   esp = 0xb71113c0   ebp = 0xb71114a8
    Found by: previous frame's frame pointer
10  libc-2.9.so + 0xe4edd
    eip = 0xb7d2aede   esp = 0xb71114b0   ebp = 0x00000000
    Found by: previous frame's frame pointer

Thread 3
 0  libpthread-2.9.so + 0x9e20
    eip = 0xb7ecde20   esp = 0xb3838220   ebp = 0xb3838278   ebx = 0x0aa7c4c4
    esi = 0x00000000   edi = 0x00000003   eax = 0xfffffffc   ecx = 0x00000000
    edx = 0x00000003   efl = 0x00000202
    Found by: given as instruction pointer in context
 1  phantomjs + 0xeb788
    eip = 0x08133789   esp = 0xb3838280   ebp = 0xb38382b8
    Found by: previous frame's frame pointer
 2  phantomjs + 0xe37028
    eip = 0x08e7f029   esp = 0xb38382c0   ebp = 0xb38382f8
    Found by: previous frame's frame pointer
 3  phantomjs + 0xe37268
    eip = 0x08e7f269   esp = 0xb3838300   ebp = 0xb3838338
    Found by: previous frame's frame pointer
 4  phantomjs + 0xe372b0
    eip = 0x08e7f2b1   esp = 0xb3838340   ebp = 0xb3838348
    Found by: previous frame's frame pointer
 5  phantomjs + 0xb812e4
    eip = 0x08bc92e5   esp = 0xb3838350   ebp = 0xb3838368
    Found by: previous frame's frame pointer
 6  phantomjs + 0xead42
    eip = 0x08132d43   esp = 0xb3838370   ebp = 0xb3838378
    Found by: previous frame's frame pointer
 7  phantomjs + 0x19a2d8f
    eip = 0x099ead90   esp = 0xb3838380   ebp = 0xb38383b8
    Found by: previous frame's frame pointer
 8  libpthread-2.9.so + 0x6375
    eip = 0xb7eca376   esp = 0xb38383c0   ebp = 0xb38384a8
    Found by: previous frame's frame pointer
 9  libc-2.9.so + 0xe4edd
    eip = 0xb7d2aede   esp = 0xb38384b0   ebp = 0x00000000
    Found by: previous frame's frame pointer

Loaded modules:
0x08048000 - 0x0a505fff  phantomjs  ???  (main)
0xb25aa000 - 0xb2fbafff  sazanami-mincho.ttf  ???
0xb3839000 - 0xb3f8efff  sazanami-gothic.ttf  ???
0xb5813000 - 0xb5819fff  libnss_dns-2.9.so  ???
0xb581a000 - 0xb5825fff  libnss_files-2.9.so  ???
0xb5826000 - 0xb5839fff  libresolv-2.9.so  ???
0xb7a3a000 - 0xb7a7ffff  libssl.so.0.9.8  ???
0xb7a80000 - 0xb7bc8fff  libcrypto.so.0.9.8  ???
0xb7bd4000 - 0xb7bd5fff  f6b893a7224233d96cb72fd88691c0b4-x86.cache-2  ???
0xb7bd6000 - 0xb7c0cfff  LC_CTYPE  ???
0xb7c0d000 - 0xb7c0dfff  LC_NUMERIC  ???
0xb7c0e000 - 0xb7c0efff  LC_TIME  ???
0xb7c11000 - 0xb7c30fff  libexpat.so.1.5.2  ???
0xb7c31000 - 0xb7c44fff  libz.so.1.2.3  ???
0xb7c46000 - 0xb7da5fff  libc-2.9.so  ???
0xb7da9000 - 0xb7db5fff  libgcc_s.so.1  ???
0xb7db6000 - 0xb7ddbfff  libm-2.9.so  ???
0xb7ddc000 - 0xb7ebdfff  libstdc++.so.6.0.10  ???
0xb7ec4000 - 0xb7ed9fff  libpthread-2.9.so  ???
0xb7edc000 - 0xb7ee4fff  librt-2.9.so  ???
0xb7ee6000 - 0xb7ee9fff  libdl-2.9.so  ???
0xb7eea000 - 0xb7f12fff  libfontconfig.so.1.3.0  ???
0xb7f13000 - 0xb7f88fff  libfreetype.so.6.3.20  ???
0xb7f89000 - 0xb7f89fff  LC_MONETARY  ???
0xb7f8a000 - 0xb7f8afff  SYS_LC_MESSAGES  ???
0xb7f8b000 - 0xb7f8bfff  LC_PAPER  ???
0xb7f8c000 - 0xb7f8cfff  LC_NAME  ???
0xb7f8d000 - 0xb7f8dfff  LC_ADDRESS  ???
0xb7f8e000 - 0xb7f8efff  LC_TELEPHONE  ???
0xb7f8f000 - 0xb7f8ffff  LC_MEASUREMENT  ???
0xb7f90000 - 0xb7f90fff  LC_IDENTIFICATION  ???
0xb7f92000 - 0xb7f92fff  linux-gate.so  ???
0xb7f93000 - 0xb7fb2fff  ld-2.9.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
