### ISSUE TITLE
Allow crash dump path to be configured

### ISSUE THREAD

**Issue by samwgoldman** [ariya/phantomjs#12377]
If PhantomJS fails, it places a crash dump in a [hard-coded directory](https://github.com/ariya/phantomjs/blob/master/src/main.cpp#L70).

I use PhantomJS in a SaaS CI environment, where I don't have access to the /tmp directory. If PhantomJS crashes on CI, I would like to be able to retrieve the crash dump so I can see what went wrong.

Would it be possible to make the crash dump location a configuration option?

**Comment by Vitallium** [comment]
Not relevant anymore.

**Comment by timirwin** [comment]
Could you provide a link what makes this irrelevant?

**Comment by Vitallium** [comment]
@timirwin we removed Breakpad in this commit https://github.com/ariya/phantomjs/commit/7a53778b276f0e1ca3671406ed87275d4d0e1e88
That means there are no more crash dumps. They were useless. Instead of that we ask users to provide a minimal test case to reproduce their problem.
