### ISSUE TITLE
PhantomJS crash :-(

### ISSUE THREAD

**Issue by sibnerian** [ariya/phantomjs#12370]
I'm using PhantomJS in conjunction with [grunt-phantom](https://github.com/behrang/grunt-phantom). Today (after build problems led to several reinstallations of node_modules), it stopped working. 

I'm on OSX, so making a stack trace was difficult, so here is a link to the dump file: https://www.dropbox.com/s/rw0izlenc4yqw7u/275AB2BB-866E-4D5D-AA1A-2E6F47733C6F.dmp

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
