### ISSUE TITLE
Error.stack is not writable

### ISSUE THREAD

**Issue by SBoudrias** [ariya/phantomjs#12381]
`Error.stack` is writable in Chrome and most browser, but it is not inside phantomjs.

Following code return false `Object.getOwnPropertyDescriptor(err, 'stack').writable`, so it is discoverable, but that make the behavior a bit inconsistent.

**Comment by unional** [comment]
This cause `bluebird` unable to attach stack trace when an `Error` is thrown inside a promise.

As you may know, the stack trace as-is inside promise is not that helpful for debug purposes.

https://github.com/petkaantonov/bluebird/issues/942

**Comment by unional** [comment]
I found where it need to change, although I don't know how to change it. It is on the `qtwebkit`:
https://github.com/Vitallium/qtwebkit/blob/phantomjs/Source/JavaScriptCore/interpreter/Interpreter.cpp#L694
