### ISSUE TITLE
Indeterminate Crash

### ISSUE THREAD

**Issue by frankiethekneeman** [ariya/phantomjs#12380]
Our PhantomJS Server keeps crashing, and we have no idea why, to be honest. It's the standard MacOSX Binary.  I've pasted a sample crash dump, decoded, but it's frankly gibberish to me.

http://pastebin.com/A30V1Q9Y

The line from the stderr: 

phantom stderr: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/F165E994-6129-49DE-A3F6-2C746BD6B79C.dmp

We're running it from NodeJS:
    #!/usr/bin/env node

    var prerender = require('prerender');

    var server = prerender({
        workers: process.env.PHANTOM_CLUSTER_NUM_WORKERS || 4,
        iterations: process.env.PHANTOM_WORKER_ITERATIONS || 1,
        phantomBasePort: process.env.PHANTOM_CLUSTER_BASE_PORT || 12300,
        messageTimeout: process.env.PHANTOM_CLUSTER_MESSAGE_TIMEOUT || 20000,
        port: 3001,
    
        phantomArguments: [
            "--load-images=false",
            "--ignore-ssl-errors=true"
        ]
    });

    server.use({
        onPhantomPageCreate: function(page, req, res, next) {

            page.viewportSize = {
                width: 1000,
                height: 800
            };

            page.onError = function(msg, trace) {
                var msgStack = ['ERROR: ' + msg];

                if (trace && trace.length) {
                    msgStack.push('TRACE:');
                    trace.forEach(function(t) {
                        msgStack.push(' -> ' + t.file + ': ' + t.line + (t.function ? ' (in function "' + t.function +'")' : ''));
                    });
                }
                console.error(msgStack.join('\n'));
            };
            next();
        }
    });
    //server.use(prerender.removeScriptTags());
    //server.use(prerender.inMemoryHtmlCache());

    server.start();

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
