### ISSUE TITLE
Text comes as squares using version 1.9.7 on CentOS 6

### ISSUE THREAD

**Issue by petervasilev** [ariya/phantomjs#12389]
This happends on the majority of the websites I've tried. The few that work come as weird, scaled down text. Here is a screenshot:

http://imgur.com/OqIfKVy

I followed the instructions here on installing PhantomJS: http://phantomjs.org/download.html

**Comment by ariya** [comment]
Due to the lack of a concrete follow-up possibility, this issue will be closed.
