### ISSUE TITLE
Text render problem

### ISSUE THREAD

**Issue by ne0c0de** [ariya/phantomjs#12399]
Hi

I'm using PhantomJS 1.9.0 on my ubuntu server.

I just installed cyrillic fonts and trying to get a screenshot of a Russian texted tweet.

On my first execution it takes it %90 truly like this: http://ajan.im/scrup/9p/kuytecpn8cwsk.png

If i execute same command again it takes screenshot like his:

http://ajan.im/scrup/ci/fnksl2p0gkcg0.png

What is the difference between those executions? Btw i'm using  fzaninotto's service that in https://github.com/fzaninotto/screenshot-as-a-service

I already tried to configure fonts but no success.

Any help would be appreciated

Thanks..

**Comment by ryana** [comment]
@ne0c0de did you ever figure this out?
