### ISSUE TITLE
Feature: Web Page's .renderBase64 method should support PDF

### ISSUE THREAD

**Issue by erichiggins** [ariya/phantomjs#12392]
There's a minor discrepancy between the supported formats of `page.render` and `page.renderBase64`. The PDF format is missing from the latter, but it'd be a great addition.

**Comment by level420** [comment]
@Vitallium: do you think this can be implemented? From a short search in the source I think this has to be done by phantomjs, as Qt does not support printing to a buffer out of the box, or am I wrong?

Regards
Dietrich

**Comment by Vitallium** [comment]
Yeah. I already did it in one of my branches. The basic idea is to write the image to a temp file (QTempFile), then read and return it as base64.

**Comment by level420** [comment]
Thank you for your Answer Vitaly.

But I wanted somehow to avoid creating files at all! Currently I have a solution with temporary files which is working, but slows down in high load situations with a lot of rendering requests to the running phantomjs webserver.

Ideally the pdf rendering is done in memory.

Is this possible?

Regards
Dietrich

**Comment by Vitallium** [comment]
I think we could just hack Qt API :)

**Comment by level420** [comment]
To be honest, I think hacking Qt is out of my skills.

But as a first step it would be great to have your QTempFile solution in master, along with a possibility to set the temporary file directory as we then could configure phantomjs to use some memory based filesystem (tmpfs) to store the temporary files.

The biggest benefit would be to have a consistent api between all output formats.

**Comment by howardroark** [comment]
@Vitallium is there a branch with your attempt that could be built from?  Ever put any more thought into this?  :)

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://learningsolutionsaz.com/shortage.php?nf>

 

klaus@hebsgaard.dk

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://montanacash.hu/fat.php?6>

 

klaus@hebsgaard.dk

**Comment by Vitallium** [comment]
Now available since https://github.com/ariya/phantomjs/commit/7d7e5f345b646ef18d23138781ae94197335b342

**Comment by kunicmarko20** [comment]
@Vitallium .renderBase64 returns empty string for PDF

**Comment by eddydarell** [comment]
@Vitallium like @kunicmarko20 said: renderBase64 returns an empty string for PDF. How exactly is one supposed to use the fix you mentionned [here](https://github.com/ariya/phantomjs/commit/7d7e5f345b646ef18d23138781ae94197335b342)
