### ISSUE TITLE
font-size, vw units ignored

### ISSUE THREAD

**Issue by tiborsaas** [ariya/phantomjs#12398]
If you set the font-size in your document in vw units, then phantomJS ignores them. 

Viewport is set to { width: 1280, height: 720 };

I've tried this on win7 and linux, using 1.9.7

I tried to add  <meta name="viewport" content="width=device-width, initial-scale=1"> to the HTML file, but no luck.

**Comment by davclark** [comment]
I'm trying to render pages to PDF with PhantomJS 2.0, and font-size appears to be ignored also, even when specified in `pt`s. Does any font-size specification work?
