### ISSUE TITLE
Add Proxy Exceptions to Phantom

### ISSUE THREAD

**Issue by h4wlt** [ariya/phantomjs#12407]
Hi, 

I have set a system proxy on my machine and when running my tests (in Protractor) all of the requests go via the proxy.  This is good, however I want to add some proxy exceptions to allow me to navigate to our qa environment but still be able to download the external analytics objects etc.

Is there a way to issue proxy exceptions to Phantom?

Thanks,
Craig.

**Comment by abnun** [comment]
We would also need this feature ... is there any timeline when it will be available
