### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by madhatter42** [ariya/phantomjs#12406]
Hi - my PhantomJS instance crashed with this crash report (please rename extension to .dmp). Can you please help?

![330ce884-72b1-d7d7-158cd2b5-47932243](https://cloud.githubusercontent.com/assets/979862/3737266/544a72ee-1735-11e4-83b1-9e19276f2666.jpg)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
