### ISSUE TITLE
PhantomJS webserver request.url utf-8 encoding problem

### ISSUE THREAD

**Issue by salisa** [ariya/phantomjs#12402]
There is an strange utf-8 issue about request.url in built-in PhantomJS webserver:

``` javascript
/*
 * requested url: http://localhost:9000/page/سلام
 * console request.url: /page/%C3%98%C2%B3%C3%99%C2%84%C3%98%C2%A7%C3%99%C2%85
 */
server = require('webserver').create();
service = server.listen(port, function (request, response) {
    console.log(request.url);
});
```

It seems the provided querystring converted & encoded to utf-8 HEX and mapped to request attributes.

p.s.
سلام - spelled salam, is a Persian/Arabic word mean Hello.
[UTF-8 encoding table and Unicode characters](http://www.utf8-chartable.de/unicode-utf8-table.pl)

**Comment by silkentrance** [comment]
@salisa it is correct that the url path is encoded using the standard url encoding scheme.

It is the responsibility of your request handler to decode the url.

Also, I do not see a querystring (?foo=bar...) in your provided URL.
