### ISSUE TITLE
Force max height

### ISSUE THREAD

**Issue by FrancoisPerez** [ariya/phantomjs#12419]
Hi,

I created a script to render a list of URLs on three types of devices (a smartphone, a tablet and a dektop browser).

As recommended I used the clipRect method to only have the equivalent of my viewport.
I often have an output that doesn't match what I should see on an actual device.

On an iPhone for example, I won't get the exact same render if a website has a 'sticky footer'. PhantomJS renders the whole page (with the footer at the very end of the page) but that is something I can't see using clipRect.

I there any "universal way" (regardless the website I render), to have a sticky footer rendered in the viewport of my device using PhantomJS ?

Thanks

**Comment by dhwaneetbhatt** [comment]
@FrancoisPerez As per my knowledge, sticky footer responds to the scrolling of a webpage. You can use scrollposition to position yourself and make sticky footer appear there and then use clipRect to take a screenshot.

More on scrollPosition here: http://phantomjs.org/api/webpage/property/scroll-position.html
