### ISSUE TITLE
Phantom is crashing

### ISSUE THREAD

**Issue by gitjeff05** [ariya/phantomjs#12412]
Using phantom to run jasmine specs. After tests finish I get this output:

phnatomjs stderr> phantomjs(97143,0xa13551a8) malloc: * mach_vm_map(size=16777216) failed (error code=3)
* error: can't allocate region
* set a breakpoint in malloc_error_break to debug
phnatomjs stderr> PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/D3EFCF25-8401-44C2-BCAA-41507F8449D2.dmp

File is too large to attach.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
