### ISSUE TITLE
XMLHttpRequest fails with a "Origin file:// is not allowed by Access-Control-Allow-Origin" error

### ISSUE THREAD

**Issue by lucachiarabini** [ariya/phantomjs#12411]
Any XMLHttpRequest calls always fail with the error "Origin file:// is not allowed by Access-Control-Allow-Origin.". 

*Using the command line parameters --local-to-remote-url-access=true and  --web-security=false does NOT solve the issue

*Setting the values webSecutiry & localToRemoteUrlAccessEnabled in the xhr object does not solve the issue either.

To reproduce the problem run the code below, which tries to download an external image file hosted on a website.

```
        var xhr = new XMLHttpRequest();
        xhr.webSecutiry =false;
        xhr.localToRemoteUrlAccessEnabled =true;
        xhr.open("GET", 'https://sites.google.com/site/rwicons/sg5_100.png', true);
        xhr.onreadystatechange = function () {
                            if (xhr.readyState == 4) {
                                if (xhr.status != 400) {
                                     console.log('OK status: ' + xhr.status + ' (' + xhr.statusText + ')');
                                     console.log('bodysize:' + xhr.responseText.length + '\n');
                                } else {
                                    console.log('ERROR status: ' + xhr.status + ' (' + xhr.statusText + ')');
                                    console.log('bodysize:' + xhr.responseText.length + '\n');
                                }
                            }                                
                        };

       xhr.send(null);
```

**Comment by Samba-Konduri** [comment]
I'm seeing the exact same issue, I'm running with the following params  summary: true,
                    '--web-security': 'on',
                    '--local-to-remote-url-access': 'yes',
                    '--ignore-ssl-errors': 'true',
                    '--output-encoding':'utf8'
after running the specs im getting bellow error 
"NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:5080/master-data/customers/!@#$%^&*()_+/entities'.
