### ISSUE TITLE
Cannot set webStorageEnabled in capabilities?

### ISSUE THREAD

**Issue by boogheta** [ariya/phantomjs#12421]
(phantom 1.9.7 on ubuntu 14.04)
I am trying to use the localStorage and read in the actual sqlite3 files afterwards, so I added to my phantom command-line the option `"--local-storage-path=MYDIR"` but could not find the resulting file even after actually using the localStorage in my JS ran on the webpage.

So investigating a bit, I realised my session capabilities were saying `"databaseEnabled":false` and `"webStorageEnabled":false`, so I then added to my desiredCapabilities the opposites, although when the session starts, the resulting negotiated capabilities are still saying false, so I assume they are not being taken into account.

Any idea why? Is there a way to do that?

**Comment by reod** [comment]
Same here.

**Comment by peshkov3** [comment]
+1

**Comment by TheMetalCode** [comment]
+1. This appears to be true in 2.1.1 as well.
