### ISSUE TITLE
PDF problems in 2.0

### ISSUE THREAD

**Issue by chripede** [ariya/phantomjs#12422]
This might be a bit early to leave bug reports for the 2.0 branch, but here goes:
- If the webpage being saved as PDF contains any web fonts (for example from Google Fonts) the output is saved as images and text is not selectable. This works in 1.9
- Column titles in thead are no longer printed on top of every page if a table spans several pages. This might be intentional since this has some problems in 1.9

**Comment by thomasbachem** [comment]
Your first point may be addressed in #13008.

**Comment by Kuurde** [comment]
Any update on the 2nd point? I'm having this issue in version "2.0.1-development"
