### ISSUE TITLE
page.open() doesn't work with certain CSS resources

### ISSUE THREAD

**Issue by ravinet** [ariya/phantomjs#12441]
Here's a simplified test case:

I created a simple .css file (test.css) with a single character, "/" .  I stored this file in /var/www on my desktop running Ubuntu 13.10. I have an Apache web server running on this desktop.

I have attached an image of the script (test.js) I am using with phantomjs (version 1.9.0). 
![phantomjs_script](https://cloud.githubusercontent.com/assets/2761909/3876295/e5ce9f68-215a-11e4-9d8c-fe660545eb31.png)

The script loads the .css file stored in /var/www by requesting
the url "http://localhost/test.css". The script uses page.load()
to load the url and exits based on the status returned from the page load.

The script also uses custom headers to ensure that the request made by phantomjs
is the same as the request made by a Google Chrome browser (version 31.0.1650.63) while loading the same css file.

I loaded "http://localhost/test.css" once with Google Chrome and once with
phantomjs and have included four images summarizing the HTTP data transfers,
captured with tcpdump/wireshark.

This image shows the HTTP request sent by phantomjs to the Web server for "http://localhost/test.css":

![phantomjs_request](https://cloud.githubusercontent.com/assets/2761909/3876304/01c6fc06-215b-11e4-8893-62dfd3031032.png)

This image shows the HTTP request sent by Google Chrome to the Web server for "http://localhost/test.css":

![chrome_request](https://cloud.githubusercontent.com/assets/2761909/3876319/1f708c40-215b-11e4-8645-f8011a8141f6.png)

Similarly, this image shows the HTTP response sent by the Web server to phantomjs for "http://localhost/test.css":
![phantom_response](https://cloud.githubusercontent.com/assets/2761909/3876467/4d4291a8-215c-11e4-90d1-b61d02b92190.png)

This image shows the HTTP response sent by the Web server to Chrome for "http://localhost/test.css":
![chrome_response](https://cloud.githubusercontent.com/assets/2761909/3876473/51618154-215c-11e4-855d-3e14a765d0dd.png)

As shown in the four images, phantomjs makes the exact same GET request as Google Chrome.  Both browsers also receive exactly the same compressed, unencrypted response (since we are not using  HTTPS).

Even though phantomjs requests and receives test.css in the same way as Chrome,  phantomjs
page.load() returns a status of 'Fail' and prints 'Unable to load address'.

**Comment by trittberg** [comment]
"What value this would provide..."   I don't understand why this question was asked? 

The obvious answer (to me anyway) is: importing CSS files would allow rendering to show proper styling and  importing JS files would allow page content to be modified before render.

For instance, I might have a simple external JS file (on my file system, not an HTTP server) that changes the title of my page to some corporate standard. (This is just an example, not a real world requirement). How would I get that new title into the image that is generated with the page.render function.

How else could we get those results? Is there already a way of doing this but just not clearly documented?
