### ISSUE TITLE
PhantomJS crashes on rendering a heavy-loaded form w/ file-upload

### ISSUE THREAD

**Issue by railsc0d0r** [ariya/phantomjs#12456]
As test-setup we use cucumber, capybara w/ poltergeist for phantomjs.

We have a form with a file-upload. This is rendered in a layout heavy loaded with javascripts and bootstrap-assets. 

When i fillin the form and attach a zip size ca. 30mb and try to press the submit-button, phantomjs crashes with a dump like the one attached. The crash is reproduceable, but doesn't occur always. When i run the same feature continously, phantomjs crashes between 30% and 60% of the time.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
