### ISSUE TITLE
Problem with floats and RTL

### ISSUE THREAD

**Issue by akg3** [ariya/phantomjs#12451]
Having an issue with how some RTL content is being rendered when in a floating DIV (content outside floating DIVs seems mostly fine).  I have attached 2 images, one how the RTL Arabic content is being rendered in browsers (in this case Chrome, but works fine in Firefox/IE too), and how phantomJS is rendering it (both in PNG and PDF).  This same HTML/CSS renders fine in PhantomJS when using a LTR language.

Any suggestions?

![chrome-rtl-pdf-render](https://cloud.githubusercontent.com/assets/8422503/3895650/d7bcb91e-224f-11e4-96d3-ff2b19d23529.jpg)
![phantomjs-rtl-pdf-render](https://cloud.githubusercontent.com/assets/8422503/3895657/f1dd91d8-224f-11e4-843d-e57da69a39c5.jpg)

**Comment by israelidanny** [comment]
I'm experiencing the same issue with Hebrew RTL. Has anyone found any solution for this?

**Comment by wombat86** [comment]
+
