### ISSUE TITLE
getEventListeners

### ISSUE THREAD

**Issue by heiskr** [ariya/phantomjs#12458]
I use PhantomJS for testing, and for one project we are testing bindings on native DOM objects.

Some of the developer tools include a way to get the event listeners:

https://developer.chrome.com/devtools/docs/commandline-api#geteventlistenersobject
https://getfirebug.com/wiki/index.php/GetEventListeners

It would be neat to have this available in PhantomJS for testing as well.

Love yall!

**Comment by redaxmedia** [comment]
+1

**Comment by mfairchild365** [comment]
+1

**Comment by jongund** [comment]
+1

We really need this feature to evaluating web pages for accessibility features

**Comment by jongund** [comment]
What we really want to test for accessibility is the presence or absence of particular event handlers.  For example if their are mouse event handlers on a DOM node or one of its ancestors are their corresponding keyboard event handlers on the DOM node or one of its ancestors.

So initially we would just need a Boolean test to identify any event handlers of a specific type (e.g. mousedown, keypress) on an DOM node.

**Comment by Ryladog** [comment]
+1 as this is also related to an IndieUI feature that could/would/will be relevant to other web technologies as well!!

**Comment by ronra** [comment]
+1

**Comment by mdy77** [comment]
+1

**Comment by nhoyt** [comment]
+1

**Comment by calnelson1** [comment]
+1

**Comment by coreyflynn** [comment]
+1

**Comment by jongund** [comment]
Any progress on adding this feature?

**Comment by adrienbrunet** [comment]
+1

**Comment by avietrov** [comment]
+1

**Comment by mato75** [comment]
+1

**Comment by zjy01** [comment]
I am finding this, can it work now?
