### ISSUE TITLE
"Content-Length" can't get if the response is gziped 

### ISSUE THREAD

**Issue by Jacky-fe** [ariya/phantomjs#12475]
i can get the file original size by the "bodySize" of response

but if the file is gziped, i can't get the gziped-size by "Content-Length" of "headers" of response

so i can't get the actually size of the net transmission

**Comment by fancyoung** [comment]
U can disable gzip in 2.0.
```
page.customHeaders = {
    'Accept-Encoding': 'gzip;q=0'
};
```
Here is my full solution: http://stackoverflow.com/a/28318252/1144742

PS: `bodySize` never right for me, the value is not gziped-size, and it always changes. 
So I get all size by `Content-Length`
