### ISSUE TITLE
renderBase64 does not take a 'quality' parameter

### ISSUE THREAD

**Issue by peller** [ariya/phantomjs#12474]
I'd like to be able to generate smaller payloads for my JPEGs by using quality ~50.  renderBase64() does not accept a quality parameter like render() does.  This is critical for network performance.

**Comment by daraosn** [comment]
+1

**Comment by grippy** [comment]
+1

**Comment by henn1nk** [comment]
+1

**Comment by dhendo** [comment]
@henn1nk Hopefully the PR for this and the related one to add rendering to a Buffer (https://github.com/ariya/phantomjs/pull/13345) will be merged soon.

**Comment by mcgoooo** [comment]
@ariya i see there is a pull in for this, any chance of movement on this?

**Comment by zackify** [comment]
Really would like to see this

**Comment by alekbarszczewski** [comment]
:+1:

**Comment by flesler** [comment]
:+1:

**Comment by alecoronel** [comment]
Any news on this on this? :-)

**Comment by zackify** [comment]
I realized the quality is fine. If your image seems pixelated, bump up the
width and height of the browser. That helped me.

**Comment by paulborza** [comment]
+1

**Comment by ghisguth** [comment]
+1

**Comment by marcdibold** [comment]
+1
