### ISSUE TITLE
Phantom Crash

### ISSUE THREAD

**Issue by nanosekund** [ariya/phantomjs#12488]
Operating system: Linux
                  0.0.0 Linux 2.6.26-2-amd64 #1 SMP Tue Jan 25 05:59:43 UTC 2011 x86_64
CPU: amd64
     family 6 model 26 stepping 5
     4 CPUs

Crash reason:  SIGSEGV
Crash address: 0x110

Thread 0 (crashed)
 0  phantomjs + 0x696aba
    rbx = 0x0000000000000000   r12 = 0x0000000000000100
    r13 = 0x00007f623fd78718   r14 = 0x0000000000000001
    r15 = 0x0000000000000000   rip = 0x0000000000a96aba
    rsp = 0x00007fffe618dee0   rbp = 0x00007fffe618df10
    Found by: given as instruction pointer in context
 1  phantomjs + 0x69ab3c
    rip = 0x0000000000a9ab3d   rsp = 0x00007fffe618df10
    rbp = 0x00007fffe618df10
    Found by: stack scanning
 2  phantomjs + 0x4edb74
    rip = 0x00000000008edb75   rsp = 0x00007fffe618df50
    Found by: stack scanning
 3  phantomjs + 0x4f36b2
    rip = 0x00000000008f36b3   rsp = 0x00007fffe618dfb0
    Found by: stack scanning
 4  phantomjs + 0xd6e8d3
    rip = 0x000000000116e8d4   rsp = 0x00007fffe618e0a0
    Found by: stack scanning
 5  phantomjs + 0x61cbd9
    rip = 0x0000000000a1cbda   rsp = 0x00007fffe618e110
    Found by: stack scanning
 6  phantomjs + 0x61ea69
    rip = 0x0000000000a1ea6a   rsp = 0x00007fffe618e1d0
    Found by: stack scanning
 7  phantomjs + 0x5efe2b
    rip = 0x00000000009efe2c   rsp = 0x00007fffe618e1f0
    Found by: stack scanning
 8  phantomjs + 0x5d303f
    rip = 0x00000000009d3040   rsp = 0x00007fffe618e270
    Found by: stack scanning
 9  phantomjs + 0x5d90a0
    rip = 0x00000000009d90a1   rsp = 0x00007fffe618e340
    Found by: stack scanning
10  phantomjs + 0x5d536e
    rip = 0x00000000009d536f   rsp = 0x00007fffe618e350
    Found by: stack scanning
11  phantomjs + 0x5db151
    rip = 0x00000000009db152   rsp = 0x00007fffe618e3a0
    Found by: stack scanning

Thread 1
 0  libc-2.11.3.so + 0xa0c5d
    rbx = 0x00007f6287fccd80   r12 = 0x00000000ffffffff
    r13 = 0x00007f6239c101a0   r14 = 0x0000000002a7e740
    r15 = 0x0000000002a7e710   rip = 0x00007f6288e95c5d
    rsp = 0x00007f6287fccc50   rbp = 0x00007f6287fccd00
    Found by: given as instruction pointer in context
 1  libc-2.11.3.so + 0xa0acf
    rip = 0x00007f6288e95ad0   rsp = 0x00007f6287fccc60
    rbp = 0x00007f6287fccd00
    Found by: stack scanning
 2  phantomjs + 0x18b5c6f
    rip = 0x0000000001cb5c70   rsp = 0x00007f6287fccc68
    rbp = 0x00007f6287fccd00
    Found by: stack scanning
 3  ld-2.11.3.so + 0x9009
    rip = 0x00007f628a3f100a   rsp = 0x00007f6287fccca0
    rbp = 0x00007f6287fccd00
    Found by: stack scanning
 4  ld-2.11.3.so + 0x982b
    rip = 0x00007f628a3f182c   rsp = 0x00007f6287fccce0
    rbp = 0x00007f6287fccd00
    Found by: stack scanning
 5  libpthread-2.11.3.so + 0xefef
    rip = 0x00007f6289911ff0   rsp = 0x00007f6287fcccf8
    rbp = 0x00007f6287fccd00
    Found by: stack scanning
 6  ld-2.11.3.so + 0x9af1
    rip = 0x00007f628a3f1af2   rsp = 0x00007f6287fccd00
    rbp = 0x00007f6287fccd00
    Found by: stack scanning
 7  libc-2.11.3.so + 0xe217
    rip = 0x00007f6288e03218   rsp = 0x00007f6287fccd48
    Found by: stack scanning
 8  libpthread-2.11.3.so + 0xb295
    rip = 0x00007f628990e296   rsp = 0x00007f6287fcce18
    Found by: stack scanning
 9  phantomjs + 0xdda2d
    rip = 0x00000000004dda2e   rsp = 0x00007f6287fcce40
    Found by: stack scanning
10  libpthread-2.11.3.so + 0x10fbf
    rip = 0x00007f6289913fc0   rsp = 0x00007f6287fcce70
    Found by: stack scanning
11  libpthread-2.11.3.so + 0x10fbf
    rip = 0x00007f6289913fc0   rsp = 0x00007f6287fccea0
    Found by: stack scanning
12  phantomjs + 0xddc98
    rip = 0x00000000004ddc99   rsp = 0x00007f6287fccec0
    Found by: stack scanning
13  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f62899098ca   rsp = 0x00007f6287fcced0
    Found by: stack scanning
14  libpthread-2.11.3.so + 0x10fbf
    rip = 0x00007f6289913fc0   rsp = 0x00007f6287fccf78
    Found by: stack scanning
15  libc-2.11.3.so + 0xcfb6c
    rip = 0x00007f6288ec4b6d   rsp = 0x00007f6287fccfe0
    Found by: stack scanning

Thread 2
 0  libc-2.11.3.so + 0xc93e3
    rbx = 0x0000000000000000   r12 = 0x00007f62877cbda0
    r13 = 0x0000000000000008   r14 = 0x0000000003d80e28
    r15 = 0x0000000003d810c0   rip = 0x00007f6288ebe3e3
    rsp = 0x00007f62877cbb70   rbp = 0x0000000003d80c70
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906326
    rip = 0x0000000001d06327   rsp = 0x00007f62877cbb80
    Found by: stack scanning
 2  ld-2.11.3.so + 0x9009
    rip = 0x00007f628a3f100a   rsp = 0x00007f62877cbba0
    Found by: stack scanning
 3  libpthread-2.11.3.so + 0xe158
    rip = 0x00007f6289911159   rsp = 0x00007f62877cbbd0
    Found by: stack scanning
 4  phantomjs + 0x19075e6
    rip = 0x0000000001d075e7   rsp = 0x00007f62877cbc10
    Found by: stack scanning
 5  phantomjs + 0x18f6ab6
    rip = 0x0000000001cf6ab7   rsp = 0x00007f62877cbc30
    Found by: stack scanning
 6  linux-gate.so + 0x531
    rip = 0x00007fffe61ff532   rsp = 0x00007f62877cbc40
    Found by: stack scanning
 7  librt-2.11.3.so + 0x3e7e
    rip = 0x00007f6289b22e7f   rsp = 0x00007f62877cbc70
    Found by: stack scanning
 8  phantomjs + 0x1840b73
    rip = 0x0000000001c40b74   rsp = 0x00007f62877cbc90
    Found by: stack scanning
 9  phantomjs + 0x1840a78
    rip = 0x0000000001c40a79   rsp = 0x00007f62877cbcd0
    Found by: stack scanning
10  phantomjs + 0x1906fa5
    rip = 0x0000000001d06fa6   rsp = 0x00007f62877cbce0
    Found by: stack scanning
11  phantomjs + 0x1908091
    rip = 0x0000000001d08092   rsp = 0x00007f62877cbd50
    Found by: stack scanning
12  phantomjs + 0x18dd4b4
    rip = 0x0000000001cdd4b5   rsp = 0x00007f62877cbda0
    Found by: stack scanning
13  phantomjs + 0x18ddca8
    rip = 0x0000000001cddca9   rsp = 0x00007f62877cbdb0
    Found by: stack scanning
14  phantomjs + 0x18dd917
    rip = 0x0000000001cdd918   rsp = 0x00007f62877cbdd0
    Found by: stack scanning
15  phantomjs + 0x17dfdf5
    rip = 0x0000000001bdfdf6   rsp = 0x00007f62877cbe30
    Found by: stack scanning
16  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f62877cbe80
    Found by: stack scanning
17  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f62899098ca   rsp = 0x00007f62877cbed0
    Found by: stack scanning

Thread 3
 0  libc-2.11.3.so + 0xc93e3
    rbx = 0x0000000000000005   r12 = 0x00007f62306c2dc0
    r13 = 0x0000000002aa3080   r14 = 0x00007f628a606040
    r15 = 0x0000000000000003   rip = 0x00007f6288ebe3e3
    rsp = 0x00007f62306c2db0   rbp = 0x00007f62306c2e4f
    Found by: given as instruction pointer in context
 1  phantomjs + 0x18b7133
    rip = 0x0000000001cb7134   rsp = 0x00007f62306c2dc0
    rbp = 0x00007f62306c2e4f
    Found by: stack scanning
 2  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f62306c2e80
    Found by: stack scanning
 3  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f62899098ca   rsp = 0x00007f62306c2ed0
    Found by: stack scanning

Thread 4
 0  libpthread-2.11.3.so + 0xb1fc
    rbx = 0x0000000007a32e40   r12 = 0x004189374bc6a7ef
    r13 = 0xffffffffffffffff   r14 = 0x0000000007a32e68
    r15 = 0x0000000007a32e00   rip = 0x00007f628990e1fc
    rsp = 0x00007f6232890d38   rbp = 0x00007f623e3ffc50
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39f4
    rip = 0x0000000001be39f5   rsp = 0x00007f6232890d60
    rbp = 0x00007f623e3ffc50
    Found by: stack scanning
 2  linux-gate.so + 0x6a4
    rip = 0x00007fffe61ff6a5   rsp = 0x00007f6232890d90
    rbp = 0x00007f623e3ffc50
    Found by: stack scanning
 3  phantomjs + 0xe70e9
    rip = 0x00000000004e70ea   rsp = 0x00007f6232890de0
    rbp = 0x00007f623e3ffc50
    Found by: stack scanning
 4  phantomjs + 0xd85268
    rip = 0x0000000001185269   rsp = 0x00007f6232890e00
    rbp = 0x00007f623e3ffc50
    Found by: stack scanning
 5  phantomjs + 0xd85492
    rip = 0x0000000001185493   rsp = 0x00007f6232890e40
    rbp = 0x00007f623e3ffc50
    Found by: stack scanning
 6  phantomjs + 0xe68fa
    rip = 0x00000000004e68fb   rsp = 0x00007f6232890e70
    rbp = 0x00007f623e3ffc50
    Found by: stack scanning
 7  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f6232890e80
    rbp = 0x00007f623e3ffc50
    Found by: stack scanning
 8  phantomjs + 0x3fafff
    rip = 0x00000000007fb000   rsp = 0x00007f6232890ea0
    rbp = 0x00007f623e3ffc50
    Found by: stack scanning
 9  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f62899098ca   rsp = 0x00007f6232890ed0
    rbp = 0x00007f623e3ffc50
    Found by: stack scanning

Thread 5
 0  libpthread-2.11.3.so + 0xb7d2
    rbx = 0x0000000007c751b0   r12 = 0x00000000000010b2
    r13 = 0x00007f6225f69de0   r14 = 0xffffffffffffff92
    r15 = 0x0000000000000000   rip = 0x00007f628990e7d2
    rsp = 0x00007f6225f69d68   rbp = 0x00000000078e67a0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39d6
    rip = 0x0000000001be39d7   rsp = 0x00007f6225f69dc0
    Found by: stack scanning
 2  phantomjs + 0x17d783c
    rip = 0x0000000001bd783d   rsp = 0x00007f6225f69e40
    Found by: stack scanning
 3  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f6225f69e80
    Found by: stack scanning
 4  libc-2.11.3.so + 0x35885f
    rip = 0x00007f628914d860   rsp = 0x00007f6225f69ea0
    Found by: stack scanning
 5  libc-2.11.3.so + 0x358867
    rip = 0x00007f628914d868   rsp = 0x00007f6225f69ea8
    Found by: stack scanning
 6  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f62899098ca   rsp = 0x00007f6225f69ed0
    Found by: stack scanning

Thread 6
 0  libc-2.11.3.so + 0xc4c13
    rbx = 0x0000000029bf2a10   r12 = 0x0000000000000002
    r13 = 0x0000000000000000   r14 = 0x00007f623102caa8
    r15 = 0x0000000000000005   rip = 0x00007f6288eb9c13
    rsp = 0x00007f623102c850   rbp = 0x00007f623102fdb8
    Found by: given as instruction pointer in context
 1  libresolv-2.11.3.so + 0x98dd
    rip = 0x00007f62316718de   rsp = 0x00007f623102c880
    rbp = 0x00007f623102fdb8
    Found by: stack scanning

Thread 7
 0  libpthread-2.11.3.so + 0xb7d2
    rbx = 0x0000000007c751b0   r12 = 0x00000000000010b4
    r13 = 0x00007f622e1fcde0   r14 = 0xffffffffffffff92
    r15 = 0x0000000000000000   rip = 0x00007f628990e7d2
    rsp = 0x00007f622e1fcd68   rbp = 0x0000000007c75450
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39d6
    rip = 0x0000000001be39d7   rsp = 0x00007f622e1fcdc0
    Found by: stack scanning
 2  phantomjs + 0x17d783c
    rip = 0x0000000001bd783d   rsp = 0x00007f622e1fce40
    Found by: stack scanning
 3  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f622e1fce80
    Found by: stack scanning
 4  libc-2.11.3.so + 0x35885f
    rip = 0x00007f628914d860   rsp = 0x00007f622e1fcea0
    Found by: stack scanning
 5  libc-2.11.3.so + 0x358867
    rip = 0x00007f628914d868   rsp = 0x00007f622e1fcea8
    Found by: stack scanning
 6  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f62899098ca   rsp = 0x00007f622e1fced0
    Found by: stack scanning

Thread 8
 0  libpthread-2.11.3.so + 0xb7d2
    rbx = 0x0000000007c751b0   r12 = 0x00000000000010b0
    r13 = 0x00007f622ebafde0   r14 = 0xffffffffffffff92
    r15 = 0x0000000000000000   rip = 0x00007f628990e7d2
    rsp = 0x00007f622ebafd68   rbp = 0x00007f628000aac0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39d6
    rip = 0x0000000001be39d7   rsp = 0x00007f622ebafdc0
    rbp = 0x00007f628000aac0
    Found by: stack scanning
 2  phantomjs + 0x17d783c
    rip = 0x0000000001bd783d   rsp = 0x00007f622ebafe40
    rbp = 0x00007f628000aac0
    Found by: stack scanning
 3  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f622ebafe80
    rbp = 0x00007f628000aac0
    Found by: stack scanning
 4  libc-2.11.3.so + 0x35885f
    rip = 0x00007f628914d860   rsp = 0x00007f622ebafea0
    rbp = 0x00007f628000aac0
    Found by: stack scanning
 5  libc-2.11.3.so + 0x358867
    rip = 0x00007f628914d868   rsp = 0x00007f622ebafea8
    rbp = 0x00007f628000aac0
    Found by: stack scanning
 6  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f62899098ca   rsp = 0x00007f622ebafed0
    rbp = 0x00007f628000aac0
    Found by: stack scanning

Thread 9
 0  libc-2.11.3.so + 0xc93e3
    rbx = 0x00007f6225768d50   r12 = 0x0000000000196560
    r13 = 0x000000000000005f   r14 = 0x000000000fcf8b28
    r15 = 0x000000000fcf8dc0   rip = 0x00007f6288ebe3e3
    rsp = 0x00007f6225768b70   rbp = 0x00000000000eae77
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906227
    rip = 0x0000000001d06228   rsp = 0x00007f6225768b80
    Found by: stack scanning
 2  phantomjs + 0x19075e6
    rip = 0x0000000001d075e7   rsp = 0x00007f6225768c10
    Found by: stack scanning
 3  phantomjs + 0x18f6ab6
    rip = 0x0000000001cf6ab7   rsp = 0x00007f6225768c30
    Found by: stack scanning
 4  linux-gate.so + 0x531
    rip = 0x00007fffe61ff532   rsp = 0x00007f6225768c40
    Found by: stack scanning
 5  librt-2.11.3.so + 0x3e7e
    rip = 0x00007f6289b22e7f   rsp = 0x00007f6225768c70
    Found by: stack scanning
 6  phantomjs + 0x1840b73
    rip = 0x0000000001c40b74   rsp = 0x00007f6225768c90
    Found by: stack scanning
 7  phantomjs + 0x1907ced
    rip = 0x0000000001d07cee   rsp = 0x00007f6225768cc0
    Found by: stack scanning
 8  phantomjs + 0x1840a78
    rip = 0x0000000001c40a79   rsp = 0x00007f6225768cd0
    Found by: stack scanning
 9  phantomjs + 0x1906fa5
    rip = 0x0000000001d06fa6   rsp = 0x00007f6225768ce0
    Found by: stack scanning
10  phantomjs + 0x1908091
    rip = 0x0000000001d08092   rsp = 0x00007f6225768d50
    Found by: stack scanning
11  phantomjs + 0x18dd4b4
    rip = 0x0000000001cdd4b5   rsp = 0x00007f6225768da0
    Found by: stack scanning
12  phantomjs + 0x18ddca8
    rip = 0x0000000001cddca9   rsp = 0x00007f6225768db0
    Found by: stack scanning
13  phantomjs + 0x18dd917
    rip = 0x0000000001cdd918   rsp = 0x00007f6225768dd0
    Found by: stack scanning
14  phantomjs + 0x17dfdf5
    rip = 0x0000000001bdfdf6   rsp = 0x00007f6225768e30
    Found by: stack scanning
15  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f6225768e80
    Found by: stack scanning
16  libpthread-2.11.3.so + 0x5ee8
    rip = 0x00007f6289908ee9   rsp = 0x00007f6225768e90
    Found by: stack scanning
17  libc-2.11.3.so + 0x35884f
    rip = 0x00007f628914d850   rsp = 0x00007f6225768e98
    Found by: stack scanning
18  libc-2.11.3.so + 0x35885f
    rip = 0x00007f628914d860   rsp = 0x00007f6225768ea0
    Found by: stack scanning
19  libc-2.11.3.so + 0x358867
    rip = 0x00007f628914d868   rsp = 0x00007f6225768ea8
    Found by: stack scanning
20  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f62899098ca   rsp = 0x00007f6225768ed0
    Found by: stack scanning

Thread 10
 0  libc-2.11.3.so + 0xc93e3
    rbx = 0x0000000000000000   r12 = 0x00007f6224f67da0
    r13 = 0x000000000000004b   r14 = 0x000000000f7a68b8
    r15 = 0x000000000f7a6b50   rip = 0x00007f6288ebe3e3
    rsp = 0x00007f6224f67b70   rbp = 0x000000000f7a6700
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906326
    rip = 0x0000000001d06327   rsp = 0x00007f6224f67b80
    Found by: stack scanning
 2  libpthread-2.11.3.so + 0xe158
    rip = 0x00007f6289911159   rsp = 0x00007f6224f67bd0
    Found by: stack scanning
 3  phantomjs + 0x19075e6
    rip = 0x0000000001d075e7   rsp = 0x00007f6224f67c10
    Found by: stack scanning
 4  phantomjs + 0x18f6ab6
    rip = 0x0000000001cf6ab7   rsp = 0x00007f6224f67c30
    Found by: stack scanning
 5  linux-gate.so + 0x531
    rip = 0x00007fffe61ff532   rsp = 0x00007f6224f67c40
    Found by: stack scanning
 6  librt-2.11.3.so + 0x3e7e
    rip = 0x00007f6289b22e7f   rsp = 0x00007f6224f67c70
    Found by: stack scanning
 7  phantomjs + 0x1840b73
    rip = 0x0000000001c40b74   rsp = 0x00007f6224f67c90
    Found by: stack scanning
 8  phantomjs + 0x1840a78
    rip = 0x0000000001c40a79   rsp = 0x00007f6224f67cd0
    Found by: stack scanning
 9  phantomjs + 0x1906fa5
    rip = 0x0000000001d06fa6   rsp = 0x00007f6224f67ce0
    Found by: stack scanning
10  phantomjs + 0x1908091
    rip = 0x0000000001d08092   rsp = 0x00007f6224f67d50
    Found by: stack scanning
11  phantomjs + 0x18dd4b4
    rip = 0x0000000001cdd4b5   rsp = 0x00007f6224f67da0
    Found by: stack scanning
12  phantomjs + 0x18ddca8
    rip = 0x0000000001cddca9   rsp = 0x00007f6224f67db0
    Found by: stack scanning
13  phantomjs + 0x18dd917
    rip = 0x0000000001cdd918   rsp = 0x00007f6224f67dd0
    Found by: stack scanning
14  phantomjs + 0x17dfdf5
    rip = 0x0000000001bdfdf6   rsp = 0x00007f6224f67e30
    Found by: stack scanning
15  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f6224f67e80
    Found by: stack scanning
16  libpthread-2.11.3.so + 0x5ee8
    rip = 0x00007f6289908ee9   rsp = 0x00007f6224f67e90
    Found by: stack scanning
17  libc-2.11.3.so + 0x35884f
    rip = 0x00007f628914d850   rsp = 0x00007f6224f67e98
    Found by: stack scanning
18  libc-2.11.3.so + 0x35885f
    rip = 0x00007f628914d860   rsp = 0x00007f6224f67ea0
    Found by: stack scanning
19  libc-2.11.3.so + 0x358867
    rip = 0x00007f628914d868   rsp = 0x00007f6224f67ea8
    Found by: stack scanning
20  libpthread-2.11.3.so + 0x68c9
    rip = 0x00007f62899098ca   rsp = 0x00007f6224f67ed0
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x0268dfff  phantomjs  ???  (main)
0x7f62279ae000 - 0x7f62279c9fff  p052024l.pfb  ???
0x7f62279ca000 - 0x7f62279dffff  n021024l.pfb  ???
0x7f62279e0000 - 0x7f62279f7fff  c059036l.pfb  ???
0x7f62279f8000 - 0x7f6227a09fff  b018035l.pfb  ???
0x7f6227a0a000 - 0x7f6227a30fff  FreeSansBoldOblique.ttf  ???
0x7f622c359000 - 0x7f622c3a9fff  DejaVuSans-ExtraLight.ttf  ???
0x7f622cac1000 - 0x7f622cadbfff  p052023l.pfb  ???
0x7f622cbff000 - 0x7f622cc16fff  c059033l.pfb  ???
0x7f622cc21000 - 0x7f622cc44fff  LiberationSerif-Italic.ttf  ???
0x7f622cc45000 - 0x7f622cc8efff  FreeSansOblique.ttf  ???
0x7f622cce2000 - 0x7f622ccf6fff  b018032l.pfb  ???
0x7f622ce75000 - 0x7f622cef5fff  DejaVuSans-BoldOblique.ttf  ???
0x7f622cf4b000 - 0x7f622cf65fff  c059016l.pfb  ???
0x7f622cf95000 - 0x7f622cfa7fff  b018015l.pfb  ???
0x7f622cfa8000 - 0x7f622cff1fff  DejaVuSansMono-Bold.ttf  ???
0x7f622cff2000 - 0x7f622d072fff  DejaVuSans-Oblique.ttf  ???
0x7f622d073000 - 0x7f622d084fff  n019004l.pfb  ???
0x7f622d085000 - 0x7f622d09bfff  z003034l.pfb  ???
0x7f622d09c000 - 0x7f622d0c0fff  LiberationSerif-Regular.ttf  ???
0x7f622d0c1000 - 0x7f622d1fbfff  FreeSerif.ttf  ???
0x7f622e21c000 - 0x7f622e236fff  LiberationMono-Regular.ttf  ???
0x7f622e237000 - 0x7f622e27ffff  DejaVuSerifCondensed.ttf  ???
0x7f622e280000 - 0x7f622e2cefff  DejaVuSansMono.ttf  ???
0x7f622e2cf000 - 0x7f622e31bfff  FreeMono.ttf  ???
0x7f622e31c000 - 0x7f622e336fff  p052003l.pfb  ???
0x7f622e337000 - 0x7f622e34efff  n022003l.pfb  ???
0x7f622e34f000 - 0x7f622e367fff  n021003l.pfb  ???
0x7f622e368000 - 0x7f622e381fff  c059013l.pfb  ???
0x7f622e382000 - 0x7f622e39afff  b018012l.pfb  ???
0x7f622ebb1000 - 0x7f622edb2fff  libnss_mdns4.so.2  ???
0x7f622f165000 - 0x7f622f17bfff  n021023l.pfb  ???
0x7f622f241000 - 0x7f622f251fff  n019023l.pfb  ???
0x7f622f58d000 - 0x7f622f5b7fff  FreeSansBold.ttf  ???
0x7f622f630000 - 0x7f622f6a0fff  FreeSans.ttf  ???
0x7f622f6a1000 - 0x7f622f6c1fff  LiberationSans-BoldItalic.ttf  ???
0x7f622fc63000 - 0x7f622fc73fff  n019024l.pfb  ???
0x7f622fc7f000 - 0x7f622fca3fff  LiberationSerif-BoldItalic.ttf  ???
0x7f62306c4000 - 0x7f62306ebfff  LiberationSans-Italic.ttf  ???
0x7f62306ec000 - 0x7f623070dfff  LiberationSans-Bold.ttf  ???
0x7f623070e000 - 0x7f6230793fff  DejaVuSansCondensed-Bold.ttf  ???
0x7f6230794000 - 0x7f623082efff  DejaVuSans.ttf  ???
0x7f6231030000 - 0x7f6231052fff  LiberationSans-Regular.ttf  ???
0x7f6231053000 - 0x7f6231258fff  libnss_dns-2.11.3.so  ???
0x7f6231259000 - 0x7f623145afff  libnss_mdns4_minimal.so.2  ???
0x7f623145b000 - 0x7f6231667fff  libnss_files-2.11.3.so  ???
0x7f6231668000 - 0x7f623187bfff  libresolv-2.11.3.so  ???
0x7f6231b68000 - 0x7f6231b77fff  a010013l.pfb  ???
0x7f6231e03000 - 0x7f6231e26fff  LiberationSerif-Bold.ttf  ???
0x7f6231e27000 - 0x7f6231e40fff  LiberationMono-Bold.ttf  ???
0x7f6231e41000 - 0x7f6231e8cfff  DejaVuSerif-Bold.ttf  ???
0x7f6231e8d000 - 0x7f6231ecefff  FreeSerifBold.ttf  ???
0x7f6231ecf000 - 0x7f6231ef7fff  FreeMonoBold.ttf  ???
0x7f6231ef8000 - 0x7f6231f12fff  p052004l.pfb  ???
0x7f6231f13000 - 0x7f6231f2bfff  n022004l.pfb  ???
0x7f6231f2c000 - 0x7f6231f44fff  n021004l.pfb  ???
0x7f62328ed000 - 0x7f62328fcfff  a010015l.pfb  ???
0x7f6284062000 - 0x7f628406afff  s050000l.pfb  ???
0x7f6284074000 - 0x7f628407ffff  d050000l.pfb  ???
0x7f6285f5a000 - 0x7f6285f6dfff  n019003l.pfb  ???
0x7f6287fce000 - 0x7f62881d0fff  ISO8859-15.so  ???
0x7f62881d1000 - 0x7f6288427fff  libssl.so.0.9.8  ???
0x7f6288428000 - 0x7f62887c4fff  libcrypto.so.0.9.8  ???
0x7f62887c9000 - 0x7f62889b5fff  locale-archive  ???
0x7f62889b6000 - 0x7f6288bddfff  libexpat.so.1.5.2  ???
0x7f6288bde000 - 0x7f6288df4fff  libz.so.1.2.3.4  ???
0x7f6288df5000 - 0x7f6289151fff  libc-2.11.3.so  ???
0x7f6289157000 - 0x7f628936cfff  libgcc_s.so.1  ???
0x7f628936d000 - 0x7f62895eefff  libm-2.11.3.so  ???
0x7f62895ef000 - 0x7f62898edfff  libstdc++.so.6.0.13  ???
0x7f6289903000 - 0x7f6289b1afff  libpthread-2.11.3.so  ???
0x7f6289b1f000 - 0x7f6289d26fff  librt-2.11.3.so  ???
0x7f6289d27000 - 0x7f6289f2afff  libdl-2.11.3.so  ???
0x7f6289f2b000 - 0x7f628a15ffff  libfontconfig.so.1.4.4  ???
0x7f628a160000 - 0x7f628a3e7fff  libfreetype.so.6.6.0  ???
0x7f628a3e8000 - 0x7f628a405fff  ld-2.11.3.so  ???
0x7f628a5a7000 - 0x7f628a5adfff  gconv-modules.cache  ???
0x7f628a5ae000 - 0x7f628a5cdfff  libc.mo  ???
0x7f628a5ce000 - 0x7f628a5d6fff  945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-3  ???
0x7f628a5d7000 - 0x7f628a5dffff  6d41288fd70b0be22e8c3a91e032eec0-le64.cache-3  ???
0x7f628a5e0000 - 0x7f628a5e9fff  d52a8644073d54c13679302ca1180695-le64.cache-3  ???
0x7f628a5f6000 - 0x7f628a5f9fff  6eb3985aa4124903f6ff08ba781cd364-le64.cache-3  ???
0x7f628a5fa000 - 0x7f628a602fff  e13b20fdb08344e0e664864cc2ede53d-le64.cache-3  ???
0x7fffe61ff000 - 0x7fffe61fffff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
