### ISSUE TITLE
Configurable disk cache location

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#12491]
Right now it's hard coded in the application-specific location. This means that every instance of launched PhantomJS will share the same cache, which may cause problems in some use cases.

**Comment by torinaki** [comment]
@ariya we run about 10 PhantomJS(1.10-dev) processes on same server at same time. I have noticed that PhantomJS crashes more often when cache is enabled. Seems like because of concurency to write a cache.

**Comment by Vitallium** [comment]
Landed in https://github.com/ariya/phantomjs/commit/c9e30ebafdeb42efe33900da7823142e146b0a1d
