### ISSUE TITLE
Setting selectionStart on an element appears to do nothing.

### ISSUE THREAD

**Issue by cuzzo** [ariya/phantomjs#12493]
Hey,

I have an element:

``` javascript
var $el = document.getElementsByTagName("input")[0];
```

When I set the selectionStart attribute on `$el` it appears to do nothing--or remain whatever the length of text inside the input is.

``` javascript
$el.value = "ABC"
$el.selectionStart = 1;
console.log($el.selectionStart);
```

That outputs `3` for me.

I've tried this in a bunch of different contexts, and in every way it seems that the selectionStart is always the length of the element's value.

``` javascript
$el.value = "ABCD";
$el.setSelectionRange(1, 1);
console.log($el.selectionStart);
```

`4`

Thanks,

**Comment by wilandrade** [comment]
:+1: PhantomJS 1.9.8 (Mac OS X)

**Comment by pontusi** [comment]
I have the same problem in Phantom 2.0. For my needs - unit tests with Jasmine - I use the workaround of instead spying on the setSelectionRange function.

	describe('textbox selection', function() {
		var textbox;

		beforeEach(function() {
			textbox = document.createElement('input');
			textbox.value = 'test';
		});

		// Fails.
		it('supports selectionStart/end', function() {
			textbox.selectionStart = 1;
			textbox.selectionEnd = 3;

			expect(textbox.selectionStart).toBe(1);
			expect(textbox.selectionEnd).toBe(3);
		});

		// Works.
		it('supports setSelectionRange', function() {
			var spy = spyOn(textbox, 'setSelectionRange');

			textbox.setSelectionRange(1, 3);

			expect(spy).toHaveBeenCalledWith(1, 3);
		});
	});

**Comment by pontusi** [comment]
I have a similar but not identical problem.

From what I can tell, WebKit - at least the version embedded in PhantomJS - does not update the selection unless the control is added to the page and can be rendered. For my needs, all I need to do is add the control to the page.

```javascript
var textbox = document.createElement('input');
document.body.appendChild(textbox); // This is critical for selectionStart/end to be updated.

textbox.value = 'test';
textbox.setSelectionRange(0, 4);

expect(textbox.selectionStart).toBe(0);
expect(textbox.selectionEnd).toBe(4);
```

As Op's control is already added to the page I'm not sure why it's not getting updated. It may be hidden by CSS.

**Comment by japgolly** [comment]
This is still a problem in PhantomJS 2.0.

**Comment by hellosmithy** [comment]
I'm seeing the same behaviour in both PhantomJS 1.9.8 and 2.0.2
Is there any likely fix on the horizon?

**Comment by oigewan** [comment]
Phantom 2.1.2 still has the issue.

**Comment by gbedardsice** [comment]
Not seeing the issue on 2.1.1 (Mac OS X), but issue occurs on 2.1.1 (Linux).

**Comment by dirkluijk** [comment]
Having the same issue on 2.1.1 (Windows).

**Comment by jamie-pate** [comment]
It appears to work when I create an input but don't add it to the dom. When I add it to the DOM it stops working.. (sometimes!)

These tests that rely on this are also failing on the linux build node, but succeeding on my linux desktop. Both are running `PhantomJS 2.1.1 (Linux 0.0.0)` :confounded:
