### ISSUE TITLE
PhantomJS Crashing on Linux

### ISSUE THREAD

**Issue by brownat** [ariya/phantomjs#12516]
While running karma unit tests with PhantomJS as the browser, occasionally we get a message that PhantomJS has crashed.  We have a dmp file and have followed the process to create a stack trace.
We are using PhantomJS 1.9.7-5
Running on SUSE Linux Enterprise Server 11 SP1  (x86_64) 
Linux TS2013Gold64 2.6.32.12-0.7-default #1 SMP 2010-05-20 11:14:20 +0200 x86_64 x86_64 x86_64 GNU/Linux

Stacktrace:
Operating system: Linux
                  0.0.0 Linux 2.6.32.12-0.7-default #1 SMP 2010-05-20 11:14:20 +0200 x86_64
CPU: amd64
     family 6 model 45 stepping 7
     2 CPUs

Crash reason:  SIGABRT
Crash address: 0x3e800000cb9

Thread 0 (crashed)
 0  libc-2.11.1.so + 0x32945
    rbx = 0x0000000002f575c0   r12 = 0x0000000002d86e90
    r13 = 0x0000000002f57590   r14 = 0x000000000308d980
    r15 = 0x0000000003153a40   rip = 0x00007f197f70b945
    rsp = 0x00007fff74b03728   rbp = 0x0000000002f575d8
    Found by: given as instruction pointer in context
 1  libc-2.11.1.so + 0x33f20
    rip = 0x00007f197f70cf21   rsp = 0x00007fff74b03730
    Found by: stack scanning
 2  libstdc++.so.6.0.10 + 0x20982
    rip = 0x00007f197fec4983   rsp = 0x00007fff74b03748
    Found by: stack scanning
 3  ld-2.11.1.so + 0x55f
    rip = 0x00007f1980c90560   rsp = 0x00007fff74b03750
    Found by: stack scanning
 4  libc-2.11.1.so + 0x6b17
    rip = 0x00007f197f6dfb18   rsp = 0x00007fff74b03768
    Found by: stack scanning
 5  libm-2.11.1.so + 0x255fff
    rip = 0x00007f197fea4000   rsp = 0x00007fff74b037a0
    Found by: stack scanning
 6  ld-2.11.1.so + 0xd8b7
    rip = 0x00007f1980c9d8b8   rsp = 0x00007fff74b037c0
    Found by: stack scanning
 7  libstdc++.so.6.0.10 + 0xc7503
    rip = 0x00007f197ff6b504   rsp = 0x00007fff74b03860
    Found by: stack scanning
 8  libpthread-2.11.1.so + 0xe51c
    rip = 0x00007f19801bd51d   rsp = 0x00007fff74b03870
    Found by: stack scanning
 9  libstdc++.so.6.0.10 + 0xc5945
    rip = 0x00007f197ff69946   rsp = 0x00007fff74b03890
    Found by: stack scanning
10  libstdc++.so.6.0.10 + 0xc5972
    rip = 0x00007f197ff69973   rsp = 0x00007fff74b038a0
    Found by: stack scanning
11  libstdc++.so.6.0.10 + 0xc61fe
    rip = 0x00007f197ff6a1ff   rsp = 0x00007fff74b038b0
    Found by: stack scanning
12  phantomjs + 0x18debeb
    rip = 0x0000000001cdebec   rsp = 0x00007fff74b038c0
    Found by: stack scanning
13  libc-2.11.1.so + 0x7a056
    rip = 0x00007f197f753057   rsp = 0x00007fff74b03920
    Found by: stack scanning
14  phantomjs + 0x18ef6fc
    rip = 0x0000000001cef6fd   rsp = 0x00007fff74b03930
    Found by: stack scanning
15  phantomjs + 0x18f7270
    rip = 0x0000000001cf7271   rsp = 0x00007fff74b03970
    Found by: stack scanning
16  phantomjs + 0x18ef493
    rip = 0x0000000001cef494   rsp = 0x00007fff74b03a10
    Found by: stack scanning
17  phantomjs + 0x17214a4
    rip = 0x0000000001b214a5   rsp = 0x00007fff74b03a90
    Found by: stack scanning
18  phantomjs + 0x1c8a4bf
    rip = 0x000000000208a4c0   rsp = 0x00007fff74b03ab8
    Found by: stack scanning
19  phantomjs + 0xed1a8
    rip = 0x00000000004ed1a9   rsp = 0x00007fff74b03ac0
    Found by: stack scanning
20  phantomjs + 0xef146
    rip = 0x00000000004ef147   rsp = 0x00007fff74b03af0
    Found by: stack scanning
21  phantomjs + 0x1c8a4bf
    rip = 0x000000000208a4c0   rsp = 0x00007fff74b03af8
    Found by: stack scanning
22  phantomjs + 0xf63e6
    rip = 0x00000000004f63e7   rsp = 0x00007fff74b03b30
    Found by: stack scanning

Thread 1
 0  libpthread-2.11.1.so + 0xb42c
    rbx = 0x0000000002a84208   r12 = 0x0000000002a76160
    r13 = 0x00007f197ebd6000   r14 = 0x0000000000000000
    r15 = 0x0000000000001000   rip = 0x00007f19801ba42c
    rsp = 0x00007f197ebd5e28   rbp = 0x0000000002a76160
    Found by: given as instruction pointer in context
 1  phantomjs + 0xddafb
    rip = 0x00000000004ddafc   rsp = 0x00007f197ebd5e50
    Found by: stack scanning
 2  libc-2.11.1.so + 0x95a7
    rip = 0x00007f197f6e25a8   rsp = 0x00007f197ebd5e68
    Found by: stack scanning
 3  libpthread-2.11.1.so + 0x1169f
    rip = 0x00007f19801c06a0   rsp = 0x00007f197ebd5e80
    Found by: stack scanning
 4  libpthread-2.11.1.so + 0x1169f
    rip = 0x00007f19801c06a0   rsp = 0x00007f197ebd5eb0
    Found by: stack scanning
 5  phantomjs + 0xddc98
    rip = 0x00000000004ddc99   rsp = 0x00007f197ebd5ed0
    Found by: stack scanning
 6  libpthread-2.11.1.so + 0x75ef
    rip = 0x00007f19801b65f0   rsp = 0x00007f197ebd5ee0
    Found by: stack scanning
 7  libpthread-2.11.1.so + 0x1169f
    rip = 0x00007f19801c06a0   rsp = 0x00007f197ebd5f88
    Found by: stack scanning
 8  libc-2.11.1.so + 0xd484c
    rip = 0x00007f197f7ad84d   rsp = 0x00007f197ebd6000
    Found by: stack scanning

Thread 2
 0  libc-2.11.1.so + 0xcdb93
    rbx = 0x0000000000000000   r12 = 0x00007f197e2d4db0
    r13 = 0x0000000000000008   r14 = 0x0000000002c10fc8
    r15 = 0x0000000002c11260   rip = 0x00007f197f7a6b93
    rsp = 0x00007f197e2d4b80   rbp = 0x0000000002c10e10
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906326
    rip = 0x0000000001d06327   rsp = 0x00007f197e2d4b90
    Found by: stack scanning
 2  libpthread-2.11.1.so + 0xe2f
    rip = 0x00007f19801afe30   rsp = 0x00007f197e2d4bd0
    Found by: stack scanning
 3  libpthread-2.11.1.so + 0xe0f
    rip = 0x00007f19801afe10   rsp = 0x00007f197e2d4bd8
    Found by: stack scanning
 4  libpthread-2.11.1.so + 0xe588
    rip = 0x00007f19801bd589   rsp = 0x00007f197e2d4be0
    Found by: stack scanning
 5  phantomjs + 0x19075e6
    rip = 0x0000000001d075e7   rsp = 0x00007f197e2d4c20
    Found by: stack scanning
 6  linux-gate.so + 0x6fa
    rip = 0x00007fff74bff6fb   rsp = 0x00007f197e2d4c40
    Found by: stack scanning
 7  phantomjs + 0x1840b73
    rip = 0x0000000001c40b74   rsp = 0x00007f197e2d4ca0
    Found by: stack scanning
 8  phantomjs + 0x1840a78
    rip = 0x0000000001c40a79   rsp = 0x00007f197e2d4ce0
    Found by: stack scanning
 9  phantomjs + 0x1906fa5
    rip = 0x0000000001d06fa6   rsp = 0x00007f197e2d4cf0
    Found by: stack scanning
10  phantomjs + 0x1908091
    rip = 0x0000000001d08092   rsp = 0x00007f197e2d4d60
    Found by: stack scanning
11  phantomjs + 0x18dd4b4
    rip = 0x0000000001cdd4b5   rsp = 0x00007f197e2d4db0
    Found by: stack scanning
12  phantomjs + 0x18ddca8
    rip = 0x0000000001cddca9   rsp = 0x00007f197e2d4dc0
    Found by: stack scanning
13  phantomjs + 0x18dd917
    rip = 0x0000000001cdd918   rsp = 0x00007f197e2d4de0
    Found by: stack scanning
14  phantomjs + 0x17dfdf5
    rip = 0x0000000001bdfdf6   rsp = 0x00007f197e2d4e40
    Found by: stack scanning
15  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f197e2d4e90
    Found by: stack scanning
16  libpthread-2.11.1.so + 0x75ef
    rip = 0x00007f19801b65f0   rsp = 0x00007f197e2d4ee0
    Found by: stack scanning

Thread 3
 0  libc-2.11.1.so + 0xcdb93
    rbx = 0x00007f193ca9ed60   r12 = 0x00000000001b0d4d
    r13 = 0x0000000000000014   r14 = 0x0000000002c8cc98
    r15 = 0x0000000002c8cf30   rip = 0x00007f197f7a6b93
    rsp = 0x00007f193ca9eb80   rbp = 0x0000000000032f27
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906227
    rip = 0x0000000001d06228   rsp = 0x00007f193ca9eb90
    Found by: stack scanning
 2  phantomjs + 0x19075e6
    rip = 0x0000000001d075e7   rsp = 0x00007f193ca9ec20
    Found by: stack scanning
 3  linux-gate.so + 0x6fa
    rip = 0x00007fff74bff6fb   rsp = 0x00007f193ca9ec40
    Found by: stack scanning
 4  phantomjs + 0x1840b73
    rip = 0x0000000001c40b74   rsp = 0x00007f193ca9eca0
    Found by: stack scanning
 5  phantomjs + 0x1907ced
    rip = 0x0000000001d07cee   rsp = 0x00007f193ca9ecd0
    Found by: stack scanning
 6  phantomjs + 0x1840a78
    rip = 0x0000000001c40a79   rsp = 0x00007f193ca9ece0
    Found by: stack scanning
 7  phantomjs + 0x1906fa5
    rip = 0x0000000001d06fa6   rsp = 0x00007f193ca9ecf0
    Found by: stack scanning
 8  phantomjs + 0x1908091
    rip = 0x0000000001d08092   rsp = 0x00007f193ca9ed60
    Found by: stack scanning
 9  phantomjs + 0x18dd4b4
    rip = 0x0000000001cdd4b5   rsp = 0x00007f193ca9edb0
    Found by: stack scanning
10  phantomjs + 0x18ddca8
    rip = 0x0000000001cddca9   rsp = 0x00007f193ca9edc0
    Found by: stack scanning
11  phantomjs + 0x18dd917
    rip = 0x0000000001cdd918   rsp = 0x00007f193ca9ede0
    Found by: stack scanning
12  phantomjs + 0x17dfdf5
    rip = 0x0000000001bdfdf6   rsp = 0x00007f193ca9ee40
    Found by: stack scanning
13  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f193ca9ee90
    Found by: stack scanning
14  libpthread-2.11.1.so + 0x75ef
    rip = 0x00007f19801b65f0   rsp = 0x00007f193ca9eee0
    Found by: stack scanning

Thread 4
 0  libpthread-2.11.1.so + 0xb799
    rbx = 0x00007f1938005a50   r12 = 0x0000000000000001
    r13 = 0x00007f1937ffedf0   r14 = 0x00007f1938005a78
    r15 = 0x0000000000000000   rip = 0x00007f19801ba799
    rsp = 0x00007f1937ffed78   rbp = 0x00007f1938005d20
    Found by: given as instruction pointer in context
 1  phantomjs + 0x17e39d6
    rip = 0x0000000001be39d7   rsp = 0x00007f1937ffedd0
    rbp = 0x00007f1938005d20
    Found by: stack scanning
 2  phantomjs + 0xf91c3f
    rip = 0x0000000001391c40   rsp = 0x00007f1937ffee00
    rbp = 0x00007f1938005d20
    Found by: stack scanning
 3  phantomjs + 0x17d783c
    rip = 0x0000000001bd783d   rsp = 0x00007f1937ffee50
    rbp = 0x00007f1938005d20
    Found by: stack scanning
 4  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f1937ffee90
    rbp = 0x00007f1938005d20
    Found by: stack scanning
 5  libpthread-2.11.1.so + 0x75ef
    rip = 0x00007f19801b65f0   rsp = 0x00007f1937ffeee0
    rbp = 0x00007f1938005d20
    Found by: stack scanning

Thread 5
 0  phantomjs + 0x18e8338
    rbx = 0x0000000000000000   r12 = 0x00007f19371bf560
    r13 = 0x00007f1938023660   r14 = 0x0000000000000000
    r15 = 0x00007f1938023660   rip = 0x0000000001ce8338
    rsp = 0x00007f19371bef70   rbp = 0x00007f19371bf518
    Found by: given as instruction pointer in context
 1  phantomjs + 0x18debeb
    rip = 0x0000000001cdebec   rsp = 0x00007f19371bef90
    rbp = 0x00007f19371bf518
    Found by: stack scanning
 2  phantomjs + 0x17c058f
    rip = 0x0000000001bc0590   rsp = 0x00007f19371bef98
    rbp = 0x00007f19371bf518
    Found by: stack scanning
 3  libc-2.11.1.so + 0x7a056
    rip = 0x00007f197f753057   rsp = 0x00007f19371beff0
    rbp = 0x00007f19371bf518
    Found by: stack scanning
 4  phantomjs + 0x18ef6fc
    rip = 0x0000000001cef6fd   rsp = 0x00007f19371bf000
    rbp = 0x00007f19371bf518
    Found by: stack scanning
 5  phantomjs + 0x18e8b28
    rip = 0x0000000001ce8b29   rsp = 0x00007f19371bf040
    rbp = 0x00007f19371bf518
    Found by: stack scanning
 6  phantomjs + 0x193c86f
    rip = 0x0000000001d3c870   rsp = 0x00007f19371bf098
    rbp = 0x00007f19371bf518
    Found by: stack scanning
 7  phantomjs + 0x18e4c6f
    rip = 0x0000000001ce4c70   rsp = 0x00007f19371bf140
    rbp = 0x00007f19371bf518
    Found by: stack scanning
 8  phantomjs + 0x1db51ef
    rip = 0x00000000021b51f0   rsp = 0x00007f19371bf150
    rbp = 0x00007f19371bf518
    Found by: stack scanning
 9  phantomjs + 0x18e4cbf
    rip = 0x0000000001ce4cc0   rsp = 0x00007f19371bf180
    rbp = 0x00007f19371bf518
    Found by: stack scanning
10  phantomjs + 0x18e99fd
    rip = 0x0000000001ce99fe   rsp = 0x00007f19371bf1c0
    rbp = 0x00007f19371bf518
    Found by: stack scanning
11  phantomjs + 0x1db1150
    rip = 0x00000000021b1151   rsp = 0x00007f19371bf1d0
    rbp = 0x00007f19371bf518
    Found by: stack scanning
12  phantomjs + 0x1db44e6
    rip = 0x00000000021b44e7   rsp = 0x00007f19371bf1e0
    rbp = 0x00007f19371bf518
    Found by: stack scanning
13  phantomjs + 0x1db44ee
    rip = 0x00000000021b44ef   rsp = 0x00007f19371bf1f0
    rbp = 0x00007f19371bf518
    Found by: stack scanning
14  phantomjs + 0x1db1150
    rip = 0x00000000021b1151   rsp = 0x00007f19371bf278
    rbp = 0x00007f19371bf518
    Found by: stack scanning
15  phantomjs + 0x1db44e6
    rip = 0x00000000021b44e7   rsp = 0x00007f19371bf280
    rbp = 0x00007f19371bf518
    Found by: stack scanning
16  phantomjs + 0x1db44ee
    rip = 0x00000000021b44ef   rsp = 0x00007f19371bf288
    rbp = 0x00007f19371bf518
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x0268dfff  phantomjs  ???  (main)
0x7f193c022000 - 0x7f193c056fff  dboMD4cI (deleted)  ???
0x7f193c057000 - 0x7f193c26bfff  libresolv-2.11.1.so  ???
0x7f193c28d000 - 0x7f193c29efff  n019004l.pfb  ???
0x7f193d20b000 - 0x7f193d21bfff  n019003l.pfb  ???
0x7f197ebd7000 - 0x7f197ee2afff  libssl.so.0.9.8  ???
0x7f197ee2b000 - 0x7f197f1a2fff  libcrypto.so.0.9.8  ???
0x7f197f1d7000 - 0x7f197f1e0fff  77e41c5059666d75f92e318d4be8c21e-x86-64.cache-2  ???
0x7f197f1e1000 - 0x7f197f23cfff  df311e82a1a24c41a75c2c930223552e-x86-64.cache-2  ???
0x7f197f23d000 - 0x7f197f298fff  17090aa38d5c6f09fb8c5c354938f1d7-x86-64.cache-2  ???
0x7f197f299000 - 0x7f197f4c2fff  libexpat.so.1.5.2  ???
0x7f197f4c3000 - 0x7f197f6d8fff  libz.so.1.2.3  ???
0x7f197f6d9000 - 0x7f197fa31fff  libc-2.11.1.so  ???
0x7f197fa37000 - 0x7f197fc4dfff  libgcc_s.so.1  ???
0x7f197fc4e000 - 0x7f197fea3fff  libm-2.11.1.so  ???
0x7f197fea4000 - 0x7f198019bfff  libstdc++.so.6.0.10  ???
0x7f19801af000 - 0x7f19803c7fff  libpthread-2.11.1.so  ???
0x7f19803cc000 - 0x7f19805d4fff  librt-2.11.1.so  ???
0x7f19805d5000 - 0x7f19807d8fff  libdl-2.11.1.so  ???
0x7f19807d9000 - 0x7f1980a0afff  libfontconfig.so.1.3.0  ???
0x7f1980a0b000 - 0x7f1980c8ffff  libfreetype.so.6.3.18  ???
0x7f1980c90000 - 0x7f1980caefff  ld-2.11.1.so  ???
0x7f1980cd6000 - 0x7f1980d03fff  8d4af663993b81a124ee82e610bb31f9-x86-64.cache-2  ???
0x7f1980d04000 - 0x7f1980d18fff  7ef2298fde41cc6eeb7af42e48b7d293-x86-64.cache-2  ???
0x7f1980d19000 - 0x7f1980d57fff  LC_CTYPE  ???
0x7f1980d58000 - 0x7f1980e74fff  LC_COLLATE  ???
0x7f1980e95000 - 0x7f1980e9bfff  d62e99ef547d1d24cdb1bd22ec1a2976-x86-64.cache-2  ???
0x7f1980e9c000 - 0x7f1980e9cfff  LC_NUMERIC  ???
0x7f1980e9d000 - 0x7f1980e9dfff  LC_TIME  ???
0x7f1980e9e000 - 0x7f1980e9efff  LC_MONETARY  ???
0x7f1980e9f000 - 0x7f1980e9ffff  SYS_LC_MESSAGES  ???
0x7f1980ea0000 - 0x7f1980ea0fff  LC_PAPER  ???
0x7f1980ea1000 - 0x7f1980ea1fff  LC_NAME  ???
0x7f1980ea2000 - 0x7f1980ea2fff  LC_ADDRESS  ???
0x7f1980ea3000 - 0x7f1980ea3fff  LC_TELEPHONE  ???
0x7f1980ea4000 - 0x7f1980ea4fff  LC_MEASUREMENT  ???
0x7f1980ea5000 - 0x7f1980eabfff  gconv-modules.cache  ???
0x7f1980eac000 - 0x7f1980eacfff  LC_IDENTIFICATION  ???
0x7fff74bff000 - 0x7fff74bfffff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
