### ISSUE TITLE
Event.popstate is fired on start any page

### ISSUE THREAD

**Issue by loduis** [ariya/phantomjs#12511]
``` javascript

var page = require('webpage').create();

page.onConsoleMessage = function(msg, lineNum, sourceId) {
    console.log('CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
};

page.open('data:text/html,'+
  '<body><script>window.addEventListener("popstate", function () { console.log("Event popstate")}); </script></body>',
  function (status) {
    console.log(status);
});

```

In chorme and firefox is event is fired only when the url to accessed was placed in the history with history.pushState or history.replaceState

This behavior on phantomjs is the same presenting  in some old versions of chrome

**Comment by geminiyellow** [comment]
@ariya be fixed in 2.x? or not.

**Comment by ariya** [comment]
@geminiyellow Did you try it?

**Comment by profsmallpine** [comment]
@ariya `window.onpopstate` is still firing on page load in phantomjs 2.1

**Comment by alex-voigt** [comment]
same for me

**Comment by profsmallpine** [comment]
@alex-voigt kind of annoying, but i attached the listener using a timeout (just to fix my tests 😦 )

```setTimeout((function() {
  return window.onpopstate = function(event) {
    return window.location.href = window.location.href;
  };
}), 1000);```

**Comment by mdix** [comment]
I have the same problem. Really annoying. :(

**Comment by SimonKlausLudwig** [comment]
Same problem here...
