### ISSUE TITLE
i can't build it

### ISSUE THREAD

**Issue by strivingzhou** [ariya/phantomjs#12520]
since i run build.cmd i got the error:
E:\OpenSource\phantomjs>build.cmd

Build type: release

GIT found. Getting 3rd party libraries.
LIB: E:\OpenSource\phantomjs\src\qt\3rdparty\openssl\lib;E:\OpenSource\phantomjs
\src\qt\3rdparty\libicu\lib;E:\OpenSource\phantomjs\src\qt\3rdparty\libxml\lib;C
:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\LIB\amd64;C:\Program Files
 (x86)\Microsoft Visual Studio 11.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\W
indows Kits\8.0\lib\win8\um\x64;
INCLUDE: E:\OpenSource\phantomjs\src\qt\3rdparty\openssl\include;E:\OpenSource\p
hantomjs\src\qt\3rdparty\libicu\include;E:\OpenSource\phantomjs\src\qt\3rdparty\
libxml\include\libxml2;C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\IN
CLUDE;C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\ATLMFC\INCLUDE;C:\P
rogram Files (x86)\Windows Kits\8.0\include\shared;C:\Program Files (x86)\Window
s Kits\8.0\include\um;C:\Program Files (x86)\Windows Kits\8.0\include\winrt;
系统找不到指定的路径。

qmake found. Building QtWebkit
系统找不到指定的路径。
Project ERROR: Unknown module(s) in QT: webkitwidgets network gui core
系统找不到指定的路径。

Unable to find phantomjs.exe. Please, check log files:
Qt: E:\OpenSource\phantomjs\build_qt_9 周五8/4/-1121.log
Webkit: E:\OpenSource\phantomjs\build_webkit_9 周五8/4/_1121.log
PhantomJS: E:\OpenSource\phantomjs\build_phantomjs_9 周五8/4/_1121.log

**Comment by Vitallium** [comment]
Outdated.
