### ISSUE TITLE
PhantomJs has crashed...

### ISSUE THREAD

**Issue by daechiku** [ariya/phantomjs#12521]
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: C:\Users\DeRa\AppData\Local\Temp\2c11146d-c2fb-4e24-968d-3cad291b44d9.dmp

I Found this error when Click submit button on iframe in action TRANSFER internet banking.
Can you tell me how this occured... thank

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
