### ISSUE TITLE
Update SSL/TLS support

### ISSUE THREAD

**Issue by zackw** [ariya/phantomjs#12524]
Qt 5.x allows use of newer SSL protocol versions beyond TLSv1.0.  This should be accessible in phantomjs.

**Comment by tisba** [comment]
I just stumbled across this. Does that mean that phantomjs (up to 2.0) does not support TLSv1.1 nor TLSv1.2?

**Comment by zackw** [comment]
Yes, that is correct, 1.x versions only support SSL 3.0 and TLS 1.0, and by default only SSL 3.0 is offered.

I believe the patches I wrote for this should backport to 1.x with no difficulty, if you need that.

**Comment by tisba** [comment]
Pardon me for pumping this: Is there any change to the TLS situation with the newly released 2.1.?

**Comment by zackw** [comment]
2.1 is better but not perfect. IIRC 2.1 will, by default, offer SSL3
through TLS1.2, provided the underlying OpenSSL supports them. You can use
command line options to restrict it to any *one* protocol level. There is
also a command line  option to tune the ciphers offered.

What still isn't possible is to offer both TLS1.1 and 1.2 but nothing
older, or to mimic Chrome's elaborate version fallback logic. That needs to
be added to Qt before we can pick it up.
