### ISSUE TITLE
PhantomJS has crashed.

### ISSUE THREAD

**Issue by pdragon** [ariya/phantomjs#12532]
phantomjs -v
1.9.0
dump:
https://dl.dropboxusercontent.com/u/2808202/tmp/54ad3023-9c6f-f304-04d0091f-73db7e52.dmp

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
