### ISSUE TITLE
PhantomJS has crashed

### ISSUE THREAD

**Issue by ta-patel** [ariya/phantomjs#12533]
phantomjs -v
successfull
 
phantomjs hello.js
"PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/69635415-954b-0ea0-2d3257d5-1b68b0f0.dmp"

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
