### ISSUE TITLE
PhantomJS Crash

### ISSUE THREAD

**Issue by zlaja1983** [ariya/phantomjs#12535]
![screen shot 2014-09-03 at 1 04 25 pm](https://cloud.githubusercontent.com/assets/7635374/4137958/6bfbb9ca-338c-11e4-8fb8-63bcff4ed921.png)
Running unit tests from the command line. PhantomJS crashes (version:     "phantomjs": "~1.9.7-14"). Stacktrace can be found at:
https://bitbucket.org/zlaja1983/stacktraces/src

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
