### ISSUE TITLE
crash EXC_BAD_ACCESS / KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by jblaise** [ariya/phantomjs#12538]
I saw a lot of issue concerning similar crashes.

To describe dev env : 
- mac os
- grunt
- protractor ( + selenium)
- phantomjs (obviously)
- requirejs
- angularjs
- jasmine (for tests)

To describe the project : 
- AMD approach
- [angular best practice](https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub) -> lot of files

To describe tests:
- each it has a fresh page (refresh in  a beforeEach) to avoid side effect

Like another one wrote, it seems to crashed Intermittently. Well, to reduce the probability, I transform massively (describe,it) into (xdescribe, xit) to avoid crash and have result for tests and exoects I am working on.

Here is the [stack trace](https://gist.github.com/jb-captic/ace04ff0f3131bc0904d)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
