### ISSUE TITLE
phantomJS crashes..

### ISSUE THREAD

**Issue by SSugatGIT** [ariya/phantomjs#12545]
I don't know the way to convert the dump to stacktrace in windows..

Context:
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/
phantomjs/issues/new with the crash dump file attached: C:\Users\Local\Temp\1dc53b90-15c5-40ff-8262-4f762ecd1d60.dmp

Is there any other way i can provide you the dump file?

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
