### ISSUE TITLE
Changes to page.settings in onPageCreated have no effect

### ISSUE THREAD

**Issue by zackw** [ariya/phantomjs#12547]
If a page calls `window.open`, the only opportunity you get to mess with `page.settings` for the new page is the `onPageCreated` hook on the parent page.  So that had better work, but right now, it doesn't.

The thing that I _know_ doesn't work is, requests issued by the child page have the default UA string even if you override `page.settings.userAgent` in `onPageCreated`.  I haven't dug very deeply into this yet, but I have the impression it is a general problem with page settings.

Test case:

```
/* When a page calls window.open, the onPageCreated hook is called on
 * its parent page.  This is the only opportunity we get to adjust the
 * child page's settings, so it had better work.
 */

var assert = require('../assert');

function escapeHTML(s) {
    return s.replace(/&/g, '&amp;')
        .replace(/"/g, '&quot;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}


var server = require('webserver').create();
server.listen(12345, function (request, response) {
    var ua = request.headers["User-Agent"];
    switch (request.url) {
        case "/":
        response.write("<!doctype html>"+
                       "<body>"+
                       "<p>" + escapeHTML(ua) + "</p>" +
                       "<script>"+
                       "window.onload = function () {"+
                       "  window.open('/win');"+
                       "};"+
                       "</script>"+
                       "</body>");
        break;

        case "/win":
        response.write("<!doctype html>"+
                       "<body>"+
                       "<p>" + escapeHTML(ua) + "</p>" +
                       "</body>");
        break;

        default:
        response.statusCode = 404;
        response.write("<!doctype html>" +
                       "<h1>Not Found</h1>" +
                       "<p>" + escapeHTML(request.url) + "</p>");
        break;
    }
    response.close();
});

const desired_UA =
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/538.1+ ' +
    '(KHTML, like Gecko) Version/6.0.5 Safari/536.30.1';

var loads_pending = 2;
function p_onLoadFinished (status) {
    assert.strictEqual(status, 'success');
    assert.strictEqual(this.plainText, desired_UA);
    if (!--loads_pending) {
        server.close();
        phantom.exit(0);
    }
}

function p_onPageCreated (page) {
    page.settings.userAgent = desired_UA;
    page.onPageCreated = p_onPageCreated;
    page.onLoadFinished = p_onLoadFinished.bind(page);
}

var parentPage = require('webpage').create();
p_onPageCreated(parentPage);
parentPage.open("http://localhost:12345/");
```

(Note that right now this test case exits successfully despite printing an AssertionError.  I'm about to file another issue about that.)

**Comment by ChairmanMeow** [comment]
Have you solved this issue zack?

**Comment by zackw** [comment]
@ChairmanMeow It's on my list of things what need fixin', and I even know how to do it, but it involves fairly major surgery and I haven't had the time.

**Comment by zackw** [comment]
(The cause is that nothing is actually looking at `page.settings` for adjustments on an ongoing basis; it's only read when you do a manual `page.open`.)

**Comment by ChairmanMeow** [comment]
Ya for people having this same issue, a temporary bandaid is to change: 
page.customHeaders = { 'User-Agent': 'someagent' }; which overwrites the user-agent.
From #12169

**Comment by zackw** [comment]
@iradul Will your pull request for #13659 also fix this issue, do you think?

**Comment by iradul** [comment]
Yes, running your example script above using fix from my pull request results in:
```2 tests passed.```

**Comment by zackw** [comment]
@iradul Excellent.
