### ISSUE TITLE
Two calls to exit() in a row: which status should win?

### ISSUE THREAD

**Issue by zackw** [ariya/phantomjs#12548]
Consider

```
var page = require('webpage').create();
page.open("about:blank", function () {
    phantom.exit(0);
    phantom.exit(1);
});
```

In this situation, Phantom does not exit immediately; it waits for the hook to return first.  (This in itself has tripped me up a couple of times, but I expect it's hard to change.) 

What should the exit status be?  Right now, it's 1.  I'd argue that it should be 0, because of the test case I just posted in issue #12547.  That test case is currently failing, but it exits succcessfully, because the `phantom.exit(0)` call in `p_onLoadFinished` -- which has to be there, else the test case wouldn't terminate if it _passed_ -- overrides the `phantom.exit(1)` call in `assert.js:showError`, which is definitely not what we want.

**Comment by zackw** [comment]
Commit zackw/phantomjs@437da9a56aa19a2b8697ea1f92667c75a587a5de applies a big hammer to this problem: `Phantom::doExit` calls `::exit`, and therefore does not return to Javascript.  I think this is the abstract Right Thing but I'm worried it might break things like caching and localStorage.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://mcprint.rlogical.com/language.php?m06q>

 

klaus@hebsgaard.dk
