### ISSUE TITLE
PhantomJS crash

### ISSUE THREAD

**Issue by velichkin** [ariya/phantomjs#12557]
<pre>Official binary 1.9.7

Operating system: Linux
                  0.0.0 Linux 3.13.0-27-generic #50-Ubuntu SMP Thu May 15 18:06:16 UTC 2014 x86_64
CPU: amd64
     family 6 model 37 stepping 5
     4 CPUs

Crash reason:  SIGSEGV
Crash address: 0x155

Thread 0 (crashed)
 0  phantomjs + 0xc70d8b
    rbx = 0x00007f24a2202580   r12 = 0x0000000000000000
    r13 = 0x0000000000000002   r14 = 0x00007f24a22025f8
    r15 = 0x00007fff942ad230   rip = 0x0000000001070d8b
    rsp = 0x00007fff942ac9a0   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  phantomjs + 0x5949d9
    rip = 0x00000000009949da   rsp = 0x00007fff942aca00
    Found by: stack scanning
 2  phantomjs + 0x42e678
    rip = 0x000000000082e679   rsp = 0x00007fff942aca10
    Found by: stack scanning
 3  phantomjs + 0x27b196
    rip = 0x000000000067b197   rsp = 0x00007fff942aca50
    Found by: stack scanning
 4  phantomjs + 0x17e0c6f
    rip = 0x0000000001be0c70   rsp = 0x00007fff942acaa0
    Found by: stack scanning
 5  phantomjs + 0x593982
    rip = 0x0000000000993983   rsp = 0x00007fff942acaf0
    Found by: stack scanning
 6  phantomjs + 0x18efbc3
    rip = 0x0000000001cefbc4   rsp = 0x00007fff942acb30
    Found by: stack scanning
 7  phantomjs + 0x18efc27
    rip = 0x0000000001cefc28   rsp = 0x00007fff942acb40
    Found by: stack scanning
 8  phantomjs + 0x18efbe2
    rip = 0x0000000001cefbe3   rsp = 0x00007fff942acb50
    Found by: stack scanning
 9  libstdc++.so.6.0.19 + 0x5f028
    rip = 0x00007f24a5d7d029   rsp = 0x00007fff942acb60
    Found by: stack scanning
10  phantomjs + 0xb5e498
    rip = 0x0000000000f5e499   rsp = 0x00007fff942acb70
    Found by: stack scanning
11  phantomjs + 0x173552f
    rip = 0x0000000001b35530   rsp = 0x00007fff942acc20
    Found by: stack scanning
12  phantomjs + 0x944d7
    rip = 0x00000000004944d8   rsp = 0x00007fff942acc30
    Found by: stack scanning
13  phantomjs + 0x1730707
    rip = 0x0000000001b30708   rsp = 0x00007fff942acc50
    Found by: stack scanning
14  phantomjs + 0x11decae
    rip = 0x00000000015decaf   rsp = 0x00007fff942acca0
    Found by: stack scanning
15  phantomjs + 0x11decae
    rip = 0x00000000015decaf   rsp = 0x00007fff942accd0
    Found by: stack scanning
16  phantomjs + 0x11e793a
    rip = 0x00000000015e793b   rsp = 0x00007fff942acd00
    Found by: stack scanning
17  phantomjs + 0x11e793a
    rip = 0x00000000015e793b   rsp = 0x00007fff942acd20
    Found by: stack scanning
18  phantomjs + 0x129343
    rip = 0x0000000000529344   rsp = 0x00007fff942acda0
    Found by: stack scanning
19  phantomjs + 0x1294d1
    rip = 0x00000000005294d2   rsp = 0x00007fff942ace90
    Found by: stack scanning
20  phantomjs + 0x14de9b
    rip = 0x000000000054de9c   rsp = 0x00007fff942aced0
    Found by: stack scanning
21  phantomjs + 0x190025d
    rip = 0x0000000001d0025e   rsp = 0x00007fff942acef0
    Found by: stack scanning
22  phantomjs + 0x7fcb2
    rip = 0x000000000047fcb3   rsp = 0x00007fff942acf10
    Found by: stack scanning

Thread 1
 0  libc-2.19.so + 0xc1d7d
    rbx = 0x00007f24a3fddc80   r12 = 0x00007f24a3fddd00
    r13 = 0x00007f24a1f5c920   r14 = 0x0000000002a7e1a0
    r15 = 0x0000000002a7e170   rip = 0x00007f24a54fdd7d
    rsp = 0x00007f24a3fddc60   rbp = 0x00000000ffffffff
    Found by: given as instruction pointer in context
 1  libc-2.19.so + 0xc1c13
    rip = 0x00007f24a54fdc14   rsp = 0x00007f24a3fddc70
    Found by: stack scanning
 2  phantomjs + 0x2e2c
    rip = 0x0000000000402e2d   rsp = 0x00007f24a3fddd10
    Found by: stack scanning
 3  ld-2.19.so + 0xa990
    rip = 0x00007f24a6b35991   rsp = 0x00007f24a3fddd20
    Found by: stack scanning
 4  libc-2.19.so + 0xe89f
    rip = 0x00007f24a544a8a0   rsp = 0x00007f24a3fddd28
    Found by: stack scanning
 5  phantomjs + 0x18b5c6f
    rip = 0x0000000001cb5c70   rsp = 0x00007f24a3fddd88
    Found by: stack scanning
 6  libc-2.19.so + 0x3d27
    rip = 0x00007f24a543fd28   rsp = 0x00007f24a3fddd98
    Found by: stack scanning
 7  libc-2.19.so + 0xe89f
    rip = 0x00007f24a544a8a0   rsp = 0x00007f24a3fddda8
    Found by: stack scanning
 8  phantomjs + 0x173d7
    rip = 0x00000000004173d8   rsp = 0x00007f24a3fdddb0
    Found by: stack scanning
 9  phantomjs + 0x2e2c
    rip = 0x0000000000402e2d   rsp = 0x00007f24a3fddde0
    Found by: stack scanning
10  libc-2.19.so + 0x10d77
    rip = 0x00007f24a544cd78   rsp = 0x00007f24a3fddde8
    Found by: stack scanning
11  phantomjs + 0x24c7
    rip = 0x00000000004024c8   rsp = 0x00007f24a3fdddf0
    Found by: stack scanning
12  libpthread-2.19.so + 0x1033f
    rip = 0x00007f24a6032340   rsp = 0x00007f24a3fdde18
    Found by: stack scanning
13  libpthread-2.19.so + 0xc4a3
    rip = 0x00007f24a602e4a4   rsp = 0x00007f24a3fdde20
    Found by: stack scanning
14  phantomjs + 0xdda2d
    rip = 0x00000000004dda2e   rsp = 0x00007f24a3fdde50
    Found by: stack scanning
15  phantomjs + 0xddc98
    rip = 0x00000000004ddc99   rsp = 0x00007f24a3fdded0
    Found by: stack scanning
16  libpthread-2.19.so + 0x8181
    rip = 0x00007f24a602a182   rsp = 0x00007f24a3fddee0
    Found by: stack scanning
17  libc-2.19.so + 0xfb30c
    rip = 0x00007f24a553730d   rsp = 0x00007f24a3fddf80
    Found by: stack scanning

Thread 2
 0  libc-2.19.so + 0xf2c33
    rbx = 0x0000000000000000   r12 = 0x00007f24a37dcdb0
    r13 = 0x0000000000000008   r14 = 0x00007f249c000a98
    r15 = 0x00007f249c000d30   rip = 0x00007f24a552ec33
    rsp = 0x00007f24a37dcb80   rbp = 0x00007f249c0008e0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906326
    rip = 0x0000000001d06327   rsp = 0x00007f24a37dcb90
    Found by: stack scanning
 2  ld-2.19.so + 0x9e9b
    rip = 0x00007f24a6b34e9c   rsp = 0x00007f24a37dcbe0
    Found by: stack scanning
 3  phantomjs + 0x19075e6
    rip = 0x0000000001d075e7   rsp = 0x00007f24a37dcc20
    Found by: stack scanning
 4  phantomjs + 0x18f6ab6
    rip = 0x0000000001cf6ab7   rsp = 0x00007f24a37dcc40
    Found by: stack scanning
 5  phantomjs + 0x18019c2
    rip = 0x0000000001c019c3   rsp = 0x00007f24a37dcc50
    Found by: stack scanning
 6  libc-2.19.so + 0x1097bc
    rip = 0x00007f24a55457bd   rsp = 0x00007f24a37dcc90
    Found by: stack scanning
 7  phantomjs + 0x1840b73
    rip = 0x0000000001c40b74   rsp = 0x00007f24a37dcca0
    Found by: stack scanning
 8  phantomjs + 0x1840a78
    rip = 0x0000000001c40a79   rsp = 0x00007f24a37dcce0
    Found by: stack scanning
 9  phantomjs + 0x1906fa5
    rip = 0x0000000001d06fa6   rsp = 0x00007f24a37dccf0
    Found by: stack scanning
10  phantomjs + 0x1908091
    rip = 0x0000000001d08092   rsp = 0x00007f24a37dcd60
    Found by: stack scanning
11  phantomjs + 0x18dd4b4
    rip = 0x0000000001cdd4b5   rsp = 0x00007f24a37dcdb0
    Found by: stack scanning
12  phantomjs + 0x18ddca8
    rip = 0x0000000001cddca9   rsp = 0x00007f24a37dcdc0
    Found by: stack scanning
13  phantomjs + 0x18dd917
    rip = 0x0000000001cdd918   rsp = 0x00007f24a37dcde0
    Found by: stack scanning
14  phantomjs + 0x17dfdf5
    rip = 0x0000000001bdfdf6   rsp = 0x00007f24a37dce40
    Found by: stack scanning
15  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f24a37dce90
    Found by: stack scanning
16  libpthread-2.19.so + 0x8181
    rip = 0x00007f24a602a182   rsp = 0x00007f24a37dcee0
    Found by: stack scanning
17  libc-2.19.so + 0xfb30c
    rip = 0x00007f24a553730d   rsp = 0x00007f24a37dcf80
    Found by: stack scanning

Thread 3
 0  libc-2.19.so + 0xf2c33
    rbx = 0x00007f24a1e92d60   r12 = 0x0000000000015e72
    r13 = 0x000000000000000a   r14 = 0x00007f2454000a98
    r15 = 0x00007f2454000d30   rip = 0x00007f24a552ec33
    rsp = 0x00007f24a1e92b80   rbp = 0x0000000000019db2
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906227
    rip = 0x0000000001d06228   rsp = 0x00007f24a1e92b90
    Found by: stack scanning
 2  phantomjs + 0x19075e6
    rip = 0x0000000001d075e7   rsp = 0x00007f24a1e92c20
    Found by: stack scanning
 3  phantomjs + 0x18f6ab6
    rip = 0x0000000001cf6ab7   rsp = 0x00007f24a1e92c40
    Found by: stack scanning
 4  phantomjs + 0x18019f3
    rip = 0x0000000001c019f4   rsp = 0x00007f24a1e92c50
    Found by: stack scanning
 5  libc-2.19.so + 0x1097bc
    rip = 0x00007f24a55457bd   rsp = 0x00007f24a1e92c90
    Found by: stack scanning
 6  phantomjs + 0x1840b73
    rip = 0x0000000001c40b74   rsp = 0x00007f24a1e92ca0
    Found by: stack scanning
 7  phantomjs + 0x1907ced
    rip = 0x0000000001d07cee   rsp = 0x00007f24a1e92cd0
    Found by: stack scanning
 8  phantomjs + 0x1840a78
    rip = 0x0000000001c40a79   rsp = 0x00007f24a1e92ce0
    Found by: stack scanning
 9  phantomjs + 0x1906fa5
    rip = 0x0000000001d06fa6   rsp = 0x00007f24a1e92cf0
    Found by: stack scanning
10  phantomjs + 0x1908091
    rip = 0x0000000001d08092   rsp = 0x00007f24a1e92d60
    Found by: stack scanning
11  phantomjs + 0x18dd4b4
    rip = 0x0000000001cdd4b5   rsp = 0x00007f24a1e92db0
    Found by: stack scanning
12  phantomjs + 0x18ddca8
    rip = 0x0000000001cddca9   rsp = 0x00007f24a1e92dc0
    Found by: stack scanning
13  phantomjs + 0x18dd917
    rip = 0x0000000001cdd918   rsp = 0x00007f24a1e92de0
    Found by: stack scanning
14  phantomjs + 0x17dfdf5
    rip = 0x0000000001bdfdf6   rsp = 0x00007f24a1e92e40
    Found by: stack scanning
15  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f24a1e92e90
    Found by: stack scanning
16  libpthread-2.19.so + 0x8181
    rip = 0x00007f24a602a182   rsp = 0x00007f24a1e92ee0
    Found by: stack scanning
17  libc-2.19.so + 0xfb30c
    rip = 0x00007f24a553730d   rsp = 0x00007f24a1e92f80
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x0268dfff  phantomjs  ???  (main)
0x7f24a1665000 - 0x7f24a1676fff  n019043l.pfb  ???
0x7f24a3fdf000 - 0x7f24a4231fff  libssl.so.0.9.8  ???
0x7f24a4232000 - 0x7f24a45bbfff  libcrypto.so.0.9.8  ???
0x7f24a45bf000 - 0x7f24a4dd2fff  locale-archive  ???
0x7f24a4dd3000 - 0x7f24a4ffcfff  libexpat.so.1.6.0  ???
0x7f24a4ffd000 - 0x7f24a5222fff  libpng12.so.0.50.0  ???
0x7f24a5223000 - 0x7f24a543bfff  libz.so.1.2.8  ???
0x7f24a543c000 - 0x7f24a57fcfff  libc-2.19.so  ???
0x7f24a5802000 - 0x7f24a5a17fff  libgcc_s.so.1  ???
0x7f24a5a18000 - 0x7f24a5d1dfff  libm-2.19.so  ???
0x7f24a5d1e000 - 0x7f24a600cfff  libstdc++.so.6.0.19  ???
0x7f24a6022000 - 0x7f24a623bfff  libpthread-2.19.so  ???
0x7f24a6240000 - 0x7f24a6447fff  librt-2.19.so  ???
0x7f24a6448000 - 0x7f24a664bfff  libdl-2.19.so  ???
0x7f24a664c000 - 0x7f24a6887fff  libfontconfig.so.1.8.0  ???
0x7f24a6888000 - 0x7f24a6b2afff  libfreetype.so.6.11.1  ???
0x7f24a6b2b000 - 0x7f24a6b4dfff  ld-2.19.so  ???
0x7f24a6c7e000 - 0x7f24a6c84fff  gconv-modules.cache  ???
0x7f24a6c85000 - 0x7f24a6cb3fff  libc.mo  ???
0x7f24a6cb4000 - 0x7f24a6cb4fff  c05880de57d1f5e948fdfacc138775d9-le64.cache-4  ???
0x7f24a6cb5000 - 0x7f24a6cbffff  945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-4  ???
0x7f24a6cc0000 - 0x7f24a6cc5fff  2cd17615ca594fa2959ae173292e504c-le64.cache-4  ???
0x7f24a6cc6000 - 0x7f24a6cc6fff  e7071f4a29fa870f4323321c154eba04-le64.cache-4  ???
0x7f24a6cc7000 - 0x7f24a6cc7fff  0d8c3b2ac0904cb8a57a757ad11a4a08-le64.cache-4  ???
0x7f24a6cc8000 - 0x7f24a6ccefff  a755afe4a08bf5b97852ceb7400b47bc-le64.cache-4  ???
0x7f24a6ccf000 - 0x7f24a6cd7fff  6d41288fd70b0be22e8c3a91e032eec0-le64.cache-4  ???
0x7f24a6cd8000 - 0x7f24a6cebfff  04aabc0a78ac019cf9454389977116d2-le64.cache-4  ???
0x7f24a6cec000 - 0x7f24a6cecfff  1ac9eb803944fde146138c791f5cc56a-le64.cache-4  ???
0x7f24a6ced000 - 0x7f24a6cf0fff  385c0604a188198f04d133e54aba7fe7-le64.cache-4  ???
0x7f24a6cf1000 - 0x7f24a6cf1fff  dc05db6664285cc2f12bf69c139ae4c3-le64.cache-4  ???
0x7f24a6cf2000 - 0x7f24a6cf3fff  767a8244fc0220cfb567a839d0392e0b-le64.cache-4  ???
0x7f24a6cf4000 - 0x7f24a6cf4fff  4794a0821666d79190d59a36cb4f44b5-le64.cache-4  ???
0x7f24a6cf5000 - 0x7f24a6cf9fff  8801497958630a81b71ace7c5f9b32a8-le64.cache-4  ???
0x7f24a6cfa000 - 0x7f24a6d00fff  3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-4  ???
0x7f24a6d01000 - 0x7f24a6d01fff  56cf4f4769d0f4abc89a4895d7bd3ae1-le64.cache-4  ???
0x7f24a6d02000 - 0x7f24a6d07fff  b47c4e1ecd0709278f4910c18777a504-le64.cache-4  ???
0x7f24a6d08000 - 0x7f24a6d1afff  d52a8644073d54c13679302ca1180695-le64.cache-4  ???
0x7f24a6d1b000 - 0x7f24a6d23fff  3f7329c5293ffd510edef78f73874cfd-le64.cache-4  ???
0x7f24a6d2d000 - 0x7f24a6d2dfff  b9d506c9ac06c20b433354fa67a72993-le64.cache-4  ???
0x7f24a6d2e000 - 0x7f24a6d38fff  d589a48862398ed80a3d6066f4f56f4c-le64.cache-4  ???
0x7f24a6d39000 - 0x7f24a6d39fff  0c9eb80ebd1c36541ebe2852d3bb0c49-le64.cache-4  ???
0x7f24a6d3a000 - 0x7f24a6d46fff  e13b20fdb08344e0e664864cc2ede53d-le64.cache-4  ???
0x7f24a6d47000 - 0x7f24a6d4afff  7ef2298fde41cc6eeb7af42e48b7d293-le64.cache-4  ???
0x7fff942ff000 - 0x7fff94300fff  linux-gate.so  ???</pre>

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
