### ISSUE TITLE
Phantomjs has crashed while trying to open "https://www.hertz.com"

### ISSUE THREAD

**Issue by mrfatboy** [ariya/phantomjs#12559]
This is the first time I have run into this error after scraping many websites.  I have attached the link to the dmp file below. 

One interesting thing to note is I can open the url using casperjs just fine.

I'm on windows 7x64.  Phantom 1.9, CasperJS latest hipstered version is 1.1-beta3,

http://www.megafileupload.com/en/file/563787/32257bab-5857-4aed-b152-e5630cea1f29-dmp.html

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
