### ISSUE TITLE
Angular UI-VIEW ( UI-ROUTER ) NOT loaded

### ISSUE THREAD

**Issue by l3r** [ariya/phantomjs#12568]
Problem of loading nested view (UI-VIEW)  e.g http://angular-ui.github.io/ui-router/sample/#/contacts/42/item/b
but rendered like that:
<a href="http://imgur.com/5NvG6pK"><img src="http://i.imgur.com/5NvG6pK.png?1" title="Hosted by imgur.com" /></a>
or simply gray screen (no content)
in browser works fine...

**Comment by abuechler** [comment]
Is there any workaround for this?

**Comment by codyrigney92** [comment]
+1

**Comment by iradul** [comment]
Workaround is to use PhantomJS 2.0
