### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by mu3** [ariya/phantomjs#12564]
I installed PhantomJS (v1.9.7) and CasperJS (v1.1b3) via npm.
Executing from CLI/Cron makes no problems.
But when I run the same php script from browser:

    echo shell_exec('casperjs --version');

I get this output:

    PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/4c9bf929-e88b-9040-2eab2104-3226ba50.dmp

Here's dump file http://cl.ly/XXCW
P.S. Please fix link in an error message https://github.com/ariya/phantomjs/wiki/Crash-Reporting

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
