### ISSUE TITLE
Segfault (with stack trace!)

### ISSUE THREAD

**Issue by heavi5ide** [ariya/phantomjs#12576]
phantom is segfaulting for us when phantom.exit() is called in some cases.

Full stacktrace here: http://pastebin.com/9LaXAHqv

Running phantom 1.9.7 in an Ubuntu Virtualbox VM on an OS X host:
```
Operating system: Linux
                  0.0.0 Linux 3.8.0-39-generic #57~precise1-Ubuntu SMP Tue Apr 1 20:04:50 UTC 2014 x86_64
CPU: amd64
     family 6 model 70 stepping 1
     1 CPU

Crash reason:  SIGSEGV
Crash address: 0x0
```

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
