### ISSUE TITLE
phantomjs crashes occasionally 

### ISSUE THREAD

**Issue by ddamyanov** [ariya/phantomjs#12574]
We are running prerender with phantomjs. Every now and then the phantom crashes with the error:

phantom stderr: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/0cfadeb7-f0b8-5209-667b763f-1c7a96b0.dmp

2014-09-16T16:44:13.904Z phantom crashed, restarting...
2014-09-16T16:44:13.906Z starting phantom
2014-09-16T16:44:14.562Z started phantom
2014-09-16T16:44:21.492Z PhantomJS restarted in the middle of this request. Aborting...

The crush dump can be downloaded from https://github.com/ddamyanov/ddd

Thank you.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
