### ISSUE TITLE
File uploading busted

### ISSUE THREAD

**Issue by Olofguard** [ariya/phantomjs#12575]
I have encountered an issue while uploading files in my acceptance tests. Though I spent the better part of day digging through codeception, phantomjs, and ghostdriver trying to resolve this issue, I haven't come any closer to getting this resolved. Any help here would be greatly appreciated.  
### Environment Details
- Codeception 2.0.6
- Phantomjs    1.9.7
- Selenium Standalone 2.42.2
### The Issue

In short, Phantomjs is throwing an error `Invalid Command Method`. It appears this error is being thrown within ghostdriver, specifically in ghost driver's request_handler.js on line 105. It's as though it can't read the json from the curl request initiated by the facebook webdriver's `HttpCommandExecutor` class. This curl request should populate the form field for uploading the file, but instead the curl request fails after getting a status code of 405 in return. Below is an example of the curl request sent by the `HttpCommandExecutor`.

``` json
{
  "url": "http://127.0.0.1:4444/wd/hub/session/bf4a6d70-3e71-11e4-858a-5fddebdf4faa/file",
  "content_type": "text/plain",
  "http_code": 405,
  "header_size": 99,
  "request_size": 505,
  "filetime": -1,
  "ssl_verify_result": 0,
  "redirect_count": 0,
  "total_time": 0.001383,
  "namelookup_time": 0.000016,
  "connect_time": 0.00012,
  "pretransfer_time": 0.00015,
  "size_upload": 315,
  "size_download": 844,
  "speed_download": 610267,
  "speed_upload": 227765,
  "download_content_length": 844,
  "upload_content_length": 315,
  "starttransfer_time": 0.001376,
  "redirect_time": 0,
  "certinfo": [],
  "primary_ip": "127.0.0.1",
  "primary_port": 4444,
  "local_ip": "127.0.0.1",
  "local_port": 49959,
  "redirect_url": ""
}
```
## Further details

I'm using codeception to `attachFile` to the form. This ultimately calls `upload()` on the `RemoteWebElement` class from the facebook web driver using the local file path. Responsibility is then  handed off to the `HttpCommandExecutor` through an execute call `execute('sendFile', $params)` , where a POST curl request should be sent to attach the file to the form. From my understanding this is where phantomjs and ghostdriver take over. 

I started to dig into the phantomjs/ghostdriver source, however, to me it seemed I had to rebuild phantomjs from source in order to test changes i make. I may be wrong (javascript is not my specialty), but I don't have the time to build from source over and over while debugging this issue. 

It is important to note that, I can switch off phantomjs, go back to firefox as the browser for my acceptance tests, and everything works flawlessly.

**Comment by jesg** [comment]
fwiw the file upload api was added in phantomjs 2.0.0.  it was not available in phantomjs 1.9.7.
