### ISSUE TITLE
Number.toLocaleString() doesn't apply appropriate formatting

### ISSUE THREAD

**Issue by vecmaven** [ariya/phantomjs#12581]
In all modern web browsers, the below snippet will output a formatted representation (with comma separation) of the number as shown below.

Modern Web Browser
var myFloat = 1234567890000.0;
console.log(myFloat.toLocaleString("en-GB"));
> 1,234,567,890,000 

PhantomJS however doesn't seem to apply the en-GB locale formatting correctly:

PhantomJS 
var myFloat = 1234567890000.0;
console.log(myFloat.toLocaleString("en-GB"));
> 1234567890000

**Comment by skawaguchi** [comment]
+1

**Comment by zaiquiri** [comment]
+1

**Comment by fkalis** [comment]
+1

**Comment by tatablack** [comment]
Seems like it's not going to be implemented. See https://github.com/ariya/phantomjs/issues/12327

**Comment by mogmi** [comment]
+1

**Comment by mdix** [comment]
+1

**Comment by vargavince91** [comment]
+1

**Comment by oller** [comment]
+1

Likewise for `Date` objects...

```js
var objDate = new Date();
var locale = 'en-gb';
var month = objDate.toLocaleString(locale, {month: 'long'});
```

**Comment by torsday** [comment]
+1

**Comment by sebdiem** [comment]
+1

**Comment by KhodeN** [comment]
+1

**Comment by prabhath** [comment]
+1

**Comment by jvmakine** [comment]
+1

**Comment by QualifiedSuccess** [comment]
Any reason why this wont be resolved?

**Comment by zackw** [comment]
Qt/Webkit implements Number.prototype.toLocaleString as identical to Number.prototype.toString.  It appears that the *very latest* development sources of Webkit are changing this (see e.g. https://bugs.webkit.org/show_bug.cgi?id=147610) but those changes will take some time to appear in Qt/Webkit.

Internationalized number formatting is a sufficiently large Twinkie that we do not want to carry around patches for it.

Sorry.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://kuyubasifidanligi.com/consist.php?1co3d>

 

klaus@hebsgaard.dk

**Comment by Mydeen-SN** [comment]
+1
