### ISSUE TITLE
Violación de segmento (core dumped) when i execute phantomjs

### ISSUE THREAD

**Issue by 50l3r** [ariya/phantomjs#12582]
Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.

1.9.7

What steps will reproduce the problem?
1. /home/www/empresa/visitik/screener/bin/phantomjs /home/www/empresa/visitik/screener/jobs/ejemplo.com123123123.js

What is the expected output? What do you see instead?
Violación de segmento (core dumped)

Which operating system are you using?

Ubuntu 13.10 (GNU/Linux 3.10.23-xxxx-std-ipv6-64 x86_64)

Did you use binary PhantomJS or did you compile it from source?

binary

Please provide any additional information below.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
