### ISSUE TITLE
textContent or innerText of comment nodes doesn't work

### ISSUE THREAD

**Issue by ryanstout** [ariya/phantomjs#12593]
First great work on phantom.

In most browsers, you can read or change the content of a comment node with:

``` javascript
node.textContent
node.textContent = 'new text'
```

or in IE ----

``` javascript
node.innerText
node.innerText = 'new text'
```

It looks like phantom doesn't support either.

I made a sample project at https://github.com/ryanstout/phantomjstextcontentbug

Thanks!

**Comment by iyyappan13391** [comment]
Yes,The phantom browser not supporting the textContent and innerText of javascript property.

Anybody knows answer of this..

Thanks!

**Comment by crookedneighbor** [comment]
I don't think this is the case any more. I am able to use `textContent` without issue.
