### ISSUE TITLE
PhantomJs set header margin to 0 when rendering pdf

### ISSUE THREAD

**Issue by Stofkn** [ariya/phantomjs#12597]
Hi

I'm using Node.js and the module phridge (version 1.0.3) to render a pdf with PhantomJs.

I want to render a pdf without any margins in the header and footer. For the moment I only found a hack to remove the left and right margin, by means of a negative left and right margin.
How can I remove the top and bottom margin of the header and footer?
It seems that the style is not applied to the header and footer.

I can't find any more information in the documentation https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage#webpage-paperSize.

I created a question on StackOverflow with more details.
http://stackoverflow.com/questions/25996487/phantomjs-set-header-margin-to-0-when-rendering-pdf

All suggestions are welcome.

**Comment by pofider** [comment]
Same for me. It seems that the header top margin even grows with the header height. In other words I get 2cm gap in the top of the pdf when the header's height is 5cm.  (can be observed [here](https://playground.jsreport.net/#playground/v3rraMiDC/3))

**Comment by liwonder** [comment]
Hi @pofider @Stofkn, 2 years passed, have you guys got the solution for this issue?

**Comment by Stofkn** [comment]
@liwonder Good questions. I don't know what's the status. I gave up and started using pdfkit, because I had issues rendering the header and footer on different platforms.

Issue on Stackoverflow: http://stackoverflow.com/questions/25996487/phantomjs-set-header-margin-to-0-when-rendering-pdf/28527652#28527652
