### ISSUE TITLE
canvas2d : context.setLineDash() undefined

### ISSUE THREAD

**Issue by maxkfranz** [ariya/phantomjs#12613]
It seems as though `context.setLineDash()` is not implemented.  Are you using an outdated version of Webkit or are there issues with HTML5 canvas?

e.g.:

(1) Check out [cytoscape.js](https://github.com/cytoscape/cytoscape.js)

(2) In the `documentation` directory, run 

```
phantomjs screencapture.js http://jsbin.com/suteci/latest test.png 5000 500x500
```

(3) Error as follows:

```
TypeError: 'undefined' is not a function (evaluating 's.setLineDash([])')

  http://cytoscape.github.io/cytoscape.js/api/cytoscape.js-latest/cytoscape.min.js:22
  http://cytoscape.github.io/cytoscape.js/api/cytoscape.js-latest/cytoscape.min.js:22
  http://cytoscape.github.io/cytoscape.js/api/cytoscape.js-latest/cytoscape.min.js:22 in r
  http://cytoscape.github.io/cytoscape.js/api/cytoscape.js-latest/cytoscape.min.js:22 in r
```

**Comment by WebDevTmas** [comment]
We have the same error over here in version 1.9.8
As far as I know I can't upgrade to 2.* for linux distribution?

**Comment by airdrummingfool** [comment]
This may be due to QT not supporting `context.setLineDash()`. `wkhtmltopdf` just merged a PR (https://github.com/wkhtmltopdf/qt/pull/31) to their fork of QT in order to fix this - perhaps similar changes could be merged into https://github.com/Vitallium/qtwebkit in order to fix it for PhantomJS?

**Comment by FlyingPumba** [comment]
Same problem here with version 1.9.8. Is this fixed in newer versions ?
