### ISSUE TITLE
Crash in 1.9.7 + Qt 5.2.1 + Ubutu 14.04 i686

### ISSUE THREAD

**Issue by johnvoloski** [ariya/phantomjs#12612]
Operating system: Linux
                  0.0.0 Linux 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:01 UTC 2014 i686
CPU: x86
     GenuineIntel family 6 model 42 stepping 7
     4 CPUs

Crash reason:  SIGSEGV
Crash address: 0x0

Thread 0 (crashed)
 0  phantomjs + 0x1ad3203
    eip = 0x09b1b203   esp = 0xbfb530f0   ebp = 0xbfb53128   ebx = 0x0a4f62bc
    esi = 0xbfb531a0   edi = 0xbfb532e0   eax = 0x00000000   ecx = 0x0a412ca0
    edx = 0x0af8ab18   efl = 0x00010246
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1ada8bf
    eip = 0x09b228c0   esp = 0xbfb53130   ebp = 0xbfb53338
    Found by: previous frame's frame pointer
 2  phantomjs + 0x1341b5f
    eip = 0x09389b60   esp = 0xbfb53340   ebp = 0xbfb536f8
    Found by: previous frame's frame pointer
 3  phantomjs + 0x1ad9bc7
    eip = 0x09b21bc8   esp = 0xbfb53700   ebp = 0xbfb53748
    Found by: previous frame's frame pointer
 4  phantomjs + 0xc863
    eip = 0x08054864   esp = 0xbfb53750   ebp = 0xbfb537a8
    Found by: previous frame's frame pointer
 5  phantomjs + 0xcefc
    eip = 0x08054efd   esp = 0xbfb537b0   ebp = 0xbfb537d8
    Found by: previous frame's frame pointer
 6  phantomjs + 0xcfce
    eip = 0x08054fcf   esp = 0xbfb537e0   ebp = 0xbfb53808
    Found by: previous frame's frame pointer
 7  phantomjs + 0x1ab7e4a
    eip = 0x09affe4b   esp = 0xbfb53810   ebp = 0xbfb53828
    Found by: previous frame's frame pointer
 8  phantomjs + 0x15f907
    eip = 0x081a7908   esp = 0xbfb53830   ebp = 0xbfb54288
    Found by: previous frame's frame pointer
 9  phantomjs + 0xbefcd3
    eip = 0x08c37cd4   esp = 0xbfb54290   ebp = 0xbfb54308
    Found by: previous frame's frame pointer
10  0xb4da826f
    eip = 0xb4da8270   esp = 0xbfb54310   ebp = 0xbfb54358
    Found by: previous frame's frame pointer
11  phantomjs + 0xbbb9a4
    eip = 0x08c039a5   esp = 0xbfb54360   ebp = 0xbfb54458
    Found by: previous frame's frame pointer
12  phantomjs + 0xc0a56b
    eip = 0x08c5256c   esp = 0xbfb54460   ebp = 0xbfb544a8
    Found by: previous frame's frame pointer
13  phantomjs + 0xcaf501
    eip = 0x08cf7502   esp = 0xbfb544b0   ebp = 0xbfb546b8
    Found by: previous frame's frame pointer
14  phantomjs + 0x250e56
    eip = 0x08298e57   esp = 0xbfb546c0   ebp = 0xbfb54718
    Found by: previous frame's frame pointer
15  phantomjs + 0x25207b
    eip = 0x0829a07c   esp = 0xbfb54720   ebp = 0xbfb54748
    Found by: previous frame's frame pointer
16  phantomjs + 0x4ce17b
    eip = 0x0851617c   esp = 0xbfb54750   ebp = 0xbfb547a8
    Found by: previous frame's frame pointer
17  phantomjs + 0x4ce2f6
    eip = 0x085162f7   esp = 0xbfb547b0   ebp = 0xbfb547e8
    Found by: previous frame's frame pointer
18  phantomjs + 0x4d4ebe
    eip = 0x0851cebf   esp = 0xbfb547f0   ebp = 0xbfb54878
    Found by: previous frame's frame pointer
19  phantomjs + 0x21e685
    eip = 0x08266686   esp = 0xbfb54880   ebp = 0xbfb548b8
    Found by: previous frame's frame pointer
20  phantomjs + 0x46a000
    eip = 0x084b2001   esp = 0xbfb548c0   ebp = 0xbfb548e8
    Found by: previous frame's frame pointer
21  phantomjs + 0x46a220
    eip = 0x084b2221   esp = 0xbfb548f0   ebp = 0xbfb548f8
    Found by: previous frame's frame pointer
22  phantomjs + 0x453305
    eip = 0x0849b306   esp = 0xbfb54900   ebp = 0xbfb54938
    Found by: previous frame's frame pointer
23  phantomjs + 0xdea521
    eip = 0x08e32522   esp = 0xbfb54940   ebp = 0xbfb54978
    Found by: previous frame's frame pointer
24  phantomjs + 0x4a5bcc
    eip = 0x084edbcd   esp = 0xbfb54980   ebp = 0xbfb549b8
    Found by: previous frame's frame pointer
25  phantomjs + 0x49b4e7
    eip = 0x084e34e8   esp = 0xbfb549c0   ebp = 0xbfb549d8
    Found by: previous frame's frame pointer
26  phantomjs + 0x703b0d
    eip = 0x0874bb0e   esp = 0xbfb549e0   ebp = 0xbfb54a88
    Found by: previous frame's frame pointer
27  phantomjs + 0x6fef5d
    eip = 0x08746f5e   esp = 0xbfb54a90   ebp = 0xbfb54ac8
    Found by: previous frame's frame pointer
28  phantomjs + 0x6ff3f4
    eip = 0x087473f5   esp = 0xbfb54ad0   ebp = 0xbfb54ae8
    Found by: previous frame's frame pointer
29  phantomjs + 0x70158a
    eip = 0x0874958b   esp = 0xbfb54af0   ebp = 0xbfb54b18
    Found by: previous frame's frame pointer
30  phantomjs + 0x1ac7566
    eip = 0x09b0f567   esp = 0xbfb54b20   ebp = 0xbfb54bf8
    Found by: previous frame's frame pointer
31  phantomjs + 0x1962176
    eip = 0x099aa177   esp = 0xbfb54c00   ebp = 0xbfb54c18
    Found by: previous frame's frame pointer
32  phantomjs + 0x18e28f2
    eip = 0x0992a8f3   esp = 0xbfb54c20   ebp = 0xbfb54cc8
    Found by: previous frame's frame pointer
33  phantomjs + 0x18c220f
    eip = 0x0990a210   esp = 0xbfb54cd0   ebp = 0xbfb54cd8
    Found by: previous frame's frame pointer
34  phantomjs + 0x18c9cd2
    eip = 0x09911cd3   esp = 0xbfb54ce0   ebp = 0xbfb54ce8
    Found by: previous frame's frame pointer
35  phantomjs + 0x1961a07
    eip = 0x099a9a08   esp = 0xbfb54cf0   ebp = 0xbfb54d68
    Found by: previous frame's frame pointer
36  phantomjs + 0x1ac2cdf
    eip = 0x09b0ace0   esp = 0xbfb54d70   ebp = 0xbfb54d88
    Found by: previous frame's frame pointer
37  phantomjs + 0x1ac39b2
    eip = 0x09b0b9b3   esp = 0xbfb54d90   ebp = 0xbfb54e98
    Found by: previous frame's frame pointer
38  phantomjs + 0x131048e
    eip = 0x0935848f   esp = 0xbfb54ea0   ebp = 0xbfb54eb8
    Found by: previous frame's frame pointer
39  phantomjs + 0x1318460
    eip = 0x09360461   esp = 0xbfb54ec0   ebp = 0xbfb55278
    Found by: previous frame's frame pointer
40  phantomjs + 0x1ab113a
    eip = 0x09af913b   esp = 0xbfb55280   ebp = 0xbfb552a8
    Found by: previous frame's frame pointer
41  phantomjs + 0x1ab1ea5
    eip = 0x09af9ea6   esp = 0xbfb552b0   ebp = 0xbfb55318
    Found by: previous frame's frame pointer
42  phantomjs + 0x1ab226c
    eip = 0x09afa26d   esp = 0xbfb55320   ebp = 0xbfb55338
    Found by: previous frame's frame pointer
43  phantomjs + 0x1375569
    eip = 0x093bd56a   esp = 0xbfb55340   ebp = 0xbfb55378
    Found by: previous frame's frame pointer
44  phantomjs + 0x1aaffcc
    eip = 0x09af7fcd   esp = 0xbfb55380   ebp = 0xbfb553a8
    Found by: previous frame's frame pointer
45  phantomjs + 0x1ab04b0
    eip = 0x09af84b1   esp = 0xbfb553b0   ebp = 0xbfb553f8
    Found by: previous frame's frame pointer
46  phantomjs + 0x1ab232c
    eip = 0x09afa32d   esp = 0xbfb55400   ebp = 0xbfb55438
    Found by: previous frame's frame pointer
47  phantomjs + 0x130fda6
    eip = 0x09357da7   esp = 0xbfb55440   ebp = 0xbfb55448
    Found by: previous frame's frame pointer
48  phantomjs + 0x259b8
    eip = 0x0806d9b9   esp = 0xbfb55450   ebp = 0xbfb55508
    Found by: previous frame's frame pointer
49  libc-2.19.so + 0x19a82
    eip = 0xb7359a83   esp = 0xbfb55510   ebp = 0x00000000
    Found by: previous frame's frame pointer
50  phantomjs + 0x1b33b1f
    eip = 0x09b7bb20   esp = 0xbfb55514   ebp = 0x00000000
    Found by: stack scanning
51  libc-2.19.so + 0x19a82
    eip = 0xb7359a83   esp = 0xbfb55520   ebp = 0x00000000
    Found by: stack scanning
52  ld-2.19.so + 0xece9
    eip = 0xb776bcea   esp = 0xbfb55530   ebp = 0x00000000
    Found by: stack scanning
53  phantomjs + 0x24ae5e7
    eip = 0x0a4f65e8   esp = 0xbfb55540   ebp = 0x00000000
    Found by: stack scanning
54  phantomjs + 0x1bff
    eip = 0x08049c00   esp = 0xbfb55544   ebp = 0x00000000
    Found by: stack scanning
55  libc-2.19.so + 0x1abfff
    eip = 0xb74ec000   esp = 0xbfb55548   ebp = 0x00000000
    Found by: stack scanning
56  phantomjs + 0x590f
    eip = 0x0804d910   esp = 0xbfb55570   ebp = 0x00000000
    Found by: stack scanning
57  ld-2.19.so + 0x144ff
    eip = 0xb7771500   esp = 0xbfb55578   ebp = 0x00000000
    Found by: stack scanning
58  libc-2.19.so + 0x19998
    eip = 0xb7359999   esp = 0xbfb5557c   ebp = 0x00000000
    Found by: stack scanning
59  ld-2.19.so + 0x20fff
    eip = 0xb777e000   esp = 0xbfb55580   ebp = 0x00000000
    Found by: stack scanning
60  phantomjs + 0x590f
    eip = 0x0804d910   esp = 0xbfb55588   ebp = 0x00000000
    Found by: stack scanning
61  phantomjs + 0x5930
    eip = 0x0804d931   esp = 0xbfb55590   ebp = 0x00000000
    Found by: stack scanning
62  phantomjs + 0x2577f
    eip = 0x0806d780   esp = 0xbfb55594   ebp = 0x00000000
    Found by: stack scanning
63  phantomjs + 0x1b33b1f
    eip = 0x09b7bb20   esp = 0xbfb555a0   ebp = 0x00000000
    Found by: stack scanning
64  phantomjs + 0x1b33b0f
    eip = 0x09b7bb10   esp = 0xbfb555a4   ebp = 0x00000000
    Found by: stack scanning
65  ld-2.19.so + 0xf17f
    eip = 0xb776c180   esp = 0xbfb555a8   ebp = 0x00000000
    Found by: stack scanning

Thread 1
 0  linux-gate.so + 0x424
    eip = 0xb775c424   esp = 0xb6e2c0e8   ebp = 0xb6e2c134   ebx = 0xb6e2c12c
    esi = 0x00000000   edi = 0xb6e2c1b4   eax = 0xfffffdfc   ecx = 0xb6e2c12c
    edx = 0xb74ec000   efl = 0x00000293
    Found by: given as instruction pointer in context

Thread 2
 0  linux-gate.so + 0x424
    eip = 0xb775c424   esp = 0xb650b04c   ebp = 0xb650b0c8   ebx = 0x00000008
    esi = 0xb5c00994   edi = 0x00000000   eax = 0xfffffdfe   ecx = 0xb5c0056c
    edx = 0xb5c00780   efl = 0x00000293
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1adbe28
    eip = 0x09b23e29   esp = 0xb650b0d0   ebp = 0xb650b0e8
    Found by: previous frame's frame pointer
 2  phantomjs + 0x1add7e6
    eip = 0x09b257e7   esp = 0xb650b0f0   ebp = 0xb650b1f8
    Found by: previous frame's frame pointer
 3  phantomjs + 0x1addc56
    eip = 0x09b25c57   esp = 0xb650b200   ebp = 0xb650b238
    Found by: previous frame's frame pointer
 4  phantomjs + 0x1aaffcc
    eip = 0x09af7fcd   esp = 0xb650b240   ebp = 0xb650b268
    Found by: previous frame's frame pointer
 5  phantomjs + 0x1ab04b0
    eip = 0x09af84b1   esp = 0xb650b270   ebp = 0xb650b2b8
    Found by: previous frame's frame pointer
 6  phantomjs + 0x199fb69
    eip = 0x099e7b6a   esp = 0xb650b2c0   ebp = 0xb650b308
    Found by: previous frame's frame pointer
 7  phantomjs + 0x199fcb0
    eip = 0x099e7cb1   esp = 0xb650b310   ebp = 0xb650b318
    Found by: previous frame's frame pointer
 8  phantomjs + 0x19a2d8f
    eip = 0x099ead90   esp = 0xb650b320   ebp = 0xb650b358
    Found by: previous frame's frame pointer
 9  libpthread-2.19.so + 0x6f6f
    eip = 0xb7643f70   esp = 0xb650b360   ebp = 0xb650b428
    Found by: previous frame's frame pointer
10  libc-2.19.so + 0xec4cd
    eip = 0xb742c4ce   esp = 0xb650b430   ebp = 0x00000000
    Found by: previous frame's frame pointer

Thread 3
 0  linux-gate.so + 0x424
    eip = 0xb775c424   esp = 0xb41ff24c   ebp = 0xffffffff   ebx = 0xb4203234
    esi = 0xb41ff2ac   edi = 0xb4203218   eax = 0xfffffdfc   ecx = 0x00000189
    edx = 0x00000001   efl = 0x00000282
    Found by: given as instruction pointer in context
 1  libpthread-2.19.so + 0xb12c
    eip = 0xb764812d   esp = 0xb41ff25c   ebp = 0xffffffff
    Found by: stack scanning
 2  libpthread-2.19.so + 0xb03a
    eip = 0xb764803b   esp = 0xb41ff27c   ebp = 0xffffffff
    Found by: stack scanning
 3  phantomjs + 0x24ae2bb
    eip = 0x0a4f62bc   esp = 0xb41ff280   ebp = 0xffffffff
    Found by: stack scanning
 4  phantomjs + 0x19a3b03
    eip = 0x099ebb04   esp = 0xb41ff290   ebp = 0xffffffff
    Found by: stack scanning
 5  phantomjs + 0x24ae2bb
    eip = 0x0a4f62bc   esp = 0xb41ff2c0   ebp = 0xffffffff
    Found by: stack scanning
 6  phantomjs + 0x1996dab
    eip = 0x099dedac   esp = 0xb41ff2d0   ebp = 0xffffffff
    Found by: stack scanning
 7  phantomjs + 0x1ac712a
    eip = 0x09b0f12b   esp = 0xb41ff2ec   ebp = 0xffffffff
    Found by: stack scanning
 8  phantomjs + 0x1b13b96
    eip = 0x09b5bb97   esp = 0xb41ff300   ebp = 0xffffffff
    Found by: stack scanning
 9  phantomjs + 0x24a6e2b
    eip = 0x0a4eee2c   esp = 0xb41ff308   ebp = 0xffffffff
    Found by: stack scanning
10  phantomjs + 0x24ae2bb
    eip = 0x0a4f62bc   esp = 0xb41ff310   ebp = 0xffffffff
    Found by: stack scanning
11  phantomjs + 0x19a2d8f
    eip = 0x099ead90   esp = 0xb41ff320   ebp = 0xffffffff
    Found by: stack scanning
12  libpthread-2.19.so + 0x18fff
    eip = 0xb7656000   esp = 0xb41ff350   ebp = 0xffffffff
    Found by: stack scanning
13  libpthread-2.19.so + 0x6f6f
    eip = 0xb7643f70   esp = 0xb41ff360   ebp = 0xffffffff
    Found by: stack scanning
14  libpthread-2.19.so + 0x18fff
    eip = 0xb7656000   esp = 0xb41ff394   ebp = 0xffffffff
    Found by: stack scanning

Loaded modules:
0x08048000 - 0x0a505fff  phantomjs  ???  (main)
0xb430d000 - 0xb4319fff  libnss_files-2.19.so  ???
0xb431a000 - 0xb432ffff  libresolv-2.19.so  ???
0xb4cd3000 - 0xb4d88fff  DejaVuSans.ttf  ???
0xb4def000 - 0xb4e02fff  n019003l.pfb  ???
0xb6e2d000 - 0xb6e45fff  libc.mo  ???
0xb6e46000 - 0xb6e9cfff  libssl.so.1.0.0  ???
0xb6e9d000 - 0xb7045fff  libcrypto.so.1.0.0  ???
0xb7060000 - 0xb7066fff  gconv-modules.cache  ???
0xb7067000 - 0xb7088fff  libc.mo  ???
0xb7089000 - 0xb7089fff  c05880de57d1f5e948fdfacc138775d9-le32d4.cache-4  ???
0xb708a000 - 0xb7091fff  945677eb7aeaf62f1d50efc3fb3ec7d8-le32d4.cache-4  ???
0xb7092000 - 0xb7095fff  2cd17615ca594fa2959ae173292e504c-le32d4.cache-4  ???
0xb7096000 - 0xb7096fff  e7071f4a29fa870f4323321c154eba04-le32d4.cache-4  ???
0xb7097000 - 0xb7097fff  0d8c3b2ac0904cb8a57a757ad11a4a08-le32d4.cache-4  ???
0xb7098000 - 0xb709cfff  a755afe4a08bf5b97852ceb7400b47bc-le32d4.cache-4  ???
0xb709d000 - 0xb70abfff  04aabc0a78ac019cf9454389977116d2-le32d4.cache-4  ???
0xb70ac000 - 0xb70acfff  1ac9eb803944fde146138c791f5cc56a-le32d4.cache-4  ???
0xb70ad000 - 0xb70affff  385c0604a188198f04d133e54aba7fe7-le32d4.cache-4  ???
0xb70b0000 - 0xb70b0fff  dc05db6664285cc2f12bf69c139ae4c3-le32d4.cache-4  ???
0xb70b1000 - 0xb70b2fff  767a8244fc0220cfb567a839d0392e0b-le32d4.cache-4  ???
0xb70b3000 - 0xb70b3fff  4794a0821666d79190d59a36cb4f44b5-le32d4.cache-4  ???
0xb70b4000 - 0xb70b7fff  8801497958630a81b71ace7c5f9b32a8-le32d4.cache-4  ???
0xb70b8000 - 0xb70bcfff  3047814df9a2f067bd2d96a2b9c36e5a-le32d4.cache-4  ???
0xb70bd000 - 0xb70bdfff  56cf4f4769d0f4abc89a4895d7bd3ae1-le32d4.cache-4  ???
0xb70be000 - 0xb70c1fff  b47c4e1ecd0709278f4910c18777a504-le32d4.cache-4  ???
0xb70c2000 - 0xb70d1fff  d52a8644073d54c13679302ca1180695-le32d4.cache-4  ???
0xb70d2000 - 0xb72d1fff  locale-archive  ???
0xb72d5000 - 0xb72fdfff  libexpat.so.1.6.0  ???
0xb72fe000 - 0xb7325fff  libpng12.so.0.50.0  ???
0xb7326000 - 0xb733ffff  libz.so.1.2.8  ???
0xb7340000 - 0xb74ecfff  libc-2.19.so  ???
0xb74f0000 - 0xb750cfff  libgcc_s.so.1  ???
0xb750e000 - 0xb7553fff  libm-2.19.so  ???
0xb7554000 - 0xb7635fff  libstdc++.so.6.0.19  ???
0xb763d000 - 0xb7656fff  libpthread-2.19.so  ???
0xb7659000 - 0xb7661fff  librt-2.19.so  ???
0xb7662000 - 0xb7666fff  libdl-2.19.so  ???
0xb7668000 - 0xb76a2fff  libfontconfig.so.1.8.0  ???
0xb76a3000 - 0xb7742fff  libfreetype.so.6.11.1  ???
0xb7743000 - 0xb7743fff  b9d506c9ac06c20b433354fa67a72993-le32d4.cache-4  ???
0xb7744000 - 0xb774afff  3f7329c5293ffd510edef78f73874cfd-le32d4.cache-4  ???
0xb774b000 - 0xb7753fff  d589a48862398ed80a3d6066f4f56f4c-le32d4.cache-4  ???
0xb7754000 - 0xb7754fff  0c9eb80ebd1c36541ebe2852d3bb0c49-le32d4.cache-4  ???
0xb7755000 - 0xb7756fff  e13b20fdb08344e0e664864cc2ede53d-le32d4.cache-4  ???
0xb7757000 - 0xb7759fff  7ef2298fde41cc6eeb7af42e48b7d293-le32d4.cache-4  ???
0xb775c000 - 0xb775cfff  linux-gate.so  ???
0xb775d000 - 0xb777efff  ld-2.19.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
