### ISSUE TITLE
Improper zooming on foreignObject html inside of svg

### ISSUE THREAD

**Issue by togakangaroo** [ariya/phantomjs#12614]
Judging from the fact that [this question on the mailing list](https://groups.google.com/forum/#!searchin/phantomjs/mauer/phantomjs/1khcHnYRY5s/6IuGnZCgkYAJ) and [this SO](http://stackoverflow.com/questions/25966175/phantomjs-zoomfactor-scale-rasterization-to-a-specific-size) garnered zero responses, I'm guessing this is a bug. Seems like zoomFactor is doing the wrong thing

---

I am rasterizing the following simple html+svg+foreignObject html

```
<html>
<head>
  <meta charset="UTF-8">
  <!--reset stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://phantomjs.googlecode.com/git-history/cbdd80e98ea1eb29d5d3a9c65c84798b472b59b1/website/reset.css" />
  <style>
  p {
    border: 1px solid red;
    font-size: 15px !important;
  }
  svg {
    outline: 1px solid purple;
  }
  </style>
</head>
<body style="height: 1050px; width: 1050px; max-width: 1050px; max-height: 750px;">

<svg style="width: 1050px; height: 750px;">
  <foreignobject height="40" requiredfeatures="http://www.w3.org/TR/SVG11/feature#Extensibility" width="45" x="45" y="45">
    <body xmlns="http://www.w3.org/1999/xhtml">
      <p>Oh when the sun begins to shine.</p>
    </body>
  </foreignobject>
</svg>
</body>
</html>
```

using this simple rasterization script:

```
webPage = require 'webpage' 
args    = (require 'system').args        
url = args[1]
destination = args[2]

page  = webPage.create()

page.paperSize = width: '10.5in', height: '7.5in', border: '0in'
#page.zoomFactor = 1.991
#page.viewportSize = (width: 1050, height: 75)

page.open url, (status) ->
  if status isnt 'success'
    console.log "Error!", url, status
    return phantom.exit()

  rasterize = -> 
    page.render destination
    console.log "Rasterized", url, "to", destination
    return phantom.exit()
  setTimeout rasterize, 100
```

![Chrome displaying svg](http://i.stack.imgur.com/AxDoH.png)

As you can see, the sizing of the single visible element is 1050px x 750px. I would like to rasterize this exactly onto a 10.5in x 7.5in paper size at 100% the size.

My rasterization script does:

```
page.paperSize = width: '10.5in', height: '7.5in', border: '0in'
```

which turns out with a pdf like this:

![Improperly scaled](http://i.stack.imgur.com/STUpq.png)

So that doesn't scale to full-size. I can adjust to full-size by adjusting the zoom factor. experimentally I've found that this works

```
page.zoomFactor = 1.991
```

![Properly scaled, font poorly sized](http://i.stack.imgur.com/ETaun.png)

Now the element scales properly but the fonts are scaled up too much.

**Comment by togakangaroo** [comment]
Would anyone be willing to maybe look at this issue with me? I'm getting really weird things happening with any svgs, not just `foreignObject`

For example I have a page with an svg that looks normal but small with zoomFactor of 1, the svg disappears with zoomFactor of 1.4, and looks properly scaled with zoomFactor 2.

**Comment by bprodoehl** [comment]
Have you tried with a build of PhantomJS 2? Our user interface is very
SVG-heavy, and 1.9.x couldnt render it well at all, but 2.0 handles it
perfectly.


On Friday, January 16, 2015, George Mauer <notifications@github.com> wrote:

> Would anyone be willing to maybe look at this issue with me? I'm getting
> really weird things happening with any svgs, not just foreignObject
>
> For example I have a page with an svg that looks normal but small with
> zoomFactor of 1, the svg disappears with zoomFactor of 1.4, and looks
> properly scaled with zoomFactor 2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ariya/phantomjs/issues/12614#issuecomment-70338347>.
>

-- 
-- 
http://www.connectify.me/

This email message is for the sole use of the intended recipient(s) and may 
contain Connectify confidential or privileged information. Any unauthorized 
review, use, disclosure or distribution is prohibited. If you are not an 
intended recipient, please contact the sender by reply email and destroy 
all copies of the original message.

**Comment by togakangaroo** [comment]
I have not. Not released yet, huh? Have to build from source? The page on how to build is pretty scary...

Honestly, I get that pdfs and webkit are a bit of a black box for most people (they are for me at least). At this point I'd settle for having a conversation with someone who can explain to me what the intended behaviour is and what some of the known issues are.

Seriously, please if that's you ping me gmauer@gmail

**Comment by bprodoehl** [comment]
What platform are you on? I have binaries for OS X, Ubuntu and Fedora on my
github. Sounds like the devs are rapidly approaching a 2.0 release, though,
too.

On Friday, January 16, 2015, George Mauer <notifications@github.com> wrote:

> I have not. Not released yet, huh? Have to build from source? The page on
> how to build is pretty scary...
>
> Honestly, I get that pdfs and webkit are a bit of a black box for most
> people (they are for me at least). At this point I'd settle for having a
> conversation with someone who can explain to me what the intended behaviour
> is and what some of the known issues are.
>
> Seriously, please if that's you ping me gmauer@gmail
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ariya/phantomjs/issues/12614#issuecomment-70340177>.
>

-- 
-- 
http://www.connectify.me/

This email message is for the sole use of the intended recipient(s) and may 
contain Connectify confidential or privileged information. Any unauthorized 
review, use, disclosure or distribution is prohibited. If you are not an 
intended recipient, please contact the sender by reply email and destroy 
all copies of the original message.

**Comment by togakangaroo** [comment]
Windows :D
