### ISSUE TITLE
Is there a way to disable localstorage?

### ISSUE THREAD

**Issue by justinleveck** [ariya/phantomjs#12625]
We need to use phantomjs with local storage disabled to test for scenarios where clients have disabled local storage and/or cookies.

I think I read once that you could pass in the following command line option to essentially disable local storage for testing but it does not seem to work. Anyone have any ideas on how to achieve this?

```
--local-storage-path = /dev/null
```

**Comment by daluu** [comment]
Curious, what was the resolution? Can't really tell from the context of this issue status.
