### ISSUE TITLE
Phantomjs 1.9.7 - Border dotted and dashed - PDF

### ISSUE THREAD

**Issue by walter-psjr** [ariya/phantomjs#12636]
Hello, i'm using phantomjs 1.9.7 for generate PDF's, but on elements, by example tables, with border dotted or dashed, they are not printed correctly. In the PDF the borders show correctly, but on printing don't show.

PDF
![image](https://cloud.githubusercontent.com/assets/8856322/4582558/98ea2a74-4fe9-11e4-81c4-e93e28240985.png)

Printing
![image](https://cloud.githubusercontent.com/assets/8856322/4582610/290185e4-4fea-11e4-83f6-aca59908d607.png)

**Comment by jackblackCH** [comment]
+1
