### ISSUE TITLE
PhantomJS has crashed

### ISSUE THREAD

**Issue by cherednichenko** [ariya/phantomjs#12638]
When member clicks create menu button                                # features/step_definitions/header.rb:33
      Connection reset by peer - recvfrom(2) (Errno::ECONNRESET)
      ./features/step_definitions/header.rb:35:in `/^member clicks create menu button$/'
      features/M023_Create_Discussion.feature:31:in `When member clicks create menu button'

 Broken pipe (Errno::EPIPE)
      /Users/sergey/.rbenv/versions/2.1.2/gemsets/qa-platform/gems/poltergeist-1.5.0/lib/capybara/poltergeist/web_socket_server.rb:62:in `write'
      /Users/sergey/.rbenv/versions/2.1.2/gemsets/qa-platform/gems/poltergeist-1.5.0/lib/capybara/poltergeist/web_socket_server.rb:62:in `write'
      /Users/sergey/.rbenv/versions/2.1.2/gemsets/qa-platform/gems/websocket-driver-0.3.3/lib/websocket/driver/server.rb:53:in `write'
      /Users/sergey/.rbenv/versions/2.1.2/gemsets/qa-platform/gems/websocket-driver-0.3.3/lib/websocket/driver/draft75.rb:69:in `frame'
      /Users/sergey/.rbenv/versions/2.1.2/gemsets/qa-platform/gems/websocket-driver-0.3.3/lib/websocket/driver.rb:89:in `text'
      /Users/sergey/.rbenv/versions/2.1.2/gemsets/qa-platform/gems/websocket-driver-0.3.3/lib/websocket/driver/server.rb:28:in `block (2 levels) in <class:Server>'
      /Users/sergey/.rbenv/versions/2.1.2/gemsets/qa-platform/gems/poltergeist-1.5.0/lib/capybara/poltergeist/web_socket_server.rb:84:in `send'
      /Users/sergey/.rbenv/versions/2.1.2/gemsets/qa-platform/gems/poltergeist-1.5.0/lib/capybara/poltergeist/server.rb:33:in `send'
      /Users/sergey/.rbenv/versions/2.1.2/gemsets/qa-platform/gems/poltergeist-1.5.0/lib/capybara/poltergeist/browser.rb:270:in `command'
      /Users/sergey/.rbenv/versions/2.1.2/gemsets/qa-platform/gems/poltergeist-1.5.0/lib/capybara/poltergeist/browser.rb:161:in `reset'
      /Users/sergey/.rbenv/versions/2.1.2/gemsets/qa-platform/gems/poltergeist-1.5.0/lib/capybara/poltergeist/driver.rb:151:in `reset!'
      /Users/sergey/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.3.0/lib/capybara/session.rb:95:in `reset!'
      /Users/sergey/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.3.0/lib/capybara.rb:255:in `block in reset_sessions!'
      /Users/sergey/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.3.0/lib/capybara.rb:255:in `each'
      /Users/sergey/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.3.0/lib/capybara.rb:255:in `reset_sessions!'
      /Users/sergey/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.3.0/lib/capybara/cucumber.rb:8:in `After'

**Comment by doredesign** [comment]
@cherednichenko, I'm getting the same error. Do you remember what you did to address it?

**Comment by cherednichenko** [comment]
@doredesign I ran my tests in Poltergeist/PhantomJS mode - the action was: "/^member clicks create menu button$/'" .

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
