### ISSUE TITLE
PhantomJS 1.9.7 crash on mac

### ISSUE THREAD

**Issue by arawlins** [ariya/phantomjs#12639]
Note when I run the same tests on Windows it doesn't crash.

Operating system: Mac OS X
                  10.9.5 13F34
CPU: x86
     GenuineIntel family 6 model 70 stepping 1
     8 CPUs

Crash reason:  EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
Crash address: 0xffffffff8f3e0017

Thread 0 (crashed)
 0  0x8f3e0017
    eip = 0x8f3e0017   esp = 0xbfffc43c   ebp = 0xbfffc478   ebx = 0x0cbc7b68
    esi = 0x0cb1aed8   edi = 0xbfffc518   eax = 0x00000000   ecx = 0x046f4e28
    edx = 0x8f3e0017   efl = 0x00210246
    Found by: given as instruction pointer in context
 1  phantomjs!__ZN9QWebFrame18evaluateJavaScriptERK7QStringS2_ + 0x115
    eip = 0x00b32f34   esp = 0xbfffc480   ebp = 0xbfffc548
    Found by: previous frame's frame pointer
 2  phantomjs!__ZN7WebPage18evaluateJavaScriptERK7QString + 0x1c9
    eip = 0x0001586e   esp = 0xbfffc550   ebp = 0xbfffc5d8
    Found by: previous frame's frame pointer
 3  0x465c93f
    eip = 0x0465c940   esp = 0xbfffc580   ebp = 0xbfffc5d8   ebx = 0x0001586e
    esi = 0x01772bf0   edi = 0xbfffc5d8
    Found by: call frame info
 4  phantomjs!__ZN7WebPage18qt_static_metacallEP7QObjectN11QMetaObject4CallEiPPv + 0x365
    eip = 0x0005cb06   esp = 0xbfffc5e0   ebp = 0xbfffc738
    Found by: previous frame's frame pointer
 5  0x60ba45f
    eip = 0x060ba460   esp = 0xbfffc630   ebp = 0xbfffc738   ebx = 0x0005cb06
    esi = 0x060ba460   edi = 0xbfffc738
    Found by: call frame info
 6  phantomjs!__ZN7WebPage11qt_metacallEN11QMetaObject4CallEiPPv + 0x79
    eip = 0x0005db40   esp = 0xbfffc740   ebp = 0xbfffc848
    Found by: previous frame's frame pointer

Thread 1
 0  libsystem_kernel.dylib + 0x18992
    eip = 0x90f7d992   esp = 0xb001067c   ebp = 0xb00106f8   ebx = 0xb00106a0
    esi = 0x978b37b9   edi = 0xb00106a0   eax = 0x00000171   ecx = 0xb001067c
    edx = 0x90f7d992   efl = 0x00000286
    Found by: given as instruction pointer in context
 1  libdispatch.dylib + 0x3531
    eip = 0x978b3532   esp = 0xb0010700   ebp = 0xb0010f08
    Found by: previous frame's frame pointer

Thread 2
 0  libsystem_kernel.dylib + 0x18046
    eip = 0x90f7d046   esp = 0xb0114f9c   ebp = 0xb0114fc8   ebx = 0x00001c03
    esi = 0xb0115000   edi = 0x903b5c69   eax = 0x00100170   ecx = 0xb0114f9c
    edx = 0x90f7d046   efl = 0x00000282
    Found by: given as instruction pointer in context
 1  libsystem_pthread.dylib + 0x6ccd
    eip = 0x903b9cce   esp = 0xb0114fd0   ebp = 0xb0114fec
    Found by: previous frame's frame pointer

Thread 3
 0  libsystem_kernel.dylib + 0x18046
    eip = 0x90f7d046   esp = 0xb0196f9c   ebp = 0xb0196fc8   ebx = 0x00002807
    esi = 0xb0197000   edi = 0x903b5c69   eax = 0x00100170   ecx = 0xb0196f9c
    edx = 0x90f7d046   efl = 0x00000282
    Found by: given as instruction pointer in context
 1  libsystem_pthread.dylib + 0x6ccd
    eip = 0x903b9cce   esp = 0xb0196fd0   ebp = 0xb0196fec
    Found by: previous frame's frame pointer

Thread 4
 0  libsystem_kernel.dylib + 0x18046
    eip = 0x90f7d046   esp = 0xb0218f9c   ebp = 0xb0218fc8   ebx = 0x0000370b
    esi = 0xb0219000   edi = 0x903b5c69   eax = 0x00100170   ecx = 0xb0218f9c
    edx = 0x90f7d046   efl = 0x00000282
    Found by: given as instruction pointer in context
 1  libsystem_pthread.dylib + 0x6ccd
    eip = 0x903b9cce   esp = 0xb0218fd0   ebp = 0xb0218fec
    Found by: previous frame's frame pointer

Thread 5
 0  libsystem_kernel.dylib + 0x130a6
    eip = 0x90f780a6   esp = 0xb029aecc   ebp = 0xb029af18   ebx = 0x0001309e
    esi = 0x0001309e   edi = 0xb6286012   eax = 0xffffffa6   ecx = 0xb029aecc
    edx = 0x90f780a6   efl = 0x00000202
    Found by: given as instruction pointer in context
 1  libsystem_c.dylib + 0x826fb
    eip = 0x9a1206fc   esp = 0xb029af20   ebp = 0xb029af48
    Found by: previous frame's frame pointer
 2  phantomjs!__ZN3WTF17TCMalloc_PageHeap15scavengerThreadEv + 0xc2
    eip = 0x00089853   esp = 0xb029af50   ebp = 0xb029af78
    Found by: previous frame's frame pointer
 3  phantomjs!__ZN3WTF17TCMalloc_PageHeap18runScavengerThreadEPv + 0x10
    eip = 0x00089889   esp = 0xb029af80   ebp = 0xb029af88
    Found by: previous frame's frame pointer
 4  libsystem_pthread.dylib + 0x15fa
    eip = 0x903b45fb   esp = 0xb029af90   ebp = 0xb029afa8
    Found by: previous frame's frame pointer
 5  libsystem_pthread.dylib + 0x1484
    eip = 0x903b4485   esp = 0xb029afb0   ebp = 0xb029afc8
    Found by: previous frame's frame pointer
 6  libsystem_pthread.dylib + 0x6cf1
    eip = 0x903b9cf2   esp = 0xb029afd0   ebp = 0xb029afec
    Found by: previous frame's frame pointer

Thread 6
 0  libsystem_kernel.dylib + 0x17aea
    eip = 0x90f7caea   esp = 0xb031ccec   ebp = 0xb031cd18   ebx = 0x018599a0
    esi = 0x05252b08   edi = 0x05252d1c   eax = 0x00140197   ecx = 0xb031ccec
    edx = 0x90f7caea   efl = 0x00000246
    Found by: given as instruction pointer in context
 1  phantomjs!__Z14qt_safe_selectiP6fd_setS0_S0_PK7timeval + 0x37
    eip = 0x011f9708   esp = 0xb031cd20   ebp = 0xb031cd68
    Found by: previous frame's frame pointer
 2  phantomjs!__ZN20QEventDispatcherUNIX6selectEiP6fd_setS1_S1_P7timeval + 0x2c
    eip = 0x011fa8a1   esp = 0xb031cd70   ebp = 0xb031cd88
    Found by: previous frame's frame pointer
 3  phantomjs!__ZN27QEventDispatcherUNIXPrivate8doSelectE6QFlagsIN10QEventLoop17ProcessEventsFlagEEP7timeval + 0x471
    eip = 0x011fb7b8   esp = 0xb031cd90   ebp = 0xb031ce78
    Found by: previous frame's frame pointer
 4  phantomjs!__ZN20QEventDispatcherUNIX13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 0xe9
    eip = 0x011fbbc6   esp = 0xb031ce80   ebp = 0xb031ceb8
    Found by: previous frame's frame pointer
 5  phantomjs!__ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 0x210
    eip = 0x011d6c83   esp = 0xb031cec0   ebp = 0xb031cef8
    Found by: previous frame's frame pointer
 6  phantomjs!__ZN7QThread4execEv + 0xca
    eip = 0x01101fc7   esp = 0xb031cf00   ebp = 0xb031cf38
    Found by: previous frame's frame pointer
 7  phantomjs!__ZN14QThreadPrivate5startEPv + 0x1fc
    eip = 0x011046e7   esp = 0xb031cf40   ebp = 0xb031cf88
    Found by: previous frame's frame pointer
 8  libsystem_pthread.dylib + 0x15fa
    eip = 0x903b45fb   esp = 0xb031cf90   ebp = 0xb031cfa8
    Found by: previous frame's frame pointer
 9  libsystem_pthread.dylib + 0x1484
    eip = 0x903b4485   esp = 0xb031cfb0   ebp = 0xb031cfc8
    Found by: previous frame's frame pointer
10  libsystem_pthread.dylib + 0x6cf1
    eip = 0x903b9cf2   esp = 0xb031cfd0   ebp = 0xb031cfec
    Found by: previous frame's frame pointer

Thread 7
 0  libsystem_kernel.dylib + 0x12f7a
    eip = 0x90f77f7a   esp = 0xb039df2c   ebp = 0xb039df68   ebx = 0xb039e048
    esi = 0x07000006   edi = 0x00000c00   eax = 0xffffffe1   ecx = 0xb039df2c
    edx = 0x90f77f7a   efl = 0x00000206
    Found by: given as instruction pointer in context
 1  CoreFoundation + 0x76bf8
    eip = 0x9189dbf9   esp = 0xb039df70   ebp = 0xb039dfa8
    Found by: previous frame's frame pointer
 2  CoreFoundation + 0x761d0
    eip = 0x9189d1d1   esp = 0xb039dfb0   ebp = 0xb039ed58
    Found by: previous frame's frame pointer
 3  CoreFoundation + 0x759e9
    eip = 0x9189c9ea   esp = 0xb039ed60   ebp = 0xb039ee08
    Found by: previous frame's frame pointer
 4  CoreFoundation + 0x7584a
    eip = 0x9189c84b   esp = 0xb039ee10   ebp = 0xb039ee38
    Found by: previous frame's frame pointer
 5  AppKit + 0x1d1b87
    eip = 0x94daeb88   esp = 0xb039ee40   ebp = 0xb039ef88
    Found by: previous frame's frame pointer
 6  libsystem_pthread.dylib + 0x15fa
    eip = 0x903b45fb   esp = 0xb039ef90   ebp = 0xb039efa8
    Found by: previous frame's frame pointer
 7  libsystem_pthread.dylib + 0x1484
    eip = 0x903b4485   esp = 0xb039efb0   ebp = 0xb039efc8
    Found by: previous frame's frame pointer
 8  libsystem_pthread.dylib + 0x6cf1
    eip = 0x903b9cf2   esp = 0xb039efd0   ebp = 0xb039efec
    Found by: previous frame's frame pointer

Thread 8
 0  libsystem_kernel.dylib + 0x17aea
    eip = 0x90f7caea   esp = 0xb0420cec   ebp = 0xb0420d18   ebx = 0x018599a0
    esi = 0x0324ad08   edi = 0x0324af1c   eax = 0x00140197   ecx = 0xb0420cec
    edx = 0x90f7caea   efl = 0x00000202
    Found by: given as instruction pointer in context
 1  phantomjs!__Z14qt_safe_selectiP6fd_setS0_S0_PK7timeval + 0x1b7
    eip = 0x011f9888   esp = 0xb0420d20   ebp = 0xb0420d68
    Found by: previous frame's frame pointer
 2  phantomjs!__ZN20QEventDispatcherUNIX6selectEiP6fd_setS1_S1_P7timeval + 0x2c
    eip = 0x011fa8a1   esp = 0xb0420d70   ebp = 0xb0420d88
    Found by: previous frame's frame pointer
 3  phantomjs!__ZN27QEventDispatcherUNIXPrivate8doSelectE6QFlagsIN10QEventLoop17ProcessEventsFlagEEP7timeval + 0x471
    eip = 0x011fb7b8   esp = 0xb0420d90   ebp = 0xb0420e78
    Found by: previous frame's frame pointer
 4  phantomjs!__ZN20QEventDispatcherUNIX13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 0xe9
    eip = 0x011fbbc6   esp = 0xb0420e80   ebp = 0xb0420eb8
    Found by: previous frame's frame pointer
 5  phantomjs!__ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 0x210
    eip = 0x011d6c83   esp = 0xb0420ec0   ebp = 0xb0420ef8
    Found by: previous frame's frame pointer
 6  phantomjs!__ZN7QThread4execEv + 0xca
    eip = 0x01101fc7   esp = 0xb0420f00   ebp = 0xb0420f38
    Found by: previous frame's frame pointer
 7  phantomjs!__ZN14QThreadPrivate5startEPv + 0x1fc
    eip = 0x011046e7   esp = 0xb0420f40   ebp = 0xb0420f88
    Found by: previous frame's frame pointer
 8  libsystem_pthread.dylib + 0x15fa
    eip = 0x903b45fb   esp = 0xb0420f90   ebp = 0xb0420fa8
    Found by: previous frame's frame pointer
 9  libsystem_pthread.dylib + 0x1484
    eip = 0x903b4485   esp = 0xb0420fb0   ebp = 0xb0420fc8
    Found by: previous frame's frame pointer
10  libsystem_pthread.dylib + 0x6cf1
    eip = 0x903b9cf2   esp = 0xb0420fd0   ebp = 0xb0420fec
    Found by: previous frame's frame pointer

Thread 9
 0  libsystem_kernel.dylib + 0x177ca
    eip = 0x90f7c7ca   esp = 0xb04a2dfc   ebp = 0xb04a2e88   ebx = 0x00000000
    esi = 0x00000401   edi = 0x00000500   eax = 0x00000131   ecx = 0xb04a2dfc
    edx = 0x90f7c7ca   efl = 0x00000246
    Found by: given as instruction pointer in context
 1  libsystem_pthread.dylib + 0x5fd6
    eip = 0x903b8fd7   esp = 0xb04a2e90   ebp = 0xb04a2ea8
    Found by: previous frame's frame pointer
 2  phantomjs!__ZN21QWaitConditionPrivate4waitEm + 0xa0
    eip = 0x01105271   esp = 0xb04a2eb0   ebp = 0xb04a2ee8
    Found by: previous frame's frame pointer
 3  phantomjs!__ZN14QWaitCondition4waitEP6QMutexm + 0x76
    eip = 0x01104f57   esp = 0xb04a2ef0   ebp = 0xb04a2f08
    Found by: previous frame's frame pointer
 4  phantomjs!__ZN17QThreadPoolThread3runEv + 0x23d
    eip = 0x010f9a3c   esp = 0xb04a2f10   ebp = 0xb04a2f38
    Found by: previous frame's frame pointer
 5  phantomjs!__ZN14QThreadPrivate5startEPv + 0x1fc
    eip = 0x011046e7   esp = 0xb04a2f40   ebp = 0xb04a2f88
    Found by: previous frame's frame pointer
 6  libsystem_pthread.dylib + 0x15fa
    eip = 0x903b45fb   esp = 0xb04a2f90   ebp = 0xb04a2fa8
    Found by: previous frame's frame pointer
 7  libsystem_pthread.dylib + 0x1484
    eip = 0x903b4485   esp = 0xb04a2fb0   ebp = 0xb04a2fc8
    Found by: previous frame's frame pointer
 8  libsystem_pthread.dylib + 0x6cf1
    eip = 0x903b9cf2   esp = 0xb04a2fd0   ebp = 0xb04a2fec
    Found by: previous frame's frame pointer

Thread 10
 0  libsystem_kernel.dylib + 0x177ca
    eip = 0x90f7c7ca   esp = 0xb0524dfc   ebp = 0xb0524e88   ebx = 0x00000000
    esi = 0x00000400   edi = 0x00000600   eax = 0x00000131   ecx = 0xb0524dfc
    edx = 0x90f7c7ca   efl = 0x00000246
    Found by: given as instruction pointer in context
 1  libsystem_pthread.dylib + 0x5fd6
    eip = 0x903b8fd7   esp = 0xb0524e90   ebp = 0xb0524ea8
    Found by: previous frame's frame pointer
 2  phantomjs!__ZN21QWaitConditionPrivate4waitEm + 0xa0
    eip = 0x01105271   esp = 0xb0524eb0   ebp = 0xb0524ee8
    Found by: previous frame's frame pointer
 3  phantomjs!__ZN14QWaitCondition4waitEP6QMutexm + 0x76
    eip = 0x01104f57   esp = 0xb0524ef0   ebp = 0xb0524f08
    Found by: previous frame's frame pointer
 4  phantomjs!__ZN17QThreadPoolThread3runEv + 0x23d
    eip = 0x010f9a3c   esp = 0xb0524f10   ebp = 0xb0524f38
    Found by: previous frame's frame pointer
 5  phantomjs!__ZN14QThreadPrivate5startEPv + 0x1fc
    eip = 0x011046e7   esp = 0xb0524f40   ebp = 0xb0524f88
    Found by: previous frame's frame pointer
 6  libsystem_pthread.dylib + 0x15fa
    eip = 0x903b45fb   esp = 0xb0524f90   ebp = 0xb0524fa8
    Found by: previous frame's frame pointer
 7  libsystem_pthread.dylib + 0x1484
    eip = 0x903b4485   esp = 0xb0524fb0   ebp = 0xb0524fc8
    Found by: previous frame's frame pointer
 8  libsystem_pthread.dylib + 0x6cf1
    eip = 0x903b9cf2   esp = 0xb0524fd0   ebp = 0xb0524fec
    Found by: previous frame's frame pointer

Loaded modules:
0x00001000 - 0x01742fff  phantomjs  ???  (main)
0x023bd000 - 0x023d8fff  csparser  ???
0x023ea000 - 0x023f2fff  libCGCMS.A.dylib  ???
0x07776000 - 0x0779efff  libRIP.A.dylib  ???
0x077af000 - 0x077b2fff  libCGXType.A.dylib  ???
0x08100000 - 0x081b0fff  ColorSyncDeprecated.dylib  ???
0x09792000 - 0x0979dfff  CommerceCore  ???
0x0c252000 - 0x0c277fff  FamilyControls  ???
0x90008000 - 0x9007dfff  ATS  ???
0x90133000 - 0x90141fff  OpenGL  ???
0x90196000 - 0x901c1fff  libsystem_network.dylib  ???
0x901c2000 - 0x901c3fff  libunc.dylib  ???
0x901c4000 - 0x9031afff  libBLAS.dylib  ???
0x9031b000 - 0x9031bfff  libodfde.dylib  ???
0x9031c000 - 0x90340fff  libxpc.dylib  ???
0x903b0000 - 0x903b2fff  libRadiance.dylib  ???
0x903b3000 - 0x903bafff  libsystem_pthread.dylib  ???
0x90b7c000 - 0x90c06fff  CoreSymbolication  ???
0x90cab000 - 0x90cb4fff  SpeechRecognition  ???
0x90cb5000 - 0x90cf3fff  NavigationServices  ???
0x90cff000 - 0x90df3fff  libFontParser.dylib  ???
0x90df4000 - 0x90df4fff  AudioUnit  ???
0x90df5000 - 0x90edbfff  CoreUI  ???
0x90edc000 - 0x90ee0fff  CommonPanels  ???
0x90ee1000 - 0x90f57fff  SecurityFoundation  ???
0x90f58000 - 0x90f64fff  libbz2.1.0.dylib  ???
0x90f65000 - 0x90f82fff  libsystem_kernel.dylib  ???
0x90f83000 - 0x91110fff  CFNetwork  ???
0x91111000 - 0x91118fff  NetFS  ???
0x91119000 - 0x91392fff  Security  ???
0x916b3000 - 0x91826fff  AudioToolbox  ???
0x91827000 - 0x91a29fff  CoreFoundation  ???
0x91a2a000 - 0x91e5efff  FaceCore  ???
0x91f0b000 - 0x91f41fff  IconServices  ???
0x92070000 - 0x92078fff  libsystem_dnssd.dylib  ???
0x9222f000 - 0x92241fff  libsystem_asl.dylib  ???
0x92242000 - 0x9225bfff  Kerberos  ???
0x9225c000 - 0x9225efff  libsystem_configuration.dylib  ???
0x9225f000 - 0x9225ffff  libOpenScriptingUtil.dylib  ???
0x92260000 - 0x9226afff  SpeechSynthesis  ???
0x9226b000 - 0x92270fff  libsystem_platform.dylib  ???
0x92271000 - 0x92271fff  Cocoa  ???
0x92272000 - 0x92303fff  ColorSync  ???
0x92304000 - 0x9234cfff  PerformanceAnalysis  ???
0x9234d000 - 0x92428fff  LaunchServices  ???
0x92429000 - 0x92433fff  ServiceManagement  ???
0x92434000 - 0x925dcfff  libobjc.A.dylib  ???
0x925dd000 - 0x925e8fff  libcsfde.dylib  ???
0x925e9000 - 0x925fdfff  MultitouchSupport  ???
0x925fe000 - 0x9260efff  libsasl2.2.dylib  ???
0x92643000 - 0x926a4fff  Symbolication  ???
0x926d3000 - 0x92719fff  libcurl.4.dylib  ???
0x9271a000 - 0x92769fff  HIServices  ???
0x92caa000 - 0x92caefff  libCoreVMClient.dylib  ???
0x92caf000 - 0x92cccfff  libresolv.9.dylib  ???
0x92ccd000 - 0x92cd7fff  DirectoryService  ???
0x92eb3000 - 0x92eb7fff  libpam.2.dylib  ???
0x92f0f000 - 0x92f0ffff  ApplicationServices  ???
0x92f10000 - 0x9300efff  libJP2.dylib  ???
0x9300f000 - 0x9300ffff  libkeymgr.dylib  ???
0x93010000 - 0x930acfff  QD  ???
0x930ad000 - 0x930eafff  libGLImage.dylib  ???
0x93f8d000 - 0x94139fff  QuartzCore  ???
0x94148000 - 0x94153fff  libcommonCrypto.dylib  ???
0x94154000 - 0x94160fff  OpenDirectory  ???
0x943d0000 - 0x94425fff  CoreAudio  ???
0x94426000 - 0x9442efff  libGFXShared.dylib  ???
0x9442f000 - 0x94431fff  SecurityHI  ???
0x949d3000 - 0x94aa3fff  libvDSP.dylib  ???
0x94aa4000 - 0x94af5fff  libstdc++.6.dylib  ???
0x94af6000 - 0x94b04fff  libz.1.dylib  ???
0x94b10000 - 0x94b14fff  libGIF.dylib  ???
0x94b7c000 - 0x94b85fff  CommonAuth  ???
0x94b86000 - 0x94bdcfff  ScalableUserInterface  ???
0x94bdd000 - 0x957fbfff  AppKit  ???
0x957fc000 - 0x95828fff  DictionaryServices  ???
0x959cc000 - 0x95a78fff  libvMisc.dylib  ???
0x95a99000 - 0x95a9cfff  TCC  ???
0x95a9d000 - 0x95a9dfff  CoreServices  ???
0x95baf000 - 0x95bbefff  libGL.dylib  ???
0x95bbf000 - 0x95bc1fff  libCVMSPluginSupport.dylib  ???
0x964e9000 - 0x967d3fff  vImage  ???
0x967d4000 - 0x96803fff  SystemAdministration  ???
0x96804000 - 0x9682cfff  libsystem_info.dylib  ???
0x968d9000 - 0x9690afff  libsystem_m.dylib  ???
0x9690b000 - 0x9693bfff  CoreServicesInternal  ???
0x96968000 - 0x96a2bfff  CoreText  ???
0x96a2c000 - 0x96a30fff  IOSurface  ???
0x96a31000 - 0x96c95fff  CoreData  ???
0x96cb7000 - 0x96cbafff  libdyld.dylib  ???
0x96cc3000 - 0x97038fff  HIToolbox  ???
0x970a5000 - 0x97173fff  Backup  ???
0x97174000 - 0x97182fff  Sharing  ???
0x97183000 - 0x9718cfff  CarbonSound  ???
0x9718d000 - 0x97192fff  libcompiler_rt.dylib  ???
0x97193000 - 0x971cbfff  MediaKit  ???
0x9723b000 - 0x97281fff  libFontRegistry.dylib  ???
0x97282000 - 0x972ebfff  SystemConfiguration  ???
0x972ec000 - 0x9736cfff  OSServices  ???
0x9736d000 - 0x9737ffff  libbsm.0.dylib  ???
0x97397000 - 0x9740efff  IOKit  ???
0x97416000 - 0x97458fff  libGLU.dylib  ???
0x97459000 - 0x97462fff  DiskArbitration  ???
0x977d5000 - 0x977f9fff  libJPEG.dylib  ???
0x977fa000 - 0x97899fff  libCoreStorage.dylib  ???
0x9789a000 - 0x978aafff  LangAnalysis  ???
0x978ab000 - 0x978affff  libcache.dylib  ???
0x978b0000 - 0x978c8fff  libdispatch.dylib  ???
0x978c9000 - 0x978d6fff  AppleFSCompression  ???
0x978d7000 - 0x978dafff  libutil.dylib  ???
0x978db000 - 0x9792bfff  libcorecrypto.dylib  ???
0x97bcf000 - 0x97bd4fff  Print  ???
0x97bd5000 - 0x97bd6fff  libsystem_sandbox.dylib  ???
0x97c03000 - 0x97c04fff  libsystem_blocks.dylib  ???
0x97c05000 - 0x97c0dfff  libcopyfile.dylib  ???
0x98571000 - 0x985dafff  DataDetectorsCore  ???
0x98645000 - 0x98698fff  HTMLRendering  ???
0x9869e000 - 0x986a4fff  AOSNotification  ???
0x986a5000 - 0x986a8fff  Help  ???
0x986a9000 - 0x986b1fff  liblaunch.dylib  ???
0x986b2000 - 0x9870bfff  libTIFF.dylib  ???
0x988b4000 - 0x98900fff  libcups.2.dylib  ???
0x98901000 - 0x98902fff  libSystem.B.dylib  ???
0x98903000 - 0x98938fff  libssl.0.9.8.dylib  ???
0x98b04000 - 0x98bf0fff  libxml2.2.dylib  ???
0x98bf1000 - 0x98ce1fff  libiconv.2.dylib  ???
0x98ce2000 - 0x98d1efff  RemoteViewServices  ???
0x98d1f000 - 0x98d5ffff  Bom  ???
0x98d60000 - 0x98e43fff  libcrypto.0.9.8.dylib  ???
0x98e44000 - 0x98e52fff  libxar.1.dylib  ???
0x98eb2000 - 0x98f02fff  OpenCL  ???
0x98f03000 - 0x98f05fff  EFILogin  ???
0x98f06000 - 0x98f13fff  Librarian  ???
0x99247000 - 0x99262fff  libPng.dylib  ???
0x993ec000 - 0x99410fff  libc++abi.dylib  ???
0x99411000 - 0x99466fff  libc++.1.dylib  ???
0x99467000 - 0x99794fff  Foundation  ???
0x99795000 - 0x998a7fff  libsqlite3.dylib  ???
0x998a8000 - 0x998cffff  CoreVideo  ???
0x9995c000 - 0x99986fff  libxslt.1.dylib  ???
0x99987000 - 0x99a1efff  Ink  ???
0x99a1f000 - 0x99a5cfff  libauto.dylib  ???
0x99a5d000 - 0x99ad0fff  SearchKit  ???
0x99ad1000 - 0x99bdefff  ImageIO  ???
0x99c8b000 - 0x99c9efff  ImageCapture  ???
0x99ca3000 - 0x99d6afff  DiscRecording  ???
0x99d6b000 - 0x99d87fff  Ubiquity  ???
0x99d8e000 - 0x99d8efff  Carbon  ???
0x99d8f000 - 0x99d9bfff  libkxld.dylib  ???
0x99d9c000 - 0x99da7fff  NetAuth  ???
0x99da8000 - 0x9a09dfff  CoreImage  ???
0x9a09e000 - 0x9a130fff  libsystem_c.dylib  ???
0x9a131000 - 0x9a149fff  CFOpenDirectory  ???
0x9a14a000 - 0x9a175fff  ChunkingLibrary  ???
0x9a176000 - 0x9a17cfff  libunwind.dylib  ???
0x9a17d000 - 0x9a1e8fff  Heimdal  ???
0x9a1e9000 - 0x9a204fff  OpenScripting  ???
0x9a633000 - 0x9a63efff  CrashReporterSupport  ???
0x9a63f000 - 0x9a69dfff  AE  ???
0x9a69e000 - 0x9a6d6fff  LDAP  ???
0x9a752000 - 0x9a753fff  liblangid.dylib  ???
0x9a754000 - 0x9a782fff  DebugSymbols  ???
0x9ad19000 - 0x9b0defff  libLAPACK.dylib  ???
0x9b0df000 - 0x9b0f7fff  libsystem_malloc.dylib  ???
0x9b12a000 - 0x9b12efff  libheimdal-asn1.dylib  ???
0x9b15b000 - 0x9b15dfff  libquarantine.dylib  ???
0x9b15e000 - 0x9b15ffff  libremovefile.dylib  ???
0x9b160000 - 0x9b17cfff  libCRFSuite.dylib  ???
0x9b17d000 - 0x9b17dfff  Accelerate  ???
0x9b17e000 - 0x9b47ffff  CarbonCore  ???
0x9b480000 - 0x9b646fff  libicucore.A.dylib  ???
0x9b647000 - 0x9ba3ffff  CoreGraphics  ???
0x9ba40000 - 0x9ba49fff  libsystem_notify.dylib  ???
0x9ba4a000 - 0x9bb35fff  DiskImages  ???
0x9bb36000 - 0x9bb37fff  libDiagnosticMessagesClient.dylib  ???
0x9bb38000 - 0x9bc6ffff  DesktopServicesPriv  ???
0x9bc70000 - 0x9bc73fff  LoginUICore  ???
0x9bc74000 - 0x9bd0cfff  Metadata  ???
0x9bd5c000 - 0x9bdb8fff  PrintCore  ???
0x9c1b3000 - 0x9c1e4fff  GSS  ???
0x9c23b000 - 0x9c255fff  GenerationalStorage  ???
0x9c261000 - 0x9c261fff  vecLib  ???
0x9c262000 - 0x9c263fff  TrustEvaluationAgent  ???
0x9c264000 - 0x9c268fff  libmacho.dylib  ???

**Comment by scien** [comment]
+1

**Comment by ankitdimania-eligible** [comment]
+1

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
