### ISSUE TITLE
Crash rendering a PDF on 1.9.7 on rhel system

### ISSUE THREAD

**Issue by waghanza** [ariya/phantomjs#12645]
Hi,

I am trying to render a pdf using [shrimp](https://github.com/adjust/shrimp) and [phantom](https://github.com/ariya/phantomjs).

When I' running this script, I've immediately a phantom crash error
~~~ruby
require 'shrimp'
url     = 'http://www.google.com'
options = { :margin => "1cm"}
Shrimp::Phantom.new(url, options).to_pdf("~/output.pdf")
~~~

**Details**
+ OS : `Fedora`
+ Version: `20`
+ Kernel: `3.16.4`
+ Arch: `x86_64`

I create a gist with the stacktrace

https://gist.github.com/anonymous/710854caadf084aae097

I hope it could be useful

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
