### ISSUE TITLE
phantomjs2 - set User-Agent problem

### ISSUE THREAD

**Issue by vovodroid** [ariya/phantomjs#12644]
Change rasterize.js to add user agent before open page:
///////////////////////////////
page.settings.userAgent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.1.17 (KHTML, like Gecko) Version/7.1 Safari/537.85.10';

page.open(address, function (status) {>
///////////////////////////////

Try to get screenshot of http://www.ivory.co.il/
Error "Unable to load the address!" returned. PhantomJS 1.9.7 works.

System: Linux CentOS 6.5 x64
PhantomJS: commit eddb0db1d253fd0c546060a4555554c8ee08c13c  - Port the tests for mousedown, mouseup, and mousemove events.
https://github.com/ariya/phantomjs/issues/12439

**Comment by ariya** [comment]
Due to the lack of a concrete follow-up possibility, this issue will be closed.
