### ISSUE TITLE
Add support for the fragment identifier

### ISSUE THREAD

**Issue by valuedvision** [ariya/phantomjs#12667]
I have PhantomJS version 1.9.7 and I would like to PhantomJS to add support for the Fragment Identifier (http://en.wikipedia.org/wiki/Fragment_identifier) to jump to a particular portion of a single page.

**Comment by aasshishpatil** [comment]
while implementing this i am getting error
null is not an object (evaluating 'document.getElementById(fragmentIdentifier).getBoundingClientRect')
 undefined:4  :7

**Comment by aasshishpatil** [comment]
how you are creating pdf file using the command
patrick@vm01:~/downloads/phantomjs-1.9.7-linux-i686/bin$ ./phantomjs save_image.js http://nl.wikipedia.org/wiki/Weimarrepubliek#Nabeschouwing image.png "1024px*800px"

**Comment by aasshishpatil** [comment]
I also want to know how should i get internal linking functioanlity within pdf using phantom js
like if i will click on specific fragment identifier link in pdf , then it should move to that part of pdf section
