### ISSUE TITLE
Phantomjs 2.0 Windows build

### ISSUE THREAD

**Issue by fjhub** [ariya/phantomjs#12666]
I came across an issue using phantomjs 1.9.7 and was curious if version 2.0  would resolve the issue.  I've downloaded the source and followed the simple instructions but was unable to build as I come across the following error:
```
compress.cpp
cppgenerator.cpp
dotgraph.cpp
lalr.cpp
main.cpp
parsetable.cpp
recognizer.cpp
grammar.cpp
        link /NOLOGO /DYNAMICBASE /NXCOMPAT /INCREMENTAL:NO /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='aaaaaaaaaaaaa' language='*' processorArchitecture='*'" /MANIFEST /MANIFESTFILE:..\..\..\bin\qlalr.exe.embed.manifest /OUT:..\..\..\bin\qlalr.exe @C:\Users\user\AppData\Local\Temp\nmE375.tmp
sicuin.lib(filteredbrk.ao) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'
```
Not knowing where to go with this, I still wanted to see if 2.0 would show my problem.  So I downloaded the macosx versions (both 1.9.7 and 2.0) and discovered that the 1.9.7 version gave the same result as the Windows version.  The 2.0 version looked to be correct.  Now I am more anxious to figure out how to get a build under Windows given that I am tied to this platform.

I've tried disabling the ``icu`` by modifying the ``qt/preconfig.cmd`` file by setting ``-no-icu`` but  this resulted in a different build error.

Is it possible to make modifications to things to ensure that I am getting a 64 bit compilation?

thanks

**Comment by aeosipov** [comment]
Hi, you can make support for 64 builds ?

**Comment by Vitallium** [comment]
Not relevant anymore.
