### ISSUE TITLE
PhantomJS is repeatedly crashing

### ISSUE THREAD

**Issue by jigfox** [ariya/phantomjs#12661]
If I try to run protractor jasmine specs for angular e2e testing phantomjs is always crashing.

I tried to convert the crash dumps into stack traces, but the steps described on http://phantomjs.org/crash-reporting.html didn't work on mac os x with this message: `exec format error: ./minidump_stackwalk`

and since github doesn't allow file uploads, here the link to the crash dumps: https://www.dropbox.com/sh/cfodl85bw1yja3v/AADlXImcm4d44aE7XITgo_u9a?dl=0

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
