### ISSUE TITLE
Phantom has crashed..

### ISSUE THREAD

**Issue by KenanSulayman** [ariya/phantomjs#12671]
https://gist.github.com/KenanSulayman/87f1888e4316ecc243c5

*Currently breaks our Jenkins.*

Happens while a test is running that clicks an input field and *_exit(-1)* is called from a helper function in a library that handles an input error inside an integration test. (exit is invoked here: https://github.com/actano/sternchen_reporter/blob/master/lib/sternchen.js#L99-L119)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
