### ISSUE TITLE
Overriding user agent settings does not render fonts correctly

### ISSUE THREAD

**Issue by amir20** [ariya/phantomjs#12682]
This took me a while to debug so I am hoping it's not something I am doing specific. I installed v2.0 on an ubuntu box recently. 

I am using this js file 

``` js
    var page = require('webpage').create(),
    system = require('system'),
    address, output, size;

    address = system.args[1];
    output = system.args[2];
    page.viewportSize = { width: 1024, height: 800 };
    page.settings.userAgent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36';
    page.open(address, function (status) {
        if (status !== 'success') {
            console.log('Unable to load the address!');
            phantom.exit(1);
        } else {
            window.setTimeout(function () {
                page.render(output);
                phantom.exit();
            }, 200);
        }
    });
```

With `page.settings.userAgent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36';` the image that is rendered does not have the fonts displayed correctly. However, without that line, everything looks fine. 

I am thinking there is a setting that this override but I am unable to find anything.

**Comment by amir20** [comment]
Interesting find @abuchanan920. I would have never guessed that. I complied it using those parameters. But I haven't tested it.

**Comment by lukepolo** [comment]
Just ran into the same issue , may try to compile with @abuchanan920 's comment

**Comment by oliveremberton** [comment]
I can confirm @abuchanan920 's explanation and have a crude workaround.

1. Google Web Fonts is trying to detect the capabilities of your browser to serve either TTF or WOFF fonts. When you set a modern custom user agent (e.g. iPhone) it thinks you have a WOFF capable browser and sends you those. But...

2. PhantomJS doesn't handle WOFF correctly.

However if you look at [the source for Google Web Fonts](https://github.com/typekit/webfontloader/blob/31360f277746d9ee72b758af5f12ee31e5a83795/src/core/fontwatchrunner.js), they detect an edge case for old versions of WebKit (AppleWebKit/536.11 and older), which forces the use of TTF.

So if you add `AppleWebKit/534.34` to the end of your normal user agent, Google will serve Phantom TTF fonts and everything seems to work. From what I can tell, this frankenstein user agent still works as an iPhone or other device, as most browser detection is done by crude regex, and doesn't get confused by the extra AppleWebKit.

**Comment by istr** [comment]
> Compile like this to get QtWebKit to actually USE libz (as opposed to simply recognizing that it is present): " ./build.sh --confirm --qmake-args WEBKIT_CONFIG+='use_zlib' "

I can confirm @abuchanan920 that this produces a build (2.0.0) that passes e.g. [this regression test](https://github.com/jory/phantom-test).
