### ISSUE TITLE
Crash plz fix

### ISSUE THREAD

**Issue by KuTi** [ariya/phantomjs#12688]
Please fix

[Download: https://www.dropbox.com/s/lupl1f3qsafa23g/76f1ee39-f42f-fc55-4e51fb62-193c82be.dmp?dl=0](https://www.dropbox.com/s/lupl1f3qsafa23g/76f1ee39-f42f-fc55-4e51fb62-193c82be.dmp?dl=0)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
