### ISSUE TITLE
Phantom crashes when clicking button

### ISSUE THREAD

**Issue by mhenrixon** [ariya/phantomjs#12699]
This is related to teampoltergeist/poltergeist/issues/548 but I am not sure who can help me so crossposting here.

I have no idea what to do about the crash dump since I am on mac os x but like I mentioned in the poltergeist issue selenium handles clicking the button just fine.

**Comment by tgjonestx** [comment]
I hit the same symptoms on Linux. There's a crash dump report in issue #13055

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (200/200 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:47929 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1apkMe-003Gt6-Cg
	for andre@castonguay.org; Mon, 11 Apr 2016 18:31:25 -0400
Date: Mon, 11 Apr 2016 15:30:44 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1460413844;
	bh=uHYyTf3UlwHk599O4/GIqOusAoTJK7xZngXr0KCtjKI=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=CROLjIEUCy8cjEGCxpqwEcFBokhvwjlxiCypBgFezD9L1lIhFRFexgEL/wvknhWJU
	 epBUHhR6BHVxD3asbBofLsudACzTaomZ7FMT5fjAX4gHeS1oI8dyr1B4FSPUMflv3I
	 mw2NyOT1A8nN2Q5RIXND9Y+NvnTmqyDO4ziIsHo8=

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (201/200 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:28678)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-cf68-andre=castonguay.org@sgmail.github.com>)
	id 1apkMf-003Gu9-EO
	for andre@castonguay.org; Mon, 11 Apr 2016 18:31:26 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=DnLWikXI+qCsLwa2IqmXxm6UP7g=; b=gGDtDE6+93iwgBWr
	n96RaVBra3Ylf9Y9NDmi8Pp3gv/KBJLRyEHe9taKRer41jTuJujRhud9aofevNSQ
	1/1ns7E9d7BMoqH2k+BFQtUf70SMdwLkcmEBc8ws/zGxOimr8kgiBebiQo58X5m4
	iJqfJe9yoR8aGLjUFRJ93qNpSaE=
Received: by filter0915p1mdw1.sendgrid.net with SMTP id filter0915p1mdw1.14324.570C25941C
        2016-04-11 22:30:44.364292448 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id 00EyWzpbRM647X3vnRYAuw
	for <andre@castonguay.org>; Mon, 11 Apr 2016 22:30:44.291 +0000 (UTC)
Date: Mon, 11 Apr 2016 15:30:44 -0700
