### ISSUE TITLE
Feature request: Generate XPath from a DOM element

### ISSUE THREAD

**Issue by vporton** [ariya/phantomjs#12708]
There should be a function which given a DOM element, generates an XPath uniquely identifying this element:

  var path = page.domToXPath(function() {
    return document.getElementById('test');
  });

This XPath can be later be used for example for click().

**Comment by ariya** [comment]
I agree with @JamesMGreene, this can be implemented as a module that can be shared with other users. Perhaps, it even makes sense to make it a feature of e.g. CasperJS.
