### ISSUE TITLE
phantomjs 1.9.8 crash on OS X Yosemite 10.10

### ISSUE THREAD

**Issue by kodeninja** [ariya/phantomjs#12709]
After upgrading to OS X Yosemite recently, I'm running into a phantomjs crash. The stacktrace for the same is available at https://dl.dropboxusercontent.com/u/15699334/phantomjs198-macosx-yosemite1010-crash-stacktrace.txt

It was generated by following the OS X-specific instructions described at http://phantomjs.org/crash-reporting.html.

The scenario is `spritesmith` being used to process image sprites, using phantomjs as one of the engines. This is run as a grunt task in my node.js app.

This is an official phantomjs binary for OS X, installed from https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip.

`node -v 0.10.32`
`npm -v 1.4.21`
`phantomjs -v 1.9.8`

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
