### ISSUE TITLE
Bandwidth limit

### ISSUE THREAD

**Issue by abozhilov** [ariya/phantomjs#12733]
Will be really useful if I can set the bandwidth limit as command line option. e.g. 

`./phantomjs --limit-rate <rate>` 

Any chance to be added in phantomjs?

**Comment by joafeldmann** [comment]
+1 for this feature

**Comment by marius1512** [comment]
+1

**Comment by nesk** [comment]
+1

Chrome already implements an equivalent feature in the mobile view, it would be awesome if it could be added to PhantomJS!

![capture d ecran 2015-04-13 a 13 17 44](https://cloud.githubusercontent.com/assets/817508/7114653/c52a32e0-e1df-11e4-8099-3899ba74e1c7.png)

**Comment by angelomichel** [comment]
+1 would like to see this feature

**Comment by doctorconceptual** [comment]
+1

**Comment by tole42** [comment]
+1
