### ISSUE TITLE
SSL Handshake fails for specific host setups on Mac OS X 10.10 (Yosemite)

### ISSUE THREAD

**Issue by Senci** [ariya/phantomjs#12746]
Hey there.
PhantomJS fails the SSL Handshake on Yosemite (the current Mac OS X Version) for specific setups.
I've tested this with _PhantomJS 1.9.8_ on _Mavericks (Mac OS X 10.9)_, _Yosemite (OS X 10.10)_ and _Ubuntu 10.04_. With _Mavericks_ and _Ubuntu_ there is no Errors, **only _Yosemite_ has problems with this specific SSL Handshake**.

The host I'm talking about is _https://www.kreditkartenbanking.de_.

I've written some simplified code to test and debug the error:

```
var page = require('webpage').create();    

page.onResourceError = function(resourceError) {
  console.log('Unable to load resource (#' + resourceError.id + 'URL:' + resourceError.url + ')');
  console.log('Error code: ' + resourceError.errorCode + '. Description: ' + resourceError.errorString);
};

page.open('https://www.kreditkartenbanking.de', function() {
  phantom.exit();
});
```

On _Yosemite_ I get the following Console-Output when issuing the script:

```
Unable to load resource (#1URL:https://www.kreditkartenbanking.de/)
Error code: 6. Description: SSL handshake failed
```

It is possible to surpress the Errors and access the host with the `--ignore-ssl-errors=yes` option. Unfortunately this is no option for me. I would really appreciate it if someone could tell me why this Issue exists and how to fix it properly.

Best wishes,
Senad

---

**UPDATE**
I noticed further Information in the debug-output.

```
[DEBUG] Network - SSL Error: "The root certificate of the certificate chain is self-signed, and untrusted"
[DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://www.kreditkartenbanking.de/"
```

I've looked up the certificate chain and the [List of available trusted root certificates](http://support.apple.com/en-us/HT6005). The "Entrust Root Certification Authority" is listed with the root Certificate, although the intermediate certificate is missing.

I've tried to find out which default CA certificate store phantomjs is accessing but I had no luck yet.

**Comment by ariya** [comment]
Can you try it again with PhantomJS 2.1?

When I run on your example script (Yosemite, PhantomJS 2.1), I don't get the "SSL handshake failed" error anymore.

**Comment by pencilcheck** [comment]
Workaround: http://stackoverflow.com/questions/25706563/ruby-phantom-js-blocked-on-specific-site
