### ISSUE TITLE
Tab is clickable through chrome browser but not in phantomjs??

### ISSUE THREAD

**Issue by DivyaAshok** [ariya/phantomjs#12743]
Hello,
I have a problem, where in I have a tab with an "id" which is clicked fine when the protractor test runs on a chrome browser. But the same piece of below code throws error when I run it in phantomjs.
I had a similar problem earlier and setting the browser size like below had solved that issue. I have gone really big with the browser size yet the element is not available to click. I have pasted the stacktrace below, any help is appreciated. And the line it breaks is the "click" line.

Thanks,
Divya

```
       expect(ptor.isElementPresent(protractor.By.id('Studies'))).toBe(true);
       ptor.findElement(protractor.By.id('Studies')).click();

        browser.driver.manage().window().setSize(1280, 1024);
        expect(ptor.isElementPresent(protractor.By.id('newStudy'))).toBe(true);
        ptor.sleep(25000);
        ptor.findElement(protractor.By.id('newStudy')).click();
```

UnknownError: {"errorMessage":"Element is not currently visible and may not be manipulated","request":{"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"27","Content-Type":"application/json; charset=utf-8","Host":"localhost:15506","User-Agent":"Apache-HttpClient/4.3.2 (java 1.5)"},"httpVersion":"1.1","method":"POST","post":"{\"id\":\":wdc:1415031743552\"}","url":"/click","urlParsed":{"anchor":"","query":"","file":"click","directory":"/","path":"/click","relative":"/click","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/click","queryKey":{},"chunks":["click"]},"urlOriginal":"/session/95f2fa90-6375-11e4-b4e1-f5967c04bd96/element/%3Awdc%3A1415031743552/click"}}
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:03'
System info: host: 'blah.blah', ip: 'xxx.xx.xx.xx', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.5', java.version: '1.7.0_67'
Driver info: driver.version: unknown

**Comment by sJeet** [comment]
Hi @DivyaAshok , did you fine the solution of this issue? I am having same problem on PhantomJS but not with Chrome. Though I am running Chrome on OS X while I am running PhantomJS on Linux.

I am stuck in this issue for very long, and your help will be greatly appreciated.

**Comment by ziki17** [comment]
Hi @DivyaAshok and @sJeet , We had the same issue. We were able to solve the issue. The issue is that you are not able to click even normal with Javascript. You need to let PhantomJs know the div which is clickable. In our case we were able to use <a> hyperlink. 

For example, we have a jobsTab and made it clickable with:

jobsTab { $("#unified-tab #unified-jobs a") }

This was a element in our page. And you can make it easily click as:

jobsTab.click()
