### ISSUE TITLE
Error in `phantomjs': double free or corruption (!prev)

### ISSUE THREAD

**Issue by l15k4** [ariya/phantomjs#12765]
I have no idea why it started to do this, what I did :-/

I'm using master, commit eddb0db1d253fd0c546060a4555554c8ee08c13c from Fri Oct 10 06:40:42 2014

Dump is attached. 

[4f1d6457-46fc-9bae-5d548296-12425060.dmp | uploaded via ZenHub](https://files.zenhub.io/54712d65dc56c6957ac28796)

**Comment by logbird** [comment]
@ariya I have a same problem!
