### ISSUE TITLE
Crash on 1.9.8

### ISSUE THREAD

**Issue by coolglacier** [ariya/phantomjs#12767]
Crash encountered running PhantomJS 1.9.8 on CircleCI.

Dump here: https://dl.dropboxusercontent.com/u/70299014/3176409c-bf01-cd9f-156cebbd-0d9a92da.dmp

Thanks,
Jeremy

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
