### ISSUE TITLE
Incorrect JS number-to-string conversion for radices other than 10

### ISSUE THREAD

**Issue by wilkinson** [ariya/phantomjs#12764]
Problem
=======

The `Number.prototype.toString` method is not computing correct results (which are defined here as "the results returned by command-line debugging shells for JavaScriptCore, Spidermonkey, and V8 as well as the developer consoles inside Chrome, Firefox, and Safari").

Test cases
---------------
```js
(0.001).toString(16)   // returns "0",  but should return "0.004189374bc6a7f"
(1.001).toString(16)   // returns "1",  but should return "1.004189374bc6a"
(-0.001).toString(16)  // returns "-0", but should return "-0.004189374bc6a7f"
(0.0005).toString(16)  // returns "0",  but should return "0.0020c49ba5e353f8"
```

Hypothesis
---------------
Somehow, this conversion is *not* being handled by JavaScriptCore like it should be, because these results are computed correctly in the command-line JSC debugging shell available on OS X and in the developer console in Safari.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
