### ISSUE TITLE
phantom doesn't load content of page as chromedriver (page has flash)

### ISSUE THREAD

**Issue by arisAlexis** [ariya/phantomjs#12784]
I have a problem running selenium tests with phantomjs from Java. I am aware that phantomjs doesn't support flash. I am running dual tests with chromedriver without flash enabled and phantom. on a page that chromedriver displays no flash plugin enabled, it just loads the rest of the page and reads it correctly. The phantom tests throw an exception of timeout to an element but thats normal because the screenshot shows that the page doesn't load.

The code to reproduce the problem follows:

public void test() throws InterruptedException {
    //System.setProperty("webdriver.chrome.driver", Application.chromeDriverPath);
    //WebDriver driver= new ChromeDriver();
    WebDriver driver=new PhantomJSDriver();
    driver.manage().timeouts().pageLoadTimeout(60, TimeUnit.SECONDS);
    driver.manage().window().setSize(new Dimension(1280, 800));

```
driver.get("http://www.betfred.com/sport");

WebElement footballLink=driver.findElement(By.linkText("Football"));
footballLink.click();

WebDriverWait wait = new WebDriverWait(driver, 10);
WebElement europeanLink= wait.until(ExpectedConditions.visibilityOfElementLocated(By.partialLinkText("European Leagues")));
europeanLink.click();

    wait = new WebDriverWait(driver, 10);
    WebElement leagueLink= wait.until(ExpectedConditions.visibilityOfElementLocated(By.partialLinkText("Swiss Super League")));
    leagueLink.click();

    wait = new WebDriverWait(driver, 10);
    WebElement finalLeagueLink=wait.until(ExpectedConditions.elementToBeClickable((By.xpath("//a[contains(text(),'Swiss Super League') and contains(@class,'action')]"))));
    Thread.sleep(1000);
    finalLeagueLink.click();

driver.switchTo().frame("sportframe");

wait = new WebDriverWait(driver, 30);
wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//span[contains(text(),'Swiss Super League')]")));
```

}

test passes with chromedriver

**Comment by williamjablonski** [comment]
Phantom Driver doesn't have support for Flash technology. This doing only Java Script .

**Comment by arisAlexis** [comment]
the page has a flash object but the target html I want to get is not in this object. I guess it is blocking the rendering.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://fusion.l50sw.com/am.php?81>

 

klaus@hebsgaard.dk

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://learningsolutionsaz.com/sofa.php?w8hp5>

 

klaus@hebsgaard.dk
