### ISSUE TITLE
classList API incorrectly supported

### ISSUE THREAD

**Issue by mixonic** [ariya/phantomjs#12782]
![screenshot of phantom vs. Chrome](https://api.monosnap.com/image/download?id=6RvUU7eSKBsPBwdmqNXb2lAt5vKpAF)

On phantomjs 1.9.8, the `classList` API is nominally supported but practically broken. `className` is not updated with additional classes, and neither is the DOM updated for attached elements.

**Comment by eps90** [comment]
I've found also that `toggle` on `classList` works incorrectly.
```javascript
element.classList.toggle('aa'); element.classList;
// ["aa"] <- that's ok
element.classList.toggle("aa", false); element.classList;
// ["aa"] <- should be removed
```

**Comment by Spaxe** [comment]
I've also just bumped into this issue. What's the current resolution of this?

**Comment by eps90** [comment]
I solved this by manually checking if class exists in `classList` and then calling proper action:

```javascript
element.querySelector('selector').classList.add('someclass');
// or:
element.querySelector('selector').classList.remove('someclass');
```

**Comment by Spaxe** [comment]
Turns out my issue is a little different—I was trying to use classList on a SVG. That doesn't work according to the specs. 

My workaround that works for me is

```javascript
element.querySelector('selector').setAttribute('class', 'someClass');
```

... and so on.

**Comment by eps90** [comment]
Of course your solution gonna work if there were no `class` attribute previously (which is not a big problem to concatenate with existing class ;) )

**Comment by Spaxe** [comment]
@eps90 Yeah, sorry I omitted a lot of code. The "and so on" includes many more things, this one just overrides the className properly for SVGs. The issue was that `classList.add` for a SVG wasn't consistent in behaviour in both browser and many unittesting packages.

**Comment by zackw** [comment]
The code responsible for `classList` is part of Webkit; the version of Webkit in PhantomJS 1.x is rather old and won't be updated further.  PhantomJS 2.0 has a much newer Webkit which *may* have fixed these problems, but without a self-contained test case, I can't easily check.  Would any of you mind testing PhantomJS 2.0 and letting us know whether it resolves these problems?

**Comment by eps90** [comment]
@zackw Sure, I'll check it in free time.

**Comment by zackw** [comment]
@eps90  Thank you.

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thanks!
