### ISSUE TITLE
Output to /dev/stdout not working

### ISSUE THREAD

**Issue by Synchro** [ariya/phantomjs#12780]
Despite #10973 being closed, and the docs saying this works, I can't make this work. I'm running 1.9.8 on Linux. While the unit tests are linked to that ticket, they don't actually contain any tests for stdout.

These scripts should produce the same result:

``` javascript
var page = require('webpage').create();
page.open('http://synchro02.synchromedia.co.uk/', function() {
  page.render('g1.png');
  phantom.exit();
});
```

Call this one as `phantomjs script2.js > g2.png`

``` javascript
var page = require('webpage').create();
page.open('http://synchro02.synchromedia.co.uk/', function() {
  page.render('/dev/stdout');
  phantom.exit();
});
```

but the second one produces an empty file. Enabling debug mode produces identical output for both scripts. To avoid content issues, the page these scripts loads does not contain any javascript, just a simple HTML4 doc with a text body.

Have I missed something?

**Comment by guidoman** [comment]
I'm having the same problem with phantom 1.9.8. The following code is working on Mac OS X but not on linux (the output is empty):
```javascript
page.open(address, function (status) {
        if (status !== 'success') {
            console.log('Unable to load the address!');
            phantom.exit(1);
        } else {
            window.setTimeout(function () {
                page.render('/dev/stdout', { format: 'pdf' });
                phantom.exit();
            }, 200);
        }
    });
```

**Comment by chompomonim** [comment]
I think you should use `/process/stdout/write' instead of `/dev/stdout`. 

`/dev/stdout` is not in POSIX and as far as I know is used mainly in FreeBSD and MacOSX. In Linux you should use tty.

**Comment by guidoman** [comment]
Thanks for your comment, but it seems it makes no difference. Anyway, both on Linux and Mac OS X /dev/stdout is a symlink...

**Comment by flesler** [comment]
+1, works locally on WIndows, fails online on AWS.
Had to roll-back to renderToBase64 for now.

**Comment by nickolaylavrinenko** [comment]
+1, faced with same problem on Ubuntu 14.04.3 LTS, on Mac OS X works fine.

**Comment by SeaOfTea** [comment]
Any updates to this? Still seems to be failing. CentOS 6.7 here.
stdout is empty

**Comment by eddydarell** [comment]
Facing the same issue on Ubuntu 16.04

**Comment by thelordgabo** [comment]
Did not work for me also in windows 7, node 6.9.1, and phantomjs-prebuilt 2.1.13.

**Comment by nicbarker** [comment]
This is still broken for me on Digital Ocean Ubuntu 16.04, works fine on my local machine (OSX El Cap)

**Comment by nicbarker** [comment]
For anyone who finds this later, you may have had the same issue as me:
`user@vps-server:~$ echo 'test' > /dev/stdout
bash: /dev/stdout: Permission denied`
It turns out that using the `su` command to change user to something other than root actually doesn't update where /dev/stdout points (it's still pointing to a file descriptor owned by root)
See here:
https://unix.stackexchange.com/questions/38538/bash-dev-stderr-permission-denied
After sshing back into the server _as_ the deprivileged user, `/dev/stdout` is now owned by the current user and phantomjs can output to it fine.
