### ISSUE TITLE
crash report 1.9.8

### ISSUE THREAD

**Issue by xini** [ariya/phantomjs#12799]
version: phantomjs-1.9.8-linux-x86_64
os: CLOUDLINUX 6.6 x86_64
The script works when I run it as root. When I run it as other user it segfaults.

**Comment by designboxcom** [comment]
How did you resolve this?

**Comment by xini** [comment]
The whole thing came down to how phantomjs allocates memory. At the start of the script it seems to just allocate memory until it gets a fault, just to see how memory it can use. Since the memory allocation in CloudLinux is restricted for all users but root, the script segfaults.
I had to increase the virtual memory limit in CloudLinux to 1.5G with the physical limit being 1G. With that the script runs fine from the command line.
Even with that set phantomjs didn't work using the exec command in PHP. It again segfaulted. I could fix that by using the 32bit version of phantomjs (although the server is 64bit).

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
