### ISSUE TITLE
Rendering with focus state 

### ISSUE THREAD

**Issue by joshrp** [ariya/phantomjs#12796]
I'm having an issue with a seemingly hard to google problem. 

I'm loading a page find and rendering OK with clicking around hover states and everything playing nice. I can simulate tabbing through the page and the `document.activeElement` updates and enter events will navigate and such. 

Problem: When rendering to an image focus state styles aren't rendered. Hover state is and everything else seems fine. 

I've tried this on multiple sites, verifying that tabbing is actually moving between elements and that there are very obvious focus states on the items, but still get nothing rendered.

Ideas? Or is this a bug?

Phantom 1.9.7 inside this container: https://registry.hub.docker.com/u/ubermuda/phantomjs/

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://edupeet.com/specify.php?tqrm>

 

klaus@hebsgaard.dk
