### ISSUE TITLE
SSL errors on Mac OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by walles** [ariya/phantomjs#12790]
Try this on a Mac OS X 10.10 Yosemite system:
- git clone https://github.com/spotify/threaddump-analyzer.git --branch phantomjs-repro
- cd threaddump-analyzer
- npm install
- phantomjs --debug=true ./node_modules/gulp-qunit/runner.js test.html

Current result:
- Output says PhantomJS won't load https://code.jquery.com/qunit/qunit-1.15.0.js because of "Network - SSL Error: "The certificate has expired"", and "Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://code.jquery.com/qunit/qunit-1.15.0.js"". The test run then fails.

Expected result:
- PhantomJS should just have loaded the given URL.

Notes:
- Chrome says the certificate is fine and that the certificate expires in July 2015 (in half a year).
- This issue does not trigger on Linux, don't know about other versions of Mac OS X.
- This ticket might be related to #12746 which has similar (but not the same) symptoms.

**Comment by mythosil** [comment]
Same issue on mavericks when I installed phantomjs with homebrew.
Downloading certificate and specifying SSL_CERT_DIR fixed for me.
I hope this helps.
```
$ wget -O /usr/local/etc/openssl/certs/cacert.pem http://curl.haxx.se/ca/cacert.pem
$ SSL_CERT_DIR=/usr/local/etc/openssl/certs phantomjs --debug=true test.js
```

**Comment by caboteria** [comment]
Same problem here.  Happens only on my laptop running OSX 10.10.1.  Phantomjs 1.9.8.0 installed by the phantomjs gem version 1.9.8.0.  Attempting to load a page that references bootstrap js and css on netdna.bootstrapcdn.com fails with:

```
2015-01-21T14:28:37 [DEBUG] Network - SSL Error: "The certificate has expired" 
2015-01-21T14:28:37 [DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" 
2015-01-21T14:28:37 [DEBUG] WebPage - updateLoadingProgress: 23 
2015-01-21T14:28:37 [DEBUG] Network - SSL Error: "The certificate has expired" 
2015-01-21T14:28:37 [DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js" 
```
Both Firefox and Chrome report that the certificates are valid.

**Comment by ariya** [comment]
Can you try it again with new PhantomJS 2.1?

When I gave it a try, it showed the following:
```bash
$ phantomjs ./node_modules/gulp-qunit/runner.js test.html 

Took 42ms to run 54 tests. 54 passed, 0 failed.
ReferenceError: Can't find variable: QUnit

  undefined:5
  :0 in exit
  phantomjs://code/runner.js:56 in onCallback
  phantomjs://platform/webpage.js:146 in connector
  :0 in call
  :1 in callPhantom
  :55
  https://code.jquery.com/qunit/qunit-1.15.0.js:691 in runLoggingCallbacks
  https://code.jquery.com/qunit/qunit-1.15.0.js:476 in done
  https://code.jquery.com/qunit/qunit-1.15.0.js:601 in process
  https://code.jquery.com/qunit/qunit-1.15.0.js:182
ReferenceError: Can't find variable: QUnit

  undefined:5
  :0 in exit
  phantomjs://code/runner.js:56 in onCallback
  phantomjs://platform/webpage.js:146 in connector
  :0 in call
  :1 in callPhantom
  :55
  https://code.jquery.com/qunit/qunit-1.15.0.js:691 in runLoggingCallbacks
  https://code.jquery.com/qunit/qunit-1.15.0.js:476 in done
  https://code.jquery.com/qunit/qunit-1.15.0.js:601 in process
  https://code.jquery.com/qunit/qunit-1.15.0.js:182
```

Obviously something is still wrong with those `ReferenceError` but I don't see any "Network - SSL Error" (even with `---debug=true`).

**Comment by walles** [comment]
@ariya, with PhantomJS 2.1.1 I get the same output you posted.

**Comment by ariya** [comment]
@walles Do you think that this issue is resolved for you?

**Comment by walles** [comment]
Not really.

What I'm trying to do still doesn't work even though it seems like it should.

And without anybody being able to point out the change that fixed this (if it actually is fixed), this new output could simply be hiding my original problem.

**Comment by pencilcheck** [comment]
Workaround: http://stackoverflow.com/questions/25706563/ruby-phantom-js-blocked-on-specific-site
