### ISSUE TITLE
1.9.8 crashes with the following stack trace running Jasmine specs

### ISSUE THREAD

**Issue by robmadole** [ariya/phantomjs#12792]
The following crash generated this stack trace:

https://gist.github.com/robmadole/2abdb543c46dc691cbe9

I am using Grunt with grunt-contrib-jasmine to run our specs. The binary that I used was `phantomjs-1.9.8-linux-x86_64`.

The Jasmine specs are from a private repository. If it's necessary for me to get the offending test case to reproduce the problem let me know and I can ask if we can open this up.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
