### ISSUE TITLE
Screen captures with text rendered as square

### ISSUE THREAD

**Issue by candido13** [ariya/phantomjs#12793]
As you can see on the attached file, the text with font-weight value at '600' is rendered as square.

![bug_font_weight](https://cloud.githubusercontent.com/assets/1814688/5264282/c89013f4-7a39-11e4-819b-1fb2315e7a35.jpg)

Html code of sample test :

<pre>
     p>Hello world!</p>
     p style="font-weight:400">400</p>
     p style="font-weight:500">500</p>
     p style="font-weight:600">600</p>
     p style="font-weight:bold">bold</p>
     p style="font-weight:normal">normal</p>
</pre>

**Comment by soulteary** [comment]
i have similar problem: https://github.com/n1k0/casperjs/issues/1376

**Comment by soulteary** [comment]
@candido13 hi, maybe  https://github.com/ariya/phantomjs/issues/10249  can help you.
