### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by fkowal** [ariya/phantomjs#12805]
when running protractor with phantomjs (i am a osx)
node_modules/.bin/phantomjs --webdriver=4445 --web-security=false --ignore-ssl-errors=true --load-images=false

node_modules/.bin/phantomjs -v
1.9.8

the process crashes
https://www.dropbox.com/s/3h7mvyqho69dq2m/AD322DE1-A95C-4A96-A8FB-E62F1198A2BD.dmp?dl=0

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
