### ISSUE TITLE
build issue in Mac

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#12804]
I'm trying to build phantomjs 2, in Mac which fails with the following error.

error: cannot initialize a parameter of type 'id<NSFileManagerDelegate>' with an lvalue of type 'NSObject<NSApplicationDelegate> _'
        [NSApp setDelegate:reflectionDelegate];
                           ^~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSFileManager.h:109:47: note: 
      passing argument to parameter 'delegate' here
@property (assign) id <NSFileManagerDelegate> delegate NS_AVAILABLE(10_5, 2_0);
                                              ^
1 error generated.
make[4]: *_\* [.obj/qcocoaapplicationdelegate.o] Error 1
make[4]: **\* Waiting for unfinished jobs....
make[3]: **\* [sub-cocoa-make_first] Error 2
make[2]: **\* [sub-platforms-make_first] Error 2
make[1]: **\* [sub-plugins-make_first] Error 2
make: **\* [sub-src-make_first] Error 2

Please provide support.
Thanks.

**Comment by ariya** [comment]
Not prioritized for now, the focus is on Linux (#15398).
