### ISSUE TITLE
phantomjs1.9.7 cannot extract text under svg element.

### ISSUE THREAD

**Issue by mlfz** [ariya/phantomjs#12813]
I have the following code in a unit test using webdriver that passes using phantomjs 1.9.0 but failed with phantomjs 1.9.7 (and 1.9.8):

```
axis_elem = webdriver.find_element_by_css_selector("#graph svg > g.highcharts-axis > text > tspan")
assert axis_elem.text == "X Axis"
```

With phantomjs 1.9.0, the `.text` returns "X Axis", but with phantomjs 1.9.7 and 1.9.8, it returns empty string thus failing the assertion above.

In fact, the return value of

```
webdriver.find_element_by_tag_name('body').text
```

is missing all elements texts under `<svg>` tags.

This appears to be a regression between the v1.9.0 and later version.

**Comment by vasanthv16** [comment]
I am seeing similar behavior. Seems like the following issues are related. No resolutions on these either, though.

https://github.com/detro/ghostdriver/issues/386
https://github.com/detro/ghostdriver/issues/405

**Comment by goodforenergy** [comment]
I am running into this at the moment, while using [Splinter](https://github.com/cobrateam/splinter) to find text elements inside an SVG. It works fine in Chrome, but fails in PhantomJS - even though if I get the html of the container, I can see the SVG and text elements present. Do you know of a workaround? It doesn't look like there's been much activity on any of the linked issues.
