### ISSUE TITLE
remote debugging is broken

### ISSUE THREAD

**Issue by vumaasha** [ariya/phantomjs#12814]
I followed the steps provided in the page http://phantomjs.org/troubleshooting.html. After starting the first tab, i ran __run() in console. debugger starts and debugging works fine in phantomjs context, when I want to open a second tab, I do not get a second link with about:blank. when I continue the debug point in first tab, it just goes and hangs. I guess, it is waiting in the debug point inside page evaluate however the webinspector is not able to catch that. To add, sometimes phantomjs also crashes.

phantomjs version:
1.9.8
Chrome version:
Chromium 37.0.2062.120 Ubuntu 12.04

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
