### ISSUE TITLE
Timezone bug for Europe/Moscow (MSK): UTC+27

### ISSUE THREAD

**Issue by shurup** [ariya/phantomjs#12812]
In PhantomJS 1.9.8, we have:
```javascript
console.log(new Date);
```
returning this:
```
Wed Dec 10 2014 13:27:06 GMT+2700 (MSK)
```

So, it deals with Moscow timezone as with UTC+27(!). It makes scripts think today is tomorrow. The should-be-value for Moscow is UTC+3.

**Comment by Vitallium** [comment]
Duplicate. Please see #11151
