### ISSUE TITLE
Phantomjs 1.9.8 linux not running & wrong version number

### ISSUE THREAD

**Issue by fatfantasma** [ariya/phantomjs#12818]
I tried updating from 1.9.7 to 1.9.8.  On my windows 7x64 dev system the upgrade with smooth and everything worked.

My production system is a Openshift (red hat) linux box.  1.9.7 works great.  In the past I have just downloaded the linux phantomjs 1.9.7 file from phantomjs.org to my windows system, unzipped, ftp'd to openshift, set the execution bit and everything worked fine.

I followed the above steps to upgrade to 1.9.8 on the linux box.  I now get a python error when phantomjs is run: 
An exception of type OSError occured, these were the arguments:
(8, 'Exec format error')

When trying to investigate, I tried to make sure I had the correct version by 'phantomjs -v' but got 1.9.7.  However, the file size was 37,700kb, the size of the new file.  Phantomjs 1.9.7 is 37,448kb.  Thinking I made a mistake I re loaded and uploaded the linux version of 1.9.8.  Now openshift linux box doesn't even recognize it as a proper file.

I have done file compares of both the original 1.9.8 that is recognized but gives 1.9.7 version number and the 1.9.8 that can't even execute.  They are the same.  Execution bit is on for all versions.

So I have two problems here that may or may not be related but are very bizarre.  I have seen several posts of the linux 1.9.8 having several crashes/problems. Does anybody have a clue what is really going on.  The 1.9.7 version works perfect in every way.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
