### ISSUE TITLE
Cannot build from source on Udoobuntu 

### ISSUE THREAD

**Issue by benoitguigal** [ariya/phantomjs#12826]
Hello, 

I am trying to build phantomjs from source on my [Udoo](http://www.udoo.org/ ) running [Udoobuntu](http://www.udoo.org/category/udoobuntu/). 
With version 1.9 I got the error: 
```
/usr/bin/ld: cannot find -lQtWebKit
/usr/bin/ld: cannot find -lQtGui
collect2: ld returned 1 exit status
make[1]: *** [../bin/phantomjs] Error 1
make[1]: Leaving directory `/home/ubuntu/git/phantomjs/src'
make: *** [sub-src-phantomjs-pro-make_default-ordered] Error 2
```
Furthermore, I have two warnings/errors during the "Building Qt and Webkit" 
```
WARNING: Failure to find: ../3rdparty/pixman/pixman-arm-neon-asm.S
```
and then 

```
make[1]: *** No rule to make target `../3rdparty/pixman/pixman-arm-neon-asm.S', needed by `.obj/release-static/pixman-arm-neon-asm.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/ubuntu/git/phantomjs/src/qt/src/gui'
make: *** [sub-gui-make_default-ordered] Error 2 
```

At the very beginning of the process, I also got:
```
Wayland auto-detection... ()
g++ -c -pipe -O2 -Wall -W  -I../../../mkspecs/linux-g++ -I. -o wayland.o wayland.cpp
wayland.cpp:41:28: fatal error: wayland-client.h: No such file or directory
compilation terminated.
make: *** [wayland.o] Error 1
Wayland disabled.
```

```
Testing size of pointers ... (/home/ubuntu/git/phantomjs/src/qt/mkspecs/linux-g++ yes /home/ubuntu/git/phantomjs/src/qt /home/ubuntu/git/phantomjs/src/qt)
rm -f ptrsizetest.o
rm -f *~ core *.core
g++ -c -pipe -O2 -Wall -W  -I../../../mkspecs/linux-g++ -I. -o ptrsizetest.o ptrsizetest.cpp
ptrsizetest.cpp: In function 'int main(int, char**)':
ptrsizetest.cpp:59:12: error: 'PointerSize' is not a member of 'QPointerSizeTest<4>'
make: *** [ptrsizetest.o] Error 1
Pointer size: 4 
```

Do you know what might be the problem ? 

Thanks a lot

**Comment by calbazasebastian** [comment]
For Ubuntu 14.04 you need to install libicu-dev package

**Comment by ikokostya** [comment]
@mugbya This problem with python 3. Use python 2 via virtualenv.

**Comment by odarbelaeze** [comment]
I have a mess with python 2 and 3, in some cases the compilation will fail in Ubuntu if the line 317 of this file:
https://github.com/ariya/phantomjs/blob/master/src/qt/qtwebkit/Source/JavaScriptCore/disassembler/udis86/itab.py#L317
is not changed for:

    operands = list(self.OperandDict.keys())

**Comment by Vitallium** [comment]
@odarbelaeze Python 3 is not supported.

**Comment by odarbelaeze** [comment]
@Vitallium my fault, I'm compiling v2.0.0 from source in Ubuntu (patched the line) and I might have started the process in a virtualenv with python3, I hope it works after compilation.

**Comment by Pithikos** [comment]
Ubuntu 15.04

  sudo apt-get install libicu-dev gperf bison libjpeg-dev -y
