### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by optimacy** [ariya/phantomjs#12824]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with phantomjs. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable phantomjs on @Sourcegraph by going to https://sourcegraph.com/github.com/ariya/phantomjs and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by ariya** [comment]
Please provide the detailed instructions and post it to [phantomjs-dev mailing list](https://groups.google.com/forum/#!topic/phantomjs-dev/).
