### ISSUE TITLE
Handle XMLHttpRequest timeout

### ISSUE THREAD

**Issue by rbelouin** [ariya/phantomjs#12837]
The XMLHttpRequest timeout attribute does not seem to be handled in PhantomJS, I currently have to write a `setTimeout(function() { xhr.abort(); }, interval)` in order to make my tests pass.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#timeout
http://www.w3.org/TR/XMLHttpRequest/#the-timeout-attribute

**Comment by vvo** [comment]
:+1:
