### ISSUE TITLE
Error on building with debugging symbols

### ISSUE THREAD

**Issue by vegetableman** [ariya/phantomjs#12833]
> Build with debugging symbols enabled:
```CFLAGS=-g CXXFLAGS=-g ./build.sh --qt-config '-webkit-debug' --qmake-args "QMAKE_CFLAGS=-g QMAKE_CXXFLAGS=-g"```

Error:``` -webkit-debug: invalid command-line switch```

OS: OSX 10.10.1

**Comment by jancurn** [comment]
I have the same problem when building PhantomJS 2 with debug symbols on Ubuntu 14.04:

    ubuntu@myhost:~/test/phantomjs$ ./deploy/build-and-package.sh
    Building Qt and PhantomJS with debugging symbols. If you have previously built without debugging symbols, you should run:

        $ git clean -xdff

    System architecture... (Linux 3.18.1-x86_64-linode50 x86_64)

    -webkit-debug: invalid command-line switch

**Comment by jancurn** [comment]
Changing  
    CFLAGS=-g CXXFLAGS=-g ./build.sh --confirm --qt-config '-webkit-debug' --qmake-args "QMAKE_CFLAGS=-g QMAKE_CXXFLAGS=-g" || exit 1 
to 
    CFG_WEBKIT=debug
    CFLAGS=-g CXXFLAGS=-g ./build.sh --confirm --qmake-args "QMAKE_CFLAGS=-g QMAKE_CXXFLAGS=-g" || exit 1
in deploy/build-and-package.sh seems to fix the problem

**Comment by DrMeers** [comment]
I came across the same error when following the instructions on http://phantomjs.org/crash-reporting.html to use `CFLAGS=-g CXXFLAGS=-g ./build.sh --qt-config '-webkit-debug' --qmake-args "QMAKE_CFLAGS=-g QMAKE_CXXFLAGS=-g"`

Based on the above, I'm attempting `CFLAGS=-g CXXFLAGS=-g CFG_WEBKIT=debug ./build.sh --qmake-args "QMAKE_CFLAGS=-g QMAKE_CXXFLAGS=-g"` hoping that the CFG_WEBKIT=debug variable is picked up somewhere?
