### ISSUE TITLE
SVG Wavy full lines not rendered properly to png

### ISSUE THREAD

**Issue by schrepfler** [ariya/phantomjs#12844]
When snap-shooting this page http://bramp.github.io/js-sequence-diagrams/ the full wavy lines are not rendered properly (they are empty), any idea what can be the problem, how can it be fixed?

**Comment by schrepfler** [comment]
And it 2.0.0 Final

**Comment by andrewwebber** [comment]
+1

**Comment by ankostyuk** [comment]
+1

http://www.creditnet.ru/nkbrelation/report?report.sharekey=mpbtceuuxykkdqky&lang=en

Google Chrome 42.0.2311.152 (64-bit) Mac OS X 10.9.5

![chrome-20150515](https://cloud.githubusercontent.com/assets/384381/7652356/8c47a338-fb14-11e4-830e-37ab7d79f63f.png)

PhantomJS 1.9.7 Mac OS X 10.9.5

![phantom-1_9_7-20150515](https://cloud.githubusercontent.com/assets/384381/7652377/b43adef0-fb14-11e4-96b4-a9f899760f09.png)
