### ISSUE TITLE
Some words in Chinese garbled

### ISSUE THREAD

**Issue by weiguang3100** [ariya/phantomjs#12840]
http://meiri.jguo.cn/mryr/2014/1209/59249.html   use gbk encoding but some words in Chinese garbled,
![gg](https://cloud.githubusercontent.com/assets/2399274/5505225/9d61428c-87c9-11e4-8d88-654eaf111a1f.png)

**Comment by wilsonpeng3** [comment]
I am facing with the same problem.

**Comment by bulain** [comment]
same problem to me.

**Comment by chdeducn** [comment]
phantom.outputEncoding="gb2312"

**Comment by liuhuiiris126** [comment]
English garbled to me. orz...
