### ISSUE TITLE
Phantomjs 1.9.8 crashing

### ISSUE THREAD

**Issue by ArsalanDotMe** [ariya/phantomjs#12857]
I'm controlling phantomjs from nodejs and scrolling down a page to load some dynamically loaded items.
Phantomjs often crashes in this scenario, sometimes very quickly, sometimes later.

Here is the stack trace.
http://pastebin.com/raw.php?i=aiAwLdFm

**Comment by ArsalanDotMe** [comment]
My guess is that it has something to do with resource received event or function.

**Comment by Vitallium** [comment]
This issue has been fixed in PhantomJS 2.
