### ISSUE TITLE
Executing script error

### ISSUE THREAD

**Issue by Zlob** [ariya/phantomjs#12853]
trying to execute this script:

``` javascript
var page = require('webpage').create();

page.onError = function onError(msg, trace) {
    console.log('Error ' + msg);
};

page.open('http://todomvc.com/', function(status) {
    if (status !== 'success') {
        console.log(status);
    } else {
        t = Date.now();
        console.log('Loading ' );
        console.log('Loading time ' + t + ' msec');
    }
    phantom.exit();
});
```

on phantomjs-1.9 output is - ReferenceError: Can't find variable: Window 
on phantomjs-2.0 - Error TypeError: undefined is not an object (evaluating 'a.**wrapper8e3dd93a60**')

But in real brouwser, such as chrome 39.0.2171.95 there is no problem or console errors.

**Comment by rarevalo13** [comment]
Running into the same problem.
