### ISSUE TITLE
Phantomjs 1.9.7 crash dump

### ISSUE THREAD

**Issue by adelinferaru** [ariya/phantomjs#12852]
Hi!

I am not able to make php-phantomjs generate website thumbshots because phantomjs is always crashing. Please see below the crash report.

Thank you in advance! 

Operating system: Linux
                  0.0.0 Linux 2.6.32-504.3.3.el6.x86_64 #1 SMP Wed Dec 17 01:55:02 UTC 2014 x86_64
CPU: amd64
     family 6 model 58 stepping 9
     8 CPUs

Crash reason:  SIGSEGV
Crash address: 0xbbadbeef

Thread 0 (crashed)
 0  phantomjs + 0xf8057
    rbx = 0xffffffffffffffff   r12 = 0x0000000003399ea0
    r13 = 0x000000000000007f   r14 = 0x00007f97beaf7820
    r15 = 0x00007f97beaf7720   rip = 0x00000000004f8057
    rsp = 0x00007fffc73de120   rbp = 0x7ff8000000000000
    Found by: given as instruction pointer in context
 1  phantomjs + 0xb31fd0
    rip = 0x0000000000f31fd1   rsp = 0x00007fffc73de130
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 2  phantomjs + 0xb88d65
    rip = 0x0000000000f88d66   rsp = 0x00007fffc73de180
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 3  phantomjs + 0x109ce0f
    rip = 0x000000000149ce10   rsp = 0x00007fffc73de1b0
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 4  phantomjs + 0xb89b2d
    rip = 0x0000000000f89b2e   rsp = 0x00007fffc73de1f0
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 5  phantomjs + 0x1cfeebd
    rip = 0x00000000020feebe   rsp = 0x00007fffc73de2d8
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 6  phantomjs + 0xf63b6
    rip = 0x00000000004f63b7   rsp = 0x00007fffc73de310
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 7  phantomjs + 0xe0a3f
    rip = 0x00000000004e0a40   rsp = 0x00007fffc73de320
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 8  phantomjs + 0x44573a
    rip = 0x000000000084573b   rsp = 0x00007fffc73de330
    rbp = 0x7ff8000000000000
    Found by: stack scanning
 9  phantomjs + 0x18957ff
    rip = 0x0000000001c95800   rsp = 0x00007fffc73de340
    rbp = 0x7ff8000000000000
    Found by: stack scanning
10  phantomjs + 0x4464e4
    rip = 0x00000000008464e5   rsp = 0x00007fffc73de3a0
    rbp = 0x7ff8000000000000
    Found by: stack scanning
11  phantomjs + 0xe0a3f
    rip = 0x00000000004e0a40   rsp = 0x00007fffc73de3f0
    rbp = 0x7ff8000000000000
    Found by: stack scanning
12  phantomjs + 0xb8b5b0
    rip = 0x0000000000f8b5b1   rsp = 0x00007fffc73de470
    rbp = 0x7ff8000000000000
    Found by: stack scanning
13  phantomjs + 0x11d381
    rip = 0x000000000051d382   rsp = 0x00007fffc73de490
    rbp = 0x7ff8000000000000
    Found by: stack scanning
14  phantomjs + 0xb900c
    rip = 0x00000000004b900d   rsp = 0x00007fffc73de4c0
    rbp = 0x7ff8000000000000
    Found by: stack scanning
15  phantomjs + 0x464b56
    rip = 0x0000000000864b57   rsp = 0x00007fffc73de4f0
    rbp = 0x7ff8000000000000
    Found by: stack scanning
16  phantomjs + 0xef146
    rip = 0x00000000004ef147   rsp = 0x00007fffc73de500
    rbp = 0x7ff8000000000000
    Found by: stack scanning
17  phantomjs + 0x195c167
    rip = 0x0000000001d5c168   rsp = 0x00007fffc73de528
    rbp = 0x7ff8000000000000
    Found by: stack scanning
18  phantomjs + 0xef1bf
    rip = 0x00000000004ef1c0   rsp = 0x00007fffc73de540
    rbp = 0x7ff8000000000000
    Found by: stack scanning
19  phantomjs + 0x827d0
    rip = 0x00000000004827d1   rsp = 0x00007fffc73de580
    rbp = 0x7ff8000000000000
    Found by: stack scanning

Thread 1
 0  libpthread-2.12.so + 0xb5bc
    rbx = 0x0000000002a84208   r12 = 0x0000000002a76160
    r13 = 0x00007f97bf5db9c0   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x000000371720b5bc
    rsp = 0x00007f97bf5dade0   rbp = 0x0000000000000000
    Found by: given as instruction pointer in context
 1  phantomjs + 0xddafb
    rip = 0x00000000004ddafc   rsp = 0x00007f97bf5dae10
    Found by: stack scanning
 2  libc-2.12.so + 0x95ff
    rip = 0x0000003716e09600   rsp = 0x00007f97bf5dae20
    Found by: stack scanning
 3  ld-2.12.so + 0x14804
    rip = 0x0000003716a14805   rsp = 0x00007f97bf5dae50
    Found by: stack scanning
 4  phantomjs + 0xddc98
    rip = 0x00000000004ddc99   rsp = 0x00007f97bf5dae90
    Found by: stack scanning
 5  libpthread-2.12.so + 0x79d0
    rip = 0x00000037172079d1   rsp = 0x00007f97bf5daea0
    Found by: stack scanning

Thread 2
 0  libc-2.12.so + 0xe1453
    rbx = 0x0000000000000000   r12 = 0x00007f97beac1d70
    r13 = 0x000000000000000c   r14 = 0x00007f97b8000a98
    r15 = 0x00007f97b8000d30   rip = 0x0000003716ee1453
    rsp = 0x00007f97beac1b40   rbp = 0x00007f97b80008e0
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1906326
    rip = 0x0000000001d06327   rsp = 0x00007f97beac1b50
    Found by: stack scanning
 2  phantomjs + 0x1e4a217
    rip = 0x000000000224a218   rsp = 0x00007f97beac1b70
    Found by: stack scanning
 3  libpthread-2.12.so + 0xeff
    rip = 0x0000003717200f00   rsp = 0x00007f97beac1b98
    Found by: stack scanning
 4  libpthread-2.12.so + 0x2d47
    rip = 0x0000003717202d48   rsp = 0x00007f97beac1ba0
    Found by: stack scanning
 5  phantomjs + 0x19075e6
    rip = 0x0000000001d075e7   rsp = 0x00007f97beac1be0
    Found by: stack scanning
 6  linux-gate.so + 0x951
    rip = 0x00007fffc73ff952   rsp = 0x00007f97beac1c00
    Found by: stack scanning
 7  librt-2.12.so + 0x3e45
    rip = 0x0000003717a03e46   rsp = 0x00007f97beac1c40
    Found by: stack scanning
 8  phantomjs + 0x1840b73
    rip = 0x0000000001c40b74   rsp = 0x00007f97beac1c60
    Found by: stack scanning
 9  phantomjs + 0x1840a78
    rip = 0x0000000001c40a79   rsp = 0x00007f97beac1ca0
    Found by: stack scanning
10  phantomjs + 0x1906fa5
    rip = 0x0000000001d06fa6   rsp = 0x00007f97beac1cb0
    Found by: stack scanning
11  phantomjs + 0x1908091
    rip = 0x0000000001d08092   rsp = 0x00007f97beac1d20
    Found by: stack scanning
12  phantomjs + 0x18dd4b4
    rip = 0x0000000001cdd4b5   rsp = 0x00007f97beac1d70
    Found by: stack scanning
13  phantomjs + 0x18ddca8
    rip = 0x0000000001cddca9   rsp = 0x00007f97beac1d80
    Found by: stack scanning
14  phantomjs + 0x18dd917
    rip = 0x0000000001cdd918   rsp = 0x00007f97beac1da0
    Found by: stack scanning
15  phantomjs + 0x17dfdf5
    rip = 0x0000000001bdfdf6   rsp = 0x00007f97beac1e00
    Found by: stack scanning
16  phantomjs + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f97beac1e50
    Found by: stack scanning
17  libpthread-2.12.so + 0x79d0
    rip = 0x00000037172079d1   rsp = 0x00007f97beac1ea0
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x0268dfff  phantomjs  ???  (main)
0x3716a00000 - 0x3716a1ffff  ld-2.12.so  ???
0x3716e00000 - 0x371718efff  libc-2.12.so  ???
0x3717200000 - 0x3717418fff  libpthread-2.12.so  ???
0x3717600000 - 0x3717803fff  libdl-2.12.so  ???
0x3717a00000 - 0x3717c07fff  librt-2.12.so  ???
0x3717e00000 - 0x3718083fff  libm-2.12.so  ???
0x3718200000 - 0x3718415fff  libz.so.1.2.3  ???
0x3718600000 - 0x371881dfff  libselinux.so.1  ???
0x3718e00000 - 0x3719015fff  libgcc_s-4.4.7-20120601.so.1  ???
0x3719200000 - 0x3719417fff  libresolv-2.12.so  ???
0x3719a00000 - 0x3719c03fff  libcom_err.so.2.1  ???
0x3719e00000 - 0x371a0f0fff  libstdc++.so.6.0.13  ???
0x371b200000 - 0x371b427fff  libexpat.so.1.5.2  ???
0x371ce00000 - 0x371d09cfff  libfreetype.so.6.3.22  ???
0x371d600000 - 0x371d835fff  libfontconfig.so.1.4.4  ???
0x3b69400000 - 0x3b6960afff  libkrb5support.so.0.1  ???
0x3b69800000 - 0x3b69ae5fff  libkrb5.so.3.3  ???
0x3b69c00000 - 0x3b69e43fff  libgssapi_krb5.so.2.2  ???
0x3b6a400000 - 0x3b6a62afff  libk5crypto.so.3.1  ???
0x3b6a800000 - 0x3b6aa6bfff  libssl.so.1.0.1e  ???
0x3fe8e00000 - 0x3fe91defff  libcrypto.so.1.0.1e  ???
0x7f97bf5e4000 - 0x7f97bf7e6fff  libkeyutils.so.1.3  ???
0x7f97bf7fb000 - 0x7f97bf7fdfff  87f5e051180a7a75f16eb6fe7dbd3749-le64.cache-3  ???
0x7f97bf7fe000 - 0x7f97bf806fff  b79f3aaa7d385a141ab53ec885cc22a8-le64.cache-3  ???
0x7fffc73ff000 - 0x7fffc73fffff  linux-gate.so  ???

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
