### ISSUE TITLE
Phantomjs-1.9.8 crashed with CasperJS

### ISSUE THREAD

**Issue by TaylorHub** [ariya/phantomjs#12858]
I'm using CasperJS (1.1.0-beta3) and PhantomJS (1.9.8).
Phantomjs often crashes.

Here is the stack trace.
http://pastebin.com/GzWVczM4

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
