### ISSUE TITLE
PhantomJS 1.9.8 Crashing Issue

### ISSUE THREAD

**Issue by Kannan24** [ariya/phantomjs#12854]
We are using PhantomJS for running the regression test cases. We are getting the following error when running the test.

PhantomJS has crashed. Please read the crash reporting guide at https://github.c
om/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.
com/ariya/phantomjs/issues/new with the crash dump file attached: C:\Users\TEMPD
E~1.004\AppData\Local\Temp\c35cce92-f449-400a-ab39-83fd2902e457.dmp

but dump file size is showing empty. And the PhantomJs.exe is taking high memory while running test cases.(max memory: 1.2 GB)

can someone help me to solve this issue.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
