### ISSUE TITLE
Cannot see the function onAdd()

### ISSUE THREAD

**Issue by Betlista** [ariya/phantomjs#12861]
I have really simple script, just to test method invoktion, but I cannot call the method from phantomjs:

ReferenceError: Can't find variable: onAdd betlista\scheduler.js : 23 :/modules/webpage.js : 281

**Comment by JamesMGreene** [comment]
Obviously we'll need to see your script, for starters, and possibly your web page contents/URL as well.

**Comment by Betlista** [comment]
Sorry I thought it would be possible to add attachment here, which is not :-/

Script:

var page = require('webpage').create();
console.log('The default user agent is ' + page.settings.userAgent);

var system = require('system');

page.onConsoleMessage = function(msg) {
    system.stderr.writeLine('console: ' + msg);
};

page.onError = function (msg, trace) {
    console.log(msg);
    trace.forEach(function(item) {
        console.log('  ', item.file, ':', item.line);
    })
}

page.open('http://czcholsint869:5555/WmRoot/scheduler.dsp?mode=useradd', function (status) {
	if (status !== 'success') {
		console.log( 'Unable to access network' );
	} else {
		console.log( 'Opened ok' );
		console.log(page.content); //page source
		var a = onAdd();
		console.log( 'onAdd=' + a );
		phantom.exit();
	}
});

log:

The default user agent is Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34
Opened ok
<html><head>

<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Expires" content="-1">


<title>IS Task Scheduler</title>
<link rel="stylesheet" type="text/css" href="webMethods.css">
<script src="webMethods.js.txt"></script>
<script src="scheduledservicesfilter.js.txt"></script>
<script language="JavaScript">
	function confirmPause () {
		return confirm("OK to pause the Scheduler?\nNo scheduled tasks will be initiated until the Scheduler is resumed.");
	}
	function confirmResume() {
		return confirm("OK to resume the Scheduler?\nThe Scheduler will proceed to initiate scheduled tasks.");
	}
</script>

</head>


<body onload="setNavigation('scheduler.dsp', '/WmRoot/doc/OnlineHelp/wwhelp.htm?context=is_help&amp;topic=IS_Server_CreateTaskScrn'); setDefaultSettings()">






<script language="JavaScript">

  function onAdd() {

    var type = "";

    // (1) validate service name
    var svc = document.schedule.service.value;
    var idx = svc.lastIndexOf(":");
    if (svc == "" || idx < 0 || idx > svc.length-1) {
      alert (
        "Specify service name in the form:\n\n"+
        "          folder.subfolder:service\n"
      );
      document.schedule.service.focus();
      return false;
    }

   // Validate user, schedule type
   if (document.schedule.runAsUser.value == "" )
   {
	alert("Specify user");
	document.schedule.runAsUser.focus();
	return false;
    }


   // If latenessAction is NOT "Run immediately", then Check for Lateness time
    var latenessActionList = document.schedule.latenessAction;
    var isLatenessActionChecked = false;
    for (var i=0; i<latenessActionList.length; i++) {
	if ( latenessActionList[i].checked)
		isLatenessActionChecked = true;
	if ( (latenessActionList[i].value == 1 && latenessActionList[i].checked) ||
	     (latenessActionList[i].value == 2 && latenessActionList[i].checked))
	{
		if ( document.schedule.lateness.value == "")
		{
			alert("Specify lateness (in minutes)");
			document.schedule.lateness.focus();
			return false;
		}
	}
    }
    if ( !isLatenessActionChecked ) {
	alert("Specify overdue option");
	return false;
    }

    // (3) determine type of service to be added
    var typeList = document.schedule.type;
    document.schedule.schaction.value='Add Task';
    for (var i=0; i<typeList.length; i++) {
      if (typeList[i].checked) type = typeList[i].value;

    }
    if ( type == "" ){
	alert("Specify schedule type");
	return false;
    }

    // (4) check inputs for that type

    // (4a) one-time tasks need a date and time
    if (type == "once") {
      var d = document.schedule.date.value;
      var t = document.schedule.time.value;
      if (d == "") {
        alert (
          "Specify date in the form:\n\n"+
          "          YYYY/MM/DD\n"
        );
        return false;
      }
      if (t == "") {
        alert (
          "Specify time in the form:\n\n"+
          "          HH:MM:SS\n"
        );
        return false;
      }
    }

   // (4b) repeating tasks need an interval
    else if (type == "repeat") {
      var i = document.schedule.interval.value;
      if (i == "") {
        alert ("Specify interval (in seconds)");
	document.schedule.interval.focus();
        return false;
      }
    }

    // (4c) complex tasks don't need anything specified -- if
    // nothing is specified, they'll be run every minute
    else {
	    // if it's complex, we need to copy the start/end values
		// into the fields with the right name.  We can't just specify
		// start-date, etc, twice (once for repeating, and once for
		// complex) because the form will submit both, and the IS will
		// pick up the blank value for repeating and ignore the proper one
		document.schedule['start-date'].value = document.schedule.sd2.value;
		document.schedule['start-time'].value = document.schedule.st2.value;
		document.schedule['end-date'].value = document.schedule.ed2.value;
		document.schedule['end-time'].value = document.schedule.et2.value;
    }




    document.schedule.submit();
  }

  function onUpdate() {
    document.schedule.schaction.value='Update Task';
    document.schedule.submit();
  }

  function validateTypeForLatesnessOpt(latenessAction)
  {
  	if (latenessAction.value == 0)
		document.schedule.lateness.disabled = true;
	else
		document.schedule.lateness.disabled = false;

	// If latenessAction is "Skip and run" option Then "Run Once" schedule type is Invalid
	if (document.schedule.type[0] != null) // Create Mode
	{
		if ( latenessAction.value == 1 )
			document.schedule.type[0].disabled = true;
		else
			document.schedule.type[0].disabled = false;
	}
  }

  function validateLatesnessOptForType(type)
  {
  	// If Schedule type is "Run Once" Then "Skip and run" latenessAction option is Invalid.
	if ( type.value == "once" )
		document.schedule.latenessAction[1].disabled = true;
	else
		document.schedule.latenessAction[1].disabled = false;
  }

  function setDefaultSettings()
  {
	if (document.schedule.type[0] != null)  // Create Mode
	{
		if ( document.schedule.latenessAction[0].checked)
			document.schedule.lateness.disabled = true;
		else
			document.schedule.lateness.disabled = false;
	}
	else
	{
		if ( document.schedule.latenessAction[0].checked)
		document.schedule.lateness.disabled = true;
	}
  }
</script>

<table width="100%">

<tbody><tr><td class="menusection-Server" colspan="7">
    Server &gt;
    Scheduler &gt;
    User Tasks &gt;
    New Task</td></tr>

  <form name="schedule" action="scheduler.dsp" method="POST"></form>
    <tr>
      <td colspan="2">
        <ul>
          <li><a href="scheduler.dsp">Return to Scheduler</a></li>
        </ul>

      </td>
    </tr>

    <tr>
      <td><img src="images/blank.gif" height="10" width="10" border="0"></td>
      <td>
        <table class="tableForm">
        

        <script type="text/javascript">
          var trgt = "";

          // define function to scroll through selections on
          // document.schedule.runAsUser
          function updateTargetSelector () {
            var sel = document.schedule.target;
            for (var i=0; i<sel.options.length; i++) {
              if (sel.options[i].value == trgt) sel.selectedIndex = i;
            }
          }
        </script>

        <tbody><tr><td class="heading" colspan="7">Service Information</td></tr>
        <tr>
          <td class="oddrow" colspan="2">Description</td>
          <td class="oddrow-l" colspan="5"><input name="description" size="40" value=""></td>
        </tr>
        <tr>
          <td class="evenrow" colspan="2">folder.subfolder:service</td>
          <td class="evenrow-l" colspan="5"><input id="service" name="service" size="40" value="">
		  
		  
			  <input type="hidden" name="scheduleDataStr" id="scheduleDataStr" value="">
		  
		  <link rel="stylesheet" type="text/css" href="subUserLookup.css">
		  <script type="text/javascript" src="subUserLookup.js"></script>
		  <script type="text/javascript">
		  	function showService() {
				var svc = document.getElementById("service").value;
				var idx = svc.lastIndexOf(":");
				if (svc == "" || idx < 0 || idx > svc.length-1) {
				  alert (
					"Specify service name in the form:\n\n"+
					"          folder.subfolder:service\n"
				  );
				  document.schedule.service.focus();
				  return false;
			    } else {
					var width = 280;
					var height = 350;
					if(is_csrf_guard_enabled && needToInsertToken) {
						showSub("scheduler-service-input-dummy.dsp?csrfTokenNm="+_csrfTokenNm_+"&csrfTokenVal="+_csrfTokenVal_+"&"+_csrfTokenNm_+"="+_csrfTokenVal_, width, height, null);
					} else {
						showSub("scheduler-service-input-dummy.dsp", width, height, null);
					}
				}
			}

			function getServiceName() {
				var service = document.getElementById("service");
				return service.value;
			}

			function setInputString(input) {
				document.schedule.scheduleDataStr.value = input;
			}

			function getInputString() {
				var inputStringField = document.getElementById("scheduleDataStr");
				return inputStringField.value;
			}
		  </script>
		  <a id="servicepopup" onclick="javascript:return showService();" onmouseover="this.style.cursor='pointer'">Assign Inputs<img border="0" align="bottom" src="icons/service_input.gif"></a>
		  </td>
        </tr>

	
	<script>
	  //This function can be changed to do something with the user
	  function callback(val){
	    document.schedule.runAsUser.value=val;
	  }
	</script>
        <tr>
          <td class="oddrow" colspan="2">Run As User</td>
          <td class="oddrow-l" colspan="5">
          <input name="runAsUser" size="12" value="">
	<link rel="stylesheet" type="text/css" href="subUserLookup.css">
	<script type="text/javascript" src="subUserLookup.js"></script>
	   <a class="submodal" href="subUserLookup.dsp"><img border="0" align="bottom" src="icons/magnifyglass.gif"></a>
          </td>
        </tr>
        

        <tr>
          <td class="evenrow" colspan="2">Target Node</td>
          <td class="evenrow-l" colspan="5">

		  
          <select name="target">
			<option value="$any">Any server</option>
                        
            <option value="czcholsint869.prg-dc.dhl.com">
                czcholsint869.prg-dc.dhl.com            </option>
                      </select>
                    </td>
        </tr>
				<tr><td class="subHeading" colspan="7">If the Task is Overdue</td></tr>
		<tr>
		  <td class="oddrow-l" colspan="7"><input name="latenessAction" checked="" onclick="validateTypeForLatesnessOpt(this)" value="0" type="radio">Run immediately</td>
		</tr>
		<tr>
		  <td class="evenrow-l" colspan="3"><input name="latenessAction" value="1" onclick="validateTypeForLatesnessOpt(this)" type="radio">Skip and run at next scheduled interval</td>
		  <td class="evenrow-l" colspan="4" rowspan="2">if more than <input name="lateness" size="12" value="" disabled=""> minutes late.</td>
		</tr>
		<tr>
		  <td class="oddrow-l" colspan="3"><input name="latenessAction" onclick="validateTypeForLatesnessOpt(this)" value="2" type="radio">Suspend</td>
		</tr>
	    



            <tr><td class="space" colspan="7">&nbsp;</td></tr>
    <tr><td class="heading" colspan="7">Schedule Type and Details</td></tr>
        <tr><td class="subHeading" colspan="7">One-Time Tasks</td></tr>
        <tr>
          <td class="oddrow-l" rowspan="2" valign="top">
            <input name="type" type="radio" onclick="validateLatesnessOptForType(this)" value="once">Run Once
          </td>
          <td class="oddrow" colspan="1">Date</td>
          <td class="oddrow-l" colspan="5">
            <input name="date" size="12" value=""> YYYY/MM/DD
          </td>
        </tr>
        <tr>
          <td class="evenrow" colspan="1">Time</td>
          <td class="evenrow-l" colspan="5">
              <input name="time" size="12" value=""> HH:MM:SS 
          </td>
        </tr>
        <tr><td class="subHeading" colspan="7">Repeating Tasks With a Simple Interval</td></tr>
        <tr>
          <td class="oddrow-l" rowspan="6" valign="top">
            <input name="type" type="radio" onclick="validateLatesnessOptForType(this)" value="repeat">Repeating
          </td>
              <td class="oddrow">Start Date</td>
              <td class="oddrow-l" colspan="6">
              <input name="start-date" value="" size="12"> YYYY/MM/DD <i>(optional)</i>
              </td>
    </tr>
            <tr>
              <td class="evenrow">Start Time</td>
              <td class="evenrow-l" colspan="6">
              <input name="start-time" value="" size="12"> HH:MM:SS <i>(optional)</i>
              </td>
            </tr>
            <tr>
              <td class="oddrow">End Date</td>
              <td class="oddrow-l" colspan="6">
              <input name="end-date" value="" size="12"> YYYY/MM/DD <i>(optional)</i>
              </td>
            </tr>
            <tr>
              <td class="evenrow">End Time</td>
              <td class="evenrow-l" colspan="6">
              <input name="end-time" value="" size="12"> HH:MM:SS <i>(optional)</i>
              </td>
            </tr>
    <tr>
    <td class="oddrow" colspan="1">Repeating</td>
          <td class="oddrow-l" colspan="5">
            <input type="checkbox" name="doNotOverlap" size="12" value="true"> Repeat after completion
          </td>

        </tr>
       <tr>
          <td class="evenrow" colspan="1">Interval</td>
          <td class="evenrow-l" colspan="5">
            <input name="interval" size="12" value=""> seconds<br>

          </td>
        </tr>

        <tr><td class="subHeading" colspan="7">Repeating Tasks with Complex Schedules</td></tr>
        <tr>
          <td valign="top" class="oddrow-l" rowspan="8">
            <input name="type" type="radio" checked="" onclick="validateLatesnessOptForType(this)" value="complex">Complex Repeating
          </td>
          <td class="oddrow">Start Date</td>
          <td class="oddrow-l" colspan="6">
          <input name="sd2" size="12"> YYYY/MM/DD <i>(optional)</i>
          </td>
        </tr>
        <tr>
          <td class="evenrow">Start Time</td>
          <td class="evenrow-l" colspan="5">
          <input name="st2" size="12"> HH:MM:SS <i>(optional)</i>
          </td>
        </tr>
        <tr>
          <td class="oddrow">End Date</td>
          <td class="oddrow-l" colspan="6">
          <input name="ed2" size="12"> YYYY/MM/DD <i>(optional)</i>
          </td>
        </tr>
        <tr>
          <td class="evenrow">End Time</td>
          <td class="evenrow-l" colspan="6">
          <input name="et2" size="12"> HH:MM:SS <i>(optional)</i>
          </td>
        </tr>
		<tr>
          <td class="oddrow" colspan="1">Repeating</td>
          <td class="oddrow-l" colspan="5">
            <input type="checkbox" name="doNotOverlap" size="12" value="true"> Repeat after completion
          </td>

        </tr>
        <tr>
          <td class="evenrow" rowspan="3">Run Mask</td><td class="evenrow-l">Months</td><td class="evenrow-l">Days</td><td class="evenrow-l">Weekly Days</td><td class="evenrow-l">Hours</td><td class="evenrow-l">Minutes</td>
        </tr>
        <tr>
          <td class="evenrow-l">
            <select name="month" size="7" multiple="">
            <option value="0">January</option><option value="1">February</option><option value="2">March</option><option value="3">April</option><option value="4">May</option><option value="5">June</option><option value="6">July</option><option value="7">August</option><option value="8">September</option><option value="9">October</option><option value="10">November</option><option value="11">December</option>            </select>
          </td>
          <td class="evenrow-l">
            <select name="mo_day" size="7" multiple="">
            <option value="0">1</option><option value="1">2</option><option value="2">3</option><option value="3">4</option><option value="4">5</option><option value="5">6</option><option value="6">7</option><option value="7">8</option><option value="8">9</option><option value="9">10</option><option value="10">11</option><option value="11">12</option><option value="12">13</option><option value="13">14</option><option value="14">15</option><option value="15">16</option><option value="16">17</option><option value="17">18</option><option value="18">19</option><option value="19">20</option><option value="20">21</option><option value="21">22</option><option value="22">23</option><option value="23">24</option><option value="24">25</option><option value="25">26</option><option value="26">27</option><option value="27">28</option><option value="28">29</option><option value="29">30</option><option value="30">31</option>            </select>
          </td>
          <td class="evenrow-l">
            <select name="wk_day" size="7" multiple="">
            <option value="0">Sunday</option><option value="1">Monday</option><option value="2">Tuesday</option><option value="3">Wednesday</option><option value="4">Thursday</option><option value="5">Friday</option><option value="6">Saturday</option>            </select>
          </td>
          <td class="evenrow-l">
            <select name="hour" size="7" multiple="">
            <option value="0">0</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option><option value="9">9</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option>            </select>
          </td>
          <td class="evenrow-l">
            <select name="min" size="7" multiple="">
            <option value="0">0</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option><option value="9">9</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option><option value="24">24</option><option value="25">25</option><option value="26">26</option><option value="27">27</option><option value="28">28</option><option value="29">29</option><option value="30">30</option><option value="31">31</option><option value="32">32</option><option value="33">33</option><option value="34">34</option><option value="35">35</option><option value="36">36</option><option value="37">37</option><option value="38">38</option><option value="39">39</option><option value="40">40</option><option value="41">41</option><option value="42">42</option><option value="43">43</option><option value="44">44</option><option value="45">45</option><option value="46">46</option><option value="47">47</option><option value="48">48</option><option value="49">49</option><option value="50">50</option><option value="51">51</option><option value="52">52</option><option value="53">53</option><option value="54">54</option><option value="55">55</option><option value="56">56</option><option value="57">57</option><option value="58">58</option><option value="59">59</option>            </select>
          </td>
        </tr>
        <tr>
          <td class="evenrow" colspan="5">
          <i>Selecting no items is equivalent to selecting all items for a given list</i>
          </td>
        </tr>

        
          <tr>
            <td class="action" colspan="7">
              <input type="hidden" id="oid" name="oid" value="">
              <input type="hidden" name="schaction">
                            <input type="button" value="Save Tasks" onclick="return onAdd();">
                          </td>
          </tr>



        
      

    </tbody></table>
    </td>
  </tr>
</tbody></table>



        
      
    






<div id="subMask"></div><div id="subContainer"><div id="subInner"><div id="subTitleBar"><div id="subTitle"></div><div id="subControls"><a onclick="hideSub(false);"><span>Close</span></a></div></div><iframe src="" style="width:100%;height:100%;background-color:transparent;" scrolling="auto" frameborder="0" allowtransparency="true" id="subFrame" name="subFrame" width="100%" height="100%"></iframe></div></div><div id="subMask"></div><div id="subContainer"><div id="subInner"><div id="subTitleBar"><div id="subTitle"></div><div id="subControls"><a onclick="hideSub(false);"><span>Close</span></a></div></div><iframe src="" style="width:100%;height:100%;background-color:transparent;" scrolling="auto" frameborder="0" allowtransparency="true" id="subFrame" name="subFrame" width="100%" height="100%"></iframe></div></div></body></html>
ReferenceError: Can't find variable: onAdd
   betlista\scheduler.js : 23
   :/modules/webpage.js : 281

**Comment by Betlista** [comment]
I executed

    phantomjs.exe betlista\scheduler.js > betlista\out.log

where script and log are above (I intended html manually)

**Comment by JamesMGreene** [comment]
`onAdd` only exists on the client web page, not in the Phantom outer context. As such, you need to call into the client page with `page.evaluate` in order to work with that function.

Try updating your `page.open` call as follows:

```js
page.open('http://czcholsint869:5555/WmRoot/scheduler.dsp?mode=useradd', function (status) {
    if (status !== 'success') {
        console.log( 'Unable to access network' );
    } else {
        console.log( 'Opened ok' );
        console.log(page.content); //page source

        // ONLY CHANGED THIS LINE OF CODE:
        var a = page.evaluate(function() { return onAdd(); });

        console.log( 'onAdd=' + a );

        phantom.exit();
    }
});
```

**Comment by Betlista** [comment]
Thanks, that works. Unfortunatelly, I still do not know why the same is not working using PhantomJSDriver from Java.

We can close this one. Thanks again ;-)

**Comment by JamesMGreene** [comment]
Happy to help!  PhantomJSDriver issues can be filed at https://github.com/detro/ghostdriver/issues/
