### ISSUE TITLE
an issue in module require code

### ISSUE THREAD

**Issue by alexeyk777** [ariya/phantomjs#12868]
Hello!
If module contains a single line comment in last line of file phantom cant compile/include it.
The issue in phantom.cpp file line 371.
We need to replace

"}.call({}," +

to

"\n}.call({}," +

Now it will work fine :)
I cant push fixed code now (only in next month), if someone can fix quickly, please do that.
Thanks!

**Comment by JamesMGreene** [comment]
Fixed by commit a4cb01b2011fe528919fe2bb47d6ef2448790ced. Thanks!

**Comment by JamesMGreene** [comment]
(Amended that commit message to include a reference to this issue.)
