### ISSUE TITLE
A way to prevent window.callPhantom from existing

### ISSUE THREAD

**Issue by chris-martin** [ariya/phantomjs#12860]
Could we have a setting to turn this feature off? I'd like Phantom to behave the same as other browsers, to the greatest extent possible.

There was a related mailing list discussion [a few years ago](https://groups.google.com/forum/#!searchin/phantomjs/callphantom/phantomjs/zIdd9NznnSo/w87QtQ0dudoJ) but it doesn't seem like the subject was ever revisited.

Being able to customize the name of this variable instead of hard-coding it to `callPhantom` would also be a fine workaround (for my case, at least).

**Comment by JamesMGreene** [comment]
If you aren't utilizing `window.callPhantom` yourself, you should just be able to remove it from the `window` object altogether, e.g.

```js
page.onInitialized = function() {
  page.evaluate(function() {
    delete window.callPhantom;
  });
};
```

**Comment by chris-martin** [comment]
Does `onInitialized` necessarily run before any scripts that are on the page?

Can I do this if I'm using Phantom via Selenium?

**Comment by JamesMGreene** [comment]
> Does `onInitialized` necessarily run before any scripts that are on the page?

**If there are `script` tags in the page's HTML**, yes, the `onInitialized` callback will be invoked immediately before the first page `script` is evaluated.

If there are **NOT** `script` tags in the page's HTML, then the `onInitialized` callback **will not be invoked at all** (see Issues #10772, #12387)... unless [apparently] you then probe the page with Phantom-based script injections like `page.evaluate` (see Issue #11684).

> Can I do this if I'm using Phantom via Selenium?

No idea, I have never used Phantom via Selenium before. Sorry!

**Comment by JohnBruce** [comment]
not sure if some new functionality got added to break something, but the example:

```
page.onInitialized = function() {
  page.evaluate(function() {
    delete window.callPhantom;
  });
};
```
no longer works for me.  Inside of that page evaluate callPhantom is indeed deleted, but if I check for window.callPhantom inside of the page.open function, its still showing up for me.  At least on 2.1.1.

IE.

```
    page.onInitialized = function() {
      page.evaluate(function() {
          delete window._phantom;
          delete window.callPhantom;
      })
    };
    page.open('http://cnn.com/', function(status){
      if(status == 'SUCCESS'){
        var pageContent = page.evaluate(function(){
          console.log(typeof(window.callPhantom));
        })
      }
    })
```

Anyone have any idea why this might be?
