### ISSUE TITLE
Phantomjs 2.0 SocketIO, Ajax, page.open takes 1000ms for each connection on localhost

### ISSUE THREAD

**Issue by congthang1** [ariya/phantomjs#12871]
I'm using PhantomJS 2.0 and trying to test socket.io between PhantomJS and NodeJS. It works but it takes alot of time for each connection (about 1000ms). I have tried on Chrome and it takes only 1-2ms. It's seems that socket.io in page.evaluate of PhantomJS is not socket.io! Here is my testing code using CasperJS:

  var casper = require('casper').create({
    clientScripts: ['jquery-1.11.1.min.js',["socket.io.js"]]
});
casper.start('http://localhost:8080');
casper.page.onConsoleMessage = function(msg) {
  console.log(msg);
};

};
casper.then(function(){
    this.evaluate(function(){
        var socket = io.connect('http://localhost:8080');
        socket.on('news', function (data) {
        socket.emit('senddata', { time: new Date().getTime() });
      });
    })
})
casper.wait(5000);
casper.run();

On NodeJS server I use this code:

var app = require('http').createServer(handler)
var io = require('socket.io')(app);
var fs = require('fs');

app.listen(8080);

function handler (req, res) {
  fs.readFile(__dirname + '/index.html',
  function (err, data) {
    if (err) {
      res.writeHead(500);
      return res.end('Error loading index.html');
    }
  res.writeHead(200);
    res.end(data);
  });
}

io.on('connection', function (socket) {
  socket.emit('news', { hello: 'world' });
  socket.on('senddata', function (data) {
    console.log(new Date().getTime()-data.time);
  });
});

The result of time measuring is always >= 1000ms. I need to tranfer data in serveral ms. I also tried with page.open (post) or send Ajax, the result was similar. Can anyone help me. Thanks

**Comment by alexeyk777** [comment]
I have no the same problem using myself builded phantomjs 2 (Windows).
My project is 100% typescript code using shared modules for phantomjs and nodejs.
The communication based on socket.io (1.2.1). A little bit of phantom code (communication module), some commects in russian:

```
var pu = require("./pUtils");

var SockChannel = (function () {
    function SockChannel(botType) {
        // создать страницу для коммуникации
        this.commPage = pu.createBrowser();
        this.botType = botType;
    }

    SockChannel.prototype.sessionId = function () {
        return this.sid;
    };

    SockChannel.prototype.sendData = function (message) {
        if (!this.sid) {
            console.log("central server not connected yet");
            return;
        }
        this.commPage.evaluate(function (_data) {
            window.socket.emit('message', _data);
        }, JSON.stringify(message));
    };
    SockChannel.prototype.onDataReceived = function (message) {
    };
    SockChannel.prototype.onDie = function () {
    };
    SockChannel.prototype.kill = function () {
        this.commPage.evaluate(function () {
            window.socket.disconnect();
        });
        pu.flushPage(this.commPage);
        if (this.onDie)
            this.onDie();
    };
    SockChannel.prototype.start = function (args) {
        var _this = this;
        if (args.length !== 2)
            throw "SockChannel invalid args";
        var callback = args[1];
        if (typeof callback !== 'function')
            throw "SockChannel function as second param expected";
        console.log('starting communication channel');
        this.commPage.open(args[0], function (status) {
            if (status !== 'success') {
                callback(false);
                return;
            }
            _this.commPage.onCallback = _this.onPhantomCallback;
            var success = _this.preparePage();
            callback(success);
        });
    };

    SockChannel.prototype.onPhantomCallback = function (data) {
        console.log('incoming message ' + data);
        var msg = data;
        if (!msg || !msg.data || !msg.message) {
            console.log("invalid data received " + JSON.stringify(data));
            return;
        }
        if (msg.message === 'setBotId' && msg.data) {
            console.log("bot session id updated: " + msg.data);
            this.sid = msg.data;
            this.sendData({ message: "setType", data: this.botType });
            return;
        }
        this.onDataReceived(msg);
    };

    SockChannel.prototype.preparePage = function () {
        return this.commPage.evaluate(function () {
            if (!io)
                return false; // socket.io клинет не найден
            var sock = io.connect();
            window.socket = sock;
            sock.on('message', function (data) {
                window.callPhantom(data);
            });
            return true; // всё ок
        });
    };
    return SockChannel;
})();
exports.SockChannel = SockChannel;
//# sourceMappingURL=sockChannel.js.map
```

The html page (/api.html):

```
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <script src="/socket.io/socket.io.js"></script>
</head>
<body>
    <script language="javascript">
    if (typeof window.callPhantom !== 'function') {
        document.write('PhantomJs expected. Recomented 2.0 version supports WebSocket!');
    }
    </script>
</body>
</html>
```

Thats it!
I hope it will help you)
