### ISSUE TITLE
CrashDump issue

### ISSUE THREAD

**Issue by ovidiul** [ariya/phantomjs#12873]
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://code.google.com/p/phantomjs/issues/entry with the crash dump file attached: /tmp/A5396443-F78F-4C9F-BBFF-6B83E53DBB48.dmp .

Dump output is here https://www.wetransfer.com/downloads/5eeae616aafc579b5515e2386f0167ce20150113124833/9350733bc7ffeb9264297799940c970520150113124833/b8658f

**Comment by Vitallium** [comment]
I got "Sorry... The download isn't available anymore"
