### ISSUE TITLE
Why phantomjs can't used includeJs to load local resources?

### ISSUE THREAD

**Issue by hugoxie** [ariya/phantomjs#12880]
My project need to insert local resource to the page

I found that phantomjs can't load local resource

It said that : CONSOLE: Not allowed to load local resource: file:///F:/test.js

How can I load local resources by phantomjs??

**Comment by bshy522** [comment]
you need to add a configuration items.

```
phantomjs --local-to-remote-url-access=true
```

**Comment by Vitallium** [comment]
`includeJs` designed to load JavaScript from a remote location, URL. To include JavaScript file from a local file, you must use 'injectJs'. Check out docs here - http://phantomjs.org/api/webpage/method/inject-js.html
