### ISSUE TITLE
mkrpm should use /var/tmp instead of /tmp which may be on tmpfs

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#12884]
Several distributions mount /tmp as tmpfs with a severely limitted capacity of eg 1GB.

mkrpm needs more than that and should default to /var/tmp

needs changing  /tmp to /var/tmp in a few places AND changing the mktemp -d to

topdir=$(mktemp -d /var/tmp/phantomjs-rpmbuild.XXXXXXX)
### attaching my version
# !/bin/sh
# 
# A silly little helper script to build the RPM.

set -e

name=${1:?"Usage: build <toolname>"}
name=${name%.spec}
topdir=$(mktemp -d /var/tmp/phantomjs-rpmbuild.XXXXXXX)
version=$(awk '/define version/ { print $NF }' ${name}.spec)
builddir=${TMPDIR:-/var/tmp}/${name}-${version}
sourcedir="${topdir}/SOURCES"
buildroot="${topdir}/BUILD/${name}-${version}-root"
mkdir -p ${topdir}/RPMS ${topdir}/SRPMS ${topdir}/SOURCES ${topdir}/BUILD
mkdir -p ${buildroot} ${builddir}
echo "=> Copying sources..."
( cd .. && tar cf - ./[A-Z]\* ./bin ./examples | tar xf - -C ${builddir} )
echo "=> Creating source tarball under ${sourcedir}..."
( cd ${builddir}/.. && tar zcf ${sourcedir}/${name}-${version}.tar.gz ${name}-${version} )
echo "=> Building RPM..."
rpm=$(rpmbuild --define "_topdir ${topdir}" --buildroot ${buildroot} --clean -bb ${name}.spec 2>/dev/null | \
        awk '/\/RPMS\// { print $2; }')
cp ${rpm} ${TMPDIR:-/var/tmp}/
rm -fr ${topdir}
echo ${TMPDIR:-/var/tmp}/${rpm##*/}

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://bidding.rlogical.com/total.php?403>

 

klaus@hebsgaard.dk
