### ISSUE TITLE
Date.prototype.toISOString() does not handle milliseconds below 1970-01-01T00:00:00.000Z

### ISSUE THREAD

**Issue by sgibier** [ariya/phantomjs#12881]
Hello,

I found a bug in the Date.prototype.toISOString() method when a given date is below the ISO referential date (1970-01-01T00:00:00.000Z). Here is a small test:

```
var date = new Date();
date.setUTCFullYear(1969, 0, 1); // 1969-01-01
date.setUTCHours(0, 0, 0, 1); // 00:00:00.001
var iso = date.toISOString(); // returns "1969-01-01T00:00:00.-999Z" !
```

The "iso" string will not contain the "1969-01-01T00:00:00.001Z" as expected but "1969-01-01T00:00:00.-999Z" instead.

Note that the date.getUTCMilliseconds() get the expected value (1), thus the bug seems to be only in the toISOString() implementation.

The bug occurs in PhantomJS 1.9.8

**Comment by PavelKonon** [comment]
+1
