### ISSUE TITLE
Cookies enabled problem

### ISSUE THREAD

**Issue by Betlista** [ariya/phantomjs#12885]
I wanted to test one webpage which used this method to identify whether cookies are enabled:

``` javascript
    function cookiesEnabled() {           
        var c = document.cookie;
        var name = "__test_cookie__";
        document.cookie = name;
        var result = (document.cookie.indexOf(name) !== -1);          
        document.cookie = c;
        return result;
    }
```

PhantomJS returned false (not enabled).

The probem is in

``` javascript
    document.cookie = "__test_cookie__";
```

it is not key value pair (for example a=b) so next document.cookie returns null. Maybe this is against some standard, but browsers allow this...

**Comment by Betlista** [comment]
It seems, that according to this RFC - http://www.ietf.org/rfc/rfc2965.txt te value in key-value pair is optional...

**Comment by Betlista** [comment]
Can be tested with HTML page as simple as:

	<html>
		<head>
			<title>Phantom JS cookies test</title>
		</head>

		<body>
			<script>
				function cookiesEnabled() {           
					var c = document.cookie;
					var name = "__test_cookie__";
					document.cookie = name;
					var result = (document.cookie.indexOf(name) !== -1);          
					document.cookie = c;
					return result;
				}
			</script>		
		</body>
	</html>

**Comment by kmilligan** [comment]
I am experiencing this issue as well; anyone have a work-around?
