### ISSUE TITLE
PhantomJS cannot open page

### ISSUE THREAD

**Issue by kyryloholodnov** [ariya/phantomjs#12908]
Hello,
I have small code that only opens a web-page:

``` javascript
var start = new Date().getTime();
console.log('Loading a web page');
var page = require('webpage').create();
var url = 'http://rolletypiter.ru/';

page.open(url, function (status) {
  console.log('Page loaded: ' + status + ', time elapsed: ' + (new Date().getTime() - start) + ' ms');
  phantom.exit();
});
```

Unfortunately the callback is executed after ~2-3 minutes that is too long (in not-headless browsers the page is loaded in a few seconds).
Are there any workarounds to load it faster?

**Comment by iradul** [comment]
This site that you are opening has so many JavaScript errors. You should turn off JavaScript for this site before you call *open* and it should open quickly:
```javascript
page.settings.javascriptEnabled = false;
```
