### ISSUE TITLE
OS X binary does not work on Snow Leopard and Yosemite

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#12900]
* Download the OS X binary of PhantomJS 2.0
* Run it on Snow Leopard
* PhantomJS refuses to run

**Comment by Vokkim** [comment]
The [OS X binary](https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-macosx.zip) does not work in Yosemite (10.10.1) either, refuses to run and outputs `Killed: 9`.

**Comment by petermichaux** [comment]
The OS X binary for PhantomJS 1.9.8 seems to work on Yosemite (10.10.1). The 2.0.0 binary does not work.

**Comment by eugene1g** [comment]
@Vokkim @petermichaux  I had the same "Killed: 9" issue while starting Phantom2 on Yosemite, so I applied a small patch as recommended elsewhere (https://github.com/ariya/phantomjs/issues/12630#issuecomment-69337830) and recompiled working V2 binaries for OSX/Ubuntu/CentOS - they are available at https://github.com/eugene1g/phantomjs/releases if you want them

**Comment by jabez128** [comment]
same issue +1

**Comment by steel** [comment]
+1 here on Yosemite

**Comment by herrernst** [comment]
From https://github.com/ariya/phantomjs/issues/12974: 
```
brew install upx
upx -d bin/phantomjs
```
Then it works.

**Comment by octatone** [comment]
Broken here with any binaries I try on Yosemite.

**Comment by MichielDeMey** [comment]
Exact same issue on OSX Yosemite.
```
[1]    57910 killed     ./phantomjs
```

**Comment by octatone** [comment]
This is the only binary I could get to run on Yosemite: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-macosx.zip

**Comment by floriansemm** [comment]
The solution from @herrernst works for me on Yosemite

**Comment by frameddialog** [comment]
The solution from @herrernst works for me on Yosemite

**Comment by jackblackCH** [comment]
The solution from @herrernst works for me on Yosemite

**Comment by sylvinus** [comment]
Got the same on latest OS X 10.10.2

**Comment by milushov** [comment]
thanks, @herrernst

**Comment by SpyderWeiss** [comment]
I searched for 4 hours today to find this solution, this needs to be posted in a more prominent place, but thank you @herrernst !

**Comment by iRet** [comment]
+1

**Comment by seanriordan** [comment]
Thanks @herrernst

brew install upx
upx -d bin/phantomjs

**Comment by bartsmilner** [comment]
Got the dreaded Killed: 9 with binary on Yosemite 10.10.2 but brew install phantomjs (on homebrew, natch) installed and worked no problem

**Comment by iabdulin** [comment]
+1 for
```bash
brew install upx
upx -d bin/phantomjs
```

**Comment by mathiasbynens** [comment]
This is fixed in master (3c3b47e7967ccaa1783d1329d4fa3a58ce06a00c). Let’s release v2.0.1 soon :)

**Comment by mathiasbynens** [comment]
Nvm

**Comment by pyper** [comment]
I think I found the issue.  I cd’d into the dirs for local storage and the cache, and cleared them out completely.  Once I did that no more problems.   Perhaps a file format change between versions.

In my case(OS X) they were here:

cd ~/Library/Caches/Ofi\ Labs/PhantomJS
rm -f -r data7

cd ~/Library/Application\ Support/Ofi\ Labs/PhantomJS
rm -f *.localstorage

**Comment by mathiasbynens** [comment]
@pyper Confirmed. Thanks for the fix!

**Comment by sarbbottam** [comment]
@pyper @mathiasbynens I could not get it working.

For my case, there was no (sub)directory for ``PhantomJS``  at ``~/Library/Caches/``, but ``~/Library/Application\ Support/Ofi\ Labs/PhantomJS``. Removed the ``*.localstorage``, but no luck.

**Comment by sarbbottam** [comment]
@soda-wy's [solution](https://github.com/ariya/phantomjs/issues/12928#issuecomment-72457801) works perfectly for me.
>> the download link https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-macosx.zip on http://phantomjs.org/ failed with "Killed: 9".

>> https://github.com/eugene1g/phantomjs/releases works, thanks.

**Comment by rfanjul** [comment]
@herrernst  also working for me thanks ! :)

**Comment by seanmac7577** [comment]
The solution from @herrernst worked for me.

**Comment by kushG** [comment]
Running it on Yosemite, but @herrernst solution doesn't works for me !

**Comment by Licas** [comment]
@herrernst  solution worked for me too, thanks! (Mac OS X 10.10.3)

**Comment by herrernst** [comment]
Just for the right credits, I got that from @wallneradam (via #12974).

**Comment by andrewmclagan** [comment]
+1 upx installation worked on Yosemite

**Comment by bootstraponline** [comment]
:+1:

**Comment by Sethathi** [comment]
Thanks, @herrernst

**Comment by jonnolen** [comment]
+1 upx installation worked on Yosemite

**Comment by sungwoncho** [comment]
+1 for @herrernst's solution:

```
upx -d [path to phantomjs executable]
```

**Comment by a932455223** [comment]
+1 from @herrernst 's solution.

**Comment by Vitallium** [comment]
Looks like current master works well with upx now.

/cc @ariya

**Comment by dorayx** [comment]
thanks, @herrernst

**Comment by montogeek** [comment]
@herrernst didnt worked for me
```
montogeek ~/Downloads/phantomjs-2.0.0-macosx/bin [05:39 PM]→ 👾  💣  ./phantomjs --webdriver=4444
[ERROR - 2015-08-12T22:39:55.228Z] GhostDriver - main.fail - {"line":85,"sourceURL":":/ghostdriver/main.js","stack":"\tat global code (:/ghostdriver/main.js:85:56)"}

  :262 in error
```

**Comment by sebastianbochan** [comment]
+1

**Comment by montogeek** [comment]
My error was some process that didn't close correctly. After restarting the machine it worked.

**Comment by ScreenDriver** [comment]
+1
The solution from @herrernst worked for me.

**Comment by oliver-moran** [comment]
Just to pile on:
+1 Solution from @herrernst  works

**Comment by factologist** [comment]
I used homebrew to update from 1.9.8 -> 2.0.0 which worked seamlessly on OSX 10.10.5.

`$ brew install phantomjs` (I was prompted to unlink the existing 1.9.8 -> `Error: phantomjs-1.9.8 already installed` followed by how-to instructions)

`$ brew unlink phantomjs` (successfully unlinked -> `Unlinking /usr/local/Cellar/phantomjs/1.9.8... 2 symlinks removed`)

`$ brew install phantomjs` and the install completed, version updated.

I had to mess with my required versions in my project's `Gemfile` and run bundler but that is to be expected.

**Comment by colinsauce** [comment]
+1 @herrernst why can't this be fixed in the source?

**Comment by vml-rmott** [comment]
if this is going to keep lingering, it should be posted as a known issue on the home page.

**Comment by Vitallium** [comment]
https://github.com/ariya/phantomjs/issues/12900#issuecomment-128972972

**Comment by franksama** [comment]
+1 @herrernst .. took me hours to figure this out, the upx solution worked for me.

**Comment by discorick** [comment]
+1 @herrernst

**Comment by AbdullahAs** [comment]
@soda-wy's solution works perfectly for me as well.

>the download link https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-macosx.zip on http://phantomjs.org/ failed with "Killed: 9".
>
>https://github.com/eugene1g/phantomjs/releases works, thanks.

**Comment by xiaoyongwu** [comment]
"upx" solution worked for me on 10.10.5 Yosemite.

**Comment by jwalton** [comment]
Why is phantomjs still broken on mac 9 months after this was reported???  :(

**Comment by sebastianbochan** [comment]
Please check 2.0.1 version, which should fixed issues.

**Comment by lkraav** [comment]
Is there supposed to be a 2.0.1 git tag/release? https://github.com/ariya/phantomjs/releases shows 2.0.0 for latest.

**Comment by MichielDeMey** [comment]
2.0.1 is not released yet, check out the latest 2.0 branch.
That branch currently at 2.0.1-development.

**Comment by JordanTheriault** [comment]
I was having the same problem.
@herrernst +1 for the solution, worked for me on 10.10.2

**Comment by danemacaulay** [comment]
+1 for upx!

**Comment by Vitallium** [comment]
Works now on OS X El Capitan.

**Comment by panxiubin** [comment]
I have a same issue
[1]    48389 killed     phantomjs -v
