### ISSUE TITLE
Description of new features and changes on PhantomJS 2

### ISSUE THREAD

**Issue by kyledrake** [ariya/phantomjs#12909]
I would love to see a description of what improvements are in PhantomJS 2 on the site or README after release, I haven't been following the changes lately so I'm unfamiliar with what's new and why I should upgrade.

FWIW, [Neocities](https://neocities.org) wouldn't exist without PhantomJS. Thank you all for your amazing work on this, and congrats on finishing the next major release. Free Neocities supporter account for anyone that's ever committed to PhantomJS, just ask. :)

Edit: Don't ask here, it's off topic. Send me an email: contact@neocities.org.

**Comment by ariya** [comment]
Unlike other projects, we keep this issue tracker to issues and not including general discussion. I would recommend starting a new thread on phantomjs-dev to collect those changes.

**Comment by kyledrake** [comment]
Understood, my apologies.

**Comment by ariya** [comment]
No worries.
