### ISSUE TITLE
Problem with page.uploadFile

### ISSUE THREAD

**Issue by rdpanek** [ariya/phantomjs#12914]
Hello everyone, 
I have problem with page.uploadFile.

OS:
Yosemite 10.10.1

I try it on versions:
`Phantomjs 1.9.7` (uploading file works) http://d.pr/i/12S4g
and
`Phantomjs 2.0.0` (`c8abe25`) (uploading file does't work) http://d.pr/i/146KE

Example:
```
var page = require('webpage').create();
page.open('./form.html', function() {
  page.uploadFile('input[name=file]', './README.md');
  page.render('testForm.png');
  phantom.exit();
});
```

PhantomJS selftests:
```
ᐰ phantomjs test/run-tests.js
Started
..........................................................................................................................................................

Finished in 6.373 seconds
154 specs, 0 failures
```
I not found test for file upload :-(

Official documentation:
http://phantomjs.org/api/webpage/method/upload-file.html

Source:
https://github.com/ariya/phantomjs/blob/master/src/modules/webpage.js#L426

Where problem? Thanks

**Comment by ariya** [comment]
This seems to be a duplicate of #12506 (please try to search for similar issue before filing a ticket).

**Comment by rdpanek** [comment]
I'm looking for and I not noticed, sorry. Thanks
