### ISSUE TITLE
PhantomJS 1.9.8 throws "Error: read ECONNRESET" on phantom.exit()

### ISSUE THREAD

**Issue by mz3** [ariya/phantomjs#12912]
I have tested this on multiple machines and internet connections. No matter what page I request, I get the same error. It doesn't matter if any libraries are loaded, this is just one of the examples from the website.

It appears to work, but throws the error when phantom.exit() is called.

```javascript
var page = require('webpage').create();

page.onConsoleMessage = function(msg) {
    console.log(msg);
};

page.open("http://www.phantomjs.org", function(status) {
    if ( status === "success" ) {
        page.includeJs("http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js", function() {
            page.evaluate(function() {
                console.log("$(\".explanation\").text() -> " + $(".explanation").text());
            });
            phantom.exit();
        });
    }
});
```

Result:

```bash
$(".explanation").text() -> 
        PhantomJS is a headless WebKit scriptable with a JavaScript API.
        It has fast and native support for various web standards:
        DOM handling, CSS selector, JSON, Canvas, and SVG.
      
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file://phantom.js. Domains, protocols and ports must match.

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:742:11)
    at Pipe.onread (net.js:535:26)
```

**Comment by Namek** [comment]
any progress? I've just stumbled upon some thing. My tests worked properly under Windows and now don't work on Ubuntu Server 14.04.2 with node 0.12.7 under CasperJS 1.1.0-beta3 on top of PhantomJS 1.9.7.

**Comment by denyskoch** [comment]
same here!

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at Pipe.onread (net.js:559:19)
```

**Comment by zackw** [comment]
PhantomJS 1.x is no longer developed.  Please try the recent 2.1 release and see if that solves your problem.  I am going to close this bug report; feel free to reopen it if you still have the problem with 2.1.

**Comment by akincansenol** [comment]
Yes, I have the same problem with 2.1.1 @zackw

**Comment by Toybreak** [comment]
same issue with "phantomjs-prebuilt": "^2.1.4"; connect with nodejs and nodejs cannot catch this error

**Comment by shbn** [comment]
Suddenly this issue started showing up on  phantom 2.1.1 and casperjs
`events.js:71
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:863:11)
    at Pipe.onread (net.js:524:19)`

**Comment by mz3** [comment]
@shbn PhantomJS is not really maintained or meant for production. I ended up porting my project to another headless browser.

**Comment by Namek** [comment]
@mz3 "another headless browser" = ?

I ended up with Codeception + Selenium Server on top of real Firefox rendering to xvfb. No need for "headless". Depends on scale but for me it's enough.

**Comment by mz3** [comment]
@Namek For my use case, ZombieJS made the most sense. The documentation leaves as lot to be desired, but it doesn't have the memory leaks and other weirdness Phantom does. Plus you run it through the node interpreter and can use it in your NodeJS programs, which is really nice.

**Comment by m-matveev** [comment]
Same issue... 
# phantomjs --version
2.1.1

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at Pipe.onread (net.js:559:19)

**Comment by naitsirch** [comment]
@zackw I also still have this error with

> $ nodejs -v
> v4.6.1
> $ phantomjs -v
> 2.1.1

This is really a show stopper and it would be nice if this could be fixed.

**Comment by prasanthsd** [comment]
Same problem for me. This occurs rather randomly when you run the program many times. Please see if this can be fixed

```
$ casperjs --version
1.1.3
$ phantomjs --version
2.1.1
$ nodejs --version
v4.2.6
```

**Comment by wupinlang** [comment]
Guys you can try `apt-get install -y libcairo2`,it works for me.

**Comment by jonnocraig** [comment]
Encountered this issue when running phantomJS on Linux (CI), the solution was to wrap the process running PhantomJS in a custom node process and handle the error gracefully.

`
const exec = require('child_process').exec;
const childProcess = exec(cmd); // where "cmd" is the command you're using to run PhantomJS
childProcess.on('error', function(err) {
  console.log("Error ----");
  console.log(err.message);
  console.log(err.stack);
});
childProcess.on('close', function(code) {
  console.log("Closed with: ", code);
  process.exit(code);
});`

Hope this helps somebody!
