### ISSUE TITLE
PhantomJS has crashed

### ISSUE THREAD

**Issue by moses-gangipogu** [ariya/phantomjs#12913]
ExceptionHandler::GenerateDump waitpid failed:No child processes
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/1bced565-df97-ac34-47ae064e-5ff81aff.dmp
Segmentation fault

my system configurations :
debain 7.8 whezzy
ram 596
hardisk 7.9G

root@# casperjs --version
1.1.0-beta3
root@# phantomjs --version
1.9.2

**Comment by Vitallium** [comment]
Can you try 1.9.8 version or 2.0 version?

**Comment by moses-gangipogu** [comment]
@Vitallium i will give it a try
