### ISSUE TITLE
Need to comment render (time / title / description / scenario

### ISSUE THREAD

**Issue by jefleponot** [ariya/phantomjs#12915]
it will be nice to use the QImage setText method to add some informations into pictures headers files

**Comment by Vitallium** [comment]
Please use our [mailing list] (https://groups.google.com/forum/#!forum/phantomjs) to discuss new (or existing) API.

**Comment by jefleponot** [comment]
Hi vitallium,

http://degooglisons-internet.org/

**Comment by jefleponot** [comment]
I can't access to google groups
