### ISSUE TITLE
PhantomJS 2.0 does not work in Mac OS Yosemite

### ISSUE THREAD

**Issue by peterchenkai** [ariya/phantomjs#12928]
PhantomJS 2.0 does not work in Mac OS Yosemite.  It failed with "Killed: 9".

**Comment by eugene1g** [comment]
Related to #12900 and #12630

I'm not affiliated with the project, but I encountered the same issue so I recompiled a working binary at https://github.com/eugene1g/phantomjs/releases if you want it.

**Comment by soda-wy** [comment]
the download link https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-macosx.zip on http://phantomjs.org/ is failed with "Killed: 9".

https://github.com/eugene1g/phantomjs/releases  is works, thanks.

**Comment by rdpanek** [comment]
I have the same problem. I must build Phantomjs 2.0 from repository,  ~30min and CPU on max

**Comment by ariya** [comment]
Duplicate of #12900.

**Comment by raycursif** [comment]
I have the same issue

**Comment by jackblackCH** [comment]
+1 same here

**Comment by tofias** [comment]
Yup.
