### ISSUE TITLE
Timeout using absolute path for HTML file on a Windows 7

### ISSUE THREAD

**Issue by Mario-S** [ariya/phantomjs#12921]
I'm running version 1.9.8 on a Windows 7 Professional machine with Service Pack 1.
When I use a absolute path to the HTML file my test runs in a timeout. But when I use a relative path, it is working.

__Timeout__: 'phantomjs.exe run-qunit.js _ABSOLUTE_PATH_\index.html'
__Passing__: 'phantomjs.exe run-qunit.js index.html'

Help is greatly appreciated.

**Comment by JamesMGreene** [comment]
Make sure you are double-escaping your backslashes in the path `ABSOLUTE_PATH\\index.html`. That's a Windows limitation, not a PhantomJS issue.

**Comment by Mario-S** [comment]
Unfortunately the double escaping backslashes in the absolute path didn't work for me. Not sure if it is only a cmd problem.
