### ISSUE TITLE
phantomjs.exe 2.0 crashes on windows

### ISSUE THREAD

**Issue by livioc** [ariya/phantomjs#12933]
if i execute phantomjs.exe on a windows 7 x86 machine it suddenly crashes with this exception

phantomjs.exe
Auto configuration failed
2504:error:02001015:system library:fopen:Is a directory:.\crypto\bio\bss_file.c:
169:fopen('F:\development\openssl\!BUILD/ssl/openssl.cnf','rb')
2504:error:2006D002:BIO routines:BIO_new_file:system lib:.\crypto\bio\bss_file.c
:174:
2504:error:0E078002:configuration file routines:DEF_LOAD:system lib:.\crypto\con
f\conf_def.c:199:

note:i got the same error if i set a script as argument

**Comment by livioc** [comment]
the version that i'm using is the file at
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-windows.zip

**Comment by Vitallium** [comment]
I tested it on Win X64 SP1. And it works.

**Comment by Vitallium** [comment]
Upstream bug: http://rt.openssl.org/Ticket/Display.html?id=3488&user=guest&pass=guest

**Comment by livioc** [comment]
so do we wait the next openssl release or do we will fix it removing the deprecated call to OPENSSL_config() ?

however on a win 7 x64 professional SP1 i get the same error
phantomjs.exe
Auto configuration failed
5448:error:02001015:system library:fopen:Is a directory:.\crypto\bio\bss_file.c:
169:fopen('F:\development\openssl\!BUILD/ssl/openssl.cnf','rb')
5448:error:2006D002:BIO routines:BIO_new_file:system lib:.\crypto\bio\bss_file.c
:174:
5448:error:0E078002:configuration file routines:DEF_LOAD:system lib:.\crypto\con
f\conf_def.c:199:

do you configure openssl with some cfg files or other way?

**Comment by jan-tosovsky-cz** [comment]
Same error on Win 7 SP1 x64 - dowloaded and unpacked today:
D:\phantomjs-2.0.0-windows\bin>phantomjs
Auto configuration failed
6708:error:02001015:system library:fopen:Is a directory:.\crypto\bio\bss_file.c:
169:fopen('F:\development\openssl\!BUILD/ssl/openssl.cnf','rb')
6708:error:2006D002:BIO routines:BIO_new_file:system lib:.\crypto\bio\bss_file.c
:174:
6708:error:0E078002:configuration file routines:DEF_LOAD:system lib:.\crypto\con
f\conf_def.c:199:

**Comment by Vitallium** [comment]
Can someone post dependencies for PhantomJS executable file? You can use [Dependency Walker](http://www.dependencywalker.com/) for this.

**Comment by jan-tosovsky-cz** [comment]
These libs are marked as missing:
API-MS-WIN-APPMODEL-RUNTIME-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
API-MS-WIN-SHCORE-SCALING-L1-1-1.DLL
DCOMP.DLL
IESHIMS.DLL

The complete image (dwi) can be found at http://drifted.in/other/phantom/phantomjs.zip

**Comment by xonze** [comment]
PS D:\Users\wx\Desktop\Codeception\selenium\phantomjs-2.0.0-windows> .\bin\phantomjs.exe
Auto configuration failed
15020:error:02001015:system library:fopen:Is a directory:.\crypto\bio\bss_file.c:169:fopen('F:\development\openssl\!BUIL
D/ssl/openssl.cnf','rb')
15020:error:2006D002:BIO routines:BIO_new_file:system lib:.\crypto\bio\bss_file.c:174:
15020:error:0E078002:configuration file routines:DEF_LOAD:system lib:.\crypto\conf\conf_def.c:199:

**Comment by Vitallium** [comment]
Ok, guys, I've updated binaries https://bitbucket.org/ariya/phantomjs/downloads Can you try it please?

**Comment by xonze** [comment]
```
Auto configuration failed
16480:error:02001015:system library:fopen:Is a directory:.\crypto\bio\bss_file.c
:168:fopen('f:\dev\openssl\/ssl/openssl.cnf','rb')
16480:error:2006D002:BIO routines:BIO_new_file:system lib:.\crypto\bio\bss_file.
c:173:
16480:error:0E078002:configuration file routines:DEF_LOAD:system lib:.\crypto\co
nf\conf_def.c:197:
```
Not ok,only different is 'F:\development\openssl!BUILD/ssl/openssl.cnf' change to 'f:\dev\openssl\/ssl/openssl.cnf'

**Comment by Vitallium** [comment]
Huh... =\

**Comment by xonze** [comment]
```
Auto configuration failed
15836:error:02001015:system library:fopen:Is a directory:.\crypto\bio\bss_file.c:168:fopen('f:\dev\openssl\/ssl/openssl.
cnf','rb')
15836:error:2006D002:BIO routines:BIO_new_file:system lib:.\crypto\bio\bss_file.c:173:
15836:error:0E078002:configuration file routines:DEF_LOAD:system lib:.\crypto\conf\conf_def.c:197:
```

this is version: 34 minutes ago

**Comment by Vitallium** [comment]
@xonze can you try one more time please? I updated Windows archive.

**Comment by xonze** [comment]
@Vitallium Nice，is running！Think you very much！

**Comment by xonze** [comment]
@Vitallium 
···
> java -jar selenium-server-standalone-2.44.0.jar
···

**Comment by xonze** [comment]
@Vitallium 
···
> java -jar selenium-server-standalone-2.44.0.jar

> phantomjs.exe --webdriver=4444

···

**Comment by polarathene** [comment]
Works great, thankyou Vitallium! I've just spent past 2 days dealing with correcting the PDF print scaling on 1.9.8, only recently got it working with a hacky addition of webkit-transform:scale(2) and adjusting body width to 50%. I no longer need that :)

**Comment by rodoabad** [comment]
Is the issue I'm having related to this issue?

```
"D:\Applications\JetBrains\WebStorm 11.0.2\bin\runnerw.exe" D:\Applications\nodejs\node.exe D:\Web\GitHub\finance-calculators\node_modules\gulp\bin\gulp.js --color --gulpfile d:\Web\GitHub\finance-calculators\gulpfile.babel.js karma
[07:50:36] Requiring external module babel-core/register
[07:50:38] Using gulpfile d:\Web\GitHub\finance-calculators\gulpfile.babel.js
[07:50:38] Starting 'karma'...
[07:50:38] Finished 'karma' after 87 ms
Hash: 8344a6c0a9b3c44a5636
Version: webpack 1.12.11
Time: 9ms
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
Hash: 97570f7ee3198ea4664d
Version: webpack 1.12.11
Time: 5430ms
           Asset     Size  Chunks             Chunk Names
webpack.karma.js  7.41 MB       0  [emitted]  webpack.karma.js
chunk    {0} webpack.karma.js (webpack.karma.js) 2.82 MB [rendered]
    [0] ./webpack.karma.js 977 bytes {0} [built]
    [1] ./~/angular/index.js 48 bytes {0} [built]
    [2] ./~/angular/angular.js 1.07 MB {0} [built]
    [3] ./~/angular-mocks/angular-mocks.js 82.8 kB {0} [built]
    [4] ./src/index.js 2.91 kB {0} [built]
    [5] ./~/angular-material/angular-material.css 888 bytes {0} [built]
    [6] ./~/css-loader!./~/angular-material/angular-material.css 441 kB {0} [built]
    [7] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
    [8] ./~/style-loader/addStyles.js 7.21 kB {0} [built]
    [9] ./~/angular-animate/index.js 60 bytes {0} [built]
   [10] ./~/angular-animate/angular-animate.js 142 kB {0} [built]
   [11] ./~/angular-aria/index.js 54 bytes {0} [built]
   [12] ./~/angular-aria/angular-aria.js 14.6 kB {0} [built]
   [13] ./~/angular-material/index.js 270 bytes {0} [built]
   [14] ./~/angular-material/angular-material.js 843 kB {0} [built]
   [15] ./~/angular-messages/index.js 62 bytes {0} [built]
   [16] ./~/angular-messages/angular-messages.js 25.7 kB {0} [built]
   [17] ./~/angular-ui-router/release/angular-ui-router.js 174 kB {0} [built]
   [18] ./src/config.js 756 bytes {0} [built]
   [19] ./src/views/root/index.js 2.41 kB {0} [built]
   [20] ./src/views/root/config.js 1.35 kB {0} [built]
   [21] ./src/views/root/controller.js 973 bytes {0} [built]
   [22] ./src/views/root/index.html 807 bytes {0} [built]
   [23] ./test \.spec\.js 189 bytes {0} [built]
   [24] ./test/root/directive.spec.js 4.86 kB {0} [optional] [built]
webpack: bundle is now VALID.
16 01 2016 07:50:43.993:ERROR [phantomjs.launcher]: Auto configuration failed
2884:error:02001015:system library:fopen:Is a directory:.\crypto\bio\bss_file.c:169:fopen('F:\development\openssl\!BUILD/ssl/openssl.cnf','rb')
2884:error:2006D002:BIO routines:BIO_new_file:system lib:.\crypto\bio\bss_file.c:174:
2884:error:0E078002:configuration file routines:DEF_LOAD:system lib:.\crypto\conf\conf_def.c:199:

16 01 2016 07:50:43.996:ERROR [launcher]: Cannot start PhantomJS2
	
16 01 2016 07:50:44.156:ERROR [phantomjs.launcher]: Auto configuration failed
9612:error:02001015:system library:fopen:Is a directory:.\crypto\bio\bss_file.c:169:fopen('F:\development\openssl\!BUILD/ssl/openssl.cnf','rb')
9612:error:2006D002:BIO routines:BIO_new_file:system lib:.\crypto\bio\bss_file.c:174:
9612:error:0E078002:configuration file routines:DEF_LOAD:system lib:.\crypto\conf\conf_def.c:199:

16 01 2016 07:50:44.158:ERROR [launcher]: Cannot start PhantomJS2
	
16 01 2016 07:50:44.318:ERROR [phantomjs.launcher]: Auto configuration failed
9324:error:02001015:system library:fopen:Is a directory:.\crypto\bio\bss_file.c:169:fopen('F:\development\openssl\!BUILD/ssl/openssl.cnf','rb')
9324:error:2006D002:BIO routines:BIO_new_file:system lib:.\crypto\bio\bss_file.c:174:
9324:error:0E078002:configuration file routines:DEF_LOAD:system lib:.\crypto\conf\conf_def.c:199:

16 01 2016 07:50:44.321:ERROR [launcher]: Cannot start PhantomJS2
	
16 01 2016 07:50:44.323:ERROR [launcher]: PhantomJS2 failed 2 times (cannot start). Giving up.

Process finished with exit code 1
```

I'm on `    "phantomjs2": "^2.0.2",`
