### ISSUE TITLE
Support for WebRTC

### ISSUE THREAD

**Issue by piranna** [ariya/phantomjs#12931]
PhantomJS has been recently released but there's no reference if it support WebRTC, nor found anything on internet except very old posts (about two years ago) claiming it's not possible. Since it's being used an updated version of QtWebkit, is it possible to use it for WebRTC based tests, or is only focused on HTML rendering instead of full browser capabilities? If so, what would be the equivalent version of Chrome?

**Comment by JamesMGreene** [comment]
Definitely not available in `2.0.0`:

```
$ ./phantomjs-2.0.0/bin/phantomjs webrtc.js
Supports WebRTC `RTCPeerConnection`? false
Supports WebRTC `webkitRTCPeerConnection`? false
```

**Test script:**

```js
var page = require('webpage').create();
page.open('http://www.example.com/', function(status) {
  result = page.evaluate(function() {
    return {
      RTCPeerConnection: 'RTCPeerConnection' in window,
      webkitRTCPeerConnection: 'webkitRTCPeerConnection' in window
    };
  });
  console.log('Supports WebRTC `RTCPeerConnection`? ' + result.RTCPeerConnection);
  console.log('Supports WebRTC `webkitRTCPeerConnection`? ' + result.webkitRTCPeerConnection);
  phantom.exit();
});
```

**Comment by bedney** [comment]
I'm not sure that the version of Webkit being supported here supports WebRTC.

It was April of 2013 when Google announced that they were forking Webkit into Blink and, while they've made sure to support WebRTC in Blink, no such assurances have been made for the core Webkit.

In fact, the Webkit guys are now back porting the WebRTC and MediaStream from Blink back into core WebKit: https://bugs.webkit.org/show_bug.cgi?id=121101

**Comment by piranna** [comment]
It's a shame :-( Well need to wait until the back porting is finished and
QtWebKit update the WebKit version, then :-/

2015-02-02 19:09 GMT+01:00 William J. Edney <notifications@github.com>:

> I'm not sure that the version of Webkit being supported here supports
> WebRTC.
>
> It was April of 2013 when Google announced that they were forking Webkit
> into Blink and, while they've made sure to support WebRTC in Blink, no such
> assurances have been made for the core Webkit.
>
> In fact, the Webkit guys are now back porting the WebRTC and MediaStream
> from Blink back into core WebKit:
> https://bugs.webkit.org/show_bug.cgi?id=121101
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ariya/phantomjs/issues/12931#issuecomment-72506214>.
>



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by Vitallium** [comment]
QtWebkit development has been ended some time ago. Qt will not update QtWebkit anymore. They officially switched to QtWebEngine (Chromium).

**Comment by piranna** [comment]
Is in the PhantomJS roadmap to move to QtWebEngine?

**Comment by Vitallium** [comment]
@piranna yes, it's in our plans.

**Comment by piranna** [comment]
Ok, great ;-)

**Comment by yahu577** [comment]
Can anyone shed some light on this ticket? I'm planning to writing a Stub client using phantomjs on webrtc feature, but it seems missing?

**Comment by scaret** [comment]
+1

**Comment by maxpavlov** [comment]
Surprised it's not in yet :( +1 for WebRTC in Phantom
