### ISSUE TITLE
phantomjs.exe - No Disk

### ISSUE THREAD

**Issue by CalebKester** [ariya/phantomjs#12946]
I keep getting this error when I try and open up the file and when I try to run phantomjs through command line:

phantomjs.exe - No Disk
There is no disk in the drive. Please insert a disk into drive F:.

I don't have a drive F. I'm on Windows 8.1

Any ideas?

**Comment by Vitallium** [comment]
Might be related to #12933

**Comment by CalebKester** [comment]
Might be, I installed 1.9.2 and it seems to be working now.

**Comment by Vitallium** [comment]
Fixed. Please download updated archive on the downloads page.
