### ISSUE TITLE
why the variables do not exist

### ISSUE THREAD

**Issue by qingfengpai** [ariya/phantomjs#12945]
issue:
## ![screenshot from 2015-02-03 18 06 30](https://cloud.githubusercontent.com/assets/7880018/6018141/846266ce-abcf-11e4-8fb8-e5fbbe243b9a.png)

the html file
## ![screenshot from 2015-02-03 18 08 57](https://cloud.githubusercontent.com/assets/7880018/6018191/ca0f917e-abcf-11e4-8811-edf090ae9a42.png)

debugger in the firefox

![screenshot from 2015-02-03 18 06 55](https://cloud.githubusercontent.com/assets/7880018/6018201/e34ffc64-abcf-11e4-8118-aee6efc25a9a.png)

**Comment by JamesMGreene** [comment]
For this one, I would suggest starting by asking the Angular community as this is likely highly implementation dependent.  I'll leave this issue open, though, if you want to inquire with them and then bring some info back here.
