### ISSUE TITLE
syntax error in phantomjs on ubuntu

### ISSUE THREAD

**Issue by israelidanny** [ariya/phantomjs#12947]
I installed PhantomJS on ubuntu via `npm install -g phantomjs`

Now, every time I try to launch it, it says:
```
root@labs-7f9a5b:/opt/ie8linter# phantomjs
/usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs: 1: /usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs: Syntax error: word unexpected (expecting ")")
```

**Comment by ariya** [comment]
That's not a problem with PhantomJS project. Please file it at https://github.com/Medium/phantomjs.

**Comment by geri777** [comment]
I installed PhantomJS Version 2.1.1 via apt-get install.
I have the same error message when I do "phantomjs --version":
`~# sudo phantomjs --version`
`~# /usr/local/bin/phantomjs: Syntax error: word unexpected (expecting ")")`
