### ISSUE TITLE
http://www.phantomjs.org/ gives GitHub error page

### ISSUE THREAD

**Issue by OscarScholten** [ariya/phantomjs#12958]
Hi there - just wanted to let you know that when visiting http://www.phantomjs.org/ you now get a GitHub error page ... http://phantomjs.org/ works ok
Cheers, Oscar

**Comment by AnthonyMastrean** [comment]
:+1:

The browser spins for a while, about 3 minutes, and I get a communication error from my corporate network appliance (or whatever).

**Comment by jmiller76** [comment]
There was an issue with one of the sample scripts not being able to access with the WWW a few weeks back.  I think it has been like this for a while. (#13196 and #13074)

**Comment by Vitallium** [comment]
Duplicate. See #13074

**Comment by jmiller76** [comment]
@Vitallium I think they were pointing out that there was an issue with the domain for the website, not Phantom or the samples.

**Comment by Vitallium** [comment]
@jmiller76 that was a long time ago :)

**Comment by jmiller76** [comment]
I just looked at the more recent comment...  and missed the agedness.

**Comment by AnthonyMastrean** [comment]
So... to be clear, www.phantomjs.org still does not resolve to a website. Are we saying that this is ok? Isn't it just a matter of adding a `CNAME` to the DNS?
