### ISSUE TITLE
phantomjs-2.0.0 build failed 

### ISSUE THREAD

**Issue by tigerfz** [ariya/phantomjs#12955]
I build the phantomjs-2.0.0 on linux and falied. The OS information is 'Linux version 2.6.32-220.7.1.el6.x86_64,gcc version 4.4.6 20110731 (Red Hat 4.4.6-3) '

The error information is as follows:
nux-g++ -I. -o avx2.o avx2.cpp
cc1plus: 错误：无法识别的命令行选项“-mavx2”
gmake: *** [avx2.o] 错误 1
avx2 disabled.
POSIX iconv auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o iconv.o iconv.cpp
g++ -Wl,-O1 -o iconv iconv.o    
iconv.o: In function `main':
iconv.cpp:(.text+0x10): undefined reference to `libiconv_open'
iconv.cpp:(.text+0x2d): undefined reference to `libiconv'
iconv.cpp:(.text+0x35): undefined reference to `libiconv_close'
collect2: ld 返回 1
gmake: *** [iconv] 错误 1
POSIX iconv disabled.
SUN libiconv auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o gnu-libiconv.o ../gnu-libiconv/gnu-libiconv.cpp
../gnu-libiconv/gnu-libiconv.cpp: In function ‘int main(int, char**)’:
../gnu-libiconv/gnu-libiconv.cpp:54: 错误：从类型‘const char**’到类型‘char**’的转换无效
../gnu-libiconv/gnu-libiconv.cpp:54: 错误：  初始化‘size_t libiconv(void*, char**, size_t*, char**, size_t*)’的实参 2
gmake: *** [gnu-libiconv.o] 错误 1
SUN libiconv disabled.
GNU libiconv auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o gnu-libiconv.o gnu-libiconv.cpp
gnu-libiconv.cpp: In function ‘int main(int, char**)’:
gnu-libiconv.cpp:54: Error：从类型‘const char**’到类型‘char**’的转换无效
gnu-libiconv.cpp:54: Error：  初始化‘size_t libiconv(void*, char**, size_t*, char**, size_t*)’的实参 2
gmake: *** [gnu-libiconv.o] 错误 1
GNU libiconv disabled.
ICU auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o icu.o icu.cpp
icu.cpp:42:28: Error：unicode/utypes.h：No such file or directory
icu.cpp:43:26: Error：unicode/ucol.h：No such file or directory
icu.cpp:44:29: Error：unicode/ustring.h：No such file or directory
icu.cpp: In function ‘int main(int, char**)’:
icu.cpp:48: Error：‘UErrorCode’No such file or directory

ICU disabled.
The ICU library support cannot be enabled.
 Turn on verbose messaging (-v) to /home/zhangfeihu/experiment/phantomjs-2.0.0/src/qt/qtbase/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /home/zhangfeihu/experiment/phantomjs-2.0.0/src/qt/qtbase/configure to continue.

**Comment by xonze** [comment]
编译教程看http://phantomjs.org/build.html

**Comment by ariya** [comment]
Is this Red Hat 4? It's too old and not supported.

**Comment by 2429** [comment]
我也是在centos5 上编译2.0.0 总是：
gmake: *** [project.o] Error 1

Building Qt...

make: *** No targets specified and no makefile found.  Stop.

Building QtWebkit...

grep: src/qt/qtbase/config.status: No such file or directory
./build.sh: line 191: /opt/phantomjs-2.0.0/src/qt/qtbase/bin/qmake: No such file or directory

Building main PhantomJS application...

./build.sh: line 198: /opt/phantomjs-2.0.0/src/qt/qtbase/bin/qmake: No such file or directory


failed;

使用1.9.8 大部分网页可以获得快照，可是我自己写的两个网页总是报：SyntaxError: Parse error

**Comment by jessexi** [comment]
Need to install package 'libicu-devel.x86_64'

**Comment by fearphage** [comment]
Debian/Ubuntu: `sudo apt-get install libicu-dev`

**Comment by herlon214** [comment]
Thanks @fearphage

**Comment by devansdev** [comment]
Thanks @fearphage

**Comment by swathi2301** [comment]
On Redhat linux:
Red Hat Enterprise Linux Server release 6.6 (Santiago)
and libicu package has been installed. [Redhat doesn't seem to have a libicu-devel]
Package libicu-4.2.1-12.el6.x86_64 already installed and latest version.

Still i see the same error:
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o icu.o icu.cpp
icu.cpp:42:28: error: unicode/utypes.h: No such file or directory
icu.cpp:43:26: error: unicode/ucol.h: No such file or directory
icu.cpp:44:29: error: unicode/ustring.h: No such file or directory
icu.cpp: In function ‘int main(int, char**)’:
icu.cpp:48: error: ‘UErrorCode’ was not declared in this scope
icu.cpp:48: error: expected ‘;’ before ‘status’
icu.cpp:49: error: ‘UCollator’ was not declared in this scope
icu.cpp:49: error: ‘collator’ was not declared in this scope
icu.cpp:49: error: ‘status’ was not declared in this scope
icu.cpp:49: error: ‘ucol_open’ was not declared in this scope
icu.cpp:50: error: ‘U_FAILURE’ was not declared in this scope
icu.cpp:52: error: ‘ucol_close’ was not declared in this scope
gmake: *** [icu.o] Error 1
ICU disabled.
The ICU library support cannot be enabled.
 Turn on verbose messaging (-v) to /export/home/temp/phantomjs-2.0.0/src/qt/qtbase/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /export/home/temp/phantomjs-2.0.0/src/qt/qtbase/configure to continue.

**Comment by ariya** [comment]
To build on Linux from source: use newer distribution (e.g. CentOS 6 or later) with fresh ICU (>= 4.8).
