### ISSUE TITLE
Phantomjs 2.0 start bug

### ISSUE THREAD

**Issue by xonze** [ariya/phantomjs#12956]
>java -jar selenium-server-standalone-2.44.0.jar role hub
>phantomjs --webdriver=8080 --webdriver-selenium-grid-hub=http://127.0.0.1:4444
```
[INFO  - 2015-02-05T02:21:37.411Z] GhostDriver - Main - running on port 8080
[INFO  - 2015-02-05T02:21:37.412Z] GhostDriver - Main - registering to Selenium HUB 'http://127.0.0.1:4444' version:  using '127.0.0.1:8080' with org.openqa.grid.selenium.proxy.DefaultRemoteProxy as remote proxy.
[ERROR - 2015-02-05T02:21:37.418Z] GhostDriver - main.fail - {"line":96,"sourceURL":"","stack":"\tat \n\tat global code (:/ghostdriver/main.js:78:37)"}
  :262 in error
```

but,works great at phantomjs 1.9.8 .

**Comment by ariya** [comment]
File with Ghost Driver. @Vitallium, IIRC Ghost Driver doesn't support PhantomJS 2 yet?

**Comment by Vitallium** [comment]
@ariya I'm working on it.

**Comment by ariya** [comment]
Should be moved to Ghost Driver project, if such a ticket is not available yet.

**Comment by pchristhuraja** [comment]
What was the fix? I am getting same error:
[INFO  - 2015-05-07T23:01:35.529Z] GhostDriver - Main - running on port 8089
[INFO  - 2015-05-07T23:01:35.529Z] GhostDriver - Main - registering to Selenium HUB 'http://localhost:4444' version:  using '127.0.0.1:8089' with org.openqa.grid.selenium.proxy.DefaultRemoteProxy as remote proxy.
[ERROR - 2015-05-07T23:01:35.532Z] GhostDriver - main.fail - {"line":96,"sourceURL":"","stack":"\tat \n\tat global code (:/ghostdriver/main.js:78:37)"}

**Comment by neuro-sys** [comment]
@DeChrish 

Just in case anyone's waiting for their linux distribution to merge the latest upstream version, and/or is unable to build it from scratch for some reason, here's the fix:

https://gist.github.com/neuro-sys/41e368839a9b20dafb34

**Comment by alexpts** [comment]
```
$ node_modules/.bin/phantomjs --webdriver=8081 --webdriver-selenium-grid-hub=http://0.0.0.0:4444
PhantomJS is launching GhostDriver...
[INFO  - 2015-08-20T11:46:14.556Z] GhostDriver - Main - running on port 8081
[INFO  - 2015-08-20T11:46:14.557Z] GhostDriver - Main - registering to Selenium HUB 'http://0.0.0.0:4444' version:  using '127.0.0.1:8081' with org.openqa.grid.selenium.proxy.DefaultRemoteProxy as remote proxy.
[ERROR - 2015-08-20T11:46:14.591Z] GhostDriver - main.fail - {"line":96,"sourceURL":"","stack":"\tat \n\tat global code (:/ghostdriver/main.js:78:37)"}

  :262 in error
```
