### ISSUE TITLE
Unable to load absolute or relative HTML file on Windows if path requires URL encoding

### ISSUE THREAD

**Issue by Vitallium** [ariya/phantomjs#12953]
PhantomJS can't load absolute or relative HTML file.

**Steps:**
1) Use relative or absolute path to a HTML file.
2) PhantomJS unable to load it because path is encoded.
Example: `Network - Resource request error: 203 ( "Error opening F:/development/compat-table/es5%5C%5Cindex.html: No such file or directory" ) URL: "file:///F:/development/compat-table/es5%255C%255Cindex.html"`

**Comment by JamesMGreene** [comment]
Tweaked the title.

**Comment by Vitallium** [comment]
@JamesMGreene Thanks! :+1:

**Comment by Vitallium** [comment]
Fixed in master.
