### ISSUE TITLE
Checksums are invalid for phantomjs-2.0.0-windows.zip on download page

### ISSUE THREAD

**Issue by valuedvision** [ariya/phantomjs#12952]
The checksums on the download page are invalid for the PhantomJS 2.0 windows binaries at: http://phantomjs.org/download.html

**Comment by Vitallium** [comment]
Fixed in https://github.com/ariya/phantomjs/commit/a76bc4c29a87a8442e30074ec2be158ee66d798f

**Comment by ariya** [comment]
Thanks @Vitallium!
