### ISSUE TITLE
Building linux binaries failing

### ISSUE THREAD

**Issue by rmfitzpatrick** [ariya/phantomjs#12959]
The following has happened on a fc21 vm and fc17 ec2 when following the standard build instructions, as well as running "./build.sh --system-qtdeps":

g++ -c -include .pch/Qt5Network -pipe -O2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -fno-exceptions -Wall -W -D_REENTRANT -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -DQT_NO_USING_NAMESPACE -DQT_BUILD_NETWORK_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I../../mkspecs/linux-g++ -I. -I../../include -I../../include/QtNetwork -I../../include/QtNetwork/5.3.0 -I../../include/QtNetwork/5.3.0/QtNetwork -Ikernel -I../../include/QtCore/5.3.0 -I../../include/QtCore/5.3.0/QtCore -I../../include/QtCore -I.moc -o .obj/moc_qtcpsocket.o .moc/moc_qtcpsocket.cpp
g++ -c -include .pch/Qt5Network -pipe -O2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -fno-exceptions -Wall -W -D_REENTRANT -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -DQT_NO_USING_NAMESPACE -DQT_BUILD_NETWORK_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I../../mkspecs/linux-g++ -I. -I../../include -I../../include/QtNetwork -I../../include/QtNetwork/5.3.0 -I../../include/QtNetwork/5.3.0/QtNetwork -Ikernel -I../../include/QtCore/5.3.0 -I../../include/QtCore/5.3.0/QtCore -I../../include/QtCore -I.moc -o .obj/moc_qudpsocket.o .moc/moc_qudpsocket.cpp
g++ -c -include .pch/Qt5Network -pipe -O2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -fno-exceptions -Wall -W -D_REENTRANT -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -DQT_NO_USING_NAMESPACE -DQT_BUILD_NETWORK_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I../../mkspecs/linux-g++ -I. -I../../include -I../../include/QtNetwork -I../../include/QtNetwork/5.3.0 -I../../include/QtNetwork/5.3.0/QtNetwork -Ikernel -I../../include/QtCore/5.3.0 -I../../include/QtCore/5.3.0/QtCore -I../../include/QtCore -I.moc -o .obj/moc_qnativesocketengine_p.o .moc/moc_qnativesocketengine_p.cpp
g++ -c -include .pch/Qt5Network -pipe -O2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -fno-exceptions -Wall -W -D_REENTRANT -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -DQT_NO_USING_NAMESPACE -DQT_BUILD_NETWORK_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I../../mkspecs/linux-g++ -I. -I../../include -I../../include/QtNetwork -I../../include/QtNetwork/5.3.0 -I../../include/QtNetwork/5.3.0/QtNetwork -Ikernel -I../../include/QtCore/5.3.0 -I../../include/QtCore/5.3.0/QtCore -I../../include/QtCore -I.moc -o .obj/moc_qsslsocket_openssl_p.o .moc/moc_qsslsocket_openssl_p.cpp
g++ -c -include .pch/Qt5Network -pipe -O2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -fno-exceptions -Wall -W -D_REENTRANT -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -DQT_NO_USING_NAMESPACE -DQT_BUILD_NETWORK_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I../../mkspecs/linux-g++ -I. -I../../include -I../../include/QtNetwork -I../../include/QtNetwork/5.3.0 -I../../include/QtNetwork/5.3.0/QtNetwork -Ikernel -I../../include/QtCore/5.3.0 -I../../include/QtCore/5.3.0/QtCore -I../../include/QtCore -I.moc -o .obj/qftp.o access/qftp.cpp
g++ -Wl,-O1 -o ../../../bin/qdoc .obj/atom.o .obj/codechunk.o .obj/codemarker.o .obj/codeparser.o .obj/config.o .obj/cppcodemarker.o .obj/cppcodeparser.o .obj/ditaxmlgenerator.o .obj/doc.o .obj/editdistance.o .obj/generator.o .obj/helpprojectwriter.o .obj/htmlgenerator.o .obj/location.o .obj/main.o .obj/node.o .obj/openedlist.o .obj/plaincodemarker.o .obj/puredocparser.o .obj/qdocdatabase.o .obj/qdoctagfiles.o .obj/qdocindexfiles.o .obj/quoter.o .obj/separator.o .obj/text.o .obj/tokenizer.o .obj/tree.o .obj/yyindent.o .obj/qqmljsast.o .obj/qqmljsastvisitor.o .obj/qqmljsengine_p.o .obj/qqmljsgrammar.o .obj/qqmljslexer.o .obj/qqmljsparser.o .obj/jscodemarker.o .obj/qmlcodemarker.o .obj/qmlcodeparser.o .obj/qmlmarkupvisitor.o .obj/qmlvisitor.o   -L/home/fvm/tmp/phantomjs/src/qt/qtbase/lib -lQt5Xml -lQt5Core -lz -licui18n -licuuc -lm -ldl -lrt -lpthread 
make[2]: Leaving directory '/home/fvm/tmp/phantomjs/src/qt/qtbase/src/tools/qdoc'
rm -f libQt5Network.a
ar cqs libQt5Network.a .obj/qftp.o .obj/qhttpnetworkheader.o .obj/qhttpnetworkrequest.o .obj/qhttpnetworkreply.o .obj/qhttpnetworkconnection.o .obj/qhttpnetworkconnectionchannel.o .obj/qabstractprotocolhandler.o .obj/qhttpprotocolhandler.o .obj/qspdyprotocolhandler.o .obj/qnetworkaccessauthenticationmanager.o .obj/qnetworkaccessmanager.o .obj/qnetworkaccesscache.o .obj/qnetworkaccessbackend.o .obj/qnetworkaccessdebugpipebackend.o .obj/qnetworkaccessfilebackend.o .obj/qnetworkaccesscachebackend.o .obj/qnetworkaccessftpbackend.o .obj/qnetworkcookie.o .obj/qnetworkcookiejar.o .obj/qnetworkrequest.o .obj/qnetworkreply.o .obj/qnetworkreplyimpl.o .obj/qnetworkreplydataimpl.o .obj/qnetworkreplyhttpimpl.o .obj/qnetworkreplyfileimpl.o .obj/qabstractnetworkcache.o .obj/qnetworkdiskcache.o .obj/qhttpthreaddelegate.o .obj/qhttpmultipart.o .obj/qnetworksession.o .obj/qnetworkconfigmanager.o .obj/qnetworkconfiguration.o .obj/qnetworkconfigmanager_p.o .obj/qbearerengine.o .obj/qbearerplugin.o .obj/qsharednetworksession.o .obj/qauthenticator.o .obj/qdnslookup.o .obj/qhostaddress.o .obj/qhostinfo.o .obj/qurlinfo.o .obj/qnetworkproxy.o .obj/qnetworkinterface.o .obj/qdnslookup_unix.o .obj/qhostinfo_unix.o .obj/qnetworkinterface_unix.o .obj/qnetworkproxy_generic.o .obj/qabstractsocketengine.o .obj/qhttpsocketengine.o .obj/qsocks5socketengine.o .obj/qabstractsocket.o .obj/qtcpsocket.o .obj/qudpsocket.o .obj/qtcpserver.o .obj/qlocalsocket.o .obj/qlocalserver.o .obj/qnativesocketengine.o .obj/qnativesocketengine_unix.o .obj/qlocalsocket_unix.o .obj/qlocalserver_unix.o .obj/qssl.o .obj/qsslcertificate.o .obj/qsslconfiguration.o .obj/qsslcipher.o .obj/qsslerror.o .obj/qsslkey.o .obj/qsslsocket.o .obj/qsslsocket_openssl.o .obj/qsslsocket_openssl_symbols.o .obj/qsslcertificateextension.o .obj/qsslcontext.o .obj/moc_qhttpnetworkreply_p.o .obj/moc_qspdyprotocolhandler_p.o .obj/moc_qnetworkaccesscache_p.o .obj/moc_qnetworkaccessbackend_p.o .obj/moc_qnetworkaccessdebugpipebackend_p.o .obj/moc_qnetworkaccessfilebackend_p.o .obj/moc_qnetworkaccessftpbackend_p.o .obj/moc_qnetworkcookiejar.o .obj/moc_qnetworkreply.o .obj/moc_qnetworkreplyhttpimpl_p.o .obj/moc_qabstractnetworkcache.o .obj/moc_qnetworkdiskcache.o .obj/moc_qhttpthreaddelegate_p.o .obj/moc_qhttpmultipart.o .obj/moc_qnetworkconfigmanager_p.o .obj/moc_qnetworksession_p.o .obj/moc_qbearerplugin_p.o .obj/moc_qdnslookup_p.o .obj/moc_qhostinfo_p.o .obj/moc_qabstractsocketengine_p.o .obj/moc_qhttpsocketengine_p.o .obj/moc_qsocks5socketengine_p.o .obj/moc_qtcpsocket.o .obj/moc_qudpsocket.o .obj/moc_qnativesocketengine_p.o .obj/moc_qsslsocket_openssl_p.o
rm -f ../../lib/libQt5Network.a
mv -f libQt5Network.a ../../lib/ 
make[2]: Leaving directory '/home/fvm/tmp/phantomjs/src/qt/qtbase/src/network'
make[1]: Leaving directory '/home/fvm/tmp/phantomjs/src/qt/qtbase/src'
Makefile:39: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2

**Comment by Vitallium** [comment]
I don't see any error here. Can you post a full build log please?

**Comment by rmfitzpatrick** [comment]
Where/how is a build log generated?  Are you referring to the entirety of stdout after running build.sh?

**Comment by Vitallium** [comment]
@rmfitzpatrick yes, stdout. You can just run make one more time to see the actual error.

**Comment by rmfitzpatrick** [comment]
Second attempt after updating yum and starting from scratch with standard build instructions.  Original issue didn't repeat, but this happened:
```
g++ -Wl,-O1 -Wl,-rpath-link,/home/fvm/tmp/phantomjs/src/qt/qtbase/lib -o ../bin/phantomjs phantom.o callback.o webpage.o webserver.o main.o utils.o networkaccessmanager.o cookiejar.o filesystem.o system.o env.o terminal.o encoding.o config.o childprocess.o repl.o crashdump.o mongoose.o linenoise.o utf8.o qcommandline.o minidump_file_writer.o convert_UTF.o md5.o string_conversion.o crash_generation_client.o exception_handler.o log.o linux_dumper.o linux_ptrace_dumper.o minidump_writer.o file_id.o guid_creator.o memory_mapped_file.o safe_readlink.o phantomjs_plugin_import.o qrc_phantomjs.o qrc_ghostdriver.o qrc_WebKit.o qrc_InspectorBackendCommands.o moc_phantom.o moc_callback.o moc_webpage.o moc_webserver.o moc_networkaccessmanager.o moc_cookiejar.o moc_filesystem.o moc_system.o moc_env.o moc_terminal.o moc_config.o moc_childprocess.o moc_repl.o moc_qcommandline.o   -L/home/fvm/tmp/phantomjs/src/qt/qtbase/lib -lQt5WebKitWidgets -Wl,-whole-archive -Wl,-no-whole-archive -L/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WebKit/release -Wl,-whole-archive -Wl,-no-whole-archive -L/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WebCore/release -Wl,-whole-archive -Wl,-no-whole-archive -L/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/ThirdParty/leveldb/release -Wl,-whole-archive -Wl,-no-whole-archive -L/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore/release -Wl,-whole-archive -Wl,-no-whole-archive -L/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WTF/release -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -lQt5PrintSupport -lQt5WebKit -Wl,-whole-archive -lWebKit1 -Wl,-no-whole-archive -Wl,-whole-archive -lWebCore -Wl,-no-whole-archive -Wl,-whole-archive -lleveldb -Wl,-no-whole-archive -Wl,-whole-archive -lJavaScriptCore -Wl,-no-whole-archive -Wl,-whole-archive -lWTF -Wl,-no-whole-archive -licudata -lQt5Sql -L/home/fvm/tmp/phantomjs/src/qt/qtbase/plugins/accessible -lqtaccessiblewidgets -lQt5Widgets -L/home/fvm/tmp/phantomjs/src/qt/qtbase/plugins/bearer -lqgenericbearer -lQt5Network -lssl -lcrypto -L/home/fvm/tmp/phantomjs/src/qt/qtbase/plugins/platforms -lqphantom -lQt5PlatformSupport -lfontconfig -lfreetype -L/home/fvm/tmp/phantomjs/src/qt/qtbase/plugins/imageformats -lqico -lQt5Gui -ljpeg -lpng -lqtharfbuzzng -lQt5Core -lz -licui18n -licuuc -lm -ldl -lrt -lpthread 
/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_WebKit.o): In function `qInitResources_WebKit()':
qrc_WebKit.cpp:(.text._Z21qInitResources_WebKitv+0x0): multiple definition of `qInitResources_WebKit()'
qrc_WebKit.o:qrc_WebKit.cpp:(.text+0x20): first defined here
/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_WebKit.o): In function `qCleanupResources_WebKit()':
qrc_WebKit.cpp:(.text._Z24qCleanupResources_WebKitv+0x0): multiple definition of `qCleanupResources_WebKit()'
qrc_WebKit.o:qrc_WebKit.cpp:(.text+0x50): first defined here
/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_InspectorBackendCommands.o): In function `qInitResources_InspectorBackendCommands()':
qrc_InspectorBackendCommands.cpp:(.text._Z39qInitResources_InspectorBackendCommandsv+0x0): multiple definition of `qInitResources_InspectorBackendCommands()'
qrc_InspectorBackendCommands.o:qrc_InspectorBackendCommands.cpp:(.text+0x20): first defined here
/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_InspectorBackendCommands.o): In function `qCleanupResources_InspectorBackendCommands()':
qrc_InspectorBackendCommands.cpp:(.text._Z42qCleanupResources_InspectorBackendCommandsv+0x0): multiple definition of `qCleanupResources_InspectorBackendCommands()'
qrc_InspectorBackendCommands.o:qrc_InspectorBackendCommands.cpp:(.text+0x50): first defined here
collect2: error: ld returned 1 exit status
Makefile.phantomjs:283: recipe for target '../bin/phantomjs' failed
make[1]: *** [../bin/phantomjs] Error 1
make[1]: Leaving directory '/home/fvm/tmp/phantomjs/src'
Makefile:38: recipe for target 'sub-src-phantomjs-pro-make_first-ordered' failed
make: *** [sub-src-phantomjs-pro-make_first-ordered] Error 2
[fvm@localhost phantomjs]$ sudo make
cd src/ && ( test -e Makefile.phantomjs || /home/fvm/tmp/phantomjs/src/qt/qtbase/bin/qmake /home/fvm/tmp/phantomjs/src/phantomjs.pro -o Makefile.phantomjs ) && make -f Makefile.phantomjs 
make[1]: Entering directory '/home/fvm/tmp/phantomjs/src'
g++ -Wl,-O1 -Wl,-rpath-link,/home/fvm/tmp/phantomjs/src/qt/qtbase/lib -o ../bin/phantomjs phantom.o callback.o webpage.o webserver.o main.o utils.o networkaccessmanager.o cookiejar.o filesystem.o system.o env.o terminal.o encoding.o config.o childprocess.o repl.o crashdump.o mongoose.o linenoise.o utf8.o qcommandline.o minidump_file_writer.o convert_UTF.o md5.o string_conversion.o crash_generation_client.o exception_handler.o log.o linux_dumper.o linux_ptrace_dumper.o minidump_writer.o file_id.o guid_creator.o memory_mapped_file.o safe_readlink.o phantomjs_plugin_import.o qrc_phantomjs.o qrc_ghostdriver.o qrc_WebKit.o qrc_InspectorBackendCommands.o moc_phantom.o moc_callback.o moc_webpage.o moc_webserver.o moc_networkaccessmanager.o moc_cookiejar.o moc_filesystem.o moc_system.o moc_env.o moc_terminal.o moc_config.o moc_childprocess.o moc_repl.o moc_qcommandline.o   -L/home/fvm/tmp/phantomjs/src/qt/qtbase/lib -lQt5WebKitWidgets -Wl,-whole-archive -Wl,-no-whole-archive -L/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WebKit/release -Wl,-whole-archive -Wl,-no-whole-archive -L/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WebCore/release -Wl,-whole-archive -Wl,-no-whole-archive -L/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/ThirdParty/leveldb/release -Wl,-whole-archive -Wl,-no-whole-archive -L/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore/release -Wl,-whole-archive -Wl,-no-whole-archive -L/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WTF/release -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -lQt5PrintSupport -lQt5WebKit -Wl,-whole-archive -lWebKit1 -Wl,-no-whole-archive -Wl,-whole-archive -lWebCore -Wl,-no-whole-archive -Wl,-whole-archive -lleveldb -Wl,-no-whole-archive -Wl,-whole-archive -lJavaScriptCore -Wl,-no-whole-archive -Wl,-whole-archive -lWTF -Wl,-no-whole-archive -licudata -lQt5Sql -L/home/fvm/tmp/phantomjs/src/qt/qtbase/plugins/accessible -lqtaccessiblewidgets -lQt5Widgets -L/home/fvm/tmp/phantomjs/src/qt/qtbase/plugins/bearer -lqgenericbearer -lQt5Network -lssl -lcrypto -L/home/fvm/tmp/phantomjs/src/qt/qtbase/plugins/platforms -lqphantom -lQt5PlatformSupport -lfontconfig -lfreetype -L/home/fvm/tmp/phantomjs/src/qt/qtbase/plugins/imageformats -lqico -lQt5Gui -ljpeg -lpng -lqtharfbuzzng -lQt5Core -lz -licui18n -licuuc -lm -ldl -lrt -lpthread 
/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_WebKit.o): In function `qInitResources_WebKit()':
qrc_WebKit.cpp:(.text._Z21qInitResources_WebKitv+0x0): multiple definition of `qInitResources_WebKit()'
qrc_WebKit.o:qrc_WebKit.cpp:(.text+0x20): first defined here
/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_WebKit.o): In function `qCleanupResources_WebKit()':
qrc_WebKit.cpp:(.text._Z24qCleanupResources_WebKitv+0x0): multiple definition of `qCleanupResources_WebKit()'
qrc_WebKit.o:qrc_WebKit.cpp:(.text+0x50): first defined here
/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_InspectorBackendCommands.o): In function `qInitResources_InspectorBackendCommands()':
qrc_InspectorBackendCommands.cpp:(.text._Z39qInitResources_InspectorBackendCommandsv+0x0): multiple definition of `qInitResources_InspectorBackendCommands()'
qrc_InspectorBackendCommands.o:qrc_InspectorBackendCommands.cpp:(.text+0x20): first defined here
/home/fvm/tmp/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_InspectorBackendCommands.o): In function `qCleanupResources_InspectorBackendCommands()':
qrc_InspectorBackendCommands.cpp:(.text._Z42qCleanupResources_InspectorBackendCommandsv+0x0): multiple definition of `qCleanupResources_InspectorBackendCommands()'
qrc_InspectorBackendCommands.o:qrc_InspectorBackendCommands.cpp:(.text+0x50): first defined here
collect2: error: ld returned 1 exit status
Makefile.phantomjs:283: recipe for target '../bin/phantomjs' failed
make[1]: *** [../bin/phantomjs] Error 1
make[1]: Leaving directory '/home/fvm/tmp/phantomjs/src'
Makefile:38: recipe for target 'sub-src-phantomjs-pro-make_first-ordered' failed
make: *** [sub-src-phantomjs-pro-make_first-ordered] Error 2

**Comment by Vitallium** [comment]
Apply this patch - https://github.com/ariya/phantomjs/pull/12899.patch

**Comment by rmfitzpatrick** [comment]
Sorry, I had done that originally but forgot to this most recent time.  Now that I've cleaned everything and updated yum the issue doesn't reproduce on my vm.  Thanks for your help.  Closing.

**Comment by titusfortner** [comment]
I can't for the life of me get a working phantomjs binary on Ubuntu 14.10. When trying to build off the 2.0 branch, I got the same error as above. Am I supposed to use a different branch? That patch that was referenced appears to only apply to Windows; is that really what is needed?

/home/webdriver/git/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a: member /home/webdriver/git/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(JSHTMLOptGroupElement.o) in archive is not an object
collect2: error: ld returned 1 exit status
Makefile.phantomjs:279: recipe for target '../bin/phantomjs' failed
make[1]: *** [../bin/phantomjs] Error 1
make[1]: Leaving directory '/home/webdriver/git/phantomjs/src'
Makefile:38: recipe for target 'sub-src-phantomjs-pro-make_first-ordered' failed
make: *** [sub-src-phantomjs-pro-make_first-ordered] Error 2

**Comment by ishaybas** [comment]
Having the exact same problem on Lubuntu 15.10.. any ideas?

**Comment by titusfortner** [comment]
I was able to get a working binary when building from master (last month at least).

**Comment by ishaybas** [comment]
Yep, worked for me just now from master.

**Comment by rsdev000** [comment]
Hello

Cannot build phantomjs 2 on Ubuntu 15.10. Trying on a VPS 1GB Ram with ./build.py --jobs 1.
Followed all building instructions and after a while it ends with this message:

```
{standard input}: Assembler messages:
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile.WebCore.Target:135937: recipe for target '.obj/svg/SVGAllInOne.o' failed
make[2]: *** [.obj/svg/SVGAllInOne.o] Error 4
make[2]: Leaving directory '/home/rs-user00/opt/phantomjs/src/qt/qtwebkit/Source/WebCore'
Makefile.WebCore:68: recipe for target 'sub-Target-pri-make_first-ordered' failed
make[1]: *** [sub-Target-pri-make_first-ordered] Error 2
make[1]: Leaving directory '/home/rs-user00/opt/phantomjs/src/qt/qtwebkit/Source/WebCore'
Makefile:177: recipe for target 'sub-Source-WebCore-WebCore-pro-make_first-ordered' failed
make: *** [sub-Source-WebCore-WebCore-pro-make_first-ordered] Error 2

ERROR: Failed to build PhantomJS! Building Qt WebKit failed.
```

Thanks
