### ISSUE TITLE
Can't get entire png from PhantomJs render command

### ISSUE THREAD

**Issue by AbhijitMuke** [ariya/phantomjs#12950]
![test](https://cloud.githubusercontent.com/assets/2360594/6037668/2558d5ac-ac7c-11e4-8f7c-210b967cac37.png)
I am using PhantomJS for converting html file into png. Actually, my html file is bit lengthier in horizontal way.PhantomJs do not capture its image entire up to last horizontal scroll.I'm using render command for converting html into png.What exactly I am missing or is there any limitation phantomJS has ? Please find png attachment.

**Comment by polarathene** [comment]
How are you setting up your render? Are you setting a viewport width?

**Comment by AbhijitMuke** [comment]
No..I am not setting any specific height and width to viewport..Setting height and width doesn't resolve problems.

**Comment by polarathene** [comment]
What about paperSize? You're not providing much information for how you're rendering this out, so it's hard to help you. How are you approaching this currently?

**Comment by AbhijitMuke** [comment]
I am simply using page.render(outfile);
No any height, width or paperSize  config I'm using.Actually I am able to create png , but my problem is specific to html file which is large in horizontal manner, so created png doesn't get entire html element up to last horizontal scroll.

**Comment by polarathene** [comment]
Does the html file work on it's own or does it link to local files(like js/css file)? If so you need to include those, put them all in a zip file. I think you can drag/drop into the comment box, or click the blue text beneath it `selecting them`.

I am new to PhantomJS but can try help. What version are you using? 1.9.8? And what OS? If you are using Windows, a working build of 2.0.0 was released an hour ago. I just spent 2 long days troubleshooting a rendering issue of my own with 1.9.8, I got it to work with some modifications but the new version renders without them. Try see if it helps: https://bitbucket.org/ariya/phantomjs/downloads

**Comment by AbhijitMuke** [comment]
HTML file work great, don't need to add anything more.Unfortunately I am not able to send my html file coz "Selecting item" do not attach zip or html attachment.Even I try for drag and drop in comment box, but it didn't work.

I am using PhantomJs - 1.9.7 on Windows 7 - professional .Sure I will try new PhantomJS 2.0  also.

**Comment by polarathene** [comment]
If 2.0 work for you let us know, I can try the html file if you can provide the zip. There are many site that let you upload file and provide link. You could also use dropbox or google drive, or create a repo on github to share it :)

**Comment by AbhijitMuke** [comment]
You can find html here https://www.dropbox.com/s/0cn23766iqjz8eu/export.html?dl=0

**Comment by polarathene** [comment]
@AbhijitMuke Ok I gave it a go and got the same problem. I then checked how much pixels width it did render, it is *32767*. Could there be something special about that number? If you google it you'll find website like this: http://rpg.hamsterrepublic.com/ohrrpgce/What_is_so_special_about_the_number_32767%3F
It explains that this is the value of a 16 bit integer! So yes it is a limitation. It's not clear where the limitation is though, could be Phantom or QT, depends how it's being rendered, browsers for example list that value as max limit for canvas http://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element

You could try use the [clipRect](http://phantomjs.org/api/webpage/property/clip-rect.html) api to render slices and then stitch the images together? If you don't need the image to be seamless you could perhaps look at rendering to PDF with a vertical version?

**Comment by AbhijitMuke** [comment]
Seem great.Thanks .

**Comment by ariya** [comment]
Closing this as no follow up is necessary.
