### ISSUE TITLE
NPM installs OSX binary of PhantomJS on FreeBSD

### ISSUE THREAD

**Issue by frvge** [ariya/phantomjs#12963]
I'm having issues with running PhantomJS on FreeBSD 10.

The following errors appear when using sitespeed.io or CasperJS. The phantomjs file is binary, so it's hard to really pinpoint the location of the error.

```
/usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs: 1: Syntax error: Unterminated quoted string
/usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs: 2: Syntax error: Error in command 
```

See also an earlier bugreport on sitespeed.io; https://github.com/sitespeedio/sitespeed.io/issues/563

**Comment by frvge** [comment]
The NPM wrapper doesn't install a FreeBSD-version of PhantomJS. By using ports manually, it installs 1.9.8 and that one works.

**Comment by denisu** [comment]
I would consider to reopen this issue, the problem still exists.

**Comment by gekkey** [comment]
I also encounter this error.

**Comment by moneypenny** [comment]
I'm getting this, too.

vagrant@vagrant-ubuntu-trusty-64:~/my-app$ node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/.bin/phantomjs --help
/home/vagrant/my-app/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs: 4: /home/vagrant/my-app/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs: Syntax error: Unterminated quoted string

**Comment by zackw** [comment]
These error messages suggest to me that the kernel is misinterpreting the phantomjs binary as a shell script.  Also, it looks like everyone encountering the problem is installing phantomjs via NPM -- we don't build that binary and we don't know who does, and I wonder if NPM doesn't understand the difference between FreeBSD and Linux.

Could one of you with this problem please post the *unedited* output of the following commands, replacing `/path/to/binary/` with the actual path to your PhantomJS binary?

    $ file /path/to/binary/phantomjs
    $ ldd /path/to/binary/phantomjs
    $ objdump -fp /path/to/binary/phantomjs

(To reiterate: *do not edit the output*. I need to see all of it, even if it looks like it didn't work.)

**Comment by kelexel** [comment]
```
$ file /home/www/prerender/sources/prerender/node_modules/phantomjs/lib/phantom/bin/phantomjs:
/home/www/prerender/sources/prerender/node_modules/phantomjs/lib/phantom/bin/phantomjs:: cannot open `/home/www/prerender/sources/prerender/node_modules/phantomjs/lib/phantom/bin/phantomjs:' (No such file or directory)
```

```
$ ldd /home/www/prerender/sources/prerender/node_modules/phantomjs/lib/phantom/bin/phantomjs
ldd: /home/www/prerender/sources/prerender/node_modules/phantomjs/lib/phantom/bin/phantomjs: not a dynamic executable
```

```
$ objdump -fp /home/www/prerender/sources/prerender/node_modules/phantomjs/lib/phantom/bin/phantomjs
objdump: /home/www/prerender/sources/prerender/node_modules/phantomjs/lib/phantom/bin/phantomjs: File format not recognized
```

FreeBSD uses truss, not strace.. I'm unfamiliar with both, so I couldn't properlly translate -eexecve for truss..
```
truss -f -c 'exec /home/www/prerender/sources/prerender/node_modules/phantomjs/lib/phantom/bin/phantomjs'
truss: execvp exec /home/www/prerender/sources/prerender/node_modules/phantomjs/lib/phantom/bin/phantomjs: No such file or directory
syscall                     seconds   calls  errors
                      ------------- ------- -------
                        0.000000000       0       0
```

I have a test VM ready in case you need more infos

**Comment by kelexel** [comment]
Hmm *bump*
Still available if you want any additional infos, or access to a FreeBSD env..
Cheers.

**Comment by ekussberg** [comment]
I am starting a docker container with node and get following error:

```
2015-11-16T10:01:37.033Z phantom crashed, restarting...
2015-11-16T10:01:37.033Z starting phantom on port [12302]
phantom stderr: /app/node_modules/phantomjs/lib/phantom/bin/phantomjs: 4: /app/node_modules/phantomjs/lib/phantom/bin/phantomjs: Syntax error: Unterminated quoted string
```

```
FROM node:0.12-onbuild
WORKDIR /app
ADD package.json /app/
RUN npm --unsafe-perm install
ADD . /app
EXPOSE 80 8080 443
CMD [ "node", "server.js"]
```

**Comment by alenoir** [comment]
Same for me with Docker.
````
phantom stderr: /src/node_modules/phantomjs/lib/phantom/bin/phantomjs: 4: /src/node_modules/phantomjs/lib/phantom/bin/phantomjs: Syntax error: Unterminated quoted string
```
```
FROM node:0.10

ADD . /src
RUN cd /src; npm install;
WORKDIR /src

EXPOSE 3000
```

**Comment by zackw** [comment]
@kelexel Sorry for not noticing you answered my question. We get so many issues it's easy for me to miss things.

This is what I needed to know, though:

>     $ file .../node_modules/phantomjs/lib/phantom/bin/phantomjs
>     .../node_modules/phantomjs/lib/phantom/bin/phantomjs: Mach-O i386 executable

Mach-O is the object format for MacOS X.

This is a bug in NPM and/or the NPM packaging of PhantomJS - it should know not to install OSX binaries on FreeBSD, Unfortunately, we cannot do anything about this; you need to take this issue to the maintainers of the NPM package of PhantomJS and/or the maintainers of NPM itself.

**Comment by simonxu72** [comment]
freebsd install  phantomjs was a known bug : https://github.com/ariya/phantomjs/issues/12963
