### ISSUE TITLE
PhantomJS refuses connections intermittently

### ISSUE THREAD

**Issue by andreypanin** [ariya/phantomjs#12969]
I'm using Ruby 2.1.0, watir-webdriver, rspec, [taza](https://github.com/hammernight/taza), and PhantomJS 1.9.8. The OS is `Linux tester 3.2.0-4-686-pae #1 SMP Debian 3.2.65-1+deb7u1 i686 GNU/Linux`.

I run PhantomJS via `Watir::Browser.new` and supply the following command line parameters: `--ignore-ssl-errors=true --ssl-protocol=any --debug=true --cookies-file=/tmp/cookies.txt`.

There's a single spec file that fails intermittently (I'd say, likely to fail than pass) at the very beginning: `Connection refused - connect(2) for "127.0.0.1" port 8910`. In the meantime, `netstat -tulpan` shows this:

```
...
tcp        0      0 127.0.0.1:43695         127.0.0.1:8910          TIME_WAIT   -
tcp        0      0 127.0.0.1:43723         127.0.0.1:8910          TIME_WAIT   -
tcp        0      0 127.0.0.1:43743         127.0.0.1:8910          TIME_WAIT   -
tcp        0      0 127.0.0.1:43677         127.0.0.1:8910          TIME_WAIT   -
tcp        0      0 127.0.0.1:43740         127.0.0.1:8910          TIME_WAIT   -
...
```

Around 90 ports in total. They remain open after `rspec` has quit. I'm puzzled of the intermittent nature of this failure. Have anyone else encountered the same problem? Any advice, recommendation, link etc. are much appreciated. Thank you.

**Comment by kmajor** [comment]
Did you find the cause of this, I'm seeing similar behavior.

**Comment by andreypanin** [comment]
@kmajor Unfortunately, I didn't.

**Comment by andreypanin** [comment]
Selenium opens a new connection for every command. So when you, say, click a button, there're few of them. Hence the number of open ports after the program quits. I guess, it's fine. What's unclear is why at some point PhantomJS stops accepting them.

**Comment by szponek** [comment]
@andreypanin is your phantomjs process still running properly when watir fails?

I'm having a similar issue and I noticed that phantomjs crashes during my tests and that's when they start failining with: 'conn refused' message right until the end.
```
jenkins  18525 12.3  0.0      0     0 pts/1    Z+   17:07   0:03 [phantomjs] <defunct>
```
and watir reports:
```
Upload   | sample_soundclip.mp3 | fail    |
      end of file reached (EOFError)
Upload   | sample_doc.pdf            | succeed |
      Connection refused - connect(2) (Errno::ECONNREFUSED)
```

**Comment by rodrigoaguilera** [comment]
I'm tryting to switch from selenium to phantomjs and I've run into this. Did you found any workaround?

**Comment by andreypanin** [comment]
@rodrigoaguilera Unfortunately, not.

**Comment by rodrigoaguilera** [comment]
To provide more info:

I can only reproduce this on my ci server. work ok on my laptop. same php, behat, phantomjs versions...

behat (mink actually) sends http DELETE requests using curl (with no timeout since there is no easy way to configure the curl calls that mink does) to delete cookies. That request is not listened by phantomjs so the behat test is hanged forever until you kill phantomjs.
