### ISSUE TITLE
phantomjs-2.0.0-macosx - Killed: 9

### ISSUE THREAD

**Issue by wallneradam** [ariya/phantomjs#12974]
PhantomJs build for Os X cannot started. I've checked my system log and I found this in there for PhantomJs: Cannot enforce a hard page-zero for ./phantomjs.

I found this information about the problem: http://stackoverflow.com/questions/26351831/os-x-app-that-runs-on-10-6-to-10-9-doesnt-run-on-10-10-yosemite-why

Also found that the binary is packed by UPX, and this cause the problem. After I unpacked it I could use it without problem:
upx -d phantomjs

There is a bug report for UPX: http://sourceforge.net/p/upx/bugs/238/
It seems it is a problem only in v3.08. I've tested it with 3.09 and it works fine. So maybe you should upgrade UPX in your build environment.

**Comment by ariya** [comment]
Good tip @wallneradam, will give it a try. Meanwhile, let's track this on #12900.
