### ISSUE TITLE
PhantomJS doesn't throw JavaScript errors in a script file and from slots in bridge JSC objects

### ISSUE THREAD

**Issue by nathanboktae** [ariya/phantomjs#12973]
On PhantomJS 1.9.8, this exits properly with a failure message, but on 2.0, it hangs forever. (discovered while running mocha-phantomjs tests on 2.0)

Reproduction of issue:

```
var page = require('webpage').create()
page.open('http://google.com', function() {
  console.log('trying to open a nonexistantfile')
  require('fs').open('nonexistantfile').read()
  console.log('all done')
})
```

**Comment by nathanboktae** [comment]
also `fs.read` also hangs

**Comment by Vitallium** [comment]
Actually, anonymous function (`open` callback) works really weird.
For example, `throw 42` doesn't work.
````
var page = require('webpage').create()
page.open('http://google.com', function() {
  throw 42; // never throws
})
````

**Comment by ariya** [comment]
Hmm, sounds like a JavaScriptCore issue? I don't recall having this behavior with Qt 4.x and PhantomJS 1.x.

**Comment by Vitallium** [comment]
@ariya yes, it is. I'll share my findings soon.

**Comment by Vitallium** [comment]
@ariya ok, here it is.

They (Digia) changed the behavior of `QtConnectionObject::execute` in Qt5. Now it uses `JSObjectCallAsFunction` but this method has no support for forwarding exceptions.

References: 
QtConnectionObject::execute - https://github.com/ariya/phantomjs/blob/master/src/qt/qtwebkit/Source/WebCore/bridge/qt/qt_runtime.cpp#L1563
JSObjectCallAsFunction - https://github.com/ariya/phantomjs/blob/master/src/qt/qtwebkit/Source/JavaScriptCore/API/JSObjectRef.cpp#L517

That's why Qt objects will not throw any exception in Qt Webkit Bridge.

**Comment by Vitallium** [comment]
Have a fix for it. Will send a PR shortly.

**Comment by LinusU** [comment]
@Vitallium Did you ever get to publish that fix, would really help me out a ton :+1:

**Comment by pyper** [comment]
@Vitallium I see the "Patch Available" label on here, but for the life of me I can’t find a pull request or patch for it.  Could you point me in the right direction?

**Comment by Vitallium** [comment]
@pyper sure. Here is the fix https://github.com/Vitallium/qtwebkit/commit/e09b87bfe2b3ad6004d31894ee58bd611c8e3e39 It has been landed recently.

**Comment by pyper** [comment]
@Vitallium Thanks Buddy!

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://bsmotors.fr/horn.php?x>

 

klaus@hebsgaard.dk

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://mp3shine.com/lawn.php?h1>

 

klaus@hebsgaard.dk

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://hmi.co.zw/factory.php?o2t>

 

klaus@hebsgaard.dk

**Comment by mchampanis** [comment]
@Vitallium I have patched and built 2.1.1 with this https://github.com/Vitallium/qtwebkit/commit/e09b87bfe2b3ad6004d31894ee58bd611c8e3e39 and it does show errors now, but it still hangs and doesn't exit; any ideas?

**Comment by wiktortomczak** [comment]
@mchampanis Could you share the binary, if you have a linux build? Thanks!

**Comment by wiktortomczak** [comment]
@Vitallium Do you intend to release a version with this bug fixed? One that prints a stack trace and exists when an exception is thrown?

I'd like to use PhantomJS for automated tests but I can't see how until the bug is fixed.

**Comment by mchampanis** [comment]
Wiktor, I built it on macOS but can send build instructions if you need

**Comment by wiktortomczak** [comment]
Hi Michael,

If the instructions are different from
https://github.com/ariya/phantomjs/tree/2.1.1/deploy, then please share,
definitely!

thanks

**Comment by mchampanis** [comment]
Wiktor:

```
git clone git@github.com:ariya/phantomjs.git
cd phantomjs
git checkout 2.1
git submodule init
git submodule update
```
Apply https://github.com/Vitallium/qtwebkit/commit/e09b87bfe2b3ad6004d31894ee58bd611c8e3e39 to `src/qt/qtwebkit/Source/WebCore/bridge/qt/qt_runtime.cpp`

```
sudo apt-get install build-essential g++ flex bison gperf ruby perl \
   libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev=1.0.1t-1+deb8u2 \
   libpng-dev libjpeg-dev python libx11-dev libxext-dev ttf-mscorefonts-installer
python build.py --jobs 4 --confirm
```

**Comment by tprdeepaklal** [comment]
@Vitallium On page error still process does not exits. Is there any other patch for this issue ?

**Comment by mchampanis** [comment]
@tprdeepaklal, try put this handler at the top of your script:

```
phantom.onError = function(msg, trace) {
    var msgStack = [msg];
    if (trace && trace.length) {
        trace.forEach(function(t) {
            msgStack.push(' -> ' + t.file + ': ' + t.line + (t.function ? ' (in function "' + t.function +'")' : ''));
        });
    }    
    console.log('\n' + msgStack.join('\n') + '\n');
    phantom.exit(1);
};
```

**Comment by tprdeepaklal** [comment]
@mchampanis Already have onError handlers as `"page.onError"` and `"phantom.onError"`
but it hangs and control were not reaching `"page.onError"` method

**Comment by mchampanis** [comment]
@tprdeepaklal maybe this? https://github.com/ariya/phantomjs/pull/14111/files

**Comment by tprdeepaklal** [comment]
@mchampanis Can u explain me, how will this resolve my issue ?
>https://github.com/ariya/phantomjs/pull/14111/files - mepard committed on Mar 17, 2016

<img width="770" alt="screen shot 2017-04-25 at 5 47 03 pm" src="https://cloud.githubusercontent.com/assets/5648213/25384876/8a6cc600-29df-11e7-901b-2439612b2286.png">
