### ISSUE TITLE
external and local css gets ignored when rendering page to pdf

### ISSUE THREAD

**Issue by kahizer** [ariya/phantomjs#12981]
I would like to know if there is a way to force phamtonjs to read/respect my css styles.
Im currently using angular and ui-grid to generate a table and when a value in the table meets a condition(if value > 1000) it will get assigned to a specific css class. 

I have noticed that it recognizes "text-align: center;" property but it wont recognize/enforce the color "color: red !important;" i have also tried "color: red;" or moving the css style and having it locally in my html file but it doesn't work. 

css file
![stylecss](https://cloud.githubusercontent.com/assets/8674217/6134165/217c0e8a-b114-11e4-88fe-663b687fe7cb.PNG)

webapge
![webpage_display](https://cloud.githubusercontent.com/assets/8674217/6133916/56146f86-b112-11e4-922f-c2c09a514011.PNG)

pdf file
![pdf_display](https://cloud.githubusercontent.com/assets/8674217/6133921/61c66e7e-b112-11e4-8948-7ec326ce055d.PNG)

Im currently using Phantomjs 2.0.0 and tested with the Chrome/Firefox,
Thank you

**Comment by kahizer** [comment]
fixed issue by using "-webkit-text-fill-color: red !important;" instead of "color: red !important;"

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://hj99.net/rice.php?jgq>

 

klaus@hebsgaard.dk
