### ISSUE TITLE
'throw' doesn't work in page callback

### ISSUE THREAD

**Issue by pulupulu01** [ariya/phantomjs#12988]
Phantomjs version 2.0.0
Environment: windows 7 64bit

----- code start -----
var webpage = require('webpage');
var page = webpage.create();
//throw new Error('test error in global');        //it works well
page.open('about:blank',function(s){
    if(s === 'success')
        console.log('open successful!'); 
    throw new Error('test error in local');    //it doesn't work!
});
----- code end -----

I am new to phantomjs.  Is this a bug?  Thanks!

**Comment by Vitallium** [comment]
Duplicate #12973
