### ISSUE TITLE
phantom.args is not exactly the same as system.args

### ISSUE THREAD

**Issue by bskendig** [ariya/phantomjs#12994]
phantom.args and system.args are both arrays of the arguments passed to the script. But system.args includes the name of the script, while phantom.args does not.

phantom.args = [ arg1, arg2, ...]
system.args = [ scriptname, arg1, arg2, ... ]

Additionally, phantom.args no longer works in phantomjs 2.0. If someone simply updates phantom.args to system.args, this can result in some existing scripts failing.

Please update http://phantomjs.org/api/phantom/property/args.html to let a developer know that:
- phantom.args is no longer deprecated, but removed altogether
- a developer will need to check his array index when changing to system.args

**Comment by DrPandemic** [comment]
You are right, this proprety was removed with https://github.com/ariya/phantomjs/commit/6c6059fd912113c351e6d1d83dbc5891ebe21a23
