### ISSUE TITLE
PhantomJS for Windows grew by 40mb in version 2.0

### ISSUE THREAD

**Issue by mmanela** [ariya/phantomjs#13005]
This is less of a bug but more of a "make sure you are aware of this". The file size for PhantomJS 2.0 in the windows static build is about 40mb larger than the previous version. Is this expected? 

I just want to make sure there wasn't some static compilation issue and that this increase is by design.

Thanks.

**Comment by Vitallium** [comment]
Previous versions were compressed by UPX. But UXP can't process PhantomJS 2.0. There is a bug in UPX, so we're just waiting for a fix. (FYI: UPX still can't process TLS properly)

**Comment by mmanela** [comment]
Ok that is good to know, thanks for the quick reply. I ship PhantomJS with my project and was concerned about quadrupling my download size. 

Is there any ETA on when this fix may come?

**Comment by ariya** [comment]
I don't think you should rely much on PhantomJS executable size. If you are concerned about the size, your bundled PhantomJS with your project needs to be in a compressed archive (e.g. ZIP).

**Comment by bpasero** [comment]
+1 for small size, would like to update but this blocks

**Comment by JamesMGreene** [comment]
@Vitallium Do you have a UPX bug/issue link for this?

**Comment by Vitallium** [comment]
@JamesMGreene it wasn't a UPX issue. It was on the Qt's side. Because when did the upgrade to Qt 5.2.1 (not sure about version), the issue just went off.

**Comment by JamesMGreene** [comment]
So should this issue be closed now, then?

**Comment by Vitallium** [comment]
Yes!

**Comment by JamesMGreene** [comment]
:+1:
