### ISSUE TITLE
PhantomJS 2.0 crash report

### ISSUE THREAD

**Issue by idlebeet** [ariya/phantomjs#13003]
crashed both windows binary and my own build on linux when open "www.today.com"

input file

``` javascript
var page = require('webpage').create();
page.open('http://www.today.com', function() {
  window.setTimeout(function () {
    page.render('test.png');
    phantom.exit();
  }, 1000);
});
```

crash dump file
https://drive.google.com/file/d/0B1dp8X2fqTO-dDdQY2ZuZ2hwaGM/view?usp=sharing

gdb trace

```
Program received signal SIGSEGV, Segmentation fault.
0x09b12758 in QFontconfigDatabase::fontEngine(QByteArray const&, double, QFont::HintingPreference) ()
(gdb) backtrace
#0  0x09b12758 in QFontconfigDatabase::fontEngine(QByteArray const&, double, QFont::HintingPreference) ()
#1  0x09cd4b0f in QRawFontPrivate::platformLoadFromData(QByteArray const&, double, QFont::HintingPreference) ()
#2  0x09cca420 in QRawFont::QRawFont(QByteArray const&, double, QFont::HintingPreference) ()
#3  0x08530975 in WebCore::createFontCustomPlatformData(WebCore::SharedBuffer*) ()
#4  0x082989f5 in WebCore::CachedFont::ensureCustomFontData() ()
#5  0x09185c72 in WebCore::CSSFontFaceSource::getFontData(WebCore::FontDescription const&, bool, bool, WebCore::CSSFontSelector*) ()
#6  0x09186311 in WebCore::CSSFontFace::getFontData(WebCore::FontDescription const&, bool, bool) ()
#7  0x0919242e in WebCore::CSSSegmentedFontFace::getFontData(WebCore::FontDescription const&) ()
#8  0x091928dc in WebCore::CSSFontSelector::getFontData(WebCore::FontDescription const&, WTF::AtomicString const&) ()
#9  0x083d32b8 in WebCore::FontCache::getFontData(WebCore::FontDescription const&, int&, WebCore::FontSelector*) ()
#10 0x083bf5db in WebCore::FontGlyphs::realizeFontDataAt(WebCore::FontDescription const&, unsigned int) const ()
#11 0x08eaf31f in WebCore::RenderStyle::fontMetrics() const ()
#12 0x08eaf55c in WebCore::RenderStyle::computedLineHeight(WebCore::RenderView*) const ()
#13 0x09039006 in WebCore::RenderBlock::lineHeight(bool, WebCore::LineDirectionMode, WebCore::LinePositionMode) const ()
#14 0x090370dd in WebCore::logicalHeightForLine(WebCore::RenderBlock const*, bool, WebCore::LayoutUnit) ()
#15 0x090f88e8 in WebCore::RenderBlock::LineBreaker::nextSegmentBreak(WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::LineInfo&, WebCore::RenderBlock::RenderTextInfo&, WebCore::RenderBlock::FloatingObject*, unsigned int, WTF::Vector<WebCore::WordMeasurement, 64u, WTF::CrashOnOverflow>&) ()
#16 0x090fdfbd in WebCore::RenderBlock::LineBreaker::nextLineBreak(WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::LineInfo&, WebCore::RenderBlock::RenderTextInfo&, WebCore::RenderBlock::FloatingObject*, unsigned int, WTF::Vector<WebCore::WordMeasurement, 64u, WTF::CrashOnOverflow>&) ()
#17 0x09100f29 in WebCore::RenderBlock::layoutRunsAndFloatsInRange(WebCore::LineLayoutState&, WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::InlineIterator const&, WebCore::BidiStatus const&, unsigned int) ()
#18 0x09102f60 in WebCore::RenderBlock::layoutRunsAndFloats(WebCore::LineLayoutState&, bool) ()
#19 0x09103640 in WebCore::RenderBlock::layoutInlineChildren(bool, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#20 0x09104021 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#21 0x08fcb7e7 in WebCore::RenderBlock::layout() ()
#22 0x090d58dc in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#23 0x090f7f0c in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
#24 0x0910481b in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#25 0x08fcb7e7 in WebCore::RenderBlock::layout() ()
#26 0x090d58dc in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#27 0x090f7f0c in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
#28 0x0910481b in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#29 0x08fcb7e7 in WebCore::RenderBlock::layout() ()
#30 0x090d58dc in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#31 0x090f7f0c in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
#32 0x0910481b in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#33 0x08fcb7e7 in WebCore::RenderBlock::layout() ()
#34 0x090d58dc in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#35 0x090f7f0c in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
#36 0x0910481b in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#37 0x08fcb7e7 in WebCore::RenderBlock::layout() ()
#38 0x090d58dc in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#39 0x090f7f0c in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
#40 0x0910481b in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#41 0x08fcb7e7 in WebCore::RenderBlock::layout() ()
#42 0x090d58dc in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#43 0x090f7f0c in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
#44 0x0910481b in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#45 0x08fcb7e7 in WebCore::RenderBlock::layout() ()
#46 0x090d58dc in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#47 0x090f7f0c in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
#48 0x0910481b in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#49 0x08fcb7e7 in WebCore::RenderBlock::layout() ()
#50 0x09018bd2 in WebCore::RenderView::layoutContent(WebCore::LayoutState const&) ()
#51 0x0906338c in WebCore::RenderView::layout() ()
#52 0x08378ccc in WebCore::FrameView::layout(bool) ()
#53 0x0836d035 in WebCore::Timer<WebCore::FrameView>::fired() ()
---Type <return> to continue, or q <return> to quit---
#54 0x0847300a in WebCore::ThreadTimers::sharedTimerFiredInternal() ()
#55 0x08473085 in WebCore::ThreadTimers::sharedTimerFired() ()
#56 0x085542fe in WebCore::SharedTimerQt::timerEvent(QTimerEvent*) ()
#57 0x0a0a4dd4 in QObject::event(QEvent*) ()
#58 0x09730934 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
#59 0x09734462 in QApplication::notify(QObject*, QEvent*) ()
#60 0x0a07990e in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
#61 0x0a0c5a1a in QTimerInfoList::activateTimers() ()
#62 0x0a0c37d0 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#63 0x09b1599e in QUnixEventDispatcherQPA::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#64 0x0a07752c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#65 0x0a07c93e in QCoreApplication::exec() ()
#66 0x09b40d34 in QGuiApplication::exec() ()
#67 0x0972bd44 in QApplication::exec() ()
#68 0x080629a5 in main ()
```

**Comment by easmith** [comment]
I had the same crash 
````
var page = require('webpage').create();

var address = "http://www.news.com.au/lifestyle/fashion/most-amazing-celebrity-wedding-dresses/story-fnjev484-1226932119612";

page.open(address, function(status) {
  console.log("Status: " + status);
  phantom.exit();
});
```
Other problem page
```
http://www.dailymotion.com/video/xrx7sl_how-to-spot-fake-chanel-sunglasses_lifestyle
http://globalgrind.com/2014/04/13/2014-mtv-movie-awards-lupita-nyongo-chanel-dress-red-carpet-photos/
http://www.thelittlebirdinc.com/products/vintage-chanel-flower-print-dress
http://www.vintagefive.com/pages/authenticity
```

**Comment by MarkR42** [comment]
Me too, latest from git

    #0  0x0000000001c3b548 in QFontconfigDatabase::fontEngine(QByteArray const&, double, QFont::HintingPreference) ()
    #1  0x0000000001dda88a in QRawFontPrivate::platformLoadFromData(QByteArray const&, double, QFont::HintingPreference) ()
    #2  0x0000000000875df4 in WebCore::createFontCustomPlatformData(WebCore::SharedBuffer*) ()
    #3  0x000000000061df16 in WebCore::CachedFont::ensureCustomFontData() ()
    #4  0x00000000013af0dc in WebCore::CSSFontFaceSource::getFontData(WebCore::FontDescription const&, bool, bool, WebCore::CSSFontSelector*) ()
    #5  0x00000000013af543 in WebCore::CSSFontFace::getFontData(WebCore::FontDescription const&, bool, bool) ()
    #6  0x00000000013b85bb in WebCore::CSSSegmentedFontFace::getFontData(WebCore::FontDescription const&) ()
    #7  0x00000000013e69b1 in WebCore::CSSFontSelector::getFontData(WebCore::FontDescription const&, WTF::AtomicString const&) ()
    #8  0x000000000073ae2e in WebCore::FontCache::getFontData(WebCore::FontDescription const&, int&, WebCore::FontSelector*) ()
    #9  0x000000000072741b in WebCore::FontGlyphs::realizeFontDataAt(WebCore::FontDescription const&, unsigned int) const ()
    #10 0x0000000001108a96 in WebCore::RenderStyle::computedLineHeight(WebCore::RenderView*) const ()
    #11 0x000000000126a57c in WebCore::RenderBlock::lineHeight(bool, WebCore::LineDirectionMode, WebCore::LinePositionMode) const ()
    #12 0x0000000001272255 in WebCore::logicalHeightForLine(WebCore::RenderBlock const*, bool, WebCore::LayoutUnit) ()
    #13 0x00000000012aea0a in WebCore::LineWidth::updateAvailableWidth(WebCore::LayoutUnit) ()
    #14 0x000000000130ec9b in WebCore::RenderBlock::LineBreaker::nextSegmentBreak(WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::LineInfo&, WebCore::RenderBlock::RenderTextInfo&, WebCore::RenderBlock::FloatingObject*, unsigned int, WTF::Vector<WebCore::WordMeasurement, 64ul, WTF::CrashOnOverflow>&) ()
    #15 0x0000000001312e4d in WebCore::RenderBlock::LineBreaker::nextLineBreak(WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::LineInfo&, WebCore::RenderBlock::RenderTextInfo&, WebCore::RenderBlock::FloatingObject*, unsigned int, WTF::Vector<WebCore::WordMeasurement, 64ul, WTF::CrashOnOverflow>&) ()
    #16 0x00000000013153e0 in WebCore::RenderBlock::layoutRunsAndFloatsInRange(WebCore::LineLayoutState&, WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::InlineIterator const&, WebCore::BidiStatus const&, unsigned int) ()
    #17 0x0000000001317869 in WebCore::RenderBlock::layoutRunsAndFloats(WebCore::LineLayoutState&, bool) ()
    #18 0x0000000001317f7e in WebCore::RenderBlock::layoutInlineChildren(bool, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
    #19 0x00000000013188e6 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
    #20 0x000000000120d245 in WebCore::RenderBlock::layout() ()
    #21 0x00000000012cc4c2 in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
    #22 0x000000000130bd30 in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
    #23 0x0000000001318b60 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
    #24 0x000000000120d245 in WebCore::RenderBlock::layout() ()
    #25 0x00000000012cc4c2 in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
    #26 0x000000000130bd30 in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
    #27 0x0000000001318b60 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
    #28 0x000000000120d245 in WebCore::RenderBlock::layout() ()
    #29 0x00000000012cc4c2 in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
    #30 0x000000000130bd30 in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
    #31 0x0000000001318b60 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
    #32 0x000000000120d245 in WebCore::RenderBlock::layout() ()
    #33 0x00000000012c97e4 in WebCore::RenderBlock::insertFloatingObject(WebCore::RenderBox*) ()
    #34 0x000000000130e80e in WebCore::RenderBlock::LineBreaker::skipLeadingWhitespace(WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::LineInfo&, WebCore::RenderBlock::FloatingObject*, WebCore::LineWidth&) ()
    #35 0x000000000130ecc6 in WebCore::RenderBlock::LineBreaker::nextSegmentBreak(WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::LineInfo&, WebCore::RenderBlock::RenderTextInfo&, WebCore::RenderBlock::FloatingObject*, unsigned int, WTF::Vector<WebCore::WordMeasurement, 64ul, WTF::CrashOnOverflow>&) ()
    #36 0x0000000001312e4d in WebCore::RenderBlock::LineBreaker::nextLineBreak(WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::LineInfo&, WebCore::RenderBlock::RenderTextInfo&, WebCore::RenderBlock::FloatingObject*, unsigned int, WTF::Vector<WebCore::WordMeasurement, 64ul, WTF::CrashOnOverflow>&) ()
    ---Type <return> to continue, or q <return> to quit---
    #37 0x00000000013153e0 in WebCore::RenderBlock::layoutRunsAndFloatsInRange(WebCore::LineLayoutState&, WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::InlineIterator const&, WebCore::BidiStatus const&, unsigned int) ()
    #38 0x0000000001317869 in WebCore::RenderBlock::layoutRunsAndFloats(WebCore::LineLayoutState&, bool) ()
    #39 0x0000000001317f7e in WebCore::RenderBlock::layoutInlineChildren(bool, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
    #40 0x00000000013188e6 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
    #41 0x000000000120d245 in WebCore::RenderBlock::layout() ()
    #42 0x00000000012c97e4 in WebCore::RenderBlock::insertFloatingObject(WebCore::RenderBox*) ()
    #43 0x000000000130bcdb in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
    #44 0x0000000001318b60 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
    #45 0x000000000120d245 in WebCore::RenderBlock::layout() ()
    #46 0x00000000012c97e4 in WebCore::RenderBlock::insertFloatingObject(WebCore::RenderBox*) ()
    #47 0x000000000130e80e in WebCore::RenderBlock::LineBreaker::skipLeadingWhitespace(WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::LineInfo&, WebCore::RenderBlock::FloatingObject*, WebCore::LineWidth&) ()
    #48 0x000000000130ecc6 in WebCore::RenderBlock::LineBreaker::nextSegmentBreak(WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::LineInfo&, WebCore::RenderBlock::RenderTextInfo&, WebCore::RenderBlock::FloatingObject*, unsigned int, WTF::Vector<WebCore::WordMeasurement, 64ul, WTF::CrashOnOverflow>&) ()
    #49 0x0000000001312e4d in WebCore::RenderBlock::LineBreaker::nextLineBreak(WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::LineInfo&, WebCore::RenderBlock::RenderTextInfo&, WebCore::RenderBlock::FloatingObject*, unsigned int, WTF::Vector<WebCore::WordMeasurement, 64ul, WTF::CrashOnOverflow>&) ()
    #50 0x00000000013153e0 in WebCore::RenderBlock::layoutRunsAndFloatsInRange(WebCore::LineLayoutState&, WebCore::BidiResolver<WebCore::InlineIterator, WebCore::BidiRun>&, WebCore::InlineIterator const&, WebCore::BidiStatus const&, unsigned int) ()
    #51 0x0000000001317869 in WebCore::RenderBlock::layoutRunsAndFloats(WebCore::LineLayoutState&, bool) ()
    #52 0x0000000001317f7e in WebCore::RenderBlock::layoutInlineChildren(bool, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
    #53 0x00000000013188e6 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
    #54 0x000000000120d245 in WebCore::RenderBlock::layout() ()
    #55 0x00000000012c97e4 in WebCore::RenderBlock::insertFloatingObject(WebCore::RenderBox*) ()
    #56 0x000000000130bcdb in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
    #57 0x0000000001318b60 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
    #58 0x000000000120d245 in WebCore::RenderBlock::layout() ()
    #59 0x00000000012cc4c2 in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
    #60 0x000000000130bd30 in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
    #61 0x0000000001318b60 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
    #62 0x000000000120d245 in WebCore::RenderBlock::layout() ()
    #63 0x00000000012cc4c2 in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
    #64 0x000000000130bd30 in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
    #65 0x0000000001318b60 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
    #66 0x000000000120d245 in WebCore::RenderBlock::layout() ()
    #67 0x00000000012cc4c2 in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
    #68 0x000000000130bd30 in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
    #69 0x0000000001318b60 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
    #70 0x000000000120d245 in WebCore::RenderBlock::layout() ()
    #71 0x00000000012cc4c2 in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
    #72 0x000000000130bd30 in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
    #73 0x0000000001318b60 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
    #74 0x000000000120d245 in WebCore::RenderBlock::layout() ()
    #75 0x000000000124aff9 in WebCore::RenderView::layoutContent(WebCore::LayoutState const&) ()
    ---Type <return> to continue, or q <return> to quit---
    #76 0x000000000129e2a9 in WebCore::RenderView::layout() ()
    #77 0x00000000006f1d55 in WebCore::FrameView::layout(bool) ()
    #78 0x00000000007c9b29 in WebCore::ThreadTimers::sharedTimerFiredInternal() ()
    #79 0x0000000002183731 in QObject::event(QEvent*) ()
    #80 0x00000000018efcfc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    #81 0x00000000018f48ce in QApplication::notify(QObject*, QEvent*) ()
    #82 0x000000000215e415 in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
    #83 0x00000000021a2e8d in QTimerInfoList::activateTimers() ()
    #84 0x00000000021a14a5 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    #85 0x0000000001c3d08d in QUnixEventDispatcherQPA::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    #86 0x000000000215c221 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    #87 0x0000000002163b59 in QCoreApplication::exec() ()
    #88 0x000000000042c45a in main ()

**Comment by MarkR42** [comment]
Crash URL is http://eenadu.net/

Seems to be 100% reproducible.

**Comment by MarkR42** [comment]
Seems fixed in https://github.com/yali25/phantomjs.git
