### ISSUE TITLE
phantomJS 2.0 not obeying box model as well as previous versions

### ISSUE THREAD

**Issue by trickeyone** [ariya/phantomjs#13006]
I've observed that v2.0.0 is not observing the box model the same way that 1.9.x had been, or as current releases of Chrome/Webkit browsers do. One key example is that `display: block;` and `display: inline-block;` elements are not obeying layout rules.

i.e.

``` html
<div style="display: block; width: 140px; padding: 10px; font-size: 23px;">
  <div style="display: inline-block;">
    <span style="white-space: nowrap;">Some really long text here that keeps going outside the container element's boundaries</span>
  </div>
</div>
```

This kind of layout produces a span element that's content does, as expected, go outside it's parent's boundaries, but when you check the span's width or scrollWidth, it's being reported as the parent's inner width. The span element's scrollWidth should be the actual width of the content. This is a major violation of the box model and is breaking things that I had working in 1.9.x versions. I wanted to move to 2.0.0 because it fixed the multiple fonts issue that existed in previous versions but this is a major blocker for adoption.

**Comment by atteeela** [comment]
I've also moved to 2.0 because of the multiple fonts issue and now I'm experiencing this problem with text layout. In particular adjusting letter-spacing and text-align:right goes outside of the box.

**Comment by ryana** [comment]
I'm seeing this issue in 1.9.8. @trickeyone what [x] in 1.9.[x] did you see this working in?

**Comment by israelidanny** [comment]
I'm experiencing this on 1.9.8 as well, on CentOS Linux. This is at its' worst when trying to render right-to-left text.
