### ISSUE TITLE
2.0.0 regression in file uploading

### ISSUE THREAD

**Issue by xaviershay** [ariya/phantomjs#13000]
The following simple file uploading spec passes on 1.9.7, but fails against 2.0.0. On OSX Yosemite.

https://github.com/teampoltergeist/poltergeist/pull/585

**Comment by Drahakar** [comment]
MIght be a duplicate of https://github.com/ariya/phantomjs/issues/12506

**Comment by xaviershay** [comment]
yep, pretty sure this is a dup. Closing in favour.
