### ISSUE TITLE
Text using webfonts is not selectable in PDF with 2.0

### ISSUE THREAD

**Issue by mikaraunio** [ariya/phantomjs#13008]
This is with PhantomJS 2.0 built on Debian wheezy from commit 26ed336:

When I render a page containing OpenType web fonts to PDF, the text in the resulting file is not selectable with either Preview or Adobe Reader on OS X.

If I remove the web font references, the text becomes selectable again.

**Comment by tedeh** [comment]
I'm experiencing this problem. Anyone got any tips?

**Comment by mikaraunio** [comment]
To double-check, I rendered the same HTML with the same script, but using PhantomJS 1.9.7, and the text was selectable again. This definitely looks like a regression, and should be labelled as such.

Also, I'm seeing this with both TTF and OTF fonts.

@tedeh if you're rendering private content, you could try installing the fonts on the host running PhantomJS and use them locally, and see if that gets you anywhere?

**Comment by gkop** [comment]
@mikaraunio to answer your question, yes, in my case using the same TTF font locally rather than with `@font-face` made the text selectable.

**Comment by mikaraunio** [comment]
I second @gkop 's observation, using the fonts locally makes the text selectable for me as well with every font I have tried so far.

**Comment by robinfhu** [comment]
Hi is there a fix for this issue?  Getting the same problem on Ubuntu 12.04.4.  We are using ProximaNova WOFF fonts, and the PDF generated doesn't have any selectable text.
