### ISSUE TITLE
Ubuntu 12.04: "You don't seem to have 'make' or 'gmake' in your PATH"

### ISSUE THREAD

**Issue by mikedotexe** [ariya/phantomjs#13010]
This is more of a documentation suggestion for:
http://phantomjs.org/build.html

For Ubuntu, to clear the error I had to additionally:
`sudo apt-get install build-essential`

before I could:
`./build.sh`

**Comment by ariya** [comment]
`build-essential` is now mentioned explicitly in the documentation. Thank you!
