### ISSUE TITLE
Source code refactor - Abstract common functionality from redundant methods.

### ISSUE THREAD

**Issue by krishnanm86** [ariya/phantomjs#13022]
* Abstract LinuxDumper::FindBeginningOfLinuxGateSharedLibrary and LinuxDumper::FindEntryPoint in  src\breakpad\src\client\linux\minidump_writer\linux_dumper.cc

* Abstract GUIDString::GUIDToWString and GUIDString::GUIDToSymbolServerWString in \src\breakpad\src\common\windows\guid_string.cc

**Comment by ariya** [comment]
This is not PhantomJS specific code. Please track it at the upstream Breakpad project. Thank you!

**Comment by krishnanm86** [comment]
Oh . That is unfortunate. I just noticed the Breakpad project from darwin seems to be inactive for many years. Is there an active breakpad repository. I am working on  evaluating a research tool that can refactor and abstract redundant code and was hoping for some acceptable pull requests. Thanks for the information anyway
