### ISSUE TITLE
PhantomJS 2.0 webserver module response.setEncoding("binary") not working

### ISSUE THREAD

**Issue by lweigand** [ariya/phantomjs#13026]
In phantomjs 2.0, calling `setEncoding("binary")` on the response object has no effect. What was working fine with version 1.9.7_1 now seems to be broken.
Code to replicate (where test.pdf may be any other binary file in the directory of the script):
```javascript
var server	= require('webserver').create(),
   	    fs  = require('fs');

server.listen(8000, function(request, response) {
	response.statusCode = 200;
	response.setHeader('Content-type', 'application/pdf')
	response.setEncoding('binary');

	response.write( fs.read('test.pdf', 'b') );
	response.close();	
});
```

I am running on Mac OSX 10.10.

**Comment by andrewsavill** [comment]
I can also confirm that this is true.  Multiple hours were spent wondering why examples wouldn't work so thank you @lweigand :D.  Works fine on 1.9.8 on Windows.

**Comment by Verikon** [comment]
Confirmed this is broken.

**Comment by sunyang213** [comment]
Confirmed in windows. It worked with version 1.9.8.

The pdf file downloaded from response cannot be opened, Adobe Reader says it is damaged.

I also found version 2.0 generates large PDF than 1.9.8 for same page.

**Comment by smalltalking** [comment]
It looks like the content is encoded to UTF-8 - something that doesn't happen with 1.9.7 - then it gets truncated to the length before the encoding, so the end of the file is lost.

**Comment by griffinmyers** [comment]
+1 big bummer

**Comment by jigfox** [comment]
confirmed on mac, too

downgrading to phantomjs 1.9.8 helped solving this issue

**Comment by marcosbrigante** [comment]
Same here. Any workarounds to avoid downgrading?

**Comment by griffinmyers** [comment]
@marcosbrigante we pushed the encoding down into the client, i.e. in the response handler from phantom did something like this: 


``` javascript
 var binaryString = new Buffer(response).toString('utf-8');
 return new Buffer(binaryString, 'binary');
```

**Comment by marcosbrigante** [comment]
@griffinmyers thanks I will give it a try. My current workaround is to use base64 instead of binary to transfer the pdf.

```javascript
response.setHeader('Content-type', 'application/base64');
response.write(btoa(fs.read('test.pdf', 'b')));
```

**Comment by Vitallium** [comment]
Pull request: https://github.com/ariya/phantomjs/pull/13452

**Comment by sunyang213** [comment]
For anyone still stuck here, please try this work around. Thanks for @marcosbrigante  and all other posts.

PhantomJS script:

    var pdfStream = fs.open(fileLocation, 'rb'); 
    var pdfContent = pdfStream.read(); 				
    var base64Encoded = btoa(pdfContent);
    response.statusCode = 200;
    response.headers = {
					'Cache': 'no-cache',
					'Content-Type': 'application/base64',
					'Connection': 'Keep-Alive',
					'Content-Length': base64Encoded.length.toString()
					};
    response.write(base64Encoded);
    response.close();


Server side [C#]:

    HttpWebResponse response =     (HttpWebResponse)httpWReq.GetResponse();
    using (Stream stream = response.GetResponseStream())
    {
        using (StreamReader readStream = new StreamReader(stream))
        {
            string base64String = readStream.ReadToEnd();
            byte[] decodedArray = Convert.FromBase64String(test);

            // The following three lines are testing if content is a valid pdf
            using (FileStream stream1 = System.IO.File.Create("c:\\test.pdf"))
            {
                stream1.Write(decodedArray, 0, decodedArray.Length);
            }
            return decodedArray;
    }

    //decodedArray could be then added in a  HttpRequest

**Comment by jigfox** [comment]
Is there a timeline, when this will be released?

**Comment by rcarmo** [comment]
I'm still having trouble with this, even with 2.1. Is that ".toLatin()" conversion right?

**Comment by Vitallium** [comment]
@rcarmo yes. It works. Just tested it.

**Comment by rcarmo** [comment]
for me, this:
{{{
res.setEncoding('binary');
res.write(fs.open(path,'rb').read());
res.close();
}}}

Is still failing under 2.1. Trying to figure out why...

**Comment by kkeybbs** [comment]
I'm not sure if I'm running with an old version(2.0.0-windows), setEncoding('binary') doesn't work.
Instead rsp.setEncoding('latin1') works with binary data.
