### ISSUE TITLE
Error: Could not start Ghostdriver

### ISSUE THREAD

**Issue by rajendraarora16** [ariya/phantomjs#13023]
Hello sir, I'm using Phantomjs. I googled and did everything to make the possibilities. But It seems It's a kind of bug. That's why i come here to tell you. Sir, I'm getting this error from 2 months. I asked the same question everywhere and did everything but nothing resolved me.

Okay, So my issue is:

You ghostdriver runs successfully on my PC/laptop. But when i upload my project into server. Let's say Openshift. It says the following error:

`PhantomJS is launching GhostDriver... [ERROR - 2014-08-01T04:14:21.160Z] GhostDriver - main.fail - {"message":"Could not start Ghost Driver","line":82,"sourceId":139887801789952,"sourceURL":":/ghostdriver/main.js","stack":"Error: Could not start Ghost Driver\n at :/ghostdriver/main.js:82","stackArray":[{"sourceURL":":/ghostdriver/main.js","line":82}]} $ ./phantomjs --version 1.9.8`

I also tried by using 1.9.7 version but nothing worked to me.

I can see the phantomjs version by using ./phantomjs -v. But unable to start ghostdriver. Please help How can i resolve this issues?

Please help! :(

**Comment by ariya** [comment]
Please bring this up with the Ghost Driver project instead.

**Comment by rajendraarora16** [comment]
Sir, I don't get you!.. Ghost driver is not running on server. But it runs on my laptop. It's a bug i guess! :( I'm getting this error from 2 months :(

**Comment by rajendraarora16** [comment]
Sir, Ghost driver is the part of PhantomJS. You should take a look.

**Comment by JamesMGreene** [comment]
GhostDriver is an embedded component within PhantomJS, not a core part of it. Please submit an issue to [detro/GhostDriver](https://github.com/detro/GhostDriver) as @ariya already correctly advised.
