### ISSUE TITLE
PhantomJS randomly crashes while running protractor e2e test

### ISSUE THREAD

**Issue by d3day** [ariya/phantomjs#13029]
# Setup:

maven (maven-ng-protractor 0.0.2)  
protractor 1.3.1
phantomjs 1.9.7
webdriver-selenium 2.42.1

once for a while (sometimes about a half of builds) crash is happening :
# Logs:
## maven relevant log entries:

Message:
[INFO]      Error: ECONNREFUSED connect ECONNREFUSED
[INFO]    Stacktrace:
[INFO]      Error: ECONNREFUSED connect ECONNREFUSED
[INFO]     at ClientRequest.emit (events.js:95:17)
[INFO]     at Socket.socketErrorListener (http.js:1551:9)
[INFO]     at Socket.emit (events.js:95:17)
[INFO]     at net.js:440:14
[INFO]     at process._tickCallback (node.js:419:13)
[INFO] ==== async task ====
[INFO] WebDriver.navigate().to(data:text/html,<html></html>)
[INFO]     at Object.webrep.pages.create (/home/src/portal/portal-webapp/src/test/e2e/someTest/webDataObject.js:32:37)
[INFO]     at [object Object].<anonymous> (/home/src/portal/portal-webapp/src/test/e2e/someTest/webSpec.js:27:22)
[INFO] ==== async task ====
[INFO] Asynchronous test function: it()
[INFO] Error
[INFO]     at [object Object].<anonymous> (/home/src/portal/portal-webapp/src/test/e2e/someTest/webSpec.js:26:5)
[INFO]     at Object.<anonymous> (/home/src/portal/portal-webapp/src/test/e2e/someTest/webSpec.js:1:63)

....(rest of e2e tests are failing after first fails)
## phantomjs relevant log entries:

[DEBUG] WebPage - evaluateJavaScript result QVariant(QString, "{"status":0,"value":"User-Agent header"}")
[DEBUG] HTTP Response - Status Code 200 OK
[DEBUG] HTTP Response - Sending Header "Cache" = "no-cache"
[DEBUG] HTTP Response - Sending Header "Content-Length" = "91"
[DEBUG] HTTP Response - Sending Header "Content-Type" = "application/json;charset=UTF-8"
[DEBUG] HTTP Request - URI /session/f5a377c0-bd03-11e4-996d-a54813631f33/window/current/maximize
[DEBUG] HTTP Request - Method POST
[DEBUG] HTTP Request - HTTP Version 1.1
[DEBUG] HTTP Request - Query String
[DEBUG] HTTP Request - Receiving Header "Accept" = "application/json; charset=utf-8"
[DEBUG] HTTP Request - Receiving Header "Content-Length" = "2"
[DEBUG] HTTP Request - Receiving Header "Content-Type" = "application/json;charset=UTF-8"
[DEBUG] HTTP Request - Receiving Header "Host" = "127.0.0.1:4444"
[DEBUG] HTTP Request - Receiving Header "Connection" = "keep-alive"
[DEBUG] HTTP Request - Method POST/PUT
[DEBUG] HTTP Request - Content Body: {}
[DEBUG] HTTP Response - Status Code 200 OK
[DEBUG] HTTP Response - Sending Header "Cache" = "no-cache"
[DEBUG] HTTP Response - Sending Header "Content-Length" = "74"
[DEBUG] HTTP Response - Sending Header "Content-Type" = "application/json;charset=UTF-8"
[DEBUG] HTTP Request - URI /session/f5a377c0-bd03-11e4-996d-a54813631f33/url
[DEBUG] HTTP Request - Method POST
[DEBUG] HTTP Request - HTTP Version 1.1
[DEBUG] HTTP Request - Query String
[DEBUG] HTTP Request - Receiving Header "Accept" = "application/json; charset=utf-8"
[DEBUG] HTTP Request - Receiving Header "Content-Length" = "38"
[DEBUG] HTTP Request - Receiving Header "Content-Type" = "application/json;charset=UTF-8"
[DEBUG] HTTP Request - Receiving Header "Host" = "127.0.0.1:4444"
[DEBUG] HTTP Request - Receiving Header "Connection" = "keep-alive"
[DEBUG] HTTP Request - Method POST/PUT
[DEBUG] HTTP Request - Content Body: {"url":"data:text/html,<html></html>"}
[DEBUG] WebPage - updateLoadingProgress: 10
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/13e77164-eec6-bc54-2b5f0435-4b0f2bd4.dmp

initial form is not allowing the attachements of dmp type
# Configuration

Command line args for the phantom js :
 --webdriver=4444
 --ignore-ssl-errors=true
 --debug=true
 --web-security=false
 --webdriver-loglevel=DEBUG
 --webdriver-logfile=webdriver.log

 phantomjs is started by protractor.
# Additional information
- Each build is starting and using new instance of phantomjs. 
- This error is happening in random tests so it's not relevant to include them here. Also if builds are reusing the same instance
  of phantomjs - then test are running much longer without any troubles. (not tested for how long but about 50 builds were successful,
  and in case of new build - new instance case it starts to fail in about 7-10 builds).
- If one build is failing next can be successful, there is no dependency between builds.

**Comment by jpiv** [comment]
I'm having a very similar issue to this, any progress?
