### ISSUE TITLE
Canvas Scaling and Font Rendering Issue

### ISSUE THREAD

**Issue by jwball** [ariya/phantomjs#13028]
Hi there,

I've noticed that when using the canvas scale transformation and then drawing text, PhantomJS fails to draw some characters properly in certain fonts.

Notice the clipping on the "O" character in the below image.
![font-rendering-problem](https://cloud.githubusercontent.com/assets/8457270/6369924/da1f2f6a-bce2-11e4-8e46-f12bfc04f141.png)
It should look like this:
![correct](https://cloud.githubusercontent.com/assets/8457270/6369956/4019f9ee-bce3-11e4-9650-a42a6def03cb.png)

I've been able to reproduce this is both PhantomJS 1.9.7, 1.9.8 and 2.0.0.

I've not been able to reproduce the problem in a WebKit based browser (either Chrome or Safari)

Have tried both on Arch Linux and Ubuntu.

I've attached code to reproduce the issue. 

Please run as follows:

```
$ phantomjs --version
1.9.8                                                // also tried 2.0.0
$ phantomjs render.js 
$ display font-rendering-problem.png 
```

_render.js:_

```
var page = require('webpage').create();

page.open('http://localhost/page.html', function() {
    setTimeout(function() {
        page.render('font-rendering-problem.png');
        phantom.exit();
    }, 5000);
});
```

_page.html:_

```
<style>
@font-face {
    font-family: 'Abril Fatface';
    src: url(http://fonts.gstatic.com/s/abrilfatface/v8/X1g_KwGeBV3ajZIXQ9VnDibsRidxnYrfzLNRqJkHfFo.ttf) format('truetype');
}

* {
    font-family: 'Abril Fatface';
}
</style>

<canvas width="400" height="200" id="canvas"></canvas>

<script>
var canvas = document.getElementById('canvas');
var context = canvas.getContext('2d');

setInterval(function() {
    context.fillStyle = "black";
    context.fillRect(0,0,400,200);

    context.fillStyle = "white";
    context.font = "40pt 'Abril Fatface'";
    context.fillText("M N O P", 10, 50);

    context.save();
    context.scale(2, 2);
    context.fillText("M N O P", 10, 75);
    context.restore();
}, 250);
</script>
```

**Comment by knoopx** [comment]
I'm experiencing the same issue on 1.9.8 and 2.0.0 as well. I'm also rendering font faces over canvas. It depends on the font family but specially on round shapes. I have no idea what could be the origin of the problem. Any ideas?

![image](https://cloud.githubusercontent.com/assets/100993/7634978/99293c6c-fa5e-11e4-9f07-e67652285cb1.png)
![image](https://cloud.githubusercontent.com/assets/100993/7635015/b48dc6ee-fa5e-11e4-86a2-e815de155df8.png)

**Comment by jwball** [comment]
I did some additional digging after posting this issue and it turns out that it might be a Qt bug rather than PhantomJS (which is using the QtWebKit): https://bugreports.qt.io/browse/QTBUG-21937

Unfortunately it doesn't seem to have progressed since 2013

**Comment by knoopx** [comment]
Here are some relevant QT-related bugs:

https://bugreports.qt.io/browse/QTBUG-2704
https://bugreports.qt.io/browse/QTBUG-20319
https://bugreports.qt.io/browse/QTBUG-21937
https://bugreports.qt.io/browse/QTBUG-36633

**Comment by knoopx** [comment]
I also found that this problem does not happen under OSX. 

Here are some code paths that may be affecting the rendering:
https://github.com/ariya/phantomjs/blob/48fabe06463460d2fb7026d6df9783216e26265c/src/qt/qtbase/src/gui/text/qdistancefield.cpp
https://github.com/ariya/phantomjs/blob/48fabe06463460d2fb7026d6df9783216e26265c/src/qt/qtbase/src/platformsupport/fontdatabases/basic/qbasicfontdatabase.cpp
https://github.com/ariya/phantomjs/blob/48fabe06463460d2fb7026d6df9783216e26265c/src/qt/qtbase/src/gui/text/qfontengine_ft.cpp
