### ISSUE TITLE
Executing typeof code

### ISSUE THREAD

**Issue by reggi** [ariya/phantomjs#13037]
I'm running phantomjs on a page with polymer on it.

Polymer has the line:

```
var hasTemplateElement = typeof HTMLTemplateElement !== 'undefined';
```

I'm getting this error from phantom:

```
ReferenceError: Can't find variable: HTMLTemplateElement
```

It shouldn't be executing that line?

This is code running on the client why isn't phantomjs executing the script? Is there a way to ignore errors? `phatomjs ./index.js --ignore-client-errors`?

**Comment by JamesMGreene** [comment]
What version of PhantomJS are you running?

**Comment by reggi** [comment]
v2.0.0 from https://github.com/eugene1g/phantomjs found in this comment https://github.com/ariya/phantomjs/issues/12900#issuecomment-72364675

**Comment by JamesMGreene** [comment]
As for handling errors, see [`phantom.onError`](http://phantomjs.org/api/phantom/handler/on-error.html) and [`WebPage#onError`](http://phantomjs.org/api/webpage/handler/on-error.html).

**Comment by reggi** [comment]
Thanks!!!!

**Comment by JamesMGreene** [comment]
Reopening as this is still a super critical bug, if it is behaving as reported.

**Comment by ariya** [comment]
It seems that PhantomJS doesn't support HTMLTemplateElement. It still should not trigger the reference error. Not sure what's wrong in that Polymer code, if you try this one:

```js
var hasTemplateElement = typeof HTMLTemplateElement !== 'undefined';
console.log(hasTemplateElement);
phantom.exit();
```

It will print `false` (rightfully so), without a `ReferenceError`.
