### ISSUE TITLE
Phantomjs opening Tablet site and not desktop

### ISSUE THREAD

**Issue by amitsha** [ariya/phantomjs#13046]
Phantomjs driver launch code:
DesiredCapabilities phantomjscap = DesiredCapabilities.phantomjs();
        phantomjscap.setJavascriptEnabled(true);
        phantomjscap.setCapability(PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY,
                "D:/phantomjsDriver/phantomjs.exe");
        phantomjscap.setCapability(PhantomJSDriverService.PHANTOMJS_CLI_ARGS, new String[] {"--web-security=no",
                "--ignore-ssl-errors=yes"});
        phantomjscap.setCapability("phantomjs.page.settings.userAgent",
                "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:26.0) Gecko/20100101 Firefox/26.0");

driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), phantomjscap);
driver.manage().timeouts().pageLoadTimeout(100, TimeUnit.SECONDS);
        driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
        driver.manage().window().maximize();

driver.get("http://www.marksandspencer.com/");

This opens the tablet version of the website.I took a screenshot, on failure, that's how i know this for sure.

I've tried this on windows 7 machine, as well as mac osx. But it's opening tablet version.
Phantomjs driver used: 1.9.8

I have used phantomjs driver in the past, but haven't faced this issue.Please let me  know if i should be using a different user agent or is that an issue with this driver.

**Comment by johntitus** [comment]
Perhaps you need to set the viewport?
http://phantomjs.org/api/webpage/property/viewport-size.html

**Comment by amitsha** [comment]
John, i did try maximizing the window with webdriver.
Would you please share how can we set viewport-size for phantomjs with webdriver/java

**Comment by amitsha** [comment]
i have tried setting size using webdriver method driver.manage().window.setSize(new Dimension(2000,2000)) But, still the tablet view is getting opened.

**Comment by johntitus** [comment]
I'm not familiar with Java, sorry, but I can try and recreate in PhantomJS - but how do you know it's the tablet version, so I can tell?

**Comment by amitsha** [comment]
The header section of the site I’m using is different for tablet and desktop.Tablet version has Stores icon in header section, while desktop has Find Stores.

**Comment by johntitus** [comment]
Haven't figured it out, but here's a PhantomJS/non-Java version if anyone else wants to have a go:

```js
var page = require('webpage').create();
var url = 'http://www.marksandspencer.com/';
page.open(url, function (status) {
	page.settings.userAgent = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36';
	page.viewportSize = {
	  width: 1920,
	  height: 1200
	};
  	page.render('/tmp/out.png', { format : 'PNG' });
  	phantom.exit();
});
```

The output png has a "STORES" nav item, while pulling it up in Chrome shows a "FIND A STORE" dropdown.

**Comment by duncan73** [comment]
Hi,

`page.settings.userAgent` should be set before `page.open` is called.
