### ISSUE TITLE
PhantomJS Crash - Frame parent link

### ISSUE THREAD

**Issue by jefleponot** [ariya/phantomjs#13042]
Hello,

PhantomJs crashes when actions (click or submit) on a child frame try to modify its parents frames with a target attribute.

example : 

<pre style="background-color:#c8c8c8">
&lt;html&gt;
&lt;frameset border="0" rows="1,*"&gt;
  &lt;frame noresize="" scrolling="NO" name="haut" src="panier.htm"&gt;&lt;/frame&gt;
  &lt;frame name="bas" src="calc_c_p01.htm"&gt;
    &lt;html&gt;
      &lt;head&gt;&lt;/head&gt;
      &lt;frameset frameborder="NO" border="0" cols="150,*"&gt;
        &lt;frame name="gauche" src="calc_c_p01_marge.htm"&gt;&lt;/frame&gt;
        &lt;frame name="droite" src="calc_c_p01_data.htm"&gt;
          ...
          &lt;a id="go" target="<b>_parent</b>" href="calc_c_p01.htm"&gt;click here&lt;/a&gt;
          ...
        &lt;/frame&gt;
      &lt;/frameset&gt;
    &lt;/html&gt;
  &lt;/frame&gt;
&lt;/frameset&gt;
&lt;/html&gt;
</pre>

a <b>SIGSEGV</b> signal is sent.
phantomjs try to access inital frame memory area : so occurs access violation.

**Comment by jefleponot** [comment]
Here is code source example :

<code>
var page = require('webpage').create();
page.open('http://www.sample.com', function() {
  page.includeJs("http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js", function() {
    page.switchToFrame("bas");
    page.switchToFrame("droite");
    page.evaluate(function() { $("#go").click(); });
    // -> crash
    ...
    phantom.exit()
  });
});
</code>

a workaround example:
----------
<code>
var page = require('webpage').create();
page.open('http://www.sample.com', function() {
  page.includeJs("http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js", function() {
    page.switchToFrame("bas");
    page.switchToFrame("droite");
    page.evaluate(function() { $("#go").delay(200).click(); });
    page.switchToMainFrame();
    // -> no more crash
    ...
    phantom.exit()
  });
});
</code>

**Comment by Maraumax** [comment]
Thanks @jefleponot that worked for me with form submission.

Using casperjs :
```
this.evaluate(function() {
  setTimeout(function() { document.getElementById('form').submit(); }, 500);
});
this.page.switchToParentFrame();
```
