### ISSUE TITLE
PhantomJs 2.0.0 - is zoomFactor supposed to work with pdfs?

### ISSUE THREAD

**Issue by togakangaroo** [ariya/phantomjs#13048]
[According to the documentation](http://phantomjs.org/api/webpage/property/zoom-factor.html) the zoomFactor parameter is supposed to control zoom.

Previously this parameter was documented as working **only** with pdf rasterization but had strange effects that I couldn't quite pin down. In various issues I gathered that its behaviour was somewhat unspecified and possibly broken.

Now everything is different. The docs explicitly show a png example, and my experiments with pdf have no effect!

```
  > phantomjs.exe W.\rasterize.js http://google.com w:/temp/foo.png null 0.2
  > phantomjs.exe W.\rasterize.js http://google.com w:/temp/foo.png null 5
```

this works fine

```
  > phantomjs.exe W.\rasterize.js http://google.com w:/temp/foo.pdf null 0.2
  > phantomjs.exe W.\rasterize.js http://google.com w:/temp/foo.pdf null 5
```

this has no effect and outputs teh same thing as no zoomFactor

**Comment by kelvin22** [comment]
Similar findings...

with no zoomFactor set:
phantomJs 2.0 renders a more zoomed in pdf than phantomJs 1.9.8

When zoomFactor is set, I get mixed results, eg. zoomFactor = 0.25 does not result in a thumbnail, but a very very large version!

Note, I'm rendering Highcharts charts to pdf.

**Comment by thomasbachem** [comment]
Duplicate of #12685

**Comment by togakangaroo** [comment]
This issue is also about the docs being inconsistent
