### ISSUE TITLE
phantom 2.0.0 can't load npm coffee-script module

### ISSUE THREAD

**Issue by togakangaroo** [ariya/phantomjs#13047]
Maybe I'm not getting something.

I had scripts written in coffeescript before and I don't want to compile them all to js as that will add some awkward steps to our development process. So I thought I could just write a little shim script that will load a coffee-script module, then use that to run the existing scripts. Except I can't get phantom to load the coffee-script module in npm.

```
> npm install coffee-script
phantomjs> var coffee = require('coffee-script')
Error: Cannot find module 'vm'

  phantomjs://bootstrap.js:299 in require
  phantomjs://bootstrap.js:263 in require
  :9
  :373
undefined
```

Is this not the intended workflow?

**Comment by johntitus** [comment]
PhantomJS isn't Node - you can't require Node modules. There are various Node modules that let you run PhantomJS from Node:

Basic - https://github.com/sgentle/phantomjs-node
Higher level - https://github.com/johntitus/node-horseman

**Comment by togakangaroo** [comment]
I see, so how would you guys recommend making this transition?

**Comment by johntitus** [comment]
If you mean, which one of those two will let you transition while rewriting as little code as possible, you're probably best off with phantomjs-node. It's API is closer to PhantomJS.  

It's actually written in Coffee-script, though I'm not sure how much that will help you. It's code looks like this:

```js
phantom = require 'phantom'

phantom.create (ph) ->
  ph.createPage (page) ->
    page.open "http://www.google.com", (status) ->
      console.log "opened google? ", status
      page.evaluate (-> document.title), (result) ->
        console.log 'Page title is ' + result
        ph.exit()
```

Which you would then run as 'node filename' like a normal node script.

**Comment by togakangaroo** [comment]
Well yes, but that requires node in my production environment.

I understand the desire to not support coffeescript, but there's got to be a way for phantom to compile coffee files. It was doing it before afterall, and coffee-script runs just fine in most js environments.

**Comment by johntitus** [comment]
Ah sorry, misunderstood the question. I wasn't aware that PhantomJS supported/used to support Coffee Script.
