### ISSUE TITLE
problem when try to run phantom: Error: EACCES

### ISSUE THREAD

**Issue by Widrogo** [ariya/phantomjs#13057]
hello I have a problem when I try to run firt the install was fine:
![selection_505](https://cloud.githubusercontent.com/assets/3698485/6537809/dc063bd4-c430-11e4-86c3-a8dd9a80e7a3.png)

but when I try to use:
![selection_506](https://cloud.githubusercontent.com/assets/3698485/6537821/ee47b160-c430-11e4-9c42-67f6463c5153.png)

node -v v0.10.33
npm -v 1.4.28
ubuntu 14.10: Linux Widrogo 3.16.0-31-generic -Ubuntu  x86_64 x86_64 x86_64 GNU/Linux

![selection_507](https://cloud.githubusercontent.com/assets/3698485/6537909/c717022a-c431-11e4-9ede-6601f1a55f02.png)

**Comment by skibz** [comment]
you called `sudo  node installjs` instead of `sudo node install.js`
