### ISSUE TITLE
Error installing phantomjs@1.9.16

### ISSUE THREAD

**Issue by CustomsAdministrationSystem** [ariya/phantomjs#13053]
I always get this error on a npm install.

phantomjs@1.9.16 install H:\gitCAS\CAS\node_modules\karma-phantomjs-launcher\node_modules\phantomjs
node install.js

Looks like an `npm install -g` on windows; unable to check for already installed version.
Download already available at C:\Users\Sujith\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Extracting zip contents
Removing H:\gitCAS\CAS\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\Sujith\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1425572106422\phantomjs-1.9.8-windows -> H:\gitCAS\CAS\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom
Phantom installation failed { [Error: EEXIST, mkdir 'H:\gitCAS\CAS\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom']
  errno: 47,
  code: 'EEXIST',
  path: 'H:\\gitCAS\\CAS\\node_modules\\karma-phantomjs-launcher\\node_modules\\phantomjs\\lib\\phantom' } Error: EEXIST, mkdir 'H:\gitCAS\CAS\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom'
/

ws@0.4.32 install H:\gitCAS\CAS\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
(node-gyp rebuild 2> builderror.log) || (exit 0)

H:\gitCAS\CAS\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--cache" ".npm_cache"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     H:\gitCAS\CAS\npm-debug.log

**Comment by JamesMGreene** [comment]
We don't manage the NPM installer for PhantomJS, please file it with https://github.com/Medium/phantomjs/

Thanks!
