### ISSUE TITLE
segfault on ubuntu with stacktrace

### ISSUE THREAD

**Issue by lukeasrodgers** [ariya/phantomjs#13066]
We are encountering occasional segfaults. Unclear what the conditions are. 

Here is a stacktrace: https://gist.github.com/lukeasrodgers/49e40bf6c2b2c4289eb3

```
Operating system: Linux
                  0.0.0 Linux 3.2.0-27-virtual #43-Ubuntu SMP Fri Jul 6 14:45:58 UTC 2012 x86_64
CPU: amd64
     family 6 model 62 stepping 4
     2 CPUs

Crash reason:  SIGSEGV
Crash address: 0x18
...
```

**Comment by BernardoGO** [comment]
It is happening to me after the kernel update on ubuntu

**Comment by Sharpe23** [comment]
@lukeasrodgers @BernardoGO 
have you solved it?

**Comment by lukeasrodgers** [comment]
@Sharpe23 no we haven't.
