### ISSUE TITLE
centos6.6(final) compile and run  crash 

### ISSUE THREAD

**Issue by myc547** [ariya/phantomjs#13068]
Microsoft (R) Windows Debugger Version 6.11.0001.404 X86
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\Users\Administrator\Desktop\41b90c08-17ee-927e-4a98041f-6286734a.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available

64-bit machine not using 64-bit API
Symbol search path is: *** Invalid ***
****************************************************************************
* Symbol loading may be unreliable without a symbol search path.           *
* Use .symfix to have the debugger choose a symbol path.                   *
* After setting your symbol path, use .reload to refresh symbol locations. *
****************************************************************************
Executable search path is: 
Unknown System Version 0 (Linux 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64) UP Free x64
Machine Name:
Debug session time: Wed Mar 11 15:21:40.000 2015 (GMT+8)
System Uptime: not available
Process Uptime: not available
................................
The call to LoadLibrary(ext) failed, Win32 error 0n2
    "系统找不到指定的文件。"
Please check your debugger configuration and/or network access.
The call to LoadLibrary(uext) failed, Win32 error 0n2
    "系统找不到指定的文件。"
Please check your debugger configuration and/or network access.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(f0f0f0f0.368a): Unknown exception - code 00000006 (first/second chance not available)
Unable to load image /lib64/libc-2.12.so, Win32 error 0n2
*** WARNING: Unable to verify timestamp for libc-2.12.so
*** ERROR: Module load completed but symbols could not be loaded for libc-2.12.so
libc_2_12+0x32625:
00000034`8e032625 483d00f0ffff    cmp     rax,0FFFFFFFFFFFFF000h

**Comment by Vitallium** [comment]
Thank you for submitting! Please read this http://phantomjs.org/crash-reporting.html about reporting crashes.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://homemadefacialmasks.info/fit.php?0hs6>

 

klaus@hebsgaard.dk
