### ISSUE TITLE
Text rendering is way off when a text block has text-align: right and letter-spacing: 8px inside a fixed width block.

### ISSUE THREAD

**Issue by atteeela** [ariya/phantomjs#13060]
Text rendering flows out of the parent div when a text block has both text-align:right (or text-align:center) and letter-spacing: 8px. (or non-zero / non-'normal' for that matter)

See Chrome 41's in-browser rendering

![josefinsansletterspacing_8px_righttextalign_mac10 9_chrome41](https://cloud.githubusercontent.com/assets/911814/6546802/5b636d44-c598-11e4-84ec-c16a32b6ce58.png)

Phantom JS 2.0 process rendering:

![josefinsansletterspacing_8px_righttextalign_mac10 9_pjs2 0_server](https://cloud.githubusercontent.com/assets/911814/6546803/5b670864-c598-11e4-8676-77f3edbde96f.png)

It looks like the letter-spacing is added to the beginning of a text line...even though the whole thing is right aligned and letter spacing to the left of the left-most character on each line is not 'needed'. Then the whole thing is shifted outside of the bounding div.  Perhaps related: https://github.com/ariya/phantomjs/issues/13006

Any help or direction on how I could patch Phantom JS or QT Font rendering would be greatly appreciated.   If you have any experience in this area, please send me a message or reply -- I'm capable with C++, just need to get a better handle on the mammoth code base that is Phantom JS + QT + WebKit.

Thanks,

---

Block HTML source:

<div id="0514f638-b89d-46fa-871f-89bc337646a8" style="text-shadow: rgba(0, 0, 0, 0.2) 1px 1px 2px; display: inline-block; padding: 0px; line-height: 1.257; text-transform: none; -webkit-line-break: after-white-space; border: 1px solid red; box-sizing: content-box; position: absolute; word-wrap: break-word; word-break: break-word; white-space: normal; color: rgb(255, 255, 255); min-width: 20px; text-rendering: geometricprecision; text-align: left; font-family: 'Josefin Sans'; font-weight: normal; font-size: 42px; font-kerning: auto; font-stretch: normal; font-variant: normal; font-variant-ligatures: normal; -webkit-user-select: none; transform: translate3d(57.1129220023283px, 201.265424912689px, 0px); -webkit-transform: translate3d(57.1129220023283px, 201.265424912689px, 0px); z-index: 100; overflow: visible; width: 917.363636493683px; letter-spacing: 8px; background-color: transparent;"><div class="itext-inner" spellcheck="false" style="outline: none; text-align: right; word-break: break-word; word-wrap: break-word; white-space: pre-wrap; box-sizing: content-box; display: block; left: -1px; top: -1px;">The quick brown fox jumped over the lazy dog. The quick brown fox jumped over the lazy cat .</div></div>

**Comment by FranciscoG** [comment]
I'm getting a similar issue where using `text-align: right ` does not expand to the left when on a new line

example
say I have a break inside a `<p>` that has a fixed width and has text-align right:
```
<p style="text-align:right; width: 500px;"> 
    I am a long string with things to say about the day <br>
    and stuff and whatever I guess I could lorem this but who cares
</p>
```
should produce that looks like this:
```
            I am a long string with things to say about the day
and stuff and whatever I guess I could lorem this but who cares
```
but instead it produces this:
```
I am a long string with things to say about the day
 and stuff and whatever I guess I could lorem this 
                                     but who cares
```

And in my case there definitely is enough space on the left for the sting to fit.  And I've tested it in every major browser on both Mac and PC and it's doing what it's supposed to.  It's just in PhantomJs (2.0.0 OSX) that it  is not working.

**Comment by shibinpjoseph** [comment]
Same here when i try with Arabic language. if anyone know a fix please let me know.

**Comment by israelidanny** [comment]
This issue is totally messing up my use cases of phantomjs as well, has anybody found a solution?
