### ISSUE TITLE
How use core node module?

### ISSUE THREAD

**Issue by alexpts** [ariya/phantomjs#13076]
`````node_modules/.bin/phantomjs test.js`````

`````var util = require('util');`````

Error: Cannot find module 'util'

How I can use core module?

**Comment by masi** [comment]
PhantomJS is NOT a node application. It only happens to use the same albeit older version of the JavaScript engine V8. Look at the documentation to see which of the few modules ship with PhantomJS that are built to work like the ones of Node.
