### ISSUE TITLE
examples/phantomwebintro.js not working

### ISSUE THREAD

**Issue by whyka** [ariya/phantomjs#13074]
I tried with both phantomjs `2.0.0` and `1.9.8`, `examples/phantomwebintro.js` just hang and log nothing.
Does includeJs have problem?
Thank you.

**Comment by Vitallium** [comment]
No, it doesn't. Seems like `http://www.phantomjs.org` just doesn't work.

**Comment by kiwiheretic** [comment]
Any update on this issue?

**Comment by jmiller76** [comment]
Sorry I missed the dupe, saw this on #13196 and submitted PR #13196 
Taking out the www. fixes things for now.

**Comment by Vitallium** [comment]
Fixed in 276aa35
