### ISSUE TITLE
Qt issue when running phantomjs on OSX 10.10

### ISSUE THREAD

**Issue by neilireson** [ariya/phantomjs#13070]
My initial attempt to run on 10.10 failed but was fixed using the bespoke build for Yosemite at https://github.com/eugene1g/phantomjs/releases. However I eventually hit another issue with the exception:

Assertion failed: (_consumed <= scratch_size), function _hb_coretext_shape, file src/hb-coretext.cc, line 764.

This seems to be a known 10.10 issue which has been fixed in qt (see https://bugreports.qt.io/browse/QTBUG-39504). Therefore builds for OSX 10.10 have to use qt>=5.3.1.

**Comment by koalalorenzo** [comment]
Same problem here, I also have the problem with _consumed <= scratch_size.

**Comment by koalalorenzo** [comment]
Any connection to https://github.com/ariya/phantomjs/issues/12918 ?

**Comment by Vitallium** [comment]
This issue will be fixed with the next Qt upgrade to 5.4.1

**Comment by Vitallium** [comment]
Duplicate of #12918.
