### ISSUE TITLE
PhantomJS crash while running Jasmine

### ISSUE THREAD

**Issue by ahuth** [ariya/phantomjs#13082]
Hi, just ran into this crash while running some Jasmine tests:

```bash
phantomjs(79423,0xa178d1a8) malloc: *** mach_vm_map(size=282509312) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/51444E5E-BBDF-41BB-8973-72EA1CA37A4C.dmp
```

Was running about 3000 or so tests, most of which completed before the crash.

Also, I have a a `dmp` file, but it won't let me attach it to here. Should I paste the contents into here? It's 7000 lines of what looks like hex.

**Comment by buenjybar** [comment]
any idea how you fixed it ?

**Comment by ahuth** [comment]
Sorry, I never fixed it. Just moved on from PhantomJS.

Maybe recent versions are more stable?
