### ISSUE TITLE
Build Fails on Suse sle11

### ISSUE THREAD

**Issue by aliminnet** [ariya/phantomjs#13092]
ICU auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o icu.o icu.cpp
g++ -Wl,-O1 -o icu icu.o   -licui18n -licuuc
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /usr/lib/libicui18n.so when searching for -licui18n
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: cannot find -licui18n
collect2: ld returned 1 exit status
gmake: **\* [icu] Error 1
ICU disabled.
The ICU library support cannot be enabled.
 Turn on verbose messaging (-v) to /home/sshusr/phantomjs/pj/phantomjs/src/qt/qtbase/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /home/sshusr/phantomjs/pj/phantomjs/src/qt/qtbase/configure to continue.

Building Qt...

make: **\* No targets specified and no makefile found.  Stop.

Building QtWebkit...

grep: src/qt/qtbase/config.status: No such file or directory
Project ERROR: Cannot load qmodule.pri!
Error processing project file: /home/sshusr/phantomjs/pj/phantomjs/src/qt/qtwebkit/WebKit.pro

Building main PhantomJS application...

cd src/ && ( test -e Makefile.phantomjs || /home/sshusr/phantomjs/pj/phantomjs/src/qt/qtbase/bin/qmake /home/sshusr/phantomjs/pj/phantomjs/src/phantomjs.pro -o Makefile.phantomjs ) && make -f Makefile.phantomjs
Project ERROR: This program can only be compiled with Qt 5.3.x.
make: **\* [sub-src-phantomjs-pro-make_first-ordered] Error 3

I have already installed libicu but I think there is an incompatible problem. Which version should be libicu?

**Comment by Vitallium** [comment]
You need to install the `dev` package for libicu 4.8 version.

**Comment by aliminnet** [comment]
Now it is like this:

.....
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -mavx -g -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o avx.o avx.cpp
cc1plus: error: unrecognized command line option "-mavx"
gmake: *** [avx.o] Error 1
avx disabled.
POSIX iconv auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o iconv.o iconv.cpp
g++ -Wl,-O1 -o iconv iconv.o
POSIX iconv enabled.
ICU auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o icu.o icu.cpp
g++ -Wl,-O1 -o icu icu.o   -licui18n -licuuc
ICU enabled.
FontConfig auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -isystem /usr/include/freetype2 -o fontconfig.o fontconfig.cpp
g++ -Wl,-O1 -o fontconfig fontconfig.o   -lfreetype -lfontconfig
FontConfig enabled.
XLib auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o xlib.o xlib.cpp
xlib.cpp:42:22: error: X11/Xlib.h: No such file or directory
xlib.cpp: In function ‘int main(int, char**)’:
xlib.cpp:46: error: ‘Display’ was not declared in this scope
xlib.cpp:46: error: ‘d’ was not declared in this scope
xlib.cpp:46: error: ‘NULL’ was not declared in this scope
xlib.cpp:46: error: ‘XOpenDisplay’ was not declared in this scope
xlib.cpp:47: error: ‘XCloseDisplay’ was not declared in this scope
gmake: *** [xlib.o] Error 1
XLib disabled.
.....
.....
.....
.....

../../corelib/kernel/qvariant.cpp:129:   instantiated from here
../../../include/QtCore/5.3.0/QtCore/private/../../../../../src/corelib/kernel/qvariant_p.h:225: error: ‘const struct QHash<QString, QVariant>’ has no member named ‘isNull’
make[2]: *** [.obj/qvariant.o] Error 1
make[2]: Leaving directory `/home/sshusr/phantomjs/pj/phantomjs/src/qt/qtbase/src/tools/bootstrap'
make[1]: *** [sub-bootstrap-make_first] Error 2
make[1]: Leaving directory `/home/sshusr/phantomjs/pj/phantomjs/src/qt/qtbase/src'
make: *** [sub-src-make_first] Error 2

Building QtWebkit...

cd Source/WTF/ && ( test -e Makefile.WTF || /home/sshusr/phantomjs/pj/phantomjs/src/qt/qtbase/bin/qmake /home/sshusr/phantomjs/pj/phantomjs/src/qt/qtwebkit/Source/WTF/WTF.pro WEBKIT_CONFIG\ -=\ \ use_glib\ use_gstreamer\ use_gstreamer010\ use_native_fullscreen_video\ legacy_web_audio\ web_audio\ video\ gamepad -o Makefile.WTF ) && make -f Makefile.WTF
Project ERROR: Unknown module(s) in QT: core
make: *** [sub-Source-WTF-WTF-pro-make_first-ordered] Error 3

Building main PhantomJS application...

cd src/ && ( test -e Makefile.phantomjs || /home/sshusr/phantomjs/pj/phantomjs/src/qt/qtbase/bin/qmake /home/sshusr/phantomjs/pj/phantomjs/src/phantomjs.pro -o Makefile.phantomjs ) && make -f Makefile.phantomjs
Project ERROR: Unknown module(s) in QT: webkitwidgets network gui core
make: *** [sub-src-phantomjs-pro-make_first-ordered] Error 3


Now the errors are shown above.

**Comment by ariya** [comment]
Do you have the proper xlib? Did you install some required libs (see http://phantomjs.org/build.html for some examples)? Also, try to start from a clean build, run `git clean -xfd .` before retrying it again.

**Comment by ward-appirio** [comment]
Running into exact same issues as above.  Anyone had any luck with resolution here?
