### ISSUE TITLE
Trouble building portable Linux build of PhantomJS 2.0.0

### ISSUE THREAD

**Issue by wrschneider99** [ariya/phantomjs#13097]
Built from source on a CentOS 7.0 box and the resulting binary breaks on a RHEL 5.9 box with error

 libicudata.so.50: cannot open shared object file: No such file or directory

Is there any way to build the resulting binary in way that is compatible across machines?

**Comment by Vitallium** [comment]
This is a known issue. We're working on a fix. See here #12948
