### ISSUE TITLE
Performance Timing Interface Returning unexpected values

### ISSUE THREAD

**Issue by benhastings** [ariya/phantomjs#13093]
My elation at the advent of the W3C performance timing interface being included in phantomJS was short-lived.  I fired up a simple test to evaluate some timings and was greeted with partial failure.

What I see is all of the timing events up to responseStart being equal to the navigationStart (with the exception of redirect & SSL, I didn't take time to find a page with those events).

It seems like the actual request is being initiated before the timing object is created (that is _purely_ speculation).

I'm attaching a simple script to illustrate the offending behavior.  The test URL was chosen as a control on the other side of the world (I'm in Ohio) that would ensure network latency.

I'm including both the output I get from my phantomJS script and the console in Chrome when I visit the same site.

Chrome Output

```
TTFB:1793 startRender:3278
VM179:18 0      secureConnectionStart
VM179:18 0      unloadEventStart
VM179:18 0      unloadEventEnd
VM179:18 0      redirectStart
VM179:18 0      redirectEnd
VM179:18 1426776452218      navigationStart
VM179:18 1426776452618      fetchStart
VM179:18 1426776452622      domainLookupStart
VM179:18 1426776452624      domainLookupEnd
VM179:18 1426776452624      connectStart
VM179:18 1426776452625      requestStart
VM179:18 1426776452625      connectEnd
VM179:18 1426776454011      responseStart
VM179:18 1426776454013      responseEnd
VM179:18 1426776454013      domLoading
VM179:18 1426776455408      domInteractive
VM179:18 1426776455408      domContentLoadedEventStart
VM179:18 1426776455496      domContentLoadedEventEnd
VM179:18 1426776457505      domComplete
VM179:18 1426776457509      loadEventStart
VM179:18 1426776457509      loadEventEnd
```

PhantomJS Output

```
Status: success
1426776521252
TTFB:0 startRender:174
0       redirectEnd
0       redirectStart
0       secureConnectionStart
0       unloadEventEnd
0       unloadEventStart
1426776521253       connectEnd
1426776521253       connectStart
1426776521253       domainLookupEnd
1426776521253       domainLookupStart
1426776521253       fetchStart
1426776521253       navigationStart
1426776521253       requestStart
1426776521253       responseStart
1426776521404       domLoading
1426776521426       responseEnd
1426776521427       domContentLoadedEventEnd
1426776521427       domContentLoadedEventStart
1426776521427       domInteractive
1426776521637       domComplete
1426776521637       loadEventStart
1426776521638       loadEventEnd
```

Script to recreate: wptDefect.js

``` javascript

var testURL='http://www.vilnius-tourism.lt/en/tourism';

var page = require('webpage').create();
var st = Date.now();
page.open(testURL, function(status) {
  console.log("Status: " + status);
  if(status === "success") {
    console.log(st);
    setTimeout(function(){
      // To unequivocally ensure that the page has finished.
      page.render('example.png');
      getMetrics(page);
      phantom.exit();
    },2000);
  }
});

function getMetrics(page) {
    var wpt=page.evaluate(function(){
        return window.performance.timing;
    });

    var ns=wpt.navigationStart;
    var ttfb=wpt.responseStart-ns;
    var sr=wpt.domContentLoadedEventEnd-ns;
    console.log('TTFB:'+ttfb+' startRender:'+sr);

      var metrics=[];

      for(var i=0;i<Object.keys(wpt).length;i++){
        val={};
        val.key=Object.keys(wpt)[i];
        val.value=wpt[val.key];
        metrics.push(val);
      }

  metrics.sort(function(a,b){
    return a.value-b.value;
  });
  metrics.forEach(function(d){console.log(d.value+'\t\t'+d.key);});
}

```

**Comment by b2rtc** [comment]
I had the similar issues...

**Comment by benhastings** [comment]
We've now tried on a number of instance types and platforms - all with consistent results.
OSX, Ubuntu, Windows both from our local machines, servers in our datacenter, and cloud.

Universally, it appears navigationStart is being set in an unusual way.  I've again tried to look at the code, but have been unsuccessful parsing the content - my areas of familiarity/expertise are python & JS.

**Comment by JanHans1** [comment]
Hello.
For what it is worth, this is my test of your script executed from Copenhagen, Denmark (closer to Vilnius than Ohio :-))

Actually it looks like Chrome and PJS is reasonably equal. Very strange/interesting

PhantomJs 2.0.0.0 on Windows 7 prof + SP1 over 8/1 Mbit ADSL line
(no caching which is default)
-----------------------------------------------------
Status: success
1431678557170
TTFB:1036 startRender:2104
0               secureConnectionStart
0               unloadEventEnd
0               unloadEventStart
1431678557172           navigationStart
1431678557172           redirectStart
1431678558208           connectEnd
1431678558208           connectStart
1431678558208           domainLookupEnd
1431678558208           domainLookupStart
1431678558208           fetchStart
1431678558208           redirectEnd
1431678558208           requestStart
1431678558208           responseStart
1431678558386           domLoading
1431678558412           responseEnd
1431678559227           domContentLoadedEventStart
1431678559227           domInteractive
1431678559276           domContentLoadedEventEnd
1431678567352           domComplete
1431678567353           loadEventStart
1431678567355           loadEventEnd

Chrome 42.0.2311.135 m
(caching disabled in F12, network)
-----------------------------------------------------
TTFB:1112 startRender:1931
0		secureConnectionStart
0		unloadEventStart
0		unloadEventEnd
1431679552269		navigationStart
1431679552503		redirectStart
1431679553214		connectStart
1431679553214		fetchStart
1431679553214		domainLookupStart
1431679553214		domainLookupEnd
1431679553214		connectEnd
1431679553214		redirectEnd
1431679553218		requestStart
1431679553381		responseStart
1431679553387		domLoading
1431679553387		responseEnd
1431679554151		domContentLoadedEventStart
1431679554151		domInteractive
1431679554200		domContentLoadedEventEnd
1431679564194		loadEventStart
1431679564194		domComplete
1431679564197		loadEventEnd

I hope this can help in investigating this issue.
/Jan

**Comment by JanHans1** [comment]
Now I got curious.
I did a "resverse" test from Copenhagen towards `http://consumer.discoverohio.com/` and this shows:
Chrome:  `ttfb: 151, startRender: 2417`
PJS:  `ttfb: 0, startRender: 2082`
More or less the same picture as Bens experience from Ohio->Vilnius. (all timings up to responseStart are identical)
/Jan

**Comment by benhastings** [comment]
I just tried a fresh AWS image - us-west Oregon,  ubuntu 14.04, m3.2xl, followed the build instructions and tried running (looks like the current version is 2.0.1-development).

On my first hit, I got a non-zero TTFB - it was 2855.  Second try was 1020.
However, when I tried hitting the suggested "http:/consumer.discoverohio.com" it was zero TTFB.  When I try hitting something popular like http://baidu.com, i get the same results as above.

It's possible that there is some caching external to the instance that's taking place, but I would still expect some of the other intermediate metrics to be non-zero.

**Comment by fromIRIS** [comment]
@benhastings  @JanHans1 hello!
is it type `phantomjs wptDefect.js` in shell? 
I got a  wrong message .
```
➜  test git:(master) ✗ phantomjs wptDefect.js
Status: success
1450339307193
TypeError: 'undefined' is not an object (evaluating 'window.performance.timing')

  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():3
  phantomjs://webpage.evaluate():3
TypeError: 'null' is not an object (evaluating 'wpt.navigationStart')

  wptDefect.js:23 in getMetrics
  wptDefect.js:12
```

**Comment by fromIRIS** [comment]
@benhastings  @JanHans1 hello!
is it type `phantomjs wptDefect.js` in shell? 
I got a  wrong message .
```
➜  test git:(master) ✗ phantomjs wptDefect.js
Status: success
1450339307193
TypeError: 'undefined' is not an object (evaluating 'window.performance.timing')

  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():3
  phantomjs://webpage.evaluate():3
TypeError: 'null' is not an object (evaluating 'wpt.navigationStart')

  wptDefect.js:23 in getMetrics
  wptDefect.js:12
```

**Comment by benhastings** [comment]
Yes @fromIRIS - the defect was evident when running from a shell.

I was just given a windows machine a few weeks ago and it seems to be working (as mentioned above).  I'm trying to fire up another ubuntu image and run it there.  My hope was to use remote hosts for periodic performance monitoring.

**Comment by fromIRIS** [comment]
thanks! you mean you can run this method in windows machine? i will try it.  but in my mac os,i tried to run `phantomjs wptDefect.js` in shell. BUT i can not  get window.performance.timing when run page.evaluate. as you can see above `TypeError: 'undefined' is not an object (evaluating 'window.performance.timing')`  do you know why? @benhastings

**Comment by DreamHackchosenone** [comment]
now，I had the similar issues，i tried to test a web dns lookuptime,and i use chrome and phantomjs test it
why chrome domainlookupEnd-domainlookupStart not equal phantomjs ？
AND phantomjs domainlookupEnd-domainlookupStart always get 0

like your ex:
chrome:
VM179:18 1426776452622      domainLookupStart
VM179:18 1426776452624      domainLookupEnd
phantomjs:
1426776521253       domainLookupEnd
1426776521253       domainLookupStart
can you give any suggestion?
THX

**Comment by bor8** [comment]
With PhantomJS I usually have a TTFB of 0 milliseconds. Which is probably not true. With Google Chrome and chromedriver 2.38 I get more realistic values.
