### ISSUE TITLE
Use Vanilla Phantom or Driver + Phantom?

### ISSUE THREAD

**Issue by dschinkel** [ariya/phantomjs#13100]
I am trying to use https://www.npmjs.com/package/phantom.

I'm wondering since PhantomJS offers a page object already, do I really need to use something like webdriver.io (which can talk to PhantomJS) or can I just use PhantomJS for most all that selenium or something like Zombie would do?

I tried to use PhantomJS but fell into issues whereas my Cucumber.js tests lost scope.  For example consider this code where I tried to for the first time get Cucumber.js step definitions to use the PhantomJS page object:

var phantom = require('phantom'), _ph, _page;

phantom.create("--web-security=no", "--ignore-ssl-errors=yes", { port: 12345 }, function (ph) {

    console.log("Phantom Bridge Initiated");

    _ph = ph;

    _ph.createPage(function(page) {
        console.log("Page created!");
        _page = page;
        console.log("_page: " + _page);

        _page.onLoadFinished = function(status) {
            console.log("Page Loaded: " + status);
        };
        //_ph.exit();
    });
});

module.exports = function() {
    "use strict";

    this.Given(/^I visit the episodes display page$/, function (callback) {

        console.log("got here, _page: " + _page);

        _page.open("/", function(status){
            status.should.equal("success");
        });

        _ph.exit();
        callback();
    });

    this.Then(/^I should not see any customers listed$/, function (callback) {
        // not implemented
        callback.pending();
    });

    this.Given(/^there are some customers to view$/, function (callback) {
        // not implemented
        callback.pending();
    });

    this.When(/^I go to the customers display page$/, function (callback) {
        // not implemented
        callback.pending();
    });

    this.Then(/^I should see a list of customers grouped by Topic$/, function (callback) {
        // not implemented
        callback.pending();
    });

};

problem is I lose the _page instance after the createPage function is done...so when it gets to console.log("got here, _page: " + _page); _page is undefined.  Not sure if I'm going about this right or not.

**Comment by JamesMGreene** [comment]
Sounds like something specific to the Node wrapper module you are using.  Please file an issue with https://github.com/sgentle/phantomjs-node instead.

As for your more general question of using vanilla PhantomJS vs. WebDriver, we encourage questions to be taken to our [mailing list (Google Groups forum)](https://groups.google.com/forum/#!forum/phantomjs) rather than on the issue tracker.

**Comment by dschinkel** [comment]
So you can't use PhantomJS with Node as it is?  You have to use a wrapper like Phantom-Node?
