### ISSUE TITLE
Arg '--cookies-file' broken on 2.0

### ISSUE THREAD

**Issue by juanchristian** [ariya/phantomjs#13115]
I was trying this simple code using 2.0:

```
from selenium.webdriver.phantomjs import webdriver

driver = webdriver.WebDriver(service_args=['--cookies-file=cookies.txt'])
driver.get('http://google.com')
driver.quit()
```

The 'cookies.txt' file wasn't being created, tried many times, no lucky. Downgraded to 1.9.8 and bang, working 100%

**Comment by yali25** [comment]
Hi,

I encountered the same issue. By changing one line in the "phantom.cpp" file I got it working, but I'm not sure if this is the correct way to do it (or if it will break existing code).

Change the the line in the Phantom::createCookieJar method from:  
**return new CookieJar(filePath, this);**

to 

**return new CookieJar(m_config.cookiesFile() != "" ? m_config.cookiesFile() : filePath,this);**

**Comment by Vitallium** [comment]
Are you sure? Because I don't see that line in `phantom.cpp`.

**Comment by yali25** [comment]
I mean in this method:

https://github.com/ariya/phantomjs/blob/master/src/phantom.cpp#L297

**Comment by jcchristian** [comment]
Yes, maybe manually modifying the source can fix the issue. But people behind PhantomJS need to fix that!

**Comment by spedy** [comment]
can this be a possible workaround http://stackoverflow.com/questions/34797962/phantomjs-custom-persistent-cookie-handling ?

**Comment by pengqi** [comment]
I met the same problem. 1.9.8 does working!

**Comment by chunfengd** [comment]
I have the same problem.

**Comment by maZahaca** [comment]
+1, Does anybody can fix it?

**Comment by Vitallium** [comment]
Perhaps there is a problem with Ghostdriver. Because the plain PhantomJS script works.

**Comment by Yossi** [comment]
This is at line 310 now.

**Comment by jantman** [comment]
I'm running into some serious issues because of this, and I would've expected functionality like this to be much more visible, and problematic for a lot of users. Is there perhaps some workaround I'm not aware of?

**Comment by Yossi** [comment]
The "workaround" is to compile it yourself after fixing the code the way @yali25 suggests. 

Here's a wiki page with step by step instructions https://github.com/Yossi/agent-stats-utils/wiki/How-to-compile-phantomjs-for-yourself

**Comment by jantman** [comment]
That "workaround" may be suitable for things that only use phantomjs locally, but it's certainly not for the acceptance tests of my open source project, which have to run on TravisCI as well as on the local machine of anyone who wants to develop the project.

For anyone else who has similar needs, I *have* come up with a workaround the solves the problem if your environment requires phantomjs, but has no control over the version or compilation. I'm using Selenium WebDriver in my tests, to wrap phantomjs. I've written some wrapper methods that are called to get a Browser instance and to request pages; after a page is requested (before teardown), I use WebDriver's ``get_cookies()`` method to retrieve a list/array of cookies and then serialize that to disk as JSON. When a new Browser is constructed and a page is first loaded, I deserialize the JSON and use ``add_cookie()`` to inject the cookies back into phantomjs. As far as I can tell, this works with any phantomjs version (and in theory should work with any other WebDriver-supported browser as well).
