### ISSUE TITLE
console.error() in page JavaScript crashes PhantomJS 2.0

### ISSUE THREAD

**Issue by masi** [ariya/phantomjs#13112]
When the loaded JS in the web page has a call to console.error() then PhantomJS stops.

console.log() works fine. I didn't test the other console methods.

**Comment by japgolly** [comment]
This seems like such a quick and easy issue to fix. Is there any chance we could get a 2.0.1 with this fixed sometime soon?

**Comment by zackw** [comment]
@japgolly We don't even have a release schedule right now :frowning: I can tell you that all the core developers' time is completely tied up with other stuff, like "clean out the bug tracker" :wink:  If you have time to fix it yourself and make a pull request, I think we could get it merged quickly, though.

**Comment by sjrd** [comment]
I see that this bug report has been downgraded to "old.Regression". What does this mean? This is a serious issue for Scala.js users (see https://github.com/scala-js/scala-js/issues/1555).

**Comment by zackw** [comment]
@sjrd The re-tagging is strictly to do with a reorganization of our bug tracker -- "old" means "old tag scheme."  I've updated this bug to the new tag scheme now.

Anyhow, I can't reproduce the problem myself, so it must be something more complicated than just "When the loaded JS in the web page has a call to console.error() then PhantomJS stops."  If you can make the bug happen reliably, could we possibly pester you for a reduced test case?  Ideally a single `.js` file that demonstrates the problem when run as `phantomjs test.js`.  You can use the `WebServer` module to serve a simple webpage that uses `console.error`.

**Comment by masi** [comment]
Just for the record, when I use console.error("foobar"); in the main script context the result (Win7, 64bit) is:

```
foobar

  :0 in error
```

PhatomJS doesn't crash in this case but there is an extra output.

**Comment by lifeiscontent** [comment]
@zackw any updates on this? I'm now getting this in the react_on_rails test dummy spec

**Comment by zackw** [comment]
@lifeiscontent As I said last year, we cannot reproduce this problem ourselves, and we need a reduced, self-contained test case.  The react_on_rails gem test dummy app is still much too big.  We have written some [draft bug reporting guidelines](http://discuss.phantomjs.org/t/draft-troubleshooting-and-reporting-bugs-in-phantomjs/22) which may help you understand what we need - if they are unclear please comment on that over there.
