### ISSUE TITLE
phantomjs -v is ridiculously slow

### ISSUE THREAD

**Issue by thomassnielsen** [ariya/phantomjs#13117]
We're making a utility that needs to check the versions of its underlying tools, one of which is PhantomJS. Compared to most of the other ones, PhantomJS is really, really slow to report its version number. This blocks some UI in our app (about-window comes to mind).

**Comment by JamesMGreene** [comment]
OS? Phantom version?

**Comment by thomassnielsen** [comment]
```
~ ❯ system_profiler SPSoftwareDataType
Software:
  System Software Overview:
    System Version: OS X 10.10.2 (14C1514)
    Kernel Version: Darwin 14.1.0
~ ❯ time phantomjs -v
1.9.8
phantomjs -v  0.77s user 0.32s system 61% cpu 1.756 total
```

**Comment by ariya** [comment]
By "ridiculously slow", do you mean < 1 sec or longer than that?
Note that the executable is compressed using UPX and hence it takes sometime to decompress it. To skip, just decompress the executable manually.

**Comment by thomassnielsen** [comment]
It's taking 1.2 - 1.8 seconds on my rMBP. Compared to for example node, taking 0.006s. 

It seems pretty unnecessary for any CLI tool to take more than a few milliseconds to report its version number. I'd guess that in phantoms case it's because it spins up a full js environment etc, but it's still very slow. Another example would be ember-cli, which also is written in javascript, taking about 0.6s (still too slow IMO, I created a similar issue there).

The big difference for our use case is that if it reliably takes less than ~0.2 seconds, we can block the UI and run the check synchronously. If not, we need to add a loading spinner or cache the value somehow (with all the complexity of invalidating the cache after a set interval etc to avoid reporting wrong data).

**Comment by ariya** [comment]
Did you try to uncompress the executable?

**Comment by marco-nicola** [comment]
Hi,
here's my OS details (the same as *thomassnielsen*)
```
$ system_profiler SPSoftwareDataType
Software:
    System Software Overview:
      System Version: OS X 10.10.2 (14C1510)
      Kernel Version: Darwin 14.1.0
```
and I run *PhantomJS 2.0.0* precompiled (`phantomjs-2.0.0-macosx.zip`).

I can confirm the slowness (sometimes > 2s).

When I try to decompress the executable file with UPX, as suggested, the response is:
```
upx: phantomjs: NotPackedException: not packed by UPX
```

I'm not a UPX expert, but it seems that it was compiled and installed correctly.
Maybe I have to try to decompress a phantomjs binary built from sources?

**Comment by ariya** [comment]
Did you use the proper way to decompress it?

```
upx -d /path/to/bin/phantomjs
```

**Comment by marco-nicola** [comment]
@ariya of course, here the details:
```
$ upx --version
upx 3.91
UCL data compression library 1.03
LZMA SDK version 9.20
Copyright (C) 1996-2013 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2013 Laszlo Molnar
Copyright (C) 2000-2013 John F. Reiser
Copyright (C) 2002-2013 Jens Medoch
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.

$ upx -d phantomjs
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: phantomjs: NotPackedException: not packed by UPX

Unpacked 0 files.

$
```
Could it be a UPX version problem?
Is there a way to know exactly how the precompiled binary included in `phantomjs-2.0.0-macosx.zip` was actually compressed?

**Comment by thomassnielsen** [comment]
I get the same trying to decompress. My phantomjs is installed through npm. Copied the binary to a temp location and attempted decompression, got the same `NotPackedException: not packed by UPX`.

Besides, for our use case, decompressing the executable isn't much of a viable option anyway, as our utility will mostly be working with the users existing install (or installing for them through npm).

**Comment by ariya** [comment]
It's not about whether the decompression is useful or not. This report is about "ridiculously slow" and we need to compare the speed when the executable is UPX-compressed vs when it is not compressed. If there is no major difference, then definitely it's not attributed to the UPX compression.

**Comment by ariya** [comment]
It is overtaken by event. For any future versions, we don't plan to compress the executable using UPX anymore and hence the perceived slowness will disappear.
