### ISSUE TITLE
Underline thickness does not grow with font size

### ISSUE THREAD

**Issue by cbou** [ariya/phantomjs#13111]
When underlining headlines for example, the line is still as small as for paragraph.

Chrome:
![screen shot 2015-03-27 at 10 41 56](https://cloud.githubusercontent.com/assets/611389/6865433/04e02fcc-d46e-11e4-9084-18b903e7c2a5.png)

PhantomJS 2.0.0 on Mac
![screen shot 2015-03-27 at 10 42 40](https://cloud.githubusercontent.com/assets/611389/6865436/0f910220-d46e-11e4-960e-49cbfc554562.png)

I have the same problem with Debian.

As a workaround I used border-bottom with `em` size at the moment.

**Comment by cbou** [comment]
Any news for this issue ?

**Comment by mmacarie** [comment]
The problem still persist in version 2.1.

**Comment by msdobrescu** [comment]
I confirm, please fix it.

**Comment by josh-oiknine** [comment]
We are having the same issue using default fonts and tried webfonts as well.

**Comment by HaukeST** [comment]
We have this issue, too. Would be great if you could fix it, state that it won't be fixed or when it might possibly be fixed. 

Thank you in advance.
