### ISSUE TITLE
HTTP 409 Conflict responses with no body content cause an error with ajax requests

### ISSUE THREAD

**Issue by aprescott** [ariya/phantomjs#13110]
Apologies for the really long issue description here but I couldn't find a way to explain it without starting at the beginning.
### Summary

I believe phantomjs's QtWebKit implementation suffers from a bug where a HTTP 409 Conflict response to an ajax request will have an error status of 0 when the response body is empty. It seems like this bug used to exist in Safari, may still exist in similar situations on Firefox, and so maybe still exists in QtWebKit.

Note that this error happens even on a same-origin request where there is no issue around `preventDefault()`.
### Longer explanation

We have a Rails application (using PhantomJS through Poltergeist) which returns a HTTP 409 Conflict in response to a jQuery `$.ajax` POST request. When the 409 response comes back, the `$.ajax` `error` handler triggers, as expected, which looks like this:

``` javascript
error: function(jqXHR, textStatus, errorThrown) {
  if (jqXHR.status === 409) {
    window.location = jqXHR.getResponseHeader("Location");
  }
}
```

This all worked fine on Rails 4.2.0, but when upgrading to Rails 4.2.1 we encountered failing tests suggesting that `jqXHR.status === 409` was no longer true. To get better insight, I added a line to the top of the `error` handler to simply

``` javascript
throw "" + jqXHR.status + " -- " + jqXHR.readyState + " -- " + textStatus;
```

On the test-passing 4.2.0, this shows the correct `jqXHR.status` of `409`. On the test-failing 4.2.1, it instead gives
- `jqXHR.status` as `0`.
- `jqXHR.readyState` as `0`.
- `textStatus` as `"error"`.

---

I'd like to pre-emptively address 2 questions here, in light of [various parts of the Internet that talk about the error values above](http://www.justinball.com/2013/02/25/jqxhr-returning-readystate-0-and-status-0/).

**This error can happen from cross-origin requests. Are you doing cross-origin requests?**

No. Nothing about the application, URL structure, domain structure, or other cross-origin related architectural stuff changed. The only difference between the passing commit and the failing commit is that the former is Rails 4.2.0 and the latter is Rails 4.2.1. No JavaScript libraries or dependencies change between the passing and failing commits.

**This error can happen when form submissions or links have JavaScript handlers that don't call `preventDefault()`. The browser's regular execution of a hyperlink or a form submission can break the ajax handler. Have you tried adding that?**

Again, there are no changes to HTML structure between the passing and failing commits. Second, the elements that trigger the ajax request don't have any default behaviour like a link or a form submission. In this specific case they're `<input>`s floating free from any actual `<form>` element.

---

After much digging, I discovered that one change included in Rails 4.2.1 was the way that HEAD responses work. Our response of 409 Conflict is implemented with

``` ruby
head :conflict, location: a_location_value
```

In Rails 4.2.0 (and many versions earlier), this actually included a single space for the response body. (For some specifics, responses with a HTTP code other than the 1xx series, 204, 205, and 304 are marked as never including content, whereas others — including the 409 in question — _can_ include content as per the HTTP spec, and in those cases a single space `" "` is used.) After https://github.com/rails/rails/pull/18255 (as part of fixing https://github.com/rails/rails/issues/18253), included in Rails 4.2.1, the response body for `head :conflict` is now empty, and not a single space. This seems to be directly responsible for causing the `0`/`0`/`"error"` values in XHR error handler. The reason being that replacing the `head` response allows you to toggle the pass/fail status of the test in question.

``` ruby
# this fails because it's basically equivalent to the `head` call
render text: "", status: :conflict, location: a_location_value

# this works, by working around the altered implementation of `head`
render text: " ", status: :conflict, location: a_location_value
```

I recreated this failure with phantomjs 1.8.2, 1.9.8 and 2.0.0, using jQuery 1.11.2. I also reproduced it with jQuery 1.11.1 and 1.11.2 using, I _think_, either phantomjs 1.7.0 or 1.8.2.
### Sounds like a jQuery problem — isn't this a jQuery problem?

I don't think so. There have been (and still are?) similar bugs to the one I'm describing here, where the bug is reported with the browser and where the jQuery team has explicitly stated it's a browser bug. Here's my thinking:
1. It works fine in a regular Chrome browser, 42.0.2311.60 beta (64-bit).
2. It works fine in a regular Firefox browser (version 34?).
3. Through http://bugs.jquery.com/ticket/13654 and https://bugzilla.mozilla.org/show_bug.cgi?id=521301 this sort of bug used to(?) exist for responses where there was no body, e.g., 204 No Content.
4. Similarly, the whole point that Rails included an empty space (`" "`) in their `head` responses was to work around a Safari bug. (See https://github.com/rails/rails/commit/cb0f8fda9652c4d24d04693bdb82cecd3b067e5c and https://github.com/rails/rails/commit/807df4fcf021fc4d15972aa1c17ba7398d43ab0d).

Specifically, the comment at http://bugs.jquery.com/ticket/13654#comment:14 seems to suggest that this issue comes directly from the browser. The fact that https://bugzilla.mozilla.org/show_bug.cgi?id=521301 exists as a bug in Firefox backs that up, too.

All that leads me to think that this is a bug in the XHR implementation of QtWebKit, especially given the inevitably mismatch between what QtWebKit does and what a plain WebKit browser would do. With more time I could provide a minimal failing test application.

**Comment by naw** [comment]
We are seeing similar behavior in a test that depends on jQuery evaluating the status code returned by a `head :forbidden` in Rails 4.2.1  Instead of a 403 as expected, we get a 0.

**Comment by GeekOnCoffee** [comment]
nice find!
