### ISSUE TITLE
realloc:  invalid next size with PhantomJS 1.9.8

### ISSUE THREAD

**Issue by vrsean** [ariya/phantomjs#13126]
Hi all,

We have a 30 node Jenkins cluster of virtual machines off two blades and got a "realloc: invalid next size"  on 3 separate VMs yesterday that build PRs--the PRs were very small compared to the rest of our fairly large codebase.   We use the PhantomJS rubygem so it doesn't look like upgrading to 2.0 is possible for us yet.    

http://pastebin.com/xZ5dZ88x

This error hasn't happened today, nor has it happened before to my knowledge.  Any advice?   

Thanks for your help.  

--sean

**Comment by lostick** [comment]
I have the same issue when evaluating an html page of 13M. I tried with both 1.9.8 and 2.1.1.
