### ISSUE TITLE
Header margin varies between Windows and Linux

### ISSUE THREAD

**Issue by sanand0** [ariya/phantomjs#13122]
When using the following paperSize configuration:

```
page.paperSize = {
    format: 'A4',
    orientation: portrait,
    header: {
        height: '1cm',
        contents: phantom.callback(function(pageNum, numPages) {
            return  '<div style="width:100%;display:block;height:30px;background-color:#000000;color:#fff">Hello header</div>';
        })
    }
}
```

... and render http://example.com/ (or any other page) as PDF, the Linux version of PhantomJS 2.0.0  renders the header without any margin (like below):

![image](https://cloud.githubusercontent.com/assets/63734/6964213/ac20b234-d964-11e4-86ff-7305aad47b42.png)

... but the Windows version has a margin on the top (like below):

![image](https://cloud.githubusercontent.com/assets/63734/6964252/ff2c5b40-d964-11e4-8bde-8fe3e4c80dac.png)

The extent of the margin varies based on the `height`. For example, with a height of `10cm`, the top margin on Windows is much higher as well.

(I think the expected behavior is what Linux shows. There appears to be no way of removing the top margin on Windows.)

**Comment by sychare** [comment]
I can confirm that we're seeing exactly that behaviour on Windows. We've headers of ~7cm and it makes PhantomJS pretty much unuseable.
