### ISSUE TITLE
Closed Connection issue

### ISSUE THREAD

**Issue by sean-hill** [ariya/phantomjs#13125]
Hey there,

I have this url: 
https://online.subutil.com/scripts/cgiip.exe/WService=SBOnline/login.w

I get this response:

```
Request (#1): {
    "headers": [
        {
            "name": "User-Agent",
            "value": "Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34"
        },
        {
            "name": "Accept",
            "value": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
        }
    ],
    "id": 1,
    "method": "GET",
    "time": "2015-04-02T18:52:58.570Z",
    "url": "https://online.subutil.com/scripts/cgiip.exe/WService=SBOnline/login.w"
}
Unable to load resource (#1 URL:https://online.subutil.com/scripts/cgiip.exe/WService=SBOnline/login.w)
Error code: 2. Description: Connection closed
Unable to access url: fail
```

Doesn't work on my production linux machine, but does work on my mac local machine.
Doesn't work with https but does work with http.

I've `apt-get update && apt-get upgrade` everything. I'm running version `1.9.8`. Can anyone replicate this error? Thanks for any help you can provided.

**Comment by marco-nicola** [comment]
Hi, have you tried requests to other https URLs?

**Comment by sean-hill** [comment]
@marco-nicola, yes I have and they work fine. It's just his unique url that doesn't seem to work. This is also only happening on my linux server, but works fine on my mac computer. It might be something to do with the linux binaries.

**Comment by marco-nicola** [comment]
@sean-hill can you please specify your linux distro and version? Also, did you installed phantomjs via `apt-get` or from sources (I guess the former)? Maybe I'll try to test on the same or a similar environment.

**Comment by sean-hill** [comment]
@marco-nicola I installed it from the source via [this](https://gist.github.com/julionc/7476620) tutorial. 

	DISTRIB_ID=Ubuntu
	DISTRIB_RELEASE=14.04
	DISTRIB_CODENAME=trusty
	DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
	NAME="Ubuntu"
	VERSION="14.04.2 LTS, Trusty Tahr"
	ID=ubuntu
	ID_LIKE=debian
	PRETTY_NAME="Ubuntu 14.04.2 LTS"
	VERSION_ID="14.04"

**Comment by sean-hill** [comment]
Also here is the script i used to test just opening a page.

    var page = require('webpage').create();

    var system = require('system');
    var url = system.args[1];

    page.settings.userAgent = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36';

    page.onError = function(msg, trace) {

        var msgStack = ['ERROR: ' + msg];

        if (trace && trace.length) {
            msgStack.push('TRACE:');
            trace.forEach(function(t) {
                msgStack.push(' -> ' + t.file + ': ' + t.line + (t.function ? ' (in function "' + t.function +'")' : ''));
            });
        }

        console.error(msgStack.join('\n'));

    };

    page.onResourceRequested = function(requestData, networkRequest) {
        console.log('Request (#' + requestData.id + '): ' + JSON.stringify(requestData, null, '\t'));
    };

    page.onResourceError = function(resourceError) {
        console.log('Unable to load resource (#' + resourceError.id + ' URL:' + resourceError.url + ')');
        console.log('Error code: ' + resourceError.errorCode + '. Description: ' + resourceError.errorString);
    };

    page.open(url, function (status) {
        if (status !== 'success') {
            console.log('Unable to access url:', status);
        } else {
            var html = page.evaluate(function() {
                return document.getElementsByTagName('html')[0].innerHTML;
            });
            console.log(html);
        }
        phantom.exit();
    });

**Comment by marco-nicola** [comment]
I just tried it on the same OS version *Ubuntu Server 14.04.2 LTS* & *phantomjs 1.9.8* and it worked well; but I built it from sources... this is probably the only difference.

I can suggest you too to download and build the sources, maybe using the latest stable release, and then retry. I recently built [`phantomjs-2.0.0-source.zip`](https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-source.zip) and your code works fine again with this.

But, of course, this does not solve completely nor explain the original issue!

Just one last thought (might be naive)... did you tried a simple `curl` call on your GNU/Linux System? Does it work?
Just this:
```
curl https://online.subutil.com/scripts/cgiip.exe/WService=SBOnline/login.w
```

**Comment by sean-hill** [comment]
Hey @marco-nicola, thanks so much for the help! I have tried `curl` and it works fine. It's such a bizarre issue. Do you have a tutorial of how to install 2.0 on an Ubuntu server? It looks like phantom doesn't have binaries right now to download.

**Comment by marco-nicola** [comment]
I started from here: [http://phantomjs.org/download.html](http://phantomjs.org/download.html)
As you can read there - and as you said - unfortunately there isn't a precompiled version yet and, sadly, the build process takes a long time to complete, but the procedure is quite easy.

First assumption: I hope you does not have particular restrictions about the installation of a little bunch of `apt-get` packages. If there are no problems, let me summarize the procedure:

Let's download the sources:
```
$ wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-source.zip
```
Depending on your paranoia level, you can compare `MD5` and/or `SHA-256` checksums with the ones reported on the download page linked above:
```
$ md5sum phantomjs-2.0.0-source.zip
feabe9064100e241d21347739312e64d  phantomjs-2.0.0-source.zip
$ sha256sum phantomjs-2.0.0-source.zip
cc81249eaa059cc138414390cade9cb6509b9d6fa0df16f4f43de70b174b3bfe  phantomjs-2.0.0-source.zip
```

Unzip it (I love the super-easy `unzip`, if you don't already have it, just run `sudo apt-get install unzip`) and, maybe, let's clean up removing the archive:
```
$ unzip phantomjs-2.0.0-source.zip
$ rm phantomjs-2.0.0-source.zip
```

Now, let's follow the instructions from here: [http://phantomjs.org/build.html](http://phantomjs.org/build.html).
As anticipated, before building you need some packages:
```
sudo apt-get install build-essential g++ flex bison gperf ruby perl \
  libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
  libpng-dev libjpeg-dev ttf-mscorefonts-installer
```
The last one (`ttf-mscorefonts-installer`) is not mandatory, but *it is recommanded* (so, *why not?*, I say).

Please note: the *build.html* page explains how to get sources directly from `git clone`, but in my case I preferred the zip file.

So, let's just step into the extracted folder and run the build process:
```
$ cd phantomjs-2.0.0/
$ ./build.sh
```
You'll quickly notice an important warning:
> ```
WARNING: Building PhantomJS from source takes a very long time, anywhere from 30
minutes to several hours (depending on the machine configuration).
```

Etcetera...

That's true, the build process might be very long; I compiled it on a ~2GHz x12 cores (with hyperthreading) machine and, just running the `build.sh` command *as is* like above, it took ~25 minutes.
But also I remind you to this note (from the *build.html* page):

> **Note:** `build.sh` by default will launch parallel compile jobs depending on the available CPU cores, e.g. 4 jobs on a modern hyperthreaded dual-core processor. If necessary, e.g. when building on a virtual machine/server or other limited environment, reduce the jobs by passing a number, e.g `./build.sh --jobs 1` to set only one compile job at a time.

If you had enough patience, now you're done: your new phantomjs executable file is located into the `bin` folder. From the `phantomjs-2.0.0` folder where you already should be, just try this:
```
$ ./bin/phantomjs --version
2.0.0
```

Now you can place this executable file where you want (eg. `/usr/local/bin` etc...).
Personally, I like to keep on my system some other good stuff, such as all the examples in the `examples` folder, and I also like to keep trace of possibly useful older and future versions, so here is my way:
```
$ cd ..
$ sudo mv phantomjs-2.0.0 /usr/local/phantomjs-2.0.0
$ sudo ln -s /usr/local/phantomjs-2.0.0 /usr/local/phantomjs
```
So you can call directly `/usr/local/phantomjs/bin/phantomjs` or, as I do, you can append `/usr/local/phantomjs/bin/` to the PATH environment variable (see `/etc/environment`).

The symbolic link provides a system-wide way to quickly upgrade (or downgrade) versions. For example, on my machine there is also a `/usr/local/phantomjs-1.9.8/bin/phantomjs`, which I can call directly, but when I just run `$ phantomjs` it refers to the latest version.

I hope this will be useful.
Cheerio! :)

**Comment by haridak** [comment]
I've been coming across a similar problem lately.
Test env : Minitest + Capybara-poltergeist + phantomjs 2.0.0
The test case, tries to visit a url https://staging.storedgefms.com and when it tries to do that, the test fails with the following error.
Minitest::UnexpectedError: Capybara::Poltergeist::StatusFailError: Request failed to reach server, check DNS and/or server status
The test case works fine with phantomjs 1.9.8.

**Comment by zackw** [comment]
This sounds very much like a regression in Qt's HTTP implementation.  The thing that would be most helpful to pinning it down is wireshark traces of both failing and succeeding network activity.

Another thing that would be very helpful is a *complete, self-contained* test case -- in this case that means a canned web server configuration so we can spin up a test server on one of our computers and watch @sean-hill's script fail.

**Comment by haridak** [comment]
Thanks @zackw. Do you have a  tentative ETA on getting this fixed?

**Comment by zackw** [comment]
@haridak Uh, I said I needed more information.  That means I can't do anything myself until I get that information.

**Comment by haridak** [comment]
Sorry, I didn't realize you were asking me. Let me see if I get you the wireshark traces. @zackw

**Comment by haridak** [comment]
Meanwhile, can someone suggest a workaround for this, other than install 1.9.8.?

**Comment by haridak** [comment]
@zackw here's the wireshark trace
[capybara-poltergeist-phantom200.txt](https://github.com/ariya/phantomjs/files/36097/capybara-poltergeist-phantom200.txt)
