### ISSUE TITLE
use PhantomJS  vist a web result in "You have not installed Flash or version is too low, please click on the install"

### ISSUE THREAD

**Issue by wsshopping** [ariya/phantomjs#13120]
Hi, all :
when i use PhantomJS  vist a web result in some problems, 

1.   the content in my script is : 

var page = require('webpage').create();
page.open("http://www.zhanqi.tv/1135749", function() {
var text = page.evaluate(function () {
return document.body.innerHTML;
});
console.log(text);
phantom.exit();
});

2.   after i  exc the command "  phantomjs   test.js  " ,  return something contains in the respond:

 <div class="no-flash">您未安装Flash或者版本过低，请点击<a
(You have not installed Flash or version is too low, please click on the install)

3.   it seems to be beaucasue of the flash version, but when i install the flash-plugin-11.2.202.451-release.x86_64.rpm  and reboot the system,  it tips me the same question.

4.  only the successful visit this page video, I can get what I want, HTML tag
 
thank you for any  answer

**Comment by JosephCastro** [comment]
Phantom doesn't have support for Flash. This doing only JS.

**Comment by wsshopping** [comment]
thank you
