### ISSUE TITLE
GIF format renders to empty file for render() 

### ISSUE THREAD

**Issue by radiosilence** [ariya/phantomjs#13135]
...and empty string for renderBase64()

Tested on OSX Yosemite and Ubuntu 14.04 "trusty".

So basically this means GIF support is entirely broken?

**Comment by radiosilence** [comment]
Looks like this is to do with QT:

http://doc.qt.io/qt-4.8/qimage.html#reading-and-writing-image-files

So we'd need to add in a custom GIF library if that was the file format.

**Comment by rjperrella** [comment]
@radiosilence  I'm getting the same behavior on Windows 10 with Phantomjs version 2.1.1

**Comment by chandon** [comment]
+1
