### ISSUE TITLE
Spec file contains outdated file references

### ISSUE THREAD

**Issue by SamNelson** [ariya/phantomjs#13138]
The rpm/phantomjs.spec file contained outdated references to coffee script files that have been removed from the main project.
The spec file version is also out of date.

**Comment by fdintino** [comment]
Your pull request is very similar to mine (#13104), although in mine I add the missing `BuildRequires` packages.

**Comment by SamNelson** [comment]
Sure. How should we resolve  this?

**Comment by Vitallium** [comment]
Fixed in 8754c98
