### ISSUE TITLE
QEventDispatcher: Failed to create QEventDispatcherWin32 internal window: 1407

### ISSUE THREAD

**Issue by EricSmekens** [ariya/phantomjs#13136]
We randomly get this error, and from then on, we cannot make phantomjs work. (Only thing that makes it work is a reboot).

```` 
Exitcode: 255. Error: QEventDispatcher: Failed to create QEventDispatcherWin32 internal window: 1407Qt: Could not initialize OLE (error 80070583).
````

This seems to be improved in QT 5.3.2.
https://bugreports.qt.io/browse/QTBUG-39471

**Comment by EricSmekens** [comment]
Closing, this was related to a desktop heap allocation failure.

**Comment by cclarke6264** [comment]
We're experiencing the same problem.
Can you tell us what you found was the problem and how it was fixed ?

Thx.
