### ISSUE TITLE
Console output character encoding issue in 2.0.0

### ISSUE THREAD

**Issue by stagas** [ariya/phantomjs#13134]
platform: **Windows 7 SP1**

output:

``` console

$ phantomjs --version
1.9.8

$ phantomjs test.js
yo ✓

$ phantomjs --version
2.0.0

$ phantomjs test.js
yo ���

```

test.js:

``` js
console.log('yo ✓');
phantom.exit();
```

same when using `--output-encoding=utf8` and `--script-encoding=utf8`

**Comment by JoshuaKGoldberg** [comment]
@stagas does this happen when using a *nix cmd? Could be related to https://github.com/mrhooray/gulp-mocha-phantomjs/issues/70.

**Comment by rodrigogrow** [comment]
It happens in ubuntu 14.04 - Gnome terminal (3.5.2) too.
