### ISSUE TITLE
phantomjs crash  by  background-img  prop in table,   1.9.7

### ISSUE THREAD

**Issue by jianhuifan** [ariya/phantomjs#13137]
.abc{
    background-image: url("http://img03.taobaocdn.com/tps/i3/T1A9n1XkheXXbTWe39-124-33.png");
  }

table
  tr
      td
        span class="abc"

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
