### ISSUE TITLE
seems phantom autocomplete not works?

### ISSUE THREAD

**Issue by chapgaga** [ariya/phantomjs#13147]
what's wrong? the auto-complete for node repl is ok, why not phantom command?
http://phantomjs.org/repl.html

**Comment by JamesMGreene** [comment]
Phantoms is not Node.js, nor does it run directly on Node.js, so their respective REPL states are irrelevant.

**Comment by chapgaga** [comment]
@JamesMGreene i know phantomjs is not node, but the official document of phantomjs said that it support auto-complete, the fact is that it does not, so what's wrong?

the following picture is from http://phantomjs.org/repl.html
![](http://img.itc.cn/photo/jf0wf9P41Pk)

**Comment by wongterrencew** [comment]
@chapgaga, what version of phantomjs are you using? Auto-complete is working for me with version 2.0.0.

**Comment by momchilov** [comment]
I have the same problem, after installing phantomjs2 using npm.

**Comment by agirorn** [comment]
I have the same issue on Linux with phantomjs version 2.1.1.

**Comment by gabmontes** [comment]
Same issue here: phantomjs@2.1.1 on Linux 64-bit.
