### ISSUE TITLE
Render source HTML instead of URL

### ISSUE THREAD

**Issue by Jzarecta** [ariya/phantomjs#13148]
Is it possible for phantom render() or another method to generate an image from an HTML snippet as opposed of a URL page?

Working withing a MVC, it would be a pain to generate a route just to render what we need back into an image snapshot. 

I wonder if I can just generate the html with the needed img src= and others, and have it withing the render() method?

If this is not possible and I am crazy, maybe you can suggest a different route to approach the problem.

**Comment by magemore** [comment]
```javascript
page.open('data:text/html,'+
    '<body>hello</body>', function(status){
        console.log(status);
        page.render('render_html.png');
});
```
does it work for you?

**Comment by JamesMGreene** [comment]
You can also use `page.content = "<body>hello </body>"`.

**Comment by JamesMGreene** [comment]
Additionally, you can use `page.clipRect` prior to `page.render` to achieve a single element "view". CasperJS has made a lovely abstraction of such as [`casper.captureSelector`](http://docs.casperjs.org/en/latest/modules/casper.html#captureselector).

@aria blogged about this concept here: http://ariya.ofilabs.com/2013/04/web-page-clipping-with-phantomjs.html

**Comment by JamesMGreene** [comment]
@Jzarecta Seems like the combination of those things covers your needs, right?

**Comment by Jzarecta** [comment]
Thanks James, I solved it last night after much poking around. Yet your solution is a lot sleeker using the data:text/html declaration.
