### ISSUE TITLE
Phantomjs 2.0 crashed 

### ISSUE THREAD

**Issue by soulrenger** [ariya/phantomjs#13142]
Im using Phantomjs 2.0 and I can't find any symbol file for it ,so I chose 1.98 version for crash report.

I posted the attach file at:
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/phantomjs/FRT_PpQZZAU
Anyone can help me?

**Comment by Vitallium** [comment]
You can't use symbol files from different version. You'll get completely wrong stack trace info.

**Comment by soulrenger** [comment]
@Vitallium 
But the official website didn't provide the latest symbol file of the 2.0 version,so I tried the 1.98version

**Comment by zackw** [comment]
@soulrenger Yeah, we know the symbol files are missing, we're working on it.  That doesn't change the fact that the 1.98 symbol file will produce a *completely meaningless* stack trace if applied to a 2.0 crash dump.

It would actually be more helpful if you could provide a test case - ideally, a self-contained single `.js` file that, when run, produces the bug.  You can use the WebServer module to serve HTML snippets to localhost.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://myphamchatluong.info/proposed.php?gu2oo>

 

klaus@hebsgaard.dk
