### ISSUE TITLE
page.render not rendering filters on svg

### ISSUE THREAD

**Issue by paragpanchal** [ariya/phantomjs#13141]
I am trying to convert svg image to png/jpg using phantomjs - page.render (page.renderBase64). It does creates a png/jpg image but it does not have filters applied on svg

**Comment by zackw** [comment]
Thank you for the bug report.  We need more information before we can do anything about it.

First, you don't say which version of PhantomJS you are using.  Version 2.0 contains a newer Webkit which *may* have fixed your problem.  Please try that.

Second, if 2.0 still doesn't work, can you provide the svg image that shows the problem?  SVG filters are very complicated and we're unlikely to be able to just make something up that triggers the same problem you're having.

**Comment by paragpanchal** [comment]
Thanks Zack for looking into this issue. I am using PhantomJS Version 2.0

Please find the attached (three) sample files – sample_576h_f.svg, sample_600h_f.svg, sample_630h_f.svg. These are three different size variation of the same svg file – 1024 x 576, 1067 x 600 and 1120 x 630.

I am providing three different size variation to demonstrate two different problems I am encountering.


1)      Sample_600h_f.svg works but it does not renders filters in the svg file. Attaching the jpg generated for Sample_600h_f.svg -> sample_600h_f.jpg.

2)      Sample_576h_f.svg and Sample_630h_f.svg does not work and crashes the PhantomJS. It gives below error message:



PhantomJS has crashed. Please read the crash reporting guide at <http://phantomjs.org/crash-reporting.html> and file a bug report at <https://github.com/ariya/phantomjs/issues/new>. Please attach the crash dump file: ...\e94e06b2-bdd6-449d-9b7b-1eb4a4704bd8.dmp



Attaching the dump file as well.

Hope this helps.

Regards,
Parag

**Comment by luanshixia** [comment]
I have encountered the same problem, and I am using 1.9.8. I guess the filter bitmap effects are hardware accelerated and rendered by GPU, thus cannot be correctly captured by `PhantomJS`.
