### ISSUE TITLE
Incorrect behavior when patching window.setTimeout

### ISSUE THREAD

**Issue by mmanela** [ariya/phantomjs#13158]
## [Patching window.setTimeout Issue in PhantomJS](https://github.com/mmanela/phantomjs_settimeout_issue)

This is a demonstration of a really strange issue in PhantomJs (tested in versions 1.9 and 2.0). The issue involves what happens when you monkey patch the window.setTimeout method in Javascript. The issue was discovered when debugging test failures that were using sinonJS (which monkey patches setTimeout). I worked through that issue and distilled the minimum repro out of it. 

I validated this issue does not occur in Chrome 41, Firefox 36 and IE 11. As far as I can tell it only repros in PhantomJS.
## Short Repro

1: Define a method (check) which references window.setTimeout

2: Call this method **two** times, then patch setTimeout to be a custom method and then call check again.

CODE:

```
function check() {
    console.log("window.setTimeout = " + window.setTimeout);
}
check();
check();
window.setTimeout = function() { console.log ("Patched"); }
check();
```

OUTPUT:

```
window.setTimeout = function setTimeout() {
    [native code]
}

window.setTimeout = function setTimeout() {
    [native code]
}

window.setTimeout = function setTimeout() {
    [native code]
}
```

3: Then call to check the third time will **not** output the contents of the monkey patched function. It will still contain the native one. THe odd thing is if you call the check() method only once (or not at all) before your patched setTimeout then it will output the expected value. For example:

CODE:

```
function check() {
    console.log("window.setTimeout = " + window.setTimeout);
}
check();
window.setTimeout = function() { console.log ("Patched"); }
check();
```

OUTPUT:

```
window.setTimeout = function setTimeout() {
    [native code]
}

window.setTimeout = function () { console.log("PATCHED"); }
```
## Runnable Repro

[This repo](https://github.com/mmanela/phantomjs_settimeout_issue) contains a phantomJS application (phantom.js) which will reproduce this issue. 

```
    phantomjs.exe phantom.js
```

This repro defines 3 method (check1, check2, check3) all which just output the contents of window.setTimeout. 

**check1**: Called 3 times. Two times before patching setTimeout and once after.
**check2**: Called 2 times. Once before patching setTimeout and once after.
**check3**: Called 1 time.  Only called after patching setTimeout

When run you will see the following output (I formatted it below so it reads better):
1. Call method check1 which outputs contents of window.setTimeout
   check1: window.setTimeout = function setTimeout() {
       [native code]
   }
2. Call methods check1 and check2 which both output contents of window.setTimeout
   check1: window.setTimeout = function setTimeout() {
       [native code]
   }
   
   check2: window.setTimeout = function setTimeout() {
       [native code]
   }
3. Moneky-patch the contents of window.setTimeout with a dummy method which just outputs the words PATCHED
4. Call methods check1, check2 and check3 which outputs contents of window.setTimeout.
   
   check1: window.setTimeout = function setTimeout() {
       [native code]
   }
   
   check2: window.setTimeout = function () { console.log("PATCHED"); }
   
   check3: window.setTimeout = function () { console.log("PATCHED"); }
5. Note that check3 (which is called once in this file) and check2 (which is called twice) both print out the expected patched setTimeout method.
   However, check1 (which is called three times) does not.

**Comment by zackw** [comment]
Thank you for your report and for the detailed reproduction recipe. Unfortunately, when I run your test program, I get this output -- the bug does not manifest:

~~~~1. Call method check1 which outputs contents of window.setTimeout
check1: window.setTimeout = function setTimeout() {
    [native code]
}
2. Call methods check1 and check2 which both output contents of window.setTimeout
check1: window.setTimeout = function setTimeout() {
    [native code]
}
check2: window.setTimeout = function setTimeout() {
    [native code]
}
3. Moneky-patch the contents of window.setTimeout with a dummy method which just outputs the words PATCHED
4. Call methods check1, check2 and check3 which outputs contents of window.setTimeout.
check1: window.setTimeout = function () { console.log("PATCHED"); }
check2: window.setTimeout = function () { console.log("PATCHED"); }
check3: window.setTimeout = function () { console.log("PATCHED"); }
5. Note that check3 (which is called once in this file) and check2 (which is called twice) both print out the expected patched setTimeout method. However, check1 (which is called three times) does not. 
~~~~

You can see that all three `check` methods report the patched function.

A problem like this is very likely to be deep in the guts of Webkit's JS interpreter. Thus, despite the fact that you only experienced the problem with PhantomJS, you may be better off reporting it at https://bugs.webkit.org/.

**Comment by mmanela** [comment]
That is odd, I did file a bug on webkit (https://bugs.webkit.org/show_bug.cgi?id=143836) but they also said no repro. I am wondering if there is some external factor. I had my co-worker try and he repro'd also. 

We both tried on Windows machines though. Did you try on a Windows box?

**Comment by zackw** [comment]
@mmanela No, I only tested on Linux.  I'll try OSX later today, but I can't easily do any testing on Windows.

This kind of bug *does* have a decent chance of being operating-system specific.  Can you test, say, Safari for Windows?

**Comment by Vitallium** [comment]
@zackw FYI: ping me, if you need to do tests on Windows.

**Comment by zackw** [comment]
@Vitallium Y'wanna try the test case https://github.com/mmanela/phantomjs_settimeout_issue on Windows?

**Comment by mmanela** [comment]
I think Safari for windows is dead. Not sure if you can still download. I did try on another Webkit based browser (http://midori-browser.org/) and was able to repro there.

**Comment by Vitallium** [comment]
Can confirm on Windows.
````
1. Call method check1 which outputs contents of window.setTimeout
check1: window.setTimeout = function setTimeout() {
    [native code]
}
2. Call methods check1 and check2 which both output contents of window.setTimeout
check1: window.setTimeout = function setTimeout() {
    [native code]
}
check2: window.setTimeout = function setTimeout() {
    [native code]
}
3. Moneky-patch the contents of window.setTimeout with a dummy method which just outputs the words PATCHED
4. Call methods check1, check2 and check3 which outputs contents of window.setTimeout.
check1: window.setTimeout = function setTimeout() {
    [native code]
}
check2: window.setTimeout = function () { console.log("PATCHED"); }
check3: window.setTimeout = function () { console.log("PATCHED"); }
5. Note that check3 (which is called once in this file) and check2 (which is called twice) both print out the expected patched setTimeout method. However, check1 (which is called three times) does not.
````

**Comment by zackw** [comment]
Thanks @Vitallium, I have added a note to https://bugs.webkit.org/show_bug.cgi?id=143836 to that effect.  I was going to test OSX, but the OSX binary on the website crashes under Yosemite, feh.

**Comment by Vitallium** [comment]
This is output from OSX (Yosemite):
````
1. Call method check1 which outputs contents of window.setTimeout
check1: window.setTimeout = function setTimeout() {
    [native code]
}
2. Call methods check1 and check2 which both output contents of window.setTimeout
check1: window.setTimeout = function setTimeout() {
    [native code]
}
check2: window.setTimeout = function setTimeout() {
    [native code]
}
3. Moneky-patch the contents of window.setTimeout with a dummy method which just outputs the words PATCHED
4. Call methods check1, check2 and check3 which outputs contents of window.setTimeout.
check1: window.setTimeout = function setTimeout() {
    [native code]
}
check2: window.setTimeout = function () { console.log("PATCHED"); }
check3: window.setTimeout = function () { console.log("PATCHED"); }
5. Note that check3 (which is called once in this file) and check2 (which is called twice) both print out the expected patched setTimeout method. However, check1 (which is called three times) does not.
````
