### ISSUE TITLE
Problema With iframe

### ISSUE THREAD

**Issue by styleweb** [ariya/phantomjs#13154]
Hello I have a problem

My code is:

var page = require('webpage').create();
           var fs = require('fs');
                page.open('{$url}', function (status) {
 
    if (status === 'success') {
 
        // Run a function in the webpage's context and catch what it returns.
        var html = page.evaluate(function() {
            // Optionally, do some more page manipulation here.
            // ...
 
            // Return the HTML from the loaded and JS-manipulated page.
            // Note that a console.log() here in this context won't be visible (by default).
            //return document.querySelectorAll('#widget2').contentDocument.documentElement;
              return document.getElementById('widget2').contentWindow.document.documentElement.outerHTML;

	
	        });
 
        // Print the HTML to standard output.
                          fs.write('{$file_name}', html, 'w');
    }
 
    // Make sure we quit PhantomJS, no point to keep waiting for nothing.
    phantom.exit();
});

The content of page is generated by javascript, create iframe but the code not print source code of iframe

Tranks

**Comment by styleweb** [comment]
up?

**Comment by SergeyZhdanov** [comment]
Hi @styleweb. I've just tried your code with static pages and it works fine. But as you mentioned content of the page is generated by javascript so possibly that content is not ready. So you could try to add time out (with setTimeout) or employ more complex solution like [here] (https://github.com/ariya/phantomjs/blob/master/examples/waitfor.js)

**Comment by styleweb** [comment]
Hello Tranks for the comment.
The page is  content of  g+.

I CAN SEND EMAIL WITH LINK ?

**Comment by styleweb** [comment]
with this code:

----

               var url = 'url'
               var page = require('webpage').create();
                var fs = require('fs');
                page.open(url, function () {
page.switchToMainFrame()
frames = page.framesCount;
for (var i=0; i < frames; i++){
  page.switchToFrame(i);
 console.log(page.frameContent)
} 
   

                    phantom.exit();
                });
                
----


Print only:
<html><head></head><body></body></html>
<html><head></head><body></body></html>

**Comment by styleweb** [comment]
up?

**Comment by zackw** [comment]
I don't think this is a bug in PhantomJS.  I think you need to change your test code so that it gives the client-side renderer a chance to download the actual content of the page.  Please try to implement the approach in [waitfor.js](https://github.com/ariya/phantomjs/blob/master/examples/waitfor.js) and see how that goes.
