### ISSUE TITLE
Not bugs but enough to cause chaos

### ISSUE THREAD

**Issue by ideepg** [ariya/phantomjs#13150]
The following link gives a detailed output as how calls coming from phantomjs can be detected and therefore worked/ignored.
http://engineering.shapesecurity.com/2015/01/detecting-phantomjs-based-visitors.html

Any plans for fixing these?Specially the javascript object

if (window.callPhantom || window._phantom) {
  console.log("PhantomJS environment detected.");
}

**Comment by JamesMGreene** [comment]
I see no compelling reason to change these.

Every browser is detectable in one way or another.  If a website chooses to block PhantomJS for some reason, then so be it... most won't want to, won't bother, or have never even heard of PhantomJS in the first place.

**Comment by gullyy** [comment]
I agree,there are no compelling reasons.I happen to have a use case(others might also have,not sure) where I don't want the web-server of the website to treat my request coming from phantomjs.The website might ban me for running automated scripts .Sooner or later they would find out I am using robots to communicate.Simple.I know I have the option to use selenium and things would be smooth but I am using phantom coz phantom doesn't open a browser in the UI hence a lot less of a hassle.

**Comment by zackw** [comment]
We probably won't ever be able to get them *all*, but I think it would be good to eliminate divergences from some known incarnation of Safari whenever they are discovered, except for the "PhantomJS" in the user-agent, which can be removed if appropriate.  (I do web crawling with PhantomJS, and it is actually important that pages not treat me specially, and I do modify the user-agent.)

In particular, I definitely think `window.callPhantom` and `window._phantom` (or whatever replaces them) should be invisible and inaccessible to page scripts that weren't injected by the PhantomJS controller script.  I also definitely think that injected scripts should be isolated from shenanigans played by page scripts (along the lines of how scripts injected by Chrome and Firefox extensions are similarly isolated)

Of the other items listed in the linked article, many amount to "QHTTP is missing protocol features, and Webkit is out of date", which should be fixed anyway.

The lack of plugins and the timing channel via `alert`, however, do not bother me.
