### ISSUE TITLE
Error while building PhantomJS 2.0 on CentOS 6

### ISSUE THREAD

**Issue by kazim1** [ariya/phantomjs#13153]
I am trying to build Phantomjs on CentOS server. It ends up with the following error every time. Can anyone have suggestions and solutions for this issue.

make[2]: Leaving directory `/home/kazim/public_html/phantomjs/phantomjs-2.0.0/src/qt/qtbase/src/gui'
make[1]: Leaving directory `/home/kazim/public_html/phantomjs/phantomjs-2.0.0/src/qt/qtbase/src'
make: *** [sub-src-make_first] Error 2

**Comment by mattbryson** [comment]
Can't recall if that was the same error, but we had to patch the repo to get it to build.

`curl -O https://patch-diff.githubusercontent.com/raw/ariya/phantomjs/pull/12899.patch`
`git apply 12899.patch`

I posted a couple of articles about building on centOS and building on AWS machine images that might help....

http://blog.rampinteractive.co.uk/compiling-phantomjs-2-0-binaries-linux/

http://blog.rampinteractive.co.uk/compiling-phantomjs-2-0-for-aws-ec2-linux-image/

**Comment by kazim1** [comment]
Still not working

**Comment by kazim1** [comment]
@mattbryson It is working now by your pre-built phantomjs 2.0 file. Thanks buddy. Closing now.

**Comment by rtacconi** [comment]
build.sh exits with 

```bash
rm -f ../../lib/libQt5Gui.a
mv -f libQt5Gui.a ../../lib/
make[2]: Leaving directory `/home/riccardo.tacconi/phantomjs/src/qt/qtbase/src/gui'
make[1]: Leaving directory `/home/riccardo.tacconi/phantomjs/src/qt/qtbase/src'
make: *** [sub-src-make_first] Error 2
```
Instead the bin works but I get the following warnings

```bash
phantomjs: /usr/lib64/libcrypto.so.10: no version information available (required by phantomjs)
phantomjs: /usr/lib64/libcrypto.so.10: no version information available (required by phantomjs)
phantomjs: /usr/lib64/libcrypto.so.10: no version information available (required by phantomjs)
phantomjs: /usr/lib64/libssl.so.10: no version information available (required by phantomjs)
```

I am using CentOS 6.4

**Comment by hdwong** [comment]
+1 help!

**Comment by rtacconi** [comment]
In a vanilla Centos it should compile. I realized the Jenkins server I was compiling in is overloaded with many softwares. The rpm distributes from phantomjs should work too.
