### ISSUE TITLE
In version 2, the export of PDF and Webpage inconsistent, but I can be exported in 1.9.7 version

### ISSUE THREAD

**Issue by baihuibo** [ariya/phantomjs#13155]
-1.9.7
![1 9 7](https://cloud.githubusercontent.com/assets/5130197/7172662/325296b0-e41e-11e4-9bd8-6e1ecf3969ac.jpg)

**Comment by baihuibo** [comment]
Connection
-2.0.0 
![2 0](https://cloud.githubusercontent.com/assets/5130197/7172724/272fb50a-e41f-11e4-995e-e409d122c079.jpg)

The contents of the output part drawing is not complete

**Comment by baihuibo** [comment]
Connection
javascript code
```javascript
var page = require('webpage').create();

function waitFor(testReady , callback){
    if(testReady()){
        callback();
    }else{
        setTimeout(function(){
            waitFor(testReady , callback);
        } , 250);
    }
}

page.viewportSize = { width: 1024, height: 800 };
page.open('http://localhost:8080/report.html', function (status) {
    if(status == 'success'){
        waitFor(function(){
            return page.evaluate(function() {
                return window._loadReady;
            });
        } , function(){
			var bcr = page.evaluate(function () { 
				return document.getElementsByTagName('html')[0].getBoundingClientRect(); 
			});
			console.log(bcr.top+'---'+bcr.left+'---'+bcr.width+'---'+bcr.height);
			// 按照实际页面的高度，设定渲染的宽高
			page.clipRect = {
				top:    bcr.top,
				left:   bcr.left,
				width:  bcr.width,
				height: bcr.height
			};
            //输出图片为PDF
            page.render('test.pdf');
            phantom.exit();
        });
    }else{
        console.log('Unable to load the address!');
        phantom.exit(1);
    }
});
```

**Comment by zackw** [comment]
I'm sorry, I don't actually see anything missing in your 2.0 screenshot, please clarify?

Also it would be helpful if you could give us a copy of the `report.html` and all necessary images and so on.

**Comment by baihuibo** [comment]
Hello,
I will be on my computer (win8.1) output sample PDF upload
The output of 2.0.0 and 1.9.7 is different, 2.0.0 chart rendering of different width
Because GitHub can't upload package, so put the code in the cloud

http://pan.baidu.com/s/1bnuDE7X
