### ISSUE TITLE
Closed window via JS - page reference is no more alive

### ISSUE THREAD

**Issue by abozhilov** [ariya/phantomjs#13157]
PhantomJS 2:
I have the following content of page.html 

```
        function closeWindow() {
                window.opener = top;
                window.close();
        }
        window.onload = closeWindow;
```

And after onload when I'm trying to use  page.evaluate I got the following error: 
`Error: cannot access member`evaluate' of deleted QObject`

**Comment by JamesMGreene** [comment]
What are you expecting to happen?

Maybe you didn't explain thoroughly enough but the behavior you described sounds about right to me so far.

**Comment by abozhilov** [comment]
I have hard reference: `var page = webpage.create();` So the page should not be GC while I have reference to that object.

**Comment by Vitallium** [comment]
You're calling `window.close`. Why do you think it should not be destroyed? It will be.
Any `close` methods inside the page which leads to closing a tab or a window like in a regular browser, will destroy (delete) your `page` object. Because `WebPage` is a `WebPage` :-)

**Comment by abozhilov** [comment]
Because it's tricky and bad design. Now before use webpage API I must to check if page actually exist even that I have hard reference. As I wrote IMHO webpage.create() should create wrapper for the actual webpage. When content script close the page, wrapper should hold empty page. Anyway, I going to write endless ifs statement...

**Comment by Vitallium** [comment]
@abozhilov well, QtWebkit by itself has a bad design. We can't change it easily.
In previous major version `WebPage` wasn't deleted immediately after we close the real web page. But in 2 version we've encountered a major issue with `phantom.exit`, so we had to change this behavior.

**Comment by abozhilov** [comment]
Well I fixed my issue with handling `page.onClosing` and exiting from the app, but you must mention in http://phantomjs.org/api/webpage/ that `page` is a weak reference.
