### ISSUE TITLE
[Windows 7] phantomjs.exit() does not end the phantomjs process

### ISSUE THREAD

**Issue by baihuibo** [ariya/phantomjs#13152]
exit在windows无法正常退出，phantomjs进程一直在执行中

**Comment by baihuibo** [comment]
在 win7 中，phantom.exit() 方法执行后，phantomjs 进程不会结束

**Comment by JamesMGreene** [comment]
In English, please?

**Comment by zackw** [comment]
Machine translation:

> In win7 during and after phantom.exit () method is executed, phantomjs process
does not end

@baihuibo Can you post for us a complete phantomjs script that demonstrates
the problem? 你能告诉我们，证明了问题的一个完整的phantomjs计划？

**Comment by baihuibo** [comment]
![1](https://cloud.githubusercontent.com/assets/5130197/7150756/ee3f2c8a-e351-11e4-9839-8a9493151fdf.png)
![2](https://cloud.githubusercontent.com/assets/5130197/7150757/eeabcd9a-e351-11e4-94ac-97114f334c47.png)
![3](https://cloud.githubusercontent.com/assets/5130197/7150763/fdbe90ba-e351-11e4-9c82-8fad71373fba.png)
![4](https://cloud.githubusercontent.com/assets/5130197/7150764/03553b46-e352-11e4-8030-3911b531f9cb.jpg)

**Comment by baihuibo** [comment]
Hi, I'm glad you can see my questions submitted.
As the above picture shows, in the process of'phantomjs.exe'and not the end.
I ask this is what causes?
-----------------------------------------
嗨，我很高兴你能看到我提交的问题。
就像上面图片里面所显示的样子，进程内的 'phantomjs.exe' 并不会结束。
请问这是什么原因导致的？

**Comment by zackw** [comment]
Thank you, that is very helpful. It should have exited.
I have two more questions.  What version of PhantomJS are you using, and where did you get it from?

谢谢你，这是非常有帮助的。它应该退出。
我有两个问题。您正在使用什么版本PhantomJS，而你从哪里得到的？

**Comment by baihuibo** [comment]
I use the version is in the official website to download the `phantomjs-1.9.7-windows` last year.
我使用的是去年在官网下载的 `phantomjs-1.9.7-windows` 版本

**Comment by zackw** [comment]
Please test version 2.0 (请测试版2.0): https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-windows.zip

**Comment by baihuibo** [comment]
Thank you, this version is the normal exit

谢谢，这个版本是可以正常退出的

**Comment by baihuibo** [comment]
I have been replaced by the 2 version, in the test Webpage screenshot PDF, there are problems, as shown in figure. But in the 1.9.7 version is the normal export.

**Comment by zackw** [comment]
Let's track the PDF problem in #13155.
