### ISSUE TITLE
get two different test result of phantomjs with TAP format on one URL

### ISSUE THREAD

**Issue by jubel-han** [ariya/phantomjs#13163]
I'm using phantomjs for test my site on Jenkins, and got the different result of the TAP within two builds, There is nothing changed. However, The result of Junit xml are same as we expected.

This is what I compared the result of TAP.

    3,4c3,4
    < ok 1 B (82) overall score
    < not ok 2 D (68) ynumreq: Make fewer HTTP requests
    ---
    > not ok 1 C (78) overall score
    > ok 2 B (80) ynumreq: Make fewer HTTP requests

    24c21
    <   message: There are 50 static components without a far-future expiration date.
    ---
    >   message: There are 45 static components without a far-future expiration date.

    77c69,81
    < ok 6 A (100) ycompress: Compress components with gzip
    ---
    > not ok 6 F (12) ycompress: Compress components with gzip

**Comment by zackw** [comment]
Thanks for the report.  We need more information before we can do anything about it.  Your tests appear to be checking for compliance with Yahoo's performance guidelines, is that right?  Did you write them yourselves, or did you get them from somewhere?  What website is this?  Exactly how are you using TAP and Jenkins?

FYI, I think this is more likely to be a problem within your own build process or testsuite than a problem with PhantomJS itself.  How did you verify that the two builds were exactly the same?  Is it possible that some of the tests are not 100% deterministic?  They seem to be reporting results in a different order each time, that is often a sign of race conditions.

**Comment by jubel-han** [comment]
@zackw  Thanks ! I've find out the reason, It seems like what you said.
The URL of I tested that is a live server on line, and it's a CDN domain which resolved multiple servers.

**Comment by zackw** [comment]
OK, I am going to close this issue now.  Thanks for clarifying.
