### ISSUE TITLE
document.querySelectorAll() return an array of null elements (except the first one)

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [ariya/phantomjs#13161]
Hello,

I think the title is pretty understandable so I will just you post you the smallest possible code required to reproduce the bug.
#### HTML

``` html
<!DOCTYPE HTML>
<html>
    <body>
        <div></div>
        <div>
            <div>something 1</div>
        </div>
    <div>something 2</div>
    </body>
</html>
```
#### Javascript

``` javascript
var page = require("webpage").create();
page.open("file:///path/to/file.html", function (error) {
    var elements = page.evaluate(function () {
        return document.querySelectorAll("div");
    });
    for(var i in elements) {
        console.log(elements[i]);
    }
    phantom.exit();
});
```

**Version : 1.9.8**

**Comment by zackw** [comment]
Confirmed to affect 2.0 as well.

If you change the script to read instead

    var page = require("webpage").create();
    page.onConsoleMessage = function (msg) { console.log(msg); }
    page.open("file:///path/to/file.html", function (error) {
        page.evaluate(function () {
            var elements = document.querySelectorAll("div");
            for (var i  = 0; i < elements.length; i++) {
                console.log(elements[i]);
            }
        });
        phantom.exit();
    });

then it gives the correct output:

    [object HTMLDivElement]
    [object HTMLDivElement]
    [object HTMLDivElement]
    [object HTMLDivElement]

which means this is a problem with the "outer environment" accessing lists in the page environment, not an issue in the guts of Webkit.  This rewrite might also give you a workaround.

Note that your `for (var i in elements)` construct iterates over some things you probably didn't want to include in the output (e.g. the `length` property).
