### ISSUE TITLE
phantomjs stdout include script error

### ISSUE THREAD

**Issue by acs1899** [ariya/phantomjs#13168]
The phantomjs (version 2.0.0) automatically print script error info (the script belongs to destination Web) when open a web page.  When I get the phantomjs stdout, I have to filter out the error info.
Can I prevent phantomjs print the destination Web script error info? (I need the page can execute script)

**Comment by zackw** [comment]
Please see #10042 for instructions on how to suppress script errors.  It's already possible, but you have to write some code.
