### ISSUE TITLE
It should be possible to send requests with no Accept-Language Header

### ISSUE THREAD

**Issue by jsut** [ariya/phantomjs#13166]
from: ./src/qt/qtbase/src/network/access/qhttpnetworkconnection.cpp

```
// some websites mandate an accept-language header and fail
// if it is not sent. This is a problem with the website and
// not with us, but we work around this by setting
// one always.
value = request.headerField("accept-language");
if (value.isEmpty()) {
    QString systemLocale = QLocale::system().name().replace(QChar::fromLatin1('_'),QChar::fromLatin1('-'));
    QString acceptLanguage;
    if (systemLocale == QLatin1String("C"))
        acceptLanguage = QString::fromLatin1("en,*");
    else if (systemLocale.startsWith(QLatin1String("en-")))
        acceptLanguage = QString::fromLatin1("%1,*").arg(systemLocale);
    else
        acceptLanguage = QString::fromLatin1("%1,en,*").arg(systemLocale);
    request.setHeaderField("Accept-Language", acceptLanguage.toLatin1());
}
```

It seems like this code comes from qt, so maybe it's not your problem really, but at any rate it doesn't seem to be possible to send a request from phantomjs that does not include an Accept-Language header.  Personally I'd much rather see this thing send no header by default and force the user to specify it.  I tried overriding the headers with the empty string and null, and both just resulted in this code pulling the lang from the locale.  I didn't look any further than that (like at what isEmpty actually does, to see if i could trick it in a less obvious way.

**Comment by zackw** [comment]
Filed https://bugreports.qt.io/browse/QTBUG-45797 to see if Qt is receptive to adding a way to suppress the header.
