### ISSUE TITLE
simple html command line argument

### ISSUE THREAD

**Issue by stevenvachon** [ariya/phantomjs#13169]
``` shell
phantomjs page.html
```

It could use a standard script for controlling the environment. Honestly, this is all many of us need when testing, especially if we have a test runner that is included via `<script>` tags.

Implementing this would denecessitate an abstraction layer like [mocha-phantomjs](https://npmjs.com/mocha-phantomjs) (and its redundant dependencies) for me. I would really prefer to use phantomjs directly and without having to work with its programmatic API on each project.

**Comment by zackw** [comment]
I can definitely see the use for this, but we'd need to pin down exactly what it should _do_ -- just load the page and then quit? wait for some event to fire and then quit? rasterize?

**Comment by stevenvachon** [comment]
How about loads the page, and `onload` checks if there're any pending events (timers, event listeners, etc), it quits? Node has `process._getActiveHandles()`

**Comment by ariya** [comment]
> ... and when finding no pending events ...

This is actually the hardest part. Since WebKit will never expose that, there is no way we will have an accurate information. Even if we want to hack it, there are countless corner cases that will make this a rabbit-hole level of activities.

**Comment by ljharb** [comment]
If phantom wrapped `setTimeout` and `setInterval`, as well as the native event API and xhr, and any other async APIs, then it could absolutely know that. It'd definitely be a rabbit-hole tho.

**Comment by ariya** [comment]
@ljharb All those things are hard, WebKit is designed for long-running browsing activities and not a quick launch-process-terminate style.
