### ISSUE TITLE
phantom stderr: PhantomJS has crashed.

### ISSUE THREAD

**Issue by davidbielik** [ariya/phantomjs#13162]
Dump file is below:

When I crawl a local site it works, but crawling `http://www.time.com` for example, crashes phantomJS. I'm using the node phantom module (`require('phantom')`)

https://gist.githubusercontent.com/dbielik/bc4a61c5594721026ef3/raw/55843cbfb1811fd1fccc503b6c9a44ef257d0143/PhantomJS%20dump%20file

```
phantomjs --version
1.9.8
```

**Comment by zackw** [comment]
Thank you for your bug report.  PhantomJS 1.9.x is no longer being developed.  PhantomJS 2.0 includes a major update to Webkit which fixed a whole lot of crash bugs.  Would it be possible for you to test whether 2.0 has the same problem?  You can get it from http://phantomjs.org/download.html.
