### ISSUE TITLE
PhantomJS 2.0.0 crashes on certain websites - Ubuntu 14.04

### ISSUE THREAD

**Issue by scone** [ariya/phantomjs#13170]
PhantomJS 2.0.0 installed from Ubuntu 14.04 repos crashes on seemingly random websites (although fewer than 1.9.8 did). Symbols file for v2.0.0 isn't available on bitbucket. 
I can't attach the dump file here as instructed on http://phantomjs.org/crash-reporting.html so here it is on dropbox. https://www.dropbox.com/s/uigu8pxadv7ehbs/7165496f-ace4-fdd3-6a884410-73c34acd.dmp?dl=0

**Comment by zackw** [comment]
Without having looked at the crash dump yet, based on the assertion that it crashes on "seemingly random websites", this is _probably_ down to our copy of Webkit being rather old, even in 2.0.  Unfortunately there is no easy way to upgrade it (or we would be keeping it more up to date ourselves).

**Comment by scone** [comment]
I'm trying to find a URL that causes this issue. The one that caused the dump wasn't saved to a log file. 

Additional information that may help:
phantomJS version 2.0 binary provided by DigitalOcean Ubuntu repository.
VPS is running 1GB of RAM, 1CPU
Website/server load is low.

Is there any more information I can give to help debug? I'm planning to replace the DigitalOcean binary with a locally compiled version with debugging on so I can trace the dump with the proper symbols.

**Comment by scone** [comment]
I was able to document a URL which causes a crash on my system. This is a potential phishing webpage (my app documents and identifies suspicious URLs) and so it may not stay live for long.

http://ltech.de09s.emmanuelastier.com/www..usaacom/inetent_logon/usaabank~update/

I still haven't had luck in creating a symbol file for my PhantomJS binary, so my crash dump isn't useful. Maybe someone else can shed some light.

**Comment by chrism-dp** [comment]
I ran across two more website that do the same thing (crash while loading the page)
http://www.cremedelamer.com/
http://www.bumbleandbumble.com/

Phantom 2.0.0 and 2.0.1-development,  on Ubuntu 14.01, Compiled from source, on Linode and in Docker container.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://teachmechemistry.co.uk/team.php?y9>

 

klaus@hebsgaard.dk
