### ISSUE TITLE
Support for Float64Array

### ISSUE THREAD

**Issue by fahdsheikh** [ariya/phantomjs#13177]
I'm using Karma with PhantomJS, and I've read about this issue earlier (due to the outdated webkit?) and it appears there isn't any fix when I last checked. I've read that PhantomJS 2.0 will support it, but for now there isn't any support at all.

**Comment by Aourin** [comment]
What was the resolution to this? I have been digging and it seems to be that support is getting added, but phantom 2.0 seems to still be unstable (or from what I have heard).
