### ISSUE TITLE
Enhancement : window.crypto.getRandomValues() Support

### ISSUE THREAD

**Issue by grempe** [ariya/phantomjs#13173]
Please add support for the window.crypto.getRandomValues() JS API.  Without this it is not possible to test any JS based application that does cryptography and needs a secure source of random numbers.  Such applications just fail under PhantomJS.

**Comment by zackw** [comment]
Thanks for the suggestion.  Is `window.crypto.getRandomValues` available in Webkit yet?  It needs to be implemented there before we can pick it up.

**Comment by grempe** [comment]
Yes, believe  so. See:




https://trac.webkit.org/changeset/134440





And:




http://caniuse.com/#feat=getrandomvalues





Safari has supported it for quite some time. 






—Glenn Rempe




email                  : glenn@rempe.us

voice                  : (415) 613-1653

twitter                 : @grempe

gpg key id          : 0xA4A288A3BECCAE17

gpg fingerprint   : 497A 6138 963D 6C47 202B  238B A4A2 88A3 BECC AE17

**Comment by benhutchins** [comment]
+1

**Comment by iradul** [comment]
```window.crypto.getRandomValues``` function exists and it's working well in PhatnomJS 2.0

**Comment by LeMoussel** [comment]
On Windows 7, `window.crypto.getRandomValues` function exists and working well with PhantomJS 1.9.8 & 2.0.0

```javascript
var array = new Uint32Array(10);
window.crypto.getRandomValues(array);

console.log("Your lucky numbers:");
for (var i = 0; i < array.length; i++) {
    console.log(array[i]);
}

phantom.exit();
```
Src : [MDN RandomSource.getRandomValues()](https://developer.mozilla.org/fr/docs/Web/API/RandomSource/getRandomValues)
