### ISSUE TITLE
Issues with XHR

### ISSUE THREAD

**Issue by pronebird** [ariya/phantomjs#13174]
Hi,

I can't get XHR to work on phantomjs.

``` js
console.log('url = ' + url);
var xhr = new XMLHttpRequest();

xhr.onload = successFn;
xhr.onerror = errorFn;
xhr.onabort = errorFn;
xhr.onprogress = progressFn;

xhr.open('GET', url, true);
xhr.responseType = 'blob';
xhr.send();
```

I use local relative URL: `assets/ball.png`. All of this works on Safari and Firefox though.

I get this printed in console:

```
url = assets/ball.png
Error loading resource file:///Users/pronebird/tests/undefined (203). Details: Error opening /Users/pronebird/tests/undefined: No such file or directory
```

As a matter of fact I use phantomjs indirectly via `gulp-mocha-phantomjs` package.

My gulp task looks as following:

``` js
gulp.task('test', function () {
    return gulp.src('tests/runner.html')
        .pipe( mochaPhantomJS({
            phantomjs: [
                '--web-security=off',
                '--local-to-remote-url-access=on',
                '--ignore-ssl-errors=true'
            ]
        }) );
});
```

**Comment by pronebird** [comment]
Standard transport via img.src, img.onload works fine.

**Comment by zackw** [comment]
Please don't close your bug report just because you've found a workaround.  We would like to remember to make XHR actually work. :wink:

**Comment by pronebird** [comment]
@zackw sorry for that.

Update: 

If use a non-existing path then logs show correct address, it's only logged as undefined for files that exist.

**Comment by zackw** [comment]
I think I can probably construct a test case out of the information you've provided, but we need one more piece of information: what version of PhantomJS are you using? And if it's 1.9.x, have you tried 2.0?

**Comment by pronebird** [comment]
It's 1.9.1. I didn't test it on 2.0 since I use phantomjs indirectly via other plugin which is not migrated to 2.0 yet.

**Comment by pronebird** [comment]
A complete test case with image decoding:

```js
var URLObject = window.URL || window.webkitURL || window.mozURL;
var xhr = new XMLHttpRequest();
xhr.onload = function () {
  var img = new Image();
  img.onload = function () {
    img.onload = null;
    URLObject.revokeObjectURL(img.src);
    console.log( 'Decoded image from XHR blob. Image size: {%f, %f}', img.width, img.height );
  };
  img.src = URLObject.createObjectURL(xhr.response);
};
xhr.onerror = function () {
  console.log('Failed to load resource. Error: ', e);
};
xhr.onabort = function () {
  console.log('Aborted');
};

xhr.open('GET', 'assets/ball.png', true);
xhr.responseType = 'blob';
xhr.send();
```

**Comment by sumbach** [comment]
Is this related to/duplicate of #11721 or #12332?
