### ISSUE TITLE
Phantom JS gets crashed

### ISSUE THREAD

**Issue by AnnamalaiNagappan** [ariya/phantomjs#13188]
I am facing a problem of Phanomjs getting crashed, when I try to see what is wrong. There was a error message saying file a bug report with a dmp file.This happened when I was trying to take a PDF of a html page.

I was unable to attach the dmp file, so am sharing the link

https://drive.google.com/file/d/0B_IkFcVfd3N5VzBzWGJWUlBoSHc/view?usp=sharing

**Comment by surenderthakran** [comment]
@AnnamalaiNagappan also share a bug reproduction
