### ISSUE TITLE
phantomjs not redirecting

### ISSUE THREAD

**Issue by gustavolira** [ariya/phantomjs#13187]
I'm using angular with protractor to create my e2e tests.

If I do my tests with Firefox or Chrome everything works fine, but if I do my tests with phantomjs(version 1.9.8) almost all my tests fail because phantomjs is not doing my redirects.

Just a simple test that would be:

```
Open a page,
click on a button that redirect to another url
check if url change
```

This test will fail =(

**Comment by Vitallium** [comment]
How exactly it fails?
PhantomJS 1.9.X doesn't play well with AngularJS. I suggest you to try 2.X

**Comment by gustavolira** [comment]
Hi,

First of all, thank you for your attention.

I simple test like this below fails with phantomjs + protractor:

beforeEach(function () {
  browser.get("/")
});


it('teste', function() {

  element(by.id('loginBtn')).click().then(function() {
    expect(browser.getLocationAbsUrl()).toEqual("/login");
  });

})

Unfortunately I couldn't be able to install phantomjs at ubuntu

2015-04-29 3:31 GMT-03:00 Vitaly Slobodin <notifications@github.com>:

**Comment by AdamDanischewski** [comment]
It may be due to an unavailable SSL protocol if it's going to an https on the redirect. I saw phantomjs failing strangely for pinterest for example. 

Try starting phantomjs with the following options: 
` phantomjs --ssl-protocol=any --ignore-ssl-errors=true 
`
If that doesn't work, you can put a little code snippet into your phantomjs to take a look at where it's going: 
```
page.onNavigationRequested = function(url, type, willNavigate, main) {
  console.log('Trying to navigate to: ' + url);
  console.log('Caused by: ' + type);
  console.log('Will actually navigate: ' + willNavigate);
  console.log('Sent from the page\'s main frame: ' + main);
  if (address !== url) { address = url; }; 
}
``
