### ISSUE TITLE
page.evaluate returns CSSOM as lowercased

### ISSUE THREAD

**Issue by BradleyStaples** [ariya/phantomjs#13197]
While inside of a page, getting rules via window.document.styleSheets[index].cssRules seems to be returning the selectorText of each rule in the array as lowercase, regardless of the case of the CSS read. I ran into this while using https://github.com/filamentgroup/criticalCSS which makes use of phantomJS.

In this case, because the outputted data is lowercased css, further use of document.querySelector() to find matching rules will fail if the original CSS was not lowercase, because that method (as well as the class attribute of HTML)  is case sensitive.

**Comment by jeffwhelpley** [comment]
You can close this. The issue occurs when your document is missing the HTML5 doctype:

```
<!DOCTYPE html>
```

The fix for this issue was submitted to criticalCSS. For other PhantomJS users, the fix would be in the source HTML document being requested by phantom.
