### ISSUE TITLE
phantomwebintro.js demo example fails on windows 7

### ISSUE THREAD

**Issue by kiwiheretic** [ariya/phantomjs#13196]
Running phantomjs-2.0.0-windows version.

C:\Projects\phantom\examples>phantomjs phantomwebintro.js
$(".explanation").text() ->

--- No text after the -> is displayed.

**Comment by jmiller76** [comment]
I changed the URL to http://phantomjs.org (no www)
and the jQuery version to 1.8.2 and it worked.  I'll do a PR.

**Comment by jmiller76** [comment]
actually, it looks like removing the www did the trick by itself.

**Comment by Vitallium** [comment]
Fixed in 276aa35
