### ISSUE TITLE
Repeating table headers on each HTML page

### ISSUE THREAD

**Issue by waghanza** [ariya/phantomjs#13193]
Hi,

I use `shrimp` (rails wrapper), to generate a _PDF_ file

I have a very long  html table (on several pages).

Unfortunately, the table header ((**thead**) does not repeat on each page, event if I force it (I think)

``` css
thead {
  display: table-header-group;
}
```

Has anyone experiencing this issue ?

I could not find any clue to repeat table header during my web research.

Regards,

PS : Some infos of my **compiled** phantomjs version install on a `debian 7.8`

```
 require('system').os        
{
   "architecture": "64bit",
   "name": "linux",
   "release": "3.2.0-4-amd64",
   "version": "unknown"
}
```

**Comment by Llorx** [comment]
What's the status on this?
