### ISSUE TITLE
Cannot access custom headers from Phantom

### ISSUE THREAD

**Issue by kherrmann** [ariya/phantomjs#13200]
Hello, 

I'm trying to access the Location response header of an $http.post() request made from angular.js, which works fine in the browser but fails in phantom (used via prerender). 

I've added the following debug code to my script:

```
console.log('Response: ' + angular.toJson(data));
console.log('Location: ' + data.headers('location'));
console.log('Server: ' + data.headers('server'));
```

Both browser and phantom serialize the response the first line like this:

```
Response: {"data":"","status":200,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"(...)","data":"","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"OK"}
```

...so without any location header. However subsequent logs are for the _browser_

```
[Log] Location: http://google.com#access_token=wLUvy0wsj8feDkE6JnMI2BpZov80cPXy&expires_in=3600&scope= (anon-auth-service.js, line 44)
[Log] Server: Jetty(9.2.10.v20150310) (anon-auth-service.js, line 45)
```

and in _Phantom_

```
Location: null
Server: null
```

CORS headers are set properly - here's the output of the same request with curl -i:

```
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, PUT, POST, DELETE
Access-Control-Allow-Headers: origin, x-requested-with, accept, content-type, authorization, x-dynatrace, accept-language, content-language, hybris-languages, hybris-currency
Access-Control-Expose-Headers: content-type, content-length, content-location, content-disposition, x-dynatrace, hybris-count, warning, link, location
Access-Control-Max-Age: 3628800
location: (...)
server: Jetty(9.2.10.v20150310)
content-type: text/plain; charset=utf-8
Date: Fri, 01 May 2015 09:22:51 GMT
Connection: keep-alive
Transfer-Encoding: chunked
```

Could it be that phantom js ignores _Access-Control-Expose-Headers_ and just gives me the simple headers? If so, is that a bug, or desired behavior?

**Comment by hagemt** [comment]
I'm also seeing this in PhantomJS 1.9.17; I've also confirmed that Access-Control-Expose-Headers names the header that we're interested in obtaining via XHR.getResponseHeader.

Looks like a newer PhantomJS version (2.x?) adds logic to expose headers as per CORS:
https://github.com/ariya/phantomjs/blob/6897baae33bf8648ceb2667da850c3609cd8b11f/src/qt/qtwebkit/Source/WebCore/xml/XMLHttpRequest.cpp#L1044

**Comment by ganemone** [comment]
+1

**Comment by james075** [comment]
+1

**Comment by thierry00** [comment]
+1

**Comment by erkobridee** [comment]
+1
