### ISSUE TITLE
PhantomJS status 'fail' for CSS file

### ISSUE THREAD

**Issue by yogeshugam** [ariya/phantomjs#13206]
I am getting Status=fail when requesting this CSS file

PhantomJS version = 2.0.0
Link : http://www.nfm.com/Content/MainMasterCss_C4BA203F2F5805AA4E787B1466B7F298.css

Even debugging not helping much.

```
console.log('Loading a web page');
var page = require('webpage').create();
var url = 'http://www.nfm.com/Content/MainMasterCss_C4BA203F2F5805AA4E787B1466B7F298.css';
page.open(url, function (status) {
   console.log(status);
   page.render('sample.jpg');
   phantom.exit();
});
```

**Comment by Vitallium** [comment]
PhantomJS doesn't support any content except HTML (XML). You can't open non-HTML page directly.

Duplicate. Please see #11501 #10695

**Comment by yogeshugam** [comment]
I am trying to load an HTML and generate JPG from it.

This CSS file is not loading in PhantomJS and thus i am getting distorted JPG.

But same html source loads correct in brower.

**Comment by Vitallium** [comment]
@yogeshugam you can get the reason why your CSS file didn't load by using [onResourceError](http://phantomjs.org/api/webpage/handler/on-resource-error.html) callback

**Comment by yogeshugam** [comment]
no resourceError.id  is generated
