### ISSUE TITLE
PhantomJS 2.0 cannot write data to a file with extension '.json'

### ISSUE THREAD

**Issue by dhwaneetbhatt** [ariya/phantomjs#13203]
var data = page.evaluate(function() {
            return document.querySelector('.export-json pre').innerHTML;
        });
        console.log(JSON.stringify(data));
        var fs = require('fs');
        fs.write(args.tmpImgDir + 'file.json', data, 'w');

The file is present at the location but it is 0 bytes and contains nothing.

It works for the extensions '.txt' and also other extensions like '.jsn', '.jso' etc (and many other random extensions) but does not work for '.json'.

OS: Windows 8.1 64 bit
Version: PhantomJS 2

**Comment by shivanraptor** [comment]
unable to replicate with PhantomJS v2.1.1. 
Note that you should write your `fs.write()` line as :

    fs.write(args.tmpImgDir + 'file.json', JSON.stringify(data), 'w');

**Comment by dhwaneetbhatt** [comment]
@shivanraptor Good news then. This got fixed in 2.1.1. I could reproduce it in 2.0, I upgraded to 2.1.1 and got fixed too. Thanks.
