### ISSUE TITLE
stdin.readLine hangs indefinitely even when the pipe is closed

### ISSUE THREAD

**Issue by madelson** [ariya/phantomjs#13207]
I have .NET process that communicates with Phantom via stdin and stdout. When the .NET process dies, Phantom's call to system.stdin.readLine() hangs forever even when the other end of the pipe closes (read(1) seems to have the same behavior). Ideally, it would return null or throw so that phantom could unblock itself in such cases.

**Comment by jmiller76** [comment]
This sounds like the behavior that I would expect.  I don't think there is any process to police the relationship between the two.   

You may want to look at Selenium (www.seleniumhq.org) the C# binding is very friendly.  ExecutePhantomJS and ExecuteScript work for my use cases to communicate with an open phantom, and harnesses are there for the command line startup options also,

Is your processes crashing or closing controlled.  you could always call process.kill if you are using System.Diagnostics.Process.

Is the suggestion that there be a timeout added to the console to wait for a command? (or that there is one and it doesn't work?)  I wonder if you could create a watchdog event to call phaton.exit().

**Comment by madelson** [comment]
@jmiller76 thanks for the response

*This sounds like the behavior that I would expect. I don't think there is any process to police the relationship between the two.*

I guess my expectation comes from the fact that C# to C# IPC has this behavior.

*Is your processes crashing or closing controlled. you could always call process.kill if you are using System.Diagnostics.Process.*

We are indeed using this as a fallback. However, it is quite difficult (if not impossible) to guarantee that if the C# process crashes/shuts down unexpectedly that we will get the opportunity to call Kill() on all phantom child processes.

*Is the suggestion that there be a timeout added to the console to wait for a command? (or that there is one and it doesn't work?) I wonder if you could create a watchdog event to call phaton.exit().*

I don't think creating a watchdog event will work, since my undrstanding is that phantom is single-threaded and stdin.readLine() is blocking, so no events fire while waiting for the read. Please correct me if I'm wrong about this, but simple examples seem to prove it out. If the API were to change, I'd love a non-blocking option for readLine (e. g. a standard async IO function with a callback). This would allow for a separate timer loop that could (if the API is available in phantom) watch for the demise of the parent process.

I'll take a look at Selenium, but I'm concerned that this will add additional overhead. We've also had some bad experiences with the Selenium C# driver in the past (we use it for testing purposes), so I'm a bit skeptical and would prefer a pure Phantom solution.

**Comment by jmiller76** [comment]
Is this the same as #10980 ?

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://edupeet.com/guidance.php?828>

 

klaus@hebsgaard.dk
