### ISSUE TITLE
Executing phantomjs on Mac OSX Yosemite exit with code 9

### ISSUE THREAD

**Issue by dudefrommangalore** [ariya/phantomjs#13212]
Trying to run the executable from the phantomjs binary distribution for Mac OSX. It exit with code 9.

**Comment by troychmieleski** [comment]
Take a look at #12974 or #12900.

I was able to run phantomjs on 10.10.3 after running the following according to the comments in the referenced issues.

'''
brew install upx
upx -d bin/phantomjs
'''

**Comment by Vitallium** [comment]
So, UPX is broken for 2 platforms: OS X and Windows. I think there is something related to Qt

**Comment by DimitryDushkin** [comment]
Maybe `upx` binaries for all before publishing?

**Comment by ariya** [comment]
Search this bug tracker, it's a know problem and will be solved with the upcoming version 2.1.
