### ISSUE TITLE
sendKeys to non-input element.

### ISSUE THREAD

**Issue by antony** [ariya/phantomjs#13213]
I've noticed a problem with PhantomJS trying to use sendKeys when the target is not an input element. It seems to be trying to read the 'value' property of whatever element you send keys to, which non-inputs don't have, and this causes the request to fail.

My specific use case is this, but it applies to a variety of wysiwyg editors:

```
http://summernote.org/#/
```

You notice that in order to write text to it, you simply hit the empty area and start typing. Unfortunately that empty area is a div, not an input.

The error which results is a bit cryptic:

```
rg.openqa.selenium.WebDriverException: Error Message => ''undefined' is not an object (evaluating 'a.value.length')'
 caused by Request => {"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"150","Content-Type":"application/json; charset=utf-8","Host":"localhost:2565","User-Agent":"Apache-HttpClient/4.3.6 (java 1.5)"},"httpVersion":"1.1","method":"POST","post":"{\"id\":\":wdc:1431121777071\",\"value\":[\"Proin lorem ligula, mattis ut aliquet sed, convallis eu sapien. Aliquam condimentum aliquet dolor non dapibus.\"]}","url":"/value","urlParsed":{"anchor":"","query":"","file":"value","directory":"/","path":"/value","relative":"/value","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/value","queryKey":{},"chunks":["value"]},"urlOriginal":"/session/85682a40-f5cb-11e4-b939-db3a397f2d6a/element/%3Awdc%3A1431121777071/value"}
Command duration or timeout: 1.21 seconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'devolve', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-31-generic', java.version: '1.8.0_40-internal'
Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=false, databaseEnabled=false, version=1.9.0, platform=LINUX, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, acceptSslCerts=false, driverVersion=1.0.3, locationContextEnabled=false, webStorageEnabled=false, browserName=phantomjs, takesScreenshot=true, driverName=ghostdriver, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 85682a40-f5cb-11e4-b939-db3a397f2d6a
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
    at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:89)
    at geb.navigator.NonEmptyNavigator.leftShift_closure30(NonEmptyNavigator.groovy:448)
    at groovy.lang.Closure.call(Closure.java:423)
    at groovy.lang.Closure.call(Closure.java:439)
    at geb.navigator.NonEmptyNavigator.leftShift(NonEmptyNavigator.groovy:447)
    at geb.content.TemplateDerivedPageContent.leftShift(TemplateDerivedPageContent.groovy:27)
    at pkg.XyzExampleSpec.User does a certain thing(XyzExampleSpec.groovy:35)
```

In other browsers this works fine.

My current workaround is to set the contents of 'note-editable' using jquery's .html method. But it's not ideal.

I'm using version 1.9.0 as it is the latest Ubuntu packaged version, and 2.x doesn't seem to play well with selenium yet, apologies if this issue has been fixed.

**Comment by tproenca** [comment]
Same problem here

**Comment by Accagain2014** [comment]
Same problem here

**Comment by clns** [comment]
With phantomjs 2.1.1 this is still an issue.

**Comment by MikeDevice** [comment]
Same here. Have anyone found a workaround?

**Comment by antony** [comment]
I didn't find a workaround, sadly. I switched to Chrome, it's the same speed, so I don't really bother with PhantomJS any more. Whilst a bit dramatic, it might be a viable option for some people, since it was one of a number of issues.

**Comment by jesg** [comment]
fwiw this looks related to some of the selenium test failures

```text
org.openqa.selenium.ContentEditableTest#testShouldBeAbleToTypeIntoEmptyContentEditableElement
org.openqa.selenium.ContentEditableTest#testTypingIntoAnIFrameWithContentEditableOrDesignModeSet
org.openqa.selenium.ContentEditableTest#testShouldBeAbleToTypeIntoContentEditableElementWithExistingValue
org.openqa.selenium.ContentEditableTest#testNonPrintableCharactersShouldWorkWithContentEditableOrDesignModeSet
org.openqa.selenium.ContentEditableTest#testShouldBeAbleToTypeIntoTinyMCE
org.openqa.selenium.ContentEditableTest#testShouldAppendToTinyMCE
```
the selenium tests have the comment `Safari: cannot type on contentEditable with synthetic events` so this is probably an issue upstream.  unfortunately we are unable to fix this in ghostdriver.

@MikeDevice you can work around this by using the javascipt api for the html WYSIWYG html editor.  both [ckeditor](http://ckeditor.com/) and [tinymce](https://www.tinymce.com/) have javascript apis.

**Comment by malthejorgensen** [comment]
We had this problem with [Quill](http://quilljs.com/) and solved it by having Selenium click the editor input field first.

**Comment by jesg** [comment]
fwiw i have a [fix](https://github.com/jesg/ghostdriver/commit/d37f6e9cfd5ae713c6bb7d7ee25a222950f86f21) for this issue.  you need to send a native click to the content editable element.  this element is often in an iframe so you have to calculate these coordinates with the iframes offset.

**Comment by LiuYangElephant** [comment]
I have sent a native click to the content editable element, while it doesn't work as well.

**Comment by KokaChernov** [comment]
Click() before SendKeys() worked for me
