### ISSUE TITLE
--disk-cache on windows 8 causes crash

### ISSUE THREAD

**Issue by hnry** [ariya/phantomjs#13225]
On a long running script phantomjs  2.0 (few minutes) will crash for me with disk cache enabled.

Not true when disabled, I had my script running without disk cache for awhile and decided to use it and it started crashing.

The crash error is a thread exception. I don't know if I will have the time to post a reproducible script... but generally all my script does is continuously visits sites with high media content.

Having --max-disk-cache set doesn't matter it.

**Comment by lovebear** [comment]
An update to this, on Mac OS X Yosemite with the same command flags to phantomjs and the same script, I am getting no crash.
