### ISSUE TITLE
PhantomJS 2.0.0 shows black stroke for svg rect with "stroke=null"

### ISSUE THREAD

**Issue by luanshixia** [ariya/phantomjs#13222]
With `stroke=null` set the stroke should be invisible, but a thick black stroke is observed. This issue is not seen in PhantomJS 1.9.8, nor in a Chrome browser.

**Comment by jefflembeck** [comment]
@luanshixia Have you tried "none" instead of "null"?

http://www.w3.org/TR/SVG/painting.html#SpecifyingPaint

**Comment by luanshixia** [comment]
@jefflembeck That is from the customers' code so I cannot change that. I know `none` is correct, but anyway, `null` is OK in real browsers like IE, FF and Chrome.
