### ISSUE TITLE
trying to build phantomjs and an encounter error :"field float_state has incomplete type google_breakpad::_libc_fpstate struct _libc_fpstate float_state"

### ISSUE THREAD

**Issue by ngundu** [ariya/phantomjs#13233]
error: :"field float_state has incomplete type google_breakpad::_libc_fpstate struct _libc_fpstate float_state"

gcc -v 
xxx@xxx-vm5:~/phantomjs/src$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/home/test/mygcc/libexec/gcc/powerpc64le-linux-gnu/6.0.0/lto-wrapper
Target: powerpc64le-linux-gnu
Configured with: ../src/configure --enable-threads=posix --enable-shared --enable-__cxa_atexit --enable-languages=c,c++,go --enable-secureplt --enable-checking=yes --with-long-double-128 --enable-decimal-float --disable-bootstrap --disable-alsa --disable-multilib --prefix=/home/test/mygcc --build=powerpc64le-linux-gnu --host=powerpc64le-linux-gnu --target=powerpc64le-linux-gnu
Thread model: posix
gcc version 6.0.0 20150513 (experimental) (GCC)

**Comment by Vitallium** [comment]
`Target: powerpc64le-linux-gnu`
We don't support PowerPC officially. Especially with experimental GCC version.

**Comment by ngundu** [comment]
when I tried with gcc version 4.9.1 encountered same error. could you suggest me any work around to fix an error.

**Comment by Vitallium** [comment]
@ngundu make sure you're building against the correct platform. I'm not sure how it exactly called in GCC. It should something like X86 or X86-64.

**Comment by ngundu** [comment]
Hi Vitalliium,

I am trying to build it on X86 machine and here is gcc --verison 

root@v-hj-0582:~/test-phantomjs/phantomjs# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9.1-16ubuntu6' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.1 (Ubuntu 4.9.1-16ubuntu6)


where I got the error when trying to build
breakpad/src/processor/scoped_ptr.h: In member function âvoid google_breakpad::s                                                                                        coped_array<T>::reset(T*)â:
breakpad/src/processor/scoped_ptr.h:168:18: warning: typedef âtype_must_be_compl                                                                                        eteâ locally defined but not used [-Wunused-local-typedefs]
     typedef char type_must_be_complete[sizeof(T)];
                  ^
breakpad/src/processor/scoped_ptr.h: In destructor âgoogle_breakpad::scoped_ptr_                                                                                        malloc<T, FreeProc>::~scoped_ptr_malloc()â:
breakpad/src/processor/scoped_ptr.h:257:18: warning: typedef âtype_must_be_compl                                                                                        eteâ locally defined but not used [-Wunused-local-typedefs]
     typedef char type_must_be_complete[sizeof(T)];
                  ^
breakpad/src/processor/scoped_ptr.h: In member function âvoid google_breakpad::s                                                                                        coped_ptr_malloc<T, FreeProc>::reset(T*)â:
breakpad/src/processor/scoped_ptr.h:262:18: warning: typedef âtype_must_be_compl                                                                                        eteâ locally defined but not used [-Wunused-local-typedefs]
     typedef char type_must_be_complete[sizeof(T)];
