### ISSUE TITLE
Trying to build Phantomjs 2.0 on Ubuntu Server 14.04 

### ISSUE THREAD

**Issue by jeromeslan** [ariya/phantomjs#13246]
Hello

I'm trying to build phantomjs 2.0 on

**Ubuntu Server 14.04 "Trusty Tahr" LTS (64bits)**

with source from 
**phantomjs-2.0.0-source.zip**

For information, i have installed all dependences needed as: 
**build-essential g++ flex bison gperf ruby perl
libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev
libpng-dev libjpeg-dev python**

The build crash with these messages:

g++: internal compiler error: Erreur de segmentation (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.8/README.Bugs for instructions.
make[2]: **\* [.obj/qabstractanimation.o] Erreur 4
make[2]: **\* Attente des tâches non terminées....
g++: internal compiler error: Erreur de segmentation (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.8/README.Bugs for instructions.
make[2]: **\* [.obj/qvariantanimation.o] Erreur 4
g++: internal compiler error: Erreur de segmentation (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.8/README.Bugs for instructions.
make[2]: **\* [.obj/qpropertyanimation.o] Erreur 4
make[2]: quittant le répertoire « /root/phantomjs-2.0.0/src/qt/qtbase/src/corelib »
make[1]: **\* [sub-corelib-make_first] Erreur 2
make[1]: quittant le répertoire « /root/phantomjs-2.0.0/src/qt/qtbase/src »
make: **\* [sub-src-make_first] Erreur 2

i have built it on my local Ubuntu 14.04 (desktop) with the same way without any trouble.

Regards

ps: i try to build the  2.0 on my server because i experienced some issues with version installed with apt-get 
(problems such as polyfill.js errors)

**Comment by Vitallium** [comment]
How much RAM do you have on it? PhantomJS requires at least 4 Gb.

**Comment by jeromeslan** [comment]
@Vitallium 
                    total       used       free     shared    buffers     cached
Mem:          3926       1546       2380          5        108       1134
-/+ buffers/cache:        302       3623
Swap:         1022          0       1022

isn't it enough ?

**Comment by Vitallium** [comment]
@jeromeslan I think no. Qt5 requires more memory to compile in comparison with Qt4.

**Comment by jeromeslan** [comment]
@Vitallium it's really surprising since i released that build on my laptop with no more memory

**Comment by Vitallium** [comment]
@jeromeslan what's your GCC version (both)?

**Comment by jeromeslan** [comment]
On server:
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

On Laptop
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

**Comment by Vitallium** [comment]
Err... That's really strange.

**Comment by jeromeslan** [comment]
I'm trying to upload the compiled version on the server to test but I'm not confident about this experience.

**Comment by Vitallium** [comment]
@jeromeslan if you have the same distro (libraries: GLIBC, icu and etc.), then it will be fine.

**Comment by TommyN84** [comment]
Es tut mir so leid , ich weiß nicht wie das passiert ist 

Send via 5s white

**Comment by jeromeslan** [comment]
@Vitallium indeed it could work but still that build crash is  very strange isn't it ? Thank you for your responses.
@TommyN84 i'm not sure to really understand

**Comment by jeromeslan** [comment]
Just for information, it seems to work fine.

if someone has a suggestion, I'm still interested.

Regards.

**Comment by TommyN84** [comment]
Bitte ich wollte das nicht 😰

Send via 5s white

**Comment by ariya** [comment]
@jeromeslan Is this problem resolved? If not, can you try again per http://phantomjs.org/build.html and make sure you plenty of disk space.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://contentmanagement911.tk/holy.php?f>

 

klaus@hebsgaard.dk

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://agn-inter.com/mount.php?l>

 

klaus@hebsgaard.dk
