### ISSUE TITLE
v2 screenshots are broken?

### ISSUE THREAD

**Issue by Kazako** [ariya/phantomjs#13240]
I've an issue with rendering screenshots, I don't know if this is just for me,
This is for twitter / facebook, at resolution: 1440 x 900 , zoomfactor of 1, --web-security=no,  --ignore-ssl-errors=yes
It is almost the same for v2.0.0 and v2.0.1-development 
Also, I set resource timeout to 60 seconds, and I wait 3 seconds after 'success' event of open function for the page to fully load

the box is centos v6.6 x64 , uname -a : Linux auto.hostname.com 2.6.32-042stab092.3 #1 SMP Sun Jul 20 13:27:24 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux

![httpfacebookcom_1440x900](https://cloud.githubusercontent.com/assets/11763042/7663004/7099c2bc-fb6c-11e4-8be0-4e9baeb2863c.png)

![httptwittercom_1440x900](https://cloud.githubusercontent.com/assets/11763042/7662989/387a511c-fb6c-11e4-9729-e27de586b73b.png)

**Comment by Vitallium** [comment]
You should install fontconfig library or check your connection.

**Comment by Kazako** [comment]
It was a font issue. My centos didn't have any fonts installed. 
Thank you.
