### ISSUE TITLE
seg fault phantomjs

### ISSUE THREAD

**Issue by scavengineer** [ariya/phantomjs#13244]
consistently, something in this one url crashes phantomjs:

~/phantomjs/bin/phantomjs --ignore-ssl-errors=true ~/render_multi_url.js a-clock.ru
PhantomJS has crashed. Please read the crash reporting guide at
http://phantomjs.org/crash-reporting.html and file a bug report at
https://github.com/ariya/phantomjs/issues/new.
Please attach the crash dump file:
  /tmp/709e38e0-fa67-dcba-424490fc-048289fe.dmp
Segmentation fault
[tom@pox ~]$ 

![phjsdumpfilerenamedto_png](https://cloud.githubusercontent.com/assets/12503345/7691547/f9e13396-fd80-11e4-8cf5-f299645819f6.png)

the attached link is a dump file renamed to be a png.  sorry, I couldn't see a different way to do it.

**Comment by Vitallium** [comment]
PhantomJS version?

**Comment by scavengineer** [comment]
2.0.1-development. compiled from source on Scientific Linux 6.6 (Carbon).
Basically Centos6.

On Tue, May 19, 2015 at 2:23 AM, Vitaly Slobodin <notifications@github.com>
wrote:

> PhantomJS version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ariya/phantomjs/issues/13244#issuecomment-103378265>.
>



-- 
What we obtain too cheap, we esteem too lightly; it is dearness only that
gives everything its value. - Thomas Payne, 1776

**Comment by scavengineer** [comment]
also these do the same thing:

535tovarov.ru
ayonarent.ru
biiz-trrading-credit.ru
blockcentre.ru
choko15.ru
davottak-cms.ru
dgywbz.com
fensterhouse.ru
golden-dragonsnz.ru
iw2rmb.ru
luzhouhuazhuang.com
satinflower.ru
usa-ksb55.ru

On Tue, May 19, 2015 at 11:09 AM, tweakin on technology <
scavengineer@gmail.com> wrote:

> 2.0.1-development. compiled from source on Scientific Linux 6.6 (Carbon).
>   Basically Centos6.
>
> On Tue, May 19, 2015 at 2:23 AM, Vitaly Slobodin <notifications@github.com
> > wrote:
>
>> PhantomJS version?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ariya/phantomjs/issues/13244#issuecomment-103378265>.
>>
>
>
>
> --
> What we obtain too cheap, we esteem too lightly; it is dearness only that
> gives everything its value. - Thomas Payne, 1776
>



-- 
What we obtain too cheap, we esteem too lightly; it is dearness only that
gives everything its value. - Thomas Payne, 1776

**Comment by yali25** [comment]
Try this fix it may help you: #13167
