### ISSUE TITLE
should onLoadFinished status be success for http errors?

### ISSUE THREAD

**Issue by bughit** [ariya/phantomjs#13257]

**Comment by Vitallium** [comment]
Provide more info please. And I think, it looks like a discussion, not an issue.

**Comment by bughit** [comment]
onLoadFinished status arg is "success" for error http status codes.  Its only "fail" for lower level tcp, dns errors.  Was not clear if that's intentional.

Also it would be good to be passed a resourceError if there is a any kind of error, same as onResourceError, which gets called for low level as well http level errors.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://thewellusa.net/worker.php?gt>

 

klaus@hebsgaard.dk
