### ISSUE TITLE
.injectJs() returns undefined when docs say it should return true or false.

### ISSUE THREAD

**Issue by RavenHursT** [ariya/phantomjs#13258]
I have the following in my code:

```javascript
phantom.createPage(function(page){
            page.onCallback = function(data) {
                console.log("ph callback: ", data);
            };
            page.open(req.query.testUrl, function(status){
                if(status !== 'success'){
                    page.close();
                    res.status(500)
                        .send('Page "' + testUrl + '" could not be loaded.')
                        .end();
                    return;
                }

                var result = page.injectJs('lib/my-test-script.js');
                console.log('injectJS: ', result);

                page.evaluate(function(){
                    window.callPhantom(window.mocha.constructor.name);
                }, function(){
                    console.log('finished');
                    page.close();

                    res.json({status: status});
                    res.end();
                });
            });
        });
```

And ```console.log('injectJS: ', result);``` is outputting "injectJS: undefined", not explicitly ```false``` as the docs say here:

http://phantomjs.org/api/webpage/method/inject-js.html

Furthermore, I've verified that my-test-script.js is there using ```fs.readDir()```, yet it appears that my code isn't being injected at all, not to mention, I never get the console output from ```page.onCallback()```.

I'm completely lost at this point.  Any help would be appreciated.

**Comment by Vitallium** [comment]
Try to launch PhantomJS with debug output `--debug=yes` To see more informational messages.

**Comment by RavenHursT** [comment]
Turns out I made a dumb mistake.. I'm using the phantomjs-node bridge and I'm not calling it correctly.

Mah bad.  Closing issue.
