### ISSUE TITLE
Build from source Error (2.0)

### ISSUE THREAD

**Issue by thielCole** [ariya/phantomjs#13268]
Building phantojs 2.0 from source on CentOS release 5.11 inside AWS

I error out in two ways,

Encountered 5 configuration warning(s):

 ! QtQuick module not found, QML APIs will not be built
 ! Missing GStreamer or QtMultimedia, disabling HTML5 media element support
 ! Missing QtWidgets module, disabling WebKit1
 ! Missing QtTest module, disabling DumpRenderTree, WebKitTestRunner and tests
 ! QtWebKitQml will not be build. It is not supported with static linking

The WebKit build was disabled for the following reasons: 
    * QtWebKit depends on gui for building. 

make: Nothing to be done for `first'.

Building main PhantomJS application...

cd src/ && ( test -e Makefile.phantomjs || /ebs/tmp/phantomjs/src/qt/qtbase/bin/qmake /ebs/tmp/phantomjs/src/phantomjs.pro -o Makefile.phantomjs ) && make -f Makefile.phantomjs 
Project ERROR: Unknown module(s) in QT: webkitwidgets network gui
make: *** [sub-src-phantomjs-pro-make_first-ordered] Error 3

**Comment by Vitallium** [comment]
> QtWebKit depends on gui for building.

Looks like your Qt build was unsuccessful.
Post the full build log please.

**Comment by thielCole** [comment]
DEFAULT_INCDIRS="/usr/include/c++/4.1.2
/usr/include/c++/4.1.2/x86_64-redhat-linux
/usr/include/c++/4.1.2/backward
/usr/local/include
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/include
/usr/include
"
DEFAULT_LIBDIRS="/lib
/usr/lib"
<srcbase> = /ebs/tmp/phantomjs/src/qt/qtbase 
<outbase> = /ebs/tmp/phantomjs/src/qt/qtbase 

... 

main.cpp:42:25: error: sys/eventfd.h: No such file or directory
main.cpp: In function ‘int main()’:
main.cpp:46: error: ‘eventfd_t’ was not declared in this scope
main.cpp:46: error: expected `;' before ‘value’
main.cpp:47: error: ‘EFD_CLOEXEC’ was not declared in this scope
main.cpp:47: error: ‘eventfd’ was not declared in this scope
main.cpp:48: error: ‘value’ was not declared in this scope
main.cpp:48: error: ‘eventfd_read’ was not declared in this scope
main.cpp:49: error: ‘eventfd_write’ was not declared in this scope
gmake: *** [main.o] Error 1
eventfd disabled.
IPv6 interface name auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o ipv6ifname.o ipv6ifname.cpp
g++ -Wl,-O1 -o ipv6ifname ipv6ifname.o    
IPv6 interface name enabled.
getifaddrs auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o getifaddrs.o getifaddrs.cpp
g++ -Wl,-O1 -o getifaddrs getifaddrs.o    
getifaddrs enabled.
OpenSSL auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o openssl.o openssl.cpp
g++ -Wl,-O1 -o openssl openssl.o    
OpenSSL enabled.

WARNING: Using static linking will disable the WebKit module.

Testing size of pointers ... (/ebs/tmp/phantomjs/src/qt/qtbase/mkspecs/linux-g++ yes /ebs/tmp/phantomjs/src/qt/qtbase /ebs/tmp/phantomjs/src/qt/qtbase)
rm -f ptrsizetest.o
rm -f *~ core *.core
g++ -c -pipe -g -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o ptrsizetest.o ptrsizetest.cpp
g++  -o ptrsizetest ptrsizetest.o    
Pointer size: 8

   Configure summary

Build type:    linux-g++ (x86_64, CPU features: mmx sse sse2)
Platform notes:

            - Also available for Linux: linux-kcc linux-icc linux-cxx
        
qmake vars .......... styles += mac fusion windows DEFINES += QT_NO_MTDEV QMAKE_CFLAGS_FONTCONFIG =  QMAKE_LIBS_FONTCONFIG = -lfreetype -lfontconfig DEFINES += QT_NO_LIBUDEV DEFINES += QT_NO_EVDEV DEFINES +=  "QT_NO_GRAPHICSVIEW" "QT_NO_GRAPHICSEFFECT" "QT_NO_STYLESHEET" "QT_NO_STYLE_CDE" "QT_NO_STYLE_CLEANLOOKS" "QT_NO_STYLE_MOTIF" "QT_NO_STYLE_PLASTIQUE" sql-drivers =  sqlite sql-plugins =  qmake switches ......... 

Build options:
  Configuration .......... accessibility audio-backend clock-gettime clock-monotonic concurrent fontconfig full-config getaddrinfo getifaddrs gif harfbuzz iconv icu inotify ipv6ifname jpeg large-config largefile medium-config minimal-config mremap no-pkg-config openssl-linked pcre png posix_fallocate precompile_header qpa qpa reduce_exports release rpath small-config sse2 sse3 ssse3 static system-freetype system-jpeg system-png system-zlib 
  Build parts ............ libs
  Mode ................... release
  Using C++11 ............ no
  Using PCH .............. yes
  Target compiler supports:
    SSE2/SSE3/SSSE3 ...... yes/yes/yes
    SSE4.1/SSE4.2 ........ no/no
    AVX/AVX2 ............. no/no

Qt modules and options:
  Qt D-Bus ............... no
  Qt Concurrent .......... yes
  Qt GUI ................. yes
  Qt Widgets ............. yes
  Large File ............. yes
  QML debugging .......... no
  Use system proxies ..... no

Support enabled for:
  Accessibility .......... yes
  ALSA ................... no
  CUPS ................... no
  Evdev .................. no
  FontConfig ............. yes
  FreeType ............... yes (system library)
  Glib ................... no
  GTK theme .............. no
  HarfBuzz ............... qt
  Iconv .................. yes
  ICU .................... yes
  Image formats: 
    GIF .................. yes (in QtGui, using bundled copy)
    JPEG ................. yes (in QtGui, using system library)
    PNG .................. yes (in QtGui, using system library)
  journald ............... no
  mtdev .................. no
  Networking: 
    getaddrinfo .......... yes
    getifaddrs ........... yes
    IPv6 ifname .......... yes
    OpenSSL .............. yes (linked to the libraries)
  NIS .................... no
  OpenGL / OpenVG: 
    EGL .................. no
    OpenGL ............... no
    OpenVG ............... no
  PCRE ................... yes (bundled copy)
  pkg-config ............. no 
  PulseAudio ............. no
  QPA backends: 
    DirectFB ............. no
    EGLFS ................ no
    KMS .................. no
    LinuxFB .............. no
    XCB .................. no
  Session management ..... no
  SQL drivers: 
    DB2 .................. no
    InterBase ............ 
    MySQL ................ 
    OCI .................. no
    ODBC ................. 
    PostgreSQL ........... 
    SQLite 2 ............. no
    SQLite ............... qt-qt
    TDS .................. no
  udev ................... no
  xkbcommon .............. no
  zlib ................... yes (system library)


WARNING: Using static linking will disable the use of dynamically
loaded plugins. Make sure to import all needed static plugins,
or compile needed modules into the library.


NOTE: When linking against OpenSSL, you can override the default
library names through OPENSSL_LIBS.
For example:
    OPENSSL_LIBS='-L/opt/ssl/lib -lssl -lcrypto' ./configure -openssl-linked

Info: creating cache file /ebs/tmp/phantomjs/src/qt/qtbase/.qmake.cache

Qt is now configured for building. Just run 'gmake'.
Once everything is built, Qt is installed.
You should not run 'gmake install'.

Prior to reconfiguration, make sure you remove any leftovers from
the previous build.

...

tools/qtimezoneprivate_icu.cpp: In function ‘bool ucalOffsetsAtTime(void**, qint64, int*, int*)’:
tools/qtimezoneprivate_icu.cpp:153: error: ‘ucal_clone’ was not declared in this scope
tools/qtimezoneprivate_icu.cpp: In copy constructor ‘QIcuTimeZonePrivate::QIcuTimeZonePrivate(const QIcuTimeZonePrivate&)’:
tools/qtimezoneprivate_icu.cpp:293: error: ‘ucal_clone’ was not declared in this scope
tools/qtimezoneprivate_icu.cpp: In member function ‘virtual bool QIcuTimeZonePrivate::isDaylightTime(qint64) const’:
tools/qtimezoneprivate_icu.cpp:386: error: ‘ucal_clone’ was not declared in this scope
make[2]: *** [.obj/qtimezoneprivate_icu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/ebs/tmp/phantomjs/src/qt/qtbase/src/corelib'
make[1]: *** [sub-corelib-make_first] Error 2
make[1]: Leaving directory `/ebs/tmp/phantomjs/src/qt/qtbase/src'
make: *** [sub-src-make_first] Error 2

Building QtWebkit...

Info: creating cache file /ebs/tmp/phantomjs/src/qt/qtwebkit/.qmake.cache

Running configure tests...

Checking for fontconfig... no
Checking for gccdepends... yes
Checking for glx... no
Checking for gnuld... yes
Checking for icu... yes
Checking for leveldb... no
Checking for libwebp... no
Checking for libXcomposite... no
Checking for libxml2... no
Checking for libXrender... no
Checking for libxslt... no
Checking for libzlib... yes

Final configuration:

Build ......................... 
Configuration ................. debug/release
All-in-one files .............. no
GNUmake ....................... yes
Static libs as shared ......... no
Static libs as thin archives .. no
Production build .............. yes

Have .......................... qttestsupport
Use ........................... tiled_backing_store cross_platform_context_menus zlib libjpeg libpng leveldb
Features ...................... fast_mobile_scrolling gesture_events inspector_server legacy_viewport_adaption smooth_scrolling subpixel_layout touch_adjustment view_mode_css_media plugin_architecture_unsupported

3D Rendering .................. yes
Accelerated 2D Canvas ......... no
Battery Status ................ no
Blob .......................... yes
Canvas Path ................... yes
CanvasProxy ................... no
Channel Messaging ............. yes
Content Security Policy 1.1 ... no
CSS Device Adaptation ......... no
CSS Exclusions ................ yes
CSS Shapes .................... yes
CSS Filters ................... yes
CSS3 Conditional Rules support (i.e. @supports)  no
CSS3 Text ..................... no
CSS3 Text Line Break .......... no
CSS box-decoration-break ...... yes
CSS image-orientation ......... no
CSS image-resolution .......... no
CSS image-set ................. yes
CSS Regions ................... yes
CSS Shaders ................... no
CSS sticky position ........... yes
CSS Compositing ............... yes
Support for unprefixed CSS animations and transforms  yes
CSS Variable .................. no
Custom Scheme Handler ......... no
Datalist Element .............. yes
Data Transfer Items ........... no
Details Element ............... yes
Device Orientation ............ no
Dialog Element ................ no
Directory Upload .............. no
Expose DOM4 Events constructors  no
Download Attribute ............ yes
File System ................... no
Filters ....................... yes
Font Load Events .............. no
FTP Directory ................. yes
Fullscreen API ................ yes
Gamepad ....................... no
Geolocation ................... no
High DPI Canvas ............... no
Icondatabase .................. yes
Iframe seamless attribute ..... yes
Indexed Database .............. yes
Input Speech .................. no
Input Type Color .............. yes
Input Type Date ............... no
Broken Input Type Datetime .... no
Input Type Datetimelocal ...... no
Input Type Month .............. no
Input Type Time ............... no
Input Type Week ............... no
Inspector ..................... yes
JavaScript Debugger ........... yes
Legacy Notifications .......... yes
Legacy Vendor Prefix .......... yes
Legacy Web Audio .............. no
Link Prefetch ................. yes
MathML ........................ no
Media Capture ................. no
Media Source .................. no
Media Statistics .............. no
Media Stream .................. no
Meter Element ................. yes
MHTML ......................... yes
Microdata ..................... no
Scaled mouse cursor ........... no
Navigator Content Utils ....... no
Netscape Plugin API ........... no
Network Info .................. no
Support for 'X-Content-Type-Options: nosniff'  no
Notifications ................. yes
Orientation Events ............ no
Page Visibility API ........... yes
Performance Timeline .......... no
Progress Element .............. yes
Proximity Events .............. no
Quota ......................... no
Resolution media query ........ yes
Resource Timing ............... no
Request Animation Frame ....... yes
Seccomp Filter sandbox ........ no
Scripted Speech ............... no
Shadow DOM .................... no
Shared Workers ................ yes
SQL Database .................. yes
Style Scoped .................. no
Suid sandbox for linux ........ no
SVG ........................... yes
SVG Fonts ..................... yes
HTMLTemplateElement ........... no
Text Autosizing ............... no
Tiled Backing Store ........... no
Threaded HTML parser .......... no
Touch Events .................. yes
Touch Slider .................. yes
Touch Icon Loading Support .... no
User Timing ................... no
Vibration ..................... no
Video ......................... no
Video Track ................... no
WebGL ......................... no
Web Audio ..................... no
Web Sockets ................... yes
Web Timing .................... yes
Workers ....................... yes
XHR Timeout ................... yes
XSLT .......................... no

Encountered 5 configuration warning(s):

 ! QtQuick module not found, QML APIs will not be built
 ! Missing GStreamer or QtMultimedia, disabling HTML5 media element support
 ! Missing QtWidgets module, disabling WebKit1
 ! Missing QtTest module, disabling DumpRenderTree, WebKitTestRunner and tests
 ! QtWebKitQml will not be build. It is not supported with static linking

The WebKit build was disabled for the following reasons: 
    * QtWebKit depends on gui for building. 

make: Nothing to be done for `first'.

Building main PhantomJS application...

cd src/ && ( test -e Makefile.phantomjs || /ebs/tmp/phantomjs/src/qt/qtbase/bin/qmake /ebs/tmp/phantomjs/src/phantomjs.pro -o Makefile.phantomjs ) && make -f Makefile.phantomjs 
Project ERROR: Unknown module(s) in QT: webkitwidgets network gui
make: *** [sub-src-phantomjs-pro-make_first-ordered] Error 3

**Comment by Vitallium** [comment]
Check version of `icu` library. PhantomJS 2 requires ICU >= 54

**Comment by jmiller76** [comment]
@Vitallium is there a list of what versions are needed for build?  It seems like there are a lot of issues submitted that may be avoided with more info on phantomjs/_posts/documentation/get-started/2000-01-02-build.md

**Comment by Vitallium** [comment]
@jmiller76 requirements are the same as for Qt5. But yes, you're right, we should write them in our build instructions.

**Comment by westfly** [comment]
fix icu,but 
phantomjs-2.0.0/src/qt/qtwebkit/Source/JavaScriptCore/disassembler/udis86/ud_opcode.py", line 115
    '/mod'   : lambda v: '00' if v == '!11' else '01',
