### ISSUE TITLE
PhantomJS 2.0 crash on Win8.1

### ISSUE THREAD

**Issue by mxxcon** [ariya/phantomjs#13261]
Please let me know if you need any additional info to this.
![93f8c24d-cb41-416b-9aaa-4b183bf3599b dmp](https://cloud.githubusercontent.com/assets/847140/7791742/13fec25a-0274-11e5-8832-a33dc446a2d0.png)

**Comment by Vitallium** [comment]
Cannot reproduce it anymore.
