### ISSUE TITLE
Ignores <select field

### ISSUE THREAD

**Issue by Tarang** [ariya/phantomjs#13260]
I'm not sure how to describe this issue:

If I submit a form the `<select` field is ignored. It's quite weird. The odd thing is it is in the `<form`. Jquery's `$('form').serialize()` does not pick it up even though `$('form select').val()` does.

Perhaps I'm doing something wrong? I'm not even sure how to debug this because it happens only on certain websites.

Using: 2.0.0 (development)

**Comment by Vitallium** [comment]
@Tarang could you please provide an example?
