### ISSUE TITLE
Phantomjs 2.0.0 Windows Kerberos / NTLM "HTTP" auth is possible ?

### ISSUE THREAD

**Issue by darkterra** [ariya/phantomjs#13262]
Hello,

After several days of searching and even paused after the question about the following issue: #11037

I have not found how to use Kerberos / NTLM authentication with "HTTP" protocol.
I have a response 401 code error.

Someone should answer ? Knowing that I should not use IE

![image](https://cloud.githubusercontent.com/assets/7060696/7837806/a0a50626-0489-11e5-969d-985cf3a9a95e.png)

**Comment by darkterra** [comment]
Hello everyone,

With WireShark, I tried to "capture" the network packets and look at why my browser (Google Chrome) successfully recovered the page and not PhantomJS.

Attempt to access a URL with PhantomJS 2.0.0 :
![image](https://cloud.githubusercontent.com/assets/7060696/7914756/54488eb2-0879-11e5-85de-f66b6f354c55.png)

Attempt to access a URL with Google Chrome :
![image](https://cloud.githubusercontent.com/assets/7060696/7914815/a5bccc5e-0879-11e5-9295-f41fcfbbf274.png)

I feel that Google Chrome and PhantomJS both receive a code 401, only the browser Google Chrome as early retries with Kerberos / NTLM authentication.


Someone an idea that has Kerberos PhantomJS gives what he expects ?

A parameter ?
Code lines ?

Something ??? ^^


Thank you in advance

**Comment by Vitallium** [comment]
Qt doesn't have support for Kerberos. See https://bugreports.qt.io/browse/QTBUG-1538

**Comment by darkterra** [comment]
@Vitallium Thank you for your reply.

If I understand it is possible to implement an overlay to be compatible with Kerberos / NTLM ?

Anyone know if this " wrapper " already exists , or should I create ?

**Comment by vaishali33** [comment]
You can manipulate request header to send Kerberos token to hit Kerberized web pages from PhantomJS. Using below -
page.customHeaders = {"Authorization": "Negotiate " + [token]};

Use https://docs.oracle.com/javase/7/docs/api/org/ietf/jgss/GSSManager.html and https://docs.oracle.com/javase/7/docs/api/org/ietf/jgss/GSSContext.html to generate Kerberos token.

**Comment by itslittlejohn** [comment]
Try using a proxy for now. cntlm worked for me: http://stackoverflow.com/questions/31209449/cntlm-proxy-with-phantomjs

**Comment by m4c0** [comment]
Can't this use something similar to this NodeJS package? https://github.com/christkv/kerberos
