### ISSUE TITLE
Cookies are shared between each webpage instance

### ISSUE THREAD

**Issue by abozhilov** [ariya/phantomjs#13267]
Per design the cookies are shared between each instance of webpage.create(); Test code: 

```
var webpage = require('webpage');

var page1 = webpage.create();
page1.open('http://localhost/test.php', function () {
    page1.render('test1.jpg');

    page1.open('http://localhost/test.php', function () {
        page1.render('test2.jpg');
    });

    var page2 = webpage.create();
    page2.open('http://localhost/test.php', function () {
        page2.render('test3.jpg');
    });
});
```

_test.php_

```
<body style="background-color: #FFFFFF;">
<?php
    echo isset($_COOKIE["TestCookie"]);
    setcookie("TestCookie", "TestCookie");
?>
</body>
```

With that design, phantomjs breaks concurrent tests, since IMHO each test must start with empty cookie storage. Are you planning to add separate cookie/cache storage for each instance of webpage?

**Comment by dawehner** [comment]
See https://github.com/detro/ghostdriver/issues/170 for an example which talks about that
