### ISSUE TITLE
QFontconfigDatabase::fontEngine crash

### ISSUE THREAD

**Issue by Gvidco** [ariya/phantomjs#13277]
PhantomJS crashes with some websites that may or may not have downloaded font decoding issues.

Example code/website:
```
var webPage = require('webpage');
var page = webPage.create();

page.open('http://giftcardjunkie.net/', function (status) {
  console.log('Status: ' + status);
});
```
phantomjs -v: `2.0.1-development`
Built on ubuntu 14.04 LTS using branch `2.0`

Stack trace from gdb gives:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000001c3b548 in QFontconfigDatabase::fontEngine(QByteArray const&, double, QFont::HintingPreference) ()
```
I would appreciate if you could help me to resolve this issue. Please note that the website used in code is an example and does not belong to me. If required I have a list of other websites that trigger the same error.

**Comment by yali25** [comment]
Maybe this helps you: #13167
