### ISSUE TITLE
Bind for querySelectorAll

### ISSUE THREAD

**Issue by rkusuma** [ariya/phantomjs#13274]
I got this error when running karma test in phantomjs. I already add bind-polyfill.js for phantomjs but it still not working. Any solution?

```
ERROR [karma]: TypeError: 'undefined' is not a function (evaluating 'document.querySelectorAll.bind(document)')
at http://localhost:9876/base/bower_components/materialize/bin/materialize.js?a8dba06400b1ea0562876ad690d94e2ff9a9236e:4
```

**Comment by Vitallium** [comment]
Make sure your polyfill loads before any scripts.

**Comment by rkusuma** [comment]
thanks @Vitallium .. it works.. my bad..
