### ISSUE TITLE
Crash on URL open

### ISSUE THREAD

**Issue by plamzi** [ariya/phantomjs#13289]
Instant crash when opening URL:
https://communities.intel.com/community/tech?forceNoRedirect=true

![196326fb-c0fb-ea0b-28901cba-4984a079 zip](https://cloud.githubusercontent.com/assets/5421384/7904027/141f41a8-07b3-11e5-836a-b46e71691e87.jpg)

**Comment by yali25** [comment]
It looks like a fontEngine problem, check this: #13167

**Comment by plamzi** [comment]
Thanks for the lead. So, we can choose to manually patch it in until it is merged?
