### ISSUE TITLE
No way to specify page range when rendering to PDF

### ISSUE THREAD

**Issue by dbkaplun** [ariya/phantomjs#13288]
Looks like the relevant code is here: https://github.com/ariya/phantomjs/blob/c4df6402d1b044fbcb416d37ca239004e03a5d08/src/webpage.cpp#L1112-L1213

**Comment by dbkaplun** [comment]
`QPrinter` is used in the linked code above, and [`QPrinter::setFromTo`](https://github.com/ariya/phantomjs/blob/48fabe06463460d2fb7026d6df9783216e26265c/src/qt/qtbase/src/printsupport/kernel/qprinter.cpp#L2123-L2131) already exists, so this change should be trivial.

**Comment by matths** [comment]
+1 for that

I have a problem to create PDF files using PhantomJS when it comes to more then ~110 pages. It doesn't crash, but some background-images are missing and some fonts do not render, I only see underscore like characters or nothing. For less then ~110 pages everything works well.

So, when i could choose to print page 0-100 and 100-end, I could work around this bug and try to combine both pdf files later on.
