### ISSUE TITLE
Object.defineProperty behaves differently on PhantomJS 1.9.8

### ISSUE THREAD

**Issue by aicioara** [ariya/phantomjs#13280]
Compared to Chrome, FF, IE9+ (not thoroughly tested on IE10+ though).

Experienced on version `1.9.8`

Sample code

``` javascript
var foo = {};

function setSize(object, size) {
  Object.defineProperty(object, "size", {
    value: size,
    configurable: true,
    writable: false
  });
}

setSize(foo, 2);
console.log(foo.size); // Browser: 2 | PhantomJS: 2

setSize(foo, 3);
console.log(foo.size); // Browser: 3 | PhantomJS: 2
```

**Comment by LeMoussel** [comment]
No differently with this config.

**Version of PhantomJS**
2.0.0

**Expected output**
2
3

**What do you see instead**
2
3

**Operating system**
Windows 7

**Did you use binary PhantomJS or did you compile it from source?**
    Binary

**Comment by aicioara** [comment]
I believe PhantomJS 2.0.0 is not yet available on `npm`?

**Comment by booleanbetrayal** [comment]
Also seeing this
