### ISSUE TITLE
Register 2.0.0 on npm

### ISSUE THREAD

**Issue by jdunck** [ariya/phantomjs#13296]
http://phantomjs.org/download.html lists 2.0 with no caveats, but the [latest version on npm](https://www.npmjs.com/package/phantomjs) is 1.9.17.

Is there a reason it's not listed on npm?

**Comment by aroc** [comment]
:+1:

**Comment by ariya** [comment]
Please track it at https://github.com/Medium/phantomjs/issues/288.
