### ISSUE TITLE
mix-blend-mode support?

### ISSUE THREAD

**Issue by mloenow** [ariya/phantomjs#13290]
Hi,

I've been trying to capture screenshots with `mix-blend-mode` and `background-blend-mode` (and their `-webkit-*` equivalents) on some elements, but without success. Is this currently supported?

Setup: v2.0.0 on OS X 10.10.3.

Thanks

**Comment by petrbrzek** [comment]
Any response on this? :)

**Comment by mintyPT** [comment]
Same here...

**Comment by minhdtb83** [comment]
I have the same request
