### ISSUE TITLE
Phantomjs unable to render page

### ISSUE THREAD

**Issue by surenderthakran** [ariya/phantomjs#13304]
Phantom Version: 2.0.0
OS: Amazon AMI 64-bit

I tried opening this page in phantomjs:
http://webrafter.com/opensource/react-slick

The `body` tag of this page has no html tags in the source, just a couple of javascript inclusions. These javascripts run to add content in the `body`.
But in phantomjs, even after a timeout of 10 seconds after status `success`, `page.content` only returns the source html.

**Comment by scone** [comment]
I cannot recreate this issue. Can you share your javascript that is attempting to render the page?

I was able to successfully render this page using PhantomJS 2.0. See it here: http://phishcheck.me/1774/details

**Comment by checkraiser** [comment]
I use React.js as the view. 
Here's my cucumber with capybara:

    Feature: Crud Todo
    @javascript
    Scenario: Create new todo
      Given I login successfully
      When I fill in the textbox 'Hello World'
      And I click 'Add' button
      Then I could see 'Hello World'

The steps just use click_button to make ajax request. 
This spec passes with selenium using chrome, but fail with phantomjs 2.0.0.

Do you know how to resolve ?

**Comment by muraveill** [comment]
I have the same issue, using PhantomJS 2.1:

index.html:

    <body>      
        <div id="app-container"></div>  
        <div id="footer"></div>
        <script src="scripts/app.js"></script>
        <script type="text/javascript" >
            $(document).ready(function(){
                var container = $("#app-container");
                container.append("<p id='jquery-div'>Text</p>");
            });
        </script>
    </body>

`app.js` renders a simple div #react-div inside of #app-container:

    var TestComponent = React.createClass({
        render: function() {
            return <div id='react-div'>React sucks?</div>;
        }
    });
    ReactDOM.render(<TestComponent />, document.getElementById('app-container'));

Whether I use CasperJS or Selenium with PhantomJS driver, only the hard-coded HTML and the jQuery part are seen by phantom, but all the React stuff is ignored.
