### ISSUE TITLE
PhantomJS default configuration file support

### ISSUE THREAD

**Issue by astefanutti** [ariya/phantomjs#13300]
While this is possible to provide a configuration file with the `--config` option to PhantomJS CLI in order to avoid passing in multiple command-line options, that be an even step further to have a default configuration file convention supported, for example taking into account the `phantomjs,json` file if its present at the root of the working directory.

**Comment by zackw** [comment]
I'm sorry, we're not going to take this change.  It is not safe; scripts will break unpredictably if moved from one directory to another, and malicious programs may be able to use it for privilege escalation.
