### ISSUE TITLE
fix-javascript

### ISSUE THREAD

**Issue by jefleponot** [ariya/phantomjs#13313]
Javascript modules error are matched with "jshint" (63) and "eslint" (649).

examples:
Missing semicolon
Use '===' to compare with 'null'
Line breaking error 'break'
variable is already defined
Strings must use doublequote
Expected literal to be on the right side of ===
Extra space before value
...

just a fix to have rigth syntax

**Comment by LeMoussel** [comment]
With [JSLint](http://www.jslint.com/) I got this warning
```javascript
    Bad option 'sloppy'.
    /*jslint sloppy: true, nomen: true */
```

**Comment by jefleponot** [comment]
HI LeMoussel,

I haven't add this line.
