### ISSUE TITLE
"Can't find variable: Intl" when injecting polyfill from compiled script

### ISSUE THREAD

**Issue by yamalight** [ariya/phantomjs#13318]
So, we have an single page application that's compiled using webpack. It uses Intl for localisation and to fix errors in older browser (and in webkit), we're injecting the polyfill from within the code at entry point, like so:
```js
// i18n polyfill
if (!global.Intl) {
    global.Intl = require('intl');
}
```
That works perfectly fine while running the app in all browsers and in our current test environments that use jsdom. But PhantomJS fails for some reason while throwing reference error: `ReferenceError: Can't find variable: Intl`
I'd found two workarounds:
1. Inject the polyfill on page init (e.g. `page.onInitialized = function() { page.injectJs('Intl.min.js') }`)
2. Add polyfill into page head as `<script>` tag

But that seems like a bug that's need to be fixed to me. Or as I doing something wrong here?

**Comment by Vitallium** [comment]
PhantomJS version? If you use 1.9.x, then you might be affected by unimplemented `Function.prototype.bind` API.

**Comment by yamalight** [comment]
@Vitallium oh, sorry, should've mentioned that from the beginning - 2.0.0, installed it from brew

**Comment by Vitallium** [comment]
@yamalight so, I suppose your code:
````
// i18n polyfill
if (!global.Intl) {
    global.Intl = require('intl');
}
````
runs in the browser in the page's context, right? Sorry, I don't have experience with WebPack.
If so, then I think PhantomJS works weird on `require` function.

About workarounds: 
Both ways are fine.

**Comment by yamalight** [comment]
@Vitallium yes, it runs in browser. `require()` there would be changed to webpack's require replacement.
I can prepare a small project to reproduce the issue if that can help

**Comment by Vitallium** [comment]
@yamalight yes, a minimal example will definitely help! Thanks!

**Comment by yamalight** [comment]
@Vitallium okay, I feed very silly now. That was my own mistake - I'd used ES6 import statements below Intl polyfill thinking that it'd be OK. After compilation, imports got hoisted and polyfill was included AFTER the code that's used it :\
The only thing that's still confusing for me is - why did that code worked fine in all browsers? That's a bit strange. But that's definitely not a phantom fault, so I'm going to close this issue.
Sorry and thanks for your time!
