### ISSUE TITLE
phantomjs Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by minimatronik** [ariya/phantomjs#13319]
Hello.
I try run selenium + phantomjs(Ghost.py, python phantomjs) on linux hosting(not vps \ vds), and it does not have ssh.
When i run script on cron, i get error:
raise WebDriverException("Unable to start phantomjs with ghostdriver.", e)
selenium.common.exceptions.WebDriverException: Message: Unable to start phantomjs with ghostdriver.
Screenshot: available via screen

I try manually run phantomjs(from cron) and get this error:
phantomjs: 1: Syntax error: "(" unexpected

I write full path to phantomjs in script.
Can You help me? What the problem?

**Comment by jarederaj** [comment]
I resolved this issue by uninstalling and reinstalling phantomjs-prebuilt:

`npm uninstall phantomjs-prebuilt`

then:

`npm install phantomjs-prebuilt`
