### ISSUE TITLE
Unable to compile debug

### ISSUE THREAD

**Issue by serl** [ariya/phantomjs#13322]
I compiled from source version 2.0.0. It give me segfault on exit (not always, but seems deterministic). As written [here](http://phantomjs.org/crash-reporting.html), I tried to do:

    $ CFLAGS=-g CXXFLAGS=-g ./build.sh --qt-config '-webkit-debug' --qmake-args "QMAKE_CFLAGS=-g QMAKE_CXXFLAGS=-g"
    ----------------------------------------
                   WARNING
    ----------------------------------------

    Building PhantomJS from source takes a very long time, anywhere from 30
    minutes to several hours (depending on the machine configuration).
    We recommend you use the premade binary packages on supported operating
    systems.

    For details, please go the the web site: http://phantomjs.org/download.html.

    Do you want to continue (y/n)?
    y

    System architecture... (Linux 3.16.0-39-generic x86_64)

    -webkit-debug: invalid command-line switch

**Comment by ariya** [comment]
This is overtaken by event, the new `build.py` should do the build. Refer to the website for details.

**Comment by erikdubbelboer** [comment]
Actually the website is still wrong on this.

http://phantomjs.org/crash-reporting.html says:
```
    Build with debugging symbols enabled:
CFLAGS=-g CXXFLAGS=-g ./build.sh --qt-config '-webkit-debug' --qmake-args "QMAKE_CFLAGS=-g QMAKE_CXXFLAGS=-g"
```
Which I guess should be:
```
./build.sh --debug
```
these days.
