### ISSUE TITLE
Crash on Debian Wheezy with official 1.9.8 binaries

### ISSUE THREAD

**Issue by tjanez** [ariya/phantomjs#13325]
I'm experiencing reproducible crashes with the latest PhantomJS 1.9.x release on Debian Wheezy.

Here is the stack trace: http://pastebin.com/szVE735Y.

Any idea what is happening?

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
