### ISSUE TITLE
Syntax error in file goes undetected

### ISSUE THREAD

**Issue by LinusU** [ariya/phantomjs#13332]
Running `phantomjs` on a file with a syntax error in it will leave phantomjs running without doing or outputting anything. I would expect it to raise a syntax error and then to terminate.

Example script:

```javascript
var page = require('webpage').create()))
```

**Comment by Vitallium** [comment]
Duplicate. Please see #12973

**Comment by LinusU** [comment]
I actually don't think that it's the same. That was inside a callback and the throwing of an error. This is just a syntax error in the main file.

```javascript
console.log())) // This bug

throw new Error('x') // Works as expected

page.open('...', function () {
  throw new Error('x') // Bug #12973
})
```

Btw, did you ever post your solution somewhere? I would really really like to have it :+1:
