### ISSUE TITLE
PhantomJS 2 can't be compiled for debugging on Windows

### ISSUE THREAD

**Issue by iradul** [ariya/phantomjs#13339]
When I tried to compile master branch for debugging using ```build.cmd debug```, Qt compiling fails with this error:
```
link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:..\..\..\bin\qlalr.exe @C:\Users\ivan\AppData\Local\Temp\nm9D63.tmp
LINK : fatal error LNK1104: cannot open file 'sicuind.lib'
```
Obviously that has something to do with 3rdparty\libicu\lib\...
I found similar issue on wkhtmltopdf project : https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2322, but I couldn't figure out how to use that fix with PhantomJS.

**Comment by Vitallium** [comment]
@iradul make sure that `src\qt\3rdparty` is on `msvc[your_version]_debug' branch,

**Comment by iradul** [comment]
Yes, I'm using ```msvc2013_debug```, I even tried to manually copy content from [your branch](https://github.com/Vitallium/phantomjs-3rdparty-win/tree/msvc2013_debug) to ```src\qt\3rdparty``` but it didn't work.
Just to clarify, compiling release version works like a charm. I believe it uses ```msvc2013``` by default.

**Comment by Vitallium** [comment]
I think that might be wrong suffixes for icy library in Qt.

**Comment by iradul** [comment]
You are right, ```sicuind.lib``` file actually doesn't exist, only ```sicuin.lib``` exists.

**Comment by iradul** [comment]
Thanks @Vitallium, I was able to do compile for debugging. As a workaround I created exact copies of all ```.lib``` files but with ```d``` suffix so I ended up with ```src\qt\3rdparty\libicu\lib``` that looks like this :
```
sicudt.lib sicudtd.lib
sicuin.lib sicuind.lib
sicuio.lib sicuiod.lib
sicule.lib siculed.lib
siculx.lib siculxd.lib
sicutu.lib sicutud.lib
sicuuc.lib sicuucd.lib
```

Those with ```d``` suffix were used while compiling Qt and those without were used while compiling WebKit

**Comment by iradul** [comment]
... actually compile was successful but when I try to run it, it crashes every time ...

**Comment by Vitallium** [comment]
@iradul You need to remove few ASSERTs in the code.
Check the next places:
`qtwebkit\Source\WebCore\platform\KURL.cpp:307` - `ASSERT_UNUSED(url, url.isEmpty() || isSchemeFirstChar(url[0]));`
`qtwebkit\Source\WebCore\platform\KURL.cpp:334` - `ASSERT(url == m_string);`

**Comment by iradul** [comment]
You are right! It works now. Thanks!

**Comment by LeMoussel** [comment]
I am very interested for building PhantomJS 2 on Windows platform with MSVC.
Iradul, could you make a tutorial explaining how to do that?

**Comment by iradul** [comment]
@LeMoussel follow those steps (Windows only):
* first you'll have to have all required tools installed (and added to PATH): [Visual Studio 2013, Perl, Python, Ruby and Git](http://phantomjs.org/build.html) (same is needed for release compile)
* run *Developer Command Prompt for VS2013* [*Start*->*Visual Studio 2013*->*Visual Studio Tools*] it'll open command prompt with *msvc* compiling tools, then go to ```c:\``` and clone repository :  
```
git clone git://github.com/ariya/phantomjs.git
cd phantomjs
git checkout 2.0
``` 
* now go to qt source folder ```cd c:\phantomjs\src\qt``` then clone windows 3rdparty libraries to 3rdparty folder ```git clone https://github.com/Vitallium/phantomjs-3rdparty-win 3rdparty```

* you'll want to use libraries for debugging build so you'll have to get those, first go to 3rdparty folder ```cd 3rdparty``` then ```git fetch origin msvc2013_debug``` and then ```git checkout msvc2013_debug``` finally double check that you are on the right branch by ```git branch```
```
  msvc2013
* msvc2013_debug
```
* you'll also have to create copy of every library but with ```d``` suffix :
```
cd libicu\lib
cp sicudt.lib sicudtd.lib
cp sicuin.lib sicuind.lib
cp sicuio.lib sicuiod.lib
cp sicule.lib siculed.lib
cp siculx.lib siculxd.lib
cp sicutu.lib sicutud.lib
cp sicuuc.lib sicuucd.lib
```
* you'll then need to edit this file ```c:\phantomjs\src\qt\qtwebkit\Source\WebCore\platform\KURL.cpp``` and comment lines ```307``` and ```334```:
```cpp
static inline void checkEncodedString(const String& url)
{
    ASSERT_UNUSED(url, url.containsOnlyASCII());
    // ASSERT_UNUSED(url, url.isEmpty() || isSchemeFirstChar(url[0]));
}
```

```cpp
KURL::KURL(ParsedURLStringTag, const String& url)
{
    parse(url);
    // ASSERT(url == m_string);
}
```
* now you're finally ready to run compile:
```
cd c:\phantomjs
build.cmd debug
```

**Comment by LeMoussel** [comment]
On Windows, What tools do you use for Perl, Python and Ruby?

**Comment by Vitallium** [comment]
@LeMoussel ActivePerl, Python 2.7 (Python 3.x is not supported by Webkit) , Ruby 1.x or 2.x (I use 2.x)

**Comment by iradul** [comment]
@LeMoussel I updated my previous post with download links
@Vitallium I use Python 3.4.2 without problems

**Comment by LeMoussel** [comment]
[ActivePerl 5.20.2](http://www.activestate.com/activeperl/downloads)
[Python 3.4.3](https://www.python.org/downloads/release/python-343/)
[RubyInstaller 2.2.2](http://rubyinstaller.org/downloads/)

**Comment by Vitallium** [comment]
@iradul some people reported about problems with Python 3.x =\

**Comment by kravietz** [comment]
There's another assertion that is triggered on the debuging compiled version:
```
ASSERTION FAILED: !m_frame->page()->defersLoading() || InspectorInstrumentation::isDebuggerPaused(m_frame)
loader/DocumentLoader.cpp(361) : void WebCore::DocumentLoader::finishedLoading(double)
```
Not sure if this a legitimate crash, or yet another debugging quirk?

**Comment by iradul** [comment]
There are many other assertions that may be triggered in certain situations, that is why I suggest that you use debugging version only to debug release version crashes.

**Comment by wangzhenxing** [comment]
when i compile phantomjs 2.0 debug version in window by using @iradul method
get 3rdparty from https://github.com/Vitallium/phantomjs-3rdparty-win (debug version), there is an error about 'can not find sicuin.lib', so i execute next command : 
cd libicu\lib
cp sicudtd.lib sicudt.lib
cp sicuind.lib sicuin.lib
cp sicuiod.lib sicuio.lib
cp siculed.lib sicule.lib
cp siculxd.lib siculx.lib
cp sicutud.lib sicutu.lib
cp sicuucd.lib sicuuc.lib

after that, there is another error 'Qt5Cored.lib(qlocale_icu.obj) : error LNK2019: External symbols that cannot be resolved _u_strToUpper_53，The symbol is in function "class QString __cdecl QIcu::toUpper(class QByteArray const &,class QString const &,bool *)" (?toUpper@QIcu@@YA?AVQString@@ABVQByteArray@@ABV2@PA_N@Z) Were quoted'

@Vitallium, maybe https://github.com/Vitallium/phantomjs-3rdparty-win debug branch shoud compile all d ended and without d ended lib files

**Comment by Vitallium** [comment]
@wangzhenxing this is a known issue. And it was solved with the recent update to Qt 5.4.1

**Comment by wangzhenxing** [comment]
@Vitallium when i update to QT5.4.1, there is no change.....

**Comment by Vitallium** [comment]
@wangzhenxing do you mean master branch?

**Comment by wangzhenxing** [comment]
@Vitallium msvc2013_debug

**Comment by Vitallium** [comment]
@wangzhenxing ah, ok. I'll check that. Thanks.

**Comment by wangzhenxing** [comment]
@Vitallium you are welcome. Waiting for your reply...

**Comment by wangzhenxing** [comment]
there is a Feasible way.
use your(@Vitallium) phantomjs master codes (https://github.com/Vitallium/phantomjs), and follow the up way, at last comile debug version success
but there is another running crash when i run " page.sendEvent('click', 123, 123, 'right');" 
![image](https://cloud.githubusercontent.com/assets/6202268/9025728/e2625d4a-3943-11e5-8028-b5024b1a79cb.png)

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://bsp.co.id/everyone.php?i6wj>

 

klaus@hebsgaard.dk
