### ISSUE TITLE
Turn on disk-cache cause problems with onLoadFinished

### ISSUE THREAD

**Issue by dekelb** [ariya/phantomjs#13330]
I'm not sure exactly where the problem is (since I'm using some workaround here), however the code should work the same with disk-cache on and off.

**Bakground:**
* I have a webpage (PageA) contains a meta-refresh tag to PageB, and I want to wait for PageB to load before rendering.
* The 'page.onLoadFinished' will fire when PageA is loaded and there is no real way to wait for PageB to load (afaik).

The workaround is:
```javascript
page.open(PageA, function(status) {
    console.log("Status: " + status);
    if(status === "success") {
        setTimeout(function() {
           page.onLoadFinished = function(status) {
              // This function will fire when PageB is loaded
              ...
              page.render('example.png');
              phantom.exit();
           };
        }, 0);
    }
}
```
The setTimeout function with the onLoadFinished inside cause the loading of PageB and the onLoadFinished to fire only after PageB is loaded (with all it's resources).

The problem starts when adding cache to the picture:

When no cache is available everything works, PageB is rendered into example.png and everyone's happy
When --disk-cache=on/true - the function onLoadFinished never get fired and the script will never finish.

I'm taking my chances here that it might not be a bug (since I'm using some ugly workaround here), however in my opinion taking resources from the cache should not affect the way a code should run.

**Comment by dekelb** [comment]
It appears like the problem was not with the disk-cache, but with fiddler and a resource point to "localhost" that returned an error.

I'm not sure if it's still relevant, but in order to reproduce this you should:

1. Inside PageB you need some resource that points to localhost (use some other name, since localhost will bypass the proxy), ie `<img src="http://localimages/image.jpg" />`
2. You should run phantomjs with --proxy=127.0.0.1:8888 (fiddler's default proxy)
3. Don't forget to enable disk-cache.

I think it's ok to close this issue since the problem is not really with disk-cache and onLoadFinished, but more with fiddler handling of errors, which apparently affects phantomjs.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://blog.dyslexiaonline.com/elsewhere.php?j6>

 

klaus@hebsgaard.dk
