### ISSUE TITLE
PhantomJS returning empty page

### ISSUE THREAD

**Issue by sayakb** [ariya/phantomjs#13341]
After looking around online for a solution for a while, I am still stuck with PhantomJS returning an empty page on Windows for a non-SSL website:

    C:\...>"C:\Program Files\PhantomJS\phantomjs.exe" JasmineRunner.js
    <html><head></head><body></body></html>

My phantomJS script:

    var page = require('webpage').create();
    
    page.open('http://internal.company.url/index.html', function () {
        setInterval(function () {
            console.log(page.content);
            //phantom.exit();
        }, 1000);
    });

I also tried spitting the content out using `page.evaluate`, but it gives me empty <body> tags.

    var content = page.evaluate(function() {
        return document.body.outerHTML;
    });

I can open the exact same index.html hosted on a different server, and I have no idea what is wrong with this URL. I tried remote debugging, changing my user agent, setting proxy to `none` - none of them seem to help.

I was earlier using phantom 1.9.3 which was showing `page.url` as about:blank, but with phantom 2.0.0, `page.url` is always blank and above is the HTML content of the page.

Any idea how I can debug this?

**Comment by leo1394** [comment]
Hi @sayakb , I am now having the same problem, you've mentioned above. Have you finally figured it our and solved it? It would be very a great help to me for any clue helpful, thanks in advance!

**Comment by sayakb** [comment]
@leo1394 unfortunately I couldn't find a solution to the blank page issue but I did find a workaround for my specific usecase. I was basically trying to open a jasmine report page which ran unit tests on a web application and reported the results to the browser console. Instead of opening the page from the server, i ended up checking out the code from git locally and then opened that file:// through phantom js and it worked.

**Comment by leo1394** [comment]
@sayakb all right! thank you anyway

**Comment by yaroslavputria** [comment]
@leo1394 Hi!
Did you find the solution?
This ```casperjs index.js --ssl-protocol=any --ignore-ssl-errors=true``` doesn't work :(
