### ISSUE TITLE
Missing symlink in build instructions for Linux

### ISSUE THREAD

**Issue by janecakemaster** [ariya/phantomjs#13357]
Current: There is a step missing in the Linux installation instructions that enables you to run phantomjs without explicitly calling it from `phantomjs/bin`
Proposed: Add a note to symlink the right executable to the right place

**Comment by ariya** [comment]
This is actually superfluous. Once the executable is produced, there are many different ways to run it (part of PATH etc), just like a normal Linux executable. There is nothing unique about `phantomjs` binary and therefore the user can follow the usual practices on how to deal with other binary.
