### ISSUE TITLE
2.0.0: Embedded fonts not loaded

### ISSUE THREAD

**Issue by gagern** [ariya/phantomjs#13353]
In Khan/KaTeX#263 I had been investigating the use of PhantomJS for the creation of snapshots for automated unit tests. The PhantomJS 1.9.0 shipped with Ubuntu had incorrect box placements. With 2.0.0 the placements looked better, but the fonts were all wrong. Looking at the server logs, it looks to me as if PhantomJS were not requesting any fonts at all, but using its defaults instead.

Steps to reproduce:

```
git clone -o gagern https://github.com/gagern/KaTeX.git
cd KaTeX
git checkout da0613e
npm install
node server.js
phantomjs dockers/Phantom/live.js
xdg-open test/screenshotter/images/
```

The `server.js` will launch a development server which means that you better run `phantomjs` in a different console, but from the same `KaTeX` directory. I've experienced the same symptoms with [the phantomjs-2.0.0 package on Gentoo Linux](https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/www-client/phantomjs/phantomjs-2.0.0.ebuild?revision=1.3&view=markup), with the [servebox/phantomjs docker image](https://registry.hub.docker.com/u/servebox/phantomjs/dockerfile/) and with the official binary for OS X (except there the set of default fonts is different).

This issue looks somewhat similar to #10247 or some other font rendering issues I've seen, except that the fonts did work with the 1.9.0 package from Ubuntu, so this feels like a more recent regression, and not some bug which dates back to 1.3.0.

**Comment by medikoo** [comment]
I'm having same issue on Ubuntu setup, when using v2 build with following instructions -> http://phantomjs.org/build.html
