### ISSUE TITLE
Your copy of the BSD license terms is missing the copyright statement

### ISSUE THREAD

**Issue by rterbush** [ariya/phantomjs#13350]
You need to add a copyright statement to the top of your BSD license as referenced in the body of the license text. More info at this link: http://opensource.org/licenses/BSD-2-Clause

**Comment by selurvedu** [comment]
I agree with one exception: the project uses 3-clause BSD license, not 2-clause.

**Comment by selurvedu** [comment]
Also, this part has two essential words words missing – `OR CONTRIBUTORS`:

Current:
```
IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
```
Desired:
```
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
```

Sources:
http://choosealicense.com/licenses/bsd-3-clause/
http://opensource.org/licenses/BSD-3-Clause
