### ISSUE TITLE
CSS3 & HTML 5 Test

### ISSUE THREAD

**Issue by LeMoussel** [ariya/phantomjs#13369]
I make this JS code [css3-html5_test](https://gist.github.com/LeMoussel/ba407bf2c83af8d56d1c)  to test how well PhantomJS support HTML5 and which CSS3 features PhantomJS recognizes.

I use PhantomJS 2.0.0 on Windows 7.

For HTML5 Test. It's OK. I got PDF & PNG files.
For CSS3 Test. It 'KO. I got PNG file but I have blank page for PDF file.

**Comment by Ryuurock** [comment]
Part of the transform properties were killed
