### ISSUE TITLE
PhantomJs Crash Report

### ISSUE THREAD

**Issue by TriptiMittal** [ariya/phantomjs#13362]
Hi,

When I try to work on the phantomjs it crash every time. I tried to generate the stack trace but can't do  that even I have gone through the crash report HTML but still dont find a way out. Can anyone help me to resolve this where I can send the .dmp file or can fix the crash.

I am using Windows and phantomjs-1.9.8-windows.

Thanks.

**Comment by gmisura** [comment]
What version? What OS?
What are you running? Just 'phantomjs'?

On Thu, Jun 25, 2015 at 9:47 PM, TriptiMittal <notifications@github.com>
wrote:

> Hi,
>
> When I try to work on the phantomjs it crash every time. I tried to
> generate the stack trace but can't do that even I have gone through the
> crash report HTML but still dont find a way out. Can anyone help me to
> resolve this where I can send the .dmp file or can fix the crash.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ariya/phantomjs/issues/13362>.
>



-- 
Gabe Misura
