### ISSUE TITLE
2.0.1-development crash report

### ISSUE THREAD

**Issue by RavenHursT** [ariya/phantomjs#13367]
I'm using 2.0.1-development for linux x64.  I'm having an issue w/ periodic crashes of PhantomJS.  I was going to convert to a stack trace, but  there's not 2.0 "symbols" file here: https://bitbucket.org/ariya/phantomjs/downloads

I've attached the dump here (GitHub won't allow me to attache the .dmp alone): http://ge.tt/6WrZe8J2/v/0

I'm seriously at a loss here.. I'm not seeing any memory spikes or CPU spikes on the box.  Is there a way to see error logs for PhantomJS?  Does it maintain a log?

**Comment by RavenHursT** [comment]
I'm seeing TONS of crash reports being added here w/ very little feedback.  

Is anyone maintaining this project anymore?

**Comment by Vitallium** [comment]
If you use your own version (compiled from the source), you have to compile it with debug info to get debug symbols.

**Comment by RavenHursT** [comment]
Arg.. I did try to compile my own, but ran into so many headaches, I ended up just using one that someone else had compiled.  Really wish the binaries for Linux would get finalized..

**Comment by zackw** [comment]
@RavenHursT said:
> I'm seeing TONS of crash reports being added here w/ very little feedback. Is anyone maintaining this project anymore?

We *do* have a bit of a manpower problem right now.  And most crash reports turn out to be bugs in Qt and Webkit, which we can't do anything about directly.  And we need to rewrite the crash reporting instructions to make it clear that a crash dump isn't enough for us to go on -- we also need some way of making the crash happen for ourselves.

The good news is, we are actively working on keeping up with Qt and Webkit upstream releases, and every one of those fixes a bunch of the crasher bugs :-)

**Comment by RavenHursT** [comment]
Thank you @zackw for the feedback.

Is there any possibility that 2.x linux binaries (as well as debug versions) might be available soon?  I'm having crashes every week w/ this thing, and I can't give any debug info because doing a proper build is so complicated at this point...
