### ISSUE TITLE
Crash when return page containing a PNG image.

### ISSUE THREAD

**Issue by LeMoussel** [ariya/phantomjs#13373]
I'm using PhantomJS 2.0.0 for Windows 7. PhantomJS has crashed when loaded this page containing a PNG image: http://httpbin.org/image/png

**Code :**

``` javascript
var page = require('webpage').create();
var url = 'http://httpbin.org/image/png';

page.open(url, function(status) {
  var title = page.evaluate(function() {
    return document.title;
  });
  console.log('Page title: ' + title);
  phantom.exit();
});
```
## Dump Summary

Dump File:  df3821eb-7f00-4802-a7fb-c36e84947161.dmp : C:\Users\TripleX\AppData\Local\Temp\df3821eb-7f00-4802-a7fb-c36e84947161.dmp
Last Write Time:    02/07/2015 08:45:26
Process Name:   phantomjs.exe : C:\Users\TripleX\SkyDrive\VS Project\PhantomJS\Debug PhantomJS\phantomjs.exe
Process Architecture:   x86
Exception Code: 0xC0000005
Exception Information:  The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:   Not Present
## System Information

OS Version: 6.1.7601
CLR Version(s): 
## Modules

Module Name Module Path Module Version

---

phantomjs.exe   C:\Users\TripleX\SkyDrive\VS Project\PhantomJS\Debug PhantomJS\phantomjs.exe    2.0.0.0
ntdll.dll   C:\Windows\System32\ntdll.dll   6.1.7601.18205
kernel32.dll    C:\Windows\System32\kernel32.dll    6.1.7601.18847
KERNELBASE.dll  C:\Windows\System32\KERNELBASE.dll  6.1.7601.18847
ws2_32.dll  C:\Windows\System32\ws2_32.dll  6.1.7601.17514
msvcrt.dll  C:\Windows\System32\msvcrt.dll  7.0.7601.17744
rpcrt4.dll  C:\Windows\System32\rpcrt4.dll  6.1.7601.18532
nsi.dll C:\Windows\System32\nsi.dll 6.1.7600.16385
winspool.drv    C:\Windows\System32\winspool.drv    6.1.7601.17514
gdi32.dll   C:\Windows\System32\gdi32.dll   6.1.7601.18778
user32.dll  C:\Windows\System32\user32.dll  6.1.7601.17514
lpk.dll C:\Windows\System32\lpk.dll 6.1.7601.18768
usp10.dll   C:\Windows\System32\usp10.dll   1.626.7601.18454
oleaut32.dll    C:\Windows\System32\oleaut32.dll    6.1.7601.18640
ole32.dll   C:\Windows\System32\ole32.dll   6.1.7601.17514
imm32.dll   C:\Windows\System32\imm32.dll   6.1.7601.17514
msctf.dll   C:\Windows\System32\msctf.dll   6.1.7601.18731
winmm.dll   C:\Windows\System32\winmm.dll   6.1.7601.17514
shell32.dll C:\Windows\System32\shell32.dll 6.1.7601.18762
shlwapi.dll C:\Windows\System32\shlwapi.dll 6.1.7601.17514
advapi32.dll    C:\Windows\System32\advapi32.dll    6.1.7601.17514
sechost.dll C:\Windows\System32\sechost.dll 6.1.7600.16385
crypt32.dll C:\Windows\System32\crypt32.dll 6.1.7601.18277
msasn1.dll  C:\Windows\System32\msasn1.dll  6.1.7601.17514
dbghelp.dll C:\Windows\System32\dbghelp.dll 6.1.7601.17514
CRYPTBASE.dll   C:\Windows\System32\CRYPTBASE.dll   6.1.7600.16385
profapi.dll C:\Windows\System32\profapi.dll 6.1.7600.16385
uxtheme.dll C:\Windows\System32\uxtheme.dll 6.1.7600.16385
cryptsp.dll C:\Windows\System32\cryptsp.dll 6.1.7600.16385
rsaenh.dll  C:\Windows\System32\rsaenh.dll  6.1.7600.16385
IPHLPAPI.DLL    C:\Windows\System32\IPHLPAPI.DLL    6.1.7601.17514
winnsi.dll  C:\Windows\System32\winnsi.dll  6.1.7600.16385
dhcpcsvc.dll    C:\Windows\System32\dhcpcsvc.dll    6.1.7600.16385
dhcpcsvc6.DLL   C:\Windows\System32\dhcpcsvc6.DLL   6.1.7600.16385
wlanapi.dll C:\Windows\System32\wlanapi.dll 6.1.7600.16385
wlanutil.dll    C:\Windows\System32\wlanutil.dll    6.1.7600.16385
winhttp.dll C:\Windows\System32\winhttp.dll 6.1.7601.17514
webio.dll   C:\Windows\System32\webio.dll   6.1.7601.17725
sspicli.dll C:\Windows\System32\sspicli.dll 6.1.7601.18812
credssp.dll C:\Windows\System32\credssp.dll 6.1.7601.18812
cfgmgr32.dll    C:\Windows\System32\cfgmgr32.dll    6.1.7601.17514
mswsock.dll C:\Windows\System32\mswsock.dll 6.1.7601.17514
WSHTCPIP.DLL    C:\Windows\System32\WSHTCPIP.DLL    6.1.7600.16385
wship6.dll  C:\Windows\System32\wship6.dll  6.1.7600.16385
dnsapi.dll  C:\Windows\System32\dnsapi.dll  6.1.7601.17570
WLIDNSP.DLL C:\Program Files\Common Files\Microsoft Shared\Windows Live\WLIDNSP.DLL 7.250.4311.0
psapi.dll   C:\Windows\System32\psapi.dll   6.1.7600.16385
rasadhlp.dll    C:\Windows\System32\rasadhlp.dll    6.1.7600.16385
FWPUCLNT.DLL    C:\Windows\System32\FWPUCLNT.DLL    6.1.7601.17514
userenv.dll C:\Windows\System32\userenv.dll 6.1.7601.17514
powrprof.dll    C:\Windows\System32\powrprof.dll    6.1.7600.16385
setupapi.dll    C:\Windows\System32\setupapi.dll    6.1.7601.17514
devobj.dll  C:\Windows\System32\devobj.dll  6.1.7600.16385

**Comment by Vitallium** [comment]
PhantomJS doesn't support any content except HTML (XML), JavaScript or CSS. Binary content is not supported. You can't open binary content directly.

**Comment by LeMoussel** [comment]
OK . 
I don't know if the page content is binary or not. Any idea on how to avoid loading binary content with PhantomJS?

**Comment by Vitallium** [comment]
@LeMoussel right now it's not possible. But QtWebkit (QWebPage) has a special signal for that: `unsupportedContent' (https://github.com/ariya/phantomjs/blob/master/src/qt/qtwebkit/Source/WebKit/qt/WidgetApi/qwebpage.h#L413)
We should use it.

**Comment by LeMoussel** [comment]
Possible to integrate this special signal in a future release?

**Comment by Vitallium** [comment]
Hard to say. I want to implement it as a part of the feature to download files. Because they are depend on each other.

**Comment by LeMoussel** [comment]
Vu. Should I close this issue?

**Comment by Vitallium** [comment]
Nop. We will use it to track `unsupportedContent` feature.
