### ISSUE TITLE
Search results (dynamic) not loading / displaying on page

### ISSUE THREAD

**Issue by plamzi** [ariya/phantomjs#13375]
Search results never load / display on this page:
http://www.celebritycruises.com/cruise-search/search-results
- Using 2.0.0 latest stable.
- Search results load normally in comparable WebKit desktop browsers.
- There are no errors loading any page resources.
- I see a single JS error but it appears to happen later on in the page load, seemingly because the carousel of search results never loaded up.

If anyone can provide some quick tips on how to debug further, it would be much appreciated.

**Comment by GregKleinGoAhead** [comment]
I'm having this issue as well!
