### ISSUE TITLE
npm install -g phantomjs2 seems to be failing

### ISSUE THREAD

**Issue by socketwiz** [ariya/phantomjs#13376]
I was actually trying to install mocha-phantomjs which seems to have a dependency on phantomjs2 which results in the following error, even if I try to install just phantomjs2 by itself.  It seems to be pointing to a fork of this repo rather than this repo itself and the path for the zip file its trying to download does not exist.  Anyone have any ideas?

```
$ sudo npm install -g phantomjs2
/usr/bin/phantomjs -> /usr/lib/node_modules/phantomjs2/bin/phantomjs

> phantomjs2@2.0.0 install /usr/lib/node_modules/phantomjs2
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://github.com/bprodoehl/phantomjs/releases/download/2.0.0-20141016/phantomjs-2.0.0-20141016-linux-x86_64.zip
Saving to /usr/lib/node_modules/phantomjs2/phantomjs/phantomjs-2.0.0-20141016-linux-x86_64.zip
Receiving...
Install exited unexpectedly
```

**Comment by Vitallium** [comment]
@socketwiz Sorry, but we don't maintain PhantomJS in npm registry. Please open an issue in the original repository (https://github.com/bprodoehl/phantomjs)

**Comment by socketwiz** [comment]
Ah sorry, I didn't realize that.  And they seem to have issues disabled, oh well :(
