### ISSUE TITLE
Upgrade Qt to 5.5

### ISSUE THREAD

**Issue by Vitallium** [ariya/phantomjs#13377]
Qt 5.5 has a bunch of improvements and fixes.
Important fixes for us are listed below:

* [QTBUG-26538] Fixed a bug that caused both QTcpSocket and QUdpSocket to
   close the socket and lose any bound ports before connecting. Now
   bind()/setSocketDescriptor() followed by connect() will retain the
   original file descriptor.
* A new SSL backend for iOS and OS X, implemented with Apple's Secure (Security Framework).

QtWebkit also requires in update to 5.5.

**Comment by iradul** [comment]
:+1:

**Comment by Vitallium** [comment]
Landed in https://github.com/Vitallium/qtbase/commit/e2871ae0b64f7b9b18954e9b3f26f04348c8f0fa
