### ISSUE TITLE
Yslow with phantomjs result on jenkins not matched with yslow via firefox plugin

### ISSUE THREAD

**Issue by qa2015** [ariya/phantomjs#13385]
platform: Win 7 professional 32 bit

Previously i faced issue on certain url where upon executing yslow with phantomjs via Jenkins getting error "fail to load, undefine".
Upon further investigation found it's due to PhantomJS defaults using SSLv3 to open HTTPS connections.
Issue resolve by issuing this command along "--ssl-protocol=any"

Now, when i evaluate yslow tap result vs yslow via firefox, the result not matched, where on yslow tap result via jenkins shows all item fine except yCDN fail and result from firefox yslow gives yCDN result fail along with Add Expires headers rating "B" and yminify (minify js and css) rating "E" (note: in yslow tap result both these achieved rating "A".

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://doasaun.com/decade.php?adehv>

 

klaus@hebsgaard.dk
