### ISSUE TITLE
Multiple PhantomJS instances hanging

### ISSUE THREAD

**Issue by yaronel** [ariya/phantomjs#13387]
Hi,

I am having a problem when running multiple instances of PhantomJS on Ubuntu 14. After a few minutes, the processes become unresponsive.

Brief background:
Using PhantomJS 2.0 to render a web page that ultimately gets saved as a PDF using Wkhtmtopdf.
PhantomJS is only responsible for loading the page, making ajax requests, and waiting for a response after the PDF is saved on the server. It does not generate the PDF itself.
There are hundreds of web pages that need to be generated into PDF, so I want to run as many PhantomJS instances in parallel as the system allows.

Each PhantomJS process is started by a shell script like so:
<code>{path to phantomjs} {path to js file} --data {some argument} >> {path to log file} 2>&1 &</code>

The problem occurs after a couple of minutes where I stop getting any output from the PhantomJS processes, and looking at <code>top</code> I can see they are just laying there not doing anything. The JS script has timers that retry to load a page if it takes longer than a minute, and eventually call <code>phantom.exit()</code> if the page can't load / PDF generation fails. So even if something goes wrong, the process should still exit - but it doesn't.

I tried changing the number of PhantomJS instances running in parallel. Tried 20 -> 10 -> 5 -> 3, but it doesn't seem to matter. I can actually get many more jobs execute successfully when maintaining 20 instances at a time.

When running with <code>--debug=true</code> I can see that at some point it gets stuck at
 <code>[DEBUG] WebPage - updateLoadingProgress:</code> 
Also going through the output I see several of these warnings: 
<code>[WARNING] QIODevice::write: device not open</code>
which makes me believe that is the source of the problem.

I thought there might be some contention for file resources so I tried without redirecting output to a log file, and not using <code>--local-storage-path</code>, but that didn't help.

As a side note, I have been using PhantomJS for several years now doing the same procedure, only sequentially (run a single PhantomJS process at a time). And although there were a few snags to overcome, it worked great.

**Comment by iradul** [comment]
Sounds like a dead lock to me. Are you using some shared resource between processes for example same log file(s), same pdf file(s) for output etc. ?

**Comment by yaronel** [comment]
Yes, the log file is shared between the processes. That's why I tried removing all the logging by commenting out all the calls to <code>console.log</code> in the PhantomJS script, and removing the stdin and stdout redirection from the shell command (or redirecting to <code>/dev/null</code>).
But, it did not help...

I can't think of any other obvious resource that is being shared between different instances of PhantomJS. I read that all the instances use the same localStorage path, but I didn't enable the localStorage option when running PhantomJS.

Any idea what else could be shared?

**Comment by mepard** [comment]
I just noticed this. The disk cache is shared. See https://github.com/ariya/phantomjs/pull/13817.

**Comment by dmitryikh** [comment]
@yaronel , did you manage to solve the ganging over multiple phantomjs processes? It seems that I have similar problem..

**Comment by yaronel** [comment]
@dmitryikh I can't say that I solved it because I don't know what exactly made it work again.
I do know that running 20 instances on an AWS t2.small / medium instance is not possible. PhantomJS takes a lot of CPU and memory and things just get queued.

I found that running 8 at a time on a t2.medium and spinning multiple EC2 instances works best.
It also depends on the type of work you have PhantomJS do. In my case it takes anywhere between 15 seconds to 2 minutes to run each task. If you have much shorter jobs you will probably get away with a higher number of PhantomJS instances.

**Comment by jconroy** [comment]
@yaronel curious, how did you go about balancing requests across multiple instances? Did you use selenium grid or a load balancer? (with the load balancer did you have to do anything special with sessions?)

**Comment by yaronel** [comment]
@jconroy we have a central job that dispatches the tasks to the servers that sit behind a load balancer. The tasks are asynchronous, meaning the dispatcher doesn't wait for a task to finish - it just receives a 200 response code letting it know it was received. So session management was not an issue. 

If in your case you need to maintain the session between requests then I know AWS load balancers have a sticky session option where it maintains the session for you and all requests of the same session will go to the same instance. I am sure other load balancers have a similar setting.
