### ISSUE TITLE
Reference screenshot differs on machines

### ISSUE THREAD

**Issue by tobiasKaminsky** [ariya/phantomjs#13381]
Hello,

I am using phantomJS within Vaadin TestBench, which uses Selenium. 
There I develop integration tests and let phantomJS create a reference screenshot.
In the test cycles these reference images are compared to the currently created one and the difference is shown.
The problem is that my local developer machine creates other reference images than the integration server.
Therefore I cannot use the same reference images for the same integration test but have to maintain for every machine an individual  set of reference screenshots.

So I have tried to narrow down the problem: 
I have created a plain html file with only < FONT FACE="arial">arial font< /FONT >
and have it rendered via:

```
var page = require('webpage').create();
page.viewportSize = { width: 1024, height: 768 };

page.open('font.html', function() {

  page.evaluate(function() {
    document.body.bgColor = 'white';
    });

  page.render('font.png');
  phantom.exit();
});
```

and "phantomjs font.js"

Attached are the three images generated on three machines.
All are different. (For better seeing the difference please open them in new tabs and switch quickly between them).

Via md5sum I have verified that the used arial.ttf file is the same on all three machines.
Also phantomjs is the same (1.9.8 ).
What other package could influence the output of the rendering?

![font](https://cloud.githubusercontent.com/assets/5836855/8518416/1fb5f86c-23ca-11e5-89c4-2512ab0c7c1b.png)
![font_debian7](https://cloud.githubusercontent.com/assets/5836855/8518414/1fb53882-23ca-11e5-8566-4faa1915436b.png)
![font_server](https://cloud.githubusercontent.com/assets/5836855/8518415/1fb5980e-23ca-11e5-8382-a870043f87b1.png)

Thank you
Tobias

**Comment by tobiasKaminsky** [comment]
Addition:
Local machine: gentoo Linux
server1: ubuntu
server2: debian7

**Comment by tobiasKaminsky** [comment]
I have copied now one binary (from debian7) to all other machines, but the result is still the same.
How can that be?
What else libs/whatever are used that could render the screenshot differently?

**Comment by OneOfOne** [comment]
fontconfig is what actually renders the font, so check the version on each machine.

**Comment by tobiasKaminsky** [comment]
Thanks for the hint, but https://wiki.freedesktop.org/www/Software/fontconfig/ says that it does not render the fonts itselfs, but this is left to FreeType or other rendering mechanisms.
But freetype is installed on my local machine (gentoo), but not on server2 (debian7) nor on server 1.
So I need to figure out which font render engine are used on server1/2.

I wish there would be a way to put this all in a nutshell and copy it to all machines so that I can get exactly the same images...

**Comment by tobiasKaminsky** [comment]
Any ideas left?
I am out of clue. 
How do you solve the problem that integration tests screenshots made one machine look different on another one? Or do you not use screenshots?

**Comment by OneOfOne** [comment]
I ended up writing my own script with PyQt5 (which uses an up-to-date qt5) and running it with xvfb.

**Comment by tobiasKaminsky** [comment]
@OneOfOne so you mean you wrote a whole replacement for phantomjs? Or only parts of it?

**Comment by OneOfOne** [comment]
@tobiasKaminsky oh just parts of it, I just needed to load a page and run a script on it then take a screenshot.

PhantomJS is just a wrapper for QtWebkit.

**Comment by tobiasKaminsky** [comment]
Can you explain this a bit more? 
Thank you :)

**Comment by OneOfOne** [comment]
Here's a trimmed version of it, https://gist.github.com/OneOfOne/07338333831c4fb392f8 

     python ss.py http://google.com > google.png

**Comment by OneOfOne** [comment]
Err to run it on a headless server you need to install xvfb, fontconfig and fonts.

on Arch I ran `pacman -S xorg-server-xvfb ttf-droid python-pyqt5 qtwebkit`
