### ISSUE TITLE
PhantomJS 1.9.8 Crashing

### ISSUE THREAD

**Issue by RavenHursT** [ariya/phantomjs#13389]
I'm running PhantomJS behind an express server that allows requests w/ ?url=[url to visit], takes the passed url, creates a page, visits the page and then does runs some tests on the page given, then closes the page and responds w/ the test results.

I keep seeing crashes after I throw a few requests at this thing.  I was using 2.0 and I see a LOT less crashing in that version, but since I have no way to generate a stack trace since there's no linux build or "symbols" available, I'm submitting this report using 1.9.8 in hopes that it'll shed some light on what (if anything) I'm doing wrong.

Thanks.

PasteBin Stacktrace: http://pastebin.com/DJhNfs2D

**Comment by RavenHursT** [comment]
Apparently this is a segfault.

I also ran a stack trace on a 2.0 dump file using the 1.9.8 symbols tar ball... not sure if that works.. But it did see the "Crash reason" as the same: SIGSEGV

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
