### ISSUE TITLE
Cannot write properties to window.crypto

### ISSUE THREAD

**Issue by knpwrs** [ariya/phantomjs#13393]
Try doing the following in the Phantom debug console:

``` js
window.crypto.foo = 'foo';
```

The string `'foo'` is printed out indicating the value which was written, however, `window.crypto.foo` is undefined if you try to access the value.

`Object.isFrozen(window.crypto)` returns `false` as it does in Chrome. Chrome, however, allows us to write properties to the `window.crypto` object.

The reason we need to be able to write to `window.crypto` is so we can polyfill `window.crypto.subtle` which is implemented by Chrome but not Phantom. Is there some sort of CLI flag to allow us to write to `window.crypto` or if not is it possible to fix this?

We are using Phantom 1.9.8.

**Comment by philipp-cliqz** [comment]
Seems to be fixed in 2.1.1
