### ISSUE TITLE
Missing phantomjs-2.0.0 linux-x86_64.zip download

### ISSUE THREAD

**Issue by Kenoshen** [ariya/phantomjs#13390]
At the time of writing this bug, the url:
https://github.com/bprodoehl/phantomjs/releases/download/2.0.0-20141016/phantomjs-2.0.0-20141016-linux-x86_64.zip

returns a 404.  This is causing an unrecoverable error when trying to npm install phantomjs2.

Was the linux distribution forgotten about?

Below is the console output when I run "sudo npm install phantomjs2":

sudo npm install phantomjs2
\
> phantomjs2@2.0.0 install /home/mwingfield/node_modules/phantomjs2
> node install.js

Downloading https://github.com/bprodoehl/phantomjs/releases/download/2.0.0-20141016/phantomjs-2.0.0-20141016-linux-x86_64.zip
Saving to /home/mwingfield/node_modules/phantomjs2/phantomjs/phantomjs-2.0.0-20141016-linux-x86_64.zip
Receiving...
Install exited unexpectedly

npm ERR! phantomjs2@2.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs2@2.0.0 install script.
npm ERR! This is most likely a problem with the phantomjs2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs2
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-431.3.1.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "phantomjs2"
npm ERR! cwd /home/mwingfield
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by Vitallium** [comment]
Sorry, but we don't maintain NPM package. You should open a new issue in the original repo (https://github.com/bprodoehl/phantomjs/releases)
