### ISSUE TITLE
PhantomJS doesn't let go of memory

### ISSUE THREAD

**Issue by joshterrill** [ariya/phantomjs#13391]
I've got a phantomjs/casperjs spider (basically something like this: http://planzero.org/blog/2013/03/07/spidering_the_web_with_casperjs) and when I run it and then open another terminal and run `top` to look at memory usage, the script just keeps using more and more memory until it eventually crashes. Is there a better way to run this so it doesn't do this? 

Edit: I think it has to do with the page maybe staying open while it goes to other pages? How can I properly close a page in the context of this scraper?

**Comment by codybonney** [comment]
Related to https://github.com/ariya/phantomjs/issues/13923?

**Comment by Vitallium** [comment]
Let's track this in https://github.com/ariya/phantomjs/issues/11390
