### ISSUE TITLE
PhantomJs Crashing everytime

### ISSUE THREAD

**Issue by kheraprabhat** [ariya/phantomjs#13418]
PhantomJs is crashing everytime evenwhen I just run phantomjs to go to console.

Dump file
https://www.dropbox.com/s/eylhwky34ngjv1j/7f2f7db1-ad0f-992b-5eea6252-3cf5a741.dmp?dl=0

**Comment by Maskime** [comment]
Same here,

Using Mac OS X pre-build version
```Darwin 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64```
