### ISSUE TITLE
Render to pdf causes wrong size of elements (2.0.0)

### ISSUE THREAD

**Issue by LinusU** [ariya/phantomjs#13417]
When rendering a simple html file with `width` and `height` properties specified in `mm`, the size get's all wrong.

Simple test case:

**test.js**

``` javascript
var page = require('webpage').create()

page.paperSize = {
  format: 'A4',
  orientation: 'portrait',
  margin: '1cm'
}

page.open('test.html', function (status) {
  if (status !== 'success') return phantom.exit(1)

  page.render('test.pdf')
  phantom.exit(0)
})
```

**test.html**

``` html
<html>
<head>
  <style>
    div {
      width: 95mm;
      height: 95mm;
      border: 1px solid black;
    }
  </style>
</head>
<body>
  <div> 95mm x 95mm </div>
</body>
</html>
```

**Usage**

``` bash
phantomjs test.js
```

**test.pdf** (output)
![screen shot 2015-07-18 at 18 09 19](https://cloud.githubusercontent.com/assets/189580/8762401/37b0c160-2d78-11e5-8508-0a8ba5f5ffa8.png)

There should be enough room to comfortable fit two boxes next to each other. An `A4` paper is 210mm x 297mm.

1.9.8 has a similar problem but it's a bit closer to being correct. Safari -> Print To Pdf renders it perfectly.

**Comment by LinusU** [comment]
Files available here: [LinusU/phantom-size-bug](https://github.com/LinusU/phantom-size-bug)

**Comment by thomasbachem** [comment]
Duplicate of #12685.
