### ISSUE TITLE
FollowingYSLOW rule :yjsbottom,yexpires, ycsstop rule don't work with phantomjs

### ISSUE THREAD

**Issue by qa2015** [ariya/phantomjs#13424]
FollowingYSLOW rule :yjsbottom,yexpires, ycsstop rule don't work with phantomjs

when compare result from yslow phantomjs against Chrome/Firefox browser yslow the result differs.

yslow withphantomjs shows "A" for these 3 rules where else manual run via browser plugin shows result fail "F"
Are these rules being ignored?

**Comment by ariya** [comment]
You likely need to discuss this on the YSlow project.
