### ISSUE TITLE
File upload fails for PhantomJS 2.0.0

### ISSUE THREAD

**Issue by dshuga** [ariya/phantomjs#13426]
I have a Selenium script that uses element.send_keys(filepath) to upload files to type=file inputs. The script succeeds when I use PhantomJS 1.9.8 but hangs indefinitely as it's attempting to send the file using PhantomJS 2.0.0. Since JavaScript can't change the value of file-type inputs for security reasons, I haven't been able to figure out a workaround.

Shouldn't matter, but I'm using selenium 2.45.0, Python 3.4.2 on a Windows 7 machine.

**Comment by johnnliu** [comment]
File Upload doesn't work seems to be a known regression in 2.0

http://phantomjs.org/release-2.0.html
https://github.com/ariya/phantomjs/issues/12506

**Comment by Vitallium** [comment]
Duplicated. See #12506

**Comment by xaviershay** [comment]
fwiw this is still broken for me in 2.1.1 on ubuntu. Reverted to 1.9.8 and it works. (Can't comment on #12506 coz it's locked)

**Comment by prusswan** [comment]
@xaviershay You will have to use the prebuilt binary, as the system package is using the vanilla webkit package while the fix works by patching webkit as well: https://bugs.launchpad.net/ubuntu/+source/phantomjs/+bug/1605628

**Comment by xaviershay** [comment]
aaah, thank you
