### ISSUE TITLE
Incorrect cursor position in remote debugging

### ISSUE THREAD

**Issue by sfsr12** [ariya/phantomjs#13427]
I am unable to debug properly.

Built 2.0 from source that includes the fixes added by @Vitallium related to issue #12864

I can get a debugger window, and execute the __run(); command.
The debugger does bring up a script window when it hits a debugger line.
However, the debugger cursor is not on the correct line and it makes it impossible to tell what I am debugging on large files.

Simple Example:
![phantomissue](https://cloud.githubusercontent.com/assets/13442518/8814710/13d3e6d0-2fcd-11e5-873d-24e4218c0212.jpg)

I thought maybe some strange caching issue - so I cleared everything - even went as far as uninstalling and reinstalling chrome.  No luck.

Anyone have any idea what would cause this incorrect cursor position?

Thanks!

**Comment by Vitallium** [comment]
Fixed in https://github.com/ariya/phantomjs/commit/8b79f62faf7335b8498770e01122b15d1405684b

**Comment by sfsr12** [comment]
Can confirm - built with these changes and everything works as expected now.   Thank you.

**Comment by Vitallium** [comment]
@sfsr12 Great! Thank you too!
