### ISSUE TITLE
Ubuntu - Fontconfig warning: ignoring UTF-8: not a valid region tag

### ISSUE THREAD

**Issue by hebbian** [ariya/phantomjs#13433]
I have this problem, I don't know it's OS warning or PhantomJS related issue. Any solution to this?

**Comment by danieljuhl** [comment]
I've had this issue too. It's not related to phantomjs, as far as I know. Please have a look at `/etc/default/locale`.

I added the following:
```
LANG="en_US.UTF-8"
LANGUAGE="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

That resolved the issue for me.

**Comment by Xychun** [comment]
export LANGUAGE=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    locale-gen en_US.UTF-8
    sudo dpkg-reconfigure locales

Solved it for me.

**Comment by itnick** [comment]
Just verified this on Testing Sandbox worker.pdf

No more error after I add these:
```
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

Then restart worker.pdf worker.


Action to be taken:
- [ ] Update AMI image
  - [ ] Add the above environment variables in ```/etc/default/locale```

**Comment by bushev** [comment]
How to fix this:  **Fontconfig warning: ignoring UTF-8: not a valid region tag**?

Info: I use `node-html-pdf` package with Danish symbols in html file to render.

```
user@server:~/Website$ locale
LANG=da_DK.UTF-8
LANGUAGE=da_DK.UTF-8
LC_CTYPE="da_DK.UTF-8"
LC_NUMERIC="da_DK.UTF-8"
LC_TIME="da_DK.UTF-8"
LC_COLLATE="da_DK.UTF-8"
LC_MONETARY="da_DK.UTF-8"
LC_MESSAGES="da_DK.UTF-8"
LC_PAPER="da_DK.UTF-8"
LC_NAME="da_DK.UTF-8"
LC_ADDRESS="da_DK.UTF-8"
LC_TELEPHONE="da_DK.UTF-8"
LC_MEASUREMENT="da_DK.UTF-8"
LC_IDENTIFICATION="da_DK.UTF-8"
LC_ALL=da_DK.UTF-8
```

**Comment by wong2** [comment]
I'm facing the same issue, I've updated my `/etc/default/locale` as @danieljuhl suggested, but it doesn't work. I also tried @Xychun 's solution, still have the issue.

this is the output of `locale` command on my system:

    LANG=en_US.UTF-8
    LANGUAGE=
    LC_CTYPE=en_US.UTF-8
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE=C
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=

**Comment by danieljuhl** [comment]
Remember to get a fresh terminal after the change.. have you done that, @wong2 ?

**Comment by woozyking** [comment]
I also get that not through command line but through running it using node.js (v5.5) `child_process.execFile` and this warning would be given through `stderr` stream despite being a warning. Before the child process `execFile`, there's another layer of `express.js` based API that accepts some parameters and a `kue` job framework to enqueue a job that eventually invokes the aforementioned `execFile`.

The weird thing is that if I invoke the `execFile` portion directly using command line, I wouldn't get this warning at all.

**Comment by SarkarSubhajit** [comment]
I also faced same problem with DigitalOcean Ubuntu server. I fixed this using below commands:

`sudo vim /etc/environment`

Add below lines to the bottom of the "environment" file:

```
LANG="en_US.UTF-8"
LC_MESSAGES="C"
LC_ALL="en_US.UTF-8"
```

Now restart the OS and check `locale` and you will get:

```
LANG=en_US.UTF-8
LANGUAGE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

Wola! You all set. 

Hope this will help you.

Thanks.

**Comment by forestallers** [comment]
@danieljuhl  solution works for me, Just reboot also the machine

**Comment by danieljuhl** [comment]
@forestallers or if connecting to a Remote machine through ssh, logout and login again (might also be enough locally

**Comment by safaorhan** [comment]
Still has this problem on Ubuntu 14.04.

Output of `locale` after reboot:
```
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by sudarsanps** [comment]
I always get this same error , Fontconfig warning: ignoring UTF-8: not a valid region tag
i had installed UTF8 and when i list locale,I get the following
LANG=C.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

I have tired all the other options listed above.still the result is same.How to solve this issue

**Comment by sudarsanps** [comment]
Hi, I have solved the above issue by doing the following:

**sudo apt-get install language-pack-en-base**
**sudo dpkg-reconfigure locales**
after this do:
 **sudo reboot**
