### ISSUE TITLE
PhantomJS 1.9.8 randomly crashes on getters and setters.

### ISSUE THREAD

**Issue by Jedrski** [ariya/phantomjs#13439]
Hello,
The problem seems to occur when a setter of a property which is an object does something to the new value object AND another property uses that property, referencing not the variable holding the value of the property, but the property (getter) itself.

The code below (run inside Webstorm karma  (jasmine)) randomly causes PhantomJS.

I could only reproduce this on OSX, so sadly I can't provide a stacktrace.

```javascript
describe('failcase', function () {
        var someProp = {},
            someObj = {
                get someOtherProp() {
                    return this.someProp.check || false;
                },
                get someProp() {
                    return someProp;
                },
                set someProp(newValue) {
                    newValue.check = true;

                    someProp = newValue;
                }
            };

        beforeEach(function () {
            someObj.someProp = {};
        });

        it('should not crash', function () {
            expect(someObj.someOtherProp).toBeTruthy();
        });
    });
```

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
