### ISSUE TITLE
C3 charts blurred when printing through phantomjs (LINUX).

### ISSUE THREAD

**Issue by preshitbakre** [ariya/phantomjs#13435]
The issue that I am facing is that when I render c3 Charts using phantomjs(v-1.9.8) in a Linux system, the charts get blurred. However the chart rendering is sharp and clear in Windows system using phantomjs(v-2.0.0).

**Comment by swamiman** [comment]
I had a similar issue, I found that by removing all but the first `<def>` elements under the `<svg>` for the chart makes it so printing of text will be sharp.

**Comment by preshitbakre** [comment]
Thanks @swamiman.

I found using phantomjs (v-2.0.0) build at the following link : 

http://www.datafilehost.com/d/07ca4477

Using this build, the blurring problem was solved.
I would suggest using v-2.0.0 because then the script for creating the chart does not need to be changed and a uniformity can be maintained for different charts.


Since this issue has been solved, I am closing the issue.
