### ISSUE TITLE
We ran into an issue that seams to be an issue with phantomJS

### ISSUE THREAD

**Issue by Giszmo** [ariya/phantomjs#13431]
Is this the way to get the bug to the right devs' attention?

@cmgustavo and I ran into [this issue](https://github.com/bitpay/angular-bitcore-wallet-client/issues/3).

**Comment by cmgustavo** [comment]
I read that it was solved in v2.0, but it was not published on npm.org (https://www.npmjs.com/package/phantomjs)

**Comment by cmgustavo** [comment]
https://github.com/ariya/phantomjs/issues/10522#issuecomment-72705658

**Comment by Giszmo** [comment]
https://bitbucket.org/ariya/phantomjs/downloads doesn't list v2.0 for linux yet. :(

Looking forward to looking into this at a later time. Anyway, good to know it might be fixed soonish.

**Comment by ariya** [comment]
`bind` is already support in 2.0. Watch the website if you need a binary package.
