### ISSUE TITLE
Provide programmatic access to the remote debugger port

### ISSUE THREAD

**Issue by nex3** [ariya/phantomjs#13432]
In [the Dart test runner](https://github.com/dart-lang/test), we run PhantomJS as a subprocess for automatic testing. We want to support remote debugging, but the way our infrastructure works means it doesn't make sense for users to explicitly pass in a port. If we pass in a particular port number, that runs the risk of collisions or race conditions, so we'd like to pass in 0 to get the OS to auto-assign a free port. Unfortunately, once this happens, there's no way to figure out the actual port that was bound.

It would be great if the API would expose this port somehow if it's bound (for example, `phantom.remoteDebuggerPort`). This could also be useful for PhantomJS scripts reacting to the existence of a remote debugger or presenting the user with a link to one.

**Comment by iradul** [comment]
This is doable but you'll have to modify some core webkit classes so I don't know if that will be acceptable, but you can always fork. Anyway [here](https://github.com/ariya/phantomjs/blob/master/src/qt/qtwebkit/Source/WebKit/qt/WebCoreSupport/InspectorServerQt.cpp#L89) you can catch the actual port number:
```cpp
void InspectorServerQt::listen(quint16 port)
{
    if (m_tcpServer)
        return;

    m_tcpServer = new QTcpServer();
    m_tcpServer->listen(QHostAddress::Any, port);
    connect(m_tcpServer, SIGNAL(newConnection()), SLOT(newConnection()));
    // this will give you the actual port number: m_tcpServer->serverPort()
}
```

**Comment by Vitallium** [comment]
Landed in master (https://github.com/ariya/phantomjs/commit/14d53ce1aad070fc02a804de9e5e6bc72464383c). Thanks!
