### ISSUE TITLE
Add BMP support to webpage.render

### ISSUE THREAD

**Issue by dcworldwide** [ariya/phantomjs#13438]
On my macbook (retina display), JPG and PNG quality (setting of 100) looks poor. Please allow us to export the raw screen data (BMP)

**Comment by ariya** [comment]
Can you double check? PNG output is lossless so it should be as pixel perfect as possible.

**Comment by dcworldwide** [comment]
I don't have access to my env atm, I"ll confirm once i revisit the project. That makes sense. It is probably my ffmpeg cfg then.
