### ISSUE TITLE
Does phantomjs support service workers?

### ISSUE THREAD

**Issue by remkoboschker** [ariya/phantomjs#13437]
I'm trying to test using service workers with localforage. They use phantomjs for the unit tests. I run into navigator.serviceWorker.register is undefined in phantomjs. The tests run fine in Chrome en Firefox nightly. I cannot find any documentation on serviceworker support in phantomjs. It is not listed here http://trac.webkit.org/wiki/QtWebKitFeatures22#WebDeveloperFeatures . Does that mean it is not supported?

**Comment by Vitallium** [comment]
Unfortunately, PhantomJS doesn't support service workers.

**Comment by CodersBrothers** [comment]
News about this?

**Comment by Arveti** [comment]
Any update on this?
