### ISSUE TITLE
Drag & Drop issue still unsolved?

### ISSUE THREAD

**Issue by 7nights** [ariya/phantomjs#13448]
I've searched for a solution to simulate drag & drop for a long time. But since the document says:

> For 'mousemove', however, there is no button pressed (i.e. it is not dragging).

It seems to be no way to do this thing? I find that someone said they found a solution (https://github.com/ariya/phantomjs/issues/10586), but it seems that they still have problems with their implementation(I tried to look for their code but got a 404 page) and it never works for me.

Does anyone have a workaround?

**Comment by lidel** [comment]
I got Drag&Drop tests working under Selenium+[Nightwatch](http://nightwatchjs.org)+PhantomJS.

My versions:

    ├── nightwatch@0.6.15 
    ├── phantomjs@1.9.18 
    └── selenium-standalone@4.6.1

To simulate drag&drop from `#foo` to `#bar`:

```javascript
  browser
//(...)
  .moveToElement('#foo',5,5)
  .mouseButtonDown('left')
  .moveToElement('#bar',5,5)
  .mouseButtonUp('left')
```

References:

- http://nightwatchjs.org/api#moveToElement
- http://nightwatchjs.org/api#mouseButtonUp
- http://nightwatchjs.org/api#mouseButtonDown
