### ISSUE TITLE
PhantomJS crashes with "http://stumbleupon.com"

### ISSUE THREAD

**Issue by suoloordi** [ariya/phantomjs#13441]
This is my script:

``` javascript
var page_module = require('webpage');
var system = require('system');
var page = page_module.create();
page.settings = {
        resourceTimeout: 1000 * 10,
        loadImages: true,
        javascriptEnabled: true,
        webSecurityEnabled: false
    },
console.log('visiting ' + system.args[1]);
page.open('http://' +  system.args[1], function(status) {
    console.log(system.args[1] + " status: " + status);
    phantom.exit(0);
});
```

I run the script like below:

```
phantomjs test.js stumbleupon.com
```

This is the crash dump:
https://www.dropbox.com/s/btir5k1dbv2v8v1/7cddb649-0984-08ea-021fa0f0-6ca0ac4d.dmp?dl=0

I'm running Xubuntu 15.04. I've also tested the same script in Windows, and it seems to work fine there.

**Comment by Vitallium** [comment]
PhantomJS version?

**Comment by suoloordi** [comment]
It's version 2.0

**Comment by kekda** [comment]
The following day we took leave of our hosts. We decided toreturn, inasmuch as our mission was accomplished; and TushegounLama explained to us that he would "move through space." Hewandered over all Mongolia, lived both in the single, simple yurtaof the shepherd and hunter and in the splendid tents of the princesand tribal chiefs, surrounded by deep veneration and panic-fear,enticing and cementing to him rich and poor alike with his miraclesand prophecies. When bidding us adieu, the Kalmuck sorcerer slylysmiled and said:"Do not give any information about me to the Chinese <a href="http://cocinatuidea.org/">Cheap Jordans</a> authorities."Afterwards he added: "What happened to you yesterday evening was afutile demonstration. You Europeans will not recognize that wedark-minded nomads possess the powers of mysterious science. Ifyou could only see the miracles <a href="http://centoolio.de/">Diesel Jeans</a> and power of the Most Holy TashiLama, href="http://www.noltecanada.com/">Canada Goose</a> when at his command the lamps and candles before the ancientstatue of Buddha light themselves and when the ikons of the godsbegin to speak and prophesy! But there exists a more powerful andmore holy man. . .""Is it the King <a href="http://www.dreamstock.us/">Livres</a> of the World in Agharti?" I interrupted.He stared and glanced at me in amazement."Have you heard <a 
href="http://showlace.com/">Pittstown New York Website</a> about him?" <a href="http://www.yourselfesteemcoach.com/">Coach Outelt</a> he asked, as his brows knit in thought.After a few seconds he raised his narrow eyes and said: "Only oneman knows his <a
href="http://www.alphatools.ca/">Cheap Jordans</a>

 holy name; only one man now living was ever inAgharti. That is I. This is the reason why the Most Holy DalaiLama has honored me and why the Living Buddha in Urga fears me. <a href="http://www.diesterwegstiftung-solingen.de/">Stiftungsneuigkeiten Solingen</a> undefined
