### ISSUE TITLE
Date doesn't have method Format.

### ISSUE THREAD

**Issue by chenwery** [ariya/phantomjs#13445]
code:
```
new Date('2015-07-29 11:30:00').getMonth()
```
this works in webbrowser but not in phantomjs?

**Comment by Vitallium** [comment]
`Date` has no function `Format`. (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date)
I think you have 3rd party JavaScript on your target web page that extends it.

**Comment by chenwery** [comment]
@Vitallium Oops! You're right, but I've found that ```new Date('2015-07-29 11:30:00').getMonth()```returns NaN.

**Comment by abobwhite** [comment]
I am having problems with Date.format(). It works in browsers but looks the format method doesn't work in PhantomJS (undefined)

Something like this doesn't work:
```
var today = new Date();
today.format('MM/dd/yyyy')
```

**Comment by zackw** [comment]
@chenwery The Date parser is very picky.  You can do `new Date('2015-07-29T11:30:00')` but not `new Date('2015-07-29 11:30:00')`.  As far as I can tell this is required by the JS language specification.  Sorry.
