### ISSUE TITLE
 phantomjs 2 uses websocket RFC 6455?

### ISSUE THREAD

**Issue by italking** [ariya/phantomjs#13446]
it does not work with tomcat8

**Comment by vercha** [comment]
I have same issue, I'm doing test with mocha-phantomjs;
node version: 4.4.7;  phantomjs: 2.1.1;
but 
![image](https://cloud.githubusercontent.com/assets/13897098/23884605/b18c5e38-08a8-11e7-884c-cbbbc46b084e.png)
it seems that phantomjs opened websocket but not connected successfully. I'm really confused with it, looking forward to some good suggestions.  Thanks !
