### ISSUE TITLE
Phantom crashing when trying to render as PDF a page full of SVG

### ISSUE THREAD

**Issue by jpvincent** [ariya/phantomjs#13456]
Hi

I'm trying to render as PDF a page containing a long list of JSON data, interpreted by highcharts, that renders graphics in SVG.

I'm on a mac so I could not convert to a stack trace.

**Comment by jpvincent** [comment]
I could not upload the dump directly on github, so please find the dump on this URL : http://dl.free.fr/bzsP9RUh3
 (will be available 30 days starting from the last download)

**Comment by zackw** [comment]
I'm afraid a stack trace by itself does not give us nearly enough information to attempt to fix the bug.  We need a minimized test case: ideally a single self-contained `.html` file which, when rendered, triggers the same crash, and which has been made as small as possible.  (If there's no way to pack everything into one file, a group of files is also acceptable. References to resources on servers, however, are not OK - they can change without notice and that might perturb the bug out of visibility.)

We also need to know whether you are using PhantomJS 1.x or 2.x.

Finally, a crash like this is almost certainly a bug in Webkit.  We do not have the manpower to fix bugs in Webkit ourselves.  Please also try to reproduce the problem with a [Webkit nightly build](http://nightly.webkit.org/) and if you can, report the bug in [their bug tracker](https://www.webkit.org/quality/reporting.html).  (They will also want a minimized test case.)

**Comment by jpvincent** [comment]
I have the 1.9.8 version installed.
By minimizing the test case, I have it working without crashing, so it seems to depend on the amount of data the page contains.
The page itself has to change soon, so I will first modify it, and if it still crashed, re-open this ticket

thanks for the answer !

**Comment by zackw** [comment]
We're not doing development on 1.9.x anymore, and 2.x has a _much_ newer
Webkit that may have solved the problem, I strongly recommend you try it.
