### ISSUE TITLE
Add system.stdout.isTTY property

### ISSUE THREAD

**Issue by astefanutti** [ariya/phantomjs#13454]
In some use cases, this is useful to detect whether PhantomJS is run inside a TTY context. This is similar to Node.js [`process.stdout.isTTY`](https://nodejs.org/api/tty.html#tty_tty).

**Comment by tylfin** [comment]
I'll take a look into this, @Vitallium any extra details or you can provide would be great!

**Comment by tylfin** [comment]
In progress https://github.com/ariya/phantomjs/pull/14578
