### ISSUE TITLE
phamtomjs 2.0 debug verison in win7 crash

### ISSUE THREAD

**Issue by wangzhenxing** [ariya/phantomjs#13451]
![image](https://cloud.githubusercontent.com/assets/6202268/9025710/f0a15ff6-3942-11e5-981e-f096a86852b7.png)
when running " page.sendEvent('click', params.x, params.y, 'right');", crash comes

**Comment by Vitallium** [comment]
If you want to produce a valid crash dump, you must compile PhantomJS in debug mode. Otherwise, you can't do much.

**Comment by wangzhenxing** [comment]
as the issue title said, i have compile PhantomJS 2.0 in debug mode in win7, see the detail(https://github.com/ariya/phantomjs/issues/13339#issuecomment-126891758)
