### ISSUE TITLE
2.0 release running remote-debugger on win7 always comes up with 404

### ISSUE THREAD

**Issue by hmh-the-one** [ariya/phantomjs#13455]
Browse http://127.0.0.1:9001/, the page shows as below:
![image](https://cloud.githubusercontent.com/assets/13616513/9032740/4342cb1c-39f4-11e5-8e83-05bc77e2cc05.png)
The about:blank list item is not shown as expected
And when click "https://github.com/" and navigate to http://127.0.0.1:9001/webkit/inspector/inspector.html?page=2, it comes up with "404 Not OK", and http://127.0.0.1:9001/webkit/inspector/inspector.html?page=1 is 404 too.

However, if use PhantomJS 1.9.X(1.9.8) instead, everything is just fine, I can browse and debug.

**Comment by Vitallium** [comment]
Duplicate. Please see #12864
