### ISSUE TITLE
Processing of scripts is not sychronous

### ISSUE THREAD

**Issue by drmuey** [ariya/phantomjs#13450]
Given markup containing this:

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<script type="text/javascript">
    $( document ).ready(function() {
          console.log("Oh hai!");
    });
</script>
```

If done in a browser I get the console.log(). Yeah it works!

Run that through `phantomjs` though and the console.log() does not happen; instead you get errors like:

```
Error: Bootstrap's JavaScript requires jQuery

  https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js:6 in global code
ReferenceError: Can't find variable: $

  file:///…/html.html:8 in global code
```

It behaves like the processing of the HTML happens without [waiting for the script's to load and execute](http://taligarsiel.com/Projects/howbrowserswork1.htm#Scripts).

That conclusion seems to fit with order that netlog.js outputs the 'recieved' info which is bootstrap.min.js then jquery.min.js.

**Comment by santiagomdq** [comment]
I have the same problem.

**Comment by drmuey** [comment]
Of note, its not a matter of using waitFor(), includeJs(), or injectJs().

waitFor() is moot since the things we are waiting for are happening in the wrong order.

For includeJs() or injectJs() we'd have to load the HTML, parse out all scripts, includeJs() or injectJs()  them all, then re-load the HTML with those already loaded. Lots of work and I am not sure you can pre includeJs() or injectJs() into a page before you load it (if you can't then those would be as moot as waitFor() since it'd all still be happening out of order before you could includeJs() or injectJs()).

**Comment by codyrigney92** [comment]
I also have the same problem.

**Comment by checkphi** [comment]
I have the same problem. Is there any solution so far?

**Comment by codyrigney92** [comment]
@checkphi It's been a while, but I think the solution for us was to upgrade to PhantomJS 2

**Comment by checkphi** [comment]
@codyrigney92 We tried to today with 2.1.1

**Comment by codyrigney92** [comment]
@checkphi If the issue is similar to this: https://github.com/electron/electron/issues/254
You could try doing this after your jquery script tag:
`window.$ = window.jQuery = module.jQuery;`

I'm curious if this would fix it, so please let me know!

**Comment by waissbluth** [comment]
Did anybody figure out a fix for this?

**Comment by waissbluth** [comment]
For future reference: the problem is not that resources are loading out of order, it is that they are not loading at all (likely due to SSL errors). See https://github.com/ariya/phantomjs/issues/12440

**Comment by drmuey** [comment]
@waissbluth thanks for the info! In this case I don't think #12440 is the root cause because:
* I don’t see any SSL warnings or errors
* the URLs in question come from companies unlikely to allow a CRT issue to last for long
* using non SSL has the same behavior
