### ISSUE TITLE
Print an error if binding the remote debugger port doesn't work

### ISSUE THREAD

**Issue by nex3** [ariya/phantomjs#13466]
Currently if `--remote-debugger-port` is passed with a port that's already bound by some other process, PhantomJS will just silently fail to bind it. It would be clearer and more helpful if it emitted an error, either on stderr or via `phantom.onError`.

See also #13432.

**Comment by Vitallium** [comment]
I think it should be fixed by https://github.com/ariya/phantomjs/pull/13444

/cc @iradul

**Comment by iradul** [comment]
@Vitallium yes it should, although phantom will not throw an error, but ```phantom.remoteDebugPort``` will return 0 when binding to specified port fails.

**Comment by Vitallium** [comment]
@iradul great! I think it's ok if it returns 0, we can print warning to stderr. Let's merge your PR ASAP. I would like to see it in 2.0.1

**Comment by iradul** [comment]
@Vitallium I just added warning message. Thanks.

**Comment by Vitallium** [comment]
Landed in `master` https://github.com/ariya/phantomjs/commit/14d53ce1aad070fc02a804de9e5e6bc72464383c Thanks!
