### ISSUE TITLE
page.url encoding problem

### ISSUE THREAD

**Issue by kodentsev** [ariya/phantomjs#13468]
I'm trying to get two params with phantomjs (location, title) from urls. Some of that urls have russian characters in them. Urls titles also have russian characters. As the result, I have no problem with titles and a big problem with locations encoding (page.url). For example when I treat url http://terrareligiosa.jimdo.com/лекторий with such part of code

page.open(system.args[1], function (status) {
    console.log(system.args[1])
    console.log(page.url)
    console.log(page.title)
    phantom.exit();
});

I get an output

http://terrareligiosa.jimdo.com/лекторий
http://terrareligiosa.jimdo.com/????????
Главная - terrareligiosas Jimdo-Page!

**Comment by iradul** [comment]
Try to encode URL before you call ```open``` function, something like this:
```javascript
var url = encodeURI(system.args[1]);
page.open(url, function (status) {
	console.log(system.args[1]);
	console.log(page.url);
	console.log(page.title);
	phantom.exit();
});
```

**Comment by zackw** [comment]
Same as #12216.
