### ISSUE TITLE
2.0 VS2013 compiler error

### ISSUE THREAD

**Issue by passage2011** [ariya/phantomjs#13469]
Compiling environment：
VS2013，QT5.3.2.

ERRORS:

error	4	error C2660: “QWebFrame::evaluateJavaScript”: Function does not accept 2 Parameters	E:\WorkSpace\boSoft\phantomjs-master\phantomjs-master\src\config.cpp	177	1	phantomjs
error	5	error C2039: “PrintCallback”: 不是“QWebFrame”的成员	e:\workspace\bosoft\phantomjs-master\phantomjs-master\src\webpage.h	49	1	phantomjs
error	6	error C2504: “PrintCallback”: undefined base class	e:\workspace\bosoft\phantomjs-master\phantomjs-master\src\webpage.h	49	1	phantomjs
error	7	error C2039: “PrintCallback”: 不是“QWebFrame”的成员	E:\WorkSpace\boSoft\phantomjs-master\phantomjs-master\src\Debug\moc_webpage.cpp	657	1	phantomjs
error	8	error C2061: 语法错误: 标识符“PrintCallback”	E:\WorkSpace\boSoft\phantomjs-master\phantomjs-master\src\Debug\moc_webpage.cpp	657	1	phantomjs
error	9	error C2039: “PrintCallback”: 不是“QWebFrame”的成员	e:\workspace\bosoft\phantomjs-master\phantomjs-master\src\webpage.h	49	1	phantomjs
error	10	error C2504: “PrintCallback”: undefined base class	e:\workspace\bosoft\phantomjs-master\phantomjs-master\src\webpage.h	49	1	phantomjs
error	11	error C2660: “QWebFrame::evaluateJavaScript”: Function does not accept 2 Parameters	E:\WorkSpace\boSoft\phantomjs-master\phantomjs-master\src\phantom.cpp	380	1	phantomjs
error	12	error C2660: “QWebFrame::evaluateJavaScript”: Function does not accept 2 Parameters	E:\WorkSpace\boSoft\phantomjs-master\phantomjs-master\src\phantom.cpp	452	1	phantomjs
error	13	error C2660: “QWebFrame::evaluateJavaScript”: Function does not accept 2 Parameters	E:\WorkSpace\boSoft\phantomjs-master\phantomjs-master\src\repl.cpp	150	1	phantomjs
error	14	error C2660: “QWebFrame::evaluateJavaScript”: Function does not accept 2 Parameters	E:\WorkSpace\boSoft\phantomjs-master\phantomjs-master\src\repl.cpp	189	1	phantomjs
error	15	error C2228: “.toStringList”的左边必须有类/结构/联合	E:\WorkSpace\boSoft\phantomjs-master\phantomjs-master\src\repl.cpp	189	1	phantomjs
error	16	error C2660: “QWebFrame::evaluateJavaScript”: Function does not accept 2 Parameters	E:\WorkSpace\boSoft\phantomjs-master\phantomjs-master\src\repl.cpp	213	1	phantomjs
error	17	error C2660: “QWebFrame::evaluateJavaScript”: Function does not accept 2 Parameters	E:\WorkSpace\boSoft\phantomjs-master\phantomjs-master\src\utils.cpp	136	1	phantomjs
error	18	error C2660: “QWebFrame::evaluateJavaScript”: Function does not accept 2 Parameters	E:\WorkSpace\boSoft\phantomjs-master\phantomjs-master\src\utils.cpp	155	1	phantomjs
error	19	error C2039: “PrintCallback”: 不是“QWebFrame”的成员	e:\workspace\bosoft\phantomjs-master\phantomjs-master\src\webpage.h	49	1	phantomjs
error	20	error C2504: “PrintCallback”: undefined base class	e:\workspace\bosoft\phantomjs-master\phantomjs-master\src\webpage.h	49	1	phantomjs
error	21	error C1083: Could not open include file:“QPrinter”: No such file or directory	E:\WorkSpace\boSoft\phantomjs-master\phantomjs-master\src\webpage.cpp	46	1	phantomjs

**Comment by passage2011** [comment]
two errors:
1、“QWebFrame::evaluateJavaScript”: Function does not accept 2 Parameters config.cpp 177 
2、“PrintCallback”: is not the member of “QWebFrame”   src\webpage.h 49

**Comment by zackw** [comment]
Did you replace the Qt bundled with PhantomJS with Qt 5.3? That's not supported.

**Comment by Vitallium** [comment]
I don't think we should treat is as a bug. I'd rather label it as `Declined`.

**Comment by zackw** [comment]
@Vitallium Well, we don't *know* that's what the OP did, yet.  It could genuinely be a problem with our code under VS2013.  Unless that's what you use?

**Comment by Vitallium** [comment]
@zackw I use VS2013 right now. And it works fine. The OP tries to compile PhantomJS with vanilla Qt version.

**Comment by zackw** [comment]
Oh, ok, go ahead and close it out then.
