### ISSUE TITLE
phantomjs 1.9x and 2 do not render utf8 chars on centos7

### ISSUE THREAD

**Issue by DerManoMann** [ariya/phantomjs#13464]
Hi there,

I've been trying to convert japanese web pages to PDF using the rasterize.js example. This does work on centos5/6 but not on centos7.

I've checked that japanese fonts are installed and rendering the same page as image does work fine.

**Comment by DerManoMann** [comment]
I should perhaps add that I tried 1.9.2, 1.9.8 and 2.0.0, all compiled locally without any issues

**Comment by DerManoMann** [comment]
After further testing it turns out that the rasterize.js example also fails to render japanese chars in a png.
I am pretty sure that it is not a fonts issue as another custom script can scrape the same page correctly.

**Comment by englianhu** [comment]
I follow below procedures, there is below error
http://phantomjs.org/build.html

```g++: internal compiler error: Killed (program cc1plus)```
```Please submit a full bug report,```
```with preprocessed source if appropriate.```
```See <http://bugzilla.redhat.com/bugzilla> for instructions.```
```make[2]: *** [.obj/inspector/InspectorAllInOne.o] Error 4```
```make[2]: Leaving directory `/home/ryoeng/phantomjs/src/qt/qtwebkit/Source/WebCore'```
```make[1]: *** [sub-Target-pri-make_first-ordered] Error 2```
```make[1]: Leaving directory `/home/ryoeng/phantomjs/src/qt/qtwebkit/Source/WebCore'```
```make: *** [sub-Source-WebCore-WebCore-pro-make_first-ordered] Error 2```

after run ```./build.sh``` in

```git clone git://github.com/ariya/phantomjs.git```
```cd phantomjs```
```git checkout 2.0```
```./build.sh```

**Comment by pablomoreno61** [comment]
I have the same problem, with Phantom 1.9.7, my letters are displayed like square boxes

**Comment by DerManoMann** [comment]
Found something that works for me. In addition to 
````
yum groupinstall Japanese Support
````

I had to install these fonts:
````
yum install cjkuni-fonts-common cjkuni-ukai-fonts cjkuni-uming-fonts
````

**Comment by ldeavila** [comment]
I made my own 2.0 and 1.9.7 builds on my centOS7 system and have the same square box issue. I'm just trying to get the pdf to generate a "hello world"

Based on what @DerManoMann has said maybe we are missing some font module?

**Comment by DerManoMann** [comment]
I think it is the responibility of the OS to provide the fonts. 
So, IMO the language groupinstall for CentOS7 is broken.

**Comment by ldeavila** [comment]
Eureka! I just solved the issue. It looks like I was missing some font modules. Was going to switch over to wkhtmltopdf and while installing it it complained that I was missing libXext libXrender xorg-x11-fonts-Type1 xorg-x11-fonts-75dpi. Installed those and on a hunch re-tested phantom and booya! It worked.

Now, that was with version 1.9.7 because like a dummy I deleted my 2.0.0 build. Sigh.

So... solution for me was:
`yum install libXext libXrender xorg-x11-fonts-Type1 xorg-x11-fonts-75dpi`

**Comment by ariya** [comment]
@DerManoMann Can you see if the solution from @ldeavila also works for you?

**Comment by DerManoMann** [comment]
Oh, sorry, I really should have closed this after my second last comment. Adding these additional fonts fixed things to me:

````
yum install cjkuni-fonts-common cjkuni-ukai-fonts cjkuni-uming-fonts
````

I suspect they are dependencies on what @ldeavila installed.

Bottom line for me is that with CentOS7 the group install is missing some libraries (at least compared to CentOS6), so this is an OS issue.

However, some documentation about additional fonts required would be good, IMO
