### ISSUE TITLE
phantomjs-1.9.7 crashes on Linux (AWS c3.xlarge)

### ISSUE THREAD

**Issue by ambirag** [ariya/phantomjs#13462]
Hi
Using Phantomjs-1.9.7 on Linux (AWS c3.xlarge) for running js unit test as part of our build.
Sometimes it crashes twith the following message:

PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/12728d2e-1b45-d6db-3eb6d192-4cdd94fd.dmp
08:49:27 :xxxx:compileTestJava FAILED

load on the CPU was comming down from 100% to 40% when this happened.

I have followed the crash reporting and attached the output

[root@ip-xx-x-xx-xx phantomjs-1.9.7-linux-x86_64-symbols]# ./minidump_stackwalk /tmp/12728d2e-1b45-d6db-3eb6d192-4cdd94fd.dmp . 2>/dev/null
Operating system: Linux
                  0.0.0 Linux 3.14.48-33.39.amzn1.x86_64 #1 SMP Tue Jul 14 23:43:07 UTC 2015 x86_64
CPU: amd64
     family 6 model 62 stepping 4
     16 CPUs

Crash reason:  SIGSEGV
Crash address: 0x0

Thread 0 (crashed)
 0  phantomjs-unix + 0x18fe60c
    rbx = 0x00007ffd956d7090   r12 = 0x000000000481acc0
    r13 = 0x0000000004819890   r14 = 0x00007ffd956d7090
    r15 = 0x0000000004841a00   rip = 0x0000000001cfe60c
    rsp = 0x00007ffd956d6fa0   rbp = 0x0000000004819890
    Found by: given as instruction pointer in context
 1  phantomjs-unix + 0xed29
    rip = 0x000000000040ed2a   rsp = 0x00007ffd956d6fc0
    Found by: stack scanning
 2  libc-2.17.so + 0x3ba75f
    rip = 0x00007f50bfa9b760   rsp = 0x00007ffd956d6ff0
    Found by: stack scanning
 3  phantomjs-unix + 0x1958c5f
    rip = 0x0000000001d58c60   rsp = 0x00007ffd956d7018
    Found by: stack scanning
 4  libc-2.17.so + 0x8012b
    rip = 0x00007f50bf76112c   rsp = 0x00007ffd956d7020
    Found by: stack scanning
 5  libstdc++.so.6.0.19 + 0x5edac
    rip = 0x00007f50c0018dad   rsp = 0x00007ffd956d7040
    Found by: stack scanning
 6  phantomjs-unix + 0xf27d
    rip = 0x000000000040f27e   rsp = 0x00007ffd956d7090
    Found by: stack scanning
 7  phantomjs-unix + 0xf33f
    rip = 0x000000000040f340   rsp = 0x00007ffd956d70c0
    Found by: stack scanning
 8  phantomjs-unix + 0x152f06
    rip = 0x0000000000552f07   rsp = 0x00007ffd956d70f0
    Found by: stack scanning
 9  phantomjs-unix + 0x1958c5f
    rip = 0x0000000001d58c60   rsp = 0x00007ffd956d7198
    Found by: stack scanning
10  phantomjs-unix + 0xb00439
    rip = 0x0000000000f0043a   rsp = 0x00007ffd956d71f0
    Found by: stack scanning
11  phantomjs-unix + 0xb08797
    rip = 0x0000000000f08798   rsp = 0x00007ffd956d7240
    Found by: stack scanning
12  phantomjs-unix + 0xe0a3f
    rip = 0x00000000004e0a40   rsp = 0x00007ffd956d7250
    Found by: stack scanning
13  phantomjs-unix + 0x103afc4
    rip = 0x000000000143afc5   rsp = 0x00007ffd956d72b0
    Found by: stack scanning
14  phantomjs-unix + 0xb1159b
    rip = 0x0000000000f1159c   rsp = 0x00007ffd956d7300
    Found by: stack scanning
15  phantomjs-unix + 0xb0df60
    rip = 0x0000000000f0df61   rsp = 0x00007ffd956d73f0
    Found by: stack scanning
16  phantomjs-unix + 0x104486e
    rip = 0x000000000144486f   rsp = 0x00007ffd956d74a0
    Found by: stack scanning
17  phantomjs-unix + 0x1068fff
    rip = 0x0000000001469000   rsp = 0x00007ffd956d74b0
    Found by: stack scanning
18  phantomjs-unix + 0xb1577c
    rip = 0x0000000000f1577d   rsp = 0x00007ffd956d7560
    Found by: stack scanning

Thread 1
 0  libc-2.17.so + 0xbd4ed
    rbx = 0x00007f50b7576cc0   r12 = 0x00007f50b7576d40
    r13 = 0x00007f50b75779c0   r14 = 0x00007f50b7577700
    r15 = 0x0000000000000000   rip = 0x00007f50bf79e4ed
    rsp = 0x00007f50b7576ca0   rbp = 0x00000000ffffffff
    Found by: given as instruction pointer in context
 1  libc-2.17.so + 0xbd383
    rip = 0x00007f50bf79e384   rsp = 0x00007f50b7576cb0
    Found by: stack scanning
 2  phantomjs-unix + 0x2e2c
    rip = 0x0000000000402e2d   rsp = 0x00007f50b7576d50
    Found by: stack scanning
 3  libc-2.17.so + 0xe82f
    rip = 0x00007f50bf6ef830   rsp = 0x00007f50b7576d68
    Found by: stack scanning
 4  phantomjs-unix + 0x18b5c6f
    rip = 0x0000000001cb5c70   rsp = 0x00007f50b7576dc8
    Found by: stack scanning
 5  libc-2.17.so + 0x36f3
    rip = 0x00007f50bf6e46f4   rsp = 0x00007f50b7576dd8
    Found by: stack scanning
 6  libc-2.17.so + 0xe82f
    rip = 0x00007f50bf6ef830   rsp = 0x00007f50b7576de0
    Found by: stack scanning
 7  phantomjs-unix + 0x2e2c
    rip = 0x0000000000402e2d   rsp = 0x00007f50b7576e20
    Found by: stack scanning
 8  libc-2.17.so + 0x10d07
    rip = 0x00007f50bf6f1d08   rsp = 0x00007f50b7576e28
    Found by: stack scanning
 9  phantomjs-unix + 0x24c7
    rip = 0x00000000004024c8   rsp = 0x00007f50b7576e30
    Found by: stack scanning
10  libpthread-2.17.so + 0xf12f
    rip = 0x00007f50c02cd130   rsp = 0x00007f50b7576e58
    Found by: stack scanning
11  phantomjs-unix + 0xdda2d
    rip = 0x00000000004dda2e   rsp = 0x00007f50b7576e90
    Found by: stack scanning
12  phantomjs-unix + 0xddc98
    rip = 0x00000000004ddc99   rsp = 0x00007f50b7576f10
    Found by: stack scanning
13  libpthread-2.17.so + 0x7df2
    rip = 0x00007f50c02c5df3   rsp = 0x00007f50b7576f20
    Found by: stack scanning
14  libc-2.17.so + 0xf61bc
    rip = 0x00007f50bf7d71bd   rsp = 0x00007f50b7576fc0
    Found by: stack scanning

Thread 2
 0  libc-2.17.so + 0xed943
    rbx = 0x0000000000000000   r12 = 0x00007f50b6d75df0
    r13 = 0x0000000000000008   r14 = 0x00007f5070000a98
    r15 = 0x00007f5070000d30   rip = 0x00007f50bf7ce943
    rsp = 0x00007f50b6d75bc0   rbp = 0x00007f50700008e0
    Found by: given as instruction pointer in context
 1  phantomjs-unix + 0x1906326
    rip = 0x0000000001d06327   rsp = 0x00007f50b6d75bd0
    Found by: stack scanning
 2  ld-2.17.so + 0x9593
    rip = 0x00007f50c0dc0594   rsp = 0x00007f50b6d75c20
    Found by: stack scanning
 3  phantomjs-unix + 0x19075e6
    rip = 0x0000000001d075e7   rsp = 0x00007f50b6d75c60
    Found by: stack scanning
 4  phantomjs-unix + 0x18f6ab6
    rip = 0x0000000001cf6ab7   rsp = 0x00007f50b6d75c80
    Found by: stack scanning
 5  phantomjs-unix + 0x18019c2
    rip = 0x0000000001c019c3   rsp = 0x00007f50b6d75c90
    Found by: stack scanning
 6  libc-2.17.so + 0x109dac
    rip = 0x00007f50bf7eadad   rsp = 0x00007f50b6d75cd0
    Found by: stack scanning
 7  phantomjs-unix + 0x1840b73
    rip = 0x0000000001c40b74   rsp = 0x00007f50b6d75ce0
    Found by: stack scanning
 8  phantomjs-unix + 0x1840a78
    rip = 0x0000000001c40a79   rsp = 0x00007f50b6d75d20
    Found by: stack scanning
 9  phantomjs-unix + 0x1906fa5
    rip = 0x0000000001d06fa6   rsp = 0x00007f50b6d75d30
    Found by: stack scanning
10  phantomjs-unix + 0x1908091
    rip = 0x0000000001d08092   rsp = 0x00007f50b6d75da0
    Found by: stack scanning
11  phantomjs-unix + 0x18dd4b4
    rip = 0x0000000001cdd4b5   rsp = 0x00007f50b6d75df0
    Found by: stack scanning
12  phantomjs-unix + 0x18ddca8
    rip = 0x0000000001cddca9   rsp = 0x00007f50b6d75e00
    Found by: stack scanning
13  phantomjs-unix + 0x18dd917
    rip = 0x0000000001cdd918   rsp = 0x00007f50b6d75e20
    Found by: stack scanning
14  phantomjs-unix + 0x17dfdf5
    rip = 0x0000000001bdfdf6   rsp = 0x00007f50b6d75e80
    Found by: stack scanning
15  phantomjs-unix + 0x17e2cc1
    rip = 0x0000000001be2cc2   rsp = 0x00007f50b6d75ed0
    Found by: stack scanning
16  libpthread-2.17.so + 0x7d93
    rip = 0x00007f50c02c5d94   rsp = 0x00007f50b6d75ee0
    Found by: stack scanning
17  locale-archive + 0x26f4b
    rip = 0x00007f50b8fb7f4c   rsp = 0x00007f50b6d75ee8
    Found by: stack scanning
18  libpthread-2.17.so + 0x7df2
    rip = 0x00007f50c02c5df3   rsp = 0x00007f50b6d75f20
    Found by: stack scanning
19  libc-2.17.so + 0xf61bc
    rip = 0x00007f50bf7d71bd   rsp = 0x00007f50b6d75fc0
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x0268dfff  phantomjs-unix  ???  (main)
0x7f50753a5000 - 0x7f507543ffff  DejaVuSansCondensed-Bold.ttf  ???
0x7f5075440000 - 0x7f50754ddfff  DejaVuSansCondensed.ttf  ???
0x7f50754e5000 - 0x7f50754f8fff  n019003l.pfb  ???
0x7f50b7578000 - 0x7f50b7796fff  libselinux.so.1  ???
0x7f50b7799000 - 0x7f50b79b0fff  libresolv-2.17.so  ???
0x7f50b79b3000 - 0x7f50b7bb5fff  libkeyutils.so.1.5  ???
0x7f50b7bb6000 - 0x7f50b7dc4fff  libkrb5support.so.0.1  ???
0x7f50b7dc5000 - 0x7f50b7ff5fff  libk5crypto.so.3.1  ???
0x7f50b7ff7000 - 0x7f50b81f9fff  libcom_err.so.2.1  ???
0x7f50b81fa000 - 0x7f50b84dcfff  libkrb5.so.3.3  ???
0x7f50b84dd000 - 0x7f50b8728fff  libgssapi_krb5.so.2.2  ???
0x7f50b8729000 - 0x7f50b8995fff  libssl.so.1.0.1k  ???
0x7f50b8996000 - 0x7f50b8babfff  libz.so.1.2.8  ???
0x7f50b8bac000 - 0x7f50b8f8cfff  libcrypto.so.1.0.1k  ???
0x7f50b8f91000 - 0x7f50bf4b7fff  locale-archive  ???
0x7f50bf4b8000 - 0x7f50bf6e0fff  libexpat.so.1.6.0  ???
0x7f50bf6e1000 - 0x7f50bfa9cfff  libc-2.17.so  ???
0x7f50bfaa2000 - 0x7f50bfcb7fff  libgcc_s-4.8.2-20140120.so.1  ???
0x7f50bfcb8000 - 0x7f50bffb9fff  libm-2.17.so  ???
0x7f50bffba000 - 0x7f50c02a8fff  libstdc++.so.6.0.19  ???
0x7f50c02be000 - 0x7f50c04d5fff  libpthread-2.17.so  ???
0x7f50c04da000 - 0x7f50c06e1fff  librt-2.17.so  ???
0x7f50c06e2000 - 0x7f50c08e5fff  libdl-2.17.so  ???
0x7f50c08e6000 - 0x7f50c0b1afff  libfontconfig.so.1.4.4  ???
0x7f50c0b1b000 - 0x7f50c0db6fff  libfreetype.so.6.3.22  ???
0x7f50c0db7000 - 0x7f50c0dd7fff  ld-2.17.so  ???
0x7f50c0fb1000 - 0x7f50c0fb9fff  b79f3aaa7d385a141ab53ec885cc22a8-le64.cache-3  ???
0x7f50c0fba000 - 0x7f50c0fc3fff  12b26b760a24f8b4feb03ad48a333a72-le64.cache-3  ???
0x7f50c0fd0000 - 0x7f50c0fd2fff  87f5e051180a7a75f16eb6fe7dbd3749-le64.cache-3  ???
0x7f50c0fd3000 - 0x7f50c0fd5fff  beeeeb3dfe132a8a0633a017c99ce0c0-le64.cache-3  ???
0x7ffd9574c000 - 0x7ffd9574dfff  linux-gate.so  ???
LONC02KK1U8FFT3:~$

**Comment by ariya** [comment]
Can you try it again with PhantomJS 2.1?

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.
