### ISSUE TITLE
Phantomjs Crashed.

### ISSUE THREAD

**Issue by famouscake** [ariya/phantomjs#13470]
The log told me to copy you the crash error log contents. Here is it. I was using it with phantomas. Since github is retaged and I can't attach a txt. Here you go.

**Comment by Vitallium** [comment]
You can upload it to any file sharing service or attach it as as image.

I stripped the crash dump from your comment to make it readable.

**Comment by FamousCake** [comment]
Life's too short Vitaly. I hope it helped anyways.

**Comment by Vitallium** [comment]
@FamousCake just re-upload your crash dump (follow my advice). And we'll have a look.
