### ISSUE TITLE
window.callPhantom is a misfeature

### ISSUE THREAD

**Issue by zackw** [ariya/phantomjs#13477]
It should not be possible for a webpage to detect that it has been loaded inside PhantomJS rather than some other Webkit-based browser (except by inspecting the user-agent, which can be overridden if the controller script so desires). `window.callPhantom` is a dead giveaway.

In addition, it is inflexible -- you only get one `onCallback` hook.  In a situation where you actually _want_ to have the page call an API exposed by the controller script, wouldn't it be nice if you could have that API consist of more than one function?

Better if `page.evaluate` could attach a function supplied by its caller to a window property, and that function would then execute in the controller context.

**Comment by zackw** [comment]
Note that in general I suspect PhantomJS provides inadequate isolation among page scripts, controller scripts, and `page.evaluate` functions.  Chrome and Firefox both enforce a hard privilege boundary between extension JS and page JS -- something analogous should be possible.

**Comment by JamesMGreene** [comment]
Not sure I agree that we want a hard divide... to me, the lack of one is what makes Phantom useful.

Also, please take a peek at https://gist.github.com/JamesMGreene/5693546 and let me know your thoughts (here, since Gists don't notify about comments)?

**Comment by zackw** [comment]
Our use cases must be very different.  It would help me understand if you could give some concrete examples of what you use controller/page communication for. I'm not opposed to the idea _in general_, but I feel that it really ought to be opt-in from the controller side.

Your gist is hard for me to understand because it's a lot of technical detail tied to polyfilling it in the PJS we have, and not much in the way of "what this API looks like from the webpage side" and "can this be subverted by a malicious webpage to execute arbitrary code in the controller context" and so forth?

**Comment by Vitallium** [comment]
@zackw here we go. Simple case is when you need to call a PhantomJS callback from your code. For example, you use PhantomJS to render your AngularJS application for search bots.
You need to *tell* PhantomJS when it can render a web page. In this case you just need to place `window.callPhantom` when you think your web page (AngularJS controller) is ready.
