### ISSUE TITLE
thumbnails on ubuntu 14.04 with phantomjs

### ISSUE THREAD

**Issue by procoder-net** [ariya/phantomjs#13485]
Hi,

When i run thumbnail on mac it works with the below code.

but on ubuntu i get negative cache error??

```
var page = require('webpage').create(); 
   page.open('http://sapui5.hana.ondemand.com/sdk/test-resources/sap/m/demokit/cart/index.html?responderOn=true', 
 function() { 
    page.render('github.png'); 
    phantom.exit(); 
 });
```

Error: found in negative cache: 'sap/ui/core/Core.js' from undefined/sap/ui/core/Core.js: The given language does not adhere to BCP-47. sapui5.netweaver.ondemand.com/resources/sap-ui-core.js:80 in a1 sapui5.netweaver.ondemand.com/resources/sap-ui-core.js:80 sapui5.netweaver.ondemand.com/resources/sap-ui-core.js:144 TypeError: 'undefined' is not an object (evaluating 'new sap.m.Shell') sapui5.netweaver.ondemand.com/test-resources/sap/m/demokit/cart/…

Please help!!!.

Thanks
Moyeen

**Comment by procoder-net** [comment]
can someone help??

**Comment by Vitallium** [comment]
I see there are errors in your JavaScript code. It might be typical error in the code. I think you should try to change the user agent of PhantomJS.

**Comment by procoder-net** [comment]
can you please give me example the same thing works in mac.
