### ISSUE TITLE
Phantomjs does not build on Fedora 22

### ISSUE THREAD

**Issue by giocomai** [ariya/phantomjs#13484]
All packages suggested at http://phantomjs.org/build.html have been installed. 
Python version, highlighted as possible problem in apparently similar build error - https://github.com/ariya/phantomjs/issues/12713 - shouldn't be an issue here: python version is 2.7.10

Last lines of the error message:

```
JSArray.cpp:(.text+0x3171): undefined reference to `void JSC::JSObject::putByIndexBeyondVectorLengthWithoutAttributes<(unsigned char)20>(JSC::ExecState*, unsigned int, JSC::JSValue)'
collect2: error: ld returned 1 exit status
Makefile.jsc:97: recipe for target '../../bin/jsc' failed
make[2]: *** [../../bin/jsc] Error 1
make[2]: Leaving directory '/home/g/bin/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore'
Makefile.JavaScriptCore:122: recipe for target 'sub-jsc-pro-make_first-ordered' failed
make[1]: *** [sub-jsc-pro-make_first-ordered] Error 2
make[1]: Leaving directory '/home/g/bin/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore'
Makefile:87: recipe for target 'sub-Source-JavaScriptCore-JavaScriptCore-pro-make_first-ordered' failed
make: *** [sub-Source-JavaScriptCore-JavaScriptCore-pro-make_first-ordered] Error 2
```

**Comment by giocomai** [comment]
This might also be related to gcc version, as highlighted in this issue: https://github.com/ariya/phantomjs/issues/13265
The patch linked in that thread, however, did not fix the problem for me, still unable to build in Fedora 22.

**Comment by giocomai** [comment]
Instead of downloading the whole patched file, I solved it by just inserting the lines of code highlighted as changed for the patch here:
https://codereview.qt-project.org/#/c/107921/3/Source/JavaScriptCore/runtime/JSObject.cpp
at the right point of the file into the source file that comes with phantomjs in:
/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore/runtime/JSObject.cpp
phantomjs now builds successfully for me on Fedora 22

**Comment by humanitiesNerd** [comment]
Did this issue produce any effect on the official release ? 

I'm considering installing Phantomjs on Fedora 22 and I'd like to know what's the situation, before beginning

**Comment by reinei** [comment]
As of today, fedora 22 without the mentioned patch from codereview.qt-project.org will NOT compile phantomJS. (erroring with the mentioned error) However, after inserting the mentioned lines, it will compile the qt source.

**Comment by kostajh** [comment]
I had the same issue on Fedora 22, and the patch fixed it.

**Comment by gardym** [comment]
I had the same issue on Fedora 23 and the patch fixed it.

**Comment by mbessolov** [comment]
As of today, on Fedora 23 with the currently included snapshot of WebKit (snapshot from http://trac.webkit.org/browser/trunk?rev=153112 ) in the phantomjs source package, the patch is still required to build phantomjs.

**Comment by zackw** [comment]
Which branch of the Git repository are y'all trying to build?  This was fixed months ago in the development branch.  The 1.9.x branch is closed, but we might make an exception for a compile fix like this one.

**Comment by zackw** [comment]
Incidentally, this fell off our radar because @giocomai closed the issue after working around it.  Please don't do that.

**Comment by st4lk3r1** [comment]
Hi, I'm trying to build on fedora 22 I've already downgraded gcc, updated and upgraded fedora
but when I try to run build.py I get this message:

{standard input}: Assembler messages:
{standard input}:9906: Warning: end of file not at end of a line; newline inserted
{standard input}:10995: Error: unknown pseudo-op: `.l'
g++: internal compiler error: Morto (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Makefile.WebCore.Target:137507: recipe for target '.obj/dom/DOMAllInOne.o' failed
make[2]: *** [.obj/dom/DOMAllInOne.o] Error 4
make[2]: ** Esperando que outros processos terminem.
make[2]: Leaving directory '/opt/phantomjs/src/qt/qtwebkit/Source/WebCore'
Makefile.WebCore:68: recipe for target 'sub-Target-pri-make_first-ordered' failed
make[1]: *** [sub-Target-pri-make_first-ordered] Error 2
make[1]: Leaving directory '/opt/phantomjs/src/qt/qtwebkit/Source/WebCore'
Makefile:177: recipe for target 'sub-Source-WebCore-WebCore-pro-make_first-ordered' failed
make: *** [sub-Source-WebCore-WebCore-pro-make_first-ordered] Error 2

can anyone help with this issue, tks

**Comment by mbessolov** [comment]
@zackw The downloads page at http://phantomjs.org/download.html in the Linux section suggests to do the following:

> Download phantomjs-2.0.0-source.zip (105 MB) and follow the build instructions.

2.0.0 is the version that cannot be built on Fedora 22 and Fedora 23 without the patch.

I've just checked on master - there is no problem building it on Fedora 23. It might make sense to update the downloads page (remove link to 2.0.0 source and simply direct people to the build instructions page which already contains proper instructions on how to clone from GitHub and build the master).

**Comment by ariya** [comment]
It's better to build it statically using Docker, see this [README](https://github.com/ariya/phantomjs/blob/master/deploy/README.md). Based on my experiment, the build binary works fine on Fedora 22.
