### ISSUE TITLE
PhantomJS crashes with SIGSEGV on loading particular URLs

### ISSUE THREAD

**Issue by zkf** [ariya/phantomjs#13483]
I replaced http://example.com in the [Page Loading][1] example with http://www.mh.is/oldungadeild/moya/news/getCalendarSummary.

```
% phantomjs hello.js
PhantomJS has crashed. Please read the crash reporting guide at
<http://phantomjs.org/crash-reporting.html> and file a bug report at
<https://github.com/ariya/phantomjs/issues/new>.
Please attach the crash dump file:
  /tmp/13c007fd-b676-b213-7a09cef7-34e14d8b.dmp
```
[Here's the stack trace.][2]

```
% phantomjs --version
2.0.0
```

[1]: http://phantomjs.org/quick-start.html
[2]: http://pastebin.com/8LsCamCC

**Comment by danik121** [comment]
I have same problem

**Comment by borski** [comment]
+1 this is happening to me too.

**Comment by zkf** [comment]
v2.1.1 has resolved this issue for me.
