### ISSUE TITLE
With --proxy argument, How does DNS resolve work?

### ISSUE THREAD

**Issue by pengqi** [ariya/phantomjs#13488]
With --proxy argument, the phantomjs process will do DNS  resolution local or send DNS requests to the proxy?

**Comment by jamb0ss** [comment]
The same question

**Comment by jamb0ss** [comment]
I'm also wondering how it'll work in both cases (http and socks)

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://heliosesportmultigaming.com/union.php?u>

 

klaus@hebsgaard.dk
