### ISSUE TITLE
Infinite loop in page JS blocks timeouts in the controller

### ISSUE THREAD

**Issue by zackw** [ariya/phantomjs#13490]
We've known for some time that `page.onLongRunningScript` is broken in 2.0 (#12504) but I've just discovered that it's worse than that: an infinite loop in page JS prevents timeouts from firing in the _controller!_  Test case:

```
var page = require('webpage').create();
setTimeout(function () { phantom.exit(0); }, 0);
page.content = "<script>while (1) {}</script>";
```

will hang forever.  Comment out the third line and it exits successfully.

The fix may be the same as the fix for #12504, but I'm filing this separately in case there's a simpler fix that can get landed immediately.

**Comment by Vitallium** [comment]
Milestone 2.0.1? I think it's really critical issue.

**Comment by zackw** [comment]
Agree.

The incomplete patches in #12504 are going to be my very next thing, but that might still wind up being next week, and it might turn out that they don't help, either :worried:

**Comment by zackw** [comment]
Debugging out loud: I believe this is closely related to #12504, but the fix for that is *not* going to fix this, because this is a nastier problem.  Consider now

    var webpage = require("webpage");
    var p1 = webpage.create();
    var p2 = webpage.create();
    p1.onCallback = function () { p1.render("p1.pdf"); };
    p2.onCallback = function () { p1.render("p2.pdf"); };
    p1.content = "<script>compute_1000000_digits_of_pi(); window.callPhantom();</script>";
    p2.content = "<script>plot_the_Mandelbrot_set(); window.callPhantom();</script>";

PhantomJS is single-threaded, so the JavaScript for `p1` and `p2` will not be executed concurrently. *But it won't even be task-switched.*  `compute_1000000_digits_of_pi()` will run to completion and only then will `plot_the_Mandelbrot_set()` get a chance to run.  And because the controller script is, as far as Qt/Webkit is concerned, "just" another webpage, it doesn't get task-switched in either.

The watchdog timer will not help with this because it does *not*, as far as I can tell, implement a task switcher.  It only implements a "should we abandon execution of this JS context? y/n" callback.  There is no way to suspend the JS continuation and return to the Qt event loop.

Any fix for this is starting to feel like it will involve major architectural changes.
