### ISSUE TITLE
phantomjs infinite hang on exception

### ISSUE THREAD

**Issue by pleasantone** [ariya/phantomjs#13497]
Self-compiled, debian, linux 64 bit image, no modifications, from github master as of July 16th, also
tested against phantomjs 1.9.2 linux 64 bit official build.

````
$ cat bar.js
throw "test exception";
:~/inteld$ phantomjs bar.js
test exception

  bar.js:2 in global code

<execution hangs at this point>
````

I would think the expected behavior would be for phantomjs to exit.  Failing that, since it's a "browser",
then it certainly should be able to do *something* after the exception.

````
$ cat baz.js
console.log("one");
throw "test exception";
console.log("two");
throw "test exception 2";
console.log("three");
$ phantomjs baz.js
one
test exception

  baz.js:2 in global code
^C
````

I find this disturbing, because I'm using phantomjs with the casperjs framework and there doesn't appear to be a good way to recover from this.

**Comment by YuriIvanov** [comment]
@pleasantone I'am looking at source code now and can say that it's not "exception" problem. Phantom will fall in infinite loop after execution of any js script (except that the script is empty). For example (in bar.js):
```javascript
console.log("one");
```

**Comment by YuriIvanov** [comment]
And it's not a bug. If you want to exit just use this code in your js:
```javascript
phantom.exit();
```

**Comment by YuriIvanov** [comment]
@pleasantone I'm looking at source code now and can say that it's not "exception" bug. Phantom will fall in infinite loop if you not explicitly shot down it in your js code by calling
```javascript
phantom.exit();
```
PhantomJs does not handle exceptions itself. So when you have unhanled exception in your js, script just stop to execute and does not reach phantom.exit().

**Comment by pleasantone** [comment]
Absolutely correct, my apologies, thank you!
