### ISSUE TITLE
SVG path nodes with semi-transparency get distorted when exporting to PDF

### ISSUE THREAD

**Issue by martynasma** [ariya/phantomjs#13494]
It seems that if the SVG <path> element has `stroke-opacity` set to anything but 1 will result in that path exported distorted. (narrower in our tests)

This only happens when exporting to PDF. Static image exports are not affected.

Here's how it looks in the browser:

![2015-08-13_10-24-01](https://cloud.githubusercontent.com/assets/1458520/9244626/a36a2b30-41a5-11e5-85c4-ddcab6cf69a4.png)

The line is semi-transparent because of the `stroke-opacity="0.8"` set for it:

```
<g>
    <path cs="100,100" d="M12.5,412.5 L36.5,334.5 L60.5,336.5 L83.5,349.5 L107.5,306.5 L132.5,299.5 L155.5,319.5 L179.5,304.5 L203.5,324.5 L227.5,273.5 L251.5,313.5 L273.5,354.5 L297.5,234.5 L320.5,121.5 L345.5,175.5 L368.5,23.5 L392.5,137.5 L416.5,109.5 L440.5,132.5 L464.5,105.5 L488.5,48.5 L512.5,93.5 L536.5,94.5 L558.5,71.5 L582.5,308.5 L605.5,265.5 L630.5,285.5 L653.5,256.5 L677.5,280.5 L701.5,240.5 L725.5,307.5 L749.5,256.5 L772.5,240.5 L797.5,279.5 L821.5,249.5 L844.5,278.5 L868.5,475.5 M0,0 L0,0" fill="none" stroke-width="9" stroke-opacity="0.8" stroke="#00b052"></path>
</g>
```

This is how it comes out when exported to PDF:

![2015-08-13_10-23-00](https://cloud.githubusercontent.com/assets/1458520/9244639/c8a40b0a-41a5-11e5-98d7-a7c13d39b8d7.png)

Now, if I make the line fully opaque, the export works as expected:

![2015-08-13_10-23-37](https://cloud.githubusercontent.com/assets/1458520/9244650/e8f1a782-41a5-11e5-983a-a79c317b6eac.png)

The code behind two exports is identical, except the last one has `stroke-opacity="1"` set.

Here are the files used for testing: (the second file is PhantomJS file)

First test (semi-transparent line):
https://www.dropbox.com/s/itp6isgque26s6f/test1.html?dl=0
https://www.dropbox.com/s/4axx2mvqlxqt7pu/test1.js?dl=0

Second test (opaque line):
https://www.dropbox.com/s/f0k32wp1jc7iqd6/test2.html?dl=0
https://www.dropbox.com/s/ybk2cobc99f6kp1/test2.js?dl=0

**Comment by zackw** [comment]
This is almost certainly a bug in WebKit.  Can you try to reproduce it with a vanilla build of upstream Webkit? (http://nightly.webkit.org/)  If you can reproduce it there, please report it to them.

**Comment by zackw** [comment]
Also, what version of PhantomJS are you using?

**Comment by martynasma** [comment]
I'm running PhantomJS 2.0.0

WebKit does not seem to have Windows builds readily available. And setting up building environment seems to be an overkill. Maybe it would be easier for you to test that? If not, I'll look for ways to test that on WebKit.

Thanks!

**Comment by martynasma** [comment]
Tested it with the latest version of WebKit. Both SVG versions display correct:

<img width="1822" alt="screen shot 2015-08-14 at 09 01 54" src="https://cloud.githubusercontent.com/assets/1458520/9268888/41bada70-426c-11e5-82ff-a1b8146ee039.png">

<img width="1822" alt="screen shot 2015-08-14 at 09 01 57" src="https://cloud.githubusercontent.com/assets/1458520/9268892/46dffddc-426c-11e5-8567-d7bb5bd09492.png">

<img width="396" alt="screen shot 2015-08-14 at 09 03 29" src="https://cloud.githubusercontent.com/assets/1458520/9268893/4a88b5e6-426c-11e5-87cf-43d493a2b1a7.png">

I suppose that would mean the issue is in PhantomJS, rather than WebKit.

**Comment by martynasma** [comment]
Just checking in. Was there any development in this area?

It doesn't seem to be a bug in WebKit.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://stereopunkt.pl/absence.php?7yn92>

 

klaus@hebsgaard.dk
