### ISSUE TITLE
event "onResourceReceived" : response.body always  returns an empty string

### ISSUE THREAD

**Issue by jefleponot** [ariya/phantomjs#13498]
With the latest version of phantomjs, we have more response attributes.

<pre>
var webPage = require('webpage');
var page = webPage.create();

page.onResourceReceived = function(response) {

  console.log('Response (#' + response.id + ', stage "' + response.stage + '"): ' + 
JSON.stringify(response));

};
</pre>

But the "Body" attribute always returns an empty string.

**Comment by goldcaddy77** [comment]
This issue has been kicking around for a long time:

- https://github.com/ariya/phantomjs/issues/10158
- https://github.com/ariya/phantomjs/issues/10702
