### ISSUE TITLE
resourceTimeout do not work

### ISSUE THREAD

**Issue by msassa** [ariya/phantomjs#13503]
Hello, I'm trying something like this:

``` javascript
    var system = require('system');
    var page = require('webpage').create();

    page.settings.userAgent = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36';
    page.settings.resourceTimeout = 2000;

    if (system.args.length === 1) {
        console.log('Try to pass some args when invoking this script!');
        phantom.exit();
    } else {
        var address = system.args[1];
        page.onResourceError = function(resourceError) {
            page.reason = resourceError.errorString;
            page.reason_url = resourceError.url;
        };
        page.onResourceTimeout = function(request) {
            console.log(JSON.stringify(request));
            phantom.exit();
        };
        page.open(address, function(status) {
            if (status !== 'success') {
                console.log("Error opening url \"" + page.reason_url+ "\": " + page.reason);
            } else {
                var ua = page.content;
                console.log(ua);
            }
            phantom.exit();
        });
    }
```

And the onResourceTimeout never happens. In some pages the script runs indefinitely.
Any help? Thanks

**Comment by zackw** [comment]
This might be another manifestation of bug #13490.  Could you please
try to construct a self-contained (no external resource loads) HTML
page that, when loaded via this script, demonstrates the bug, and post
that page here?

**Comment by msassa** [comment]
Sorry, a self-contained html would be setting the page.content? I don't understand that part.
And I use phantom 1.9.7 (if you need to know)

**Comment by zackw** [comment]
> Sorry, a self-contained html would be setting the page.content? I don't understand that part.

I mean an .html file which I could stick on a webserver and then
supply as an argument to the script you posted, and doing this would
demonstrate the bug.

> And I use phantom 1.9.7 (if you need to know)

Yeah, we aren't developing 1.9.x anymore.  Please also try to
reproduce the problem with 2.0.

**Comment by msassa** [comment]
Ok, I'll try to install 2.0 and try it. Thanks.
