### ISSUE TITLE
OsX: phantomjs binary is without a __PAGEZERO segment

### ISSUE THREAD

**Issue by aanno** [ariya/phantomjs#13508]
As I observed when using phantomjs with the kernel hardening SUIDguard, the binary is missing a __PAGEZERO segment (details: https://github.com/sektioneins/SUIDGuard/issues/6).

It is likely that security constains will disallow this soon (details (in german): http://www.heise.de/mac-and-i/meldung/Wieder-Root-Luecke-in-OS-X-Yosemite-inklusive-10-10-5-2780509.html).

**Comment by lostthetrail** [comment]
It would be great to solve this.

**Comment by zackw** [comment]
Sorry for not getting back to you about this.

When built from the current development sources, on OSX 10.9, using a current version of XCode, the phantomjs binary *does* contain a __PAGEZERO segment.  We know that the official binary on the website is out of date and doesn't work reliably on all OSX versions that are supposed to be supported - please be patient, it's on our list.

**Comment by ariya** [comment]
Hmm, I still don't see the segment in our binary:
```bash
$ otool -IV ./phantomjs | grep PAGEZERO
```

Is there any other way to verify this?

**Comment by mepard** [comment]
It's there. Try:  `otool -l ./phantomjs | grep PAGEZERO`

**Comment by ariya** [comment]
Perfect :+1: Now we can safely resolve this issue.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://annuaire-web-quebec.info/domain.php?4b>

 

klaus@hebsgaard.dk
