### ISSUE TITLE
Can't compile PhantomJS with GCC 5.0

### ISSUE THREAD

**Issue by zackw** [ariya/phantomjs#13518]
Compiling PhantomJS (dev trunk) with GCC 5.0 (which is the default compiler in Debian unstable right now) fails inside JavaScriptCore:

    g++ -fdebug-types-section -Wl,-O1 -fuse-ld=gold -Wl,-rpath,.../qtwebkit/lib -o ../../bin/jsc .obj/jsc.o   -Wl,-whole-archive -lJavaScriptCore -Wl,-no-whole-archive -L.../qtwebkit/Source/JavaScriptCore/release -Wl,-whole-archive -lWTF -Wl,-no-whole-archive -L.../qtwebkit/Source/WTF/release -licui18n -licuuc -licudata -L.../qtbase/lib -lQt5Core -lpthread -lz -licui18n -licuuc -licudata -lm -ldl -lrt -lpthread 
    .../qtwebkit/Source/JavaScriptCore/release/libJavaScriptCore.a(JSArray.o):JSArray.cpp:
      function JSC::JSArray::push(JSC::ExecState*, JSC::JSValue):
      error: undefined reference to 'void JSC::JSObject::putByIndexBeyondVectorLengthWithoutAttributes<(unsigned char)20>(JSC::ExecState*, unsigned int, JSC::JSValue)'
    collect2: error: ld returned 1 exit status
    Makefile.jsc:98: recipe for target '../../bin/jsc' failed
    make[2]: *** [../../bin/jsc] Error 1

This is already reported upstream as [Qt bug 44829](https://bugreports.qt.io/browse/QTBUG-44829) and [Webkit bug 147815](https://bugs.webkit.org/show_bug.cgi?id=147815).  A patch is available; I will make a pull request shortly.

**Comment by ariya** [comment]
Good catch! Let me see if I still have that CentOS 6 with GCC 5 setup somewhere for an additional verification.

**Comment by zackw** [comment]
Merged #13520.

**Comment by zackw** [comment]
Patch #13520 has now been applied to the 2.0 branch as well.
