### ISSUE TITLE
upgrading mongoose

### ISSUE THREAD

**Issue by twilly86** [ariya/phantomjs#13513]
Has anyone looked into upgrade the mongoose server?  It looks like the version that is bundled with phantomjs is about 4 years old and it's been updated fairly recently..

https://github.com/cesanta/mongoose/blob/master/docs/ReleaseNotes.md

**Comment by zackw** [comment]
We would like to; we know that there are many bugs in the version we have.  Unfortunately, newer mongoose is under an incompatible license.  I, personally, would not be opposed to relicensing PhantomJS under the GPL, but it's not really my decision.

**Comment by twilly86** [comment]
Any updates on this?  I've seen one suggestion on moving to QTWebServer.

What would be the level of effort on moving to a different web server?

It looks like using node has been tried, but has issues.

My problem is that Mongoose webserver hangs when I submit many concurrent connections.  It has a problem queuing them.  
Issue reported here and it looks like it is fixed in a more recent version...
https://code.google.com/p/mongoose/issues/detail?id=349

**Comment by ariya** [comment]
The use of Mongoose is deprecated, we want to move to use Qt's own HTTP stack.

(GitHub issue search so bad that I can't find the issue related to the migration).
