### ISSUE TITLE
Link to homebrew phantom js install for OSX

### ISSUE THREAD

**Issue by equivalentideas** [ariya/phantomjs#13528]
I found homebrew a quick, easy way to get started with phantomjs.

I think it would be helpful to mention that you can install phantomjs using homebrew by adding some text like:

> You can also install PhaontomJS using the OSX package manager [Homebrew](http://brew.sh/) with `brew install phantomjs`

Maybe the end of the download section would be an appropriate place
![screen shot 2015-08-26 at 3 39 55 pm](https://cloud.githubusercontent.com/assets/1239550/9486306/d1e557d8-4c08-11e5-8142-6dd8201bd183.png)

I'd be happy to do a PR for this if you could point me to the file.

**Comment by ariya** [comment]
This was done in the past and we got a lot of push back when Homebrew version was not updated. I don't want to waste time again explaining if the situation is repeated.

What I can live with: create an entirely new page, called "Alternative installs", that can be used to put the information about any installation not official from this team. Then, put a disclaimer in the header that version might be outdated, it may not work properly, etc.

**Comment by ariya** [comment]
Closing this for lack of follow-up.
