### ISSUE TITLE
PhantomJS crashes when used with prerender

### ISSUE THREAD

**Issue by bobfields** [ariya/phantomjs#13527]
I'm hoping these dmp files (converted to stack traces) have some value here. I included all of the traces, plus one stderr output in case there is value in that output. We are running PhantomJS as part of prerender server (https://prerender.io/) with some load tests. For the most part it is stable, though the most recent crashes happened when nothing was happening, overnight. If you need the original dmp files I can also supply. Since I am not a C++ developer, if you need additional information please be very specific about how I can provide it.
Linux 2.6.32-431.17.1.el6.x86_64 amd64     family 15 model 6 stepping 1     4 CPUs.
The dmp files appear to have the function names.
Nothing appears out of the ordinary in the prerender.log file with the crashes logged.
![dmp](https://cloud.githubusercontent.com/assets/2707087/9478370/764ae3ac-4b45-11e5-9a7b-94a2a07bede7.jpg)

Rename the jpg file to dmp.zip and unzip.

**Comment by ariya** [comment]
Can you try it again with PhantomJS 2.1?
