### ISSUE TITLE
Unable tu build on ubuntu 15.04

### ISSUE THREAD

**Issue by realtebo** [ariya/phantomjs#13530]
I got this message when making.

```
{standard input}: Assembler messages:
{standard input}:107377: Warning: end of file not at end of a line; newline inserted
{standard input}:108704: Error: no such instruction: `j'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
```

So compiling stopped, and no build. 
I need to use casperJs on top of phantomJs so I really really really need an help to build it.

Edit: I found this: https://bugs.gentoo.org/show_bug.cgi?id=256766 

It tell me to remove `-pipe ` switch but I really don't understand which file to modify

**Comment by zackw** [comment]
>     g++: internal compiler error: Killed (program cc1plus)

This error message almost always means "your computer does not have enough RAM to compile this program".  Try adding at least 10GB more swap, and be prepared for the compile to take a very long time.

**Comment by realtebo** [comment]
I'm upgrading my VM to have a min of 2 core and 1 GB of RAM. I'll retry and let you know the esit. Please, keep this issue opened.

**Comment by Vitallium** [comment]
@realtebo you need at least 4 GB of RAM to build PhantomJS.

**Comment by realtebo** [comment]
Actually, the point where the build previously stopped has been passed succesfully. Using htop I see memory occupied a 767/1024 MB. I'm hoping you're wrong, but I'm thinking you're right.

Please, add a note to the documentation about the huge memory amount needed. 
And, please, prepare an ubuntu package !

**Comment by zackw** [comment]
> Actually, the point where the build previously stopped has been passed succesfully. Using htop I see memory occupied a 767/1024 MB. I'm hoping you're wrong, but I'm thinking you're right.

The link phase may require *even more* memory.

> please, prepare an ubuntu package!

They won't take it, because of the embedded copy of both Qt and Webkit
and associated issues with keeping up to date with security patches.
Maybe someday if we ever don't need that anymore.

**Comment by realtebo** [comment]
You're right. Crashed when compilink `svg/SVGAllInOne.cpp`. 

I cannot afford 30$ right now for VPS upgrade, just for compile this package. I'll find another way.

Thanks. I close.

**Comment by ariya** [comment]
@realtebo If you have a capable desktop/laptop, install VirtualBox and run Ubuntu.
