### ISSUE TITLE
getDate, getUTCDate: wrong result

### ISSUE THREAD

**Issue by craff** [ariya/phantomjs#13538]
The method getDate and getUTCDate give result in 0-30 range while, accoding to spec it should be 1-31 (I agree taht getDate in 1-31 and getMonth in 0-11 is not coherent, but this is what the specs are saying).

More importantly, getDate can give result outside the month range (and together with getMonth, we can have a date like 32nd august !!!)

**Comment by zackw** [comment]
phantomjs> new Date('2000-01-31').getDate()
    31

If you are using PhantomJS 1.9.x, please update to 2.0, it contains a much newer Webkit that may have resolved the problem.  If you still experience the problem with 2.0 please provide a complete JavaScript program that demonstrates the problem.
