### ISSUE TITLE
Path is always null (because location.js is missing)

### ISSUE THREAD

**Issue by RachelSatoyama** [ariya/phantomjs#13532]
Just like in phantomjs, in phantomjs2 there's following line of code:
`exports.path = path.resolve(__dirname, require('./location').location)`

The thing is that location.js is not present in phantomjs2 package.
Thus, phantomjs2.path is always null.

**Comment by JamesMGreene** [comment]
Sounds like you might be using the [`phantomjs2` NPM module](https://www.npmjs.com/package/phantomjs2). Please file an issue with them at [zeevl/phantomjs2](https://github.com/zeevl/phantomjs2) as this has nothing to do with Phantom core.

**Comment by RachelSatoyama** [comment]
My bad. I apologize for this.  Thanks!
