### ISSUE TITLE
Tests hang when run under Jenkins, repeatedly printing meaningless error message

### ISSUE THREAD

**Issue by swatcats143** [ariya/phantomjs#13536]
Error : [INFO  - 2015-08-27T14:22:44.495Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW

I am getting this above error in jenkins  when I am using phantomjs tests stop runing and get this mesaage repeatedly 
In local machine It is working absoultely fine 

My driver setup in local machine

    def createPhantomJsDriver :WebDriver = {
      val capabilities : DesiredCapabilities = new DesiredCapabilities()
      capabilities.setJavascriptEnabled(javascriptEnabled)
      new PhantomJSDriver(capabilities)
    }

Can someone please help me

**Comment by swatcats143** [comment]
[INFO  - 2015-08-27T14:22:44.495Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2015-08-27T14:27:44.494Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW

**Comment by zackw** [comment]
That looks to me like a junk debugging message.  I don't know from Jenkins, but we need to know what your actual *problem* is -- is it just that you get a noise message you didn't get anywhere else, or is something actually failing? And in the latter case, we need a *complete, self-contained testcase* that we can run for ourselves and observe the problem.

**Comment by swatcats143** [comment]
@zackw tests stopping in jenkins after running for certain time and start saying the error message
![image](https://cloud.githubusercontent.com/assets/14017140/9663172/ffae7606-525a-11e5-8169-7c4863117133.png)

**Comment by zackw** [comment]
OK, that message is the only visible symptom of the problem; unfortunately, it tells us *nothing* about what the actual problem might be.

Again, we are not able to do anything with this bug report unless you can provide us with a complete, self-contained, minimal test case so we can make the same problem happen on our end.

**Comment by swatcats143** [comment]
@zackw please refer to https://github.com/ariya/phantomjs/issues/11526 it is the same issue it is shame that so far no solution has been found
phantomjs-2.0 unbuntu

**Comment by zackw** [comment]
@swatcats143 Thank you for identifying the earlier bug report; I will now close this as a duplicate.

There is still **nothing** we can do without a complete, self-contained, minimal test case.
