### ISSUE TITLE
phantomjs2.0 build failed

### ISSUE THREAD

**Issue by node-rookie** [ariya/phantomjs#13542]
System architecture... (Linux 2.6.32-431.23.3.el6.x86_64 x86_64)

This is the Qt Open Source Edition.

You are licensed to use this software under the terms of
the Lesser GNU General Public License (LGPL) versions 2.1.
You are also licensed to use this software under the terms of
the GNU General Public License (GPL) versions 3.

You have already accepted the terms of the Open Source license.

Precompiled-headers support enabled.
g++ -c -fvisibility=hidden fvisibility.c
Symbol visibility control enabled.
g++ -o libtest.so -shared -Wl,-Bsymbolic-functions -fPIC bsymbolic_functions.c
g++: error trying to exec 'ld': execvp: 没有那个文件或目录
Symbolic function binding disabled.
DEFAULT_INCDIRS="/usr/include/c++/4.4.7
/usr/include/c++/4.4.7/x86_64-redhat-linux
/usr/include/c++/4.4.7/backward
/usr/local/include
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/include
/usr/include
"
DEFAULT_LIBDIRS="/lib64
/usr/lib64
/usr/lib
/lib
/usr/lib/gcc/x86_64-redhat-linux/4.4.7
"
<srcbase> = /root/www/phantomjs/src/qt/qtbase 
<outbase> = /root/www/phantomjs/src/qt/qtbase 
Creating qmake...
gmake: Nothing to be done for `first'.
Running configuration tests...
Determining architecture... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -g -Wall -W -fPIE  -I../../mkspecs/linux-g++ -I. -o arch.o arch.cpp
g++  -o arch arch.o    
g++: error trying to exec 'ld': execvp: 没有那个文件或目录
gmake: *** [arch] 错误 1
Unable to determine architecture!

Could not determine the target architecture!
Turn on verbose messaging (-v) to see the final report.
System architecture: 'unknown'
Host architecture: 'unknown'
C++11 auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -std=c++0x -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o c++11.o c++11.cpp
g++ -Wl,-O1 -o c++11 c++11.o    
g++: error trying to exec 'ld': execvp: 没有那个文件或目录
gmake: *** [c++11] 错误 1
C++11 disabled.
floatmath auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o floatmath.o floatmath.cpp
floatmath.cpp:44: 警告：未使用的参数‘argc’
floatmath.cpp:44: 警告：未使用的参数‘argv’
g++ -Wl,-O1 -o floatmath floatmath.o    
g++: error trying to exec 'ld': execvp: 没有那个文件或目录
gmake: *** [floatmath] 错误 1
floatmath disabled.
sse2 auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -msse2 -g -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o sse2.o sse2.cpp
g++  -o sse2 sse2.o    
g++: error trying to exec 'ld': execvp: 没有那个文件或目录
gmake: *** [sse2] 错误 1
sse2 disabled.
POSIX iconv auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o iconv.o iconv.cpp
g++ -Wl,-O1 -o iconv iconv.o    
g++: error trying to exec 'ld': execvp: 没有那个文件或目录
gmake: *** [iconv] 错误 1
POSIX iconv disabled.
SUN libiconv auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o gnu-libiconv.o ../gnu-libiconv/gnu-libiconv.cpp
../gnu-libiconv/gnu-libiconv.cpp: In function ‘int main(int, char**)’:
../gnu-libiconv/gnu-libiconv.cpp:54: 错误：从类型‘const char**’到类型‘char**’的转换无效
../gnu-libiconv/gnu-libiconv.cpp:54: 错误：  初始化‘size_t iconv(void*, char**, size_t*, char**, size_t*)’的实参 2
gmake: *** [gnu-libiconv.o] 错误 1
SUN libiconv disabled.
GNU libiconv auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o gnu-libiconv.o gnu-libiconv.cpp
gnu-libiconv.cpp: In function ‘int main(int, char**)’:
gnu-libiconv.cpp:54: 错误：从类型‘const char**’到类型‘char**’的转换无效
gnu-libiconv.cpp:54: 错误：  初始化‘size_t iconv(void*, char**, size_t*, char**, size_t*)’的实参 2
gmake: *** [gnu-libiconv.o] 错误 1
GNU libiconv disabled.
ICU auto-detection... ()
g++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -Wall -W -fPIE  -I../../../mkspecs/linux-g++ -I. -o icu.o icu.cpp
g++ -Wl,-O1 -o icu icu.o   -licui18n -licuuc 
g++: error trying to exec 'ld': execvp: 没有那个文件或目录
gmake: *** [icu] 错误 1
ICU disabled.
The ICU library support cannot be enabled.
 Turn on verbose messaging (-v) to /root/www/phantomjs/src/qt/qtbase/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /root/www/phantomjs/src/qt/qtbase/configure to continue.

**Comment by Vitallium** [comment]
PhantomJS 2 requires libicu >= 4.8
