### ISSUE TITLE
XHR and responseType

### ISSUE THREAD

**Issue by tatablack** [ariya/phantomjs#13540]
I am creating a Web Worker from a string (see [here](http://stackoverflow.com/questions/10343913/how-to-create-a-web-worker-from-a-string)), using a `Blob` and an `ObjectURL`.
Since PhantomJS does not support the Blob constructor (as far as I can see), I am using [this polyfill](https://github.com/peerlibrary/Blob.js).

Inside the worker I am doing:

```javascript
var xhr = new XMLHttpRequest();
xhr.responseType = 'json';
xhr.onreadystatechange = function () {
// more code
}
```

I  run PhantomJS through Karma, and in the console I see:

```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  INVALID_STATE_ERR: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.
  at blob:http://localhost:9876/9748df51-be46-407f-9db2-2a62f4eeb32e:5
```

If I remove the `xhr.responseType = 'json';` line, and parse `responseText` as JSON inside the `onreadystatechange` handler, all seems fine.

Am I doing something wrong in trying to set the `responseType` there? Other browsers seem fine with it.

**Comment by zackw** [comment]
Please try PhantomJS 2.0.  It contains a much newer Webkit which may have resolved this issue.  If you still have a problem with 2.0 please report it directly to the Webkit developers: https://www.webkit.org/quality/reporting.html
