### ISSUE TITLE
Parsed date not correct

### ISSUE THREAD

**Issue by stmichael** [ariya/phantomjs#13543]
I found a weird bug when parsing dates. 2034-02-28 and earlier dates are being parsed correctly. But all dates after that specific day are always one day behind.
```
phantomjs> new Date('2034-02-28')
"2034-02-28T00:00:00.000Z"
phantomjs> new Date('2034-03-01')
"2034-02-28T00:00:00.000Z"
phantomjs> new Date('2034-03-02')
"2034-03-01T00:00:00.000Z"
```

I'm using version 2.0.0.

**Comment by zackw** [comment]
How very peculiar.

This is a bug in Webkit, please report it directly to them: https://www.webkit.org/quality/reporting.html
