### ISSUE TITLE
[Travis CI] Migrate to container-based infrastructure

### ISSUE THREAD

**Issue by Vitallium** [ariya/phantomjs#13554]
Travis CI switched to a new container-based infrastructure.
Jobs running on container-based infrastructure:

- start up faster
- allow the use of caches for public repositories
- disallow the use of sudo, setuid and setgid executables

[Guide on migrating to new infrastructure](http://docs.travis-ci.com/user/migrating-from-legacy/)

**Comment by Vitallium** [comment]
I did fix it. But now we have another problem on Travis CI:
```
{standard input}: Assembler messages:
{standard input}:27311: Warning: end of file not at end of a line; newline inserted
{standard input}:27839: Error: bad register name `%rb'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
```
https://travis-ci.org/Vitallium/phantomjs/builds/78923450

**Comment by zackw** [comment]
You cut it off right before the *real* error message -- the complaints from the assembler are just fallout.

    compiling css/CSSAllInOne.cpp
    {standard input}: Assembler messages:
    {standard input}:27311: Warning: end of file not at end of a line; newline inserted
    {standard input}:27839: Error: bad register name `%rb'
    {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
    g++: internal compiler error: Killed (program cc1plus)

The container doesn't have enough RAM for the compiler.

**Comment by Vitallium** [comment]
Whoopsi. Yes, you're right. Thanks!

**Comment by Vitallium** [comment]
Hm, I found this in the docs:
```
The new containers have 2 dedicated cores and 4GB of memory, vs 1.5 cores and 3GB on our legacy infrastructure. CPU resources are now guaranteed, which means less impact from ‘noisy neighbors’ on the same host machine and more consistent build times throughout the day.
```
http://docs.travis-ci.com/user/migrating-from-legacy/#More-available-resources

**Comment by zackw** [comment]
Maybe try forcing -j1?

**Comment by Vitallium** [comment]
Yup, forcing to 1 compile jobs made it.

**Comment by Vitallium** [comment]
Fixed in https://github.com/ariya/phantomjs/commit/2e28bb39768e2cec0d881693d4c525c13816f845
