### ISSUE TITLE
TypedArray iteration and accessor methods unsupported

### ISSUE THREAD

**Issue by mpeteuil** [ariya/phantomjs#13559]
After PhantomJS 2.0 landed there were many features that came with it including basic support for TypedArrays as described in issue #10607. However, there still seems to be a lack of support for the iteration and accessor methods that are standard on the Array type. These methods are a part of the [TypedArray specification](http://www.ecma-international.org/ecma-262/6.0/#sec-%typedarray%.prototype.entries).

That they're missing can be seen in the screenshot below. It only shows `Uint8Array`, but the behavior is the same for the rest of the TypedArray family (`Uint8ClampedArray`, `Uint16Array`, `Uint32Array`, `Int8Array`, `Int16Array`, `Int32Array`, `Float32Array`, `Float64Array`)

```
OS: OSX 10.9.5
PhantomJS version: 2.0.0
```

![PhantomJS missing TypedArray iteration and accessor methods](https://cloud.githubusercontent.com/assets/459756/9707177/ecfd1d22-54cc-11e5-8929-fb3f4d0d733d.png)

**Comment by zackw** [comment]
Yes, unfortunately, PhantomJS is not keeping up with Webkit at the moment - I think our version is currently about a year old.

We will eventually pick up a browser core with complete TypedArray support, but we're not going to start cherry-picking web platform features. I regret I don't have a time frame for you.
