### ISSUE TITLE
phantomjs - google fonts not rendering

### ISSUE THREAD

**Issue by zadahead** [ariya/phantomjs#13557]
Im using phantomjs to capture a webpage.

The page has fonts from the google fonts api

when i render the page, the font are not rendered and go back to default.

please tell me how to fix this.

(and please, if is need to update/install/add something, tell how to do so - Im new at this,)

phantomjs ver: 2.0 platform: windows

thank you

**Comment by 6tem9** [comment]
Hello, I have the same problem, I've found no solution for now. If someone has an idea, I 'm very interested.

**Comment by zackw** [comment]
We apologize for not responding to this bug report sooner.

I cannot reproduce any problem with Google Fonts using PhantomJS 2.0 on Linux. This suggests a Windows-specific issue. It is probably deep in the guts of WebKit.

Unfortunately, we do not have the manpower to debug WebKit issues ourselves. Please report this directly to the WebKit development team: https://www.webkit.org/quality/reporting.html
