### ISSUE TITLE
PhantomJS is crashing while running CasperJS script with Infinite Loop

### ISSUE THREAD

**Issue by NileshKSingh** [ariya/phantomjs#13566]
Platform: Windows
Version: 1.9.8

I have created a small casperjs script with infinite looping using (https://github.com/yotsumoto/casperjs-goto)

After 200+ iterations the PhantomJS is crashing with the following message: "PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: C:\Users\NILESH~1.SIN\AppData\Local\Temp\c8ba2e65-3f7b-4331-937a-aaabb3a2f718.dmp"

**Comment by zackw** [comment]
PhantomJS 1.9.8 is very old and no longer maintained.  Please upgrade to 2.0.

There are known memory leak bugs in 2.0, so your script may not work there either.  Why do you need an infinite loop?
