### ISSUE TITLE
Crashdump

### ISSUE THREAD

**Issue by mobiright** [ariya/phantomjs#13563]
Hi,
I'm having lots of crashes recently, I have no idea why
The dump: 
https://drive.google.com/file/d/0By_fc4VYL_S5Q3gzTXlaa3dWWU0/view?usp=sharing

**Comment by zackw** [comment]
We apologize for not responding to this bug report promptly.

If you are using PhantomJS 1.9.x, we strongly recommend you upgrade to 2.0, which contains an enormous number of bugfixes.  We are not working on 1.9.x any more.

If you still experience crashes with 2.0, we don't actually want the dump file; we want a minimal, self-contained test case. Please note that nearly all crash bugs are WebKit's fault, and we do not have the manpower to fix WebKit bugs ourselves; we strongly encourage you to attempt to reproduce such bugs using a WebKit nightly build (https://www.webkit.org/) and report them directly to that team.

If you have not read it yet, please check also a few tips on [Effective Q&A](https://github.com/ariya/phantomjs/wiki/Support).
