### ISSUE TITLE
Some regular fonts change to italic on capture

### ISSUE THREAD

**Issue by yairza** [ariya/phantomjs#13561]
I use phantom to capture site with many custom fonts (some google fonts, some local)
For unknown reason some of the fonts become italic on capture
Changing the CSS font-face didn't change anything.
Example of pages with problematic fonts:
https://www.google.com/fonts/specimen/Amatic+SC
https://www.google.com/fonts/specimen/Rozha+One

phantomjs ver: 2.0 platform: windows

JS code used:
/*
var page = require('webpage').create();
page.viewportSize = { width: 320, height: 480 };
page.open('https://www.google.com/fonts/specimen/Amatic+SC', function (status) {
    if (status !== 'success') {
        console.log('Unable to access the network!');
    } else {
        page.evaluate(function () {
        });
        page.render('technews.png');
    }
    phantom.exit();
});
*/
![capture](https://cloud.githubusercontent.com/assets/14158907/9712338/a13e4600-5552-11e5-87fe-eaa6d779ac79.PNG)

**Comment by sirceljm** [comment]
I also noticed this with Material design iconic font. (http://zavoloklom.github.io/material-design-iconic-font/icons.html)
![pjs_bug](https://cloud.githubusercontent.com/assets/963690/10172324/023a3f0c-66df-11e5-9193-f76d067cff01.png)

Left image is from Chrome and right is rendered with PhantomJS 2.0.0.

There is no italic font problem if I render the page with the previous version of PhantomJS.

**Comment by zackw** [comment]
We apologize for not responding to this bug report sooner.

I cannot reproduce the problem using PhantomJS 2.0 on Linux (I tried both of the Google Fonts pages).  This suggests a Windows-specific issue.  It is probably deep in the guts of WebKit.

Unfortunately, we do not have the manpower to debug WebKit issues ourselves.  Please report this directly to the WebKit development team: https://www.webkit.org/quality/reporting.html

**Comment by tiborsaas** [comment]
Problem still persists :/

**Comment by luffs** [comment]
Stumbled across this bug too, a workaround is to disable certain font formats (.ttf, .otf), ex:
```
@font-face {
  font-family: 'CustomFont-Medium';
  src: url('CustomFont-Medium.eot');
  src: url('CustomFont-Medium.woff2') format('woff2'),
       url('CustomFont-Medium.woff') format('woff'),
       /*url('CustomFont-Medium.ttf') format('truetype'),*/
       url('CustomFont-Medium.svg#CustomFont-Medium') format('svg'),
       url('CustomFont-Medium.eot?#iefix') format('embedded-opentype');
  font-weight: normal;
  font-style: normal;
}
```

**Comment by HugoHeneault** [comment]
Thanks @luffs ! I looked for this bug for a while.

**Comment by argo-qu** [comment]
Issue still persists
![source](https://user-images.githubusercontent.com/12495817/33843397-5226d2a2-deae-11e7-9d75-65d734bea7d8.PNG)
![capture](https://user-images.githubusercontent.com/12495817/33843398-524be6be-deae-11e7-93a8-3528b47e0293.png)
