### ISSUE TITLE
svg: rasterization using phantomjs slightly different from chrome rendering

### ISSUE THREAD

**Issue by cricri** [ariya/phantomjs#13569]
I am not sure it's a bug
This seems to be tied with the non integer width/height.

chrome : Version 45.0.2454.85 (64-bit)
phantomjs: 2.0.0
command line: phantomjs-2.0.0/bin/phantomjs phantomjs-2.0.0/examples/rasterize.js test.svg out.png "800px*800px"

Open test.svg and out.png in chrome, you will see that the black filled rectangle is shifted in the png output.

l1.svg
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="551.1" height="527.5700000000002">
<style type="text/css"><![CDATA[path{fill:none;stroke:#000;stroke-width:.1;vector-effect:non-scaling-stroke}]]></style>
<path d="M30 140h50v-30h-50v30"/>
</svg>
```

l2.svg
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="556.39" height="532.5900000000001">
<path d="M35 120h20v20h-20v20"/>
</svg>
```

test.svg
```svg
<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g transform="matrix(8,0,0,8,-31250,-19300)">
    <image xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" width="551.1" height="527.5700000000002" xlink:href="file:///home/christophe/Desktop/bug/l1.svg" transform="matrix(0.6,0,0,0.6,3891.1716663776606,2348.851288801672)"></image>
    <image xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" width="556.39" height="532.5900000000001" xlink:href="file:///home/christophe/Desktop/bug/l2.svg" transform="matrix(0.6,0,0,0.6,3889.4948949068494,2346.416549279014)"></image>
  </g>
</svg>
```

out.png
![out](https://cloud.githubusercontent.com/assets/621068/9762168/f09f1a02-5701-11e5-92d1-7e50bce3646b.png)

**Comment by zackw** [comment]
Sorry for the delay getting back to you.

If this is a bug, it's a bug in Webkit.  We do not have the manpower to fix bugs in Webkit ourselves.  Please report this directly to the Webkit team: https://www.webkit.org/quality/reporting.html

**Comment by cricri** [comment]
To the best of my understanding, there is a difference between the webkit output and the phantomjs output, that's why I reported to phantomjs.

**Comment by marhub** [comment]
@cricri did you resolve this issue somehow ?

**Comment by cricri** [comment]
nope :-(

**Comment by cricri** [comment]
reported to webkit:
https://bugs.webkit.org/show_bug.cgi?id=170052
