### ISSUE TITLE
How to get the model values to script?

### ISSUE THREAD

**Issue by SowmiyaV** [ariya/phantomjs#13576]
For page capturing, using phanthomjs in my c# project.
Classfile.cs 
void capturing(int Identifier)
{
 newDirectory = "F://Documents//Project//Content//StaticPages//FileName-" + Identifier + ".html";
                   File.Create(newDirectory);
                   Console.WriteLine("Creating Static Page for the  Id : {0}", Identifier);
                   ExecuteCommand(string.Format("cd {0} & phantomjs static.js>Static_{1}.html", path, Identifier));
}
Need to pass the 'Identifier' values to the script file "static.js". 

static.js
page.open('http://www.xyz.com/document/' + Identifier , function (status) {
    if (status === 'success') {
       console.log(page.evaluate(svgDrawer));	
    }
	phantom.exit();
});

In js file, while hard coded the "Identifier" value as "10" means its working. But I need to pass the model variable "Identifier".

Please suggest to fix this issue. 

Regards,
Sowmiya

**Comment by Vitallium** [comment]
Please read documentation first.

[1] http://phantomjs.org/api/command-line.html
[2] http://phantomjs.org/api/system/property/args.html
