### ISSUE TITLE
Modifying Headers Crashes

### ISSUE THREAD

**Issue by ChairmanMeow** [ariya/phantomjs#13573]
Attempting to render a picture of a page that displays my http headers. 
i added custom headers the image appears encoded.
I modified my header to include: "Accept-Encoding" : "gzip"

Attached is the image of the resulting page.
Not sure how to attach crash dump.
![image](https://cloud.githubusercontent.com/assets/1448407/9785203/5a483386-5765-11e5-84a3-f516d06fe6cb.png)

**Comment by zackw** [comment]
Sad to say, PhantomJS doesn't support gzip-encoding right now.  We're tracking that as bug #13621.
