### ISSUE TITLE
Cannot Load PAC file in to Firefox.

### ISSUE THREAD

**Issue by RathanakSreang** [ariya/phantomjs#13571]

**Comment by zackw** [comment]
We can't help you with Firefox.  Try https://support.mozilla.org/

**Comment by RathanakSreang** [comment]
@zackw my wrong writing, it not Firefox. 
My problem is I am unable create phantomjs to use system proxy.
>require "selenium-webdriver"
>driver = Selenium::WebDriver.for :phantomjs, :args => ["--ignore-ssl-errors=true", "--proxy-type=system"]
