### ISSUE TITLE
phantomjs 2.0 build error on centos7

### ISSUE THREAD

**Issue by kxjhcs** [ariya/phantomjs#13582]
Could NOT find IDL file for interface "InternalSettingsGenerated"!
make[2]: *** [generated/JSInternalSettings.cpp] 错误 255
make[2]: *** 正在等待未完成的任务....
make[2]: 离开目录“/root/shuai/mnt/new/phantomjs/src/qt/qtwebkit/Source/WebCore”
make[1]: *** [sub-DerivedSources-pri-make_first-ordered] 错误 2
make[1]: 离开目录“/root/shuai/mnt/new/phantomjs/src/qt/qtwebkit/Source/WebCore”
make: *** [sub-Source-WebCore-WebCore-pro-make_first-ordered] 错误 2

**Comment by kxjhcs** [comment]
I tried to compile phantomjs 1.98 on centos6.4：

ar cqs libqkrcodecs.a .obj/release-static/qeuckrcodec.o .obj/release-static/main.o
rm -f ../../../../plugins/codecs/libqkrcodecs.a
mv -f libqkrcodecs.a ../../../../plugins/codecs/
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
make[1]: Leaving directory `/root/mnt/910/phantomjs/src/qt/src/plugins/codecs/kr'
~/mnt/910/phantomjs/src/qt
Building main PhantomJS application. Please wait...

QMAKESPEC has not been set, so configuration cannot be deduced.
Error processing project file: /root/mnt/910/phantomjs/phantomjs.pro

**Comment by zackw** [comment]
Sorry for the delay getting back to you about this.

We are no longer developing phantomjs 1.9.x.  Please try to build 2.0 instead.

>     make[1]: warning: Clock skew detected. Your build may be incomplete.

Also, make sure your computer's clock is set to the right time.

**Comment by kxjhcs** [comment]
@zackw TKS
