### ISSUE TITLE
Install phantom via NPM - Windows

### ISSUE THREAD

**Issue by maxime1992** [ariya/phantomjs#13588]
I cannot make phantom works on windows.

Here's the result of "npm install phantom"

![image](https://cloud.githubusercontent.com/assets/4950209/9857120/0fab53c8-5b19-11e5-87bc-600a76deffd9.png)

Any idea why ? I installed visual studio, i tried to delete every node_modules and to clean the cache ...

**Comment by Vitallium** [comment]
Sorry. But we don't maintain the NPM registry. Please open your issue in the corresponding repository: https://github.com/Medium/phantomjs
