### ISSUE TITLE
Security issue with npm installer

### ISSUE THREAD

**Issue by jamie-pate** [ariya/phantomjs#13580]
I know most people don't have multi-user systems with untrusted users, that also run production node/phantomjs but if you do, then this:
```
Download already available at /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Extracting tar contents (via spawned process)
Removing /home/[user]/5-4/100d/migadmin/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1441919026028/phantomjs-1.9.8-linux-x86_64 -> /home/[user]/5-4/100d/migadmin/node_modules/phantomjs/lib/phantom
```
is a huge security hole. (imagine if you did `sudo npm install phantomjs -g` and there was a rogue copy at that location)

A nice fix would be:
A) copy the file to a non-global temp location (with restricted write permissions for other users)
B) confirm the file contents with a checksum/signing

In theory this could also cause permission errors if multiple users tried installing phantomjs via npm on the same machine with a shared tmp dir.

**Comment by Vitallium** [comment]
Sorry, but we don't maintain the NPM version. Please open your issue in the author's repo: https://github.com/Medium/phantomjs

**Comment by jamie-pate** [comment]
Cool, thanks.
