### ISSUE TITLE
ubuntu 12.04 build failed

### ISSUE THREAD

**Issue by FreemanHsu** [ariya/phantomjs#13598]
I tried to build on ubuntu 12.04, but got the following error messages... 

cc1plus: error: -Werror=unused-but-set-variable: No option -Wunused-but-set-variable
cc1plus: error: -Werror=unused-but-set-variable: No option -Wunused-but-set-variable
make[2]: *** [.obj/db/builder.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [.obj/db/c.o] Error 1
make[2]: *** [.obj/db/dbformat.o] Error 1
cc1plus: error: -Werror=unused-but-set-variable: No option -Wunused-but-set-variable
make[2]: *** [.obj/db/db_impl.o] Error 1
make[2]: Leaving directory `/home/jxu/Developer/phantomjs/src/qt/qtwebkit/Source/ThirdParty/leveldb'
make[1]: *** [sub-Target-pri-make_first] Error 2
make[1]: Leaving directory `/home/jxu/Developer/phantomjs/src/qt/qtwebkit/Source/ThirdParty/leveldb'
make: *** [sub-Source-ThirdParty-leveldb-leveldb-pro-make_first-ordered] Error 2

**Comment by Vitallium** [comment]
Quoting @zackw:
>This almost always means either you don't have enough RAM, or your RAM is faulty. Try ./build.sh --confirm --jobs 1; this will make the build require less RAM (but also it will be even slower).

**Comment by zackw** [comment]
@Vitallium That excuse applies only if you see `cc1plus: Killed` or `cc1plus: Segmentation fault` in the build log.  *This* looks like "Your GCC is too old."

@FreemanHsu What does `g++ --version` print?  Also, just to be sure, how much RAM does this computer have?

**Comment by Vitallium** [comment]
I don't think its about old GCC version. I use 12.04 in my tests. But who knows.

**Comment by zackw** [comment]
@FreemanHsu It has been three weeks since we heard anything from you, and we can't reproduce this problem ourselves, so I am going to close the bug report.  If you still have a problem, feel free to reopen.
