### ISSUE TITLE
Corrupt JPEG data

### ISSUE THREAD

**Issue by Jaironlanda** [ariya/phantomjs#13596]
Error
Corrupt JPEG data: 1688 extraneous bytes before marker 0xe2
 error shown then my test freeze. 

Codeception version 2.1.2 
My acceptance.suite.yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://12.0.0.4/framework/
            browser: phantomjs
            host: 127.0.0.1
        - \Helper\Acceptance
        - WebDriver

**Comment by zackw** [comment]
We need more information to be able to do anything about this bug:

1. Are you using PhantomJS 2.0?  1.9.x is no longer being developed, and is known to have many bugs.
1. The error message suggests a problem with a JPEG image.  Can you please figure out exactly which image is the problem, and attach it to this bug report.
1. Please also try to construct a minimal test case.  This could conceivably be as simple as

    # test.html
    <!doctype html><img src="test.jpg">

    # test.js
    require("webpage").create().open("test.html", function (s) { phantom.exit(s != "success") });

but if more code is required, we need to know that. If you can make the bug happen without WebDriver, that is best.
