### ISSUE TITLE
TypeError: 'undefined' is not a function (evaluating 'c.generate.bind(c)')

### ISSUE THREAD

**Issue by mentallurg** [ariya/phantomjs#13595]
Phantomjs 1.9.8-4.1, openSUSE 13.1, 64 bit.
Used in Java with com.codeborne:phantomjsdriver:1.2.1.
Following error occurs:
    TypeError: 'undefined' is not a function (evaluating 'c.generate.bind(c)')
    (anonymous function) (http://.../bootstrap.min.js:21)
    ...

The problem has currently no solution:
- 1.9: there is no fix
- 2.0: there is no version for Linux

This problem makes PhantomJS unusable. PhantomJS seems to be dead since 2014.

**Comment by Vitallium** [comment]
We don't fix 1.x anymore. We advice to switch to 2.x version.
Unfortunately, there is no version Linux yet. But we're working on it.
Alternatively you can build it from sources by yourself.

Thanks!
