### ISSUE TITLE
Exit code 127

### ISSUE THREAD

**Issue by gustavohenke** [ariya/phantomjs#13597]
Hello,

I'm seeing the exit code 127 while running Phantom in [GitLab CI](https://gitlab.org/gitlab-ci/) environment. My project uses Karma to build (and most specifically, [karma-phantomjs-launcher](https://github.com/karma-runner/karma-phantomjs-launcher)).

This is the log I have:

```
18 09 2015 17:51:35.447:INFO [launcher]: Starting browser PhantomJS
18 09 2015 17:51:35.447:DEBUG [temp-dir]: Creating temp dir at /tmp/karma-76412877
18 09 2015 17:51:35.490:DEBUG [launcher]: /home/gitlab-runner/builds/b351a788/0/syoangular/eventowizard/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs /tmp/karma-76412877/capture.js
18 09 2015 17:51:35.498:DEBUG [launcher]: Process PhantomJS exited with code 127
18 09 2015 17:51:35.498:ERROR [launcher]: Cannot start PhantomJS
```

**Server OS:** Ubuntu 14.04.3

I just would like to know what this exit code means in Phantom, and how can I fix it.
Thank you in advance.

**Comment by gustavohenke** [comment]
So, after reproducing the same environment in a docker container, I found that I was missing `libfontconfig` and `libfreetype6`.
After installing them via `apt-get`, Phantom is now running.

**Comment by islandlinux** [comment]
I had the same problem with Ubuntu 14.04 64 bit. Had to install the 32bit libraries:

```bash
sudo apt-get install libfontconfig:i386 libfreetype6:i386
```

Reference:

 * [error while loading shared libraries; cannot open shared object file: No such file or directory](http://askubuntu.com/questions/409310/error-while-loading-shared-libraries-cannot-open-shared-object-file-no-such-fi)

**Comment by eyalzoref** [comment]
Worked for me as well.

sudo apt-get install libfreetype6
sudo apt-get install libfontconfig 

Cheers @gustavohenke

**Comment by deepak41** [comment]
Thanks. Worked for me also. I was missing libfontconfig.
