### ISSUE TITLE
Could you update the npm source of phantomjs？

### ISSUE THREAD

**Issue by zhangjh** [ariya/phantomjs#13602]
Could you update the npm source of phantomjs so that I can install it by npm ?
Because I met many dependencies errors when I install phantomjs 2.0 from compiling source code .
I tried as "http://phantomjs.org/build.html" says, but errors already exist.
Thanks a lot.

**Comment by zackw** [comment]
We don't have any control over the NPM package of PhantomJS.

If you post your build log to the mailing list we may be able to help you with the dependency problems.
