### ISSUE TITLE
Build crash

### ISSUE THREAD

**Issue by Tomaas** [ariya/phantomjs#13601]
I encountered the following error while building phantomjs on a debian (Jessie)

g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile.WebCore.Target:551556: recipe for target '.obj/html/HTMLElementsAllInOne.o' failed
make[2]: *** [.obj/html/HTMLElementsAllInOne.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/user/phantomjs/src/qt/qtwebkit/Source/WebCore'
Makefile.WebCore:64: recipe for target 'sub-Target-pri-make_first-ordered' failed
make[1]: *** [sub-Target-pri-make_first-ordered] Error 2
make[1]: Leaving directory '/home/user/src/qt/qtwebkit/Source/WebCore'
Makefile:173: recipe for target 'sub-Source-WebCore-WebCore-pro-make_first-ordered' failed
make: *** [sub-Source-WebCore-WebCore-pro-make_first-ordered] Error 2

**Comment by zackw** [comment]
This almost always means either you don't have enough RAM, or your RAM is faulty.  Try `./build.sh --confirm --jobs 1`; this will make the build require less RAM (but also it will be even slower).

**Comment by arthur24b6** [comment]
I'm not getting  a segfault, but I am seeing an error from what I think is the same file on Ubuntu 15.10
```
In file included from platform/LayoutUnit.h:39:0,
                 from platform/animation/AnimationUtilities.h:30,
                 from platform/graphics/Color.h:29,
                 from dom/Document.h:32,
                 from bindings/js/JSDOMBinding.h:31,
                 from generated/JSDOMWindow.h:25,
                 from generated/JSDOMWindow.cpp:22:
../WTF/wtf/SaturatedArithmetic.h: In function ‘int32_t saturatedAddition(int32_t, int32_t)’:
../WTF/wtf/SaturatedArithmetic.h:46:26: warning: suggest parentheses around operand of ‘!’ or change ‘&’ to ‘&&’ or ‘!’ to ‘~’ [-Wparentheses]
     if (!((ua ^ ub) >> 31) & (result ^ ua) >> 31)
                          ^
{standard input}: Assembler messages:
{standard input}:59560: Warning: end of file not at end of a line; newline inserted
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile.WebCore.Target:433332: recipe for target '.obj/generated/JSDOMWindow.o' failed
make[2]: *** [.obj/generated/JSDOMWindow.o] Error 4
make[2]: Leaving directory '/var/www/phantomjs/src/qt/qtwebkit/Source/WebCore'
Makefile.WebCore:64: recipe for target 'sub-Target-pri-make_first-ordered' failed
make[1]: *** [sub-Target-pri-make_first-ordered] Error 2
make[1]: Leaving directory '/var/www/phantomjs/src/qt/qtwebkit/Source/WebCore'
Makefile:173: recipe for target 'sub-Source-WebCore-WebCore-pro-make_first-ordered' failed
make: *** [sub-Source-WebCore-WebCore-pro-make_first-ordered] Error 2
```
