### ISSUE TITLE
--remote-debugger-port in phantom.js JSON config

### ISSUE THREAD

**Issue by Andrey-Pavlov** [ariya/phantomjs#13614]
When I try to use following JSON config for phantom.js, remoteDebuggerPort parameter just gets ignored:

``` javascript
{
    "localToRemoteUrlAccessEnabled": true,
    "webSecurityEnabled": false,
    "remoteDebuggerPort": 9001,
    "remoteDebuggerAutorun": "yes"
}
```

i guess it missed in https://github.com/ariya/phantomjs/blob/e73d2ab63965184b207900bf41af0b0403b5f834/src/config.h

and please review other options.

**Comment by zackw** [comment]
1) Are you using PhantomJS 2.0?  1.9.x is no longer developed and has many bugs.

2) Please show exactly how you are starting up PhantomJS, and any code used.
