### ISSUE TITLE
Pass environment variable to child_process execFile

### ISSUE THREAD

**Issue by descl** [ariya/phantomjs#13613]
Hi and thanks for this awesome tool.

I need to make a link between my casperjs script and pgsql. So i'm building a module like this one for sqlite https://github.com/ThomasMoquet/casperjs-sqlite3/blob/master/sqlite3.js 

But in order to use the command psql we need to pass the password as an environment variable, like: "PGPASSWORD='myPassword' psql -h localhost -U login -d dbname  -c 'SELECT \* FROM table;'" 

It's working like a charm on commandline but i didnt manage to make it working as a module with the phantomjs implementation of child_process because only execFile is implemented and so i cant make something like this:

```
        childProcess.execFile("PGPASSWORD='myPassword' psql", ["-c","'request''"],  null, function (err, stdout, stderr) {});
```

Bo you have a solution? thanks, Chris

**Comment by zackw** [comment]
Indeed, this does not appear to be possible currently.  `system.env` is not writable and `child_process` does not expose anything useful.  A crude workaround would be

    child_process.execFile("/bin/sh", ["sh", "-c", "PGPASSWORD='mypassword' psql -c 'request'"], ...)

but then you'd have to deal with shell quoting.  I suppose what we ought to do is clone node.js's child_process API in detail...
