### ISSUE TITLE
PhantomJS crash help

### ISSUE THREAD

**Issue by ssangani** [ariya/phantomjs#13611]
I am trying to build a scrapper using PhantomJS and it keeps crashing at specific point in runtime. After it crashes it says to create an issue here and attach the .dmp file. I am on Windows system and I couldn't figure out how to obtain stack trace from the .dmp file and GitHub won't allow me to attach .dmp file to the issue so I uploaded it on my drive here https://drive.google.com/file/d/0BzNRHH7MTdRdYklhUGEyOXZwOEU/view?pli=1. Can anyone help me with this issue?

**Comment by zackw** [comment]
We really ought to take that message out.  .dmp files are basically useless to us.

1. Are you using PhantomJS 2.0?  1.9.x is no longer developed and has many bugs.

1. If you have a webpage that crashes using 2.0, please see if it also crashes a nightly build of WebKit, and if so, report that to the WebKit developers.  We do not have the manpower to fix WebKit bugs ourselves.

1. If you have a webpage that crashes PhantomJS 2.0 but *not* a nightly build of WebKit, we will eventually pick up the fix when we upgrade our embedded copy of WebKit, but that might be quite some time from now, sorry.
