### ISSUE TITLE
it cannot be done when the phantomjs was called by php? 

### ISSUE THREAD

**Issue by antstudio-git** [ariya/phantomjs#13612]
i wanna to capture the web page and addcookie in the js file,

```
var system = require('system');
var html_path = system.args[1];
var pdf_path = system.args[2];
var sessionid = system.args[3];
var page = require('webpage').create();
page.viewportSize = { width: 1024, height: 768 };

var ret = phantom.addCookie({
    'name':'PHPSESSID',
    'value': sessionid,
    'path':'/',
    'domain':'localhost'
});

console.log(ret===true?'true':'false');
page.open(html_path, function (status) {    
        window.setTimeout(function(){
            page.render(pdf_path);
            page.close();
            phantom.exit();
        },5000)

});
```

when i call the action in php, it cannot be done and is always running. any ideas?

**Comment by zackw** [comment]
I don't see anything obviously wrong with your code.  I have three questions for you:

1. Are you using PhantomJS 2.0?  1.9.x is no longer developed and has many bugs.
1. I don't understand what you mean by "when i call the action in php, it cannot be done and is always running."  Are you executing PhantomJS *from* a PHP script, or are you using PhantomJS to access a webpage whose server-side implementation is PHP, or both?
1. Please construct the *smallest possible* set of PHP files which, together with this PhantomJS script, reproduce the bug, and show them to us.

**Comment by antstudio-git** [comment]
i'll show the code below:
<....>
$phantomjs="phantom/pdfdll";
$pdfjs = "phantom/topdf.js";
$command = "$phantomjs $pdfjs $url $filename $sessid";

@exec($command);
<....>

and the php was published by httpd - apache as user apache

when i request the php file , the process can be find with ps -ef command, but it cannot be finished....
