### ISSUE TITLE
Assertion failed: JS engine does not provide full typed array support

### ISSUE THREAD

**Issue by bennyn** [ariya/phantomjs#13619]
Hello, 

I am using PhantomJS (in combination with [jasmine](http://jasmine.github.io/)) to run unit tests for my web application. In my application I am including [libsodium.js](https://github.com/jedisct1/libsodium.js), which is also referenced in my unit tests.

Whenever I try to run a test (which is based on libsodium.js) I get a warning from PhantomJS telling me:

> log: Assertion failed: JS engine does not provide full typed array support

> Error caught from PhantomJS. More info can be found by opening the Spec Runner in a browser.
Warning: abort("Assertion failed: JS engine does not provide full typed array support") at Error: 0

I also do get:

> PhantomJS threw an error:ERROR
> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code 3221225477. Use --force to continue.

How can this issue be solved?

**Comment by zackw** [comment]
I believe this is fixed in PhantomJS 2.0, please try that.
