### ISSUE TITLE
Is there any synchronized module like async or step in phantomjs

### ISSUE THREAD

**Issue by wangzhenxing** [ariya/phantomjs#13615]
Asynchronized js code is so sick. Is there any ynchronized module like async or step in phantomjs? @ariya

**Comment by JamesMGreene** [comment]
If it is Node.js-compatible, you can generally just put it somewhere locally and `require` it in, e.g.:

```js
var async = require("./async");
var step = require("./step.js");
```

If it is not Node.js-compatible, you can generally just put it somewhere locally and use [`phantom.injectJs`](http://phantomjs.org/api/phantom/method/inject-js.html) to load it into PhantomJS's outer context, e.g.:

```js
var wasSuccessful = phantom.injectJs("./lib/utils.js");
```
