### ISSUE TITLE
random crash .....

### ISSUE THREAD

**Issue by michliu** [ariya/phantomjs#13620]
Alaways random crash , I got a dump file (.dmp) , please help.
OS:CentOS release 5.11 (Final)
Phantomjs 1.9.2

dmp file: https://www.dropbox.com/s/9yp12e2y5d28tm0/063d108f-0ae6-0336-6be52a76-7f010c75.dmp?dl=0

**Comment by zackw** [comment]
PhantomJS 1.9.x is no longer developed.  PhantomJS 2.0 contains an enormous number of bugfixes, please try that.

If you still experience crashes with 2.0, we don't actually want the dump file; we want a minimal, self-contained test case.  Please note that nearly all crash bugs are WebKit's fault, and we do not have the manpower to fix WebKit bugs ourselves; we strongly encourage you to attempt to reproduce such bugs using a WebKit nightly build (https://www.webkit.org/) and report them directly to that team.
