### ISSUE TITLE
phantomjs throws error with node module phantom

### ISSUE THREAD

**Issue by teslaji** [ariya/phantomjs#13622]
I am trying phantomjs in MEAN stack for report generation but after installing phantom binaries in my ubuntu os server and using phantom node_module + rasterize.js throws below error.

Error: Cannot find module 'events'

  phantomjs://bootstrap.js:254 in require
  /home/kb/code/backend/backend/api_server/node_modules/phantom/node_modules/dnode/node_modules/dnode-protocol/index.js:1
  /home/kb/code/backend/backend/api_server/node_modules/phantom/node_modules/dnode/node_modules/dnode-protocol/index.js:126
Error: Cannot find module 'stream'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
  /home/kb/code/backend/backend/api_server/node_modules/phantom/node_modules/dnode/lib/dnode.js:2
  /home/kb/code/backend/backend/api_server/node_modules/phantom/node_modules/dnode/lib/dnode.js:154
Error: Cannot find module 'net'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
  /home/kb/code/backend/backend/api_server/node_modules/phantom/node_modules/dnode/index.js:3
  /home/kb/code/backend/backend/api_server/node_modules/phantom/node_modules/dnode/index.js:138
Error: Cannot find module 'http'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
  /home/kb/code/backend/backend/api_server/node_modules/phantom/phantom.js:8
  /home/kb/code/backend/backend/api_server/node_modules/phantom/phantom.js:193
  /home/kb/code/backend/backend/api_server/node_modules/phantom/phantom.js:194
TypeError: 'undefined' is not a function (evaluating 'phantom.createWebPage()')

  :/modules/webpage.js:905
  report.js:7

**Comment by zackw** [comment]
This appears to be a problem with the node wrapper for phantomjs, not with phantomjs itself.  We do not maintain the node wrapper and cannot help you with it.

If you can reproduce this problem using a standalone phantomjs controller script, executed directly from the command line, please feel free to reopen the issue.

**Comment by Xsmael** [comment]
have you found a solution for this  ? i have the same problem!
