### ISSUE TITLE
how to make Phantomjs support gzip?

### ISSUE THREAD

**Issue by ouonet** [ariya/phantomjs#13621]
I'm using Phantomjs 2.0
if I set headers "Accept-Encoding": "deflate,sdch", Phantomjs will get correct page content.
if I set headers "Accept-Encoding": "gzip,deflate,sdch", the page content will not correct .
how to make Phantomjs to support gzip?
Hope someone can help me

**Comment by zackw** [comment]
PhantomJS *does* support gzip transfer-encoding (inherited from Webkit; we
haven't done anything to turn it off).  There must be something else
wrong.  Please try to construct the *smallest possible* server application
and PhantomJS controller script which, together, reproduce the problem, and
post them here.

**Comment by zackw** [comment]
I take that back: there does seem to be a problem, as demonstrated by this test case:

```
var server = require("webserver").create();

server.listen("8080", function (request, response) {
    response.setEncoding("binary");
    response.setHeader("Content-Type", "text/html;charset=utf-8");
    response.setHeader("Content-Encoding", "gzip");
    // gzip("<!doctype html><body>hello world</body>")
    response.write(
        "\x1f\x8b\x08\x00\x00\x0a\x1c\x56\x00\x03\xb3\x51\x4c\xc9\x4f\x2e" +
        "\xa9\x2c\x48\x55\xc8\x28\xc9\xcd\xb1\xb3\x49\xca\x4f\xa9\xb4\xcb" +
        "\x48\xcd\xc9\xc9\x57\x28\xcf\x2f\xca\x49\xb1\xd1\x07\x8b\x00\x00" +
        "\x6d\x5f\x93\x08\x27\x00\x00\x00");
    response.close();
});

var page = require("webpage").create();
page.customHeaders["Accept-Encoding"] = "gzip";
page.open("http://localhost:8080/", function (status) {
    console.log(status);
    console.log(page.plainText);
    phantom.exit(status === "success" ? 0 : 1);
});
```

will print "fail" and exit unsuuccessfully.  More detailed logging is unhelpful but evocative: the [`onResourceError`](http://phantomjs.org/api/webpage/handler/on-resource-error.html) hook gets called with errorString set to "200 OK"!

Two possibilities: I screwed up generating a gzipped response, or Qt's HTTP library honestly doesn't support gzip.

**Comment by JSXRED** [comment]
I'm also interested in a solution. I have the situation that my communication endpoint is forcing gzip.

**Comment by ouonet** [comment]
@zackw It seems that this is webkit's bug. I found this  [Content-Encoding: Gzip with Qt Webkit?](https://forum.qt.io/topic/2308/content-encoding-gzip-with-qt-webkit/9).

**Comment by corford** [comment]
If I'm reading @ouonet 's linked bug report correctly, it looks like webkit automatically enables gzip providing an "accept-encoding" header isn't already present.

So @zackw 's above test case should work if page.customHeaders["Accept-Encoding"] = "gzip"; is removed. Haven't had time to test though.

**Comment by awakmu** [comment]
@ouonet I have another testcase, that verify, this is a qt's bug. ariya/phantomjs#13909

1. Without modify accept-encoding header, Phantomjs 2 will add "accept-encoding=gzip" header (though, this will not shown in page.onResourceRequested callback), and can decompress gzipped content successfully.
2. While we adding "accept-encoding=gzip" in the requests's header, Phantomjs 2 can't decompress it.

About @zackw 's test case above, I' confused, because I can run it successfully on Phantomjs 2 or 1.9.8. Any idea?

**Comment by zackw** [comment]
@awakmu The key difference between your test case and mine seems to be how we set customHeaders.  In the latest dev tree, this construct triggers the bug:

    page.customHeaders = {
        "Accept-Encoding": "gzip" // or "gzip,deflate"
    };

and this one doesn't:

    page.customHeaders["Accept-Encoding"] = "gzip"; // or "gzip,deflate"

Regarding the question you asked in #13909, we do accept patches to Qt, but we would encourage you to submit them to the Qt project _as well as_ our code.  File your pull request against [Vitallium/qtbase](https://github.com/Vitallium/qtbase) and also follow the instructions at http://wiki.qt.io/ReportingBugsInQt to submit the patch. Existing Qt bugs that appear related to this class of problems are [QTBUG-18239](https://bugreports.qt.io/browse/QTBUG-18239) and [QTBUG-41840](https://bugreports.qt.io/browse/QTBUG-41840).

Your patch should probably set autoDecompress if _either_ "gzip" _or_ "deflate" appears in the Accept-Encoding header.

**Comment by nickhaughton** [comment]
Is there any solution to this problem? I am experiencing the same issue.

**Comment by HexValid** [comment]
:+1:
