### ISSUE TITLE
Some `white-space` values on SVG `text` causes wrong computed width

### ISSUE THREAD

**Issue by erykpiast** [ariya/phantomjs#13625]
PhantomJS 2.0 & 1.9.8 on Windows.

When style `white-space: normal` (or `initial`, 'pre-wrap', 'pre-line') is set on SVG `text` element, methods `getBoundingClientRect` and `getComputedTextLength` return weird results. [See test code here](https://gist.github.com/erykpiast/6b23a1c3fb87615813e4).

For values `nowrap` and `pre` or when property is not set at all, everything works fine.

**Comment by zackw** [comment]
This is a bug in WebKit.  We do not have the manpower to fix bugs in WebKit ourselves.  Please see if you can reproduce the bug with a nightly build of WebKit (https://www.webkit.org/) and, if the bug is present there, report it directly to them.

**Comment by erykpiast** [comment]
Ok, got it! Don't be angry, I didn't know :)

**Comment by zackw** [comment]
That was supposed to sound apologetic, not angry.  My bad.

**Comment by zackw** [comment]
I am going to go ahead and close this issue, though.
