### ISSUE TITLE
phantomjs crashes when snapping the whole site

### ISSUE THREAD

**Issue by asif-burberry** [ariya/phantomjs#13630]
Crash happened on OS X (Yosemite). I was using the spider feature so I can compare the whole site.

Sorry I don't have access to Linux box...

I can't attach the dump file. It doesn't like the .dmp file format. I tried renaming it to .txt but same issue. Let me know how i can upload the .dmp file please.

**Comment by zackw** [comment]
We really need to stop telling people to give us .dmp files: Github doesn't like them and 99% of the time they turn out to be useless anyway.

What we *actually* need is a *minimal, complete, self-contained test case*.  The *smallest possible* website -- ideally just one HTML file with no external resources -- that causes PhantomJS to crash, plus precise instructions for how to apply PhantomJS to the test case to make it crash.

Additionally, are you using PhantomJS 2.0?  Almost all crash bugs are Webkit's fault, and 2.0 has a much newer Webkit.

**Comment by asif-burberry** [comment]
Unfortunately I am on phantomjs version 2.

--------
Best Regards,
Asif

**Comment by zackw** [comment]
OK.  We still need a minimal, complete, self-contained test case to be able to do anything about this.
