### ISSUE TITLE
PhantomJS crashes when looking for PayPal "confirm" button (in sandbox)

### ISSUE THREAD

**Issue by bgstar** [ariya/phantomjs#13635]
Test automation logs into PayPal Express Checkout page which loads a confirmation page dynamically.

The test attempts to click "Agree and Continue":
   driver.FindElement(By.Id("confirmButtonTop").Click()
within a WebDriverWait 'Until' function

and while it passes with ChromeDriver the PhantomJS reports an error "not found: Gave up" (error 262) and finally exists the wait function, and crashes.

Windows PhantomJS ver 2.0.0

**Comment by zackw** [comment]
This is almost certainly either a bug in Webkit or a bug in the WebDriver glue.  We do not have the manpower to fix Webkit bugs ourselves.  We *do* take responsibility for our WebDriver glue, but we will not be able to do anything about this bug unless you can provide us with a minimized, self-contained test case.  That means: a complete test program that interacts only with a test website (in particular, *not* with PayPal), both of which are as small as possible while still reproducing the problem, and both of which you can give to us and we can include in our test suite.

If you can make the problem happen *without* WebDriver, that is also valuable information.

**Comment by bgstar** [comment]
Thanks - I've resolved my issue by adding a thread-sleep to help the PhantomJS completely load the initial page. I'll close the bug but wonder if ChromeDriver is faster or PhantomJS doesn't wait for the same completion event?

**Comment by zackw** [comment]
I really can't even make a guess without a proper test case.

**Comment by rudboy972** [comment]
@bgstar hi, i need the same error on paypal with this code : 
try:
    WebDriverWait(driver, delay).until(EC.presence_of_element_located(driver.find_element_by_id('confirmButtonTop')))
    print "Page is driver!"
except TimeoutException:
    print "Loading took too much time!"

confirmButton =driver.find_element_by_id("confirmButtonTop")
confirmButton.click()

or this code : 

 confirmButton = browser.wait.until(EC.presence_of_element_located((By.ID, "confirmButtonTop")))
    confirmButton.click()

can you help me please

**Comment by bgstar** [comment]
@rudboy972
I ended up using ChromeDriver instead - it worked fine with the same code.

There is also a meta-tag in the response that contains a non-JS version of the page; you can simply navigate to that legacy PayPal version

**Comment by rudboy972** [comment]
@ bgstar Okok , I think too that Chrome is the best way for PayPal 
Thx a lot for your reponse
