### ISSUE TITLE
Fails to open files with unicode characters in filename

### ISSUE THREAD

**Issue by shakiba** [ariya/phantomjs#13633]
PhantomJS is not able to open files with unicode characters in filename, for example output of following code is `fail`:

``` js
require('webpage')
  .create()
  .open("📖.svg", function(status) {
    console.log(status);
    phantom.exit();
});
```

This issue was initially reported [here](/shakiba/svgexport/issues/14).

**Comment by zackw** [comment]
What OS, and what is the character encoding of your test file?

**Comment by shakiba** [comment]
I'm using Ubuntu, I have not tried it with other OS. The issues is with unicode character in filename.

**Comment by zackw** [comment]
Thanks.  I think you might have misunderstood my second question.  I need to know the character *encoding* of the *script that tries to open the file*, not the file that can't be opened.  ("Unicode" is a character *set*, not a character *encoding*.)

Another piece of information that would be helpful is the result of running

    LC_ALL=C ls -1fb

in the directory containing the file that can't be opened.  Type that command at a shell prompt **exactly as shown**, and post the output **unedited**.

**Comment by zackw** [comment]
I can reproduce the bug myself, but I still need to know the answers to the questions I asked, because that will help me figure out how complicated the bug is.

**Comment by shakiba** [comment]
With UTF-8 it prints "fail", if I save file as UTF-16 it prints "SyntaxError: Parse error" (contents are not corrupted) and if I replace file name with `\360\237\223\226.svg` which is result of running your second command it prints `success`.

**Comment by shakiba** [comment]
@zackw Do you know any cross-platform way to encode/escape filenames in either phantomjs or nodejs? I guess it can help me fix the issue in my own code.

**Comment by minhthuanit** [comment]
I'm also get this error when trying to capture local html page with japanese character in filename.
Please help me to figure out the way to avoid it.
Thanks you.
