### ISSUE TITLE
Make deleted QObjects actually equal to null

### ISSUE THREAD

**Issue by ricardograca** [ariya/phantomjs#13631]
Currently it seems that when one tries to access a deleted QObject it's not exactly `null`. These conditions all return false:

``` javascript
deleteQObject === null
deletedQObject == null
deletedQObject == undefined
deletedQObject === undefined
!deletedQObject
deletedQObject === 'null'
```

The only way to check if a QObject has been deleted is to concatenate it with an empty string and compare the result with a string that says `'null'`:

``` javascript
deletedQObject + '' === 'null'
```

This is extremely obscure and unexpected in a JavaScript API. Deleted QObjects should equal actual `null` and not a string that says `'null'`.

**Comment by zackw** [comment]
I'm not sure we're going to be able to do anything about this -- it might be a fundamental issue with the Qt glue layer -- but could you please provide a *complete* test case for the problem?  In particular I do not know how to set up `deletedQObject` to reproduce the issue.

**Comment by ricardograca** [comment]
An easy way to reproduce this is to attempt to send a response twice in the webserver module. I'll try to provide a test case soon.

**Comment by zackw** [comment]
The webserver module is special, in the bad way.  Please try to figure out whether this *only* affects the webserver module; if it doesn't, we would very much prefer a test case that doesn't involve it.

**Comment by ricardograca** [comment]
Will do. Thanks for the info.
