### ISSUE TITLE
2.0.1-development examples fail - Can't Find Variable

### ISSUE THREAD

**Issue by coralnut** [ariya/phantomjs#13637]
version 2.0.1-development fails to properly execute example code.

example: using the code examples provided on the QuickStart page, located here: 
http://phantomjs.org/quick-start.html

executing the following commands produces the following results:

phantomjs loadspeed.js http:/www.google.com
Loading http:/www.google.com
Loading time 1310 msec

phantomjs loadspeed.js http:/www.lowes.com
ReferenceError: Can't find variable: CQ
  http://www.lowes.com/etc/clientlibs/foundation/testandtarget/testandtarget.min.js:843 in isInSimulationMode
  http://www.lowes.com/etc/clientlibs/foundation/testandtarget/testandtarget.min.js:680 in init
Loading http:/www.lowes.com
Loading time 28913 msec

phantomjs loadspeed.js http:/www.homedepot.com
FAIL to load the address

Relevant information:
Fresh install of phantomjs was performed on 10-09-2015 following these instructions for a linux-based distro:
http://phantomjs.org/build.html

the actual target system is running Fedora 21 and the build was completed without any errors.

**Comment by zackw** [comment]
The error message you are seeing is caused by a bug in the JavaScript on Lowes' website. PhantomJS itself appears to be working correctly.  I don't know why you could not load `http://www.homedepot.com/`, that one works fine for me.

Note that there are supposed to be *two* slashes after `http:`.
