### ISSUE TITLE
iframe getboundingclientrect() positions

### ISSUE THREAD

**Issue by mutex12** [ariya/phantomjs#13632]
I'm using phantomjs v2.0 for windows to capture (cliprect) all iframes on various web pages.

The getboundingclientrect positions I receive have correct width + height, but typically left and sometimes top are off.

I wait for the page to open with a successful status, then do a js ready check on main and child frames, then perform setTimeout(func(), 4000) to call me back to ensure things are loaded.

I have a large viewport, 1024 x 2048, and tried disabling scrollbars, but still no good.

The same code in Slimerjs (getboundingclientrect + cliprect) works without issue, but has no disabling cross domain security support which I need for walking and testing dom, hence seeking to resolve in phantomjs.

I believe this is an old/outstanding webkit bug which may be related to whatever version is being used.
I found google posts indicating the same problem.

Regards.

**Comment by zackw** [comment]
This really can't be anything *but* a bug in Webkit.  We do not have the manpower to fix Webkit bugs ourselves. Please try to reproduce the problem with a nightly build of Webkit (see https://www.webkit.org/) and if you can, report it directly to them. Sorry for the trouble.
