### ISSUE TITLE
-webkit-writing-mode: vertical-rl rendered wrong character direction

### ISSUE THREAD

**Issue by djyde** [ariya/phantomjs#13648]
I use **phantom 2.0 stable** both on OS X and Linux (Ubuntu 14.04 LTS), but get something wrong with the chinese vertical writing mode.

Like the performance below, the left one is correct character direction, the right one (phantom rendered) is wrong.

![](http://i.imgur.com/QfdUjam.jpg)

The whole HTML: 
```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>vertical test</title>
		<style>
			.test{width:100px;height:100px;margin:10px;border:1px solid #aaa;}
			.lr-tb{-webkit-writing-mode:horizontal-tb;writing-mode:lr-tb;writing-mode:horizontal-tb;}
			.tb-rl{-webkit-writing-mode:vertical-rl;writing-mode:tb-rl;writing-mode:vertical-rl;}
			.tb-lr{-webkit-writing-mode:vertical-lr;writing-mode:tb-rl;writing-mode:vertical-lr;}
		</style>
	</head>
	<body>
		<div class="test lr-tb">本段文字将按照水平从左到右的书写方向进行流动。</div>
		<div class="test tb-rl">本段文字将按照垂直从右到左的书写方向进行流动。</div>
		<div class="test tb-lr">本段文字将按照垂直从左到右的书写方向进行流动。</div>
		<ul class="tb-rl">
			<li class="test">This is a test</li>
			<li class="test">本段文字将按照垂直从右到左的书写方向进行流动。</li>
		</ul>
		<ul class="tb-lr">
			<li class="test">本段文字将按照垂直从左到右的书写方向进行流动。</li>
			<li class="test">本段文字将按照垂直从左到右的书写方向进行流动。</li>
		</ul>
	</body>
</html>

```

**Comment by zackw** [comment]
This is a bug in Webkit.  Unfortunately, we do not have the manpower to fix Webkit bugs ourselves.  Please try to reproduce the problem with a nightly build of Webkit (https://www.webkit.org/) and if you can, report it directly to them.

**Comment by djyde** [comment]
Could you tell me how I can know which build was used by the Phantomjs that I'm using. And how to use the nightly webkit build in Phantomjs?

Thanks a lot.

**Comment by zackw** [comment]
> Could you tell me how I can know which build was used by the Phantomjs that I'm using

There is a fixed version for each release.  2.0 appears to correspond to "upstream subversion revision 153112".  I don't know how to map that onto Webkit release numbers.

> And how to use the nightly webkit build in Phantomjs?

Sorry, this is not possible.  You have to use the nightly build as a regular web browser.  See https://www.webkit.org/quality/reporting.html for more instructions.

**Comment by djyde** [comment]
I mean I wanna recompile the Phantomjs with the nightly build webkit, it is posiible?

**Comment by zackw** [comment]
That is the thing I was saying was not possible.
