### ISSUE TITLE
Long delay to send out the request after page redirect 

### ISSUE THREAD

**Issue by joshhe** [ariya/phantomjs#13645]
See screen shot. I tested waterfall on two websites, http://yahoo.com and http://google.com. There is a big delay after redirect and before the next request starts. 

![image](https://cloud.githubusercontent.com/assets/2215603/10441300/076bb998-70e3-11e5-8ff8-5e2a1d5d9980.png)

Is this normal? I don't see this delay in other browser, firefox or chrome.

**Comment by zackw** [comment]
Could you please tell us which version of PhantomJS you are using, and exactly how you made this screenshot?  I don't know how to reproduce the problem.

**Comment by chemicwepn** [comment]
I am using phantomjs 1.9.8. The screen shot is generated by using browsermob-proxy ( https://github.com/lightbody/browsermob-proxy) in combination with ghostdriver (https://github.com/detro/ghostdriver)
to generate the Har file. Then view the har file online here:
http://www.softwareishard.com/har/viewer/
