### ISSUE TITLE
Can not access protocol-relative URLs, like CDN scripts

### ISSUE THREAD

**Issue by alexpirine** [ariya/phantomjs#13646]
If your web page contains resources like this one:

```html
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
```

…then PhantomJS will not be able to load them.

This is an important issue, since many websites now include these URLs, and there is nothing we can do about it.

Can we add support for protocol-relative URLs?

**Comment by Vitallium** [comment]
PhantomJS supports protocol-relative URLs. Please provide a small sample to illustrate your problem.

**Comment by alexpirine** [comment]
If PhantomJS supports protocol-relative URLs, this is good news. I am sorry if I am mistaken: but I can't figure out what's going on here:

My PhantomJS version is 1.9.7. This is a non-working example:

```javascript
// test.js
var page = require('webpage').create();

var url = 'https://www.packagingwholesalers.com/members/login.aspx'

page.open(url, function (status) {
    console.log("Status: " + status);
    
    if (status == "success") {
        var h3 = page.evaluate(function() {
           return $('h3').first().text(); 
        });
        console.log(h3);
    }
    
    phantom.exit();
});
```

I see a bunch of errors:

```
$ phantomjs --ssl-protocol=TLSv1 test.js
ReferenceError: Can't find variable: $
...
```

I came across this issue using selenium. If I replace PhantomJS by Firefox, everything works fine, and jQuery is available. I thought this was because of the protocol-relative URLs…

**Comment by zackw** [comment]
Please try PhantomJS 2.0.  1.9.x is no longer being developed and has many bugs.  I can't reproduce the problem with 2.0; if you can, feel free to reopen the bug report.

**Comment by Mikrovolnovka** [comment]
Hello. The problem is here when we load the local html file.

```js
// test.js
var page = require('webpage').create();

var url = '/path/to/local/index.html'

page.open(url, function (status) {
    console.log("Status: " + status);

    if (status == "success") {
        var h3 = page.evaluate(function() {
           return $('h3').first().text(); 
        });
        console.log(h3);
    }

    phantom.exit();
});
```

PhantomJS automatically resolves url as `file://path/to/local/index.html` and loads all protocol-relative URLs with `file://` protocol:

```
Unable to load resource (request ID:14, URL:file://cdn3.optimizely.com/js/geo2.js)
Error code: 302. Description: Request for opening non-local file file://cdn3.optimizely.com/js/geo2.js
```

Is there any workaround on this?

**Comment by zackw** [comment]
Do other browsers behave differently? This is the behavior I would expect.

A possible workaround is to put a <base href> tag in the local file, specifying an http or https url.
