### ISSUE TITLE
Missing documentation for phantom.callback

### ISSUE THREAD

**Issue by svvac** [ariya/phantomjs#13644]
The `phantom.callback()` function/helper is missing documentation on the main site

**Comment by zackw** [comment]
I would write documentation, but I don't know how it works myself!

**Comment by svvac** [comment]
By the looks of it, it is a way to bind a function defined in the script context (ain't familiar with the terminology here, I'm talking about the js script executed by `phantomjs script.js`) into the webpage context.

The only use I know for it is for creating headers and footers (implemented in [src/webpage.cpp#L1288](https://github.com/ariya/phantomjs/blob/master/src/webpage.cpp#L1288)) where it basically injects a script that hooks it to appropriate callbacks defined by the WebKit engine IIRC. As I said, I'm not familiar with the codebase at all, so there could be more to it

**Comment by FelixAkk** [comment]
Here's a few things that I've discovered by experimenting:

The helper function is executed in a new page. No styling or scripting of the page that the footer/header is added to will be available.

The helper function get's converted through some process, which will crash when any variable that is not locally declared get's invoked (this throws an `SyntaxError: Parse error`). So don't reference anything inside this function, except the two pagenumber arguments that are provided.
