### ISSUE TITLE
Clicking Label doesn't check associated checkbox

### ISSUE THREAD

**Issue by scheffield** [ariya/phantomjs#13642]
The following code (karma, jasmine) works in firefox and chrome but not in phantomjs:

```
	it('foo', function() {
		$(
			'<input id="foo" type="checkbox">' +
			'<label id="lala" for="foo">foo label</label>'
		).appendTo('body');

		expect($('#foo').prop('checked')).to.be.false;
		$('#lala').trigger('click');
		expect($('#foo').prop('checked')).to.be.true;
	});
```

Not sure whether this is an jQuery or Phantom issue.

**Comment by zackw** [comment]
Are you using PhantomJS 1.x or 2.0?  2.0 contains a significantly newer Webkit which may have fixed this.

If you're using 2.0, this is still a Webkit bug.  We do not have the manpower to fix Webkit bugs ourselves.  Please try to reproduce the problem with a nightly build of Webkit (see https://www.webkit.org/) and if you can, report it directly to them.  Sorry for the trouble.

**Comment by scheffield** [comment]
Hi, sorry how carelessly: It is an Phantom: 1.9.8. I will try to reproduce this with a newer Phantom an com e back to you...
