### ISSUE TITLE
Phantomjs get stuck when running test for http://www.aruba.com/

### ISSUE THREAD

**Issue by chemicwepn** [ariya/phantomjs#13641]
I did " ./phantomjs ../examples/loadspeed.js http://www.aruba.com" on the command line. It got stuck for quite some time (more than 10 mins) and I had to manually kill it. 

Anyone know what the problem is? There is no error on the screen output.

**Comment by zackw** [comment]
Confirmed.  It appears to be stuck doing something compute-intensive involving JavaScript strings.

This is a bug in Webkit.  We do not have the manpower to fix Webkit bugs ourselves. Please try to reproduce the problem with a nightly build of Webkit (see https://www.webkit.org/) and if you can, report it directly to them. Sorry for the trouble.
