### ISSUE TITLE
Material Angular JS sites viewport does not work

### ISSUE THREAD

**Issue by zt9** [ariya/phantomjs#13643]
Any site created using Material Angular JS does not seem to get rendered properly. This is similar to the issue [opened here](https://github.com/angular/material/issues/3180).

```
var page = require('webpage').create();
page.viewportSize = { width: 1280, height: 900 };

page.open('http://52.10.111.167/', function() {
     window.setTimeout(function () {
           page.render('AngularMaterial.png');
            phantom.exit();
        }, 1000);
});
```

It is rendered like [this](https://cloud.githubusercontent.com/assets/859075/10420438/2833b238-7062-11e5-9ee1-5c6761c1675a.png). Here is how the real site [looks like](https://cloud.githubusercontent.com/assets/859075/10420457/77784a34-7062-11e5-9edc-d0e632a300e6.png). 

You can try other sites build with this framework and they have the same problem.. For eg:

* https://material.angularjs.org/latest/#/
* https://material.angularjs.org/0.11.2/#/demo/material.components.input

Any clues or how I can debug this?

**Comment by zackw** [comment]
Are you using PhantomJS 1.x or 2.0? 2.0 contains a significantly newer Webkit which may have fixed this.

If you're using 2.0, this is still a Webkit bug. We do not have the manpower to fix Webkit bugs ourselves. Please try to reproduce the problem with a nightly build of Webkit (see https://www.webkit.org/) and if you can, report it directly to them. Sorry for the trouble.
