### ISSUE TITLE
table rowspan and colspan have a problem

### ISSUE THREAD

**Issue by caroline0803** [ariya/phantomjs#13650]
sorry ,i come from china ,my english is very poor 
i have a page ，this page having some rowspan and column span ,
my phantomjs version is phantomjs-2.0.0-windows,
my page javascrpt is renderd, i set the timeout is very big .
Attach files have page ,output image and rasterize.js
thank you very much ！
![outputimage](https://cloud.githubusercontent.com/assets/3123446/10480402/9e3d5a92-729c-11e5-804b-b187a0a46b76.png)

![webpage](https://cloud.githubusercontent.com/assets/3123446/10480676/1a95724a-729e-11e5-9459-b7e8c3f5e3c1.png)

the js file is not allow upload , this is the rasterize.js file content:
-------------------------------------------file start------------------------------------------------------
var page = require('webpage').create(),
    system = require('system'),
    address, output, size,addressJquery;

if (system.args.length < 4 || system.args.length > 5) {
    console.log('Usage: rasterize.js URL filename');
    phantom.exit(1);
} else {
    address = system.args[1];
    output = system.args[2];
    addressJquery = system.args[3];
    page.viewportSize = {
        width: 1024,
        height: 600
    };

```
//page.zoomFactor = 0.6;缩放系数0-1
page.open(address, function(status) {
    /**
    page.includeJs("http://localhost:8080/IBSC/static/js/platform/component/jQuery/jquery-easyui-1.3.5/jquery.easyui.min.js", function() {
          console.log("load jquery js");
    });
    **/
    //不知道为啥：jquery的路径变为动态，则不能进行日志的输出
    console.log("load jquery start ");
    page.includeJs(addressJquery, function() {
        console.log("load jquery js");
    });
    console.log("load jquery end ");
    console.log('open page success');
    if (status !== 'success') {
        console.log('Unable to load the address!');
        phantom.exit(1);
    }

    console.log("wrait 5s page will render ");
    setTimeout(function() {
            // 通过在页面上执行脚本获取页面的渲染高度
            var heightAndWidth = page.evaluate(function() {
                //获取表格的高度和页面的宽度
                return $("#CardTable").height() + "abc" + $("#CardTable").width();
            });
            console.log('table height and widht is ' + heightAndWidth);
            var pageWidth = 1024;//宽度
            var pageHeight = 400;
            var splitArray = new Array();
            splitArray = heightAndWidth.split("abc");
            for(i = 0; i < splitArray.length; i++){
                if(i == 0){
                    console.log('table height is ' + splitArray[i])
                    pageHeight = splitArray[i];
                }else if(i == 1){
                    pageWidth = splitArray[i];
                    console.log('table width is ' + splitArray[i])
                }
            }
            //console.log('table height is ' + pageHeight + ";table width is " + pageWidth);
            //var pageHeight = bb * 0.6; 如果觉得图片尺寸过大，改成需要计算的高度乘以放大系数
            page.viewportSize = { width: pageWidth, height: pageHeight};
            page.clipRect = { top: 0, left: 0, width: pageWidth, height: pageHeight };
            //page.zoomFactor = 0.6;
            // 预留一定的渲染时间
            window.setTimeout(function() {
                page.render(output);
                page.close();
                console.log('render ok');
                phantom.exit();
            }, 7000);
    }, 7000);
});
```

}
-------------------------------------------file end------------------------------------------------------
the exe command is
phantomjs.exe rasterize.js http://localhost:8080/IBSC/avicit/ibsc/ibscfinal/ibscsummarizevscontrol/ibscCardMonitorFullManagerJSPtoPPT.jsp cnblogs2.png http://localhost:8080/IBSC/static/js/platform/component/jQuery/jquery-easyui-1.3.5/jquery.easyui.min.js

thank you very much.

**Comment by zackw** [comment]
1. I'm sorry, I do not understand what is wrong, perhaps because I don't speak Chinese.  I assume that the page is not being drawn properly but I do not see anything obviously wrong with it.  Please explain.

1. If the problem is with the page being drawn improperly, then this is a bug in Webkit.  Unfortunately, we do not have the manpower to fix bugs in Webkit ourselves.  Please try to reproduce the problem using a nightly build of Webkit (https://www.webkit.org/) and, if you can, report it directly to them.

1. We don't have access to your development servers and neither do the Webkit devs.  You should construct the smallest possible *HTML page* that reproduces the problem, and include it in your report to Webkit.

**Comment by caroline0803** [comment]
sorry ,my english is very poor ，i user page is jsp page , i want to translate the jsp page to html page ,i try it,Thank you for your prompt reply。 thank you very much。phantomjs is a very good sofrware，i used it resolve some problem，thank you。
