### ISSUE TITLE
2.0 crashes

### ISSUE THREAD

**Issue by mrqaidi** [ariya/phantomjs#13651]
i am  having this error with  ver 2.0.0     OS: linux centos
please help
1   0x1733b87 phantomjs() [0x1733b87]
2   0x174db65 phantomjs() [0x174db65]
3   0x57ab3f phantomjs() [0x57ab3f]
4   0x7ce176 phantomjs() [0x7ce176]
5   0x7ce1ad phantomjs() [0x7ce1ad]
6   0x61adb5 phantomjs() [0x61adb5]
7   0x61e5a3 phantomjs() [0x61e5a3]
8   0x67ba97 phantomjs() [0x67ba97]
9   0x67bc0e phantomjs() [0x67bc0e]
10  0x671abf phantomjs() [0x671abf]
11  0x87eaf8 phantomjs() [0x87eaf8]
12  0x87e5e9 phantomjs() [0x87e5e9]
13  0x2023095 phantomjs() [0x2023095]
14  0x1a78118 phantomjs() [0x1a78118]
15  0x1ae26d1 phantomjs() [0x1ae26d1]
16  0x201c56e phantomjs() [0x201c56e]
17  0x17a8f8c phantomjs() [0x17a8f8c]
18  0x17ae84e phantomjs() [0x17ae84e]
19  0x1ff9ef0 phantomjs() [0x1ff9ef0]
20  0x2039d98 phantomjs() [0x2039d98]
21  0x1b161e5 phantomjs() [0x1b161e5]
22  0x1ff3fa1 phantomjs() [0x1ff3fa1]
23  0x1ff66bd phantomjs() [0x1ff66bd]
24  0x440f61 phantomjs() [0x440f61]
25  0x7f36283b7d5d /lib64/libc.so.6(__libc_start_main+0xfd) [0x7f36283b7d5d]
26  0x427089 phantomjs() [0x427089]
PhantomJS has crashed. Please read the crash reporting guide at
<http://phantomjs.org/crash-reporting.html> and file a bug report at
<https://github.com/ariya/phantomjs/issues/new>.
Unfortunately, no crash dump is available.
(Is $TMPDIR (/tmp) a directory you cannot write?)

**Comment by zackw** [comment]
Thank you for the bug report.  We need more information before we can do anything about it.  Specifically, we need you to give us a complete, self-contained, and minimal test case.  That is, the *smallest possible* set of HTML page(s), resources, and PhantomJS controller script that makes the crash happen.

For future reference, a stack trace like this is useless, because it has almost no symbols.  The crash almost certainly has nothing to do with `libc.so.6(__libc_start_main)` - *every program* on your system will go through there on its way to `main`.

**Comment by mrqaidi** [comment]
thanks for your  reply  . what you want me to do  to give you more information ?

i tested my command via putty its working fine but when i use  php function   do it   its giving me this  error

and why  its not saving crash dump ?

please help . also i can give you my server root to find  issue and solve

**Comment by zackw** [comment]
> forget to say . most time when i run php its give me no output 

That suggests that your *hardware* is faulty.  Try a different computer.

> and why its not saving crash dump ?

I don't know.

> please help . also i can give you my server root to find issue and solve 

I'm very sorry, I do not have time to help you debug this any more.

**Comment by mrqaidi** [comment]
okay   do you have an php source to  call phantomjs  ?

**Comment by zackw** [comment]
No.  Please take further support requests to the mailing list.
