### ISSUE TITLE
Background grid is shifted downwards in PDF rendering

### ISSUE THREAD

**Issue by Konafets** [ariya/phantomjs#13664]
I captured an AmChart (smooth line chart) with PhantomJS. While the PNG rendering looks the same as in the browser, the grid of the PDF rendering is incorrect. I marked the difference in the image below.

I changed the CSS to print but this had no effect at all.

![phantomjs png_pdf comarision](https://cloud.githubusercontent.com/assets/363363/10571354/b2a81080-763e-11e5-9450-a7e7fbf00f05.png)

**Comment by nigulasikk** [comment]
the same problem with u

**Comment by fangwChina** [comment]
try this 
 window.setTimeout(function () {
                page.render(output);
                phantom.exit(1);
            }, 1000); //setting the time is enough to loading the page. document.ready

**Comment by nigulasikk** [comment]
but if there are many pics in this page ,how can u confirm all the pics is downloaded
