### ISSUE TITLE
Error when set src property of an Image to the URL of Blob constructed from SVG

### ISSUE THREAD

**Issue by DmitriyPogorelov** [ariya/phantomjs#13662]
Hi,

We construct SVG on the fly and then create Image with this SVG as content. It is a part of the bigger scenario, but I reproed a failure in PhantomJS with very simple scenario involving only construction of image out of Blob.

We construct SVG as a string. Then we create Blob out of this SVG. Then we create an URL for the Blob. Then this URL is used to set `src` property of an `Image`. As a result, Image does not load properly and `onerror` function on Image is called. This same page works fine in IE and Chrome.
#### PhantomJS version

2.0.0 and 2.0.1. Didn`t try other versions.
#### Here is a Javascript which I execute in PhantomJS:

``` javascript
var page = require('webpage').create();
var stderr = require('system').stderr;

page.onError = function(msg, trace) {
  var msgStack = ['ERROR: ' + msg];
  if (trace && trace.length) {
    msgStack.push('TRACE:');
    trace.forEach(function(t) {
      msgStack.push(' -> ' + t.file + ': ' + t.line + (t.function ? ' (in function ' + t.function +')' : ''));
    });
  }
  stderr.write(msgStack.join('\n'));
}

page.open('file:///E:/temp/VisCanvas.htm', function() {
phantom.exit();
});
```
#### Here is a page which I try to load in PhantomJS (via the script above, referred as VisCanvas.htm):

``` javascript
<!DOCTYPE html>
<html>
<body onload="myCanvas();">
<div id="VisCanvas"></div>
<script>
function myCanvas() {
    var svg = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100" height="100"> <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" /> </svg>';
    var svgBlob = new Blob([svg], {type: 'image/svg+xml;charset=utf-8'});
    var blobUrl = window.URL.createObjectURL(svgBlob);
    var img = new Image();
    img.onerror = function() {
        console.error("Error loading image", blobUrl);
    };
    img.src = blobUrl;
}
</script>
</body>
</html>
```
#### Error we get:

``` javascript
ERROR: Error loading image blob:file:///38f79bd4-2166-4e7f-8141-9d3d9de60099
TRACE:
 -> file:///e:/temp/VisCanvas.htm: 17 (in function onerror)
```

**Comment by tpetry** [comment]
I currently have the same problem. It's sad because this is a common trick to convert svg elements to canvas: within a `img.onload` callback you can use it to paint the svg to a canvas.

**Comment by DmitriyPogorelov** [comment]
Had to come back to this problem again. Realized that can bypass this problem by using following approach. In my example above I can use:
img.src = "data:image/svg+xml;charset=utf-8," + svg;
It works fine in phantomjs and Chrome. It does not work in IE and Edge. For IE and Edge I have to use an old approach. Hope it helps someone.
