### ISSUE TITLE
Compile error Debian 7.8

### ISSUE THREAD

**Issue by Gelio** [ariya/phantomjs#13679]
I've followed build instructions on Linux and I've encountered a few error while doing so, but they fixed themselves after trying to build once again.

Now, however, I can't seem to get the issue straightened out this way. Here's the console's output:

	{standard input}: Assembler messages:
	{standard input}:126756: Warning: end of file not at end of a line; newline inserted
	{standard input}:127637: Error: number of operands mismatch for `lea'
	{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
	g++: internal compiler error: Killed (program cc1plus)
	Please submit a full bug report,
	with preprocessed source if appropriate.
	See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
	make[2]: *** [.obj/css/CSSAllInOne.o] Error 4
	make[2]: Leaving directory `/root/phantomjs/src/qt/qtwebkit/Source/WebCore'
	make[1]: *** [sub-Target-pri-make_first-ordered] Error 2
	make[1]: Leaving directory `/root/phantomjs/src/qt/qtwebkit/Source/WebCore'
	make: *** [sub-Source-WebCore-WebCore-pro-make_first-ordered] Error 2

How do I make it work again? I've installed every package it was required from me [here](http://phantomjs.org/build.html) (the "Debian" ones).

**Comment by Vitallium** [comment]
> `g++: Internal error: Killed (program cc1plus)`

This error message almost always means that your computer does not have enough RAM to compile PhantomJS.  The build has been known to require four gigabytes of RAM *per CPU core*.  You may be able to work around the problem by invoking build.sh like this:

    ./build.sh --confirm --jobs 1

but this will make the build even slower.
