### ISSUE TITLE
Unable to install PhantomJs on lubuntu 15.04

### ISSUE THREAD

**Issue by fghebert** [ariya/phantomjs#13670]
I've tried to npm install PhantomJS2 on ubuntu 14.04

node --version > 4.2.1

Here is the standard error output : 

/usr/bin/phantomjs -> /usr/lib/node_modules/phantomjs2/bin/phantomjs

> phantomjs2@2.0.0 install /usr/lib/node_modules/phantomjs2
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://github.com/bprodoehl/phantomjs/releases/download/2.0.0-20141016/phantomjs-2.0.0-20141016-linux-x86_64.zip
Saving to /usr/lib/node_modules/phantomjs2/phantomjs/phantomjs-2.0.0-20141016-linux-x86_64.zip
Receiving...
Install exited unexpectedly
npm ERR! Linux 3.19.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "phantomjs2"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2@2.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs2@2.0.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log

See following gist of npm-debug.log: https://gist.github.com/fghebert/46205741c1ade241ac54

**Comment by Vitallium** [comment]
Thank you for reporting! But we don't maintain the NPM package. Please fill your issue in the corresponding repo: https://github.com/zeevl/phantomjs2

**Comment by helloyou2012** [comment]
problem

```
> node install.js
 
sh: 1: node: Permission denied
```

solved

```
npm config set user 0
npm config set unsafe-perm true
sudo npm install -g phantomjs
```
