### ISSUE TITLE
JavaScript interpreter crash issue (2.0.1-development) continues.

### ISSUE THREAD

**Issue by asowani** [ariya/phantomjs#13675]
Further to my thread started earlier (https://github.com/ariya/phantomjs/issues/13655), I tried to understand working of the JavaScript interpreter code using gdb. A typical stack trace I got was given below. What I would like to understand is that whether the interpreter is going into recursive loops (#29 and #15):

#10 0x000000001262e824 in WebCore::reportException(JSC::ExecState*, JSC::JSValue, WebCore::CachedScript*) ()

#11 0x000000001021e524 in WebCore::ScriptController::evaluateInWorld(WebCore::ScriptSourceCode const&, WebCore::DOMWrapperWorld*) ()
#12 0x000000001021ef60 in WebCore::ScriptController::evaluate(WebCore::ScriptSourceCode const&) ()
#13 0x000000001020439c in WebCore::ScriptController::executeScript(WebCore::ScriptSourceCode const&) ()
#14 0x00000000101cbec0 in QWebFrameAdapter::evaluateJavaScript(QString const&, QString const&) ()
#15 0x00000000100fdc84 in QWebFrame::evaluateJavaScript(QString const&, QString const&) ()

#16 0x0000000010073488 in injectCallbacksObjIntoFrame (frame=0x156e4490, callbacksObject=0x156d9540) at webpage.cpp:1601
#17 0x00000000100737c8 in WebPage::setupFrame (this=0x156da510, frame=0x0) at webpage.cpp:1613
#18 0x00000000100ee660 in WebPage::qt_static_metacall (_o=0x156da510, _c=QMetaObject::InvokeMetaMethod, _id=67, _a=0x3fffffffe908) at moc_webpage.cpp:519
#19 0x0000000013a82428 in QMetaObject::activate (sender=0x156e4490, signalOffset=3, local_signal_index=0, argv=0x0) at kernel/qobject.cpp:3680
#20 0x0000000013a81968 in QMetaObject::activate (sender=0x156e4490, m=0x153272a8 <QWebFrame::staticMetaObject>, local_signal_index=0, argv=0x0) at kernel/qobject.cpp:3546
#21 0x00000000100fbaec in QWebFramePrivate::didClearWindowObject() ()
#22 0x000000001019a114 in WebCore::FrameLoaderClientQt::dispatchDidClearWindowObjectInWorld(WebCore::DOMWrapperWorld*) ()
#23 0x00000000104dce20 in WebCore::FrameLoader::dispatchDidClearWindowObjectInWorld(WebCore::DOMWrapperWorld*) ()
#24 0x000000001021c790 in WebCore::ScriptController::initScript(WebCore::DOMWrapperWorld*) ()
#25 0x000000001021ee50 in WebCore::ScriptController::evaluateInWorld(WebCore::ScriptSourceCode const&, WebCore::DOMWrapperWorld*) ()
#26 0x000000001021ef60 in WebCore::ScriptController::evaluate(WebCore::ScriptSourceCode const&) ()
#27 0x000000001020439c in WebCore::ScriptController::executeScript(WebCore::ScriptSourceCode const&) ()
#28 0x00000000101cbec0 in QWebFrameAdapter::evaluateJavaScript(QString const&, QString const&) ()
#29 0x00000000100fdc84 in QWebFrame::evaluateJavaScript(QString const&, QString const&) ()

#30 0x000000001008644c in Utils::injectJsInFrame (jsFilePath=..., jsFileLanguage=..., jsFileEnc=..., libraryPath=..., targetFrame=0x156e4490, startingScript=true)
    at utils.cpp:138
#31 0x000000001005c6f0 in Phantom::execute (this=0x154a9740) at phantom.cpp:228
#32 0x0000000010084edc in main (argc=3, argv=0x3ffffffff698) at main.cpp:68

Is this something valid or if this is the indicator of a trouble?

Thanks,
Atul.

**Comment by zackw** [comment]
This is 100% normal.  I'll have more to say in #13655.
