### ISSUE TITLE
File://

### ISSUE THREAD

**Issue by compunuke** [ariya/phantomjs#13681]
The documentation doesn't seem to mention it, but I suspect the open method must have a URL that does not begin with file://.

Following the examples, I was able to get the title of a local document opened this way, but I was unable to parse the DOM to get, for instance, all anchors document.getElementByTagName('a');

**Comment by zackw** [comment]
Yes, unfortunately, this is a limitation of the way controller scripts are implemented right now. You can probably work around it with `--web-security=no` on the command line (before the controller script).

**Comment by twolfson** [comment]
I was leveraging this behavior in `1.9.x` for [phantomjssmith][]. Strangely, it seems to work in the Ubuntu 12.04 Travis CI build of PhantomJS. However, on Windows 7 it's fully failing and sending me to `about:blank` (even with`--web-security=no`).

[phantomjssmith]: https://github.com/twolfson/phantomjssmith
