### ISSUE TITLE
window.location.href is decoded

### ISSUE THREAD

**Issue by thomasvnoort** [ariya/phantomjs#13687]
I would expect `window.location.href` to never be decoded, none of the browsers do that. However, phantomjs 1.9.18 does decode it and that causes our application to break.

Consider the following example `breaking.js`:

```
var page = require('webpage').create();

var url = "http://www.example.com/this%20is%20decoded%20100%25/";

page.open(url, function(e) {
  var uri = page.evaluate(function() {
    return window.location.href;
  });
  console.log(uri);
  phantom.exit();
});
```

Running this gives the following:

```
% phantomjs a.js
http://www.example.com/this is decoded 100%/
```

I would expect the output to be the same as the url that is opened.

**Comment by zackw** [comment]
This looks to be another manifestation of bug #12216.  If you can test the [`encode-all-the-urls` branch](https://github.com/zackw/phantomjs/tree/encode-all-the-urls), that would be helpful.

**Comment by thomasvnoort** [comment]
Yes, that branch seems to resolve the issue. Will that branch ever be included in a 1.x release or do I need to wait for 2.x?

**Comment by zackw** [comment]
> Yes, that branch seems to resolve the issue.

Great, thanks for confirming.

> Will that branch ever be included in a 1.x release or do I need to wait for 2.x?

I'm afraid you're going to have to wait for 2.1 on this one.  Or you can keep using builds from my branch ;-)
