### ISSUE TITLE
Pure virtual fn call

### ISSUE THREAD

**Issue by morlic** [ariya/phantomjs#13684]
Dump attached.. happens fairly often during javascript unit testing on localhost, not sure how to debug it.

**Comment by morlic** [comment]
I'll update the post with trace info...

**Comment by morlic** [comment]
Can't generate trace, sorry.. version is 1.9.7, Linux 64-bit

**Comment by zackw** [comment]
Please test version 2.0.  It has a newer version of Webkit which resolved many crash bugs.

If you can reproduce the problem with 2.0, then we need a minimized test case -- you ought to be able to cut your unit tests down to a very short piece of JavaScript (plus, perhaps, a small webpage or two) that show the same problem.

**Comment by morlic** [comment]
We're using it via node modules, AFAIK 2.0 is currently not supported as a module. I'll try to use 1.9.18 for the time being
