### ISSUE TITLE
Cannot build phantomjs 2.0 on Ubuntu 15.04(Vivid Vervet)

### ISSUE THREAD

**Issue by jbrawley** [ariya/phantomjs#13691]
This is the tail of the terminal output when it fails.

'Makefile.JavaScriptCore.Target:87005: recipe for target '.obj/runtime/JSObject.o' failed
make[2]: **\* [.obj/runtime/JSObject.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[2]: Leaving directory '/home/bonnie/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore'
Makefile.JavaScriptCore:94: recipe for target 'sub-Target-pri-make_first-ordered' failed
make[1]: **\* [sub-Target-pri-make_first-ordered] Error 2
make[1]: Leaving directory '/home/bonnie/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore'
Makefile:87: recipe for target 'sub-Source-JavaScriptCore-JavaScriptCore-pro-make_first-ordered' failed
make: **\* [sub-Source-JavaScriptCore-JavaScriptCore-pro-make_first-ordered] Error 2
'

It looked similar to what was reported for Fedora 22, but when I tried including the snippet they used to fix the problem, it did not resolve the issue.

**Comment by zackw** [comment]
I'm afraid you've cut off the build log below the actual error - all of those errors are just fallout from the real problem.

Please update to the latest git sources (either `2.0` or `master` branch), and then do

    git clean -dxf
    ./build.sh --confirm --silent --jobs 1

If it still fails, provide at least 50 lines of build log.  (Look for the first appearance of the token `error: `, that will probably indicate the real problem.)
