### ISSUE TITLE
PDF Strong text appears duplicated

### ISSUE THREAD

**Issue by tonypatton** [ariya/phantomjs#13698]
I am using the 2.0.0 version of phantomjs on windows to export pdf from webapp. I have had similar issues with pdfs as mentioned in other bugs (in regards to the pagesize / viewport size). However, I am also having an issue that I can not seem to find mentioned in any other tickets. 

On our app any strong font (bold) renders twice in the pdfs, almost like a dark shadow.
To be clear, the text does not have any css shadows, regular (non bold) text does not share the issue, and the images below are greatly magnified to show the issue.

Any ideas?

Text rendered in chrome export to pdf
<img width="778" alt="screen shot 2015-10-29 at 4 20 45 pm" src="https://cloud.githubusercontent.com/assets/10273151/10832161/09e447e6-7e60-11e5-81e1-e49f0aee5226.png">

Same text rendered from phantomjs
<img width="790" alt="screen shot 2015-10-29 at 4 20 58 pm" src="https://cloud.githubusercontent.com/assets/10273151/10832171/1b11f50e-7e60-11e5-9ecf-b1faba95a213.png">

**Comment by zackw** [comment]
This is a bug in Webkit.  We do not have the manpower to fix bugs in Webkit ourselves.  Please report it directly to the Webkit developers: <https://www.webkit.org/quality/reporting.html>.
