### ISSUE TITLE
Phantomjs crashed  

### ISSUE THREAD

**Issue by sidEligible** [ariya/phantomjs#13692]
[debug] [phantom] Navigation requested: url=https://hsdvpn.cccounty.us/PlanLink/common/,DanaInfo=.a184C5.F8-DJAHK,SSL+NoBack1.html, type=Other, lock=true, isMainFrame=false
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/B820970B-7FD4-426C-9AFD-AD77B6199CB9.dmp

**Comment by zackw** [comment]
Are you using PhantomJS 2.0?  It contains a newer version of Webkit which fixes many crash bugs.

If you can still reproduce the problem with 2.0, then we need a minimized test case.

**Comment by wernight** [comment]
I also have many crashes on PhantomJS 2.0.0 mostly with the PayPal website.
