### ISSUE TITLE
Object.keys returns more than just expando properties on DOM elements

### ISSUE THREAD

**Issue by aleksey-bykov** [ariya/phantomjs#13697]
In Chrome and IE Object.keys only returns expando properties if called with a DOM element. PhantomJS returns lot more.

**Comment by zackw** [comment]
I'm not sure what the relevant standards say this is supposed to do, but if it's a bug, it's a bug in Webkit.  We do not have the manpower to fix Webkit bugs ourselves.  Please test a nightly build of Webkit, and if that exhibits the same behavior, report it to the Webkit developers: <https://www.webkit.org/quality/reporting.html>

**Comment by aleksey-bykov** [comment]
I no sure why you are closing it. **PhantomJs behaves differently** than the major browers do, it's not a problem of a certain browser it's PhantomJS problem.

**Comment by zackw** [comment]
PhantomJS uses Webkit as its rendering engine.  If this is a bug, it is a bug in Webkit, and we need you to ask the Webkit developers to fix it, because we can't do it ourselves.
