### ISSUE TITLE
Crashing on certain web link

### ISSUE THREAD

**Issue by Mohibur** [ariya/phantomjs#13699]
HI, 
I have tried the following command 
 ./phantomjs-1.9.8-linux-x86_64/bin/phantomjs  --ssl-protocol=any --ignore-ssl-errors=false --web-security=false nice.js "https://www.vizury.com/campaign/rtb/adx/cmr.php?google_gid=CAESEAxXWqYIjZRWeOkVaT5xbEk&google_cver=1"
And phantomjs crash. 
Dumped data is as below:

Operating system: Linux
                  0.0.0 Linux 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64
CPU: amd64
     family 6 model 58 stepping 9
     1 CPU

Crash reason:  SIGSEGV
Crash address: 0x0

Thread 0 (crashed)
 0  phantomjs!WebCore::ImageDocumentParser::appendBytes [ImageDocument.cpp : 135 + 0x0]
    rbx = 0x00007ffea7137d80   r12 = 0x0000000000000000
    r13 = 0x00007ffea7137e20   r14 = 0x00007f8c57e62d00
    r15 = 0x0000000001d5f340   rip = 0x000000000079d637
    rsp = 0x00007ffea7137d70   rbp = 0x00007f8c5c0da200
    Found by: given as instruction pointer in context
 1  phantomjs!WebCore::DocumentWriter::endIfNotLoadingMainResource [DocumentWriter.cpp : 208 + 0x12]
    rbx = 0x00007f8c57e0e070   r12 = 0x0000000000000001
    r13 = 0x00007ffea7137e20   r14 = 0x00000000030f4b20
    r15 = 0x0000000001d5f340   rip = 0x000000000084b532
    rsp = 0x00007ffea7137dc0   rbp = 0x00007f8c5c0da200
    Found by: call frame info
 2  phantomjs!QWebFrame::setUrl [qwebframe.cpp : 759 + 0x7]
    rbx = 0x00007f8c57e0e070   r12 = 0x00007ffea7137e90
    r13 = 0x00007ffea7137e20   r14 = 0x00000000030f4b20
    r15 = 0x0000000001d5f340   rip = 0x00000000004822da
    rsp = 0x00007ffea7137de0   rbp = 0x0000000003342740
    Found by: call frame info
 3  phantomjs!Phantom::doExit [phantom.cpp : 476 + 0x21]
    rbx = 0x00007ffea7137e90   r12 = 0x00000000030f4ad0
    r13 = 0x0000000000000000   r14 = 0x00000000030f4b20
    r15 = 0x0000000001d5f340   rip = 0x0000000000408b20
    rsp = 0x00007ffea7137e60   rbp = 0x00007ffea7137e80
    Found by: call frame info
 4  phantomjs!Phantom::exit [phantom.cpp : 400 + 0x9]
    rbx = 0x00000000030f4ad0   r12 = 0x00000000030f4ad0
    r13 = 0x000000000000000e   r14 = 0x0000000000000000
    r15 = 0x0000000001d5f340   rip = 0x0000000000408c8f
    rsp = 0x00007ffea7137ef0   rbp = 0x0000000000000000
    Found by: call frame info
 5  phantomjs!Phantom::qt_static_metacall [moc_phantom.cpp : 124 + 0x6]
    rbx = 0x00007ffea71386f0   r12 = 0x00000000030f4ad0
    r13 = 0x000000000000000e   r14 = 0x0000000000000000
    r15 = 0x0000000001d5f340   rip = 0x000000000046960f
    rsp = 0x00007ffea7137f20   rbp = 0x00007ffea71386f0
    Found by: call frame info
 6  phantomjs!Phantom::qt_metacall [moc_phantom.cpp : 169 + 0xe]
    rbx = 0x0000000000000000   r12 = 0x00000000030f4ad0
    r13 = 0x000000000000000e   r14 = 0x0000000000000000
    r15 = 0x0000000001d5f340   rip = 0x00000000004698ef
    rsp = 0x00007ffea7137f50   rbp = 0x00007ffea71386f0
    Found by: call frame info
 7  phantomjs!JSC::Bindings::QtRuntimeMetaMethod::call [qt_runtime.cpp : 1455 + 0x17]
    rbx = 0x00007ffea71384c0   r12 = 0x00007ffea71386f0
    r13 = 0x00007ffea7138890   r14 = 0x0000000000000000
    r15 = 0x0000000001d5f340   rip = 0x0000000000553007
    rsp = 0x00007ffea7137ff0   rbp = 0x0000000000000001
    Found by: call frame info
 8  phantomjs!JSC::cti_op_call_NotJSFunction [JITStubs.cpp : 2191 + 0x3]
    rbx = 0x0000000000000000   r12 = 0x00007f8c5c936100
    r13 = 0x00007f8ca04589a0   r14 = 0x00007ffea7138df8
    r15 = 0x00007f8c5c9360b8   rip = 0x0000000000f5d175
    rsp = 0x00007ffea7138da0   rbp = 0x00007ffea7138e00
    Found by: call frame info
 9  0x7f8c5cd8ac18
    rbx = 0x00007f8c5cd8bff3   r12 = 0x00000000000001ff
    r13 = 0x00007f8c5c9360b8   r14 = 0xffff000000000000
    r15 = 0xffff000000000002   rip = 0x00007f8c5cd8ac19
    rsp = 0x00007ffea7138e00   rbp = 0x00007ffea7138ea0
    Found by: call frame info
10  phantomjs!JSC::Interpreter::executeCall [JITCode.h : 77 + 0x16]
    rip = 0x0000000000f2e476   rsp = 0x00007ffea7138eb0
    Found by: stack scanning
11  phantomjs!JSC::call [CallData.cpp : 38 + 0x21]
    rbx = 0x00007ffea71390e0   r12 = 0x00007f8ca045be20
    r13 = 0x00007f8c57d98950   r14 = 0x00007f8ca045c150
    r15 = 0x00007f8ca04998f0   rip = 0x0000000000f72a1d
    rsp = 0x00007ffea7138f80   rbp = 0x00007f8c57d98cd0
    Found by: call frame info
12  phantomjs!JSC::Bindings::QtConnectionObject::execute [qt_runtime.cpp : 1863 + 0x17]
    rbx = 0x00007ffea71390e0   r12 = 0x00007f8ca045be20
    r13 = 0x00007f8c57d98950   r14 = 0x00007f8ca045c150
    r15 = 0x00007f8ca04998f0   rip = 0x0000000000542fce
    rsp = 0x00007ffea7138f90   rbp = 0x00007f8c57d98cd0
    Found by: call frame info
13  phantomjs!JSC::Bindings::QtConnectionObject::qt_metacall [qt_runtime.cpp : 1807 + 0xa]
    rbx = 0x0000000000000000   r12 = 0x00007ffea7139360
    r13 = 0x000000000333d3f0   r14 = 0x0000000000000004
    r15 = 0x00000000033704b0   rip = 0x0000000000543a0c
    rsp = 0x00007ffea7139210   rbp = 0x0000000000000000
    Found by: call frame info
14  phantomjs!QMetaObject::activate [qobject.cpp : 3555 + 0x1f]
    rbx = 0x0000000000000004   r12 = 0x0000000003341201
    r13 = 0x0000000000000000   r14 = 0x0000000000000004
    r15 = 0x00000000033704b0   rip = 0x0000000001cf7260
    rsp = 0x00007ffea7139240   rbp = 0x000000000333d3f0
    Found by: call frame info
15  phantomjs!WebPage::loadFinished [moc_webpage.cpp : 428 + 0x4]
    rbx = 0x0000000003341280   r12 = 0x0000000003341280
    r13 = 0x0000000003090ab0   r14 = 0x000000000308e208
    r15 = 0x00000000033b7a90   rip = 0x000000000046a263
    rsp = 0x00007ffea7139360   rbp = 0x00000000033b7a50
    Found by: call frame info
16  phantomjs!WebPage::finish [webpage.cpp : 735 + 0x7]
    rbx = 0x0000000003341280   r12 = 0x0000000003341280
    r13 = 0x0000000003090ab0   r14 = 0x000000000308e208
    r15 = 0x00000000033b7a90   rip = 0x0000000000412cd2
    rsp = 0x00007ffea7139380   rbp = 0x00000000033b7a50
    Found by: call frame info
17  phantomjs!WebPage::qt_static_metacall [moc_webpage.cpp : 294 + 0xb]
    rbx = 0x0000000003341280   r12 = 0x0000000003341280
    r13 = 0x0000000003090ab0   r14 = 0x000000000308e208
    r15 = 0x00000000033b7a90   rip = 0x000000000046a3b5
    rsp = 0x00007ffea71393a0   rbp = 0x00000000033b7a50
    Found by: call frame info
18  phantomjs!QObject::event [qobject.cpp : 1191 + 0x8]
    rbx = 0x0000000003341280   r12 = 0x00000000033b7a90
    r13 = 0x0000000003090ab0   r14 = 0x000000000308e208
    r15 = 0x00000000033b7a90   rip = 0x0000000001cefd28
    rsp = 0x00007ffea71394d0   rbp = 0x0000000000000000
    Found by: call frame info
19  phantomjs!QApplicationPrivate::notify_helper [qapplication.cpp : 4562 + 0xc]
    rbx = 0x00007ffea7139e80   r12 = 0x00000000033b7a90
    r13 = 0x0000000003090ab0   r14 = 0x000000000308e208
    r15 = 0x00000000033b7a90   rip = 0x00000000015dedaf
    rsp = 0x00007ffea7139670   rbp = 0x0000000003341280
    Found by: call frame info
20  phantomjs!QApplication::notify [qapplication.cpp : 4423 + 0x17]
    rbx = 0x00007ffea7139e80   r12 = 0x00000000033b7a90
    r13 = 0x00007ffea7139e80   r14 = 0x000000000308e208
    r15 = 0x00000000033b7a90   rip = 0x00000000015e7a3b
    rsp = 0x00007ffea71396a0   rbp = 0x0000000003341280
    Found by: call frame info
21  phantomjs!QCoreApplication::notifyInternal [qcoreapplication.cpp : 946 + 0x2]
    rbx = 0x000000000308e1c0   r12 = 0x00000000033b7a90
    r13 = 0x00007ffea7139e80   r14 = 0x000000000308e208
    r15 = 0x000000000308e1fc   rip = 0x0000000001cde4d4
    rsp = 0x00007ffea7139b70   rbp = 0x0000000003341280
    Found by: call frame info
22  phantomjs!QCoreApplicationPrivate::sendPostedEvents [qcoreapplication.h : 231 + 0x1f]
    rbx = 0x00000000033b7a90   r12 = 0x000000000308e1c0
    r13 = 0x0000000003341280   r14 = 0x000000000308e208
    r15 = 0x000000000308e1fc   rip = 0x0000000001cdf434
    rsp = 0x00007ffea7139bc0   rbp = 0x00000000033b7af0
    Found by: call frame info
23  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 909 + 0xc]
    rbx = 0x000000000333f1e0   r12 = 0x00007ffea7139cd0
    r13 = 0x000000000308d560   r14 = 0x0000000000000000
    r15 = 0x000000000308e2d8   rip = 0x0000000001d08123
    rsp = 0x00007ffea7139c80   rbp = 0x0000000003092030
    Found by: call frame info
24  phantomjs!QEventDispatcherQPA::processEvents [qeventdispatcher_qpa.cpp : 246 + 0x4]
    rbx = 0x000000000333f1e0   r12 = 0x0000000000000000
    r13 = 0x000000000308d560   r14 = 0x00007ffea7139d10
    r15 = 0x000000000308e2d8   rip = 0x000000000163a7a4
    rsp = 0x00007ffea7139cd0   rbp = 0x0000000003092030
    Found by: call frame info
25  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x000000000333f1e0   r12 = 0x00007ffea7139da0
    r13 = 0x00007ffea7139db0   r14 = 0x000000000308e230
    r15 = 0x000000000308e2d8   rip = 0x0000000001cdd5b5
    rsp = 0x00007ffea7139d10   rbp = 0x00007ffea7139d50
    Found by: call frame info
26  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x000000000333f1e0   r12 = 0x00007ffea7139da0
    r13 = 0x00007ffea7139db0   r14 = 0x000000000308e230
    r15 = 0x000000000308e2d8   rip = 0x0000000001cdda18
    rsp = 0x00007ffea7139d40   rbp = 0x00007ffea7139e80
    Found by: call frame info
27  phantomjs!QCoreApplication::exec [qcoreapplication.cpp : 1218 + 0x4]
    rbx = 0x000000000308e1c0   r12 = 0x00007ffea7139e80
    r13 = 0x00007ffea713a050   r14 = 0x00007ffea7139df0
    r15 = 0x0000000000000000   rip = 0x0000000001cdf8cb
    rsp = 0x00007ffea7139da0   rbp = 0x000000000308e1c0
    Found by: call frame info
28  phantomjs!main [main.cpp : 121 + 0x4]
    rbx = 0x00000000030f4ad0   r12 = 0x00007ffea7139e80
    r13 = 0x00007ffea713a050   r14 = 0x00007ffea7139df0
    r15 = 0x0000000000000000   rip = 0x0000000000427db2
    rsp = 0x00007ffea7139de0   rbp = 0x00007ffea713a018
    Found by: call frame info
29  libc-2.19.so + 0x21ec4
    rbx = 0x0000000000000000   r12 = 0x0000000000407cc0
    r13 = 0x00007ffea713a010   r14 = 0x0000000000000000
    r15 = 0x0000000000000000   rip = 0x00007f8c9ecc5ec5
    rsp = 0x00007ffea7139f40   rbp = 0x0000000000000000
    Found by: call frame info
30  phantomjs + 0x27b5f
    rip = 0x0000000000427b60   rsp = 0x00007ffea7139f60
    Found by: stack scanning

Thread 1
 0  libpthread-2.19.so + 0xc414
    rbx = 0x0000000002a84208   r12 = 0x0000000002a76160
    r13 = 0x00007f8ca059cce0   r14 = 0x0000000002a7e1a0
    r15 = 0x0000000002a7e170   rip = 0x00007f8c9f895414
    rsp = 0x00007f8c9dd36e20   rbp = 0x0000000002a76160
    Found by: given as instruction pointer in context
 1  phantomjs!WTF::TCMalloc_PageHeap::scavengerThread [FastMalloc.cpp : 2495 + 0x7]
    rip = 0x00000000004ddbfc   rsp = 0x00007f8c9dd36e50
    Found by: stack scanning
 2  phantomjs!WTF::TCMalloc_PageHeap::runScavengerThread [FastMalloc.cpp : 1618 + 0x4]
    rbx = 0x00007f8c9dd37700   r12 = 0x0000000000000000
    r13 = 0x0000000000000000   r14 = 0x00007f8c9dd379c0
    r15 = 0x00007f8c9dd37700   rip = 0x00000000004ddd99
    rsp = 0x00007f8c9dd36ed0   rbp = 0x0000000000000000
    Found by: call frame info
 3  libpthread-2.19.so + 0x8181
    rbx = 0x00007f8c9dd37700   r12 = 0x0000000000000000
    r13 = 0x0000000000000000   r14 = 0x00007f8c9dd379c0
    r15 = 0x00007f8c9dd37700   rip = 0x00007f8c9f891182
    rsp = 0x00007f8c9dd36ee0   rbp = 0x0000000000000000
    Found by: call frame info
 4  libc-2.19.so + 0xfa47c
    rip = 0x00007f8c9ed9e47d   rsp = 0x00007f8c9dd36f80
    Found by: stack scanning

Thread 2
 0  libc-2.19.so + 0xf1da3
    rbx = 0x0000000000000000   r12 = 0x00007f8c9d535db0
    r13 = 0x0000000000000008   r14 = 0x00007f8c58000a98
    r15 = 0x00007f8c58000d30   rip = 0x00007f8c9ed95da3
    rsp = 0x00007f8c9d535b80   rbp = 0x00007f8c580008e0
    Found by: given as instruction pointer in context
 1  phantomjs!qt_safe_select [qcore_unix.cpp : 83 + 0x15]
    rip = 0x0000000001d06427   rsp = 0x00007f8c9d535b90
    Found by: stack scanning
 2  phantomjs!QEventDispatcherUNIXPrivate::doSelect [qeventdispatcher_unix.cpp : 223 + 0xd]
    rbx = 0x00007f8c580012b0   r12 = 0x00007f8c9d535db0
    r13 = 0x00007f8c580008e0   r14 = 0x0000000000000000
    r15 = 0x00007f8c58000d30   rip = 0x0000000001d076e7
    rsp = 0x00007f8c9d535c20   rbp = 0x00007f8c580008e0
    Found by: call frame info
 3  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 937 + 0x4]
    rbx = 0x00007f8c580012b0   r12 = 0x00007f8c9d535db0
    r13 = 0x00007f8c580008c0   r14 = 0x0000000000000001
    r15 = 0x000000000330f1d8   rip = 0x0000000001d08192
    rsp = 0x00007f8c9d535d60   rbp = 0x00007f8c580008e0
    Found by: call frame info
 4  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x00007f8c580012b0   r12 = 0x00007f8c9d535e40
    r13 = 0x00007f8c9d535e50   r14 = 0x000000000308e230
    r15 = 0x000000000330f1d8   rip = 0x0000000001cdd5b5
    rsp = 0x00007f8c9d535db0   rbp = 0x00007f8c9d535df0
    Found by: call frame info
 5  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x00007f8c580012b0   r12 = 0x00007f8c9d535e40
    r13 = 0x00007f8c9d535e50   r14 = 0x000000000308e230
    r15 = 0x000000000330f1d8   rip = 0x0000000001cdda18
    rsp = 0x00007f8c9d535de0   rbp = 0x00007ffea7139e80
    Found by: call frame info
 6  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
    rbx = 0x000000000330f150   r12 = 0x000000000330f1d8
    r13 = 0x0000000000000001   r14 = 0x00007f8c9d5369c0
    r15 = 0x00007f8c9d536700   rip = 0x0000000001bdfef6
    rsp = 0x00007f8c9d535e40   rbp = 0x000000000330f1d8
    Found by: call frame info
 7  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x000000000330f1d8   r12 = 0x00000000030ea510
    r13 = 0x0000000000000001   r14 = 0x00007f8c9d5369c0
    r15 = 0x00007f8c9d536700   rip = 0x0000000001be2dc2
    rsp = 0x00007f8c9d535e90   rbp = 0x00000000030de480
    Found by: call frame info
 8  libpthread-2.19.so + 0x8181
    rbx = 0x00007f8c9d536700   r12 = 0x0000000000000000
    r13 = 0x0000000000000000   r14 = 0x00007f8c9d5369c0
    r15 = 0x00007f8c9d536700   rip = 0x00007f8c9f891182
    rsp = 0x00007f8c9d535ee0   rbp = 0x0000000000000000
    Found by: call frame info
 9  libc-2.19.so + 0xfa47c
    rip = 0x00007f8c9ed9e47d   rsp = 0x00007f8c9d535f80
    Found by: stack scanning

Thread 3
 0  libc-2.19.so + 0xf1da3
    rbx = 0x00007f8c57d95d60   r12 = 0x000000000000047a
    r13 = 0x000000000000000a   r14 = 0x00007f8c50000a98
    r15 = 0x00007f8c50000d30   rip = 0x00007f8c9ed95da3
    rsp = 0x00007f8c57d95b80   rbp = 0x0000000000042ede
    Found by: given as instruction pointer in context
 1  phantomjs!qt_safe_select [qcore_unix.cpp : 93 + 0x16]
    rip = 0x0000000001d06328   rsp = 0x00007f8c57d95b90
    Found by: stack scanning
 2  phantomjs!QEventDispatcherUNIXPrivate::doSelect [qeventdispatcher_unix.cpp : 223 + 0xd]
    rbx = 0x00007f8c500012b0   r12 = 0x00007f8c57d95db0
    r13 = 0x00007f8c500008e0   r14 = 0x00007f8c57d95d60
    r15 = 0x00007f8c50000d30   rip = 0x0000000001d076e7
    rsp = 0x00007f8c57d95c20   rbp = 0x00007f8c500008e0
    Found by: call frame info
 3  phantomjs!QEventDispatcherUNIX::processEvents [qeventdispatcher_unix.cpp : 937 + 0x4]
    rbx = 0x00007f8c500012b0   r12 = 0x00007f8c57d95db0
    r13 = 0x00007f8c500008c0   r14 = 0x0000000000000001
    r15 = 0x0000000003380698   rip = 0x0000000001d08192
    rsp = 0x00007f8c57d95d60   rbp = 0x00007f8c500008e0
    Found by: call frame info
 4  phantomjs!QEventLoop::processEvents [qeventloop.cpp : 149 + 0x1]
    rbx = 0x00007f8c500012b0   r12 = 0x00007f8c57d95e40
    r13 = 0x00007f8c57d95e50   r14 = 0x000000000308e230
    r15 = 0x0000000003380698   rip = 0x0000000001cdd5b5
    rsp = 0x00007f8c57d95db0   rbp = 0x00007f8c57d95df0
    Found by: call frame info
 5  phantomjs!QEventLoop::exec [qeventloop.cpp : 200 + 0x4]
    rbx = 0x00007f8c500012b0   r12 = 0x00007f8c57d95e40
    r13 = 0x00007f8c57d95e50   r14 = 0x000000000308e230
    r15 = 0x0000000003380698   rip = 0x0000000001cdda18
    rsp = 0x00007f8c57d95de0   rbp = 0x00007ffea7139e80
    Found by: call frame info
 6  phantomjs!QThread::exec [qthread.cpp : 542 + 0xc]
    rbx = 0x0000000003380610   r12 = 0x0000000003380698
    r13 = 0x0000000000000001   r14 = 0x00007f8c57d969c0
    r15 = 0x00007f8c57d96700   rip = 0x0000000001bdfef6
    rsp = 0x00007f8c57d95e40   rbp = 0x0000000003380698
    Found by: call frame info
 7  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x0000000003380698   r12 = 0x0000000003380750
    r13 = 0x0000000000000001   r14 = 0x00007f8c57d969c0
    r15 = 0x00007f8c57d96700   rip = 0x0000000001be2dc2
    rsp = 0x00007f8c57d95e90   rbp = 0x00000000033805f0
    Found by: call frame info
 8  libpthread-2.19.so + 0x8181
    rbx = 0x00007f8c57d96700   r12 = 0x0000000000000000
    r13 = 0x0000000000000000   r14 = 0x00007f8c57d969c0
    r15 = 0x00007f8c57d96700   rip = 0x00007f8c9f891182
    rsp = 0x00007f8c57d95ee0   rbp = 0x0000000000000000
    Found by: call frame info
 9  libc-2.19.so + 0xfa47c
    rip = 0x00007f8c9ed9e47d   rsp = 0x00007f8c57d95f80
    Found by: stack scanning

Thread 4
 0  libpthread-2.19.so + 0xc7ce
    rbx = 0x00007f8c50006b30   r12 = 0x0000000000000001
    r13 = 0x00007f8c5758ddf0   r14 = 0xffffffffffffff92
    r15 = 0x00007f8c50006a00   rip = 0x00007f8c9f8957ce
    rsp = 0x00007f8c5758dd70   rbp = 0x00007f8c50006e10
    Found by: given as instruction pointer in context
 1  phantomjs!QWaitCondition::wait [qwaitcondition_unix.cpp : 84 + 0x7]
    rip = 0x0000000001be3ad7   rsp = 0x00007f8c5758ddd0
    Found by: stack scanning
 2  phantomjs!QThreadPoolThread::run [qthreadpool.cpp : 141 + 0x1d]
    rbx = 0x00007f8c50006a50   r12 = 0x00007f8c50006ad9
    r13 = 0x0000000000000002   r14 = 0x00007f8c5758e9c0
    r15 = 0x00007f8c5758e700   rip = 0x0000000001bd793d
    rsp = 0x00007f8c5758de50   rbp = 0x00007f8c50006e10
    Found by: call frame info
 3  phantomjs!QThreadPrivate::start [qthread_unix.cpp : 338 + 0x9]
    rbx = 0x00007f8c480012b0   r12 = 0x00007f8c50006fb0
    r13 = 0x0000000000000001   r14 = 0x00007f8c5758e9c0
    r15 = 0x00007f8c5758e700   rip = 0x0000000001be2dc2
    rsp = 0x00007f8c5758de90   rbp = 0x00007f8c50006e10
    Found by: call frame info
 4  libpthread-2.19.so + 0x8181
    rbx = 0x00007f8c5758e700   r12 = 0x0000000000000000
    r13 = 0x0000000000000000   r14 = 0x00007f8c5758e9c0
    r15 = 0x00007f8c5758e700   rip = 0x00007f8c9f891182
    rsp = 0x00007f8c5758dee0   rbp = 0x0000000000000000
    Found by: call frame info
 5  libc-2.19.so + 0xfa47c
    rip = 0x00007f8c9ed9e47d   rsp = 0x00007f8c5758df80
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x0268dfff  phantomjs  ???  (main)
0x7f8c566fe000 - 0x7f8c56757fff  DejaVuSerif.ttf  ???
0x7f8c56758000 - 0x7f8c5695dfff  libnss_dns-2.19.so  ???
0x7f8c5695e000 - 0x7f8c56b69fff  libnss_files-2.19.so  ???
0x7f8c56b6a000 - 0x7f8c56d82fff  libresolv-2.19.so  ???
0x7f8c9dd38000 - 0x7f8c9df96fff  libssl.so.1.0.0  ???
0x7f8c9df97000 - 0x7f8c9e36dfff  libcrypto.so.1.0.0  ???
0x7f8c9e372000 - 0x7f8c9e63afff  locale-archive  ???
0x7f8c9e63b000 - 0x7f8c9e864fff  libexpat.so.1.6.0  ???
0x7f8c9e865000 - 0x7f8c9ea8afff  libpng12.so.0.50.0  ???
0x7f8c9ea8b000 - 0x7f8c9eca3fff  libz.so.1.2.8  ???
0x7f8c9eca4000 - 0x7f8c9f063fff  libc-2.19.so  ???
0x7f8c9f069000 - 0x7f8c9f27efff  libgcc_s.so.1  ???
0x7f8c9f27f000 - 0x7f8c9f584fff  libm-2.19.so  ???
0x7f8c9f585000 - 0x7f8c9f873fff  libstdc++.so.6.0.19  ???
0x7f8c9f889000 - 0x7f8c9faa2fff  libpthread-2.19.so  ???
0x7f8c9faa7000 - 0x7f8c9fcaefff  librt-2.19.so  ???
0x7f8c9fcaf000 - 0x7f8c9feb2fff  libdl-2.19.so  ???
0x7f8c9feb3000 - 0x7f8ca00eefff  libfontconfig.so.1.8.0  ???
0x7f8ca00ef000 - 0x7f8ca0391fff  libfreetype.so.6.11.1  ???
0x7f8ca0392000 - 0x7f8ca03b4fff  ld-2.19.so  ???
0x7f8ca05ae000 - 0x7f8ca05b1fff  d589a48862398ed80a3d6066f4f56f4c-le64.cache-4  ???
0x7ffea71e5000 - 0x7ffea71e6fff  linux-gate.so  ???

**Comment by zackw** [comment]
Please test PhantomJS 2.0.  2.0 contains a newer Webkit which may well have fixed this bug.

If you can reproduce this problem with 2.0, please test a nightly build of Webkit and, if you still observe a crash, report the problem directly to them: <https://www.webkit.org/quality/reporting.html> We do not have the manpower to fix bugs in Webkit ourselves.

**Comment by Mohibur** [comment]
Thanks for the update, even though, I labeled it as 1.9.. It was crashing on both 1.9 and 2.0. Anyway, I understand that this is caused by third party software. I will do as you have suggested.
