### ISSUE TITLE
Porting PhantomJS to ppc64le.

### ISSUE THREAD

**Issue by asowani** [ariya/phantomjs#13708]
PhantomJS is an important software used to headless browser testing. At present PhantomJS is not available on ppc64le platform. The main hurdle is that the two main components viz. Google Breakpad and QtWebkit need to be ported to ppc64le first. Towards this, two issues have been created for Breakpad and QtWebkit:
https://bugs.chromium.org/p/google-breakpad/issues/detail?id=673
https://bugreports.qt.io/browse/QTBUG-49219
Once these packages are ported to ppc64le, they need to be integrated in PhantomJS and then PhantomJS code needs to be compiled for ppc64le. At present, no substantial effort is identified in order to port PhantomJS code (excluding above mentioned components) to ppc64le platform.

**Comment by smartmouse** [comment]
Any updates ? We need this too.

**Comment by ariya** [comment]
We don't use Breakpad anymore. Porting QtWebKit won't be trivial.

Please track the progress, if any, in those upstream issues. PhantomJS won't be ported until those issues are resolved.

**Comment by asanjar** [comment]
any update? lack of phantomjs support for Power architecture is breaking Apache Zeppelin build on Power as well..

**Comment by ayappanec** [comment]
i am able to build phantomjs 2.1.1 and the development branch as such without any fixes in ppc64le (RHEL 7.1)
Ran some of the examples which comes with the source.
Ran the test-suite as well..
$ python run-tests.py
ff...................f.........f.............s................P............s....f...
module/webpage/render: XPASS
XPASS: JPEG
XPASS: JPEG (format option)
XPASS: JPEG (quality option)
XPASS: JPEG (format and quality options)

17.470s elapsed
  203 passed
    4 passed unexpectedly
   12 failed as expected
    2 skipped

I am interested in contributing the binary to the official download site. 
https://bitbucket.org/ariya/phantomjs/downloads

**Comment by ayappanec** [comment]
I also managed to build the binary with few dynamic linkings
$ ldd phantomjs
        linux-vdso64.so.1 =>  (0x00003fff884c0000)
        libz.so.1 => /lib/powerpc64le-linux-gnu/libz.so.1 (0x00003fff88480000)
        libfontconfig.so.1 => /usr/lib/powerpc64le-linux-gnu/libfontconfig.so.1 (0x00003fff88410000)
        libfreetype.so.6 => /usr/lib/powerpc64le-linux-gnu/libfreetype.so.6 (0x00003fff88330000)
        libdl.so.2 => /lib/powerpc64le-linux-gnu/libdl.so.2 (0x00003fff88300000)
        libpthread.so.0 => /lib/powerpc64le-linux-gnu/libpthread.so.0 (0x00003fff882c0000)
        libstdc++.so.6 => /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6 (0x00003fff88150000)
        libm.so.6 => /lib/powerpc64le-linux-gnu/libm.so.6 (0x00003fff88060000)
        libgcc_s.so.1 => /lib/powerpc64le-linux-gnu/libgcc_s.so.1 (0x00003fff88030000)
        libc.so.6 => /lib/powerpc64le-linux-gnu/libc.so.6 (0x00003fff87e60000)
        /lib64/ld64.so.2 (0x000000005da70000)
        libexpat.so.1 => /lib/powerpc64le-linux-gnu/libexpat.so.1 (0x00003fff87e00000)
        libpng12.so.0 => /lib/powerpc64le-linux-gnu/libpng12.so.0 (0x00003fff87dc0000)

**Comment by ayappanec** [comment]
Uploaded the binary tar in the below link
https://github.com/ibmsoe/phantomjs/releases/download/2.1.1/phantomjs-2.1.1-linux-ppc64.tar.bz2

**Comment by ayappanec** [comment]
I am interested in contributing the binary to the official download site. 
https://bitbucket.org/ariya/phantomjs/downloads
