### ISSUE TITLE
 Phantomjs : html to single page pdf conversion gives blank pdf 

### ISSUE THREAD

**Issue by jagadale1** [ariya/phantomjs#13706]
I am using phantomjs 2.0 version for url to single page pdf conversion. for some file phantomjs generate black pdf . I want output in single page pdf .

**Comment by zackw** [comment]
Thank you for the bug report.  To do anything about it we need a minimized test case -- that is, the smallest possible webpage which is rendered incorrectly.

**Comment by ldeavila** [comment]
+1 on this issue. I am trying to generate a PDF from HTML on CentOS 7. Text is blank. I reused the existing rasterize.js sample from phantomjs.org. 

`var page = require('webpage').create();
page.open('http://github.com/', function() {
page.render('phantomjs.pdf');
phantom.exit();
});`

The above code works perfectly fine on iOS. Additionally, the above code causes a crash on 1.9.8.
