### ISSUE TITLE
A date of November 1, 2015 at 2:00:00 CST returns the wrong time

### ISSUE THREAD

**Issue by scottfwalter** [ariya/phantomjs#13703]
console.log(new Date(2015,10,1,2)) returns Sun Nov 01 2015 01:00:00 GMT-0600 (CST) however Chrome, Safari and Firefox return:

Sun Nov 01 2015 02:00:00 GMT-0600 (CST)

When constructing a date object on November 1, 2015 specifying an hour of either: 2,3,4,5,6 causes the issue.  Specifying an hour of 0,1 or greater than 6 does not exhibit the issue.

**Comment by zackw** [comment]
This looks like a bug in your operating system's timezone information and/or in the way Webkit uses it.  Unfortunately, we do not have the manpower to fix Webkit bugs ourselves.  Please try to reproduce the problem with a nightly build of Webkit, and if you can, report the bug directly to them: <https://www.webkit.org/quality/reporting.html>
