### ISSUE TITLE
Error: phantomjs terminated with signal SIGSEGV

### ISSUE THREAD

**Issue by WNLee** [ariya/phantomjs#13702]
Hello!
When I run phantomjs, it catch "phantomjs terminated with signal SIGSEGV". I don't know what happened! What caused this error？What should I do？

<img width="289" alt="2015-11-03 12 46 43" src="https://cloud.githubusercontent.com/assets/3413551/10887968/9df8b8a6-81c4-11e5-8876-6ce08dbb7846.png">

**Comment by zackw** [comment]
Please make sure you are using PhantomJS 2.0.  2.0 fixes many crash bugs.

If you still have a problem, please file a new bug including a self-contained test case - the *smallest possible* page you can construct that causes PhantomJS to crash.

**Comment by WNLee** [comment]
`upx -d phantomjs` can fix my problem. Phantomjs can run on my OS X 10.10.5.

**Comment by WNLee** [comment]
`upx -d phantomjs` can fix my problem. Phantomjs can run on my OS X 10.10.5.
