### ISSUE TITLE
PhantomJs doesn't load fixtures using Jasmine and Jasmine-jQuey

### ISSUE THREAD

**Issue by RaduPoe** [ariya/phantomjs#13713]
I use the PhantomJs 2 and Jasmine for testing. My current tests use also the Jasmine-jQuery to load html fixtures locally hosted the same website structure, sibling to the test. 

in any browser -> everything runs fine, the fixture is loaded.
in PhantomJs -> the fixture is not loaded.

The PhantomJs is called by Resharper with the following parameters: --proxy-type=none --ssl-protocol=any --local-to-remote-url-access=yes --web-security=no

Please let me know how can I make the tests run everywere.

**Comment by darrensw777** [comment]
@RaduPoe Did you ever find a solution for this? I've got the same issue detailed here: http://stackoverflow.com/questions/37300512/phantomjs-cant-find-jasmine-fixture
