### ISSUE TITLE
onLoadFinished called before images are loaded

### ISSUE THREAD

**Issue by donv** [ariya/phantomjs#13717]
Hi!

When switching from phantomjs 1.9.8 to 2.0.0 we see a change in behaviour of `onLoadFinished`.  When using 1.9.8 the images on the page are always loaded before `onLoadFinished` is fired, while when using 2.0.0 the images may or may not be loaded.

This is tested using poltergeist by calling `visit` and taking a screen shot directly afterwards.  https://github.com/teampoltergeist/poltergeist/issues/649

Is this a known change in phantomjs 2.0.0?

Is there are way to wait until images have completed loading before taking a screen shot?

**Comment by awakmu** [comment]
I don't know if this is an issued on v2.
I have many cases that not all resource finished loaded when onLoadFinished callback called, in v1.9.

You can use page.onResourceReceived to track if your image already received.

**Comment by donv** [comment]
@awakmu Thanks for the response.  OK, so `onLoadFinished` does not guarantee that resources are loaded.  Is there an easy way to ensure all images are loaded?  Must I scan the dom for `img` elements and check each one myself?

**Comment by awakmu** [comment]
You can use this technique https://github.com/ariya/phantomjs/blob/master/examples/waitfor.js

**Comment by donv** [comment]
Thanks for the tip @awakmu !  It paid off.  The problem was not `visit` but a JS-enabled link that manipulated the DOM.  I ended up with a simple script that serves my needs:

```javascript
function pending_image() {
  var images = document.images;
  for (var i = 0; i < images.length; i++) {
    if (!images[i].complete) {
        return images[i].src;
    }
  }
  return false;
}
```

I wait-loop until this function returns false before I take the screen shot.  Thanks again.  Closing.
