### ISSUE TITLE
Wish for PDF render corresponding to print, not screenshot

### ISSUE THREAD

**Issue by en90** [ariya/phantomjs#13714]
Hello, render to PDF using [PhantomJS examples/rasterize.js](https://github.com/ariya/phantomjs/blob/master/examples/rasterize.js) currently produces screenshot-like output. Is it possible to get output like a browser would give when printing a page and selecting save as PDF? If so, can it also, like ordinary browsers, output *without* header and footer text? (By header and footer, I mean the title, time stamp, URL and page numbering.) Can the margins be adjusted to zero using CSS3 `@page` rule?

If this is not possible, consider this issue a feature request.

**Comment by Neoshinji-** [comment]
You can use phantomjs as data extractor, and then apply mPDF library (it's possible to customize with a lot of options: margins, header, footer, multiple pages, watermarks, protect document...). Your solution exists ;)

Here some examples of you can do: 
http://www.mpdf1.com/mpdf/index.php?page=Examples

**Comment by en90** [comment]
Thank you, @Neoshinji-
