### ISSUE TITLE
Support Qt 5.5

### ISSUE THREAD

**Issue by infinity0** [ariya/phantomjs#13727]
This is preventing PhantomJS 2 from entering Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=795719

**Comment by infinity0** [comment]
Patch against 2.0.0 here: https://anonscm.debian.org/cgit/collab-maint/phantomjs.git/tree/debian/patches/port-to-qt55.patch

It doesn't apply against HEAD but I think the conflicts are pretty trivial to fix.

**Comment by infinity0** [comment]
It would also be preferable to remove Qt from the source tree. It greatly reduces the source tarball (87MB to 5MB) and reduces the build time to ~2 minutes.

**Comment by zackw** [comment]
I've read over your patch and the Debian bug report.  I'm going to see how much of it I can merge into the current tree without breaking the build with the bundled 5.4.  However, there are major problems with moving to 5.5 at present:

* The loss of `webSecurity` is a deal-breaker for us. A substantial fraction of our user base absolutely relies on being able to do `--web-security=no` on the command line.  If we can't make that work in 5.5 then we're never going to pick up 5.5.  (Also, you didn't remove the code that *sets* `
def[PAGE_SETTINGS_WEB_SECURITY_ENABLED]`, so the command line option would still exist and silently not work, which is even more unacceptable.)

* I might be wrong about this; however, it is my understanding that the bundled Qt(Webkit) 5.4 is nontrivially modified, such that an unbundled 5.4 flat-out does not work.  (The `build.sh` options that appear to allow building with system-provided Qt and QtWebkit were intended to be a step toward fixing that, but no further work was done; the last time I tried it, it didn't even compile that way.)  How thoroughly did you test your unbundled 5.5 build?  Note that the test suite is not as thorough as it could be, and might not detect the problems.

* Even if building with an unbundled Qt worked, the bulk of people who download the program directly from us want a static link, so we need to preserve a bundled build as an option. However, we did just move much of the bundled code to git submodules, so I suppose a pjs-only source tarball is a possibility.

@Vitallium Over in #12948 you said you thought 5.5 wouldn't be hard - am I wrong about any of this?

**Comment by Vitallium** [comment]
@zackw you're correct. We can upgrade to Qt 5.5 safely. I'll take care of it.

We can't remove bundled copy of Qt. Since we customized it for our needs. QtBase contains our headless platform for Linux. QtWebkit contains several important changes: header/footer printing, WebSecurity control option.
Even if you build PhantomJS with the system provided Qt, we don't guarantee its work (as an example, you will not be able to print custom footer or header).

**Comment by infinity0** [comment]
@zackw yes it's a preliminary patch and I haven't released it yet. Will look at removing that option. Perhaps you can persuade Qt5.5 upstream to re-add webSecurity?

@Vitallium do you have a diff of PhantomJS's modifications? FWIW not only could I build with the patch I wrote, I could also actually run the resulting binary (dynamically linked against Debian Qt 5.5) through Karma, passing all my previous tests just as 1.9.8 did.

How many of those modifications can you push back to Qt upstream, and how many can you re-factor out back into PhantomJS? Don't you think the massive size **and** build time reduction is worth doing this?

**Comment by Vitallium** [comment]
@infinity0
>do you have a diff of PhantomJS's modifications? 
you can create a simple diff on Qt release version (5.4.2) and our bundled copy to see the difference.

>FWIW not only could I build with the patch I wrote, I could also actually run the resulting binary (dynamically linked against Debian Qt 5.5) through Karma, passing all my previous tests just as 1.9.8 did.
Our tests doesn't cover all functionality (we don't test custom headers). Also, as @zackw mentioned, `webSecurity` is the important option. We can't remove it.

>How many of those modifications can you push back to Qt upstream, and how many can you re-factor out back into PhantomJS?
We can't push any modification back to the upstream, because QtWebkit is not supported anymore by Digia. I doubt they will accept patches.

>Don't you think the massive size and build time reduction is worth doing this?
I think yes, worth. We have (I have) a lot of planned changes to implement to our bundled copy, and since QtWebkit became deprecated, I don't see anything bad in keeping it in our source tree.

/cc @ariya

**Comment by infinity0** [comment]
OK, I can see https://github.com/Vitallium/qtwebkit - I suppose this will make it fairly easy to track changes, then. It will cost more developer time in the long run, to maintain your own copy of QtWebkit. I heard already that PhantomJS developers do not have that much time to spare. Have you seen the [QtWebEngine](https://wiki.qt.io/Porting_from_QtWebKit_to_QtWebEngine)?

Is it feasible then, to avoid bundling QtBase? Or at least track Qt upstream on this, instead of your own fork. You may think that you are saving time by making minor patches to QtBase, but bundling your own copy is not merely about patching it easily - you are effectively implying a contract to your users, "I will track *the entire upstream QtBase code* myself and merge in any security bugfixes". This is a long-time developer time commitment, *in addition* to maintaining patches you apply to your bundled copy.

In practise, most people that do what you're doing, don't make this commitment, which then pushes this cost (of preventing bit-rot) out to every single distribution, such as Debian. This is why we really really don't like static linking.

**Comment by zackw** [comment]
* Yes, we are painfully aware of the cost we are inflicting on ourselves by doing this, you do not need to remind us.
* Unfortunately, QtWebEngine is not an option as it does not provide all the hooks we need.
* The QtBase changes are not minor.

**Comment by Vitallium** [comment]
PhantomJS build on top of Qt 5.5.1 now. See https://github.com/ariya/phantomjs/issues/13377

**Comment by varac** [comment]
@zackw: I saw that pjs2 .deb package was removed from Debian unstable because of this bug. This bug has been closed now, and i'm wondering if there's any traction to get it into unstable again ?

**Comment by zackw** [comment]
@varac We are still embedding an entire copy of QtWebkit, so, no, PJS should not be packaged for Debian until further notice.
