### ISSUE TITLE
ReferenceError: Can't find variable: require

### ISSUE THREAD

**Issue by sasha2002** [ariya/phantomjs#13733]
Have error similar to this :
http://stackoverflow.com/questions/30779915/is-it-possible-to-use-fs-filesystem-module-inside-page-executed-by-phantomjs

var fs = require('fs');
...
ReferenceError: Can't find variable: require

Anyone know how to solve this?

this is javascript that was executed in page

**Comment by Vitallium** [comment]
Hi. No, you can't do that. You can't reference or use any built-in module inside the page context. Use `page.evaluate` to transfer needed objects or data.
