### ISSUE TITLE
Phantomjs opens a about:blank page instead of the URL

### ISSUE THREAD

**Issue by Angelanu** [ariya/phantomjs#13738]
I am creating a new project with phantomjs and selenium. I am able to see the instance of driver is opened but it is showing the title as about:blank. Can anyone tell me what is that i am doing wrong.
have attched the pom.xml and my test java file.
[MavenTest.txt](https://github.com/ariya/phantomjs/files/38931/MavenTest.txt)
[pom.txt](https://github.com/ariya/phantomjs/files/38930/pom.txt)

**Comment by pere00** [comment]
Hi, could you find a solution? Same happens to me with phantom 1.9.7.

**Comment by masud-technope** [comment]
Which version of PhantomJS and casperJS solved this issue? I am facing this problem
casperjs 1.1.3
phantomjs 2.1.1

**Comment by pere00** [comment]
I could not solve it yet. With chromedriver it works perfectly. Basically it is the same issue here:
https://github.com/detro/ghostdriver/issues/177

**Comment by masud-technope** [comment]
The problem was occurring due to casperjs 1.1.2. Although the folder was casperjs 1.1.3, I checked the version by command "casperjs --version", and found that it was originally 1.1.2. Then I made sure that casperjs is really 1.1.3, and the problem disappeared.

**Comment by andfinally** [comment]
I still get the issue even after upgrading to 1.1.4.

**Comment by rgalaxy** [comment]
it happens to me, casperjs 1.1.0-beta5, phantomjs 2.1.1
it happens as i added new test, and increasing casper.setMaxListeners(25); before it was 16, 

but now even i delete the test or decrease the maxListener, it keeps giving the error
