### ISSUE TITLE
SVG incomplete

### ISSUE THREAD

**Issue by ccuenca** [ariya/phantomjs#13739]
Hi all

i have a svg file generated from Telerik RadHtmlChart and with the regular command line to rasterize i found an imcomplete image like this

[imagen.pdf](https://github.com/ariya/phantomjs/files/39114/imagen.pdf)

i was trying with the width and height but the result just works for width.

**Comment by zackw** [comment]
We need to see the document you were trying to rasterize.  Also, if you are using 1.9.x please try 2.0, it contains a much newer Webkit which may have fixed this problem.

**Comment by ccuenca** [comment]
Thanks!
