### ISSUE TITLE
PhantomJS 2.0.0 crashes when upgrading Babel and core-js

### ISSUE THREAD

**Issue by lencioni** [ariya/phantomjs#13734]
I am currently using PhantomJS 2 for running my Jasmine and Capybara tests for a web app. When using Babel 5.1.11 (which is using core-js 0.8.4) things are working fine. However, when I try to upgrade these (even with the new Babel 6 and core-js 1.2.6), PhantomJS crashes. This happens both on my laptop (Mac OS X 10.10.5) and in my CI environment (CentOS Linux release 7.1.1503).

Here's the dump file that was generated from my laptop: https://www.dropbox.com/s/vw0x0g6ei1eleav/phantomjs.dmp?dl=0

It seems to crash from some combination of specs that I run. For example, if I run a set of specs it will crash at the same point every time. But, if I run each of them in isolation, it doesn't end up crashing.

I hope this is helpful. Please let me know if there's any more info I can provide.

**Comment by janpaul123** [comment]
Still running into this. Would be great if someone could have a look at this.

**Comment by trotzig** [comment]
I'm seeing crashes in babel 5.8.34, which is also using core-js 1.2.6.

**Comment by laggingreflex** [comment]
Could #13836 be a cause of this? I'm using Babel 6 on my ph scripts and requiring babel-polyfill (as is required by babel 6) which I think is what uses core-js and I think it was in that (some core-js files) in which I discovered that bug. So try compiling from latest source and see if that resolves it? it did in my case.

**Comment by trotzig** [comment]
@laggingreflex I don't think so, but I'll do some digging to find out more about what the crash is caused by.

**Comment by trotzig** [comment]
I was going to convert the dump file into a stack trace, as explained here: http://phantomjs.org/crash-reporting.html . Unfortunately there's no download for 2.0.0 macosx with symbols. Therefore it's hard to produce anything useful. I'm attaching the dump anyway, but I don't think it reveals anything.

[dump.txt](https://github.com/ariya/phantomjs/files/90500/dump.txt)

EDIT: I just read https://github.com/ariya/phantomjs/issues/13367 which reports the issue of the missing symbol files. And then further down, there's this reply:

> And most crash reports turn out to be bugs in Qt and Webkit, which we can't do anything about directly. And we need to rewrite the crash reporting instructions to make it clear that a crash dump isn't enough for us to go on -- we also need some way of making the crash happen for ourselves.

My next attempt will be to build phantomjs from source as @laggingreflex suggests above.

**Comment by trotzig** [comment]
I couldn't get phantomjs to compile on my local macbook. But I found something interesting: Turning off source maps in our Webpack config seems to resolve the issue, so perhaps @laggingreflex was right in that this is caused by the same problem as https://github.com/ariya/phantomjs/issues/13836.

**Comment by zackw** [comment]
The most valuable thing you can do here is construct a minimal, complete, and self-contained test case.  I'm not familiar with Babel, so I can't be terribly specific, but the abstract thing we need is a set of files - PJS controller script + all of the HTML, JS, etc. that it tries to load - such that we could reproduce the crash on our own machines running the controller script, and it wouldn't try to load anything other than the supplied HTML, JS, etc., from a webserver on 127.0.0.1 - and, finally, all of this stuff is *as small as possible* while still reproducing the problem.

I strongly recommend you not bother trying to build from source, catch the problem in a debugger, or anything like that until after you have the test case in hand.

**Comment by trotzig** [comment]
I agree, that would be ideal. I'll try to construct a repro case, but I suspect it might take a while. There's a chance the root cause was fixed in a4cb01b2011fe52 (that's the reason I wanted to try building from source, since that commit hasn't been released yet).

**Comment by rzane** [comment]
I also experienced this issue. Disabling source maps solved the problem for me.

**Comment by tristanoneil** [comment]
I've also run into this it seems to do with source map settings, pretty much all of the `devtool` settings outlined [here](http://webpack.github.io/docs/build-performance.html) cause PhantomJS 2.1.1 to crash.

**Comment by tristanoneil** [comment]
The only setting I've found that doesn't cause PhantomJS to crash is `inline-source-map`

**Comment by jedwards1211** [comment]
I experienced this today when I tried adding `babel-polyfill` to my project
