### ISSUE TITLE
Problems with phantomjs 1.9.8 and reactjs

### ISSUE THREAD

**Issue by haridak** [ariya/phantomjs#13747]
Hi,
The application I am trying to automate has reactjs. The test case work fine with phantomjs 2.0 but fail to find link or click link with v 1.9.8. Is phantomjs 1.9.8 not supported with reactjs?

**Comment by zackw** [comment]
I do not know for certain, but it is quite plausible that the version of Webkit bundled with 1.9.8 is too old for reactjs.  In particular I recall something about that version not supporting newer DOM Events APIs.

1.9.x is no longer being developed. We understand that there are several third-party tools and environments that don't work with 2.0 yet and that it is difficult to get a working binary on some platforms; we are actively working on those problems to the extent they are under our control.
