### ISSUE TITLE
Pdf rendering problem

### ISSUE THREAD

**Issue by szdmr** [ariya/phantomjs#13742]
Any font in HTML renders OK when the page is rendered to PNG, however rendering to PDF does not respect font itself, font-size, font spacing etc. When the generated PDF opened for edit in Adobe PDF, it shows an error saying that the font is not available.

Details with images here: http://stackoverflow.com/questions/33840518/phantomjs-font-rendering-problems-when-generating-pdf

**Comment by zackw** [comment]
Please attach one of the problem PDFs.  A complete, self-contained test case (a webpage that produces the problem, plus a PhantomJS script that renders to PDF the way you are doing it) would also be helpful.

**Comment by szdmr** [comment]
my16.pdf, my16.png -> rendered by 1.6
my20.pdf, my20.png -> rendered by 2.0

Here is the content of my rasterize.js 
```
var page = new WebPage();
var system = require("system");

page.paperSize = {
  format: "A4",
  orientation: "portrait",
  margin: {top: "5mm"}
};
page.zoomFactor = 2;

page.open(system.args[1], function (status) {
  page.render(system.args[2]);
  phantom.exit();
});
```
... and this is basically how I generated those images & pdfs. Nothing fancy.
```
phantomjs16.exe rasterize.js my.html my16.pdf
phantomjs16.exe rasterize.js my.html my16.png
phantomjs20.exe rasterize.js my.html my20.pdf
phantomjs20.exe rasterize.js my.html my20.png

```

Open my16.pdf and my20.pdf side by side and you will see the difference. 
The letters are too narrow to each other in the PDF generated by 2.0 and it is easily observable.
The same error is not observed in PNG versions of the conversions.

PDF Generated by 1.6 -> [my16.pdf](https://github.com/ariya/phantomjs/files/43528/my16.pdf)
PNG Generated by 1.6
![my16](https://cloud.githubusercontent.com/assets/231821/11390199/bcfc12d4-9358-11e5-8fe5-5c696459cb45.png)
PDF Generated by 2.0 -> [my20.pdf](https://github.com/ariya/phantomjs/files/43529/my20.pdf)
PNG Generated by 2.0
![my20](https://cloud.githubusercontent.com/assets/231821/11390200/bd042a64-9358-11e5-88a5-11af2617d51a.png)

**Comment by szdmr** [comment]
Anybody interested?

**Comment by szdmr** [comment]
I can't go back to 1.6 because I lose the ability to page-break properly. Can somebody help me with this?

**Comment by szdmr** [comment]
I can't go back to 1.6 because I lose the ability to page-break properly. Can somebody help me with this?

**Comment by gildonei** [comment]
+1 
I am also having this problem with font-size, in Windows everthing works fine, but in Debian even after install fonts or use a Webfont like Roboto the font-size isn't respected. As a workaround I had to downgrade to version 1.9.8, but in this version the table borders are larger than in 2.1.1 at least the font-size and styles are preserved
