### ISSUE TITLE
Don't fail silently

### ISSUE THREAD

**Issue by raingloom** [ariya/phantomjs#13741]
Things like writing `page.eval` instead of `page.evaluate` makes the program "hang" until I press ctrl+c.
It took me several re-reads of my source and comparing it to the examples to realize this mistake, while in any previous framework I used would have complained loudly.

Am I just missing some command line verbosity flag, or is this really how PhantomJS handles errors?

**Comment by zackw** [comment]
Yeah, this is how PhantomJS handles errors. It's *supposed* to at least give you an error message, but the way the code works, we have no good way of telling that the script has crashed.  We'd be glad to take improvements, but we are seriously lacking in manpower to do much of anything ourselves right now, and there are several higher-priority problems.

**Comment by raingloom** [comment]
Thanks, I'll try checking into it, but I'm mostly new to JS and WebKit.
