### ISSUE TITLE
Build fails when containing directory's name is non-ASCII ("qmake: not found")

### ISSUE THREAD

**Issue by GabrielCW** [ariya/phantomjs#13744]
In order to build phatomjs on Ubuntu, I followed the instructions found here: http://phantomjs.org/build.html

After starting `./build.sh`, an error happens quite quickly during the Qt make:

``` sh
Qt is now configured for building. Just run 'make'.
Once everything is built, Qt is installed.
You should not run 'make install'.

Prior to reconfiguration, make sure you remove any leftovers from
the previous build.


Building Qt...

cd src/ && ( test -e Makefile || /home/gabriel/T�l�chargements/phantomjs/src/qt/qtbase/bin/qmake /home/gabriel/Téléchargements/phantomjs/src/qt/qtbase/src/src.pro -o Makefile ) && make -f Makefile 
cd qmake/ && ( test -e Makefile.qmake-docs || /home/gabriel/T�l�chargements/phantomjs/src/qt/qtbase/bin/qmake /home/gabriel/Téléchargements/phantomjs/src/qt/qtbase/qmake/qmake-docs.pro -o Makefile.qmake-docs ) && make -f Makefile.qmake-docs 
/bin/sh: 1: /home/gabriel/T�l�chargements/phantomjs/src/qt/qtbase/bin/qmake: not found
/bin/sh: 1: /home/gabriel/T�l�chargements/phantomjs/src/qt/qtbase/bin/qmake: not found
make: *** [sub-src-make_first] Erreur 127
make: *** Attente des tâches non terminées....
make: *** [sub-qmake-qmake-docs-pro-make_first] Erreur 127
```

I don't really know what to think. I've installed all the requirements, and when I do go to `src/qt/qtbase/bin/` there is an executable `qmake` file.

**Comment by zackw** [comment]
This is going to sound ridiculous, but try doing the build from a directory whose absolute pathname doesn't contain any non-ASCII characters.  I think it's gotten mixed up about the character encoding you're using for your filenames.

**Comment by GabrielCW** [comment]
Indeed, it worked from a directory without non-ASCII characters in the path.

I don't think I should mark the issue as closed, as this is clearly is a bug. It'll be useful to keep it here as a reference in case other people encounter this problem before this is is resolved.

Thank you!

**Comment by zackw** [comment]
Yeah, I agree this is a bug.  Unfortunately, it might be a bug in qmake itself, and if that's the case there is an excellent chance it can't be fixed because too many existing `.pro` files depend on the buggy behavior.

I can do this myself if you don't have time or don't want to futz with git, but it would be interesting to know whether the Python script `build.py`, which has replaced `build.sh` in the very newest development sources, has the same problem.
