### ISSUE TITLE
weird forEach

### ISSUE THREAD

**Issue by ekkis** [ariya/phantomjs#13752]
aprilis:browser ekkis$ phantomjs -v
    1.9.8

    phantomjs> 'a b c d'.split(/ /).forEach(function(x) { console.log(x); });
    a
    b
    c
    d
    undefined

huh (it's not the split)??

    phantomjs> 'a b c d'.split(/ /)
    {
       "0": "a",
       "1": "b",
       "2": "c",
       "3": "d"
    }

**Comment by zackw** [comment]
`forEach` always returns `undefined`, and this is printed as the value of the overall expression.  It's not a bug.

**Comment by ekkis** [comment]
oh... my bad. wtf?

**Comment by zackw** [comment]
no worries, it took me a few minutes to figure out what was going on too.

**Comment by ekkis** [comment]
oh.. I get it.  the forEach isn't logging the undefined to the console.  it's phantomjs showing me the result of the expression.  curiously it breaks my tests.  now I have to figure out why...
