### ISSUE TITLE
npm install phantomjs2 breaks on Windows

### ISSUE THREAD

**Issue by HamletDRC** [ariya/phantomjs#13757]
I cannot install phantomjs2 on my machine using npm install. 

    $ npm install phantomjs2
    npm WARN package.json Sindbad-Apps-Common@0.0.1 No license field.
    npm ERR! Windows_NT 10.0.10240
    npm ERR! argv "C:\\dev\\nodejs\\node.exe" "C:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "phantomjs2"
    npm ERR! node v4.2.0
    npm ERR! npm  v2.14.7
    npm ERR! path C:\Users\hamda\Workspaces\sindbad\apps\common\node_modules\phantomjs2\lib\phantomjs\bin\phantomjs
    npm ERR! code ENOENT
    npm ERR! errno -4058
    npm ERR! syscall chmod
    npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\hamda\Workspaces\sindbad\apps\common\node_modules\phantomjs2\lib\phantomjs\bin\phantomjs'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent
    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\hamda\Workspaces\sindbad\apps\common\npm-debug.log

Full debug log is available here: https://dl.dropboxusercontent.com/u/138156/npmdebug.log

**Comment by Vitallium** [comment]
Hi. Thanks for reporting the issue. But we don't support npm packages (`phantomjs` or `phantomjs2`). Please file your issue in the corresponding repository: https://github.com/zeevl/phantomjs2

Thanks!
