### ISSUE TITLE
Webpage object properties (hooks, settings, etc) should maybe inherit to child windows

### ISSUE THREAD

**Issue by zackw** [ariya/phantomjs#13770]
Currently, any tweaks made to a webpage object by the controller script do not inherit to child windows.  This causes surprising behavior for any page that opens child windows, e.g. the user-agent will be the default, `onResourceRequested` won't see the HTTP requests for the child windows, etc.  To work around this, you have to write some fairly hairy code involving `onPageCreated`, and that isn't effective for everything (e.g. `onPageCreated` is too late to set the user-agent -- which is its own bug, but still).  For examples of the problems this causes, see #13758 and #13659.

We should consider having all such properties automatically inherit to child windows.  This isn't completely straightforward because, for instance, right now many of the event hooks have no way of knowing which page they're called on; we'd have to add one (my preference would be for setting `this` to the page, consistently).  But it shouldn't be hard to _implement_ once it's designed.

**Comment by Vitallium** [comment]
I remember we have a pull request for that.

**Comment by zackw** [comment]
I might look into it later this week, it would simplify my page-scraper a great deal.
