### ISSUE TITLE
click on an element with href="#" in phantomjs

### ISSUE THREAD

**Issue by Rita1985** [ariya/phantomjs#13773]
I'm trying to click on an element with href="#". This is open a new division. This is working fine in firefox.
But when I use phantomjs, it doesnot do anything. The page is not reloaded but the hidden division is not seen.
Tried everything actions, driver.click, javascriptexecutor. Nothing works

**Comment by vignesh02** [comment]
@Rita1985 : Are you using selenium remote driver. if yes, can you please below one
link { driver.findElement(By.linkText("xxxx"))}

**Comment by Rita1985** [comment]
I am using phantomjs driver.

I have created the driver as below:
DesiredCapabilities caps = DesiredCapabilities.phantomjs();
 caps.setCapability("takesScreenshot", true);
 caps.setJavascriptEnabled(true);
 caps.setCapability(CapabilityType.SUPPORTS_FINDING_BY_CSS, true);
 caps.setCapability(PhantomJSDriverService.PHANTOMJS_CLI_ARGS,new String[]{"--ignore-ssl-errors=yes","--ssl-protocol=any","--web-security=false"});
 caps.setCapability("applicationCacheEnabled", true);
 caps.setCapability("acceptSslCerts",true);
 caps.setCapability("handlesAlerts", true);
 caps.setCapability(PhantomJSDriverService.PHANTOMJS_GHOSTDRIVER_CLI_ARGS, new String[] { "--logLevel=2" });
 caps.setCapability(PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY, PhantomJSpath);
 caps.setCapability("phantomjs.page.customHeaders.Accept-Language", "en-GB");
driver = new PhantomJSDriver(caps);


and to click the link I have written the code:
jsx.executeScript("arguments[0].click();", driver.findElement(By.linkText("xxx")));

I have also tried 
 driver.findElement(By.linkText("xxx"))).click();

This is working in firefox driver.

**Comment by peibibing** [comment]
I had same issue, and it's trouble me a few days, so there is my question: had you solved this problem? waiting for your answer.

**Comment by mythilikp** [comment]
did you solve the problem?
