### ISSUE TITLE
Consider giving Vitallium maintainer/releaser priviledges and/or releasing 2.0.0

### ISSUE THREAD

**Issue by mikemcquaid** [ariya/phantomjs#13783]
In Homebrew we're having real problems in that the latest 1.9.x won't compile on the latest OS X (10.11) but there's been no "offiical" 2.0.x release yet. Could @Vitallium make one of his tags a stable release? If not: would you consider making @Vitallium's fork the official upstream?

Thanks for this great project and all the hard work that has gone into it :heart_eyes:

**Comment by mikemcquaid** [comment]
CC @ariya specifically here I guess.

**Comment by pluskid** [comment]
+1

**Comment by ariya** [comment]
Sorry for the slow response. We are definitely cooking something for the next release.
As a reminder, I recommend bringing up such a "meta-development" issue to the dev mailing-list: https://groups.google.com/forum/#!forum/phantomjs-dev. Thank you!

**Comment by mikemcquaid** [comment]
@ariya Do you have any ETA/timescale on that? That may help inform whether we ship @Vitallium's version as-is for now. Thanks!

**Comment by e6nian** [comment]
@mikemcquaid Vitallium's version has a bug with  respons.body is an empty string!
#13774

**Comment by mikemcquaid** [comment]
@e6nian That says it applies to all versions.

**Comment by e6nian** [comment]
@ariya since source code  repo and issues stay in github, may you discuss on github issues instead of google groups.
thoses days tons of issues stay in  this repo, but little commits in the past year. this aswesome project is dying?

**Comment by mlarcher** [comment]
It seems phantomjs 1.9.8 is running very slowly on OSX ElCapitan, and it takes about 90s after the tests before the process exits. Running phantomjs 2 solves the problem, so we are eagerly waiting for an official release of version2.
In the meantime, anybody with the same issue can use https://www.npmjs.com/package/phantomjs2 which seems to work nicely and get things back to normal speed.

**Comment by timlib** [comment]
I have [a project](https://github.com/timlib/webxray) which has phantomjs as a dependency, as brew is no longer working I'll have to revise my documentation for mac.  I am also hoping @Vitallium 's contribution can be made 'official' as my documentation updates will now have to point people away from the official release, which is undesirable for a host of reasons.  

as others have commented, phantomjs is an invaluable project and it seems that the community (eg @Vitallium) is doing an admirable job of maintaining progress even if @ariya may understandably have different priorities at this time.  

again, thanks to all involved in this project, it is meeting a vital need for many in the developer and research communities.

**Comment by mikemcquaid** [comment]
For those following along: it looks like a 2.0.1 release is imminent and will be in Homebrew shortly afterwards: https://groups.google.com/forum/#!topic/phantomjs-dev/vkdGvFpULNo

**Comment by timlib** [comment]
fantastic, I really didn't want to rewrite my documentation.  ;-)

**Comment by mlarcher** [comment]
Glad to see version 2 is closing in.
I need to take a step back from my previous comment though, as even though phantomjs2 does present the speed issue I was refering too less frequently, it is still happening. Not sure it can be fully attributed to phantom per se, actually..

**Comment by timlib** [comment]
still not seeing this working in brew...?

**Comment by mikemcquaid** [comment]
@timlib `brew update`, we just decided to release his 2.0.1.
