### ISSUE TITLE
PhantomJSDriver could not getting Ajax data ...

### ISSUE THREAD

**Issue by ihlayy** [ariya/phantomjs#13788]
I setup a local rails server ,using the code below on index.html
```
<html>
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script>
function test(){
	$.ajax({
                        url:'http://localhost:3000/index',
                        async:false, // if set to true then ok???
                        success:function(data){
                        	$('#ajax_ok')[0].innerHTML="data ok";
                        },error: function (xhr, ajaxOptions, thrownError) {

                        	$('#ajax_ok')[0].innerHTML=xhr.status;
                        }
                    });

}
</script>
<body>
<a id='mybutton' href="javascript:void(0)" onclick="test()") >click me</a>
<p id="ajax_ok">&nbsp;</p>
</body>
</html>
```

I use "PhantomJSDriver" to get url , then find the "mybutton' webElement and trigger "click" method.

If i set async to false, in $.ajax() method , i will get the error result (xhr.status = 0),and if i set async to true , everything is ok? 

why ? How can i solve this problem?

**Comment by krskrs** [comment]
Hi I think this is the same issue as : https://github.com/ariya/phantomjs/issues/11195#issuecomment-164808838

and it's a regression introduced in the 2.0.x branch

I have already reported and confirmed this bug in the other issue linked above.

**Comment by Vitallium** [comment]
Fixed in master.
