### ISSUE TITLE
Screen capture : Can not justify text with GeometricPrecision option

### ISSUE THREAD

**Issue by dranouil** [ariya/phantomjs#13795]
Hello,

I take some screen capture with PhantomJS. I have a problem with the attribute 'text-rendering:GeometricPrecision", my text is not justified if I use it. When I delete the "text-rendering" option, my text is justified.
I'm using PhantomJS 2.0.1-development on Ubuntu 14.04.3 LTS.

Chrome Rendering : 
![source](https://cloud.githubusercontent.com/assets/12966673/11686935/23bccdf2-9e84-11e5-874d-2adb70a1c789.png)

PhantomJS Rendering : 
![result](https://cloud.githubusercontent.com/assets/12966673/11686936/23bf6cba-9e84-11e5-887c-9de47d48ab17.png)

You can easily reproduce the problem with : 

``` html
<html>
<head>  
    <meta charset="UTF-8">
    <style>
        body {
            text-rendering: geometricPrecision;
            width: 320px;
        }

        #paragraph21 {
            font-family: Arial;
            font-size: 16px;
            line-height: 21px;
            text-align: justify;
        }
    </style>
</head>
<body>
    <p id="paragraph21">
        <span>
            Manuel Valls revient sur le terrain des réformes. Il reçoit lundi à Matignon dix organisations syndicales et
            patronales. Trois autres rendez-vous ont lieu mardi. Au menu de ces journées marathon, le déblocage
            des embauches dans les PME, avec des décisions rapides, promet-on au ministère. Il y a urgence.
            Le nombre de chômeurs inscrits à Pôle emploi atteignait en mars 3.509.800, un record. Le chiffre d'avril sera connu
            en fin de journée demain.
        </span>
    </p>
</body>
</html>
```

Am-i doing something wrong ?
Please tell me if you want more informations.

**Comment by dranouil** [comment]
Hello,

Any idea ? :/

**Comment by kaldenficklin** [comment]
Same problem, except neither work to justify the text

**Comment by evandrojr** [comment]
Having the same problem here! In my case I I'm not explicitly using text-rendering: geometricPrecision;

That is quit bad! I guess it will never be fixed...
