### ISSUE TITLE
"Segmentation fault" error when i run phantomjs 1.9.8

### ISSUE THREAD

**Issue by 92hackers** [ariya/phantomjs#13798]
my os is ubuntu 14.10,
i download  phantomjs 1.9.8 from bitbucket,
and when i run it, 
terminal displays  "Segmentatin  fault",

i installed phantom 1.9.0 from apt-get install  in the past, and i apt-get remove it already.

so,  how to solve  this problem, who  can give me a hand ?

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
