### ISSUE TITLE
Compiling phantomjs-1.9.8 on Power8/PPC is not working!

### ISSUE THREAD

**Issue by xiaojuntong** [ariya/phantomjs#13799]
I Compiling The phantomjs-1.9.8 on Power8 For Ambari Hadoop。But The  phantomjs-1.9.8 Need Google breakpad Code。The linux_syscall_support.h Compiling on PPC is not working。can you help me，how to work ?

------------------------------------------------------------------------------------------------------------
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DHAVE_CONFIG_H -DHAVE_FCNTL_H -DHAVE_STDARG_H -DHAVE_STDINT_H -DHAVE_UNISTD_H -DUSE_UTF8 -DSTATIC_BUILD -DQCOMMANDLINE_STATIC -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -Iqt/mkspecs/linux-g++ -I. -Iqt/include/QtCore -Iqt/include/QtNetwork -Iqt/include/QtGui -Iqt/include/QtWebKit -Iqt/include -Igif -Imongoose -Ilinenoise/src -Iqcommandline -Ibreakpad/src -I. -o minidump_writer.o breakpad/src/client/linux/minidump_writer/minidump_writer.cc
breakpad/src/client/linux/minidump_writer/linux_ptrace_dumper.cc:221:2: error: #error "This code hasn't been ported to your platform yet."
 #error "This code hasn't been ported to your platform yet."
  ^
In file included from breakpad/src/client/linux/log/log.cc:35:0:
breakpad/src/third_party/lss/linux_syscall_support.h: In function ‘void* sys_mmap2(void*, size_t, int, int, int, off_t)’:
breakpad/src/third_party/lss/linux_syscall_support.h:2429:18: error: ‘__NR_mmap2’ was not declared in this scope
         __sc_0 = __NR_##name
                  ^
breakpad/src/third_party/lss/linux_syscall_support.h:2432:13: note: in expansion of macro ‘LSS_LOADARGS_0’
             LSS_LOADARGS_0(name);

**Comment by zackw** [comment]
I regret to say that "This code hasn't been ported to your platform yet" means exactly what it says.  PhantomJS 1.9.8 does not support Power8.

PhantomJS 1.x is no longer being developed; new features (including support for new CPU architectures) will appear in the 2.x series *only*.  PhantomJS 2.0 *may* support Power8 already, but I do not know for sure.  Unfortunately, we do not have the manpower to do a port to Power8 ourselves; if 2.x doesn't work for you, you will have to work with our upstreams (Qt and Webkit) to get the port developed.

**Comment by xiaojuntong** [comment]
Thank you !

**Comment by xiaojuntong** [comment]
PhantomJS 2.0 Can support Power8 on RedHat7 But The Apache Hadoop not support PhantomJS 2.0。

**Comment by zackw** [comment]
I'm afraid there's nothing we can do about Hadoop not supporting 2.x.
