### ISSUE TITLE
Mac pre-built binary won't run

### ISSUE THREAD

**Issue by zendude** [ariya/phantomjs#13790]
Running OSX 10.11.1, just downloaded
  -rw-r-----@ 1 ward  staff   14392288 Dec  6 13:01 phantomjs-2.0.0-macosx.zip
and unzipped, yielding
> l bin
total 28496
-rwxr-xr-x@ 1 ward  staff  14588338 Jan 23  2015 phantomjs

However, neither the REPL nor anything else will run:
  > bin/phantomjs
  Killed: 9
  > 

Someone tell me what stupid thing I'm doing?

**Comment by mlb-** [comment]
Reporting the same issue on 10.10.5

**Comment by Vitallium** [comment]
This is a know issue with previous release. You need to install upx and run the following command on phantomjs executable: `upx -d phantomjs`

**Comment by mlb-** [comment]
Rather than closing the issue with no resolution, forcing others to search Google for this particular thread and solution, perhaps update the documentation on http://phantomjs.org/download.html to amend the "Note:" for OS X to include mention of upx?
