### ISSUE TITLE
PhantomJS 2.0 with Web font support for windows

### ISSUE THREAD

**Issue by sbrar** [ariya/phantomjs#13792]
Hi,

I need PhantomJS for windows with web font support enabled. Can someone guide me to the right direction as to how can I enable web fonts in PhantomJS.

Thanks,
Suman

**Comment by Vitallium** [comment]
Current release version doesn't support Web Fonts. If you need them, you have two options:
- compile PhantomJS from source by yourself
- use this binary version - https://github.com/Vitallium/phantomjs/releases/tag/2.0.1

**Comment by IAMtheIAM** [comment]
@Vitallium Hey, I tried your prebuilt binary for webfont enabled phantomjs, and it still doesn't work for me. I'm using [typekit WebFontLoader](https://github.com/typekit/webfontloader) and it gets as far as "Font Loading" but never gets to the "Font Active" callback. Do you have an updated binary that works with `typekit WebFontLoader` on windows?
