### ISSUE TITLE
how to set --proxy-type to 'Https' or 'socks4' ?

### ISSUE THREAD

**Issue by Mehrdad1991h** [ariya/phantomjs#13797]
Hello,
I see this section :

> --proxy-type=[http|socks5|none] specifies the type of the proxy server (default is http).

Ok , you support 'http' , 'socks5' however what about 'https' or 'socks4' ?

**Comment by huazhouji** [comment]
I also want to know it

**Comment by gsouf** [comment]
@ariya ?

**Comment by Vitallium** [comment]
SOCKS4 is not supported. HTTPS should work fine with you specify it as `http`

**Comment by instagramlover** [comment]
@Vitallium you mean by "HTTPS should work fine with you specify it as http"
That we can open https websites , but the problem is , 
some sometimes there is an HTTPS proxy , which we need to tell phantom that the proxy type is HTTPS not HTTP.

That's why we have a problem with pahntomjs

**Comment by cys138138** [comment]
I also want to know it
