### ISSUE TITLE
Build instructions not working

### ISSUE THREAD

**Issue by felicitus** [ariya/phantomjs#13793]
Hi,

I'm following the build instructions on `http://phantomjs.org/build.html` for Linux. My distribution is Debian Jessie.

## Attempt 1 as per manual:
```
git clone --recurse-submodules git://github.com/ariya/phantomjs.git
cd phantomjs
git checkout 2.0.0
```

Result:
```
error: The following untracked working tree files would be overwritten by checkout:
        src/qt/qtbase/.gitignore
        src/qt/qtbase/.qmake.conf
        src/qt/qtbase/.tag
        src/qt/qtbase/INSTALL
        src/qt/qtbase/LGPL_EXCEPTION.txt
        src/qt/qtbase/LICENSE.FDL
        src/qt/qtbase/LICENSE.PREVIEW.COMMERCIAL
        [etc]
```

## Attempt 2 without `--recurse-submodules`:

```
git clone git://github.com/ariya/phantomjs.git
cd phantomjs
git checkout 2.0.0
./build.sh --jobs 1
```

Result:

```
g++ -c -include .pch/Qt5Network -pipe -O2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -fno-exceptions -Wall -W -D_REENTRANT -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -DQT_NO_USING_NAMESPACE -DQT_BUILD_NETWORK_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I../../mkspecs/linux-g++ -I. -I../../include -I../../include/QtNetwork -I../../include/QtNetwork/5.3.0 -I../../include/QtNetwork/5.3.0/QtNetwork -Ikernel -I../../include/QtCore/5.3.0 -I../../include/QtCore/5.3.0/QtCore -I../../include/QtCore -I.moc -o .obj/qftp.o access/qftp.cpp
g++ -c -include .pch/Qt5Network -pipe -O2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -fno-exceptions -Wall -W -D_REENTRANT -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -DQT_NO_USING_NAMESPACE -DQT_BUILD_NETWORK_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I../../mkspecs/linux-g++ -I. -I../../include -I../../include/QtNetwork -I../../include/QtNetwork/5.3.0 -I../../include/QtNetwork/5.3.0/QtNetwork -Ikernel -I../../include/QtCore/5.3.0 -I../../include/QtCore/5.3.0/QtCore -I../../include/QtCore -I.moc -o .obj/qsslsocket_openssl_symbols.o ssl/qsslsocket_openssl_symbols.cpp
In file included from ssl/qsslsocket_openssl_symbols.cpp:58:0:
ssl/qsslsocket_openssl_symbols.cpp: In function ‘const SSL_METHOD* q_SSLv3_client_method()’:
ssl/qsslsocket_openssl_symbols_p.h:185:39: error: ‘SSLv3_client_method’ was not declared in this scope
     ret q_##func(arg) { funcret func(a); }
                                       ^
ssl/qsslsocket_openssl_symbols.cpp:269:1: note: in expansion of macro ‘DEFINEFUNC’
 DEFINEFUNC(const SSL_METHOD *, SSLv3_client_method, DUMMYARG, DUMMYARG, return 0, return)
 ^
ssl/qsslsocket_openssl_symbols.cpp: In function ‘const SSL_METHOD* q_SSLv3_server_method()’:
ssl/qsslsocket_openssl_symbols_p.h:185:39: error: ‘SSLv3_server_method’ was not declared in this scope
     ret q_##func(arg) { funcret func(a); }
                                       ^
ssl/qsslsocket_openssl_symbols.cpp:279:1: note: in expansion of macro ‘DEFINEFUNC’
 DEFINEFUNC(const SSL_METHOD *, SSLv3_server_method, DUMMYARG, DUMMYARG, return 0, return)
 ^
ssl/qsslsocket_openssl_symbols.cpp: At global scope:
ssl/qsslsocket_openssl_symbols.cpp:119:6: warning: ‘void {anonymous}::qsslSocketUnresolvedSymbolWarning(const char*)’ defined but not used [-Wunused-function]
 void qsslSocketUnresolvedSymbolWarning(const char *functionName)
      ^
ssl/qsslsocket_openssl_symbols.cpp:124:6: warning: ‘void {anonymous}::qsslSocketCannotResolveSymbolWarning(const char*)’ defined but not used [-Wunused-function]
 void qsslSocketCannotResolveSymbolWarning(const char *functionName)
      ^
Makefile:21031: recipe for target '.obj/qsslsocket_openssl_symbols.o' failed
make[2]: *** [.obj/qsslsocket_openssl_symbols.o] Error 1
make[2]: Leaving directory '/home/felicitus/repos/phantomjs/src/qt/qtbase/src/network'
Makefile:180: recipe for target 'sub-network-make_first' failed
make[1]: *** [sub-network-make_first] Error 2
make[1]: Leaving directory '/home/felicitus/repos/phantomjs/src/qt/qtbase/src'
Makefile:39: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2
```

Either the build instructions are outdated, or my build setup has a problem.

**Comment by Toushin** [comment]
I am also running into problems building phantomjs, in my case on debian wheezy. 2 hours into the build I got this error:

```
...-o .obj/inspector/InspectorAllInOne.o inspector/InspectorAllInOne.cpp
{standard input}: Assembler messages:
{standard input}:115447: Warning: end of file not at end of a line; newline inserted
{standard input}: Error: .size expression for _ZThn40_N7WebCore22InspectorTimelineAgent4stopEPN3WTF6StringE does not evaluate to a constant
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
make[2]: *** [.obj/inspector/InspectorAllInOne.o] Error 4
make[2]: Leaving directory `/root/phantomjs/src/qt/qtwebkit/Source/WebCore'
make[1]: *** [sub-Target-pri-make_first-ordered] Error 2
make[1]: Leaving directory `/root/phantomjs/src/qt/qtwebkit/Source/WebCore'
make: *** [sub-Source-WebCore-WebCore-pro-make_first-ordered] Error 2

ERROR: Failed to build PhantomJS! Building Qt WebKit failed.
```
Before this try I was also trying on Jessie, but having had absolutely no luck there I thought I'd try Wheezy...

**Comment by latortuga** [comment]
I was having this exact issue just the other day. The manual seems to have been updated to not include the `git checkout` command.

**Comment by Toushin** [comment]
to be clear, I didn't check out 2.0.0 because after several tries I tried doing different things, but building from master didn't work either :/

**Comment by Vitallium** [comment]
`git checkout` is needed if you want to build the release version. But if you're compiling PhantomJS from sources, I assume you want the latest available version, that's why you have to compile it against the `master` branch.


If you need help with building PhantomJS from sources, please don't forget to post your build environment (OS, compiler versions, etc.)

**Comment by felicitus** [comment]
@Vitallium no, I don't want the development version. I want the latest release version. There are no Linux binaries and the [Download](http://phantomjs.org/download.html) page says: `In the mean time, it is recommended that you build the Linux version from source.`

**Comment by shaojwa** [comment]
build always failed.
this time it told me that: can not found gperf
failed on  build for serval weeks
shit

**Comment by Vitallium** [comment]
@shaojwa you can find all needed binaries in the 3rd party folder: `src/qt/3rdparty/gnuwin32` Just add it to your `PATH` variable.

**Comment by latortuga** [comment]
Note for others on Linux in this thread, I also thought that I had to build from source but I found a stackoverflow thread that suggested just installing from npm. I ended up using `sudo npm install phantomjs` and then symlinking the resulting installation to a location on my $PATH. Works great!

**Comment by erik-landvall** [comment]
My docker build that works:

    FROM ubuntu:14.04

    ENV DEBIAN_FRONTEND noninteractive

    RUN apt-get -y update \
      && apt-get -y install \
          build-essential g++ flex bison gperf ruby perl libsqlite3-dev \
          libfontconfig1-dev libicu-dev libfreetype6 libssl-dev libpng-dev \
          libjpeg-dev python libx11-dev libxext-dev git

    RUN git clone git://github.com/ariya/phantomjs.git /tmp/phantomjs \
      && cd /tmp/phantomjs \
      && git checkout 2.0 \
      && ./build.sh --jobs 1 --confirm \
      && mv bin/phantomjs /usr/local/bin \
      && rm -rf /tmp/phantomjs

    RUN apt-get autoremove -y && apt-get clean all

**Comment by felicitus** [comment]
The build instructions are updated and it seems that the problem was fixed in the repo for 2.0 as well, so it's working for me.

**Comment by gauravsitlani** [comment]
@latortuga can you share the steps after installing phantomjs from npm, I'm using Fedora

**Comment by 2000liux** [comment]
> My docker build that works:
> 
> ```
> FROM ubuntu:14.04
> 
> ENV DEBIAN_FRONTEND noninteractive
> 
> RUN apt-get -y update \
>   && apt-get -y install \
>       build-essential g++ flex bison gperf ruby perl libsqlite3-dev \
>       libfontconfig1-dev libicu-dev libfreetype6 libssl-dev libpng-dev \
>       libjpeg-dev python libx11-dev libxext-dev git
> 
> RUN git clone git://github.com/ariya/phantomjs.git /tmp/phantomjs \
>   && cd /tmp/phantomjs \
>   && git checkout 2.0 \
>   && ./build.sh --jobs 1 --confirm \
>   && mv bin/phantomjs /usr/local/bin \
>   && rm -rf /tmp/phantomjs
> 
> RUN apt-get autoremove -y && apt-get clean all
> ```
Give it a try
