### ISSUE TITLE
Memory leakage?

### ISSUE THREAD

**Issue by superhero** [ariya/phantomjs#13805]
**The code:** https://gist.github.com/superhero/16c81ebdb6a07caaf536
Using PhantomJS 2.0 on Ubuntu 14.04.

After each request I see an ascending memory usage for the service running in a docker container. After 10 000 requests to the server, I'm at 43% of 8GB memory.

I tried using `clearMemoryCache` right before I close the page, no difference..

Am I missing something simple here? or is it as I suspect, a memory leakage issue?
#### Possible solution?

I looked at: https://github.com/ariya/phantomjs/issues/10357
...where I noticed this possibility: **PrivateBrowsingEnabled** -> http://doc.qt.io/qt-4.8/qwebsettings.html#WebAttribute-enum I like to make a request for this future if possible.

**Comment by Vitallium** [comment]
Lets track this in https://github.com/ariya/phantomjs/issues/11390
