### ISSUE TITLE
PhantosJS with Tor  - dns timeout error

### ISSUE THREAD

**Issue by Dexus77** [ariya/phantomjs#13807]
I am using the РhantomJS with Tor (Python 3.5, selenium). All latest version. 
The page contains a resource that is not DNS resolves
if using PhantomJs direct connect all ok and debug show ("errorCode":3,"errorString":"Host  not found")
if use with Tor. PhantomJs wait and page not load. Crach with error (Error: 'timeout').

For a proxy server, you need to interrupt the download of resources that do not resolve DNS resource as a direct connection.

Fix this please.

**Comment by zackw** [comment]
I think I understand the gist of your problem, but could you please specify _exactly_ how you are starting up Tor and PhantomJS?  (In particular, Tor is picky about which variant of the SOCKS protocol you use with it.)  A concrete test case would also be helpful.

**Comment by Dexus77** [comment]
Я использую socks5. Если необходимо могу подготовить тест.

**Comment by zackw** [comment]
socks5 is the right thing to use.  I will look into this, but I cannot promise to do it soon.  A test would still be helpful.

socks5 это правильно использовать. Я буду смотреть в это, но я не могу обещать сделать это в ближайшее время. Тест будет по-прежнему быть полезным.

**Comment by Dexus77** [comment]
[dns_resolve_bug.txt](https://github.com/ariya/phantomjs/files/61389/dns_resolve_bug.txt)
Link contains 301 redirect.
This bug for me is not very critical, I would be grateful if you can do it whenever possible.

**Comment by zackw** [comment]
Thank you for the script.  We need one more thing, though.  When I load the URL in your script, there is a 301 redirect but there are no failed DNS lookups.  We need you to build a self-contained tiny website that we could point your script at and see the problem.  You do not have to host this website yourself; we just need you to give us all the files *we* would need to host that website.  Just this might be enough:

    <html><body><img src="http://nonexistent.invalid/foo.png"></body></html>

... but I don't know that.  If you write the website then you can make sure it demonstrates the exact same problem you are having.

**Comment by Dexus77** [comment]
I am not writing a site just experimented with PhantomJS and Tor. Several times encountered this error on different sites, and therefore decided to tell you. All of the sites I am not to debug, but encountered this error when the code 301 and 401. Unfortunately my English is very bad, and I did not understand what I need to do? Web server configured I not have.

**Comment by Dexus77** [comment]
Run please my example without logging Tor. In the debug log, you see an error, which normally handles PhantomJS without Tor. 

[DEBUG - 2015-12-12T18:57:41.145Z] Session [37e21c80-a102-11e5-8d44-4714a9904430] - page.onResourceError - {"errorCode":3,"errorString":"Host  not found","id":17,"status":null,"statusText":null,"url":"http://:0/"}

[DEBUG - 2015-12-12T18:57:41.145Z] Session [37e21c80-a102-11e5-8d44-4714a9904430] - page.onResourceReceived - {"contentType":null,"headers":[],"id":17,"redirectURL":null,"stage":"end","status":null,"statusText":null,"time":"2015-12-12T18:57:41.145Z","url":"http://:0/"}

Sorry unclear to what resource the error relates.

In the case of a Tor of this error in the logs there no.
[DEBUG - 2015-12-13T10:42:53.150Z] Session [37bc8720-a186-11e5-a868-f153513d5d56] - _execFuncAndWaitForLoadDecorator - Page Loading in Session: true

Wait and timeout exception.
and no normal load page 
[DEBUG - 2015-12-12T18:57:41.253Z] Session [37e21c80-a102-11e5-8d44-4714a9904430] - _oneShotCallback - onLoadFinished

**Comment by zackw** [comment]
Thanks.  I will get back to you if I can't figure it out.  Do not expect to hear anything more about this until mid-January 2016 at the earliest.

**Comment by Dexus77** [comment]
Thank you.
