### ISSUE TITLE
PhantomJS crashes when loading jQuery onto Calvin Klein product page

### ISSUE THREAD

**Issue by vadimg** [ariya/phantomjs#13800]
I am using the downloaded binary of version 2.0.0 on OS X 10.9. Here's a small script to reproduce the crash:

```
var page = require('webpage').create();

var address = 'http://www.calvinklein.com/shop/en/ck/mens-clothing/mens-shirts/22020985-423';

// uncomment the line below if you want it to not crash
// var address = 'https://www.everlane.com/collections/mens-all/products/mens-double-knit-crew-black-dark-grey';

page.open(address, function(status) {
  console.log('status', status);
  console.log('BEFORE INCLUDE JQUERY');
  page.includeJs('https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js', function() {
    console.log('AFTER INCLUDE JQUERY');
    phantom.exit();
  });
});
```

For some reason, it only crashes on Calvin Klein pages. Most other sites I've tested work fine.

In case you want the crash dump too, here it is (I didn't convert it to a stacktrace because it's hard to do on OS X and there's a easy way to reproduce): 
[CA7392BA-293E-457D-893E-D0FFB3D67A7A.dmp.zip](https://github.com/ariya/phantomjs/files/58768/CA7392BA-293E-457D-893E-D0FFB3D67A7A.dmp.zip)

**Comment by zackw** [comment]
1) This is almost certainly a bug in WebKit. Please try to reproduce the
problem using a WebKit nightly build (see webkit.org). If you find that
WebKit nightlies have the same problem, please report it directly to the
WebKit developers.

2) Calvin Klein could change their website at any time and make the problem
disappear. Please try to cut their site down to the smallest possible
self-contained page that still shows the crash.

**Comment by vadimg** [comment]
I will try to reproduce this using the webkit nightlies. In the meantime, here is the current state of CalvinKlein's website: 
[bug.zip](https://github.com/ariya/phantomjs/files/58832/bug.zip)
You can serve this by running `python -m SimpleHTTPServer`

**Comment by ariya** [comment]
Can you try it again with PhantomJS 2.1?

**Comment by vadimg** [comment]
PhantomJS 2.1 still segfaults on my test script.

**Comment by tangphillip** [comment]
I don't have a desymbolication file, but here's the stack trace I get—Phantom seems to crash deep within a recursive method.

https://gist.github.com/tangphillip/81b7a9023b311411963d

**Comment by porkopek** [comment]
I have the same problem with Windows binaries 2.1.1 trying to inject jquery in github https://github.com/.

My code:

var page = require('webpage').create();
var system = require('system');
var args = system.args;
page.open('https://github.com/', function () {
    page.includeJs("http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js", function () {
             console.log('hi');
        phantom.exit();
    });
});
