### ISSUE TITLE
PhantomJS2 build dependent on libicu-devel 

### ISSUE THREAD

**Issue by Eudaephoric** [ariya/phantomjs#13808]
Copying my built PhantomJS2 executable to another machine errors on start with the following:

phantom stderr: /data/prerender/node_modules/phantomjs/lib/phantom/bin/phantomjs: error while loading shared libraries: libicudata.so.42: cannot open shared object file: No such file or directory

**Comment by Vitallium** [comment]
Linux builds are broken right now. You can solve it by installing libicu on your target machine.
Please see this issue #12948
