### ISSUE TITLE
Ability to specify disk cache location

### ISSUE THREAD

**Issue by mepard** [ariya/phantomjs#13816]
When running several instances of PhantomJS, I've occasionally seen crashes that I suspect are due to cache corruption. #13410 sounds similar.

I've created a feature branch with the ability to specify the location of the disk cache so each instance can have its own. A pull request will be forthcoming.

(This is my first PR, so let me know if I'm doing anything wrong.)

**Comment by Vitallium** [comment]
Landed in https://github.com/ariya/phantomjs/commit/c9e30ebafdeb42efe33900da7823142e146b0a1d
