### ISSUE TITLE
vs2013 windows compiled phantomjs 2.0 error: ;The specified executable is not a valid Win32 application

### ISSUE THREAD

**Issue by wangzhenxing** [ariya/phantomjs#13815]
in win7 64bit and vs2013 environment , building phantomjs 2.0 with new 2.0 source codes.

but in some windows systems , error : The specified executable is not a valid Win32 application happens.

Is there anyone can help me?

**Comment by Vitallium** [comment]
On what kind of environments are you trying to run?

**Comment by wangzhenxing** [comment]
window xp(32bit)

**Comment by Vitallium** [comment]
Unfortunately, we dropped support for Windows XP in 2.0. If you really need it, you have to compile PhantomJS and all its dependencies by yourself - http://doc.qt.io/qt-5/windows-issues.html
