### ISSUE TITLE
Release a tag with correct phantomjs.spec 

### ISSUE THREAD

**Issue by selurvedu** [ariya/phantomjs#13811]
Currently tag 2.0.0 includes an outdated `phantojs.spec`. The updated version was committed to `master` 7 months ago... Can you release (e.g.) 2.0.1, or reassign a tag to another commit, or just release a usual 2.0.0 tarball with correct spec file?

**Comment by zackw** [comment]
2.1 is coming Real Soon Now.

**Comment by selurvedu** [comment]
Glad to hear that. :)
