### ISSUE TITLE
page.renderBase64 and page.renderBuffer should support pdf output

### ISSUE THREAD

**Issue by dhendo** [ariya/phantomjs#13823]
From discussions in https://github.com/ariya/phantomjs/pull/13345 both page.renderBuffer and page.renderBase64 only currently support image formats. They should be refactored to additionally use the pdf codepath from page.render

**Comment by level420** [comment]
It would be great to have the possibility to stream rendered PDF without the need of creating temporary files, when using phantomjs in "server" mode.

**Comment by jozsi** [comment]
+1

**Comment by kachkaev** [comment]
Any plans on this guys? I'd like to try out [sindresorhus/pageres](https://github.com/sindresorhus/pageres), but lack of PDF support suggests using something else. Getting vector outputs is pretty crucial in many cases!

**Comment by atljoseph** [comment]
absolutely no one working on phantom has responded to this.  at least make a response.  Hello?????? People want pdfs, not just images.  We can build workarounds, but a reponse to a question would be desirable.
