### ISSUE TITLE
captureContent should maybe work on content-types instead of urls?

### ISSUE THREAD

**Issue by erikdubbelboer** [ariya/phantomjs#13835]
A lot of times when you use phantomjs to load/render a page you have no idea what kind of URLs it loads. This makes it hard to block loading of video or large binary files while capturing other interesting bodies. In slimerjs captureContent works on the Content-Type instead of the url. Using this it's much easier to ignore videos and capture all javascript content for example.

I have already written a patch that we are using internally. Would there be interest if I created a pull request for this?

I know it would break backwards compatibility with the current implementation of captureContent. Maybe we could add it as a new property called captureContentTypes if this is an issue?

**Comment by erikdubbelboer** [comment]
The only discussion I see on content-type versus url is https://github.com/ariya/phantomjs/pull/11484#discussion_r19300381 . I think URL was chose because it was easier to implement?

**Comment by zackw** [comment]
I like this idea in principle...

**Comment by erikdubbelboer** [comment]
Changing the old property or adding the new `captureContentTypes` property?

**Comment by erikdubbelboer** [comment]
We have been using this change for more than 2 years already: https://github.com/atomx/phantomjs/commit/d0ac77b5010d368cf26f48df055866b790046427
