### ISSUE TITLE
[bug] Parsing error when requiring a file whose last line has a // comment

### ISSUE THREAD

**Issue by laggingreflex** [ariya/phantomjs#13836]
I'm facing a weird bug on Windows with Phantom 2.0

If you have two files:

**a.js**

    require('./b.js');

**b.js**

    console.log('b') // a comment

Running this results in the error

    > phantomjs a.js
    SyntaxError: Expected token '}'

      :1 in loadModule
      phantomjs://bootstrap.js:282 in _compile
      phantomjs://bootstrap.js:126 in .js
      phantomjs://bootstrap.js:278 in _load
      phantomjs://bootstrap.js:311 in require
      phantomjs://bootstrap.js:263 in require

The file **b.js** has to be `require()`-ed. And though in this example it only has one line, it could have more preceding it, but the important thing is that it's the last line and it contains a comment.

Removing the comment, or adding an empty last line resolves the issue.

Tested on Windows 10 with Phantom 2.0

**Comment by zackw** [comment]
This is bug #12868.  It will be fixed in the next release.
