### ISSUE TITLE
Add information who or what initiated the network request (if any) to onResourceRequested

### ISSUE THREAD

**Issue by vitallium** [ariya/phantomjs#13831]
Sometimes you need to know who or what initiated the network request.
It will be useful if we add this kind of information to our `onResourceRequested` callback.

**Comment by Vitallium** [comment]
To implement this feature we need to assign a metadata to the QNetworkReply instance inside the WebCore.

**Comment by RReverser** [comment]
@Vitallium Just to show what I meant in relevant tweet - groups like in [type options](https://adblockplus.org/en/filters#options) would be great.

**Comment by Vitallium** [comment]
@RReverser yes, like in DevTools.

**Comment by RReverser** [comment]
@Vitallium Pretty much, yeah (although never checked whether they show the real initiator of just type of content - e.g. will `<script src="image.png"></script>` be shown as script or as image).

**Comment by ariya** [comment]
@Vitallium Is there already an upstream Qt bug (https://bugreports.qt.io/browse/QTBUG) filed for this?

**Comment by Vitallium** [comment]
@ariya No. And I doubt if it will be there since they stopped developing QtWebkit.

**Comment by futurist** [comment]
What's the status/plan for this feature now? we need this feature in a project now. :smile:

**Comment by Vitallium** [comment]
@futurist the plan is to implement it. But status is just TODO.

**Comment by wisec** [comment]
Hello @Vitallium ,
I would be really glad to have this feature implemented, how can I help/be involved on this? 
Thanks

**Comment by wisec** [comment]
@Vitallium I would really like to help but I dont' know the call flow from OnResourceRequested and the WebKit method that gives the "type" info. 
Would you be so kind to help me by giving me some direction so that I can start digging? 
Maybe someone like @annulen can help giving some flow information on this? 
Just as a head start - if possible.
Thanks a lot

**Comment by Vitallium** [comment]
@wisec I doubt that we can implement that in the current state.

**Comment by wisec** [comment]
Can you elaborate why? 
I am obviously considering this on PhantomJS +2.5

**Comment by Vitallium** [comment]
@wisec this kind of information is available inside WebCore, not QtWebKit layer. To pull this info you have to implement it (forward it) to QtWebKit layer.

**Comment by wisec** [comment]
@Vitallium I see... so I'm on my own :D I'll see what I can do then.
Thanks for your explaination

**Comment by annulen** [comment]
I guess this issue describes the same feature: https://github.com/annulen/webkit/issues/108

**Comment by wisec** [comment]
@annulen I guess so, thanks for pointing that out.

**Comment by jianghaizhi** [comment]
Is there any progress for this improvement?
