### ISSUE TITLE
config.json: proxyType has no effect

### ISSUE THREAD

**Issue by mitsukuri** [ariya/phantomjs#13839]
**PhantomJS 2.0**

Trying to include proxy type option in config.json, e.g.
```{
	"proxy": "localhost:1234",
	"proxyType": "socks5"
}```
this won't work (`phantomjs --config=config.json test.js`),
but `phantomjs --proxy=localhost:1234 --proxy-type=socks5 test.js` works OK.

**Comment by zackw** [comment]
The keys you use in config.json are the same as the command line options, not camelcased versions of them.  This should work:

    { "proxy": "localhost:1234", "proxy-type": "socks5" }

**Comment by mitsukuri** [comment]
Sorry, no, `proxy-type` doesn't work either. Using command line arguments I can load a page via Tor, and using a config file I can't.

**Comment by zackw** [comment]
Yeah let's continue this in #13840.
