### ISSUE TITLE
PhantomJS has crashed

### ISSUE THREAD

**Issue by Alexander198961** [ariya/phantomjs#13842]
There is output:
casperjs --web-security=no  test casper_login_yahoo.js
Test file: casper_login_yahoo.js                                                
# Login with Yahoo
HELLOOPOPUP
11111111111
ERRRRRRRRRRRRTypeError: 'undefined' is not a function (evaluating 'x.bind(null,"Yahoo")')
222222222222
best
PASS Find an element matching: xpath selector: //*[@class='yahoo']/span
wesy
weqwwsy
FAIL <id?> did not pop up in 5000ms
#    type: uncaughtError
#    file: casper_login_yahoo.js
#    error: <id?> did not pop up in 5000ms

#    stack: not provided
FAIL 2 tests executed in 10.303s, 1 passed, 1 failed, 0 dubious, 0 skipped.     

Details for the 1 failed test:

In casper_login_yahoo.js
  Login with Yahoo
    uncaughtError: <id?> did not pop up in 5000ms
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/4acbd514-cfd9-6639-72fe90f7-4d0c1c6b.dmp
[4acbd514-cfd9-6639-72fe90f7-4d0c1c6b.dmp.txt](https://github.com/ariya/phantomjs/files/74890/4acbd514-cfd9-6639-72fe90f7-4d0c1c6b.dmp.txt)

Segmentation fault (core dumped)

**Comment by Alexander198961** [comment]
casper.test.begin('Login with Yahoo' , 3 , function(test) {



var myUrl="app.qa.slicetest.com"
//var myUrl="staging.slice.com"
var myEmail="pinboxtest16@yahoo.com"
var myPasswd="alex1234"
var mouse = require("mouse").create(casper);
x=require('casper').selectXPath;









casper.on('error', function () { 
 this.echo("HEllo alert")
});
casper.on('remote.alert', function () { 
 this.echo("HEllo alert")
});
casper.on('page.created', function () { 
 this.echo("HELLOOPOPUP")
});
casper.on('page.initialized', function () { 
 this.echo("11111111111")
});


casper.on('page.resource.received', function () { 
 this.echo("222222222222")
});



casper.on('popup.loaded', function () { 
 this.echo("444444444444444")
});

casper.on('page.error', function (msg, trace) { 
 this.echo("ERRRRRRRRRRRR"+ msg)
});
casper.start("https://"+myUrl + "/logmein" , function() {
this.wait(1000, function() {



this.echo('best')
test.assertExists(x("//*[@class='yahoo']/span"));

this.echo('wesy')
/*
this.evaluate(function(){
   // addPeriode();
   var el = document.querySelector('.yahoo');
   el.click();
});
*/
this.click("html.notOauth body div.main div#logmein div.openid span.yahoo span.logo");


this.capture("mytest.png");

this.echo('weqwwsy')

});

  

 this.wait(2000, function () {

this.capture("mytest12.png");

  }) 
 
});
})

casper.waitForPopup('<id?>', function(popup) {
    this.echo(popup.url + ' is loaded and is the current active page');
    popup.close();
});

//casper.waitForPopup(/popup\.html$/, function() {
  //  this.echo("fdfdfsdf");
   // this.test.assertEquals(this.popups.length, 1);
//});
//casper.thenOpen("https://app.qa.slicetest.com" + "/signup" , function() {
//})
 casper.run(function() {
    });

**Comment by Vanuan** [comment]
Please specify which binary is that:
https://bitbucket.org/ariya/phantomjs/downloads

**Comment by Alexander198961** [comment]
it was 1.9.8 but I will try to reproduce again under linux

**Comment by ariya** [comment]
Can you try it again with PhantomJS 2.1?

**Comment by Alexander198961** [comment]
ok will  try to update my linux version

**Comment by Alexander198961** [comment]
ok will  try to update my linux version

**Comment by Alexander198961** [comment]
it seems worked fine  not crashed with 2.1
