### ISSUE TITLE
Typo in instructions for Path

### ISSUE THREAD

**Issue by DavidMoritz** [ariya/phantomjs#13844]
The instructions indicate that when you put the contents of the zip folder into `C:\bin\phantomjs` that you should then add `C:\bin\phantomjs` to the environment variables. However, the newest version (2.0.0) has "phantomjs.exe" inside of "bin" which means the PATH needs to also be changed to be "C:\bin\phantomjs\bin".

**Comment by ariya** [comment]
Please be specific: which instructions? This one seems to be correct: http://phantomjs.org/download.html.

**Comment by ariya** [comment]
Due to the lack of a concrete follow-up possibility, this issue will be closed.
