### ISSUE TITLE
Build 32-bit Linux static binary in a 64-bit system

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#13849]
Docker facilitates a self-contained system to build PhantomJS static binary (#13822). This works well on a 64-bit system. With some tweaks, it is still possible to pull a 32-bit Docker image and produce 32-bit static binary. However, it is preferred to keep using the same official 64-bit Ubuntu 14.04 image to produce 32-bit binary.

**Comment by ariya** [comment]
Some tricks from https://developer.mozilla.org/en-US/docs/Compiling_32-bit_Firefox_on_a_Linux_64-bit_OS:

**Method 1**: Cross-compile using 64-bit compiler and libraries. This requires packages such as `gcc-multilib` (and a few others), as well as `-m32` in the `CFLAGS`.

**Method 2**: Create a 32-bit environment using chroot.

**Comment by Vanuan** [comment]
Would be great to support symbols as well: http://phantomjs.org/crash-reporting.html

**Comment by ariya** [comment]
Obsoleted for now, since we want to use system-installed Qt and QtWebKit (see e.g. #15341).
