### ISSUE TITLE
config.json "proxy-type" : "socks5" doesn't change proxy type

### ISSUE THREAD

**Issue by mitsukuri** [ariya/phantomjs#13840]
PhantomJS 2.0, Windows 7 x64

I'm testing a script that loads a page over TOR and console.logs its content.

Here's my config.json:
`{"proxy": "localhost:9050", "proxy-type": "socks5"}`

If I run `phantomjs --config=config.json test.js`, I'm getting `Tor is not an HTTP Proxy`,

but if I run `phantomjs --proxy=localhost:9050 --proxy-type=socks5 test.js` I'm getting page source as expected, so I guess that the relevant option in config.json doesn't affect the proxy type.

I've been told that it should indeed be "proxy-type" and not "proxyType" as I first assumed (see [issue #13839](https://github.com/ariya/phantomjs/issues/13839))

**Comment by zackw** [comment]
Thanks for the bug report.  I agree this is a bug, and we don't need anything more from you before we can investigate, but, FYI, we are very short on developer manpower right now and can't promise a fix soon.  If you feel up to digging into it and sending us a pull request, that may well get things done faster.

**Comment by mitsukuri** [comment]
Ok, thank you! I will consider that.
