### ISSUE TITLE
Repeating crash in OSX El Capitan

### ISSUE THREAD

**Issue by ernestm** [ariya/phantomjs#13841]
Running robot framework + extendedselenium2library with phantomjs on a test suite. It runs one test suite fine then crashes at the same place in the middle of the second every time (not doing anything weird, the test is just logging into a Web page a couple times with good and bad credentials). Crash dump and ghostdriver.log file enclosed. It used to work a couple weeks ago.  I am on El Capitan and so can't brew install phantomjs, instead I did brew install npm; npm install phantom phantomjs -g which gets 1.9.8.   Robot framework 2.9.2 (Python 2.7.10) if it's relevant. selenium 2.48.

[phantomcrash.zip](https://github.com/ariya/phantomjs/files/74343/phantomcrash.zip)

**Comment by Vanuan** [comment]
```
Crash reason:  EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
Crash address: 0xffffffffffffffc8

Thread 0 (crashed)
 0  0xa3980cd
    eip = 0x0a3980cd   esp = 0xbfffd810   ebp = 0xbfffd858   ebx = 0x0e58c300
    esi = 0x00000200   edi = 0x0e66b048   eax = 0x11688678   ecx = 0x00000000
    edx = 0xfffffffb   efl = 0x00210202
    Found by: given as instruction pointer in context
 1  phantomjs!__ZN3JSC11Interpreter11executeCallEPNS_9ExecStateEPNS_8JSObjectENS_8CallTypeERKNS_8CallDataENS_7JSValueERKNS_7ArgListE + 0x534
    eip = 0x000d90c6   esp = 0xbfffd860   ebp = 0xbfffd8e8
    Found by: previous frame's frame pointer
 2  phantomjs!__ZN3JSC4callEPNS_9ExecStateENS_7JSValueENS_8CallTypeERKNS_8CallDataES2_RKNS_7ArgListE + 0x49
    eip = 0x00150e79   esp = 0xbfffd8f0   ebp = 0xbfffd918
    Found by: previous frame's frame pointer
 3  phantomjs!__ZN3JSC8Bindings18QtConnectionObject7executeEPPv + 0x7be
    eip = 0x00225152   esp = 0xbfffd920   ebp = 0xbfffdaa8
    Found by: previous frame's frame pointer
 4  phantomjs!__ZN3JSC8Bindings18QtConnectionObject11qt_metacallEN11QMetaObject4CallEiPPv + 0x46
    eip = 0x00222138   esp = 0xbfffdab0   ebp = 0xbfffdad8
    Found by: previous frame's frame pointer
 5  phantomjs!__ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 0x639
    eip = 0x011ec1ef   esp = 0xbfffdae0   ebp = 0xbfffdb88
    Found by: previous frame's frame pointer
 6  phantomjs!__ZN7WebPage12loadFinishedERK7QString + 0x3d
    eip = 0x0005e4df   esp = 0xbfffdb90   ebp = 0xbfffdba8
    Found by: previous frame's frame pointer
```

**Comment by Vanuan** [comment]
I.e.:

    JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)

**Comment by Vanuan** [comment]
Looks similar to #12523

**Comment by ariya** [comment]
Can you try it again with PhantomJS 2.1?

**Comment by ernestm** [comment]
It works now with 2.1!  Thanks!  (And I can even brew install phantomjs now as a bonus...)

**Comment by ernestm** [comment]
Ah whoops, spoke too soon.

**Comment by ernestm** [comment]
Actually, I'm having some other problem now but this one appears to be fixed, thanks!
