### ISSUE TITLE
PhantomJS has crashed

### ISSUE THREAD

**Issue by vietthventura** [ariya/phantomjs#13845]
Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/38a8fe9d-33cf-ab72-578a8340-498c6c4a.dmp

Capybara::Poltergeist::DeadClient: PhantomJS client died while processing {"id":"19ff5bdb-c485-491c-a865-4c3fd42f1a37","name":"click","args":[71,20]}

Please change file of extention to .dmp 
[38a8fe9d-33cf-ab72-578a8340-498c6c4a.pdf](https://github.com/ariya/phantomjs/files/75304/38a8fe9d-33cf-ab72-578a8340-498c6c4a.pdf)

**Comment by Vanuan** [comment]
Which phantomjs binary is that?

**Comment by vietthventura** [comment]
@Vanuan is this the file you mean?
[38a8fe9d-33cf-ab72-578a8340-498c6c4a.txt](https://github.com/ariya/phantomjs/files/86967/38a8fe9d-33cf-ab72-578a8340-498c6c4a.txt)

I used nokogiki for the case, so thank you so much.

**Comment by Vanuan** [comment]
Sorry, I don't understand.

**Comment by Vanuan** [comment]
I meant which version of phantomjs did you use.
