### ISSUE TITLE
Use SemaphoreCI to check pull requests

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#13850]
While we are still searching for an ideal continuous build system (#13828), it was discovered that SemaphoreCI might be sufficient to run a build and the test suite for a feature branch in a pull request. It will be limited to 64-bit Linux, but it's better than nothing.

This issue is to track and note the progress of implementing pull request check using SemaphoreCI.

**Comment by Vanuan** [comment]
Isn't this trivial?
As you see here, pull requests are built automatically:
https://github.com/Vanuan/phantomjs/pull/1

**Comment by ariya** [comment]
Trivial or not, this is a placeholder to document any possible issues. If there is no issue, then it's fine. But it's always better to have it documented for future reference and/or search.

**Comment by ervinb** [comment]
Hi! I'm working on the Semaphore platform. The current plan is to double the number of cores available in the Docker enabled platform, starting from the next platform update, scheduled for Tuesday (19.02.2016). I hope this will have a positive effect on your project. Let me know if there's anything else I can help you with.

**Comment by ariya** [comment]
Obsoleted by #15403.
