### ISSUE TITLE
Clicks on li elements are lost

### ISSUE THREAD

**Issue by drauch** [ariya/phantomjs#13856]
While working perfectly fine with Selenium ChromeDriver and InternetExplorerDriver, we experienced that clicks on HTML li elements are "lost", i.e. not processed. No exception / error occurs, the click is simply not performed.

Here is a repro NUnit test case (NUnit 2.6.4, PhantomJS 2.0.0):

```
[Test]
public void PhantomJS_ClicksOnLiElementsAreIgnored ()
{
  using (var driver = new PhantomJSDriver ())
  {
    var uri = new Uri(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().CodeBase), "test.html")).AbsoluteUri;

    driver.Url = uri;
    Thread.Sleep (1000);
    driver.Title.Should().Be ("Test");

    var li = driver.FindElement (By.Id ("myLink"));

    // DOES NOT WORK:
    //li.Click();

    // ONLY THIS WORKS:
    var a = li.FindElement (By.TagName ("a"));
    a.Click();

    Thread.Sleep (1000);
    driver.Title.Should().Be ("Test2");
  }
}

// Samle test.html:
<html>
<head>
   <title>Test</title>
 </head>
 <body>
 <ul>
   <li id="myLink">
     <a href="test2.html">My Link</a>
   </li>
 </ul>
 </body>
 </html>

// Sample test2.html:
<html>
 <head>
   <title>Test2</title>
 </head>
 <body>
 Test2
 </body>
 </html>
```

Other browsers allow to click on the &lt;li&gt; element as well.

**Comment by eryczou** [comment]
Had similar issue here.  Using Protractor and Phantomjs. 

Phantomjs cannot click an li element, but Chrome Webdriver can do it

**Comment by JustAlexOne** [comment]
Having the same issue in my tests using PhantomJS and clicking on "li" element
