### ISSUE TITLE
Update Docs and PhantomJS 2.0 release notes regarding PDF issues

### ISSUE THREAD

**Issue by zeroedin-bill** [ariya/phantomjs#13868]
This issue is intended to propose, collect and proof modifications to the [documention on screen capture](http://phantomjs.org/screen-capture.html) and the PhantomJS 2.0 release notes to more thoroughly communicate the current issues surrounding use of PhantomJS as a HTML to PDF/Image renderer.

There are currently [161](https://github.com/ariya/phantomjs/search?utf8=%E2%9C%93&q=pdf+is%3Aopen&type=Issues) open issues mentioning PDF.

One of the major issues is that a change in QTWebkit causes PDF rendering inconsistencies between platforms. This seems to be due to the system DPI mismatch between 72 for POSIX based systems and 96 for Windows. There may be other factors involved, as users report that setting page.paperSize and page.viewportSize produces unexpected behavior. Users have posted a very wide variety of workarounds in #12685, and patches have been in the works for a while (see #13583), but no final solution has been committed to master.

Aside from the major issue above, numerous other PDF issues are reported.

I will keep this bug open for a week to collect verbiage suggestions, and then open a PR to modify the documentation and release notes as needed.

**Comment by ariya** [comment]
I support this initiative :+1:

**Comment by ariya** [comment]
As a reminder, for an even low-barrier mechanism to collect and collaborate on the notes, the wiki https://github.com/ariya/phantomjs/wiki is open for everyone. Link it from the web page, or do whatever the easiest.

**Comment by zeroedin-bill** [comment]
As there is now a PR #14085 open from Vitallium that largely fixes this, I think this is no longer required - as soon as the patch is merged I will submit a PR updating the docs explaining how to use the new WebPage.settings.dpi setting.
