### ISSUE TITLE
[OSX] master branch crashes when run in a sandbox

### ISSUE THREAD

**Issue by dunn** [ariya/phantomjs#13876]
Over at Homebrew we build and test packages in a sandbox.  The master branch of PhantomJS builds fine, but fails during the test.

To reproduce:
1. `./build.py --confirm --jobs 4`
2. Create the following test file and sandbox profile:

``` js
console.log("hello");
phantom.exit();
```

```
(version 1)
(debug deny) ; log all denied operations to /var/log/system.log
(allow file-write* (subpath "/private/tmp"))
(allow file-write* (subpath "/private/var/tmp"))
(allow file-write* (regex #"^/private/var/folders/[^/]+/[^/]+/[C,T]/"))
(allow file-write* (subpath "/private/tmp"))
(allow file-write* (subpath "/Library/Caches/Homebrew"))
(allow file-write* (subpath "/usr/local/var/cache"))
(allow file-write* (subpath "/usr/local/var/log"))
(allow file-write* (subpath "/usr/local/var/run"))
(allow file-write*
    (literal "/dev/ptmx")
    (literal "/dev/dtracehelper")
    (literal "/dev/null")
    (literal "/dev/zero")
    (regex #"^/dev/fd/[0-9]+$")
    (regex #"^/dev/ttys?[0-9]*$")
    )
(deny file-write*) ; deny non-whitelist file write operations
(allow process-exec
    (literal "/bin/ps")
    (with no-sandbox)
    ) ; allow certain processes running without sandbox
(allow default) ; allow everything else
```

Now `/usr/bin/sandbox-exec -f sandbox.sb phantomjs test.js` will fail with an error like this:

```
2016-01-10 08:58:22.433 phantomjs[62643:8250627] -[_NSXPCDistantObjectWithError performScanWithChannels:ssidList:legacyScanSSID:includeHiddenNetworks:mergeScanResults:maxAge:maxMissCount:maxWakeCount:maxAutoJoinCount:interfaceName:waitForWiFi:waitForBluetooth:token:priority:reply:]: unrecognized selector sent to instance 0x7ff8bc9089f0
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Abort trap: 6
```

**Comment by zackw** [comment]
We'd like this to work, but it's not been tried before AFAIK and so it's
not surprising it fails. I am unfamiliar with this sandboxing mechanism,
and the error message is unhelpful. Could you look in the system logs for
other, clearer errors?

Also, the test suite needs to bind and connect to unprivileged ports on
127.0.0.1; I don't see anything in that config file to allow that.

**Comment by dunn** [comment]
Here's the crash report: https://gist.github.com/dunn/c5d739a5d64204213fbd

The system logs didn't have any other errors messages, though.

**Comment by dunn** [comment]
> the test suite needs to bind and connect to unprivileged ports on 127.0.0.1; I don't see anything in that config file to allow that.

The sandbox currently just prevents certain filesystem writes; network activity is OK and we have quite a few tests that bind to a local port during their test.

**Comment by ariya** [comment]
Looks like we need to play with DTrace to figure out what file access was the offender.

**Comment by hermione521** [comment]
Bazel is also affected by this (see reference above). I'd like to know if you have any fix or workaround. Thanks.

**Comment by PierreAmmeloot** [comment]
Hello, what is the status of this request?

**Comment by dunn** [comment]
The current stable version of PhantomJS works fine in the sandbox, so I don't know if it's been fixed or is a transient error.
