### ISSUE TITLE
./build.py succeeds on branch master ./build.sh fails on branch 1.9.8 with `src/qt/bin/qmake: No such file or directory`

### ISSUE THREAD

**Issue by dmmmdfll** [ariya/phantomjs#13871]
I was able to successfully build version 2.0.0 on

    Linux ubuntug5 3.13.0-74-powerpc64-smp 
    #118-Ubuntu SMP Thu Dec 17 23:07:20 UTC 2015 ppc64 ppc64 ppc64 GNU/Linux

using the [instructions for building PhantomJS](http://phantomjs.org/build.html).

I then wanted to try version 1.9.8 of PhantomJS so I did the following:

```bash

    git checkout 1.9.8
    ./build.sh
```

The following error was returned: `src/qt/bin/qmake: No such file or directory`

Knowing very little about these sorts of things I turned to Google and found that others had had the same error returned. 

I did not find a solution in [a discussion I found here](https://groups.google.com/forum/#!msg/phantomjs/rIYDDP8wzds/VQ5cfZdrHE4J).

I found my own solution, however. Granted, it is not likely the most elegant solution; it did, however, work.

I am a newbie so please comment on how this could be done more elegantly! This is a hack because I do not really grok why my solution succeeded. I pieced together other hacks I found while googling. Though I think I have a sense of what is going on.

```bash

    git checkout 1.9.8
    # I noted that the build in 2.0.0 is a Python module and not a shell script so I checked out build.py
    git checkout master build.py
    # I postulated that qmake is built and needed source files so I removed ./src/qt
    # and checked out the master version
    rm -rf  ./src/qt
    git checkout master ./src/qt
    cd ./src/qt
    # I then populated the qt directory with the submodules with the qt source
    rm -rf 3rdparty/
    git clone https://github.com/Vitallium/phantomjs-3rdparty-win.git 3rdparty
    rm -rf qtbase
    git clone https://github.com/Vitallium/qtbase.git
    rm -rf qtwebkit
    git clone https://github.com/Vitallium/qtwebkit.git
    cd ../..
    git submodule init
    ./build.py
```

S̶u̶c̶c̶e̶s̶s̶!̶

NB: I tried using the source code from a non-git source. I ran `./build.sh` and had the same  `src/qt/bin/qmake: No such file or directory` error.

**Comment by ariya** [comment]
Switching between 1.x and 2.x branches are not recommended due to various complications (new submodule in 2.x etc). You may get it away by doing `git clean -xfd .` after switching. However, the safest way is to have a separate working directory for 1.x and 2.x.

**Comment by dmmmdfll** [comment]
I'll try that.

I declared success a little too early.

The build endlessly looped over the inability to find qt/src/3rdparty/webkit/Source/WebCore/generated/InspectorBackendStub.qrc

**Comment by dmmmdfll** [comment]
Is there a definitive solution to the `src/qt/bin/qmake: No such file or directory` ?

It's happening on two different machines for me. I would like to build version 1.9.8.

**Comment by dmmmdfll** [comment]
Your suggestion seems to be working on this machine:

    Linux DX4860 3.16.0-51-generic #69~14.04.1-Ubuntu SMP Wed Oct 7 15:32:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I am getting the `src/qt/bin/qmake: No such file or directory error` on this machine:

    Linux ubuntug5 3.13.0-74-powerpc64-smp #118-Ubuntu SMP Thu Dec 17 23:07:20 UTC 2015 ppc64 ppc64 ppc64 GNU/Linux

I installed all the requisite packages on both machines with the same command.

**Comment by Vitallium** [comment]
Qt 5 doesn't support PowerPC.

**Comment by dmmmdfll** [comment]
@Vitallium Thank you! That solves that. Nothing like chasing red herrings. It will teach me to stick on one machine until I get it working.
