### ISSUE TITLE
Failed at the phantomjs@1.9.19 install script 'node install.js'.

### ISSUE THREAD

**Issue by randydjones** [ariya/phantomjs#13877]
info postinstall request@2.42.0
4691 verbose unlock done using /root/.npm/_locks/request-7bb64398ccb405eb.lock for /opt/local/lib/node_modules/phantomjs/node_modules/request
4692 verbose about to build /opt/local/lib/node_modules/phantomjs
4693 info build /opt/local/lib/node_modules/phantomjs
4694 verbose linkStuff [ true,
4694 verbose linkStuff   '/opt/local/lib/node_modules',
4694 verbose linkStuff   true,
4694 verbose linkStuff   '/opt/local/lib/node_modules' ]
4695 info linkStuff phantomjs@1.9.19
4696 verbose linkBins phantomjs@1.9.19
4697 verbose link bins [ { phantomjs: './bin/phantomjs' }, '/opt/local/bin', true ]
4698 verbose linkMans phantomjs@1.9.19
4699 verbose rebuildBundles phantomjs@1.9.19
4700 verbose rebuildBundles [ '.bin',
4700 verbose rebuildBundles   'adm-zip',
4700 verbose rebuildBundles   'fs-extra',
4700 verbose rebuildBundles   'kew',
4700 verbose rebuildBundles   'md5',
4700 verbose rebuildBundles   'npmconf',
4700 verbose rebuildBundles   'progress',
4700 verbose rebuildBundles   'request',
4700 verbose rebuildBundles   'request-progress',
4700 verbose rebuildBundles   'which' ]
4701 verbose gentlyRm verifying that /opt/local is managed by npm
4702 silly isManaged /opt/local is not inside /opt/local/lib/node_modules
4703 silly isManaged /opt/local is not inside /opt/local/lib/node_modules
4704 silly isManaged /opt/local/bin is inside /opt/local
4705 silly gentlyRm /opt/local is managed by npm
4706 silly gentlyRm /opt/local/bin/phantomjs is under /opt/local
4707 verbose gentlyRm vacuuming /opt/local/bin/phantomjs up to /opt/local
4708 info install phantomjs@1.9.19
4709 verbose unsafe-perm in lifecycle false
4710 info phantomjs@1.9.19 Failed to exec install script
4711 verbose unlock done using /root/.npm/_locks/phantomjs-7b796d8c35016010.lock for /opt/local/lib/node_modules/phantomjs
4712 verbose stack Error: phantomjs@1.9.19 install: `node install.js`
4712 verbose stack Exit status 1
4712 verbose stack     at EventEmitter.<anonymous> (/opt/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
4712 verbose stack     at EventEmitter.emit (events.js:110:17)
4712 verbose stack     at ChildProcess.<anonymous> (/opt/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
4712 verbose stack     at ChildProcess.emit (events.js:110:17)
4712 verbose stack     at maybeClose (child_process.js:1008:16)
4712 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
4713 verbose pkgid phantomjs@1.9.19
4714 verbose cwd /home/admin/blecloud
4715 error SunOS 5.11
4716 error argv "/opt/local/bin/node" "/opt/local/bin/npm" "-g" "install" "phantomjs"
4717 error node v0.12.0
4718 error npm  v2.5.1
4719 error code ELIFECYCLE
4720 error phantomjs@1.9.19 install: `node install.js`
4720 error Exit status 1
4721 error Failed at the phantomjs@1.9.19 install script 'node install.js'.
4721 error This is most likely a problem with the phantomjs package,
4721 error not with npm itself.
4721 error Tell the author that this fails on your system:
4721 error     node install.js
4721 error You can get their info via:
4721 error     npm owner ls phantomjs
4721 error There is likely additional logging output above.
4722 verbose exit [ 1, true ]
4723 verbose unbuild lib/node_modules/phantomjs
4724 info preuninstall phantomjs@1.9.19
4725 info uninstall phantomjs@1.9.19
4726 verbose unbuild rmStuff phantomjs@1.9.19 from /opt/local/lib/node_modules
4727 verbose gentlyRm verifying that /opt/local is managed by npm
4728 silly isManaged /opt/local is not inside /opt/local/lib/node_modules
4729 silly isManaged /opt/local is not inside /opt/local/lib/node_modules
4730 silly isManaged /opt/local is not inside /opt/local/bin
4731 silly isManaged /opt/local is inside /opt/local
4732 silly gentlyRm /opt/local is managed by npm
4733 silly gentlyRm /opt/local/bin/phantomjs is under /opt/local
4734 verbose gentlyRm vacuuming /opt/local/bin/phantomjs up to /opt/local
4735 silly gentlyRm removing /opt/local/bin/phantomjs
4736 silly gentlyRm quitting because other entries in /opt/local/bin
4737 info postuninstall phantomjs@1.9.19
4738 verbose gentlyRm vacuuming /opt/local/lib/node_modules/phantomjs
4739 silly gentlyRm purging /opt/local/lib/node_modules/phantomjs
4740 silly gentlyRm quitting because other entries in /opt/local/lib/node_modules

**Comment by nathanboktae** [comment]
The npm package wrapper around `phantomjs` is separately maintained at https://github.com/Medium/phantomjs

**Comment by Vitallium** [comment]
Exactly. We don't maintain the NPM package.
