### ISSUE TITLE
Problems reported by test/run-tests.py on OS X, Ubuntu

### ISSUE THREAD

**Issue by mepard** [ariya/phantomjs#13882]
I grabbed the current master and built the debug version on OS X 10.11.2 with Xcode 7.2. Then I ran test/run-tests.py. 

./build.py --confirm --debug --git-clean-qtbase --git-clean-qtwebkit > buildout.txt 2>&1
test/run-tests.py >test/testout-debug.txt 2>&1

The result is a bunch of failures due to leak reports written to stderr as well as a crash due to a failed assertion. There's also an HTTP server error. Attached are the outputs of build.py and run-tests.py as well as the crash report.

I don't know if this is new behavior as I haven't tried run-tests.py previously. 

[buildout.txt](https://github.com/ariya/phantomjs/files/85992/buildout.txt)
[testout-debug.txt](https://github.com/ariya/phantomjs/files/85993/testout-debug.txt)
[phantomjs_2016-01-11-094955_Marcs-MacBook-Pro.crash.zip](https://github.com/ariya/phantomjs/files/86002/phantomjs_2016-01-11-094955_Marcs-MacBook-Pro.crash.zip)

**Comment by mepard** [comment]
I get similar results with Ubuntu-64 14.04.3.

[testout-ubuntu.txt](https://github.com/ariya/phantomjs/files/87662/testout-ubuntu.txt)

**Comment by Vitallium** [comment]
Landed in master! Thank you!
