### ISSUE TITLE
Object.defineProperty TypeError: Attempting to configurable attribute of unconfigurable property

### ISSUE THREAD

**Issue by MKuenzi** [ariya/phantomjs#13895]
When I run this code in phantomjs:

``` javascript
var Test = (function()
{
        function Test()
        {
            this.instanceProp = "hello!";
        }

        Object.defineProperty(Test, "name", {
            get: function () {
                return "TextHelper";
            },
            enumerable: true,
            configurable: true
        });

        return Test;
})();
```

I am getting the error TypeError: Attempting to configurable attribute of unconfigurable property.

Running this code in Firefox, Chrome and IE does not seem to produce an issue.

Thanks in advance for your help.

**Comment by CyborgMaster** [comment]
I've run into the same issue.  I'm running phonegap tests inside the ripple emulator inside phantomjs.  During part of it's initialization it runs something like the following:

``` js
Object.defineProperty(window, 'name', {
  value: {}, configurable: true, enumerable: true
});
```

which throws this error:
```
TypeError: Attempting to configurable attribute of unconfigurable property.
```

This doesn't happen in Chrome.  Interestingly enough I'm seeing the crash trying to define a property with the same name (`name`) as the OP.  That might be a clue to the underlying issue.

**Comment by MKuenzi** [comment]
Good observation.  When I change the name of the property in the code that was failing it seems PhantomJS is fine.   So indeed it appears to be an issue with a property named "name".

**Comment by MKuenzi** [comment]
Good observation.  I have changed all uses of the property "name" in my code and everything seems to run fine now.

**Comment by CyborgMaster** [comment]
I wish I had that option.  I'm using a third party tool (apache ripple emulator), and so I can't change the properties they use.

**Comment by CyborgMaster** [comment]
Just checking in on this issue.  Has it been fixed?

**Comment by CyborgMaster** [comment]
I can confirm that this is still failing in phantomjs 2.1.1

**Comment by mitermayer** [comment]
still happens on 2.1.7

**Comment by dfleury** [comment]
I had the same problem when testing my SPA which uses CasperJS+PhantomJS and InfernoJS.

**Comment by sridharrajagopal** [comment]
I have the same issue when using AWS SDK - aws-sdk-2.2.19.min.js

**Comment by sridharrajagopal** [comment]
Any updates on this? 

Thanks,
Sridhar

**Comment by ljqx** [comment]
See [Function.name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name), before ES6, Function.name is not configurable. I think for fixing this bug, PhantomJS needs to upgrade QtWebkit to latest version. Current QtWebkit 2.2 is released 2011, there will be more and more bugs like this one.

**Comment by ljqx** [comment]
There is already a tracing issue, see #14506. @ariya , this bug is related to ES6 too.

**Comment by AlexandreBonneau** [comment]
On my end I'm using:
```js
Object.defineProperty(domElement, attributeToWatch, {
    set: val => {
        console.log('value has changed', val);
    },
});
```
where `attributeToWatch` can be `'value'`, `'textContent'` or `'nodeValue'` with PhantomJS `2.1.1`, and I get that `TypeError: Attempting to change access mechanism for an unconfigurable property.` error message too.

**Comment by limingli0707** [comment]
Do you guys have any work around about this issue. I'm updating mt project with angular 1.7.9 and got the `TypeError: Attempting to configurable attribute of unconfigurable property`, but it was working for with angular 1.7.5

**Comment by rksinghUI** [comment]
@limingli0707 , Have you got any fix fort This issue. I am also trying to update to Angular 1.7.9 and stuck. Can you help with the solution.

**Comment by aleen42** [comment]
Any progress?

**Comment by ilanb1996** [comment]
I also have similar issue, im using phatomJs for running unit tests for legacy browsers (es5 support) and my tests keep failing, in the beginning ive used `jasmine.spyOnProperty(document.body, 'scrollHeight', 'get')` and got this error, then ive tried to use 
```JS
Object.defineProperty(document.body, 'scrollHeight', {
          value: 1000,
          writable: true,
          configurable: true
        });
```
but i still get this error, not sure what to do, thinking on just dropping this test for phantomJs but i dont like it because its a hack and not a real solution
