### ISSUE TITLE
PhantomJS handles calc incorrectly if it relies on vh or vw

### ISSUE THREAD

**Issue by etamponi** [ariya/phantomjs#13896]
I am using PhantomJS compiled from source, last compilation some hour ago (it also reproduces on PhantomJS 2.0 on Windows).

This html snippet will render an empty page in PhantomJS:

``` html
<style>
   .container {
        width: 100%;
        height: calc(100vh - 50px);
    }
</style>
<div class="container"></div>
```

If you use `height: calc(100pt - 50px)`, it will work. If you use `height: 100vh`, it will work. The combination of `calc` and `vh` will not.

**Comment by monkpit** [comment]
+1 - this is affecting my tests, unfortunately. Anyone have any ideas about what's causing the problem on Phantom's side of things?

**Comment by etamponi** [comment]
I investigated a bit more and found that it is a WebKit bug...
Il 27 apr 2016 8:13 AM, "Kyle Pittman" <notifications@github.com> ha
scritto:

**Comment by JabbyPanda** [comment]
https://bugreports.qt.io/browse/QTBUG-39553

This issue was logged as QtWebKit bug quite a while ago

**Comment by chrisswarb** [comment]
Just wondering if there has been any progress on this issue?

Thought a fix would be in the latest QtWebkit, but it still seems to fail. I've attached a screenshot to show the behavior.

The first paragraph of the screenshot is all standard vw values. As you can see, the font size changes as expected between the reference and test file.
The second and third paragraphs contain fonts sized with calc(vw) and -webkit-calc(vw), and neither of them change between the reference and test.

![phantomtestcalcvw](https://cloud.githubusercontent.com/assets/16538371/20054858/945d14f0-a4d6-11e6-97fa-9c142316d020.png)

**Comment by Vitallium** [comment]
@chrisswarb what do you mean by the latest QtWebKit? NG version by @annulen ?

**Comment by chrisswarb** [comment]
@Vitallium Thanks for your quick response! 

Just thought the problem was in QtWebkit, so I upgraded my PhantomJS install to 2.1.1 which uses Qt 5.5 right? 

This doesn't seem to fix anything unfortunately. Even though the comments on this ticket say it has been fixed in relation to another issue (https://bugreports.qt.io/browse/QTBUG-39553)

**Comment by lessenadam** [comment]
Just a quick ping on this issue. 

Even with ```viewportSize: {
height: 720,
width: 1280
} ```, both `calc(100vh)` and `-webkit-calc(100vh)` compute to 0px, which causes some tests to break. 

Any thoughts on potential fixes? Thanks!

**Comment by chrisswarb** [comment]
@lessenadam Didn't find a fix myself, so I just ended up adding an appropriate fallback value that wasn't using calc and vw together. This worked for my case.

Otherwise I suppose the only other way you could try is to hook in some kind of script which calculates the absolute values and overwrites the calc(vw) rules on the fly.

**Comment by lessenadam** [comment]
@chrisswarb Thanks for the response! Yeah, I ended up just doing a check in JS to handle this one edge case, but a parsing script in less might be interesting to catch all instances. 

Seems like Safari had a similar issue in 2014 but fixed it. Would be curious to know if there is something analogous that would work for PhantomJS, or how it could even be fixed under the hood...

Safari issue: http://stackoverflow.com/questions/25516934/safari-css-using-calc-with-vh-does-not-work

**Comment by Jack89ita** [comment]
Any news about this?
Thanks

**Comment by annulen** [comment]
@Jack89ita Please try 2.5.0-beta from https://bitbucket.org/ariya/phantomjs/downloads/

**Comment by chrisswarb** [comment]
@Jack89ita @lessenadam 

This is now working as expected in 2.5.0-beta.

![phantom-2 5 0-betavw](https://cloud.githubusercontent.com/assets/16538371/23406082/234a3e7c-fdb5-11e6-99ec-6d5d0e9ac9dd.png)

**Comment by Jack89ita** [comment]
@chrisswarb Thank you very much!

**Comment by etamponi** [comment]
Thank you!
