### ISSUE TITLE
Crash in webservice to capture page to PDF file

### ISSUE THREAD

**Issue by fvhovell** [ariya/phantomjs#13899]
See attached stacktrace. During the crash a webserver running in PhantomJS 1.9.8 was 'bombarded' with at max 5 simultaneous requests from a golang client.

[stacktrace.txt](https://github.com/ariya/phantomjs/files/92939/stacktrace.txt)

**Comment by ariya** [comment]
Can you try it again with PhantomJS 2.1?

**Comment by fvhovell** [comment]
After fixing my JS script to deal with double URI-encoded query string on incoming requests (see [commit](https://bitbucket.org/ariya/phantomjs/commits/1c203a39279ae556f84bf7b525415e50845419b3#Lsrc/webserver.cppT206) for issue #12216), I can no longer reproduce the issue with the crashing phantomjs process. 

However because the PDF rendering in the 2.0+ versions of phantomjs is unusable for me (see e.g. issues #13553, #12685 and #13524), the current situation is not a solution to this issue with crashing webserver module inside phantomjs 1.9.x. 

Ideally I would like to use an updated webserver module in phantomjs 1.9.x series (i.e. using the known-working pdf-rendering libqt4)
