### ISSUE TITLE
cookies aren't enable - selenium webdriver.io phantomjs

### ISSUE THREAD

**Issue by narainsagar** [ariya/phantomjs#13897]
The documentation says: Cookies are enabled in PhantomJS by default. But not sure why Amazon returns that page.

![2](https://cloud.githubusercontent.com/assets/13800762/12371319/f34a8dea-bc50-11e5-8ce6-1885258d6317.png)

Here is my code:

```
var webdriverio = require('webdriverio');

var opts = desiredCapabilities: {
    browserName: 'phantomjs',
    javascriptEnabled: true
  },
  "host": "localhost",
  "port": 4444
};

var email = ''; // your email
var password: ''; // your password

var client = webdriverio
      .remote(opts)
      .init()
      .url('https://www.amazon.co.uk/gp/sign-in.html')
      .setValue('#ap_email', email)
      .setValue('#ap_password', password)
      .submitForm('form[name="signIn"]')
      .then(function() { // save the screenshot
              this.saveScreenshot(__dirname + '/loginPage.png');
      })
      .end();
```

I had logged the cookies object it returns empty/none:

```
{ 
  sessionId: 'a96eb340-bb6a-11e5-ae83-c52b2435a008',
  status: 0,
  value: [] 
}
```

, and tried to set a custom Cookie with

`.setCookie({name: '', value: '', domain: 'amazon.co.uk'})`

But still have the same problem..

As I think phantomJS is blocking it because when i changed the browserName with chrome then it works fine.. Still, I want it work via PhantomJS.

Any help will be appreciated - Thanks.

**Comment by thesciz** [comment]
I'm having a similar issue with cookies seemingly not being enabled by default. I'm using Karma.

**Comment by narainsagar** [comment]
Hi @thesciz The problem actually was that Amazon server blocks the IP, so to achieve we have used `Tor` instances through which we dynamically change/switch over the IP.
