### ISSUE TITLE
Is there a way to enable Video Support

### ISSUE THREAD

**Issue by michaelgohl** [ariya/phantomjs#13902]
Hey Guys,

one question: Is there a way to enable the qtwebkit support for video and audio tags in phantomjs. I know that phantomjs doesn't support it. That's ok.

Thanks for your answer!

**Comment by michaelgohl** [comment]
Compiling with use_gsteamer doesn't work...

**Comment by ariya** [comment]
Unfortunately, it's pretty unlikely that this is going to be supported in PhantomJS 2.
