### ISSUE TITLE
PhantomJS 2.0.0 Crash on OS X 10.11.2

### ISSUE THREAD

**Issue by Chekote** [ariya/phantomjs#13906]
Apologies, but I could not convert the crash dump to a stack trace, since there are no symbols available on the [download page](https://bitbucket.org/ariya/phantomjs/downloads) for version 2.0.0 of PhantomJS.

I have attached the stack trace [as instructed](http://phantomjs.org/crash-reporting.html):

[5FD2B3F2-2CAC-404C-B938-2CB80BB7849B.dmp.zip](https://github.com/ariya/phantomjs/files/96093/5FD2B3F2-2CAC-404C-B938-2CB80BB7849B.dmp.zip)

**Comment by ariya** [comment]
Can you try it again with PhantomJS 2.1?
