### ISSUE TITLE
cannot change user-agent

### ISSUE THREAD

**Issue by digitaldavenyc** [ariya/phantomjs#13900]
I am changing the phantom user-agent string from the page.settings, but it's not actually changing the user-agent. If you inspect navigator.userAgent it shows the PhantomJS agent string.

```
var page = require('webpage').create(),
system = require('system'),
address, output, size;

address = system.args[1];
output = system.args[2];
page.customHeaders =  {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36'
};
page.viewportSize = { width: 1024, height: 800 };
page.settings.userAgent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36';
page.open(address, function (status) {
    if (status !== 'success') {
        console.log('Unable to load the address!');
        phantom.exit(1);
    } else {
        window.setTimeout(function () {
            console.log(navigator.userAgent);
            phantom.exit();
        }, 200);
    }
});
```

`navigator.userAgent` should return `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36`

but it returns `Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.0.0 Safari/538.1`

Tested on PhantomJS 2.0.0 and 1.9.8 on MacOSX

**Comment by awakmu** [comment]
I have verified that setting ```page.settings.userAgent``` "will" change the ```User-Agent``` header in the http request.
But I don't know if ```navigator.userAgent``` should change or not.

**Comment by digitaldavenyc** [comment]
@awakmu I think it should, it's inconsistent if they do not match.

But even if it doesn't, there needs to be a way to change it in the navigator because it's not truly changing the userAgent if the navigator userAgent doesn't match the http request.

**Comment by awakmu** [comment]
> This is actually causing a failure for me, one of the site's I run this on checks the navigator.userAgent in JavaScript and does not run the application if someone visits the site in an unsupported browser.
You're right about this.

**Comment by awakmu** [comment]
Hi @digitaldavenyc,

I think you should log ```navigator.userAgent``` at page context, not at outer context.
Like this:
```
page.evaluate(function(args)
{
	console.log(navigator.userAgent);
});	
```
This will output the same user agent string with ```page.settings.userAgent``` variable.

**Comment by ariya** [comment]
@digitaldavenyc You can try the trick given in the example script, look for `examples/detectsniff.js`.

**Comment by groovemaps** [comment]
@ariya thanks for pointing me to that file. I get back `The page tried to sniff the user agent.`

@awakmu The userAgent is not being set somewhere properly because I am receiving a message that it is an unsupported browser from a third-party website that I run the phantomjs code against.

**Comment by digitaldavenyc** [comment]
@ariya thanks for pointing me to that file. I get back `The page tried to sniff the user agent.`

@awakmu The userAgent is not being set somewhere properly because I am receiving a message that it is an unsupported browser from a third-party website that I run the phantomjs code against.

**Comment by ariya** [comment]
@digitaldavenyc Well yeah, that's expected. But if you understand what `detectsniff.js` is doing, why can't you try to change the detected user agent?

**Comment by digitaldavenyc** [comment]
@ariya By overwriting the navigator.userAgent ... yes I suppose that would work, but why is it even being set as phantomJS if the headers are set properly?

**Comment by awakmu** [comment]
Hi @digitaldavenyc,

"The userAgent is not being set somewhere properly because I am receiving a message that it is an unsupported browser from a third-party website that I run the phantomjs code against."

Have you solved this problem after change user agent using ```page.onInitialized``` callback ?
