### ISSUE TITLE
PhantomJS v2 won't start on Windows when drive f: is an empty DVD drive

### ISSUE THREAD

**Issue by db6edr** [ariya/phantomjs#13905]
We are running PhantomJS 2.0.0 inside of karma-phantomjs2-launcher. On machines that have empty (virtual) DVD drives as drive f:, PhantomJS crashes with this error message:

```
ERROR [phantomjs.launcher]: Auto configuration failed
10192:error:02001015:system library:fopen:Is a directory:.\crypto\bio\bss_file.c:169:fopen('F:\development\openssl\!BUILD/ssl/openssl.cnf','rb')
10192:error:2006D002:BIO routines:BIO_new_file:system lib:.\crypto\bio\bss_file.c:174:
10192:error:0E078002:configuration file routines:DEF_LOAD:system lib:.\crypto\conf\conf_def.c:199:

ERROR [launcher]: Cannot start PhantomJS2
```

The workaround is astonishingly simple: Reconfigure the drive to have any other drive letter and PhantomJS runs as expected.

Using `subst` to create a mapped drive f: does **not** trigger this error.

**Comment by ariya** [comment]
@Vitallium Did you build the Windows binary with some OpenSSL library on the F: drive?

**Comment by ariya** [comment]
@db6edr Could you quickly try if this is still the case with the brand new PhantomJS 2.1?

**Comment by db6edr** [comment]
Sure ... 
This issue still occurs with PhantomJS, binary version 2.1.1. The npm package already is at  2.1.2.

**Comment by Vitallium** [comment]
@ariya that was a problem with 2.0.0 release only. Current version (2.1.1) is ok.

**Comment by woppa684** [comment]
@Vitallium This problem still exists in 2.1.1 right? We are still abnle to reproduce it ...

**Comment by Vitallium** [comment]
@woppa684 I can't reproduce it with 2.1.1 version. See my screenshot above.

**Comment by woppa684** [comment]
Maybe it's worth mentioning that we use the NPM package (which just always downloads the 2.1.1 version zip file and installs it) so we run it via node. Could that make a difference?

**Comment by Vitallium** [comment]
@woppa684 I don't think so. Which npm package are you using?

**Comment by woppa684** [comment]
I used https://www.npmjs.com/package/phantomjs2 this time ...

**Comment by Vitallium** [comment]
@woppa684 , could you please run PhantomJS manually from `node_modules`? To ensure the correct version.

**Comment by woppa684** [comment]
Found it! We were using the (deprecated) karma-phantomjs2-launcher. This launcher had phantomjs-ext or something as a dependency (and was using that in stead of the latest phantomjs). We now switched to karma-phantomjs-launcher which has the latest phantomjs as a PEER dependency and it works!

**Comment by Vitallium** [comment]
@woppa684 Great!
