### ISSUE TITLE
Segmentation fault on Ubuntu Server 14.04 "Trusty Tahr" LTS

### ISSUE THREAD

**Issue by renaissancesoftware** [ariya/phantomjs#13913]
Build fails on Ubuntu Server 14.04 "Trusty Tahr" LTS. I am following build instructions from http://phantomjs.org/build.html

./build.py --jobs 1
----------------------------------------
               WARNING
----------------------------------------

Building PhantomJS from source takes a very long time, anywhere from 30 minutes
to several hours (depending on the machine configuration). It is recommended to
use the premade binary packages on supported operating systems.

For details, please go the the web site: http://phantomjs.org/download.html.

Do you want to continue (Y/n)? Y
Executing in /home/www/html/atest/phantomjs: git submodule init
Executing in /home/www/html/atest/phantomjs: git submodule update --init
configuring Qt Base, please wait...
Executing in /home/www/html/atest/phantomjs/src/qt/qtbase: /home/www/html/atest/phantomjs/src/qt/qtbase/configure -static -opensource -confirm-license -prefix /home/www/html/atest/phantomjs/src/qt/qtbase -qt-zlib -qt-libpng -qt-libjpeg -qt-pcre -nomake examples -nomake tools -nomake tests -no-qml-debug -no-dbus -no-opengl -no-audio-backend -D QT_NO_GRAPHICSVIEW -D QT_NO_GRAPHICSEFFECT -D QT_NO_STYLESHEET -D QT_NO_STYLE_CDE -D QT_NO_STYLE_CLEANLOOKS -D QT_NO_STYLE_MOTIF -D QT_NO_STYLE_PLASTIQUE -D QT_NO_PRINTPREVIEWDIALOG -qpa phantom -openssl -openssl-linked -no-openvg -no-eglfs -no-egl -no-glib -no-gtkstyle -no-cups -no-sm -no-xinerama -no-xkb -no-xcb -no-kms -no-linuxfb -no-directfb -no-mtdev -no-libudev -no-evdev -no-pulseaudio -no-alsa -no-feature-PRINTPREVIEWWIDGET -fontconfig -icu -release

This is the Qt Open Source Edition.

You are licensed to use this software under the terms of
the Lesser GNU General Public License (LGPL) versions 2.1.
You are also licensed to use this software under the terms of
the GNU Lesser General Public License (LGPL) versions 3.

You have already accepted the terms of the Open Source license.

<srcbase> = /home/www/html/atest/phantomjs/src/qt/qtbase
<outbase> = /home/www/html/atest/phantomjs/src/qt/qtbase
Creating qmake...
.Done.
Running configuration tests...

WARNING: Using static linking will disable the WebKit module.

   Configure summary

Build type:    linux-g++ (x86_64, CPU features: mmx sse sse2)
Platform notes:

            - Also available for Linux: linux-clang linux-kcc linux-icc linux-cxx

Build options:
  Configuration .......... accessibility avx avx2 c++11 clock-gettime clock-monotonic compile_examples concurrent enable_new_dtags eventfd fontconfig full-config getaddrinfo getifaddrs gif harfbuzz iconv icu inotify ipv6ifname jpeg large-config largefile medium-config minimal-config mremap nis openssl-linked pcre png posix_fallocate precompile_header qpa qpa reduce_exports reduce_relocations release rpath small-config sse2 sse3 sse4_1 sse4_2 ssse3 static system-freetype use_gold_linker xlib xrender zlib
  Build parts ............ libs
  Mode ................... release
  Using sanitizer(s)...... none
  Using C++11 ............ yes
  Using gold linker....... yes
  Using new DTAGS ........ yes
  Using PCH .............. yes
  Target compiler supports:
    SSE2/SSE3/SSSE3 ...... yes/yes/yes
    SSE4.1/SSE4.2 ........ yes/yes
    AVX/AVX2 ............. yes/yes

Qt modules and options:
  Qt D-Bus ............... no
  Qt Concurrent .......... yes
  Qt GUI ................. yes
  Qt Widgets ............. yes
  Large File ............. yes
  QML debugging .......... no
  Use system proxies ..... no

Support enabled for:
  Accessibility .......... yes
  ALSA ................... no
  CUPS ................... no
  Evdev .................. no
  FontConfig ............. yes
  FreeType ............... yes (system library)
  Glib ................... no
  GStreamer .............. no
  GTK theme .............. no
  HarfBuzz ............... yes (bundled copy)
  Iconv .................. yes
  ICU .................... yes
  Image formats:
    GIF .................. yes (in QtGui, using bundled copy)
    JPEG ................. yes (in QtGui, using bundled copy)
    PNG .................. yes (in QtGui, using bundled copy)
  journald ............... no
  libinput................ no
  mtdev .................. no
  Networking:
    getaddrinfo .......... yes
    getifaddrs ........... yes
    IPv6 ifname .......... yes
    libproxy.............. no
    OpenSSL .............. yes (linked to the libraries)
  NIS .................... yes
  OpenGL / OpenVG:
    EGL .................. no
    OpenGL ............... no
    OpenVG ............... no
  PCRE ................... yes (bundled copy)
  pkg-config ............. yes
  PulseAudio ............. no
  QPA backends:
    DirectFB ............. no
    EGLFS ................ no
      EGLFS i.MX6....... . no
      EGLFS KMS .......... no
      EGLFS Mali ......... no
      EGLFS Raspberry Pi . no
      EGLFS X11 .......... no
    LinuxFB .............. no
    XCB .................. no
  Session management ..... no
  SQL drivers:
    DB2 .................. no
    InterBase ............ no
    MySQL ................ no
    OCI .................. no
    ODBC ................. no
    PostgreSQL ........... no
    SQLite 2 ............. no
    SQLite ............... yes (plugin, using bundled copy)
    TDS .................. no
  tslib .................. no
  udev ................... no
  xkbcommon-x11........... no
  xkbcommon-evdev......... no
  zlib ................... yes (bundled copy)

WARNING: Using static linking will disable the use of dynamically
loaded plugins. Make sure to import all needed static plugins,
or compile needed modules into the library.

NOTE: When linking against OpenSSL, you can override the default
library names through OPENSSL_LIBS.
For example:
    OPENSSL_LIBS='-L/opt/ssl/lib -lssl -lcrypto' ./configure -openssl-linked

Qt is now configured for building. Just run 'make'.
Once everything is built, Qt is installed.
You should not run 'make install'.

Prior to reconfiguration, make sure you remove any leftovers from
the previous build.

building Qt Base, please wait...
Executing in /home/www/html/atest/phantomjs/src/qt/qtbase: make -j 1
cd src/ && ( test -e Makefile || /home/www/html/atest/phantomjs/src/qt/qtbase/bin/qmake /home/www/html/atest/phantomjs/src/qt/qtbase/src/src.pro -o Makefile ) && make -f Makefile
make[1]: Entering directory `/home/www/html/atest/phantomjs/src/qt/qtbase/src'
cd tools/bootstrap/ && ( test -e Makefile || /home/www/html/atest/phantomjs/src/qt/qtbase/bin/qmake /home/www/html/atest/phantomjs/src/qt/qtbase/src/tools/bootstrap/bootstrap.pro -o Makefile ) && make -f Makefile
make[2]: Entering directory `/home/www/html/atest/phantomjs/src/qt/qtbase/src/tools/bootstrap'
make[2]: Nothing to be done for `first'.
make[2]: Leaving directory `/home/www/html/atest/phantomjs/src/qt/qtbase/src/tools/bootstrap'
cd tools/moc/ && ( test -e Makefile || /home/www/html/atest/phantomjs/src/qt/qtbase/bin/qmake /home/www/html/atest/phantomjs/src/qt/qtbase/src/tools/moc/moc.pro -o Makefile ) && make -f Makefile
make[2]: Entering directory `/home/www/html/atest/phantomjs/src/qt/qtbase/src/tools/moc'
make[2]: Nothing to be done for `first'.
make[2]: Leaving directory `/home/www/html/atest/phantomjs/src/qt/qtbase/src/tools/moc'
cd tools/rcc/ && ( test -e Makefile || /home/www/html/atest/phantomjs/src/qt/qtbase/bin/qmake /home/www/html/atest/phantomjs/src/qt/qtbase/src/tools/rcc/rcc.pro -o Makefile ) && make -f Makefile
make[2]: Entering directory `/home/www/html/atest/phantomjs/src/qt/qtbase/src/tools/rcc'
make[2]: Nothing to be done for `first'.
make[2]: Leaving directory `/home/www/html/atest/phantomjs/src/qt/qtbase/src/tools/rcc'
cd 3rdparty/pcre/ && ( test -e Makefile || /home/www/html/atest/phantomjs/src/qt/qtbase/bin/qmake /home/www/html/atest/phantomjs/src/qt/qtbase/src/3rdparty/pcre/pcre.pro -o Makefile ) && make -f Makefile
make[2]: Entering directory `/home/www/html/atest/phantomjs/src/qt/qtbase/src/3rdparty/pcre'
make[2]: Nothing to be done for `first'.
make[2]: Leaving directory `/home/www/html/atest/phantomjs/src/qt/qtbase/src/3rdparty/pcre'
cd corelib/ && ( test -e Makefile || /home/www/html/atest/phantomjs/src/qt/qtbase/bin/qmake /home/www/html/atest/phantomjs/src/qt/qtbase/src/corelib/corelib.pro -o Makefile ) && make -f Makefile
make[2]: Entering directory `/home/www/html/atest/phantomjs/src/qt/qtbase/src/corelib'
g++ -c -include .pch/Qt5Core -pipe -O3 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -Wall -W -D_REENTRANT -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_TSLIB -DQT_NO_LIBINPUT -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -DQT_NO_PRINTPREVIEWDIALOG -DQT_NO_USING_NAMESPACE -DQT_BUILD_CORE_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_USE_ICU -DQT_CORE_LIB -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -I. -I../3rdparty/zlib -I../../include -I../../include/QtCore -I../../include/QtCore/5.5.1 -I../../include/QtCore/5.5.1/QtCore -Iglobal -I../3rdparty/pcre -I../3rdparty/harfbuzz/src -I../3rdparty/md5 -I../3rdparty/md4 -I../3rdparty/sha3 -I../3rdparty/forkfd -I.moc -I../../mkspecs/linux-g++ -o .obj/qdir.o io/qdir.cpp

g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [.obj/qdir.o] Error 4
make[2]: Leaving directory `/home/www/html/atest/phantomjs/src/qt/qtbase/src/corelib'
make[1]: *** [sub-corelib-make_first] Error 2
make[1]: Leaving directory `/home/www/html/atest/phantomjs/src/qt/qtbase/src'
make: *** [sub-src-make_first] Error 2

ERROR: Failed to build PhantomJS! Building Qt Base failed.
===================================================
root@ns3019079:/home/www/html/atest/phantomjs# free -g
             total       used       free     shared    buffers     cached
Mem:           251        214         37          0          2         57
-/+ buffers/cache:        154         97
Swap:            0          0          0

**Comment by ariya** [comment]
You need at least 4 GB RAM and 3 GB disk space. It seems that your system doesn't have enough resource. Can you confirm?

**Comment by ariya** [comment]
Closing this due to lack of further information.
