### ISSUE TITLE
Phantom Remote Debugger Crashing in 2.1.1

### ISSUE THREAD

**Issue by DhirajAdPushup** [ariya/phantomjs#13938]
Just built a new binary of Phantom today. While applying `breakpoint` the phantom is crashing, Although when using `conditional Breakpoint` and writing a console.log statement there, things are working. So practically not able to use debugger. @Vitallium I will be highly obliged if you will have a look into it.

**Comment by iradul** [comment]
Can you provide example script ?
What platform are you using ?
