### ISSUE TITLE
PhantomJs crashes while i try to retrieve a textarea field id and set its value.

### ISSUE THREAD

**Issue by jigneshdesai** [ariya/phantomjs#13939]
I am using casperJS

  var xxxxx =   this.evaluate(function () {
      return $("[name$='Listing.Description']")[0].id;
    });
  casper.echo(xxxxx);
  casper.echo('input[id="' + xxxxx + '"]');

  this.sendKeys('input[id="'+ xxxxx +  '"]', 'WTF');

When it reaches to this point in the script it crashes.   

Inside the eval function ....
AppListing_DescriptionTextarea_1152921504653905921
input[id="AppListing_DescriptionTextarea_1152921504653905921"]
PhantomJS has crashed. Please read the crash reporting guide at
http://phantomjs.org/crash-reporting.html and file a bug report at
https://github.com/ariya/phantomjs/issues/new.
Please attach the crash dump file:
  C:\Users\j\AppData\Local\Temp\2806364d-4119-4991-a057-bfae513a15de.dmp

Any advice please ?

Regards

**Comment by ariya** [comment]
Can you try it again with PhantomJS 2.1?
