### ISSUE TITLE
Create a self-contained source archive

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#13930]
Now that we're using git submodules, producing a self-contained archive of the source code is non-trivial.

**Comment by ariya** [comment]
I tried https://github.com/meitar/git-archive-all.sh to no avail. Any other tips or help will be appreciated!

/cc @Vitallium @zackw

**Comment by ariya** [comment]
Hmm, seems that I shall also try this Python-based https://github.com/Kentzo/git-archive-all.

**Comment by ariya** [comment]
Good news: the Python-based git-archive-all. seems to work!
Bad news: building from the source tarball fails miserably :cry: 

@zackw I've included your `skip-git` trick but it seems that something is still wrong, QMake can't be bootstrapped.

Steps to reproduce (from the master branch):
```bash
sudo pip install git-archive-all
git-archive-all -v source-test.zip
unzip source-test
cd source-test
./build.py --confirm --release
```

It will quickly fail with the following error:
```
../src/corelib/global/qglobal.h:72:10: fatal error: 'QtCore/qsystemdetection.h' file not found
#include <QtCore/qsystemdetection.h>
         ^
1 error generated.
make: *** [project.o] Error 1
```

**Comment by zackw** [comment]
> @zackw I've included your `skip-git` trick but it seems that something is still wrong, QMake can't be bootstrapped.

I had the same problem when I was experimenting with Docker.  `touch src/qt/qtbase/.git` before invoking `build.py` will get you further -- the qt configure script needs to *think* it's building out of git, or it will skip a critical step.  I don't know if that's *enough*, I never got past qtwebkit not detecting static ICU properly.

**Comment by Vitallium** [comment]
@zackw afaik, we already trigger git build it in `build.py`. But I'm not sure.

**Comment by ncopa** [comment]
This is an issue for packaging phantomjs for alpine linux. We need working release tarballs.

Also, would it be an option to use system qt and system qtwebkit instead of shipping a fork of it?

**Comment by Vitallium** [comment]
@ncopa right now we can't use system Qt and QtWebkit due to the patches that we applied to them. If you need working release tarballs you can get them from here https://bitbucket.org/ariya/phantomjs/downloads

**Comment by ncopa** [comment]
@Vitallium there are not source tarball for 2.1.1 on https://bitbucket.org/ariya/phantomjs/downloads

What patches are applied to Qt and QtWebkit. Can those patches be forwarded to upstream Qt? If upstream accept them then I can apply those to the qt packages on Alpine Linux.

**Comment by Vitallium** [comment]
@ncopa you can download it via github (choose Tag 2.1.1, clone, pull all submodules and create an archive).

Unfortunately, our patches are too specific and we can't forward them to the upstream.

**Comment by ncopa** [comment]
@Vitallium I think it would be great if upstream could provide working release tarballs so downstream does not need to. It is no problem to do the release engineering for upstream when you maintain 10 or less packages, but it becomes annoying if you maintain more than 100 packages and a real problem if you have more than 1000.

it also scares me a bit that you chose to maintain your own fork of qtwebkit: https://blogs.gnome.org/mcatanzaro/2016/02/01/on-webkit-security-updates/

**Comment by Vitallium** [comment]
@ncopa we know that. But this is not possible in the current state. Perhaps we will use the upstream version of Webkit in future. We don't have that much human power to develop PhantomJS super actively.

**Comment by zackw** [comment]
@ncopa We don't like the present situation any more than you do.  But I think it would probably be best if you didn't package PhantomJS for Alpine.

**Comment by ariya** [comment]
Let's keep this ticket focused on the original issue (how to create a source tarball).

If someone wants to start the discussion on upstream, let's do this on our [phantomjs-dev mailing list](groups.google.com/forum/#!topic/phantomjs-dev/)!

**Comment by annulen** [comment]
@ncopa: it is possible to 1) review all changes needed for PhantomJS and 2) add necessary APIs into QtWebKit upstream. However, both 1) and 2) will take time, and even if all QtWebKit patches were submitted today I'm not sure if they could be accepted into Qt 5.7 because it is already in feature freeze.

**Comment by mislav** [comment]
I get absolutely the same error, even though I pulled source from git + submodules and not from any source archive:

```
git checkout -q 2.1.1
git submodule update --init
./build.py --jobs 1 --confirm
```

Results in:

```
[precise-amd64]  ../src/corelib/global/qglobal.h:72:37: fatal error: QtCore/qsystemdetection.h: No such file or directory
[precise-amd64]  compilation terminated.
[precise-amd64]  make: *** [project.o] Error 1
```

I fail to see how this problem is a problem of source archives per se? It seems like a general problem with the build system.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
