### ISSUE TITLE
Remove service-dependent examples

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#13931]
Some example scripts rely on web sites out there to work. This is a maintenance burden, there is not even guarantee that it will work forever. The example code was necessary back when PhantomJS was relatively unknown and the documentation was minimal. This is not the case anymore these days and thus we should lean towards a set of maintenance-free example scripts.

**Comment by zackw** [comment]
:+1:

I've been working in the same direction on the test suite (right now the core testsuite only ever talks to localhost, but the ghostdriver test suite relies on all kinds of external websites to exist -- with the same HTML structure as they used to have, too).
