### ISSUE TITLE
module/webpage/includejs provokes ASSERTION FAILED: !m_frame->page()->defersLoading() || InspectorInstrumentation::isDebuggerPaused(m_frame) in debug mode

### ISSUE THREAD

**Issue by zackw** [ariya/phantomjs#13935]
When phantomjs is compiled in debug mode, we get an assertion failure in the test suite:

```
module/webpage/includejs: ERROR
ERROR: Unexpected output on stderr
  ASSERTION FAILED: !m_frame->page()->defersLoading() || InspectorInstrumentation::isDebuggerPaused(m_frame)
  loader/DocumentLoader.cpp(361) : void WebCore::DocumentLoader::finishedLoading(double)
ERROR: PhantomJS killed by signal 11
```

(The segfault is WebCore deliberately forcing a crash.)

**Comment by mepard** [comment]
module/webpage/includejs tests okay for me (OS X 10.11.2, Xcode 7.2) in debug mode:

    module/webpage/includejs: pass
    HTTP server errors: pass
    
     1.013s elapsed
        2 passed
