### ISSUE TITLE
Building RPM for Centos 6/7

### ISSUE THREAD

**Issue by daniel-lucio** [ariya/phantomjs#13941]
[root@pilar phantomjs-2.1.1]# ./build.py --confirm           
configuring Qt Base, please wait...
Executing in /root/rpmbuild/SOURCES/phantomjs-2.1.1/src/qt/qtbase: /root/rpmbuild/SOURCES/phantomjs-2.1.1/src/qt/qtbase/configure -static -opensource -confirm-license -prefix /root/rpmbuild/SOURCES/phantomjs-2.1.1/src/qt/qtbase -qt-zlib -qt-libpng -qt-libjpeg -qt-pcre -nomake examples -nomake tools -nomake tests -no-qml-debug -no-dbus -no-opengl -no-audio-backend -D QT_NO_GRAPHICSVIEW -D QT_NO_GRAPHICSEFFECT -D QT_NO_STYLESHEET -D QT_NO_STYLE_CDE -D QT_NO_STYLE_CLEANLOOKS -D QT_NO_STYLE_MOTIF -D QT_NO_STYLE_PLASTIQUE -D QT_NO_PRINTPREVIEWDIALOG -qpa phantom -openssl -openssl-linked -no-openvg -no-eglfs -no-egl -no-glib -no-gtkstyle -no-cups -no-sm -no-xinerama -no-xkb -no-xcb -no-kms -no-linuxfb -no-directfb -no-mtdev -no-libudev -no-evdev -no-pulseaudio -no-alsa -no-feature-PRINTPREVIEWWIDGET -fontconfig -icu -release
Traceback (most recent call last):
  File "./build.py", line 458, in <module>
    main()
  File "./build.py", line 451, in main
    builder.run()
  File "./build.py", line 357, in run
    self.buildQtBase()
  File "./build.py", line 300, in buildQtBase
    self.configureQtBase()
  File "./build.py", line 287, in configureQtBase
    if self.execute(configure, "src/qt/qtbase") != 0:
  File "./build.py", line 134, in execute
    process = subprocess.Popen(command, stdout=sys.stdout, stderr=sys.stderr, cwd=workingDirectory)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Not familiar with phython. What dependency is it looking for

I have reviewed src/qt/qtbase and it is empty.

I have already this requires (rpm Phantom 2.0),
BuildRequires: gcc
BuildRequires: gcc-c++
BuildRequires: make
BuildRequires: flex
BuildRequires: bison
BuildRequires: gperf
BuildRequires: ruby
BuildRequires: openssl-devel
BuildRequires: freetype-devel
BuildRequires: fontconfig-devel
BuildRequires: libicu-devel
BuildRequires: sqlite-devel
BuildRequires: libpng-devel
BuildRequires: libjpeg-devel
BuildRequires: python
BuildRequires: qtwebkit-devel
BuildRequires: gstreamer-devel
BuildRequires: alsa-lib-devel
BuildRequires: cups-devel
BuildRequires: xorg-x11-drv-evdev-devel
BuildRequires: glib2-devel
BuildRequires: mtdev-devel
BuildRequires: mesa-libEGL-devel
BuildRequires: mesa-libGLU-devel
BuildRequires: mesa-libGLw-devel
BuildRequires: pcre-devel
BuildRequires: pkgconfig
BuildRequires: pulseaudio-libs-devel
BuildRequires: libxcb-devel
BuildRequires: postgresql-devel
BuildRequires: sqlite2-devel
BuildRequires: libgudev1-devel
%if 0%{?rhel}  == 7
BuildRequires: mariadb-devel
BuildRequires: gtk3-devel
BuildRequires: libxkbcommon-devel
BuildRequires: mesa-libGLES-devel
%else
BuildRequires: mysql-devel
%endif

I guess I am missing new ones, please advice.

**Comment by iradul** [comment]
How about [download](http://phantomjs.org/download.html) official 2.1.1 executable :smile:  ?

If you really want to compile it yourself you should use Docker as explained [here](https://github.com/ariya/phantomjs/blob/master/deploy/README.md).

**Comment by daniel-lucio** [comment]
I am not asking support for docker, nor  to use your binaries. Thats why you give the source.

Do you have a list of build-reqs?

**Comment by ariya** [comment]
Was this building from a git clone as documented in http://phantomjs.org/build.html?

**Comment by daniel-lucio** [comment]
Im using the zip ball you provide here, i have packed 1.9 and 2.0 without an issue. I have problems with 2.1

I am stucked here:

webpage.h:49:1: error: expected class-name before ‘{’ token
 {
 ^
phantom.cpp: In member function ‘void Phantom::loadModule(const QString&, const QString&)’:
phantom.cpp:384:134: error: no matching function for call to ‘QWebFrame::evaluateJavaScript(QString&, QString)’
     m_page->mainFrame()->evaluateJavaScript(scriptSource, QString(JAVASCRIPT_SOURCE_PLATFORM_URL).arg(QFileInfo(filename).fileName()));
                                                                                                                                      ^
phantom.cpp:384:134: note: candidate is:
In file included from /usr/include/qt5/QtWebKitWidgets/QWebFrame:1:0,
                 from webpage.h:37,
                 from phantom.cpp:46:
/usr/include/qt5/QtWebKitWidgets/qwebframe.h:211:14: note: QVariant QWebFrame::evaluateJavaScript(const QString&)
     QVariant evaluateJavaScript(const QString& scriptSource);
              ^
/usr/include/qt5/QtWebKitWidgets/qwebframe.h:211:14: note:   candidate expects 1 argument, 2 provided
phantom.cpp: In member function ‘void Phantom::onInitialized()’:
phantom.cpp:483:5: error: no matching function for call to ‘QWebFrame::evaluateJavaScript(QString, QString)’
     );
     ^
phantom.cpp:483:5: note: candidate is:
In file included from /usr/include/qt5/QtWebKitWidgets/QWebFrame:1:0,
                 from webpage.h:37,
                 from phantom.cpp:46:
/usr/include/qt5/QtWebKitWidgets/qwebframe.h:211:14: note: QVariant QWebFrame::evaluateJavaScript(const QString&)
     QVariant evaluateJavaScript(const QString& scriptSource);
              ^
/usr/include/qt5/QtWebKitWidgets/qwebframe.h:211:14: note:   candidate expects 1 argument, 2 provided
make[1]: *** [phantom.o] Error 1
make[1]: Leaving directory `/root/rpmbuild/SOURCES/phantomjs-2.1.1/src'
make: *** [sub-src-phantomjs-pro-make_first-ordered] Error 2

ERROR: Failed to build PhantomJS! Building PhantomJS failed.


What QtWebKitWidgets and QT5 are you using (exact release), cause this error means that prototypes are incompatible. I am compiling against 5.5.1

**Comment by daniel-lucio** [comment]
But i see your point,
i am going to reproduce those steps with simple unzip things

**Comment by ariya** [comment]
We don't provide source tarball for now. If you grab it from this tagged release from Github, i.e. https://github.com/ariya/phantomjs/tags, it won't work.

For now, the only way to build from source is using git. See #13930 for more details.

**Comment by ariya** [comment]
This seems to be solved, see #13949.
