### ISSUE TITLE
Incorrect date handling

### ISSUE THREAD

**Issue by drkn** [ariya/phantomjs#13948]
./phantomjs --version
2.1.1

./phantomjs                                                                                                                                
phantomjs> new Date()
"2016-01-26T22:23:40.197Z" <-- correct
phantomjs> console.log(new Date())
Wed Jan 27 2016 22:23:55 GMT+2400 <!-- invalid

Why GMT is reported as GMT+2400 ? Correct one should be +0100, but I guess in this case it still should be UTC. I'm having issues with moment library on PhantomJS because of this where moment(new Date()).format("DD.MM.YYYY") returns 27.01.2016 where it should be 26.01.2016 ...

**Comment by lmanzke** [comment]
Unfortunately, dates have numerous issues said to have been fixed. I also stumbled upon various dubious things. '10.10.2010' is a valid Date in Chrome. Not so in phantom 2.1.1 That is really annoying if you have Date validation in place!

**Comment by Vitallium** [comment]
Duplicate. Please see #11151
