### ISSUE TITLE
Centos 6/7 RPMs for PhamtomJS 2.1.1 

### ISSUE THREAD

**Issue by daniel-lucio** [ariya/phantomjs#13949]
http://inside-out.xyz/technology/rpm-for-phantomjs-2-1-1.html

Enjoy!

**Comment by ariya** [comment]
Well thanks! But what do you want us to do with this?

**Comment by daniel-lucio** [comment]
It is part of my job, to build RPM packages. As it is opensource, they are available for public.

Many sysadmins will prefer RPM rather than using a tarball.

**Comment by ariya** [comment]
Thanks! Next time someone is looking for an RPM, we'll share this information with them!
