### ISSUE TITLE
Incorrect webserver.port after "autodetect"

### ISSUE THREAD

**Issue by puzrin** [ariya/phantomjs#13947]
``` js
var webserver = require('webserver').create();

webserver.listen('127.0.0.1:0', function () {
   console.log(webserver.port); // => 127.0.0.1:0 instead of real value.
});
```

I'd like to bump problem that was ripped in 1.x branch. There are no simple way to know webserver port if it was selected automatically (and that works fine in slimerjs). Current code just mirror input value instead of real one https://github.com/ariya/phantomjs/blob/2.1.1/src/webserver.cpp#L130.

Could you fix that?

**Comment by ariya** [comment]
Oops, this sounds like an annoying side effect. I'll take a look!
