### ISSUE TITLE
Phantomjs 2.1.1 doesn't build on Freebsd 10.2

### ISSUE THREAD

**Issue by OllieJones** [ariya/phantomjs#13946]
While trying to build on Freebsd 10.2 the following error crops up after less than a minute.

    Running configuration tests...
    The ICU library support cannot be enabled.
    Turn on verbose messaging (-v) to /usr/home/ollie/phantomjs/build/phantomjs/src/qt/qtbase/configure to see the final report.
    If you believe this message is in error you may use the continue
     switch (-continue) to /usr/home/ollie/phantomjs/build/phantomjs/src/qt/qtbase/configure to continue.

    ERROR: Failed to build PhantomJS! Configuration of Qt Base failed.

icu version 55.1 appears to be correctly installed.

**Comment by OllieJones** [comment]
I don't mind working to fix this issue if you can point me in the right direction. Thanks.

**Comment by ariya** [comment]
Do you have ICU development libraries and header files?

**Comment by OllieJones** [comment]
Indeed I do have the ICU development stuff. icu-55.1 is installed, using the standard FreeBSD "pkg install icu". 

The headers are in /usr/local/include/unicode  
and the libs are in /usr/local/lib/libicu*

Does your build require this stuff to be in /usr/ rather than /usr/local/ ?

Thanks.

**Comment by ariya** [comment]
Yeah, `/usr/local` is not searched by default. Thus, try:

```bash
python build.py --qt-config "-I /usr/local/include/ -L /usr/local/lib/"
```

**Comment by OllieJones** [comment]
That's it. Thank you sir.

**Comment by martinsb** [comment]
On FreeBSD 10.2 I have the following error (checked out the 2.1.1 version):
```
g++ -Wl,-O1 -pthread -o ../../../bin/rcc .obj/rcc.o  .obj/main.o   -L/usr/local/lib -L/usr/home/mb/src/phantomjs/src/qt/qtbase/lib -lQt5Bootstrap -lz
/usr/local/lib/libQt5Bootstrap.a(qstring.o): In function `QString::multiArg(int, QString const**) const':
../../corelib/tools/qstring.cpp:(.text._ZNK7QString8multiArgEiPPKS_+0x236): undefined reference to `void std::__1::__sort<std::__1::__less<int, int>&, int*>(int*, int*, std::__1::__less<int, int>&)'
collect2: error: ld returned 1 exit status
```
@OllieJones, did you encounter the same error and if you did, how did you work around it?

**Comment by avkarenow** [comment]
I have the same problem with g++/ld on FreeBSD 10.3. Any ideas?

**Comment by carylewis** [comment]
Experiencing the same issue on Freebsd 10.3 attempting to build phantomjs using port.

Tried gcc 5.1, gcc46
