### ISSUE TITLE
PhantomJS 2.1.1 crash

### ISSUE THREAD

**Issue by ethaizone** [ariya/phantomjs#13950]
1   0x1b67967 phantomjs() [0x1b67967]
2   0x1b800a9 phantomjs() [0x1b800a9]
3   0x18378f4 phantomjs() [0x18378f4]
4   0x1aa5fb1 phantomjs() [0x1aa5fb1]
5   0x1986fbd phantomjs() [0x1986fbd]
6   0x1a8ea33 phantomjs() [0x1a8ea33]
7   0x79da8e phantomjs() [0x79da8e]
8   0x79e042 phantomjs() [0x79e042]
9   0x170c3c0 phantomjs() [0x170c3c0]
10  0x174409e phantomjs() [0x174409e]
11  0x1744259 phantomjs() [0x1744259]
12  0x1403b65 phantomjs() [0x1403b65]
13  0x171de7e phantomjs() [0x171de7e]
14  0x171e7bb phantomjs() [0x171e7bb]
15  0x173973f phantomjs() [0x173973f]
16  0x175247e phantomjs() [0x175247e]
17  0x7f20fd phantomjs() [0x7f20fd]
18  0x177e84e phantomjs() [0x177e84e]
19  0xd95a1b phantomjs() [0xd95a1b]
20  0x7fb2105190e5 [0x7fb2105190e5]

This is last one I got from my ssh. My server crash.

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

$ cat /proc/version
Linux version 3.13.0-32-generic (buildd@kissel) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014

**Comment by ethaizone** [comment]
Another one that I got from server after run again.

1   0x1b67967 phantomjs() [0x1b67967]
2   0x1b84ac3 phantomjs() [0x1b84ac3]
3   0x1ba0f99 phantomjs() [0x1ba0f99]
4   0x1b9a618 phantomjs() [0x1b9a618]
5   0x1b9a9ae phantomjs() [0x1b9a9ae]
6   0x16fa9ce phantomjs() [0x16fa9ce]
7   0x1744076 phantomjs() [0x1744076]
8   0x1744259 phantomjs() [0x1744259]
9   0x1403b65 phantomjs() [0x1403b65]
10  0x171de7e phantomjs() [0x171de7e]
11  0x171e7bb phantomjs() [0x171e7bb]
12  0x173973f phantomjs() [0x173973f]
13  0x175247e phantomjs() [0x175247e]
14  0x7f20fd phantomjs() [0x7f20fd]
15  0x177e84e phantomjs() [0x177e84e]
16  0xd95a1b phantomjs() [0xd95a1b]
17  0x7fca313dd0e5 [0x7fca313dd0e5]
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault

**Comment by ariya** [comment]
Do you have any steps to reproduce the crash?

**Comment by bharatraj88** [comment]
I too faced the same issue. This was what I am getting on the logs. No specific steps to reproduce as well.

1   0x1b67967 phantomjs() [0x1b67967]
2   0x1baac35 phantomjs() [0x1baac35]
3   0x1b9369c phantomjs() [0x1b9369c]
4   0x18970ad phantomjs() [0x18970ad]
5   0x1896ace phantomjs() [0x1896ace]
6   0x1896ddf phantomjs() [0x1896ddf]
7   0x19c52ad phantomjs() [0x19c52ad]
8   0x7f9d25dd4372 [0x7f9d25dd4372]
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report


We running phantomjs on Linux

**Comment by ethaizone** [comment]
Oh. I'm sorry for not reply. I think I can do somehow about it so it's not important issue anymore. Thank you for response.
