### ISSUE TITLE
PhantomJS 2.1.1 downloading, frequent 429 Too Many Requests errors

### ISSUE THREAD

**Issue by johanneswuerbach** [ariya/phantomjs#13951]
Recently downloading PhantomJS binaries failed more and more often in my CI runs. I'm fully aware that this is a bitbucket issue, but would it be possible to distribute the binaries also via github releases https://github.com/ariya/phantomjs/releases, which I found was quite reliable in the past?

Example testem CI run:
https://ci.appveyor.com/project/johanneswuerbach/testem/build/768/job/k13peuov2jh5tex5
```
Status: 429
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-windows.zip",
  "encoding": null,
  "followRedirect": true,
  "headers": {
    "User-Agent": "npm/2.14.12 node/v4.2.4 win32 ia32"
  },
  "strictSSL": true
}
```

**Comment by ariya** [comment]
Unfortunately Github doesn't provide any metrics at all. We would like to at least keep track of the download counts.

In all cases, bring this up to https://github.com/Medium/phantomjs/ as we don't handle that npm package. Possible workarounds (1) that npm package should support alternative download URL via environment variable and you point it to your own mirror (2) in your CI process, download the binary yourself from your own mirror.

**Comment by johanneswuerbach** [comment]
Looks like everybody is hardcoding the semi broken bitbucket mirror at the moment. choco (the windows package management) is also using it https://chocolatey.org/packages/PhantomJS and failing frequently.

Homebrew is using https://bintray.com/, which is free for OSS and has stats. Maybe that could be an option?

**Comment by johanneswuerbach** [comment]
> Possible workarounds (1) that npm package should support alternative download URL via environment variable and you point it to your own mirror (2) in your CI process, download the binary yourself from your own mirror.

Yes that would be definitely an option, but I guess I'm not the only one running into that issue and it feels a bit pointless that everybody maintains their own mirror. (which would also screw up download stats)

**Comment by ariya** [comment]
For alternative download location, discuss it at #13953.
