### ISSUE TITLE
Regression: phantom.onError trace does not contain files any more

### ISSUE THREAD

**Issue by joscha** [ariya/phantomjs#13955]
In Phantom 1.x the `trace` parameter to `onError` looked like this:

``` json
[
  {
    "file": "phantomjs://webpage.evaluate()",
    "line": 2,
    "function": "erroneusFinder"
  },
  {
    "file": "phantomjs://webpage.evaluate()",
    "line": 3,
    "function": ""
  },
  {
    "file": "phantomjs://webpage.evaluate()",
    "line": 3,
    "function": ""
  }
]
```

whereas in 2.x it looks like this:

``` json
[
  {
    "file": "undefined",
    "line": 2,
    "function": "erroneusFinder"
  },
  {
    "file": "",
    "line": 3,
    "function": ""
  }
]
```

with the former format it was actually possible to determine whether the error was thrown within a function ran/injected by PhantomJS vs. ones of the target page or resources on the target page.
This is for example used in [crawlkit/isPhantomError](https://github.com/crawlkit/crawlkit/blob/master/src/isPhantomError.js).
Can we fix the `file` parameter for Phantom 2.x to align with the Phantom 1.x trace again?

**Comment by Vitallium** [comment]
@joscha thanks for reporting. Answerting to your question: yes, it will be fixed in #12973
