### ISSUE TITLE
Task Manager full with PhantomJS instances

### ISSUE THREAD

**Issue by vjeetje** [ariya/phantomjs#13958]
I'm using the PhantomJS 2.0.0 on windows 10 with Selenium. I made sure to call the quit method on each driver in the finally block of the main execution method. At the end of my tests, my taskmanager is full of  'PhantomJS is a headless webkit with javascript api' entries. They aren't doing anything more than taking a bit of RAM. I have set the phantomjs.exe myself:

		capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY,
				"C:/tools/phantomjs-2.0.0-windows/bin/phantomjs.exe");

I thought this issue was fixed in a previous release(1.9.x), but it still occurs for me on 2.0.0.
Is there any other data I can provide?

**Comment by ariya** [comment]
Thanks for the report! PhantomJS quits properly if you call `phantom.exit()`, there must be some interplay with other tools that caused this. Can you bring this up to the Ghost Driver project instead?

**Comment by vjeetje** [comment]
Thanks for your reply. The PhantomJSDriver doesn't have an exit() method unfortunately.
For people with the same issue a work-around is calling both close() and quit()
