### ISSUE TITLE
Performance API not impilmented

### ISSUE THREAD

**Issue by zackarychapple** [ariya/phantomjs#13957]
ran into issues with my unit tests going against PhantomJS because I am directly using the performance API.  Is there plans for adding this to PhantomJS?

**Comment by yorkmoy** [comment]
In my particular scenario using phantomJS v2.1.14, performance.now() works, but performance.mark() does not.  It looks like mark() has not been implemented in WebKit, https://developer.mozilla.org/en-US/docs/Web/API/Performance/mark .
