### ISSUE TITLE
Failing to install on CentOS 7.1

### ISSUE THREAD

**Issue by finid** [ariya/phantomjs#13964]
Trying to install MEAN on CentOS 7.1, but always get the following errors after running `npm install`:

```
npm ERR! Linux 3.10.0-229.20.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
```

Note that despite the failure, the rest of the application still works. It would be nice to get PhantomJS to install.

Any clues? 

Node 4.2.6 and NPM 2.14.12. Fails even with NPM 3.3

**Comment by Vitallium** [comment]
Sorry but we don't maintain the npm package. Please file your issue in the corresponding repo.
