### ISSUE TITLE
Opening a color input dialog causes hanging in PhantomJS 2.0

### ISSUE THREAD

**Issue by stephanepoirier** [ariya/phantomjs#13979]
Hi,

**Description**
Since PhantomJS 2.0, opening an HTML color input causes execution to hang, presumably waiting for user input.

The behavior slightly differs depending on the OS used.
- Windows 10: a color-picking modal dialog pops, then execution hangs (until the dialog is manually closed).
- Debian 8 (XFCE): execution simply hangs (no dialog).

PhantomJS 1.9.8 + Windows/Debian: OK
PhantomJS 2.0.0 + Windows (Debian not tested): reproduced
PhantomJS 2.1.1 + Windows/Debian: reproduced

**Test case**
The attached [test case](https://github.com/ariya/phantomjs/files/118259/phantomjs.color.input.hang.test.case.zip) opens a page containing a color input. PhantomJS then presses "Enter" to trigger color input. Usage:
- Extract
- cd into directory
- run `phantomjs main.js` in terminal.

Expected: execution terminates.
Actual: execution hangs when triggering color input.

**Thoughts**
I could not identify the specific reason for the behavior change between 1.9.8 and 2.0.0.

Following the pattern of other PhantomJS modal dialog listeners (e.g. webpage.onAlert), the issue could possibly be addressed by hooking on QtWebKit's QWebPagePrivate::colorSelectionRequested ([qtwebkit/Source/WebKit/qt/WidgetApi/qwebpage_p.h](https://github.com/qtproject/qtwebkit/blob/14a3e9e525d48d18a823e9dd133a2175015bf6c2/Source/WebKit/qt/WidgetApi/qwebpage_p.h#L101)).

A simpler alternative would be to build QtWebKit with the `QT_NO_COLORDIALOG` flag. That would prevent invocation of the color picking dialog (see [qtwebkit/Source/WebKit/qt/WidgetApi/qwebpage.cpp](https://github.com/qtproject/qtwebkit/blob/14a3e9e525d48d18a823e9dd133a2175015bf6c2/Source/WebKit/qt/WidgetApi/qwebpage.cpp#L1841)). The downside of this approach is that it does not give control on the color picking process.

---

I'm new to PhantomJS. If you confirm I'm not too off-track, I'll be glad to contribute in fixing this. :-)

**Comment by futurist** [comment]
I'm also suffered from this problem using PhantomJS 2.1.1, whether it's been fixed? How to get updated phantom version? Thanks!
