### ISSUE TITLE
Can't build on SuSE s/390

### ISSUE THREAD

**Issue by apsf2** [ariya/phantomjs#13973]
Trying to build from source on a SUSE Linux Enterprise Server 11 (s390x).

I have built CURL 7.47.0, OpenSSL 1.1.0-pre2, ICU 65 from source, and still I get failure when running qt tests:

You have already accepted the terms of the Open Source license.

<srcbase> = /data/tmp/phantomjs-2.1/src/qt/qtbase
<outbase> = /data/tmp/phantomjs-2.1/src/qt/qtbase
Creating qmake...
.Done.
Running configuration tests...
OpenSSL support cannot be enabled due to functionality tests!
 Turn on verbose messaging (-v) to /data/tmp/phantomjs-2.1/src/qt/qtbase/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /data/tmp/phantomjs-2.1/src/qt/qtbase/configure to continue.

ERROR: Failed to build PhantomJS! Configuration of Qt Base failed.

Any idea on how to fix this?

Thanks

**Comment by ariya** [comment]
I assume this is not x86 system. If that is the case, then the platform is not supported.

**Comment by CurryKitten** [comment]
@ariya I've just been searching to look for s390/s390x (i.e zLinux) support.  Obviously it isn't supported as yet - in order so support it, are you looking for someone to resolve the issues in building/contribute those back and supply the binary to your prebuilt download site ?

I can see that some work on ppc64le here https://github.com/ariya/phantomjs/issues/14421 although no word on BE.  But this hasn't made it to the binary downloads ?
