### ISSUE TITLE
Harmonize child_process API with Node

### ISSUE THREAD

**Issue by zackw** [ariya/phantomjs#13970]
The `child_process` module's API is not precisely aligned with Node.  The issue I know about is that the `exit` event doesn't report unsuccessful exit / death due to signals in the same way that Node documents, but there may be others.

Node 5.5 documentation for this module: https://nodejs.org/api/child_process.html

@L09 pointed this out during discussion of #13945.  @L09, if you have time to go through the Node documentation thoroughly, make a list of all of the deviations, and post it here, that would be very helpful.

**Comment by L09** [comment]
* process.spawn('bad_command').on('error') is not supported in PhantomJS. Only on('exit') is supported.

* process.exec is not yet implemented.

* process.execFile always passes null as the error parameter to the callback function. It should pass the Error object in case of an error. If the command returned a non-null exit status, it should pass the status in the error.code property.
