### ISSUE TITLE
Download link for "latest" version

### ISSUE THREAD

**Issue by BanzaiMan** [ariya/phantomjs#13986]
Hello, I was wondering if it is feasible to have a download URL that points to the latest version; e.g., https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-latest-linux-x86_64.tar.bz2 It would be beneficial for testing with the latest release.

Thanks.

**Comment by ariya** [comment]
Unfortunately, Bitbucket doesn't offer a symbolic link. We may be able to do this once we move away from Bitbucket, keep an eye on issue #13953.
