### ISSUE TITLE
problem with taking screenshot by phantomjs?

### ISSUE THREAD

**Issue by ShahrokhNiakan** [ariya/phantomjs#13987]
var page = require( 'webpage' ).create();

var url = 'beytoote.com';

  page.viewportSize = { width: 1920, height: 1080 };

  page.open( 'http://' + url + '/' );

  page.onLoadFinished = function(status) {

    if ( status !== 'success' ) {

        console.log( 'Unable to load the address!' );

        phantom.exit();

    } else {

        console.log( status );
 
        page.render( url + '.png' );

        phantom.exit();

    }
};

When I run this program in Cammand Line I get this error : 
TypeError: null is not an object (evaluating 'document.getElementById("flashObj"
).style')

  http://ads.goldiran.ir/show.aspx?s=6&u=635202199247551609:28 in global code

problem is with web pages that use iframe I think?

**Comment by Vitallium** [comment]
I suppose, that `flashObj` is a Adobe Flash element. Is this correct?
But Flash is not supported by PhantomJS.

**Comment by ShahrokhNiakan** [comment]
this is another error that have problem with screenshot .
TypeError: null is not an object (evaluating 'd.getElementById('awadclose').oncl
ick = function() {
                                        location = u + "&aid=b-64315&ai=28281645
";
                                }')

  http://ad.anetwork.ir/showad/c.php?adwidth=300&adheight=250&aduser=1437226049&

**Comment by Vitallium** [comment]
@ShahrokhNiakan this is not an issue of PhantomJS. This is just a regular error in a bad JavaScript code because PhantomJS doesn't support Adobe Flash.

**Comment by ShahrokhNiakan** [comment]
@Vitallium  how can solve this problem i need screenshot of this pages?

**Comment by Vitallium** [comment]
@ShahrokhNiakan you still can render screenshots. If you want to suppress those JavaScript errors use callback `onError` - http://phantomjs.org/api/webpage/handler/on-error.html

**Comment by ShahrokhNiakan** [comment]
@Vitallium how should i add this callback to my code?

**Comment by Vitallium** [comment]
@ShahrokhNiakan check out the link above. Our API has examples.

**Comment by ShahrokhNiakan** [comment]
@Vitallium i mean where should i put it after page.open() or before it or some where else? thanks
