### ISSUE TITLE
Possible caught the virus?

### ISSUE THREAD

**Issue by Jatik** [ariya/phantomjs#13993]
When I try to download the exe file my Microsoft Security Essentials reports that is has a virus and deletes it. It says that phantomjs.exe file contains Trojan:Win32/Varpes.M!plock

Can you please verify what's going on??? Thanks

**Comment by zackw** [comment]
Please give the exact URL of the file you tried to download?

**Comment by Jatik** [comment]
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-windows.zip

**Comment by Vitallium** [comment]
@Jatik repost from our mailing list: https://groups.google.com/forum/#!topic/phantomjs/f8Ea19KmQ3c

>Windows binary is compressed with UPX. It's false alarm. If you're curious you can decompress it (`upx -d phantomjs.exe`) and re-scan it again. I'm sure Windows Defender will not complain about it.

**Comment by Jatik** [comment]
Thanks for the response. Is it possible to compress it with something else? We are going to use it for the testing in our company and I'm afraid we can't overcome this issue even if we have some proof of "innocence" of this file. But another problem was the antivirus "detected" virus in already unpacked exe file. And I really don't know what to do with it.

**Comment by Vitallium** [comment]
@Jatik unfortunately we can't help you with this. You probably should mark PhantomJS as trusted executable.

**Comment by jmiller76** [comment]
Wouldn't using the decompressed version work?

**Comment by Jatik** [comment]
Yes decompression version definitely would work but I have no idea where to get it.Thanks

**Comment by jmiller76** [comment]
UPX is on SourceForge and the command line that Vitallium linked to above worked for me to expand the file to 49MB.
