### ISSUE TITLE
CSS3 Background Gradients and Borders problem with PDFs

### ISSUE THREAD

**Issue by Lussay** [ariya/phantomjs#13999]
Second Issue:

When outputting a div that has a CSS3 background gradients and borders to PDF, the outputed background looks weird.

If the border is removed, it looks fine.

Test URL: http://www.comandarapid.ro/testhtml/htmlxhead.html
For result please see attached PDF:
[phantomjs2.pdf](https://github.com/ariya/phantomjs/files/127230/phantomjs2.pdf)

**Comment by Lussay** [comment]
Upon further testing I realized that the height of the bad gradient is caused by the sum of the following CSS values:

top
margin-top
border-top

Still a bug ...

**Comment by fangwChina** [comment]
why i set background color is unwork when page to pdf ?

**Comment by pouu69** [comment]
i have same issue
