### ISSUE TITLE
Cannot run PhantomJS 2 on Debian 8 (Jessie)

### ISSUE THREAD

**Issue by guenhter** [ariya/phantomjs#13990]
Hi,

when running PhantomJS 2 on Debian 8 (Jessie) the following error appears:

`bin/phantomjs: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory`

Turns out, that the `libjpeg.so.8` is not longer available for Debian. Also at 
[https://packages.debian.org/search?keywords=libjpeg8](https://packages.debian.org/search?keywords=libjpeg8)
no `libjpeg8` can be found for that debian version.

It seems that the original `libjpeg8` was replaced in favour of `libjpeg62-turbo`.

**Comment by ariya** [comment]
How did you install PhantomJS?

Is this a standard Debian 8 installation or a customized one?

I tested the binary before making the 2.1 release. In fact, I just verified it again and it runs just fine. Here are steps if you want to follow along.

First, we make a VM for Debian 8 using its [Vagrant base box](https://wiki.debian.org/Teams/Cloud/VagrantBaseBoxes):
```bash
vagrant init debian/jessie64
vagrant up
vagrant ssh
```

and once inside the virtual machine, we can download PhantomJS and run it:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.3 (jessie)
Release:	8.3
Codename:	jessie

$ uname -a
Linux debian-jessie 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux

$ wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
$ tar jxf phantomjs-2.1.1-linux-x86_64.tar.bz2
$ phantomjs-2.1.1-linux-x86_64/bin/phantomjs -v
2.1.1
```
In fact, if you look at the binary, it won't even need `libjpeg.so.8`:
```
$ ldd phantomjs-2.1.1-linux-x86_64/bin/phantomjs 
	linux-vdso.so.1 (0x00007ffe60d98000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb361d4a000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fb361b0d000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fb361863000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb36165f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb361457000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb36123a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb360f2f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb360c2e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb360a18000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb36066d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb361f65000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fb360444000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fb36021d000)
```

**Comment by guenhter** [comment]
Thanks. I will double check why this happens in my environment, than let you know and close the ticket.

**Comment by ariya** [comment]
@guenhter Please provide also the details on the system, e.g. `lsb-release -a`, `uname -a`, like in the examples I've given above.

**Comment by guenhter** [comment]
Not longer an issue, after use a clean environment. I think i had a mixup.
