### ISSUE TITLE
Number.isInteger() is undefined 

### ISSUE THREAD

**Issue by ivancho98** [ariya/phantomjs#14014]
I am running my karma tests in phantomjs, but when trying to call Number.isInteger() an error is displayed: 

`	TypeError: 'undefined' is not a function (evaluating 'Number.isInteger(3)')`

When running with Chromium, the call to isInteger is executed without problems.

**Comment by zackw** [comment]
I regret to say that `Number.isInteger` is an ECMAScript v6 feature that is not supported by the version of Webkit we have (even in 2.1.1).  It's in Safari version 9, so if we ever manage to upgrade Webkit again, we might get it then, but Webkit upstream has dropped Qt support, which means that may never happen.  We do not have the manpower or the expertise to add features to Webkit ourselves.

Your best bet is actually to help out with the port to CEF: https://github.com/KDAB/phantomjs-cef

**Comment by Droogans** [comment]
I referenced this issue from an outdated diff: https://github.com/rackerlabs/encore-ui/pull/1641#discussion-diff-62691306
