### ISSUE TITLE
npm update report that phantomjs fails

### ISSUE THREAD

**Issue by khemit** [ariya/phantomjs#14012]
`Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/qn/s827rzbj3cs7pj5d7j1gzlt80000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...

Error requesting archive.
Status: 429
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "server": "nginx/1.6.2",
  "vary": "Accept-Language, Cookie",
  "cache-control": "max-age=900",
  "content-type": "text/plain",
  "strict-transport-security": "max-age=31536000",
  "date": "Tue, 16 Feb 2016 19:41:59 GMT",
  "x-served-by": "app-106",
  "expires": "Tue, 16 Feb 2016 19:41:59 GMT",
  "content-language": "en",
  "etag": "\"62dcd5481fd29816ecc5ae00be2da0b0\"",
  "x-static-version": "3b9e7b99f146",
  "x-render-time": "0.0105710029602",
  "connection": "close",
  "x-request-count": "10",
  "x-frame-options": "SAMEORIGIN",
  "last-modified": "Tue, 16 Feb 2016 19:41:59 GMT",
  "x-version": "3b9e7b99f146",
  "content-length": "46"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ezechiel/fooapp/npm-debug.log`
# logs here:
`4003 verbose lifecycle phantomjs@1.9.18~install: CWD: /Users/ezechiel/nordsysgroup/nordlab/node_modules/phantomjs
4004 silly lifecycle phantomjs@1.9.18~install: Args: [ '-c', 'node install.js' ]
4005 silly lifecycle phantomjs@1.9.18~install: Returned: code: 1  signal: null
4006 info lifecycle phantomjs@1.9.18~install: Failed to exec install script
4007 verbose unlock done using /Users/ezechiel/.npm/_locks/staging-3f107103aefc5ea7.lock for /Users/ezechiel/node_modules/.staging
4008 silly rollbackFailedOptional Starting
4009 silly rollbackFailedOptional Finishing
4010 silly runTopLevelLifecycles Starting
4011 silly runTopLevelLifecycles Finishing
4012 silly install printInstalled
4013 verbose stack Error: phantomjs@1.9.18 install: `node install.js`
4013 verbose stack Exit status 1
4013 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
4013 verbose stack     at emitTwo (events.js:100:13)
4013 verbose stack     at EventEmitter.emit (events.js:185:7)
4013 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
4013 verbose stack     at emitTwo (events.js:100:13)
4013 verbose stack     at ChildProcess.emit (events.js:185:7)
4013 verbose stack     at maybeClose (internal/child_process.js:821:16)
4013 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
4014 verbose pkgid phantomjs@1.9.18
4015 verbose cwd /Users/ezechiel
4016 error Darwin 15.3.0
4017 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
4018 error node v5.5.0
4019 error npm  v3.3.12
4020 error code ELIFECYCLE
4021 error phantomjs@1.9.18 install: `node install.js`
4021 error Exit status 1
4022 error Failed at the phantomjs@1.9.18 install script 'node install.js'.
4022 error Make sure you have the latest version of node.js and npm installed.
4022 error If you do, this is most likely a problem with the phantomjs package,
4022 error not with npm itself.
4022 error Tell the author that this fails on your system:
4022 error     node install.js
4022 error You can get their info via:
4022 error     npm owner ls phantomjs
4022 error There is likely additional logging output above.
4023 verbose exit [ 1, true ]
`

**Comment by Vitallium** [comment]
Thanks a lot for filing this issue! But we don't maintain the NPM package, please fill your issue in the corresponding repository: https://github.com/Medium/phantomjs
