### ISSUE TITLE
Fatal Windows exception, code 0xc0000005

### ISSUE THREAD

**Issue by robin-obrien** [ariya/phantomjs#14018]
I am constantly getting the following error when running CasperJS version 1.1.0-beta5 & PhantomJS 2.1.1. It is happening after around 10 minutes of work.

Please advise, I am stuck for 2 days trying to solve it

Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
http://phantomjs.org/bug-reporting.html and file a bug report.

**Comment by zackw** [comment]
Thank you for your bug report.  Unfortunately, we cannot do anything about it without a reduced, self-contained test case.  Please read our [draft bug reporting guidelines](http://discuss.phantomjs.org/t/draft-troubleshooting-and-reporting-bugs-in-phantomjs/22) and follow the instructions.  If they are unclear, please let us know in the discussion thread on that document.

**Comment by Wislow** [comment]
+1

**Comment by Suhar777777** [comment]
I have Fatal Windows exception, code 0xc0000005 after 20 minutes running CasperJS version 1.1.0-beta5 & PhantomJS 2.1.1.

**Comment by hsHemant** [comment]
I am looping through many 500 URLs at a time using casperjs. I got this issue because memory leak issue with casperjs

I also closed the page 
but still issue is there.

this.then(function () {
                    casper.page.close();
                    casper.newPage();
});

Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

**Comment by Suhar777777** [comment]
Why you used 2 the same code. Casper.page.close() and casper.newPage()? I open the secret))) Then you use casper.newPage() command casper.page.close is alredy launch. If you do not belive me. Open githab casperjs and find this command casper.newPage(), and you will see many interesting things. And finaly i know how low mamory leak and this error but this very expansive for you)))
