### ISSUE TITLE
Date toLocalString() not obeying format rules

### ISSUE THREAD

**Issue by djensenIncomm** [ariya/phantomjs#14010]
Hi,
If I do the following:
-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-
var dateOptions = {
	weekday : "short",
	year : "numeric",
	month : "short",
	day : "numeric",
	hour : "2-digit",
	minute : "2-digit"
};

var date = 1392389160000; // "Fri, Feb 14, 2014, 7:46 AM"
var response = new Date(date).toLocaleString("en-us", dateOptions);
console.log(response);
-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-
The output will be:
February 14, 2014 at 7:46:00 AM MST

But every other browser will be:
Fri, Feb 14, 2014, 7:46 AM

Am I doing something invalid?

Thanks,

David

**Comment by zackw** [comment]
Unfortunately, the version of Webkit we use does not include support for the 'options' argument to Date.toLocaleString.  I don't know if this has yet been implemented in upstream Webkit.  We don't have the manpower or the expertise needed to make this kind of change to Webkit ourselves.  Please discuss it with them: https://www.webkit.org/quality/reporting.html
