### ISSUE TITLE
General "Script error" in console. (version 1.9.18)

### ISSUE THREAD

**Issue by bclover** [ariya/phantomjs#14025]
### Expected behavior
Unit tests should run and either pass / fail.

### Actual behavior
Randomly, when running our tests via Grunt, we sometimes get a Script error in the console. But, then if we try running again, the script error does NOT occur and tests will run and fail / pass properly.  This is an important issue because while we can run tests locally as many times as we want in development, the CI server runs the tests once and then the builds fail as a result.  We then have to manually try to rerun the CI server to make a build pass.

### Enviroment Details
Karma version: 0.13.21
karma-phantomjs-launcher 0.2.1
PhantomJS 1.9.18
grunt-cli v0.1.13
grunt v0.4.5
Mac OS X 10.10.5

### Steps to reproduce the behavior
1. It seems like when we make changes to our tests, or add new tests, the first time we run the tests we get the Script error.  But, then if we try running again, the script error does NOT occur and tests will run and fail or pass properly.  This is an important issue because while we can run tests locally as many times as we want in development, the CI server runs the tests and builds fail as a result.  We then will have to manually try to rerun the CI server to make a build pass.

![image](https://cloud.githubusercontent.com/assets/1993603/13178725/71a1d858-d6ee-11e5-8532-d3fb92f86ad7.png)

**Comment by bclover** [comment]
Also posted in Karma github issues...as we're not sure what the culprit is:
https://github.com/karma-runner/karma/issues/1917

**Comment by zackw** [comment]
PhantomJS 1.9.x is no longer being developed.  The just-released 2.1 includes a much newer Webkit which may have addressed this problem.  Please test 2.1.

If you are able to reproduce the problem with 2.1, then we need a self-contained test case.  Please read our [draft bug reporting guidelines](http://discuss.phantomjs.org/t/draft-troubleshooting-and-reporting-bugs-in-phantomjs/22) and follow those instructions.  If they are unclear, please tell us what's unclear in the discussion thread over there.

We can't do anything more about this bug report, so I am going to close it.  Feel free to reopen it if you determine that the problem still exists in 2.1.
