### ISSUE TITLE
PhantomJs on OSX won't work

### ISSUE THREAD

**Issue by ekkis** [ariya/phantomjs#14026]
I'm running El Capitan (v10.11.3) and recently upgraded from PhantomJs v1.9.8 to 2+.  I've installed via `npm` but the browser doesn't seem to work at all.  it won't even tell me its version:

```
$ phantomjs -v
$
```

here's the log of `npm install -g phantomjs2`:

> npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
> /usr/local/bin/phantomjs -> /usr/local/lib/node_modules/phantomjs2/bin/phantomjs
> 
> > phantomjs2@2.0.2 install /usr/local/lib/node_modules/phantomjs2
> > node install.js
> 
> Looks like an `npm install -g`; unable to check for already installed version.
> Download already available at /var/folders/8q/q2rvsm3d2pj6fwbth49cp3r00000gn/T/phantomjs/phantomjs-2.0.0-macosx.zip
> Extracting zip contents
> [ '/var/folders/8q/q2rvsm3d2pj6fwbth49cp3r00000gn/T/phantomjs/phantomjs-2.0.0-macosx.zip-extract-1455911733460/phantomjs-2.0.0-macosx/bin/phantomjs' ]
> Copying extracted folder /var/folders/8q/q2rvsm3d2pj6fwbth49cp3r00000gn/T/phantomjs/phantomjs-2.0.0-macosx.zip-extract-1455911733460/phantomjs-2.0.0-macosx/bin/phantomjs -> /usr/local/lib/node_modules/phantomjs2/lib/phantom/bin
> Writing location.js file
> Done. Phantomjs binary available at /usr/local/lib/node_modules/phantomjs2/lib/phantom/bin/phantomjs
> /usr/local/lib
> └─┬ phantomjs2@2.0.2 
>   ├── adm-zip@0.4.4 
>   ├─┬ fs-extra@0.23.1 
>   │ ├── graceful-fs@4.1.3 
>   │ ├── jsonfile@2.2.3 
>   │ ├── path-is-absolute@1.0.0 
>   │ └─┬ rimraf@2.5.2 
>   │   └── glob@7.0.0 
>   ├─┬ glob@6.0.4 
>   │ ├─┬ inflight@1.0.4 
>   │ │ └── wrappy@1.0.1 
>   │ ├── inherits@2.0.1 
>   │ ├─┬ minimatch@3.0.0 
>   │ │ └─┬ brace-expansion@1.1.3 
>   │ │   ├── balanced-match@0.3.0 
>   │ │   └── concat-map@0.0.1 
>   │ └── once@1.3.3 
>   ├── kew@0.4.0 
>   ├─┬ mkdirp@0.5.1 
>   │ └── minimist@0.0.8 
>   ├─┬ npmconf@2.1.1 
>   │ ├─┬ config-chain@1.1.10 
>   │ │ └── proto-list@1.2.4 
>   │ ├── ini@1.3.4 
>   │ ├─┬ nopt@3.0.6 
>   │ │ └── abbrev@1.0.7 
>   │ ├─┬ osenv@0.1.3 
>   │ │ ├── os-homedir@1.0.1 
>   │ │ └── os-tmpdir@1.0.1 
>   │ ├── semver@4.3.6 
>   │ └── uid-number@0.0.5 
>   ├── progress@1.1.8 
>   ├─┬ request@2.42.0 
>   │ ├── aws-sign2@0.5.0 
>   │ ├─┬ bl@0.9.5 
>   │ │ └─┬ readable-stream@1.0.33 
>   │ │   ├── core-util-is@1.0.2 
>   │ │   ├── isarray@0.0.1 
>   │ │   └── string_decoder@0.10.31 
>   │ ├── caseless@0.6.0 
>   │ ├── forever-agent@0.5.2 
>   │ ├─┬ form-data@0.1.4 
>   │ │ ├── async@0.9.2 
>   │ │ ├─┬ combined-stream@0.0.7 
>   │ │ │ └── delayed-stream@0.0.5 
>   │ │ └── mime@1.2.11 
>   │ ├─┬ hawk@1.1.1 
>   │ │ ├── boom@0.4.2 
>   │ │ ├── cryptiles@0.2.2 
>   │ │ ├── hoek@0.9.1 
>   │ │ └── sntp@0.2.4 
>   │ ├─┬ http-signature@0.10.1 
>   │ │ ├── asn1@0.1.11 
>   │ │ ├── assert-plus@0.1.5 
>   │ │ └── ctype@0.5.3 
>   │ ├── json-stringify-safe@5.0.1 
>   │ ├── mime-types@1.0.2 
>   │ ├── node-uuid@1.4.7 
>   │ ├── oauth-sign@0.4.0 
>   │ ├── qs@1.2.2 
>   │ ├── stringstream@0.0.5 
>   │ ├── tough-cookie@2.2.1 
>   │ └── tunnel-agent@0.4.2 
>   ├─┬ request-progress@0.3.1 
>   │ └── throttleit@0.0.2 
>   └── which@1.0.9 
>

**Comment by ekkis** [comment]
incidentally, installing it via brew seems to work

**Comment by Vitallium** [comment]
Thanks for reporting! But we don't support npm packages. If you have any troubles with them, please file the issue in the corresponding repo.

The correct ways to install PhantomJS on OS X are with Homebrew or by using our binary from here: https://bitbucket.org/ariya/phantomjs/downloads
