### ISSUE TITLE
requestData.url not properly encoded as utf8

### ISSUE THREAD

**Issue by tzeppy** [ariya/phantomjs#14027]
reproduce:

```
var webPage = require('webpage')
var page = webPage.create();
address = "http://www.google.com/ロリ/index.html";

page.onResourceRequested = function (reqData, netReq) {
    console.log(address);
    console.log(reqData.url);
    netReq.abort()
};

page.open(address, function (status) {
    phantom.exit();
});
```

The first output is the correct utf8 address; but the reqData.url output line seems to be an ascii encoding.

tested with phantoms-2.1.1 release on mac osx 10.11.3

**Comment by zackw** [comment]
Darn it, I thought I *fixed* all of these.

Thank you for the bug report.  We don't need any more information, but I'm afraid it may be some time before anyone gets around to writing a patch.
