### ISSUE TITLE
PhantomJS 2.x uses different time zone than 1.9.x

### ISSUE THREAD

**Issue by tjunghans** [ariya/phantomjs#14023]
Me and my colleagues use PhantomJS heavily for testing and have been using it for quite some time now. I couldn't imagine life without it ;-)

I just bumped into an issue with date creation and time zone offsets. It seems that PhantomJS 2.x handles offsets differently than 1.9.x.

Starting point:

```
phantomjs > var d = new Date(2013, 1, 5, 9, 11, 42, 249);
```

In **PhantomJS 1.9.7 and 1.9.8** ~~I get the expected result (same as Chrome on my machine)~~

**Update: My issue may not have anything to do with PhantomJS 2.x but PhantomJS running in Cygwin vs anywhere else.**

:heavy_check_mark: **Windows, CMD and PhantomJS 1.9.8**:

```
phantomjs > d.toISOString(); // "2013-02-05T08:11:42.249Z"
phantomjs > d.getTimezoneOffset(); // -60
```

:x:**Windows, Cygwin Bash and PhantomJS 1.9.8**

```
phantomjs > d.toISOString(); // "2013-02-05T09:11:42.249Z"
phantomjs > d.getTimezoneOffset(); // 0
```

:heavy_check_mark: **Windows, Google Chrome**:

```
phantomjs > d.toISOString(); // "2013-02-05T08:11:42.249Z"
phantomjs > d.getTimezoneOffset(); // -60
```

:heavy_check_mark: **Unix machine and PhantomJS 1.9.7**:

```
phantomjs > d.toISOString(); // "2013-02-05T08:11:42.249Z"
phantomjs > d.getTimezoneOffset(); // -60
```

In **PhantomJS 2.0.0 and 2.1.1** I get an offset that takes me a day back on Windows with Cygiwn & Bash

:heavy_check_mark: **Windows, CMD and PhantomJS 2.1.1**:

```
phantomjs > d.toISOString(); // "2013-02-05T08:11:42.249Z"
phantomjs > d.getTimezoneOffset(); // -60
phantomjs > d.toString(); // "Tue Feb 05 2013 09:11:42 GMT+0100 (W. Europe Standard Time)"
```

:x:**Windows, Cygwin Bash and PhantomJS 2.1.1**

```
phantomjs > d.toISOString(); // echos "2013-02-04T09:11:42.249Z"
phantomjs > d.getTimezoneOffset() // echos -1440
phantomjs > d.toString(); // "Tue Feb 05 2013 09:11:42 GMT+2400 (W. Europe Daylight Time)"
```

**TODO: Add Unix example**

~~This seems like a bug to me or am I missing something in the documentation? For now I am using 1.9.8 but it would be great to move to 2.x.~~

After further investigating it seems like PhantomJS and Cygwin don't play nice. Further more, PhantomJS 2.x and 1.9.x provide different timezone offsets in Cygwin. This was what led me to first think PhantomJS could be the issue.
## Further Details
- The date and timezone from the `date` command line tool is correct under Cygwin. So `date +"%z"` on Unix and Cygwin echo the same result, which is **+0100** in my case.
- Setting the `TZ` variable has no effect
## Environment details
- Windows 7 Enterprise, SP1, 64bit

Do you have any ideas? My first thought is to update Cygwin.

**Comment by zackw** [comment]
Thank you for the bug report.  Could you please tell us your operating system, and describe the system time zone settings?  We haven't seen this ourselves.

**Comment by tjunghans** [comment]
Hi @zackw, I have added my os and version but there's a bit more information that I need to provide. I'm using cygwin and bash and - after further tests - realisied that Cygwin bash and Windows cmd are returning different results. I will investigate further and provide more information.

**Comment by tjunghans** [comment]
I have been able to work around this issue in two ways:

1. Prepend assigned `TZ` Variable before running phantomjs eg. `TZ=GMT-1 mycommand`. This only works if the timezone does not change during execution.
2. Use IntelliJ's [Embedded Local Terminal](https://www.jetbrains.com/idea/help/working-with-embedded-local-terminal.html)

Maybe anyone else stumbling across this issue will find this helpful.

**Comment by danielcheng825** [comment]
Hi, I encountered a similar issue with cygwin out of the equation.

In a Windows machine running phantomjs in cmd:

When `TZ=UTC`, `new Date().getTimezoneOffset()` returns `-1440` which is wrong.

But in a Linux machine (Ubuntu when I tested):

When `TZ=UTC`, `new Date().getTimezoneOffset()` returns `0` which is correct.
