### ISSUE TITLE
line 1: syntax error: unexpected word (expecting ")")

### ISSUE THREAD

**Issue by alienx2** [ariya/phantomjs#14029]
After extracted from phantomjs-2.1.1-linux-i686.tar.bz2, then tried type "phantomjs --help" then got error like this: `/opt/bin/phantomjs: line 1: syntax error: unexpected word (expecting ")")`

**Comment by ariya** [comment]
Are you sure `/opt/bin/phantomjs` is coming from your extracted tarball?

In addition, what's your machine configuration? Please provide the output of:
```bash
uname -a
cat /proc/meminfo | head -n3
lscpu
```

**Comment by alienx2** [comment]
2.6.22.19 #1 Thu Dec 24 13:56:06 EST 2015 mips GNU/Linux
MemTotal:       239532 kB
MemFree:         70996 kB
Buffers:          4244 kB

lscpu doesnt exist...but its Router Asuswrt Merlin.

**Comment by ariya** [comment]
Just to confirm: this is MIPS? If that is the case, the binary you downloaded won't work (it is designed for 64-bit x86). Due to lack of manpower, PhantomJS doesn't support MIPS (and probably won't support it for the foreseeable future).

**Comment by alienx2** [comment]
correct is MIPS cpu architect. aww i see.. i was looking for execute php code with redirect. that's why i found this phantomJS like i dont need browser =/

**Comment by ariya** [comment]
Closing this as Not supported. Perhaps in the future there will be a MIPS version of PhantomJS.
