### ISSUE TITLE
phantomjs process takes up to 4 seconds to end after phantom.exit()

### ISSUE THREAD

**Issue by dadza** [ariya/phantomjs#14033]
I'm using PhantomJS 2.1.1 under OS X El Capitan (10.11.3).  The process takes about 3-4 for seconds to end after phantom.exit() is being called.  This happens most of the time, but not always.

I tested with the trivial Hello world example from https://github.com/ariya/phantomjs/blob/master/examples/hello.js

The timestamps look like this:

```
lchirita@MacBook-Pro-Lucian:~/tmp/phantomjs$ (phantomjs hello.js && echo done ) |ts "%H:%M:%.S"
16:08:33.748764 Hello, world!
16:08:37.579262 done
```

Notice the 4 second delay between the console.log line, which is right before phantom.exit(), and the "echo done" line which is written after the process has ended.

2.0.0 is fine, the process ends almost immediately after exit().  Like this:

```
lchirita@MacBook-Pro-Lucian:~/tmp/phantomjs$ (phantomjs hello.js && echo done ) |ts "%H:%M:%.S"
16:11:43.461184 Hello, world!
16:11:43.481345 done
```

**Comment by jmullo** [comment]
I have the same behaviour in Windows 7 and PhantomJS 2.1.1. Maybe even longer than 4 seconds.

If I remember correctly, PhantonJS 1.9.x didn't have the delay.

**Comment by raido** [comment]
I am experiencing 5 seconds delay with the exit() call. 

OS X 10.12.2
PhantomJS 2.1.1

**Comment by aaugustin** [comment]
I'm seeing this as well on macOS Sierra with PhantomJS 2.1.1

```

$ phantomjs -v
2.1.1

$ wget https://github.com/ariya/phantomjs/raw/master/examples/rasterize.js
# ... snip ...
2017-03-16 11:21:56 (28.9 MB/s) - ‘rasterize.js’ saved [2241/2241]

$ echo "<html><title>Hello</title><body>World</body></html>" > test.html

$ time phantomjs rasterize.js test.html test.pdf
phantomjs rasterize.js test.html test.pdf  0.60s user 0.29s system 17% cpu 5.056 total

$ # turn wifi off

$ time phantomjs rasterize.js test.html test.pdf
phantomjs rasterize.js test.html test.pdf  0.65s user 0.26s system 91% cpu 0.988 total

$ # turn wifi back on

$ time phantomjs rasterize.js test.html test.pdf
phantomjs rasterize.js test.html test.pdf  0.65s user 0.29s system 18% cpu 5.182 total
```

**Comment by aaugustin** [comment]
I captured a dtruss trace, it's about 5000 lines long and I failed to spot a likely culprit.

**Comment by aaugustin** [comment]
To be clear -- the delay happens only when I have an active network connection.

**Comment by raido** [comment]
I can confirm that network connection makes a difference. 😲

**Comment by aaugustin** [comment]
At first I suspected a DNS resolution timeout but I failed to confirm this guess: every domain name phantomjs would have a reason to connect to resolves instantly on my machine.

**Comment by sajal50** [comment]
Any update on this?

**Comment by computermathman** [comment]
I am also experiencing this. Any new developments.
