### ISSUE TITLE
Segmentation fault: 11 on basic page.open

### ISSUE THREAD

**Issue by bhartard** [ariya/phantomjs#14036]
Mac OS 10.10.5
PhantomJS binary
v2.1.1

test.js:

> "use strict";
> var webPage = require('webpage');
> var page = webPage.create();
> 
> page.open('http://www.viennacookiecompany.com/', function(status) {
>  console.log('Status: ' + status);
> });

Result:

> ./phantomjs test.js
> PhantomJS has crashed. Please read the bug reporting guide at
> http://phantomjs.org/bug-reporting.html and file a bug report.
> Segmentation fault: 11

**Comment by mull** [comment]
FYI it helps I just ran into this as well. If you installed via brew it might help to reinstall. I couldn't use the cask version at all.

```
brew uninstall phantomjs
brew cask uninstall phantomjs
brew install phantomjs
```
