### ISSUE TITLE
Memory exhausted running phantom on Windows

### ISSUE THREAD

**Issue by robin-obrien** [ariya/phantomjs#14038]
I am running phantom on Windows and after 10 minutes the program crashes on memory exhausted, even though the used physical memory reached only 25%, Is there any feature in the OS to limit the cmd memory usage? is it a bug?

**Comment by BerndErnst** [comment]
Bump

**Comment by eugene-manuilov** [comment]
Bump

**Comment by robin-obrien** [comment]
@ariya Can you please help?

**Comment by mepard** [comment]
Do you have loadImages set to false? See https://github.com/ariya/phantomjs/issues/12903

**Comment by robin-obrien** [comment]
Yes I do, also the plugins

**Comment by mepard** [comment]
A fix is in the works. https://github.com/Vitallium/qtwebkit/pull/8

**Comment by robin-obrien** [comment]
OK, so if I set it to true then there shouldn't be a leak on Windows?

**Comment by mepard** [comment]
Assuming it's the same bug, there shouldn't be a leak. There's also a work-around discussed in #12903.

**Comment by BerndErnst** [comment]
thx @mepard
LoadImage was set to false too.
I will switch it to on.

**Comment by mepard** [comment]
I hit a situation that caused Memory Exhausted even with LoadImages set to false and posted my solution in #11390.

This bug should probably be closed in favor of #11390.
