### ISSUE TITLE
Local PhantoJS Broken?

### ISSUE THREAD

**Issue by nVVEBd** [ariya/phantomjs#14039]
I'm trying to run Jasmine specs that I've written.

I'm using grunt-contrib-jasmine to get the grunt workflow going and for headless testing.

`
Running "jasmine:postgres" (jasmine) task
Testing jasmine specs via PhantomJS

/usr/local/x/y/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: /usr/local/x/y/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: Kann die Datei nicht ausführen (Translated: Can't run the file). 0 [ '/usr/local/x/y/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: /usr/local/x/y/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: Kann die Datei nicht ausführen.' ]
Warning: PhantomJS exited unexpectedly with exit code 126. Use --force to continue.
`

I took a look at the file permissions and they were 755 & changed them to be 777 just to try, but failed again.

When I tried `phantomjs --version` the same error is present.

I can't find any info why this happens so any help would be very much appritiated.

**Comment by Vitallium** [comment]
Operating system?

**Comment by nVVEBd** [comment]
I'm running CentOS Linux release 7.2.1511 (Core) -> Vagrant Machine.

And I have permission errors when trying to install it from npm. I have a root account access.

**Comment by ariya** [comment]
Run `file` on the executable and see what the result is. There is a likelihood that the executable is not correct.

In all cases, we don't control the installation via npm. You need to bring up the issue at https://github.com/Medium/phantomjs.
