### ISSUE TITLE
Polymer Support?

### ISSUE THREAD

**Issue by wogsland** [ariya/phantomjs#14045]
I know this was brought up a couple years ago [elsewhere](https://github.com/Polymer/polymer/issues/724), but I am curious where this stands on the current development roadmap. When will PhantomJS support Web Components?

**Comment by zackw** [comment]
Only when we are able to upgrade to a version of Webkit (or, conceivably, a different browser engine - Qt/Webkit's future is in some doubt) that supports this feature.  If [caniuse](http://caniuse.com/#search=web%20components) is to be believed, there currently *is* no released version of Webkit that supports this, so it's gonna be Quite Some Time.

This is also the answer to any question of the form "when will PhantomJS support [web feature X]?"  We do not have either the manpower or the expertise to do much of anything at all to Webkit ourselves.

**Comment by ariya** [comment]
In addition to that, @wogsland did you try to run PhantomJS 2 on your test case? I'm not surprised if it supports some parts of Web Components. In all cases, it's better to discuss this in the forum or mailing-list.

**Comment by wogsland** [comment]
@ariya I did. It only loads the footer. I'll search for the forum. Thanks!

**Comment by eob** [comment]
FWIW, Just want to +1 this feature request!

**Comment by rafalradomski** [comment]
+1
