### ISSUE TITLE
Crash Reporting documentation is out of date

### ISSUE THREAD

**Issue by alex-napofearth** [ariya/phantomjs#14049]
Hi, I'm trying to investigate a crash that consistently occurs when I run my project's unit test suite, with the following configurations:

phantomjs v 2.1.1
on Mac OS X 10.10.5, installed with homebrew
and on Ubuntu 12.04.5 LTS (running on the same machine via VirtualBox + Vagrant), installed from the binary available here: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2, linked from http://phantomjs.org/download.html

When I run my test suite, it gets halfway through, then crashes. On Ubuntu, I get only a `Segmentation fault` error. On OS X, I see:

    PhantomJS has crashed. Please read the bug reporting guide at
    <http://phantomjs.org/bug-reporting.html> and file a bug report.

Note that is the wrong address, the current one seems to be http://phantomjs.org/crash-reporting.html

I'm trying to build 2.1.1 with debug symbols enabled so that I can generate a proper stack trace, since one isn't listed in the error message, and nothing appears in my `/tmp` directory, but the build instructions on that page are also out of date.

The "Obtaining a stack trace from gdb" section refers to `./build.sh`, but the only build script in 2.1.1 is `./build.py`.

It says to build with debugging symbols enabled with the following command:

    Build with debugging symbols enabled:
    CFLAGS=-g CXXFLAGS=-g ./build.sh --qt-config '-webkit-debug' --qmake-args "QMAKE_CFLAGS=-g QMAKE_CXXFLAGS=-g"

If I do that, but substitute build.sh with build.py, I get the following error:

    usage: build.py [-h] [-r] [-d] [-j JOBS] [-c] [-n] [-s]
                    [--qmake-args QMAKE_ARGS]
                    [--webkit-qmake-args WEBKIT_QMAKE_ARGS]
                    [--phantomjs-qmake-args PHANTOMJS_QMAKE_ARGS]
                    [--qt-config QT_CONFIG] [--git-clean-qtbase]
                    [--git-clean-qtwebkit] [--skip-qtbase]
                    [--skip-configure-qtbase] [--skip-qtwebkit]
                    [--skip-configure-qtwebkit] [--skip-git]
    build.py: error: argument --qt-config: expected one argument

Note the command does match this format, but I needed to use equals signs in order for it to parse the arguments properly. I'm running this via Python 2.7.3, which has argparse version 1.1.

    CFLAGS=-g CXXFLAGS=-g ./build.py --qt-config="-webkit-debug" --qmake-args="QMAKE_CFLAGS=-g QMAKE_CXXFLAGS=-g"

The above command gives me a new error when trying to build qt-base:

    configuring Qt Base, please wait...
    Executing in /tmp/phantomjs/src/qt/qtbase: /tmp/phantomjs/src/qt/qtbase/configure -static -opensource -confirm-license -prefix /tmp/phantomjs/src/qt/qtbase -qt-zlib -qt-libpng -qt-libjpeg -qt-pcre -nomake examples -nomake tools -nomake tests -no-qml-debug -no-dbus -no-opengl -no-audio-backend -D QT_NO_GRAPHICSVIEW -D QT_NO_GRAPHICSEFFECT -D QT_NO_STYLESHEET -D QT_NO_STYLE_CDE -D QT_NO_STYLE_CLEANLOOKS -D QT_NO_STYLE_MOTIF -D QT_NO_STYLE_PLASTIQUE -D QT_NO_PRINTPREVIEWDIALOG -qpa phantom -openssl -openssl-linked -no-openvg -no-eglfs -no-egl -no-glib -no-gtkstyle -no-cups -no-sm -no-xinerama -no-xkb -no-xcb -no-kms -no-linuxfb -no-directfb -no-mtdev -no-libudev -no-evdev -no-pulseaudio -no-alsa -no-feature-PRINTPREVIEWWIDGET -fontconfig -icu -webkit-debug -release
    -webkit-debug: invalid command-line switch

    ERROR: Failed to build PhantomJS! Configuration of Qt Base failed.

Does anyone know the proper steps to build phantomjs 2.1.1 with debug symbols enabled?

**Comment by mepard** [comment]
Here's what I use on OS X. You should get symbols and a normal OS X crash report even with --release.

`./build.py --confirm --release > ../buildout-2.2.0-release.txt 2>&1`
or
`./build.py --confirm --debug > ../buildout-2.2.0-debug.txt 2>&1`

If you switch between debug and release, you need to clean the qt submodules:

`./build.py --confirm --release --git-clean-qtbase --git-clean-qtwebkit > ../buildout-2.2.0-release.txt 2>&1`
or
`./build.py --confirm --debug --git-clean-qtbase --git-clean-qtwebkit > ../buildout-2.2.0-debug.txt 2>&1`

**Comment by zackw** [comment]
We don't actually want a stack trace anymore.  They are almost always completely useless, even with symbols.  Please read http://discuss.phantomjs.org/t/draft-troubleshooting-and-reporting-bugs-in-phantomjs/22 which describes what we do want (a self-contained test case).  That's going to replace the bug-reporting document you found once it gets a little more polished.

You might have found *two* bugs; you should have received the "PhantomJS has crashed..." message on both Ubuntu and OSX.
