### ISSUE TITLE
Simple OPEN doesnot work

### ISSUE THREAD

**Issue by lohithcodes** [ariya/phantomjs#14041]
Hi Team. for this perticular page  "http://fit.bncollege.com/webapp/wcs/stores/servlet/TBWizardView?catalogId=10001&langId=-1&storeId=23551"  open doesnot work.  Or in other words I think its getting blocked. 

The same page works well with   WebDriver + Firefox  and also with Chrome.  can you please help me understanding the gap, If it needs a code change in phantomJS I'm willing to do and contribute.

var page = require('webpage').create();

page.open('http://fit.bncollege.com/webapp/wcs/stores/servlet/TBWizardView?catalogId=10001&langId=-1&storeId=23551', settings, function(status) {
  console.log("Status: " + status);
  if(status === "success") {
    page.render('example.png');
  }
  phantom.exit();
});

**Comment by lohithcodes** [comment]
I also see that phantomJs Crashes on opening this site

var page = require('webpage').create();

page.open('http://snowplay.com/', function(status) {
  console.log("Status: " + status);
  if(status === "success") {
    page.render('example.png');
  }
  phantom.exit();
});

_____________________________________________

and the original problem 


var page = require('webpage').create();

page.open('http://fit.bncollege.com/webapp/wcs/stores/servlet/TBWizardView?catalogId=10001&langId=-1&storeId=23551/", function(status) {
  console.log("Status: " + status);
  if(status === "success") {
    page.render('example.png');
  }
  phantom.exit();
});

**Comment by Vitallium** [comment]
Thanks a lot for filing this issue! But unfortunately I can't reproduce your problem. Please fill any additional information that could help up to solve your issue. You should write following information:

* operating system
* PhantomJS version
* how did you installed it?

**Comment by lohithcodes** [comment]
Hi Vitallum thanks for the response, 
are you able to see the image in the example.png that the above code generates ? 
I see an empty image where as on firefox you actually see a page.

I tried on both  Phantomjs-2.1.1  and 1.9.8
