### ISSUE TITLE
NETWORK_ERR: XMLHttpRequest Exception 101

### ISSUE THREAD

**Issue by melissanoelle** [ariya/phantomjs#14040]
I did find this: https://github.com/ariya/phantomjs/issues/10985 and I went through the entire thing but it was not able to help me.

I'm using PhantomJS with CasperJS, and attempting to make a GET request for a JSON object. On the `.send()` method, I'm getting the `NETWORK_ERR: XMLHttpRequest Exception 101` error.  After digging through this, I believe that the issue is most likely with PhantomJS and not CasperJS.

###### PhantomJS version:
1.8.2

###### How to reproduce:
1. Using CasperJS and this file: https://gist.github.com/melissanoelle/704796109351ed828abe
2. Run `casperjs --ssl-protocol=tlsv1 --ignore-ssl-errors=true --cookies-file=/tmp/cookies.txt --web-security=no test home_page.js`
3. See error:

````
A-0666:front-end-functional-tests madamaitis$ casperjs --ssl-protocol=tlsv1 --ignore-ssl-errors=true --cookies-file=/tmp/cookies.txt --web-security=no test home_page.js 
2016-02-24 14:09:06.733 phantomjs[51669:19647671] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
Test file: home_page.js                                                         
# Home page body tests.
XMLHttpRequest cannot load https://www.limelight.com/get_strings?page_name=home_page. Origin file:// is not allowed by Access-Control-Allow-Origin.
FAIL Error: NETWORK_ERR: XMLHttpRequest Exception 101
#    type: uncaughtError
#    file: home_page.js:90
#    error: {"line":90,"sourceId":252873456,"sourceURL":"home_page.js","stack":"Error: NETWORK_ERR: XMLHttpRequest Exception 101\n    at home_page.js:90\n    at /usr/local/Cellar/casperjs/1.1-beta3/libexec/modules/tester.js:1064\n    at /usr/local/Cellar/casperjs/1.1-beta3/libexec/bin/bootstrap.js:60\n    at begin (/usr/local/Cellar/casperjs/1.1-beta3/libexec/modules/tester.js:1093)\n    at home_page.js:141","stackArray":[{"sourceURL":"home_page.js","line":90},{"sourceURL":"/usr/local/Cellar/casperjs/1.1-beta3/libexec/modules/tester.js","line":1064},{"sourceURL":"/usr/local/Cellar/casperjs/1.1-beta3/libexec/bin/bootstrap.js","line":60},{"function":"begin","sourceURL":"/usr/local/Cellar/casperjs/1.1-beta3/libexec/modules/tester.js","line":1093},{"sourceURL":"home_page.js","line":141}],"code":101,"message":"NETWORK_ERR: XMLHttpRequest Exception 101","name":"NETWORK_ERR"}
#    stack: not provided
FAIL 1 test executed in 0.134s, 0 passed, 1 failed, 0 dubious, 0 skipped.       

Details for the 1 failed test:

In home_page.js:90
  Home page body tests.
    uncaughtError: Error: NETWORK_ERR: XMLHttpRequest Exception 101

````

CasperJS's documentation said to add the flag `--web-security=no`, and that this error would be solved. I looked through CasperJS's source code, and found that it was just piping that along directly to PhantomJS. So, then I looked through PhantomJS's source code for where the `web-security` flag is used and found this:

https://github.com/ariya/phantomjs/blob/b483dd673a1ca589ff10c5f73dfea1e43bfa3225/test/ghostdriver-test/java/src/test/java/ghostdriver/BaseTest.java#L103-L108

Java is certainly not my strongest language, and I'm certainly not very familiar with the codebase for this, but it looks as if the ability to turn off web security has been... commented out?

However, there's also a C++ file here:

https://github.com/ariya/phantomjs/blob/3e8e04e3d6965f73f85dcf0fab7da82a43da689b/src/config.cpp#L804-L806

That seems to allow it to be set... however it sets a variable called `m_webSecurityEnabled` that based on a search of the repo I don't see being used?

It was at this point that I decided that perhaps this would be better handled by asking someone more familiar with this project for some help. If this is actually an error with CasperJS, I'm happy to go open this up over there. It is sometimes difficult to be completely sure where to open an issue at. Thanks in advance.

###### Expected output
That the `XMLHttpRequest` object can retrieve the data at the specified endpoint without creating the `NETWORK_ERR: XMLHttpRequest Exception 101` error.

###### My OS
Mac 10.10.3

###### How I installed PhantomJS
via Homebrew

**Comment by melissanoelle** [comment]
Is this something that I should be opening over at CasperJS? How can I get some attention on this issue here?

**Comment by mickaelandrieu** [comment]
Hi @melissanoelle,

thanks for this complete report. As CasperJS is mostly a wrapper around phantomJS or SlimerJS, I think it's an phantomJS issue.

For instance, you should try to use SlimerJS instead of phantomJS: if it works as expected, it's not a CasperJS issue ^^

Mickaël

**Comment by Vitallium** [comment]
Thanks a lot for filing this issue! But could you please try again with the latest PhantomJS?

I see that you used 2.0.0, but this version doesn't have a fix for your issue (https://github.com/ariya/phantomjs/commit/d938eddaf2039cc4d8a90704f736129edb8e1260)
It was landed in later versions.

Thank you!

**Comment by melissanoelle** [comment]
@mickaelandrieu -- I attempted to install and use Slimer, but it goes up to FF version 38 and I have 44 installed. After messing around with it for a few hours I decided to drop it.

@Vitallium -- I'm having trouble installing the latest version from source and then using it in the command line. I followed the instructions here: https://github.com/ariya/phantomjs/tree/master/deploy but when I attempted to run the `make clean`... bit, it failed on me:

````
A-0666:phantomjs madamaitis$ make clean && cd src/qt && make clean && cd ../..
cd src/ && ( test -e Makefile.phantomjs || /Users/madamaitis/repos/phantomjs/src/qt/qtbase/bin/qmake /Users/madamaitis/repos/phantomjs/src/phantomjs.pro -o Makefile.phantomjs ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.phantomjs clean
rm -f qrc_phantomjs.cpp qrc_ghostdriver.cpp
rm -f moc_phantom.cpp moc_callback.cpp moc_webpage.cpp moc_webserver.cpp moc_networkaccessmanager.cpp moc_cookiejar.cpp moc_filesystem.cpp moc_system.cpp moc_env.cpp moc_terminal.cpp moc_config.cpp moc_childprocess.cpp moc_repl.cpp moc_qcommandline.cpp
rm -f webpage.moc
rm -f phantom.o callback.o webpage.o webserver.o main.o utils.o networkaccessmanager.o cookiejar.o filesystem.o system.o env.o terminal.o encoding.o config.o childprocess.o repl.o crashdump.o mongoose.o linenoise.o utf8.o qcommandline.o phantomjs_plugin_import.o qrc_phantomjs.o qrc_ghostdriver.o moc_phantom.o moc_callback.o moc_webpage.o moc_webserver.o moc_networkaccessmanager.o moc_cookiejar.o moc_filesystem.o moc_system.o moc_env.o moc_terminal.o moc_config.o moc_childprocess.o moc_repl.o moc_qcommandline.o
rm -f *~ core *.core
make: *** No rule to make target `clean'.  Stop.
````

I figured "well, I haven't previously built this, so it's probably ok" so I moved on to verifying the version, but the terminal didn't recognize phantomjs and so failed when I attempted to run `phantomjs --version`. (`/usr/local/bin/phantomjs` doesn't exist)

I also tried the Mac zip here: http://phantomjs.org/download.html but I wasn't sure how to run it with CasperJS because all it did was open an terminal window with a `phantomjs>` prompt.

What else can I try/is there a different set of directions I should be following?

Alternatively, is the person who packages this for Homebrew still active? I don't know anything about packaging for Homebrew, and the highest version it has is 2.0.0.

**Comment by Vitallium** [comment]
@melissanoelle you can use Homebrew. We actively working with Homebrew maintainers. It contains the latest release - 2.1.1. Try to do `brew update` first.

**Comment by Vitallium** [comment]
@istr so no error 101, right?

**Comment by Vitallium** [comment]
@istr thank you!

**Comment by melissanoelle** [comment]
If I'm able to do `phantomjs -v` in the command line and get back `2.1.1`, and then I run the tests with `casperjs --ssl-protocol=tlsv1 --ignore-ssl-errors=true --cookies-file=/tmp/cookies.txt --web-security=no test home_page.js` is it possible that it might still be defaulting to 2.0.0 somewhere or somehow?

Using what @istr tried, I did this:

````
A-0666:front-end-functional-tests madamaitis$ ENGINE_EXECUTABLE=~/usr/local/bin/phantomjs-2.1.1 /usr/local/bin/casperjs --ssl-protocol=tlsv1 --ignore-ssl-errors=true --cookies-file=/tmp/cookies.txt --web-security=no test home_page.js
2016-03-01 11:06:16.717 phantomjs[3256:23010188] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
Test file: home_page.js                                                         
# Home page body tests.
XMLHttpRequest cannot load https://www.limelight.com/get_strings?page_name=home_page. Origin file:// is not allowed by Access-Control-Allow-Origin.
FAIL Error: NETWORK_ERR: XMLHttpRequest Exception 101
#    type: uncaughtError
#    file: home_page.js:90
#    error: {"line":90,"sourceId":251710192,"sourceURL":"home_page.js","stack":"Error: NETWORK_ERR: XMLHttpRequest Exception 101\n    at home_page.js:90\n    at /usr/local/Cellar/casperjs/1.1-beta3/libexec/modules/tester.js:1064\n    at /usr/local/Cellar/casperjs/1.1-beta3/libexec/bin/bootstrap.js:60\n    at begin (/usr/local/Cellar/casperjs/1.1-beta3/libexec/modules/tester.js:1093)\n    at home_page.js:141","stackArray":[{"sourceURL":"home_page.js","line":90},{"sourceURL":"/usr/local/Cellar/casperjs/1.1-beta3/libexec/modules/tester.js","line":1064},{"sourceURL":"/usr/local/Cellar/casperjs/1.1-beta3/libexec/bin/bootstrap.js","line":60},{"function":"begin","sourceURL":"/usr/local/Cellar/casperjs/1.1-beta3/libexec/modules/tester.js","line":1093},{"sourceURL":"home_page.js","line":141}],"code":101,"message":"NETWORK_ERR: XMLHttpRequest Exception 101","name":"NETWORK_ERR"}
#    stack: not provided
FAIL 1 test executed in 0.239s, 0 passed, 1 failed, 0 dubious, 0 skipped.       

Details for the 1 failed test:

In home_page.js:90
  Home page body tests.
    uncaughtError: Error: NETWORK_ERR: XMLHttpRequest Exception 101
````

@mickaelandrieu -- would CasperJS default to using a different version of PhantomJS or something?

**Comment by istr** [comment]
Your environment variable ```ENGINE_EXECUTABLE=~/usr/local/bin/phantomjs-2.1.1``` looks fishy.
Do you really have ```/usr/local...``` relative to your home?

A simple invocation of ```casperjs``` without any arguments will give you the full information, e.g.

```
$ ENGINE_EXECUTABLE=~/bin/phantomjs-2.0.0 bin/casperjs
CasperJS version 1.1.0-beta4 at {censored}, using phantomjs version 2.0.0
Usage: casperjs [options] script.[js|coffee] [script argument [script argument ...]]
       casperjs [options] test [test path [test path ...]]
       casperjs [options] selftest
       casperjs [options] __selfcommandtest

Options:

--verbose   Prints log messages to the console
--log-level Sets logging level
--help      Prints this help
--version   Prints out CasperJS version
--engine=name Use the given engine. Current supported engine: phantomjs and slimerjs

Read the docs http://docs.casperjs.org/
```

```
$ bin/casperjs
CasperJS version 1.1.0-beta4 at {censored}, using phantomjs version 1.9.6
Usage: casperjs [options] script.[js|coffee] [script argument [script argument ...]]
       casperjs [options] test [test path [test path ...]]
       casperjs [options] selftest
       casperjs [options] __selfcommandtest

Options:

--verbose   Prints log messages to the console
--log-level Sets logging level
--help      Prints this help
--version   Prints out CasperJS version
--engine=name Use the given engine. Current supported engine: phantomjs and slimerjs

Read the docs http://docs.casperjs.org/
```

**Comment by melissanoelle** [comment]
Ah, good catch.

Thanks, I'm getting a different error now.

And, I'd like to point out here that after inspecting the output of `casperjs --help` it shows that it's been on PhantomJS of 1.8.2 this entire time even though I have 2.1.1 installed on my system, so the above error (now edited) can only be applicable for 1.8.2.

Closing this, thanks guys. I appreciate the help.
