### ISSUE TITLE
Strict mode violation Octal Literal in pre-build

### ISSUE THREAD

**Issue by SamMorrowDrums** [ariya/phantomjs#14058]
Using version 2.1.1

```
node_modules/phantomjs-prebuilt/lib/phantomjs.js:53
    var mode = st.mode | 0555;
                         ^^^^

SyntaxError: Octal literals are not allowed in strict mode.
```

**Comment by SamMorrowDrums** [comment]
Can easily be fixed by making everything a string

```
    var mode = st.mode | "0555";
    if (mode.toString() !== st.mode.toString()) {
      fs.chmodSync(exports.path, mode);
    }
```

**Comment by ariya** [comment]
Since that is the code from phantomjs-prebuilt npm package, you have to bring it up at https://github.com/Medium/phantomjs as we don't own/control that module.

**Comment by zackw** [comment]
Also, I don't understand what `mode | "0555"` actually does, but it is *not* what the code is trying to do.  Observe:

```
function a(mode) { return mode | 0555; }
function b(mode) { "use strict"; return mode | "0555"; }
console.log(a(0644) + " " + b(0644))
493 943
```

**Comment by SamMorrowDrums** [comment]
Probably should have just changed it to `mode | parseInt("0555", 8)` anyway I'll mention it there.

**Comment by SamMorrowDrums** [comment]
FYI I've created issue in correct repo now https://github.com/Medium/phantomjs/issues/483

**Comment by SamMorrowDrums** [comment]
And thanks @zackw for pointing that out. Total brain fart, but now I've contributed correct PR to the right repo. I'd probably have shamefully let the issue die otherwise.
