### ISSUE TITLE
Cannot open local relative URL that contains query string

### ISSUE THREAD

**Issue by ArchCodeMonkey** [ariya/phantomjs#14050]
I use PhantomJS as part of a build chain that runs automated QUnit tests of my JavaScript code. After upgrading recently from PhantomJS 1.9.8 to PhantomJS 2.1.1 the process started failing when PhantomJS was attempting to launch the test html file. Here is a screenshot of the Jenkins build console output.

![build failure](https://cloud.githubusercontent.com/assets/11328425/13371749/adddedd6-dd81-11e5-9553-22cc36346984.png)

After some investigation I have tracked the issue to the `noGlobals` query parameter which tells QUnit to check for global namespace pollution. When I turned this option off PhantomJS was able to load the test html and the build would continue normally.

I have put together a very simple test file that reproduces the error and provides some debugging output.

``` javascript
console.log("Testing parameter issue");

//var TEST_URL = 'test.html';
var TEST_URL = 'test.html?param=test';
//var TEST_URL = 'file:///g://test//test.html?param=test';

var page = require('webpage').create();

page.onResourceRequested = function(requestData, networkRequest) {
  console.log('Request (#' + requestData.id + '): ' + JSON.stringify(requestData));
};

page.onResourceError = function(resourceError) {
   console.log('Unable to load resource (#' + resourceError.id + 'URL:' + resourceError.url + ')');
   console.log('Error code: ' + resourceError.errorCode + '. Description: ' + resourceError.errorString);
};

page.open(TEST_URL, function(status) {
  var text = page.evaluate(function() {
    return document.title;
  });

   if ( status === 'success' )
   {
      console.log('\nReturned text is:\n' + text);
   }

   phantom.exit();
});
```

``` html
<html>
<head>
<title>Test Title</title>
</head>
<body>
<h1>Test Heading</h1>
</body>
</html>
```

When loading a URL that contains a query string it produces the following output:

![phantom211 - relative query](https://cloud.githubusercontent.com/assets/11328425/13371815/2abc508a-dd83-11e5-90e5-a8804e77192e.png)

It can be seen from the debugging output that the `?` in the query string has been encoded and then a second copy of the query string has been appended.
I ran the same test on PhantomJS 1.9.8 and the issue did not occur so I believe this is a regression introduced somewhere in version 2 onwards.

![phantom198 - relative query](https://cloud.githubusercontent.com/assets/11328425/13371832/9c3c8a68-dd83-11e5-8dcd-9062d8de09ac.png)

I also determined that if an absolute file path is used then the issue does not occur in PhantomJS 2.1.1.

![phantom211 - absolute query](https://cloud.githubusercontent.com/assets/11328425/13371842/bed495c0-dd83-11e5-83e0-4309e1b6c0c2.png)

I have investigated the PhantomJS source code and I believe the issue happening in `webpage.cpp` where the URL is explicitly turned into a `file:///` based path if no protocol is specified.

``` cpp
void WebPage::openUrl(const QString& address, const QVariant& op, const QVariantMap& settings)
{

. . .

// Assume local file if scheme is empty
if (url.scheme().isEmpty()) {
   url.setPath(QFileInfo(url.toString()).absoluteFilePath().prepend("/"));
   url.setScheme("file");
}

request.setUrl(url);
```

I think the `url.toString()` is causing the `?` to be encoded as a part of adding the entire query string to the file path. Then when the URL is reassembled by the `request` object an additional query string is appended.

I'm not set up for C++ compilation on my PC so I can't test this but I think changing line 948 to the following might fix the problem given that the query string should not actually be required to determine the absolute path of the file on the file system.

``` cpp
if (url.scheme().isEmpty()) {
   url.setPath(QFileInfo(url.toString(QUrl::RemoveQuery)).absoluteFilePath().prepend("/"));
   url.setScheme("file");
}
```

**Comment by khelmar** [comment]
I'm seeing the same issue.

**Comment by starwed** [comment]
I'm also seeing this issue (with grunt, qunit and the `noglobals` flag:  "phantomjs unable to load".)

Mostly leaving this comment since the initial post used an image, which made it hard to find in search results.  :)

**Comment by alexsoble** [comment]
Seeing the same issue here.
