### ISSUE TITLE
Array.prototype.find TypeError: 'undefined' is not a function

### ISSUE THREAD

**Issue by vfil** [ariya/phantomjs#14054]

**Comment by crissdev** [comment]
Same here...Testing with phantomjs is not cool... :disappointed:

**Comment by chuckplantain** [comment]
https://github.com/ptim/phantomjs-polyfill-find solves this by using mdn recommendated polyfill

**Comment by crissdev** [comment]
Thanks. I might try that in the future, but I already switched to using Firefox. I wonder, however, why such functionality isn't in PhantomJS though.

**Comment by ariya** [comment]
@crissdev Simple reason: it takes a lot of time and effort to update to the latest WebKit and we're a very small team.

**Comment by danidee10** [comment]
Hi @ariya any ETA on when it's going to be supported?
