### ISSUE TITLE
Checkbox check/frame rendering seems off

### ISSUE THREAD

**Issue by szakharchenko** [ariya/phantomjs#14051]
Using PhantomJS 2.1.1 (on Debian Sid; same issue with PhantomJS 2.0.0 on FreeBSD 10.2-RELEASE), examples/rasterize.js and e.g. the following HTML:

```
<!DOCTYPE html>
<html>
<head>
  <title>Child frame</title>
</head>
<body>
  <h1>This is a non-scrolling frame test</h1>
  <input type='checkbox' name='checkbox' checked='checked'/>
</body>
</html>
```

I get the following results, in which the checkbox frame is too small to fit the check:

[checkbox.pdf](https://github.com/ariya/phantomjs/files/149273/checkbox.pdf)

![checkbox](https://cloud.githubusercontent.com/assets/8455469/13372122/4907885e-dd4a-11e5-9098-1e2154359769.png)

**Comment by piran-e2x** [comment]
+1
