### ISSUE TITLE
ReferenceError: Strict mode forbids implicit creation of global property 'service'

### ISSUE THREAD

**Issue by micschk** [ariya/phantomjs#14053]
Strict mode causes bug in postserver.js example

**Comment by art-solopov** [comment]
I think I've encountered a [similar error.](http://stackoverflow.com/questions/37173611/browserify-shim-poltergeist-phantom-js-strict-mode-issues) It looks like PhantomJS behaving as per strict mode, but neither Firefox nor Chrome report any errors.
