### ISSUE TITLE
Exported PDF different in local and live environments

### ISSUE THREAD

**Issue by ninjarhino** [ariya/phantomjs#14055]
We currently have two environments - live and local. They are running the exact same code from the exact same branch. We're using PhantomJS to create a PDF of some Google Charts. The PDF output we're seeing looks fine on all our local environments however it's displaying incorrectly on the live environment with the charts being small and font sizes incorrect.

So far we've confirmed that the code is exactly the same, we've checked that the versions of Phantom being used match up, ensured that there are no JS errors and all files are being served correctly.

Is anyone experiencing this issue or aware of any potential conflicts/problems that could be causing this?

**Comment by Vitallium** [comment]
Thanks a lot for filing this issue!

Could you please describe your environments? Are they completely the same?

**Comment by yanivlllev** [comment]
+ 1 

I'm having the same issue here...  have the same phantom js version and the same code... 
the desirable output PDF on local environment is different than the live one on the server...

![1st_frame](https://cloud.githubusercontent.com/assets/12447235/15098028/07907cc4-1539-11e6-9c62-f90bd6d98515.jpg)

**Comment by evertondanilo** [comment]
I'm also having the same issue, any solution?
