### ISSUE TITLE
set QT_QPA_PLATFORM env variable causes crash

### ISSUE THREAD

**Issue by L2501** [ariya/phantomjs#14061]
phantomjs-2.1.1-linux-x86_64

QT_QPA_PLATFORM=xcb phantomjs                                                                                                            :(
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Available platform plugins are: phantom.

Reinstalling the application may fix this problem.
PhantomJS has crashed. Please read the bug reporting guide at
http://phantomjs.org/bug-reporting.html and file a bug report.
[1]    6608 abort (core dumped)  QT_QPA_PLATFORM=xcb phantomjs

**Comment by Vitallium** [comment]
This is not supported. Don't setup environment variables. We static version of Qt, it contains only minimal plugins for PhantomJS functionality.

**Comment by zackw** [comment]
Maybe we should detect such environment variables before initializing Qt, and either arrange to ignore them, or fail to start with a message that makes clear that this is *not* a bug, or both.

**Comment by Vitallium** [comment]
@zackw Qt has a lot of environment variables. I know that in this case we should handle only QT_QPA_PLATFORM. But I don't like this idea. Sounds like a hack for me.

Another thing. I know that some users (and we) would like to move away from bundled QtBase to system provided. Perhaps we should just wait for it.

**Comment by frantic1048** [comment]
Exactly same issue, just tried `unset QT_QPA_PLATFORM` then phantomjs works...

**Comment by nauar** [comment]
Same here:

- Archlinux latest
- Frantic1048 solution works for me too

Thank you!

**Comment by ChALkeR** [comment]
@Vitallium QT_QPA_PLATFORM is set by the system here, just installing phantomjs and running it fails. 

`npm test` for whatever that is using phantomjs also fails.

**Comment by Vitallium** [comment]
@ChALkeR damn. Looks like we have to unset it.

**Comment by ChALkeR** [comment]
@Vitallium I believe that `qputenv("QT_QPA_PLATFORM", "");` before https://github.com/ariya/phantomjs/blob/master/src/main.cpp#L45 should work.

**Comment by Vitallium** [comment]
@ChALkeR `qunsetenv` will be better. Feel free to create a pull request for that.

**Comment by ChALkeR** [comment]
@Vitallium Indeed.

Sorry, I don't want to file pull requests without testing things, and I don't have time to build PhantomJS myself atm =), so no pull request from me for now. I could do this later, though, if it would still be needed. No idea when, though.

**Comment by JuHwon** [comment]
I got the same issue. 
Arch Linux here too.
Thx.

**Comment by p-kozlov** [comment]
The same bug for me for phantomjs-2.1.1. Adding alias with unset environment variable works around.

**Comment by stephenmac7** [comment]
I also have the issue. Thanks @JuHwon for the temporary fix.

**Comment by p-kozlov** [comment]
Anyway, I just compiled new version of phantomjs from the source from master branch (with qt-5.6.1), works fine for me with `QT_QPA_PLATFORM=xcb bin/phantomjs`. No idea what actually could be changed... I can't try to build it from source from tag 2.1.1, because it requires qt-5.5, which is not installed in my computer).

@ariya when are you going to do next release, like 2.1.2 ?

**Comment by leeight** [comment]
@Vitallium After set `QT_QPA_PLATFORM=offscreen`, phantomjs 2.5.0-development can launch. Empty `QT_QPA_PLATFORM` not working.

```
$ env QT_QPA_PLATFORM='offscreen' bin/phantomjs -v
2.5.0-development

$ env QT_QPA_PLATFORM='' bin/phantomjs -v
QXcbConnection: Could not connect to display :0.0
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
[1]    7715 abort      env QT_QPA_PLATFORM='' bin/phantomjs -v
```

**Comment by mehdivk** [comment]
@leeight Do you use a pre-compiled version of PhantomJS or a compiled one? I compiled it and still get the error with/without the `QT_QPA_PLATFORM` env variable.

**Comment by sfatfarma** [comment]
Same issue is happening for me, the following command fixes it (as a workaround):
env QT_QPA_PLATFORM='offscreen' phantomjs -v
