### ISSUE TITLE
Documentation: sendEvent(mouseEventType[, mouseX, mouseY, button='left']) 

### ISSUE THREAD

**Issue by lollodevnews** [ariya/phantomjs#14070]
On the documentation http://phantomjs.org/api/webpage/method/send-event.html
the function sendEvent to send mouse event has this form:  
sendEvent(mouseEventType[, mouseX, mouseY, button='left'])  
while it should have this form based on the function itself:  
sendEvent(mouseEventType, mouseX, mouseY, button)
Hope this was the right place to report it

**Comment by Vitallium** [comment]
I'm not sure I follow you. Only the `mouseEventType` argument is required. That's why the signature has this form.

**Comment by lollodevnews** [comment]
It confused me because square brackets are normally used in arrays, so I had to look up the source to see how the function was declared.
I don't know JavaScript well enough to know if that is a common notation, if so consider this closed, but a notation like
sendEvent(mouseEventType /*, mouseX, mouseY, button */) 
looks less ambiguous  to me
Thank you for your time
