### ISSUE TITLE
Unable to fetch any results on LInode 1GB instance

### ISSUE THREAD

**Issue by aquaindian** [ariya/phantomjs#14091]
I have installed phantomjs (1.9.8) using npm on Linode having specs as  1GB RAM 1CPU Core 24 GB SSD Storage. 
While trying to locate any element it results in 'TimeoutException' . Tried increasing wait time-outs but didn't worked out .
Same program run perfect on linode with higher configuration as 8 GB RAM 6 CPU Cores. 

Any suggestions on how i can traceback this?? or is there any issue with the build ?

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
