### ISSUE TITLE
DST Issue In U.S. on March 13th, 2016

### ISSUE THREAD

**Issue by scottfwalter** [ariya/phantomjs#14093]
`
d = new Date(2016, 2, 13);

d.setHours(5);

console.log(d);

//outputs  Sun Mar 13 2016 06:00:00 GMT-0500 (CDT)
`

However it should be Sun Mar 13 2016 05:00:00 GMT-0500 (CDT)

**Comment by Vitallium** [comment]
Duplicate. Please see #11151
