### ISSUE TITLE
"TypeError: undefined is not a constructor" phantomjs 2.1.1

### ISSUE THREAD

**Issue by bourbon1991** [ariya/phantomjs#14096]
Hello, I tried to listen a webpage using phantomjs 2.1.1 in windows 8.1.
However, when the page load a js, there is an error as follow:
`TypeError: undefined is not a constructor (evaluating 'Number.isFinite(V)')`
 I found the follow code in that js:
`(Number.isFinite(z) ? z : 0)`
Now ,because of this error, the page can not load normally.
Is there any methods to solved this error?
Thanks!

**Comment by xeoshow** [comment]
I met the similar problem, and just would like to know what api set is supported for the specific phantomjs version? How I can check if some api is supported? Thanks!

**Comment by bourbon1991** [comment]
Using `injectJs` method could solve these kind error.

**Comment by JiechengZhao** [comment]
I met the similar problem. How to use injectJs to solve that? And I believe it should be bug.
