### ISSUE TITLE
Bad timezone DST related handling

### ISSUE THREAD

**Issue by jurko-gospodnetic** [ariya/phantomjs#14097]
Somewhere in the bowels of PhantomJS there's a bug with handling timezone DST changes.

To see it use the following configuration:
- use the `moment` library (saw it with version `2.10.3`)
- set your local timezone to `'America/Edmonton'` (possibly by setting `TZ='America/Edmonton'` on the command-line before running `PhantomJS`
- run the following code:

```
for (var i = 1; i < 11; ++i) {
    console.log('hour ' + i + ':', moment('2016-03-13').hour(i));
}
```
- there was a 2 --> 3 DST change in that time-zone on that day, so when you run something like this in `node.js` or `Firefox`, you get the following results:

```
i --> hour
1 --> 1
2 --> 3 (the only one changed!)
3 --> 3
4 --> 4
```
- however, under PhantomJS you get results like these:

```
i --> hour
1 --> 1
2 --> 3 (changed!)
3 --> 4 (changed!)
4 --> 5 (changed!)
5 --> 6 (changed!)
6 --> 7 (changed!)
7 --> 8 (changed!)
8 --> 9 (changed!)
9 --> 9
10 --> 10
```

Now I have not taken the time to research this further, and in theory it could be something that `moment` is doing internally that is interacting badly with PhantomJS code, but it's strange that this happens only with PhantomJS while not with any other browser I've tested or with `node.js`.

Hope this helps.

[I hoped to find the time to research this a bit more and find out exactly which native Date operations get performed by `moment` in those `.hour()` calls, but unfortunately have not found it yet. However, if anyone does want to take a look, I don't expect that part to be difficult.]

**Comment by dhurlburtusa** [comment]
I have also come across a similar DST issue but in native JavaScript code.  I have seen it with the `Date` constructor as in the following example.  I have also seen it when used with `Date#setFullYear` on dates that on not in DST but the new year _is_ in DST.

Let TZ=America/Denver.

```js
var dst, std;
dst = new Date(2008, 2, 9, 3);
if (/central/i.test(dst.toString())) {
  // The following fails in PhantomJS 2.1.1.
  expect(dst.getTimezoneOffset()).toBe(300);
  expect(dst.toISOString()).toBe('2008-03-09T08:00:00.000Z');
  expect(dst.getTime()).toBe(1205049600000);
}
else if (/mountain/i.test(dst.toString())) {
  // The following fails in PhantomJS 2.1.1.
  expect(dst.getTimezoneOffset()).toBe(360);
  expect(dst.toISOString()).toBe('2008-03-09T09:00:00.000Z');
  expect(dst.getTime()).toBe(1205053200000);
}
...
dst = new Date(2008, 2, 9, 8);
console.log(dst.toString());
if (/central/i.test(dst.toString())) {
  // The following fails in PhantomJS 2.1.1.
  expect(dst.getTimezoneOffset()).toBe(300);
  expect(dst.toISOString()).toBe('2008-03-09T13:00:00.000Z');
  expect(dst.getTime()).toBe(1205067600000);
}
else if (/mountain/i.test(dst.toString())) {
  // The following fails in PhantomJS 2.1.1.
  expect(dst.getTimezoneOffset()).toBe(360);
  expect(dst.toISOString()).toBe('2008-03-09T14:00:00.000Z');
  expect(dst.getTime()).toBe(1205071200000);
}

dst = new Date(2008, 2, 9, 9);
console.log(dst.toString());
if (/central/i.test(dst.toString())) {
  // The following does NOT fail in PhantomJS 2.1.1.
  expect(dst.getTimezoneOffset()).toBe(300);
  expect(dst.toISOString()).toBe('2008-03-09T14:00:00.000Z');
  expect(dst.getTime()).toBe(1205071200000);
}
else if (/mountain/i.test(dst.toString())) {
  // The following fails in PhantomJS 2.1.1.
  expect(dst.getTimezoneOffset()).toBe(360);
  expect(dst.toISOString()).toBe('2008-03-09T15:00:00.000Z');
  expect(dst.getTime()).toBe(1205074800000);
}
```

Study the example above and you may notice a pattern.  The further the offset of the timezone is from UTC, the more dates are incorrect.  Notice that central does _NOT_ fail for `new Date(2008, 2, 9, 9).`

**Comment by navipegator** [comment]
Reproduced this with code:
phantomjs> var p3 = new Date(1427590740000);
undefined
phantomjs> p3
"2015-03-29T00:59:00.000Z"
phantomjs> p3.getSeconds();
0
phantomjs> p3.setSeconds(1);
1427587141000
phantomjs> p3
"2015-03-28T23:59:01.000Z"
phantomjs>

So just using setSeconds throws hours to previous day.
