### ISSUE TITLE
PhantomJS will not run on a linux ubuntu AWS instance because of electron

### ISSUE THREAD

**Issue by mwiegant** [ariya/phantomjs#14092]
My team and I are developing an application that monitors our other servers so we can be the first to know when a server goes down.  We've used PhantomJS to achieve this, and it's really reliable.

.....That is, it's really reliable on our development machines and mac minis in our office. We tried to upload our code to an AWS instance running ubuntu 14.04.3 and had no success. After some research, we discovered that electron was the problem. For whatever reason, electron-prebuilt does not come with the right stuff to be run off of ubuntu and work as expected.

Because electron does not work, phantomJS tests that we run fail silently. No errors are thrown, but we can see that as soon as the first test is hit no further progress is made and during the next testing cycle the first test is hit again before stopping and waiting until another testing cycle begins.

Is there a way around this? Maybe a different version of electron can be used? Has anyone else had problems running PhantomJS on an AWS instance, or been able to get PhantomJS working on one?

**Comment by Vitallium** [comment]
Could you please elaborate why do you use Electron with PhantomJS?

**Comment by mwiegant** [comment]
electron is a dependency of PhantomJS. My understanding is that electron is used within PhantomJS to actually create the headless-browser

**Comment by Vitallium** [comment]
No, PhantomJS doesn't use Electron at all. PhantomJS is a standalone headless browser without any dependency.

**Comment by mwiegant** [comment]
I'm sorry, I'm totally on the wrong thread. Meant nightmareJS, not phantomJS :)

We were using PhantomJS though for a little bit before nightmareJS. As I remember, we weren't able to get phantomJS to work though.  Sorry!

**Comment by Vitallium** [comment]
No worries!
