### ISSUE TITLE
event.which seems broken in 2.1.1

### ISSUE THREAD

**Issue by Kirill89** [ariya/phantomjs#14109]
I have different behaviour between 1.9.7 and 2.1.1 versions when trying simulate click event. Looks like in 2.1.1 we have no information about which mouse button clicked.

**Example code:**

``` javascript
// test.js
var page = require('webpage').create();
var url = 'http://phantomjs.org/';

page.onConsoleMessage = function (msg) {
  console.log('CONSOLE: ' + msg);
};

page.open(url, function () {
  page.evaluate(function () {
    document.querySelector('body').onclick = function (event) {
      console.log(event.which);
    };
  });

  page.evaluate(function () {
    var event = document.createEvent('MouseEvent');

    event.initEvent('click', true, true);
    // Simulate click
    document.querySelector('.btn-download').dispatchEvent(event);
  });

  phantom.exit();
});
```

**Example output:**

```
./phantomjs-1.9.7-macosx/bin/phantomjs test.js
CONSOLE: 1
./phantomjs-2.1.1-macosx/bin/phantomjs test.js
CONSOLE: 0
```

**Comment by Vitallium** [comment]
>This feature is non-standard and is not on a standards track
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/which

**Comment by Kirill89** [comment]
@Vitallium but this feature supported by all modern browsers and modern libraries, like jQuery, [uses](https://api.jquery.com/event.which/) this flag.
