### ISSUE TITLE
Why there is no proxy() method in 2.0?

### ISSUE THREAD

**Issue by wskorodecki** [ariya/phantomjs#14108]
It looks like someone has removed the phantom.proxy() method by mistake, because it is present in the following versions:
https://github.com/ariya/phantomjs/blob/master/src/phantom.cpp
https://github.com/ariya/phantomjs/blob/2.1/src/phantom.cpp

but not in 2.0.

**Comment by Vitallium** [comment]
Because it was added in 2.1 version.
