### ISSUE TITLE
pageSize and viewportSize

### ISSUE THREAD

**Issue by TWKDreamState** [ariya/phantomjs#14106]
If I set both the pageSize and viewportSize, the viewportSize does not have any effect.

Eg.
```
console.log('Loading a web page');
var page = require('webpage').create();
var url = 'http://phantomjs.org/';
page.open(url, function (status) {
  //Page is loaded!
  page.viewportSize = {width: 4000, height: 4000}
  page.paperSize = {format: 'A4', orientation: 'portrait'}
  page.render("test.pdf");
  phantom.exit();
})
```

If I remove the paperSize then the viewportSize works as expected. I need to standardise the PDF output regardless of the individuals screen resolution. How would I go about this?

**Comment by francescjimenez** [comment]
+1

**Comment by TWKDreamState** [comment]
Hi,

I built from source but with the changes proposed here ..
https://github.com/ariya/phantomjs/pull/13583/files
... for DPI settings and it seems to be working for me now.
