### ISSUE TITLE
Random crashing happening on OSX 10.10.4 using mocha-phantomjs

### ISSUE THREAD

**Issue by dmi3y** [ariya/phantomjs#14104]
Here is the [package.json](https://github.com/nathanboktae/mocha-phantomjs/blob/v4.0.1/package.json) of the `mocha-phantomjs` which I'm on.

The tests seems to be executed properly, and at the very end it just crashes, like 1 from 10 with no trackable pattern from what I can see.

Not sure what would be the best place to file report, but crash says:

> PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/1434FB42-60BF-40CD-BE5C-7C7BA3D6B2FD.dmp

So here I'm. Let me know If I need open one on mocha-phantomjs side too, and/or close this one.

Thank you in advance.

[dump.zip](https://github.com/ariya/phantomjs/files/177008/dump.zip)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
