### ISSUE TITLE
Getting "Rate limit for this resource has been exceeded" on bitbucket download fetch

### ISSUE THREAD

**Issue by jhwal** [ariya/phantomjs#14112]
Sorry, don't know if this is the right place for this. 

When fetching: 

https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2

Now getting rate limit exceeded message in subject line. Thx

**Comment by jhwal** [comment]
Seems to have cleared up (?) Closing.

**Comment by ariya** [comment]
See #13953.
