### ISSUE TITLE
networkRequest abort() error in onResourceRequested 

### ISSUE THREAD

**Issue by panther7** [ariya/phantomjs#14114]
Hi,

If in page are absolute URLs without defined protocols (like "//" for http(s)) and this URLs is aborted then is error in debug log.
This error can cause other issue such as abort blacklist url and so on.

**Example code:**

``` javascript
var webpage = require("webpage");
var page = webpage.create();
var url = "http://www.youtube.com";

page.onResourceRequested = function(requestData, networkRequest) {
    if (requestData.url.indexOf("//s.ytimg.com") != -1) {
        networkRequest.abort();
    }
};

page.open(url, function(status) {
    phantom.exit();
});
```

**Error in v2.1.1**
`[DEBUG] Network - Resource request error: QNetworkReply::NetworkError(ProtocolUnknownError) ( "Protocol \"\" is unknown" ) URL: ""`
**Error in v1.9.8**
`[DEBUG] Network - Resource request error: 301 ( "Protocol "" is unknown" ) URL: ""`

**Comment by Vitallium** [comment]
I think I can say this is a known problem. The patch for this in progress.
In future all network related problems with requests will not be passed to `onResourceError` callback.

But about your issue, I'm not sure I follow you. Usually you don't need to run PhantomJS with debug enabled.

**Comment by panther7** [comment]
Thanks for fast response.

My issue does not cause this error, it was other else.
