### ISSUE TITLE
Include the files from https://bitbucket.org/ariya/phantomjs/downloads

### ISSUE THREAD

**Issue by paladox** [ariya/phantomjs#14124]
GitHub now allows you to host additional files when releasing releases please do add It to GitHub since they doint rate limit.

**Comment by paladox** [comment]
To avoid the rate limit you can use http://cnpmjs.org/downloads

**Comment by paladox** [comment]
Which I just found from @Hashar

**Comment by ariya** [comment]
Please discuss this as part of #13953.
