### ISSUE TITLE
Occasional 403's when trying to grab binary from bitbucket

### ISSUE THREAD

**Issue by TheAlphaNerd** [ariya/phantomjs#14139]
I have been noticing some instances in the node.js smoke testing suite of getting 403's from bitbucket when trying to install via npm.

While this package is not `officially` supported by npm, (the npm package is [published by medium](https://github.com/medium/phantomjs), I think it is safe to say that the 403's we are getting from bit bucket should be brought up with the main project.

I cannot reproduce reliably but I'll try and dig up a log from our CI to share

**Comment by Vitallium** [comment]
Sorry, but we don't maintain the NPM package. 

For more info please take a look here: #13953

**Comment by ariya** [comment]
Hi @TheAlphaNerd, the quickest workaround is set up a mirror and the use `PHANTOMJS_CDNURL` (as supported by `phantomjs-prebuilt` npm module). As you can see from #13953, we are working on a short/medium/long-term solution. Thanks!

**Comment by TheAlphaNerd** [comment]
thanks for the response aria. Likely adding the as an env var to CI will fix the problem
