### ISSUE TITLE
Cannot create multiple-page PDFs

### ISSUE THREAD

**Issue by tquetano-r7** [ariya/phantomjs#14138]
I have been banging my head against a wall for several days now, hoping someone might be able to help.

I am using v2.1.1 via the phantomjs-prebuilt NPM package. I know of all the rendering issues regarding zoomFactor, DPI settings, etc., and have done the appropriate hacks to make the pages render correctly, and it works ... for one page. I cannot for the life of me figure out how to set the overflow to the next page.

Following the rasterize.js from examples, My setup is pretty straightforward:

```
page.paperSize = {
    orientation: "landscape",
    margin: 15,
    format: "Letter"
  };

  // phantom crashes with literally any other userAgent?!?!?
  page.settings.userAgent =
      "Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/535.7 (KHTML, like Gecko) Chrome/16.0.912.75 Safari/535.7"; 
  page.customHeaders = {
    "SESSIONID": sessionId
  };
  page.zoomFactor = 1;
  page.settings.loadImages = true;
```

And in my application, I've done the recommended zoom hack of:

```
@media print {
  html {
    zoom: 0.65;
  }
}
```

I've even forcibly set CSS in my application to cause a series of page breaks just to see if it will force anything:

```
.section {
  page-break-before: always;
}
```

No dice. The one page that is produced looks correct, but there are no other pages and the content is clearly cut off. Is this a bug related to the zoom / dpi issue? Or am I just an idiot and need to do something else?

**Comment by TWKDreamState** [comment]
In my code I had to do the following to get a page break to work....

`<div style="page-break-after:always;">&nbsp;</div>`

I don't know if this will help? I'm using a version I built from source with the modifications for DPI.
