### ISSUE TITLE
Download link for OSX is giving an error

### ISSUE THREAD

**Issue by MarcLapierre** [ariya/phantomjs#14145]
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip

```<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2016-03-28T19:56:23Z</Expires>
<ServerTime>2016-03-28T20:06:27Z</ServerTime>
<RequestId>33B0E7906070A5A0</RequestId>
<HostId>
/L+dR/c6Ge3hwM6H4hNvcQs0aqKOkp/qTEMPYTp9wUYRrRKRnUbMv/A1sZQ3vN8SUWv5T9WIzfI=
</HostId>
</Error>```

**Comment by KordonDev** [comment]
NodeJs update, solved this problem for me.

**Comment by Vitallium** [comment]
Hi. Sorry, but this is not the PhantomJS issue. It might be a problem with your network.

**Comment by knalli** [comment]
Well, I'm getting this error sometimes as well, both on Travis and local build server instances. The error is an AWS S3 403 error page instead of the download. Perhaps an issue with the bitbucket loadbalancer?

**Comment by knalli** [comment]
Ah, I see: #14139 (just for the records)

**Comment by Vitallium** [comment]
@knalli perhaps. We received message from people about problems with bitbucket. But we can't do anything with it. Sorry. 

You can find more information here #13953
