### ISSUE TITLE
Phantomjs hangs on syntax errors and strictness errors

### ISSUE THREAD

**Issue by Perseid** [ariya/phantomjs#14142]
The current 2.1.1 release (in the Arch package repository and in the wernight/phantomjs docker image) hangs (i.e. freezes) on syntax errors and (some) strictness errors, instead of printing an error message. This test scripts should print a syntax error.

    }{-)-
    console.log("Hello world");

The following script hangs, when `"use strict";` is on the top of the script, but exits normally otherwise:

    //"use strict";
    try {
    	function foo() {
    	}
    	phantom.exit();
    } catch (err) {
    	phantom.exit();
    }

**Comment by Vitallium** [comment]
Hi. Thanks for reporting. But this issue has been already reported. The fix will be landed soon.
