### ISSUE TITLE
prebuilt phantomjs.exe v2.1.1 errors with is not a valid win32 app on WinXP

### ISSUE THREAD

**Issue by jeffbski** [ariya/phantomjs#14140]
Trying to just run the bin\phantomjs.exe (v2.1.1) on WinXP errors with phantomjs.exe is not a valid Win32 application.

v1.9.8 runs fine

**Comment by Vitallium** [comment]
Unfortunately, PhantomJS 2 can't be run on Windows XP because it's outdated operating system.

But if you really need it, you have to compile it from sources by yourself.

**Comment by rockerox** [comment]
I have the same issue using Windows 10. Have support this SO?
