### ISSUE TITLE
PhantomJS not returning Control to cmd & PHP

### ISSUE THREAD

**Issue by Sahilgoyal190** [ariya/phantomjs#14147]
After Running several JS reports in a sequence  in phantomJS control is not coming back to cmd and php. Is phantom crashes or its a bug. Is there any work around for the same.

**Comment by iradul** [comment]
It's hard to say anything without working example.
Do you call `phantom.exit()` properly ? If so I suggest that you wrap all your code (callbacks separately) inside `try` - `catch`. This way you can react and properly exit if any exception happens so something like this could be workaround:
```javascript
try {
  // your code goes here
} catch(e) {
  console.log(e);
  phantom.exit(1);
}
```

**Comment by naitsirch** [comment]
I struggled with the same issue. You have to add `phantom.exit();` after calling `page.render()`

If there are any errors with the content, you can output it with this:
```javascript
var webPage = require('webpage');
var page = webPage.create();

phantom.onError = function(msg, trace) {
    console.log(JSON.stringify({msg: msg, trace: trace}));
    phantom.exit(1);
};
page.onError = phantom.onError;

// your code goes here
```
