### ISSUE TITLE
Mac OSX build

### ISSUE THREAD

**Issue by bhofmei** [ariya/phantomjs#14151]
I'm trying to download the binary version of phantom.js (as suggested by the website). I'm getting an error when trying to download the Mac OSX static build. I will build from source if necessary, but I'd really prefer not to.

Specifically, using wget, I get `ERROR 403: Forbidden`

If I tryi to download directly from the website, I get the following error:

    <Error>
        <Code>AccessDenied</Code>
        <Message>Request has expired</Message>
        <Expires>2016-03-29T12:04:25Z</Expires>
        <ServerTime>2016-03-29T12:13:09Z</ServerTime>
        <RequestId>113CB62C81A5180C</RequestId>
        <HostId>
            nZ3hFFa0HhF2jQet6enqWDPwA48gFmLU8G04iVeF4oXvNbFSVfTa8NPOxGy64K40pUJ2UXRwVoo=
        </HostId>
    </Error>

**Comment by Vitallium** [comment]
Hi. Sorry, but this is not the PhantomJS issue. It might be a problem with your network. We received message from people about problems with bitbucket. But we can't do anything with it. Sorry.

You can find more information here #13953
