### ISSUE TITLE
phantomjs binary fails to install when using "npm install --ignore-scripts"

### ISSUE THREAD

**Issue by agenaille** [ariya/phantomjs#14154]
On our project, we have recently been made aware of the [npm install vulnerability](http://news.softpedia.com/news/node-js-package-manager-vulnerable-to-malicious-worm-packages-502216.shtml) in which a malicious user could add some lifecycle scripts which execute postinstall with elevated permissions.

[Npm recommends a mitigation strategy](http://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability) of disabling scripts globally via: 

`npm config set ignore-scripts true`

or

`npm install --ignore-scripts`

In our application, we are using phantomjs to execute karma unit tests, but when we download the dependencies with "npm install", and also using npm config set ignore-scripts true, the phantomjs binary fails to be recognized by the karma runner. 

I'm curious if there is a way to install phantomjs manually, or if this is a bug, the fact that it cannot be installed with --ignore-scripts?

Any help would be greatly appreciated! :) Thank you for your time, and also, excellent product!

**Comment by agenaille** [comment]
FOLLOW UP: I've found that I can manually install phantomjs like so:

//regularly install it with the other modules
npm install

//switch to phantomjs module dir
cd node_modules\phantomjs

//run the "install" script specified in package.json manually
npm run-script --ignore-scripts false install

This will make the binary available, and the karma tests run successfully.

**Comment by zackw** [comment]
We (PhantomJS maintainers) do not maintain the npm *package* of PhantomJS.  You should re-file this bug against [medium/phantomjs](https://github.com/Medium/phantomjs).  Sadly, there is no way to reassign Github bugs.

**Comment by zackw** [comment]
That said, it appears that the install script does all the actual work of downloading and installing a PhantomJS binary, so I'm not sure there's much they can do.

**Comment by agenaille** [comment]
@zackw Thank you for your quick response. I'll file the issue with medium/phantomjs to see if they have any opinions or suggestions.
