### ISSUE TITLE
`--local-to-remote-url-access` option doesn't work in Phantomjs 2.x?

### ISSUE THREAD

**Issue by hanfeisun** [ariya/phantomjs#14159]
I am using Phantomjs 2.1.0 to render screenshots for a local HTML which makes AJAX call to a remote server. However, it throws an error which says the remote access is not permitted. 

I tried `--local-to-remote-url-access` but it still didn't work.

I found  that `--local-to-remote-url-access` doesn't appear in the help documentation of phantomjs 2.0 (phantomjs --help). Does that mean phantomjs doens't allow local content to access remote URL? If not, is there a way to make it possible?

**Comment by Vitallium** [comment]
This option is still presented and it works (I use PhantomJS 2.1.1. on OS X). From where you downloaded the binary?

**Comment by hanfeisun** [comment]
I see. The option is presented in phantomJS. I'll close this issue for now until I create a reproducible demo..
