### ISSUE TITLE
Dynamically change the proxy settings

### ISSUE THREAD

**Issue by jamb0ss** [ariya/phantomjs#14157]
Is there any way to bind a new proxy server to already running PhantomJS process?
I do websites testing from different locations and "restart" procedure is very expensive.

**Comment by iradul** [comment]
Yes there is, you can use:
`phantom.setProxy(host_or_IP, port, proxy_type, user_name, password);`
`host_or_IP` only this argument is required others are optional
`port` is numeric value by default 8080
`proxy_type` can be `http` (default) or `socks5`

Also this kind of question should be asked on [phantom's board](https://groups.google.com/forum/#!forum/phantomjs) but also this functionality should be documented on the website though.

**Comment by jamb0ss** [comment]
Can be the proxy set via `page`? What is the difference?

https://github.com/ariya/phantomjs/blob/db0758195614ceb8a000b88c4e24face8fd35d7c/src/webpage.cpp
In this case it accept the proxy URL, doesn't it?

Yeah, it would be great to have such info documented for such a big project with so many users

**Comment by iradul** [comment]
Yes it can but it would set proxy only on that particular `page` instance on the other hand setting up proxy on `phantom` global object will set proxy globally no all present and future `page` instances except those that have their own proxy setting. I'm not sure if you can later revert `page` instance proxy back to global setting once you change it.
Also default port is 80 not 8080 (I fixed that in above comment)

**Comment by jamb0ss** [comment]
Ok, got it, thanks!

**Comment by iradul** [comment]
`phantom.setProxy("")`

**Comment by barbolo** [comment]
I found this issue when googling for "phantom set proxy". What I need is to set the proxy for each page, so this is how I'm doing it (in case anyone else has the same need):

> page.setProxy("http://user:pass@proxy_ip_or_host:port/"); // with authentication;
> page.setProxy("http://proxy_ip_or_host:port/"); // or with no authentication;
