### ISSUE TITLE
PDF file won't get created if css refers to invalid or external URI

### ISSUE THREAD

**Issue by naitsirch** [ariya/phantomjs#14162]
I have written this script and try to execute it with Phantom 2.1.1 (Windows 7):

``` javascript
var webPage = require('webpage');
var page = webPage.create();

page.viewportSize = {"width":600,"height":600};
page.settings = {"javascriptEnabled":true,"localToRemoteUrlAccessEnabled":false};

page.paperSize = {"format":"A4","orientation":"portrait","margin":"20mm","header":{"height":null,"contents":null},"footer":{"height":null,"contents":null}};

page.setContent('<html>'
+'    <head>'
+'        <style type=\"text/css\">'
+'            body { background: url(\"\"); }'
+'        </style>'
+'    </head>'
+'    <body>'
+'        Hello'
+'    </body>'
+'</html>', 'http://example.com');

window.setTimeout(function () {
    page.render('C:\\path\to.pdf', {format: 'pdf'});
    phantom.exit();
}, 200);
```

But the problem is, that the PDF file won't get created and there aren't any errors. If I put a valid location to the `background: url(\"\")` directive (something like "file:///C:path/to/file.jpg") the file is created.
Any idea what the reason could be, or is it a bug?

**Comment by Pavnii** [comment]
@naitsirch Well I am running into the same issue.I understood from other posts that phantomjs requires to know about angular library path locally on the system.But i dont really find any docs for same.Could you please tell how did you do that?

**Comment by naitsirch** [comment]
What does this have to do with angular?
