### ISSUE TITLE
Waitfor support for Promise pattern

### ISSUE THREAD

**Issue by loretoparisi** [ariya/phantomjs#14166]
When `phantom` is used as `node` module, the
https://github.com/ariya/phantomjs/blob/master/examples/waitfor.js

does not work when `page.evaluate` is a `Promise` like:

``` javascript
sitepage.evaluate(function() {
                return document.querySelectorAll('.content > ul');
              }).then(function(html) {
                  sitepage.close();
                  phInstance.exit();
                  if(done) done( pageContent );
              });
```

so this will not work:

``` javascript
waitFor(
                    function () {
                       return sitepage.evaluate(function() {
                return document.querySelectorAll('.content > ul');
              }).then(function(html) {
                  sitepage.close();
                  phInstance.exit();
                  if(done) done( pageContent );
              });
                    },
                    function () {
                      sitepage.close();
                      phInstance.exit();
                    }, 1000);
```

In this case the `then` holds the results from the `evaluate` condition. So it possible to implement in the `waitFor` support for the `Promise`?

**Comment by loretoparisi** [comment]
According to node-phantom author here https://github.com/amir20/phantomjs-node/issues/431#issuecomment-207865947

the `waitFor` could become `waitUntil` to support `Promise` like:

```javascript
function waitUntil(asyncTest) {
    return new Promise(function(resolve, reject) {
        function wait() {
            console.log('loop...')
            asyncTest().then(function(value) {
                console.log('value', value)
                if (value === true) {
                    resolve();
                } else {
                    setTimeout(wait, 100);
                }
            }).catch(function(e) {
                console.log('Error found. Rejecting.', e);
                reject();
            });
        }
        wait();
    });
}
```

and then

```javascript
waitUtil(function() {
    return sitepage.evaluate(function() {
        return document.querySelectorAll('.content > ul > li').length > 1;
    })
}).then(function(){
  // evaluate is true
})
```

Could you please add this an alternative example?

**Comment by amir20** [comment]
Hey @loretoparisi I think you are misunderstanding the difference between NodeJS and PhantomJS. The examples directory in this project is about doing sample scripts with PhantomJS directly. There is no `Promise`s or async blocks because everything just runs directly with PhantomJs. `phantomjs-node` is a wrapper on top of phantom which allows you to use PhantomJs in NodeJS. They are two different platforms. 

I hope that makes sense as to why NodeJS and PhantomJS are different.

**Comment by loretoparisi** [comment]
@amir20 yes it's clear to me, that makes sense, question is then, why `PhantomJS` does not support `Promise` ECMAScript6?

**Comment by Vitallium** [comment]
@loretoparisi because PhantomJS uses a bit old version of WebKit. This version doesn't have some feature from ECMAScript6. We're working on updating our web engine to deliver latest cool features to our users,

**Comment by loretoparisi** [comment]
Ok this makes a lot of sense. If you agree I would keep this issue opened tagging it as `enhancement`.Thank you.
Inviato da Outlook Mobile




On Mon, Apr 11, 2016 at 10:36 AM -0700, "Vitaly Slobodin" <notifications@github.com> wrote:












@loretoparisi because PhantomJS uses a bit old version of WebKit. This version doesn't have some feature from ECMAScript6. We're working on updating our web engine to deliver latest cool features to our users,

**Comment by loretoparisi** [comment]
@Vitallium btw at which version of the WebKit is 2.1?

**Comment by brutalcrozt** [comment]
What is `Qt` and `WebKit` , i am really new :confused: .
@loretoparisi i am trying to achieve same things.
Yet found 2 options:
  0. [phantom](https://www.npmjs.com/package/phantom)
  0. [phantom-promise](https://www.npmjs.com/package/phantom-promise)
