### ISSUE TITLE
Dynamically change the local storage path

### ISSUE THREAD

**Issue by jamb0ss** [ariya/phantomjs#14165]
Is there any way to change the local storage path after the PhantomJS process is started?
Or is the only way to set `--local-storage-path` while starting it?
Is it the same as offlineStoragePath, so I can set it via `page.offlineStoragePath` later?

**Comment by Vitallium** [comment]
1) No, there is no such feature
2) No. Offline storage is HTML5 offline storage. It differs from Local Storage.
