### ISSUE TITLE
over 1000 connects, this error:Service' object has no attribute 'log_file'

### ISSUE THREAD

**Issue by ddythink** [ariya/phantomjs#14163]
`Exception AttributeError: "'Service' object has no attribute 'log_file'" in <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0xb569858c>> ignored`

I can't find any answer on the internet...

**Comment by yiptsangkin** [comment]
i have the same problem, i though this maybe the selenium's problem. Have you solve this problem?
