### ISSUE TITLE
Messing with `Host:` in custom headers causes "Operation canceled" errors

### ISSUE THREAD

**Issue by zackw** [ariya/phantomjs#14164]
Originally reported as part of issue #12750, but I'm betting it is not the same problem.

@gsouf wrote:

> Executing phantomjs with this file will **work**:
> 
> ``` js
> "use strict";
> var page = require('webpage').create();
> var lastResourceError = null;
> 
> page.onResourceError = function (resourceError) {
>       console.log("Url errored: " + resourceError.url);
>       console.log("message : " + resourceError.errorString);
>     console.log("------")
> };
> 
> var settings = {
> }
> 
> var url = "https://www.wikipedia.org/";
> 
> page.open(url, settings, function (status) {
>     if (status !== 'success') {
>         console.error('Error');
>         phantom.exit(1);
>     } else {
>       console.log(page.plainText);
>         phantom.exit();
>     }
> });
> "use strict";
> var page = require('webpage').create();
> var lastResourceError = null;
> 
> page.onResourceError = function (resourceError) {
>       console.log("Url errored: " + resourceError.url);
>       console.log("message : " + resourceError.errorString);
>     console.log("------")
> };
> 
> var settings = {
> }
> 
> var url = "https://www.wikipedia.org/";
> 
> page.open(url, settings, function (status) {
>     if (status !== 'success') {
>         console.error('Error');
>         phantom.exit(1);
>     } else {
>       console.log(page.plainText);
>         phantom.exit();
>     }
> });
> ```
> 
> now replace the `settings` variable to this:
> 
> ```
> var settings = {
>       "headers": {
>               "Host": "wikipedia.org"
>       }
> }
> 
> var url = "https://www.wikipedia.org/";
> ```
> 
> And execute that will **fail**
> 
> Now replace the setting to a different host, and that will **work** (though the server returns a domain error):
> 
> ```
> var settings = {
>       "headers": {
>               "Host": "google.com"
>       }
> }
> 
> var url = "https://www.wikipedia.org/";
> ```
> 
> Querying google with different existing tld will fail (google redirects to the tld in the host)
> 
> ```
> var settings = {
>       "headers": {
>               "Host": "google.fr"
>       }
> }
> 
> var url = "https://www.google.com/";
> ```
> 
> (redirect to google.fr then fails)
> 
> I found a case in which it works: with the website getcomposer.org. Maybe is it due to what resources are loaded or not on the page.
> 
> The two following examples **work**:
> 
> ```
> var settings = {
> }
> 
> var url = "https://getcomposer.org";
> ```
> 
> ```
> var settings = {
>       "headers": {
>               "Host": "getcomposer.org"
>       }
> }
> 
> var url = "https://getcomposer.org";
> ```
> 
> But for some reasons this will also **fail** (operation cancelled)
> 
> ```
> var settings = {
>       "headers": {
>               "Host": "foo.bar"
>       }
> }
> 
> var url = "https://getcomposer.org";
> ```
> 
> As a side note for this last example, I tried it in chrome leads to a loop redirection.
> 
> Last note: trying this on a page that does not load much resources (http://httpbin.org/get) seems to work in every cases.

Given the crucial importance of `Host:` to the low-level workings of HTTP, Qt screwing up the protocol when it's overridden in custom headers is not terribly surprising.  I am inclined to say that this should not be supported and maybe page.open should throw an error if you try it.  @Vitallium @ariya: thoughts?

**Comment by gsouf** [comment]
:+1:

**Comment by gsouf** [comment]
I'm actually using the host header, because the software that generates the request, auto generates the host header. I managed to remove it before passing the request to phantomjs
