### ISSUE TITLE
No error message shown if port is already used when using remote debugger

### ISSUE THREAD

**Issue by naitsirch** [ariya/phantomjs#14177]
Environment: Windows 7, PhantomJS v2.1.1

When I tried remote debugging with `phantomjs.cmd --remote-debugger-port=9000 test.js` the debugging did not work. After some searching in the web I tried to change the port for the debugger and it worked.

Showing an error message on the console output would help users to find the problem.

**Comment by zackw** [comment]
Confirmed.  Not Windows-specific.  There's a qWarning() that is supposed to get called in this case but it isn't and I'm not sure why.  (And a warning seems a little weak.)

**Comment by naitsirch** [comment]
Yes, I'd suggest to exit the process in this case with an error code.
