### ISSUE TITLE
phantomjs unable to find angular library

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#14172]
While generating PDF its always throws 

`ReferenceError: Can't find variable: angular`

How do i tell phantomjs where is angular library?

**Comment by Vitallium** [comment]
Could you post a sample please? Current PhantomJS supports AngularJS.

**Comment by Luis-Palacios** [comment]
Hey guys I ran into this same issue, I can provide a simple test case:

test.js file:
```js
var page = require('webpage').create();
page.open('http://preview.granadatile.com/en/', function() {
  page.render('test.png');
  phantom.exit();
});
```
from the commandline:
```sh
phantomjs test.js
```

Output:

![output](https://user-images.githubusercontent.com/4844997/27748278-0df70e24-5d8c-11e7-87ba-a013abeb83f7.png)

OS :Windows 10
phantomjs --version
2.1.1

If there is something else i need to provide please let me know.

Thanks!
