### ISSUE TITLE
ReferenceError: Can't find variable: uuid

### ISSUE THREAD

**Issue by loretoparisi** [ariya/phantomjs#14171]
I get this error

``` shell
  phantomjs://platform/test.js:73
  phantomjs://platform/webpage.js:286 in _onPageOpenFinished
ReferenceError: Can't find variable: uuid
```

Version is `2.1.1`
MacOS X `10.10.5`
node `v.4.2.6`

**Comment by Vitallium** [comment]
This line from stack strace `phantomjs://platform/test.js:73` tells that the problem is in you code (in file `test.js`)

**Comment by loretoparisi** [comment]
@Vitallium I have found out that this was due to a page creation based on array, before closing the previous page. Is that possible?

**Comment by Vitallium** [comment]
Could you please show me an example?
