### ISSUE TITLE
PhantomJS 2.0 Crash Report on Linux Ubuntu ARM

### ISSUE THREAD

**Issue by LeMoussel** [ariya/phantomjs#14175]
I'm using PhantomJS 2.0.0 on Linux Ubuntu 15.04 with ARMv7 Processor rev 2 (v7l)
I get these `.dmp` files when running my tests on http://www.bloomberg.com site.

[35a2231f-6b75-9ea0-38f66cbd-493faf7b.dmp](https://www.dropbox.com/s/tsg95aeqc10nqxs/35a2231f-6b75-9ea0-38f66cbd-493faf7b.dmp?dl=0)

I couldn't find symbol files for 2.0.0, so I can't expand the `.dmp` files.

**Comment by ariya** [comment]
For now, ARM is not really supported.

**Comment by medemi68** [comment]
You guys should add support for ARM. Armhf
