### ISSUE TITLE
Errors when using a custom user-agent not containing WebKit

### ISSUE THREAD

**Issue by BenMorel** [ariya/phantomjs#14198]
I'm using the binary version of PhantomJS 2.1.1 on Fedora 23 64 bit.

I'm using PhantomJS with Selenium and Facebook's php-webdriver. When using the default user-agent, everything works fine. But when I set a custom user-agent that does not contain "WebKit", I start getting errors on `click()`:

> undefined is not an object (evaluating 'B(A(a)).getComputedStyle(a,null).MozTransform.match')
- A detailed report is available in facebook/php-webdriver#293 ; someone commented being able to reproduce the same issue with webdriver.io, and suggests the issue lies with phantomjs
- A similar issue has been reported on ghostdriver with phantomjs: detro/ghostdriver#325

So in total, 3 different drivers are having issues with phantomjs when using a user-agent string that does not contain the string "WebKit".

**Comment by Vitallium** [comment]
Well. PhantomJS is powered by WebKit under the hood. Of course, if you change the user-agent server will stop recognize it as a WebKit-based browser and will serve (and use) different capabilities. The same also applies to JavaScript.

The schema is:
- WebKit browser? Yes => Send JavaScript that it understands
- No? Okay. Mozilla Firefox? Yes => Send JavaScript that Firefox understands
- and so on...

**Comment by BenMorel** [comment]
Interesting, thanks for your reply. So the issue would lie with Selenium, rather than PhantomJS?

As mentioned in my original issue on php-webdriver, my code works with any user-agent when using the Firefox driver though!
