### ISSUE TITLE
phantomjs-2.1.1-linux-x86_64 proxy authentication not working 

### ISSUE THREAD

**Issue by hrushikesh198** [ariya/phantomjs#14193]
1. Which version of PhantomJS are you using?
phantomjs-2.1.1-linux-x86_64

2. What steps will reproduce the problem?
  1.Try some proxy that needs authentication

3. Which operating system are you using?
centos 6.6

4. Did you use binary PhantomJS or did you compile it from source?
binary
5. Please provide any additional information below.
I tried command line option by setting --proxy and --proxy-auth also phantom.setProxy() . None of the method works when the proxy needs authentication.

**Comment by Vitallium** [comment]
What kind of proxy did you use?

**Comment by hrushikesh198** [comment]
I was using a http proxy. My bad. Tried with some other proxies. It's working fine. Closing the issue.

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (231/200 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:53758)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-cf68-andre=castonguay.org@sgmail.github.com>)
	id 1apkQj-003N3P-Hj
	for andre@castonguay.org; Mon, 11 Apr 2016 18:35:38 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=YrZtEAxSMRQKDNkpldSrxXrOSYg=; b=AiSGCcBQfI3tK3jl
	8U7THDDonwvXwduCXe1DFl7wIt9cQB63+Ax3w/NYSaTy9RmMUDJg5PpYKNgqB7ZG
	BLRKvFqRw7S6x1HnW88fFB24vaj/gg1kCivrX5OabHsNdYZ9eyUZYBqOj3vGKDw8
	8+jAfLJubuFBaHJ7DyBWyEU41QE=
Received: by filter0823p1mdw1.sendgrid.net with SMTP id filter0823p1mdw1.19941.570C268F23
        2016-04-11 22:34:55.795286642 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id 3AAS2sACT7u4wh3NAGGOEQ
	for <andre@castonguay.org>; Mon, 11 Apr 2016 22:34:55.659 +0000 (UTC)
Date: Mon, 11 Apr 2016 15:34:55 -0700

**Comment by dREc** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  sirzifnab@gmail.com
    Domain castonguay.org has exceeded the max emails per hour (237/200 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:1375)
	by server191.web-hosting.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-cf68-andre=castonguay.org@sgmail.github.com>)
	id 1apkRO-003O0y-Bh
	for andre@castonguay.org; Mon, 11 Apr 2016 18:36:19 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=GrxSp8qNMGF0Zu2+bynsN6iy6sU=; b=pJln7SVZk1D1l/cV
	e5fgC0LsdCtyUY056PBhEcssFN6bQv3eJ7Mcn/qBdBoqUXlm/Bg8zJLWMKekdO0R
	TWQbMwHRevQXydPNujvcW/+N6eDyDTihkoAYD1+qt+TXJhDC1GQvKKamaDvCgunQ
	pnezw35GxD9OYWiDxYIzqtQFBHI=
Received: by filter0458p1mdw1.sendgrid.net with SMTP id filter0458p1mdw1.18793.570C268F5D
        2016-04-11 22:34:55.851849907 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id --Ge2DfqR4OTdXFbTNnn_w
	for <andre@castonguay.org>; Mon, 11 Apr 2016 22:34:55.645 +0000 (UTC)
Date: Mon, 11 Apr 2016 15:34:55 -0700
