### ISSUE TITLE
Link for downloading phantomjs is broken

### ISSUE THREAD

**Issue by maxgu** [ariya/phantomjs#14197]
Link for downloading phantomjs is broken
On this page http://phantomjs.org/download.html
in Linux 32-bit > Download phantomjs-2.1.1-linux-i686.tar.bz2 (23.0 MB) and extract the content.

link https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-i686.tar.bz2 - is broken

how i can download phantomjs v2.1.1 for Linux 32b ?

**Comment by Vitallium** [comment]
Just tried to download and unpack it. Everything is ok.

**Comment by maxgu** [comment]
yes, аlready working
