### ISSUE TITLE
Cannot get basic phantomJS examples to run in chrome. Javascript exceptions thrown 

### ISSUE THREAD

**Issue by jabberfest** [ariya/phantomjs#14196]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2.1.1

2. What steps will reproduce the problem?
  1. Download the mac osx binary from the phantomjs site
  2. Extract the zip file
  3. From the extracted directory run

```
./phantomjs --remote-debugger-port=9000 ../examples/version.js 
```
 4. Navigate to http://localhost:9000/
 5. Navigate to http://localhost:9000/webkit/inspector/inspector.html?page=1
 6. Clicking on any of the buttons in the remote inspector causes exceptions in the browser window, break points never hit even after running __run() in the remote webkit console (See Screenshot)
Exceptions are thrown in the browsers native console.

<img width="1437" alt="screen shot 2016-04-12 at 3 56 41 pm" src="https://cloud.githubusercontent.com/assets/1287294/14475496/e2415bd0-00c7-11e6-9aef-2a8ecd84a83f.png">

3. Which operating system are you using?
OS X Yosemite 10.10.5

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.
I saw similar things happening on PhantomJS 1.9.8. Also happened in Safari.

**Comment by jabberfest** [comment]
Closing. Looks like I had a chrome emoji plugin that was screwing things up. I also had the phantomjs binary and one installed globally via npm.

I removed the phantomjs version installed via npm, and used safari since I have no plugins installed on it.

**Comment by bigbearzhu** [comment]
I saw this on Windows Chrome too. Would it be due to Chrome may have removed the getPropertyCSSValue method? https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/3VmxWFzcyJc/GFOnJxnWBN0J
Similar issue: https://github.com/square/PonyDebugger/issues/157

**Comment by bruce965** [comment]
Not that it fixes anything, but you can paste this code in Chrome console (the real one) to patch it.

```
window.CSSPrimitiveValue = function(styledec, name) {
	this._styledec = styledec;
	this._name = name;
};
window.CSSPrimitiveValue.prototype.setFloatValue = function(unitType, floatValue) { };
window.CSSStyleDeclaration.prototype.getPropertyCSSValue = function(x) {
	var self = this;
	var a = new CSSPrimitiveValue(this, x);
	a.getCssText = function() { return self[x]; };
	a.getCssValueType = function() { return -1; };
	a.setCssText = function(y) { self[x] = y; };
};
```
