### ISSUE TITLE
PhantomJS 1.9.8  segfault 

### ISSUE THREAD

**Issue by smabie** [ariya/phantomjs#14199]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

1.9.8

2. What steps will reproduce the problem?
Can't reliably reproduce the problem

3. Which operating system are you using? 
0.0.0 Linux 3.13.0-35-generic #62~precise1-Ubuntu SMP Mon Aug 18 14:52:04 UTC 2014 x86_64

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.

[dump.txt](https://github.com/ariya/phantomjs/files/217731/dump.txt)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
