### ISSUE TITLE
customHeaders cannot be partially updated

### ISSUE THREAD

**Issue by jamb0ss** [ariya/phantomjs#14204]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

> 2.1.1
1. What steps will reproduce the problem?

```
var page = require('webpage').create();

// 1
console.log(JSON.stringify(page.customHeaders));

page.customHeaders['test'] = 'ok';

// 2
console.log(JSON.stringify(page.customHeaders));

page.open('http://httpbin.org/headers', function (status) {

    // 3
    console.log(JSON.stringify(page.customHeaders));

    console.log(page.plainText);
    phantom.exit();

});
```

In all cases (1, 2, 3) the customHeaders will be empty

Is it an expected behavior and we have to replace the entire "customHeaders" object to add more default headers there?

**Comment by Jeff-14159** [comment]
Just ran into the same issue.... after ripping my hair I've only been able to set customHeaders during the create:
``var page = require('webpage').create({ customHeaders: { 'test11': 'test11' } });``

then you can reference them with:
 ``console.log(JSON.stringify(page.customHeaders));``

I could not **set** them as mentioned in the docs[ here](http://phantomjs.org/api/webpage/property/custom-headers.html) with:
``page.customHeaders = { "X-Test": "foo"} `` _unless_ I had already set it once during the "create"
 
furthermore in no way could I add to them with:
``page.customHeaders.foo = "foo"``  or  ``page.customHeaders['foo'] = "foo"} ``

believe it may be related to another issues [#12547](https://github.com/ariya/phantomjs/issues/12547) #13660 ,  

 at very least I think the documentation needed updated to mention setting them during the create function
