### ISSUE TITLE
Phantomjs Crash

### ISSUE THREAD

**Issue by priyankachaturvedi** [ariya/phantomjs#14207]
1. Which version of PhantomJS are you using?
      2.1.1
2. What steps will reproduce the problem?
   1. opening my outlook account using phantomjs
      or
   2. trying to access a lot of accounts say 9-10 at the same time (mainly Linkedin)
3. Which operating system are you using?
   Ubuntu 14.04
4. Did you use binary PhantomJS or did you compile it from source?
   binary for Linux 64-bit
5. Please provide any additional information below.
   If I try to access my outlook account, it breaks in between.when I saw the phantomjs crash dump SIGSEGV concerned me the most and the highlight of  dump says :

Crash|**SIGSEGV**|0x7ff8aaea6000|0
Module|phantomjs||phantomjs|7E6DA1FCFA15CCA0996242A004A2B7070|0x00400000|0x02d91fff|1
Module|DejaVuSerif-Bold.ttf||DejaVuSerif-Bold.ttf|000000000000000000000000000000000|0x7ff8ab1a3000|0x7ff8ab1f7fff|0
Module|DejaVuSerif.ttf||DejaVuSerif.ttf|000000000000000000000000000000000|0x7ff8ab1f8000|0x7ff8ab251fff|0

Module|libnss_dns-2.19.so||libnss_dns-2.19.so|87A5E6626E095E14CC7CD2BF5E323B840|0x7ff8abdfa000|0x7ff8abffffff|0
Module|libnss_mdns4_minimal.so.2||libnss_mdns4_minimal.so.2|B50461EE610532261E52F46188993FA10|0x7ff8c0042000|0x7ff8c0244fff|0 

Is it related to the memory and is there any solution to it?
[phantom.dump.txt](https://github.com/ariya/phantomjs/files/227875/phantom.dump.txt)
[out1.txt](https://github.com/ariya/phantomjs/files/223419/out1.txt)
[out.txt](https://github.com/ariya/phantomjs/files/223420/out.txt)

@ariya  can you please help.. I am really stuck.

**Comment by Vitallium** [comment]
Are you sure that you use PhantomJS 2.1.1? We removed crash dumps in this version.

**Comment by priyankachaturvedi** [comment]
Thanks a lot @Vitallium  for your reply , actually this dump is from my local system which have "2.0.1-development" , but my server have 2.1.1 , and there also I am getting the same Issue. Is this something related to memory? but why only outlook? as soon as I am about to get logged-In phantomjs crashes.

**Comment by priyankachaturvedi** [comment]
I think I got the cause..but not the root cause..phantomjs crashes at the loading page of outlook..If I directly open this url "**https://outlook.live.com/owa/**" which If you notice gives a page with "loader", It crashes Phantomjs.

This outlook page must be having something which phantomjs is not able to handle..I think phantomjs guys should be aware of this , if I am not wrong @ariya @Vitallium . I am at phantojs 2.1.1 (latest)
