### ISSUE TITLE
PhantomJS crashes with Segmentation Fault when it runs out of memory

### ISSUE THREAD

**Issue by SeanHayes** [ariya/phantomjs#14205]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. Write and run a script that will use up all available memory
3. Which operating system are you using?
   Linux staging.bluewonder.co 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
4. Did you use binary PhantomJS or did you compile it from source?
   binary for Linux 64-bit

Also tried phantomjs-prebuilt for node.
1. Please provide any additional information below.
   I tried running my script while in another window I monitored memory and swap with `htop`. I noticed the crash happened when both filled up. PhantomJS doesn't provide any other info except:

> 1   0x1b67967 phantomjs() [0x1b67967]
> 2   0x1b800a9 phantomjs() [0x1b800a9]
> 3   0x1b9b4d3 phantomjs() [0x1b9b4d3]
> 4   0x1ba0ad8 phantomjs() [0x1ba0ad8]
> 5   0x1ba400e phantomjs() [0x1ba400e]
> 6   0x1820fa2 phantomjs() [0x1820fa2]
> 7   0x181cab8 phantomjs() [0x181cab8]
> 8   0x7b0376 phantomjs() [0x7b0376]
> 9   0x7b0b96 phantomjs() [0x7b0b96]
> 10  0x7b0e28 phantomjs() [0x7b0e28]
> 11  0x7b0f93 phantomjs() [0x7b0f93]
> 12  0x7b10cb phantomjs() [0x7b10cb]
> 13  0x22f4fd1 phantomjs() [0x22f4fd1]
> 14  0x46c672 phantomjs(_ZN8Callback6calledERK5QListI8QVariantE+0x22) [0x46c672]
> 15  0x42100b phantomjs() [0x42100b]
> 16  0x4213b5 phantomjs() [0x4213b5]
> 17  0x421493 phantomjs() [0x421493]
> 18  0x7b6cad phantomjs() [0x7b6cad]
> 19  0x17fd966 phantomjs() [0x17fd966]
> 20  0x19db06e phantomjs() [0x19db06e]
> 21  0x19e7b07 phantomjs() [0x19e7b07]
> 22  0x19eed55 phantomjs() [0x19eed55]
> PhantomJS has crashed. Please read the bug reporting guide at
> http://phantomjs.org/bug-reporting.html and file a bug report.

I think a message indicating the cause of the error would be helpful, I spent a lot of time trying different phantomjs binaries thinking it was compiled wrong or somehow incompatible with my server.

**Comment by Batistleman** [comment]
I had the same problem on my 2G RAM Digital Ocean droplet, setting up a swap solved it for me (https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04)
