### ISSUE TITLE
Date behavior differs from Chromium's

### ISSUE THREAD

**Issue by eduardodelgaldo** [ariya/phantomjs#14200]
As per [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) specification, Date() only accepts two valid string formats, ISO8601 among them, that is _yyyy/mm/dd_. Despite of that, in Chromium `new Date('dd-mm-yyyy')` returns no errors.

In PhantomJS console:
```
new Date('01-01-2011');
# Invalid date
```
In Chromium 49.0.2623.108
```
new Date('01-01-2011');
# Sat Jan 01 2011 00:00:00 GMT-0200 (UYST)
```
Version: 2.1.1
OS: Ubuntu 14.04

Is this a expected behavior?

**Comment by Vitallium** [comment]
Duplicate. Please see https://github.com/ariya/phantomjs/issues/11151
