### ISSUE TITLE
Strace on long stuck phantom process results in lots of pselect timeout calls.

### ISSUE THREAD

**Issue by mdeora** [ariya/phantomjs#14201]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`. 2.1.1
2. What steps will reproduce the problem?
   1. did a simple webpage call.
      2.
      3.
3. Which operating system are you using? 
   Ubuntu 14.04
4. Did you use binary PhantomJS or did you compile it from source?
   Compiled from source
5. Please provide any additional information below.

Doing an strace on phantom process which is stuck for long time, prints the below continously : 

Process 11967 attached
pselect6(4, [3], [], [], {0, 4377644}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 48000000}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 0}, {NULL, 8}) = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
pselect6(4, [3], [], [], {0, 6000000}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 0}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 0}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 0}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 56000000}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 3000000}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 0}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 0}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 33000000}, {NULL, 8}) = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
pselect6(4, [3], [], [], {0, 26000000}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 57000000}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 2000000}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 0}, {NULL, 8}) = 0 (Timeout)
pselect6(4, [3], [], [], {0, 12000000}, {NULL, 8}) = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
........repeat.......
........repeat.......

Any ideas ?

**Comment by h3110w0r1d** [comment]
same problem

2.1.1

CentOS release 6.5 (Final)

Compiled from source

/opt/phantomjs/bin/phantomjs /data/www/console-1.0.22/src/Resources/phantomjs/screenshot.js http://localhost/mobilepage/html/prod/641486581/12591458802/12591458802.html /data/www/localhost/mobilepage/html/prod/641486581/12591458802/12591458802 750*580 0 0 http://localhost/mobilepage/jquery-1.11.3.min.js

**Comment by h3110w0r1d** [comment]
i think this is qt's problem

i rollback phantomjs to 1.9.7,there are no problems.

the difference between 1.9.x and 2.x is the file /src/qt/qtbase/src/corelib/kernel/qcore_unix.cpp

the qt of 2.x
```cpp
int qt_safe_select(int nfds, fd_set *fdread, fd_set *fdwrite, fd_set *fdexcept,
                   const struct timespec *orig_timeout)
{
    if (!orig_timeout) {
        // no timeout -> block forever
        int ret;
        EINTR_LOOP(ret, select(nfds, fdread, fdwrite, fdexcept, 0));
        return ret;
    }

    timespec start = qt_gettime();
    timespec timeout = *orig_timeout;

    // loop and recalculate the timeout as needed
    int ret;
    forever {
#ifndef Q_OS_QNX
        ret = ::pselect(nfds, fdread, fdwrite, fdexcept, &timeout, 0);
#else
        timeval timeoutVal;
        timeoutVal.tv_sec = timeout.tv_sec;
        timeoutVal.tv_usec = timeout.tv_nsec / 1000;
        ret = ::select(nfds, fdread, fdwrite, fdexcept, &timeoutVal);
#endif
        if (ret != -1 || errno != EINTR)
            return ret;

        // recalculate the timeout
        if (!time_update(&timeout, start, *orig_timeout)) {
            // timeout during update
            // or clock reset, fake timeout error
            return 0;
        }
    }
}
```

the qt of 1.9.x, not use pselect
```cpp
int qt_safe_select(int nfds, fd_set *fdread, fd_set *fdwrite, fd_set *fdexcept,
                   const struct timeval *orig_timeout)
{
    if (!orig_timeout) {
        // no timeout -> block forever
        register int ret;
        EINTR_LOOP(ret, select(nfds, fdread, fdwrite, fdexcept, 0));
        return ret;
    }

    timeval start = qt_gettime();
    timeval timeout = *orig_timeout;

    // loop and recalculate the timeout as needed
    int ret;
    forever {
        ret = ::select(nfds, fdread, fdwrite, fdexcept, &timeout);
        if (ret != -1 || errno != EINTR)
            return ret;

        // recalculate the timeout
        if (!time_update(&timeout, start, *orig_timeout)) {
            // timeout during update
            // or clock reset, fake timeout error
            return 0;
        }
    }
}
```

**Comment by h3110w0r1d** [comment]
now, select method also cause timeout
```
select(4, [3], [], [], {0, 83999})      = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 0})          = 0 (Timeout)
select(4, [3], [], [], {0, 83999})      = 0 (Timeout)
```

**Comment by avis7** [comment]
Have you solved this issue somehow?

**Comment by adgud** [comment]
I have the same issue on phantomjs 2.1.1, Ubuntu 16.04, phantom downloaded as binary.
