### ISSUE TITLE
svg.outerHTML unsupported?

### ISSUE THREAD

**Issue by sherburne** [ariya/phantomjs#14202]
The outerHTML for svg elements is undefined; I can get outerHTML for other HTML elements like 'div'.

I'm running the 2.1.1 Mac binary on Mac OS X 10.11.4. I haven't checked other platforms or releases.

Here's my test PhantomJS script:
`var page = require('webpage').create();
page.onError = function(m){console.log(m);phantom.exit(1);};
page.open('https://localhost/svg.html', function(){phantom.exit();});`

And the sample HTML file:
`<!DOCTYPE html><html><body><div id="mydiv">test div</div><svg id="mysvg"><text x="50" y="50">test svg</text></svg><script>if (!document.getElementById('mysvg').outerHTML){throw new Error('no outerHTML');}</script></body></html>`

The result of running the script is `Error: no outerHTML`. The script completes without errors if I swap "mydiv" for "mysvg".

**Comment by sierraindiagolf** [comment]
This also happens on windows.

**Comment by erossignon** [comment]
I found this issue as well.
A work around could to get the innerHTML of the parent element:
```
document.getElementById('mysvg').parentElement.innerHTML
```
