### ISSUE TITLE
Array.from() with NodeList causes TypeError

### ISSUE THREAD

**Issue by julmot** [ariya/phantomjs#14216]
### 1. Which version of PhantomJS are you using?
2.1.5

### 2. What steps will reproduce the problem?

In a Babel generated code I have something like that:

```javascript
Array.from(document.querySelectorAll("*"));
```

`document.querySelectorAll("*")` returns a `NodeList`. PhantomJS will fail with this code.

```bash
TypeError: undefined is not a constructor (evaluating 'Array.from(document.querySelectorAll("*"))')
```

### 3. Which operating system are you using?
Windows 7

### 4. Did you use binary PhantomJS or did you compile it from source?
I am using Karma, which acutally needs phantomjs-prebuilt. So I am not using phantomjs directly.

**Comment by julmot** [comment]
@ariya

**Comment by Vitallium** [comment]
ES6 features are not supported in PhantomJS yet.

**Comment by julmot** [comment]
@Vitallium Thank you for your answer!

This is quite funny, because as I already said, this is a part of a _Babel generated code_. 
When using

```javascript
var arr = [...theNodeList]
```

to convert a `NodeList` to an `array`, the following (including `Array.from()`) will be generated, even when using the es2015 preset:

```javascript
function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

var arr = _toConsumableArray(theNodeList);
```
I have taken this way of conversion from the [docs](https://developer.mozilla.org/de/docs/Web/API/NodeList).

So, as you already mentioned that `Array.from()` is part of ES6, it is funny that Babel generates a ES6 code to workaround ES6. I will open an issue for that...

**Comment by julmot** [comment]
Can be tracked here https://phabricator.babeljs.io/T7305

**Comment by ariya** [comment]
In the mean time, please track ES6 support in #14506. Thank you!
