### ISSUE TITLE
PhantomJS spawns many child processes

### ISSUE THREAD

**Issue by maxpmaxp** [ariya/phantomjs#14214]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   PhantomJS v2.1.1 + selenium 2.53.1 + python 2.7
2. What steps will reproduce the problem?

I'm starting PhantomJS (v2.1.1) with Selenium (v2.53.1) in my python code. Newly created process spawns 19-20 child PhantomJS processes right after start.

Here comes what I did:

```
>>> from selenium import webdriver
>>> dcap = webdriver.DesiredCapabilities.PHANTOMJS.copy()
>>> dcap["phantomjs.page.settings.userAgent"] = "Some UA string"     
>>> b = webdriver.PhantomJS(desired_capabilities=dcap)
>>> b.service.process.pid
28304
```

After that I checked all the children of 28304 with pstree and saw:

```
> sudo pstree -p 28304
phantomjs(28304)─┬─{phantomjs}(28305)
                 ├─{phantomjs}(28306)
                 ├─{phantomjs}(28307)
                 ├─{phantomjs}(28308)
                 ├─{phantomjs}(28309)
                 ├─{phantomjs}(28310)
                 ├─{phantomjs}(28311)
                 ├─{phantomjs}(28312)
                 ├─{phantomjs}(28313)
                 ├─{phantomjs}(28314)
                 ├─{phantomjs}(28315)
                 ├─{phantomjs}(28336)
                 ├─{phantomjs}(28337)
                 ├─{phantomjs}(28338)
                 ├─{phantomjs}(28339)
                 ├─{phantomjs}(28340)
                 ├─{phantomjs}(28341)
                 ├─{phantomjs}(28342)
                 └─{phantomjs}(28343)
```
1. Which operating system are you using?
   Ubuntu 14.04.1 LTS (GNU/Linux 4.5.0-x86_64-linode65 x86_64)
2. Did you use binary PhantomJS or did you compile it from source?
   Binary
3. Please provide any additional information below.
   Is this an issue? How can I decrease the number of children to decrease memory usage?

**Comment by jamb0ss** [comment]
I'm pretty sure, that you see child threads, not processes

**Comment by maxpmaxp** [comment]
There is no huge difference and this changes nothing. `ps` says all of the above are `phantomjs` instances. PhantomJS starts these subprocesses by default and this sufficiently increases memory usage. Is there a way to decrease the number of threads or get rid of them at all?

**Comment by stalehard** [comment]
I have same problem. I solved her with help dirty method - run "killall phantomjs" as a shell command in end my script.

**Comment by jamb0ss** [comment]
It's not a PhantomJS instances, but its threads. And it's a big difference (processes vs threads). I'm not sure, but it sounds impossible to make such thing work in single thread by design.
