### ISSUE TITLE
Can't download binary files using curl / wget

### ISSUE THREAD

**Issue by icy** [ariya/phantomjs#14212]
The download page https://bitbucket.org/ariya/phantomjs/downloads is now protected by some mechanism, and that breaks all Docker builds that use `wget/curl` to download phantomjs binary.

Please allow us to download binary files from your page. We are working from the Linux shell, and *we are not human*!

**Comment by thuandt** [comment]
How about change `User-Agent`, maybe it can help you :)

**Comment by icy** [comment]
@thuandt  I tried and it didn't help at all :(

**Comment by icy** [comment]
The links seems to work now (I didn't change anything on my client).

Let's see if that happens again.

Thanks!

**Comment by ariya** [comment]
Duplicate of #13953.
