### ISSUE TITLE
For some url to scrap (by phantomjs) dont return the exact content. 

### ISSUE THREAD

**Issue by sudiptokarmoker** [ariya/phantomjs#14226]
I have deployed an app on heroku written by phantomjs. Actually we are using this for scraping website images. It was working but the problem is for some URL it is getting problem. For example for this url 

http://theultralinx.com/2012/10/random-inspiration-51-architecture-cars-girls-style-gear/

When i go for scrap page content (by phantomjs), it does not return the exact content. And then if try again after page refresh it can then give the page content result. Some time if i try for 2 - 3 times then i can get the page content. But i need the 100% result on each request.

Is there anyone to help me for this issues. i am just using 
page.open method to get the content. but sometime for some url its not working properly. But i need to e sure 100% that on each request it will give the content.

**Comment by deepsh91** [comment]
Did you find any solution?

**Comment by sudiptokarmoker** [comment]
Yes finding the solution for this. That is, why phantomjs could not always return the perfect results. But sometimes it can. Now i am using casperjs. This output is much better than phantomjs scraping. Do you have any suggestion for this ?

**Comment by deepsh91** [comment]
I am experiencing a similar problem. May be I should give casperjs a try.

**Comment by sudiptokarmoker** [comment]
Yes you can. That is much better than that. Also i am not expert on this technology. May be i dont have the robust scraping code on phantomjs. But according to my experience casperjs is getting much good result. It is not 100% perfect. But it is giving good result.
