### ISSUE TITLE
Phantomjs taking upto 90% of CPU

### ISSUE THREAD

**Issue by sbsomya** [ariya/phantomjs#14227]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. Run a phantomjs long process 
   2. phantomjs taking 90% of cpu
      3.
3. Which operating system are you using? 
   ubuntu 14.1
4. Did you use binary PhantomJS or did you compile it from source?
   I did npm install phantomjs2
5. Please provide any additional information below.

**Comment by gouchaoer** [comment]
i had the same problem.
in my case, phantomjs is managed by selenium.
doing the same job, 1/100 phantomjs process will crash and take up 100% cpu.
i suggest you use a daemon to monitoring all system process and kill crashed phantomjs process.

**Comment by ariya** [comment]
@sbsomya What's the best way to reproduce it? Without it, it's almost impossible for us to troubleshoot the problem.

**Comment by sbsomya** [comment]
Was taking screenshots of a website every 40 ms for atleast 5 secs and checked the CPU usage it was taking around 90% of CPU

**Comment by gouchaoer** [comment]
check this issue:https://github.com/ariya/phantomjs/issues/14334
