### ISSUE TITLE
Dont create event onFileDownload

### ISSUE THREAD

**Issue by bitset** [ariya/phantomjs#14238]
1. PhantomJS version 2.1.1 Linux 64bit

2. What steps will reproduce the problem?
See "5. Test code".

3. Which operating system are you using?
Debian 8

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Test code:
var page = require('webpage').create();

page.onResourceReceived = function(status) {
  console.log('onResourceReceived: ' + JSON.stringify(status));
  if(status.stage === 'end') {
    phantom.exit(0);
  }
}

page.onResourceRequested = function(requestData, networkRequest) {
  console.log('onResourceRequested(' + JSON.stringify(requestData) + ')');
}

page.onFileDownload = function(status) {
	console.log('onFileDownload(' + status + ')');
	return 'sample.pdf';
}

page.onFileDownloadError = function(status) {
	console.log('onFileDownloadError(' + status + ')');
};

page.open('http://www.cbu.edu.zm/downloads/pdf-sample.pdf');

**Comment by Vitallium** [comment]
Sorry but this feature is not implemented yet
