### ISSUE TITLE
ISO8601 Date parsing fail

### ISSUE THREAD

**Issue by ulrik59** [ariya/phantomjs#14237]
1. Which version of PhantomJS are you using? 
   **2.1.7**
2. What steps will reproduce the problem?
  **`new Date("2016-03-24T17:50:00+0100")` will return an `'Invalid Date`'**
3. Which operating system are you using?
 **Ubuntu 15.10**
4. Did you use binary PhantomJS or did you compile it from source?
 **binary**
5. Please provide any additional information below.
 **I am using karma-phantomjs-launcher 1.0.0 with phantomjs-prebuilt 2.1.7**

**Comment by Vitallium** [comment]
Duplicate. Please see #11151
