### ISSUE TITLE
Error shown when connected to socket 

### ISSUE THREAD

**Issue by jpicornellHB** [ariya/phantomjs#14232]
**1. Which version of PhantomJS are you using?** 2.1.1

**2. What steps will reproduce the problem?**
1. Launch karma for testing angularjs 2
2. Launch the PhantomJS with npm module "karma-phantomjs-launcher"
3. Get an unspecified error

*_3. Which operating system are you using? *_
Redhat 7.2 Maipo

**4. Did you use binary PhantomJS or did you compile it from source?**
binary

**5. Please provide any additional information below.**
console output:
1   0x1b67967 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1b67967]
2   0x1b800a9 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1b800a9]
3   0x1836fc7 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1836fc7]
4   0x1aa5fb1 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1aa5fb1]
5   0x1986fbd ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1986fbd]
6   0x1a8ea33 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1a8ea33]
7   0x79da8e ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x79da8e]
8   0x79e042 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x79e042]
9   0x170c3c0 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x170c3c0]
10  0x866340 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x866340]
11  0x8668c6 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x8668c6]
12  0x866b88 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x866b88]
13  0x85682a ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x85682a]
14  0x8a24d5 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x8a24d5]
15  0x8f72bd ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x8f72bd]
16  0xaefa23 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0xaefa23]
17  0xaef5b0 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0xaef5b0]
18  0xaefd0f ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0xaefd0f]
19  0x22f4ace ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x22f4ace]
20  0x1f5d971 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1f5d971]
21  0x1fc2aed ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1fc2aed]
22  0x22f8aee ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x22f8aee]
23  0x4ac3bc ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x4ac3bc]
24  0x4b0000 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x4b0000]
25  0x22d3f70 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x22d3f70]
26  0x2314598 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x2314598]
27  0x1bbf4b5 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1bbf4b5]
28  0x22cf7a9 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x22cf7a9]
29  0x22d4585 ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x22d4585]
30  0x415b9a ../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x415b9a]
31  0x7f4a27e89b15 /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f4a27e89b15]
PhantomJS has crashed. Please read the bug reporting guide at
http://phantomjs.org/bug-reporting.html and file a bug report.

**Comment by brophdawg11** [comment]
We also see this issue, intermittently, using `karma-phantomjs-launcher 1.0.0/phantomjs-prebuilt 2.1.7` running `angular 1.4.7` unit tests in a Jenkins CI environment running:

```
CentOS release 6.6 (Final)
Linux aa7b83f27f8e 2.6.32-642.1.1.el6.x86_64 #1 SMP Tue May 31 21:57:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

It doesn't seem to have a reliable pattern of failing through.  Sometimes it'll fail 3-4 time sin a row, others it won't happen for 5-10 builds straight.  Any input would be greatly appreciated!
