### ISSUE TITLE
Screenshot taking 120 ms of time

### ISSUE THREAD

**Issue by sbsomya** [ariya/phantomjs#14236]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. Check the time difference between before taking the screenshot and after it
  2.
  3.

3. Which operating system are you using?
ubuntu 14
4. Did you use binary PhantomJS or did you compile it from source?
I use [node-horseman](https://github.com/johntitus/node-horseman)
5. Please provide any additional information below.
Refer to this issue for more details
https://github.com/johntitus/node-horseman/issues/166

**Comment by ariya** [comment]
Care to elaborate? What else do you expect to see rather than 120ms rendering time?

**Comment by sbsomya** [comment]
Actually have a requirement to take screenshots in every 40 ms 
So dont want to waste the time or else execute it in a separate thread

**Comment by ariya** [comment]
Unfortunately, it is impossible to limit the screenshot time since it depends on many factors (and other technical limitations) that PhantomJS do not control.
