### ISSUE TITLE
Increase logging in PhantomJS

### ISSUE THREAD

**Issue by luisperezphd** [ariya/phantomjs#14233]
1) Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

**2.1.1**

2) What steps will reproduce the problem?

1. **Using IWebDriver find element by id (it's an <a href="url"></a>)**
2. **Call Click() on that element**
3. **Half the time nothing happens**

3) Which operating system are you using?

**Windows 8.1 Pro**

4) Did you use binary PhantomJS?

**Yes, binary. From NuGet package: https://www.nuget.org/packages/PhantomJS/2.1.1**

5) Additional information

**How do I increase the logging from PhantomJS to get more detail into what's going on?**

**Most of the Selenium scripts work fine. One particular link when it's clicked on works sometimes and sometimes now. I'm trying to get a better sense of what's happening behind the scenes.**

**I couldn't find any command line options that would increase the amount of logging.**

**Thanks in advance for any help**

**Comment by Vitallium** [comment]
You can pass `--debug=yes` to enable additional debug messages.

**Comment by Vitallium** [comment]
@luisperezphd I've also updated our command line reference. Sorry for the inconvenience!

**Comment by luisperezphd** [comment]
Thank you Vitallium !!!
