### ISSUE TITLE
phantomjs failed on python run-test.py on module/webpage/keypress-event

### ISSUE THREAD

**Issue by michelmno** [ariya/phantomjs#14230]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   last git commit: phantomjs-2.1.1+git20160411.d038837 
2. What steps will reproduce the problem?
   1. retrieve the phantomjs from openSUSE OBS from https://build.opensuse.org/package/show/home:michel_mno:branches:devel:languages:nodejs/phantomjs
   2. build phantomjs
   3. cd test; python run-test.py

```
===
$osc build --alternative-project=openSUSE:Factory:PowerPC
$osc chroot --alternative-project=openSUSE:Factory:PowerPC
...
abuild@twppc64le:~> cd rpmbuild/BUILD/phantomjs-2.1.1+git20160411.d038837/test/
abuild@twppc64le:~/rpmbuild/BUILD/phantomjs-2.1.1+git20160411.d038837/test>  python run-tests.py
...
module/webpage/keypress-event: FAIL
FAIL: key press events
  assert_equals: expected "ABCD" but got ""
  phantomjs://code/keypress-event.js:64:18
 0.369s elapsed
    1 failed
===
```
1. Which operating system are you using?
   either x86_64 or ppc64le
2. Did you use binary PhantomJS or did you compile it from source?
   compilation from source tarball as detailed in 2.
3. Please provide any additional information below.
   I am not familiar with phantomjs, so do not know how to add traces to help for investigation.

**Comment by vaibhi9** [comment]
I am also facing same issue. plz help

**Comment by zaid-golwala** [comment]
Any update on the above issue?

**Comment by anujajakhade** [comment]
Can you check if you have installed the packages 

`xorg-x11-utils xorg-x11-font-utils xorg-x11-fonts-Type1.noarch xorg-x11-devel  libXfont libXfont-devel`

Installing the above packages resolved the issue for me,
