### ISSUE TITLE
The rasterization of a SVG is crashing phantomjs 2.1.1 (small example included)

### ISSUE THREAD

**Issue by gaa-cifasis** [ariya/phantomjs#14244]
I'm using PhantomJS 2.1.1 (downloaded from [here](https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2))

To reproduce:
1.  Download [this svg file](https://gist.githubusercontent.com/gaa-cifasis/b123cb1c85f27cba51a1968ea9631a83/raw/ba2b24a6913cb6e12b430a49f50e1d40a152a493/crash.svg).
2. Execute:
   
    ./bin/phantomjs examples/rasterize.js crash.svg out.png
     PhantomJS has crashed. Please read the bug reporting guide at
    http://phantomjs.org/bug-reporting.html and file a bug report.
    Segmentation fault

Using gdb you can check is a null pointer derreference but the real cause is unknown. I don't have the symbols ..

This was tested in Ubuntu 14.04 (x86_64). It was found using [QuickFuzz](http://QuickFuzz.org).

Regards,
Gus.

**Comment by Alexislavie** [comment]
I encounter the same issue, did you try to run PhantomJS in debug mode?

`phantomjs --remote-debugger-port=9000 --remote-debugger-autorun=yes`

This issue might be related: #14659.

**Comment by mr-moon** [comment]
Getting the same issue. Will do our homework and come back.
