### ISSUE TITLE
QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by samcontesse** [ariya/phantomjs#14240]
1. Which version of PhantomJS are you using?
Version 2.1.1

2. What steps will reproduce the problem?
  1. Open a shell
  2. Type `phantomjs`
  3. Press enter

3. Which operating system are you using?
Ubuntu 16.04 LTS

4. Did you use binary PhantomJS or did you compile it from source? 
Binary from the official Ubuntu repository - version 2.1.1+dfsg-1

5. Please provide any additional information below.
This is a fresh install, no X11 library has been installed (headless).
```
QXcbConnection: Could not connect to display 
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Aborted
```

**Comment by Vitallium** [comment]
1) We don't support official packages from repositories for distros. Because they are usually modified. Like this one.
2) Dependencies list of this package contains excess packages that are not needed to build PhantomJS:

	libjs-coffeescript
	libx11-dev,
	libxext-dev,
	libqt5webkit5-dev,

**Comment by samcontesse** [comment]
Thank you for your help. The official Linux 64-bit build works as expected.

**Comment by zackw** [comment]
For future reference, this sort of breakage is caused by compiling PhantomJS against a system-supplied QtBase instead of our bundled version, *which has been substantially modified*.

**Comment by Vitallium** [comment]
@zackw for future reference, Qt 5.6 is bundled with `offscreen` platform, which we can use in PhantomJS to build against system-supplied Qt :-)

**Comment by hashar** [comment]
The Debian bug is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=817277
