### ISSUE TITLE
Phantomjs scales/zooms page when creating PDF in Azure Worker Role

### ISSUE THREAD

**Issue by hisuwh** [ariya/phantomjs#14243]
Phantom version 2.1.1

This might be too specific for a Github issue but every avenue of investigation I have explorer has got me nowhere.

**The scenario**
- Microsoft Azure worker role
- Phantomjs installed as nuget package
- Running phantom process from worker role to convert given webpage to pdf
- viewport size is hard coded in rasterize.js
- setting page size to A4 in arguments

**The Problem**
- The page is scaled/zoomed which results in the edges being cropped off the page
- Setting the zoomFactor does not counter this (or work at all)

**Observations**
- I have RDPd on to the worker role and ran phantomjs through the command line - this produces a normal output
- I have created a console application that runs the phantom process and ran it both locally and on the worker role - this produces a normal output
- I have ran the worker role in the compute emulator locally - this produces a normal output
- I have tried changing the region of my PC to US (to match azure and as opposed to UK) - this produces a normal output

Any help or ideas what so ever would be greatly appreciated.

**Comment by Vitallium** [comment]
I think it should be fixed in the `master` branch.

**Comment by hisuwh** [comment]
Is this a known issue then?
Do you know when the next release is due?
