### ISSUE TITLE
Windows Download is broken...

### ISSUE THREAD

**Issue by AcousticGuitar** [ariya/phantomjs#14256]
To recreate go to PhantomJS main site click on Windows download, you will see this...
 
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2016-05-03T21:38:29Z</Expires>
<ServerTime>2016-05-03T21:42:56Z</ServerTime>
<RequestId>11824CDC281719E9</RequestId>
<HostId>
dqBKNwJVcapk7d+Iq9DclDv8fqQ9zc0fifLFmows6ZokUPzs9pxj3Q3v9L9BGUhPzEgyLBWF+MI=
</HostId>
</Error>

**Comment by Vitallium** [comment]
Duplicate
