### ISSUE TITLE
Can't download Windows Phantom.js, error sez:  

### ISSUE THREAD

**Issue by AcousticGuitar** [ariya/phantomjs#14255]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2. What steps will reproduce the problem?
  1.
  2.
  3.

3. Which operating system are you using?

4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.

**Comment by AcousticGuitar** [comment]
Windows download link is not working

<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2016-05-03T21:38:29Z</Expires>
<ServerTime>2016-05-03T21:42:56Z</ServerTime>
<RequestId>11824CDC281719E9</RequestId>
<HostId>
dqBKNwJVcapk7d+Iq9DclDv8fqQ9zc0fifLFmows6ZokUPzs9pxj3Q3v9L9BGUhPzEgyLBWF+MI=
</HostId>
</Error>

**Comment by Vitallium** [comment]
Hi. Thank you for opening this issue. But this is not a PhantomJS issue. This is a problem with BitBucket CDN. We're working on moving to another service to serve downloads. 

You can check this issue #13953 for more info.
