### ISSUE TITLE
phantomjs doesn't focus <label> elements even with tabindex

### ISSUE THREAD

**Issue by edenpessach** [ariya/phantomjs#14250]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. Create an chronological list of tabindex element (I checked with inputs)
   2. Make sure one of them is a <label> element
   3. Send Keydown Tab event and check which is the document.activeElement
   4. Watch as <label> is ignored
3. Which operating system are you using?
   OS X Yosemite
4. Did you use binary PhantomJS or did you compile it from source?
   binary
5. Please provide any additional information below.
   I am using a dialog that contains few inputs and a label and tab through them.
   Using chrome, it works perfectly, when switching to phantom it ignores the label element even though it has the next tabindex value.

Specifically I am using protractor over an Angularjs application.
I have reproduced the problem using only native phantomjs, so protractor isn't the cause.

Illustration:

```
<input tabindex="1"/>
<input tabindex="2"/>
<label tabindex="3">some text</label>
<input tabindex="4"/>
```

Sending 4 tab keydown events, focus will go: 1 -> 2 -> 4 -> 1

**Comment by antgonzales** [comment]
+1

**Comment by coderas** [comment]
+1
