### ISSUE TITLE
Different PDF output for local environment (windows) and server (linux)

### ISSUE THREAD

**Issue by yanivlllev** [ariya/phantomjs#14263]
I'm having an issue with different PDF output for my localhost environment and the live server environment.. 
The code is the same, the phantomjs version is the same (2.1.3) - but the desirable output on local isn't what i get on the server:
![1st_frame](https://cloud.githubusercontent.com/assets/12447235/15106112/b25c1546-15cf-11e6-97d9-f5ab961f06be.jpg)
the page definitions for pdf rendering are:

```
page.viewportSize = { 
   width: 1440, 
   height: 900 
};
page.paperSize =  { 
   format: 'A4', 
   orientation: 'portrait',  
   margin: '0.2cm' 
};
```

The only thing i can think of is that the server runs linux and I run windows on my localhost..
any ideas what to do?
(btw, I tried playing with the zoomFactor, but it doesn't have any effect whatsoever)

**Comment by nicholascowan** [comment]
This is because of differing DPI between Windows and Linux. New property page.settings.dpi was recently added to allow you to set one manually, but is not yet available in latest. Either compile the latest in master yourself or wait for new release.

**Comment by yanivlllev** [comment]
thanks for the quick reply. is there any ETA for the new release?

**Comment by nicholascowan** [comment]
Last I heard: Soon™.

**Comment by bettiolo** [comment]
I think that this has been fixed?

**Comment by yale8848** [comment]
i find 2.1.2 release, binary not ready  to download

**Comment by evertondanilo** [comment]
I'm also having the same issue, any solution?

**Comment by yale8848** [comment]
@evertondanilo @elyssonmr  you can try https://github.com/GoogleChrome/puppeteer , puppeteer is ok
