### ISSUE TITLE
Undeclared variables in examples/rasterize.js

### ISSUE THREAD

**Issue by keiranmraine** [ariya/phantomjs#14260]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

Bug is in example js file rasterize.js

2. What steps will reproduce the problem?
  1. phantomjs examples/rasterize.js <someweb-page> images/001.png '1200*1000px'

5. Please provide any additional information below.

2 of the variables aren't declared, only complains when you use the 'px' code route

**Comment by Vitallium** [comment]
Duplicate. See #13976
