### ISSUE TITLE
Alpine Linux support (musl libc) on prebuilt phantomjs

### ISSUE THREAD

**Issue by ricoli** [ariya/phantomjs#14265]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. Run ```phantomjs -v``` on alpine linux

3. Which operating system are you using?
Alpine linux 3.3

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
So it seems the binary requires glibc in order to work - any plans to make the binary work on musl libc, so that it can work on the popular alpine linux distro?

**Comment by ariya** [comment]
It could be a huge undertaking.
In all cases, better track this at the upstream bug: [QTBUG-46543](https://bugreports.qt.io/browse/QTBUG-46543).
