### ISSUE TITLE
Crashes during Ruby on Rails/Cucumber testing

### ISSUE THREAD

**Issue by resgraph** [ariya/phantomjs#14269]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   1.9.8.0
2. What steps will reproduce the problem?
   1. Dies within our cucumber features suite
   2. I don't believe there is a way for you to reproduce this
      3.
3. Which operating system are you using?
   Description:    Ubuntu 12.04.5 LTS
   Release:    12.04
   Codename:   precise
4. Did you use binary PhantomJS or did you compile it from source?
   Binary
5. Please provide any additional information below.

Happens for both Ruby 2.3.0 and 2.3.1.

```
  PhantomJS client died while processing {"id":"d9cd1fb2-2075-4ae1-bcf0-8d8a4a8ea249","name":"visit","args":["http://127.0.0.1:56218/users/sign_in",60]} (Capybara::Poltergeist::DeadClient)
  /home/ubuntu/leatherman/vendor/bundle/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/server.rb:38:in `send'
```

[phantomjs-stack-trace.txt](https://github.com/ariya/phantomjs/files/258404/phantomjs-stack-trace.txt)

**Comment by tjshipe** [comment]
Did you figure out what the issue was?

**Comment by resgraph** [comment]
I fixed the issue by down-revving phantom-js, but never found out the cause of the issue. Sorry, about not closing this.
