### ISSUE TITLE
change default version for SSL

### ISSUE THREAD

**Issue by valugi** [ariya/phantomjs#14264]
> -ssl-protocol=[sslv3|sslv2|tlsv1|any']  sets the SSL protocol for secure connections (default is SSLv3).

I suggest changing the default version to `tlsv1`.  SSLv3 is [not secure since 2014](https://blog.mozilla.org/security/2014/10/14/the-poodle-attack-and-the-end-of-ssl-3-0/) and Apache does not even accept it.

**Comment by zackw** [comment]
We were waiting for a mode matching what "normal" browsers currently do (TLS 1.1 or later, essentially) to become supported in Qt.  It looks like this happened in Qt 5.6.  @Vitallium, are we there yet?

**Comment by Vitallium** [comment]
@zackw not yet. Qt 5.6 has a problem with QPA builds. I'm waiting for 5.6.1 release.

**Comment by JamesBelchamber** [comment]
Is there any reason the default shouldn't be 'any'? (We hit this today as well)
