### ISSUE TITLE
Building from source - 3rdparty software missing.

### ISSUE THREAD

**Issue by drook** [ariya/phantomjs#14276]
When building from source 3rdparty software directories are empty. No instructions are privided on how to obtain such software. build.sh crashes immidiately after discovering empty qt base.

**Comment by Vitallium** [comment]
Please provide more information.

And, please, don't remove the issue template and fill it. It will help us.

**Comment by drook** [comment]
Seems like I was having some local troubles in the enviromnent. Sorry for disturbing, the 3rdparty software is now checking out just fine.
