### ISSUE TITLE
Crash report 

### ISSUE THREAD

**Issue by vitxd** [ariya/phantomjs#14270]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
1.9.7
2. What steps will reproduce the problem?
Using the same script, crashes in different places every time I run it. the message appearing before the crash is always: `pure virtual method called`

3. Which operating system are you using?
centos6
4. Did you use binary PhantomJS or did you compile it from source?
binary from npm
5. Please provide any additional information below.
[phantomjs_dump.txt](https://github.com/ariya/phantomjs/files/258709/phantomjs_dump.txt)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
