### ISSUE TITLE
version 2.1.1 can't catch some kind of javascript errors

### ISSUE THREAD

**Issue by catalsdevelop** [ariya/phantomjs#14279]
hi 
phantomjs version 2.1.1

code:

```
var webpage = require('webpage');
var page = webpage.create();
page.onError = function(message){
    console.log(message)
}
page.onConsoleMessage = function(message){
    console.log(message)
}
page.open('https://www.catals.com/test/test.html', function(){
    setTimeout(function(){
        phantom.exit();
    }, 3000);
});
```
sample url

1. http://sale.jd.com/act/NyTxIgU4XM1iGaOc.html
2. http://sale.jd.com/m/act/AY3pEOVBqdcGRi.html
3. https://www.catals.com/test/test.html

url1 contains an inline error
url2 and url3 contains an external error
url1 and url2 have a same error

result is 
url1 url2 can't catch
url3 worked fine

Is my code something wrong or is this a bug? @Vitallium @zackw

**Comment by Vitallium** [comment]
I think it was fixed in master.

**Comment by catalsdevelop** [comment]
Thx @Vitallium  i will try later. if worked fine, i will close this issue.

**Comment by catalsdevelop** [comment]
hi @Vitallium. I used master code to compile phantomjs on centos 6.7. Compiled version is 2.2.0-development, and page error didn't capture as before.
