### ISSUE TITLE
Fail to compile from source on Windows

### ISSUE THREAD

**Issue by iradul** [ariya/phantomjs#14287]
I'm trying to compile PhantomJS from source using latest master branch but _qtwebkit_ build fails. @Vitallium I see that you upgraded _qtbase/phantomjs_ to [5.6.0](https://github.com/Vitallium/qtbase/commits/phantomjs). Have you been able to compile Phantom on Windows?

Flowing error might be related to https://bugreports.qt.io/browse/QTBUG-50607
```
        link /NOLOGO /DYNAMICBASE /NXCOMPAT /INCREMENTAL:NO /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144cc
f1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:..\..\bin\jsc.exe @C:\Users\IRADUL~1\AppData\Local\Temp\nm393E.tmp
LINK : fatal error LNK1181: cannot open input file '\OPT:REF.obj'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\link.EXE"' : return code '0x49d'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '(' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.

ERROR: Failed to build PhantomJS! Building Qt WebKit failed.
```

**Comment by Vitallium** [comment]
@iradul hi! Yes, I've upgraded QtBase and QtWebkit to 5.6. About this problem: it was fixed in branch `phantomjs`. Try to pull QtWebkit and QtBase manually and run the build script with `--skip-git`

**Comment by iradul** [comment]
Awesome! Great work!
You are right. My QtWebkit was outdated. It's still compiling but looks good so far.

Thanks for super quick reply :+1:

**Comment by iradul** [comment]
It worked. The only thing I had to fix was to update [this](https://github.com/ariya/phantomjs/blob/master/src/phantomjs.pro#L2) line to reflect 5.6 version update.

**Comment by Vitallium** [comment]
@iradul yes, I didn't update the PhantomJS's master branch. Will do it today.

**Comment by beginnerg** [comment]
Hello,
I have the same problem, but I'm not very familiar with compiling, but I like to learn.
Can you describe me, how you have updated to 5.6?

Thank you very much for your help!
