### ISSUE TITLE
Page.renderBuffer is undefined

### ISSUE THREAD

**Issue by OrKoN** [ariya/phantomjs#14285]
`phantomjs --version` === `2.1.1`
1. Run the following file:

```
var server = require('webserver').create();

var listening = server.listen(8001, function(request, response) {
  var url = "http://phantomjs.org", format = 'png', quality = -1;

  var page = require('webpage').create();

  page.viewportSize = {
    width: 800,
    height: 600
  };

  page.open(url, function start(status) {
    try {

      // Buffer is an Uint8ClampedArray
      var buffer = page.renderBuffer(format, quality);

      response.statusCode = 200;
      response.headers = {
        "Cache": "no-cache",
        "Content-Type": "image/" + format
      };
      page.close();

      // Pass the Buffer to 'write' to send the Uint8ClampedArray to the client
      response.write(buffer);
      response.close();
    } catch (err) {
      console.log(err);
    }
  });

});
```

Taken from here: http://phantomjs.org/api/webpage/method/render-buffer.html

The result is: 

`TypeError: undefined is not a function (evaluating 'page.renderBuffer(format, quality)')`

Ubuntu 16.04, binary version

**Comment by aviceinc** [comment]
typeof(page.render(QString,QVariantMap))=function
typeof(page.render(QString))=function
typeof(page.renderBase64(QByteArray))=function
typeof(page.renderBase64())=function

"page.renderBuffer" method undefined !!!!

**Comment by wildlyinaccurate** [comment]
The docs are slightly ahead. The feature is in #13345, which hasn't been merged yet.

**Comment by yhBluescape** [comment]
If possible may I know when the merge for renderBuffer will be,...

Thanks,

**Comment by screenmeet** [comment]
Any updates here? This has been open ~6 months now...

**Comment by vsesh** [comment]
Hi! What about this issue?

**Comment by djanowski** [comment]
ROFL. A simple comment on the non-existing `renderBuffer` method's documentation would save everyone (maintainers included) so much time.

**Comment by artureg** [comment]
It seems phantomjs looks like piece of shit.

**Comment by Mnuzz** [comment]
@wildlyinaccurate username checks out, docs are more than slightly ahead

**Comment by TimYi** [comment]
We need renderBuffer method, when can this method be implemented?

**Comment by dlgoodchild** [comment]
+1

**Comment by artureg** [comment]
> We need renderBuffer method, when can this method be implemented?

newer
