### ISSUE TITLE
 PhantomJS can support AMD and MVVM ???

### ISSUE THREAD

**Issue by 1-0-2-3** [ariya/phantomjs#14288]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
1.9.8
2. What steps will reproduce the problem?
  1.open a page url
  2.waitforSelector
 then failed.

the page is based on AMD import.the page couldn't be fully rendered;Why?
and pantomjs 1.9.8 can support MVVM framework such as Angular、Vue?

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
