### ISSUE TITLE
Jasmine fixtures not loading

### ISSUE THREAD

**Issue by darrensw777** [ariya/phantomjs#14297]
In Jasmine I am adding a fixture as below:

    jasmine.getFixtures().fixturesPath = '/';

    var fixture = readFixtures('test2.html');
    setFixtures(fixture);

The tests run fine in the browser.

However, when I try to run the tests using PhantomJS (version 2.1.1) I get the following error:

    Network - Resource request error: QNetworkReply::NetworkError(ContentNotFoundError) ( "Error opening /test2.html: No such file or directory" ) URL: "file:///test2.html?_=123456789

It's as if PhantomJS cannot read the correct relative file path.

Is there anything I can do differently to get past this error?

**Comment by zackw** [comment]
jasmine.getFixtures().fixturesPath = '/';
    // ...
    Error opening /test2.html: No such file or directory

You set it to look for fixtures in the directory '/', and that is what it did.  Try '.' instead.

In the future please post requests for help to the PhantomJS mailing list.  The bug tracker is only for *definite* bugs.

**Comment by darrensw777** [comment]
The jasmine tests run perfectly in the browser but fail with setting the fixtures path, as you suggested, to '.', as they should, that's just wrong.

Therefore, they also fail with PhantomJS.

The fixture is at web root hence my setting the path there.

**Comment by zackw** [comment]
Yes, but when you load pages from `file:` URLs, the "web root" is the root directory of the filesystem.  PhantomJS has no way of knowing how your webserver is configured.  You will probably find that your tests work, unmodified, if you point PhantomJS at a test webserver (as you are presumably doing for in-browser tests) rather than at files.

**Comment by darrensw777** [comment]
Thanks for the reply. If I run 'phantomjs runTest.js /path/to/my/SpecRunner.html' isn't that what I'm doing? Pointing at server I mean

**Comment by zackw** [comment]
No, pointing at server would be `phantomjs runTest.js http://server.example/my/SpecRunner.html` - the URL would be the same one you put into your browser for the in-browser tests.

**Comment by darrensw777** [comment]
Great! Thanks, although it's still not working as phantomjs simply hangs and does nothing whereas the browser produces the results as it should, but at least this has solved the fixtures issue. Appreciated!
