### ISSUE TITLE
Poor wi-fi performance every 13 seconds

### ISSUE THREAD

**Issue by andris-silis** [ariya/phantomjs#14296]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   Start phantomjs and leave it running
3. Which operating system are you using?
   OSX 10.11.4
4. Did you use binary PhantomJS or did you compile it from source?
   Binary from npm phantomjs-prebuilt@2.1.7
5. Please provide any additional information below.

These guys had the same issue: https://github.com/owncloud/client/issues/4294

Console "Diagnostic and Usage Messages" log is filled with the following

```
19.05.16 09:35:10,050 airportd[66]: com.apple.message.domain: com.apple.wifi.internal.scanning
com.apple.message.error: No Error
com.apple.message.duration: 3
com.apple.message.process_name: phantomjs
com.apple.message.mac_address: ac:bc:32:b2:ff:69
SenderMachUUID: D1FCF015-F884-34A4-87C2-5D94E1EBC21D
```

In System log

```
19.05.16 09:36:34,126 airportd[66]: SecTaskLoadEntitlements failed error=22
```

Ping to wifi router usually is 1-3ms but at these moments it drops to around 100ms. It affects network speed and calls in Google hangouts etc are performing really bad.

**Comment by moos** [comment]
Possibly related to Qt issue during GC? https://groups.google.com/forum/#!topic/golden-cheetah-users/fsMM-LvvFQc

I'm seeing wifi-scanning (once) on exiting phantom REPL - takes about 5 secs to exit.  With wifi off, exits immediately.  Found while investigating why tests are running so slow! (it's phantom.exit() !!)

18:18:02.456168 -0700	airportd	com.apple.message.domain: com.apple.wifi.internal.scanning
com.apple.message.error: No Error
com.apple.message.duration: 4
com.apple.message.process_name: phantomjs
com.apple.message.mac_address: ...
SenderMachUUID: ....

Phantom 2.1.1 / Mac Sierra 10.12.3

**Comment by hartator** [comment]
Same here. Wifi drops until reboot.
