### ISSUE TITLE
PhantomJS is a headless WebKit with JavaScript API 已停止工作 has stopped working

### ISSUE THREAD

**Issue by jokerbo1** [ariya/phantomjs#14291]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   vaersion:2.1.1
2. What steps will reproduce the problem?
   1.I'm executing scripts with robotframework ,the phantomjs is instead of the browser.,main loop access urls  .executing report the prompts
   \
3. Which operating system are you using?
   my os is windows 7 x64  
4. Did you use binary PhantomJS or did you compile it from source?
   i installed is the binary windows .exe
5. Please provide any additional information below.
   no many!!!

**Comment by Vitallium** [comment]
Could you please describe what is your problem exactly? Thanks.

**Comment by 359274651** [comment]
OK, I'm running the RobotFramework+Selenium2LIbrary  ,in this code can using your project phantomjs,using method code the following this(eg: develop language python):

   driver=Webdriver.Phantomjs()
   driver.get(yoururl)
   
Simultaneously ,i hava i edit e library update my computer's host file ,main feature is verify refresh my company's website normal or bad,this keyword framewwork need your phantomjs,running instance of the prompt ,i want solution the problem ,Thanks .

**Comment by 359274651** [comment]
I want know the problem how to solution and what reason  triggered this problem,Thank you.
