### ISSUE TITLE
QPA platform plugin error while building PhantomJS (master).

### ISSUE THREAD

**Issue by sowani** [ariya/phantomjs#14292]
Hi,

I am trying to build latest PhantomJS code from top-of-the-tree master branch. In fact it was building successfully till 16.May.2016, but after that I started getting following error:

Running configuration tests (phase 1)...
Done running configuration tests.
<srcbase> = /root/phantomjs/src/qt/qtbase
<outbase> = /root/phantomjs/src/qt/qtbase
Creating qmake...
.Done.
Running configuration tests (phase 2)...
No QPA platform plugin enabled!
 If you really want to build without a QPA platform plugin you must pass
 -no-qpa-platform-guard to configure. Doing this will
 produce a Qt that can not run GUI applications.
 The dependencies needed for xcb to build are listed in
 src/plugins/platforms/xcb/README

ERROR: Failed to build PhantomJS! Configuration of Qt Base failed.

I am using Ubuntu 16.04 for compilation. I did install the dependencies mentioned in the src/qt/qtbase/src/plugins/platforms/xcb/README file. On Ubuntu 16.04, libxcb-sync0 is libxcb-sync1. But even after these steps I continue to get the same errors.

Are there any additional packages I need to install in order to get the build back on track?

Thanks,
Atul.

**Comment by Vitallium** [comment]
Thanks for reporting. This is a known issue. We are upgrading Qt to 5.6 and the current master is broken. It will be fixed later today. Thank you!

**Comment by dmig** [comment]
Trying to build phantomjs master. Still getting this error.
