### ISSUE TITLE
phantomjs prebuilt not working on EC2

### ISSUE THREAD

**Issue by kaustubh56** [ariya/phantomjs#14290]
Hi,

I developed a code using the node phantom module (https://www.npmjs.com/package/phantom).
It uses a prebuilt phantom binary.
The code runs successfully without any errors on my local system.
I deployed my code on amazon's EC2 instance, and phantom stopped working.
No errors are thrown, it just stops further execution when trying to create a phantom instance.

Are there any steps I need to perform separately on the EC2 instance to get phantom to work?

Edit 1:
I already tried rebuilding the prebuilt binary (npm rebuild).

**Comment by Vitallium** [comment]
Try to run PhantomJS directly without any wrapper. Then post the output of the `ldd phantomjs` command.

**Comment by kaustubh56** [comment]
@Vitallium 
Thanks for the reply, but I was able to pinpoint the issue after deep debugging.
Apologize for not replying to this earlier.

The issue was with my node version(0.10) installed on EC2 which doesn't have support for few inbuilt constructors.
