### ISSUE TITLE
SyntaxError: invalid syntax when I try to install phantomjs 

### ISSUE THREAD

**Issue by NabiKAZ** [ariya/phantomjs#14309]
I have problem with install phantomjs on centos.

error message:

```
# python build.py
  File "build.py", line 452
    except RuntimeError as error:
                         ^
SyntaxError: invalid syntax
```

**Comment by ariya** [comment]
Which Python version did you use? Use `python --version` to figure it out.

**Comment by NabiKAZ** [comment]
```
# python --version
Unknown option: --
Unknown option: -e
Unknown option: -r
Unknown option: -s
Unknown option: -o
Unknown option: -n
Unknown option: --
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
```


```
# python
Python 2.4.3 (#1, Jan  9 2013, 06:49:54)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```


```
# cat /etc/redhat-release
CentOS release 5.11 (Final)
```

And so I have installed Cpanel.

**Comment by ariya** [comment]
See if you can get Python 2.6 or later.
In all cases, we're not planning to support CentOS 5. (see also #13940).

**Comment by NabiKAZ** [comment]
I install `python 2.7`
After `python build.py` get this error:


:

**Comment by Vitallium** [comment]
libicu version? You need at least 53.1.

**Comment by NabiKAZ** [comment]
# yum list installed | grep libicu
libicu.i386                                     3.6-5.16.1             installed
libicu-devel.i386                               3.6-5.16.1             installed
