### ISSUE TITLE
error when install windows 7 

### ISSUE THREAD

**Issue by lewisbellwood** [ariya/phantomjs#14301]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2. What steps will reproduce the problem?
  1. npm i --no-optional
  2.
  3.

3. Which operating system are you using?

windows 7 

4. Did you use binary PhantomJS or did you compile it from source?

npm version 

5. Please provide any additional information below.

68511 silly lifecycle yauzl@2.4.1~install: no script for install, continuing
68512 silly install extract-zip@1.5.0 C:\Users\Lewis.Bellwood\Documents\investec_frontend\frontend\node_modules\.staging\extract-zip-3d042cfb
68513 info lifecycle extract-zip@1.5.0~install: extract-zip@1.5.0
68514 silly lifecycle extract-zip@1.5.0~install: no script for install, continuing
68515 silly install phantomjs@1.9.20 C:\Users\Lewis.Bellwood\Documents\investec_frontend\frontend\node_modules\.staging\phantomjs-d630d5e2
68516 info lifecycle phantomjs@1.9.20~install: phantomjs@1.9.20
68517 verbose lifecycle phantomjs@1.9.20~install: unsafe-perm in lifecycle true
68518 verbose lifecycle phantomjs@1.9.20~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Lewis.Bellwood\Documents\investec_frontend\frontend\node_modules\phantomjs\node_modules\.bin;C:\Users\Lewis.Bellwood\Documents\investec_frontend\frontend\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Enterprise Vault\EVClient\x64\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Users\Lewis.Bellwood\AppData\Roaming\npm
68519 verbose lifecycle phantomjs@1.9.20~install: CWD: C:\Users\Lewis.Bellwood\Documents\investec_frontend\frontend\node_modules\phantomjs
68520 silly lifecycle phantomjs@1.9.20~install: Args: [ '/d /s /c', 'node install.js' ]
68521 silly lifecycle phantomjs@1.9.20~install: Returned: code: 1  signal: null
68522 info lifecycle phantomjs@1.9.20~install: Failed to exec install script
68523 verbose unlock done using C:\Users\Lewis.Bellwood\AppData\Roaming\npm-cache\_locks\staging-327423d56fd324d8.lock for C:\Users\Lewis.Bellwood\Documents\investec_frontend\frontend\node_modules\.staging
68524 silly rollbackFailedOptional Starting
68525 silly rollbackFailedOptional Finishing
68526 silly runTopLevelLifecycles Starting
68527 silly runTopLevelLifecycles Finishing
68528 silly install printInstalled
68529 verbose stack Error: phantomjs@1.9.20 install: `node install.js`
68529 verbose stack Exit status 1
68529 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
68529 verbose stack     at emitTwo (events.js:100:13)
68529 verbose stack     at EventEmitter.emit (events.js:185:7)
68529 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
68529 verbose stack     at emitTwo (events.js:100:13)
68529 verbose stack     at ChildProcess.emit (events.js:185:7)
68529 verbose stack     at maybeClose (internal/child_process.js:850:16)
68529 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
68530 verbose pkgid phantomjs@1.9.20
68531 verbose cwd C:\Users\Lewis.Bellwood\Documents\investec_frontend\frontend
68532 error Windows_NT 6.1.7601
68533 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-optional"
68534 error node v5.10.1
68535 error npm  v3.8.3
68536 error code ELIFECYCLE
68537 error phantomjs@1.9.20 install: `node install.js`
68537 error Exit status 1
68538 error Failed at the phantomjs@1.9.20 install script 'node install.js'.
68538 error Make sure you have the latest version of node.js and npm installed.
68538 error If you do, this is most likely a problem with the phantomjs package,
68538 error not with npm itself.
68538 error Tell the author that this fails on your system:
68538 error     node install.js
68538 error You can get information on how to open an issue for this project with:
68538 error     npm bugs phantomjs
68538 error Or if that isn't available, you can get their info via:
68538 error     npm owner ls phantomjs
68538 error There is likely additional logging output above.
68539 verbose exit [ 1, true ]

**Comment by Vitallium** [comment]
Sorry, but we don't maintain the NPM package. Please file your issue in the corresponding repository. Thank you!
