### ISSUE TITLE
CSS order property not handled

### ISSUE THREAD

**Issue by alex88** [ariya/phantomjs#14319]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`. 2.1.1
2. What steps will reproduce the problem?
   1. Create a page with elements using the order css property
3. Which operating system are you using? OSX, tested on Linux too
4. Did you use binary PhantomJS or did you compile it from source? Binary
5. Please provide any additional information below.

Seems phantomjs does not respect order property, I've tried to add some fallbacks:

```
-webkit-box-ordinal-group: 2
-ms-flex-order: 1
-webkit-order: 1
order: 1
```

but the elements are not ordered correctly

**Comment by alex88** [comment]
Simple test

```
<html>
<body>
  <div style="display: flex">
    <div style="order: 2">1</div>
    <div style="order: 1">2</div>
  </div>
</body>
</html>
```

browser:

![screen shot 2016-05-26 at 9 31 46 pm](https://cloud.githubusercontent.com/assets/436888/15597870/6097db42-2389-11e6-999f-2d396bae6c70.png)

phantomjs:

![github](https://cloud.githubusercontent.com/assets/436888/15597873/66b29eb8-2389-11e6-811e-93dabe7b55b0.png)

**Comment by gael-boyenval** [comment]
it seems that flex is just completely ignored… not just order
