### ISSUE TITLE
PhantomJS@2.1.1 Object.defineProperty behaves incorrectly for functions

### ISSUE THREAD

**Issue by antonioMerkulov** [ariya/phantomjs#14310]
There was an [issue](https://github.com/ariya/phantomjs/issues/11856) when `Object.defineProperty` works incorrectly in PhantomJS. And now it works OK for objects but not for functions...

The following behaves correctly in browsers and node.js, but incorrectly in PhantomJS:

``` javascript
var foo = function () { console.log('foo function'); };
Object.defineProperty(foo, 'name', {value: 'bar', configurable: true});
console.log(foo.name); //bar
```

browser example:
![browser](http://i.imgur.com/ECW5NED.png)

node example:
![node](http://i.imgur.com/NZfvcUw.png)

phantomjs example:
![phantomjs](http://i.imgur.com/ky2kInw.png)

**Comment by elias-winberg** [comment]
The 'name' attribute seems to be non-configurable and read-only by default in PhantomJS. The actual error is 'TypeError: Attempting to configurable attribute of unconfigurable property.', [but the REPL (read–eval–print loop) prints "'%1' is a cyclic structure\" whenever a TypeError occurs.](https://github.com/ariya/phantomjs/blob/842715be9d2bb27865c179c12761290fa3f2929c/src/repl.cpp#L60)
