### ISSUE TITLE
Memory spikes and phantomjs crashes

### ISSUE THREAD

**Issue by ivy3698** [ariya/phantomjs#14324]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.   
1.9.8

2. What steps will reproduce the problem?
  1.  Run Jasmine tests via Karma in IntelliJ (doesn't happen every time though)

3. Which operating system are you using?
OSX 10.10.5

4. Did you use binary PhantomJS or did you compile it from source?
Not sure?
[C86DBE7A-30B1-43B5-840A-606B7BC6FD9C.dmp.zip](https://github.com/ariya/phantomjs/files/287344/C86DBE7A-30B1-43B5-840A-606B7BC6FD9C.dmp.zip)

5. Please provide any additional information below.
Memory spikes up super high right before it crashes (all used by phantomjs)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
