### ISSUE TITLE
Partial element position error！

### ISSUE THREAD

**Issue by jjskay** [ariya/phantomjs#14322]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
![image](https://cloud.githubusercontent.com/assets/5975458/15600018/ee989478-2419-11e6-8bd4-cbad1935845f.png)

2. What steps will reproduce the problem?
  1.Print out of the elements of dislocation
  2.
  3.

3. Which operating system are you using?
system:
![image](https://cloud.githubusercontent.com/assets/5975458/15600295/a425a6ae-241b-11e6-8e26-f795e8f45416.png)

browser:
![image](https://cloud.githubusercontent.com/assets/5975458/15600315/c363e2d8-241b-11e6-9982-98842d886901.png)

4. Did you use binary PhantomJS or did you compile it from source?
webpack/nodejs

5. Please provide any additional information below.
When the bar style： position:absolute
HTML screenshot: 
![image](https://cloud.githubusercontent.com/assets/5975458/15600138/b7409eb6-241a-11e6-81aa-1a7a5101e165.png)
PDF screenshot: 
![image](https://cloud.githubusercontent.com/assets/5975458/15600147/c91f99ac-241a-11e6-82ca-80c5f9142544.png)

When the bar style： position:relative
PDF screenshot: it's look goods.
![image](https://cloud.githubusercontent.com/assets/5975458/15600174/fda1792a-241a-11e6-98dc-f883f7990fd7.png)

But there's a problem:
HTML screenshot: 
![image](https://cloud.githubusercontent.com/assets/5975458/15600234/4b8f236c-241b-11e6-8554-b2c7651199d1.png)

PDF screenshot:
![image](https://cloud.githubusercontent.com/assets/5975458/15600245/5fe3e14a-241b-11e6-9534-73652632c5bc.png)

I have been troubled by this problem for several days. Looking forward to your answer, thank you.

**Comment by Devil-Cong** [comment]
I have a similar problem. How did you solve it?
