### ISSUE TITLE
Statically linked phantom is using openssl1.0.1e

### ISSUE THREAD

**Issue by SamSaffron** [ariya/phantomjs#14320]
Latest phanotmjs release on the website is statically linking against 1.0.1e, should follow node's path probably and link against 1.0.2h cause 1.0.1e has lots of security flaws. 

This popped up in our docker image scan.

**Comment by Vitallium** [comment]
Hi Sam! PhantomJS 2.5 now linked against the system-provided versions of OpenSSL. On macOS it even uses SecureTransport now. Would you mind give it a shot?

With this change we can release security updates more often.

Thanks!

**Comment by SamSaffron** [comment]
Sounds good! thanks, will see if we can integrate this into our docker image  @xfalcox

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
