### ISSUE TITLE
The same codes, same node version,run correct in windows,error in linux

### ISSUE THREAD

**Issue by swumao** [ariya/phantomjs#14323]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

    2.1.1
2. What steps will reproduce the problem?

    - I develop on windows 7 operation system, and install phantomjs with -g option.Then I write code and run correct.
    - But when I deploy it to a linux system(centos 6.5), the same codes doesn't work.
    - My node version is 6.2.0.

3. Which operating system are you using?
windows7 and centos 6.5

4. Did you use binary PhantomJS or did you compile it from source?
binary version

5. Please provide any additional information below.

**Comment by Vitallium** [comment]
What do you mean it doesn't work? Logs? Script?

**Comment by swumao** [comment]
@Vitallium I have find the reason of this problem! https protocol make it doesn't work.
