### ISSUE TITLE
Can't find variable: console

### ISSUE THREAD

**Issue by bwhitty6** [ariya/phantomjs#14327]
I am running version 2.1.1 of Phantom JS, on Ubuntu.

I have been using karma-chrome to edit and create my tests and it works perfectly, but now that I have completed my tests I do not want to use chrome but rather PhantomJS. When I do this I keep getting the error, Can't find variable: console. Any ideas on how to fix this? 

Thanks

**Comment by Vitallium** [comment]
Could you please post your script? `console` is supported by PhantomJS. Because it's a browser.

**Comment by Vitallium** [comment]
No response. Closing.
