### ISSUE TITLE
CSS property object-fit : contain is not working in phantomjs

### ISSUE THREAD

**Issue by sbsomya** [ariya/phantomjs#14321]

**Comment by Vitallium** [comment]
Ok.

**Comment by kjantzer** [comment]
Why was this closed? Still looks broken on `2.1.1`

**Comment by jorchg** [comment]
Any alternative to this?

**Comment by kjantzer** [comment]
@jorchg The alternative I went with was using `background-image` and `background-size` instead of an `<img>` and `object-fit`

**Comment by Ugoku** [comment]
Can I ask again why this was closed? This is a very useful CSS property and it would be great if PhantomJS supported it.

**Comment by Vitallium** [comment]
@Ugoku because this issue has only title and zero useful info.

**Comment by kjantzer** [comment]
@Vitallium The title seems pretty self explanatory. Use the css `object-fit: contain` doesn't function like it should.

**Comment by Vitallium** [comment]
@kjantzer we have a template to report issue. This template helps us a lot in fixing problems. Plus, writing a a simple example that reproduces a problem helps a lot. 

And I think this problem is fixed in 2.5 beta version.

**Comment by kjantzer** [comment]
@Vitallium I understand. It's hard to expect an outside user to use your "template to report" though when there doesn't seem to be documentation on it. Couldn't you have just tagged it with the "Unclear" label?

**Comment by Vitallium** [comment]
@kjantzer our template uses the GitHub reporting system: when you click on "Create a new issue", this template will be in your text field.

>Couldn't you have just tagged it with the "Unclear" or "Need more information" label?
I think I'll tag it as `probably fixed` in 2.5 milestone. And I'll check it later.

**Comment by Ugoku** [comment]
Thanks for the update!

**Comment by Ugoku** [comment]
> Plus, writing a a simple example that reproduces a problem helps a lot.

Here's my situation:

HTML:
`<img src="http://lorempixel.com/900/450/">`

CSS:
```
img {
    height: 450px;
    object-fit: contain;
    width: 600px;
}
```

The loaded image is the same height as the height assigned to the `img` tag, but it is wider than the tag. Without `object-fit`, it is stretched to fit the tag. With `object-fit`, it will fit the container with the top and bottom empty.

Attached is a test case: [objectfit.txt](https://github.com/ariya/phantomjs/files/816566/objectfit.txt) (as .txt because GitHub doesn't allow .html upload)
