### ISSUE TITLE
onFilePicker callback not called on click if file input has "multiple" attribute

### ISSUE THREAD

**Issue by ScottJMarshall** [ariya/phantomjs#14331]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. Use Phantom to run the attached test [pickerTest.js.zip](https://github.com/ariya/phantomjs/files/293765/pickerTest.js.zip).  You would expect to see "file picker opened" logged. Removing the "multiple" attribute and re-running will give the expected result.  The fact that this fails silently makes it very hard to diagnose.  At the very least it would be helpful to document this in the onFilePicker section of the product documentation.
3. Which operating system are you using?
   OSX El Capitan
4. Did you use binary PhantomJS or did you compile it from source?
   Binary

**Comment by jesg** [comment]
this looks like the root cause for a bug in ghostdriver.  ghostdriver will freeze in this special case.

@ariya @zackw @Vitallium can support be added to trigger a callback when the file input has the multiple attribute?
