### ISSUE TITLE
phantomjs disk-cache deadlock bug

### ISSUE THREAD

**Issue by gouchaoer** [ariya/phantomjs#14334]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   both 2.1.1 and 2.0.0
2. What steps will reproduce the problem?
   1.drive a lot of phantomjs to access the same url such as "http://a.com" and enable disk-cache 
   2.after a few hours or a few days, all of your phantomjs get stuck on get "http://a.com" and the cpu is 100% used by phantomjs.
   3.if you delete the cache file, then everything is ok again.
3. Which operating system are you using?
   win7
4. Did you use binary PhantomJS or did you compile it from source?
   binary
5. Please provide any additional information below.
   I cost a lot of time to find this bug which made me crazy.
   please have a look at this [bug](https://github.com/ariya/phantomjs/issues/14228), thanks!

**Comment by gouchaoer** [comment]
I　had the same problem too and I finally know the reason.

You must had enabled the disk-cache.

The disk-cache of phantomjs has a dead lock bug. By keep doing job on the same url for many times, i ran out of this bug. If you delete the cache directory, then everything is OK.

**Comment by crapthings** [comment]
@gouchaoer 

where is the cache director ?

**Comment by gouchaoer** [comment]
just read the official doc. you will find sth like --disk-cache-path, set it to different path gor different phantomjs instance

**Comment by gouchaoer** [comment]
phantomjs is far behind chromium in new features...just switch to chrome headless
