### ISSUE TITLE
PDF file is not getting download in Windows Server 2012 using phantomjs

### ISSUE THREAD

**Issue by uma-p** [ariya/phantomjs#14332]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
version 2.0
2. What steps will reproduce the problem?
  1.Locally everything working fine
  2.we have instaleld the software at client location in windows 2012 server.
  3.click on download button its giving issue as "Couldnt find the fg5683judukkml.pdf file".

3. Which operating system are you using?
Windows Sercver 2012
4. Did you use binary PhantomJS or did you compile it from source?
from sorce
5. Please provide any additional information below.
![phantomerror](https://cloud.githubusercontent.com/assets/19702816/15735786/f9e89906-28b8-11e6-9158-00efce9fe0ed.png)

**Comment by Vitallium** [comment]
Sorry, but without logs we can't help you.
