### ISSUE TITLE
can this screenshot be better?

### ISSUE THREAD

**Issue by crackjack** [ariya/phantomjs#14341]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2.1.1
1. What steps will reproduce the problem?
   1. open the page https://angular.io/
   2. take screenshot
   3. even try with phantomjs cloud
2. Which operating system are you using?

CentOS 7
1. Did you use binary PhantomJS or did you compile it from source?

used Medium/phantomjs, locally compiled, but does occur with binary, compiled, npm version, apt-get version and yum version as well.
1. Please provide any additional information below.

I have experienced these issues in sites that use javascript to load their content, after the page load. I'm attaching the screenshot of the site https://angular.io/
![screnshot](https://cloud.githubusercontent.com/assets/191368/15845954/f463fc4a-2c97-11e6-856b-717b9095513a.jpg)

**Comment by marktheunissen** [comment]
Add an artificial delay, here it is 3 seconds:

```javascript
// Open and execute screenshotting.
page.open(url, function(status) {
    window.setTimeout(function () {
        page.render(file, {format: 'png'});
        phantom.exit();
    }, 3000);
});
```

Document ready fires before all the content is loaded. It is impossible to know when a webpage is finished loading, as JavaScript can just keep loading content forever. So just wait a few seconds.

**Comment by crackjack** [comment]
@marktheunissen the screenshot I attached is with 15 seconds timeout. The thing you mentioned was definitely my first though, but that doesn't seem to be the issue here.

slimerjs on the other hand does bring up the screenshot, with all content, without any timeout set. I strongly feel this is related to WebKit v/s Gecko.

If you can post a screenshot you got back with that 3 seconds of timeout, I'd really like to see it.

**Comment by marktheunissen** [comment]
![angular](https://cloud.githubusercontent.com/assets/453297/15955839/ba318110-2ee4-11e6-9e55-0afa6951d315.png)

**Comment by marktheunissen** [comment]
Are you using v2.1.1? 

What about these settings:

```
// The actual size of the headless browser
page.viewportSize = {
    width: w,
    height: h
};

// Portion of the page to take a screenshot of
page.clipRect = {
    top: 0,
    left: 0,
    width: w,
    height: h
};
```

can you run with --debug and see if there are any errors?

**Comment by crackjack** [comment]
@marktheunissen Yes, I'm using 2.1.1

Yes, I have tried setting the viewportSize and clipRect. With clipRect we only get back a portion of the page, but I want full page, of any site.

Nevertheless, even with cliprect the result is same.
![1](https://cloud.githubusercontent.com/assets/191368/15957341/3c3e8c10-2f0e-11e6-8f79-e3d01b65861a.jpg)

**Comment by crackjack** [comment]
@marktheunissen how did you get that screenshot? I'm on CentOS 7, could there be something that you are doing and I'm missing?

can you please share your code you used to generate that screenshot?

**Comment by marktheunissen** [comment]
I'm running it using the prebuilt binary for Mac, and the code is basically all I've posted in here so far. 3 second delay before snapshotting. Maybe post yours?

**Comment by marktheunissen** [comment]
I would say the problem is those WARNING messages you're getting. Are you running the fully self-contained version of Phantom in true headless mode?

**Comment by crackjack** [comment]
here you go

```
var webPage = require('webpage');
var page = webPage.create();

page.viewportSize = {
	width: 1920,
	height: 1080
};

page.open('https://angular.io/', function (status) {
	window.setTimeout(function(){
		page.render('angular.jpg');
  		phantom.exit();
	}, 10000);
});
```

by WARNING messages, do you mean those from libpng? I'm assured that they hardly affect the process. https://wiki.archlinux.org/index.php/Libpng_errors

**Comment by marktheunissen** [comment]
Oh, I think it's  the large viewport size. When I try 1920x1080, I get the same broken screenshot that you see.

If I use 1024x768, it looks fine.

**Comment by crackjack** [comment]
nah, still the same
```
var webPage = require('webpage');
var page = webPage.create();

page.viewportSize = {
	width: 1024,
	height: 768
};

page.open('https://angular.io/', function (status) {
	window.setTimeout(function(){
		page.render('angular.jpg');
  		phantom.exit();
	}, 10000);
});
```

**Comment by marktheunissen** [comment]
This works for me:

```javascript
var webPage = require('webpage');
var page = webPage.create();

page.viewportSize = {
    width: 1024,
    height: 768
};

// Portion of the page to take a screenshot of
page.clipRect = {
    top: 0,
    left: 0,
    width: 1024,
    height: 768
};

page.open('https://angular.io/', function (status) {
    window.setTimeout(function(){
        page.render('angular.jpg');
        phantom.exit();
    }, 1000);
});

```

**Comment by crackjack** [comment]
with the cliprect, I get the same as you got now.

but it is only a section, when I try to get the full page, it again goes like before.

**Comment by kurtismgit** [comment]
Not certain if it's the same root cause, but I see something similar for pages I'm trying to load and opened:

https://github.com/ariya/phantomjs/issues/14373

I found this issue and saw the suggest related to slimerjs.  That works for me as well.  If this issue ever gets fixed, I'd like to try my site again.
