### ISSUE TITLE
console.error recursively triggers phantom.onError

### ISSUE THREAD

**Issue by acoulton** [ariya/phantomjs#14346]
> 1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2.1.1

> 1. What steps will reproduce the problem?

Run the following script (trimmed down version of the example in the [on-error documentation](http://phantomjs.org/api/phantom/handler/on-error.html))

``` js
phantom.onError = function(msg, trace) {
    console.log('onError '+msg+"\n");
    console.error('PHANTOM ERROR: ' + msg);
    phantom.exit(1);
};

foo = bar;
phantom.exit(0);
```

Observe that phantomjs enters a recursive loop until it eventually segfaults

> 1. Which operating system are you using?

Ubuntu 14.04

> 1. Did you use binary PhantomJS or did you compile it from source?

Binary

**Comment by MaxiSantos** [comment]
Hey @acoulton I had the same issue and I found this "fix" from here [https://github.com/ariya/phantomjs/issues/13707](https://github.com/ariya/phantomjs/issues/13707)

**Comment by acoulton** [comment]
@MaxiSantos thanks : I can't actually remember where I ran into this now, but I'll bear that in mind! :)
