### ISSUE TITLE
URL() constructor returns an empty object

### ISSUE THREAD

**Issue by elleuca** [ariya/phantomjs#14349]
## Steps to reproduce
1. start phantomjs console
2. insert `var a = new URL('http://phantomjs.org');`
3. print content of `a`

_Current result_ -- `a` is `{}`

_Expected result_ -- `a` should be a non empty object, but

```
{ href: "http://phantomjs.org/", origin: "http://phantomjs.org", protocol: "http:", username: "", password: "", host: "phantomjs.org", hostname: "phantomjs.org", port: "", pathname: "/", search: "" }
```

[cfr mdn docs for URL](https://developer.mozilla.org/en-US/docs/Web/API/URL)
## Phantomjs version
- version 2.1.1
- Ubuntu 16.04 and OSX 10.11
- Binary downloaded from https://github.com/Medium/phantomjs/releases/ (through phantomjs-prebuilt npm package)

**Comment by JellyBellyDev** [comment]
👍

**Comment by otroboe** [comment]
:+1:

**Comment by shfx** [comment]
Any news on this?

**Comment by pavel-freshcode** [comment]
Have the same issue on 2.1.7

**Comment by twalpole** [comment]
PhantomJS 2.1.x is basically equivalent to Safari 5.1ish as far as JS and web technology support goes.  The URL API was not fully defined at that point of time and is therefore not fully supported.  Try the PhantomJS 2.5 beta
