### ISSUE TITLE
Disk caching only works for the same running instance.

### ISSUE THREAD

**Issue by TariqAbughofa** [ariya/phantomjs#14355]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   1.9.7 and 2.1
2. Which operating system are you using?
   linux mint 17.3 rosa
3. Did you use binary PhantomJS or did you compile it from source?

I use binary PhantomJS
1. Please provide any additional information below.

I am running the same url by starting phantomjs process each time and its not using the cache. I am using the following options:

--ignore-ssl-errors=true --ssl-protocol=tlsv1 --disk-cache=true --max-disk-cache-size=1000000

but the caching seems to work only for the same process.

**Comment by ritobrotos** [comment]
Is there any update for this issue?? I am facing the same. Also would want to know if there is any alternative to it. My PhantomJs version is 2.1.1
