### ISSUE TITLE
phantom.addCookie always returns false

### ISSUE THREAD

**Issue by ArtemZag** [ariya/phantomjs#14368]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. Create file test.js
  2. Insert the following text into the file:
  ```
  phantom.cookiesEnabled = true;
  
  var isAdded = phantom.addCookie({
      'name': 'Valid-Cookie-Name',
      'value': 'Valid-Cookie-Value',
      'domain': 'localhost',
      'path': '/',
      'httponly': true,
      'secure': false
  });
  
  if (isAdded === false) {
      console.log('Not added');
  }
  else {
      console.log('Added');
  }

  phantom.exit();
  ```
 3. Run `phantomjs test.js`

3. Which operating system are you using?
Windows 10 Pro

4. Did you use binary PhantomJS or did you compile it from source?
Use binary PhantomJS (downloaded by npm)

5. Please provide any additional information below.
The supposed result is text 'Added' in console. But I get 'Not added'.

**Comment by elias-winberg** [comment]
Does the following snippet work (I added a `.` before `localhost`)?

```
phantom.cookiesEnabled = true;

var isAdded = phantom.addCookie({
    'name': 'Valid-Cookie-Name',
    'value': 'Valid-Cookie-Value',
    'domain': '.localhost',
    'path': '/',
    'httponly': true,
    'secure': false
});

if (isAdded === false) {
    console.log('Not added');
}
else {
    console.log('Added');
}

phantom.exit();
```

**Comment by ArtemZag** [comment]
Wow, thanks. It works! I'm closing the issue.

**Comment by elias-winberg** [comment]
According to the Qt docs the cookie will match all hostnames that end with the domain if it starts with a dot.
