### ISSUE TITLE
webpage.paperSize: orientation landscape/portrait is swapped

### ISSUE THREAD

**Issue by ricokahler** [ariya/phantomjs#14360]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.2.0-development

2. What steps will reproduce the problem?

Run this script:
```
var page = require('webpage').create();

// landscape
page.content = '<html><head></head><body><h1>This should be landscape</h1></body></html>';
page.paperSize = { format: 'Letter', orientation: 'landscape', margin: '1cm' };
page.render('this_should_be_landscape.pdf', { format: 'pdf', quality: '100' });

// portrait
page.content = '<html><head></head><body><h1>This should be portrait</h1></body></html>';
page.paperSize = { format: 'Letter', orientation: 'portrait', margin: '1cm' };
page.render('this_should_be_portrait.pdf', { format: 'pdf', quality: '100' });
phantom.exit();
```
Observe:

![image](https://cloud.githubusercontent.com/assets/10551026/16122701/19feeeb8-33b6-11e6-8fce-ccf068198759.png)
![image](https://cloud.githubusercontent.com/assets/10551026/16122712/2360d5e8-33b6-11e6-8fac-a21164ea3645.png)

3. Which operating system are you using?
Windows 7

4. Did you use binary PhantomJS or did you compile it from source?
Compiled it from source on 6/16/2016

5. Please provide any additional information below.

**Comment by elias-winberg** [comment]
I think https://github.com/ariya/phantomjs/commit/7d7e5f345b646ef18d23138781ae94197335b342#diff-e6d43d0460770360ad54e3b50f04734cL1198 is the change that introduced the bug (it works on version 2.1.1). It should be easy to fix though.

**Comment by elias-winberg** [comment]
It looks like there already is a [fix](https://github.com/ariya/phantomjs/pull/14298), the pull request just hasn't been merged yet.

**Comment by ricokahler** [comment]
Oh oops, I should've looked further. if there's already a pull request to fix the bug, then we're good
