### ISSUE TITLE
QtWebEngine instead of QtWebKit ?

### ISSUE THREAD

**Issue by aight8** [ariya/phantomjs#14366]
I saw that QtWebKit which provide the headless browser for PhantomJS is outdated. QtWebEngine is the new way to go which is developed heavilly. When I now look at the compat table for PJS I saw arround 10% for ES6 and wondering how this could work in the future. Isn't it a good idea to switch to the future proof technology? Or what is your motivation for the future with PS before it uses very outdated technologies?

And I have an additional question: I know a lot of WebKit functionality is implemented by the browser. But which steps are needed to upgrade to support the ES6 syntax?

**Comment by adam77** [comment]
I understand QtWebEngine is missing some key APIs. There was some discussion about switching to [Chromium Embedded Framework](https://en.wikipedia.org/wiki/Chromium_Embedded_Framework). Not sure where that is at.

Your best bet with Phantom and ES6 might be to use a transpiler [1](https://babeljs.io/),[2](https://www.typescriptlang.org/) and generate ES5.

**Comment by Vitallium** [comment]
I think you should read our mailing list about moving to Chromium.

But I'll write them here. Right now we are working on bringing new and latest WebKit. This is our primary goal. This update will close 95% of our issues and will deliver cool and modern features to users.

Moving to Chromium is impossible at the moment. Google is working on a headless shell and this shell is far from complete. We can't move to it. But we don't drop it from our plans.

**Comment by adam77** [comment]
Great news, thanks for the clarification.

**Comment by ariya** [comment]
Switching to QtWebEngine/Chromium is a monumental amount of work. Consider the situation, it's not likely going to happen in the near future. Meanwhile, track the progress of modernizing PhantomJS in #14458.
