### ISSUE TITLE
Implement API to capture DOM elements (via selector)

### ISSUE THREAD

**Issue by vitallium** [ariya/phantomjs#14367]
Sometimes users don't need to capture the whole page. They want to capture only a single element.

I think we should implement this API as `page.renderElement(selector, filename)`. I know there were hacks and functions to extend our `page.render` API.

We can implement this by using `QWebElement`.

**Warning**
This issue is for tracking, not for discussion. Discuss it here: https://groups.google.com/forum/#!topic/phantomjs-dev/fy22zHRb17Q

**Comment by seppsepp** [comment]
CasperJS does this using PhantomJS's clipRect:

https://github.com/casperjs/casperjs/blob/985dd061c24d4252a8c7f38f87d9306359726e5d/modules/casper.js#L387

**Comment by seppsepp** [comment]
Sorry, haven't seen your _warning_ before - page was open and you edited the description I guess. Feel free to delete my comments. I c&p it to the Google Group.

**Comment by Vitallium** [comment]
That's ok. We definitely must keep in mind that CasperJS already has this.
