### ISSUE TITLE
Linux x64 PhantomJS downloaded from CDN is a corrupt tar.gz file

### ISSUE THREAD

**Issue by fake-name** [ariya/phantomjs#14375]
I'm trying to script phantomjs retrieval for an automated deploy system.

The "official" url (`https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2`) from [the homepage](http://phantomjs.org/download.html) sometimes 403 errors from DigitalOcean IPs. This is a known error: https://github.com/Medium/phantomjs/issues/506 , though apparently the fix described there never made it to the phantomjs.org home page.

Apparently there is a "package" in some system somewhere that doesn't use that URL (I'm working from python, Pretty sure it's in NPM, I don't have node installed). Using the URL in the comment there: `http://cnpmjs.org/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2` *does* work, but the tar.gz file at that address appears to be corrupt.

What URL can I use for retrieving phantomjs in deploy scripts?

**Comment by fake-name** [comment]
Ok, looking at the same package downloaded from the two sites:

```
$ md5sum phantomjs-2.1.1-linux-x86_64*
c6f2739f66e4c0a5033e93f5c64ca6e5 *phantomjs-2.1.1-linux-x86_64 (1).tar.bz2
1c947d57fce2f21ce0b43fe2ed7cd361 *phantomjs-2.1.1-linux-x86_64 (2).tar.bz2
```

It appears the file from cnpmjs.org is damaged or something.

**Comment by Vitallium** [comment]
Host it on your own CDN. We know about the problems with bitbucket. But we can't do anything with that.

**Comment by fake-name** [comment]
@Vitallium Uh..... did you read the report?

The bitbucket issue I can understand. The problem is that the version hosted on cnpmjs **is corrupt and not a valid archive**.

**Comment by Vitallium** [comment]
@fake-name Yes, I read it carefully. But we don't host anything on cnpmjs. We have only one place to download **official** binaries - bitbucket.org. I think you should file your issue in the Medium's repository. Thanks.

**Comment by fake-name** [comment]
Oh, I assumed it was an official mirror from the way it was referred to in #506.
