### ISSUE TITLE
QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by arrmo** [ariya/phantomjs#14376]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. Take a working javascript file (e.g. rasterize.js)
  2. Call the file from a script file (e.g. executable file, #!/bin/sh at the start)
  3. Now execute the script file as a cron job

3. Which operating system are you using?
Ubuntu 16.04 LTS

4. Did you use binary PhantomJS or did you compile it from source?
Binary - installed it as part of Ubuntu (using apt).

5. Please provide any additional information below.
This is very similar to https://github.com/ariya/phantomjs/issues/14240, but I am using the stock version of PhantomJS (with Ubuntu). Below is the output from running the cron job (which calls the script file, to generate a pdf file once a day) ...

> QXcbConnection: Could not connect to display 
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Aborted (core dumped)

Thanks!

**Comment by Vitallium** [comment]
Please check your environment variable `QT_QPA_PLATFORM`. It must be empty.

**Comment by arrmo** [comment]
Yep, it is - in both cases. Does this need to be manually forced for some reason?

Thanks!

**Comment by zackw** [comment]
I would send a patch to reset all the troublesome environment variables before initializing Qt ... if I could find a list of them anywhere.

But it sounds like this isn't actually the problem?

**Comment by arrmo** [comment]
It doesn't sound like it, but I could definitely be wrong.

**Comment by arrmo** [comment]
Trying different things, no luck. Is there a setting of QT_QPA_PLATFORM that you believe may help?

Thanks!

**Comment by ricohumme** [comment]
Hi,

Having same issue here.
Working with 1.9 on my dev machine, works fine.
But on the live server I can't even download 1.9.x so I'm stuck now.

Where can I find this settings of QT? How to get there. So I can check that on my side.

Thanks!

**Comment by jglogan** [comment]
The `offscreen` platform is a usable workaround for me with the stock Ubuntu package.  This works for me:

`QT_QPA_PLATFORM=offscreen phantomjs rasterize.js 2i8zaNg04d9B41Zir2kT3J/output.html  2i8zaNg04d9B41Zir2kT3J.png`

**Comment by istinspring** [comment]
can confirm `export QT_QPA_PLATFORM=offscreen` before selenium scripts work's well.

**Comment by ricohumme** [comment]
We finally got things working by downloading the binary at  https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 and extracting the phantomjs to /usr/bin

**Comment by istinspring** [comment]
I had hard times with ubuntu 16.04 they basically distribute half finished system with lots of broken packages.

**Comment by ricohumme** [comment]
I'm running on 16.04 too, but the problem with the repo's is that they deliver with x11, which fails. So with the binary I don't have that issue and it works perfectly now.

**Comment by arrmo** [comment]
Works here now also - thanks!!!

**Comment by ariya** [comment]
Debian/Ubuntu has a modified version of PhantomJS that can work headlessly, hence the problem with QXcb. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=817277 for details.

Unfortunately, this is not something that we (=PhantomJS team) can fix.

**Comment by 3zzy** [comment]
@ricohumme Can you provide the steps (commands) to install it? I tried:
```
export PHANTOM_JS_VERSION=2.1.1
wget "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-$PHANTOM_JS_VERSION-linux-x86_64.tar.bz2"
tar xvfj "./phantomjs-$PHANTOM_JS_VERSION-linux-x86_64.tar.bz2"
ln -sf "./phantomjs-$PHANTOM_JS_VERSION-linux-x86_64/bin/phantomjs" "/usr/bin"
```

but still couldn't get it working

**Comment by ricohumme** [comment]
@3zzy the steps I used are as follows:
`wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2`
`bzip2 -d phantomjs-2.1.1-linux-x86_64.tar.bz2`
`tar -xvf phantomjs-2.1.1-linux-x86_64.tar`
`cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/phantomjs`

Does this help your case?

**Comment by wojciechmorawski** [comment]
Thanks for help, solution above works well :)

**Comment by elhamdaoui** [comment]
I'm the same error but in **Odoo**

**Comment by seachanged** [comment]
xvfb-run worked best for me, from Ariya's link posted 8/2016. 
xvfb is "providing an unobtrusive way to run applications that don’t really need an X server but insist on having one anyway."

**Comment by michaelkl** [comment]
@jglogan Thank you for solution with `QT_QPA_PLATFORM=offscreen`. It let me run phantomjs itself, but it was failing for me with `EOFError: end of file reached` message on certain pages.
After some experiments with different platforms I found out that it works like a charm with `QT_QPA_PLATFORM=minimal`.
Hope this will help someone.

**Comment by Dingo64** [comment]
Thanks a lot, guys! QT_QPA_PLATFORM=offscreen works great on Debian 8 jessie amd64 with PhantomJS 2.1.1

```
# QT_QPA_PLATFORM=offscreen phantomjs --version
2.1.1
```

**Comment by ip1981** [comment]
> Debian/Ubuntu has a modified version of PhantomJS that can work headlessly, hence the problem with QXcb. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=817277 for details.

This is quite the opposite:
> Unfortunately it can not be fixed in Debian. To achieve headless-ness
upstream statically link with customised QT + Webkit. We don't want to ship
forks of those projects. It would be great to eventually convince upstream to
use standard libraries.

There is also a suggestion to use `xvfb-run`, which is right.

**Comment by eunick** [comment]
try to uninstall phantomjs and just download the binary then create the softlink. that works for me..

apt-get remove phantomjs
ln -s /opt/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs

**Comment by jorgesinval** [comment]
Every time I try to plot anything with RStudio Cloud using the webshot package I obtain an error. An example:

```
#install webshot
library(webshot)
webshot::install_phantomjs()
# Make the graph
my_graph=wordcloud2(demoFreq, size=1.5)
# save it in html
library("htmlwidgets")
saveWidget(my_graph,"tmp.html",selfcontained = F)
# and in png
webshot("tmp.html","fig_1.png", delay =5, vwidth = 480, vheight=480)
```
The error says:

```
QXcbConnection: Could not connect to display :0
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Error in webshot("tmp.html", "fig_1.png", delay = 5, vwidth = 480, vheight = 480) : 
  webshot.js returned failure value: -6
```

Any thoughts?
