### ISSUE TITLE
PhantomJS does not support hexa decimal color codes in the exported PDF.

### ISSUE THREAD

**Issue by saranyaanandan** [ariya/phantomjs#14371]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   PhantomJS 2.1.1
2. What steps will reproduce the problem?
   1. Html page contains hexa decimal code for background color.
   2. Export it as PDF.
   3. Exported PDF doesn't have the color.
3. Which operating system are you using?
   Windows 8.
4. Did you use binary PhantomJS or did you compile it from source?
   Binary
5. Please provide any additional information below.

**Comment by tahayk** [comment]
I have the same problem using PhantomJS 1.0.4 as a meteor package on Ubuntu 14

**Comment by nigulasikk** [comment]
the same problem uising phantomJS 2.1.1 on mac

**Comment by fangwChina** [comment]
the same problem uising phantomJS 2.1.1 on Windows 7

**Comment by pouu69** [comment]
the same issue using phantomJS 2.1.1 on mac
