### ISSUE TITLE
gzip body content

### ISSUE THREAD

**Issue by tasoss** [ariya/phantomjs#14372]
Hello i'm using 2.1.1 and i would like to ask about gzip content.I have found a few topics related but i don't know if they are exactly the same as mine.
The question is:
In onResourceReceived if the content is gzipped the bodysize is for example 20k but the body is empty.Is it possible somehow to get the response body ?
Thanks!

**Comment by gkio** [comment]
format will help

**Comment by tasoss** [comment]
indeed! :P

**Comment by gkio** [comment]
i know bro i am super duper ultra fixer 
FORMAT FTW

**Comment by tasoss** [comment]
gkio FTW ;)
