### ISSUE TITLE
phantomjs installs but fails to run due to Qt dependency

### ISSUE THREAD

**Issue by ralvez** [ariya/phantomjs#14377]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
phantom-prebuilt ver. 2.1.7

2. What steps will reproduce the problem?
  1. npm install phantomjs-prebuilt
  2. call node_modules/phantomjs-prebuilt/bin/phantom
  Response is : This application failed to start because it could not find or load the Qt platform plugin "xcb".

3. Which operating system are you using?
ArchLinux
4. Did you use binary PhantomJS or did you compile it from source?
npm install 

5. Please provide any additional information below.
I do have all the Qt libraries for xcb.
I also understand from the documentation in this site that there is no dependency on Qt

**Comment by Vitallium** [comment]
What's your env variable `QT_QPA_PLATFORM `? It must be empty to run PhantomJS successfully.

**Comment by esmeetu** [comment]
@Vitallium @ralvez 
 I have the same issue, my env is `QT_QPA_PLATFORM=xcb`.
after doing this: `QT_QPA_PLATFORM='' phantomjs --help`, it works well. 
But i don't know why.

**Comment by Vitallium** [comment]
No response. Closing.

**Comment by mleduque** [comment]
$ echo $QT_QPA_PLATFORM
xcb

(not the original poster)

**Comment by Rhathe** [comment]
> What's your env variable QT_QPA_PLATFORM? It must be empty to run PhantomJS successfully.

![why?](https://media.giphy.com/media/1M9fmo1WAFVK0/giphy.gif)

**Comment by solvemon** [comment]
A workaround is setting the env variable for the single call:

`QT_QPA_PLATFORM="" phantomjs myscript.js`

**Comment by Climax777** [comment]
@solvemon your workaround works. Shouldn't this be fixed in phantomjs?

**Comment by Vitallium** [comment]
The problem is that we compile PhantomJS statically, that means all dependencies (not in 2.5) will be compiled into a single binary (even Qt platform plugins). I already pushed the fix to master (https://github.com/ariya/phantomjs/commit/abd8ac58ea0a60482373df848d6b7928c722ca83)

**Comment by arendtio** [comment]
@Vitallium Any idea when or if the fix will become part of a release? I just stumbled upon this issue the second time :-/
