### ISSUE TITLE
Screen Capture: Huge corrupted image getting generated

### ISSUE THREAD

**Issue by nikhilgarg789** [ariya/phantomjs#14380]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?

Execute the following code:

var page = require('webpage').create();
page.viewportSize = { width: 1260, height: 800 };
page.open('https://www.onlinegambling.ca/real-money.php', function() {
  page.render(’screenshot.png');
  phantom.exit();
}); 
1. Which operating system are you using?
   Linux and Mac
2. Did you use binary PhantomJS or did you compile it from source?
   binary
3. Please provide any additional information below.
   The screenshot getting generated is huge in size and it is causing google chrome to hang / crash when the image is loaded in it. Firefox says "Error in image data".

**Comment by roohat** [comment]
`viewportSize` is only changes "browser" resolution, not effects which part to be rendered. Try with `clipRect`: [http://phantomjs.org/api/webpage/property/clip-rect.html](http://phantomjs.org/api/webpage/property/clip-rect.html)

**Comment by nikhilgarg789** [comment]
Yes the viewportSize is for defining the browser resolution. But in my case, the screenshot getting generated has width of more than 60,000 px. I have defined the viewport width as 1260.

**Comment by roohat** [comment]
I tested it and like you said it gives huge image output. Don't know what causes it but i get more desirable output with using `clipRect` and tingling with the `zoomFactor`.

For example; this:
```javascript
var page = require('webpage').create();

page.viewportSize = { width: 1260, height: 800 };
page.clipRect = {
  top: 0,
  left: 0,
  width: 1260,
  height: 800
};
page.zoomFactor = 1.5;

page.open('https://www.onlinegambling.ca/real-money.php', function() {
  page.render('screenshot.png');
  phantom.exit();
});

```
Gives [this](https://cloud.githubusercontent.com/assets/16094134/16412895/54b626ea-3d37-11e6-9b69-fd6e4f5d5718.png) (on windows).

Hope it helps.

**Comment by nikhilgarg789** [comment]
The solution suggested by you is giving the screenshot in mobile view. The requirement at our end is to have the screenshot at 1280 resolution.

I debugged and found that the following CSS is causing issue:

#header:before {
    background: url('../images/header/bg-header-btm.png') repeat-x transparent;
    bottom: 0;
    content: "";
    display: block;
    height: 75px;
    position: absolute;
    right: 100%;
    width: 5000em;
}
#header:after {
    background: url('../images/header/bg-header-btm.png') repeat-x transparent;
    bottom: 0;
    content: "";
    display: block;
    height: 75px;
    left: 100%;
    position: absolute;
    width: 5000em;
}

The width of "5000em" is causing the issue. The page renders correctly in browsers..not sure what is causing the issue in phantomjs.
