### ISSUE TITLE
PhantomJS Crashes consistently with bus error 10

### ISSUE THREAD

**Issue by JalfResi** [ariya/phantomjs#14388]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. run netsniff.js script with the following url: https://www.hertz.com/ e.g:
      $ phantomjs --debug=true netsniff.js https://www.hertz.com/
      Crashes for any url on the above domain
3. Which operating system are you using?
   OSX El Capitan v10.11.5
4. Did you use binary PhantomJS or did you compile it from source?
   Binary I think (maybe homebrew)
5. Please provide any additional information below.

Couldn't produce a stack trace but have attached the crash dump.

[hertz-crash-output.txt](https://github.com/ariya/phantomjs/files/346460/hertz-crash-output.txt)

[phantomjs_2016-07-04-151957_C07JVKD6DWYL-2.crash.zip](https://github.com/ariya/phantomjs/files/346458/phantomjs_2016-07-04-151957_C07JVKD6DWYL-2.crash.zip)

**Comment by JalfResi** [comment]
Tried on a different OSX and noticed that the line:
$ phantomjs --debug=true netsniff.js https://www.hertz.com/

works once, and then any subsequent runs produce the crash from then on.

This was also duplicated on Ubuntu:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

Same result: first run works fine, subsequent runs produce a segmentation fault with a core dump.

**Comment by JalfResi** [comment]
Issue remains post reboot!

**Comment by JalfResi** [comment]
Closed by mistake!

**Comment by allquixotic** [comment]
Unless you can dig into this with a debug build and run through the stack trace and figure out exactly what is causing the crash, it's unlikely that this will get fixed. 

Tsk, tsk... running PhantomJS in production; you should know better! ;)

This is a small, community-maintained project with basically no active maintainers (those who do contribute, do so on their own agenda, and rarely look at issues unless it affects them in their workload). You won't find much support here I'm afraid.

Anyway..... if you were using the Selenium interface to PhantomJS, you could have easily swapped out PhantomJS for something better, like jBrowserDriver (uses the Java VM's built-in webkit engine), or temporarily swap in a "headed" browser like Firefox just to get your work done.

For your own sanity I would recommend you investigate porting your work over to Selenium ASAP. Even if you end up using Selenium with PhantomJS via GhostDriver, in the long run you'll benefit by being able to swap out PhantomJS for something else with minimal code changes.

**Comment by JalfResi** [comment]
Agree on all points - the original plan was to integrate our tools directly using WebDriver to talk to any target browser we like, but as ever, time can always be better spent elsewhere. Anyway, I actually have pinned this issue down exactly, and have fix for this in place, so once I've finished testing I'll update the issue.

It appears that the issue has something to do with the ApplicationCache.db file - there are entries in there that do not match files on the FS, so I think its crashing there - clearing the tables (or even better, I'm hoping to use --disk-cache-path to specify a file I can delete after each request) appears to magically spring phantomjs back to life.

**Comment by JalfResi** [comment]
I've found a non-breaking fix for those who are happy to disable the PhantomJS cache to get this working. Simple run the following sqlite queries on the ApplicationCache.db. The location of this file differs depending on your OS:

OSX:
 ~/Library/Application\ Support/Ofi\ Labs/PhantomJS/ApplicationCache.db

Ubuntu: 
~/.local/share/Ofi\ Labs/PhantomJS/ApplicationCache.db
~/.qws/share/data/Ofi\ Labs/PhantomJS/ApplicationCache.db
OR
/root/.local/share/Ofi\ Labs/PhantomJS/ApplicationCache.db
/root/.qws/share/data/Ofi\ Labs/PhantomJS/ApplicationCache.db

The following SQL deletes all entries from the cache, and adds triggers which prevent new entries being added to the cache. This effectively stops the crashing.

```sqlite
DELETE FROM Caches;
DELETE FROM CacheAllowsAllNetworkRequests;
DELETE FROM CacheEntries;
DELETE FROM CacheGroups;
DELETE FROM CacheResourceData;
DELETE FROM CacheResources;
DELETE FROM Origins;
 
CREATE TRIGGER IF NOT EXISTS DisableCacheInsert AFTER INSERT ON Caches BEGIN DELETE FROM Caches WHERE id = NEW.id; END;
CREATE TRIGGER IF NOT EXISTS DisableCacheAllowsAllNetworkRequestsInsert AFTER INSERT ON CacheAllowsAllNetworkRequests BEGIN DELETE FROM CacheAllowsAllNetworkRequests WHERE wildcard = NEW.wildcard AND cache = NEW.cache; END;
CREATE TRIGGER IF NOT EXISTS DisableCacheEntriesInsert AFTER INSERT ON CacheEntries BEGIN DELETE FROM CacheEntries WHERE cache = NEW.cache AND type = NEW.type AND resource = NEW.resource; END;
CREATE TRIGGER IF NOT EXISTS DisableCacheGroupsInsert AFTER INSERT ON CacheGroups BEGIN DELETE FROM CacheGroups WHERE id = NEW.id; END;
CREATE TRIGGER IF NOT EXISTS DisableCacheResourceDataInsert AFTER INSERT ON CacheResourceData BEGIN DELETE FROM CacheResourceData WHERE id = NEW.id; END;
CREATE TRIGGER IF NOT EXISTS DisableCacheResourcesInsert AFTER INSERT ON CacheResources BEGIN DELETE FROM CacheResources WHERE id = NEW.id; END;
CREATE TRIGGER IF NOT EXISTS DisableOriginsInsert AFTER INSERT ON Origins BEGIN DELETE FROM Origins WHERE origin = NEW.origin AND quota = NEW.quota; END;
```

**Comment by wallneradam** [comment]
You can simply disable cache by command line parameter:
`phantomjs --disk-cahe=false --max-disk-cache-size=0 yourscript.js`

I checked, I deleted the cache directory, and it is not created again. With this parameters.
