### ISSUE TITLE
Why is phantom rendering a different document than all other browsers ?

### ISSUE THREAD

**Issue by theguythatrepeatedit** [ariya/phantomjs#14381]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`
2.1.1.

2. What steps will reproduce the problem?
  1. load a url (that I can not share)
  2. wait for a hundred years, or not - in all imaginable viewports and user agents
  3. try --debug=true
  3. take a screenshot
  4. compare the result with safari, chrome, ff, IE, Netscape
  5. try remote debugging, try throwing exceptions, try crying, try googling, try outing the source and read it until your eyes bleed, try punching yourself in the mouth

**Result:**
No other browser on earth renders like phantom - and it looks like crap

3. Which operating system are you using?
Windows

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.
Help me - please help me understand what it is that make phantom render a web document like it does - it makes no sense! then I can fix it! is there a graphic reference engine anywhere on this planet ?

**Comment by roohat** [comment]
It may help: [https://github.com/ariya/phantomjs/issues/14380#issuecomment-228960441](https://github.com/ariya/phantomjs/issues/14380#issuecomment-228960441)
