### ISSUE TITLE
UI tests with PhantomJS affect hardware in the workstation and the server

### ISSUE THREAD

**Issue by SeregaZH** [ariya/phantomjs#14384]
When I am running tests in my workstation all my peripheral devices is not working. Mouse is freezing, audio card stopped, sometimes monitors extinguished due to Intel display adapter stopped their work. 

Also when we enabled tests execution in the our server it have started to become unreachable time to time. After disabling the tests in the server it have became stable.

I have Windows 8.1 on the my workstation but it is also reproducible on Windows 7. 
1. What steps will reproduce the problem?
   1. Run test using karma+pahantomjs.
   2. Node.js server was started normally.
   3. When phantomjs started to execute tests all peripheral devices became freezing.
2. Environment: Windows 7, Windows 8.1
3. I use binary. I used npm to install phantomjs.
4. Here is the link on the my question on the stackoverflow with additional information and configuration (http://stackoverflow.com/questions/38051985/ui-tests-with-phantomjs-affect-hardware-in-the-workstation-and-server).

Thank you in advance,
Siarhei

**Comment by jmullo** [comment]
I confirm the mouse, audio & display adapter freeze on Windows 7. The freeze happens every time at the end of Karma test run.

Related issue: #14033
