### ISSUE TITLE
TypeError: window object - null is not an object

### ISSUE THREAD

**Issue by randyamiel** [ariya/phantomjs#14382]
**PhantomJS - Version 2.1.1 - Windows 7 - Bin**

Window object returns null. Line 1177 - Attaching JS
_TypeError: null is not an object (evaluating 'portalWnd.getEventObject') (index_1.concat.js:1177)_
[index_1.concat.js.txt](https://github.com/ariya/phantomjs/files/335923/index_1.concat.js.txt)

This call the function on line 5301:
'''//-----------------------------------------------------------------------------
function getEventObject(evt,wnd)
{
    if (typeof(wnd) == "undefined")
        return (evt ? evt : (window.event ? window.event : null));
    else
        return (evt ? evt : (wnd.event ? wnd.event : null));
}
'''

**Comment by iam-peekay** [comment]
@randyamiel I have the same issue. Did you end up figuring it out?

**Comment by randyamiel** [comment]
@iam-peekay I haven't figured it out yet, but I'm guessing the function is being called before phantomJS creates the javascript window object. I don't think the DOM is fully loaded. Possibly, changing to window.onload instead as a fix, but I'm not sure how phantomJS is processing the javascript differently then a non-headless browser. Or maybe the window object is not being handled the same way. Anyone?
