### ISSUE TITLE
PhantomJS has crashed

### ISSUE THREAD

**Issue by eugenet8k** [ariya/phantomjs#14393]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   phantomjs-1.9.8-linux-x86_64
2. What steps will reproduce the problem?
   Not sure, if there is an easy way. It's failed during running our front end unit tests using mocha in the CI linux environment.
3. Which operating system are you using?
   Linux
4. Did you use binary PhantomJS or did you compile it from source?
   Binary https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-linux-x86_64.tar.bz2
5. Please provide any additional information below.
   The stack trace restored from symbols is attached in [dump.txt](https://github.com/ariya/phantomjs/files/350661/dump.txt)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
