### ISSUE TITLE
Consecutive Not Concurrent Multiple Requests Leads to 'PhantomJS has crashed'

### ISSUE THREAD

**Issue by vincer-innoverne** [ariya/phantomjs#14392]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

$ phantomjs --version
1.9.8

2. What steps will reproduce the problem?

Not sure, but this works time & time again, however this is the first time I've seen PhantomJs crash. Essentially I am:

- Logging in (sign in) to a development website
- Navigating to a particular page
- Adding an Asset Group
- Adding an Asset to that Group
- Logging Out
- Repeat 
[crash.zip](https://github.com/ariya/phantomjs/files/349543/crash.zip)

x9: crashed on the 7th run

3. Which operating system are you using?

$ uname -a
Linux WKS101029 3.19.0-64-generic #72-Ubuntu SMP Fri Jun 24 15:12:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

4. Did you use binary PhantomJS or did you compile it from source?

Binary

5. Please provide any additional information below.

Run several consecutive commands to hit a website & generate many assets.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
