### ISSUE TITLE
Webpage module `getCookies(url)` 

### ISSUE THREAD

**Issue by abozhilov** [ariya/phantomjs#14391]
Current array `cookies` does not provide convenient way to retrieve all cookies for particular URL. 
I guess would be easier for you to use optimized data structure in order to implement `getCookies(url)`. 

Thoughts?

**Comment by Vitallium** [comment]
@abozhilov Could you please write a few samples how do you see this API method? Just to be sure that we are on the same line.

**Comment by abozhilov** [comment]
Currently there is no way to extract cookies which are sent for certain requests. We can found several issues here related to missing `Cookie` request header. 
With API like this we can get all cookies related to certain request in `onResourceRequested` e.g.

```
page.onResourceRequested = function(request, networkRequest) {
    page.getCookies(request.url);   
};
```
