### ISSUE TITLE
onbeforeunload callbacks do not allow network requests

### ISSUE THREAD

**Issue by Gerg** [ariya/phantomjs#14396]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   
   > 2.1.1
2. What steps will reproduce the problem?
   1. Register a `beforeunload` callback containing a network request.
   2. Load the page in phantom
   3. Close the page
   4. The callback triggers but the network request is not made
   
   Example: 

``` js
window.addEventListener('beforeunload', function () {
   $.post('/foo', {});
});
```
1. Which operating system are you using?

> OSX
1. Did you use binary PhantomJS or did you compile it from source?

> Installed via homebrew
1. Please provide any additional information below.

> It works in Chrome/Firefox/Safari.

**Comment by elias-winberg** [comment]
This is most likely due to the fact that `$.post('/foo', {});` is an asynchronous operation, and that the page closes before the operation is finished. You need to replace the asynchronous operation with a synchronous one:

```js
$.ajax({
    async: false,
    data: {},
    type: "post",
    url: "/foo"
});
```

**Comment by Gerg** [comment]
Using JQuery synchronous requests is our current work-around. However `async: false` is [deprecated as of 1.8](https://blog.jquery.com/2012/08/09/jquery-1-8-released/) and is a hack anyway. What we really want is the proposed [beacon standard](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon).

As far as I can tell, sending xhr requests as the page unloads is a gray area in the browser spec. Chrome and Safari let the request through. Firefox lets it through but trigger the 'fail' callback. IE aborts the request and Phantom appears to not even make the request.

In this gray space, it would be nice if PhantomJS adopted the more lenient behavior of Chrome/Safari.

**Comment by erikdubbelboer** [comment]
I just tested this with the latest Firefox, Chrome and Safari on Mac and only Chrome actually sends the HTTP request if it's `async`. Firefox and Safari both don't even send the request.

**Comment by Gerg** [comment]
That's interesting because I definitely saw the requests reach my server from Firefox/Safari. I was running the server locally, so it's possible that it only worked because of the low latency.

**Comment by erikdubbelboer** [comment]
Looks like you are right. I tested it a bit more now. Before I tested using PHP, now I'm testing with nodejs. Firefox does request the URL, I'm guessing PHP was too slow and didn't start before the request was cancelled. I still can't get it to work with Safari (both local and remote). The only time Safari seems to request the url is when I exit Safari.

```js
require('http').createServer(function(req, res) {
  console.log(req.url);

  res.statusCode = 200;
  res.end(`
<!doctype html>
<html>
<head>
<meta charset=utf-8>
<title>beforeunload ajax test</title>
</head>
<body>

<a href='http://example.com'>link</a>

<script>

window.addEventListener('beforeunload', function () {
  var x = new XMLHttpRequest();
  x.onreadystatechange = function() {
    console.log(x.readyState, x.status);
  };
  x.open('GET', 'http://dubbelboer.com:8090/beforeunload', true);
  x.send();
});

</script>
</body>
</html>
  `)
}).listen(8090);
```

**Comment by Vitallium** [comment]
Quick question: are you doing this in the main execution context? Or with a real web page?

**Comment by Gerg** [comment]
@erikdubbelboer I too am using a node backend. I also noticed that Safari only made the request when closing the tab, but at the time I just assumed it was because the event was not firing on refresh.

@Vitallium It's a real webpage. I tested Chrome/ Firefox manually and using webdriverio (where their behavior matched). I only tested phantom using webdriverio.

**Comment by FelipeeDev** [comment]
What about this issue? I'm forcing it too. Are there any other way or a hook to handle the `onbeforeunload` event through the webdriver and *phantomjs*?

**Comment by nadavye** [comment]
@FelipeeDev @Gerg Did you guys managed to solve this one?
I'm facing it myself.
