### ISSUE TITLE
FreeBSD 10.3 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Nikolassssss** [ariya/phantomjs#14407]
Why is latest version for FreeBSD - 2.0.0?? On your site - 2.1.1

```
console.log('Loading a web page');
var page = require('webpage').create();
var url = 'https://www.similarweb.com/';
page.open(url, function (status) {
    console.log('Page is loaded!');
    phantom.exit();
});
```

After run this code i have **Segmentation fault (core dumped)**.

If i run this code on windows/debian - its ok.
For windows/debian i use v2.1.1.

I have problem only with this site.
Can u update phantomjs for FreeBSD?

**UDP**
Sometimes i have:

> PhantomJS has crashed. Please read the bug reporting guide at
> http://phantomjs.org/bug-reporting.html and file a bug report.
> Segmentation fault

On debian with phantomjs v2.1.1

**Comment by Nikolassssss** [comment]
And add please something to change ip interface, for exampke curl_interface in curl php

**Comment by Vitallium** [comment]
How did you install PhantomJS?

**Comment by annulen** [comment]
Port was last upgraded 10 month ago, please contact its maintainer, or just try to change `PORTVERSION` in Makefile to 2.1.1

http://www.freshports.org/lang/phantomjs/

**Comment by Nikolassssss** [comment]
pkg install phantomjs
how change PORTVERSION ?

**Comment by Nikolassssss** [comment]
https://bitbucket.org/ariya/phantomjs/downloads/
phantomjs-2.0.0-source.zip - latest version
phantomjs-2.1.1-source.zip - not found

even if you change the makefiles that he be updated because the repository the latest version 2.0

**Comment by Nikolassssss** [comment]
Say what? could you update the script under FreeBSD?

**Comment by Nikolassssss** [comment]
I still have this error under FreeBSD (version 2.0).

**Comment by jc-gm** [comment]
I updated from 1.9 to 2.0 and I'm now having the same issues,  segmentation fault.
I'm wondering if anyone knows how to fix this issue

**Comment by bogdik** [comment]
FreeBSD 11.0-RELEASE-p8
phantomjs 2.1.1
Segmentation fault
