### ISSUE TITLE
Windows download does not work

### ISSUE THREAD

**Issue by Nannooskeeska** [ariya/phantomjs#14400]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
None

2. What steps will reproduce the problem?
  1. Go to http://phantomjs.org/download.html
  2. Click on the Windows download link
  3. "This XML file does not appear to have any style information associated with it. The document tree is shown below."

3. Which operating system are you using?
Windows 8.1

4. Did you use binary PhantomJS or did you compile it from source?
N/A

5. Please provide any additional information below.
N/A

**Comment by Vitallium** [comment]
Hi. Thanks for reporting. But this is not a PhantomJS issue. We host our binaries on Bitbucket (on S3 to be more specific). Sometimes it goes down. Just try again a bit later.

**Comment by Nannooskeeska** [comment]
Ah it's working now. Thanks! I thought that the link was broken or something :)
