### ISSUE TITLE
Remote debugging not working on PhantomJs (2.1.1) (Windows 10)

### ISSUE THREAD

**Issue by lawred2** [ariya/phantomjs#14408]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

Version 2.1.1
1. What steps will reproduce the problem?

Just try to enable remote debugger - specify any known available port

--remote-debugger-port=XXXX

Then use netstat -abno and nothing will appear as listening on port XXXX
Attempts to connect using chrome to that port fail for site not found
No visible errors in phantomjs debug console output
1. Which operating system are you using?

Windows 10
1. Did you use binary PhantomJS or did you compile it from source?

Binary
1. Please provide any additional information below.

**Comment by Vitallium** [comment]
You have to add `--remote-debugger-autorun=yes` to enable debugger. Did it work in previous version (1.9.8)?

**Comment by lawred2** [comment]
Hi..

According to the documentation _--remote-debugger-autorun=yes_ is not required to enable debugging. 

http://phantomjs.org/troubleshooting.html

It's purpose according to the documentation is

> After setting breakpoints (or if you are using debugger instead), to run your script, simply enter the __run() command in the Web Inspector Console. Alternatively, use --remote-debugger-autorun=yes command-line argument to have your script launched immediately.

Either way I tried adding it and it made no difference. I also tried the 1.9.8 binary and that didn't work either. 

Has debugging been verified on Windows 10?

**Comment by lzwsoar** [comment]
Same issue on Windows 10 x64.

**Comment by joeparkerz** [comment]
This still doesn't work.

phantomjs --remote-debugger-port=9001 --remote-debugger-autorun=yes --proxy-type=none

Result: 404 when accesing http://localhost:9001 in a browser.

**Comment by iradul** [comment]
It seems like it doesn't work anymore in newer versions of Chrome. `__run()` call doesn't seem to be evaluated nor anything else typed in console.

As an alternative you can try [code](https://code.visualstudio.com/) editor with phantomjs debugger plugin.

**Comment by sryze** [comment]
Same here, WIndows 10, phantomjs 2.1.1 and Chrome 56.

**Comment by stormbeta** [comment]
Confirm this is also broken on macOS Sierra, Chrome 58.0.3029.110.

It's also broken in Safari and Firefox in different ways.

**Comment by chinafootballyu** [comment]
Same here, Windows7, phantomjs 2.1.1 and Chrome 58 + .

**Comment by restmeter** [comment]
same here, windows 10, phantomjs 2.1.1 and chrome 62

**Comment by v1r** [comment]
Same here, windows 7, v2.1.1 and Chrome 62. I eneded up replacing it with Puppeteers.

**Comment by derMart** [comment]
damn debugging is really important
