### ISSUE TITLE
Precompiled version 2.1.1 doesn't run on CentOS 5.5

### ISSUE THREAD

**Issue by silvangithub** [ariya/phantomjs#14409]
(sorry for newbie question)

I am running a linux server, version: CentOS release 5.5 (Final)

I receive following error after "npm install phantomjs" and running "phantomjs -v"

phantomjs: /usr/lib64/libz.so.1: no version information available (required by phantomjs)
phantomjs: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by phantomjs)
phantomjs: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by phantomjs)
phantomjs: /lib64/libc.so.6: version `GLIBC_2.9' not found (required by phantomjs)
phantomjs: /lib64/libc.so.6: version `GLIBC_2.10' not found (required by phantomjs)
phantomjs: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by phantomjs)

When i type "ldd --version": ldd (GNU libc) 2.5

When I type "yum list glibc"...
Loaded plugins: fastestmirror
base                                                                                                      3667/3667
Installed Packages
glibc.i686                                         2.5-49.el5_5.7                                          installed
glibc.x86_64                                       2.5-49.el5_5.7                                          installed
Available Packages
glibc.i686                                         2.5-123.el5_11.3                                        updates
glibc.x86_64                                       2.5-123.el5_11.3                                        updates

**Comment by zackw** [comment]
Yes, this is a known problem.  CentOS 5.5 ships with C and C++ runtime libraries that are just too old for the precompiled version.  You will need to compile PhantomJS yourself, and we can't guarantee it will work -- those libraries might be too old, period.  My personal recommendation is that you should switch to Debian stable, which is nice and stable but not nearly as outdated; however, you'd have to get used to a different set of system management tools.

(Note: [GLib](https://developer.gnome.org/glib/) and [GNU libc](https://www.gnu.org/software/libc/libc.html) are completely unrelated libraries.  PhantomJS does not use GLib.)
