### ISSUE TITLE
phantomjs force urlencode the location.hash which is different with modern browsers(such as Chrome)

### ISSUE THREAD

**Issue by kxcode** [ariya/phantomjs#14417]
like this issue:
https://groups.google.com/d/msg/phantomjs/riFlgcSi8Rg/iVgTozpUaFUJ
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   all
2. What steps will reproduce the problem?
   1. open http://xxxx.com/aaa#<test> in chrome and phantomjs
   2. print location.hash , and they are different

**Comment by KxCode** [comment]
which sourcecode affects this issue,  or is it a feature in qtwebkit ?

**Comment by KxCode** [comment]
i wrote a demo using qt webview control,
seems that this issue is a feature in qtwebkit engine
