### ISSUE TITLE
Clickable Links in SVG converted to PDF don't work

### ISSUE THREAD

**Issue by slominskir** [ariya/phantomjs#14410]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   Use the example rasterize.js to convert a webpage with an svg containing an anchor 
3. Which operating system are you using?
   Windows
4. Did you use binary PhantomJS or did you compile it from source?
   Binary
5. Please provide any additional information below.
   If I use Chrome 51 to print to PDF the document has clickable links (even if the source was SVG)

This is similar to, but not the same as https://github.com/ariya/phantomjs/issues/10196

**Comment by synoptive** [comment]
We see this issue as well using PhantomJS 2.1.7. Links like this:
`<a href="https://goo.gl/D7xRVk"><text x="17" y="663" class="st1 st10 link">https://goo.gl/D7xRVk</text></a>`

inside SVG rendered to PDF are not clickable. Using jsPDF in browser works.
