### ISSUE TITLE
Symbol tarball not available for 2.1.1

### ISSUE THREAD

**Issue by tomredsky** [ariya/phantomjs#14412]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2.1.1
1. What steps will reproduce the problem?
   1. I tried to download the symbol tar to create a mindump but they are not available.
2. Which operating system are you using?
   CentOS 6.7
3. Did you use binary PhantomJS or did you compile it from source?
   binary.
4. Please provide any additional information below.

**Comment by mrog** [comment]
This would be useful for me, too.  Any progress?
