### ISSUE TITLE
Error - PhantomJS has crashed 

### ISSUE THREAD

**Issue by gaurav-balodi** [ariya/phantomjs#14414]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
1.9.0
2. What steps will reproduce the problem?
  1.
[6ab47c40-b1bf-cc41-699ad54b-0b6bded0.dmp.zip](https://github.com/ariya/phantomjs/files/370907/6ab47c40-b1bf-cc41-699ad54b-0b6bded0.dmp.zip)

3. Which operating system are you using?
Linux 14.04
4. Did you use binary PhantomJS or did you compile it from source?
Compiled from source
5. Please provide any additional information below.
I am using capybara gem with poltergeist in a ROR project to scrape a particular site. And, this crash keeps occurring while a new page is being visited.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
