### ISSUE TITLE
PhantomJS 2.0.1-development has crashed Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by praveen-kaple** [ariya/phantomjs#14416]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.0.1-development
2. What steps will reproduce the problem?
   Stack Trace:
   Operating system: Linux
                 0.0.0 Linux 2.6.32-573.8.1.el6.x86_64 #1 SMP Tue Nov 10 18:01:38 UTC 2015 x86_64
   CPU: amd64
    family 6 model 60 stepping 3
    4 CPUs

Crash reason:  SIGSEGV
Crash address: 0x87ab5e67

Thread 0 (crashed)
 0  libc-2.12.so + 0x89781
    rbx = 0x0000000004d0eaf0   r12 = 0x00000000051599d0
    r13 = 0x0000000004e29aa8   r14 = 0x0000000004ed6328
    r15 = 0x0000000007ab5e68   rip = 0x0000003c94a89781
    rsp = 0x00007ffef1ee6718   rbp = 0x0000000000000035
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1b3b4f5
    rip = 0x0000000001f3b4f6   rsp = 0x00007ffef1ee6720
    Found by: stack scanning
 2  phantomjs + 0x1a311de
    rip = 0x0000000001e311df   rsp = 0x00007ffef1ee6740
    Found by: stack scanning
 3  phantomjs + 0x1b3b7e7
    rip = 0x0000000001f3b7e8   rsp = 0x00007ffef1ee6770
    Found by: stack scanning
 4  phantomjs + 0x1b3b4f5
    rip = 0x0000000001f3b4f6   rsp = 0x00007ffef1ee6790
    Found by: stack scanning
 5  phantomjs + 0x227701f
    rip = 0x0000000002677020   rsp = 0x00007ffef1ee67c0
    Found by: stack scanning
 6  phantomjs + 0x22771bf
    rip = 0x00000000026771c0   rsp = 0x00007ffef1ee67c8
    Found by: stack scanning
 7  phantomjs + 0x1c1a9e8
    rip = 0x000000000201a9e9   rsp = 0x00007ffef1ee6800
    Found by: stack scanning
 8  phantomjs + 0x1b56837
    rip = 0x0000000001f56838   rsp = 0x00007ffef1ee6820
    Found by: stack scanning
 9  phantomjs + 0x227701f
    rip = 0x0000000002677020   rsp = 0x00007ffef1ee6830
    Found by: stack scanning
10  phantomjs + 0x22771bf
    rip = 0x00000000026771c0   rsp = 0x00007ffef1ee6838
    Found by: stack scanning
11  phantomjs + 0x1cae3aa
    rip = 0x00000000020ae3ab   rsp = 0x00007ffef1ee6840
    Found by: stack scanning
12  phantomjs + 0x21ecb3f
    rip = 0x00000000025ecb40   rsp = 0x00007ffef1ee6890
    Found by: stack scanning
13  phantomjs + 0x21d096d
    rip = 0x00000000025d096e   rsp = 0x00007ffef1ee68a0
    Found by: stack scanning
14  phantomjs + 0x1b57246
    rip = 0x0000000001f57247   rsp = 0x00007ffef1ee68e0
    Found by: stack scanning
15  phantomjs + 0x21d096d
    rip = 0x00000000025d096e   rsp = 0x00007ffef1ee6948
    Found by: stack scanning
16  phantomjs + 0x194dd9b
    rip = 0x0000000001d4dd9c   rsp = 0x00007ffef1ee6980
    Found by: stack scanning
17  phantomjs + 0x19483ff
    rip = 0x0000000001d48400   rsp = 0x00007ffef1ee69e0
    Found by: stack scanning
18  phantomjs + 0x194de7a
    rip = 0x0000000001d4de7b   rsp = 0x00007ffef1ee6a50
    Found by: stack scanning
19  libc-2.12.so + 0x7ab1b
    rip = 0x0000003c94a7ab1c   rsp = 0x00007ffef1ee6af0
    Found by: stack scanning
20  libstdc++.so.6.0.13 + 0xbd0bc
    rip = 0x0000003c9b6bd0bd   rsp = 0x00007ffef1ee6b10
    Found by: stack scanning
21  phantomjs + 0x1924e42
    rip = 0x0000000001d24e43   rsp = 0x00007ffef1ee6b30
    Found by: stack scanning
22  phantomjs + 0x1910e3c
    rip = 0x0000000001d10e3d   rsp = 0x00007ffef1ee6ba0
    Found by: stack scanning
23  phantomjs + 0x35cca3
    rip = 0x000000000075cca4   rsp = 0x00007ffef1ee6bb0
    Found by: stack scanning
24  phantomjs + 0xb914ce
    rip = 0x0000000000f914cf   rsp = 0x00007ffef1ee6c80
    Found by: stack scanning
25  phantomjs + 0x339689
    rip = 0x000000000073968a   rsp = 0x00007ffef1ee6cc0
    Found by: stack scanning
26  phantomjs + 0x35cf03
    rip = 0x000000000075cf04   rsp = 0x00007ffef1ee6d00
    Found by: stack scanning
27  phantomjs + 0x45c561
    rip = 0x000000000085c562   rsp = 0x00007ffef1ee6d70
    Found by: stack scanning
28  phantomjs + 0x34d7e7
    rip = 0x000000000074d7e8   rsp = 0x00007ffef1ee6db0
    Found by: stack scanning
29  phantomjs + 0xd081c3
    rip = 0x00000000011081c4   rsp = 0x00007ffef1ee6de0
    Found by: stack scanning
30  phantomjs + 0xdb7ba5
    rip = 0x00000000011b7ba6   rsp = 0x00007ffef1ee6e80
    Found by: stack scanning
31  phantomjs + 0xd52208
    rip = 0x0000000001152209   rsp = 0x00007ffef1ee6f00
    Found by: stack scanning
32  phantomjs + 0xd5ecd1
    rip = 0x000000000115ecd2   rsp = 0x00007ffef1ee6f50
    Found by: stack scanning

Thread 1
 0  libpthread-2.12.so + 0xb63c
    rbx = 0x0000000002f5a820   r12 = 0x0000000000000000
    r13 = 0x00007f05c86e93f0   r14 = 0x0000000002f66490
    r15 = 0x000000000000009f   rip = 0x0000003c94e0b63c
    rsp = 0x00007f0646c99d20   rbp = 0x0000000000000001
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1346702
    rip = 0x0000000001746703   rsp = 0x00007f0646c99d50
    Found by: stack scanning
 2  phantomjs + 0x1346728
    rip = 0x0000000001746729   rsp = 0x00007f0646c99dd0
    Found by: stack scanning
 3  libpthread-2.12.so + 0x7a50
    rip = 0x0000003c94e07a51   rsp = 0x00007f0646c99de0
    Found by: stack scanning

Thread 2
 0  libc-2.12.so + 0xe15be
    rbx = 0x00007f0606136a30   r12 = 0x00007f0600000a78
    r13 = 0x0000000000000000   r14 = 0x00007f0600000f98
    r15 = 0x0000000000000007   rip = 0x0000003c94ae15be
    rsp = 0x00007f0606136980   rbp = 0x00007f0600000d08
    Found by: given as instruction pointer in context
 1  ld-2.12.so + 0xe0bf
    rip = 0x0000003c9460e0c0   rsp = 0x00007f06061369b0
    Found by: stack scanning
 2  libc-2.12.so + 0xe567
    rip = 0x0000003c94a0e568   rsp = 0x00007f06061369d0
    Found by: stack scanning
 3  ld-2.12.so + 0x148f4
    rip = 0x0000003c946148f5   rsp = 0x00007f0606136a00
    Found by: stack scanning
 4  librt-2.12.so + 0x3e45
    rip = 0x0000003c95e03e46   rsp = 0x00007f0606136a20
    Found by: stack scanning
 5  phantomjs + 0x73d9b9
    rip = 0x0000000000b3d9ba   rsp = 0x00007f0606136a58
    Found by: stack scanning
 6  phantomjs + 0x341958
    rip = 0x0000000000741959   rsp = 0x00007f0606136a60
    Found by: stack scanning
 7  phantomjs + 0x1c386ec
    rip = 0x00000000020386ed   rsp = 0x00007f0606136a80
    Found by: stack scanning
 8  phantomjs + 0x73d9b9
    rip = 0x0000000000b3d9ba   rsp = 0x00007f0606136a98
    Found by: stack scanning
 9  phantomjs + 0x341958
    rip = 0x0000000000741959   rsp = 0x00007f0606136aa0
    Found by: stack scanning
10  phantomjs + 0x1c390e2
    rip = 0x00000000020390e3   rsp = 0x00007f0606136ab0
    Found by: stack scanning
11  phantomjs + 0x73d9b9
    rip = 0x0000000000b3d9ba   rsp = 0x00007f0606136ac8
    Found by: stack scanning
12  phantomjs + 0x341958
    rip = 0x0000000000741959   rsp = 0x00007f0606136ad0
    Found by: stack scanning
13  phantomjs + 0x1c39988
    rip = 0x0000000002039989   rsp = 0x00007f0606136b10
    Found by: stack scanning
14  phantomjs + 0x1bf9dbc
    rip = 0x0000000001ff9dbd   rsp = 0x00007f0606136b50
    Found by: stack scanning
15  phantomjs + 0x1adff57
    rip = 0x0000000001edff58   rsp = 0x00007f0606136b70
    Found by: stack scanning
16  phantomjs + 0x73d9b9
    rip = 0x0000000000b3d9ba   rsp = 0x00007f0606136b88
    Found by: stack scanning
17  phantomjs + 0x341345
    rip = 0x0000000000741346   rsp = 0x00007f0606136b90
    Found by: stack scanning
18  librt-2.12.so + 0x3e45
    rip = 0x0000003c95e03e46   rsp = 0x00007f0606136ba0
    Found by: stack scanning
19  phantomjs + 0x1adff57
    rip = 0x0000000001edff58   rsp = 0x00007f0606136bc0
    Found by: stack scanning
20  phantomjs + 0x73d9b9
    rip = 0x0000000000b3d9ba   rsp = 0x00007f0606136bd8
    Found by: stack scanning
21  phantomjs + 0x34151b
    rip = 0x000000000074151c   rsp = 0x00007f0606136be0
    Found by: stack scanning
22  phantomjs + 0x31d548
    rip = 0x000000000071d549   rsp = 0x00007f0606136bf0
    Found by: stack scanning
23  phantomjs + 0x1c3b489
    rip = 0x000000000203b48a   rsp = 0x00007f0606136c00
    Found by: stack scanning
24  phantomjs + 0x1c39e2c
    rip = 0x0000000002039e2d   rsp = 0x00007f0606136c40
    Found by: stack scanning
25  phantomjs + 0x1bf3fb0
    rip = 0x0000000001ff3fb1   rsp = 0x00007f0606136c90
    Found by: stack scanning
26  phantomjs + 0x1c1a9e8
    rip = 0x000000000201a9e9   rsp = 0x00007f0606136cc0
    Found by: stack scanning
27  libstdc++.so.6.0.13 + 0xbd0bc
    rip = 0x0000003c9b6bd0bd   rsp = 0x00007f0606136cd0
    Found by: stack scanning
28  phantomjs + 0x1bf3c43
    rip = 0x0000000001ff3c44   rsp = 0x00007f0606136cf0
    Found by: stack scanning
29  phantomjs + 0x1a277d9
    rip = 0x0000000001e277da   rsp = 0x00007f0606136d30
    Found by: stack scanning
30  phantomjs + 0x1a2ce4a
    rip = 0x0000000001e2ce4b   rsp = 0x00007f0606136d70
    Found by: stack scanning
31  libpthread-2.12.so + 0x7a50
    rip = 0x0000003c94e07a51   rsp = 0x00007f0606136de0
    Found by: stack scanning

Thread 3
 0  libpthread-2.12.so + 0xb63c
    rbx = 0x00007f06461f6204   r12 = 0x0000000000000000
    r13 = 0x00007f06461f6058   r14 = 0x00007f06461f6208
    r15 = 0x00007f06461f6230   rip = 0x0000003c94e0b63c
    rsp = 0x00007f0605719d50   rbp = 0x0000000000000001
    Found by: given as instruction pointer in context
 1  phantomjs + 0x1050765
    rip = 0x0000000001450766   rsp = 0x00007f0605719d80
    Found by: stack scanning
 2  phantomjs + 0x13752a0
    rip = 0x00000000017752a1   rsp = 0x00007f0605719dd0
    Found by: stack scanning
 3  libpthread-2.12.so + 0x7a50
    rip = 0x0000003c94e07a51   rsp = 0x00007f0605719de0
    Found by: stack scanning

Thread 4
 0  libpthread-2.12.so + 0xb63c
    rbx = 0x0000000004c95e20   r12 = 0x00007f06461fece8
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000003c94e0b63c
    rsp = 0x00007f0604cf9d70   rbp = 0x0000000004c94660
    Found by: given as instruction pointer in context
 1  phantomjs + 0x10518e2
    rip = 0x00000000014518e3   rsp = 0x00007f0604cf9da0
    Found by: stack scanning
 2  phantomjs + 0x13752a0
    rip = 0x00000000017752a1   rsp = 0x00007f0604cf9dd0
    Found by: stack scanning
 3  libpthread-2.12.so + 0x7a50
    rip = 0x0000003c94e07a51   rsp = 0x00007f0604cf9de0
    Found by: stack scanning

Thread 5
 0  libpthread-2.12.so + 0xb63c
    rbx = 0x0000000004ccee10   r12 = 0x00007f06461fece8
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000003c94e0b63c
    rsp = 0x00007f05ffffed70   rbp = 0x0000000004c94840
    Found by: given as instruction pointer in context
 1  phantomjs + 0x10518e2
    rip = 0x00000000014518e3   rsp = 0x00007f05ffffeda0
    Found by: stack scanning
 2  phantomjs + 0x13752a0
    rip = 0x00000000017752a1   rsp = 0x00007f05ffffedd0
    Found by: stack scanning
 3  libpthread-2.12.so + 0x7a50
    rip = 0x0000003c94e07a51   rsp = 0x00007f05ffffede0
    Found by: stack scanning

Thread 6
 0  libpthread-2.12.so + 0xb63c
    rbx = 0x0000000004cbcf10   r12 = 0x00007f06461fece8
    r13 = 0x0000000000000001   r14 = 0x0000000000000000
    r15 = 0x0000000000000003   rip = 0x0000003c94e0b63c
    rsp = 0x00007f05ff5fdd70   rbp = 0x0000000004c94a20
    Found by: given as instruction pointer in context
 1  phantomjs + 0x10518e2
    rip = 0x00000000014518e3   rsp = 0x00007f05ff5fdda0
    Found by: stack scanning
 2  phantomjs + 0x13752a0
    rip = 0x00000000017752a1   rsp = 0x00007f05ff5fddd0
    Found by: stack scanning
 3  libpthread-2.12.so + 0x7a50
    rip = 0x0000003c94e07a51   rsp = 0x00007f05ff5fdde0
    Found by: stack scanning

Thread 7
 0  libc-2.12.so + 0xe15be
    rbx = 0x00007f05fe602a30   r12 = 0x00007f05e4000a78
    r13 = 0x0000000000000000   r14 = 0x00007f05e4000f98
    r15 = 0x0000000000000013   rip = 0x0000003c94ae15be
    rsp = 0x00007f05fe602980   rbp = 0x00007f05e4000d08
    Found by: given as instruction pointer in context
 1  librt-2.12.so + 0x3e45
    rip = 0x0000003c95e03e46   rsp = 0x00007f05fe602a20
    Found by: stack scanning
 2  phantomjs + 0x73d99b
    rip = 0x0000000000b3d99c   rsp = 0x00007f05fe602a58
    Found by: stack scanning
 3  phantomjs + 0x1c386ec
    rip = 0x00000000020386ed   rsp = 0x00007f05fe602a80
    Found by: stack scanning
 4  phantomjs + 0x73d99b
    rip = 0x0000000000b3d99c   rsp = 0x00007f05fe602a98
    Found by: stack scanning
 5  phantomjs + 0x1c390e2
    rip = 0x00000000020390e3   rsp = 0x00007f05fe602ab0
    Found by: stack scanning
 6  phantomjs + 0x73d99b
    rip = 0x0000000000b3d99c   rsp = 0x00007f05fe602ac8
    Found by: stack scanning
 7  phantomjs + 0x1c39988
    rip = 0x0000000002039989   rsp = 0x00007f05fe602b10
    Found by: stack scanning
 8  phantomjs + 0x1bf9dbc
    rip = 0x0000000001ff9dbd   rsp = 0x00007f05fe602b50
    Found by: stack scanning
 9  phantomjs + 0x1adff57
    rip = 0x0000000001edff58   rsp = 0x00007f05fe602b70
    Found by: stack scanning
10  phantomjs + 0x73d99b
    rip = 0x0000000000b3d99c   rsp = 0x00007f05fe602b88
    Found by: stack scanning
11  librt-2.12.so + 0x3e45
    rip = 0x0000003c95e03e46   rsp = 0x00007f05fe602ba0
    Found by: stack scanning
12  phantomjs + 0x1adff57
    rip = 0x0000000001edff58   rsp = 0x00007f05fe602bc0
    Found by: stack scanning
13  phantomjs + 0x73d99b
    rip = 0x0000000000b3d99c   rsp = 0x00007f05fe602bd8
    Found by: stack scanning
14  phantomjs + 0x1c3b489
    rip = 0x000000000203b48a   rsp = 0x00007f05fe602c00
    Found by: stack scanning
15  phantomjs + 0x1c39e2c
    rip = 0x0000000002039e2d   rsp = 0x00007f05fe602c40
    Found by: stack scanning
16  phantomjs + 0x1bf3fb0
    rip = 0x0000000001ff3fb1   rsp = 0x00007f05fe602c90
    Found by: stack scanning
17  phantomjs + 0x1c1a9e8
    rip = 0x000000000201a9e9   rsp = 0x00007f05fe602cc0
    Found by: stack scanning
18  libstdc++.so.6.0.13 + 0xbd0bc
    rip = 0x0000003c9b6bd0bd   rsp = 0x00007f05fe602cd0
    Found by: stack scanning
19  phantomjs + 0x1bf3c43
    rip = 0x0000000001ff3c44   rsp = 0x00007f05fe602cf0
    Found by: stack scanning
20  phantomjs + 0x1a277d9
    rip = 0x0000000001e277da   rsp = 0x00007f05fe602d30
    Found by: stack scanning
21  phantomjs + 0x1a2ce4a
    rip = 0x0000000001e2ce4b   rsp = 0x00007f05fe602d70
    Found by: stack scanning
22  libpthread-2.12.so + 0x7a50
    rip = 0x0000003c94e07a51   rsp = 0x00007f05fe602de0
    Found by: stack scanning

Thread 8
 0  libpthread-2.12.so + 0xb63c
    rbx = 0x00007f05fc9454b0   r12 = 0x00007f05fc9454b0
    r13 = 0x0000000004df02c0   r14 = 0x00000000ffffffff
    r15 = 0x0000000000000003   rip = 0x0000003c94e0b63c
    rsp = 0x00007f05e1ba9d30   rbp = 0x00007f05fc945488
    Found by: given as instruction pointer in context
 1  phantomjs + 0x137519a
    rip = 0x000000000177519b   rsp = 0x00007f05e1ba9d60
    rbp = 0x00007f05fc945488
    Found by: stack scanning
 2  phantomjs + 0x424dab
    rip = 0x0000000000824dac   rsp = 0x00007f05e1ba9da0
    rbp = 0x00007f05fc945488
    Found by: stack scanning
 3  phantomjs + 0x13752a0
    rip = 0x00000000017752a1   rsp = 0x00007f05e1ba9dd0
    rbp = 0x00007f05fc945488
    Found by: stack scanning
 4  libpthread-2.12.so + 0x7a50
    rip = 0x0000003c94e07a51   rsp = 0x00007f05e1ba9de0
    rbp = 0x00007f05fc945488
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x02b62fff  phantomjs  ???  (main)
0x3c94600000 - 0x3c9461ffff  ld-2.12.so  ???
0x3c94a00000 - 0x3c94d8efff  libc-2.12.so  ???
0x3c94e00000 - 0x3c95018fff  libpthread-2.12.so  ???
0x3c95200000 - 0x3c95403fff  libdl-2.12.so  ???
0x3c95600000 - 0x3c95883fff  libm-2.12.so  ???
0x3c95a00000 - 0x3c95c15fff  libz.so.1.2.3  ???
0x3c95e00000 - 0x3c96007fff  librt-2.12.so  ???
0x3c96200000 - 0x3c96417fff  libresolv-2.12.so  ???
0x3c96600000 - 0x3c9681dfff  libselinux.so.1  ???
0x3c98200000 - 0x3c98427fff  libexpat.so.1.5.2  ???
0x3c98a00000 - 0x3c98c9cfff  libfreetype.so.6.3.22  ???
0x3c98e00000 - 0x3c99015fff  libgcc_s-4.4.7-20120601.so.1  ???
0x3c99200000 - 0x3c99425fff  libpng12.so.0.49.0  ???
0x3c99600000 - 0x3c99835fff  libfontconfig.so.1.4.4  ???
0x3c9b600000 - 0x3c9b8f0fff  libstdc++.so.6.0.13  ???
0x3c9ba00000 - 0x3c9bddefff  libcrypto.so.1.0.1e  ???
0x3c9be00000 - 0x3c9c002fff  libkeyutils.so.1.3  ???
0x3c9c200000 - 0x3c9c403fff  libcom_err.so.2.1  ???
0x3c9c600000 - 0x3c9c82afff  libk5crypto.so.3.1  ???
0x3c9ca00000 - 0x3c9cce6fff  libkrb5.so.3.3  ???
0x3c9ce00000 - 0x3c9d00afff  libkrb5support.so.0.1  ???
0x3c9d200000 - 0x3c9d443fff  libgssapi_krb5.so.2.2  ???
0x3c9e200000 - 0x3c9e46bfff  libssl.so.1.0.1e  ???
0x3ca2a00000 - 0x3ca2d4ffff  libicuuc.so.42.1  ???
0x3ca3600000 - 0x3ca3994fff  libicui18n.so.42.1  ???
0x3ca8600000 - 0x3ca883ffff  libjpeg.so.62.0.0  ???
0x3caba00000 - 0x3cacb4afff  libicudata.so.42.1  ???
0x7f05d6b7a000 - 0x7f05d6c29fff  DejaVuSans.ttf  ???
0x7f05e3b04000 - 0x7f05e3b5cfff  DejaVuSerif.ttf  ???
0x7f05fcdb8000 - 0x7f05fcfbdfff  libnss_dns-2.12.so  ???
0x7f05fcfbe000 - 0x7f05fd1cbfff  libnss_files-2.12.so  ???
0x7f060571b000 - 0x7f0605736fff  mime.cache  ???
0x7f0606138000 - 0x7f060613afff  87f5e051180a7a75f16eb6fe7dbd3749-le64.cache-3  ???
0x7f060613b000 - 0x7f0606143fff  b79f3aaa7d385a141ab53ec885cc22a8-le64.cache-3  ???
0x7f0606144000 - 0x7f0606146fff  0b1bcc92b4d25cc154d77dafe3bceaa0-le64.cache-3  ???
0x7f0606147000 - 0x7f0606148fff  2e1514a9fdd499050989183bb65136db-le64.cache-3  ???
0x7f0606149000 - 0x7f060614bfff  5c755b2f27115486aa6359c84dd3cbda-le64.cache-3  ???
0x7f060614c000 - 0x7f060614cfff  b966c23d19cce9e9a98d55765cf2a0c7-le64.cache-3  ???
0x7f060614d000 - 0x7f060614efff  3f821257dd33660ba7bbb45c32deb84c-le64.cache-3  ???
0x7f060614f000 - 0x7f0606150fff  830f035fa84a65ce80e050178dbb630d-le64.cache-3  ???
0x7f0606151000 - 0x7f0606151fff  81a173283b451552b599cfaafd6236bd-le64.cache-3  ???
0x7f0606152000 - 0x7f0606152fff  ac68f755438cc3dc5a526084839fc7ca-le64.cache-3  ???
0x7f0606153000 - 0x7f0606153fff  6cfc7d49b27ba7d3eb71ab86e04def2c-le64.cache-3  ???
0x7f0606154000 - 0x7f0606154fff  6fcb01a03a016cc71057b587cdea6709-le64.cache-3  ???
0x7f0606155000 - 0x7f0606155fff  46d51d90fe9d963f6f4186edb936a931-le64.cache-3  ???
0x7f0606156000 - 0x7f0606156fff  b887eea8f1b96e1d899b44ed6681fc27-le64.cache-3  ???
0x7f0606157000 - 0x7f0606157fff  860639f272b8b4b3094f9e399e41bccd-le64.cache-3  ???
0x7f0606158000 - 0x7f0606158fff  211368abcb0ff835c229ff05c9ec01dc-le64.cache-3  ???
0x7f0606159000 - 0x7f0606159fff  c46020d7221988a13df853d2b46304fc-le64.cache-3  ???
0x7f060615a000 - 0x7f060615afff  df893b4576ad6107f9397134092c4059-le64.cache-3  ???
0x7f060615b000 - 0x7f060615bfff  900402270e15d763a6e008bb2d4c7686-le64.cache-3  ???
0x7f060615c000 - 0x7f060615cfff  47f48679023f44a4d1e44699a69464f6-le64.cache-3  ???
0x7f060615d000 - 0x7f060615dfff  2881ed3fd21ca306ddad6f9b0dd3189f-le64.cache-3  ???
0x7f060615e000 - 0x7f060615efff  3c3fb04d32a5211b073874b125d29701-le64.cache-3  ???
0x7f060615f000 - 0x7f060615ffff  e61abf8156cc476151baa07d67337cae-le64.cache-3  ???
0x7f0606160000 - 0x7f0606163fff  b67b32625a2bb51b023d3814a918f351-le64.cache-3  ???
0x7f0606164000 - 0x7f0606164fff  991510d2da7f7b2bf8468002aae90060-le64.cache-3  ???
0x7f0606165000 - 0x7f0606166fff  d3379abda271c4acd2ad0c01f565d0b0-le64.cache-3  ???
0x7f0606167000 - 0x7f0606167fff  b4d0b56f766d89640448751fcd18ec1e-le64.cache-3  ???
0x7f0606168000 - 0x7f0606169fff  99a1ce9f8b6a0434aadb01d3779b0780-le64.cache-3  ???
0x7f060616a000 - 0x7f060616bfff  f9d379b867d7c69c85310a4f24e5228f-le64.cache-3  ???
0x7f060616c000 - 0x7f0606175fff  12b26b760a24f8b4feb03ad48a333a72-le64.cache-3  ???
0x7f0606176000 - 0x7f0606187fff  74717c444f6fd72454fa9c9c0ee01ca7-le64.cache-3  ???
0x7f0606188000 - 0x7f060618efff  928306c3ad40271d946e41014a49fc28-le64.cache-3  ???
0x7f060618f000 - 0x7f0606195fff  fa1582dab13e7e8e44e5a9424d309f0e-le64.cache-3  ???
0x7f0646ca5000 - 0x7f064cb35fff  locale-archive  ???
0x7f064cb48000 - 0x7f064cb4cfff  18db0204b1f108dd01663673626fcd3d-le64.cache-3  ???
0x7f064cb4d000 - 0x7f064cb4dfff  1248881498ac025e45c3042f6afe9284-le64.cache-3  ???
0x7f064cb4e000 - 0x7f064cb4efff  d04038e664b0033ae700a78c51f179d3-le64.cache-3  ???
0x7f064cb4f000 - 0x7f064cb51fff  beeeeb3dfe132a8a0633a017c99ce0c0-le64.cache-3  ???
0x7ffef1f29000 - 0x7ffef1f29fff  linux-gate.so  ???
1. Which operating system are you using?
   Linux version 2.6.32-573.8.1.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Tue Nov 10 18:01:38 UTC 2015
2. Did you use binary PhantomJS or did you compile it from source?
   phantomjs binary
3. Please provide any additional information below.
   I am trying to render approx 0.2 Million records using phantomjs

**Comment by praveen-kaple** [comment]
I am facing same issue with phantomjs version **'2.1.1'**.
**Output:**
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Aborted (core dumped)

**Comment by praveen-kaple** [comment]
I am not getting any error with phantomjs version **'1.9.8'**.
PDF is getting created for 0.2 million records.

**Comment by praveen-kaple** [comment]
Do we have any solution for crashing issue on 2.0.1-development and 2.1.1 phantomjs version?

**Comment by Vitallium** [comment]
Do you have a small sample to reproduce your crash?

**Comment by praveen-kaple** [comment]
Given below is the command that I used to create the PDF file:
/home/phantomjs --ignore-ssl-errors=true --ssl-certificates-path=/home/site.cert --ssl-protocol=TLSv1 /home/rasterize.js **URL** /home/data.pdf A4 57880 23440

Also, attached here is the json response from the server which I am trying to convert into PDF using phantomjs.
[data.zip](https://github.com/ariya/phantomjs/files/381489/data.zip)

**Comment by praveen-kaple** [comment]
Do we have any solution for crashing issue on 2.0.1-development and 2.1.1 phantomjs version?
Please let me know if any other information is needed to troubleshoot this issue.

**Comment by praveen-kaple** [comment]
Any further update? any clu to address this ?

**Comment by developermedia** [comment]
Any solution?
