### ISSUE TITLE
Minified js in ghostdriver undistributable in Debian-based distros

### ISSUE THREAD

**Issue by pv** [ariya/phantomjs#14424]
I'd like to point out that Ubuntu & Debian do not distribute the src/ghostdriver/third_party/webdriver-atoms files needed for using phantomjs as a selenium backend. This is due to their policy of requiring having unminified source for JS in source packages (minifying during build is ok).
See http://metadata.ftp-master.debian.org/changelogs//main/p/phantomjs/phantomjs_2.1.1+dfsg-2_changelog:  "\* Disabled Ghostdriver due to pre-built source-less Selenium blobs."

The fix is to replace the webdriver-atoms in the repository with the corresponding unminified JS, which probably is available from the selenium project.

(NB. I don't have anything to do with the packaging, just noticed that the ubuntu phantomjs distro packages are unusable with selenium.)

**Comment by onlyjob** [comment]
@stale bot wishes this issue were never reported... :(
