### ISSUE TITLE
PhantomJS lacks EcmaScript 6 data types support

### ISSUE THREAD

**Issue by thecoderok** [ariya/phantomjs#14429]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
Version: 2.1.1

Webkit used by phantomjs does not support EcmaScript 6 data types, like Map and Set etc 
But those data types are supported by Chrome, IE, Firefox.

When is the next version planned to be in pair with what Chrome supports?

**Comment by chrismbeckett** [comment]
+1 - Wondering about eventual support for Web Components and Polymer.

**Comment by Vitallium** [comment]
Next major version will support each aspect and feature from ES2015.

**Comment by Vitallium** [comment]
Closing this. Track the progress of ES2015 here https://github.com/ariya/phantomjs/issues/14506
