### ISSUE TITLE
page.renderBuffer can't work

### ISSUE THREAD

**Issue by tinhour** [ariya/phantomjs#14420]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
phantomjs  version:2.1.1 
2. What steps will reproduce the problem?
when I use this demo :http://phantomjs.org/api/webpage/method/render-buffer.html
I can't get anything when I open browser with localhost:8001,It's always waiting response.
and I change the response data to text,and content-type:"text/html",it will return the text.
and then I change to using page.render("img.png"),It alos can return the scrrencapture as the image "img.png "
3. Which operating system are you using?
win7 64bit
4. Did you use binary PhantomJS or did you compile it from source?
no I download form the official site.
5. Please provide any additional information below.
myCodes:
`var server = require('webserver').create();
var listening = server.listen(8001, function(request, response) {
	var url = "https://***.***.com/login/";
	var  format = 'png', quality = -1;
	console.log("requestURL:",request.url)
	var page = require('webpage').create();

	page.viewportSize = {
		width: 800,
		height: 600
	};

	page.open(url, function start(status) {
		    if (status !== 'success') {
        console.log('FAIL to load the address');
    } else {
        console.log("open url:",url ,"status:",status);
		// page.render('loginpage.png');
		var buffer = page.renderBuffer(format, quality);
		response.statusCode = 200;
		response.headers = {
			"Cache": "no-cache",
			//"Content-Type":"text/html"
			"Content-Type": "image/" + format
		};
		page.close();
		// Pass the Buffer to 'write' to send the Uint8ClampedArray to the client
		response.write(buffer);
		response.close();
    }
	});
});`

**Comment by Vitallium** [comment]
`renderBuffer` available in development build only.

**Comment by tinhour** [comment]
how can i download development version @Vitallium

**Comment by Vitallium** [comment]
I offer development builds for Windows only. If you need development version for Linux or macOS you have to build it from sources.

**Comment by tinhour** [comment]
thanks,can u publish on http://phantomjs.org/download.html this page. or give me an link to download. @Vitallium

**Comment by tinhour** [comment]
@Vitallium I need window development version

**Comment by cfa532** [comment]
I met exactly the same problem. My build is 2.1.1, Win10, 64bit, WebStorm2.1. I am trying to scrape a image url directly. The thread of execution seems broken after running renderBuffer. I will give the development version a trial.

**Comment by tinhour** [comment]
@cfa532 see my github [https://github.com/tinhour/screencapture-sendmail/blob/master/index.js] project ,I using a webcamera to do this .
it's can used as renderBuffer.

**Comment by cfa532** [comment]
Thanx, tinhour. I have to run it under Phantomjs. webcam package won't do. I used child_process to start a http.get to download the image. It is an ugly solution but it works. I will wait for the renderBuffer to be released.
