### ISSUE TITLE
both injectJs and includeJs are not working....keep getting "can't find variable: $"

### ISSUE THREAD

**Issue by carinlynchin** [ariya/phantomjs#14430]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
           2.1.1
2. What steps will reproduce the problem?
   1.   use either includeJs with URL 
   2.  or use injectJs with local min jquery file
      3.
3. Which operating system are you using?
   OSX
4. Did you use binary PhantomJS or did you compile it from source?
     installed into /usr/local/share
5. Please provide any additional information below.

**Comment by Vitallium** [comment]
Could you please compose a sample to reproduce the problem? I know that both methods work fine.

**Comment by carinlynchin** [comment]
I found out what it was... even though the html file had jquery link on it... i had to manually do it with includeJs. Thanks though
