### ISSUE TITLE
PhantomJS support to skip load images or other resource in html

### ISSUE THREAD

**Issue by rfyiamcool** [ariya/phantomjs#14437]
Hello,
       Do PhantomJS support to skip load images or other resource in html ?   phantomjs only support  html , js  resource ?    
I have not found a way to solve this problem, so create new issue in github .  thanks you !

**Comment by ariya** [comment]
You can use `onResourceRequested`, please check the documentation for details. For an example, please read https://ariya.io/2013/06/capturing-web-page-without-stylesheets.
