### ISSUE TITLE
phantomjs dependency not found on Ubuntu

### ISSUE THREAD

**Issue by kirubasankars** [ariya/phantomjs#14433]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
**phantomjs-2.1.1-linux-i686**
2. What steps will reproduce the problem?

https://gist.github.com/julionc/7476620

3. Which operating system are you using?
**Ubuntu 16.04 LTS**
4. Did you use binary PhantomJS or did you compile it from source?
**Binary**
5. Please provide any additional information below.
_**phantomjs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory**_

**Comment by Vitallium** [comment]
gist is missing.

Could you also post the output of `ldd phantomjs` ?

**Comment by kirubasankars** [comment]
Thanks gist url update.

$ ldd phantomjs
ldd: ./phantomjs: No such file or directory

**Comment by Vitallium** [comment]
Thanks.

You must execute `ldd` on the executable from the archive.

**Comment by kirubasankars** [comment]
Sorry,

$ ldd phantomjs 
	linux-gate.so.1 =>  (0xf77d9000)
	libz.so.1 => not found
	libfontconfig.so.1 => not found
	libfreetype.so.6 => not found
	libdl.so.2 => /lib32/libdl.so.2 (0xf77b2000)
	librt.so.1 => /lib32/librt.so.1 (0xf77a9000)
	libpthread.so.0 => /lib32/libpthread.so.0 (0xf778b000)
	libstdc++.so.6 => not found
	libm.so.6 => /lib32/libm.so.6 (0xf7736000)
	libgcc_s.so.1 => not found
	libc.so.6 => /lib32/libc.so.6 (0xf7583000)
	/lib/ld-linux.so.2 (0x565f8000)

**Comment by Vitallium** [comment]
I think you're trying to run x86 ELF binary on x64 system. I suggest you to try phantomjs-2.1.1-linux-x86_64.tar.bz2

**Comment by kirubasankars** [comment]
what a stupid i am. thank you for pointing out.

**Comment by eromoe** [comment]
In ubuntu 14.04 x64 docker get this error too.
```
root@f57e4f37f0aa:/data/phantomjs-2.1.1-linux-x86_64/bin# ls
phantomjs

root@f57e4f37f0aa:/data/phantomjs-2.1.1-linux-x86_64/bin# phantomjs
phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

root@f57e4f37f0aa:/data/phantomjs-2.1.1-linux-x86_64/bin# uname -a
Linux f57e4f37f0aa 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by eromoe** [comment]
solved by
`
apt-get install libfontconfig
`

**Comment by lfurzewaddock** [comment]
Thanks @eromoe - fixed the same problem with MS Windows 10 (WSL) running Ubuntu 16.04
