### ISSUE TITLE
Phantom update: [31merror[39m:/phantomjs-prebuilt/lib/phantom/bin/phantomjs] executable. Please make sure phantomjs is installed correctly.

### ISSUE THREAD

**Issue by azattelman** [ariya/phantomjs#14431]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
version 2.0.10

Something has happened to this version. It used to work fine but as soon as I reinstalled our node packages on AWS we started getting the error below. I have tried different versions of phantom with different versions of node but nothing has solved this issue.

2. What steps will reproduce the problem?
  1. Downloading a fresh version of phantom 2.0.10 this week and trying to execute phantomJS on AWS server

3. Which operating system are you using?
64bit Amazon Linux 2015.09 v2.0.4 running Node.js + nginx

4. Did you use binary PhantomJS or did you compile it from source?
Using binary PhantomJS

5. Please provide any additional information below.
Phantomjs works fine locally on a mac with same version + codebase using express. PhantomJS only started to crash on AWS with the below error due to a recent package update this week:

 [31merror[39m: Could not spawn [/tmp/deployment/application/node_modules/phantom/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs] executable. Please make sure phantomjs is installed correctly.
[31merror[39m:  Error: spawn /tmp/deployment/application/node_modules/phantom/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)

Please, please help! :)

**Comment by ariya** [comment]
Something is wrong with your npm-based install. Bring up the issue with https://www.npmjs.com/package/phantomjs-prebuilt project please.
