### ISSUE TITLE
Problem with building current sources on Windows

### ISSUE THREAD

**Issue by mschlebusch** [ariya/phantomjs#14432]
The build of qtwebkit fails on Windows.
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   Current Sources
2. What steps will reproduce the problem?
   Follow instructions on http://phantomjs.org/build.html
3. Which operating system are you using?
   Windows 7
4. Did you use binary PhantomJS or did you compile it from source?
   Compile it from current source
5. Please provide any additional information below.

Output of the build process:

   Creating library ....\bin\ImageDiff.lib and object ....\bin\ImageDiff.exp
Qt5Gui.lib(png.obj) : error LNK2019: unresolved external symbol _inflateReset referenced in function _png_reset_zstream
Qt5Gui.lib(pngrutil.obj) : error LNK2001: unresolved external symbol _inflateReset
Qt5Gui.lib(png.obj) : error LNK2019: unresolved external symbol _adler32 referenced in function _png_compare_ICC_profile_with_sRGB
Qt5Gui.lib(png.obj) : error LNK2019: unresolved external symbol _crc32 referenced in function _png_calculate_crc
Qt5Gui.lib(pngread.obj) : error LNK2019: unresolved external symbol _inflateEnd referenced in function _png_read_destroy
Qt5Gui.lib(pngwrite.obj) : error LNK2019: unresolved external symbol _deflateEnd referenced in function _png_write_destroy
Qt5Gui.lib(pngwutil.obj) : error LNK2001: unresolved external symbol _deflateEnd
Qt5Gui.lib(pngwutil.obj) : error LNK2019: unresolved external symbol _deflate referenced in function _png_compress_IDAT
Qt5Gui.lib(pngwutil.obj) : error LNK2019: unresolved external symbol _deflateReset referenced in function _png_deflate_claim
Qt5Gui.lib(pngwutil.obj) : error LNK2019: unresolved external symbol _deflateInit2_ referenced in function _png_deflate_claim
Qt5Gui.lib(pngrutil.obj) : error LNK2019: unresolved external symbol _inflate referenced in function _png_inflate
Qt5Gui.lib(pngrutil.obj) : error LNK2019: unresolved external symbol _inflateInit_ referenced in function _png_inflate_claim
....\bin\ImageDiff.exe : fatal error LNK1120: 10 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\link.EXE"' : return code '0x460'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.

ERROR: Failed to build PhantomJS! Building Qt WebKit failed.

The same issue was already reported here:
https://groups.google.com/forum/#!topic/phantomjs/n8XnupRLQRE

**Comment by Vitallium** [comment]
Looks like zlib is missing.

**Comment by markusschlebusch** [comment]
Is it missing in any dependency of the sources or do I need to put it anywhere for the build process?

**Comment by markusschlebusch** [comment]
I've found zlib in the following folder as 3rdparty dependency: ..\src\qt\3rdparty\zlib
Threfore it is generally available for the build process.
