### ISSUE TITLE
When PhantomJS crashes, Fatal Windows exception, code 0xc00000050

### ISSUE THREAD

**Issue by prajavk** [ariya/phantomjs#14449]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. Install Sencha Cmd version 6.1.3.42 on Windows 7 (32bit and 64bit)
   2. run mvn clean package, to build sencha ExtJS6 version web application
   3. 
3. Which operating system are you using?
   Windows 7 64 bit
4. Did you use binary PhantomJS or did you compile it from source?
   No, we use PhantomJS.exe  from Sencha/cmd/6.1.3.42/bin/windows/phantomjs folder
5. Please provide any additional information below.
   PhantomJS executed as part of sencha cmd build, used to write sass content to PROD *.scss

**Comment by tamerhalim** [comment]
phantomjs version 1.9.8
Windows 7 64 bit
binary PhantomJS

**Comment by parky128** [comment]
Did you ever find a solution for this? I am seeing the same issue running on windows 10 64 bit, using phantomjs 2.1.1 with the latest version of phantom js launcher
