### ISSUE TITLE
please provide checksum files on Bitbucket

### ISSUE THREAD

**Issue by jakoch** [ariya/phantomjs#14440]
Hey!

Please provide the SHA256 checksums for your releases as files on Bitbucket. 
Additionally, please sign them.

This allows to automate download mirroring using Bitbucket as the primary trusted source.
(Given the the number of wild mirrors, because of Bitbucket it's already a bit late. Ref. #13953)
It also allows to build automated installers using downloads from mirrors, without the inconvenient need to grab [the checksums from your readme](http://phantomjs.org/download.html#checksums) and updating the checksums in the installers with every new release. 

In case Bitbucket builds the checksums for uploaded files automatically and exposes them via an API endpoint, please point me to it and include the link in the checksum section of your readme. 

Thank you in advance.
Best, Jens

**Comment by ariya** [comment]
If you have the checksum file handy, I'll be happy to place it right away on Bitbucket downloads.
As for the signing, please track it at #13019.

Thanks!
