### ISSUE TITLE
Print media is no longer activated when rendering to PDF

### ISSUE THREAD

**Issue by mafredri** [ariya/phantomjs#14441]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   
   `2.2.2-development` (6090f5457d2051ab374264efa18f655fa3e15e79)
2. What steps will reproduce the problem?
   1. Install PhantomJS (6090f5457d2051ab374264efa18f655fa3e15e79)
   2. Open a page that utilizes `@media print {}`-css
   3. Save to PDF with `page.render('out.pdf');`
3. Which operating system are you using?
   
   macOS 10.11.6
4. Did you use binary PhantomJS or did you compile it from source?
   
   Source
5. Please provide any additional information below.
   
   The `print`-media used to get applied prior to 7d7e5f345b646ef18d23138781ae94197335b342. Reverting the following two commits brings back the old behaviour:
   
   ``` console
   git revert bfccbd65f2855d38b9c8d826813315857b6379b0
   git revert 7d7e5f345b646ef18d23138781ae94197335b342
   ```
   
   I also reverted bfccbd65f2855d38b9c8d826813315857b6379b0 because it seemed to continue on some of the changes introduced in 7d7e5f345b646ef18d23138781ae94197335b342.

**Comment by zowers** [comment]
in issue #10623 people want the opposite, to always use media=screen

**Comment by mafredri** [comment]
I can see a reason for both, to be honest. If this had not been a breaking change in previous behavior, I probably wouldn't have reported it and relied on applying css classes for phantom "print emulation". Currently I have production systems relying on this behavior though :).

As exporting a webpage to PDF is usually done through a browsers print dialog, I think it makes sense to apply the print media by default. And I'm sure there are cases when you don't want it as well.

I haven't checked, but one concern about this change is e.g. how it affects pagination, etc.

**Comment by GendelfLugansk** [comment]
Any workaround for this? I need to use print media
