### ISSUE TITLE
Font rendering issue

### ISSUE THREAD

**Issue by perhanid** [ariya/phantomjs#14450]
1. Which version of PhantomJS are you using?
   2.1.1
2. Which operating system are you using?
   Windows Server 2012R2
3. Did you use binary PhantomJS or did you compile it from source?
   binary
4. Please provide any additional information below.
   Font rendering isn't working properly. It shows different results on browsers and phantomjs. We tried turning off ClearType and it was still different. Ideally we would like to produce the same results as chrome. Is it possible to configure the font antialiasing  mechanism that phantomjs is using?

![image](https://cloud.githubusercontent.com/assets/10029045/17393657/c3958138-5a2d-11e6-90b2-8269f3e20f9f.png)

HTML
[html.txt](https://github.com/ariya/phantomjs/files/400989/html.txt) [in text form]

phantomjs code
[phantomjs.txt](https://github.com/ariya/phantomjs/files/400990/phantomjs.txt) [in text form]

command
phantomjs C:\Users\user\Desktop\phantomjs.js

**Comment by Vitallium** [comment]
PhantomJS relies on Qt font antialiasing. I suspect this is not possible to get font rendering same as in Google Chrome.

**Comment by annulen** [comment]
Chrome uses DirectWrite on Windows (since 52 it's the only option, previously GDI could also be used). Qt can use it as one of font engines, if it is not disabled when Qt is compiled. If Qt actually uses DirectWrite and results are still different, it should be possible to eleminate difference by adjusting DirectWrite settings (change in Qt API wuld be required in worst case).

So it's probably feasible, but requires some groundwork

**Comment by annulen** [comment]
However, if you are looking for pixel perfect equality in generic case, it's not possible. There will be subtle-almost-invisible differences in canvas rendering, gradients and shadows (or not so subtle in case of bugs :)

**Comment by perhanid** [comment]
ok, thank you very much :)
I'll look further into it.

**Comment by perhanid** [comment]
Could you point us where these are located and where/how to change them? Or is there any guide available for that?

**Comment by annulen** [comment]
PhantomJS 2.1.1 is using Qt 5.5 which does not activate DirectWrite support in default build configuration. It will be fixed in the next version as a consequence of Qt update.

**Comment by perhanid** [comment]
After some testing, I found out that on fonts of 14px and above, fonts are rendering almost perfectly, and below 13 the difference is too great. 
Is there a way to know when the next update will come out? Hopefully this will be fixed by then.

Thank you for time and help :)
