### ISSUE TITLE
Compile phatomjs with only shared libraries

### ISSUE THREAD

**Issue by richardmat** [ariya/phantomjs#14469]
Our corporate legal dept. requires that we can only use a compiled version of phantomjs with **shared libraries, not static libraries**. In compiling phantomjs using the standard documentation provided we note that the qt and other libraries appear to be statically linked.

Is there a document that will show us how to correctly compile a version of phantomjs with shared libraries only?

3. Which operating system are you using? Linux (RH/6)

4. Did you use binary PhantomJS or did you compile it from source? Compiled from source.

**Comment by ariya** [comment]
It's not easy to do this with the current version (2.1). It may be easier in the upcoming version.
In the mean time, take a look at the examples of what Debian is doing: https://packages.debian.org/sid/web/phantomjs.
