### ISSUE TITLE
Usage of phantomjs with Reactjs?

### ISSUE THREAD

**Issue by jinxac** [ariya/phantomjs#14462]
I compiled my reactjs using webpack and got a bundle file bundles.js. My bundles.js contains a component that make API calls to get the data.

Now,I put this file in my html and pass the url to phantom.js to get static html data.

Now, I am witnessing something strange here, the ajax calls for APIS are not getting fired at all.

For example, I have a component called Home which is called when I request for url /home. My Home components makes an ajax request to backend(django-rest) to get some data. Now when I call home page in phantomjs this api call is not getting fired.

Am I missing something here?

**Comment by martinhearn** [comment]
Are you setting a timeout in PhantomJS to tell it to wait for a period of time so that the ajax calls can be fired?

```
page.open('http://www.example.com', function () {
     window.setTimeout(function () {
         console.log(page.content);
         phantom.exit();
     },2000);
});
```

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thanks!

**Comment by jinxac** [comment]
Let me give it a shot.
