### ISSUE TITLE
Printing header and footer

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#14461]
Previously, our modified version of QtWebKit implements the support for header and footer. This is now gone with the move to use system-installed QtWebKit (#14458).

We shall investigate the feasibility and the effort in implementing this feature for upstream QtWebKit ([annulen/webkit](https://github.com/annulen/webkit)).

**Comment by annulen** [comment]
I think it makes sense to walk through whole diff between PhantomJS fork and qt/qtwebkit@c1b8d4bf2a and find out what features need to be added to QtWebKit. This PR reduces diff significantly: https://github.com/Vitallium/qtwebkit/pull/14

**Comment by willemmulder** [comment]
Thanks for considering, headers and footers are a very significant feature for us! We use it in our document generation, and can't do without, really.

**Comment by tiborsaas** [comment]
+1 on this. A header and footer option that pushes content beneath and forces content to the next page is a dealbreaker if not implemented correctly.

**Comment by annulen** [comment]
@tiborsaas Help would be welcome!

**Comment by robinfhu** [comment]
+1 Please keep the header/footer feature in PhantomJS.  It is extremely useful!

**Comment by scottbell** [comment]
This is also an important feature for us! Please keep header and footer options.

**Comment by iqmeta** [comment]
with dropping support on headers, are there any ideas/example code to have something similar on the PDF output? like html5 footer/sections, etc?

but of course the contents event was just excelent, also for custom logic.
