### ISSUE TITLE
Fail to load subdomain.localhost

### ISSUE THREAD

**Issue by kevinresol** [ariya/phantomjs#14468]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

    2.1.1
2. What steps will reproduce the problem?
  1. serve something at localhost
  2. `page.open('http://subdomain.localhost')`
  3. `status` in the callback will be `'fail'`
3. Which operating system are you using?

  Mac OSX 10.11.6
4. Did you use binary PhantomJS or did you compile it from source?

  Binary (from homebrew)
5. Please provide any additional information below.

**Comment by ariya** [comment]
Can you load http://subdomain.localhost from your browser?

**Comment by kevinresol** [comment]
Yes,  it's OK using chrome

**Comment by ariya** [comment]
How about Safari? How about curl?

**Comment by kevinresol** [comment]
oh well, only chrome loads

**Comment by ariya** [comment]
Seems that Chrome has the ability to treat localhost in a different way. In all cases, it's unlikely that we want to implement that since it's not a common feature among all other browsers.
