### ISSUE TITLE
FormData.getAll support 

### ISSUE THREAD

**Issue by MartijnR** [ariya/phantomjs#14464]
Is FormData.getAll support on the roadmap?

e.g. 

``` js
var fd = new FormData();
fd.append('a', 'b');
fd.getAll('a'); // now causes exception 'fd.getAll('a')' is a cyclic structure \n phantomjs://repl-input:1 in global code
// it should return ['b'].
```

**Comment by alexbryukhanova** [comment]
Just curious if there's been any news on this? Very useful for testing!

**Comment by Vitallium** [comment]
This feature will be available in the next coming release 2.5.

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thanks!

**Comment by k3n** [comment]
Where would one find the 2.5 binary? I don't see it released and I don't see a branch nor a tag for it.

**Comment by octachrome** [comment]
https://bitbucket.org/ariya/phantomjs/downloads/
