### ISSUE TITLE
The ICU library support cannot be enabled. 

### ISSUE THREAD

**Issue by xiaocaiyidie** [ariya/phantomjs#14473]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1.python build.py
  2.
  3.

3. Which operating system are you using?
  centos6.5
4. Did you use binary PhantomJS or did you compile it from source?
 git clone git://github.com/ariya/phantomjs.git

5. Please provide any additional information below.

You have already accepted the terms of the Open Source license.

<srcbase> = /root/phantomjs/src/qt/qtbase 
<outbase> = /root/phantomjs/src/qt/qtbase 
Creating qmake...
.Done.
Running configuration tests...
The ICU library support cannot be enabled.
 Turn on verbose messaging (-v) to /root/phantomjs/src/qt/qtbase/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /root/phantomjs/src/qt/qtbase/configure to continue.

ERROR: Failed to build PhantomJS! Configuration of Qt Base failed.

**Comment by ariya** [comment]
Please do not file an issue with an incredibly long subject.

The problem is solvable by following the suggestion in the error message: install/build ICU library.

**Comment by hs06** [comment]
... e.g. on a recent debian / ubuntu / raspbian system you can install libicu with.
$ sudo apt-get install libicu-dev icu-devtools libicu52

for SLES use YUM or alike. YMMV.
HTH
Hendrik
