### ISSUE TITLE
Why won't callback for google charts work no matter where i put it

### ISSUE THREAD

**Issue by carinlynchin** [ariya/phantomjs#14470]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   1.9.0
2. What steps will reproduce the problem?
   1. just trying to open the page
      2.
      3.
3. Which operating system are you using?
   ubuntu (server)
4. Did you use binary PhantomJS or did you compile it from source?
   just did sudo apt-get
5. Please provide any additional information below.
   No matter whether I use setOnLoadCallback  or put the callback property in the load arguments, it will not call the function in that callback. I have put console.log messages everywhere in order to narrow it down and it just doesn't get into the callback fn.

window.setupDealershipReport = function() {
    console.debug(JSON.stringify(google));
    logFunctionCall('stuff here');

```
google.charts.load                  ('current', {packages: ['corechart','gauge']});
google.charts.setOnLoadCallback     (callbackMethod);
```

};

**Comment by JohnDRoach** [comment]
@carinlynchin , did you get any resolution on this?  I have been running into the same problem using a node.js library called 'phantom-html-to-pdf' that uses phantomjs in the background.  To get around it I have been using a setTimeout to call the callbackMethod after 5 seconds after which I hope the Google Charts libraries have loaded.  This seems to work, but I'm sure will fail eventually.

**Comment by carinlynchin** [comment]
As far as I remember, nothing ever worked so we abandoned using phantom js. Sorry
