### ISSUE TITLE
PhantomJS bootstrap taking ~1-2 seconds

### ISSUE THREAD

**Issue by ikoichi** [ariya/phantomjs#14486]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
phantomjs 1.9.2

2. What steps will reproduce the problem?
  1. phantomjs js rasterize like processing
  2.
  3.

3. Which operating system are you using?
Windows 7

4. Did you use binary PhantomJS or did you compile it from source?
Compiled from source

5. Please provide any additional information below.

I am using phantomjs to create PDF files. I only use local resources (js, html, css) so no resources are retrieved from Internet.
I noticed that it takes around 2 seconds to complete the execution.
Do you know if there is a way to reduce this time?
I already tried using --proxy-type=none but I did not notice any improvements.
Thanks

**Comment by eltonjude** [comment]
Does the load time get any better if you use the `--disk-cache=true` CLI option?

http://phantomjs.org/api/command-line.html
`
--disk-cache=[true|false] enables disk cache (at desktop services cache storage location, default is false). Also accepted: [yes|no].
--disk-cache-path specifies the location for the disk cache.
--max-disk-cache-size=size limits the size of disk cache (in KB).
`

**Comment by ikoichi** [comment]
Hi @eltonjude thanks for your reply.
Unfortunately the `--disk-cache` option did not provide any visible effects on phantomjs bootstrap time.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
