### ISSUE TITLE
[Docs] Command line docs not up-to-date with v.2.1.1

### ISSUE THREAD

**Issue by corywestropp** [ariya/phantomjs#14480]
The options specified in [config.cpp](https://github.com/ariya/phantomjs/blob/2.1/src/config.cpp) do not match those in the [phantom docs](http://phantomjs.org/api/command-line.html). Namely:

- disk-cache-path
- local-url-access
- offline-storage-path
- offline-storage-quota
- script-language
- ssl-protocol (out of date)
- ssl-client-certificate-file
- ssl-client-key-file
- ssl-client-key-passphrase
- ssl-ciphers
- webdriver-logfile
- webdriver-loglevel

**Comment by Vitallium** [comment]
Fixed.
