### ISSUE TITLE
phantomjs javascript fails when using variable as json key

### ISSUE THREAD

**Issue by DanPatten** [ariya/phantomjs#14484]
1. Which version of PhantomJS are you using? Tested on 2.0 and 2.1 (latest)
2. What steps will reproduce the problem?
   Add the following javascript to a page for phantom js to load:

```
var key = "anything";   
var json = {   
    [key]: "key attribute"  
};
```

The above is valid javascript for defining a JSON key using a javascript variable. (See: http://stackoverflow.com/questions/882727/is-there-a-way-that-use-var-to-create-json-objects-with-a-key) 

PhantomJS does not support the brackets around [key], but it is valid javascript in modern browsers. My temporary fix was to remove the brackets [] and then phantomjs loaded the page as valid javascript.
1. Which operating system are you using? Windows 10
2. Did you use binary PhantomJS or did you compile it from source? Binary
3. Please provide any additional information below.

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thanks!
