### ISSUE TITLE
php exec() execute phantomjs, and page.render() return false;

### ISSUE THREAD

**Issue by zuojj** [ariya/phantomjs#14485]
**phantomjs: 2.1.1
Red Hat Enterprise Linux Server release 6.6 (Santiago)
PHP 5.3.3**

## Problem
```
$ phantomjs /workspace/js/screenshot.js
```
Execute above script ,the result is right, can create a image;

**But**:  PHP exec()
```php
<?php  
    $command = "phantomjs /workspace/js/screenshot.js"; 

    $response = exec($command, $ouput, $return_var);  
    
    print_r($return_var);  // print  0;
?>
```
screenshot.js
```
var webpage = require('webpage'),
    page = webpage.create();

page.open('http://m.baidu.com', function(status) {
    if('success' !== status) {
        console.log('Open Fail');
    }else {
        console.log('Open success');
        window.setTimeout(function () {
            var rendered = page.render('xxxx.jpg');
            console.log(rendered);
            phantom.exit();
        }, 2000);
    }
});
```
The result is wrong, rendered always return false;

**Comment by lcoder** [comment]
解决没，我的nodejs page.render( '/tmp/123.pdf' ) 都返回return false，蛋疼

**Comment by zuojj** [comment]
我的已解决，是因为执行名时的身份权限问题。

**Comment by lcoder** [comment]
我也找到原因了，检查了下render失败的页面，发现是因为页面里面有js，并且进行了insertBefore操作，然后render总是返回false，把操作的js代码删除，就可以render成功了。具体是不是因为有dom操作就失败，也没测试，感觉不太可能。因为我的案例有百度统计代码，追查原因，是s.parentNode.insertBefore这句代码的问题，删掉这句render就成功了。
