### ISSUE TITLE
WebPage thinking PhantomJS is loading as Safari 5, Forge User-Agent Header? 

### ISSUE THREAD

**Issue by randyamiel** [ariya/phantomjs#14487]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. Load a page that thinks PhantomJS is running as Safari 5
      2.
      3.
3. Which operating system are you using?
   Win7x64
4. Did you use binary PhantomJS or did you compile it from source?
   Bin
5. Please provide any additional information below.

Is there any way of tricking a page into thinking you are using a later version of Safari or Webkit? Further, is it in the timeline to update the WebKit engine or is this now closed source?

**Comment by Vitallium** [comment]
You can change the user-agent to mimic another browser.

**Comment by randyamiel** [comment]
@Vitallium isnt that just forging the user-agent error which still doesnt mean the JS would be compatable. I'll give it a try and see what happens. 

@randyamiel I don't think this works the same way as say injecting the IE emulate meta tag like below:
`<meta http-equiv="X-UA-Compatible" content="IE=8">`

**Comment by randyamiel** [comment]
@Vitallium Also, I tried using @TrifleJS but the page just renders blank, which is a port of phantomJS built using the V8 engine with .net to emulateIE but I guess thats not 100% ported yet.

**Comment by randyamiel** [comment]
Ill try:
```
var webPage = require('webpage');
var page = webPage.create();
page.settings.userAgent = "Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.57 Safari/537.36";
```

@ariya I saw in the documentation that **page.settings** may not be persistant after page.open? What if you are logging in then making a subsequent calls, or maybe I'm misunderstanding and this means the _page.settings_ cannot be changed _after page.open_?

> Note: The settings apply only during the initial call to the page.open function. Subsequent modification of the settings object will not have any impact.
