### ISSUE TITLE
Not able access one url from phantomjs .giving connection closed

### ISSUE THREAD

**Issue by satapathy2** [ariya/phantomjs#14488]
I tried to open a url  and then I tried to click on of the hyperlink on the page.then I am getting connectionclosed error but when I tried htmlunitdriver then I did not get this issue.can anyone plz help me on this.i tried putting all the command line argument but no use.plz suggest.

**Comment by Vitallium** [comment]
Please post your output with debug option enabled. Run phantomjs with `--debug=yes`
