### ISSUE TITLE
Usage of Phantom JS in production phase

### ISSUE THREAD

**Issue by jt4000** [ariya/phantomjs#14495]
**1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.**
PhantomJS 2.1.1

**2. What steps will reproduce the problem?_**
I have added phantomJSdriver in my asp.net mvc project and it installed an exe file in order to use phantom JS.

I have used the code "Install-Package PhantomJS" for package manager console.

I have some questions:

*Will phantom JS with exe file will be working in production phase and in the webhotel?

*When I use phantom JS, it displayed a firewall and I wonder if it gonna be the same result in production phase in the web hotel?

**_3. Which operating system are you using?_**
Windows 8.1

**_4. Did you use binary PhantomJS or did you compile it from source?_**
I used the code from the dll file

5. Please provide any additional information below.
![data3](https://cloud.githubusercontent.com/assets/14993569/17848865/27d935f0-6856-11e6-88e7-b6d53c6764a6.png)

**Comment by Vitallium** [comment]
Yes, it will be if you have enabled Windows Firewall there.

**Comment by Vitallium** [comment]
No response. Closed.
