### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by aplicacionamedida** [ariya/phantomjs#14491]
Hi,
I am trying to build the latest version of PhantomJS.

I am following the exact instructions in the build page:
http://phantomjs.org/build.html

I could build successfully phantomJS on linux Mint.

But I have problems building on windows. My operating system is Windows 8.1
I installed ActivePerl, Ruby and Git.

I have installed visual studio 2012.

From the Visual Studio 2012 Command Tool, I did:
`set PATH=%CD%\src\qt\3rdparty\gnuwin32\bin;%PATH%`

This is my enviroment variable PATH:
`C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\gnuwin32\bin;C:\Per
l64\site\bin;C:\Perl64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files
(x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32
;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\
;C:\Program Files (x86)\Acer\abFiles\;C:\Program Files\Intel\Intel(R) Management
 Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine C
omponents\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C
:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Go\bin;
C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX
\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Gi
t\cmd;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Pr
ogram Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsof
t SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\
Ruby23-x64\bin;C:\Tcl_x86\bin;C:\TclDevKit\bin;C:\Tcl\bin;C:\Program Files (x86)
\Google\Chrome\Application;C:\Program Files (x86)\phantomjs-2.1.1-windows\bin;C:
\Python27;C:\Python27\Scripts;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1
A\Bin;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin;C:\MinGW\bin;C:
\MinGW\MSYS\1.0\local\bin;C:\MinGW\MSYS\1.0\bin;C:\Perl64\site\bin;C:\Perl64\bin
;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C
:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\Sys
tem32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Ac
er\abFiles\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\
Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program F
iles\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Inte
l\Intel(R) Management Engine Components\IPT;C:\Go\bin;C:\Windows\system32\config
\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Mi
crosoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x8
6)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL
Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\
Program Files\Microsoft SQL Server\120\Tools\Binn\`

From the Visual Studio 2012 Command Tool, I did:
`python build.py`

I get this error:
`fatal error C1083: it's not possible to open 'cstddef': No such file or directory`

This is the output:

```
Building PhantomJS from source takes a very long time, anywhere from 30 minutes
to several hours (depending on the machine configuration). It is recommended to
use the premade binary packages on supported operating systems.

For details, please go the the web site: http://phantomjs.org/download.html.

Do you want to continue (Y/n)? Y
Executing in C:\Users\Usuario\Desktop\phantomjs\phantomjs: git submodule init
      1 [main] sh 3724 C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - in
ternal error reading the windows environment - too many environment variables?
   8205 [main] sh 3724 cygwin_exception::open_stackdumpfile: Dumping stack trace
 to sh.exe.stackdump
Executing in C:\Users\Usuario\Desktop\phantomjs\phantomjs: git submodule update
--init
      0 [main] sh 3084 C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - in
ternal error reading the windows environment - too many environment variables?
    566 [main] sh 3084 cygwin_exception::open_stackdumpfile: Dumping stack trace
 to sh.exe.stackdump
configuring Qt Base, please wait...
Executing in C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\qtbase: C:\User
s\Usuario\Desktop\phantomjs\phantomjs\src\qt\qtbase\configure.bat -static -opens
ource -confirm-license -prefix C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\
qt\qtbase -qt-zlib -qt-libpng -qt-libjpeg -qt-pcre -nomake examples -nomake tool
s -nomake tests -no-qml-debug -no-dbus -no-opengl -no-audio-backend -D QT_NO_GRA
PHICSVIEW -D QT_NO_GRAPHICSEFFECT -D QT_NO_STYLESHEET -D QT_NO_STYLE_CDE -D QT_N
O_STYLE_CLEANLOOKS -D QT_NO_STYLE_MOTIF -D QT_NO_STYLE_PLASTIQUE -D QT_NO_PRINTP
REVIEWDIALOG -mp -static-runtime -no-cetest -no-angle -icu -openssl -openssl-lin
ked -I C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\libicu\inclu
de -I C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\libxml\includ
e -I C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\openssl\includ
e -I C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\zlib\include -
L C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\libicu\lib -L C:\
Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\libxml\lib -L C:\Users
\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\openssl\lib -L C:\Users\Usu
ario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\zlib\lib -release
Please wait while bootstrapping configure ...
<srcbase> = C:/Users/Usuario/Desktop/phantomjs/phantomjs/src/qt/qtbase
<outbase> = C:/Users/Usuario/Desktop/phantomjs/phantomjs/src/qt/qtbase
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/animation/ { qab
stractanimation.h (1), qabstractanimation_p.h (1), qanimationgroup.h (1), qanima
tiongroup_p.h (1), qparallelanimationgroup.h (1), qparallelanimationgroup_p.h (1
), qpauseanimation.h (1), qpropertyanimation.h (1), qpropertyanimation_p.h (1),
qsequentialanimationgroup.h (1), qsequentialanimationgroup_p.h (1), qvariantanim
ation.h (1), qvariantanimation_p.h (1) }
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/arch/ { qatomic_
armv5.h (1), qatomic_armv6.h (1), qatomic_armv7.h (1), qatomic_bootstrap.h (1),
qatomic_cxx11.h (1), qatomic_gcc.h (1), qatomic_ia64.h (1), qatomic_mips.h (1),
qatomic_msvc.h (1), qatomic_unix.h (1), qatomic_x86.h (1) }
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/codecs/ { cp949c
odetbl_p.h (1), qbig5codec_p.h (1), qeucjpcodec_p.h (1), qeuckrcodec_p.h (1), qg
b18030codec_p.h (1), qiconvcodec_p.h (1), qicucodec_p.h (1), qisciicodec_p.h (1)
, qjiscodec_p.h (1), qjpunicode_p.h (1), qlatincodec_p.h (1), qsimplecodec_p.h (
1), qsjiscodec_p.h (1), qtextcodec.h (1), qtextcodec_p.h (1), qtsciicodec_p.h (1
), qutfcodec_p.h (1), qwindowscodec_p.h (1) }
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/global/ { qcompi
lerdetection.h (1), qconfig-dist.h (1), qconfig-large.h (1), qconfig-medium.h (1
), qconfig-minimal.h (1), qconfig-nacl.h (1), qconfig-small.h (1), qendian.h (1)
, qflags.h (1), qglobal.h (1), qglobalstatic.h (1), qhooks_p.h (1), qisenum.h (1
), qlibraryinfo.h (1), qlogging.h (1), qnamespace.h (1), qnumeric.h (1), qnumeri
c_p.h (1), qprocessordetection.h (1), qsysinfo.h (1), qsystemdetection.h (1), qt
_pch.h (1), qt_windows.h (1), qtypeinfo.h (1), qtypetraits.h (1) }
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/io/ { qabstractf
ileengine_p.h (1), qbuffer.h (1), qdatastream.h (1), qdatastream_p.h (1), qdatau
rl_p.h (1), qdebug.h (1), qdebug_p.h (1), qdir.h (1), qdir_p.h (1), qdiriterator
.h (1), qfile.h (1), qfile_p.h (1), qfiledevice.h (1), qfiledevice_p.h (1), qfil
einfo.h (1), qfileinfo_p.h (1), qfileselector.h (1), qfileselector_p.h (1), qfil
esystemengine_p.h (1), qfilesystementry_p.h (1), qfilesystemiterator_p.h (1), qf
ilesystemmetadata_p.h (1), qfilesystemwatcher.h (1), qfilesystemwatcher_fsevents
_p.h (1), qfilesystemwatcher_inotify_p.h (1), qfilesystemwatcher_kqueue_p.h (1),
 qfilesystemwatcher_p.h (1), qfilesystemwatcher_polling_p.h (1), qfilesystemwatc
her_win_p.h (1), qfsfileengine_iterator_p.h (1), qfsfileengine_p.h (1), qiodevic
e.h (1), qiodevice_p.h (1), qipaddress_p.h (1), qlockfile.h (1), qlockfile_p.h (
1), qloggingcategory.h (1), qloggingregistry_p.h (1), qnoncontiguousbytedevice_p
.h (1), qprocess.h (1), qprocess_p.h (1), qresource.h (1), qresource_iterator_p.
h (1), qresource_p.h (1), qsavefile.h (1), qsavefile_p.h (1), qsettings.h (1), q
settings_p.h (1), qstandardpaths.h (1), qstorageinfo.h (1), qstorageinfo_p.h (1)
, qtemporarydir.h (1), qtemporaryfile.h (1), qtemporaryfile_p.h (1), qtextstream
.h (1), qtextstream_p.h (1), qtldurl_p.h (1), qurl.h (1), qurl_p.h (1), qurlquer
y.h (1), qurltlds_p.h (1), qwindowspipereader_p.h (1), qwindowspipewriter_p.h (1
), qwinoverlappedionotifier_p.h (1) }
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/itemmodels/ { qa
bstractitemmodel.h (1), qabstractitemmodel_p.h (1), qabstractproxymodel.h (1), q
abstractproxymodel_p.h (1), qidentityproxymodel.h (1), qitemselectionmodel.h (1)
, qitemselectionmodel_p.h (1), qsortfilterproxymodel.h (1), qstringlistmodel.h (
1) }
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/json/ { qjson_p.
h (1), qjsonarray.h (1), qjsondocument.h (1), qjsonobject.h (1), qjsonparser_p.h
 (1), qjsonvalue.h (1), qjsonwriter_p.h (1) }
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/kernel/ { qabstr
acteventdispatcher.h (1), qabstracteventdispatcher_p.h (1), qabstractnativeevent
filter.h (1), qbasictimer.h (1), qcore_mac_p.h (1), qcore_unix_p.h (1), qcoreapp
lication.h (1), qcoreapplication_p.h (1), qcorecmdlineargs_p.h (1), qcoreevent.h
 (1), qcoreglobaldata_p.h (1), qcrashhandler_p.h (1), qeventdispatcher_blackberr
y_p.h (1), qeventdispatcher_glib_p.h (1), qeventdispatcher_unix_p.h (1), qeventd
ispatcher_win_p.h (1), qeventdispatcher_winrt_p.h (1), qeventloop.h (1), qeventl
oop_p.h (1), qfunctions_nacl.h (1), qfunctions_p.h (1), qfunctions_vxworks.h (1)
, qfunctions_wince.h (1), qfunctions_winrt.h (1), qjni_p.h (1), qjnihelpers_p.h
(1), qmath.h (1), qmetaobject.h (1), qmetaobject_moc_p.h (1), qmetaobject_p.h (1
), qmetaobjectbuilder_p.h (1), qmetatype.h (1), qmetatype_p.h (1), qmetatypeswit
cher_p.h (1), qmimedata.h (1), qobject.h (1), qobject_impl.h (1), qobject_p.h (1
), qobjectcleanuphandler.h (1), qobjectdefs.h (1), qobjectdefs_impl.h (1), qpoin
ter.h (1), qppsattribute_p.h (1), qppsattributeprivate_p.h (1), qppsobject_p.h (
1), qppsobjectprivate_p.h (1), qsharedmemory.h (1), qsharedmemory_p.h (1), qsign
almapper.h (1), qsocketnotifier.h (1), qsystemerror_p.h (1), qsystemsemaphore.h
(1), qsystemsemaphore_p.h (1), qtimer.h (1), qtimerinfo_unix_p.h (1), qtranslato
r.h (1), qtranslator_p.h (1), qvariant.h (1), qvariant_p.h (1), qwineventnotifie
r.h (1) }
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/mimetypes/ { qmi
medatabase.h (1), qmimedatabase_p.h (1), qmimeglobpattern_p.h (1), qmimemagicrul
e_p.h (1), qmimemagicrulematcher_p.h (1), qmimeprovider_p.h (1), qmimetype.h (1)
, qmimetype_p.h (1), qmimetypeparser_p.h (1) }
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/plugin/ { qelfpa
rser_p.h (1), qfactoryinterface.h (1), qfactoryloader_p.h (1), qlibrary.h (1), q
library_p.h (1), qmachparser_p.h (1), qplugin.h (1), qpluginloader.h (1), qsyste
mlibrary_p.h (1), quuid.h (1) }
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/statemachine/ {
qabstractstate.h (1), qabstractstate_p.h (1), qabstracttransition.h (1), qabstra
cttransition_p.h (1), qeventtransition.h (1), qeventtransition_p.h (1), qfinalst
ate.h (1), qhistorystate.h (1), qhistorystate_p.h (1), qsignaleventgenerator_p.h
 (1), qsignaltransition.h (1), qsignaltransition_p.h (1), qstate.h (1), qstate_p
.h (1), qstatemachine.h (1), qstatemachine_p.h (1) }
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/thread/ { qatomi
c.h (1), qbasicatomic.h (1), qexception.h (1), qfuture.h (1), qfutureinterface.h
 (1), qfutureinterface_p.h (1), qfuturesynchronizer.h (1), qfuturewatcher.h (1),
 qfuturewatcher_p.h (1), qgenericatomic.h (1), qmutex.h (1), qmutex_p.h (1), qmu
texpool_p.h (1), qorderedmutexlocker_p.h (1), qreadwritelock.h (1), qreadwritelo
ck_p.h (1), qresultstore.h (1), qrunnable.h (1), qsemaphore.h (1), qthread.h (1)
, qthread_p.h (1), qthreadpool.h (1), qthreadpool_p.h (1), qthreadstorage.h (1),
 qwaitcondition.h (1) }
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/tools/ { qalgori
thms.h (1), qarraydata.h (1), qarraydataops.h (1), qarraydatapointer.h (1), qbit
array.h (1), qbytearray.h (1), qbytearraylist.h (1), qbytearraymatcher.h (1), qb
ytedata_p.h (1), qcache.h (1), qchar.h (1), qcollator.h (1), qcollator_p.h (1),
qcommandlineoption.h (1), qcommandlineparser.h (1), qcontainerfwd.h (1), qcontig
uouscache.h (1), qcryptographichash.h (1), qdatetime.h (1), qdatetime_p.h (1), q
datetimeparser_p.h (1), qeasingcurve.h (1), qelapsedtimer.h (1), qfreelist_p.h (
1), qharfbuzz_p.h (1), qhash.h (1), qiterator.h (1), qline.h (1), qlinkedlist.h
(1), qlist.h (1), qlocale.h (1), qlocale_blackberry.h (1), qlocale_data_p.h (1),
 qlocale_p.h (1), qlocale_tools_p.h (1), qmap.h (1), qmargins.h (1), qmessageaut
henticationcode.h (1), qpair.h (1), qpodlist_p.h (1), qpoint.h (1), qqueue.h (1)
, qrect.h (1), qrefcount.h (1), qregexp.h (1), qregularexpression.h (1), qringbu
ffer_p.h (1), qscopedpointer.h (1), qscopedpointer_p.h (1), qscopedvaluerollback
.h (1), qset.h (1), qshareddata.h (1), qsharedpointer.h (1), qsharedpointer_impl
.h (1), qsimd_p.h (1), qsize.h (1), qstack.h (1), qstring.h (1), qstringalgorith
ms_p.h (1), qstringbuilder.h (1), qstringiterator_p.h (1), qstringlist.h (1), qs
tringmatcher.h (1), qtextboundaryfinder.h (1), qtimeline.h (1), qtimezone.h (1),
 qtimezoneprivate_data_p.h (1), qtimezoneprivate_p.h (1), qtools_p.h (1), qunico
detables_p.h (1), qunicodetools_p.h (1), qvarlengtharray.h (1), qvector.h (1), q
versionnumber_p.h (1) }
QtCore: created fwd-include header(s) for <srcbase>/src/corelib/xml/ { qxmlstrea
m.h (1), qxmlstream_p.h (1), qxmlutils_p.h (1) }

Utilidad de mantenimiento de programas de Microsoft (R) versión 12.00.21005.1
(C) Microsoft Corporation. Reservados todos los derechos.

        cl -c -Yc -nologo -Zc:wchar_t -W3 -GR -EHsc -w34100 -w34189   -DUNICODE
-DQT_NO_CODECS -DQT_NO_TEXTCODEC -DQT_NO_UNICODETABLES -DQT_LITE_COMPONENT -DQT_
NO_COMPRESS -DQT_NO_THREAD -DQT_NO_QOBJECT -DQT_NO_GEOM_VARIANT -D_CRT_SECURE_NO
_DEPRECATE -DQT_BOOTSTRAPPED -DQT_BUILD_CONFIGURE -I"..\..\include" -I"..\..\inc
lude\QtCore" -I"..\..\include\QtCore\5.5.1" -I"..\..\include\QtCore\5.5.1\QtCore
" -I"C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\qtbase\tools\shared" -I
"C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\qtbase\mkspecs\win32-msvc20
08" -Fpconfigure_pch.pch -Foconfigure_pch.obj -TP C:\Users\Usuario\Desktop\phant
omjs\phantomjs\src\qt\qtbase\tools\configure\configure_pch.h
configure_pch.h
c:\users\usuario\desktop\phantomjs\phantomjs\src\qt\qtbase\include\qtcore\../../
src/corelib/global/qglobal.h(39) : fatal error C1083: No se puede abrir el archi
vo incluir: 'cstddef': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\bin\cl.EXE"' : código devuelto '0x2'
Stop.

ERROR: Failed to build PhantomJS! Configuration of Qt Base failed.
```

**Comment by Vitallium** [comment]
You have two problems:

- MSV2012 is not supported. Minimal supported version is 2015.
- I see there is an error `fatal error - in
ternal error reading the windows environment - too many environment variables?`. This error is not related to PhantomJS build process. I sugeest you to upgrade your GIT installation.

**Comment by aplicacionamedida** [comment]
Hi,
many thanks for your answer. To build on windows is a little bit frustating.

I am using now the developer console of visual studio 2015.

"git --version" returns:
    
     git version  2.9.3.windows.1

I have this error now:
     ERROR: Failed to build PhantomJS! Configuration of Qt Base failed.

I can not solve the problem with git.

This is my path:

	C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\gnuwin32\bin;C:\Pro
	gram Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Micro
	soft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin;C:\Program Files (x86)\M
	icrosoft Visual Studio 14.0\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual
	 Studio 14.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\
	Tools;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Micro
	soft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\HTML Help Workshop;
	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools
	;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsof
	t SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Perl64\site\bin;C:\Perl64\bin;C:
	\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\P
	rogram Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System
	32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Acer\
	abFiles\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Pro
	gram Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program File
	s\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\I
	ntel(R) Management Engine Components\IPT;C:\Go\bin;C:\Windows\system32\config\sy
	stemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Micro
	soft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\
	Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Ser
	ver\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Pro
	gram Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\TortoiseSVN\bin
	;C:\Ruby23-x64\bin;C:\Tcl_x86\bin;C:\TclDevKit\bin;C:\Tcl\bin;C:\Program Files (
	x86)\Google\Chrome\Application;C:\Python27;C:\Python27\Scripts;C:\Perl64\site\bi
	n;C:\Perl64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel
	\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows
	;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
	 Files (x86)\Acer\abFiles\;C:\Program Files\Intel\Intel(R) Management Engine Com
	ponents\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\D
	AL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program F
	iles (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Go\bin;C:\Windows\
	system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\P
	rogram Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Pr
	ogram Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files
	\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\Type
	Script\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Fil
	es\TortoiseSVN\bin

This is the log:

	C:\Users\Usuario\Desktop\phantomjs\phantomjs>python build.py
	----------------------------------------
				   WARNING
	----------------------------------------

	Building PhantomJS from source takes a very long time, anywhere from 30 minutes
	to several hours (depending on the machine configuration). It is recommended to
	use the premade binary packages on supported operating systems.

	For details, please go the the web site: http://phantomjs.org/download.html.

	Do you want to continue (Y/n)? Y
	Executing in C:\Users\Usuario\Desktop\phantomjs\phantomjs: git submodule init
		  0 [main] sh 4172 C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - in
	ternal error reading the windows environment - too many environment variables?
		532 [main] sh 4172 cygwin_exception::open_stackdumpfile: Dumping stack trace
	 to sh.exe.stackdump
	Executing in C:\Users\Usuario\Desktop\phantomjs\phantomjs: git submodule update
	--init
		  0 [main] sh 6096 C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - in
	ternal error reading the windows environment - too many environment variables?
		424 [main] sh 6096 cygwin_exception::open_stackdumpfile: Dumping stack trace
	 to sh.exe.stackdump
	configuring Qt Base, please wait...
	Executing in C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\qtbase: C:\User
	s\Usuario\Desktop\phantomjs\phantomjs\src\qt\qtbase\configure.bat -static -opens
	ource -confirm-license -prefix C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\
	qt\qtbase -qt-zlib -qt-libpng -qt-libjpeg -qt-pcre -nomake examples -nomake tool
	s -nomake tests -no-qml-debug -no-dbus -no-opengl -no-audio-backend -D QT_NO_GRA
	PHICSVIEW -D QT_NO_GRAPHICSEFFECT -D QT_NO_STYLESHEET -D QT_NO_STYLE_CDE -D QT_N
	O_STYLE_CLEANLOOKS -D QT_NO_STYLE_MOTIF -D QT_NO_STYLE_PLASTIQUE -D QT_NO_PRINTP
	REVIEWDIALOG -mp -static-runtime -no-cetest -no-angle -icu -openssl -openssl-lin
	ked -I C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\libicu\inclu
	de -I C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\libxml\includ
	e -I C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\openssl\includ
	e -I C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\zlib\include -
	L C:\Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\libicu\lib -L C:\
	Users\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\libxml\lib -L C:\Users
	\Usuario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\openssl\lib -L C:\Users\Usu
	ario\Desktop\phantomjs\phantomjs\src\qt\3rdparty\zlib\lib -release
	Please wait while bootstrapping configure ...
	<srcbase> = C:/Users/Usuario/Desktop/phantomjs/phantomjs/src/qt/qtbase
	<outbase> = C:/Users/Usuario/Desktop/phantomjs/phantomjs/src/qt/qtbase
	No suitable compiler found in PATH. Aborting.

	ERROR: Failed to build PhantomJS! Configuration of Qt Base failed.

**Comment by Vitallium** [comment]
Are you using MSYS GIT? Looks like your GIT can't handle the long PATH variable.
