### ISSUE TITLE
Generated PDF not rendering SVG gradients on OSX 

### ISSUE THREAD

**Issue by eltonjude** [ariya/phantomjs#14492]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. phantomjs rasterize.js http://www.w3schools.com/svg/svg_grad_linear.asp /var/tmp/w3c-gradients.pdf A4
      [w3c-gradients-fails.pdf](https://github.com/ariya/phantomjs/files/429284/w3c-gradients-fails.pdf)
   2. Open generated PDF on mac using default PDF viewer (Preview) or in Safari
   3. Renders fine if viewed using Chrome or Adobe Reader on MAC
3. Which operating system are you using?
   OSX 10.11.6
   Preview Version 8.1
4. Did you use binary PhantomJS or did you compile it from source?
   Used binary installed using npm
5. Please provide any additional information below.
   Another link for which it fails: http://jsfiddle.net/GEBjE/485
   [highcharts-gradient-fails.pdf](https://github.com/ariya/phantomjs/files/429282/highcharts-gradient-fails.pdf)

Works for http://jsfiddle.net/GEBjE/486
[highcharts-solid-works.pdf](https://github.com/ariya/phantomjs/files/429288/highcharts-solid-works.pdf)

If you Print to PDF using Chrome's Print menu, then that PDF renders fine in Preview.
[highcharts-gradient-from_chrome-works.pdf](https://github.com/ariya/phantomjs/files/429285/highcharts-gradient-from_chrome-works.pdf)

**Comment by yacine555** [comment]
I have the same issue with the Windows binary 2.1.1. Generated PDF does not show SVG Gradient  on Sarfari. The same PDF does show up SVG on Chrome. Also SVG without gradient do show properly. 

Finally, it seems that the Linux binary 2.1.1 does work. And it does work with version 1.9.7 of the Windows binary.
