### ISSUE TITLE
[feature request] Enable to set pdf title

### ISSUE THREAD

**Issue by lucaz16** [ariya/phantomjs#14494]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   v2.1.1
2. What steps will reproduce the problem?
   1. render as pdf
3. Which operating system are you using?
   OSX
4. Did you use binary PhantomJS or did you compile it from source?
   binary PhantomJS
5. Please provide any additional information below.
   Enable to set title/creator of generated pdf file.

**Comment by cloud-garbage** [comment]
in terms of design, the page.render() method already takes an options parameter as the third argument, ex (from the docs):

`page.render('google_home.jpeg', {format: 'jpeg', quality: '100'});`

I assume it's fine for different formats to accept different parameters? maybe something like:

`page.render('google_home.pdf', { format: 'pdf', title: 'Google Home', author: 'PhantomJS' });`

or maybe:

`page.render('google_home.pdf', { format: 'pdf', metadata: { title: 'Google Home', author: 'PhantomJS' }});`
