### ISSUE TITLE
Inconsistency of Content-Type header with empty bodied POST request across Chrome&Firefox vs PhantomJS

### ISSUE THREAD

**Issue by SilverGhostBS** [ariya/phantomjs#14497]
When using PhantomJS version 2.1.1 if you initiate a POST request without a body (I know it doesn't make sense, but I came across an app that was doing that), Chrome & Firefox will NOT set any 'Content-Type' header, as should be expected.

PhantomJS forces the Content Type header to "application/x-www-form-urlencoded", which I believe it should not do with an empty body.

The application in question responded by a 415 (Invalid Content-Type) to this request.

It happened both on Linux & Windows platform using the prebuilt binary.

I fixed the issue, and will link this to the Pull request in case the community thinks this would be worthy to fix.

PS: It will also requires a small fix in QT in order to work on empty POST request having a query string, but there was an equivalent problem there, that they "fixed" but not completely, that final OR should be removed:
https://codereview.qt-project.org/#/c/99686/2/src/network/access/qhttpnetworkrequest.cpp

**Comment by jimmythompson** [comment]
I've recently been doing some work using an API where you must POST with an empty body to subscribe to a channel, e.g. `POST /channel/<id>/subscribers`. Your access token IDs you, and you are subscribed.

Our tests work fine driving with Chrome and Firefox, but PhantomJS is forcing the content type to `application/x-www-form-urlencoded`, which returns an error from the API.

I'd love for this to be fixed. 😄
