### ISSUE TITLE
Extra Line Breaks in PDF Rendering

### ISSUE THREAD

**Issue by PhilCowart** [ariya/phantomjs#14502]
**1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.**
Using version 2.1.1

**2. What steps will reproduce the problem?**
Using PhantomJS to create PDFs of editable documents. Occasionally the rendering will appear to add extra line breaks in text blocks or shift text down. 

The issue only occurs with PhantomJS for linux. Have tried with OSx and same issues do not appear.

**3. Which operating system are you using?**
Ubuntu 14.04

**4. Did you use binary PhantomJS or did you compile it from source?**
Binary

**5. Please provide any additional information below.**

For my User Agent I am using 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.57 Safari/537.17';

The issue doesn't seem to appear if I export to PNG but I need PDF.

I have attached some example screen shots.

![screen shot 2016-08-23 at 9 46 31 am](https://cloud.githubusercontent.com/assets/2186798/17896756/5f3946b8-6917-11e6-9683-c4cfb0902cdc.png)

![screen shot 2016-08-23 at 9 48 46 am](https://cloud.githubusercontent.com/assets/2186798/17896760/62b53086-6917-11e6-884f-3ffa95f827b7.png)

![screen shot 2016-08-23 at 9 51 40 am](https://cloud.githubusercontent.com/assets/2186798/17896800/7b55abb6-6917-11e6-930a-a0aad47313d5.png)

![screen shot 2016-08-23 at 9 48 58 am](https://cloud.githubusercontent.com/assets/2186798/17896811/86c288a2-6917-11e6-800b-e6afe4c4db75.png)

**Comment by funkju** [comment]
I am having the same issue. 

This screenshot is a piece of a small document. Here is the relevant HTML snippet:

> <div class="altbox">
>   <div class="wrap">
>     <div style="border-color: #000; width: 300px; margin: 0px auto;">
>       <div class="header">Lorem Ipsum
>       </div>
>       <div class='body'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam varius risus arcu, quis feugiat nunc tincidunt sed. Nunc ipsum quam, ullamcorper at finibus pulvinar, blandit sit amet ex. Duis molestie laoreet libero sit amet eleifend. 
>       </div>
>     </div>
>   </div>
> </div>


![image](https://user-images.githubusercontent.com/1482389/35065544-24f7a5b6-fb93-11e7-9946-627b3eac1712.png)

I am on OSX. Am trying on Linux now.

**Comment by funkju** [comment]
I also tested this on the 2.5 beta on osx and the issue still persists.

This also seems to be the same issue from Aug 2013 in #15145
