### ISSUE TITLE
switch_to_alert() is not working

### ISSUE THREAD

**Issue by ssowmya27** [ariya/phantomjs#14508]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2. What steps will reproduce the problem?
   1. i am using phantomjs for selenium automation and am not able to handle alerts
   2. switch_to.alert.accept()  doesn't work
   3. I need help to automate for popup and alert
3. Which operating system are you using?
   Windows 7
4. Did you use binary PhantomJS or did you compile it from source?
5. Please provide any additional information below.

**Comment by michaelfward** [comment]
This should be posted in the Selenium forum, not here;

However, the reason for this issue is because PhantomJS' GhostDriver does not handle alerts (in fact, it's explicitly set to false).
