### ISSUE TITLE
Support ES6/ES2015 Features

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#14506]
ES2015 (also colloquially known as ES6) will be possible with the new effort towards version 2.5 (see #14458 for details).

When building PhantomJS with the latest QtWebKit, PhantomJS will get all the latest JavaScriptCore support for ES2015. See the blog post [ES6 Feature Complete](https://webkit.org/blog/6756/es6-feature-complete/) for more details.

At that time, all examples should be also modernized to use the latest ES2015 syntax.

**Comment by ariya** [comment]
(This is to consolidate every little, individual inquiry on ES6 request)

**Comment by nataljatamming** [comment]
Hi!
1) When approximately do you plan release PhantomJS version 2.5( with ES6 support)?
2) New PhantomJS version 2.5 will support 100% ES6?

Thanks in advance

**Comment by mgamsjager** [comment]
I also would like to know when this is going to happen.

**Comment by Vitallium** [comment]
Hi. Answering to your questions:

1) When we solve all issues listed here https://github.com/ariya/phantomjs/issues/14458
2) Yes. 2.5 will have full support for ES2015.

**Comment by jedwards1211** [comment]
`babel-polyfill` seems to be crashing PhantomJS for me...has anyone else seen that happen?

**Comment by Vitallium** [comment]
2.5 beta release now supports ES2015! Give it a try! 🙌

**Comment by killerbytes** [comment]
How do I install beta release?

**Comment by atesgoral** [comment]
After spending around 30 minutes looking around (GitHub, Bitbucket, existing documentation) and even looking at the commit history (on master and 2.1 branches), I still don't know where the 2.5 beta source code is. Where is the latest and greatest (even if unstable) codebase for PhantomJS (for those of us who want to try building it ourselves)?

**Comment by Vitallium** [comment]
@atesgoral current 2.5 release is in the `master` branch. Beta binaries are [here](https://bitbucket.org/ariya/phantomjs/downloads)

**Comment by atesgoral** [comment]
@Vitallium Thanks for the quick response.

Part of my confusion stems from a third-party project which is Docker image that wraps PhantomJS and all its dependencies: https://hub.docker.com/r/wernight/phantomjs/ So, maybe the issue I'm having has nothing with the original PhantomJS repo, but is something that's wrong with the way that image is built and tagged.

The "latest" tag of that Docker image is supposed to be building PhantomJS from the master branch (as evidenced by the [Dockerfile](https://hub.docker.com/r/wernight/phantomjs/~/dockerfile/)).
 
However, when I do a `docker run -it --rm wernight/phantomjs:latest phantomjs --version`, I get 2.1.1 reported back, and when I run it in REPL mode, I see that at least some ES6 features don't work (like `let` and string formatting with backticks). This is the reason I was led to doubt that the master branch had the 2.5 beta changes on it. I'll keep poking around...

**Comment by branpar** [comment]
Hi, is there a timeline for 2.5 release?

**Comment by branpar** [comment]
@Vitallium I downloaded the 2.5 beta Windows exe and attempted a simple js file not transpiled with just a single import statement and I got "SyntaxError: Unexpected keyword 'import'" error. Seems like it doesn't support es6 yet.

**Comment by Vitallium** [comment]
@branpar ES6 modules is not enabled currently.

**Comment by branpar** [comment]
@Vitallium thanks for the quick response! Do we know when it might be enabled again?

**Comment by jtheoof** [comment]
`import` modules resolution is not part of the ES2015 spec. If you use a bundler such as `webpack`, `systemjs` or `browserify` you should be able to use ES2015 code without the pain of resolving imports from phantomJS.

**Comment by branpar** [comment]
@jtheoof that's not actually true. If you read the [ECMAScript® 2015 Language Specification](http://www.ecma-international.org/ecma-262/6.0/#sec-imports) you'll see that `modules`, `import`, and `export `are all three in the spec.

I'm trying to avoid using a transpiler for this project because there are problems associated with using a transpiler when also using PhantomJS. And if native support is coming it isn't needed to transpile down to es5 anymore. 

Most modern browsers have a wide range of support for es6 naively [es6 Compatibility Table](https://kangax.github.io/compat-table/es6/) so really PhantomJS is lagging behind on this standard right now.

**Comment by jtheoof** [comment]
Mmm I disagree, the keywords are present but how they are resolved [is not](https://github.com/whatwg/loader/) in the spec.

>>>
Section 15.2 of the ES2015 specification describes the syntax for the new import and export declarations, but does not specify how modules are to be loaded. This repository consolidates work on the ECMAScript module loading semantics with the integration points of Web browsers, as well as Node.js.

**Comment by mAAdhaTTah** [comment]
@branpar You'll notice the compat table doesn't include ES6 modules. They are not shipped by any browser nor Node at this point, as there are still issues to work out, so I would be surprised and impressed if PhantomJS was the first.

**Comment by hisapy** [comment]
> babel-polyfill seems to be crashing PhantomJS for me...has anyone else seen that happen?
@jedwards1211 did you fix this?

**Comment by jedwards1211** [comment]
@hisapy I haven't tried with the latest PhantomJS recently...

**Comment by hisapy** [comment]
I tried the latest beta version yesterday and couldn't make it work with Webpack, babel-polyfill, React. I had the following errors:

```bash
SyntheticEvent.augmentClass is not a function. (In 'SyntheticEvent.augmentClass(SyntheticCompositionEvent, CompositionEventInterface)', 'SyntheticEvent.augmentClass' is undefined)
TypeError: __WEBPACK_IMPORTED_MODULE_6_react_dom___default.a.render is not a function. (In '__WEBPACK_IMPORTED_MODULE_6_react_dom___default.a.render(__WEBPACK_IMPORTED_MODULE_5_react___default.a.createElement(Application, null), document.getElementById('react-root'))', '__WEBPACK_IMPORTED_MODULE_6_react_dom___default.a.render' is undefined)
```

PhantomJS 2.1.1 is working fine with babel-polyfill but it doesn't support flexbox. Anyways I managed to implement a hack for it using postcss-loader and autoprefixer plugin

**Comment by repus** [comment]
try it

**Comment by shellscape** [comment]
Would someone with the project be able to release the 2.5 beta on npm under a `next` or `beta` tag? Tried the binary directly and ended up with `dyld: Library not loaded: /usr/local/opt/webp/lib/libwebp.6.dylib`.

**Comment by arokhmistrov** [comment]
@Vitallium Binaries of the latest beta version for windows (phantomjs-2.5.0-beta-windows.zip) does not follow naming conversion for executable path as in previous versions.
It's  now  
`phantomjs-2.5.0.beta-windows\bin\phantomjs.exe`
  instead of 
`phantomjs-2.5.0-beta-windows\bin\phantomjs.exe`

It breaks [phantomjs-maven-plugin](https://github.com/klieber/phantomjs-maven-plugin/), which uses this template `phantomjs-{version}-{classifier}/bin/phantomjs.exe` for the path.

For linux it's ok.

**Comment by Vitallium** [comment]
@arokhmistrov Whoops. Added to downloads! Thank you.

**Comment by Bard182** [comment]
Any plan on creating a ruby gem for the 2.5 beta? Super eager to experiment with it in a ruby library, but not having any luck getting the downloads working in our project. Thanks!

**Comment by arantius** [comment]
I'm on trusty:

    $ grep DISTRIB /etc/lsb-release
    DISTRIB_CODENAME=trusty
    DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=14.04

I downloaded `phantomjs-2.5.0-beta-linux-ubuntu-trusty-x86_64.tar.gz` and extracted it, I get:

    $ ./phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs 
    ./phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs)
    ./phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs)
    ./phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs)
    ./phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs)

Looks like, I think, it wants gcc 4.9 but only up to 4.8 is available.  I can't use PPAs, which seems to be the way the internet suggests getting gcc 4.9 on trusty.

**Comment by Vitallium** [comment]
@arantius yes, we follow Webkit plans to drop `old` compilers (like GCC 4.8 or MSVC2015). Modern WebKit requires compilers with C++11 and C++14 support (most of them).

**Comment by ashawley** [comment]
@Bard182 For Ruby gems of 2.5, try building the branch at colszowka/phantomjs-gem#97.

The gem needs testing on Windows, so it would be useful to have someone verify it works.

**Comment by ariya** [comment]
Seems that it is now viable with the updated community QtWebKit.
From now on, please track #15342. Thank you!
