### ISSUE TITLE
Error with latest angular2 rc app running with systemjs

### ISSUE THREAD

**Issue by sunshineo** [ariya/phantomjs#14515]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. Open http://systemjs.craigsmenu.com/ to verify that the site works. (It may take up to 15s to load)
   2. Try use PhantomJS to open the site.
   3. It does not render properly. See details below.
3. Which operating system are you using?
   Mac
4. Did you use binary PhantomJS or did you compile it from source?
   Binary
5. Please provide any additional information below.

The script I used is:

```
var page = require('webpage').create();
page.open('http://systemjs.craigsmenu.com/', function(status) {
    console.log("status is: " + status);
    if (status === "success") {
        console.log("success");
        setTimeout(function() {
            console.log("screenshot");
            page.render('screenshot.png');
            phantom.exit();

        }, 10000);
    }
    else {
        console.log("not success");
        phantom.exit();
    }
});
```

The command I ran is `phantomjs ./craigsmenu.js`
I do not get a proper snapshot.png and the console shows error:

```
MBP:nld-crawler-js gordon$ ./phantomjs/bin/phantomjs ./craigsmenu.js
status is: success
success
Error: eval@[native code]
        invoke@http://systemjs.craigsmenu.com/node_modules/zone.js/dist/zone.js:323:34
        run@http://systemjs.craigsmenu.com/node_modules/zone.js/dist/zone.js:216:50
        http://systemjs.craigsmenu.com/node_modules/zone.js/dist/zone.js:571:61
        invokeTask@http://systemjs.craigsmenu.com/node_modules/zone.js/dist/zone.js:356:43
        runTask@http://systemjs.craigsmenu.com/node_modules/zone.js/dist/zone.js:256:58
        drainMicroTaskQueue@http://systemjs.craigsmenu.com/node_modules/zone.js/dist/zone.js:474:43
        g@http://systemjs.craigsmenu.com/node_modules/core-js/client/shim.min.js:8:19360
        http://systemjs.craigsmenu.com/node_modules/core-js/client/shim.min.js:8:19482
        k@http://systemjs.craigsmenu.com/node_modules/core-js/client/shim.min.js:8:14322
        Evaluating http://systemjs.craigsmenu.com/app
        Error loading http://systemjs.craigsmenu.com/app

  http://systemjs.craigsmenu.com/:17
screenshot
MBP:nld-crawler-js gordon$
```

**Comment by katia-ua** [comment]
+1

**Comment by Vitallium** [comment]
I am afraid that Angular2 is not supported yet due to a modern JS (ES2015) features.

**Comment by sunshineo** [comment]
Thank you @Vitallium . Any plan to support it soon?

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thanks!

**Comment by sunshineo** [comment]
Where do I get 2.5 binary? http://phantomjs.org/

**Comment by Vitallium** [comment]
@sunshineo [here](https://bitbucket.org/ariya/phantomjs/downloads)

**Comment by sunshineo** [comment]
I cannot run it
```
MBP:phantom gordon$ ./bin/phantomjs ./craigsmenu.js
dyld: Library not loaded: /usr/local/opt/webp/lib/libwebp.6.dylib
  Referenced from: /Users/gordon/Downloads/phantom/./bin/phantomjs
  Reason: image not found
Abort trap: 6
MBP:phantom gordon
```

**Comment by Vitallium** [comment]
@sunshineo you must install webp libraries. For example, in Ubuntu: `sudo apt install webp`

**Comment by sunshineo** [comment]
@Vitallium I'm on Mac. I downloaded from https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html but cannot figure out how to install.

**Comment by Vitallium** [comment]
Just use HomeBrew to install it. This is the easiest way.

**Comment by sunshineo** [comment]
I did
```
brew install webp
```
It still complains
```
dyld: Library not loaded: /usr/local/opt/webp/lib/libwebp.6.dylib
```
Ironically, I have:
/usr/local/opt/webp/lib/libwebp.7.dylib
/usr/local/opt/webp/lib/libwebp.3.dylib

not libwebp.6.dylib .
