### ISSUE TITLE
502 Bad Gateway when i use phantom.setProxy

### ISSUE THREAD

**Issue by csimpi** [ariya/phantomjs#14518]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. Get a HTTP/HTTPS proxy from here https://incloak.com/proxy-list/?maxtime=2002&type=s#list
   2.  phantom.setProxy( proxy.ip, proxy.port, 'manual', '', '' );
   3. page.open(url, function(){ .....
3. Which operating system are you using?
   Same as Linux Debian and Windows 10
4. Did you use binary PhantomJS or did you compile it from source?
   I tried both
5. Please provide any additional information below.
   When i try to use phantom.setProxy( proxy.ip, proxy.port, 'manual', '', '' ); method i get a 502 Bad Gateway error (i save a screenshot to png). I tried with so many proxies, i got same error every time.
   ![screenshot](https://cloud.githubusercontent.com/assets/6192067/18104263/9a3cf01e-6efa-11e6-8135-7baefa23ac12.png)

I can't use command line option, i have to use setProxy method.

Thanks,
Peter

**Comment by Vitallium** [comment]
Are you sure that the problem **with** PhantomJS? I suggest you to try other browers.

**Comment by csimpi** [comment]
Other browser?  The PhantomJS is a browser! :)

I have some progression, i changed 'manual' to html in 
phantom.setProxy( proxy.ip, proxy.port, 'http', '', '' );

That way sometimes i can get the website what i want open, but frequently doesnt works.
If i delete setProxy line from my code, everything works fine.
