### ISSUE TITLE
Fatal windows exception, 0xc0000005

### ISSUE THREAD

**Issue by lfberge** [ariya/phantomjs#14511]
PhantomJS 2.1.1, Windows 7, binary PhantomJS

Cucumber 2.4.0, Capybara 2.8.0, Poltergeist 1.10.0

`Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.`

`An existing connection was forcibly closed by the remote host. (Errno::ECONNRESET)`

While running my cucumber scenarioes some steps randomly failes with the exception listed above. After the error most following scenarioes fails as well. After a reboot, everything seems fine for a couple of runs, before the error returns.

**Comment by xDEADC0DE** [comment]
Same issue today, on windows 7 and cygwin :

```
$ ./phantomjs.exe --version
2.1.1
Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault
```

I also get this message (without the "Segmentation fault" line) when I try to execute "phantom.exit();"
