### ISSUE TITLE
RightClick to Show Sourcecode

### ISSUE THREAD

**Issue by jt4000** [ariya/phantomjs#14519]
_1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`._
The latest version

_2. What steps will reproduce the problem?_
is it possibly to specify the mouse's location and then rightclick and select show source code using phantom JS?

_3. Which operating system are you using?_
Win 8.1

_4. Did you use binary PhantomJS or did you compile it from source?_
Using Nuget in C#

5. Please provide any additional information below.

**Comment by Vitallium** [comment]
No, it's not possible. Use `content` property to get the source code: http://phantomjs.org/api/webpage/property/content.html
