### ISSUE TITLE
Phantomjs is locking after corrupted image preview

### ISSUE THREAD

**Issue by gokhanege** [ariya/phantomjs#14517]
1. PhantomJS version is 2.1.1 64Bit
2. I have corrupted (exif corrupted) image. It is crashed after FTP upload but viewing from any browser or photo viever.
3. OS is Centos 6.8
4. I have download from directly download page.
5. I am load this image with PhantomJS but it is locking / crashing and using high CPU. And it caught my attention, updateLoadingProgress is staying, it is not completing.

I am uploaded this image on this message.

[exif-crash-image.zip](https://github.com/ariya/phantomjs/files/445503/exif-crash-image.zip)

**Comment by Vitallium** [comment]
Are trying to open this image directly with PhantomJS e.g. `page.open('..jpg'` ?
