### ISSUE TITLE
--version reports 2.1.1 when 2.1.12 is installed

### ISSUE THREAD

**Issue by ssteinerx** [ariya/phantomjs#14510]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
It says it's 2.1.1, but I just installed 2.1.12

2. What steps will reproduce the problem?
```
npm install phantomjs-prebuilt

> phantomjs-prebuilt@2.1.12 install irrelevant-path/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /var/folders/bw/w312ywz17pv4k41b9wk2l9z00000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing irrelevant-path/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/bw/w312ywz17pv4k41b9wk2l9z00000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1472304206043/phantomjs-2.1.1-macosx -> irrelevant-path/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at irrelevant-path/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
myproject@0.4.0 irrelevant-path
└─┬ phantomjs-prebuilt@2.1.12
         ├── es6-promise@3.2.1
        └── fs-extra@0.30.0

$ node_modules/.bin/phantomjs --version
2.1.1
```
3. Which operating system are you using?

OS X, 10.11.6

4. Did you use binary PhantomJS or did you compile it from source?

See above, `npm install phantomjs-prebuilt`

5. Please provide any additional information below.

I removed all other copies of phantomjs from my system before doing this.

**Comment by ariya** [comment]
You are confused because 2.1.12 is the version of https://www.npmjs.com/package/phantomjs-prebuilt (which is BTW not officially part of PhantomJS project).

**Comment by ssteinerx** [comment]
Is there an official npm package I should be using?  `phantomjs` module says it's been replaced by `phantomjs-prebuilt`?

**Comment by ariya** [comment]
PhantomJS is **not** a Node.js module.

That `phantomjs-prebuilt` package is a convenient installer (download and unpack the binary for you). Check https://github.com/Medium/phantomjs for more details /cc @nicks.
