### ISSUE TITLE
PhantomJS crashing

### ISSUE THREAD

**Issue by vivinRajagopalan** [ariya/phantomjs#14512]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.3
2. What steps will reproduce the problem?
   1.I am trying to launch phantom JS from Karma and when i try invoking it,  i get the following error.

ERROR
" 29 08 2016 12:25:31.495:ERROR [phantomjs.launcher]: Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
http://phantomjs.org/bug-reporting.html and file a bug report.

29 08 2016 12:25:31.641:ERROR [launcher]: PhantomJS crashed.

29 08 2016 12:25:31.652:INFO [launcher]: Trying to start PhantomJS again (1/2).
29 08 2016 12:26:31.653:WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
29 08 2016 12:26:31.671:INFO [launcher]: Trying to start PhantomJS again (2/2).
29 08 2016 12:27:31.675:WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
29 08 2016 12:27:31.693:ERROR [launcher]: PhantomJS failed 2 times (timeout). Giving up. "

  2.
  3.
1. Which operating system are you using? Windows 7.0 64

Please let me know how to resolve this ?

Regards,
Vivin

**Comment by AndrewJohnBenjamin** [comment]
Has there been any progress on this? I am seeing the exact same behavior on a Window 10 x64 machine. The failure is random and occurs probably 70% of the time. I have done some searching around and it seems a fair amount of others have this problem as well; would be great to get a diagnosis on this as I am yet to find one anywhere else.

**Comment by parky128** [comment]
I am also seeing this issue on a windows 10 64 bit machine. I have phantomjs 2.1.1 installed globally, using karma v.1.4.0 with phantomjs launcher.

**Comment by leizz** [comment]
I have been seeing this issue on Ubuntu 16.04, Redhat 7.3, Sles 12 SP2.  I have phantomjs 2.1.1 installed globally, and Karma v1.3.0. Mine was actually from the front-end testing of a project called Grafana.

**Comment by georgiosd** [comment]
Seems to be fixed in 2.5.0 beta for me

**Comment by parky128** [comment]
I agree with @georgiosd - the issue also seems to be fixed with 2.5.0 beta for me

**Comment by tsvetomir** [comment]
The crash _might be_ originating in the QT WebSocket handling code. Try setting the Karma [transports](https://karma-runner.github.io/1.0/config/configuration-file.html) setting to _polling_ to disable the communication through WebSockets:

```js
transports: ['polling']
```

**Comment by ZachShaw** [comment]
@tsvetomir 's solution of adding transports fixed this for me. Nothing I had attempted to fix this including editing .bashrc, removing, upgrading, globally installing PhantomJS.

I can finally run unit tests on my XPS using PhantomJS, thank you. Win10, 64bit.
