### ISSUE TITLE
Built on Ubuntu 14.04 with Source, but not working on another Machine.

### ISSUE THREAD

**Issue by nemojjh** [ariya/phantomjs#14513]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1.  Runtime, Shared Library error of LibICU 
3. Which operating system are you using?
   **\- Debian  7 & Ubuntu 14.04**
4. Did you use binary PhantomJS or did you compile it from source?
   - Compiled from source
5. Please provide any additional information below.
   - Compiled from source on Ubuntu 14.04 but not working on Debian 7. Because of Shared Object.

How can I build them as Static Library with Source?

Thank you :)

**Comment by Vitallium** [comment]
You need to build ICU as a static library. Version from you distro will not work.

**Comment by markusschlebusch** [comment]
Hi @Vitallium . How do I build on Linux (Ubuntu) with static libraries (especially ICU)? I've sources of August 2016 which contains a build.py.

**Comment by ariya** [comment]
@markusschlebusch Take a look at `deploy/docker-build.sh`. Thanks!
