### ISSUE TITLE
Can't capture 

### ISSUE THREAD

**Issue by kevinquillen** [ariya/phantomjs#14516]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. Try to capture "https://www.google.com/#q=music"
3. Which operating system are you using?

Ubuntu
1. Did you use binary PhantomJS or did you compile it from source?

Used the binary
1. Please provide any additional information below.

Why is it you can't capture certain URLs, for instance, ones like "https://www.google.com/#q=music" - the # is a problem. Is there a way to support this so it can be captured? I occasionally have a requirement to capture pages to PNG or PDF that contain AngularJS code, sometimes it works, sometimes it doesn't. The URLs often have a query string beginning with # like that above for Angular.

**Comment by gustavoisensee** [comment]
Hello Kevin, Can you solved you problem?
I'm having the same problem and I can't solve it yet.

**Comment by neciszhang** [comment]
@kevinquillen @gustavoisensee Can you solved your problem? I'm having the same problem.
