### ISSUE TITLE
PDF render: disable header / footer on first page

### ISSUE THREAD

**Issue by tiborsaas** [ariya/phantomjs#14522]
I've seen this page:
http://phantomjs.org/api/webpage/property/paper-size.html

However it's not clear if I can disable the header on the first page. I don't just want the content to be removed, I'd like to remove the whole white space it inserts, because the cover page design starts at zero pixels from the top.

**Comment by benjamineberle** [comment]
I don't think that's supported and you shouldn't do it anyway as header/footer support is being removed.
We already switched to a custom margin/header/footer system where we just use 100% of the page and do everything manually, i.e. absolute positioning of divs with white background at the top and buttom and page breaks are inserted by offsetting components to the next page via margin-top or spacer divs. It means ridiculous fiddling, but it works.

**Comment by junkmail767828** [comment]
@benjamineberle It would be a shame to remove the header/footer support. Sounds like a hassle to do it without. Any chance you'd know the reason?

**Comment by benjamineberle** [comment]
https://github.com/ariya/phantomjs/issues/14461
