### ISSUE TITLE
How to exit phantom if it hangs on page.open (with example)

### ISSUE THREAD

**Issue by leem32** [ariya/phantomjs#14529]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
version 2.1.1
2. What steps will reproduce the problem?

     ```javascript
      var system = require("system");
      var page;

      // user supplied url
      var myurl = system.args[1];
      // var myurl = 'https://waffles.ch/';

      page = require('webpage').create();

      // suppress errors from output
      page.onError = function(msg, trace) {};

      // 5 seconds
      page.settings.resourceTimeout = 5000;

      // page.settings.javascriptEnabled = false;

      page.open(myurl, function(status) {

          //hack for page.open not hooking into phantom.onError
          setTimeout(function() {
              if (status !== "success") {
                  console.log(myurl);
                  phantom.exit();
                  throw new Error("Unable to access network");
              } else {
                  var pageTitle = myurl.replace(/http.*\/\//g, "").replace("www.", "").split("/")[0];
                  var filePath = "img/" + pageTitle + '.jpg';
                  page.render(filePath, {format: 'jpeg', quality: '75'});
                  console.log(filePath);
                  phantom.exit();
              }

          }, 0);
      });
     ```

3. Which operating system are you using?
Windows 7 64bit

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.

Using the above code to take screenshots works fine for most webpages.
Running the script through the console or a web app with the url "https://waffles.ch/", however, causes it to hang infinitely on page.open (i believe). 

The reason for this I assume is because this URL contains some JS animation which doesn't stop running (an aeroplane flying across the screen), and it causes Phantom to lock up. Is this a known bug??

I'm quite sure JS causes the hang because if I switch it off with ```javascript page.settings.javascriptEnabled = false;``` then the screenshot for the page is rendered without any problems.

I can't realistically switch off javascript to take screenshots for obvious reasons (page.evaluate, redirects etc), so here's my 2 questions.

1.) Is there a way to render a screenshot for a webpage containing animation like `waffles.ch` without having to switch off javascript?? 

2.) If a webpage does hang, on `page.open` how can I exit phantom and possibly also return an errror??)

Any help/advice would be greatly appreciated. 

Other thing I've tried. (But still hangs for the above url.)

```javascript

var system = require("system");
var page;
// user supplied url
var myurl = system.args[1];

var page = require('webpage').create();
page.open(myurl, function (status) {
    try {
        if (status !== "success") {
            console.log("Unable to access network");
            phantom.exit();
        } else {
            //do some stuff with the DOM
            var pageTitle = myurl.replace(/http.*\/\//g, "").replace("www.", "").split("/")[0];
            var filePath = "img/" + pageTitle + '.jpg';
            page.render(filePath, {format: 'jpeg', quality: '75'});
            console.log(filePath);
            phantom.exit();
        }
    } catch (ex) {
        var fullMessage = "\nJAVASCRIPT EXCEPTION";
        fullMessage += "\nMESSAGE: " + ex.toString();
        for (var p in ex) {
            fullMessage += "\n" + p.toUpperCase() + ": " + ex[p];
        }
        console.log(fullMessage);
    }
});

```
// ******************************

Using `waitfor()` function.
https://github.com/ariya/phantomjs/blob/master/examples/waitfor.js

```javascript
var system = require("system");
var page;
// user supplied url
var myurl = system.args[1];

var page = require('webpage').create();

// suppress errors from output
page.onError = function(msg, trace) {
  console.log("Error occurred" + msg);
  phantom.exit();
};

// 5 seconds
page.settings.resourceTimeout = 5000;

page.open(myurl, function (status) {
    // Check for page load success
    if (status !== "success") {
        console.log("Unable to access network");
        phantom.exit();
    } else {
        waitFor(function() {
            // Check in the page if a specific element is now visible
            return page.evaluate(function() {

                return $("body").is(":visible");
            });
        }, function() {
           console.log("body is visible");
           phantom.exit();
        });
    }
});```

**Comment by Vitallium** [comment]
This is a known problem in PhantomJS 2.1.1. Unfortunately there is no workaround or a fix for that. This problem will be fixed only with the next upgrade of QtWebKit. You can track the progress here: https://github.com/ariya/phantomjs/issues/14458
