### ISSUE TITLE
Web Security Enabled doesn't prevent CORS POSTs

### ISSUE THREAD

**Issue by ffffranklin** [ariya/phantomjs#14524]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   
   ``` bash
   $ ./node_modules/.bin/phantomjs --version
   2.1.1
   ```
2. What steps will reproduce the problem?
   
   **Step 1**
   
   ``` bash
   $ git clone https://gist.github.com/c1debf96444088957aa4cd6ab33f52dc.git phantomjs-bug
   $ cd phantomjs-bug
   $ npm i
   $ npm start
   ```
   
   **Step 2**
   Observe output
3. Which operating system are you using?
   - OSX 10.11.5
4. Did you use binary PhantomJS or did you compile it from source?
   - prebuilt from npm
5. Please provide any additional information below.
   - Gist source
     - https://gist.github.com/ffffranklin/c1debf96444088957aa4cd6ab33f52dc
   - Resulting output
   
   ``` bash
   log(page1):  sending POST
   log(page1):  response [200]:  {
     "success": true
   }
   log(page2):  sending POST
   log(page2):  response [200]:  {
     "success": true
   }
   ```

**Comment by critterothecreed** [comment]
Hi ffffranklin,

I'm wondering about 2 things.

Firstly, if this note on the phantomjs api docs for the settings object has anything to do with your issue:
"Note: The settings apply only during the initial call to the page.open function. Subsequent modification of the settings object will not have any impact."

Secondly i wounder wether to allow or not CORS in your case is determined by the config parameter --local-to-remote-url-access (i would expect local would only include the "file://" type url but not 100% sure)

**Comment by critterothecreed** [comment]
Ohh, another thing occured to me. If i remember correctly the way closures work in javascript, your xhr response hanler may not be properly defined.

function handler() {
      console.log('response [' + xhr.status + ']: ', xhr.responseText);
    }

Isn't tje xhr object in this instance is sort of a clone made from the upper context at the time of the function definition (NOT execution) ? you should probably use the way the documentation does it:

console.log(this.responseText);

or better yet, make 2 distinct hadlers for error/success and log some static text inside as well to differentiate betweeen the 2.

**Comment by ffffranklin** [comment]
@critterothecreed, thanks for the feedback.   please note that the `page{n}.settings.webSecurityEnabled` is set before `page{n}.open` is called.  `--local-to-remote-url-access` seems to have no effect.  

In regards to the `xhr` instance.  I'm not entirely clear on the mixup around instantiation, but to be clear the page.html is served from mongoose webserver and executes at the `top` window context.  Each call to `http://localhost:8888` returns a separate unique response that is evaluated in the context of `page{n}`.  There should be no cross over.   

And referencing the `xhr` instance outside of scope is no different than referencing `this` in this usecase and is preferred in others as `this` can be volatile.  The implementation is fashioned after MDN's xhr usage examples https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest
