### ISSUE TITLE
PhantomJS + Karma + SystemJS

### ISSUE THREAD

**Issue by vlio20** [ariya/phantomjs#14526]
[PhantomJS 1.9.8 (Mac OS X 0.0.0)]:
I am trying to run some unit tests on my transpiled code (typescript).  
My issue that I am using Systemjs as my module loader, and in order to run the tests I am invoking each test by importing the spec file:   
`System.import('grid-footer.spec')`

I am using Karma to run the tests and jasmine to do the testing. 
System.import return a promise so it seems like Phantom stops working when this promise is resolved so there are no test that it runs.  

Here is the output I am getting:  
`PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0 secs / 0 secs)`  

When running the tests in Chrome every thing is working as expected and the tests are executed.

Any idea how can I solve this issue?

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
