### ISSUE TITLE
I can not get a transparent png format image

### ISSUE THREAD

**Issue by Einsy** [ariya/phantomjs#14532]
version 1.8
system : win8

2. What steps will reproduce the problem?

 I use this code:   page.render("test.png");  

How can I get a transparent  png image?

I If this feature is not available, can you provide it?

**Comment by Einsy** [comment]
At present, I  get  the picture with a white background

**Comment by Einsy** [comment]
is ok!

var 
  page2 = require('webpage').create();

page2.viewportSize = { width: 100, height : 100 };


page2.content = '<html><head><style>body {background-color: transparent} </style><body><div style="color: red; border: 10px solid red; -webkit-border-radius: 10px; font-size: 100px">0</div></body></html>';


page2.render('page2.png');

phantom.exit();

**Comment by Einsy** [comment]
var 

  page2 = require('webpage').create();


page2.viewportSize = { width: 100, height : 100 };


page2.content = '<html><head><style>body {background-color: transparent} </style><body><div style="color: red; border: 10px solid red; -webkit-border-radius: 10px; font-size: 100px">0</div></body></html>';


page2.render('page2.png');

phantom.exit();

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
