### ISSUE TITLE
page.includeJs does not return with errors

### ISSUE THREAD

**Issue by loretoparisi** [ariya/phantomjs#14537]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
`2.1.1`

2. What steps will reproduce the problem?
  1. Open `stackoverflow.com`

```javascript
url="http://stackoverflow.com"
page.open(url);
```

  2. use `page.includeJs`

```javascript
    var jsResource = "http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js";
    page.includeJs(jsResource, function(res) {
     ////....
})
```

At this point nothing will happens and the `page.includeJs` will not return.

3. Which operating system are you using?
`MacOS X El Capitan`

4. Did you use binary PhantomJS or did you compile it from source?
`binary`

5. Please provide any additional information below.
Is it possibile to add an `error` to the function, in the way that:

```javascript
page.injectJS(res, function(res, err) {
  if(err) {
     // abort...
  }
})
```

**Comment by Vitallium** [comment]
You can use [`onError`](http://phantomjs.org/api/webpage/handler/on-error.html) callback (or `onResourceError` to handle a network error) to catch the error.

**Comment by thoop** [comment]
@Vitallium please close this issue :)

@loretoparisi feel free to add more info/reopen issue if @Vitallium's suggestion doesn't work for you.

**Comment by loretoparisi** [comment]
@Vitallium sorry thank you guys. I will check the `onError` callback.
