### ISSUE TITLE
Tried everything phantomjs fails to run after successful build

### ISSUE THREAD

**Issue by northkode** [ariya/phantomjs#14539]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.2.0-development

This application failed to start because it could not find or load the Qt platform plugin "phantom"
in "".

We have tried everything.. we need this to work asap :(

**Comment by Vitallium** [comment]
How did you compile it? Current master is still doesn't work properly on Linux an macOS(?) We must land some tweaks.

**Comment by northkode** [comment]
Well i compiled from the hash commit of 6090f54 on my mac and it worked perfect so we now are trying to compile on a different linux box for production.. but it fails.. we can't use 2.1.1 as it doesn't contain the fixes for the page.settings.dpi portion that we really need

**Comment by Vitallium** [comment]
Make sure you linked `phantom` platform plugin into the final executable and build Qt with it.

**Comment by northkode** [comment]
OK!... now.. i apologize.. but we dont know what that means? how do we link it? Sorry

**Comment by Vitallium** [comment]
if you do a regular build by using our python script `build.py` you will have it linked successfully. Could you please describe step by step how did you build Linux version?

**Comment by northkode** [comment]
We ran the build.py as you mentioned.. 
Step for step
checked out master.. 
reset head to 6090f54 as we knew that worked for us locally.. 
then i ran sub module init, update
and then the python build.py command. 

it finished the build successfully.. but we get that error.  
```
This application failed to start because it could not find or load the Qt platform plugin "phantom"
in "".
```

**Comment by northkode** [comment]
keep in mind the above process works for my mac.. and runs fine.  But not on our production linux box.

**Comment by thoop** [comment]
@northkode Do you have any more info that could help move this forward? Which version of linux are you using?

You might just have to wait for an official release here.

**Comment by jesg** [comment]
@northkode @thoop the build.py script has been deprecated and the build process is being refactored for the 2.5 release.   i also don't have any luck building phantomjs from source on the master branch.

i've had to build the linux version from source to apply patches.  i ended up using the 2.1.1 release and cherry pick the patches.  then i built the release on [docker](https://github.com/ariya/phantomjs/tree/master/deploy).

**Comment by northkode** [comment]
@jesg do you have a process you can document in here? as well as the patches you applied?

I ended up going back to 2.0.0 and using a fork from someone else that had the dpi settings that we needed and got it working, but i would rather be using 2.1.1

**Comment by jesg** [comment]
first apply the patches you want on top of the 2.1.1 release.  i applied the dpi patch and the cookie patch in this example.
```shell
$ git checkout 2.1.1
$ git checkout -b 2.1.1-1
# apply the dpi patch
$ git cherry-pick 5232c9dff98115600d1b1491e538e01c0de2d650
# apply the cookie patch
$ git cherry-pick d0388371cfda166d97165c1b68182857b954cc83
```
next we follow the [release](https://github.com/ariya/phantomjs/tree/master/deploy) instructions.
```shell
$ git clean -xfd .
$ docker run -v $PWD:/src debian:wheezy /src/deploy/docker-build.sh
```
the project should build everything from source in the docker container.
