### ISSUE TITLE
Phantomjs blocks CORS requests on some pages even when web security is disabled

### ISSUE THREAD

**Issue by critterothecreed** [ariya/phantomjs#14531]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   using phantomjs 2.1.1 (but also reproductible on 2.0)
   (Version 1.9.8 does not present the issue)
2. What steps will reproduce the problem?
   1. created config file phantomConfig.JSON with contents attached
      [phantomConfig.zip](https://github.com/ariya/phantomjs/files/462209/phantomConfig.zip)
   2. created test.js file with contents attached
      [test.zip](https://github.com/ariya/phantomjs/files/462217/test.zip)
   3. ran (in ssh command line): ./phantomjs2.1.1 --config=phantomConfig.JSON test.js
   4. Expected output "Finishing sandboxed_processContent". Got:
      **SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
   
   undefined:3 in open
   :3 in sandboxed_processContent
   :5**
3. Which operating system are you using?
   CentOS 6.4 (Linux 2.6.32-358.el6.x86_64)
4. Did you use binary PhantomJS or did you compile it from source?
   Tried with downloaded binary but also with my own, compiled from source. Same behaviour.

**Comment by Losiara** [comment]
> Expected output "Finishing sandboxed_processContent". Got: **SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.

Try to change user_agent with PhantomJS.

**Comment by critterothecreed** [comment]
i tryied it to something like 'Special Agent' as well as something taked from a working version of phantomjs (1.9.8). Same problem.

**Comment by Losiara** [comment]
> like 'Special Agent'
Lol! Realy dont understand?
OK, you need very standart firefox or chrome desktop Agent because many sites prevent their content been hacked by robots.

**Comment by critterothecreed** [comment]
As far as i know, since sites can not keep track of what new version of Chrome (for example) will send as name of the agent, they rarely parse this info. Thats certainly true for this site i'm using where 'Special Agent' works just fine (with phantomjs 1.9.8).

**Comment by Losiara** [comment]
> SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.

I got the same message on some sites, so decided that it is security policy, but if you did the same on that site with success... so I am sorry, I dont know.
