### ISSUE TITLE
Worker is not a function

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [ariya/phantomjs#14534]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   **2.1.1**
2. What steps will reproduce the problem?
   
   ``` sh
   $ node_modules/phantomjs-prebuilt/bin/phantomjs 
   phantomjs> typeof Worker
   "object"
   phantomjs> 
   ```
3. Which operating system are you using?
   **Debian 3.2.81-2 x86_64 GNU/Linux**
4. Did you use binary PhantomJS or did you compile it from source?
   **binary**
5. Please provide any additional information below.
   Worker should be a function (Constructor) and not an object: https://developer.mozilla.org/en-US/docs/Web/API/Worker

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thank!

**Comment by natlibfi-arlehiko** [comment]
Thank you. Where can I find the 2.5 binary? The [download page](http://phantomjs.org/download.html)`only has the 2.1.1 release.

**Comment by Vitallium** [comment]
@natlibfi-arlehiko [here](https://bitbucket.org/ariya/phantomjs/downloads)

**Comment by natlibfi-arlehiko** [comment]
Nope:
```sh
$ bin/phantomjs 
phantomjs> typeof Worker
"object"
phantomjs> 
```

**Comment by Vitallium** [comment]
@natlibfi-arlehiko ok! Thank you!

**Comment by twalpole** [comment]
In 2.5.0
    
    phantomjs> typeof Worker == "function"
    true

so it appears to be fixed there
