### ISSUE TITLE
page.settings cannot use specific username/password with NTLM auth in PhantomJs 2.1.1.

### ISSUE THREAD

**Issue by bigbearzhu** [ariya/phantomjs#14547]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. set username and password on page.settings.
   2. call page.Open(url)
3. Which operating system are you using?
   Windows 7
4. Did you use binary PhantomJS or did you compile it from source?
   binary PhantomJS.
5. Please provide any additional information below.
   I try to change the user opening a authenticated web page to a local user, e.g. MyMachine\Foo. The previous versions of PhantomJS 1.9 and 2.0 both worked against the Windows Authentication set up in IIS. The authentication method was NTLM through Microsoft Negotiate. However in PhantomJS 2.1 it was ignoring the username and password on the page settings, and always logon as the user running the PhantomJS process.

**Comment by Vitallium** [comment]
This is a known problem. Right now username/password are not set correctly. I'll land my fix to master soon.

**Comment by bigbearzhu** [comment]
Many thanks @Vitallium! Good to see it is a known issue and fix is coming! I didn't find any existing bug about it, so I raised it. Feel free to close if it is duplicate to anything.

Do you have any details about why this is happening or workaround? I did a quick check on the code of NetworkAccessManager trying to figure it out. But doesn't seem there was any changes on PhantomJS side. And setUser, setPassword are both called on the QNetworkAccessManager::authenticationRequired signal.

**Comment by Vitallium** [comment]
@bigbearzhu the bug is in the Config class. `user` and `password` are never called.

**Comment by bigbearzhu** [comment]
Sorry @Vitallium, I'm confused. My understanding is Config class only cares about proxyAuth not the authentication for a single page, are you referring to proxyAuth? Correct me if I'm wrong.

**Comment by AlvaroRojas** [comment]
Any news about this issue @Vitallium ?

**Comment by sridharangopal** [comment]
Hi @Vitallium ... any updates on this issue?
Thanks.
