### ISSUE TITLE
PhantomJS crashed during casperJS script

### ISSUE THREAD

**Issue by csimpi** [ariya/phantomjs#14544]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. Run my script
   2. Wait
      3.
3. Which operating system are you using?
   Linux Ubuntu Trusty
4. Did you use binary PhantomJS or did you compile it from source?
   Bin
5. Please provide any additional information below.
   I have a huge URL list (300 url). I use eachthen and thenopen to open all url and evaluate some data. 
   When i use my script with 1-10 url it is run well, but when i use 50+ url casperjs randomly stops (sometimes it can get through all url). 
   I can think to overflow or something similar error. 

```
[info] [phantom] Step anonymous 538/5213: done in 358139ms.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault (core dumped)
```

I'm trying to release some resources (delete screenshots, url list store and read from file not from variable etc..), it can run more times but it still crashes. 
How can i see full bugreport?

**Comment by thoop** [comment]
Please follow the link in the error message to output the crash logs: http://phantomjs.org/bug-reporting.html

How many URLs are you loading at the same time? How long are you waiting after each URL to load a new one?
