### ISSUE TITLE
Multiple 

### ISSUE THREAD

**Issue by apur** [ariya/phantomjs#14540]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1. Call rasterize.js from php

3. Which operating system are you using?
Ubuntu 14.04
4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.
Am getting multiple phantomjs processes running in the ubuntu server.

**Comment by Vitallium** [comment]
This is definitely something wrong with your code. PhantomJS has single process model.

**Comment by apur** [comment]
Following is the code, could you please help?
 $url = "phantomjs rasterize.js" + $url_of_webpage;
        $output = shell_exec($url);

**Comment by Vitallium** [comment]
Sorry, I'm not a PHP expert.

**Comment by apur** [comment]
Its a shell exec.
Is there anything we need to call after making a call to rasterize?

**Comment by Vitallium** [comment]
No, `rasterize.js` just opens an URL, renders it to an image and exists PhantomJS
