### ISSUE TITLE
PhantomJS 1.9.8 Segmentation fault 11 in macOS Sierra

### ISSUE THREAD

**Issue by justinjmoses** [ariya/phantomjs#14558]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
PhantomJS 1.9.8 for Mac

2. What steps will reproduce the problem?
  1. Install macOS Sierra
  2. Download and unpack https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip 
  3. Run `phantomjs`
  4. `Segmentation Fault: 11`
 
3. Which operating system are you using?
MacOS Sierra (production release) 10.12. (This occurs both before and after upgrading to XCode 8.0 8A218a)

4. Did you use binary PhantomJS or did you compile it from source?
Binary (though I tried a source build but ran into obvious compiler warnings for unsupported OS version and crashing soon thereafter for missing header files).

5. Please provide any additional information below.
I can't upgrade to Phantom2.x for the time being; we're getting unusual errors with header scripts either downloading as `async` or `defer` in Phantom, causing body scripts to error out as their deps haven't loaded (still investigating)

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by barryoneill** [comment]
Thank you for the response, but that's not really an option to those of us with legacy unit test suites that don't work with v2.

**Comment by Vitallium** [comment]
Feel free to file a new issue about your problems with 2 version.

**Comment by justinjmoses** [comment]
My issue is already filed: https://github.com/ariya/phantomjs/issues/13908

**Comment by boneskull** [comment]
Hi.  I understand PhantomJS 1.9.x is not longer supported.  Many projects are still using it.  Mocha consumes PhantomJS 1.9.x for the sole purpose of ensuring those projects that *do* use it can still run their tests.  Unfortunately, there's a real lack of visibility around how many projects still use 1.9.x.

Our CI suite doesn't run on macOS, so this is mostly just an inconvenience for those Mac users hacking on Mocha.

**Comment by SelviRatnasingam1** [comment]
I still get the error "Segmentation failed: 11", while I am using Phantomjs 2.1.1 (in macOS Sierra). Any idea?

**Comment by johanbaath** [comment]
Same issue on 2.1.1 for me as well 😢 .

**Comment by shifi** [comment]
I get `'Segmentation fault: 11'` too on 2.1.1. Any ideas how to fix that?

**Comment by hisapy** [comment]
Same problem here with 2.1.1 in macOS Sierra

**Comment by geoffcallender** [comment]
Pleeeeease fix this issue, or make 2.1 usable on Mac OS (https://github.com/ariya/phantomjs/issues/12685, which is closed but should not have been).
