### ISSUE TITLE
Fix typo in Contributing Guide

### ISSUE THREAD

**Issue by vjwilson** [ariya/phantomjs#14550]
There is a minor typo in the Contributing Guide, regarding how to name feature branches.

Under the subheading [Use Feature Branch](https://github.com/ariya/phantomjs/blob/master/CONTRIBUTING.md#use-feature-branch), the first _instead of_ is confusing and should be removed.

> Give it a meaningful name ~~instead of~~, e.g. `prevent-zero-divide` instead of just `fix`

I read about the need for help with fixing issues, e.g., in #14541, and I want to help out. Rather than just add to the list of issues, I will submit a PR for this, as a way to "get my feet wet".

**Comment by johanssj** [comment]
On 21/09/16 19:55, Van Wilson wrote:
> Rather than just add to the list of issues, I will submit a PR for 
> this, as a way to "get my feet wet".

Good on you Van. I started perusing the source and issues few days ago 
before my weekly time budget for extra-curricula OSS ran out.
Hopefully next week with a new time quota I can "get my feet wet" too! :-)
