### ISSUE TITLE
phantomJS download server is offline, getting xml error when trying to dl PhantomJS windows https://bitbucket.org/ariya/phantomjs/downloads/ 

### ISSUE THREAD

**Issue by korygrandy** [ariya/phantomjs#14557]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2. What steps will reproduce the problem?
  1.
  2.
  3.

3. Which operating system are you using?
Windows
4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.
Clicking the file https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-windows.zip fails to load  Please correct bitbucket fileServ

**Comment by Vitallium** [comment]
That's okay. Sometimes Amazon S3 acts weird and disallows downloading it. Just wait a bit.
