### ISSUE TITLE
phantomjs proxy authentication fails

### ISSUE THREAD

**Issue by JensBoeykens** [ariya/phantomjs#14554]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   1.9.20     ("grunt-casper": "0.4.2")
2. What steps will reproduce the problem?

```
var page = require('webpage').create();
page.onResourceReceived = function(response) {
    console.log('Response (#' + response.id + ', stage "' + response.stage + '"): ' + JSON.stringify(response));
};
page.open('http://www.hln.be/', function() {
    console.log(page.content);
});
```

In grunt we set these proxy parameters:

```
--proxy=<server>:<port>
--proxy-auth=<user>:<pw>
```

expected result: the html of the page
actual result: html of the proxy (proxy authentication failed)
1. Which operating system are you using?
   Linux Red Hat 7 (RHEL7)
2. Did you use binary PhantomJS or did you compile it from source?
   we use grunt-casper which has phantomjs as a requirement
3. Please provide any additional information below.

related to https://github.com/ariya/phantomjs/issues/10811 but this story has been closed. Is there a workaround?

**Comment by thoop** [comment]
Can you upgrade to the latest PhantomJS 2.1.1 to see if this issue is fixed?

Are you sure you aren't actually using the wrong username/password for your proxy?

**Comment by max-favilli** [comment]
I am using PhantomJS 2.1.1
I am sure the username/password are correct

I confirm it doesn't work.

**Comment by Vitallium** [comment]
@max-favilli more info? Because I can confirm it works.

**Comment by max-favilli** [comment]
@Vitallium if you want I can share privately proxy+username+password

**Comment by Vitallium** [comment]
@max-favilli no needs. What kind of proxy is it?

**Comment by max-favilli** [comment]
I am using http://shader.io/

**Comment by cfank** [comment]
I am also experiencing this problem when attempting to use http://crawlera.com to scrape a site with phantom+casper. The credentials work fine when using:
```
curl -U <api-key>:<blank> -x proxy.crawlera.com:8010 http://httpbin.org/ip
```
...but when I attempt to use --proxy and --proxy-auth, I receive a 407 "Proxy requires authentication" response.

1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. Using the command-line:
```
casperjs --url="https://www.example.com" --ssl-protocol-any --ignore-ssl-errors=true --proxy="proxy.crawlera.com:8010" --proxy-auth="<api-key>:<blank>" casper-script.js
```
... results in a 407 "Proxy requires authentication" response.

3. Which operating system are you using?
OSX 10.10.5 but also reproducible on centOS 6.5

4. Did you use binary PhantomJS or did you compile it from source?
Binary from npm

5. Please provide any additional information below.
I believe Crawlera uses an HTTP proxy, and using their "Fetch API" seems to be working okay for now but it's... not ideal. Any help you can provide would be appreciated, and I'll try to provide any additional needed information I can.

**Comment by cfank** [comment]
@max-favilli Have you been able to get this to work with Phantom v2.1.1?

**Comment by max-favilli** [comment]
@cfank Nope. The proxy provider whitelisted my ip addresses to avoid authentication.

**Comment by cfank** [comment]
Thanks Max.

@Vitallium is there any additional information I could provide you with to help troubleshoot this issue? I've followed up with my proxy provider and they appear to be stumped.

I've reproduced this issue with the following barebones PhantomJS script: (where the username is my API key and the password is empty, as outlined in [my proxy provider's documentation](https://doc.scrapinghub.com/crawlera.html))
```js
var page = require('webpage').create(),
    system = require('system'),
    address = 'http://docs.casperjs.org';
phantom.setProxy('proxy.crawlera.com', '8010', 'manual', '<API key>', '');
page.open(address, function (status) {
    console.log('Page title is ' + page.evaluate(function () {
        return document.title;
    }));
    phantom.exit();
});
```

...which yields the following output (the last line being the 409 Proxy Authentication Required error):
```
2016-12-22T10:42:01 [DEBUG] Phantom - execute: Starting normal mode
2016-12-22T10:42:01 [DEBUG] WebPage - setupFrame ""
2016-12-22T10:42:01 [DEBUG] FileSystem - _open: ":/modules/fs.js" QMap(("mode", QVariant(QString, "r")))
2016-12-22T10:42:01 [DEBUG] FileSystem - _open: ":/modules/system.js" QMap(("mode", QVariant(QString, "r")))
2016-12-22T10:42:01 [DEBUG] FileSystem - _open: ":/modules/webpage.js" QMap(("mode", QVariant(QString, "r")))
2016-12-22T10:42:01 [DEBUG] Set  "manual"  proxy to:  "proxy.crawlera.com" : 8010
2016-12-22T10:42:01 [DEBUG] WebPage - updateLoadingProgress: 10
2016-12-22T10:42:01 [DEBUG] Network - Resource request error: QNetworkReply::NetworkError(ProxyAuthenticationRequiredError) ( "Proxy requires authentication" ) URL: "http://docs.casperjs.org/"
```

As I mentioned above, the `username:` format works fine for `curl`, but PhantomJS is perhaps failing on it? Any ideas or assistance is appreciated. 😄

**Comment by ezako2** [comment]
have the same problem here can't get crawlera working with phantomjs, while they doen't provide password (only username) 
its working fine with curlf

**Comment by melalj** [comment]
You should use this format:
```js
page.setProxy("http://user:pass@proxy_ip_or_host:port/");
```

**Comment by cfank** [comment]
@melalj it looks like the issue is probably related to proxy credentials without a password being discarded, as mentioned here: #14886
