### ISSUE TITLE
phantomjs network monitoring response body undefined always

### ISSUE THREAD

**Issue by gkio** [ariya/phantomjs#14555]
### binary

---

i use this code 

`var url = "http://google.com"`
`var page = require('webpage').create();`
`page.onResourceReceived = function(response) {`
`console.log('Receive ' + response.body);`
`};`
`page.open(url);`

**Comment by thoop** [comment]
`onResourceReceived` does not contain the body in the response:

http://phantomjs.org/api/webpage/handler/on-resource-received.html

**Comment by gkio** [comment]
@thoop how can i get then the data

**Comment by thoop** [comment]
You can't currently.

See:
https://github.com/ariya/phantomjs/issues/10158
https://github.com/ariya/phantomjs/pull/13922
https://github.com/ariya/phantomjs/issues/13908

**Comment by lippea** [comment]
sadly to see it's empty in response body in onResourceReceived and couldn't change it

**Comment by jasonswearingen** [comment]
this issue has been raised in 2011 https://github.com/ariya/phantomjs/issues/10158 and as the related feature has never worked, I am guessing it never will.
