### ISSUE TITLE
dev branch no longer builds 

### ISSUE THREAD

**Issue by ayappanec** [ariya/phantomjs#14563]
While building the master branch, i am encountering the below issue.

g++ -c -m64 -pipe -O2 -Wall -W -std=c++0x -D_REENTRANT -fPIE -DUSE_UTF8 -DSTATIC_BUILD -DQCOMMANDLINE_STATIC -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_LOCATION_LIB -DQT_WEBKIT_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_POSITIONING_LIB -DQT_SENSORS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -Imongoose -Ilinenoise/src -Iqcommandline -I/usr/include/qt5 -I/usr/include/qt5/QtWebKitWidgets -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtOpenGL -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtLocation -I/usr/include/qt5/QtWebKit -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtPositioning -I/usr/include/qt5/QtSensors -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -o networkaccessmanager.o networkaccessmanager.cpp
networkaccessmanager.cpp: In member function âvoid NetworkAccessManager::prepareSslConfiguration(const Config_)â:
networkaccessmanager.cpp:218:41: error: no matching function for call to âQSslCipher::QSslCipher(const QString&)â
             QSslCipher cipher(cipherName);
                                         ^
networkaccessmanager.cpp:218:41: note: candidates are:
In file included from /usr/include/qt5/QtNetwork/QSslCipher:1:0,
                 from networkaccessmanager.cpp:38:
/usr/include/qt5/QtNetwork/qsslcipher.h:61:5: note: QSslCipher::QSslCipher(const QSslCipher&)
     QSslCipher(const QSslCipher &other);
     ^
/usr/include/qt5/QtNetwork/qsslcipher.h:61:5: note:   no known conversion for argument 1 from âconst QStringâ to âconst QSslCipher&â
/usr/include/qt5/QtNetwork/qsslcipher.h:60:5: note: QSslCipher::QSslCipher(const QString&, QSsl::SslProtocol)
     QSslCipher(const QString &name, QSsl::SslProtocol protocol);
     ^
/usr/include/qt5/QtNetwork/qsslcipher.h:60:5: note:   candidate expects 2 arguments, 1 provided
/usr/include/qt5/QtNetwork/qsslcipher.h:59:5: note: QSslCipher::QSslCipher()
     QSslCipher();
     ^
/usr/include/qt5/QtNetwork/qsslcipher.h:59:5: note:   candidate expects 0 arguments, 1 provided
networkaccessmanager.cpp: In member function âvirtual QNetworkReply_ NetworkAccessManager::createRequest(QNetworkAccessManager::Operation, const QNetworkRequest&, QIODevice_)â:
networkaccessmanager.cpp:309:22: error: âFollowRedirectsAttributeâ is not a member of âQNetworkRequestâ
     req.setAttribute(QNetworkRequest::FollowRedirectsAttribute, true);
                      ^
networkaccessmanager.cpp:394:21: error: âredirectedâ is not a member of âQNetworkReplyâ
     connect(reply, &QNetworkReply::redirected, this, &NetworkAccessManager::handleRedirect);
                     ^
make[1]: *_\* [networkaccessmanager.o] Error 1
make[1]: Leaving directory `/home/ayappan/phantomjs_master/phantomjs/src'
make: **\* [sub-src-phantomjs-pro-make_first-ordered] Error 2

For the first error, it seems like there is a mismatch in the function arguments for QSslCipher cipher(cipherName); 
cipherName has type QString and the function declaration in /usr/include/qt5/QtNetwork/qsslcipher.h

class Q_NETWORK_EXPORT QSslCipher
{
public:
    QSslCipher();
    **QSslCipher(const QString &name, QSsl::SslProtocol protocol);**               ----> 2 arguments
    QSslCipher(const QSslCipher &other);
    ~QSslCipher();
    QSslCipher &operator=(const QSslCipher &other);

Second error is pretty straightforward. i don't know from where FollowRedirectsAttribute comes from ?

**Comment by Vitallium** [comment]
Qt 5.5 is not supported yet. Qt 5.6 is required. I'll add a workaround for that. But I doubt that we will support it. Because 5.6 contains this important `redirected` signal for us.

**Comment by ayappanec** [comment]
Okay. I am using Ubuntu 14.04.5. I have installed qt5 but i guess it is not 5.6. Is there anyway to install 5.6 version ?

**Comment by Vitallium** [comment]
@ayappanec you have two options:

1) Use the official installed from http:/qt.io But we didn't test it yet.
2) Use our fork https://github.com/Vitallium/qtbase and build it from sources. Then you need to build new WebKit (annulen/webkit). After that you can try to build PhantomJS

**Comment by ayappanec** [comment]
Thanks for the info. 
Actually i trying this in PowerPC64 Little Endian machine. I didn't see any official builds for ppc64le in qt site. So i think i need to go for option 2.

**Comment by Vitallium** [comment]
Keep in mind that Qt 5 does not support OS X on PowerPC.

**Comment by ayappanec** [comment]
Qt 5 is available for PowerPC through the distro. apt-get install qt5 works in ppc64le ubuntu 14.04. So i think it now boils down to building Qt 5.6 in PowerPC

**Comment by ayappanec** [comment]
@Vitallium What is the procedure for building and installing Vitallium/qtbase & annulen/webkit ?

./configure, make & "make install" for qtbase ?
qmake & "make install" for webkit ?
