### ISSUE TITLE
Getting blank page with PhantomJS request

### ISSUE THREAD

**Issue by gorv** [ariya/phantomjs#14566]
I am trying to get a page of site names build.com using phantomjs like this : 

```
var page = require('webpage').create();
var fs = require('fs');
page.settings.userAgent = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.36';
page.onInitialized = function ()
{
    page.customHeaders = {
        "Accept-Language": "en-US,en;q=0.8",
        "Upgrade-Insecure-Requests": "1",
        "Pragma": "no-cache",
        "Cache-Control": "no-cache"
    };
    page.viewportSize = {
        width: 1280,
        height: 1024
    };
};
page.evaluate(function () {});
page.open('https://www.build.com/millennium-lighting-rwhc17-pendant-light/s875082', function (status)
{
    if (status == 'success')
    {}
    page.render('export.png');
    fs.write('1.html', page.content, 'w');
    phantom.exit();
});
```

But am getting a blank page. Why is it so ? Am I doing something wrong here ? Please help. Am new to phantomjs world :)

Tried with different versions of phantomJS, But still same behaviour :(

Downloaded phantomJS from [this](http://phantomjs.org/download.html) link

I am testing mainly with phantomJS 1.9.8 and MacOS operating system.

To reproduce this issue save this javascript with some name "test.js" (say) and run this command : phantomjs test.js

**Comment by XiaoFaye** [comment]
I'm using the version 2.1.1 on Windows 10, getting the same issue as well. In onUrlChanged event, it will always return "about:blank" at the end.
