### ISSUE TITLE
HTML5 Video

### ISSUE THREAD

**Issue by Rimander** [ariya/phantomjs#14567]
I need play youtube video.
I searched online and in 2012 PhantomJS does not support it.

**Comment by Vitallium** [comment]
Please see https://github.com/ariya/phantomjs/issues/10839#issuecomment-14994323

We will not implement this feature because then we will lose full headless mode. You always can build you own custom PhantomJS with HTML5 Video and Audio.

**Comment by rebootcode** [comment]
@Vitallium  How to build with HTML5 video and audio support ?
