### ISSUE TITLE
PhantomJS cannot connect to internal intranet site to take screenshot

### ISSUE THREAD

**Issue by sramzan** [ariya/phantomjs#14569]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   1.9.7
2. What steps will reproduce the problem?
   May not be able to replicate issue since it relates to my internal network, but I can provide the issues. I continuously get "Operation Cancelled Error Code: 5" which seems to be coming form the underlying QT Project.
3. Which operating system are you using?
   MacOS
4. Did you use binary PhantomJS or did you compile it from source?
   npm install phantomjs
5. Please provide any additional information below.
   I have tried all of the obvious tricks of "--ssl-protocol=any", "--ignore-ssl-errors", "web-security=false", and have set a plethora of settings within the script I run with phantom (can provide them is necessary). I have changes timeout settings, and have tried passing login credentials, but to absolutely no avail. 

My end goal is to simply take a screenshot of the site in question. At best, I have been able to generate a blank screenshot.

I'm just stuck at this point. It has been over a week now, and after hours of reading issues here & posts on Google, I have not found a solution.

If someone could provide some help, or at least point me in the correct direction, I'd greatly appreciate it!

Thanks.

-Sean

**Comment by Vitallium** [comment]
Could you please try 2.1.1 version?

**Comment by sramzan** [comment]
Apologies for the delayed response @Vitallium. Thanks for your response! - Upgrading to version 2.1.1 did in fact help. But, to future readers, using a lazy rendering approach may be helpful (this link was extremely useful: https://gist.github.com/cjoudrey/1341747). I also used a proxy which seemed to help when connecting to an internal site (within our intranet).

For Phantom Team:
------------------------
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I feel the error logging could be a tad more fruitful. Again, I am new to the framework so please correct me if I'm wrong. - I was consistently given an "Operation Cancelled Error Code: 5". This lead me to believe that I had a security issue when trying to connect to an internal site within our company. After some digging, and brute force attempts (i.e. simply curling the site), I realized that my issue was not security related at all. The issue was that the site took some time to load all resources. BUT, setting a fixed interval of time to wait for those resources to load did not cut it either. Using lazy rendering (mentioned above) is the best solution as it dynamically waits for the resources to load. I know this is sort of an edge case, but perhaps there could be a way to add some extra logging on top of QT's 'Error Code 5' error code?

Hope this helps someone, and thanks again for the help @Vitallium!
