### ISSUE TITLE
Uncaught Error: Fatal Windows exception, code 0xc0000005. PhantomJS has crashed. 

### ISSUE THREAD

**Issue by Sugaryou** [ariya/phantomjs#14568]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1.use atom packges markdown-themeable-pdf
   2.use it to make markdown pdf
   3.
3. Which operating system are you using?
   Win7
4. Did you use binary PhantomJS or did you compile it from source?
   http://phantomjs.org/download.html
5. Please provide any additional information below.
   Error: Fatal Windows exception, code 0xc0000005.
   PhantomJS has crashed. Please read the bug reporting guide at
   http://phantomjs.org/bug-reporting.html and file a bug report.
   at ChildProcess.<anonymous> (C:\Users\Sugaryou.atom\packages\markdown-themeable-pdf\node_modules\html-pdf\lib\pdf.js:121:17)
   at emitTwo (events.js:100:13)
   at ChildProcess.emit (events.js:185:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

**Comment by LochMiwa** [comment]
1. Version 2.1.1
2. Just "phantomjs --version" produces the error.
3. Win7 Ent SP1
4. Download from http://phantomjs.org/download.html
5. Fatal Windows exception, code 0xc0000005.
    PhantomJS has crashed. Please read the bug reporting guide at
    <http://phantomjs.org/bug-reporting.html> and file a bug report.

**Comment by rainbow57** [comment]
Is this exception solved? I got the same problem, but does not know how to solve.

**Comment by AndrewJohnBenjamin** [comment]
I am also still seeing this. I am resorting to trying to build phantom myself as a 64bit version as I have read that it may help. The documentation on how to build it from source is poor and its an absolute nightmare. Are we likely to see a 64 bit version of phantom available anytime soon?

**Comment by YuriiZadorozhnyi** [comment]
I have the same problem. Does anybody found the solution?

**Comment by SeanHub** [comment]
Same problem here. Using latest version 2.1.7

**Comment by williamHYJ** [comment]
hi all, what is the final solution of this problem? which already blocked my work

**Comment by zuozonglin** [comment]
same problem,phantomjs verison=2.1.1,windows 10

**Comment by eduardoalvara2** [comment]
Same here. PhantomJs 2.1.1, Windows 10
