### ISSUE TITLE
SVGSVGElement.width throws NotSupportedError when trying to access it.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [ariya/phantomjs#14571]
PhantomJS v2.1.1

Uncaught NotSupportedError: The implementation did not support the requested type of object or operation
1. What steps will reproduce the problem?
   1. Using zoom manually with d3.js
   2. E.g. ask for the .ownerSVGElement of an SVGElement.
   3. Try to access .width.baseVal.value on it.
2. Which operating system are you using?
   Linux
3. Did you use binary PhantomJS or did you compile it from source?
   Binary
4. Please provide any additional information below.

Lodged issue on d3 as well.
https://github.com/d3/d3/issues/2991

Getting an error with SVGSVGElement not having a width property implemented with PhantomJS, (I'll probably lodge an issue with them as well).

I figure it gets the width and height of the parent SVG element.

In Google Chrome the SVG node has a .width property as an instance of SVGAnimatedLength
One thing that comes to mind is that this might be used for the case of SVG inside SVG with animation/translation on them?

```
function defaultExtent() {
  var e = this, w, h;
  if (e instanceof SVGElement) {
    e = e.ownerSVGElement || e;
    w = e.width.baseVal.value;
    h = e.height.baseVal.value;
  } else {
    w = e.clientWidth;
    h = e.clientHeight;
  }
  return [[0, 0], [w, h]];
}
```

I ended up wrapping it in a try catch.
Tried to add properties to the SVGSVGElement object for width and height but it just would not use them.

```
  function defaultExtent() {
    var e = this, w, h;
    if (e instanceof SVGElement) {
      e = e.ownerSVGElement || e;
      try {
        w = e.width.baseVal.value;
        h = e.height.baseVal.value;
      } catch (e) {
        w = this.clientWidth;
        h = this.clientHeight;
      }
    } else {
      w = e.clientWidth;
      h = e.clientHeight;
    }
    return [[0, 0], [w, h]];
  }
```

Maybe not an ideal fix.

My attempt to add properties.

```
// A fix to add width and height with baseVal.value to the SVGElement prototype.
// PhantomJS does not have these features.
if (SVGSVGElement && SVGSVGElement.prototype) {
    if (!SVGSVGElement.prototype.hasOwnProperty('width')) {
        console.log('adding width property');
        Object.defineProperty(SVGSVGElement.prototype, 'width', {
            get: function () {
                console.log('GOTTED WIDTH');
                return {baseVal: {
                    value: this.clientWidth
                }};
            }
        });
    }
    if (!SVGSVGElement.prototype.hasOwnProperty('height')) {
        console.log('Giving height propertys');
        Object.defineProperty(SVGSVGElement.prototype, 'height', {
            get: function () {
                return {baseVal: {
                    value: this.clientHeight
                }};
            }
        });
    }
}
```

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thank!
