### ISSUE TITLE
PhantomJS crash when running test suite with Poltergeist

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#14577]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   1.9.7
2. What steps will reproduce the problem?
   1. Running our rspec with poltergeist test suite
3. Which operating system are you using?
   Ubuntu 14.04 x86_64
4. Did you use binary PhantomJS or did you compile it from source?
   Binary
5. Please provide any additional information below.
   Occurs only 1 time out of every 20 runs

[PhantomJS_crash_stack.txt](https://github.com/ariya/phantomjs/files/512608/PhantomJS_crash_stack.txt)

**Comment by votlon** [comment]
I've noticed this with 1.9 as well, So i've been using 1.7 and 1.8 for ubuntu 14-16.04. Works consistently unlike the newer versions

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
