### ISSUE TITLE
SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW

### ISSUE THREAD

**Issue by asevans48** [ariya/phantomjs#14588]
PhantomJS: 2.1
OS : Ubuntu 16.04 / Centos 6/ Windows 10
- What steps will reproduce the problem?
  1. started concurrent drivers with Selenium 2 or 3
  2. went to any website
  3. Search using JS or a click but it is more prevalent when calling executeScript
  4. started obtaining links
  5. obtained a certain number of pages before the error occurs
- A sample of my log output would be:

13:50:41.459 [main] INFO  org.slf4j.Logger - Using //img[contains(@src,'/maps/')]
13:50:41.460 [main] INFO  org.slf4j.Logger - Found 1 images
13:50:41.471 [main] INFO  org.slf4j.Logger - Getting Image http://216.223.229.7/maps/18605299K1626.jpg for 1476388238960-14440310570192505
13:50:42.327 [main] INFO  org.slf4j.Logger - <----- Getting Back
13:50:42.447 [ForkJoinPool-1-worker-13] INFO  org.slf4j.Logger - Using //ul[@id='ALI']
13:50:42.487 [ForkJoinPool-1-worker-13] INFO  org.slf4j.Logger - Using //ul[@id='SMT']
13:50:42.491 [ForkJoinPool-1-worker-13] INFO  org.slf4j.Logger - Using //table[@id='OFF']
13:51:15.643 [main] INFO  org.slf4j.Logger - Getting 18609162M9682
13:51:15.643 [main] INFO  org.slf4j.Logger - Attempting to Get 18609162M9682 ----->
13:51:15.643 [main] INFO  org.slf4j.Logger - Using JS
13:51:15.651 [main] INFO  org.slf4j.Logger - Executing window.location.assign('http://meganslaw.ca.gov/cgi/prosoma.dll?&W6=14221&searchby=offender&id=18609162M9682')
[INFO  - 2016-10-13T19:53:22.813Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-13T19:54:43.656Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-13T19:54:50.134Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-13T19:58:22.812Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-13T19:59:43.656Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-13T19:59:50.134Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-13T20:03:22.812Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-13T20:04:43.657Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-13T20:04:50.134Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-13T20:08:22.812Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-13T20:09:43.657Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-13T20:09:50.134Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
- Did you use binary PhantomJS or did you compile it from source?

I use the binary for Linux x 64
- Please provide any additional information below:

This happens so often I cannot use the tool. It is with every run after a certain number of crawls, tests, downloads; whatever. There are no apparent zombies.
- Recommendation:

Seeing as this is an extremely common issue of extreme severity, perhaps it would be best to run the cleanup in an asynchronous thread and then just kill everything on failure after a timeout as well as deleting all held resources in whatever tear down you are using. In Selenium, I do this for page loading (see https://github.com/asevans48/GoatGrazerSelenium).

**Comment by jesg** [comment]
@asevans48 is this script running over 6 hours?  you have 13:51:15.651 then 2016-10-13T19:53:22.813Z.  is this the same timezone?

is there some reason you need to use javascript `window.location.assign` instead of the selenium api [go](https://w3c.github.io/webdriver/webdriver-spec.html#go) to navigate?  does phantomjs return a value to selenium or does it hang indefinitely?

**Comment by asevans48** [comment]
No value is returned. I am using Selenium. The website I am using has some difficulty with the using click or anything of the like. There are also javascript links. It is likely a freeze will occur there as well. A work around is really a last ditch effort. Any chance this will be solved?

**Comment by asevans48** [comment]
I have things running in threads to avoid all problems. Everyone's web driver implemenation has been giving me some sort of trouble. I had to containerize the chrome driver. 

This is from a system just using the go() function. I use phantom js on a javascript heavy site.

[INFO  - 2016-10-14T14:59:45.063Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:01:26.455Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:02:38.705Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:04:45.063Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:06:26.456Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:07:38.780Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:09:45.063Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:11:26.456Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:12:38.780Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:14:45.063Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:16:26.456Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:17:38.856Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:19:45.063Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:21:26.456Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:22:38.857Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:24:45.063Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:26:26.456Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-14T15:27:38.857Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
09:29:43.672 [main] INFO  org.slf4j.Logger - Crawler Timed Out After 3600001 milliseconds. 3600 seconds allowed.

Almost working reliably but still pretty infeasible. 
Crawler Timed Out After 3600001 milliseconds. 3600 seconds allowed.

**Comment by asevans48** [comment]
@jesg It runs over 6 hours  because it is in a future in Scala. Please see my above comments as well.

**Comment by jesg** [comment]
@asevans48 you should set the selenium page load timeout and the script timeout in selenium.  page load timeout defaults to 2^31 - 1 and script timeout defaults to 2^31 - 1 in ghostdriver.  the page load time out should default to 300,000 milliseconds and the script timeout should default to 30,000 milliseconds per [w3c timeout spec](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-session-script-timeout).  i'll create a ticket in ghostdriver to fix these timeouts.

(SessionManagerReqHand - _cleanupWindowlessSessions)[https://github.com/ariya/phantomjs/blob/2.1.1/src/ghostdriver/request_handlers/session_manager_request_handler.js#L160] is a cleanup script that runs periodically via javascript setInterval.  it defaults to 300,000 milliseconds (5 minutes)[https://github.com/ariya/phantomjs/blob/2.1.1/src/ghostdriver/request_handlers/session_manager_request_handler.js#L37].  it looks like a bunch of the `_cleanupWindowlessSessions` callbacks are being queued up since setIterval does not require the previous callback to complete before executing the next callback.  internally `getWindowsCount` calls `Object.keys` which is O(n) and might be very large after running for 6 hours.  i'll try to test this out and see if i can reproduce the issue you are seeing.

**Comment by asevans48** [comment]
I set the timeouts as stated and am still seeing:

 [INFO  - 2016-10-17T16:22:52.352Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-17T16:22:52.520Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW

I will notify both tickets if the program freezes.

**Comment by asevans48** [comment]
It is still a major problem, even with the appropriate timeout settings.

[INFO  - 2016-10-17T16:40:52.635Z] Session [77b65540-9488-11e6-8b50-6587ab547a16] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1","webSecurityEnabled":false}
[INFO  - 2016-10-17T16:40:52.635Z] Session [77b65540-9488-11e6-8b50-6587ab547a16] - page.customHeaders:  - {}
[INFO  - 2016-10-17T16:40:52.635Z] Session [77b65540-9488-11e6-8b50-6587ab547a16] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":false,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyAutoconfigUrl":null,"autodetect":false,"socksUsername":null,"socksPassword":null,"httpProxy":"173.208.36.69:3128","proxyType":"MANUAL","noProxy":null,"ftpProxy":"173.208.36.69:3128","socksProxy":"173.208.36.69:3128","hCode":373097727,"class":"org.openqa.selenium.Proxy","sslProxy":"173.208.36.69:3128"}}
[INFO  - 2016-10-17T16:40:52.635Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 77b65540-9488-11e6-8b50-6587ab547a16
Oct 17, 2016 10:40:52 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[INFO  - 2016-10-17T16:42:52.352Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-17T16:42:52.526Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
10:43:23.626 [main] INFO  org.slf4j.Logger - https://sors.doc.state.ok.us/svor/f?p=119:1: Obtained
[INFO  - 2016-10-17T16:45:52.463Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-17T16:47:52.352Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2016-10-17T16:47:52.526Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW

**Comment by asevans48** [comment]
Perhaps it is related to https://github.com/ariya/phantomjs/pull/13817?

**Comment by jesg** [comment]
@asevans48 yes phantomjs caches resources.  there is another issue about pages with lots of resources ariya/phantomjs#14028.

**Comment by asevans48** [comment]
this did not resolve the issue

**Comment by wu491925129** [comment]
![qq 20161018095750](https://cloud.githubusercontent.com/assets/16916857/19461936/6fe8f3fc-951b-11e6-96fc-7ddc819a4c73.png)

what happen？

**Comment by jesg** [comment]
@wu491925129 this does not look related in any way to the issue asevans48 created.

**Comment by asevans48** [comment]
First off, thanks for the responsiveness. It took way longer to timeout this time. I end up stuck in what seems like a constant load loop, neither of which use executeScript, neither of which are run from such a loop. I take the commands from a Queue which drops the popped command and I know this works. 

## Attempt

Here is what I have done for a build:

-set disk cache to a deleting directory in a public path (deletes when the futures complete as expected)
- Set the log path to a deleting path in a log directory (deletes when futures complete as expected)
- Set application cache path in the same way but also disable it entirely (set to false)
- Run the tool in a proxy with page load timeouts at 300,000 ms as recommended and async script timeouts at 30,000 ms my old timeouts were 120,000 ms and 120,000 ms respectively. The timeouts helped, I am guessing, but the error still occurs.  I am using my tools from github which have completed successfully multiple times so the majority of the problem is from what was stated. I could provide a code sample to run in the tool. It is under GPL. A few pesky sites remain. It should be able to speed up debugging/ test case replication. The following steps recreate the problem.

- Enter a series of commands to go through the website https://sors.doc.state.ok.us/svor/f?p=119:1:
- Repeat these series of commands, spawning new phantomjs instances inside futures as old futures finish, maintaining a constant number utilizing different distinct 3 letter search terms.
- Wait for the error.

## Log

The debug data is really, really large but the following sample has been recurring since about 7:00 pm last night almost consistently now:

[DEBUG - 2016-10-18T16:00:03.656Z] RouterReqHand - _handle - {"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"50","Content-Type":"application/json; charset=utf-8","Host":"localhost:14772","User-Agent":"Apache-HttpClient/4.5.2 (Java/1.8.0_101)"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"xpath\",\"value\":\"//input[@name='p_v01']\"}","url":"/session/2c267d50-9549-11e6-bcd8-99b2e8ab9127/elements","urlParsed":{"anchor":"","query":"","file":"elements","directory":"/session/2c267d50-9549-11e6-bcd8-99b2e8ab9127/","path":"/session/2c267d50-9549-11e6-bcd8-99b2e8ab9127/elements","relative":"/session/2c267d50-9549-11e6-bcd8-99b2e8ab9127/elements","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/session/2c267d50-9549-11e6-bcd8-99b2e8ab9127/elements","queryKey":{},"chunks":["session","2c267d50-9549-11e6-bcd8-99b2e8ab9127","elements"]}}
[DEBUG - 2016-10-18T16:00:03.656Z] WebElementLocator - _handleLocateCommand - Element(s) Search Start Time: 1476806403656
[DEBUG - 2016-10-18T16:00:03.656Z] WebElementLocator - _find.locator - {"using":"xpath","value":"//input[@name='p_v01']"}
[DEBUG - 2016-10-18T16:00:03.659Z] WebElementLocator - _locateElements.locator - {"using":"xpath","value":"//input[@name='p_v01']"}
[DEBUG - 2016-10-18T16:00:03.660Z] WebElementLocator - _locateElements.findElementsResult - {"status":0,"value":[]}
[DEBUG - 2016-10-18T16:00:03.660Z] WebElementLocator - _handleLocateCommand.elements - {"status":0,"value":[]}
[DEBUG - 2016-10-18T16:00:03.660Z] WebElementLocator - _handleLocateCommand.rootElement - BODY
[DEBUG - 2016-10-18T16:00:03.660Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: RETRY. Search Stop Time: 1476806403856
[DEBUG - 2016-10-18T16:00:03.681Z] WebElementLocator - _handleLocateCommand - Element(s) Search Start Time: 1476806403518
[DEBUG - 2016-10-18T16:00:03.681Z] WebElementLocator - _find.locator - {"using":"xpath","value":"//input[contains(@id,'LAST_NAME')]"}
[DEBUG - 2016-10-18T16:00:03.684Z] WebElementLocator - _locateElements.locator - {"using":"xpath","value":"//input[contains(@id,'LAST_NAME')]"}
[DEBUG - 2016-10-18T16:00:03.684Z] WebElementLocator - _locateElements.findElementsResult - {"status":0,"value":[]}
[DEBUG - 2016-10-18T16:00:03.684Z] WebElementLocator - _handleLocateCommand.elements - {"status":0,"value":[]}
[DEBUG - 2016-10-18T16:00:03.685Z] WebElementLocator - _handleLocateCommand.rootElement - BODY
[DEBUG - 2016-10-18T16:00:03.685Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: RETRY. Search Stop Time: 1476806403718
[DEBUG - 2016-10-18T16:00:03.699Z] WebElementLocator - _handleLocateCommand - Element(s) Search Start Time: 1476806403589
[DEBUG - 2016-10-18T16:00:03.699Z] WebElementLocator - _find.locator - {"using":"xpath","value":"//input[contains(@id,'LAST_NAME')]"}
[DEBUG - 2016-10-18T16:00:03.702Z] WebElementLocator - _locateElements.locator - {"using":"xpath","value":"//input[contains(@id,'LAST_NAME')]"}
[DEBUG - 2016-10-18T16:00:03.702Z] WebElementLocator - _locateElements.findElementsResult - {"status":0,"value":[]}
[DEBUG - 2016-10-18T16:00:03.703Z] WebElementLocator - _handleLocateCommand.elements - {"status":0,"value":[]}
[DEBUG - 2016-10-18T16:00:03.703Z] WebElementLocator - _handleLocateCommand.rootElement - BODY
[DEBUG - 2016-10-18T16:00:03.703Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: RETRY. Search Stop Time: 1476806403789
[DEBUG - 2016-10-18T16:00:03.710Z] WebElementLocator - _handleLocateCommand - Element(s) Search Start Time: 1476806403656
[DEBUG - 2016-10-18T16:00:03.711Z] WebElementLocator - _find.locator - {"using":"xpath","value":"//input[@name='p_v01']"}
[DEBUG - 2016-10-18T16:00:03.714Z] WebElementLocator - _locateElements.locator - {"using":"xpath","value":"//input[@name='p_v01']"}
[DEBUG - 2016-10-18T16:00:03.714Z] WebElementLocator - _locateElements.findElementsResult - {"status":0,"value":[]}
[DEBUG - 2016-10-18T16:00:03.714Z] WebElementLocator - _handleLocateCommand.elements - {"status":0,"value":[]}
[DEBUG - 2016-10-18T16:00:03.714Z] WebElementLocator - _handleLocateCommand.rootElement - BODY
[DEBUG - 2016-10-18T16:00:03.714Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: RETRY. Search Stop Time: 1476806403856
[DEBUG - 2016-10-18T16:00:03.736Z] WebElementLocator - _handleLocateCommand - Element(s) Search Start Time: 1476806403518
[DEBUG - 2016-10-18T16:00:03.736Z] WebElementLocator - _find.locator - {"using":"xpath","value":"//input[contains(@id,'LAST_NAME')]"}
[DEBUG - 2016-10-18T16:00:03.739Z] WebElementLocator - _locateElements.locator - {"using":"xpath","value":"//input[contains(@id,'LAST_NAME')]"}
[DEBUG - 2016-10-18T16:00:03.740Z] WebElementLocator - _locateElements.findElementsResult - {"status":0,"value":[]}
[DEBUG - 2016-10-18T16:00:03.740Z] WebElementLocator - _handleLocateCommand.elements - {"status":0,"value":[]}


## Afterthought

Since the preceeding text is basically all that appears and nothing really completes, I am guessing that this is why the clean up script gets triggered. I would expect to log the next action in my queue when the current process completes but it never does. The futures just time out after 60 minutes and the same process repeats.

**Comment by jesg** [comment]
@asevans48 i'm sceptical that "SessionManagerReqHand - _cleanupWindowlessSessions" is triggering the failure.  it's a function that runs periodically via setInterval.  with that said it could fail if the number of windows is large.  for example both of the following scripts will crash phantomjs:
```javascript
const _max32bitInt = Math.pow(2, 31) -1;
console.log('before loop')
var large_obj = {};
for(var k = 0; k< _max32bitInt; k+=1) {
    if(k % 1000 === 0) {
        console.log(k);
    }
    large_obj[k] = k;
}
console.log('after');
```
and
```javascript
# warning your system may run out or ram
const _max = 268430000;
console.log('before loop')

var large_obj = {};
for(var k = 0; k< _max; k+=1) {
    if(k % 1000 === 0) {
        console.log(k);
    }
    large_obj[k] = k;
}
console.log('after');
console.log(Object.keys(large_obj).length);
```
i don't think you are opening a window per search or reusing the same phantomjs process so i find this scenario unlikely.

as far as the locators are concerned i would use css selectors instead of xpath.  contains is expensive you should use anchors when possible.
eg.
```
//input[contains(@id,'LAST_NAME')] => input[id$="LAST_NAME"]
//input[@value='Search'] => input[value="Search"]
```

if chromedriver also stalls then this might be something that is inherent to selenium or browsers in general for the site you are scraping.

**Comment by alihesari** [comment]
Any fix for this issue yet?
