### ISSUE TITLE
Where is build.py?

### ISSUE THREAD

**Issue by isnifer** [ariya/phantomjs#14585]
Hey! I've got an error while build docker container:
```bash
Recreating the build directory /root/build...

Transferring the source: /src -> /root/build. Please wait...

Compiling PhantomJS...
python: can't open file 'build.py': [Errno 2] No such file or directory
```
2. What steps will reproduce the problem?
```bash
docker run -v $PWD:/src debian:wheezy /src/deploy/docker-build.sh
```

3. Which operating system are you using? - macOS Sierra

4. Did you use binary PhantomJS or did you compile it from source? - compile

Also, for os x the same problem:
```bash
deploy/build-and-package.sh

# result
deploy/build-and-package.sh: line 5: ./build.py: No such file or directory
```

**Comment by Vitallium** [comment]
We have removed it because we removed bundled submodules (QtBase and QtWebKit). We are still working on the updated instruction how to build PhantomJS.

But you always can checkout tag 2.1 and build it.

**Comment by isnifer** [comment]
Ok, thanks

**Comment by mateor** [comment]
maybe add that to the README...

**Comment by Jevin23** [comment]
Have some news about how to build PhantomJS from master ?

**Comment by jublo** [comment]
@Vitallium How can phantomJS be built?

> We are still working on the updated instruction how to build PhantomJS from master.

**Comment by dcballs** [comment]
Maybe anyone can give a hint about building a bleeding edge phantomjs :-)

**Comment by insatmc** [comment]
Any idea how to build from master?
