### ISSUE TITLE
phantomjs proxy catch exception

### ISSUE THREAD

**Issue by ljdawn** [ariya/phantomjs#14581]
my phantomjs version is 2.1.1
here is my code 
```
service_args = [
    '--proxy=%s' % '124.42.7.103:80',
    '--proxy-type=%s' % 'https',
    '--ignore-ssl-errors=true',
    '--ssl-protocol=TLSv1'
]
driver = webdriver.PhantomJS(service_args=service_args)
driver.implicitly_wait(TIME_WAIT)
wait = WebDriverWait(driver, TIME_WAIT)
driver.get('http://www.baidu.com')
```
if the proxy is invalid, then driver.page_source get '<html><head></head><body></body></html>'
I wanna catch the exception, Could u plz tell me how to do that ? 
And sometimes I got 
"Message: {"errorMessage":"Currently Window handle/name is invalid (closed?)","request":{"headers":{"Accept":"application/json","Accept-Encodin    g":"identity","Connection":"close","Content-Length":"114","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:64373","User-Agent":"Python-urllib/2.7"},"httpVersi    on":"1.1","method":"POST","post":"{\"url\": \"http://zhushou.360.cn/detail/index/soft_id/3508760\", \"sessionId\": \"e55562e0-8d2a-11e6-a764-3330391cee5b\"}","url":"/url","url    Parsed":{"anchor":"","query":"","file":"url","directory":"/","path":"/url","relative":"/url","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol    ":"","source":"/url","queryKey":"
This should be caused by the invalid proxy, how can i fix this ?
 thank you

**Comment by ljdawn** [comment]
driver.set_page_load_timeout(60) seems this line can fix this? I'm confused

**Comment by chfyjy** [comment]
I  have the same problem。Is the problem solved, or can some suggestion tell me

**Comment by chfyjy** [comment]
I have the same problem。Is the problem solved, or can tell me some suggestion

**Comment by chfyjy** [comment]
When I set proxy by this|:self.driver.capabilities["proxy"] = {"proxy": proxyip.proxy,                                  
                                         "proxy-type": "http"} 

to open a url address success

**Comment by ljdawn** [comment]
@chfyjy  which proxy are u using?

**Comment by chfyjy** [comment]
Code like I show， that http is.
