### ISSUE TITLE
Missing build.py in master branch blocks builds

### ISSUE THREAD

**Issue by deviantintegral** [ariya/phantomjs#14589]
I'm trying to build phantomjs off of the master branch using the docker containers. After installing the build dependencies, the build script dies looking for build.py. It looks like that was intentionally removed, but do the deploy/* scripts need to be updated too?

Here's the build log: https://gist.github.com/deviantintegral/e31cd1c8679a73b0dfa78ae734a78426

**Comment by graaff** [comment]
See #14585
