### ISSUE TITLE
Splits the argument on comma

### ISSUE THREAD

**Issue by 3zzy** [ariya/phantomjs#14596]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. `phantomjs ./script.js 'http://www.google.com/search?as_st=y&tbm=isch&hl=en&as_q=&q=GRIFFIN "GB40337"&as_oq=&as_eq=&cr=countryAU&as_sitesearch=&safe=images&tbs=ctr:countryAU,itp:photo,isz:lt,islt:xga&tbm=isch' 'Mozilla/5.0 (Windows; U; Windows NT 6.0; hu-HU) AppleWebKit/528.16 (KHTML, like Gecko) Version/4.0 Safari/528.16'`
   2. `console.log(system.args);`
3. Which operating system are you using?
   Ubuntu 16.04
4. Did you use binary PhantomJS or did you compile it from source?
   binary
5. Please provide any additional information below.
   As you would see in the output, PhantomJS splits the string into multiple arguments upon encountering a **comma** which is not desired since its a single argument enclosed on quotes.

**Comment by MaxiSantos** [comment]
@3zzy, I was experimenting similar issues with a json stringified sent as an argument to phantomjs.
You need to delete all whitespaces and then put all within double quotes and if you need to have a double quotes inside your parameter then escape them with \"
`javascript`
phantomjs phantom.js "{\"url\":\"http://localhost:8080/#topic/id\",\"output\":\"/src/graphs/\",\"domain\":\"localhost\",\"user_id\":\"AAA\",\"user_email\":\"some_mail\",\"graph_type\":\"pie\"}" "{\"topics\":[\"id1\",\"id2\"],\"age\":5}"

So when I receive them within phantom I have 3 argments as I expect.
