### ISSUE TITLE
random freezes of phantomJS during tests in Docker Container

### ISSUE THREAD

**Issue by ppaulis** [ariya/phantomjs#14595]
Hello!

We are running Behat tests in our CI system with the PhantomJS 2.1.1 binary (PHP/Behat/Mink/PhantomJS) on Docker containers. But very often, there are random freezes of PhantomJS. The process is still running, but doesn't respond anymore, so the Behat test is hanging. Our containers are running on ubuntu host machines on AWS EC2.
Initially we thought, that the error occured only when all the memory of the container was used, but later we found out that the problem also occurs with enough free memory.

We already tried to restart PhantomJS at every Behat test case, but this doesn't prevent the error either.

Is there perhaps some known issue about this? Don't hesitate to get back to me if you need more information.

Thank you,
Pascal

**Comment by asevans48** [comment]
If you can get to your logs, do you see something like __cleanupWindowlessSessions - Asynchronous cleanup starting NOW

**Comment by deviantintegral** [comment]
We're having issues with phantomjs in docker as well. Our tests will hang at an indeterminate point such as:

```
2016-10-06T18:57:58 [DEBUG] WebPage - updateLoadingProgress: 33
2016-10-06T18:57:58 [DEBUG] WebPage - updateLoadingProgress: 36
2016-10-06T18:57:58 [DEBUG] WebPage - updateLoadingProgress: 38
2016-10-06T18:57:58 [DEBUG] WebPage - updateLoadingProgress: 40
2016-10-06T18:57:58 [DEBUG] WebPage - updateLoadingProgress: 42
```

I'm not seeing anything about windowless sessions.

It'd be great to have a build off of master we could test against to see if this is fixed.

**Comment by asevans48** [comment]
I have an open issue that started in much the same way. I ran phantom js from selenium separately and found that as an issue. https://github.com/ariya/phantomjs/issues/14588.

**Comment by ppaulis** [comment]
@asevans48 Indeed... I added some logging and found this:
```[INFO  - 2016-10-19T20:29:06.182Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW```

**Comment by ppaulis** [comment]
@asevans48 It seems to me that this is the same problem than the one mentionned in #11526

**Comment by asevans48** [comment]
Because it is happening in more than just Behat, my system is straight java with no containers yet. For me it seems to be a concurrency problem. I am going to try LXC.

**Comment by emerson-h** [comment]
I've also experienced random crashes with Docker; we've been able to reproduce locally on OSX hosts, though local crashes are not as common as those running on EC2 Ubuntu hosts
