### ISSUE TITLE
2.1.1 port for FreeBSD

### ISSUE THREAD

**Issue by courtland** [ariya/phantomjs#14597]
I realize this is not specifically a phantomjs issue, but it would be really nice to have an easy way to install 2.1.1 on FreeBSD. Currently the lang/phantomjs FreeBSD port has been stuck at 2.0.0 for some time, which suffers from bugs that have been fixed in 2.1.

Since 2.1 switched to having qt as a git submodule (i.e., no longer able to simply download a phantomjs-source archive that includes qt), I am struggling with trying to update the port to 2.1.1 myself. My hope is that someone more familiar with the phantomjs project could help push along getting the FreeBSD port updated.

I have also reached out to the FreeBSD community and port maintainer here:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213634

Thanks.

**Comment by Vitallium** [comment]
We have good news actually about that. Some time ago folks from Debian encountered with the same problem. And we as a team don't like to have the whole Qt module inside of our repository. That's why our next major release 2.5 can be build against the system Qt version. So I suggest to wait for 2.5.

**Comment by Avaray** [comment]
Too bad. Reaching 2.5 might take years.

**Comment by do3meli** [comment]
What are the plans for phantomjs 2.5? I do depend on a 2.1.1 FreeBSD port too and cant wait for a 2.5 version. could this bug may be prioritized and included in an earlier minor release of 2.1, @Vitallium ?

**Comment by Vitallium** [comment]
@do3meli 2.5 is around the corner. But I do not have a BSD machine here, so you will depend on BSD maintainer to get the 2.5 version.

**Comment by do3meli** [comment]
@Vitallium around the corner could mean a lot :-) can you may share some more details? getting a BSD port is not a big deal once Qt is no longer part of phantomjs i guess.

**Comment by Vitallium** [comment]
@do3meli it means that you can build and use it right now.

**Comment by nomadlogic** [comment]
Hi can you clarify the previous comment regarding "you can build and use it right now"?  Is this the master branch, or have the dependencies with QT been broken out in the 2.1.1 branch?

Reason I ask is it does not look like there is a build.py script in the master branch, and pulling submodules against Master does not seem to pull in anything.

As per the docs located here: http://phantomjs.org/build.html

```
[pewright@pwright-dev ~/git/phantomjs]$ git branch -vv
* master ec2966b [origin/master] Add code block for clean tree command (#14583)
[pewright@pwright-dev ~/git/phantomjs]$ git submodule init
[pewright@pwright-dev ~/git/phantomjs]$ git submodule update
[pewright@pwright-dev ~/git/phantomjs]$
```

I'd love to build/test this locally for my environment.  Thanks in advance!

**Comment by nomadlogic** [comment]
Hi, Bumping this thread in light of 2.5 hitting beta as per:
https://groups.google.com/forum/#!topic/phantomjs/AefOuwkgBh0

- I'm a bit confused as to which source we should be using to build v2.5.  I downloaded the Master branch from Bitbucket but I am unsure if this is the correct repository vs the one here on Github.  Master in both repositories does not seem to be in sync.

Any guidance will be really appreciated as I'm hoping to help get the FreeBSD port updated as soon as possible.

Cheers!
-pete
