### ISSUE TITLE
Screen Capture when image height over 32000px，image is white.

### ISSUE THREAD

**Issue by skyii123** [ariya/phantomjs#14593]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   phantomjs-2.1.1-windows
2. What steps will reproduce the problem?
   1. Screen Capture when image height over 32000px，image is white.
      2.
      3.
3. Which operating system are you using?
4. Did you use binary PhantomJS or did you compile it from source?
5. Please provide any additional information below.

**Comment by trista00** [comment]
I also appeared this problem Did you solve it?
