### ISSUE TITLE
Selenium Webdriver returns empty response even with --ssl-protocol=any and --ignore-ssl-errors=true

### ISSUE THREAD

**Issue by EuclidHeron** [ariya/phantomjs#14591]
Hi,

Not sure if this is the right place, but this seemed like a bug to me.
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.0.0
2. What steps will reproduce the problem?
   Can be reproduced by running the following Python script :
   from selenium import webdriver
   driver = webdriver.PhantomJS(service_args=['--ignore-ssl-errors=true', '--debug=true', '--ssl-protocol=any'])
   driver.get("https://tmp.org")
   print(driver.page_source)

I am seeing (in my logs)
2016-10-16T18:31:31 [DEBUG] Network - Resource request error: 2 ( "Connection closed" ) URL: "https://tmp.org/"

If I try the url 'https://www.americascarmuseum.org' I get 'Resource request error: 6 ( "SSL handshake failed" )'

Additionally, I get 'Resource request error: 6 ( "SSL handshake failed" )' when I do driver.get("https://www.americascarmuseum.org") , which seems contradictory to '--ignore-ssl-errors=true' and  '--ssl-protocol=any'
1. Which operating system are you using? Mac
2. Did you use binary PhantomJS or did you compile it from source? binary
3. Please provide any additional information below.
   See above for how to reproduce (its a really short script).

**Comment by eromoe** [comment]
os:windows 8
phantomjs:2.1.1

I meet this problem too,  remove `--ssl-protocol=any` is fine.
