### ISSUE TITLE
I cannot use Phantomjs in a multi-threaded environment.

### ISSUE THREAD

**Issue by JafferWilson** [ariya/phantomjs#14605]
I am trying to use the PhantomJS in a multi-threaded environment. But it is becoming single threaded. What shall I do if I want to make Phantomjs run in a multi-threaded environment.?
If anyone can help them please do let me know .. fast.
Thank you.

**Comment by Vitallium** [comment]
I m not sure that you mean. Could you please elaborate more?

**Comment by JafferWilson** [comment]
I was trying to work with PhantomJS and I was not able to use it in a multi thread environment. I have searched a lot and found that the PhantomJS is made to run in a single threaded environment. So may I know if there is any way to run the PhantomJS in multi threaded mode. Say multi threaded means I want to run two or more threads using PhantomJS whereas now it is only working with single thread.
