### ISSUE TITLE
Phantom Capture produces empty GIFs

### ISSUE THREAD

**Issue by j-medland** [ariya/phantomjs#14603]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
Version 2.1.1

2. What steps will reproduce the problem?
Running the rasterize.js example from http://phantomjs.org/screen-capture.html with the output as tiger.gif produces a GIF file of zero bytes.

3. Which operating system are you using?
Windows 7 Professional 

4. Did you use binary PhantomJS or did you compile it from source?
Binary

**Comment by Vitallium** [comment]
We removed GIF rendering from 2.0 release. See this https://github.com/ariya/phantomjs/issues/12480 for more information.
