### ISSUE TITLE
The requested URL was rejected. Please consult with your administrator.  Your support ID is

### ISSUE THREAD

**Issue by george-dragnea** [ariya/phantomjs#14601]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. Which operating system are you using?
   I have tried both Windows 10 (x64) and Ubuntu 16.10 (x64). I have tried using PHP, after that I have tried using NodeJs.
3. Please provide any additional information below.
   Sometimes the script works, sometimes I get the following message:

The requested URL was rejected. Please consult with your administrator.
Your support ID is: 11243555349794389926

I don't really think is a problem with PhantomJs, but if someone know why this appear...

Thanks.

**Comment by gloute** [comment]
Hi,
If this is of any help, this message is issued by an network equipement, specifically a F5 Application Security Manager.
