### ISSUE TITLE
After set proxy get like this: <html><head></head><body></body></html>

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#14602]
Env:python 2.7 selenium webdriver phantomjs(2.1)
I tried these way to set proxy
1.         dcap['proxy'] = {
            "httpProxy":ipport,#ipport='xx.xx.xx.xx:xxxx'
            "ftpProxy":ipport,
            "sslProxy":ipport,
            "noProxy":None,
            "proxyType":"MANUAL",
            "class":"org.openqa.selenium.Proxy",
            "autodetect":False
            }
2.         self.driver = webdriver.PhantomJS(executable_path='phantomjs.exe', desired_capabilities=dcap)
            proxytmp = webdriver.Proxy()
            proxytmp.proxy_type = ProxyType.MANUAL
            proxytmp.http_proxy = ipport
            proxytmp.add_to_capabilities(webdriver.DesiredCapabilities.PHANTOMJS)
            self.driver.start_session(webdriver.DesiredCapabilities.PHANTOMJS)
1 or 2 can set proxy,
 the log(ghostdriver.log)like: "proxy":{"proxyType":"MANUAL","httpProxy":"94.233.164.76:80"}}
but get webpage's source code like this:<html><head></head><body></body></html>
3.         service_args = [
            '--proxy=%s'%(ipport),
            '--proxy-type=%s'%(proxytype),
            ]
            self.driver = webdriver.PhantomJS(executable_path='phantomjs.exe',service_args =service_args)
4.         self.driver.capabilities['proxy'] = {'proxy': ipport, 'proxy-type': 'http'}
3 or 4 can't set proxy the log:"proxy":{"proxyType":"direct"}

Couldyou give me some advice ? Thanks.

**Comment by chfyjy** [comment]
1 or 2 can set proxy,
the log(ghostdriver.log)like: "proxy":{"proxyType":"MANUAL","httpProxy":"94.233.164.76:80"}}
but get webpage's source code like this:<html><head></head><body></body></html>

**Comment by chfyjy** [comment]
the log(ghostdriver.log)like: "proxy":{"proxyType":"MANUAL","httpProxy":"94.233.164.76:80"}}
but get webpage's source code like this:---->'<html><head></head><body></body></html> '

**Comment by chfyjy** [comment]
the log(ghostdriver.log)like: "proxy":{"proxyType":"MANUAL","httpProxy":"94.233.164.76:80"}}
but get webpage's source code like this:\<html\>\<head\>\</head\>\<body\>\</body\>\</html\>

**Comment by chfyjy** [comment]
I‘m so sorry，the problem caused by that proxy is invalid
