### ISSUE TITLE
Syntax Error: Use of reserved word 'class'

### ISSUE THREAD

**Issue by Davy-F** [ariya/phantomjs#14611]
I'm running PhantomJS v2.1.1 along with Karma, Jasmine and Gulp as a testing platform. I am new to this, but getting the following error multiple times:

![image](https://cloud.githubusercontent.com/assets/19592376/19763091/86393a98-9c34-11e6-88b4-198b6fb0cea1.png)

In these JS files I am calling 'export class'.

A quick Google suggests that this could be down to it not being compatible with ES6 as I am running the latest version of Angular2.

Any help around this issue would be appreciated. Thank you.

**Comment by michaeljota** [comment]
I don't think there is a workaround. You should compile down to ES5 for the PhantomJS to run properly.

**Comment by ariya** [comment]
Modern JavaScript features (from ES6/ES2015 or later) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
