### ISSUE TITLE
Failure to render WebP images inside a page

### ISSUE THREAD

**Issue by mrharel** [ariya/phantomjs#14616]
1. PhantomJS version: 2.1..1
2. I was just trying to render a page where there are Webp images. for example: https://developers.google.com/speed/webp/gallery1
3. using Mac
4. binary

when running this code:

``` javascript
var webPage = require('webpage');
var page = webPage.create();

page.viewportSize = { width: 1920, height: 1080 };
page.open("https://developers.google.com/speed/webp/gallery1", function start(status) {
  page.render('test.jpeg', {format: 'jpeg', quality: '100'});
  phantom.exit();
});
```

i got this image:
![screen shot 2016-10-28 at 01 19 02](https://cloud.githubusercontent.com/assets/473889/19789020/8fe49420-9cac-11e6-82a4-680ec80c938a.png)

any idea if this going to be fixed?

**Comment by Vitallium** [comment]
Support for WebP images will be in 2.5 release

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thank!
