### ISSUE TITLE
Not bundled all the javascript in one binary file distribution

### ISSUE THREAD

**Issue by aplicacionamedida** [ariya/phantomjs#14615]
I think that it's a good idea to have 2 kind of distributions.  The current distribution: all bundled in one  binary file. And the not bundled all distribution: the binary file for execution separated from the javascript  files  used by phantomjs (not all is bundled in the same binary). With this other approach is much more easy to hack phantomjs without any compilation step. On linux it's very easy to compile. But on windows is very painful. And at the same time its much more easy to test new ideas and get a feedback because the compilation is very long.

**Comment by ariya** [comment]
Implementing this is a major undertaking and currently beyond the scope of the project.
You are however free to work on it on your own or sponsor someone to implement it. Once it is in a state where we can consider it for inclusion, please reopen this issue and submit a pull request of the implementation. Thank you!
