### ISSUE TITLE
Wrong result from regex test

### ISSUE THREAD

**Issue by ykaragol** [ariya/phantomjs#14625]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?

-   tested:  `/^\d{1,3}(\.\d{1,3})?$/.test("11.23")` and it returns false.
-   tested: `new RegExp(/^\d{1,3}(\.\d{1,3})?$/).test("22.24")` and it returns false.

3. Which operating system are you using?
Windows 10

4. Did you use binary PhantomJS or did you compile it from source?
Binary downloaded

5. Please provide any additional information below.
Both test values returns true in chrome. Also https://regex101.com/#javascript site returns true for both values.

**Comment by Vitallium** [comment]
Could you please try again with 2.5 beta binary?

**Comment by ykaragol** [comment]
From where can I download it?

**Comment by Vitallium** [comment]
https://bitbucket.org/ariya/phantomjs/downloads

**Comment by ykaragol** [comment]
Same result:
```
phantomjs> /^\d{1,3}(\.\d{1,3})?$/.test("11.23")
false
phantomjs> new RegExp(/^\d{1,3}(\.\d{1,3})?$/).test("22.24")
false
phantomjs>

```

**Comment by twalpole** [comment]
This is ja result of the phantomjs command line parser - If you put the regex into a js file and run phantomjs with that file it will be fine.  If you escape the \s at the phantomjs command line it will work too

    /^\\d{1,3}(\\.\\d{1,3})?$/.test("11.23") => true
