### ISSUE TITLE
fs module not found

### ISSUE THREAD

**Issue by jadeclan** [ariya/phantomjs#14620]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.13
2. What steps will reproduce the problem?
  1.fs = require('fs');
  2.
  3.

3. Which operating system are you using? linux mint rosa

4. Did you use binary PhantomJS or did you compile it from source? binary

5. Please provide any additional information below.
I suspect there is a problem with the nodejs fs file and the phantomjs fs file, but I have no idea where to find the phantomjs fs file let alone install it.

**Comment by sramzan** [comment]
Do you have phantomjs installed? How did you install it? Is it built?

**Comment by jadeclan** [comment]
Sean, thanks for response.  It turns out phantomjs' fs file conflicts with
node's fs file and that was the problem.

**Comment by sramzan** [comment]
Yup that's what I was thinking, that's why I was asking how you installed it & such. Glad you were able to resolve your issue :)

May be best to close this issue when you get a chance @jadeclan
