### ISSUE TITLE
Regression in encoding.cpp

### ISSUE THREAD

**Issue by jowiho** [ariya/phantomjs#14632]
The (refactoring) commit 9d1c6b9 introduced a bug in ``encoding.cpp``. The comparison on line 76 was accidentally reverted, which effectively renders ``setEncoding`` useless.

**Comment by zackw** [comment]
Clearly our test suite is inadequate, it should have caught this -- can you
provide a test case?

**Comment by Vitallium** [comment]
Whoops. Damn. Nice catch! We definitely need a test for it. But we also have a bunch of failing tests. These tests should be fixed too.

**Comment by jowiho** [comment]
If I can find the time, I could have a look at adding a test. But I'll wait for the new build instructions first. Currently I can't even figure out how to build the project. :-)
