### ISSUE TITLE
Support for Umlaut URLs

### ISSUE THREAD

**Issue by pex** [ariya/phantomjs#14631]
Testet with version **2.1.1** on macOS 10.12.1:

Run `$ ./bin/phantomjs examples/loadspeed.js "http://de.wikipedia.org/wiki/Dorfkirche_Alt-Lönnewitz"` (freshly downloaded binary)

- Expected result is `Page title is Dorfkirche Alt-Lönnewitz – Wikipedia`
- Actual result is `Page title is Ungültiger Titel – Wikipedia` (which translates to "invalid title")

I did not find a single Umlaut URI I was able to open successfully.

First investigation showed, that the opened URL already seems to be wrong (having utf-8 replacement characters instead of actual umlauts). I used following script for testing:

```javascript
var page = require('webpage').create();
var url = 'http://de.wikipedia.org/wiki/Dorfkirche_Alt-Lönnewitz';
page.open(url, {encoding: 'utf8'}, function () {
  console.log(url);
  phantom.exit();
});
```

Output is 'https://de.wikipedia.org/wiki/Dorfkirche_Alt-L%EF%BF%BDnnewitz` - which obviously is wrong.

Passing `--output-encoding=utf8` to the executable didn't change the result.

**Comment by HaNdTriX** [comment]
Try encoding the URI before using it:

    var page = require('webpage').create();
    var url = encodeURI('http://de.wikipedia.org/wiki/Dorfkirche_Alt-Lönnewitz');

    page.open(url, function () {
      var title = page.evaluate(function() {
        return document.title;
      });
      console.log('Width raw URL:', url, title);
    });

should work

**Comment by pex** [comment]
Thanks @HaNdTriX works like a charm!
Though I think this could become part of Phantomjs as well.
