### ISSUE TITLE
4 Errors encountered installing phantomjs

### ISSUE THREAD

**Issue by perskes** [ariya/phantomjs#14642]
[deleted]

**Comment by ricokahler** [comment]
What version of phantomjs are you trying to build? The current master doesn't have a `build.py`.

Also provide `phantomjs/src/qt/qtwebkit/config.log`. I think that should show more detail on why webkit failed the configuration tests.

**Comment by sramzan** [comment]
Are you using node at all? npm would be rather helpful in this case, in my opinion.

`npm install phantomjs`

[Installing Phantom via npm](https://www.npmjs.com/package/phantomjs)
