### ISSUE TITLE
[Question] Removing fontconfig dependency

### ISSUE THREAD

**Issue by ricokahler** [ariya/phantomjs#14644]
I've been building versions of phantomjs 2.2 to use as an HTML to PDF converter. I don't full access to the servers that will be running my modified version of phantomjs so it would be ideal to link all dependencies statically.

Question: **How do I link fontconfig statically properly? Is this even a good idea?**

The current phantomjs (2.1.x) depends on fontconfig. I'm trying to remove that dependency but I can't seem to get it working correctly. I have compiled fontconfig on centOS 5 with
```shell
./configure --prefix=/usr        \
            --enable-static \
            --disable-shared \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-docs       \
            --docdir=/usr/share/doc/fontconfig-2.12.1
```
. Phantomjs compiles but on a clean installation of centOS 5 but it won't load web safe fonts correctly. It loads embedded fonts correctly but not the fonts that are suppose to part of the OS. 

Running `./phantomjs rasterize.js https://people.mozilla.org/~jkew/woff/ test0.pdf` works as expected:
![image](https://cloud.githubusercontent.com/assets/10551026/20246899/ddcb6aa8-a98e-11e6-8bb0-4efba1e952ea.png)

But running `./phantomjs rasterize.js http://ariya.github.io/html/webfont/ test1.pdf` produces this:
![image](https://cloud.githubusercontent.com/assets/10551026/20246907/08c703b6-a98f-11e6-97de-e66c51b91c48.png)

So this leads me to believe fontconfig isn't configured properly. My question is how to do so and is it a good idea to link fontconfig statically in the first place? Should we consider linking it statically in master?

Thanks!

####
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
`phantomjs2.2.0-development`
2. What steps will reproduce the problem?
  1.
  2.
  3.

3. Which operating system are you using?
centos 5 and centos 6
4. Did you use binary PhantomJS or did you compile it from source?
compiled it from source
5. Please provide any additional information below.

**Comment by annulen** [comment]
I would try to build Qt with bundled freetype (-qt-freetype) and without fontconfig support
