### ISSUE TITLE
Typekit fonts stopped rendering

### ISSUE THREAD

**Issue by ksere** [ariya/phantomjs#14641]
Using phantomjs 2.1.1 (binary) on Windows 10.

Steps to reproduce:
  1. Try a page render on a page that loads fonts from typekit. For example [this page](http://blog.typekit.com/2015/08/04/new-embed-code-for-asynchronous-font-loading/).

You will see that the fallback font load instead from the one from typekit.
This started happening in the last few days, and since nothing changed from my side, something propably changed on how typekit serves it's fonts.

Others pages on the typekit site render their fonts properly ( for example [this one](https://typekit.com/colophons/cid0nfb) ) but in that case they serve a different font loader script from the one they supply for public use.

Using phantomjs with debug on, prints out this warning:

`[WARNING] QWindowsFontDatabase::fontEngine: Can't change family name of font`

(printed x times for each font trying to load)

I understand this issue is weird, out of scope, and propably typekit's fault, but i am really out of ideas.
Thanks.

**Comment by ksere** [comment]
The linux binaries render the fonts correctly.

**Comment by Vitallium** [comment]
Could you please try again with 2.5 beta binary?
