### ISSUE TITLE
Not support flexbox css?

### ISSUE THREAD

**Issue by rohmanhm** [ariya/phantomjs#14666]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`. **2.1.1**

2. What steps will reproduce the problem?
  1. 
  2.
  3.

3. Which operating system are you using? **OSX El-Capitan 10.11.6**

4. Did you use binary PhantomJS or did you compile it from source? **YA.**

5. Please provide any additional information below.
I put a screenshot from my web page, and the result is messy if the element using flexbox style.

**Comment by rohmanhm** [comment]
Here the screenshot with phantomjs
![image](https://cloud.githubusercontent.com/assets/7524911/20644756/df735970-b473-11e6-9311-674443ba5a90.png)

compared with this one with Google Chrome
![image](https://cloud.githubusercontent.com/assets/7524911/20644761/20804068-b474-11e6-96f1-0fd035ca654a.png)

**Comment by jbreckmckye** [comment]
The PhantomJS webkit version is ancient. If you are able to run your headless browser on an OS with an X-server (or XVFB), I would suggest you try using Electron or SlimerJS instead. Both should support Flexbox rendering and a whole host of modern web features (including ES6 scripting).

**Comment by Vitallium** [comment]
Full flexbox support will be in version 2.5.

**Comment by rohmanhm** [comment]
Woo, sounds cool 👍🏼

**Comment by Vitallium** [comment]
Flexbox landed in 2.5 beta!

**Comment by fergardi** [comment]
Hello!

I'm trying to use the 2.5.0 (first, second does not work, lacks something in F:\ drive) beta version with flexbox support, and my modern CSS is working fine as expected. But the PDF renderization only gives me 1 page. It cuts the content of my web page in half as expected, but do not loops over pages, so my final DPF is single paged, no matter what combination of options.

Am I missing something here?

Thank you.

**Comment by ariya** [comment]
Modern web features (flexbox etc) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
