### ISSUE TITLE
What versions of Selenium is PhantomJS 2.1.1 compatible with?

### ISSUE THREAD

**Issue by macdonjo** [ariya/phantomjs#14669]
I looked at the release notes and there's almost nothing. This isn't an "issue" with the code but rather an issue with the docs. I'd love to know a combination of the 2 that I can use.

I'm trying to find a combination to work with Python, Selenium and PhantomJS.

**Comment by jesg** [comment]
ghostdriver implements selenium's [json wire protocol](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol).  so selenium 2 and 3 should work for most clients.  it is missing parts of the the [w3c webdriver](https://www.w3.org/TR/webdriver/) specification.

**Comment by madhavajay** [comment]
Why is this issue still broken?
https://gist.github.com/neuro-sys/41e368839a9b20dafb34

I have tried multiple versions of PhantomJS with ghostdriver and it doesn't seem to be able to connect to Selenium Grid, is there an official version with this fix?

**Comment by Vitallium** [comment]
@madhavajay the short answer is @detro doesn't maintain the Ghostdriver anymore. And we don't have time and human power to fix it.

**Comment by madhavajay** [comment]
But its just a two line comment out from the join_hub.js. I am going to try building it without it and see if it works, then surely it could be accepted into the master branch and a new build made? Its pretty annoying that there doesn't seem to be a stable phantomjs for selenium. Theres even a pull request on the official selenium repo for phantomjs support from 2 years ago that is still not accepted. Does no one use PhantomJS with selenium out there?

**Comment by Vitallium** [comment]
@madhavajay I know that users are using it with Selenium, but they can't (or do not want) contribute back. Personally, I don't use Selenium bindings, so all Selenium related issues have low priority in my TODO list.

**Comment by madhavajay** [comment]
Thats a real pity... if I can get it to work is anyone interested in helping me get the fix upstream, i mean my understanding is it simply removes some meta information which while that would be nice, stopping it from functioning is far worse: https://github.com/detro/ghostdriver/issues/394#issuecomment-75531714

**Comment by Vitallium** [comment]
@madhavajay the basic to update it is:

1) Get the most up to date fork, like this https://github.com/asolntsev/ghostdriver
2) Update it according to all latest changes in master in PJS
3) Make a pull request

**Comment by madhavajay** [comment]
I still need to make the change which fixes the bug though right, its not going to work by simply getting the latest GhostDriver code, or are you saying that it will work with the latest GhostDriver code but the code in PhantomJS is too out of sync?

**Comment by madhavajay** [comment]
So it looks like theres already work on 2.5 which i assume brings all these things together as well? How far away is that?

**Comment by jesg** [comment]
> I have tried multiple versions of PhantomJS with ghostdriver and it doesn't seem to be able to connect to Selenium Grid, is there an official version with this fix?

@madhavajay you should be able to connect to selenium grid with the up to date detro/ghostdriver master branch.

fwiw you don't need to recompile phantomjs to run a more recent version of ghostdriver.  if you are running java you can set the selenium `phantomjs.ghostdriver.path` capability to the more recent src/main.js

> So it looks like theres already work on 2.5 which i assume brings all these things together as well? How far away is that?

in 2.5 there are plans to update ghostdriver and add a command line option to override the packaged version of ghostdriver in phantomjs.  i managed to build 2.5 on Vitallium's repository yesterday so i can start testing ghostdriver on it.  i also plan on releasing an unofficial npm package for ghostdriver so it's easier for users to install.

**Comment by madhavajay** [comment]
I am trying to run phantomjs as a selenium node in a docker container. Can I set the phantomjs.ghostdriver.path capability on the selenium node and point to a fresh checkout of the ghost driver? The only working phantomjs selenium docker container I can find it this one https://github.com/AkeemMcLennon/docker-selenium-node-phantomjs but its 2.0 and it crashes sometimes so I figured it might be a good idea to use 2.1.1 seeing how much newer it is.

**Comment by Vitallium** [comment]
@jesg it would be awesome to get updated Ghostdriver in 2.5 :-)

**Comment by jesg** [comment]
@madhavajay if you run phantomjs on a selenium server node you can set `phantomjs.ghostdriver.path`.  it is a java system property so it would be something like

```
java  -Dphantomjs.ghostdriver.path=<path to ghostdriver> -jar selenium-standalone.jar -role node
```

if that does not work you can try https://www.npmjs.com/package/ghostdriver which is my attempt to package a more recent version of ghostdriver.
