### ISSUE TITLE
Version 1.x: HTTPS does not work anymore (at all) (new version of openssl?)

### ISSUE THREAD

**Issue by paps** [ariya/phantomjs#14664]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
1.9.8

2. Which operating system are you using?
Debian unstable

3. Did you use binary PhantomJS or did you compile it from source?
Binary
`npm install phantomjs@1.9.20`

Here is a minimal test script:
```
'use strict';
var page = require('webpage').create();
page.onResourceReceived = function(response) {
  console.log('Response (#' + response.id + ', stage "' + response.stage + '"): ' + JSON.stringify(response, undefined, 2));
};
page.onResourceError = function(err) {
  console.log(JSON.stringify(err, undefined, 2));
};
page.open('http://www.iplocation.net/find-ip-address', function(status) {
  console.log("Status: " + status);
  if(status === "success") {
    console.log("Yay!");
  }
  phantom.exit();
});
```

At my company we still need to use PhantomJS 1 and it stopped working for all HTTPS URLs recently.

Running `phantomjs --ignore-ssl-errors=true --ssl-protocol=any --web-security=false --debug=true script.js`
gives
`Error creating SSL context (error:140A90C4:SSL routines:func(169):reason(196))`

Interestingly, using `--ssl-protocol=tlsv1` gives a slightly different error:
`Invalid or empty cipher list (error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match)`

With `--debug=true` we can see some relevant warnings:
`[WARNING] QSslSocket: cannot call unresolved function SSLv23_client_method`
and
`[WARNING] QSslSocket: cannot call unresolved function sk_num`

My idea is that openssl was updated and removed support for SSLv3 (which is vulnerable and deprecated). However using `--ssl-protocol=any` does not fix the problem so I'm not sure... In fact I was not able to make it work with any combination of parameters.

Does this affect anybody else? Any idea on how to make this work again?

Thanks!

**Comment by invik** [comment]
All the same as you.
Same OS (debian unstable), same phantomjs version, using binary downloaded from site

**Comment by Vitallium** [comment]
Hi! Unfortunately, we don't support PhantomJS 1.x anymore. Please upgrade to 2nd version. 
But if you really need PhantomJS 1.x you always can build it from sources.

**Comment by xandl** [comment]
you don't support 1.X but can't make table header repeating in 2.X ....

what's the best way to get both?
