### ISSUE TITLE
is there any one has built a xp version?

### ISSUE THREAD

**Issue by zhiying8710** [ariya/phantomjs#14679]
my program is running on xp, for some reason, it must be xp, and also i need to use phantomjs2.x, is there any one has built a xp version? can u share it, thx very much.

**Comment by Vitallium** [comment]
Unfortunately, we dropped Windows XP with version 2. The only way to get it working on Windows XP - build it from sources.

**Comment by Vitallium** [comment]
This is what you need - http://doc.qt.io/qt-5/windows-issues.html#targeting-xp-with-visual-studio-2012-and-later
