### ISSUE TITLE
version 1.9.2 no longer downloadable, breaks other packages

### ISSUE THREAD

**Issue by shukriadams** [ariya/phantomjs#14678]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

1.9.2

2. What steps will reproduce the problem?
  1. try using grunt-grunticon @1.0.0
  2.
  3.

3. Which operating system are you using?
Windows

4. Did you use binary PhantomJS or did you compile it from source?
npm package

5. Please provide any additional information below.

We use grunt-grunticon 1.0.0 in a bunch of our builds, by way of dependencies it uses a version of svg-to-png which needs phantomjs 1.9.2, but it seems the content required by this version of the phantomjs is no longer online. One solution is to manually track down this version of phantomjs and drop it your local npm cache, but this is messy. Can we get the 1.9.2 content restored somehow? Thanks.

**Comment by Vitallium** [comment]
You still can download old binaries from Google Code archive: https://code.google.com/archive/p/phantomjs/downloads

**Comment by shukriadams** [comment]
Yes, that's what I'm doing by dropping stuff into my download cache, but this doesn't help automated installs much.

**Comment by Vitallium** [comment]
I am not sure that I can help you with it. You always can download the archive and cache it somewhere.

**Comment by shukriadams** [comment]
Ok, if it can't be fixed then we can close the ticket. 

Just to understand this better though, what happened to the original binaries for that release? Is there a rolling removal of binaries more than x versions behind current?

**Comment by Vitallium** [comment]
Nothing. Google has closed code.google.com. So we moved to github.com. I guess we should transfer all old binaries to Bitbucket as well.
