### ISSUE TITLE
Html to Pdf conversion

### ISSUE THREAD

**Issue by sambasivaraomangapati** [ariya/phantomjs#14673]
Hi all,

I would like to use this phantomjs for html to pdf conversion , my requirements are 
1)Table of contents 
2)BookMarks 
3)Watermarks 
4)Pdf Editing
5)Adding Html controls  
by using phantomjs   my requirements are full filled are not. give your suggestions.

**Comment by vemv** [comment]
> give your suggestions.

* Do your own research
* Don't use an issue tracker as a support desk.

**Comment by dhilipsiva** [comment]
Can we please close this issue?
