### ISSUE TITLE
ReferenceError: Can't find variable: GetQueryString

### ISSUE THREAD

**Issue by feelsky** [ariya/phantomjs#14689]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.11

2. What steps will reproduce the problem?
I copy demo code from "http://phantomjs.org/quick-start.html", then test code like this:

var page = require('webpage').create();
page.open('http://www.163.com/', function(status) {
    console.log("Status: " + status);
    if(status === "success") {
      page.render('example.png');
    }
    phantom.exit();
});

It will show this ReferenceError:
F:\>phantomjs phantemJsTest.js
ReferenceError: Can't find variable: GetQueryString

  http://x.jd.com/exsites?spread_type=2&ad_ids=745:5&location_info=0&callback=ge
tjjsku_callback:35 in global code
ReferenceError: Can't find variable: GetQueryString

http://x.jd.com/exsites?spread_type=2&ad_ids=15:5&location_info=0&callback=getjjsku_callback:35 in global code

3. Which operating system are you using?
win7
4. Did you use binary PhantomJS or did you compile it from source?
No
5. Please provide any additional information below.

**Comment by Vitallium** [comment]
I think these errors are regular errors from a web page. You can ignore them.
