### ISSUE TITLE
header refresh not redirecting

### ISSUE THREAD

**Issue by yurikoex** [ariya/phantomjs#14681]
1. Which version of PhantomJS are you using?
2.1.1

2. What steps will reproduce the problem?
-server 200 OK
-add header Refresh: 0; url=http://some.url
-Expect redirect, but not redirected

3. Which operating system are you using?
c9.io
4.2.0-c9

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
We have tested all other forms of redirection and they work fine.

**Comment by safvanak** [comment]
I cannot redirect my aps page by using phantomjs. When trying o redirect it redirect to login page
