### ISSUE TITLE
Phantomjs.org website not served over HTTPS

### ISSUE THREAD

**Issue by sampablokuper** [ariya/phantomjs#14687]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

    N/A

2. What steps will reproduce the problem?
    1. Visit https://phantomjs.org in a reasonably mainstream, up-to-date web browser. This will result in a "certificate error" or similar warning in the browser.

3. Which operating system are you using?

    This is likely to affect all operating systems on which such a web browser can run.

4. Did you use binary PhantomJS or did you compile it from source?

    N/A

5. Please provide any additional information below.

    This is due to phantomjs.org being [hosted by GitHub Pages](https://github.com/ariya/phantomjs/issues/10490), which [does not support HTTPS for custom domains](https://github.com/isaacs/github/issues/156).

**Comment by Vitallium** [comment]
cc @ariya

**Comment by ariya** [comment]
I'm thinking of moving the site to Firebase (SSL for custom domain, CDN support, HTTP/2, etc).
