### ISSUE TITLE
wrong Date after year 2834

### ISSUE THREAD

**Issue by baabgai** [ariya/phantomjs#14680]
1. Which version of PhantomJS are you using?
    
    Version: 2.1.1

2. What steps will reproduce the problem?
  
     1. call ```new Date('2900')``` or any date string higher than the year 2834
  
3. Which operating system are you using?
    
    OSX 10.11.6

4. Did you use binary PhantomJS or did you compile it from source?

    binary distribution using npm install phantomjs-prebuilt

5. Please provide any additional information below.

The machine is configured to CET local time. Not sure if this has any impact on that specific problem.
The problem is that that any call to ```new Date()``` using a year higher than 2834 the resulting date will be off by one day

e.g. in phantomjs shell
```javascript
new Date('2835') // => "2834-12-31T00:00:00.000Z"
```

in node (v6.4) the result looks like
```javascript
new Date('2835') // => "2835-01-01T00:00:00.000Z"
```

in Chrome (54.0.x) the result is
```javascript
(new Date('2835')).toISOString()  // => "2835-01-01T00:00:00.000Z"
```

**Comment by Vitallium** [comment]
I think it's related to #14506

**Comment by Vitallium** [comment]
Could you please try it again but with 2.5 version?
