### ISSUE TITLE
Doc Improvement Request: Exit/Status Codes 

### ISSUE THREAD

**Issue by michaelfward** [ariya/phantomjs#14682]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
    2.1.1
2. What steps will reproduce the problem?
  1. As of right now, the problem is not reproducible, which is why I am making this post.

3. Which operating system are you using?
  Debian 7.9 Wheezy

4. Did you use binary PhantomJS or did you compile it from source?
  Compiled from source

5. Please provide any additional information below.
  While checking logs, I saw this error message:
  Message: Service /path/to/phantom/phantomjs/latest/bin/phantomjs unexpectedly exited. Status code was: 1  
  EDIT: I removed one log, which was generated by our code and unrelated to the issue with phantom.
I used phantom as normal before & after these messages with no issues. The code that utilizes phantom is ran hundreds of times per day in production; this is the first time this has ever happened. There is no mention of any status/exit/error codes in the docs, and I could not find any while (quickly) searching through the source code as well. While I realize that the contributors to this repository may not be able to resolve the issue for me, I do think that documenting the various codes would go a very long way towards us being able to diagnose & resolve this issue ourselves.

**Comment by Vitallium** [comment]
PhantomJS doesn't generate custom exit status codes. Qt framework provides the native status codes to match the running platform. The answer is just find the regular codes for your platform and check what it does mean.
