### ISSUE TITLE
Phantomjs is throwing error on joining the grid

### ISSUE THREAD

**Issue by ambikashri** [ariya/phantomjs#14688]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1.Install phantomjs
  2.Start the selenium hub
  3.Run the below command

`phantomjs --webdriver=8090 --webdriver-selenium-grid-hub=http://127.0.0.1:4444`

It throws the below error in ubuntu OS

`$ phantomjs --webdriver=8090 --webdriver-selenium-grid-hub=http://127.0.0.1:4444`
`QXcbConnection: Failed to initialize XRandr`
`Qt: XKEYBOARD extension not present on the X server.`
`[INFO  - 2016-12-07T10:46:27.715Z] GhostDriver - Main - running on port 8090`
`[INFO  - 2016-12-07T10:46:27.720Z] GhostDriver - Main - registering to Selenium HUB 'http://127.0.0.1:4444' version:  using '127.0.0.1:8090' with org.openqa.grid.selenium.proxy.DefaultRemoteProxy as remote proxy.`
`[ERROR - 2016-12-07T10:46:27.740Z] GhostDriver - main.fail - {"line":97,"stack":"register\nglobal code"}`

In windows 10 OS it throws the below error

`[INFO  - 2016-12-07T10:46:27.715Z] GhostDriver - Main - running on port 8090`
`[INFO  - 2016-12-07T10:46:27.720Z] GhostDriver - Main - registering to Selenium HUB 'http://127.0.0.1:4444' version:  using '127.0.0.1:8090' with org.openqa.grid.selenium.proxy.DefaultRemoteProxy as remote proxy.`
`[ERROR - 2016-12-07T10:46:27.740Z] GhostDriver - main.fail - {"line":97,"stack":"register\nglobal code"}`

3. Which operating system are you using?
Windows 10 and Ubuntu16

4. Did you use binary PhantomJS or did you compile it from source?
Used phantomJS binary

5. Please provide any additional information below.
I am using selenium grid version 2.53.1

**Comment by jesg** [comment]
@ambikashri i'm not able to reproduce this issue on phantomjs 2.1.1 when running ghostdriver's master branch.

**Comment by ambikashri** [comment]
I didnt compile it from the source code. I directly downloaded and tried it.

**Comment by agreif** [comment]
same problem here with ubuntu 17.04

$ phantomjs --debug=false --webdriver=127.0.0.1:5555 --webdriver-selenium-grid-hub=127.0.0.1:4444 --webdriver-loglevel=INFO --ignore-ssl-errors=true
Fontconfig warning: ignoring UTF-8: not a valid region tag
[INFO  - 2017-05-26T20:25:26.167Z] GhostDriver - Main - running on port 5555
[INFO  - 2017-05-26T20:25:26.167Z] GhostDriver - Main - registering to Selenium HUB '127.0.0.1:4444' version:  using '127.0.0.1:5555' with org.openqa.grid.selenium.proxy.DefaultRemoteProxy as remote proxy.
[ERROR - 2017-05-26T20:25:26.168Z] GhostDriver - main.fail - {"line":97,"stack":"register\nglobal code"}

**Comment by jesg** [comment]
@agreif this issue is fixed in ghostdriver 2.0.0.
