### ISSUE TITLE
Phantomjs has crashed issue with dmp file attached.

### ISSUE THREAD

**Issue by webelieve** [ariya/phantomjs#14690]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

1.9.0

2. What steps will reproduce the problem?
  1. Install phantomjs-1.9.0-linux-x86_64.tar.bz2 on linux 
  2. Linux version: Linux xxxx1247 2.6.32-573.12.1.el6.x86_64
  3. We set up a job on our CI Jenkins server to run test automation. We use ruby cucumber for automation testing.  This is how we start phantomjs:

phantomjs --webdriver=8001 &

3. Which operating system are you using?

  Linux version: Linux xxxx1247 2.6.32-573.12.1.el6.x86_64

4. Did you use binary PhantomJS or did you compile it from source?

We installed phantomjs-1.9.0-linux-x86_64.tar.bz2 on linux

5. Please provide any additional information below.

When we use Install phantomjs-2.1.1-linux-x86_64.tar.bz2 version, we get:

 phantomjs://platform/console++.js:263 in error
     [ERROR - 2016-12-09T19:45:12.372Z] WebElementLocator -     
     _handleLocateCommand - Element(s) NOT Found: GAVE UP. 
     Search Stop Time: 1481312712354

     phantomjs://platform/console++.js:263 in error

So we googled it, some people saying that it might be caused with version compatible issue. So we tried to use phantomjs-1.9.0-linux-x86_64.tar.bz2. But we get "phantomjs has crashed" error. 

Thank you!

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
