### ISSUE TITLE
chang applyScreenWidthOverride

### ISSUE THREAD

**Issue by nekulin** [ariya/phantomjs#14693]
Hello! There is a Screen class and it

```
InspectorInstrumentation::applyScreenWidthOverride(m_frame, &width);
InspectorInstrumentation::applyScreenHeightOverride(m_frame, &height);
```

page.viewportSize don't affect them, is there a way to change them ?

**Comment by Vitallium** [comment]
I doubt you can change it. We have an idea about exposing Developer Tools protocol (and methods) to the user. But this idea is still is `need-to-think-how-to-do-that` phase.

**Comment by nekulin** [comment]
Yes, any idea how to do it.
