### ISSUE TITLE
THEAD not repeated on every page

### ISSUE THREAD

**Issue by kuba-orlik** [ariya/phantomjs#14691]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

`2.1.1`

2. What steps will reproduce the problem?
Run this script:

```
var page = require('webpage').create();

var system = require('system');
var args = system.args;

page.open(args[1], function(status) {
  console.log("Status: " + status);
  page.paperSize = {
	  format: 'A4',
	  orientation: 'portrait',
	  margin: '1cm'
  };

  if(status === "success") {
    page.render(args[2]);
  }
  phantom.exit();
});
```
On an html file with a very tall table, like this:

[table.html.zip](https://github.com/ariya/phantomjs/files/643763/table.html.zip)

The expected result is that the THEAD is repeated on every page, like so:

[expected.pdf](https://github.com/ariya/phantomjs/files/643770/expected.pdf)

But the result does not contain the repeated headers:

[actual.pdf](https://github.com/ariya/phantomjs/files/643771/actual.pdf)

It seems to be a regression, as version 1.9.8 handles the THEAD as expected

3. Which operating system are you using?
Manjaro Arch Linux

4. Did you use binary PhantomJS or did you compile it from source?

binary

**Comment by meneguite** [comment]
We have the same problem here.

**Comment by rafwell** [comment]
+1

**Comment by krutkowski86** [comment]
+1

**Comment by logycware** [comment]
+1

**Comment by mhourahine** [comment]
+1

**Comment by Eric-Cedarspace** [comment]
Any news on this?

**Comment by cmacedo80** [comment]
+1

**Comment by SachaZvetelman** [comment]
+1
