### ISSUE TITLE
pure virtual method called

### ISSUE THREAD

**Issue by Malych** [ariya/phantomjs#14704]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
1.9.2

2. What steps will reproduce the problem?

3. Which operating system are you using?
Red Hat Enterprise Linux Server release 6.8 (Santiago)

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.

[dump.zip](https://github.com/ariya/phantomjs/files/658063/dump.zip)

pure virtual method called
terminate called without an active exception
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at
+https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/7d7b97a7-5e64-9157-497c947d-6cb538c0.dmp

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
