### ISSUE TITLE
PhantomJS failed to install via npm

### ISSUE THREAD

**Issue by Ratstail91** [ariya/phantomjs#14700]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
phantomjs-prebuilt@2.1.14

2. What steps will reproduce the problem?
  1. Install npm via 'sudo yum install nodejs npm'
  2. Install karma via 'npm install karma --save-dev
  3. Install PhantomJS via 'npm install karma-phantomjs-launcher --save-dev'

3. Which operating system are you using?
CentOS 7

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.
PhantomJS fails to install regardless of the method of installation. I've tried everything short of building from source.

**Comment by Vitallium** [comment]
Thank you for submitting the ticket. But we don't maintain the NPM package. Please file your issue under the corresponding repository. Thank you!
