### ISSUE TITLE
Binary Version PhantomJS does not run on alpine

### ISSUE THREAD

**Issue by bluesky4485** [ariya/phantomjs#14725]
1. The version of PhantomJS is  phantomjs-2.1.1, I download form [phantomjs/download](http://phantomjs.org/download.html).

2. What steps will reproduce the problem?
  1. I run a docker of alpine, and I download the binary version of phantomjs and run phantomjs, and I get 'not found' error.
  ![error](http://ww1.sinaimg.cn/large/62b80425gw1fb8vta7r49j20nz078ab6.jpg)
I am so confused about this error.

The same binary version phantomjs-2.1.1 works fine with docker of centos.

**Comment by ylavoie** [comment]
Alpine versions must be compiled with MUSL instead of GLIBC.
Alpine is gaining momentum, it would be very nice to have binaries for it.

**Comment by igalic** [comment]
for reference, from the already closed https://github.com/ariya/phantomjs/issues/14265 there was this (low-prio) Qt bug linked: https://bugreports.qt.io/browse/QTBUG-46543
