### ISSUE TITLE
Console window popup when using phantomjs/pm2 in Windows

### ISSUE THREAD

**Issue by jmartindivmedianet** [ariya/phantomjs#14721]
1. Which version of PhantomJS are you using?
    Looks like 2.1.0 (being loaded by 'webshot').

2. What steps will reproduce the problem?
  Set up a node server to call 'webshot' (or any other screenshotting package that uses phantomjs) either once or on a periodic basis.
  Start your node server with pm2.

3. Which operating system are you using?
    Windows 7 Professional

4. Did you use binary PhantomJS or did you compile it from source?
    It's being loaded inside another package (currently 'webshot', but you'll see the same results with node-horseman, url-to-screenshot, etc.)

5. Please provide any additional information below.
    So starting up one's one node server and calling phantomjs directly or from another package is perfectly smooth.  Once you start up your server with pm2, every call to phantomjs pops up a black console window that steals focus until it disappears.

This is NOT a 'bug' per se... I'm just hoping to get some help to understand (and I imagine the reason is simple) what about phantomjs makes it run in the foreground when it gets spawned by a server running under pm2.

Thanks a lot.

**Comment by jazarja** [comment]
I also found this behavior on windows 8. Phantomjs window is visible when running under pm2.
