### ISSUE TITLE
PhantomJs crashed

### ISSUE THREAD

**Issue by fmajet** [ariya/phantomjs#14726]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1.Just trying to make a simple exec on an hello.js which should display "hello"
  2.phantomjs --version is working and display 2.1.1
  3.

3. Which operating system are you using?
Linux 32 bit

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.
here is the outpout

0x9814f61 /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x9814f61]
3   0x9930124 /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x9930124]
4   0x8460645 /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x8460645]
5   0x8460c8b /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x8460c8b]
6   0x845a5af /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x845a5af]
7   0x84373d5 /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x84373d5]
8   0x80c5f0d /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x80c5f0d]
9   0x8069f53 /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x8069f53]
10  0x80bc24d /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x80bc24d]
11  0xa22bbdd /htdocs/public/www/test/phantomjs/bin/phantomjs() [0xa22bbdd]
12  0x80c4155 /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x80c4155]
13  0x841e143 /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x841e143]
14  0x859d5c2 /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x859d5c2]
15  0x8460252 /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x8460252]
16  0x846087c /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x846087c]
17  0x8460c8b /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x8460c8b]
18  0x845a5af /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x845a5af]
19  0x84373d5 /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x84373d5]
20  0x80c5f0d /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x80c5f0d]
21  0x807f212 /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x807f212]
22  0x80608c9 /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x80608c9]
23  0x805a66c /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x805a66c]
24  0xf7402e16 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xe6) [0xf7402e16]
25  0x805c66d /htdocs/public/www/test/phantomjs/bin/phantomjs() [0x805c66d]

**Comment by ak120684** [comment]
I am seeing this issue almost every day, while running tests on our CI server - which is a linux 64 bit server.
I noticed this error occurs intermittently, and almost all times, it is thrown during a click() event or while opening a page.

*** Error in `/usr/local/phantomjs-2.1.1-linux-x86_64/bin/phantomjs': double free or corruption (out): 0x00007f8f2000eef0 ***

I checked the phantomjsdriver code here - https://github.com/codeborne/ghostdriver/blob/master/binding/java/src/main/java/org/openqa/selenium/phantomjs/PhantomJSCommandExecutor.java

line # 88 is where the error is thrown...but my concern is, its not consistent. it is intermittent.

Need help please. It is everyday thing now, and it gives false negatives.
