### ISSUE TITLE
Remote Debugging - Console "dead"

### ISSUE THREAD

**Issue by arrmo** [ariya/phantomjs#14736]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
v2.1.1 (Ubuntu 16.04 LTS)

2. What steps will reproduce the problem?
  1. Start phantomjs, with remote debugging on (--remote-debugger-port=9000)
  2. Connect to the debugger (http://localhost:9000). This works fine, see the debugger interface, files, etc.
  3. Try to start the program ... the console is non-responsive. For example __run() -> carriage return just line feeds, does not start the program. I can also try to auto-start, but even with debugger; in place it doesn't stop and debug. BTW, I added debugger; to the JS file, and even with refresh it's not showing up in the Webkit debugger.

3. Which operating system are you using?
Ubuntu 16.04 LTS.

4. Did you use binary PhantomJS or did you compile it from source?
Binary, from Ubuntu install.

5. Please provide any additional information below.

**Comment by hitok** [comment]
Same issue.
Windows 10.
Binary.

**Comment by dillonsvincent** [comment]
I am also having the same issues on Mac and Windows. I can get the script to halt but I can never get localhost to show the about:blank link. I'm on -v 2.1.1

**Comment by sontek** [comment]
This seems to only work in Safari.  Broken in Chrome and Firefox

**Comment by jesobreira** [comment]
Same issue here.

Chrome and Firefox. Tested on Ubuntu 16.10 and Windows 7.

**Comment by xlzhao** [comment]
Got Same issue.
Windows 7, Chrome 57.

**Comment by rga-odoo** [comment]
Same issue with Ubuntu 14.04.5 LTS

Workaround for GTD: write __run() in any of source file and `Evaluate in Console` will work.
