### ISSUE TITLE
Phantomjs ignores paint-order attribute on svg path

### ISSUE THREAD

**Issue by adamgamble** [ariya/phantomjs#14733]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1. phatomjs test.js
test.js
```
var page = require('webpage').create();
page.open('https://static.vecteezy.com/system/user_svg_versions/svgs/000/000/136/original/6992e1ff-ab9b-41b3-b38e-b2622048cb8e.svg?1483742968', function() {
  page.render('stroke.png');
  phantom.exit();
});
```

3. Which operating system are you using?
OS X, & Linux
4. Did you use binary PhantomJS or did you compile it from source?
Got it from brew, also used svg2png
5. Please provide any additional information below.

Phantomjs seems to be ignoring the paint-order attribtue which would cause the stroke to be behind the fill of this text. Instead the stroke is on top and you can't see the fill.

Here is what phantomjs renders: 
![stroke](https://cloud.githubusercontent.com/assets/237171/21735643/08bf6ad0-d431-11e6-8657-0611e61ffae2.png)

Here is what it should look like (screenshot from chrome):
<img width="1152" alt="6992e1ff-ab9b-41b3-b38e-b2622048cb8e_svg" src="https://cloud.githubusercontent.com/assets/237171/21735650/12c0a9cc-d431-11e6-8863-65f3ab320962.png">

**Comment by Vitallium** [comment]
Could you please try it with 2.5 beta binary?
