### ISSUE TITLE
PhantomJS identifies Promises as [object Object] instead of [object Promise]

### ISSUE THREAD

**Issue by rbiggs** [ariya/phantomjs#14730]
1. I'm running PhantomJS version 2.1.1 with Mocha and Chai for unit testing.
2. What steps will reproduce the problem?
  1. var promise = new Promise(function() {
     return true;
  });
  2. var test = Object.prototype.toString.call(promise)
  3. console.log(test) // returns [object Object]
  4. In desktop Safari 10 and Chrome 54 this returns [object Promise]
  5. In node this returns [object Promise].

3. Which operating system are you using? I'm on macOS Sierra.

4. Did you use binary PhantomJS or did you compile it from source? NPM install.

5. Please provide any additional information below.
I use this technique to test for native promises. Since I'm using PhantomJS with Mocha and Chai for unit tests, all test that rely on testing for promises fail because they appear to be generic objects.

**Comment by Vitallium** [comment]
Fixed in 2.5 beta
