### ISSUE TITLE
Entire pages are crushed and have their entire <body> removed?

### ISSUE THREAD

**Issue by ddfssdfkofdsfighdfuigf** [ariya/phantomjs#14743]
On some URLs (I can't give an example for privacy reasons), which work in normal browsers, Phantom.js somehow gets confused to the point where it nukes most of the page, leaving </head></body> in the bottom. Very frustrating. Phantom.js doesn't seem reliable at all, and no longer developed at all?

**Comment by zackw** [comment]
Try the 2.5 beta that was just released.

But without an example, there is literally nothing more I can suggest.

**Comment by ddfssdfkofdsfighdfuigf** [comment]
Would love to, but FreeBSD only still has only phantomjs-2.0.0. Very frustrating.
