### ISSUE TITLE
Segfault when visiting https://www.kriminalomsorgen.no/

### ISSUE THREAD

**Issue by petterreinholdtsen** [ariya/phantomjs#14746]
My version of PhantomJS segfaults when visiting the HTTPS version of www.kriminalomsorgen.no.  The HTTP version do not segfault.  I suspect it is related to the fact that the site currently have an invalid SSL certificate.

1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
1.9.0

2. What steps will reproduce the problem?
  1. download https://github.com/ariya/phantomjs/raw/master/examples/netsniff.js and add a line "setTimeout(function() {phantom.exit();},10000);" at the start to ensure it do not hang forever.
  2. run "phantomjs --ssl-protocol any netsniff.js https://www.kriminalomsorgen.no/"
  3. observe segfault

3. Which operating system are you using?
Linux

4. Did you use binary PhantomJS or did you compile it from source?
Precompiled binaries.

5. Please provide any additional information below.

Running the process in valgrind show this problem near the end:

==11722== Invalid read of size 8
==11722==    at 0xED2986: ??? (in /usr/lib/phantomjs/phantomjs)
==11722==    by 0xED6E24: ??? (in /usr/lib/phantomjs/phantomjs)
==11722==    by 0xEFF2A6: ??? (in /usr/lib/phantomjs/phantomjs)
==11722==    by 0xF08B1E: ??? (in /usr/lib/phantomjs/phantomjs)
==11722==    by 0xEFF1D9: ??? (in /usr/lib/phantomjs/phantomjs)
==11722==    by 0xED2E4D: ??? (in /usr/lib/phantomjs/phantomjs)
==11722==    by 0x4EEC7B: ??? (in /usr/lib/phantomjs/phantomjs)
==11722==    by 0x5277D2: ??? (in /usr/lib/phantomjs/phantomjs)
==11722==    by 0x527AE2: ??? (in /usr/lib/phantomjs/phantomjs)
==11722==    by 0x5178B1: ??? (in /usr/lib/phantomjs/phantomjs)
==11722==    by 0x47929B: ??? (in /usr/lib/phantomjs/phantomjs)
==11722==    by 0x410E1C: ??? (in /usr/lib/phantomjs/phantomjs)
==11722==  Address 0x3a is not stack'd, malloc'd or (recently) free'd

Look like a null pointer to a struct is being accessed somewhere.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.
