### ISSUE TITLE
Is there ANY point in asking questions here or trying to get in touch with the Phantom.js developers?

### ISSUE THREAD

**Issue by ddfssdfkofdsfighdfuigf** [ariya/phantomjs#14744]
I have numerous critical issues with Phantom.js, but I'm unable to get any kind of sign of life from the devs. Is there any point in waiting week after week for it to come back to life and people to answer questions? The documentation doesn't mention a word about anything you need to know to do anything, such as how to make it save proper data and make it so you can save pages with images and CSS and whatnot hosted locally.

I have many more problems but I don't get it. It's as if you have shut down the project but not told anyone? And this is somehow still the "best" headless browser project? What am I missing?

**Comment by ariya** [comment]
Questions are best posted to the mailing-list. Also read carefully #14541.
