### ISSUE TITLE
How to use a non-default IP address?

### ISSUE THREAD

**Issue by ddfssdfkofdsfighdfuigf** [ariya/phantomjs#14742]
My server has an admin IP address (never advertised) and a bunch of secondary IP addresses (public). Phantom.js, seems to FORCE the use of the default one. How do I bind it to one of the secondary ones, so I don't use the admin IP address?

Note: I'm not talking about proxies.

**Comment by zackw** [comment]
This _should_ be entirely controlled by the kernel's routing table - PhantomJS isn't doing anything special network-wise, it just creates TCP sockets like any other network client.
