### ISSUE TITLE
page.renderBase64 sometimes returns empty string

### ISSUE THREAD

**Issue by madelson** [ariya/phantomjs#14754]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2.2.1

2. What steps will reproduce the problem?
  a. Have phantom open a webpage and wait for it to load (we poll for the presence of a known element)
  b. Find an empty div (`<div id="someId"></div>`) on the page and retrieve its bounding rectangle (`element.getBoundingClientRect()`)
  c. Render the element using `page.renderBase64`:
```
page.clipRect = boundingClientRect;
var base64Image = page.renderBase64('PNG'); // empty string
```

3. Which operating system are you using?
Windows 7

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.
We use phantom to capture screenshots of our website. Occasionally, phantom will return an empty string from renderBase64. There might be multiple scenarios where this happens but one that I've identified is when the captured element is empty as  This doesn't make sense to me, since this does not decode to a valid PNG image (I would at least expect the PNG header data to be there). Obviously, this isn't that difficult for us to work around, but it would be nice if the PNG coming back were always valid.

**Comment by twalpole** [comment]
An empty div, by default, has dimensions on the page of 0 x 0 which is not possible to produce a PNG for since 0 is not an allowable width or height in the IHDR chunk - https://www.w3.org/TR/PNG/#11Chunks

**Comment by madelson** [comment]
@twalpole very interesting I wasn't aware of that limitation. I'm still not sure that empty string is the best return value in this case, but it sounds like I'm not going to be able to get a valid PNG back regardless.

**Comment by jsCONFIG** [comment]
i have the same problem, and i just use `setTimeout` to wrapper `page.renderBase64` on the inner callback of page.open, and it works!

**Comment by madelson** [comment]
@jsCONFIG can you explain further? Do you setTimeout for a certain period or does any number (e. g. 0ms) work? Do you know why this fixes the issue?
