### ISSUE TITLE
2.5 beta - Date.getDate() returning the wrong day of the month. 

### ISSUE THREAD

**Issue by RussKahler** [ariya/phantomjs#14751]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.5.0-development

2. What steps will reproduce the problem?
  1.use this script 
var testDate = new Date('2016/6/22');

var temp1 = testDate.getDate()
var temp2 = testDate.getUTCDate()
console.log('Should be 22 but is :' + temp1);
console.log('Should be 22 and is :' + temp2);

  2.  in Chrome 
Should be 22 but is :22
Should be 22 but is :22

  3. in phantomjs 
Should be 22 but is :21
Should be 22 but is :22

3. Which operating system are you using?
Windows 10 

4. Did you use binary PhantomJS or did you compile it from source?
binary  2.5 beta

5. Please provide any additional information below.

**Comment by Vitallium** [comment]
The UTC methods calculate their date assuming that the date object is of local time and date. So no error here.

**Comment by RussKahler** [comment]
getUTCDate is not the problem, that method is right.  the problem is getDate method is returning wrong.  if you are -5 like I am if the date created is hours less than 5 the date returned is one less than date used to build the date.     That is the problem.

**Comment by Vitallium** [comment]
Well, if the problem was in `getDate` then Chrome also returns an invalid value. But it's not.

**Comment by RussKahler** [comment]
No, chrome properly is returning me the same date I provided to the date constructor.  For you at +3 it would probably be correct too.   If you set your system TZ to a zone that is after UTC I think you will see the same issue.

**Comment by RussKahler** [comment]
Is there something you need from me on this issue?

**Comment by RussKahler** [comment]
There is script above to reproduce this.  if your system date is  after UTC this problem will happen.  I would bet if your system date was before UTC and you created a date with hours closer to midnight than your offset this would happen too.

**Comment by martinwebrant** [comment]
Today is april 10 2017 and time is 10:29:42
This is the weird output:

const date = new Date(2017, 3, 10, 10, 29, 0);
const date2 = new Date(2017, 3, 10, 0, 0, 0);
const date3 = new Date();

console.error(date);
console.error(date2);
console.error(date3);

ERROR: Mon Apr 10 2017 10:29:00 GMT+0200 (W. Europe Daylight Time)
ERROR: Sun Apr 09 2017 00:00:00 GMT-2200 (W. Europe Daylight Time)
ERROR: Sun Apr 09 2017 10:29:42 GMT-2200 (W. Europe Daylight Time)

**Comment by martinwebrant** [comment]
btw: this works fine in 2.1.1 so it will most likely get most people in trouble that uses 2.5 and dates. Atleast for CET TZ.

**Comment by RussKahler** [comment]
Yeah, we commented out all our tests that were using date (moment) as we needed some of the features that are in 2.5.   Waiting on a resolution to this problem yet.

**Comment by martinwebrant** [comment]
Same here, disabled all unittest and acceptancetest involving dates. 
My guess it's a fault in the webkit version that is used.

**Comment by X-Coder** [comment]
Same here on 2.5.
JQuery's datepicker getDate function is returning the same wrong timezone result like martinwebrant posted (GMT-2200 instead of GMT+0200). MinDate/MaxDate validation is not possible because of this bug.

Small issue with V2.1.1 is, it lacks support of {month: '2-digit'} option for toLocaleDateString.
