### ISSUE TITLE
Is there any way that prevent loading the inlined images but 'loaded event' still be fired

### ISSUE THREAD

**Issue by vhoangvu** [ariya/phantomjs#14756]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
I am building a Pinterest like images crawler, so I need increase the speed as close as Pinterest did, I don't need phantomjs load inlined images, but still need 'loaded event' of DOM element be fired. You can see the sample site http://www.hugoboss.com/uk/all-brands/men/clothing/ use a js library to lazy showing images (https://afarkas.github.io/lazysizes/), that I believe it need 'loaded event' be fired to load other images.

    2.1. Run this command to load the page without loading inline image: phantomjs test.js http://www.hugoboss.com/uk/all-brands/men/clothing/ false
You will see a lot of lines in result: http://images.hugoboss.com/is/image/boss/hbeu50325816_001_21?wid=40&qlt=70
that mean the loaded event was not fired

    2.2. Run this command to load the page with loading inline image: phantomjs test.js http://www.hugoboss.com/uk/all-brands/men/clothing/ true 
You will see the lines above was replaced with lines like: http://images.hugoboss.com/is/image/boss/hbeu50318497_495_21?wid=225&qlt=70
that mean the loaded event was fired, and the real image was set to img tag

3. Which operating system are you using?
OS El Capitan

4. Did you use binary PhantomJS or did you compile it from source?
I used binary PhantomJS

5. Please provide any additional information below.
See test script in attachment
[test.js.zip](https://github.com/ariya/phantomjs/files/705689/test.js.zip)

**Comment by Vitallium** [comment]
You try to run PhantomJS with `--load-images=false`.

**Comment by vhoangvu** [comment]
Is there any difference between `--load-images=false` and setting `page.settings.loadImages = false` in code ? I run the step 2.1 with a setting `page.settings.loadImages = false` and step 2.2 without this setting by checking the command input argument (true/false at the end). Please have a look the attachment code.
