### ISSUE TITLE
PhantomJS Webpage.open encoding issue

### ISSUE THREAD

**Issue by slagumen** [ariya/phantomjs#14753]
Good Day,

i am trying to extract a webpage that has an utf-8 encoding, the actual text should be like this: 

Fodtræningskit

but when i try to open the page and get the content phantomjs is returning me this content.

Fodtr├ªningskit

i tried adding encoding in the page.settings, but no luck. i hope you can help me with this.

Thanks!

**Comment by Vitallium** [comment]
Hi! Could you please paste a sample script (or an URL) to reproduce your problem?

**Comment by Julyyq** [comment]
I met the same problem, encoding settings on OSX is working fine, but on ubuntu server, it does not work as expected.
