### ISSUE TITLE
2.5.0-development WebPage#url and window.location.href are incorrect after redirect

### ISSUE THREAD

**Issue by twalpole** [ariya/phantomjs#14750]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
    2.5.0-development

2. What steps will reproduce the problem?
  With test.js
    
```
      var page = require('webpage').create();
      page.open('http://www.github.com', function(status) {
        if(status === "success") {
          url = page.evaluate(function(){ return window.location.href; });
          console.log(url);
          console.log(page.url);
        }
        phantom.exit()
      });
```
   run  `phantomjs test.js`
   
   with phantomjs 2.1.1 it outputs "https://www.github.com" twice, with 2.5.0-development it outputs "http://www.github.com" twice.  Running with `--debug=true` shows that phantomjs i2.5.0 is redirecting to https, it just doesn't update the page url

3. Which operating system are you using?

 OSX

4. Did you use binary PhantomJS or did you compile it from source?

  The macos 2.5.0-development binary

**Comment by justinklemm** [comment]
FWIW, I noticed that 2.5.0 isn't following 301 redirects, so I think that's probably the root cause here. http://www.github.com redirects to https://www.github.com. 2.1.1 follows that redirect, but 2.5.0 does not. That's why the URL is different.

**Comment by twalpole** [comment]
@justinklemm When running with --debug=true the logs show that it is redirecting

2017-01-16T12:07:43 [DEBUG] Network - Redirecting to  "https://www.github.com/"
2017-01-16T12:07:43 [DEBUG] Network - Redirecting to  "https://github.com/"
2017-01-16T12:07:43 [DEBUG] Network - Redirecting to  "https://github.com/"

and the page content is loaded, so I believe it is actually following the redirect, just not updating the current url

**Comment by justinklemm** [comment]
Ah, interesting. I didn't dig in that deeply when I saw the issue, so I may have misdiagnosed. Either way, you're right that there's a problem here.

**Comment by diiigle** [comment]
I can also confirm this bug in the version from `2017-01-08` uploaded by @Vitallium 
on Bitbucket. 

Is there any progress on this?
