### ISSUE TITLE
DeadClient when running on WSL

### ISSUE THREAD

**Issue by xanthipe** [ariya/phantomjs#14757]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
Version 2.1.1 with Poltergeist 1.10

2. What steps will reproduce the problem?
 1. Attempt to run Cucumber tests on Capybara on Bash on Ubuntu on Windows 10 (tests run and pass on a pure Ubuntu set-up, code itself can be run up fine under WSL).

Result: 
PhantomJS client died while processing {"id":"0053b3f4-ea57-4217-bcf0-895a1d49ba0a","name":"visit","args":["http://127.0.0.1:64001/users/sign_in",30]} (Capybara::Poltergeist::DeadClient)

This applies to any of the tests and any of the steps.

3. Which operating system are you using?
Bash on Ubuntu on Windows 10 - PhantomJS is installed under Ubuntu.

Description:  Ubuntu 14.04.5 LTS
Codename:   trusty

4. Did you use binary PhantomJS or did you compile it from source?
Binary - did have to add the bin path to the environment variables.

5. Please provide any additional information below.
Initially tried this with PhantomJS 1.9.8 on Poltergeist 1.9, this lead to a crash with no dump file - which I believe possibly indicates a permissions error? I'm a Linux newbie so while I'm happy to investigate I will need a bit of hand-holding I'm afraid.

Repo is https://github.com/xanthipe/bladesdb

**Comment by Vitallium** [comment]
>Bash on Ubuntu on Windows 10
No surprise. Bash on Windows 10 has limited API.

**Comment by kerbs17** [comment]
There is a similar issue reported on BashOnWindows

[Microsoft/BashOnWindows#903](https://github.com/Microsoft/BashOnWindows/issues/903)

**Comment by bmayen** [comment]
Some headway over there:
"I was able to repro this and it looks like an Access Violation in PhantomJS i.e it is doing a NULL access/dereference somewhere. I don't know where exactly that is happening, yet. It requires the setup to be run under gdb or put enough print logs within PhantomJS. Anyone has ideas on how to run the whole setup ./node_modules/.bin/karma start --browsers PhantomJS under gdb or some other form of debugging PhatomJS here?"

Can anybody here provide some insight/guidance?

**Comment by mbland** [comment]
FYI, I'm reasonably sure the source of the crash is [the lack of nonblocking `connect()` support in WSL causing a low-level QT error when using WebSockets](https://github.com/Microsoft/BashOnWindows/issues/903#issuecomment-306066510).
