### ISSUE TITLE
PhantomJS has crashed.

### ISSUE THREAD

**Issue by noinlijin** [ariya/phantomjs#14752]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
![image](https://cloud.githubusercontent.com/assets/3073370/21927973/3e3262de-d9c3-11e6-9a22-fa4573b1701e.png)

2. What steps will reproduce the problem?
  1.use casperjs login "https://login.live.com/login.srf"
  2.after login and save cooke
```
var cookies = JSON.stringify(phantom.cookies);
        var fs = require('fs');
        fs.write("./cookie/"+userName, cookies, "w");
```
  3.then use cookie open "https://outlook.live.com/owa", first time is write, next time crash 
error:
![image](https://cloud.githubusercontent.com/assets/3073370/21928143/18079e66-d9c4-11e6-9904-ad0f0d2439f4.png)

3. Which operating system are you using?
mac 10.12.2 and ubuntu 14.04
4. Did you use binary PhantomJS or did you compile it from source?
I use compile source 
5. Please provide any additional information below.

**Comment by noinlijin** [comment]
I use casperjs , I change to engine of slimerjs work well, so I think it is phantomJs this please have a bug

**Comment by noinlijin** [comment]
this is the casperjs code, I use engine of slimerjs work well, but phantomJs was error
```
var casper = require('casper').create({
    pageSettings: {
        loadImages:  false,
        loadPlugins: false,
        userAgent:'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36'
    },
});
casper.options.viewportSize = {width: 1200, height: 800};

casper.start();

var userName = casper.cli.get('user')
var pwd = casper.cli.get("pwd")

casper.on( 'page.error', function (msg, trace) {
    this.echo( 'Error: ' + msg, 'ERROR' );
});

function getElementByContent(selector, text) {
    var elements = document.querySelectorAll(selector);
    return Array.prototype.filter.call(elements, function(element){
        return RegExp(text).test(element.textContent);
    });
}

// login
casper.thenOpen("https://login.live.com/login.srf");
casper.wait(3000,function() {
    this.sendKeys("[name='loginfmt']", userName);
    this.click("[type='submit']");
});

casper.wait(3000,function() {
    this.sendKeys("[name='passwd']", pwd);
    this.click("[type='submit']");
    console.log("login 2");
    this.capture("./img/1.png")

});

casper.wait(5000,function () {
    casper.echo("wait 3s")
    this.capture("./img/2.png")
})

// casper.thenOpen('https://outlook.live.com/owa/')

// casper.wait(10000,function () {
//     this.capture("./img/3.png")
//     var cookies = JSON.stringify(phantom.cookies);
//     var fs = require('fs');
//     fs.write("./cookie/"+userName, cookies, "w");
//     console.log("login sucess");
//
// })

casper.thenOpen('https://outlook.live.com/owa/?path=/mail/inbox',function () {
    casper.echo(2)
})

casper.wait(10000,function () {
    this.capture("./img/4.png")
    console.log("looked");
    this.evaluate(function (getElementByContent) {
        getElementByContent("span","Verify your Apple ID")[0].click()
    },getElementByContent)
})

casper.wait(3000,function () {
    this.capture("./img/5.png")
    console.log("click");
    this.evaluate(function (getElementByContent) {
        return getElementByContent("a","Verify")[0].click()
    },getElementByContent)
})

casper.wait(5000,function () {
    this.capture("./img/6.png")
    console.log("over");
})

casper.run();
```

**Comment by Vitallium** [comment]
Could you please try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads)? Thanks!

**Comment by noinlijin** [comment]
@Vitallium  hi  I had try with 2.5 , phantomJs crash again

**Comment by noinlijin** [comment]
[this is the code](https://gist.githubusercontent.com/noinlijin/e2f3734209434bd495fd9f42adc7b530/raw/6b1af5d8c5b11adf3c96507d6e56deaebc31f4f9/hotmail.js)

**Comment by ak120684** [comment]
I am seeing this issue almost every day, while running tests on our CI server - which is a linux 64 bit server.
I noticed this error occurs intermittently, and almost all times, it is thrown during a click() event or while opening a page.

*** Error in `/usr/local/phantomjs-2.1.1-linux-x86_64/bin/phantomjs': double free or corruption (out): 0x00007f8f2000eef0 ***

I checked the phantomjsdriver code here - https://github.com/codeborne/ghostdriver/blob/master/binding/java/src/main/java/org/openqa/selenium/phantomjs/PhantomJSCommandExecutor.java

line # 88 is where the error is thrown...but my concern is, its not consistent. it is intermittent.

Need help please. It is everyday thing now, and it gives false negatives.

**Comment by dx-pbuckley** [comment]
@Vitallium does this still need reproduction, or should that label get removed? Seems like @noinlijin shared a couple ways to repro, and confirmed it happens with both 2.1.1 and 2.5. Or is there more needed?

**Comment by Vitallium** [comment]
@dx-pbuckley I am so sorry! I misses the reply from @noinlijin I will have a look into it ASAP.

**Comment by lunny** [comment]
```
1   000000014147AE00
2   000000014147243D
3   0000000141472301
4   000000014147759E
5   00000001410887EB
6   0000000077315F26
7   00000000770C5D7A
8   0000000141707693
9   0000000141088780
10  0000000140F70348
11  0000000140FB14B6
12  0000000140FAF07B
13  000000014041074D
14  000000014096B29E
15  0000000140909785
16  000000013FAF8E40
17  000000013FACDF01
18  000000013FAC9269
19  000000013FAA155F
20  000000013FAA1782
21  000000013FA989B2
22  000000013FA99772
23  000000013FA8ABCC
24  000000013FA8AC48
25  00000001417089C9
26  00000000770D59ED
27  000000007730B371
Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
```

**Comment by Jing19** [comment]
It also happens to me lately, do we know how can we fixed it asap? 
I am using casperjs v1.1.3 and phantomjs-prebuilt v2.1.7. The operation system is macOS Sierra v10.12.5.
It start running few tests cases and just crashed as following after few more steps:
# Log in to the platform...
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

**Comment by PatrickMcGuire176** [comment]
@lunny 

Newbie here:  

I have also received Fatal Windows Exception, code 0xc0000005 while running simple web scraping program using 2.1.1.  

To workaround this, I catch UnreachableBrowserException and redeclare the webdriver. 

Let me know if I should provide more information.

**Comment by christian-draeger** [comment]
@PatrickMcGuire176 
do you have a small example where / how to catch the UnreachableBrowserException and redeclare the webdriver

**Comment by PatrickMcGuire176** [comment]
All I did was below.  I haven't seen the issue since in a program that I run 5 days a week for ~4 hours a day.  Seemed to solve the issue for me.  I did try to test by explicitly throwing unreachablebrower, but, for whatever reason, that blew up the statement

catch (UnreachableBrowserException e) {
                    System.out.println(e);
                    driver = new PhantomJSDriver(caps);
}

**Comment by lunny** [comment]
I have resolved my issue via send a PR to a go project https://github.com/benbjohnson/phantomjs/pull/3

**Comment by luolizhi** [comment]
i have this problem when i run my code on centos, it's ok on windows 10.

here is the log, the program is still running ,  anybody know how to fixed it.

`*** Error in `phantomjs': double free or corruption (!prev): 0x0000000005f04a80 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c503)[0x7f5d18307503]
phantomjs[0x223059c]
phantomjs[0x2228cb3]
phantomjs[0x17dc868]
phantomjs[0x17d555b]
phantomjs[0x17d76a9]
phantomjs[0x17d8561]
phantomjs[0x17d87d1]
phantomjs[0x17d5da8]
phantomjs[0x17c22ea]
phantomjs[0xa0978b]
phantomjs[0xb4b971]
phantomjs[0xb530d1]
phantomjs[0xb55369]
phantomjs[0xb5d41a]
phantomjs[0xb5ba52]
phantomjs[0xb5bca6]
phantomjs[0xc8f0e2]
[0x7f5cd13360e5]
======= Memory map: ========
00400000-042c9000 r-xp 00000000 fd:01 534798                             /usr/local/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
044c8000-046c9000 rwxp 03ec8000 fd:01 534798                             /usr/local/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
046c9000-0470b000 rwxp 00000000 00:00 0 
056a7000-06008000 rwxp 00000000 00:00 0                                  [heap]
7f5c82db7000-7f5c82dc0000 ---p 00000000 00:00 0 
7f5c82dc0000-7f5c82dd0000 rwxp 00000000 00:00 0 
7f5c82dd0000-7f5c82de0000 ---p 00000000 00:00 0 
7f5c82de0000-7f5c82df0000 rwxp 00000000 00:00 0 
7f5c82df0000-7f5c82e00000 ---p 00000000 00:00 0 
7f5c82e00000-7f5c82e10000 rwxp 00000000 00:00 0 
7f5c82e10000-7f5c82e20000 ---p 00000000 00:00 0 
7f5c82e20000-7f5c82e30000 rwxp 00000000 00:00 0 
7f5c82e30000-7f5c82e40000 ---p 00000000 00:00 0 
7f5c82e40000-7f5c82e50000 rwxp 00000000 00:00 0 
7f5c82e50000-7f5c82e60000 ---p 00000000 00:00 0 
7f5c82e60000-7f5c82e70000 rwxp 00000000 00:00 0 
7f5c82e70000-7f5c82e80000 ---p 00000000 00:00 0 
7f5c82e80000-7f5c82ea0000 rwxp 00000000 00:00 0 
7f5c82ea0000-7f5c82eb0000 ---p 00000000 00:00 0 
7f5c82eb0000-7f5c82ec0000 rwxp 00000000 00:00 0 
7f5c82ec0000-7f5c82ed0000 ---p 00000000 00:00 0 
7f5c82ed0000-7f5c82ee0000 rwxp 00000000 00:00 0 
7f5c82ee0000-7f5c82ef0000 ---p 00000000 00:00 0 
7f5c82ef0000-7f5c82f00000 rwxp 00000000 00:00 0 
7f5c82f00000-7f5c82f10000 ---p 00000000 00:00 0 
7f5c82f10000-7f5c82f20000 rwxp 00000000 00:00 0 
7f5c82f20000-7f5c82f30000 ---p 00000000 00:00 0 
7f5c82f30000-7f5c82f40000 rwxp 00000000 00:00 0 
7f5c82f40000-7f5c82f50000 ---p 00000000 00:00 0 
7f5c82f50000-7f5c82f60000 rwxp 00000000 00:00 0 
7f5c82f60000-7f5c82f70000 ---p 00000000 00:00 0 
`
