### ISSUE TITLE
new Date(new Date().toLocaleDateString()) return  Invalid Date

### ISSUE THREAD

**Issue by chaoren1641** [ariya/phantomjs#14763]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

> 2.1.1

2. What steps will reproduce the problem?
 

>  1.  new Date(new Date().toLocaleDateString())
>   2. return "Invalid Date"
>   3. chrome is ok

3. Which operating system are you using?

> mac os 10.12.2 (16C67)

4. Did you use binary PhantomJS or did you compile it from source?

> no

5. Please provide any additional information below.

> i am from china

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!

**Comment by akram1905** [comment]
Worked for me on 2.5 beta!

I was using `new Date().toLocaleDateString('nl-NL')` , expecting `'28-12-2017'` for example but was getting `'28 December 2017'` instead.
