### ISSUE TITLE
phantomjs 2.1.1 crash with simple code

### ISSUE THREAD

**Issue by tchwpkgorg** [ariya/phantomjs#14769]
I'm trying to migrate from phantomjs 1.9.8 to 2.1.1, unfortunately, it crashes.

I've removed all redundant code from my scripts - just a oneliner crashes phantomjs.

1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

```
# phantomjs --version
2.1.1
```

Downloaded from phantomjs website.

2. What steps will reproduce the problem?

```
$ echo "Object.defineProperty(Date.prototype, 'startOfLastWeek', {});" > phantomcrash.js
$ phantomjs phantomcrash.js
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault
```
3. Which operating system are you using?

Reproducible on Ubuntu 14.04 and Ubuntu 16.04 (both 64 bit).

4. Did you use binary PhantomJS or did you compile it from source?

Binary provided on phantomjs website.

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!

**Comment by twalpole** [comment]
Date.prototype didn't become a normal object until ES6 - which 2.1.1 doesn't support, you can't use it with defineProperty.

**Comment by tchwpkgorg** [comment]
@Vitallium: I would, if it worked!

This is what happens if I attempt to run phantomjs from phantomjs-2.5.0-beta-linux-ubuntu-trusty-x86_64.tar.gz on Ubuntu Trusty (14.04):

```
# ./phantomjs
./phantomjs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./phantomjs)
./phantomjs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./phantomjs)
./phantomjs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./phantomjs)
./phantomjs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./phantomjs)

```


I've tried compiling the latest version from the master, with little success.

**Comment by tchwpkgorg** [comment]
@twalpole - are you sure? I did not crash phantomjs 1.9.8. It does crash phantom 2.1.1, which is a stable version - so looks like regression to me.

We use it extensively in our code working with 1.9.8 (which unfortunately has numerous issues with SSL/SNI).

**Comment by twalpole** [comment]
@tchwpkgorg 100% sure the prototype didn't become a regular object until ES6, Mostly sure on the rest -- it might not crash 1.9.8 but is it working the way you expect it to in 1.9.8?

**Comment by tchwpkgorg** [comment]
@Vitallium - could you add phantomjs 2.5 binary which actually works on Ubuntu Trusty (14.04)?

**Comment by Vitallium** [comment]
@tchwpkgorg what version of GLIBC is installed on your OS? And write the exact Ubuntu version. I built binaries on 14.04.5

**Comment by tchwpkgorg** [comment]
```
# dpkg -l|grep libc6
ii  libc6:amd64                              2.19-0ubuntu6.9                   amd64        Embedded GNU C Library: Shared libraries
ii  libc6-dev:amd64                          2.19-0ubuntu6.9                   amd64        Embedded GNU C Library: Development Libraries and Header Files

# cat /etc/issue
Ubuntu 14.04.5 LTS \n \l

```

**Comment by Vitallium** [comment]
Hhm. I have the same here in my VM:

```
vitaly@ubuntu ~/p/bin> dpkg -l|grep libc6
ii  libc6:amd64                        2.19-0ubuntu6.9                   amd64        Embedded GNU C Library: Shared libraries
ii  libc6-dev:amd64                    2.19-0ubuntu6.9                   amd64        Embedded GNU C Library: Development Libraries and Header Files
```

```
vitaly@ubuntu ~/p/bin> cat /etc/issue
Ubuntu 14.04.5 LTS \n \l
```

**Comment by tchwpkgorg** [comment]
So I've installed libraries phantom 2.5 depends on and:

```
# apt-get install libxslt1.1 libhyphen0 libwebp5

# wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.5.0-beta-linux-ubuntu-trusty-x86_64.tar.gz

# tar xpf phantomjs-2.5.0-beta-linux-ubuntu-trusty-x86_64.tar.gz

# phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs
phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs)
phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs)
phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs)
phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs)

# echo $?
1
```


Tested with default Ubuntu 14.04 kernel:

```
# uname -a
Linux build01.sys.timedoctor.com 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Also tested it with a ppa kernel:

```
# uname -a
Linux www.timedoctortest.com 4.9.0-040900-generic #201612111631 SMP Sun Dec 11 21:33:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

But it's not a kernel mismatch - it's library mismatch.

**Comment by Vitallium** [comment]
Ah. yes. I guess you need to install newer version of GLIBC (which comes with GCC 5).

**Comment by tchwpkgorg** [comment]
This libc is already the latest available for Ubuntu 14.04. 

Also, gcc-5 is not available in Ubuntu 14.04 repositories.

**Comment by Vitallium** [comment]
@tchwpkgorg are you sure?
```
vitaly@ubuntu ~> sudo apt-cache show gcc-5
Package: gcc-5
Priority: optional
Section: devel
Installed-Size: 21632
Maintainer: Ubuntu Core developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 5.4.1-2ubuntu1~14.04
Recommends: libc6-dev (>= 2.13-0ubuntu6)
Replaces: gcc-5-base (<< 5-20150329-1), gcc-5-plugin-dev (<< 5-20150321-1), gccgo-5 (<< 5.4.1-2ubuntu1~14.04)
Suggests: gcc-5-multilib, gcc-5-doc (>= 5.4.0-6), gcc-5-locales (>= 5.4.0-6), libgcc1-dbg (>= 1:5.4.1-2ubuntu1~14.04), libgomp1-dbg (>= 5.4.1-2ubuntu1~14.04), libitm1-dbg (>= 5.4.1-2ubuntu1~14.04), libatomic1-dbg (>= 5.4.1-2ubuntu1~14.04), libasan2-dbg (>= 5.4.1-2ubuntu1~14.04), liblsan0-dbg (>= 5.4.1-2ubuntu1~14.04), libtsan0-dbg (>= 5.4.1-2ubuntu1~14.04), libubsan0-dbg (>= 5.4.1-2ubuntu1~14.04), libcilkrts5-dbg (>= 5.4.1-2ubuntu1~14.04), libmpx0-dbg (>= 5.4.1-2ubuntu1~14.04), libquadmath0-dbg (>= 5.4.1-2ubuntu1~14.04)
Provides: c-compiler
Depends: cpp-5 (= 5.4.1-2ubuntu1~14.04), gcc-5-base (= 5.4.1-2ubuntu1~14.04), libcc1-0 (>= 5.4.1-2ubuntu1~14.04), binutils (>= 2.24), libgcc-5-dev (= 5.4.1-2ubuntu1~14.04), libc6 (>= 2.15), libgcc1 (>= 1:3.0), libgmp10, libisl15 (>= 0.15), libmpc3, libmpfr4 (>= 3.1.3), libstdc++6 (>= 4.1.1), zlib1g (>= 1:1.1.4)
Filename: pool/main/g/gcc-5/gcc-5_5.4.1-2ubuntu1~14.04_amd64.deb
Size: 6596270
MD5sum: 86c645e86a042e3fa38ad9ddc504abcc
SHA1: 9deb0fd8004c6a9cfbecaa6c90fc78cc3ee71531
SHA256: 9759ff001c644ff3fe38b2843350d28f11939ee1d4e87c0a69b4e9f42b1f8452
Description-en: GNU C compiler
 This is the GNU C compiler, a fairly portable optimizing compiler for C.
Description-md5: 394374e688b1afb3af5f419895d29698
Original-Maintainer: Debian GCC Maintainers <debian-gcc@lists.debian.org>
```

**Comment by tchwpkgorg** [comment]
Pretty much sure.

gcc-5 comes with Ubuntu versions after 14.04. It seems you may have some nonstandard repositories added, or installed gcc-5 from a newer Ubuntu distribution.

Seems you have gcc-5 from Ubuntu 16.10:

http://packages.ubuntu.com/search?keywords=gcc-5


On default Ubuntu 14.04 installation:

```
# apt-cache show gcc-5
N: Unable to locate package gcc-5
E: No packages found
```

**Comment by Vitallium** [comment]
@tchwpkgorg ouch. Interesting.. Ok, I'll have a look into it. Thanks!

**Comment by oleghind** [comment]
This helped me solving the same issue:  
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test  
sudo apt-get update
sudo apt-get install gcc-4.9 g++-4.9
```

**Comment by tchwpkgorg** [comment]
By the way phantomjs 2.1.1 also crashes on the same piece of code:

`$ echo "Object.defineProperty(Date.prototype, 'startOfLastWeek', {});" > phantomcrash.js
$ phantomjs phantomcrash.js
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault
$ phantomjs --version
2.1.1
`

**Comment by lewsid** [comment]
Ran into the same error attempting to run PhantomJS on Ubuntu 14.04.5 LTS on a freshly provisioned AWS instance. @oleghind's fix worked for me.
