### ISSUE TITLE
Browser Crashing 

### ISSUE THREAD

**Issue by PratheepV** [ariya/phantomjs#14764]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  while running ember acceptance test

3. Which operating system are you using?
 Ubuntu

4. Did you use binary PhantomJS or did you compile it from source?
 Binary

5. Please provide any additional information below.

[PhantomJS] error
     Error: Browser exited unexpectedly
Stderr: 
 1   0x1b67967 /home/travis/build/sample_app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1b67967]
2   0x1baac35 /home/travis/build/sample_app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1baac35]
3   0x1b9369c /home/travis/build/sample_app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1b9369c]
4   0x18970ad /home/travis/build/sample_app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x18970ad]
5   0x1896ace /home/travis/build/sample_app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1896ace]
6   0x1896ddf /home/travis/build/sample_app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x1896ddf]
7   0x19c4b28 /home/travis/build/sample_app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs() [0x19c4b28]
8   0x7f6159e9d6d5 [0x7f6159e9d6d5]
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

**Comment by gokatz** [comment]
+1

**Comment by FutoRicky** [comment]
+1
