### ISSUE TITLE
2.5-beta: console.log only logs first argument when used with multiple arguments.

### ISSUE THREAD

**Issue by sdeprez** [ariya/phantomjs#14765]
Not a very serious bug with easy workaround (use `+`), but just to let you know.

1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.5.0-development

2. What steps will reproduce the problem?
  1. Create a simple file script
```
console.log('Hello', 'world!', 'and some extra string');
phantom.exit()
```

  2. Run it.
  3. See the output truncated to the first argument `Hello`

3. Which operating system are you using?
Ubuntu 15.10

4. Did you use binary PhantomJS or did you compile it from source?
Binary downloaded here https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.5.0-beta-linux-ubuntu-xenial-x86_64.tar.gz

5. Please provide any additional information below.
The script works fine with binary phantom 2.1.1

Thanks!

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.
