### ISSUE TITLE
Performance issuse, very slow loading website.

### ISSUE THREAD

**Issue by waza123x** [ariya/phantomjs#14768]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
* v2.1.1

2. What steps will reproduce the problem?
* run 21 instance of phantomjs.exe test.js (where test is just opening any page)

3. Which operating system are you using?
* win7 64bit , 64gb ram, 32 cores.

4. Did you use binary PhantomJS or did you compile it from source?
* binary.

5. Please provide any additional information below.

The problem is with performance

if you start one instance of phantomjs.exe it will load website in ~10 seconds.
if you run 21 instances of phantomjs.exe any of instance will load website in ~60 seconds.

BUT
if you run website in browser chrome/firefox , it will load website in 3 seconds (while 21 instances of phantomjs is running)

Whats wrong, how this bug can be fixed ?

thanks

p.s. If you run code with just only console.log("hello world") while 21 instance is running, the code of hello world will be executed in 3 sec, But .open() website will be executed in 60 sec.

p.s.s. If you run open() with "about:blank" its loading 3 secs.

**Comment by waza123x** [comment]
fuck yes i found the answer to problem !

Just launch instances with this parameter:

--proxy-type=none

and all 21 instances all running now 3-7 seconds.

Peace!

**Comment by Vitallium** [comment]
>possible its using windows api like internet explorer to get proxy automatically, but somehow it is not multi thread..

Exactly! By default Qt uses system proxy on Windows. This slows down the network performance a bit.
