### ISSUE TITLE
Web fonts stopped working

### ISSUE THREAD

**Issue by smagnetize** [ariya/phantomjs#14760]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?

google-font.svg:
```
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200">
  <style>@import url(https://fonts.googleapis.com/css?family=Pacifico);</style>
  <text x="10" y="20" font-family="Pacifico">Pacifico Font</text>
</svg>

```
google-font.js:
```
var webPage = require('webpage');
var page = webPage.create();

page.open("google-font.svg", function start(status) {
  page.render('google-font.png', {format: 'png', quality: '100'});
  phantom.exit();
});
```
Expected: output image renders webfont
Actual: default font is used

3. Which operating system are you using?
Windows 2008, Windows 10
4. Did you use binary PhantomJS or did you compile it from source?
binary
5. Please provide any additional information below.
  - It works on 2.5.0-development
  - Our setup was working fine and then it seemed to just stop working, perhaps second half of December to beginning of January.
  - Doesn't work on 2.0.

**Comment by Vitallium** [comment]
Hi! Thanks for reporting. But I am not sure what's the point of this issue? Could you please elaborate?

**Comment by smagnetize** [comment]
font-face just seems to not work anymore, so it renders the default font instead of the custom font

**Comment by pbb72** [comment]
Possible duplicate: #14885
