### ISSUE TITLE
 Captured image are looks are different Image rendering issue

### ISSUE THREAD

**Issue by Sunil-Cube** [ariya/phantomjs#14779]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
	PhantomJS  - 2.1.1
	Python - 2.7
	selenium - 3.0

2. What steps will reproduce the problem?
 I was capture url for example :"http://www.bjs.com/office.category.3000000000000116959.2000134" thru tool of "python + selenium + phantoms" .
 Captured image are looks are different, like product parts are in vertical manner .
 
3. Which operating system are you using?
   Ubuntu 16.04

Thanks and please advise,

**Comment by Sunil-Cube** [comment]
![001 full_page](https://cloud.githubusercontent.com/assets/7599784/22287839/643a4aea-e31a-11e6-8546-7c41c0bab9de.jpg)

**Comment by Sunil-Cube** [comment]
![001 full_page](https://cloud.githubusercontent.com/assets/7599784/22287940/cdfad4ae-e31a-11e6-8c67-6af57e5b5fbd.jpg)

**Comment by Sunil-Cube** [comment]
Render thru Google Chrome : 
![render thru google chrome](https://cloud.githubusercontent.com/assets/7599784/22288167/b00f04a0-e31b-11e6-9426-f5901f904f0e.png)

**Comment by trista00** [comment]
I also met the same problem, can you solve it?

**Comment by trista00** [comment]
I also met the same problem, can you solve it?
