### ISSUE TITLE
Multiple scripts 

### ISSUE THREAD

**Issue by SvyrydovAndrey** [ariya/phantomjs#14771]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1. Run in the same time many casperjs scripts
3. Which operating system are you using?
Ubuntu 14.04
4. Did you use binary PhantomJS or did you compile it from source?
Source
5. Please provide any additional information below.
If I have run many casperjs scripts in the same time, around 50 copies with different names and different cookies files. First few scripts works fast and take 100-150 seconds - it is normal.  But then other scripts take more time and more, like 1000 seconds. Help me please. What I do wrong ?

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
