### ISSUE TITLE
how can phontomjs run on IBM aix5?

### ISSUE THREAD

**Issue by vencher** [ariya/phantomjs#14772]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.master

2. What steps will reproduce the problem?
  1.Running on IBM  aix5

3. Which operating system are you using?
IBM  aix5

4. Did you use binary PhantomJS or did you compile it from source?
no

**Comment by ariya** [comment]
Due to our limited resources, for the near future I believe the official binaries will only support x86 arch.
We will reopen this and revisit the subject in the future if other architectures will be supported. Thank you!
