### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'p.parentNode')

### ISSUE THREAD

**Issue by TibZz** [ariya/phantomjs#14770]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
 2.1.1
2. What steps will reproduce the problem?
               phantomjs assets\speaky.lite.min.js

3. Which operating system are you using?
  Windows 10
4. Did you use binary PhantomJS or did you compile it from source?
From source
5. Please provide any additional information below.

When I type 'phantomjs assets\speaky.lite.min.js', I get this error "TypeError: undefined is not an object (evaluating 'p.parentNode')".  Everything works fine when I don't use minified javascript files and I get this error only with this web navigator.

Thank you in advance.

**Comment by twalpole** [comment]
What is speaky.lite.min.js ?

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
