### ISSUE TITLE
Cannot declare a parameter named 'b'  in strict mode

### ISSUE THREAD

**Issue by SimplyLinn** [ariya/phantomjs#14778]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   x86_64
   2.1.1

2. What steps will reproduce the problem?
   `phantomjs> (function (){'use strict';console.log('hi');var a = function b (b) {};})();`

3. Expected result
   `hi`

4. Actual result
   `Cannot declare a parameter named 'b'  in strict mode`

5. Which operating system are you using?
```
$ lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux unstable (sid)
Release:	unstable
Codename:	sid
```
AND
```
$ lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie
```
6. Did you use binary PhantomJS or did you compile it from source?
Binary release

7. Please provide any additional information below.
  For some reason, phantom JS fails to scope the parameters or something to a named function which have a parameter with the same name. This issue is not present in any other JS-engine I've encountered (Chrome, Node, Firefox). This issue is also not present if I do not assign the named function to a variable. I.e use `function b(b){}` rather than `var a = function b(b){}`. It works as intended in non-strict mode.

```
phantomjs> (function (){'use strict';console.log('hi');function b (b) {};})();
hi
undefined
phantomjs> (function (){'use strict';console.log('hi');var a = function b (b) {};})();
Cannot declare a parameter named 'b'  in strict mode

  phantomjs://repl-input:1 in global code
```

**Comment by MrOpposite** [comment]
I should add, that this is for any arbitrary name on `b`, as long as the function name and argument is the same, this bug is present.

**Comment by Orekhov** [comment]
+1
Same issue happens for me.

**Comment by twalpole** [comment]
This was a bug in Webkit that was fixed about a year ago (and also affects any versions of Safari more than a year old) -  PhantomJS 2.1.1 uses a much older version of Webkit than that and therefore has the bug.  Not much PhantomJS can do about it, until the 2.5 release.
