### ISSUE TITLE
PhantomJS webdriver in Selenium error code -6

### ISSUE THREAD

**Issue by rwalid** [ariya/phantomjs#14775]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  from selenium import webdriver
  driver = webdriver.PhantomJS()

3. Which operating system are you using?
Ubuntu 16.04.1 LTS

4. Did you use binary PhantomJS or did you compile it from source?
binary PhantomJS

5. Please provide any additional information below.
Here is my full question on StackOverflow:
http://stackoverflow.com/questions/41793401/phantomjs-webdriver-error-code-6

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
