### ISSUE TITLE
Webdriver navigation not waiting for page to load

### ISSUE THREAD

**Issue by folbricht** [ariya/phantomjs#14788]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
`2.5.0-development` (beta)

2. What steps will reproduce the problem?
   1. Start with --webdriver=PORT
   2. Create a session
   3. Navigate to any page

3. Which operating system are you using?
OSX El Capitan

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
When using webdriver to navigate to a any page, it returns immediately and does not wait for the page to load. See the log below, it return right away with `200 OK`.

```
[selenium] 19:30:55.033110 -> POST http://localhost:64775/wd/hub/session/3ea2cbd0-e75d-11e6-bff1-83a772b564ee/url [33 bytes]
[selenium] 19:30:55.033228 -> TRACE
POST /wd/hub/session/3ea2cbd0-e75d-11e6-bff1-83a772b564ee/url HTTP/1.1
Host: localhost:64775
Accept: application/json
Content-Type: application/json

{"url":"https://www.google.com/"}
[selenium] 19:30:55.047012 <- TRACE
HTTP/1.1 200 OK
Content-Length: 74
Cache: no-cache
Content-Type: application/json;charset=UTF-8

{"sessionId":"3ea2cbd0-e75d-11e6-bff1-83a772b564ee","status":0,"value":{}}
[selenium] 19:30:55.047036 <- 200 OK ([application/json;charset=UTF-8]) [74 bytes
```

**Comment by jesg** [comment]
@folbricht the behaviour around `Webpage::loading` changed in 2.5-beta.  it no longer returns `true` immediately after you start loading a page.

**Comment by folbricht** [comment]
This issue appears to be addressed in https://github.com/ariya/phantomjs/pull/14849
