### ISSUE TITLE
PhantomJS is crashing on PayPal checkout site

### ISSUE THREAD

**Issue by husirap** [ariya/phantomjs#14781]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
 1.3.0

2. What steps will reproduce the problem?
I try to test a web shop checkout process that is using PayPal as payment provider. When I access the PayPal checkout page and try to login, the browser is crashing.
I just fill in the credentials and click on the login button.
I run this test on a Atlassian Bamboo build server. What is a bit weird is the fact that if I run the same test in my local IDE it works fine!
First I thought, that I probably have to increase the memory, but I do not exactly know if this change really has an effect as the browser was still crashing. I set the following: JAVA_OPTS=-Xms2048m -Xmx2048m

3. Which operating system are you using?
CentOS Linux release 7.3.1611 

4. Did you use binary PhantomJS or did you compile it from source?
Binary downloaded from Maven repo.

5. Please provide any additional information below.
[build_crash.dmp.zip](https://github.com/ariya/phantomjs/files/732316/build_crash.dmp.zip)

**Comment by sahaviev** [comment]
I think that paypal have protection from PhantomJS automatization tool. PhantomJS not suitable for this goals.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
