### ISSUE TITLE
SyntaxError: Unexpected token ',' - But it's valid JavaScript

### ISSUE THREAD

**Issue by meenie** [ariya/phantomjs#14797]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?

I'm getting this error with the following code example:
```coffeescript
export default Ember.Component.extend
  content: (->
    [@get('min')..@get('max')] if @get('min') && @get('max')
  ).property('min', 'max')
  hasSelection: Ember.computed.notEmpty('selectedOption')
```

Which generates the following javascript:
```javascript
export default Ember.Component.extend({
  content: (function() {
    var i, ref, ref1, results;
    if (this.get('min') && this.get('max')) {
      return (function() {
        results = [];
        for (var i = ref = this.get('min'), ref1 = this.get('max'); ref <= ref1 ? i <= ref1 : i >= ref1; ref <= ref1 ? i++ : i--){ results.push(i); }
        return results;
      }).apply(this);
    }
  }).property('min', 'max'),  // <-- This is the comma that PhantomJS has an issue with...
  hasSelection: Ember.computed.notEmpty('selectedOption')
});
```

3. Which operating system are you using? Mac OS X El Capitan

4. Did you use binary PhantomJS or did you compile it from source? Binary

When running the above code through PhantomJS, it complains about the comma after the `.property('min', 'max'),`.  There is nothing wrong with this syntax as far as I'm aware.

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!

**Comment by ariya** [comment]
Modern JavaScript features (from ES6/ES2015 or later) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
