### ISSUE TITLE
Angle brackets are erroneously escaped in content of noscript tags

### ISSUE THREAD

**Issue by mrog** [ariya/phantomjs#14795]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  2.1. Use PhantomJS to view the content of https://www.amazon.com.  This script will work:
```
var page = require('webpage').create();
page.open('https://www.amazon.com', function(status) {
  console.log("Status: " + status);
  if(status === "success") {
    console.log(page.content);
  }
  phantom.exit();
});
```

Result: The content contains escaped angle brackets (&lt; and &gt;) that should not be escaped.  This is an excerpt from the PhantomJS output:
```
<!--[if gt IE 6]--><noscript>&lt;![endif]&gt;
&lt;style type="text/css"&gt;&lt;!--
  #navbar #nav-shop .nav-a:hover {
    color: #ff9900;
    text-decoration: underline;
  }
  #navbar #nav-search .nav-search-facade,
  #navbar #nav-tools .nav-icon,
  #navbar #nav-shop .nav-icon,
  #navbar #nav-subnav .nav-hasArrow .nav-arrow {
    display: none;
  }
  #navbar #nav-search .nav-search-submit,
  #navbar #nav-search .nav-search-scope {
    display: block;
  }
  #nav-search .nav-search-scope {
    padding: 0 5px;
  }
  #navbar #nav-search .nav-search-dropdown {
    position: relative;
    top: 5px;
    height: 23px;
    font-size: 14px;
    opacity: 1;
    filter: alpha(opacity = 100);
  }
--&gt;&lt;/style&gt;
&lt;![if gt IE 6]&gt;</noscript><!--[endif]-->
```

Here's the same piece of HTML as downloaded by Firefox or Chrome:
```
<![if gt IE 6]><noscript><![endif]>
<style type="text/css"><!--
  #navbar #nav-shop .nav-a:hover {
    color: #ff9900;
    text-decoration: underline;
  }
  #navbar #nav-search .nav-search-facade,
  #navbar #nav-tools .nav-icon,
  #navbar #nav-shop .nav-icon,
  #navbar #nav-subnav .nav-hasArrow .nav-arrow {
    display: none;
  }
  #navbar #nav-search .nav-search-submit,
  #navbar #nav-search .nav-search-scope {
    display: block;
  }
  #nav-search .nav-search-scope {
    padding: 0 5px;
  }
  #navbar #nav-search .nav-search-dropdown {
    position: relative;
    top: 5px;
    height: 23px;
    font-size: 14px;
    opacity: 1;
    filter: alpha(opacity = 100);
  }
--></style>
<![if gt IE 6]></noscript><![endif]>
```

3. Which operating system are you using?
OSX

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.
This appears to be an issue when HTML tags or comments are included as children of a noscript element.

**Comment by OlivierChirouze** [comment]
I do see the same behavior (same version)
Also I really can't manage to have `javascriptEnabled = false` working as I'd expect: wether it's `true` of `false` doesn't seem to make any difference?
Setting `javascriptEnabled = false`, I'd expect to:

1. don't see requests for elements that are dynamically added with Javascript => I **do** see them
2. see requests for elements included in `<noscript>` => I **don't** see them

Unless I'm missing something, there is something wrong with `javascriptEnabled`
