### ISSUE TITLE
Array.prototype.fill undefined

### ISSUE THREAD

**Issue by timhaley94** [ariya/phantomjs#14798]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
I'm running it through karma so I may need to check what phantomjs version it is. But here are my phantomjs related dependencies.

```javascript
{
    "karma": "1.1.0",
    "karma-phantomjs-launcher": "^1.0.0",
    "phantomjs-polyfill": "0.0.2",
    "phantomjs-prebuilt": "^2.1.4",
}
```

2. What steps will reproduce the problem?
Screenshots below show code that you can run and reproduce the problem.

3. Which operating system are you using?
OS X El Capitan 10.11.6

4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.
When Phantom was running my code I discovered that `Array.prototype.fill` is undefined. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

Not sure if this is because this method was added as a part of es6.

When I run:
<img width="456" alt="screen shot 2017-02-02 at 3 19 59 pm" src="https://cloud.githubusercontent.com/assets/14980932/22566919/d060f6f0-e95b-11e6-8af6-d2084f88f29e.png">

I get:
<img width="1187" alt="screen shot 2017-02-02 at 3 19 49 pm" src="https://cloud.githubusercontent.com/assets/14980932/22566922/d5c121a6-e95b-11e6-865c-4abf0cea2eae.png">

**Comment by twalpole** [comment]
PhantomJS 2.1.1 does not support ES5+ (it's basically equivalent to a 4-5 year old Safari).  If you want to use your code with PhantomJS 2.1.1 you'll need to transpile and polyfill any missing features.  You could also try using the PhantomJS 2.5.0 beta which will most likely provide the missing methods but has it's own issues at the moment (hence beta)

**Comment by ariya** [comment]
Correction:
PhantomJS 2.1 **does** support ES 5.1 (see e.g. https://ariya.io/2014/08/phantomjs-2-and-javascript-goodies).

`Array.prototype.fill` is part of ES2015 (also known as ES6). It will be supported from PhantomJS >= 2.5.

**Comment by twalpole** [comment]
@ariya Whoops - my error - fixed

**Comment by ariya** [comment]
Modern JavaScript features (from ES6/ES2015 or later) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
