### ISSUE TITLE
Query: PhantomJS 2.5 beta code for early evaluation.

### ISSUE THREAD

**Issue by asowani** [ariya/phantomjs#14796]
Hi,

Is it possible to get PhantomJS 2.5 beta code for testing and evaluation on ppc64le platform? I didn't find anything about it in the repository (branch/tag) etc. I would like to check this code on ppc64le for possible improvements related to latest qtwebkit code along with phantomjs code.

Thanks,
Atul.

**Comment by Vitallium** [comment]
AFAIK, Qt doesn't support ppc64 anymore. I suggest you to check Qt first for ppc64.

**Comment by ariya** [comment]
We can't do much here, please bring up your request to the Qt team: https://www.qt.io/.

**Comment by asowani** [comment]
@ariya Understood. So I checked up about this with the qt team and they advised to upgrade the qtwebkit version. PhantomJS 2.1.1 is using Qt 5.5.1 version. So my question is - which version of Qt is being used by PhantomJS 2.5? I would like to clone the 2.5 code and work on the qt code in that to make it work on ppc64le. With my experience so far, only one fix is required to make Qt work on ppc64le, which is about pagesize value change. I have this fix with me and with this, PhantomJS 2.1.1 (Qt 5.5.1) works okay on ppc64le save the above mentioned issues with CSS parser. So I have high hopes that PhantomJS 2.5 should work on ppc64le as well.

Thanks!

**Comment by asowani** [comment]
The discussion with Qt community is at https://lists.webkit.org/pipermail/webkit-dev/2017-February/028722.html
