### ISSUE TITLE
Rendered image shows an older version of Google Alerts. Changing the User Agents didn't work.

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#14790]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
    1. Run the script.
    2. Wait for the rendered images.
    3. Check the images to see the difference.

3. Which operating system are you using?
Xubuntu 16.04.1 LTS 64bits

4. Did you use binary PhantomJS or did you compile it from source?
I installed using `npm install -g phantomjs-prebuilt`

5. Please provide any additional information below.
I'm trying to use PhantomJS to create RSS feeds with Google Alerts. So far I'm able to enter in the name of the new alert and press "Show options" that's present on the website, to change to RSS. The issue is the version of the website that's rendered, it appears to be a very old version, when Google Alerts had not yet RSS options back:

![screenshot_2017-01-31_15-08-30](https://cloud.githubusercontent.com/assets/22737068/22455387/292c750c-e7c7-11e6-9415-a7af6ea2cb84.png)

If you access the website, fill up the field and click "Show options" you'll see an extra field above the button, which is "Deliver to", but it doesn't appear in the image.

I've posted a [question](http://stackoverflow.com/questions/41931302/why-is-phantomjs-showing-an-old-version-of-google-alerts) on StackOverflow, and the answer there, which is to change the `userAgent`, did not help me.

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!
