### ISSUE TITLE
Phantomjs handles flexbox

### ISSUE THREAD

**Issue by sowich** [ariya/phantomjs#14793]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
* Run the script, the screenshot of the page, but the flex items are not displayed on the destination screen!

3. Which operating system are you using?
Debian GNU/Linux 8

4. Did you use binary PhantomJS or did you compile it from source?
npm install -g phantomjs-prebuilt

**Comment by twalpole** [comment]
Try using the PhantomJS 2.5.0 beta -  2.1.1 is basically equivalent to a 4-5 year old version of Safari which was before flex box was standardized.

**Comment by attiks** [comment]
Manual work-around works, download from https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.5.0-beta-linux-ubuntu-xenial-x86_64.tar.gz and extract phantomjs to node_modules/phantomjs-prebuilt/bin/phantomjs

**Comment by attiks** [comment]
See also #14365

**Comment by ariya** [comment]
Modern web standards (including Flexbox, among others) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
