### ISSUE TITLE
ServerSideEvents (SSE) - using inside of phantomjs/mongoose

### ISSUE THREAD

**Issue by sameuser** [ariya/phantomjs#14801]
Hello. I trying to use SSE inside phantomjs.

	var system = require('system');
	var server = require('webserver').create();
	var $listenPort = 8081;

	var $service = server.listen($listenPort, function (request, response)  
	{
		response.statusCode = 200;
		response.setHeader('Content-Type', 'text/event-stream; charset=utf-8');
		response.setHeader('Access-Control-Allow-Origin', 'http://SomeWebSite.abc');
		response.setHeader('Access-Control-Allow-Credentials', 'true');
		response.setHeader('Connection', 'keep-alive');

		var $time = new Date().toLocaleTimeString();

		setInterval(function() //we send a chunks, for example, every 5 seconds
		{
			response.write('data: ' + $time + '\n\n');
		}, 5000); 
	});

Client-side script:

	<script>
	var EventSource = new EventSource("http://phantomJShost:8081/sse.htm", { withCredentials: true });
		EventSource.onopen = function(e) { console.log ('connection opened'); };
		EventSource.onerror = function(e) { console.log ('error : ' + + this.readyState); };
		EventSource.onmessage = function(e) { console.log(e); };
		//... other code
	</script>

So.. Expect to got a data:

message { target: EventSource, isTrusted: true, data: "5:28:17 AM GMT+08:00", origin: "http://phantomJShost:8081", lastEventId: "", currentTarget: EventSource, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1486416554899000 }

But.. Where is the problem?

The problem is next: browser (firefox) can receive a data chunk ONLY after i **stop the script** completely (phantomjs with CTRL+C in console) or ONLY if i send **response.close** right after response.write.

But connection must be opened.

How should be ? I think, there are missed mechanism to send a chunk. Maybe i need something like 

**response.send**? or **response.flush**? But there are no these methods in API.

Example from ASP is below ( ref.: http://www.w3schools.com/html/html5_serversentevents.asp ) :

	<%
	Response.ContentType = "text/event-stream"
	Response.Expires = -1
	Response.Write("data: The server time is: " & now())
	Response.Flush()
	%> 

phantomjs --version : 2.1.1 \ debian linux (downloaded binary)

**Comment by sameuser** [comment]
Anybody tried to use SSE in phantomJS ?

**Comment by sontek** [comment]
I'm also wondering if SSE works with PhantomJS.  I'm using selenium to test my webapp but PhantomJS fails to load the app if webpack hot module reloading is enabled (which uses SSE)

**Comment by sameuser** [comment]
Temporary solution:

		var $timeNow = new Date().toLocaleTimeString();
		response.write('data: ' + $timeNow + '\n\n');
		response.write('retry: ' + 1000 + '\n\n'); // reconnect time, msec
		response.close(); // should close it each time to trigger reconnect on client side
