### ISSUE TITLE
Navigating to relative url using location.href= is impossible in 2.5 beta.

### ISSUE THREAD

**Issue by crazyshot** [ariya/phantomjs#14802]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.5.0-development
2. What steps will reproduce the problem?
  evaluate JS `location.href = '/'` or `window.location = '/'`
  nothing happens
3. Which operating system are you using?
  MacOS Sierra
4. Did you use binary PhantomJS or did you compile it from source?
  Binary
5. Please provide any additional information below.
  Just checked again on 2.1.1 release, it works correctly there.
  `location.pathname = '/'` works correctly in 2.5

**Comment by Vitallium** [comment]
Yes, this is a known regression.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
