### ISSUE TITLE
Still memory issue is not fixed.

### ISSUE THREAD

**Issue by santosh-hegde** [ariya/phantomjs#14803]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1.Upload a file more than 1GB using phantomJs
 

3. Which operating system are you using?
Linux Redhat

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.

`((PhantomJSDriver) driver)
						.executePhantomJS("var page = this; var p=page.clearMemoryCache();console.log('memory Cleared');");`

I have been clearing the memory frequently and still phantomjs is crashing.

**Comment by Vitallium** [comment]
We cover this issue in https://github.com/ariya/phantomjs/issues/11390

**Comment by santosh-hegde** [comment]
When this will get released?

**Comment by Vitallium** [comment]
When it's ready.

**Comment by santosh-hegde** [comment]
Will it available in 2.5 ?

**Comment by Vitallium** [comment]
2.5 improved memory consumption mechanisms and it consumes less memory than 2.1 or 1.9. But we still have job to do.

**Comment by santosh-hegde** [comment]
Good to hear that.
2.5 Beta is asking lot of dependencies like libjpeg.so.8 etc. 
I'm using RedHat 7 and have latest libjpeg.so. So Can I build the binary which has all the dependecies?

So that user don't have to install anything extra.:-)
