### ISSUE TITLE
the size of generated pdf is too big after generating the pdf - how to fix it ? 

### ISSUE THREAD

**Issue by jpca999** [ariya/phantomjs#14807]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

± phantomjs --version
2.1.1

2. What steps will reproduce the problem?
  1. load the html on localhost:1313
  2.then run this command on terminal : 
phantomjs rasterize.js 'http://localhost:1313/html/contract.html' suhag.pdf
  3.

3. Which operating system are you using?
mac
4. Did you use binary PhantomJS or did you compile it from source?
i dont know. 
5. Please provide any additional information below.

heres the output  https://github.com/jpca999/phantom-contr-gen/blob/master/suhag.pdf

Required output pdf size :  

https://github.com/jpca999/phantom-contr-gen/blob/master/original%20/AS%20IS%20Residential%20Contract%20for%20Sale%20%20and%20Purchase.pdf

heres the code. 
https://github.com/jpca999/phantom-contr-gen

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
