### ISSUE TITLE
2.5.0 crashes on stdin/stdout use on Mac

### ISSUE THREAD

**Issue by jhy** [ariya/phantomjs#14806]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.5.0-development on OSX El Capitan 10.11.6

2. What steps will reproduce the problem?
  1. run `bin/phantomjs examples/stdin-stdout-stderr.js`

3. Which operating system are you using?
OSX El Capitan 10.11.6

4. Did you use binary PhantomJS or did you compile it from source?
Binary from beta download.

Had to use `brew install webp` to get it to run at all (which seems like a missing library in the static linking?)

5. Please provide any additional information below.

As soon as there's a write to stdout it crashes.

```
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault: 11
```

Aren't the examples used as part of build testing?

**Comment by jhy** [comment]
On the same machine, version `2.1.1` executes the same test correctly.

**Comment by oleghind** [comment]
2.5 crashes left and right, it's not stable enough yet

**Comment by Vitallium** [comment]
@oleghind do you have any script to reproduce your problem?

**Comment by oleghind** [comment]
@Vitallium you can try this code, it crashes on mac, ubuntu 14.04, ubuntu 16.04
```
var page = require('webpage').create();  
link = 'http://my.visme.co/projects/y4ye7x14-the-science-behind-the-most-popular-infographics-of-2016';  
page.open(link, function(status) {  
  if (status !== 'success') {  
    console.log('Unable to access network');  
  } else {  
    page.render('test.pdf');  
    phantom.exit();   
  }  
 });
```

**Comment by Vitallium** [comment]
@jhy works fine here:

```
vitaly at Vitalys-Mac in /Volumes/COFFEE/dev/phantomjs on master [?] ⇡
❯ bin/phantomjs examples/stdin-stdout-stderr.js                                                                                                          17:52
Hello, system.stdout.write!
Hello, system.stdout.writeLine!
Hello, system.stderr.write!
Hello, system.stderr.writeLine!
system.stdin.readLine():
^C⏎
vitaly at Vitalys-Mac in /Volumes/COFFEE/dev/phantomjs on master [?] ⇡
❯ ./bin/phantomjs --version                                                                                                                           6s 376ms
2.5.0-development
```

Could you please post the output of `otool -L bin/phantomjs`?

**Comment by clarkk** [comment]
@jhy how did you build master when there is no build.py file ?

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.

**Comment by autopaybyphone** [comment]
For those interested, a workaround, though not fully cross-platform, is to use the following:

    fs.read('/dev/stdin');

**Comment by vic-cw** [comment]
A potential workaround, though not cross-platform, is to use the following instead:

    fs.read('/dev/stdin');
