### ISSUE TITLE
can't execute phantomjs

### ISSUE THREAD

**Issue by SergiyPakholchak** [ariya/phantomjs#14805]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1. run ./phantomjs 
  2.
  3.

3. Which operating system are you using?
    3.14.51-grsec-pvops-xen-x64 GNU/Linux
4. Did you use binary PhantomJS or did you compile it from source?
   binary
5. Please provide any additional information below.

$ ./phantomjs screenshot.js uname -or
1   0x9a185f0 ./phantomjs() [0x9a185f0]
2   0x9a5b62d ./phantomjs() [0x9a5b62d]
3   0x981aff4 ./phantomjs() [0x981aff4]
4   0x9a41ddf ./phantomjs() [0x9a41ddf]
5   0x9a41f8b ./phantomjs() [0x9a41f8b]
6   0x981ac44 ./phantomjs() [0x981ac44]
7   0x96a5dff ./phantomjs() [0x96a5dff]
8   0x986d3f4 ./phantomjs() [0x986d3f4]
9   0x986dbfa ./phantomjs() [0x986dbfa]
10  0x9869103 ./phantomjs() [0x9869103]
11  0x986969d ./phantomjs() [0x986969d]
12  0x9971d15 ./phantomjs() [0x9971d15]
13  0x996c8e3 ./phantomjs() [0x996c8e3]
14  0x99501a3 ./phantomjs() [0x99501a3]
15  0x997a1c0 ./phantomjs() [0x997a1c0]
16  0x997ed6b ./phantomjs() [0x997ed6b]
17  0x95e2f98 ./phantomjs() [0x95e2f98]
18  0x95e35dd ./phantomjs() [0x95e35dd]
19  0x95e3751 ./phantomjs() [0x95e3751]
20  0x960c241 ./phantomjs() [0x960c241]
21  0x960c3b7 ./phantomjs() [0x960c3b7]
22  0x845edc5 ./phantomjs() [0x845edc5]
23  0x846014d ./phantomjs() [0x846014d]
24  0x846087c ./phantomjs() [0x846087c]
25  0x8460c8b ./phantomjs() [0x8460c8b]
26  0x845a5af ./phantomjs() [0x845a5af]
27  0x84373d5 ./phantomjs() [0x84373d5]
28  0x80c5f0d ./phantomjs() [0x80c5f0d]
29  0x807f212 ./phantomjs() [0x807f212]
30  0x80608c9 ./phantomjs() [0x80608c9]
31  0x805a66c ./phantomjs() [0x805a66c]
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault

Please help...

**Comment by Vitallium** [comment]
Can you post the output of the `ldd phantomjs` command?

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
