### ISSUE TITLE
Proxy is bypassed when requesting url on localhost network

### ISSUE THREAD

**Issue by GuilloOme** [ariya/phantomjs#14808]
1. Which version of PhantomJS are you using?
**2.1.1**

2. What steps will reproduce the problem?
  - set a proxy on localhost (like burp proxy)
  - run the command `$ phantomjs --proxy-type=http --proxy=127.0.0.1:8080 test.js` with the code:
  ```javascript
var page = require('webpage').create();

page.open('http://localhost/test.html', function () {});
  ```
  - no request has been logged in the proxy

3. Which operating system are you using?
**Ubuntu 16.04.1**

4. Did you use binary PhantomJS or did you compile it from source?
**binary from official repository**

5. Please provide any additional information below.
N/A

**Comment by elyscape** [comment]
This is a result of the following, from [the QNetworkProxy documentation][qnetworkproxy]:
>Network proxy is not used if the address used in connectToHost(), bind() or listen() is equivalent to QHostAddress::LocalHost or QHostAddress::LocalHostIPv6.

Looking through the source, there does not appear to be a way to disable this behavior.

[qnetworkproxy]: https://doc.qt.io/qt-5/qnetworkproxy.html#details
