### ISSUE TITLE
Phantomjs 2.1.1 on macOS Sierra 10.12.1 uses lots of memory

### ISSUE THREAD

**Issue by ambirag** [ariya/phantomjs#14804]
1. phantomjs version : 2.1.1 (mac)

2. What steps will reproduce the problem?
  1. We run around 3000+ js unit test using phantomjs using 1.9.8 but after upgrading to macOS Sierra, upgraded phantomjs to 2.1.1

3. Which operating system are you using? - macOS Sierra

4. Did you use binary PhantomJS  Binary PhantomJS

5. Everytime js unit tests are run in parallel (via gradlew), it consumes lots of memory, see attached screenshot
![image](https://cloud.githubusercontent.com/assets/1718620/22733785/2e2329e6-edeb-11e6-974e-5aed1c6f2e7d.png)

**Comment by Vitallium** [comment]
Duplicate. Please see #11390
