### ISSUE TITLE
Exception not such element

### ISSUE THREAD

**Issue by emy14** [ariya/phantomjs#14813]
I am using Xubuntu 16.10 and the last version of phantomJS 2.1 with nightwatch. My tests are running fine on firefox but not on phamtomJS. An element is not find present on the page. I tried to resize the windows, it resolve some problems but not all. I have got the exact same issue with chrome but it resolves when I put size 2000*1000.

**Comment by Vitallium** [comment]
Could you please combine a small sample to reproduce your problem?

**Comment by emy14** [comment]
On PhamtomJSDriver:

Executing: [click: 4 [[PhantomJSDriver: phantomjs on LINUX (aaf50c40-efa4-11e6-9082-1934f05b6cff)] -> css selector: div[data-reactid=".0.1.5:$column0.$MediaPage"]]])
16:22:04.707 WARN - Exception thrown
org.openqa.selenium.ElementNotVisibleException: {"errorMessage":"Element is not currently visible and may not be manipulated","request":{"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"27","Content-Type":"application/json; charset=utf-8","Host":"localhost:13343","User-Agent":"Apache-HttpClient/4.5.2 (Java/1.8.0_121)"},"httpVersion":"1.1","method":"POST","post":"{\"id\":\":wdc:1486740122110\"}","url":"/click","urlParsed":{"anchor":"","query":"","file":"click","directory":"/","path":"/click","relative":"/click","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/click","queryKey":{},"chunks":["click"]},"urlOriginal":"/session/aaf50c40-efa4-11e6-9082-1934f05b6cff/element/:wdc:1486740122110/click"}}


On FirefoxDriver: 

16:27:19.732 INFO - Executing: [click: 4 [[FirefoxDriver: firefox on LINUX (674f2301-3294-4da0-bd23-9e87107afb9d)] -> css selector: div[data-reactid=".0.1.0:$column0.$DispMediaPage"]]])
16:27:19.758 INFO - Done: [click: 4 [[FirefoxDriver: firefox on LINUX (674f2301-3294-4da0-bd23-9e87107afb9d)] -> css selector: div[data-reactid=".0.1.5:$column0.$DispMediaPage"]]]

**Comment by emy14** [comment]
I am going to see if I can find something simple to reproduce it
