### ISSUE TITLE
how to generate pdf from pdf with few changed contents  ?

### ISSUE THREAD

**Issue by jpca999** [ariya/phantomjs#14810]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2. What steps will reproduce the problem?
  1.
  2.
  3.

3. Which operating system are you using?

4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.

**Comment by Vitallium** [comment]
You can't do that. I suggest you to use other tools that can operate PDF files.

**Comment by jpca999** [comment]
okay, how about I somehow convert it to html, put that html in my filebase or database, then make changes to that html, load it and take the snapshot of it....   now the question is 
1) how can i create the html of the originial pdf - Ive tried that but they're not as perfect as i wanna see, do you know of any way to genrate high class html  off of original pdf ?

2) I have to generate these pdfs on batch bases, on after another in an application so  other tools wont work...

**Comment by Vitallium** [comment]
@jpca999 do you want to generate HTML from a PDF file? I doubt you can achieve the ideal result. When the page is being printed to a PDF, its content converts to a special PDF content, and some of this content will be lost.

**Comment by jpca999** [comment]
i want to dynamically generate filled  pdfs   ( this ->   https://goo.gl/OTMGt2
in a batch. one after another.  There has to be a way coz other people are doing it, using php...
