### ISSUE TITLE
Any errors inside the page.open() will cause a silent crash or hang.

### ISSUE THREAD

**Issue by maxupp** [ariya/phantomjs#14812]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
Using 2.1.1

2. What steps will reproduce the problem?

```
(function(){
    var page = require('webpage').create();
    page.open('about:blank', function(){
        SYNTAXERROR        
        console.log('test');
        phantom.exit();
    });
    page.onLoadFinished = function() {
       phantom.exit();}
}());
```

This minimal example demonstrates the behavior. It will finish without any console logging or errors. if the onLoadFinished handler is omitted, it will simply hang. Which makes debugging a nightmare.

3. Which operating system are you using?
Arch Linux

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.

**Comment by Vitallium** [comment]
This issue has been fixed in master and released in 2.5 beta version. Closing this issue because we have the tracking issue - 12973

**Comment by maxupp** [comment]
Nice, so i'll just compile the current version? Can't find a binary for 2.5 anywhere.

**Comment by Vitallium** [comment]
@maxupp yes or grab the 2.5 beta here https://bitbucket.org/ariya/phantomjs/downloads

**Comment by santosh-hegde** [comment]
Can you update the latest build in https://bitbucket.org/ariya/
phantomjs/downloads. It would be great if you upload the binary which
contains all libraries.

Thanks and Regards
Santosh Hegde
