### ISSUE TITLE
snyk test

### ISSUE THREAD

**Issue by knoxcard** [ariya/phantomjs#14815]
✗ Medium severity vulnerability found on request@2.67.0
- desc: Remote Memory Exposure
- info: https://snyk.io/vuln/npm:request:20160119
- from: node_services@1.0.0 > phantomjs@2.1.7 > request@2.67.0
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

✗ High severity vulnerability found on tough-cookie@2.2.2
- desc: ReDoS via long string of semicolons
- info: https://snyk.io/vuln/npm:tough-cookie:20160722
- from: node_services@1.0.0 > phantomjs@2.1.7 > request@2.67.0 > tough-cookie@2.2.2
No direct dependency upgrade can address this issue.
Run `snyk wizard` to explore remediation options.

**Comment by Vitallium** [comment]
??

**Comment by ariya** [comment]
@knoxcard Good report but wrong project. Please file it to https://github.com/Medium/phantomjs.
