### ISSUE TITLE
unproper svg rendering with overlapping text

### ISSUE THREAD

**Issue by dcballs** [ariya/phantomjs#14814]
Version 2.1.1 from binary on OSX 10.12.1

After rendering an c3.js graph, the legend is not properly rendered on a large zoomFactor.

![image](https://cloud.githubusercontent.com/assets/4049071/22841730/f185a24a-efd2-11e6-9792-2007ccd9bf1e.png)

Here is the script:

```javascript
page.zoomFactor = 4; 

var pageWidth = 1300 * page.zoomFactor; 
var pageHeight = 1300 * page.zoomFactor; 

page.viewportSize = { 
  width: pageWidth, 
  height: pageHeight 
}; 
return page.open(url, function(status) {
  page.render(outputDir + '/' + snapshotName);
});
```

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!
