### ISSUE TITLE
PhantomJS crashes while processing something like calc(100vh - 200px).

### ISSUE THREAD

**Issue by asowani** [ariya/phantomjs#14818]
Hi,

I am using PhantomJS 2.1.1 (built from cloned source, standard build procedure as given in docs). What I found was, PhantomJS crashes while processing CSS elements like height:calc(100vh - 200px)
This is an issue similar to the one discussed at http://stackoverflow.com/questions/27256849/it-is-possible-to-use-vh-minus-pixels-in-a-css-calc
I tried modifying my CSS the way given in the above thread, so the line looks like:
height:calc(100vh - 200px)
height:calc(~"100vh - 200px")
This seems to be working fine. So is this an issue with the CSS interpreter of PhantomJS?

Thanks,
Atul.

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!

**Comment by santosh-hegde** [comment]
@Vitallium  Can you update binaries @ bit bucket ?
