### ISSUE TITLE
inline-block + 0 height rendering issue

### ISSUE THREAD

**Issue by potatopeelings** [ariya/phantomjs#14817]
A phantomjs snapshot of a 0 height inline-block element differs from what you actually see in the browser.

1. Which version of PhantomJS are you using?
2.1.1

2. What steps will reproduce the problem?

**HTML**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <style type="text/css">
        a {
            display: inline-block;
            height: 0;
        }
    </style>
</head>
<body>
    <ul>
        <li>
            <a>abcd</a>
        </li>
    </ul>
</body>
</html>
```
**Phantomjs script**
```
var page = require('webpage').create();
page.open('file:///path/to/test.html', function(status) {
  if(status === "success") {
    page.render('example.png');
  }
  phantom.exit();
});
```
**Expected**
From Chrome Version 56.0.2924.87
![browser](https://cloud.githubusercontent.com/assets/300494/22871679/3e8ef394-f207-11e6-8430-ecedf05f1bdb.PNG)
**Actual** 
Notice that the content is almost one line below the li marker
![phantomjs](https://cloud.githubusercontent.com/assets/300494/22871761/280e1e8c-f208-11e6-8b03-aa97a0c3ab09.PNG)

3. Which operating system are you using?
Windows 7 Enterprise (64 bit)

4. Did you use binary PhantomJS or did you compile it from source?
Binary

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!

**Comment by potatopeelings** [comment]
Thanks! That fixed it. 

Do you want me to close this now, or after 2.5 is officially published?
