### ISSUE TITLE
the capture is not my wish

### ISSUE THREAD

**Issue by kanxue660** [ariya/phantomjs#14816]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.5.0-development
2. What steps will reproduce the problem?

3. Which operating system are you using?
windows10 x64
4. Did you use binary PhantomJS or did you compile it from source?
binary 
5. Please provide any additional information below.
casper.start("https://appleid.apple.com/account");

casper.then(function _wait() {
	this.wait(30*1000);
});

casper.then(function _jietu(){
this.capture('appleid.jpg');
});

**The capture image is not as same as a normal browser show,why?**

**Comment by Vitallium** [comment]
What do you mean by a normal browser? Can you also post the difference?

**Comment by kanxue660** [comment]
in browser, it has a form to register,but my capture has not. i have been add delay 30 seconds.
