### ISSUE TITLE
Phantomjs 2.5 expects libwebp.6.dylib, webp 0.6.0 provides libwebp.7.dylib

### ISSUE THREAD

**Issue by Empact** [ariya/phantomjs#14819]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

The 2.5 beta, phantomjs --version outputs:
2.5.0-development

2. What steps will reproduce the problem?

```
$ phantomjs --version
dyld: Library not loaded: /usr/local/opt/webp/lib/libwebp.6.dylib
  Referenced from: /usr/local/bin/phantomjs
  Reason: image not found
Abort trap: 6
```

3. Which operating system are you using?

```
$ brew info webp
webp: stable 0.6.0 (bottled), HEAD
Image format providing lossless and lossy compression for web images
https://developers.google.com/speed/webp/
/usr/local/Cellar/webp/0.6.0 (37 files, 2.0M) *
  Poured from bottle on 2017-02-13 at 13:36:40
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/webp.rb
```

4. Did you use binary PhantomJS or did you compile it from source?

binary

5. Please provide any additional information below.

linking /usr/local/opt/webp/lib/libwebp.dylib to /usr/local/opt/webp/lib/libwebp.6.dylib seems to work, but I didn't test it against actual webp images.

**Comment by Vitallium** [comment]
Damn. Looks like I need to update the binary.

**Comment by Empact** [comment]
Here are the contents btw - note I added the libwebp.6.dylib link.
```
$ ls -l /usr/local/opt/webp/lib/
total 3096
lrwxr-xr-x  1 ben  admin      37 Feb 13 13:47 libwebp.6.dylib -> /usr/local/opt/webp/lib/libwebp.dylib
-r--r--r--  1 ben  admin  375416 Feb 13 13:36 libwebp.7.dylib
-r--r--r--  1 ben  admin  575456 Jan 30 12:41 libwebp.a
lrwxr-xr-x  1 ben  admin      15 Jan 30 12:41 libwebp.dylib -> libwebp.7.dylib
-r--r--r--  1 ben  admin  193836 Feb 13 13:36 libwebpdecoder.3.dylib
-r--r--r--  1 ben  admin  290224 Jan 30 12:41 libwebpdecoder.a
lrwxr-xr-x  1 ben  admin      22 Jan 30 12:41 libwebpdecoder.dylib -> libwebpdecoder.3.dylib
-r--r--r--  1 ben  admin   18464 Feb 13 13:36 libwebpdemux.2.dylib
-r--r--r--  1 ben  admin   13544 Jan 30 12:41 libwebpdemux.a
lrwxr-xr-x  1 ben  admin      20 Jan 30 12:41 libwebpdemux.dylib -> libwebpdemux.2.dylib
-r--r--r--  1 ben  admin   38388 Feb 13 13:36 libwebpmux.3.dylib
-r--r--r--  1 ben  admin   41864 Jan 30 12:41 libwebpmux.a
lrwxr-xr-x  1 ben  admin      18 Jan 30 12:41 libwebpmux.dylib -> libwebpmux.3.dylib
drwxr-xr-x  6 ben  admin     204 Feb 13 13:36 pkgconfig
```

**Comment by ndelangen** [comment]
@Empact Can you explain how to do this:

> linking /usr/local/opt/webp/lib/libwebp.dylib to /usr/local/opt/webp/lib/libwebp.6.dylib

**Comment by Empact** [comment]
On linux/unix/mac: `ln -s /usr/local/opt/webp/lib/libweb.dylib /usr/local/opt/webp/lib/libwebp.6.dylib`

**Comment by santosh-hegde** [comment]
@Vitallium  When can we get new binary ?

**Comment by mattpr** [comment]
Looks like webp is a required dependency on macos (at least for me on Yosemite).

The release notification only cites required dependencies for Ubuntu.
https://groups.google.com/forum/#!topic/phantomjs/AefOuwkgBh0

It also appears that system installed QT5 and QtWebKit will be required dependencies as well...but that doesn't seem to be the case with the released 2.5.0-beta macos binary package.
https://github.com/ariya/phantomjs/issues/14458

I know the team is probably overwhelmed with tickets and issues, but just wondering if there is some documentation I missed clarifying the current dependencies and requirements for 2.5.0-beta.

The 2.5.0-beta binary works for me on macos x yosemite (after `brew install webp; ln -s /usr/local/opt/webp/lib/libwebp.dylib /usr/local/opt/webp/lib/libwebp.6.dylib`).  Just starting to wonder if I have an older QtWebkit installed in my system or if it was bundled in the beta binary.  Guess I'll try to sort that out later.   `phantomjs --debug=true` doesn't yield any insight into which Qt and QtWebKit are being used as far as I can tell.

**Comment by monkpit** [comment]
Creating the symlink doesn't work on my machine (mac Sierra) - I had to change the command to `ln -s /usr/local/opt/webp/lib/libwebp.7.dylib /usr/local/opt/webp/lib/libwebp.6.dylib`

**Comment by haroon-sheikh** [comment]
@Empact Linking doesn't work for me either.
@Vitallium any ETA on updated binary?

**Comment by Empact** [comment]
@monkpit @haroon-sheikh I installed via homebrew, here's what my package shows (after linking):

```
$ brew info webp --files
webp: stable 0.6.0 (bottled), HEAD
Image format providing lossless and lossy compression for web images
https://developers.google.com/speed/webp/
/usr/local/Cellar/webp/0.6.0 (37 files, 2.0M) *
  Poured from bottle on 2017-02-13 at 13:36:40
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/webp.rb
==> Dependencies
Required: libpng ✔
Recommended: jpeg ✔
Optional: libtiff ✔, giflib ✔
==> Options
--with-giflib
	Build with giflib support
--with-libtiff
	Build with libtiff support
--without-jpeg
	Build without jpeg support
--HEAD
	Install HEAD version
$ brew list webp
/usr/local/Cellar/webp/0.6.0/bin/cwebp
/usr/local/Cellar/webp/0.6.0/bin/dwebp
/usr/local/Cellar/webp/0.6.0/bin/img2webp
/usr/local/Cellar/webp/0.6.0/bin/webpmux
/usr/local/Cellar/webp/0.6.0/include/webp/ (6 files)
/usr/local/Cellar/webp/0.6.0/lib/libwebp.7.dylib
/usr/local/Cellar/webp/0.6.0/lib/libwebpdecoder.3.dylib
/usr/local/Cellar/webp/0.6.0/lib/libwebpdemux.2.dylib
/usr/local/Cellar/webp/0.6.0/lib/libwebpmux.3.dylib
/usr/local/Cellar/webp/0.6.0/lib/pkgconfig/ (4 files)
/usr/local/Cellar/webp/0.6.0/lib/ (9 other files)
/usr/local/Cellar/webp/0.6.0/share/man/ (3 files)
$ ls -l /usr/local/opt/webp/lib/
total 3096
lrwxr-xr-x  1 ben  admin      37 Feb 13 13:47 libwebp.6.dylib -> /usr/local/opt/webp/lib/libwebp.dylib
-r--r--r--  1 ben  admin  375416 Feb 13 13:36 libwebp.7.dylib
-r--r--r--  1 ben  admin  575456 Jan 30 12:41 libwebp.a
lrwxr-xr-x  1 ben  admin      15 Jan 30 12:41 libwebp.dylib -> libwebp.7.dylib
-r--r--r--  1 ben  admin  193836 Feb 13 13:36 libwebpdecoder.3.dylib
-r--r--r--  1 ben  admin  290224 Jan 30 12:41 libwebpdecoder.a
lrwxr-xr-x  1 ben  admin      22 Jan 30 12:41 libwebpdecoder.dylib -> libwebpdecoder.3.dylib
-r--r--r--  1 ben  admin   18464 Feb 13 13:36 libwebpdemux.2.dylib
-r--r--r--  1 ben  admin   13544 Jan 30 12:41 libwebpdemux.a
lrwxr-xr-x  1 ben  admin      20 Jan 30 12:41 libwebpdemux.dylib -> libwebpdemux.2.dylib
-r--r--r--  1 ben  admin   38388 Feb 13 13:36 libwebpmux.3.dylib
-r--r--r--  1 ben  admin   41864 Jan 30 12:41 libwebpmux.a
lrwxr-xr-x  1 ben  admin      18 Jan 30 12:41 libwebpmux.dylib -> libwebpmux.3.dylib
drwxr-xr-x  6 ben  admin     204 Feb 13 13:36 pkgconfig
```

**Comment by haroon-sheikh** [comment]
@Vitallium Do we have an update on this? This is currently blocking a lot of us trying out 2.5.

**Comment by Darren-Mack** [comment]
You can download webp 0.5.2 from google, that generates libwebp.6.dylib. That's how I got round it anyway... I didn't have libwebp.6.dylib on my system at all...

**Comment by tute** [comment]
This worked for me in Sierra:

```
cd /usr/local/opt/webp/lib
cp libwebp.{7,6}.dylib
```

**Comment by Empact** [comment]
@tute minor point but `ln` is preferable as it avoids copying the file, just creates an alias for it.

**Comment by tute** [comment]
Indeed; I must have had a typo cause the `ln` didn't work for me

**Comment by tute** [comment]
Indeed. I must have had a typo cause the `ln` didn't work for me. Thanks!

**Comment by tute** [comment]
Indeed; I must have had a typo cause the `ln` didn't work for me. Thanks!

**Comment by laycoding** [comment]
@tute omg thank you very much , ln didn't work for me too, but cp did!

**Comment by clarkk** [comment]
How did you build and install master when there is no build.py file?

**Comment by takuhii** [comment]
It's installable via homebrew, so I guess homebrew does all the donkey work... Alternatively I just download it direct from Google

**Comment by clarkk** [comment]
Are you sure?

Isn't master only available from github?

The latest release is 2.1.1 and I can't use it.. Need some of the fixes comitted after the release

**Comment by DarrenMack-OD** [comment]
In all honesty I haven't tried it direct from GitHub... Are we talking about the libwebp.6.dylib or PhantomJS in general?

**Comment by clarkk** [comment]
I just searched all issues and found this with `phantomjs 2.5` in the subject..

I'm talking about phantomjs in general.. Can't find out how to build and install master

**Comment by takuhii** [comment]
Do you use Node? Try my NPM module; phantomjs25-beta

I ported the whole thing across...

**Comment by clarkk** [comment]
@takuhii no not really but maybe I might if you have a working version available :)

If you have a working instance of phantomjs 2.5 maybe you could make a quick test for me? (This is another issue I just found)

poppler's pdftohtml does seem to strip all spaces
https://bugs.freedesktop.org/show_bug.cgi?id=103724

Could you generate a simple PDF file for me with this content? :)

```
<div>This is a test</div>
```

**Comment by clarkk** [comment]
@takuhii 
When installing I get this..

```
# npm install -g phantomjs25-beta
/usr/bin/phantomjs -> /usr/lib/node_modules/phantomjs25-beta/bin/phantomjs

> phantomjs25-beta@1.0.16 install /usr/lib/node_modules/phantomjs25-beta
> node install.js

module.js:538
    throw err;
    ^

Error: Cannot find module './lib/phantomjs'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/phantomjs25-beta/install.js:14:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs25-beta@1.0.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs25-beta@1.0.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-14T16_06_09_042Z-debug.log
```

**Comment by JoyChou93** [comment]
@mattpr `brew install webp; ln -s /usr/local/opt/webp/lib/libwebp.dylib /usr/local/opt/webp/lib/libwebp.6.dylib` sovled my problem.

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.
