### ISSUE TITLE
Unable to debug at all

### ISSUE THREAD

**Issue by jesobreira** [ariya/phantomjs#14826]
**1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.**
2.1.1

**2. What steps will reproduce the problem?**
  1. Put this code on a file named `hello.js`:
```
debugger;

for (var i=0; i < 5; i++)
{
  console.log('debugging in phantom js:' + i);
}

phantom.exit();
```
  2. Run it with `phantomjs --remote-debugger-port=9000 hello.js`
  3. Open `http://localhost:9000/` and click `file://hello.js`

**3. Which operating system are you using?**
Tested on:
* Mac OS X Sierra (Safari, Chrome, Firefox)
* Ubuntu 16.10 (Safari on Wine, Chrome, Firefox)
* Windows 7 Ultimate (Safari, Chrome, Firefox)

All browsers are updated.

**4. Did you use binary PhantomJS or did you compile it from source?**
Binary.

**5. Please provide any additional information below.**
The results are:

Safari:

> Detached from the target
> Remote debugging has been terminated with reason: websocket_closed
> Please re-attach to the new target

(reloading didn't help)

It shows up instantly after clicking "hello.js". The process continues running. Sometimes when this happens I have this on terminal console (stdout) and the process stops:

> Fatal Windows exception, code 0xc0000005.
> PhantomJS has crashed. Please read the bug reporting guide at
> <http://phantomjs.org/bug-reporting.html> and file a bug report.

Chrome and Firefox:

The console is totally non-responsible and I am unable to run `__run()`, as `__run()` + <kbd>Enter</kbd> just adds a line feed on the console input, and does not submit it to be ran.

So I am totally unable to debug it, unless by adding several console.log and reading the STDOUT all the time.

**Comment by jberumen3** [comment]
Have exactly the same issue here. 
Tested with Windows 10, latest version of Chrome and Chromium.

**Comment by jberumen3** [comment]
Found a workaround!
On the resources tab once you have webkit debugger open, edit the file containing the `function __run(){...}`, and place `__run();` after the function. Then select the statement and select 'Evaluate in Console'.

**Comment by lawulu** [comment]
@jberumen3 Great solution!
