### ISSUE TITLE
FileReaderSync API is missing

### ISSUE THREAD

**Issue by Danielku15** [ariya/phantomjs#14823]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
```
phantomjs> new FileReader()
{
   "error": null,
   "onabort": null,
   "onerror": null,
   "onload": null,
   "onloadend": null,
   "onloadstart": null,
   "onprogress": null,
   "readyState": 0,
   "result": null
}
phantomjs> new FileReaderSync()
Can't find variable: FileReaderSync

  phantomjs://repl-input:1 in global code
```
3. Which operating system are you using?
Windows 10 64 Bit

4. Did you use binary PhantomJS or did you compile it from source?
Binary via Chutzpah Testrunner. 

5. Please provide any additional information below.
It appears that phantomjs only has partial support for the HTML5 File interfaces. The [HTML5 FileAPI](https://www.w3.org/TR/FileAPI/#FileReaderSync) defines the FileReaderSync for reading content synchronous. Also [QtWebKit 2.2](https://trac.webkit.org/wiki/QtWebKitFeatures22) claims to support this HTML5 File API  Is PhantomJS maybe still using QTWebkit2.1?

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!

**Comment by Danielku15** [comment]
Same problem with the 2.5 binary: 
```
phantomjs-2.5.0.beta-windows\bin>phantomjs.exe --version
2.5.0-development
phantomjs-2.5.0.beta-windows\bin>phantomjs.exe
phantomjs> new FileReader()
{}
phantomjs> new FileReaderSync()
Can't find variable: FileReaderSync
phantomjs>
```

**Comment by Vitallium** [comment]
@Danielku15 because 
>This interface is only available in workers as it enables synchronous I/O that could potentially block.

See here: https://developer.mozilla.org/en-US/docs/Web/API/FileReaderSync

So, no error here. You are trying to use unavailable interface.

**Comment by Danielku15** [comment]
You are right, if I run my code in a Worker it's working fine. No bug or missing feature in phantomjs therefore. It was just my fault that I was unit-testing a component that is supposed to run in a worker without a worker. Also with 2.1.1 it is working as expected.
