### ISSUE TITLE
build phantomjs failed in CentOS 6.5

### ISSUE THREAD

**Issue by fifyrio** [ariya/phantomjs#14821]
error:  make[1]: Leaving directory `/usr/local/src/phantomjs/src'
then, it finished
![image](https://cloud.githubusercontent.com/assets/8080188/22921432/a9d6c078-f2d4-11e6-9ca5-508733b1d928.png)

**Comment by Vitallium** [comment]
Check the `bin` directory.

**Comment by santosh-hegde** [comment]
@Vitallium  How to build with all the dependencies in the same binary ?
Is there any doc available for 2.5 building ?

**Comment by fifyrio** [comment]
I check the '/usr/bin' and '/usr/local/bin', and find nothing at all, 
By the way, I follow these:
git clone git://github.com/ariya/phantomjs.git
cd phantomjs
git checkout 2.1.1
git submodule init
git submodule update

python build.py

**Comment by Vitallium** [comment]
@fifyrio by default the binary will be placed to `SOURCE_DIR/bin`, not into system directories.

@santosh-hegde do you mean 2.5 version? This is not possible right now. I have a WIP instruction here: https://gist.github.com/Vitallium/f84664eb2d71a4dd91e7e5f1bd8c915e

**Comment by fifyrio** [comment]
@Vitallium  so ,how to start phantomJS in SOURCE_DIR

**Comment by Vitallium** [comment]
@fifyrio I wrote the command above. After `build.py` finishes successfully, you can run PhantomJS from the current dir by using this command: `./bin/phantomjs`

**Comment by santosh-hegde** [comment]
@Vitallium I can't build 2.5 or with all dependencies, it's not possible not now?

When can we expect 2.5 unavailabilities ?

**Comment by fifyrio** [comment]
@Vitallium  by the way, how to build in CentOS by binary packages, hope you answer

**Comment by Vitallium** [comment]
@santosh-hegde please post your build log.

**Comment by santosh-hegde** [comment]
@Vitallium  Here we go.


Got below error when i ran _./configure -static -nomake examples -nomake tests -nomake tools -system-zlib -system-libpng \
-system-libjpeg -opensource -no-cups -confirm-license -no-sql-psql -no-qml-debug -qt-pcre \
-no-xcb -no-dbus -no-libinput -no-gstreamer -no-kms -no-gbm -no-eglfs -no-alsa -no-pulseaudio \
-no-glib -no-evdev -no-xkbcommon-evdev -no-egl -no-qml-debug -no-linuxfb -no-opengl -no-tslib \
-no-qpa-platform-guard -no-gtkstyle -no-xinput2 -no-pkg-config -openssl-linked \
-qpa offscreen -fontconfig -system-freetype -no-directfb -icu -no-mtdev \
-silent -prefix $PWD/../qtbase-build_

santosh@ubuntu:/media/santosh/Part2/test2/phantomjs2/Qt5.7.1$ ./configure -static -nomake examples -nomake tests -nomake tools -system-zlib -system-libpng \ -system-libjpeg -opensource -no-cups -confirm-license -no-sql-psql -no-qml-debug -qt-pcre \ -no-xcb -no-dbus -no-libinput -no-gstreamer -no-kms -no-gbm -no-eglfs -no-alsa -no-pulseaudio \ -no-glib -no-evdev -no-xkbcommon-evdev -no-egl -no-qml-debug -no-linuxfb -no-opengl -no-tslib \ -no-qpa-platform-guard -no-gtkstyle -no-xinput2 -no-pkg-config -openssl-linked \ -qpa offscreen -fontconfig -system-freetype -no-directfb -icu -no-mtdev \ -silent -prefix $PWD/../qtbase-build
+ cd qtbase
+ /media/santosh/Part2/test2/phantomjs2/Qt5.7.1/qtbase/configure -top-level -static -nomake examples -nomake tests -nomake tools -system-zlib -system-libpng  -system-libjpeg -opensource -no-cups -confirm-license -no-sql-psql -no-qml-debug -qt-pcre  -no-xcb -no-dbus -no-libinput -no-gstreamer -no-kms -no-gbm -no-eglfs -no-alsa -no-pulseaudio  -no-glib -no-evdev -no-xkbcommon-evdev -no-egl -no-qml-debug -no-linuxfb -no-opengl -no-tslib  -no-qpa-platform-guard -no-gtkstyle -no-xinput2 -no-pkg-config -openssl-linked  -qpa offscreen -fontconfig -system-freetype -no-directfb -icu -no-mtdev  -silent -prefix /media/santosh/Part2/test2/phantomjs2/Qt5.7.1/../qtbase-build
 -system-libjpeg: unknown argument
 -no-xcb: unknown argument
 -no-glib: unknown argument
 -no-qpa-platform-guard: unknown argument
-no-gtkstyle: invalid command-line switch
 -qpa: unknown argument
offscreen: unknown argument
 -silent: unknown argument


and  after running **_./Tools/Scripts/build-webkit --qt --release --no-device-orientation \
--no-web-audio --no-video --no-video-track --no-touch-events \
--no-touch-slider --no-geolocation --64-bit \
--cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=/media/vitaly/data/dev/qtbase-build -DENABLE_NETSCAPE_PLUGIN_API=OFF -DUSE_GSTREAMER=OFF -DUSE_THIN_ARCHIVES=OFF -DENABLE_API_TESTS=OFF -DENABLE_TEST_SUPPORT=OFF"_**

./Tools/Scripts/build-webkit --qt --release --no-device-orientation \
--no-web-audio --no-video --no-video-track --no-touch-events \
--no-touch-slider --no-geolocation --64-bit \
--cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=/media/vitaly/data/dev/qtbase-build -DENABLE_NETSCAPE_PLUGIN_API=OFF -DUSE_GSTREAMER=OFF -DUSE_THIN_ARCHIVES=OFF -DENABLE_API_TESTS=OFF -DENABLE_TEST_SUPPORT=OFF"


I followed the instuction given @ https://gist.github.com/Vitallium/f84664eb2d71a4dd91e7e5f1bd8c915e.

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.

**Comment by fifyrio** [comment]
thanks
