### ISSUE TITLE
Build instructions are outdated

### ISSUE THREAD

**Issue by sryze** [ariya/phantomjs#14835]
Tried to find out how to build PhantomJS from source code but failed to do so because the documentation appears to be outdated: there is no bulid.py or build.sh anywhere. It would be nice if somebody updated them.

I'm guessing I need to use phantomjs.pro with QtCreator, is that correct? I'd like to make a debug build to capture a stack trace for the crash I'm having.

**Comment by Vitallium** [comment]
2.1 version lives in branch 2.1 - https://github.com/ariya/phantomjs/tree/2.1
For 2.5 version we have WIP instruction here: https://gist.github.com/Vitallium/f84664eb2d71a4dd91e7e5f1bd8c915e

I know this is annoying but we will update instructions soon.

**Comment by Naatan** [comment]
Those WIP instructions seem a bit lacking. Looking forward to proper instructions.
