### ISSUE TITLE
requestAnimationFrame gets wrong time stamp value in phantomjs

### ISSUE THREAD

**Issue by ajithr** [ariya/phantomjs#14832]
1. Which version of PhantomJS are you using? 
    `2.5beta`

2. What steps will reproduce the problem?
  
   - create a requestAnimationFrame method
   - log the time stamp value
   - It gets wrong time stamp value compared with other browsers.

   Shared the example code snippet as below

    ```js
       function rAF(timeStamp) {
          console.log(timeStamp);
          phantom.exit();
      }
      var rAFId = requestAnimationFrame(rAF);
    ```

3. Which operating system are you using?
    windows 10

4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.
    phantomjs gets below time stamp value
         1487305416073.099

    Other browsers get the below time stamp values.
          chrome: 10760.406999965198
          firefox: 9702.835612626144

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
