### ISSUE TITLE
Analytics "Time on Page"

### ISSUE THREAD

**Issue by Rimander** [ariya/phantomjs#14833]
I have a problem with Analytics.
When i visit my website with Phantomjs and use phantom.exit() with setTimeout(function(){phantom.exit();},50000);

Analytics says that "Time on Page" 00:00:00

Thanks and sorry for my english.

**Comment by Vitallium** [comment]
Can you post your script please?

**Comment by Rimander** [comment]
Ok.

Its a basic code.
`
var webPage = require('webpage');
var page = webPage.create();

page.customHeaders = {
  "Connection": "keep-alive"
};
page.open('mywebsite.mywebsite', function(status) {
 
});
setTimeout(function() {phantom.exit(0);}, 200000);
`
Analytics -> Time on Page -> 0!

In the middle of page.open.
I was try to click on links and others things, because i think that google analytics send data if you move the mouse or create other events.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
