### ISSUE TITLE
Phantomjs crashed while scraping

### ISSUE THREAD

**Issue by allanth4** [ariya/phantomjs#14846]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

[_var_www_branches_bin_phantomjs.0.crash.txt](https://github.com/ariya/phantomjs/files/799279/_var_www_branches_bin_phantomjs.0.crash.txt)

2. What steps will reproduce the problem?
  Many steps

3. Which operating system are you using?
Ubuntu

4. Did you use binary PhantomJS or did you compile it from source?
Downloaded binaries

5. Please provide any additional information below.
Sometimes it doesn't crash the first time, but only the following runs.

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
