### ISSUE TITLE
get element doesn't work in linux whereas it works in macosx (using phantomjs 2.1.1)

### ISSUE THREAD

**Issue by anbeque** [ariya/phantomjs#14845]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
Phantomjs 2.1.1
2. What steps will reproduce the problem?
 Trying to get an element via Xpath: By.xpath("//tr/td/input[@title="+title* "']")
It works with phantomjs 2.1.1. binary in macosx but it doesn't work in Linux 3.14.27-25.47.amzn1.x86_64 

4. Did you use binary PhantomJS or did you compile it from source?
Binary PhantomJs for both macosx and Linux.

Wondering if the issue could be platform related. The same code works in macosx whereas it fails in linux 86_64. I also wanted to test the same thing with version 2.0.0 but I can't find a binary for linux distribution. Could you point me to the right place to download it? Do you think that trying to build binaries from source versions for both 2.1.1 will be worth to test? Same thing for 2.0.0?

Thanks in advance,
Angela.

**Comment by jesg** [comment]
@anbeque have you tried the equivalent css selector?  xpath selectors don't have good support across major browsers.

```
tr td input[title*="title"]
```

**Comment by dd-github** [comment]
Yes, we have tried the equivalent selector, but the driver is still unable to locate it.

**Comment by dd-github** [comment]
these elements are rendered from the source website after processing some javascript, could the failure be related to it ?

**Comment by anbeque** [comment]
We are stuck at the moment, so any kind of information from you guys about new things to try or any helpful info that could bring some clarity at our end is welcome. 

As I said before, using version 2.1.1, same code works in macosx and it doesn't in a Linux env. This is why I thought it could be an issue with the Linux distribution of phantomjs.

Thanks!

**Comment by jesg** [comment]
have you tried waiting for the element to be present with `WebDriverWait` and `ExpectedConditions`?

http://docs.seleniumhq.org/docs/04_webdriver_advanced.jsp

**Comment by dd-github** [comment]
yes, we wait for 120 sec before failing. What we a have used to be a working implementation before the website changed the way it rendered pages.I have used the css selector in the browser dev console to locate the element correctly and then used it in By.cssselector

**Comment by jesg** [comment]
are you able to create a snippet of html that i can use to reproduce the issue?

**Comment by jesg** [comment]
fwiw i've not tested ghostdriver against pages with [shadow dom](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM).

**Comment by dd-github** [comment]
is there an email where i can send the particulars of the page in concern and login credentials, if this is possible i'd very much appreciate that
