### ISSUE TITLE
Testing my Angularjs

### ISSUE THREAD

**Issue by gerome0123** [ariya/phantomjs#14851]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
 PhantomJS 2.1.1 

2. What steps will reproduce the problem?
  1. my karma config
      `// Karma configuration
// Generated on Mon Feb 27 2017 09:29:38 GMT+0800 (PHT)

module.exports = function(config) {
  config.set({

      preprocessors: {
          '**/*.coffee': ['coffee']
      },

      coffeePreprocessor: {
          // options passed to the coffee compiler
          options: {
              bare: true,
              sourceMap: false
          },
          // transforming the filenames
          transformPath: function(path) {
              return path.replace(/\.coffee$/, '.js')
          }
      },

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],

    // list of files / patterns to load in the browser
    files: [
        'support_files/angular.js',
        'support_files/angular-mocks.js',
        '../base/module.js', 
        '../caes/module.js', 
        '../caes/controllers/positions/Position1IndexCtrl.js',
         'unit/*.js'
    ],

    // list of files to exclude
    exclude: [
    ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
    },

    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],

    // web server port
    port: 9876,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,

    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['PhantomJS'],

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: Infinity
  })
}
`
  2. base/module
`//= require angular-resource
//= require angular-translate
//= require angular-translate-loader-partial
//= require angular-translate-storage-cookie
//= require angular-translate-storage-local

angular.module("CommonApp", ["App", "ngResource", "pascalprecht.translate"]);`
  
3. error

PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: angular
  at /app/assets/javascripts/app/base/module.js:7

3. Which operating system are you using?
 Mac OX
4. Did you use binary PhantomJS or did you compile it from source?
no

5. Please provide any additional information below.
im try to test my angularjs 

my unit/test

describe('Testing Position1 Suite', function () {
    describe('Testing Position1Index Controller', function () {
        it('should be initialize the position in the scope', function () {
            module('CaesApp');

            var scope = {};
            var ctrl;

            inject(function($controller) {
                ctrl = $controller('Position1IndexCtrl', {$scope:scope});
            });

            expect(scope.position).toBeDefined();
        });
    });

});

my controller trying to test Position1Indexctrl

//= require ./../../module

var Position1IndexCtrl;

Position1IndexCtrl = function($scope) {
    $scope.position = "sample";

};

Position1IndexCtrl.$inject = ["$scope"];

**Comment by Vitallium** [comment]
I think you should check you configuration. Have you tried it in other browsers?

**Comment by gerome0123** [comment]
do u have a sample basic configuration karma testing angularjs that working???
