### ISSUE TITLE
crash without no report under /tmp

### ISSUE THREAD

**Issue by 191264513** [ariya/phantomjs#14850]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?

hard to reproduce the problem.

I use it in python's multiprocessing way. in subprocess ,i called it by subprocess.Popen()
seems in some situations, i crashed, but no report file found under /tmp. only some outputs saw at the screen. 

3. Which operating system are you using?

centos 7.2

4. Did you use binary PhantomJS or did you compile it from source?

binary PhantomJS

5. Please provide any additional information below.

1   0x1b67967 /usr/local/bin/phantomjs() [0x1b67967]
2   0x8c01e2 /usr/local/bin/phantomjs() [0x8c01e2]
3   0x8b5301 /usr/local/bin/phantomjs() [0x8b5301]
4   0x764ebe /usr/local/bin/phantomjs() [0x764ebe]
5   0x8b49ba /usr/local/bin/phantomjs() [0x8b49ba]
6   0x89cac5 /usr/local/bin/phantomjs() [0x89cac5]
7   0x89cd70 /usr/local/bin/phantomjs() [0x89cd70]
8   0x8f6cd5 /usr/local/bin/phantomjs() [0x8f6cd5]
9   0x8f6e3b /usr/local/bin/phantomjs() [0x8f6e3b]
10  0x8ed440 /usr/local/bin/phantomjs() [0x8ed440]
11  0xaef89b /usr/local/bin/phantomjs() [0xaef89b]
12  0xaef5b0 /usr/local/bin/phantomjs() [0xaef5b0]
13  0xaefe62 /usr/local/bin/phantomjs() [0xaefe62]
14  0x22f4ace /usr/local/bin/phantomjs() [0x22f4ace]
15  0x22f4ace /usr/local/bin/phantomjs() [0x22f4ace]
16  0x1f5d971 /usr/local/bin/phantomjs() [0x1f5d971]
17  0x1fc2aed /usr/local/bin/phantomjs() [0x1fc2aed]
18  0x22f8aee /usr/local/bin/phantomjs() [0x22f8aee]
19  0x4ac3bc /usr/local/bin/phantomjs() [0x4ac3bc]
20  0x4b0000 /usr/local/bin/phantomjs() [0x4b0000]
21  0x22d3f70 /usr/local/bin/phantomjs() [0x22d3f70]
22  0x2314598 /usr/local/bin/phantomjs() [0x2314598]
23  0x1bbf4b5 /usr/local/bin/phantomjs() [0x1bbf4b5]
24  0x22cf7a9 /usr/local/bin/phantomjs() [0x22cf7a9]
25  0x22d4585 /usr/local/bin/phantomjs() [0x22d4585]
26  0x415b9a /usr/local/bin/phantomjs() [0x415b9a]
27  0x7f4dc6c2caf5 /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f4dc6c2caf5]
28  0x4176a1 /usr/local/bin/phantomjs() [0x4176a1]

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!
