### ISSUE TITLE
npm installation fails due to dead link to bitbucket downloads site

### ISSUE THREAD

**Issue by HackerMD** [ariya/phantomjs#14856]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2. What steps will reproduce the problem?
  npm install phantomjs

3. Which operating system are you using?
 Ubuntu 16.04

4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.

https://bitbucket.org/ariya/phantomjs/downloads

<img width="1440" alt="screen shot 2017-02-28 at 22 58 42" src="https://cloud.githubusercontent.com/assets/6855297/23436077/8dbdbc62-fe09-11e6-8ca4-c134c2598dd5.png">

**Comment by Vitallium** [comment]
I guess this is because Amazon S3 had problems. We can close this issue now.

**Comment by HackerMD** [comment]
Yes! Thanks!
