### ISSUE TITLE
High use of system resources on Mac OS X when idle

### ISSUE THREAD

**Issue by lharkleroad** [ariya/phantomjs#14863]
My team and I are using the binary phantomjs 2.1.1 for Mac and Linux. I have tested it on both El Capitan and Sierra versions of Mac OS X as we are upgrading the team from El Capitan to Sierra for development. Amazon Linux is used for production.

The problem is that while the Mac instance of phantomjs is running supposedly idle and waiting for data, CPU usage spikes.

On Linux, it works great and remains nearly 0% until there is data to process. Once the instance receives and begins processing the data, CPU usage will go up a few percent and immediately go back to zero, which is exactly what I would expect.

For El Capitan, CPU usage fluctuates constantly between 0% and around 20%. For Sierra, CPU usage will often peak at over 90%. It also appears to suffer from a memory leak. It will start at about 20 MB and slowly climb. Over about a 2 day period, it was using several hundred MB. It may work for simple testing, but we would have to start the phantomjs process when we want to test and then kill it when we're done to avoid this issue of hogging resources.

Have other users noticed this behavior? If so, is there a fix available or an update in the works? I really need to upgrade to 2.1.1 because 1.9.x does not work at all on Sierra, which the whole team will soon be using.

Thanks!

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
