### ISSUE TITLE
what is the phantom pdf A4 size in pixel?

### ISSUE THREAD

**Issue by iyyappan13391** [ariya/phantomjs#14869]
Actually i am using getting final output pdf A4 with help of phantom.I'm having content of exact A4 size(595 * 842 pixels).But **phantom pdf output** is larger than A4(595 * 842 pixels) size.

Does anybody know???

**Comment by chro008** [comment]
really?in fact,you can set the width and height to the paper,such like:
page.paperSize = {
			//format:'A3',
			width:'1000px',
			height:'1100px'
		}
