### ISSUE TITLE
This webpage cannot be parsed totally

### ISSUE THREAD

**Issue by wangyunshuai** [ariya/phantomjs#14862]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
code as below:
```js
var page = require('webpage').create();
page.open('http://www.backcountry.com/new-arrivals?fl=true', function () {
    console.log(page.content)
    phantom.exit();
});
```

problem is the main html code of this webpage is in  <--   -->, havent been parsed by phantomjs.

3. Which operating system are you using?
Mac OS 10.12.1

4. Did you use binary PhantomJS or did you compile it from source?
install by brew install phantomjs

5. Please provide any additional information below.

**Comment by zackw** [comment]
The `page.open` callback fires at approximately the same time as the
`onload` event, not afterward - we have no way of knowing how much work is
still to be done by JavaScript.  Try adding a delay of five to ten seconds
after the `page.open` callback fires, before calling `console.log`, to give
scripts a chance to run.
