### ISSUE TITLE
ArrayBuffer.isView is undefined

### ISSUE THREAD

**Issue by hitsthings** [ariya/phantomjs#14868]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. Open a webpage with in-browser JS that runs ArrayBuffer.isView("{}")

3. Which operating system are you using? OSX

4. Did you use binary PhantomJS or did you compile it from source?
npm install -g

5. Please provide any additional information below.
This function is supported in all major browsers (and is used by [BrowserFS](https://github.com/jvilk/BrowserFS), which therefore fails).

Cross-reference with BrowserFS issue - https://github.com/jvilk/BrowserFS/issues/175

This is causing an archiving issue for the Internet Archive iiuc - https://twitter.com/textfiles/status/838185877067071488

**Comment by twalpole** [comment]
ArrayBuffer is ES2015 which PhantomJS 2.1.1 doesn't support -- try the 2.5 beta

**Comment by hitsthings** [comment]
Thanks for that! The weird thing is that ArrayBuffer existed, but had no isView method. Possible there was some half polyfill mixed in somewhere. I tried the beta but I'm getting 

```
[user dir]$ /Users/user/Downloads/phantomjs-2.5.0-beta-macos/bin/phantomjs script.js
dyld: Library not loaded: /usr/local/opt/webp/lib/libwebp.6.dylib
  Referenced from: /Users/aahmed/Downloads/phantomjs-2.5.0-beta-macos/bin/phantomjs
  Reason: image not found
Trace/BPT trap: 5
```

I'll need to figure that out to see if the beta fixes it. Thanks again!

**Comment by ariya** [comment]
Modern JavaScript features (from ES6/ES2015 or later) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
