### ISSUE TITLE
FormData methods not available

### ISSUE THREAD

**Issue by Radiergummi** [ariya/phantomjs#14867]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
    1. Create a new FormData object
    2. Append a key
    3. Try to `get` the key, or use `has`, `entries`, `values`

3. Which operating system are you using?
      System Version: macOS 10.12.3 (16D32)
      Kernel Version: Darwin 16.4.0

4. Did you use binary PhantomJS or did you compile it from source?
`phantomjs-prebuilt` from npm. Tried to use 2.5-beta, failed because of #14819 

5. Please provide any additional information below.
This is likely related to #14464, but it also affects other FormData methods. Output on command line: 

````
phantomjs> var fd = new FormData()
undefined
phantomjs> fd
{}
phantomjs> fd.append('foo', 'bar')
undefined
phantomjs> fd.get('foo')
'fd.get('foo')' is a cyclic structure

  phantomjs://repl-input:1 in global code
phantomjs> fd.has('foo')
'fd.has('foo')' is a cyclic structure

  phantomjs://repl-input:1 in global code
phantomjs> fd.entries()
'fd.entries()' is a cyclic structure

  phantomjs://repl-input:1 in global code
````

**Comment by raff** [comment]
If you use FormData inside page.evaluate it works as expexted

**Comment by Radiergummi** [comment]
@raff that doesn't apply when using PhantomJS for automated tests - the `page` object is not available there.
