### ISSUE TITLE
Building phantomjs 2.5 on MacOS fails to link (with https://github.com/annulen/webkit)

### ISSUE THREAD

**Issue by raff** [ariya/phantomjs#14873]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
  2.5

2. What steps will reproduce the problem?
  1. build and install webkit from https://github.com/annulen/webkit
  2. build phantomjs 2.5

3. Which operating system are you using?
  MacOS

4. Did you use binary PhantomJS or did you compile it from source?
  Compile from source

5. Please provide any additional information below.
  The build tries to link to Qt5WebKit and Qt5WebKitWidgets (as libraries: -lQt5WebKit) but WebKit actually installed WebKit and WebKitWidgets as frameworks (-framework WebKit).

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.
