### ISSUE TITLE
PhantomJS 2.1.1 port to ppc64le - pagesize changes.

### ISSUE THREAD

**Issue by asowani** [ariya/phantomjs#14876]
I am planning to upstream following fix in webkit 5.5.1 to support ppc64le.  I would like to know if PhantomJS 2.1.1 will pull it automatically once it is approved and merged by the webkit community (basically, will it also be available in vitallium/qtwebkit.git as well). Thanks!

1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
PhantomJS 2.1.1

2. What steps will reproduce the problem?
Nothing in particular.

3. Which operating system are you using?
Ubuntu 16.04LTS on ppc64le (Power8/LE)

4. Did you use binary PhantomJS or did you compile it from source?
Compiled PhantomJS from source cloned from GitHub.

5. Please provide any additional information below.
For using PhantomJS on ppc64le, a change in pagesize value is required. On x86_64, pagesize value is 32KB. On ppc64le, default pagesize is 64KB. Webkit submodule needs to be updated for this.

**Comment by Vitallium** [comment]
@asowani I saw your messages in WebKit mailing list ;-) We plan to use revived fork of QtWebKit (https://github.com/annulen/webkit) I suggest to send your patches there.

**Comment by asowani** [comment]
Thanks @Vitallium I will send my patches to the said fork.

**Comment by annulen** [comment]
@asowani It would be even better if you got your patches merged to trunk, then I would cherry-pick them

**Comment by annulen** [comment]
https://github.com/annulen/webkit/wiki/How-to-submit-patches-to-webkit.org
