### ISSUE TITLE
PhantomJS: setTimeout Still Not Working?

### ISSUE THREAD

**Issue by VikR0001** [ariya/phantomjs#14879]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  See below

3. Which operating system are you using?
OS X, running PhantomJS from Terminal.

4. Did you use binary PhantomJS or did you compile it from source?
Binary.

5. Please provide any additional information below.

There are a lot of posts on the net [documenting](https://groups.google.com/forum/#!topic/phantomjs/dEI28sMwGEU) a serious bug in PhantomJS, in which the delay in setTimeout is ignored. Most of them are a few years old. I would have thought this bug had been fixed by now, but I appear to be encountering it:

Here's my PhantomJS test code, used with PhantomJS v2.1.1:

```
    page.open(uri, function (status) {
        var content = page.content;
        console.log('page loaded');
    
        if (status !== "success")
        {
            phantomResult = JSON.stringify({
              "status": status,
              "content": "page not opened"
            });
            console.log(phantomResult);
            phantom.exit(1);
        }
        else
        {
            content = page.content;
            page.onConsoleMessage = function (msg) { console.log(msg); };
    
            console.log('about to try timeout test');
            window.setTimeout(console.log('set timeout test'), 100);
    
            console.log('about to try timeout test 2');
            window.setTimeout(console.log('set timeout test 2'), 2000);
    
            console.log('about to try timeout test 3');
            window.setTimeout(console.log('set timeout test 3'), 4000);
    
            window.setTimeout(console.log(phantom.exit(1)), 6000);
        }
    });
```

The console.log calls executed via setTimeout are executed immediately one right after the other, with no delay between them.

Has this bug not been fixed yet? I'm using OS X and calling phantomJS via the terminal.

Hopefully there's a fix for this! Thanks in advance to all for any info.

**Comment by thisispaul** [comment]
You have your set timeouts set up wrong.

You need to do this:

```
window.setTimeout(function () {
  console.log('set timeout test')
}, 100);
```

**Comment by bissictjj** [comment]
Is this just on macOS? or all versions of Phantomjs?

**Comment by decease** [comment]
This line `window.setTimeout(console.log('set timeout test'), 100);` means to run `console.log('set timeout test')` and use it's result as a first parameter of setTimeout().

I think you need to do something like that:
`window.setTimeout(function () { console.log('set timeout test') }, 100);`

**Comment by bkawk** [comment]
Still not working on mcOS High Sierra

**Comment by twalpole** [comment]
@bkawk Did you read any of the previous comments explaining why this is user error and not an actual issue with PhantomJS ???

**Comment by bkawk** [comment]
Yes I did and i still can't get it to work

**Comment by twalpole** [comment]
@bkawk then rather than just stating “still doesn’t work” - post an example where it’s not working that isn’t just user error
