### ISSUE TITLE
localStorage is null in 2.5.0

### ISSUE THREAD

**Issue by DrunkAdmin** [ariya/phantomjs#14878]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.5.0-development
2. What steps will reproduce the problem?
  _make script like_:
`"use strict";
var page = require('webpage').create();
page.onConsoleMessage = function(msg, lineNum, sourceId) {
  console.log('Browser CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
};
page.open('https://html5test.com/index.html', function (status) {
    if (status !== 'success') {
        console.log('Unable to access network');
    } else {
        console.log('localStorage object: ' + page.evaluate(function () {
            return JSON.stringify(window.localStorage);
        }));
        setTimeout(function() {
        	page.render('./shot.png', {format: 'png', quality: '10'});
        	console.log('Render');
        	setTimeout(function() {
	        	phantom.exit();
        	}, 1000);
        }, 3000);
    }
});`
_run it by_ `./phantomjs --disk-cache=false --cookies-file="./cookies.txt" --local-storage-path="./" test.js`
_see that_ object localStorage is null and service not detect it in report

3. Which operating system are you using?
Ubuntu-1404-trusty-64-minimal
4. Did you use binary PhantomJS or did you compile it from source?
binary from https://bitbucket.org/ariya/phantomjs/downloads/

**Console screenshot:**
![console](https://cloud.githubusercontent.com/assets/7716174/23697577/5a29cfd0-03f9-11e7-89c3-338072719cfa.png)

**Report screenshot**
![shot](https://cloud.githubusercontent.com/assets/7716174/23697531/298159de-03f9-11e7-8eea-3d0de3a3334f.png)

**Comment by Vitallium** [comment]
Local storage is disable by default. Use `--local-store-quota` argument and set it to any positive value.
