### ISSUE TITLE
PhantomJS does not work with Karma in Angular2 project

### ISSUE THREAD

**Issue by coderchief** [ariya/phantomjs#14877]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`. 
**version 2.1.1**

2. What steps will reproduce the problem?

**1.   create project with angular2 cli (ng new TestPhantomJS)
2.    run npm install karma-phantonjs-launcher
3.   in the karma.conf file add PhantomJS, ie change to browsers: ['Chrome'] this browsers:['Chrome', 'PhantomJS']**

3. Which operating system are you using?
**Windows10**

The test run OK with ng test as long as the Chrome is specified as the browser, The problem is when you try and use PhantomJS. You will get the error as per image below. My research suggests that this is has to do with PhantomJS and javascript version compatibility. However, I have not found a solution to this problem.

> 
> PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
>   SyntaxError: Unexpected token 'const'
>   at webpack:///src/app/app.component.ts:1:0 <- src/test.ts:63166
> 
> PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
>   SyntaxError: Unexpected token 'const'
>   at webpack:///src/app/app.component.ts:1:0 <- src/test.ts:63166

**Comment by twalpole** [comment]
You're using an ES2015 feature (const) - PhantomJS 2.1.1 doesn't support ES2015 (ES6) - You either need to transpire all code (and poly fill) to a lower version of JS, or you can attempt to try the PhantomJS 2.5 beta

**Comment by BernhardRode** [comment]
@twalpole - I'd love to try that out. Do i just need to checkout master, or is 2.5 handled elsewhere?

**Comment by twalpole** [comment]
@BernhardRode https://groups.google.com/forum/#!topic/phantomjs/AefOuwkgBh0  Note it is still very much a beta so you may run into other issues.
