### ISSUE TITLE
PhantomJS/ghostdriver bug when trying to type to multipe input field

### ISSUE THREAD

**Issue by CasperHollemans** [ariya/phantomjs#14881]
1. Which version of PhantomJS are you using?
2.5 beta, also tried with:
- 1.9.6
- 1.9.7
- 1.9.8
- 2.0.0
2. What steps will reproduce the problem?
Use the function sendKeys() to type in a multiple file input element (java class: org.openqa.selenium.WebElement)

3. Which operating system are you using?
Windows 8 and oracle linux 6.8 (Comareable to red hat 6.8 )

4. Did you use binary PhantomJS or did you compile it from source?
Binary
5. Please provide any additional information below.
After you send keys to a multipe file input field the driver will "freeze" (Stops working) and'll remain that way.

If somebody else has experianced the same problem as me and knows a fix or workaround please give a reply on my question on stackoverflow so everyone will have your answer: http://stackoverflow.com/questions/42647627/selenium-test-with-multiple-file-input-crashes-when-run-with-phantomjsdriver-gho

**Comment by jesg** [comment]
@CasperHollemans should be fixed in the next version of ghostdriver.

**Comment by CasperHollemans** [comment]
@jesg ah thank you, that's really good to hear.

**Comment by CasperHollemans** [comment]
@jesg Could you give me a indication when the next version will be released?

**Comment by jesg** [comment]
> Could you give me a indication when the next version will be released?

detro/ghostdriver#511 is pretty close.  i need to refactor where the java client driver is published to.

2.5-beta works on centos 6.8?

**Comment by CasperHollemans** [comment]
Ah good, I assume it does my version of linux is built on the same base as centos 6.8
