### ISSUE TITLE
PhantomJS crashes randomly

### ISSUE THREAD

**Issue by joyer** [ariya/phantomjs#14880]
## Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2.1.1

## What steps will reproduce the problem?

1. Launch phantomjs using supervisor: /usr/bin/phantomjs --disk-cache=no render.js 8888 http://localhost.forphantom
2. We parse our sitemap with 800-900 items and use curl to get HTML content of our pages rendered by phantom. It crashes randomly.

**render.js**
```
var system = require('system');
var fs = require('fs');

if (system.args.length < 3) {
  console.log("Missing arguments.");
  phantom.exit();
}

var server = require('webserver').create();
var port = parseInt(system.args[1]);
var urlPrefix = system.args[2];

var parse_qs = function (s) {
  var queryString = {};
  var a = document.createElement("a");
  a.href = s;
  a.search.replace(
    new RegExp("([^?=&]+)(=([^&]*))?", "g"),
    function ($0, $1, $2, $3) {
      queryString[$1] = $3;
    }
  );
  return queryString;
};

var renderHtml = function (url, cb) {
  // console.log("try to load page "+url);
  var page = require('webpage').create();
  page.settings.loadImages = false;
  page.settings.localToRemoteUrlAccessEnabled = true;
  page.onCallback = function () {
    cb(page.content);
    page.close();
  };

  page.onInitialized = function () {
    page.evaluate(function () {
      setTimeout(function () {
        window.callPhantom();
      }, 15000);
    });
  };
  page.open(url);
};

server.listen(port, function (request, response) {
  var route = parse_qs(request.url)._escaped_fragment_;


  var url = urlPrefix + '/' + request.url;

  renderHtml(url, function (html) {
    response.statusCode = 200;
    response.write(html);
    response.close();
    console.log("render and save: " + request.url);
    var path = 'render-tmp/' + request.url + '/index.html';
    fs.write(path, html, 'w');
  });
});

console.log('Listening on ' + port + '...');
console.log('Press Ctrl+C to stop.');
```

## Which operating system are you using?
Ubuntu 14.04.5 LTS 32bit 

_df -h_
`Filesystem     Size  Used Avail Use% Mounted on
/dev/xvda3       38G  9.1G   27G  26% /`

_free_
`             total       used       free     shared    buffers     cached
Mem:       2055804    1892132     163672      39088     223776     982704
-/+ buffers/cache:     685652    1370152
Swap:       524284       1160     523124`

htop screen: http://prntscr.com/ehft10
## Did you use binary PhantomJS or did you compile it from source?
binary PhantomJS from this page: https://bitbucket.org/ariya/phantomjs/downloads/

## Please provide any additional information below.
I would love to convert the crash dump to a stack trace but there are no symbols for the version phantomjs-2.1.1-linux-i686.tar.bz2 I use.
I tried to launch phantom without supervisor. Upgrading to 2.5.0.beta gave nothing. As well as downgrading to 1.9.x

**Comment by joyer** [comment]
Hello, is there anything I can do to help?

**Comment by joyer** [comment]
hello...

**Comment by robocrm** [comment]
:(

**Comment by joyer** [comment]
Is there any chance to get an answer?

**Comment by joyer** [comment]
Wondering how long could it take...

**Comment by joyer** [comment]
:+1:

**Comment by joyer** [comment]
Hi.
