### ISSUE TITLE
screen shot is not accurate as its seeing in browser

### ISSUE THREAD

**Issue by nk-nareshkumar** [ariya/phantomjs#14883]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
: version : 1.9.8

2. What steps will reproduce the problem?
: I pasted my script in this issue.

3. Which operating system are you using?
: Ubuntu 14

4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.

**My words:**

With this below code i tried to capture screen from a url  but it seems its not giving perfect screen shot..
Or i am doing something wrong ?

screen shot : http://www.awesomescreenshot.com/image/2275399/7cf995d2e287cb87c4ca4895b6b69934

Website : http://www.whiteboardexplainers.com/

```
var system = require("system");
if (system.args.length > 0) {
    var page = require('webpage').create();
	page.viewportSize = {width: 1280, height: 1024};
    page.open(system.args[1], function() {
        var pageTitle = system.args[1].replace(/http.*\/\//g, "").replace("www.", "").split("/")[0]
        var filePath = "pageTitle + '.png';
        
        window.setTimeout(function () {
			page.evaluate(function() {
				document.body.bgColor = 'white';
			});  
			page.render(filePath);
        	console.log(filePath);
        	phantom.exit();
		}, 200);
        
    });
}
```

**Comment by jesg** [comment]
@nk-nareshkumar you need to set [clipRect](http://phantomjs.org/api/webpage/property/clip-rect.html) to take a screenshot of a subsection of the screen.

**Comment by nk-nareshkumar** [comment]
screen shot : http://www.awesomescreenshot.com/image/2275399/7cf995d2e287cb87c4ca4895b6b69934

Website : http://www.whiteboardexplainers.com/

In these both screen the only difference the header issue is coming in captured screenshot.. not getting why you suggested clipRect method,. correct me if i am wrong.

**Comment by jesg** [comment]
your right.

i see the following in phantomjs 2.1.1:
![tmp](https://cloud.githubusercontent.com/assets/1785589/23789532/1228b5f6-0530-11e7-812d-b64d3582788f.png)

and on phantomjs 2.5.0-beta
![tmp](https://cloud.githubusercontent.com/assets/1785589/23789555/34ef06da-0530-11e7-9039-0a212cc38641.png)

so it looks like a phantomjs 1.9.8 issue.

**Comment by nk-nareshkumar** [comment]
ok.. thank you .. i will test after update the phantomjs package
