### ISSUE TITLE
It's not possible scren a pdf file?

### ISSUE THREAD

**Issue by dvjunior** [ariya/phantomjs#14888]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
 2.1.1

2. What steps will reproduce the problem?
  1. Create new file.js for render a webpage
  2. execute on cmd(windows)- phantomjs --web-security=no script.js
  3. don't have

3. Which operating system are you using?

4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.
my script:

```var page = require('webpage').create();
page.open("http://localhost/phantom/", function(status) {
  if(status !== 'success'){
  	console.log('Unable to load the address!');
  }else{
  	window.setTimeout(function(){
  		page.render('AAAA.png');
  		phantom.exit();
  	}, 20000
  	);
  }
});
```
In http://localhost/phantom/ have <iframe src="file.pdf" width="600" height="780" style="border: none;"></iframe>

The return of script.js, file AAAA.png is white, null file, cant not scren/render.

If I chance for page.open("http://localhost/phantom/file.pdf", function(status) returns "Unable to load the address!"

**Comment by Vitallium** [comment]
PhantomJS doesn't support plugins. It can't render PDF files on a web page.

**Comment by dvjunior** [comment]
Thanks @Vitallium
