### ISSUE TITLE
PhantomJS shouldn't disable proxy auth on empty password

### ISSUE THREAD

**Issue by dege88** [ariya/phantomjs#14886]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1. trying to connect to a proxy with an empty password

3. Which operating system are you using?
Ubuntu 16.04

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.

The issue has been described quite accurately by @cfank in comment https://github.com/ariya/phantomjs/issues/14554#issuecomment-270241200
but I think that this is a separate issue from the linked one.

https://github.com/ariya/phantomjs/blob/master/src/phantom.cpp#L423 This check could be causing the issue with crawlera.
Unfortunately crawlera uses the api key as the username and an empty password, but this line of code discards username and password altogether in case of an empty password.

CC: @ezako2

**Comment by cfank** [comment]
Great investigation @dege88 this looks likely to be the issue that's been plaguing us, and the fix could be as simple as changing that `&&` to a `||` ... 😅

I'd be happy to test a properly patched build, just let me know.
