### ISSUE TITLE
PhantomJS 2.5.0 on Redhat 7.3 missing libraries

### ISSUE THREAD

**Issue by antcs** [ariya/phantomjs#14894]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.5.0-development

2. What steps will reproduce the problem?
  1. execute phantomjs -v

3. Which operating system are you using?
Redhat 7.3

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
First of all thank you and congratulation to the new release.

I really want to run the newest phantom on my redhat, but get the following message.

error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory

I need to install the missing dependencies, which Vitaly mentioned for Ubuntu, but which exactly do I need for redhat?

yum search png or yum search jpeg gives me a lot of results so I'm a little confused....

Thanks!

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.
