### ISSUE TITLE
PhantomJS cutting/splitting words in half across page breaks

### ISSUE THREAD

**Issue by IAMtheIAM** [ariya/phantomjs#14892]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
[phantomjs-node ^v2.1.21](https://github.com/amir20/phantomjs-node)
2. What steps will reproduce the problem?
  a. Create multi page website
  b. Render as pdf

3. Which operating system are you using?
windows 10 x64

4. Did you use binary PhantomJS or did you compile it from source?
[phantomjs-node](https://github.com/amir20/phantomjs-node) pre-compiled
5. Please provide any additional information below.

I am using the phantomjs-node api to render a PDF. The problem is that words that appear near the end of a page are split across 2 pages, half the word on page 1, other half on page 2. I cannot understand why this is happening. What can I do to fix this?

![phantomjs_cutting_words_in_half_across_page_breaks](https://cloud.githubusercontent.com/assets/13709948/23868424/92e59e26-07dc-11e7-8fa2-817a0f0bb1e9.png)

**Comment by vamsimutyala** [comment]
@IAMtheIAM Did you find any work around for this problem ?

**Comment by visvk** [comment]
@IAMtheIAM Is there any work around?

**Comment by theaspect** [comment]
Try `page-break-inside:avoid` could help, or not
