### ISSUE TITLE
Authorization headers not being used for image requests in 2.5

### ISSUE THREAD

**Issue by Doogal666** [ariya/phantomjs#14895]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.5.0-development
2. What steps will reproduce the problem?
  1. The script contains something like
var page: WebPage = require("webpage").create();
page.onResourceReceived = function(response) {
  console.log(response.url + " received, status " + response.status);
};
page.customHeaders = { "Authorization": "Basic " + btoa("username:password") };
page.open(pageThatRequiresAuthentication);

  2. In 2.1 the images referenced by the page are returned. In 2.5, the response is my login page, suggesting the authorization header isn't being include with the image requests

3. Which operating system are you using?
Windows
4. Did you use binary PhantomJS or did you compile it from source?
binary
5. Please provide any additional information below.

**Comment by jesg** [comment]
@Doogal666 if there is a redirect then this is probably related to #14858 .  the authorization headers will not be in the redirect.

**Comment by Doogal666** [comment]
@jesg, there is a redirect because the server thinks the client isn't authenticated, so I think the redirect is an effect rather than the cause of the issue
