### ISSUE TITLE
 hundred's of different instances simultaneous Using too much RAM 

### ISSUE THREAD

**Issue by sk1967** [ariya/phantomjs#14906]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
1.9.7
2. What steps will reproduce the problem?
  1. 60+ instances of PhantomJS  running different scripts.
Using too much RAM (the system has 8 Gb)

3. Which operating system are you using?
Ubuntu 
4. Did you use binary PhantomJS or did you compile it from source?
binary
5. Please provide any additional information below.

I  need to run hundred's of different instances simultaneous...

I am thinking of create the PhantomJS using shared library. (Create everything as shared library except the main.cpp and then link together).  I am not very familiar with makefile so any help tip where to start will be helpfully.

**Comment by ariya** [comment]
Implementing this is a major undertaking and currently beyond the scope of the project.
You are however free to work on it on your own or sponsor someone to implement it. Once it is in a state where we can consider it for inclusion, please reopen this issue and submit a pull request of the implementation. Thank you!
