### ISSUE TITLE
Css Selector Error: Same object with xpath works just fine. 

### ISSUE THREAD

**Issue by lalexco** [ariya/phantomjs#14903]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1. Try to locate an object with Css Selector in this case : This is my object 
        [FindsBy(How = How.CssSelector, Using = ".ng-binding[ng-bind = '$ci.homePhone'")]
        private readonly IWebElement _homePhone = null;
  2. Exception thrown: 
OpenQA.Selenium.InvalidElementStateException: {"errorMessage":"SyntaxError: DOM Exception 12","request":{"headers":{"Accept":"application/json, image/png","Connection":"Close","Content-Length":"72","Content-Type":"application/json;charset=utf-8","Host":"localhost:49785"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"css selector\",\"value\":\".ng-binding[ng-bind = '$ci.homePhone'\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/786c4bf0-0b72-11e7-97bd-cfc575ce6d32/element"}}

With Chrome works just fine. 

3. Which operating system are you using?
Windows 10
4. Did you use binary PhantomJS or did you compile it from source?
Nuget Package from visual studio. 

5. Please provide any additional information below.

**Comment by jesg** [comment]
@ianoxley you are getting an error because your css selector has a syntax error.

**Comment by lalexco** [comment]
@jesg it doesn't make sense, with chrome and firefox works just fine the same CSS selector. 
The only problem is with PhantomJS

**Comment by jesg** [comment]
regardless `.ng-binding[ng-bind = '$ci.homePhone'` is not valid.  it should be `.ng-binding[ng-bind = '$ci.homePhone']`.  chrome and firefox must seem to be more forgiving than phantomjs.

**Comment by kensoh** [comment]
Nice reply @jesg thanks, learnt something new. Didn't know Chrome/Firefox accept incorrect CSS locators.

**Comment by kensoh** [comment]
Nice reply @jesg thanks, learnt something new. Didn't know Chrome/Firefox accept bad CSS locators.
