### ISSUE TITLE
How install phanomjs on arch aarch64

### ISSUE THREAD

**Issue by renatomsys** [ariya/phantomjs#14901]
I need know how install phantomjs on arch aarch64, Linux Linux tegra-ubuntu 3.10.96-tegra, based in Ubuntu. Thanks.

**Comment by renatomsys** [comment]
Any idea?

**Comment by kensoh** [comment]
Hi @renatomsys this thread and @mitghi might have the answer you are looking for you - https://github.com/ariya/phantomjs/issues/14968

**Comment by ariya** [comment]
Due to our limited resources, for the near future I believe the official binaries will only support x86 arch.
We will reopen this and revisit the subject in the future if other architectures will be supported. Thank you!
