### ISSUE TITLE
return html object from page.evaluate() causes crash

### ISSUE THREAD

**Issue by deejbee** [ariya/phantomjs#14908]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
npm phantomjs-prebuilt
phantomjs-prebuilt node module version 2.1.1

2. What steps will reproduce the problem?
Attempting to return a HTML object from page.evaluate() causes crash.

3. Which operating system are you using?
Windows10

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.
page.evaluate() can return a simple object but when I tried to return the response of an xpath query that evaluated to a HTMLInputElement type, phantomjs crashed.

I was hoping to use the object that was passed back.  I'm not sure if just simple types are supported or not or if I'm perhaps just breaking the expected usage pattern for this function.

**Comment by seansd** [comment]
uh this is already called out in the docs. . .you can't do that.   you can only return simple types back.  Note that you can return Objects but they have to be something that can be serialized via JSON (like object literals/simple JS objects), you can't send dom refs, etc.

see this documentation: http://phantomjs.org/api/webpage/method/evaluate.html

**Comment by deejbee** [comment]
Sorry I didn't read the specifics on evaluate.  Thanks for the clarification.
