### ISSUE TITLE
page-break-after/before not working properly

### ISSUE THREAD

**Issue by sagargupta138** [ariya/phantomjs#14913]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`. 
2.1.1

2. What steps will reproduce the problem?
  1. Issue comes when generating pdf with multiple pages. 
  2. Render a page with css property 'page-break-after/before' set to 'always' so that any new page starts on new pdf page.
  3. There is now a considerable empty white space between the two pages, and because of this, the 2nd page is now split in two pdf pages. If we render more pages, this white space is between every two pages.

3. Which operating system are you using?
Mac OSX

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.
When trying without 'page-break-after/before' property, we need to be able to match my page height with pdf page height. Even after doing that, first few pages are rendering fine, but after a certain page, small empty white space (not as big as when 'page-break-after' was set) is left between the pages. This again causes my page to drag down a bit, and a part of the page is moved to next pdf page. Right now, my page is not getting perfectly aligned to a pdf page for all the pages that i render. 'page-break-after/before' was working properly in the older version of phantom.

**Comment by ttimmons** [comment]
I'm having this same issue as well, also running phantomjs version 2.1.1 and running Mac OSX Sierra.

After setting a page-break-before there is a bunch of white space after the page-break was entered.

**Comment by replete** [comment]
```css
  .page-break {
    page-break-inside: avoid !important;
    float: none;
  }
```

You're welcome

**Comment by kensoh** [comment]
Interesting solution @replete, following thread to see how this develops :)

**Comment by replete** [comment]
If it doesn't work - it's because there are nested floats somewhere along the way.
