### ISSUE TITLE
electron packager

### ISSUE THREAD

**Issue by spyshow** [ariya/phantomjs#14918]
hi all 

i have a program that use Html-pdf (which use Phantom JS"2.1.4") to generate a PDF report . my program work fine when i use 
`electron .` . but when after i package it with electron-packager it wont work giving an error that the  buffer is undefined  ( i use the buffer of PDF file to transfer it to a base64 encoded file)

[UPDATE] : after checking if i remove `--asar=true` then everything is running as usual

any idea why ? 

here is my packge.json:

      {
        "name": "cpfid",
        "productName": "CPF-ID",
        "version": "1.0.0",
        "description": "cpf id",
        "main": "main.js",
        "scripts": {
          "start": "electron .",
          "build": "electron-packager . --overwrite --asar=true"
        },
        "author": "",
        "license": "ISC",
        "devDependencies": {
          "devtron": "^1.4.0",
          "electron-packager": "^8.5.0",
          "electron-winstaller": "^2.5.1",
          "jshint": "^2.9.4"
        },
        "dependencies": {
          "async": "^2.1.4",
          "base64-img": "^1.0.3",
          "base64-stream": "^0.1.3",
          "blob-to-buffer": "^1.2.6",
          "buildmail": "^4.0.0",
          "chart.js": "^2.4.0",
          "electron": "1.4.1",
          "excel4node": "^1.2.1",
          "file-saver": "^1.3.3",
          "html-docx-js": "^0.3.1",
          "html-pdf": "^2.1.0",
          "html2xlsx": "^0.2.0",
          "jszip": "^2.6.1",
          "mailparser": "^0.6.1",
          "mssql": "^3.3.0",
          "path": "^0.12.7",
          "pdfkit": "^0.8.0"
      }
     }

**Comment by ariya** [comment]
This seems to be the problem with `html-pdf`. Please file a report to that project and/or provide more troubleshooting information from there.
