### ISSUE TITLE
PhantomJS doesn't evaluate dynamic content? Clicking a button to open the modal dialog doesn't open it.

### ISSUE THREAD

**Issue by softtama** [ariya/phantomjs#14917]
The expected behaviour, which is worked if I do it on a browser (Chrome):
  1. Open a page with hidden `.jqmWindow` modal dialog
  2. Click on the button that trigger the `.jqmWindow` to appear
  3. The `.jqmWindow` is shown and can be manipulated (like: filling in the form in the modal, click the button in the modal, etc.)

To reproduce the problem:
  1. Open a page with hidden `.jqmWindow` modal dialog
  2. Click on the button that trigger the `.jqmWindow` to appear
  3. Screenshot the page (`page.render()`) 5 seconds after step no.2
  4. You can see that the `.jqmWindow` modal dialog is not there in the screenshot

Environment:
 - PhantomJS 2.1.1 binary version
 - Windows 10 Pro Build 14393.953 64-bit
 - Node.js v4.6.1

Detail:
I have a page (a product page in an online shop website) that already has jQuery included, there I want to open a [`jqModal` modal dialog](http://jquery.iceburg.net/jqModal) by a button click.

Here is a piece of code:

```javascript
page.evaluate(function () {
	if ($('a#promo-topads').length > 0) {
		console.log('==> DEBUG: "Promo TopAds" button exist!');
	} else {
		console.log('==> DEBUG: "Promo TopAds" button DOES NOT exist!');
	}

	console.log('==> Clicking "Promo TopAds" button...');
        // I expected this action to open the modal dialog
	$('a#promo-topads').click();
});
```

The debug says that the button exist. But after doing `$('a#promo-topads').click();`, the modal dialog doesn't appear.

More detail is coming...

**Comment by lin09** [comment]
I also encountered this problem.

**Comment by lin09** [comment]
`var clickElement = function (el) {
  var ev = document.createEvent('MouseEvent');
  ev.initMouseEvent('click', true, true, window, null, 0, 0, 0, 0, false, false, false, false, 0, null);
  el.dispatchEvent(ev);
};
clickElement($('a#promo-topads')[0]);
$('a#promo-topads').click();`
