### ISSUE TITLE
build.py no in the repo?

### ISSUE THREAD

**Issue by jaredpetker** [ariya/phantomjs#14912]
trying to run the build and package script for mac, it tries to run a build.py script that is no where to be found, what am I missing?

**Comment by jaredpetker** [comment]
I see, things were changed for building, I'll look into it.

**Comment by GuilloOme** [comment]
I am interested too, did you find out something?

**Comment by Vitallium** [comment]
See branch 2.1 - https://github.com/ariya/phantomjs/tree/2.1

**Comment by GuilloOme** [comment]
thank you, I saw this too: #14458 explaining the situation
