### ISSUE TITLE
Enormous memory usage in linux phantomjs 2.1.1 when using --proxy-auth

### ISSUE THREAD

**Issue by georgiosd** [ariya/phantomjs#14915]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

`2.1.1`

2. What steps will reproduce the problem?
  1. Set --proxy and --proxy-auth
  2. Visit a website like asos.com
  3. Refresh every 5 sec

3. Which operating system are you using?

`Ubuntu 16.10`

4. Did you use binary PhantomJS or did you compile it from source?

`Binary from website`

5. Please provide any additional information below.

`Memory goes up to 10G in a few seconds! Doesn't happen without --proxy-auth`

**Comment by georgiosd** [comment]
Seems to be OK in 2.5.0 - not sure if you're interested in fixing it in 2.1.1

**Comment by Vitallium** [comment]
@georgiosd Yes, we are not interested in fixing this in 2.1. 2.5 version has huge number of improvements and fixes.

**Comment by tizianoMaini** [comment]
Where can i find the binary for 2.5 version?
