### ISSUE TITLE
Unit test karma with browser phantomJS doesn't support import inheritance

### ISSUE THREAD

**Issue by thanhnguyen92** [ariya/phantomjs#14927]
### Expected behaviour

> Do not show that error

### Actual behaviour
> PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
>   TypeError: undefined: can't set as prototype!

### Environment Details
I have these model classes:

**base.model.ts**
```javascript
export class BaseModel {
    id?: number;
    name?: string;
}
```

**customer.model.ts**
```javascript
import { BaseModel  } from './base.model';

export class CustomerModel extends  BaseModel {
    address?: string;
    // more properties defined
}
```

**product.model.ts**
```javascript
import { BaseModel  } from './base.model';

export class ProductModel extends  BaseModel {
    type?: string;
    // more properties defined
}
```

**home.model.ts**
```javascript
import { BaseModel  } from './base.model';
import { Customer } from './customer.model';
import { Product } from './product.model';

export class HomeModel extends  BaseModel {
    param1: CustomerModel;
    param2: ProductModel;

    constructor(data?: any) { // write some logic in here }
}
```

**home.service.ts**
```javascript
import { Injectable } from '@angular/core';
import { Home } from './home.model';

@Injectable()
export class HomeService {
    constructor(){  }

    get() {
        let home = new HomeModel();
    }
}
```
- Karma version (output of `karma --version`): 1.5.0
- Relevant part of your `karma.config.js` file
```javascript
basePath: '',
frameworks: ['jasmine', 'source-map-support'],
browsers: ['PhantomJS']
```
- **PhamtomJS** version 2.1.1
- **karma-phantomjs-launcher** version 1.0.4

### Steps to reproduce the behaviour

1. Write the unit test for function get() of HomeService (home.service.ts)
2. Run the unit test: `npm run test` will excute `karma start config/karma.conf.js`
3. See the result at **Actual behaviour**

### Follow my research
In `HomeModel`, when you import the `BaseModel` at the first line and the other import also have import `BaseModel` inside it. It will cause the error because `BaseModel` now became `undefined` in the other import.
Maybe PhantomJS doesn't understand the import inheritance like that. Anyone have another suggestion?

Below are links that I have found:

> https://github.com/ariya/phantomjs/issues/14506
http://stackoverflow.com/questions/37398829/barrel-import-appears-to-break-load-order
https://github.com/angular/angular/issues/9334

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!

**Comment by ariya** [comment]
Modern JavaScript features (from ES6/ES2015 or later) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
