### ISSUE TITLE
String.prototype.replace() special replacement patterns

### ISSUE THREAD

**Issue by nakednamor** [ariya/phantomjs#14921]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
 1 Save the following content to test.js
  ```javascript
 var input = 'ABC';
 var output = input.replace('B', function(){return '$$'} );
 console.log('input: ' + input);
 console.log('output: ' + output); 
 phantom.exit();
```
 2 execute:    `phantomjs.exe test.js` 
 3 the expected output is: `A$$C` but is actually `A$C`

3. Which operating system are you using?
Windows 10

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
According to the MDN documentation of String.prototype.relace() there are several special patterns (see first link below) which can be used in the second argument of the function. However if the second argument is a funtion, for my understanding those special pattern should not be applied but it looks as they are.
If I use the code from above in latest Chrome, Firefox and Edge it shows the expected output 'A$$C'.

[MDN Specifying a string as a parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter)
[MDN Specifying a function as a parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_function_as_a_parameter)

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!

**Comment by twalpole** [comment]
Since the current versions of Safari 10.1 and 10.2 tech preview both currently exhibit the broken non spec compliant behavior I would guess it's not fixed in 2.5

**Comment by nakednamor** [comment]
Just tested it with `2.5.0-development` and still the same result

**Comment by twalpole** [comment]
https://bugs.webkit.org/show_bug.cgi?id=170151

**Comment by swookie** [comment]
will this be resolved? the latest binary as of 2017-12-08 is still `2.5.0-beta` https://bitbucket.org/ariya/phantomjs/downloads/ and the latest source release is still `2.1.1` https://github.com/ariya/phantomjs/releases

safari seems to have resolved the issue: https://bugs.webkit.org/show_bug.cgi?id=170151
