### ISSUE TITLE
2.5 beta pdf height is truncated based on viewport height.

### ISSUE THREAD

**Issue by jasonswearingen** [ariya/phantomjs#14922]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.5beta

2. What steps will reproduce the problem?
  1.  set viewport to 1280x1280
  2.  render a pdf of a page like cnn.com
  3. the pdf height will be truncated.

3. Which operating system are you using?
ubuntu 16.04 or windows 10

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
phantomjs 2.1.1 and prior will ignore the viewport height when rendering pdf's.  this is the expected result.

**Comment by teterovic** [comment]
Have the same issue. It exports only one page

**Comment by jasonswearingen** [comment]
yes, further testing shows other differences too, such as no header/footer.  not sure if those need to be in separate issues though.

**Comment by pg1671** [comment]
I have the same problem and have encountered a few other issues so have gone back to 2.1.1.

**Comment by JensVanhooydonck** [comment]
Same issue over here. Gone back to 2.1.1, but here i miss flexbox support..

**Comment by linuxfreakus** [comment]
Not sure if there might be a patch floating around... but I've also noticed that it doesn't seem to want to allow more than one page... paper size + viewport size are set and can only see one page.

I don't really have the option to go back to 2.1.1

**Comment by kensoh** [comment]
I understand that there won't be v2.5.. Does anyone know the state of things for PhantomJS? After maintainer Vitaly's announcement in April that he is stepping down. And Chrome headless is coming, Firefox headless is coming.

I really hope and still believe someone or organization would step up to take on the baton. After all, so much vested interests have been made in the PhantomJS ecosystem. Or at least some form of mitigation steps to ease any transition.

**Comment by mohanzeal** [comment]
same problem here.. i am using ubuntu 16.04 and  https://github.com/marcbachmann/node-html-pdf package to render pdfs. I pointed the phantomjs build to 2.5 beta version using the config settings in the above npm package mentioned.

Currently I am using below viewport settings to render pdf.
` "viewportSize":{
                    width: 595,
                    height: 842
                }`

this is A4 size width and height but I am unable to get pagination in the pdf with the page-break css applied. Can any one help.

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.
