### ISSUE TITLE
PhantomJS doesn't work COMPLETELY!!Please see a code and issue below.

### ISSUE THREAD

**Issue by Denchik1987** [ariya/phantomjs#14920]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
I using the latest satbel version 2.1.1
2. What steps will reproduce the problem?
  1. This is my code below: (Actually I tied several different variations)

   case PhantomJSDriver:
             
                   	DesiredCapabilities caps = new DesiredCapabilities();
    				caps.setJavascriptEnabled(true);
    				caps.setCapability("takesScreenshot", true);
    				File file = new File("//Users//denisbondya/Desktop//All Jars Repository//phantomjs-2.1.1-macosx//bin//phantomjs");
    				caps.setCapability(PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY,
    						file.getAbsolutePath());
              	  //System.setProperty("phantomjs.binary.path", "//Users//denisbondya//Documents//workspace//V2_MainSite_SmokeAutomation//PhantomJs//phantomjs");
                    
            driver =new PhantomJSDriver(caps);

It looks like that it starts working but it doesn't see any xpath I am facing this issue:

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-03-27T15:32:19.493Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1490628739457
  

2.
  3.

3. Which operating system are you using?

macOS Sierra
Version 10.12.3

4. Did you use binary PhantomJS or did you compile it from source?
I am using binary version but tried to compile as well. 
5. Please provide any additional information below.

**Comment by Vitallium** [comment]
cc @jesg

**Comment by jesg** [comment]
@Denchik1987 can you give the version of phantomjsdriver and selenium you are using?

example html would be helpful.  do other selectors work?

**Comment by Denchik1987** [comment]
My selenium version is 3.2.0 and Phantom is 2.1.1
It gives me this weird error



  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-03-28T17:42:05.093Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1490722925060

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-03-28T17:42:05.887Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1490722925861

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-03-28T17:42:06.702Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1490722926651

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-03-28T17:42:07.502Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1490722927470

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-03-28T17:42:07.793Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1490722927767

**Comment by Denchik1987** [comment]
FInally I came up with this code :
It starts working but I have the same problem. It says that unable to locate an element by XPATH. On Chrome, Firefox, Safari everything works just perfect. I put explicit wait, located elements by ID. This f.... ing Phantom doesn't work at all

  	String[] cli_args = new String[]{ "--ssl-protocol=any", "--ignore-ssl-errors=true", "--web-security=false" };
                   	DesiredCapabilities caps = new DesiredCapabilities();
    				caps.setJavascriptEnabled(true);
    				caps.setCapability("takesScreenshot", true);
    				File file = new File("//Users//denisbondya/Desktop//All Jars Repository//phantomjs-2.1.1-macosx//bin//phantomjs");
    				caps.setCapability( PhantomJSDriverService.PHANTOMJS_CLI_ARGS, cli_args );
    				caps.setCapability(PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY,
    						file.getAbsolutePath());
    	  driver =new PhantomJSDriver(caps);
            driver.manage().window().setSize(new Dimension(1280, 1024));

**Comment by jesg** [comment]
@Denchik1987 so locating elements by id works but locating by xpath does not work?  does it also fail for expressions of the form `//<tag name>[@id='<my-id>']` or `//*[@id='<my-id>']`.

can you provide some html here or on [jsfiddle](https://jsfiddle.net/)?  also provide the xpath expression you are using.

**Comment by Denchik1987** [comment]
Please see all my xpath below. In my tests I always find some unique div which has @id and then start initializing other elements . Everything works just fine on other browsers (Chrome, IE, Safari, Firefox) . I am just completely stuck with headless browser.



	@FindBy(how=How.XPATH, using = "//div[@data-automation-id='container:category_menu']/child::a[3]")
	private WebElement cartridgesDropDownHeader;
	
	
	

	@FindBy(how=How.XPATH, using = "//div[@data-automation-id='container:category_menu']/child::a[4]")
	private WebElement e_LiquidsDropDown;
	
	
	


	@FindBy(how=How.XPATH, using = "//div[@data-automation-id='container:category_menu']/child::a[5]")
	private WebElement accessoiresButtonHeader;
	
	
	

	@FindBy(how=How.XPATH, using = "//div[@data-automation-id='container:category_menu']/child::a[6]")
	private WebElement saleDropDown;
	
	
	
	


	@FindBy(how=How.XPATH, using = "//div[@data-automation-id='container:category_menu']/child::a[7]")
	private WebElement videosButton;

**Comment by jesg** [comment]
phantomjs 2.1.1 on 64bit linux `//div[@data-automation-id='container:category_menu']/child::a[3]` finds the element correctly.  i need to check the behaviour on a mac.

does the html below look correct?  do you have `iframes` in your html?
```html
<html>
	<head>
	</head>
	<body>
		<div>
			<div data-automation-id='container:category_menu'>
				<a href='#' id=1 >1</a>
				<a href='#' id=2 >2</a>
				<a href='#' id=3 >3</a>
				<a href='#' id=4 >4</a>
			</div>
		</div>
	</body>
</html>
```

**Comment by twalpole** [comment]
@Denchik1987 In case you didn't realize @jesg is trying to help you - answer the questions or provide your HTML so the issue can be reproduced - Without that there's no way to diagnose your issue.

**Comment by Denchik1987** [comment]
Thank you so much. Please see a screenshot attached below. There is a unique @id for the container and then I just put slash child:: etc..
![screen shot 2017-03-29 at 4 02 20 pm 3](https://cloud.githubusercontent.com/assets/26229019/24515718/71b7fe52-1546-11e7-9f33-604ad46574ec.png)

**Comment by Denchik1987** [comment]
I am sorry Above one is a wrong one!!
![screen shot 2017-03-30 at 12 39 39 pm](https://cloud.githubusercontent.com/assets/26229019/24515790/a20b145e-1546-11e7-9d57-ccc531152cf9.png)

**Comment by jesg** [comment]
@Denchik1987 i'm not able to reproduce the issue on a mac with the example i gave in my previous comment.

this looks like a site that is built with reactjs.  are you able to provide a simple reactjs example?
