### ISSUE TITLE
Error when parsing date around Daylight Savings Time

### ISSUE THREAD

**Issue by cgledezma1101** [ariya/phantomjs#14935]
Hi.

I'm currently running PhantomJS through Chutzpah in VS2017, with my local time zone set to "Canberra, Melbourne, Sydney". It seems though that the engine is having issues when creating dates around the transition between Australian Daylight Time and Australian Standard Time.

The issue is reproducible with a test that does the following:

	var result = new Date(2017, 3, 1, 16);
	expect(result.getHours()).toBe(16);

This will actually fail, specifying that getHours() returned 17.

The test doesn't fail, nonetheless, when it is run within a browser (Tested in Chrome, FF and IE).

A couple questions, then:

1. Why is the time being offset on "01/04/2017 16:00" if the offset was actually in effect on "02/04/2017 3:00"
2. If I don't provide a time zone for the date, shouldn't the engine assume that I need **exactly** the specified date/time on the current time zone, as opposed to attempting to offset it?

Thanks in advance.

**Comment by jedateach** [comment]
We have seen this same issue recently cause intermittent test failures. We narrowed down the issue this code:
```
console.log(new Date(2017, 8, 24));
```
Displays
 * `Sat Sep 23 2017 23:00:00 GMT+1200 (NZST)` in PhantomJS 2.1.1
 * `Sun Sep 24 2017 00:00:00 GMT+1200 (NZST)` Chrome 61.0.3163.91
