### ISSUE TITLE
How to install phantom js on Mac machine

### ISSUE THREAD

**Issue by sudheer496** [ariya/phantomjs#14938]
Hi ,

I'm on Mac machine, I downloaded zip file from this location https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip

And then extracted the zip file.
What are the next steps to install phantom js?

Thanks,
Sudheer

**Comment by Vitallium** [comment]
Please refer to http://phantomjs.org/quick-start.html

**Comment by sudheer496** [comment]
Hi , I'm not getting anything out of this link.
There are no instructions for installation. The doc says 
**_This instruction assumes that PhantomJS is installed and its executable is placed somewhere in the PATH._**

**Comment by Vitallium** [comment]
Just place it to folder which is in your `PATH` environment variable. For example. in `~/bin`.

**Comment by sudheer496** [comment]
Yeah , I got it I haven't set the path variable . Thanks.
