### ISSUE TITLE
 The highest Firefox version supported by phantomjs ？

### ISSUE THREAD

**Issue by searchmodel** [ariya/phantomjs#14945]
The highest Firefox version supported by phantomjs ？

**Comment by GuilloOme** [comment]
@searchmodel, PhantomJS being a browser, your question do not make much sense…
Could you please be more specific?

**Comment by Vitallium** [comment]
PhantomJS is based on WebKit (QtWebKit to be more specifically). If you want Firefox, you should try [SlimerJS](https://slimerjs.org/)
