### ISSUE TITLE
How to pass GET parameters to page.open()?

### ISSUE THREAD

**Issue by juj** [ariya/phantomjs#14940]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2.1.1

2. What steps will reproduce the problem?

When writing a web page crawler, calling `page.open('foo.html?someparam=value', function(status) { ...` fails with status result `fail`. Reading the documentation at http://phantomjs.org/api/webpage/method/open.html, it is not clear if there is a way to pass GET parameters to the page? Is that supported?

Attempting to modify the `POST` example on the documentation page with something like

> page.open('http://www.google.com/', 'GET', 'someparam=value', ...

does not seem to work at least. Perhaps GET queries could be passed by some other manner I have missed?

3. Which operating system are you using?

Linux Mint 18

4. Did you use binary PhantomJS or did you compile it from source?

binary

**Comment by xakep-amatop** [comment]
For GET method will be right:
> calling page.open('foo.html?someparam=value', function(status) { ...
Make sure that the site exists and there is a connection.

**Comment by juj** [comment]
Thanks for the reply. Further searching I notice that the issue is that GET parameters cannot be passed if the URL is relative, i.e. `foo.html?someparam=value` won't work, as reported in bug #14050. Closing this as duplicate.
