### ISSUE TITLE
unable to run tests on windows "WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1491927081375

### ISSUE THREAD

**Issue by prat23k** [ariya/phantomjs#14946]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
"version":"2.5.0
Serenity version: 1.2.2
2. What steps will reproduce the problem?
  1.i am just running my webtests using serenity and phantom js
  2.
  3.

3. Which operating system are you using?
Windows
4. Did you use binary PhantomJS or did you compile it from source?
binary phantomjs
5. Please provide any additional information below.
[INFO  - 2017-04-11T16:11:17.161Z] GhostDriver - Main - running on port 47267
[INFO  - 2017-04-11T16:11:17.724Z] Session [7e7cdd80-1ed1-11e7-ae0e-1951bd800dbc] - page.settings - {"XSSAuditingEnabled":false,"dpi":96,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/602.1 (KHTML, like Gecko) PhantomJS/2.5.0-development Version/9.0 Safari/602.1","webSecurityEnabled":true}
[INFO  - 2017-04-11T16:11:17.725Z] Session [7e7cdd80-1ed1-11e7-ae0e-1951bd800dbc] - page.customHeaders:  - []
[INFO  - 2017-04-11T16:11:17.725Z] Session [7e7cdd80-1ed1-11e7-ae0e-1951bd800dbc] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.5.0","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"windows-7-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2017-04-11T16:11:17.725Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 7e7cdd80-1ed1-11e7-ae0e-1951bd800dbc
[ERROR - 2017-04-11T16:11:19.230Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1491927079174
[ERROR - ] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1491927081375

**Comment by jesg** [comment]
@prathimak you need ghostdriver 2.0.0 when running phantomjs 2.5.

`driverVersion` should be 2.0.0.
```
{"browserName":"phantomjs","version":"2.5.0","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"windows-7-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
```

 you can use the npm [package](https://www.npmjs.com/package/ghostdriver) and set the `PHANTOMJS_BINARY_PATH` environment variable to the phantomjs 2.5 beta binary.

**Comment by prathimak** [comment]
Thank you jesg. But my selenium version under 3.0 do you think still i can use phantomjs 2.5.0

**Comment by prathimak** [comment]
if i am using old one i got below error

Apr 12, 2017 2:26:23 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--webdriver=16140]
Apr 12, 2017 2:26:23 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
[INFO  - 2017-04-12T13:26:25.482Z] GhostDriver - Main - running on port 16140
[INFO  - 2017-04-12T13:26:26.270Z] Session [a1223580-1f83-11e7-8cfc-95977521208f] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1","webSecurityEnabled":true}
[INFO  - 2017-04-12T13:26:26.270Z] Session [a1223580-1f83-11e7-8cfc-95977521208f] - page.customHeaders:  - {}
[INFO  - 2017-04-12T13:26:26.270Z] Session [a1223580-1f83-11e7-8cfc-95977521208f] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"windows-7-32bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2017-04-12T13:26:26.270Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: a1223580-1f83-11e7-8cfc-95977521208f
[ERROR - 2017-04-12T13:26:28.015Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1492003588009

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-04-12T13:26:30.261Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1492003590255

  phantomjs://platform/console++.js:263 in error
[ERROR - 2017-04-12T13:26:32.492Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1492003592483

**Comment by jesg** [comment]
@prathimak you are running ghostdriver 1.2.0.  phantomjs 2.5 beta requires ghostdriver 2.0.0.

see my previous comment on how to run ghostdriver 2.0.0 on pantomjs 2.5 beta or wait for the official phantomjs 2.5 release.

**Comment by kensoh** [comment]
@jesg do you know the state of things for PhantomJS? After maintainer Vitaly's announcement in April that he is stepping down. And Chrome headless is coming, Firefox headless is coming.

I really hope and still believe someone or organization would step up to take on the baton. After all, so much vested interests have been made in the PhantomJS ecosystem. Or at least some form of mitigation steps to ease any transition. Vitaly has a dummy Phantonium repo now, following it.

**Comment by jesg** [comment]
> do you know the state of things for PhantomJS?

* phantomjs does not have an active maintainer
* phantomjs 2.5 beta has some quirks that make it unusable in most real world cases (see issues with 2.5 in it)
* i'm the current active maintainer of ghostdriver ... through there is no point in making updates when the parent project is stalled out

neither chrome headless or firefox headless are ready for selenium users.

> I really hope and still believe someone or organization would step up to take on the baton.

same here.  though maintaining a web browser across 3 different platforms is a colossal undertaking.  the phantomjs devs made an honest effort to recruit more devs but did not get any takers.  hence i wouldn't have high hopes.

**Comment by kensoh** [comment]
Thank you ver much @jesg for your generous sharing. I understand more now.

My vested interest is in CasperJS and a general purpose [web automation tool](https://github.com/tebelorg/TagUI) I made. CasperJS has intention to try to support Chrome headless. And there's Firefox headless direction through SlimerJS.

I try to look through CasperJS/PhantomJS open issues to see if anything I can contribute. CasperJS side made good progress past week. For PhantomJS after browsing through looks like I can't contribute much as my experience was through CasperJS layer.

**Comment by prat23k** [comment]
Hi,

Still i can see this issue with the below versions

I am using with serenity and i set the birnary path as well
"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"windows-7-32bit",


Can you please help me resolve this
