### ISSUE TITLE
cookies won't load/work

### ISSUE THREAD

**Issue by nkaywon** [ariya/phantomjs#14952]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
    2.1.1
2. What steps will reproduce the problem?
  See the code attached

3. Which operating system are you using?
    Windows 10
4. Did you use binary PhantomJS or did you compile it from source?
    binary
5. Please provide any additional information below.

```
var page = require('webpage').create(),
	fs = require('fs');

phantom.cookiesEnabled = true;

var viewportSize = {
	width: 1280,
	height: 918
};


page.settings.userAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36';
page.viewportSize = viewportSize;
page.zoomFactor = 1;

restoreCookies();

page.open('http://www.whatarecookies.com/cookietest.asp', function(status){
	if (status !== 'success') {
		console.log('FAIL to load the address');
		phantom.exit();
	} else {
		console.log('/ Navigated to http://www.whatarecookies.com/cookietest.asp /');
		setTimeout(function(){
			page.render('entirepage.png');
			saveCookies();
			phantom.exit();
		}, 5000)
	}
});

function saveCookies() {
	var cookies = JSON.stringify(phantom.cookies);
	fs.write("cookie.txt", cookies, "w");
}

function restoreCookies() {
	var cookieFileName = 'cookie.txt';
	if (fs.exists(cookieFileName)){
		console.log('here');
		var cookies = fs.read(cookieFileName);
		phantom.cookies = JSON.parse(cookies);
	} else {
		console.log('there');
	}
}
```

Please, try my script out. I'm using this cookie test:[http://www.whatarecookies.com/cookietest.asp](url)
It works perfectly on any browser, but when I'm trying to make this working on phantom, I always get "no existing cookie was found for this website" message as if I would navigate to this site for the first time. 

The cookies ARE saved with success to the file and they also are loaded successfully (at least looks like), but nothing changes on the website. Please, point me to the right direction...

**Comment by nkaywon** [comment]
I just realised what IS the problem but how should I fix it?

So, I tried to manually add each cookie using .addCookie method and this is what I got:
```
www.whatarecookies.com
false
www.whatarecookies.com
false
www.whatarecookies.com
false
.whatarecookies.com
false
.whatarecookies.com
true
.www.whatarecookies.com
true
.www.whatarecookies.com
true
```

So, half of cookies were not added... Guess why? What should I do? :/

**Comment by kensoh** [comment]
@nkaywon this is interesting issue. I'm a CasperJS user for couple of years, now browsing through open issues on CasperJS/PhantomJS. Can you try maybe wait 5 seconds after page loading before saving cookie and image?

The gist is I wrote a tool for [web automation](https://github.com/tebelorg/TagUI) on CasperJS + PhantomJS. When I run the following 3 times, the expected results appear to show that cookies are being tracked correctly and the number of visits correct. This mean that fundamentally PhantomJS cookies should surely work. But I am not too familiar with using PhantomJS directly to add more inputs.

`tagui below_script --cookies-file=cookies.txt`

```
http://www.whatarecookies.com/cookietest.asp
wait 5 seconds
snap page
```
