### ISSUE TITLE
Phantomjs fails to support ES2016 exponentiation operator (**)

### ISSUE THREAD

**Issue by mondwan** [ariya/phantomjs#14951]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

```
$ phantomjs --version
2.1.1
```

2. What steps will reproduce the problem?

```
$ phantomjs
phantomjs> Math.pow(2, 2)
4
phantomjs> 2 ** 2
Unexpected token '*'

  phantomjs://repl-input:1 in global code
phantomjs> 2 * 2
4
```

3. Which operating system are you using?

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

4. Did you use binary PhantomJS or did you compile it from source?

Binary

5. Please provide any additional information below.

`**` is a feature of ES2016. Would phantomjs support ES2016?

**Comment by Vitallium** [comment]
Could you try again with 2.5 [binary](https://bitbucket.org/ariya/phantomjs/downloads) please? Thanks!

**Comment by mondwan** [comment]
Sorry for late reply. It does work neither on 2.5.

```
C:\Users\Mond Wan\phantomjs-2.5.0.beta-windows\bin>phantomjs.exe --version
2.5.0-development

C:\Users\Mond Wan\phantomjs-2.5.0.beta-windows\bin>phantomjs.exe

phantomjs> 2 ** 2
Unexpected token '*'
phantomjs> Math.pow(2, 2)
4
phantomjs> 2 * 2
4
phantomjs>
```

**Comment by ariya** [comment]
Modern JavaScript features (from ES6/ES2015 or later) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
