### ISSUE TITLE
PhantomJS has crashed

### ISSUE THREAD

**Issue by psalnikov** [ariya/phantomjs#14955]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`. 
1.9.7
2. What steps will reproduce the problem?
  1. switch to third iframe
  2. switch to first iframe
  3. click on <a> selector

3. Which operating system are you using?
Ubuntu 16.04 LTS
4. Did you use binary PhantomJS or did you compile it from source?
binary PhantomJS
5. Please provide any additional information below.

**Comment by bologer** [comment]
@psalnikov, we need to least minimum code example and dump if exists. 

Also, if process of phantomjs stays in the memory, you may use `try catch` blocks to exit phantomjs safely.
