### ISSUE TITLE
[v2.5.0-development] remote debug/web inspector interface not rendering correctly

### ISSUE THREAD

**Issue by GuilloOme** [ariya/phantomjs#14950]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
v2.5.0-development

2. What steps will reproduce the problem?
  1. run in remote debug mode: `--remote-debugger-port=xxxx` 
  2. the interface look like that:
![screenshot from 2017-04-12 10-11-48](https://cloud.githubusercontent.com/assets/247594/24961976/7a8a69e4-1f68-11e7-9e8b-437b7cae019f.png)
![screenshot from 2017-04-12 10-11-10](https://cloud.githubusercontent.com/assets/247594/24961980/7d1367e2-1f68-11e7-98f0-cf28f7b3f2d0.png)
 
3. Which operating system are you using?
Ubuntu xenial (16.04)

4. Did you use binary PhantomJS or did you compile it from source?
Binary from bitbucket repo

5. Please provide any additional information below.
The main concern is that some element of the interface are not usable because of that.

**Comment by Vitallium** [comment]
This is a known problem with TP5 of new QtWebKit. We have fixed this in master branch - https://github.com/annulen/webkit

**Comment by GuilloOme** [comment]
@Vitallium, is there any plan to update the development binary present in the bitbucket repo? 
I tryed to compile it myself but it's not really a straight path (even when following the instruction from #14458)
thank,

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.
