### ISSUE TITLE
PhantomJS crashes, can't find dump anywhere

### ISSUE THREAD

**Issue by turalus** [ariya/phantomjs#14963]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1.  Downloaded and unarchived phantomjs-2.1.1-linux-x86_64.tar.bz2 from official website
  2.  mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
  3.  sudo ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin

3. Which operating system are you using?
Ubuntu 16.10 (Yakkety)
4. Did you use binary PhantomJS or did you compile it from source?
Binary
5. Please provide any additional information below.
It works normally, at some random point crashes with message:

PhantomJS has crashed. Please read the bug reporting guide at
 and file a bug report.

neither in /tmp nor in script's folder, I can't find crash dump.

Where are crash dumps in Ubuntu 16.10?

**Comment by bologer** [comment]
@turalus, you may wrap code into `try catch` block and if it catches error, you may save stacktrace in the file (e.g. dump.txt) using [file system module](http://phantomjs.org/api/fs/). This is one solution I can suggest. And each time when script crushes or send errors, it will save information in the same file. This is what I am currently doing. You may also add some other information such as current date and time, etc.

**Comment by earth2016** [comment]
@bologer where did you use try-catch? i am using phpstorm and i have edited C:\<my_user>\.PhpStorm2017.1\config\plugins\js-karma\js_reporter\karma-intellij\lib\intellijServer.js

I couldn't see the issue but it happens to me. Sometimes is ok but antoher times failed. It's a bug ghost!

**Comment by bologer** [comment]
@earth2016, you may wrap the whole code into the `try catch` block. And in case something fails, it will use `catch`, where you define the `phantomjs.exit()` to exist the running process.

This could be an example: 

```js
'use strict';
var page = require('webpage').create();
page.settings.loadImages = false;
page.settings.resourceTimeout = 20000;
page.settings.userAgent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36';
try {
    page.open('https://google.com/', function (status) {
        page.viewportSize = { width: 1024, height: 900 };
        ...
    });
} catch(e) {
    console.log('Error happened.');
    console.log(e);
    phantom.exit();
}
page.onInitialized = function(){
    ...
};
```
Another way would be using `onError` callback, that catches any errors that happened within the code. 

Ref: http://phantomjs.org/api/phantom/handler/on-error.html

```js
'use strict';
var page = require('webpage').create();
phantom.onError = function(msg, trace) {
  var msgStack = ['PHANTOM ERROR: ' + msg];
  if (trace && trace.length) {
    msgStack.push('TRACE:');
    trace.forEach(function(t) {
      msgStack.push(' -> ' + (t.file || t.sourceURL) + ': ' + t.line + (t.function ? ' (in function ' + t.function +')' : ''));
    });
  }
  console.error(msgStack.join('\n'));
  phantom.exit(1);
};
page.settings.loadImages = false;
page.settings.resourceTimeout = 20000;
page.settings.userAgent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36';

...
```
