### ISSUE TITLE
90070BB44EEF.dmp

### ISSUE THREAD

**Issue by Edrauda** [ariya/phantomjs#14966]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2. What steps will reproduce the problem?
  1.
  2.
  3.

3. Which operating system are you using?

4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.

**Comment by xhlwill** [comment]
❓

**Comment by kensoh** [comment]
@xhlwill wow. @Edrauda is this some automated posting of issue or a typo?
