### ISSUE TITLE
rasterize.js HTML generation pdf Display error in firefox

### ISSUE THREAD

**Issue by xhh110** [ariya/phantomjs#14969]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
> 2.0.1-development
2. What steps will reproduce the problem?
  > *  rasterize.js HTMLGeneration Pdf display error，font is not display incomplete In firefox
  > * Is not a system, Firefox version, the resolution of the problem，Because win7 will also be the problem

3. Which operating system are you using?
 window Xp
4. Did you use binary PhantomJS or did you compile it from source?
use PhantomJS 
5. Please provide any additional information below.
this error is in Browser，download this pdf is No problem
![picture](http://oo4uyf3x3.bkt.clouddn.com/error.png)

**Comment by xhh110** [comment]
who can help me？

**Comment by kensoh** [comment]
Hi @xhh110 I'm a CasperJS user for couple of years, now browsing through open issues on CasperJS/PhantomJS. Looks like you want to capture screenshot of some websites.

Maybe you can try using a newer version of PhantomJS v2.1.1 and see if this happens? And share the script / website that you use where this error happens. I haven't try capturing images with Chinese fonts before.

**Comment by xhh110** [comment]
@kensoh I have a try. but v2.1.1 can't solve it..it solve en and number... but it not solve chinese...

**Comment by kensoh** [comment]
Hi @xhh110 I see.. Really strange error. The only other way I think may be possible is tweaking with it's CSS to change font size. But that is a strange way to solve this problem, and I haven't try something like that to know exactly how to do it correctly.

**Comment by xhh110** [comment]
@kensoh  i can‘t solve it too。。
