### ISSUE TITLE
Crashes when external fonts are loaded. 

### ISSUE THREAD

**Issue by PokerPro123** [ariya/phantomjs#14960]
1. Which version of PhantomJS are you using? 2.0

2. What steps will reproduce the problem?
**Run the PhantomJS .exe from a network drive.**
Load a page with an external font referenced within a CSS file.

Example:
@font-face {
	font-family:"Minion Pro";
	font-style:normal;
	font-weight:bold;
	src : url("../font/MinionPro-Bold.otf");
}

span.test {
	font-family:"Minion Pro";
	font-style:normal;
}

Load the page a few times via PhantomJS. 

**NOTE: 70% of the time, phantomJS will crash. Sometimes the page will render though...**

Exception message from the crash dump file: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

I cannot attach the crash dump files... Even if I zip them.

3. Which operating system are you using? Windows 7

4. Did you use binary PhantomJS or did you compile it from source? binary

5. Please provide any additional information below.

**Comment by PokerPro123** [comment]
Interesting... The attached file is actually a .zip (which will not upload).
So I changed the file extension to .PDF and it works LOL!.

1, Download CrashDump.pdf and rename it CrashDump.zip, then you can extract the 9 crash dump files. 
[CrashDump.pdf](https://github.com/ariya/phantomjs/files/926741/CrashDump.pdf)

**Comment by kensoh** [comment]
Hi @PokerPro123 I'm a CasperJS user for couple of years, now browsing through open issues on CasperJS/PhantomJS. If you try running with newer PhantomJS v2.1.1 and run it locally on your PC instead of network drive will the same issue happen?
