### ISSUE TITLE
Some third party software installed phantomjs to my computer but i cannot remove it now or i cannot execute its .exe, it keeps poping up pls help

### ISSUE THREAD

**Issue by agemennon675** [ariya/phantomjs#14962]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
no idea
2. What steps will reproduce the problem?
  1.
  2.
  3.

3. Which operating system are you using?
win10
4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.

**Comment by itsusony** [comment]
It's not an issue. you can reinstall your os.

**Comment by agemennon675** [comment]
Well I already did that, and closed session.exe and deleted session.exe then stopped phantomjs is a headless bla bla and deleted phantomjs.exe with entire multisessions folder but it creates a new one everytime i restart my computer

**Comment by agemennon675** [comment]
Really need some help about it, it creates a folder for itself in windows called ''Multisessions'' it recreates istself cant find the source :( Takes some of my internet and %5 of my cpu ..

**Comment by kensoh** [comment]
@agemennon675 this is very strange software. Could it be some malware that persists? Sounds like need to contact the creator of that software as the code to keep reinstalling is controlled by it not PhantomJS.

**Comment by agemennon675** [comment]
Maybe but I already uninstalled the software that installed phantomjs in my MultiSessions folder, now I only have its icon

**Comment by kensoh** [comment]
After uninstalling the 3rd-party software, if you notice that the software is reinstalled by itself, maybe some hidden update code/program left behind by the software to secretly re-install itself again.

**Comment by agemennon675** [comment]
Software is not re-installing itself, only the phantomjs part

**Comment by agemennon675** [comment]
![error](https://cloud.githubusercontent.com/assets/22632862/26449645/06fd6b1e-415c-11e7-86b5-2c4f88eeb73e.png)

**Comment by kensoh** [comment]
Looks like the 3rd-party software is corrupted, above image shows when you try to uninstall it is unable to uninstall. For PhantomJS executable setup, there is only 1 file phantomjs.exe and nothing else. If you try to delete the phantomjs.exe it will be gone. But don't know what the other files in that folder are for. Probably some sub-programs that your 3rd-party software tries to install.

**Comment by agemennon675** [comment]
Yeah but it also recreates phantomjs.exe and session.exe whenever i restart my pc

**Comment by kensoh** [comment]
I'm a CasperJS user for couple of years, which is base on PhantomJS. But don't think any expert on PhantomJS can advise how to handle this. Because PhantomJS is only phantomjs.exe and does not auto-install back.

If you try to delete the folder away and comes back, the 3rd-party program maybe has some start-up or hidden script that tries to reinstall this whole folder. What I'm trying to say is phantomjs.exe does not have ability to auto-install itself after deletion. Some other program is controlling this, probably the 3rd-party program you are using.

**Comment by agemennon675** [comment]
I understand :) Thank you for your interest ;)

**Comment by kensoh** [comment]
No probs! Probably you have tried to contact the 3rd-party software provider and no response, that's why you are raising this issue here :)

**Comment by agemennon675** [comment]
I didnt because I realized this long after I delete the 3rd-party software, and now i cannot remember what was that :)

**Comment by kensoh** [comment]
Oh I see.. That will be tricky. Hmm if after too long it is also not safe to use windows restore to turn back time. Will lose many files.

**Comment by kensoh** [comment]
I think Windows administrator or expert friend maybe can look at your Windows to check where the software do that secret installation thing every time you restart PC.

**Comment by agemennon675** [comment]
Yeah :( I will give it a shot

**Comment by kensoh** [comment]
Thanks @agemennon675, not necessary to close. You may want to keep it open to share your findings later on. Maybe other people have the same issue with the 3rd-party software. This is interesting but strange issue..

**Comment by agemennon675** [comment]
You might be right, I will write the further information that I gather from now on.
