### ISSUE TITLE
Element is not currently visible and may not be manipulated exception

### ISSUE THREAD

**Issue by nesttle** [ariya/phantomjs#14979]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
`2.1.1` and `1.9.0`
2. What steps will reproduce the problem?
 

- 1.  1. Go to: https://accounts.google.com/signin/v2/identifier?flowName=GlifWebSignIn&flowEntry=ServiceLogin
- 2.   2. Insert user > Next > Insert password > Login
- 3.   3. Error (Insert password): Element is not visible.

3. Which operating system are you using?
`Ubuntu 14 x64`
4. Did you use binary PhantomJS or did you compile it from source?
`Binary`
5. Please provide any additional information below.
```
            WebElement un= driver.findElement(By.id("identifierId"));
            un.click();
            un.sendKeys("user@name.com");
            Thread.sleep(3000);

            driver.findElement(By.xpath(".//*[@id='identifierNext']/content/span")).submit();
            Thread.sleep(3000);

            WebElement pw =driver.findElement(By.name("password"));
            pw.click();
            pw.clear();
            pw.sendKeys("mypassw123");
            Thread.sleep(3000);
            driver.findElement(By.xpath(".//*[@id='passwordNext']/content/span")).submit();
```

Error:
```
"errorMessage":"Element is not currently visible and may not be manipulated",
"request"
```

**Comment by happy0412** [comment]
driver.findElement(By.xpath(".//*[@id='passwordNext']/content/span")).click();  this piece of code doesn't work could you please help

**Comment by filtration** [comment]
IWebDriver driver = new FirefoxDriver();
            driver.Navigate().GoToUrl("https://www.gmail.com/");
            IWebElement query = driver.FindElement(By.Id("identifierId"));
            query.Click();
            query.SendKeys("email");

            driver.FindElement(By.XPath("//*[@id=\"identifierNext\"]")).Click();
            Thread.Sleep(3000);
            IWebElement pw = driver.FindElement(By.Name("password"));
            pw.Click();
            pw.Clear();
            pw.SendKeys("corkish1");
            driver.FindElement(By.XPath("//*[@id=\"passwordNext\"]")).Click();
            Thread.Sleep(3000);

**Comment by kensoh** [comment]
@filtration's code looks good :) I know its personal preference, I'm lazy in typing, so I use single-quote '' for the XPath string and double-quote for the parameter inside XPath. @nesttle not sure why you have a . in front of your XPath. May not be necessary to extend all the way to the individual child element of the NEXT word. Clicking on parent normally works and gets interpreted as a click anyway. Also submit isn't appropriate, click is for clicking on the button.
