### ISSUE TITLE
Can't click on any element on a page (XHR requests)

### ISSUE THREAD

**Issue by piotrjaworski** [ariya/phantomjs#14984]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
`2.1.1`
2. What steps will reproduce the problem?
  1.1 Run the first example with: `phantom app.js`
  1.2 `open youtube.png`
  2.1 Run the second example with: `phantom app.js`
  2.2 `open yahoo.png`

3. Which operating system are you using?
`macOS Sierra 10.12.4 (16E195)`

4. Did you use binary PhantomJS or did you compile it from source?
I installed it via `brew install phantomjs`.

5. Please provide any additional information below.
I wrote a script which tries to sign in to YouTube. After when Google updated their styles, I changed it and rewrote it. As far I noticed, phantomJS can't click at any on an element on a page. I don't have any idea why... All elements on a page exist, IDs are correct. Here is the source code:
```javascript
console.log('Loading a web page');
var page = require('webpage').create();
var url = 'https://accounts.google.com/signin/v2/identifier?hl=en&uilel=3&service=youtube&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Ffeature%3Dsign_in_button%26next%3D%252F%26hl%3Den%26action_handle_signin%3Dtrue%26app%3Ddesktop&flowName=GlifWebSignIn&flowEntry=ServiceLogin';
page.open(url, function() {
  page.evaluate(function() {
    document.getElementById('identifierId').value = "test@test.com";
    document.getElementBtId('identifierNext').click();
  });
  setTimeout(function(){
    page.render("youtube.png");
    phantom.exit();
  }, 5000);
});
```
Result, I wasn't redirected to the next page, unable to click any button:
![youtube](https://cloud.githubusercontent.com/assets/5247571/25772999/19b3fe7a-3276-11e7-9d48-a2460bfee812.png)

I rewrote this code to test it on other pages - Yahoo. Everything works as expected. Here is the code:
```javascript
console.log('Loading a web page');
var page = require('webpage').create();
var url = 'https://www.yahoo.com/';
page.open(url, function() {
  page.evaluate(function() {
    document.getElementById('uh-search-box').value = "test@test.com";
    document.getElementById('uh-search-button').click();
  });
  setTimeout(function(){
    page.render("yahoo.png");
    phantom.exit();
  }, 5000);
});
```
Result, I was redirected to the next page:
![yahoo](https://cloud.githubusercontent.com/assets/5247571/25772998/19b3dc24-3276-11e7-9d3b-70b63cbef998.png)

**Comment by karenpetrie** [comment]
@piotrjaworski I'm also getting this same issue. Have you had any luck resolving?
I've got a wait set for an element to no longer be visible on the page (loading icon) but the tests are just timing out as the XHR request doesn't complete.

It was working before as I've been running my tests for a long time.

**Comment by piotrjaworski** [comment]
@karenpetrie Yeah, I found a fix today, finally!

You need to specify a userAgent, for example:
`"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11"`

and run it as: `phantomjs --ssl-protocol=any app.js `

**Comment by kensoh** [comment]
Cool! Seconding that, have experienced that Google explicitly shows a different website for PhantomJS headless browser. User Agent option will 'fake' the browser's identity. 

This is a useful article by a friend which shares some other tips on making automated browsers appear real. Solid stuff which you may find helpful.. https://franciskim.co/dont-need-no-stinking-api-web-scraping-2016-beyond/

Though normally I respect webowner's decision not to serve automated browsers and just leave them alone.
