### ISSUE TITLE
Can Play HTML5 videos in background

### ISSUE THREAD

**Issue by ccmoralesj** [ariya/phantomjs#14985]
Hey there,

I've been looking all over the internet for a solution to this particular situation. I have to say I have read the **Supported/Unsupported Web standards** but there it says "_Video and Audio would require shipping a variety of different codecs._" and I was wondering can I do it for myself in some way? Any idea of how to do so? I just need to play webm (vp9 codec) videos, so I was wondering how to support it on phantom? Any idea? How do I "ship" that specific codec?

**Comment by umokk** [comment]
GStreamer may save you.
