### ISSUE TITLE
PhantomJS is not capturing images from div having style as overflow hidden.

### ISSUE THREAD

**Issue by rkumar-c** [ariya/phantomjs#15001]
Hi,
I am using PhantomJS 2.1.1 to capture the screenshot of a webpage.  The page has three divs with style overflow hidden and auto property.  Unfortunately PhantomJS is capturing only top div image and ignoring other div images. Following is the URL for which I am getting issue:
URL : https://item.mercari.com/gl/m56999829099/

Captured images is below:

![screenshot1](https://cloud.githubusercontent.com/assets/22680503/26311172/2c514c88-3eb8-11e7-96f7-11c91a33ed16.png)

Please help me out to fix it as soon as possible.
Rakesh.

**Comment by JustinYi922** [comment]
Please past you code here.Perhaps somebody will help you.

**Comment by bologer** [comment]
@rkumar-c, what do you mean by overflow elements? For example, the menu that slides horizontally and only a few elements shown at the beginning? In this case, it will not show you all elements of the menu, because it is hidden (you will need to slide to see other elements) and you will receive the same result if you would open this webpage with a normal mobile device.

**Comment by rkumar-c** [comment]
I need to capture the screenshot of desktop webpage not from mobile devices. I understand that there is scroll  but at least images should be captured whatever is visible. If you will look at image, in second and third frame no images are captured.  I achieved this by writing custom js inside page.evaluate and here is the code:

    page.evaluate(function() {
   var box=document.getElementsByClassName("items-box-photo");
  for(i=0; i<box.length; i++)
  { 
  //	var myimg = box[i].getElementsByTagName('img')[0];
	var someimage = box[i].children[0].getAttribute('data-src');
       console.log("image src " + someimage);
                   box[i].innerHTML= " <img src='"+someimage+"'>";
   }
       });
But this is page specific and we can not run it capture any webpages. Now I am facing issue to capture screenshot of webpages with ajax and lazy loading like amazon.in or http://www.shopclues.com/fashion.html

So is there way to write common code and to capture screenshot of webpage like amazon or any other with lazy load webpages?

**Comment by kensoh** [comment]
I'm a CasperJS/PhantomJS user for couple of years. Hmm normally images don't show up because they haven't completed loading. Not sure if explicitly waiting before capturing the images will help.

**Comment by bologer** [comment]
@rkumar-c, make sure check that you don't have

```js
page.settings.loadImages = false
```
Once I have activated this setting in the script and could not understand why images were not loading for me.

**Comment by JustinYi922** [comment]
虽然我英文不好，大概的意识好像是捕获图片的时候，只捕获到左面的部分，不是完整的宽度。如果是，你试试
var bb = page.evaluate(function () {
                return document.body
            });
        // 按照实际页面的高度，设定渲染的宽高
        page.clipRect = {
            top: 0,
            left: 0,
            width: bb.clientWidth,
            height: bb.clientHeight
        };

**Comment by JustinYi922** [comment]
突然想到我也遇到这样的问题。我在html文件里面只输入了几个文字，结果render出来的图片大小是400*300的。好像是phantomjs的最小长宽。 @bologer 是不是phantomjs确实做了默认的设置？

**Comment by rkumar-c** [comment]
I am not getting the full page screenshot for following two URLs:
  https://shop.adidas.co.in/#c/men-basketball-shoes/Pag-60/No-0/0
  http://www.lifestylestores.com/c/men-tops-tshirts

Can anybody provide sample code to capture screenshot for above URLs.

**Comment by kensoh** [comment]
I'm not expert at PhantomJS, but for a general purpose [web automation tool](https://github.com/tebelorg/TagUI) that I make (base on CasperJS/PhantomJS), the code is below. I get Adidas logo only for second row of images onwards. For the second website, it is blank image for below and also when I use Safari browser. Not sure what is wrong with the website that I cannot even also with real browser.

```
https://shop.adidas.co.in/#c/men-basketball-shoes/Pag-60/No-0/0
wait 10 seconds
snap page to adidas.png
http://www.lifestylestores.com/c/men-tops-tshirts
wait 10 seconds
snap page to lifestore.png
```

**Comment by bologer** [comment]
@rkumar-c your problem with the first website is the loading time. For some reason it takes around 20 seconds to load all images and everything on the website. 

This is what I received on 15 secs, so I assume that you will have all images loaded on 20secs.

## Screenshot 
![1](https://cloud.githubusercontent.com/assets/9879933/26511867/21b575b0-4264-11e7-8bb8-8239bb6d8284.png)


## Source code
```js
var p = p || {};

p.adidas = {

	webpage:	false,
	system:		false,
	page:		false,
	url:		false,
	userAgent:	false,
	newsJSON: 	false,
	newsString: false,

	init: function() {
		this.webpage	= require('webpage');
		this.fs 		= require('fs');
		this.page		= this.webpage.create();
		this.url		= 'https://shop.adidas.co.in/#c/men-basketball-shoes/Pag-60/No-0/0';
		this.userAgent	= 'Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0';
		this.timeout	= 20000;
		this.log		= '[ =========> ] ';
	},

	solve: function() {
		var self = this;
		this.page.settings.userAgent = this.userAgent;
		this.page.viewportSize = { width: 1024, height: 900 };

		this.page.open(this.url, function(status) {

			console.log(self.log + 'Page loaded');

			try {
				setTimeout(function() {

					console.log(self.log + 'Timeout finished.');
					

					self.page.render('1.png');

					console.log(self.log + 'Picture taken');

					console.log(self.log + 'Job should be finished now');
					phantom.exit()
				}, self.timeout);
			} catch(e) {
				console.log('PhantomJS has unexpectable stopped working. Date: ' + new Date().toUTCString());
				phantom.exit(); 
			}
		});
	}
}

p.adidas.init();
p.adidas.solve();
```

**Comment by rkumar-c** [comment]
@bologer  I tried the above code but fails to capture all the images, this is also happening with ebay and alibaba websites. What could be the reason for not capturing all the images, I increased the timeout 90000 but that also didn't work.

**Comment by bologer** [comment]
@rkumar-c, alright, I will test my code a bit more and will try to output working solution :+1:

**Comment by kensoh** [comment]
Also adding on, invisible browsers such as PhantomJS or Electron (through NightmareJS) are different in behaviour from real browsers such as Chrome or Safari. And website owners often add logic to prevent invisible / automated browsers from working correctly.

This is a nice post by a friend on this topic. Although I normally will not automate for websites which don't want to serve automated browsers. https://franciskim.co/dont-need-no-stinking-api-web-scraping-2016-beyond

Other possible setups could be using Selenium + Chrome + Xvfb or maybe SikuliX + Xvfb to replicate exact browsers behavior. Also, headless Chrome is here (Firefox headless soon too). Tools such as [CasperJS](https://github.com/casperjs/casperjs) which have intention to support headless Chrome or [Chromy](https://github.com/OnetapInc/chromy) can also be considered.

**Comment by bologer** [comment]
@rkumar-c, if purpose of this threat to get images of the product from let's say Adidas, then the following code can be used. It is not required to load the images unless the whole DOM has loaded, than you can scrap the URL of the images and recursively saved them as you wish. 

I have written everything until recursive saving, this all on you. 

```js
var p = p || {};

p.adidas = {

	webpage:	false,
	system:		false,
	page:		false,
	url:		false,
	userAgent:	false,
	newsJSON: 	false,
	newsString: false,

	init: function() {
		this.webpage	= require('webpage');
		this.fs 		= require('fs');
		this.page		= this.webpage.create();
		this.url		= 'https://shop.adidas.co.in/#c/men-basketball-shoes/Pag-60/No-0/0';
		this.userAgent	= 'Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0';
		this.timeout	= 6000;
		this.log		= '[ =========> ] ';
	},

	solve: function() {
		var self = this;
		this.page.settings.userAgent = this.userAgent;
		this.page.viewportSize = { width: 1024, height: 900 };

		this.page.open(this.url, function(status) {

			console.log(self.log + 'Page loaded');

			try {
				setTimeout(function() {

					console.log(self.log + 'Timeout finished.');

					var imageUrls = self.page.evaluate(function() {
						var q = document.querySelectorAll('.productListing li.card');
						var obj = {};
						var length = q.length - 1;

						for(var i = 0; i <= length; i++) {
							obj[i] = {
								name: q[i].querySelector('.adidasOriginals.productIdentifier').innerText.trim(),
								src: q[i].querySelector('.productImageWrap > img').getAttribute('data-src').trim().replace(/\.plp$/gi, '')
							};
						}

						return obj;
					});
					

					self.page.render('1.png');

					console.log(self.log + 'Picture taken');

					console.log(self.log + 'Job should be finished now');

					console.log(self.log + 'Images:');

					console.log(JSON.stringify(imageUrls));

					self.fs.write('urls.txt', JSON.stringify(imageUrls));

					phantom.exit()
				}, self.timeout);
			} catch(e) {
				console.log('PhantomJS has unexpectable stopped working. Date: ' + new Date().toUTCString());
				phantom.exit(); 
			}
		});
	}
}

p.adidas.init();
p.adidas.solve();
```

Though I am not sure if this is what you are looking for. 

> I am still trying to understand why it is not allowing to load all images form the website even if you put huge timeout on the load of the page (e.g. 30 secs). 

I will try again and give you the results :+1:

**Comment by kensoh** [comment]
Cool stuff! Thanks @bologer for sharing! :smile:

**Comment by rkumar-c** [comment]
Thanks guys for promptly replying to the issue with solutions, I really appreciate solution given by @bologer and it was very much helpful to me.
Here I am closing this thread and once again thanks to @bologer.
