### ISSUE TITLE
Phantom 2.1.1 chokes on string.startsWith()

### ISSUE THREAD

**Issue by RichardNeill** [ariya/phantomjs#15006]
string.startsWith() has been part of javascript for sometime now. It's widely supported in modern browsers. However, it makes phantomJS fail rather badly. (Similar failures affect wkhtml2pdf).

To see it, look at the attached html file (a very simple test-case), and view it in a web browser. 
Comment out either of the .startsWith() or .match() lines, and it works the same.

Then try ./phantomjs rasterize.js ~/test.html test.pdf
the startsWith() line causes it to complain:
  TypeError: undefined is not a function (evaluating 'aaa.startsWith("alpha")')

[test.txt](https://github.com/ariya/phantomjs/files/1024377/test.txt)

**Comment by BobbyCannon** [comment]
I'm also seeing this behavior

**Comment by hayd** [comment]
Is this closed because it is fixed?

**Comment by cxiao84** [comment]
@hayd 

> @RichardNeill @BobbyCannon @hayd Please see [this](http://phantomjs.org/anon)

Not Found. How to fix?
