### ISSUE TITLE
Phantomjs throws error, on destructuring assignment(ES2015 feature) in JS code.

### ISSUE THREAD

**Issue by shroffshyam** [ariya/phantomjs#15029]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
1.14

3. Which operating system are you using?
OSX

4. Did you use binary PhantomJS or did you compile it from source?
karma-phantom-launcher

**Comment by SeqviriouM** [comment]
ES6 features will be possible with the new version 2.5 https://github.com/ariya/phantomjs/issues/14506
