### ISSUE TITLE
Requests to WebDriver endpoint with Transfer-Encoding: Chunked fail

### ISSUE THREAD

**Issue by jonhoo** [ariya/phantomjs#15037]
1. Which version of PhantomJS are you using?
2.1.1

2. What steps will reproduce the problem?
  1. Start PhantomJS with a WebDriver:
```console
$ phantomjs --webdriver=4444
```
  2. Send a new session request with `Transfer-Encoding: chunked`
```console
$ echo '{"desiredCapabilities":{},"requiredCapabilities":{}}' | curl -N -X POST --data-binary @- -H "Transfer-Encoding: chunked" -H 'Content-Type: application/json' http://localhost:4444/session -v
* Connected to localhost (127.0.0.1) port 4444 (#0)
> POST /session HTTP/1.1
> Host: localhost:4444
> User-Agent: curl/7.54.1
> Accept: */*
> Transfer-Encoding: chunked
> Content-Type: application/json
```
  3. Observe that the response gives a `400 Bad Request` with the "Missing Command Parameter" error:
```text
HTTP/1.1 400 Bad Request
Cache: no-cache
Content-Length: 434
Content-Type: text/plain

Missing Command Parameter - {"headers":{"Content-Type":"application/json","Host":"localhost:4444","Transfer-Encoding":"chunked"},"httpVersion":"1.1","method":"POST","url":"/session","urlParsed":{"anchor":"","query":"","file":"session","directory":"/","path":"/session","relative":"/session","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/session","queryKey":{},"chunks":["session"]}}⏎
```
  4. Observe that removing the chunked encoding (by removing `Transfer-Encoding: chunked`) so that `Content-Length: 53` is sent instead works just fine.

3. Which operating system are you using?

Arch Linux.

4. Did you use binary PhantomJS or did you compile it from source?

Binary distribution.

5. Please provide any additional information below.

It seems like the request body is omitted from the post body in https://github.com/ariya/phantomjs/blob/5cb736d2f4782f725c6c66431407ff174c512ba1/src/ghostdriver/request_handlers/session_manager_request_handler.js#L67, resulting in the failure to decode, and ultimately in a command failure. Since chunked transfers are a fully standard part of the HTTP protocol, and should *not* include a `Content-Length` header, this should likely be considered a bug. Other WebDriver implementations (e.g., `geckodriver`) do not suffer from this issue.

**Comment by jesg** [comment]
@jonhoo is ghostdriver broken on an officially supported client driver?  if yes can you give the language and the version.

**Comment by jonhoo** [comment]
I've been writing my own WebDriver client, so I do not know if Selenium has this issue. If phantomjs aims to only ever work with Selenium, I guess that might be fine (unless someone can replicate on Selenium), but it does seem like incorrect behavior...

*(trip down spec rabbit hole forthcoming; feel free to skip)*

---------

The [HTTP 1.1 spec (RFC7230)](https://tools.ietf.org/html/rfc7230#section-3.3.1) requires that
> [a] recipient MUST be able to parse the chunked transfer coding because it plays a crucial role in framing messages when the payload body size is not known in advance.

Since phantomjs advertises `HTTP/1.1` in its responses, the chunked transfer encoding should be supported. If it is not, phantomjs should instead advertise `HTTP/1.0`. Both the [WebDriver spec](https://www.w3.org/TR/webdriver/#h-processing-model) and the old [Selenium WebDriver wire protocol](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#commands) require client to conform to `HTTP/1.1`; they say
> 1. Read bytes from the connection until a complete HTTP request can be constructed from the data. Let request be a request constructed from the received data, according to the requirements of RFC7230.

and
> WebDriver command messages should conform to the HTTP/1.1 request specification. 

respectively. This means that phatomjs/ghostdriver will also not be considered as conforming to either of those standards until this is fixed. In addition to being spec violations, this also just generally makes it harder to write clients that can interact with phantomjs' WebDriver server. Many language clients use `HTTP/1.1` requests (including `Transfer-Encoding: chunked`) by default, and can be difficult to reconfigure not to. This is, for example, the case for the main Rust HTTP library, Hyper, which is heavily geared towards all request bodies [being streams](https://docs.rs/hyper/0.11.0/hyper/struct.Body.html) (and therefore chunked).

**Comment by jonhoo** [comment]
I did some more digging, and turns out `chromedriver` has this same issue. I've reported it upstream at https://bugs.chromium.org/p/chromedriver/issues/detail?id=1850. `geckodriver` does not.
