### ISSUE TITLE
I can't stop PhantomJS

### ISSUE THREAD

**Issue by sdfusfhaigfhihsfdgyu** [ariya/phantomjs#15035]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
I don't know what version
2. What steps will reproduce the problem?
No steps
It just stars running in the background, it uses all my cpu power and I can't do anything about it

3. Which operating system are you using?
 Windows 10
4. Did you use binary PhantomJS or did you compile it from source?
I never used this program
5. Please provide any additional information below.
It started running one day for no reason and since then it keeps coming back without me doing anything.
It stops after sometime but I still can't do anything while is open.
Please help I can't find anything that works

**Comment by merlinthemagic** [comment]
@sdfusfhaigfhihsfdgyu Your question is too open ended and the fact that you cannot provide the version number makes it unlikely you will get help. May i suggest you find a wrapper for PhantomJS built in your preferred language. 

I.e: for PHP: https://github.com/merlinthemagic/MTS

here is a more comprehensive list:
http://phantomjs.org/related-projects.html
