### ISSUE TITLE
phantomjs-2.1.1 not surpport sync ajax?

### ISSUE THREAD

**Issue by xiatian** [ariya/phantomjs#15033]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1.page.open
  2.page.evaluate
  3.new XMLHttpRequest().open('GET', url, false).send()

3. Which operating system are you using?
centos
4. Did you use binary PhantomJS or did you compile it from source?
binary 
5. Please provide any additional information below.
` page.evaluate(function () {
        var xhr = new XMLHttpRequest();
        xhr.open('GET', 'https://www.baidu.com/img/bd_logo1.png', false);
        xhr.responseType = 'blob';
        xhr.send();
        console.log(xhr.response, xhr.readyState);
    });`

InvalidAccessError: DOM Exception 15: A parameter or an operation was not supported by the underlying object.

  undefined:4
  :7

**Comment by damusix** [comment]
I get InvalidStateError DOM Exception 11 when attempting to AJAX with `reqwest`. Using Karma with PhantomJS.

```

FAILED TESTS:
  Ajax functions
    ✖ should make a GET request
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    InvalidStateError: DOM Exception 11
    stringify@http://localhost:9876/context.js:75:49
    stringify@http://localhost:9876/context.js:75:45
    log@http://localhost:9876/context.js:138:33
    http://localhost:9876/context.js:242:19
    get@dist/cjs.js:133:16
    test/ajax.js:9:17
```
