### ISSUE TITLE
页面太长，截取图片为空

### ISSUE THREAD

**Issue by JustinYi922** [ariya/phantomjs#15039]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1.render的图片为空
  2.

3. Which operating system are you using?
Mac 和Linux都不行
4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.
网页长宽:990*78879。我把resourceTimeout设置成10s以上也没有用。

**Comment by GreatFireWall** [comment]
楼上的兄弟放弃吧, 我15年提的问题到现在也没有一条回复.

**Comment by itbdw** [comment]
如果只是要截图的话，可以看看 Chrome ，59已经支持服务器执行了。

chrome --headless

**Comment by JustinYi922** [comment]
@itbdw chrome-headless 可以在centos上用吗？前一段时间我没有找到对应的版本
@GreatFireWall 额。目前只能放弃了。超过一定长度，我就提示不支持了。

**Comment by itbdw** [comment]
可以吧，yum 安装我不清楚版本，59就可以了。最不济可以直接用google的
