### ISSUE TITLE
IFrames content doesn't get evaluated

### ISSUE THREAD

**Issue by bessgeor** [ariya/phantomjs#15047]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. Which operating system are you using?
Windows 7 x64

3. Did you use binary PhantomJS or did you compile it from source?
Binary 2.1.1

4. What steps will reproduce the problem?
  4.1. download [phantomrepro.js](https://pastebin.com/KfdB7KhR)
  4.2. run phantomjs phantomrepro.js

5. What is the expected behaviour?
  5.1 Script downloads the page specified
  5.2 Script initializes iframe creation by script
  5.3 Iframe is loaded and evaluated
  5.4 Evaluation of script element in the iframe creates another iframe inside of it

6. What happens instead?
  6.1 Script downloads the page specified
  6.2 Script initializes iframe creation by script
  6.3 Iframe is loaded but is not evaluated

**Comment by bessgeor** [comment]
Can get around of it by
1. Filtering resource requests like the iframe's url
2. Extracting iframe's src
3. Making different page.load call on iframe's src

but it's too overcomplicated

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, there might be only community support on issues.

In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is working on adding headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome.
