### ISSUE TITLE
window.location redirects

### ISSUE THREAD

**Issue by daisy-cyt** [ariya/phantomjs#15048]
How does PhantomJS handle window.location redirects?

For example, say there are two pages, page1.html and page2.html, and page1.html has the following code:

<script>window.location="page2.html"</script>

How can I get page2.html

Tks

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, there might be only community support on issues.

In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is working on adding headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome.

**Comment by dedisuryadi** [comment]
You can use page.open or redirect dynamically using page.evaluate
`
page.evaluate(function(){
    window.location = 'page2.html';
});

`
