### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by tresero** [ariya/phantomjs#15055]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`. 2.11

2. What steps will reproduce the problem?
  1. Not sure, It was running automated
  2.
  3.

3. Which operating system are you using?
Debian 8

4. Did you use binary PhantomJS or did you compile it from source?
source

5. Please provide any additional information below.

[3cec343c-ab83-5889-65cbfd35-403fcd38.zip](https://github.com/ariya/phantomjs/files/1117210/3cec343c-ab83-5889-65cbfd35-403fcd38.zip)

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, there might be only community support on issues.

In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is working on adding headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome.
