### ISSUE TITLE
PhantomJS crash

### ISSUE THREAD

**Issue by Luan1** [ariya/phantomjs#15059]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
1.9.8

2. What steps will reproduce the problem?
  1. Installed highcharts-export-server
  2. Use with shell_exec or exec in php the command (highcharts-export-server -infile file.json -outfile file.png)
  3. When I use with shell command it works, however it doesnt work when executed with php.

3. Which operating system are you using?
x86_64 GNU/Linux

4. Did you use binary PhantomJS or did you compile it from source?
Both

5. Please provide any additional information below.

[71683e7e-7b80-31b3-2bb86b7d-53a955df.dmp.zip](https://github.com/ariya/phantomjs/files/1125412/71683e7e-7b80-31b3-2bb86b7d-53a955df.dmp.zip)

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, there might be only community support on issues.

In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is working on adding headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome.
