### ISSUE TITLE
http://phantomjs.org/troubleshooting.html missing numbers under remote debugging section

### ISSUE THREAD

**Issue by stevenqzhang** [ariya/phantomjs#15057]
this section contains numbers that are not being rendered:

```
Instrument your PhantomJS script with two debugger; lines as in the example above.
Start PhantomJS on the command line with the --remote-debugger-port=9000 option.
Open http://127.0.0.1:9000/ in a Webkit-based web browser.
There should be a bulleted list with a single link. Click on it to open a web inspector that operates in the PhantomJS context. (Sometimes the link is invisible because it contains no text; if you see nothing, navigate directly to http://127.0.0.1:9000//webkit/inspector/inspector.html?page=1.)
Change to the Console section of the inspector and execute the statement __run(). This should cause the script to run until your first debugger; statement.
Open a new browser tab and return to the debugging portal at http://127.0.0.1:9000. There should now be a second entry in the bulleted list.
Click on this entry to open a new debugger that operates in the context of your page inside PhantomJS.
Return to the first web inspector tab and click the “Continue” button in the debugger.
In the second tab, you should now find the JS debugger paused at the second debugger; statement. You can now debug your page’s JS using the full capabilities of the Webkit inspector.
```

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, there might be only community support on issues.

In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is working on adding headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome.

**Comment by stevenqzhang** [comment]
@pixiuPL  Why was this closed without an explanation?

**Comment by pixiuPL** [comment]
@stevenqzhang this must have been done in error. My bet

**Comment by pixiuPL** [comment]
@stevenqzhang maybe not bulleted, but numbered list will do
