### ISSUE TITLE
Visible svg elements outside <svg> are not rendered

### ISSUE THREAD

**Issue by jneuendorf** [ariya/phantomjs#15056]
### Which version of PhantomJS are you using?
    - 2.1.1

### What steps will reproduce the problem?

Run this JS (let's say `some_path/svg-bug.js`) to render the markup (shown below as formatted HTML) as PNG:

```JavaScript
var page = require("webpage").create();

page.content = '<!DOCTYPE html><html><head></head><body><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" overflow="visible" style="margin-left: 35px;"><rect height="30" width="30" transform="translate(0, 0)" fill="green" /><rect height="30" width="30" transform="translate(-35, 0)" fill="red" /></svg></body></html>';

page.onLoadFinished = function(status) {
    if (status === "success") {
        page.render("some_path/test.png", {format: "png", quality: 0});
        phantom.exit();
    }
};
```

Run the file with

```bash
phantomjs some_path/svg-bug.js
```

### Which operating system are you using?
macOS Sierra (10.12.5)

### Did you use binary PhantomJS or did you compile it from source?
The binary version for Mac OS X from the [Downloads](http://phantomjs.org/download.html) page.

### Additional information below.

The following HTML page
```html
<!DOCTYPE html>
<html><head></head><body>
<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" overflow="visible" style="margin-left: 35px;">
    <rect height="30" width="30" transform="translate(0, 0)" fill="green" />
    <rect height="30" width="30" transform="translate(-35, 0)" fill="red" />
</svg>
</body></html>
```

looks like this in Chrome:

![expected](https://user-images.githubusercontent.com/6906734/27793833-e897033e-5fff-11e7-9393-7d69b1693e2a.png)

Note that the `<svg>` has `overflow="visible"`. I also tested `style="oveflow: visible"`: It behaves exactly the same.

When rendering the page with phantomJS the produced image looks like this:

![test](https://user-images.githubusercontent.com/6906734/27793918-35d44562-6000-11e7-9692-eb4b4e002a11.png)

That means even though the **red rectangle should be visible it is not in the screenshot**.

This [stackoverflow question](https://stackoverflow.com/questions/42458786) seems to address the same bug.

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, there might be only community support on issues.

In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is working on adding headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome.
