### ISSUE TITLE
Mouse Hover not triggering javascript

### ISSUE THREAD

**Issue by rangitotosystems** [ariya/phantomjs#15053]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
 PhantomJS version 2.1.1 

2. What steps will reproduce the problem?
 I'm running a data extraction program to get pay data from a corporate web site. 

  1. Running selenium 3.4.3 using Webdriver option with Python
  2. Using Firefox gecko driver, my program has no problem using the following sample code to hover over a link, triggering the link javascript, and then clicking on the link to get a popup window to open.

        bb = driver.find_element_by_link_text('Activity Sheet')
        ll = bb.location
        act = ActionChains(driver)
        # need to hover over element to load javascript. 
        act.move_to_element(bb)
        act.perform()
        time.sleep(1)
        print('Link is at location: ' + str(ll) + ' Enabled? ' + str(bb.is_enabled()) + " Displayed? " + 
                  str(bb.is_displayed()))
        driver.save_screenshot('scrshotHoverActivSht.png')
        act = ActionChains(driver)
        act.click(bb)
        act.perform()

  3. Running the same code as with the firefox driver, using the phantomjs driver, the "Activity Sheet"  link is not triggered. Clicking on the link has no effect. The lack of link trigger is seen in screen captures, as the link text never shows an underline associated with a mouse hover over the link. The move step and location check shows that the mouse 'is in the right place' in both driver configurations. 
There is no error issued, the "click" with JS is done on a 'dead' link, IE, one with the javascript not triggered. 

The link associated javascript is:

<a href="javascript:top.Open_PopWnd('SheetDetailE.asp?PRM=RU1QX05SPTYwNDkxMyZSUFRfTlI9MiZGb250U2l6ZT0yJlJQVF9EVD01LzEvMjAxNw==','Pop1','scrollbars=1,resizable=1,dependent=1,menubar=0,location=0,status=0,width=800,height=500');" onmouseover="window.status='View and Print Activity Sheet';return true;" onmouseout="window.status='';return true;">Activity Sheet</a>

3. Which operating system are you using?
Windows 10

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
The problem appears to be that the mouse hover event never occurs. The link never becomes active, so the popup window expected never appears. Screen capture with firefox running shows an active underlined link, with phantomJS, no underline.

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, there might be only community support on issues.

In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is working on adding headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome.

**Comment by fertaku** [comment]
Having the same issue here.

```
def hover(self):
        WebDriverWait(self.driver, 10).until(EC.visibility_of(self.root))
        ActionChains(self.driver).move_to_element(self.root).perform()

def test():
        assert not category.is_highlighted()
        category.hover()
        assert category.is_highlighted()
```

This will not change the class of the category element. I. e, JavaScript doesn't seem to be executed.
I'm still trying to figure it out though. Let me know if you have an answer or workaround.
