### ISSUE TITLE
PhantomJS has crashed. Very simple code

### ISSUE THREAD

**Issue by seliseev** [ariya/phantomjs#15054]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
Run that simple code
```
'use strict';

var webpage = require('webpage');

var page = webpage.create();

page.open('https://claimwith.me/', function(status){
    console.log('status: ' + status);
});
```

3. Which operating system are you using?
Ubuntu 16.04 LTS

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.

- The page return status=success
- Wait ~5 sec. and phantom crashes
```
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault (core dumped)
```

This bug reproduce only on my ubuntu. When run that code on Mac or Window it is OK.

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, there might be only community support on issues.

In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is working on adding headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome.
