### ISSUE TITLE
phantomjs 2.5 beta does not run on windows 32bit 

### ISSUE THREAD

**Issue by alinoson** [ariya/phantomjs#15063]
1. I m using the phantomJs version 2.5 downloaded from https://bitbucket.org/ariya/phantomjs/downloads/

2. When running phantomjs on windows server 2008 32 bit i got an error message that is an incompatible version
  
3. I m using windows 2008 server 32bit

4. I m using the built version

I tried to build 32bit compatible version from source but it did not  succeed. Thanks for precious help.

Alinoson

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, there might be only community support on issues.

In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is working on adding headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome.
