### ISSUE TITLE
async

### ISSUE THREAD

**Issue by jacobxy** [ariya/phantomjs#15069]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
  1. open a url which contain a script which run as "async"
  2. Can not find the content  which load by the script!
  3.

3. Which operating system are you using?
Windows10
4. Did you use binary PhantomJS or did you compile it from source?
   use binary PhantomJS 
5. Please provide any additional information below.
   How can I evaluate after the all scripts completed include the one runed as "async""?

**Comment by qinshenghechu** [comment]
I met too.open a url which contain a script which run as "async". it can not go to end,still wait for.
version 2.1.1
thanks~
