### ISSUE TITLE
The text looks like ◼◼◼ ◼ ◼◼◼◼◼ ◼◼◼ ◼◼.

### ISSUE THREAD

**Issue by danieloquendo** [ariya/phantomjs#15062]
![](https://user-images.githubusercontent.com/12579110/27929408-760883b4-6258-11e7-9fb7-3910cd68b6fb.png)
PhantomJS v1.9.15

Not render text.

Centos

Node v6.10.3

I already installed (yum install -y fontconfig and sudo yum install -y freetype)

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, there might be only community support on issues.

In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is working on adding headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome.
