### ISSUE TITLE
HTML5 support, when?

### ISSUE THREAD

**Issue by victorhazbun** [ariya/phantomjs#15060]
1. 2.1.1

2. Run any test that requires Audio (html5)

3. OS X 10.12.5

4. Binary

5. When are you gonna give support for HTML5 features like video or audio?

BTW, I think phantomJS is awesome.

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, there might be only community support on issues.

In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is working on adding headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome.

**Comment by umokk** [comment]
https://github.com/ariya/phantomjs/issues/10839

**Comment by umokk** [comment]
![example](https://user-images.githubusercontent.com/7175477/28040261-e96795f2-65cd-11e7-998c-c6189118b185.png)

**Comment by SeNaP** [comment]
@umokk how ??

**Comment by umokk** [comment]
‘How’ is not the toughest question. The toughest question is ‘Where it can be useful?’ Nobody needs it, nobody thinks it’s worth anything. Just a waste of time.
How to build WebKit on Linux:
1.	Install gstreamer.
2.	Enable any option you want. You may want ENABLE_VIDEO and ENABLE_WEB_AUDIO.
3.	Build WebKit.
4.	PROFIT!
