### ISSUE TITLE
PhantomJS 2.1.1 Crash On FreeBSD 11.1-PRERELEASE

### ISSUE THREAD

**Issue by budsz** [ariya/phantomjs#15067]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
```
root:~# phantomjs --version
2.1.1
```
2. What steps will reproduce the problem?
  -   Installing PhantomJS:
```   
      root:~# pkg install phantomjs
      Updating FreeBSD repository catalogue...
      FreeBSD repository is up to date.
      All repositories are up to date.
      The following 1 package(s) will be affected (of 0 checked):

      New packages to be INSTALLED:
           phantomjs: 2.1.1_1

      Number of packages to be installed: 1

      The process will require 35 MiB more space.
      10 MiB to be downloaded.

      Proceed with this action? [y/N]: y
      [1/1] Fetching phantomjs-2.1.1_1.txz: 100%   10 MiB 297.3kB/s    00:35
      Checking integrity... done (0 conflicting)
      [1/1] Installing phantomjs-2.1.1_1...
      Extracting phantomjs-2.1.1_1: 100%
```
  -  Running PhantomJS:
```
       root:~# phantomjs
       phantomjs>
```

  -   CTRL+C
```
      PhantomJS has crashed. Please read the bug reporting guide at
      <http://phantomjs.org/bug-reporting.html> and file a bug report.
      Bus error
```
3. Which operating system are you using?
```
root:~# uname -srm
FreeBSD 11.1-PRERELEASE i386
```
4. Did you use binary PhantomJS or did you compile it from source?
Binary installing from `pkg(7)` 

5. Please provide any additional information below.
Well, I use PhantomJS (`phantomjs-1.9.8.txz`)  since `FreeBSD 9.3-STABLE`, I decided to upgrade FreeBSD to `FreeBSD 10.3-STABLE` with the same version, that's great. After upgrade to `FreeBSD 11.1-PRERELEASE i386` and `phantomjs-2.1.1_1.txz` the problem appears.

This is output `dmesg`:
```
root:~# dmesg
pid 1124 (phantomjs), uid 0: exited on signal 10
pid 1526 (phantomjs), uid 0: exited on signal 10
pid 1529 (phantomjs), uid 0: exited on signal 10
pid 1532 (phantomjs), uid 0: exited on signal 10
pid 1581 (phantomjs), uid 0: exited on signal 10
pid 2111 (phantomjs), uid 0: exited on signal 10
pid 2306 (phantomjs), uid 0: exited on signal 10
```
Output with `gdb(1)`:
```
root:~# gdb /usr/local/bin/phantomjs
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "i386-marcel-freebsd"...(no debugging symbols found)...
(gdb) run eth-modem.js
Starting program: /usr/local/bin/phantomjs eth-modem.js
warning: Lowest section in /usr/local/lib/libicudata.so.58 is .hash at 000000b4

Program received signal SIGBUS, Bus error.
0x0a38ca64 in ?? ()
Current language:  auto; currently minimal
(gdb) bt
#0  0x0a38ca64 in ?? ()
#1  0x08433bf3 in QCommandLine::parseError ()
#2  0x08434034 in QCommandLine::parseError ()
#3  0x085959e7 in QCommandLine::parseError ()
#4  0x0857ff4d in QCommandLine::parseError ()
#5  0x0857d840 in QCommandLine::parseError ()
#6  0x0857fbdc in QCommandLine::parseError ()
#7  0x084480a6 in QCommandLine::parseError ()
#8  0x080cb19f in QCommandLine::parseError ()
#9  0x0806784e in ?? ()
#10 0x0805eceb in ?? ()
#11 0x0806099b in ?? ()
#12 0x08081b07 in QtMetaTypePrivate::QMetaTypeFunctionHelper<WebServerResponse*, true>::Construct ()
#13 0x0805e0aa in ?? ()
#14 0x00000002 in ?? ()
#15 0xbfbfec58 in ?? ()
#16 0xbfbfec64 in ?? ()
#17 0xbfbfec64 in ?? ()
#18 0xbfbfec54 in ?? ()
#19 0x00000000 in ?? ()
(gdb) quit
The program is running.  Exit anyway? (y or n) y
```

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, this is the [status of the project](https://github.com/ariya/phantomjs/issues/14946#issuecomment-303985078) and there might be only community support on issues. In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is [working on adding](https://github.com/casperjs/casperjs/issues/1825) headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome. It basically converts natural-language-looking steps into CasperJS JavaScript code to run web automation, while at the same time supporting CasperJS API. It also has a Chrome extension.

**Comment by kensoh** [comment]
PhantomJS maintainer Vitaly is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), he may be coming up with another [PhantomJS-like project](https://github.com/Vitallium/phantomium) for headless Chrome. Until then, this is the [status of the project](https://github.com/ariya/phantomjs/issues/14946#issuecomment-303985078) and there might be only community support on issues.

In the meantime, you may want to check out [CasperJS project](https://github.com/casperjs/casperjs), a well-documented navigation and testing tool based on PhantomJS, so using it is probably very familiar to a PhantomJS user. The main maintainer is working on adding headless + visible Chrome support now.

Also, I just finished developing [TagUI tool](https://github.com/tebelorg/TagUI) base on CasperJS which can automate headless + visible Chrome. So users of the tool can transit to CasperJS easily once it officially supports Chrome.

**Comment by pleaseshutup** [comment]
I'll add FWIW that i've replicated the issue on 32bit freebsd but it works fine on 64bit / amd64 

working:
FreeBSD 11.0-RELEASE-p9 FreeBSD 11.0-RELEASE-p9 #0: Tue Apr 11 08:48:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64



fails:
FreeBSD 11.1-RELEASE-p1 FreeBSD 11.1-RELEASE-p1 #0: Wed Aug  9 11:17:49 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  i386
