### ISSUE TITLE
Product descripton

### ISSUE THREAD

**Issue by JoeKahl** [ariya/phantomjs#15078]
We have a big project and someone else set it up.  I have no idea why there are hundreds of javascript libraries included.  The build is failing for me due to PhamtomJS.  This web site neglects to state what capabilities the PhantomJS library provides.  Please add the FAQ some basic product description.  Thank you.

**Comment by kensoh** [comment]
Hi @JoeKahl adding some info and see what other PhantomJS users can add on. I assume you mean that you can't find description of what PhantomJS can be used for. It looks quite clear from the readme page of this project (pasted below). There are more technical details if you view the [PhantomJS API](http://phantomjs.org/api/webpage/).

Also PhantomJS isn't a product as in a commercial product that a company makes and sells. It is created and maintained by open-source contributors for free using their own time. Maybe you can also check with your team-mate who didn't document how he/she uses PhantomJS in that project.

## Use Cases
- Headless web testing. Lightning-fast testing without the browser is now possible!
- Page automation. Access and manipulate web pages with the standard DOM API, or with usual libraries like jQuery.
- Screen capture. Programmatically capture web contents, including CSS, SVG and Canvas. Build server-side web graphics apps, from a screenshot service to a vector chart rasterizer.
- Network monitoring. Automate performance analysis, track page loading and export as standard HAR format.

## Features
- Multiplatform, available on major operating systems: Windows, Mac OS X, Linux, and other Unices.
- Fast and native implementation of web standards: DOM, CSS, JavaScript, Canvas, and SVG. No emulation!
- Pure headless (no X11) on Linux, ideal for continuous integration systems. Also runs on Amazon EC2, Heroku, and Iron.io.
-  Easy to install: Download, unpack, and start having fun in just 5 minutes.
