### ISSUE TITLE
Some picture screenshots are not correct

### ISSUE THREAD

**Issue by XYUU** [ariya/phantomjs#15074]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
phantomjs-2.1.1-windows
2. What steps will reproduce the problem?
phantomjs screenshots.js
`
var page = require('webpage').create();
page.open('http://static.228.cn/upload/2017/05/31/AfterTreatment/1496206919569_e9y3-0.jpg', function() {
    page.render('1.png');
    phantom.exit();
});
`

3. Which operating system are you using?
windows 10
4. Did you use binary PhantomJS or did you compile it from source?
binary PhantomJS.
5. Please provide any additional information below.
http://static.228.cn/upload/2017/05/31/AfterTreatment/1496206919569_e9y3-0.jpg
The size of this image in chrome is 288 x 384.

**Comment by kensoh** [comment]
Not sure if PhantomJS is designed to view an image file directly. It looks like you are trying to get a copy of a static image from an URL. Would it help if you use XMLHttpRequest to try to download instead? Or use some other Node.js package that can directly download the file. There are many packages to do that, for eg https://www.npmjs.com/package/download (I haven't use it myself)

**Comment by XYUU** [comment]
This image is just an example. You can download the picture to the local and the picture as an element of html, you will find the size of the picture and the size of the screenshot is inconsistent.

**Comment by kensoh** [comment]
I'm using PhantomJS indirectly through CasperJS. When I try to capture the image by visiting image URL directly, I can replicate the issue. The rendered image is smaller than the original image by few pixels in width and height.

**Comment by XYUU** [comment]
Yes, that's the problem.
