### ISSUE TITLE
LittleDocBug on http://phantomjs.org/page-automation.html

### ISSUE THREAD

**Issue by scenaristeur** [ariya/phantomjs#15070]
In the doc "Dom Manipulation" of the http://phantomjs.org/page-automation.html, the line 
```
 return document.getElementById('myagent').textContent; 
```
should be, I think, 
``` 
return document.getElementById('qua').textContent;
```
because "myagent" return "null is not an object".

**Comment by kensoh** [comment]
Oh yeah, it looks like that web page has changed, it also now redirects from http://www.httpuseragent.org to https://useragent.openadmintools.com.

Same for me, element with ID myagent is no longer there and qua is there instead.
