### ISSUE TITLE
Mac Osx: Undownloadable from bitbucket.

### ISSUE THREAD

**Issue by fullhdpixel** [ariya/phantomjs#15079]
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip

So bitbucket is incredibly slow for this particular release. How come this hasn't been sorted out yet? There've been complaints in the past.

**Comment by Vitallium** [comment]
Hi! Could you please explain how exactly slow it is? Because it's fine for me here.

**Comment by fullhdpixel** [comment]
The 16.4mb would take over an hour, but it always fails due to "network error"

**Comment by Vitallium** [comment]
Perhaps something is wrong with your network connection or with Amazon S3 for your region?

**Comment by fullhdpixel** [comment]
No, I think BitBucket is the cause (rate limit or something)

**Comment by fullhdpixel** [comment]
Any chance you can upload it for me to somewhere else?

**Comment by fullhdpixel** [comment]
Finally worked...
