### ISSUE TITLE
PhantomJS 2.1.1 not Compatible with Selenium-Remote-Driver 2.53.0

### ISSUE THREAD

**Issue by mojojojo94** [ariya/phantomjs#15076]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. Set PhantomJS to latest version
  2. Set Selenium-Remote-Driver to 2.53.0

3. Which operating system are you using?
macOS Sierra 10.12.5

4. Did you use binary PhantomJS or did you compile it from source?
Compile from source

5. Please provide any additional information below.
Right now PhantomJS 2.1.1 work with selenium-remote-driver 2.43.0, but I need it to work with selenium-remote-driver 2.53.0.

What version of PhantomJS is compatible with selenium-remote-driver 2.43.0 and above?
Or what version of selenium-remote-driver is compatible with the latest PhantomJS version?

Any help, documentation and resources for this issue will be greatly appreciated. 😄

**Comment by jesg** [comment]
@mojojojo94 

you should use a [branch](https://github.com/jesg/phantomjs/tree/backport-ghostdriver-2-0-to-phantomjs-2-1) i created that backports ghostdriver 2.0.0 to phantomjs 2.1.1.

**Comment by mojojojo94** [comment]
Adding this branch to my maven dependency in addition with phantomJS 2.1.1 will allow me to run headless testing with higher version of selenium-remote-driver?

**Comment by mojojojo94** [comment]
@jesg Could you include java binding for a maven project as an example on your read.me page.
