### ISSUE TITLE
Canvas Context's toDataURL not returning webp

### ISSUE THREAD

**Issue by DronRathore** [ariya/phantomjs#15088]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.5.5-beta
2. What steps will reproduce the problem?
  1. Using [WhammyJS Tutorial](http://antimatter15.com/whammy/clock.html) to generate webm video
3. Which operating system are you using?
OSX-Seirra 
4. Did you use binary PhantomJS or did you compile it from source?
Binary
5. Please provide any additional information below.
Canvas's context.toDataURL is returning a base64 ```png``` file, however the modern browsers returns base64 encoded webp images for the same. Though phantom does have support for webp, it would be great if canvas's dataURL too can be returned in webp format.

**Comment by csvan** [comment]
PhantomJS is abandoned. The maintainer recommends you use Chrome Headless instead.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

**Comment by Vitallium** [comment]
@csvan Hi. Could you please stop posting messages like this? I know that people still open issues and wait for fixes, but we have more than 1000+ issues here. Are you going to comment all of them? :-)

PhantomJS is not abandoned yet (until we hear an official statement from Ariya)

**Comment by csvan** [comment]
@Vitallium sorry, it's been fixed.

**Comment by Vitallium** [comment]
@csvan Thank you!
