### ISSUE TITLE
PhantomJs not showing syntax error

### ISSUE THREAD

**Issue by appzone** [ariya/phantomjs#15085]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. write any syntax error code 
  2.
  3.

3. Which operating system are you using?
Windows 7

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
when my code have syntax error, it not showing error. it just like hang until i Ctrl+C
example : my code missing semicolon, or missing ), etc

**Comment by csvan** [comment]
PhantomJS is abandoned. The maintainer recommends you use Chrome Headless instead.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
