### ISSUE TITLE
Support Function.name for anonymous functions. ES2015 "Inferred function names"

### ISSUE THREAD

**Issue by rsemenov** [ariya/phantomjs#15086]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
    Create `issue.js` file with next content:
  ```
var f = function() {};
var object = {
  someMethod: function() {}
};

console.log(f.name); // "f"
console.log(object.someMethod.name); // "someMethod"
  ```
 Run `phantomjs.exe issue.js`
    `f.name` and `object.someMethod.name` return empty strings.

3. Which operating system are you using?
Windows 10

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
Are there any plans to add that support?
Please see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name "Inferred function names" sections.

Function.name for normal functions works fine.

**Comment by csvan** [comment]
PhantomJS is abandoned. The maintainer recommends you use Chrome Headless instead.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
