### ISSUE TITLE
High memory consumption; management?

### ISSUE THREAD

**Issue by Napolitain** [ariya/phantomjs#15082]
Hello!

I have an issue : I have to run a script that is scrapping a big dynamic rich page, and it will eventually go out of memory. That said, I though about deleting DOM elements so I could load, delete, load more, delete more... Now I saw that deleting DOM elements don't clear the RAM. How can I do it?

1. I can use any version of PhantomJS (lets say the latest).

2. I use Windows (again, 7 or later).

3. The data is not loadable separately (by this I mean that I can't load data1, close page, load data2... it must be load 1 load 2)

Isn't there any ways to clear memory from deleted DOM (it could be a solution)?

**Comment by csvan** [comment]
PhantomJS is abandoned. The maintainer recommends you use Chrome Headless instead.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
