### ISSUE TITLE
str.includes Fails

### ISSUE THREAD

**Issue by arrmo** [ariya/phantomjs#15080]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
v2.1.1

2. What steps will reproduce the problem?
  1. Try using str.includes ... example code: console.log(String('intTest'.includes('int'))); => JavaScript error / exception, code exits. Note, this is inside a web page I am opening (rasterize.js).

3. Which operating system are you using?
Ubuntu v16.04

4. Did you use binary PhantomJS or did you compile it from source?
Installed using apt-get.

5. Please provide any additional information below.

**Comment by djheru** [comment]
I've had success using https://www.npmjs.com/package/phantomjs-polyfill-includes

**Comment by arrmo** [comment]
Hi,

I may be missing your point, but to make sure ... my issue is with this command inside my web page, that PhantomJS is loading => not within PhantomJS executing this command (inside it's JS) file ... make sense?

Thanks!
