### ISSUE TITLE
2.1.1 not support css blend modes,  css style mix-blend-mode did not work

### ISSUE THREAD

**Issue by arsen2010** [ariya/phantomjs#15099]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
   A img or div uses [cssgram](https://una.im/CSSgram/) style
   use phantomjs take a screenshot
   you will find the screenshot picture do not look the same as the web page.

3. Which operating system are you using?
window and linux both I had a try.

4. Did you use binary PhantomJS or did you compile it from source?
use binary version

5. Please provide any additional information below.
Is it not support **css blend modes**? 
The **mix-blend-mode** attribute of css do not work, look two pictures below , any help will be appreciate, thanks for anyone reply me.
[http://imgur.com/yxzWiUA](http://imgur.com/yxzWiUA)
[http://imgur.com/SgBh5yb](http://imgur.com/SgBh5yb)

**Comment by csvan** [comment]
PhantomJS is abandoned. The maintainer recommends you use Chrome Headless instead.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

**Comment by reysmerwvr** [comment]
Hi Friend, I have the same issue. Could you figured it out?

**Comment by pageborn** [comment]
@reysmerwvr Helpless, i have no idea
