### ISSUE TITLE
phantomjs will have no reflection when open some url

### ISSUE THREAD

**Issue by paine1690** [ariya/phantomjs#15096]
here is my test code:
`
var page = require('webpage').create();
    console.log('start');
    var url = 'http://e.cn.miaozhen.com/r/k=2054059&p=77r0X&dx=__IPDX__&rt=2&ns=__IP__&ni=__IESID__&v=__LOC__&xa=__ADPLATFORM__&tr=__REQUESTID__&ro=sm&vv=1&vo=376ecb7ed&vr=2&o=https%3A%2F%2Fwww.ikea-sh.cn%2Fonline-campaign.html%3Futm_source%3Dgdt%26utm_campaign%3Dfy17%255Fbacktoschool%26utm_adgroup%3DShanghai%26utm_medium%3DDisplay%26utm_channel%3D%25E6%2589%258BQ%25E7%25A9%25BA%25E9%2597%25B4%25E4%25BF%25A1%25E6%2581%25AF%25E6%25B5%2581%25E2%2580%2594%25E2%2580%2594%25E5%259B%25BE%25E6%2596%2587%25E5%25B9%25BF%25E5%2591%258A';
    //var url = 'http://www.baidu.com';
    
    console.log('1');
    
page.onClosing = function(closingPage) {
  console.log('The page is closing! URL: ' + closingPage.url);
};

var t1 = window.setInterval(function(){
  console.log('aa');
},100); 

page.onConfirm = function(msg) {
  console.log('CONFIRM: ' + msg);
  return true; // `true` === pressing the "OK" button, `false` === pressing the "Cancel" button
};

page.onConsoleMessage = function(msg, lineNum, sourceId) {
  console.log('CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
};
    
    
page.onError = function(msg, trace) {
  var msgStack = ['ERROR: ' + msg];
  if (trace && trace.length) {
    msgStack.push('TRACE:');
    trace.forEach(function(t) {
      msgStack.push(' -> ' + t.file + ': ' + t.line + (t.function ? ' (in function "' + t.function +'")' : ''));
    });
  }
  console.error(msgStack.join('\n'));
};

page.onLoadFinished = function(status) {
  console.log('Status: ' + status);
  // Do other things here...
};

page.onNavigationRequested = function(url, type, willNavigate, main) {
  console.log('Trying to navigate to: ' + url);
  console.log('Caused by: ' + type);
  console.log('Will actually navigate: ' + willNavigate);
  console.log('Sent from the page\'s main frame: ' + main);
}

page.onResourceError = function(resourceError) {
  console.log('Unable to load resource (#' + resourceError.id + 'URL:' + resourceError.url + ')');
  console.log('Error code: ' + resourceError.errorCode + '. Description: ' + resourceError.errorString);
};

page.onResourceReceived = function(response) {
  console.log('Response (#' + response.id + ', stage "' + response.stage + '"): ' + JSON.stringify(response));
};  

page.onResourceRequested = function(requestData, networkRequest) {
  console.log('Request (#' + requestData.id + '): ' + JSON.stringify(requestData));
};

page.onResourceTimeout = function(request) {
    console.log('Response (#' + request.id + '): ' + JSON.stringify(request));
};

page.onUrlChanged = function(targetUrl) {
  console.log('New URL: ' + targetUrl);
};
    
    
    //page.settings.userAgent= 'Mozilla/5.0 (Linux; Android 5.1.1; Nexus 6 Build/LYZ28E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Mobile Safari/537.36';
    //page.settings.userAgent= 'User-Agent, Mozilla/5.0 (Linux; U; Android 2.3.7; en-us; Nexus One Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1';
    page.settings.resourceTimeout = 3000;

    

    
    page.onAlert = function(msg) {
      console.log('ALERT: ' + msg);
    };

    page.open(url, function(status) {
      console.log('ok!');
      if (status == "success" ) {      
        page.render('E:\\12345.png');
        console.log('ok!');
        phantom.exit();       
      } else{
        console.log(status +':' + address + ', out:' + output);
        phantom.exit(1);
      }
    });
  
    
    
`

sometimes there will be no reflection in the console, and even the timer t1 has no information in the sonsole.

my phantomjs version is 2.1.1, in windows platform

**Comment by csvan** [comment]
PhantomJS is abandoned. The maintainer recommends you use Chrome Headless instead.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
