### ISSUE TITLE
Program is crashing with Status Code -6.

### ISSUE THREAD

**Issue by abhisharma7** [ariya/phantomjs#15093]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
I am using PhantomJS inside Scrapy to download Javascript pages. In my opinion this error is because of Memory as more and more pages it crawl this error become more frequent. Its getting timed out or previous connection didn't get closed properly. Can you please confirm the reason for this error code "Status Code : -6 "

3. Which operating system are you using?
AWS Compute( ec2 ) : Ubuntu 

4. Did you use binary PhantomJS or did you compile it from source?
Binary, installed using apt-get

**Comment by csvan** [comment]
PhantomJS is abandoned. The maintainer recommends you use Chrome Headless instead.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

**Comment by binqiangsun** [comment]
any solution?

**Comment by abhisharma7** [comment]
Nope, I kind of given up on PhantomJS..It is not even working with nohup (in background)....Chrome headless browser is also an option but its not available for Linux.

I am trying to figure out the best way to resolve this problem, will let you know if I manage to find out what actually causing this or if I found any alternate way.

**Comment by twalpole** [comment]
@abhisharma7 Chrome headless definitely is available on Linux

**Comment by abhisharma7** [comment]
I don't think its like PhantomJS... It will use display library of Python to run it in background. I think speed wise it will be much slower then PhantomJS.

Can you please share any tutorial link which uses Selenium with Chrome Headless browser.

Thank you.

**Comment by twalpole** [comment]
@abhisharma7 Yes it will be slower, and requires `chromedriver` to use with selenium, but it is currently being maintained/developed unlike PhantomJS.  https://intoli.com/blog/running-selenium-with-headless-chrome/ is an article about using it with Python.

**Comment by abhisharma7** [comment]
Thank you for this article...really appreciate your help.

Thanks
