### ISSUE TITLE
Can't generate correct highchart with useHTML enabled option.

### ISSUE THREAD

**Issue by RredCat** [ariya/phantomjs#15098]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
I am using 2.1.1 version of phantomjs 

2. What steps will reproduce the problem?
  *  start phantomjs server `phantomjs highcharts-convert.js -host 127.0.0.1 -port 3003`
  * call it with next infile parameter - `"{'chart':{'type':'bar'},'xAxis':{'categories':['&#39;<b>Jan</b>&#39;', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],'labels':{'useHTML':true}},'series':[{'data':[29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]}]}"`
  * I recieved image without any categorties.
  * If I take off `'labels':{'useHTML':true}` I have correct chart but my html category looks bad (`&#39;<b>Jan</b>&#39;` instead of &#39;<b>Jan</b>&#39;).
  * Web version of highchart doesn't have this issue [http://jsfiddle.net/RredCat/v90pv006/](http://jsfiddle.net/RredCat/v90pv006/)  and works correct.

3. Which operating system are you using?
I am using Windows 10.

4. Did you use binary PhantomJS or did you compile it from source?
I am using downloaded binary of PhantomJS 

5. Please provide any additional information below.

**Comment by csvan** [comment]
PhantomJS is abandoned. The maintainer recommends you use Chrome Headless instead.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
