### ISSUE TITLE
I can not find support for HTTPS proxy

### ISSUE THREAD

**Issue by instagramlover** [ariya/phantomjs#15094]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
phantom.setProxy('https://6d2a7d7f9d78558032874ec057e55b07af9ba311:39D56662E83CC3A0CCBA99E3DB331DA3D4201EAA641FB5889F2C22010B8620D9@us.opera-proxy.net:443');

i test : 
--proxy=us.opera-proxy.net:443 --proxy-type='https' --proxy-auth='6d2a7d7f9d78558032874ec057e55b07af9ba311:39D56662E83CC3A0CCBA99E3DB331DA3D4201EAA641FB5889F2C22010B8620D9'

all same problem

3. Which operating system are you using?
Linux
4. Did you use binary PhantomJS or did you compile it from source?
binary PhantomJS
5. Please provide any additional information below.

Dear all , when i am using opera proxy i got 
[warning] [phantom] Loading resource failed with status=fail: https://www.googl.com
while when i use the proxy with CURL , it work just fine 

Please advice

**Comment by csvan** [comment]
PhantomJS is abandoned. The maintainer recommends you use Chrome Headless instead.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

**Comment by bad-day** [comment]
https proxy is not supported. Use http or socks5
