### ISSUE TITLE
Pug in PhantomJS

### ISSUE THREAD

**Issue by VivekRagunathan** [ariya/phantomjs#15101]
**`phantomjs --version`**
2.1.1 (Ready to upgrade to any version that offers what I need)

Is there a way I can use a template engine like Pug/Jade in a PhantomJS script to conjure up my HTML? I would like to do something like `require("jade")` and then `var html = jade.compile("file.jade");` and use the `html` above to generate my image with PhantomJS.

Please tell me it is possible 😩.

Thanks in advance 🙏. 

P.S: Currently I am constrained in having a separate Node/express server and PhantomJS calling that node/express server.

**Comment by csvan** [comment]
PhantomJS is abandoned. The maintainer recommends you use Chrome Headless instead.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
