### ISSUE TITLE
TypeError: null is not an object(evaluating 'document.getElementById('").textContent')

### ISSUE THREAD

**Issue by GintasS** [ariya/phantomjs#15104]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
You can see all the steps in this link:
https://stackoverflow.com/questions/45651237/phantomjs-typeerror-null-is-not-an-objectevaluating-document-geteelementbyid

But in short, I'm geting error:
ERROR: 
TypeError: null is not an object(evaluating 'document.geElementById('resInfo-0').textContet')

when trying to find an element in website html.

https://stackoverflow.com/questions/45651237/phantomjs-typeerror-null-is-not-an-objectevaluating-document-geteelementbyid

3. Which operating system are you using?
Windows 10

4. Did you use binary PhantomJS or did you compile it from source?
I'm using binary package.
phantomjs-2.1.1-windows.zip (17.4 MB)

5. Please provide any additional information below.
You can see all the information on link below:
https://stackoverflow.com/questions/45651237/phantomjs-typeerror-null-is-not-an-objectevaluating-document-geteelementbyid

Not rewriting the issue because it looks better on stackeroverflow.

**Comment by csvan** [comment]
PhantomJS is abandoned. The maintainer recommends you use Chrome Headless instead.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
