### ISSUE TITLE
Returning a list from page.evaluate() eats the first element and returns undefined

### ISSUE THREAD

**Issue by nmondal** [ariya/phantomjs#15109]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
    2.1.1
2. What steps will reproduce the problem?
  1. Create a page evaluate function to return a proper array, say `var a = [42,1,2,3 ] `
  2. The returned array will have `a[0] = undefined `
  3.

3. Which operating system are you using?
Mac OS X
4. Did you use binary PhantomJS or did you compile it from source?
brew install phantomjs
5. Please provide any additional information below.

**Comment by csvan** [comment]
PhantomJS is no longer actively developed. See #15105
