### ISSUE TITLE
The official website can not download the windows installation package

### ISSUE THREAD

**Issue by AACKC** [ariya/phantomjs#15102]
Dear Developer:
      I downloaded your website "phantomjs" windows installation package, there can not download the phenomenon, and prompt: URL: https://bbuseruploads.s3.amazonaws.com/fd96ed93-2b32-46a7-9d2b-ecbc0988516a/downloads And / or / / -2.1.1-windows.zip "page may temporarily be unable to connect, or it has been permanently moved to the new URL.
ERR_TUNNEL_CONNECTION_FAILED.
     Trouble in dealing with this issue, thank you very much for your busy schedule to see this feedback.
    If you have already processed this question, can you reply to me by email? E-mail: 799518261@qq.com. Thank you very much!

**Comment by csvan** [comment]
PhantomJS is abandoned. The maintainer recommends you use Chrome Headless instead.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
