### ISSUE TITLE
TypeError: undefined is not a function (evaluating 'fs.readFileSync()')

### ISSUE THREAD

**Issue by Jehanramadhan** [ariya/phantomjs#15106]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1. phantomjs index.js
  2.
  3.

3. Which operating system are you using?
Linux Mint 17.3
4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.

I have some problem for read file synchronous,
when i run my phantom js script :

`try {
      var user = Yaml.safeLoad(
        fs.readFileSync('myfile/config.json')
      )
      this.initUrl(user.url);
      this.initCustom(user.pages);
      this.initCredentials(user.username, user.password);
    } catch (e) {
      console.log(e);
    } finally {
      this.checkUrl();
    }`

i got TypeError: undefined is not a function (evaluating 'fs.readFileSync('myfile/config.json')')
what i must doing to fix it?

**Comment by csvan** [comment]
PhantomJS is no longer actively developed. See #15105

**Comment by charly3pins** [comment]
Hi @Jehanramadhan , 
the fs.readFileSync is a node function, but it's not included in file system library from phantom.
You can use the fs.read() function from phantom to read your file:
```javascript
try {
	var user = Yaml.safeLoad( fs.read('myfile/config.json') ) 
	this.initUrl(user.url); 
	this.initCustom(user.pages); 
	this.initCredentials(user.username, user.password); 
} catch (e) { 
	console.log(e); 
} finally { 
	this.checkUrl(); 
}
````
See http://phantomjs.org/api/fs/method/read.html
