### ISSUE TITLE
Please add notice that PhantomJS is abandoned

### ISSUE THREAD

**Issue by csvan** [ariya/phantomjs#15105]
I think it would be good to provide a link to the following if no further maintenance is planned. Chrome Headless has been out for all major platforms for some time now and is already seeing major adaption, as predicted by the original maintainer.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

**Comment by ashawley** [comment]
@csvan There's a 2.5 beta out.  Give it a try!

**Comment by Vitallium** [comment]
Now we can - https://github.com/GoogleChrome/puppeteer

This is a meta issue for final words. I would like to give thanks to all who have been developing this project so far:
```
Ariya Hidayat
James M. Greene
Ivan De Marino
execjosh
Jon Leighton
Zack Weinberg
Jim Evans
Antonin Stefanutti
jesg
Samuel Cochran
Jochem Wichers Hoeth
daniel grippi
Anastasia A
Adi Prasetyo
Van Wilson
Annamalai
Elias Winberg
Elan Ruusamäe
xiaohuo
tntim96
Andrew Murray
Marc Epard
Osman Yuksel
Connor Dunn
Mehmet Beydogan
Tobias Dammers
Alhadis
Erik Dubbelboer
Ivan Radulovic
Artur Signell
Luke Street
Steven Masala
Piotr Deszynski
Jilles Soeters
Felicia Santoro-Petti
Paul Morelle
YunJu Lee
tmallery
Milian Wolff
Christoph Bünte
Alex Greif
salihsagdilek
nbouvrette
Monika Schrenk
Alex Nicksay
Eugeniu Ceglov
AllBinary
Florian Fray
Dmitry Parshin
Frankie Dintino
jmiller76
Sam Nelson
Vishesh Handa
Eric Radman
Eugene
Paul Millar
Andrey Plotnikov
Jacek Migdal
Marcel Duran
Artem
Craig Teegarden
John Gozde
Petteri Räty
Mike McQuaid
Artem Koshelev
Sven Eckelmann
Eric Heydenberk
Thomas Schlage
Dmitry Mazuro
Richard Harris
petercoles
Adrian Chung
Rikke Simonsen
paulo alem
Trevor North
Joseph Rollinson
Vasyl Vavrychuk
Ashish Kulkarni
James McParlane
Brad Daily
Ben Cox
Bojan Markovic
Aaron Stone
Oleg Plakhotniuk
Francisco de Borja Lopez Río
Martin Popelak
Max Edmands
hexid
Morgan Roderick
Bryan Bishop
Alex Alvarez
Jan Minar
Andrew Galloni
Robin Helgelin
Pavel
DjinnS
Jonathan Wilkins
Tom Aizenberg
Laurent Jouanneau
Max Desyatov
Alexander James Phillips
Dody Suria Wijaya
Capi Etheriel
Juliusz Gonera
Julian Szulc
Jeff Boulter
Matthew Barr
bongole
Oleg Pudeyev
Ken Collins
Sebastian Krzyszkowiak
David Burrows
qubird
fastclemmy
Jan Schaumann
Johan Sköld
Ian Oxley
Shawn Krisman
Zhaolong
Ryan Cumming
Harry Waye
Jakub
neraliu
Ilya Grigorik
Alessandro Portale
Ariya
Nicolas Perriault
Tom Stuart & Jon Leighton
Marco Ferragina
Anthony O
Nera Liu
david
Eivind Uggedal
b.long
leeight
Brikou CARRE
Stephen Young
Brian Donovan
Chris Smith
Baffo32
Leo Franchi
Maurice Svay
Antono Vasiljev
Will
IceArmy
Danny Wang
Paul Tsier
Viorel Dram
Aditya Ivaturi
Joe Gornick
Nick Rowe
Gregor Martynus
Alex Whitman
Paul Dixon
mintbridge
Julien Ammous
Niek
Rob Terrell
Bartosz Nitka
Kapil Reddy
Alexey Palazhchenko
Roejames12
Dennis Kaarsemaker
sujal
M. Scott Ford
Dunk Fordyce
rgieseke
Francisco Souza
Ville Lautanala
Ismael Celis
Peter Jihoon Kim
Weston Ruter
Jon Turner
Gabor Torok
Wouter de Bie
Matthias
mattn
jdalton
```

It was an amazing time! You can be sure that Google DevTools can handle and develop `puppeteer` further with regular updates which we, unfortunately, unable to deliver. Thank you!

With this message, no more commits will be pushed here. The development has been stopped for good and all.

**Comment by kensoh** [comment]
Thank you very much Vitaly, Ariya and PhantomJS gang. Your work has enabled new possibilities and solutions for countless people. Want to say wish you all the best in your next huge undertaking!!

**Comment by csvan** [comment]
PhantomJS has been crucial in projects I have been involved in over the years. We still have it in production for some systems and it is likely to be spinning there for quite some time..

Thank you @Vitallium and all the contributors for your work, it has made a difference for thousands of devs.

**Comment by nesttle** [comment]
Thanks for your great job guys.

**Comment by pageborn** [comment]
Thank you PhantomJS!

**Comment by jefleponot** [comment]
@Vitallium @ariya 

Thank you very much for all the work you have done in recent years. You have contributed to the evolution of the use of web browsers in a considerable way (in terms of application tests, scrapping, supervision ...)

I have only one regret is that version 2.5 which led to the management of "promises" will never come out in stable version.

My adminstration will continue to use PhantomJS version 2.1.1 for a long time with all possible javascript patches (without having ever contributed to the project).

Thank you and congratulations.
jef

**Comment by ashawley** [comment]
For things like promises, we use this ES6 shim:

https://github.com/paulmillr/es6-shim

We use Phantom for headless unit testing of Jasmine tests, so we have control of what assets can be added to the page.

**Comment by BasZhang** [comment]
Thank you PhantomJS guys!

**Comment by sonyarianto** [comment]
Thank you PhantomJS, and welcome Chrome headless era

**Comment by FireQQTW** [comment]
PhantomJS helped me a lot, thanks!!!

**Comment by bughit** [comment]
@Vitallium Since this issue is still open and there is no notice on either github or phantomjs.org, is the abandonment uncertain?

**Comment by Vitallium** [comment]
@bughit I stopped working on PhantomJS two months ago.

**Comment by bughit** [comment]
@Vitallium I understand that your stepping down is certain, it was unclear if there was some significance to this being open and the absence of notice.

**Comment by Vitallium** [comment]
@bughit We decided to not do that. Anyone can catch up and continue developing the project ;-)

**Comment by narze** [comment]
Thank you guys for your hard work! 👍

**Comment by josephzidell** [comment]
We used PhantomJS for several years. Was instrumental in getting us where we are today. RIP

**Comment by yan12125** [comment]
I see there are quite a few new commits by @pixiuPL recently. Does that mean PhantomJS is living again? ;)

**Comment by kensoh** [comment]
Adding on to @yan12125's comment, did you guys see that [PhantomJS homepage](http://phantomjs.org) now shows v2.1.3 latest release instead of v2.1.1 ?! - @pixiuPL's commits are still coming in 😱

**Comment by pixiuPL** [comment]
Well, to be completely honest with you all, I must admit that **currently** Im **the only one** dev working on PhantomJS.

**Comment by kensoh** [comment]
This is great news for a lot of people! Thank you very much pixiuPL! 😄

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.
