### ISSUE TITLE
Wrong rendering of texts with different font-weights on PDF 

### ISSUE THREAD

**Issue by PohlodSlavik** [ariya/phantomjs#15100]
PhantomJS version: 2.1.1
Operating system: Windows 10 x64
Using PhantomJS binary downloaded from http://phantomjs.org/

Texts looks different in html file opened in browser and converted to PDF.
There is a difference between font-weight:700 and font-weight: 900 in browser but there is no difference in PDF.
Text with font-weight:900 don't look bold enough:
![example](https://user-images.githubusercontent.com/2474660/29124735-6646adae-7d22-11e7-9e78-42c443fb88ed.png)

To reproduce:
1) extract files:
[FontWeightIssue.zip](https://github.com/ariya/phantomjs/files/1211616/FontWeightIssue.zip)
2) run command: `phantomjs.exe "init.js" "test.html" "test.pdf"`

**Comment by pageborn** [comment]
One normal font does not support bold or italic, you should the specific fonts, like the code below: 
@font-face {
	font-family: AdventPro;
	src: url(./font/AdventPro.woff2) format("woff2"), url(./font/AdventPro.woff) format("woff");
	font-style: normal;
	font-weight: normal;
}

@font-face {
	font-family: AdventPro;
	src: url(./font/AdventPro-Bold.woff2) format("woff2"), url(./font/AdventPro-Bold.woff) format("woff");
	font-style: normal;
	font-weight: bold;
}
