### ISSUE TITLE
phantomjs does not render svg pattern image

### ISSUE THREAD

**Issue by malio10AC** [ariya/phantomjs#15107]
1. Version 2.1.1

2. phantomjs can not render svg->pattern->image. I get a black fill:

`<svg id="svg-room" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="630px" height="300px" enable-background="new 0 0 630 300" xml:space="preserve" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:ev="http://www.w3.org/2001/xml-events">
    <defs>
        <pattern id="svg-wood-door" height="100%" width="100%" patternContentUnits="objectBoundingBox">
            <image preserveAspectRatio="none" xlink:href="typo3conf/ext/zargenkonfigurator/Resources/Public/images/texture_wood_door.jpg" width="1" height="1"></image>
        </pattern>
    </defs>
    <g id="svg-door">
        <rect x="228.1" y="20.3" fill="url(#svg-wood-door)" stroke="#000000" stroke-width="0.24" width="44" height="32"></rect>
    </g>
</svg>`

3. operating system: Arch 64bit

4. binary PhantomJS

5. The implementation of that would be great. Thanx

**Comment by csvan** [comment]
PhantomJS is no longer actively developed. See #15105
