### ISSUE TITLE
2.5beta2 crashes in windows cmd

### ISSUE THREAD

**Issue by X-Coder** [ariya/phantomjs#15103]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.5.0-development

2. What steps will reproduce the problem?
    - enter phantomjs without any parameters in cmd, press enter 
    - enter any javascript, doesn't matter which, it crashes on every command. For example: console.log('hello world')

3. Which operating system are you using?
Windows 2012R2

4. Did you use binary PhantomJS or did you compile it from source?
I used precompiled windows binary from [phantomjs-2.5.0-beta2-windows.zip](https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.5.0-beta2-windows.zip)

5. Please provide any additional information below.
This is the error message of the crash:
  Problemereignisname:	APPCRASH
  Anwendungsname:	phantomjs.exe
  Anwendungsversion:	2.5.0.0
  Anwendungszeitstempel:	596210dd
  Fehlermodulname:	ntdll.dll
  Fehlermodulversion:	6.3.9600.18696
  Fehlermodulzeitstempel:	59153753
  Ausnahmecode:	c00000fd
  Ausnahmeoffset:	0000000000030d02
  Betriebsystemversion:	6.3.9600.2.0.0.16.7
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	271e
  Zusatzinformation 2:	271e507b3cb1d7abee4992d36784e3b9
  Zusatzinformation 3:	5677
  Zusatzinformation 4:	5677161906e5a984bf9f50171bebe7b7

Running phantomjs test.js is not crashing. Older versions are working.

**Comment by csvan** [comment]
PhantomJS is abandoned. The maintainer recommends you use Chrome Headless instead.

https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
