### ISSUE TITLE
text-shadow is rendered NOT like in chrome/firefox

### ISSUE THREAD

**Issue by cronfy** [ariya/phantomjs#15117]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

```
$ phantomjs --version
2.1.1
```

2. What steps will reproduce the problem?

Here is a fiddle: https://jsfiddle.net/Cronfy/yyg3a5ec/1/

In browser I see it like this:

![image](https://user-images.githubusercontent.com/762954/29719271-193b1772-89be-11e7-9199-d925c9d85fbb.png)

But in PhantomJS text shadow is much lighter, on second line it is nearly invisible:

![image](https://user-images.githubusercontent.com/762954/29719332-4aad16d4-89be-11e7-9873-ac8085904931.png)

I use this simple script for capture:

```
var page = require('webpage').create();
page.viewportSize = { width: 1920, height: 768 };
page.open('https://jsfiddle.net/Cronfy/yyg3a5ec/1/', function() {
  page.render('main.png');
  phantom.exit();
});
```

3. Which operating system are you using?

Linux Mint 17.3

I also tried [phantomjscloud](https://phantomjscloud.com/api/browser/v2/a-demo-key-with-low-quota-per-ip-address/?request={url:%22https://jsfiddle.net/Cronfy/yyg3a5ec/1/%22,renderType:%22png%22}), result is the same.

4. Did you use binary PhantomJS or did you compile it from source?

I use phantomjs-prebuilt@2.1.15

**Comment by GianCastle** [comment]
Hi, I have the same problem. Were you able to solve it?

Best rewards

**Comment by cronfy** [comment]
@GianCastle yes, but I had to give up with phantomjs as it is not actively supported. To take screenshots I am using [GoogleChrome/puppeteer](https://github.com/GoogleChrome/puppeteer) now.
