### ISSUE TITLE
Phantomjs ignore links to pdf files

### ISSUE THREAD

**Issue by khersonIT** [ariya/phantomjs#15136]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
tested on 2.1.1 (latest stable) and 2.5.0 (latest).
2. What steps will reproduce the problem?

  i. Go to pdf link - http://che.org.il/wp-content/uploads/2016/12/pdf-sample.pdf
This step should be clarified. Attempt to go to the website by GoToUrl method is completely ignored. I try to open link by javascript:

`window.open('http://che.org.il/wp-content/uploads/2016/12/pdf-sample.pdf');`

to get at least some response from phantomjs.
  ii. Get a blank page without (!) url to pdf or title and with next html struct:

`<html><head></head><body></body></html>` 

3. Which operating system are you using?
Windows 7 x64
4. Did you use binary PhantomJS or did you compile it from source?
Binary
5. Please provide any additional information below.
I encountered this error when working on a site that generates a link to a Pdf file when you click on the button and opens it in a new tab. Next I want to get this link then download the file. In chrome everything works fine, but phantomjs generates a blank page, so there is no way to get a link.

**Comment by khersonIT** [comment]
Why issue was closed? Is it solved in latest version?

**Comment by pixiuPL** [comment]
@khersonIT Yes, I've been working on it recently and it'll be fixed in the 2.1.4
