### ISSUE TITLE
function renderBuffer Blocking process

### ISSUE THREAD

**Issue by seven-tan** [ariya/phantomjs#15134]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
     v2.1.1
2. What steps will reproduce the problem?
  1.var buffer = page.renderBuffer(format, quality);  Blocking process

3. Which operating system are you using?
  ubuntu16

**Comment by fvolohin** [comment]
As I understand, this method is not implemented yet https://github.com/ariya/phantomjs/issues/14285
