### ISSUE TITLE
PhantomJS erroneously elevates `console.error` calls to `onError`

### ISSUE THREAD

**Issue by ticky** [ariya/phantomjs#15132]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
Run this script:
```js
var page = require('webpage').create();

page.onError = function (msg) {
  console.log('onError ' + msg);
};

page.onConsoleMessage = function (msg) {
  console.log('onConsoleMessage ' + msg);
};

page.evaluate(function () {
  console.log('Console log');
  console.error('Console error');
  throw new Error('Uncaught error');
});

phantom.exit();
```

And note that the output is:

```
onConsoleMessage Console log
onError Console error
onError Error: Uncaught error
```

3. Which operating system are you using?
macOS 10.12

4. Did you use binary PhantomJS or did you compile it from source?
binary, from Homebrew

5. Please provide any additional information below.
Pertinent source is at:
https://github.com/ariya/phantomjs/blob/35c0cbb82b614268a09cf4728d0ad19634a7c6de/src/webpage.cpp#L179-L181

`console.error` doesn’t trigger a global error callback in any browser I can find. This behaviour seems to be inconsistent.

It would be more helpful if in 2.5 all console messages were passed to `onConsoleMessage`, and the callback was passed the severity. `onError` should only ever be passed actual, honest-to-goodness uncaught errors.

This current behaviour causes strange interactions with things like React.js, which [use `console.error` in development builds](https://github.com/facebook/fbjs/blob/ec77199fd42a9713204c132ad6788fcfd8e9485b/packages/fbjs/src/__forks__/warning.js#L32-L37) to produce useful console output in browsers, but this causes [things like Poltergeist](https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/client/web_page.coffee#L77-L86) to consider tests using PhantomJS to have failed unless all JS errors are ignored.

See also #14776. I think a change which fixes my issue would also allow them more control! Also #14346.

**Comment by ticky** [comment]
Sorry, why was this closed?

**Comment by pixiuPL** [comment]
@ticky as this is queued to be done later (when other things get done).
