### ISSUE TITLE
Google map markers are not showing with phantomjs 1.9.8 on jsreport platform with recipe phantom-pdf

### ISSUE THREAD

**Issue by RajeevkumarRathore** [ariya/phantomjs#15144]
Few days back phantomjs 1.9.8 was working fine with google map markers.I face this issue from today.Can anyone please tell me why this issue occur from today and how can we fix it with phantomjs 1.9.8.
If I use phantomjs versions 2.1.1 then markers are shown but report design is distorted.

**Comment by afs6969** [comment]
Facing the same issue.
