### ISSUE TITLE
Test Case failure with Python 2.7.13

### ISSUE THREAD

**Issue by anujajakhade** [ariya/phantomjs#15149]
1. I am running PhantomJS version 2.1.1 on Intel.  I have built PhantomJS from source.

2. While executing the test cases using Python 2.7.13, I am observing one test case failure.
```
module/webserver/requests: ERROR
ERROR: setup failed
ERROR: assert_is_false: expected false got true
```
The same test case passes when I use python 2.7.9. Is there any Python specific requirement for this test case?

**Comment by rajendraarora16** [comment]
On what platform you did build standalone executable file? can you please share in more details.

**Comment by anujajakhade** [comment]
I am working on RHEL 7.3

**Comment by srajmane** [comment]
I am facing same issue on SLES 12 SP3 with Python 2.7.13
