### ISSUE TITLE
Update modernizr to 3.5.0 for features.js example

### ISSUE THREAD

**Issue by sbai** [ariya/phantomjs#15150]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. Run the features.js example using the included modernizr 2.8.2.

3. Which operating system are you using?
MacOS Sierra

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
The modernizr used by features.js is quite old now.

**Comment by sbai** [comment]
:-1:

**Comment by pixiuPL** [comment]
@sbai what did you try to say by this emoticon?

**Comment by sbai** [comment]
You closed the ticket after four months without any discussion or doing anything to fix the problem. But that's okay, I'm using headless Chrome now.
