### ISSUE TITLE
node child_process spawn call phantomjs  

### ISSUE THREAD

**Issue by branchesGit** [ariya/phantomjs#15156]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1. node  had call phantomjs  process, but  don't execute  js file 
  2.
  3.

3. Which operating system are you using?

4. Did you use binary PhantomJS or did you compile it from source?
no 
5. Please provide any additional information below.

I really need some help,  i don't know what's wrong with this problem,  when  i start write this code , is exeucte ok.  But, after one month, i doesn't work!

**Comment by rajendraarora16** [comment]
As per my knowledge, `phantomjs 2.1.1` is stable version. You can download it from here: 
[https://bitbucket.org/ariya/phantomjs/downloads/](https://bitbucket.org/ariya/phantomjs/downloads/)

**Comment by vp131** [comment]
Give more info such as code snippet, etc
