### ISSUE TITLE
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/3c041f42-679a-ea4a-242626c9-593e2e54.dmp , Segmentation fault error: if you are using macOS Sierra with phantomjs < 2 remember that phantomjs < 2 does not work there and has bugs (https://github.com/ariya/phantomjs/issues/14558), try to upgrade to phantom 2 if using macOS Sierra

### ISSUE THREAD

**Issue by ragesh-kannan** [ariya/phantomjs#15152]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
    2.1.1
2. What steps will reproduce the problem?
    Creating large reports results in **PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/3c041f42-679a-ea4a-242626c9-593e2e54.dmp
, Segmentation fault error: if you are using macOS Sierra with phantomjs < 2 remember that phantomjs < 2 does not work there and has bugs (https://github.com/ariya/phantomjs/issues/14558), try to upgrade to phantom 2 if using macOS Sierra**
3. Which operating system are you using?
   linux
4. Did you use binary PhantomJS or did you compile it from source?
  binary
5. Please provide any additional information below.
im using phantomjs via jsreport to creating a large report and ended up with the above error result

**Comment by codepearlex** [comment]
Same error here.

1. Which version of PhantomJS are you using? Tip: run phantomjs --version.
**2.1.1**

2. What steps will reproduce the problem?
**See 4.**

3. Which operating system are you using?
**Arch Linux**

4. Did you use binary PhantomJS or did you compile it from source?
**I installed phantomjs via npm.**

5. Please provide any additional information below.

-----

#### ./global.js
```javascript
var _viewportSizes = [
    {width: 1920, height: 1080},
    {width: 375, height: 667}
]

casper.freeOfErrorTest = function( name, url ) {
    casper.test.begin('\n********** '+name+' **********\n', 1, function freeOfErrors(test) {
        phantom.cookies = [];
        casper.start();
        casper.setHttpAuth(_users.admin.username, _users.admin.password);
        casper.thenOpen(url, function() {
            test.assertFreeOfErrors();
        });
        casper.then(function() {
            this.capture(_capturePath+name+".png");
        });
        casper.run(function() {
            test.done();
        });
    });
};
```

#### ./scenarios/scenario1/test.js
```javascript
phantom.injectJs( './global.js');
_viewportSizes.forEach( function (viewportSize, index) {
    casper.options.viewportSize = viewportSize;
    casper.freeOfErrorTest ( "flightArchive_"+_getViewportSizeString(), _rootURL + "/" );
});
```

#### Execution:
```bash
node_modules/casperjs/bin/casperjs --ignore-ssl-errors=true test ./scenarios/
```

-----

When I alter global.js like this (remove the other viewport size, s.th. the loop gets executed only once) the error disappears:

#### ./global.js
```javascript
var _viewportSizes = [
    {width: 1920, height: 1080}
]
```

It should be noted that I have multiple scenarios. Executing multiple tests in separate scenarios doesn't seem to be a problem. Executing multiple tests **in a loop** in the same scenario, however, is not working.

**Comment by codepearlex** [comment]
Same error here.

1. Which version of PhantomJS are you using? Tip: run phantomjs --version.
**2.1.1**

2. What steps will reproduce the problem?
**I use CasperJS 1.1.4 to test my website. See 5. for details.**

3. Which operating system are you using?
**Arch Linux**

4. Did you use binary PhantomJS or did you compile it from source?
**I installed phantomjs via npm.**

5. Please provide any additional information below.

-----

#### ./global.js
```javascript
var _viewportSizes = [
    {width: 1920, height: 1080},
    {width: 375, height: 667}
]

casper.freeOfErrorTest = function( name, url ) {
    casper.test.begin('\n********** '+name+' **********\n', 1, function freeOfErrors(test) {
        phantom.cookies = [];
        casper.start();
        casper.setHttpAuth(_users.admin.username, _users.admin.password);
        casper.thenOpen(url, function() {
            test.assertFreeOfErrors();
        });
        casper.then(function() {
            this.capture(_capturePath+name+".png");
        });
        casper.run(function() {
            test.done();
        });
    });
};
```

#### ./scenarios/scenario1/test.js
```javascript
phantom.injectJs( './global.js');
_viewportSizes.forEach( function (viewportSize, index) {
    casper.options.viewportSize = viewportSize;
    casper.freeOfErrorTest ( "flightArchive_"+_getViewportSizeString(), _rootURL + "/" );
});
```

#### Execution:
```bash
node_modules/casperjs/bin/casperjs --ignore-ssl-errors=true test ./scenarios/
```

-----

When I alter global.js like this (remove the other viewport size, s.th. the loop gets executed only once) the error disappears:

#### ./global.js
```javascript
var _viewportSizes = [
    {width: 1920, height: 1080}
]
```

It should be noted that I have multiple scenarios. Executing multiple tests in separate scenarios doesn't seem to be a problem. Executing multiple tests **in a loop** in the same scenario, however, is not working.

**Comment by alex-arriaga** [comment]
Hi, did you find the actual cause of this?
Thanks.
