### ISSUE TITLE
 WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time:   phantomjs://platform/console++.js:263 in error

### ISSUE THREAD

**Issue by AnjumMomin** [ariya/phantomjs#15157]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
 phantomjs 2.1.1
2. What steps will reproduce the problem?
  1.can't find webelement 
  2.It's working on windows but it can't run on linux
  3.

3. Which operating system are you using?
windows 7 and Linux

4. Did you use binary PhantomJS or did you compile it from source?
No

5. Please provide any additional information below.
Error-
[ERROR - 2017-10-12T10:22:02.924Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1507803722910

  phantomjs://platform/console++.js:263 in error

![image](https://user-images.githubusercontent.com/29423781/31491970-c9d78930-af66-11e7-987e-72348c8c3207.png)

![image](https://user-images.githubusercontent.com/29423781/31492085-27a11932-af67-11e7-8de2-b14addfefb2e.png)

**Comment by jgros32** [comment]
I also experience this error. I am using phantomjs 2.1.1 version.
The script is working on firefox and chrome browsers but can't recognize certain objects when using phantomjs.

09:09:42.123 WARN - Exception: {"errorMessage":"Unable to find element with xpat
h './/input[@id='input-firstName']'","request":{"headers":{"Accept-Encoding":"gz
ip,deflate","Connection":"Keep-Alive","Content-Length":"59","Content-Type":"appl
ication/json; charset=utf-8","Host":"localhost:21221","User-Agent":"Apache-HttpC
lient/4.5.2 (Java/1.8.0_121)"},"httpVersion":"1.1","method":"POST","post":"{\"us
ing\":\"xpath\",\"value\":\".//input[@id='input-firstName']\"}","url":"/element"
,"urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/e
lement","relative":"/element","port":"","host":"","password":"","user":"","userI
nfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":
["element"]},"urlOriginal":"/session/2fce06a0-b3a0-11e7-844e-03ecdf0b3ca8/elemen
t"}}
