### ISSUE TITLE
Many webs detect phantomjs as bot for being a headless browser, will there be a version that corrects this serious problem?

### ISSUE THREAD

**Issue by fran0254** [ariya/phantomjs#15159]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1.
  2.
  3.

3. Which operating system are you using?
ubuntu
4. Did you use binary PhantomJS or did you compile it from source?
you compile it from source
5. Please provide any additional information below.

**Comment by rajendraarora16** [comment]
Try using `headless chrome` that would be I guess behaved as a browser.

**Comment by fran0254** [comment]
Is it compatible with phantomjs ?

**Comment by superhero** [comment]
I'm not sure if you refer to the agent header? I do something like this, could it help?
```
  var page = webPage.create();

  // Default settings..
  page.settings =
  {
    userAgent       : 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36',
    loadImages      : false
  };

  // Reading the content of the requested url..
  page.open(args.url, function(status)
  {
....
```

**Comment by ariya** [comment]
Implementing this is a major undertaking and currently beyond the scope of the project.
You are however free to work on it on your own or sponsor someone to implement it. Once it is in a state where we can consider it for inclusion, please reopen this issue and submit a pull request of the implementation. Thank you!
