### ISSUE TITLE
Performance and Resources issue

### ISSUE THREAD

**Issue by jt4000** [ariya/phantomjs#15162]
I have used phantom JS with Selenium in relation to .net in production phase and when you start using it takes about 80 MB memory and if you use 4 Phantom JS in parallell the memory will be 4 x 80 MB memory.

The goal is to retrieve the source code of the webpage without visualize it. 

My questions are:

1.
Does it take a lot resouces when you use it in relation to selenium (with phantom driver)?

2.
Is there another solution to retrieve the sourcecode with high performance and low resources.

Thank you!

**Comment by btrewern** [comment]
80MB doesn't sound too bad for a full web browser.  Curl or wget might be what you want?

**Comment by ariya** [comment]
Implementing this is a major undertaking and currently beyond the scope of the project.
You are however free to work on it on your own or sponsor someone to implement it. Once it is in a state where we can consider it for inclusion, please reopen this issue and submit a pull request of the implementation. Thank you!
