### ISSUE TITLE
does not respect referrer-policy

### ISSUE THREAD

**Issue by azul** [ariya/phantomjs#15164]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  * test a page with meta tag name="referrer" content="no-referrer"
  * click a link
  * the referrer was send to the linked page

3. Which operating system are you using?
linux

4. Did you use binary PhantomJS or did you compile it from source?
ruby gem 'phantomjs-binaries', '~> 2.1.1'

5. Please provide any additional information below.
This is from a test driven with poltergeist. I don't think it matters but i will try to isolate the problem in a purer phantomJS setting.

**Comment by pacoyang** [comment]
Same problem
