### ISSUE TITLE
Wiki broke

### ISSUE THREAD

**Issue by TheJaredWilcurt** [ariya/phantomjs#15176]
https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage/_compare/41277d919d3b1216c3850cb4d3a19f0141144b80...14e2e75be29b6bd44c1c807fa66bd613c5ad647a

Several wiki pages are replaced with emoji characters.

**Comment by markhu** [comment]
That particular page got fixed: https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage
--but others seem to be oddly wiki-vandalized.

**Comment by TheJaredWilcurt** [comment]
Fixed.
