### ISSUE TITLE
Phantomjs upload photo failed on : https://www.facebook.com/ads/tools/text_overlay

### ISSUE THREAD

**Issue by baobaosan** [ariya/phantomjs#15178]
I use both phantomjs v2.1 and phantomjs Beta v2.5 are all failed. my code as below:
	this.then(function() {
	   this.page.uploadFile("._3jk input[type='file']", PhotoPath);
	});
 It is failed, and no error message be given, I try casperjs + phantomjs, the code as below:
casper.then(function() {
    this.fill('._3jk', {
        'image': PhotoPath
    }, true);
});
It is failed as well. and gave the error message: 
submitting form to unknown, HTTP GET[warning] [remote] unable to submit form[info]

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
