### ISSUE TITLE
PhantomJS fails on ES8, implemented in all common browsers

### ISSUE THREAD

**Issue by SimonSimCity** [ariya/phantomjs#15172]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

PhantomJS is installed in version 2.1.1

2. What steps will reproduce the problem?
  2.1. Write a website calling `''.padStart(1, '-')`
  2.2. Watch it failing 😉 

3. Which operating system are you using?

Mac OS X 10.11.6

4. Did you use binary PhantomJS or did you compile it from source?

Binary

5. Please provide any additional information below.

I expected the method, standardized in ES8 to work in PhantomJS because it works in all major browsers, including NodeJS.

* http://node.green/#ES2017-features-String-padding-String-prototype-padStart
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart#Browser_compatibility

6. Do you know of a workaround?

Yes, just use the polyfil method provided on the MDN website: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart#Polyfill

I saw that you referred to a version `2.5.0` on #14951, which is in beta phase as of the time writing, but this version doesn't solve it.

**Comment by ariya** [comment]
Modern JavaScript features (from ES6/ES2015 or later) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
