### ISSUE TITLE
PhantomJS fails to deal with the Spread Operator

### ISSUE THREAD

**Issue by patrickbard** [ariya/phantomjs#15187]
_1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`._
PhantomJS 2.1.1

_2. What steps will reproduce the problem?_
  1. Use PhantomJS to run Karma/Jasmine tests
  2. Test a file which makes use of a [Spread Operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator)

_3. Which operating system are you using?_
Ubuntu 16.04

_4. Did you use binary PhantomJS or did you compile it from source?_
Binary

_5. Please provide any additional information below._
Whe have a ESLint rule which says:

> Suggest using the spread operator instead of .apply(). (prefer-spread)

I've changed a few places where that applies, and suddenly the whole build was failing, here is the log:

[INFO] PhantomJS 2.1.1 (Linux 0

> .0.0) ERROR
> [INFO]   SyntaxError: Unexpected token '.'
> [INFO]   at path/to/file.js:lineNumber

It was even worse to detact the problem since lineNumber does not correspond to the place where the spread operator was used. But since it was the only major difference between the last successful build, I could verify that this piece of code

`successCallback(... params);`

need to be changed back to this in order to work

`successCallback.apply(null, params);`

**Comment by apokryfos** [comment]
I couldn't find any details anywhere but provided that the spread operator is an ES2015 operator and it doesn't seem that PhantomJS supports it (chances are there's very little ES2015 support). You probably need to be transpiling your JavaScript to target older browsers.

**Comment by ariya** [comment]
Modern JavaScript features (from ES6/ES2015 or later) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
