### ISSUE TITLE
Got error 'ImageDataConstructor is not a constructor' will calling new ImageData(5, 6)

### ISSUE THREAD

**Issue by scozic** [ariya/phantomjs#15185]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
PhantomJS 2.1.1 (Linux 0.0.0)
2. What steps will reproduce the problem?
   1. Setup a VueJS project using 'webpack' template : e.g.:
  `yarn yarn global add vue-cliI `
   `vue init webpack myProject`
Select default options e.g. karma+mocha for unit tests. Then initialize the project with NPM or Yarn
   `cd myProject && yarn`
   2. Create test unit test file ```test\unit\specs\image.spec.js```
```javascript
describe('Test creation of ImageData', function () {
  it('Test creation of ImageData using ImageData(width, height) constructor', function () {
    let imageData = new ImageData(5, 6)
    expect(imageData.data.length).to.equal(5 * 6 * 4)
  })
})
```
   3. Execute tests:
`yarn run test`
Test will fail with the following error:
```
  Test for image.js
    ✗ Test creation of ImageData using ImageData(width, height) constructor
	ImageDataConstructor is not a constructor (evaluating 'new ImageData(5, 6)')
	http://localhost:9877webpack:///test/unit/specs/image.spec.js:3:34 <- index.js:12139:34
```

3. Which operating system are you using?
Linux i7 4.4.0-97-generic (x64)

4. Did you use binary PhantomJS or did you compile it from source?
Binary
5. Please provide any additional information below.
What proves this error is related to Phantom JS is using firefox browser instead.
Changing:
```test/unit/karma.conf.js``` : 
``` browsers: ['PhantomJS'],```
with
``` browsers: ['Firefox'],```
Tests will pass.

I am quite new to PhantomJS, is there some configuration that would prevent ```ImageData``` features not to be supported?

Thank you.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
