### ISSUE TITLE
how can i copy text to clipboard

### ISSUE THREAD

**Issue by rebelboy** [ariya/phantomjs#15197]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
     2.1.1
2. What steps will reproduce the problem?
   i want to copy some text to clipboard.
   my code:
```
 1           $("#fff").val("2222222343333");
 2           $("#fff").focus();
 3           $("#fff").select();
 4            page.sendEvent('keypress', 'c', null, null, page.event.modifier.ctrl);
```

dont use 1,2,3 how can do it

   help me thanks

  
3. Which operating system are you using?
windows 10 64bit

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
