### ISSUE TITLE
How to build from source - The guides I have found only works for older versions

### ISSUE THREAD

**Issue by clarkk** [ariya/phantomjs#15191]
I need some of the updates comitted after the last release 2.1.1

But I can't find a guide how to build and install

I need to build and install master

http://phantomjs.org/build.html

```
# git clone https://github.com/ariya/phantomjs.git
# cd phantomjs
```

But there is no build.py file?

**Comment by clarkk** [comment]
Sorry

This is the solution :)

```
page.onLoadFinished = function(status) {
   page.render('/dev/stdout', {format : 'pdf'});
    phantom.exit();
};
```

**Comment by ashawley** [comment]
The current master is for an incomplete version 2.5, see #14458

**Comment by xxfelixxx** [comment]
Could someone update the build.html page?  Maybe suggest that to build they checkout version X.Y.Z?

**Comment by ariya** [comment]
This should up-to-date again now. Thank you very much!
