### ISSUE TITLE
Not working with IIS

### ISSUE THREAD

**Issue by gauravsrmsin** [ariya/phantomjs#15198]
1. 2.1.1.

2. Which operating system are you using?

Win 7

3. Did you use binary PhantomJS or did you compile it from source?
Binary 

4. Please provide any additional information below.
Hi, i am trying to capture image from browser. Everything is working perfectly fine from my local computer. Once I deployed the code in IIS,  image is not generating in that case.
I am using C# ASP.net MVC 5

**Comment by ariya** [comment]
Please provide a simple reproducible test case and then reopen the issue.
