### ISSUE TITLE
MAC 10.12 phantomjs Operation not permitted

### ISSUE THREAD

**Issue by jinzb** [ariya/phantomjs#15199]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
     PhantomJS :phantomjs-2.1.1-macosx
2. What steps will reproduce the problem?
  1.phantomjs --version
  2.-bash: /Users/XXX/PycharmProjects/phantomjs-2.1.1-macosx/bin/phantomjs: Operation not permitted
  
![image](https://user-images.githubusercontent.com/25708645/33130006-d9109442-cfcc-11e7-937c-6edf299663b4.png)

**Comment by ariya** [comment]
Did you run it as root? If yes, try it again as a normal user.
