### ISSUE TITLE
phantomjs.exe does not exit after the desired operation is complete.

### ISSUE THREAD

**Issue by tosanjayrajpal** [ariya/phantomjs#15194]
1. Which version of PhantomJS are you using?  
  Version: 2.1.1

2. What steps will reproduce the problem?
  We are running this tool using command line, and generating a screenshot of the web page.

3. Which operating system are you using? 
Windows Server 2012

4. Did you use binary PhantomJS or did you compile it from source? 
We are using PhantomJS.exe.

5. Please provide any additional information below.
Rasterize.js file used is as given below:
var page = require('webpage').create(),
    system = require('system'),
    address, output, size;

if (false) {
    console.log('Usage: rasterize.js URL filename [paperwidth*paperheight|paperformat] [zoom]');
    console.log('  paper (pdf output) examples: "5in*7.5in", "10cm*20cm", "A4", "Letter"');
    phantom.exit(1);
} else {
    address = system.args[1];
    output = system.args[2];
    var username = system.args[3];
    var password = system.args[4];
    width = system.args[5];
    height = system.args[6];
    page.viewportSize = { width: width, height: height };
    page.settings.userName = username;
    page.settings.password = password;
	
	page.paperSize = { width: width, height: height, margin: '0px' }
    page.onConsoleMessage = function(msg) {
       console.log(msg);
    };

    page.open(address, function (status) {
        if (status !== 'success') {
            console.log('Unable to load the address!');
            phantom.exit();
        } else {
                window.setTimeout(function () {
	       console.log("about to render");
                    page.render(output);
                    phantom.exit();
                }, 10000);
        }
    });
}

What happens is sometimes phantomjs.exe does not close it's process' instance in Task Manager. And our subsequent jobs do not run as a result of this. We want to make sure no matter what happens, phantomjs.exe should close gracefully after the job is completed, and other jobs are processed successfully. 

Any help/suggestions with troubleshooting this issue is highly appreciated. Could you please help asap ?

-Sanjay

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
