### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Service phantomjs unexpectedly exited. Status code was: 1

### ISSUE THREAD

**Issue by wa15aa** [ariya/phantomjs#15208]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
use python from selenium import webdriver 
2. What steps will reproduce the problem?
  1.when start scrapy
  2.
  3.

3. Which operating system are you using?
mac
4. Did you use binary PhantomJS or did you compile it from source?
no
5. Please provide any additional information below.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
