### ISSUE TITLE
the link in update libs script is expired and gives 404

### ISSUE THREAD

**Issue by developernew123** [ariya/phantomjs#15206]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
I didn't build yet
2. What steps will reproduce the problem?
  1.
  2.
  3.

3. Which operating system are you using?
windows 8
4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.

this is my output when I run the script

Checking Last-Modified date of qtwebkit-libs-win.zip...
Could not access https://dl.dropboxusercontent.com/u/30021413/qtwebkit-libs-win.zip:
Connection: close
Date: Mon, 27 Nov 2017 12:41:43 GMT
Server: nginx
Vary: Accept-Encoding
Content-Type: text/html
Client-Date: Mon, 27 Nov 2017 12:40:58 GMT
Client-Peer: 162.125.66.6:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
Client-SSL-Cert-Subject: /C=US/ST=California/L=San Francisco/O=Dropbox, Inc/OU=Dropbox Ops/CN=*.dl.dropboxusercontent.com
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Client-Transfer-Encoding: chunked
Link: <https://cfl.dropboxstatic.com/static/css/error.css>; rel="stylesheet"; type="text/css"
Link: <https://cfl.dropboxstatic.com/static/images/favicon.ico>; rel="shortcut icon"
Strict-Transport-Security: max-age=15552000; includeSubDomains
Title: Dropbox - 404
X-Dropbox-Request-Id: 4009d3eb8df7fac4aee34b8e4710c3bb
X-Robots-Tag: noindex, nofollow, noimageindex

You may not be connected to the internet. Attempting to build without updating.

**Comment by ariya** [comment]
This is likely nothing to do much with PhantomJS. None of PhantomJS built-in functionality reached out to Dropbox to download some files.
Please provide more information to help reproducing the issue. Once that is available, feel free to reopen this issue.
