### ISSUE TITLE
some webkit can NOT be rendered 

### ISSUE THREAD

**Issue by albertyou2** [ariya/phantomjs#15209]
phantomjs version : 2.1.1
OS :mac os 10.12.6:
node :v8.5.0

hi @ariya 
I use phantomjs in nodejs to render some pages to image.
I found that some website can NOT be render by using : 
     "page.render('xxxxxx.png');"

For example "only.tmall.com" can not be render as a image(phantomjs give a empty image to me ) .you can reproduce this issue by using this any time 

I notice that the site is very very very height ,so I guess there may exist some limits in phantomjs wen rendering a page?

Could you please give some help?

thank you very much !

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
