### ISSUE TITLE
Rendering Large HTML file to pdf problem

### ISSUE THREAD

**Issue by engharb** [ariya/phantomjs#15207]
1. Which version of PhantomJS are you using? 
2.1.1

2. What steps will reproduce the problem?
  - I create a large HTML file with 10000 table rows (15 MB)
  - then I want to convert it to pdf

3. Which operating system are you using?
MAC OSX

The problem is when converting a large HTML file size i.e 15MB, phantomJS debug will show me success message but the pdf file will never be generated. In other case like small HTML file i.e 5MB the pdf file are generated successfully. 

I need that to generate invoices pdf file, and it is urgent to file a solution.
I will be very thankful for your help and suggestion.

Regards,

**Comment by michaelfward** [comment]
Do you get any stack traces, etc?

**Comment by engharb** [comment]
What do you mean exactly with stack traces?

**Comment by pixiuPL** [comment]
@engharb is anything suspicious in `/var/log/messages`?

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
