### ISSUE TITLE
Rendering an image of a local HTML file with linked CSS does not render any CSS styles

### ISSUE THREAD

**Issue by Bilge** [ariya/phantomjs#15218]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
`2.1.1`

2. What steps will reproduce the problem?
  1. `phantomjs.exe rasterize.js "file:///C:\Steam Top 250\site\index.html" index.png`

3. Which operating system are you using?
Windows 7

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.
* Output is completely unstyled (see attachment), even if I set the working directory to the same location as `index.html`.
* Typical contents of `index.html` can be found [here](https://github.com/250/Steam-Top-250/blob/gh-pages/index.html), albeit minified.
* When viewed in either Firefox or Chrome, the page displays normally.
* When rendering a [remote version](http://steam250.com) it loads the CSS normally (although fails to load Google fonts). Therefore it seems this problem is directly related to local files.

![index](https://user-images.githubusercontent.com/470626/34022414-0dd9b28c-e137-11e7-839a-27047e145e98.png)

**Comment by mfvaughan** [comment]
This is happening to me as well, but it is only selectively ignore SOME of the styling in the local HTML file, see attached images. 

- PhantomJS version = 2.1.1
- OS = Windows 10
- Generated using Selenium + PhantomJS in Python using "save_screenshot" method on local HTML file

When opened in Chrome, the HTML-formatted table renders just fine, but after saving as .png, some of the filled bar styling is gone, but only in select rows. Strangely, the cells that are missing the orange fill when saves as .png are consistent every time.

<img width="566" alt="png-render" src="https://user-images.githubusercontent.com/12395865/34120866-14eaf994-e3f5-11e7-9933-06a0fc2b3a60.PNG">
<img width="637" alt="browser-render-chrome" src="https://user-images.githubusercontent.com/12395865/34120867-150acc24-e3f5-11e7-89e0-46ab1a86f66f.PNG">

**Comment by mfvaughan** [comment]
FYI - the behavior is the same when I tested on Mac (Sierra) ... the same CSS is selectively ignored when saving local HTML as PNG in my case, both Win10 and Sierra.

**Comment by Bilge** [comment]
Closed without comment?

**Comment by pixiuPL** [comment]
@Bilge Its under heavy investigation so its no point in this issue being opened. Update it once fix is available.
