### ISSUE TITLE
Can not find localStorage in phantomjs-2.5.0-beta-macos

### ISSUE THREAD

**Issue by DerekYeung** [ariya/phantomjs#15212]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
phantomjs-2.5.0-beta-macos
2. What steps will reproduce the problem?
  1.use ptjs2.5.0-beta-macos
  2.use window.localStorage in js
  3.run

3. Which operating system are you using?
macOS High Sierra 10.13.1
4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.
My code:
`
							try{
								window.localStorage.setItem('user', JSON.stringify(user));
								window.localStorage.setItem('menus', JSON.stringify(data));
							}catch(e){
								console.log('没有localStorage');
							}
`

the stack is "null is not an object(evaluating 'window.localStorage.setItem')"

I don't know what's the problem with, the same code is no problem under Windows 10.

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.
