### ISSUE TITLE
phantomjs needs too much RAM and crashes in loop

### ISSUE THREAD

**Issue by marisana** [ariya/phantomjs#15210]
1. `phantomjs --version 2.1.1`.

2. What steps will reproduce the problem?
A composition of different scripts.
  1. page.open
  2. page.content http://phantomjs.org/api/webpage/property/content.html
  3. fs.write
  4. waitFor() https://github.com/ariya/phantomjs/blob/master/examples/waitfor.js
  5. setInterval https://github.com/ariya/phantomjs/blob/master/examples/countdown.js

3. Lubuntu 16.04

4. PhantomJS install over Synaptic

5. The script is running for the first loop correctly. On the second loop get this message in the console:
```
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Abgebrochen (Speicherabzug geschrieben)
```
and this message (not everytime, but on two times) in Lubuntu:
> no memory to send the bug report.

Well, my RAM is too small to do a second loop.

At the moment I have no idea how to fix it, or how to restart it with new loop value after phantom.exit().

**Comment by marisana** [comment]
... page.close(); after fs.write() helps a bit.

**Comment by pixiuPL** [comment]
will look into it.....

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
