### ISSUE TITLE
Rasterize not rendering some unicode characters properly

### ISSUE THREAD

**Issue by samnads** [ariya/phantomjs#15214]
1. Which version of PhantomJS are you using?
     **2.1.1**
2. What steps will reproduce the problem?
   1. Open **https://crush4u.com/test/phantom?width=150&height=76&size=&weight=&text=ഞാന്‍&language=ml&bg=00aaff&color=000&debug**
   2. Check the **text in image** with the **text parameter from url**, both are different

3. Which operating system are you using?
    **Ubuntu 16.04.3 LTS**

4. Did you use binary PhantomJS or did you compile it from source?
   I am using **rasterize.js** to create image from command line
5. Please provide any additional information below.
    After a small research i have found that the problem is with the **Zero-width joiner** (https://en.wikipedia.org/wiki/Zero-width_joiner), how to add support for these type of characters

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
