### ISSUE TITLE
We are using phantomjs convert HTML to PDF, but crashed

### ISSUE THREAD

**Issue by Joo-fanChang** [ariya/phantomjs#15220]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1.HTML file contains Spaces in English and ^M(windows)  will transform failure
  2.HTML files generated by the Windows system
  3.The conversion process is the use of Linux system

3. Which operating system are you using?
Linux
4. Did you use binary PhantomJS or did you compile it from source?
yes
5. Please provide any additional information below.

**Comment by takashiro** [comment]
I guess PhantomJS crashed here in your case. https://github.com/Vitallium/qtbase/blob/phantomjs/src/gui/text/qfontsubset.cpp#L962
Some glyph may contain only one element. So it can't be converted into a path. Try to modify it into `if (path.elementCount() > 1) {` and rebuild PhantomJS.

**Comment by Vitallium** [comment]
If the problem is in the Qt code, I suggest to test against the Qt 5.9 and if the problem still exists, file your bug in their bug tracker.
