### ISSUE TITLE
Example Code out of date - Windows version

### ISSUE THREAD

**Issue by jlbowm** [ariya/phantomjs#15228]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. Example useragent.js
  2.
  3.

3. Which operating system are you using?
Windows

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.

The offending code is :

return document.getElementById('myagent').innerText; 

The fix would be:

return document.getElementById('qua').value;

Happy holidays!

**Comment by pixiuPL** [comment]
Test now please
