### ISSUE TITLE
After 250+ Requests, PhantomJS crashes

### ISSUE THREAD

**Issue by NirviDoshi** [ariya/phantomjs#15229]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1.  We have a PhantomJS webserver running which makes request to another server for html, renders the content to pdf file, reads from the pdf file and returns contents of pdf file in form of response.
  2.  PFA javascript we are using when starting PhantomJS 
 
[sample.txt](https://github.com/ariya/phantomjs/files/1589690/sample.txt)

3. Which operating system are you using?
Linux 2.6.32-696.6.3.el6.x86_64
4. Did you use binary PhantomJS or did you compile it from source?
Binary PhantomJS
5. Please provide any additional information below.
Below is the stack trace

1   0x1b67967 ./phantomjs() [0x1b67967]
2   0x1b91e92 ./phantomjs() [0x1b91e92]
3   0x1b91f58 ./phantomjs() [0x1b91f58]
4   0x1aa48a0 ./phantomjs() [0x1aa48a0]
5   0x188f2a5 ./phantomjs() [0x188f2a5]
6   0x188fad5 ./phantomjs() [0x188fad5]
7   0x1aad842 ./phantomjs() [0x1aad842]
8   0x1892c94 ./phantomjs() [0x1892c94]
9   0x22f8909 ./phantomjs() [0x22f8909]
10  0x4ac3bc ./phantomjs() [0x4ac3bc]
11  0x4b0000 ./phantomjs() [0x4b0000]
12  0x22d1036 ./phantomjs() [0x22d1036]
13  0x231633c ./phantomjs() [0x231633c]
14  0x23146e0 ./phantomjs() [0x23146e0]
15  0x1bbf4b5 ./phantomjs() [0x1bbf4b5]
16  0x22cf7a9 ./phantomjs() [0x22cf7a9]
17  0x22d4585 ./phantomjs() [0x22d4585]
18  0x415b9a ./phantomjs() [0x415b9a]
19  0x3d8541ed1d /lib64/libc.so.6(__libc_start_main+0xfd) [0x3d8541ed1d]
20  0x4176a1 ./phantomjs() [0x4176a1]
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

**Comment by pixiuPL** [comment]
@NirviDoshi First off => PJS 2.1.1 **will not**work steady on kernel that old. Upgrade kernel to 3.x branch (possibly even 4.x branch) and than try again. If this issue will pop-up again, than let us know.
