### ISSUE TITLE
Can't scroll youtube videos page. I see only the first page. Source code included.

### ISSUE THREAD

**Issue by ProgrammingLife** [ariya/phantomjs#15226]
PhantomJS 2.1.1, MacOS X 10.12.5

I attached my source code here: https://pastebin.com/LjsA9mhu
I try to scroll down 3 or more pages and save it to the output test.html file but there's only the first page I see. Looks like it doesn't scroll the page properly. You see how many tries I have done for getting it to work and nothing works:

//document.body.scrollTop = document.body.scrollHeight;
//window.scrollTo( 0, document.body.scrollHeight );
//window.document.body.scrollTop = document.body.scrollHeight;
//window.scrollTo(0, Math.max(Math.max(document.body.scrollHeight,document.docume‌​ntElement.scrollHeig‌​ht),Math.max(documen‌​t.body.offsetHeight,‌​document.documentEle‌​ment.offsetHeight),M‌​ath.max(document.bod‌​y.clientHeight, document.documentElement.clientHeight)));
//window.scrollTo( 0, document.body.scrollHeight || document.documentElement.scrollHeight );

What do I do wrong here?

**Comment by pixiuPL** [comment]
@ProgrammingLife Could you possibly specify the **exact** version (screenshot would be best) of macOS you are using? Thanks

**Comment by ProgrammingLife** [comment]
@pixiuPL I'm using 10.12.5. I don't think it works like this because of my OS. I tried to run it is as well on Debian (the latest versions) and Ubuntu - works the same.

**Comment by pixiuPL** [comment]
Without any deeper investigation, I would **guess** that this is not PJS problem/bug, but its system specific. Do you have option (=switch) to enable/disable smooth scrolling in your videocard/DEs' settings panel?

I will let core devs know about your issue and we will work on this, but after Christmas. Happy Christmas :)
