### ISSUE TITLE
build debug && VS project create?

### ISSUE THREAD

**Issue by codeliving** [ariya/phantomjs#15232]
Build 2.1.1 debug on win10-64bit,IDE:VS2013.
I git msvc2013_debug from https://github.com/Vitallium/phantomjs-3rdparty-win/tree/msvc2013_debug.
because msvc2013_debug have no zlib,I copy zlib from msvc2013,So debug build OK!
there have an error as follow,when run.
PS D:\phantomjs\phantomjs> .\bin\phantomjs.exe .\examples\hello.js
Hello, world!
LEAK: 12 WebCoreNode

what is LEAK: 12 WebCoreNode???

I want know how to create VS project file,and how to build project using VS2013IDE???

**Comment by pixiuPL** [comment]
Similar to #14714

**Comment by codeliving** [comment]
@Vitallium could you make a tutorial explaining how to build a debug phantomJS2.1.1?
I have built debug follow the tutorial in #13339, made by @iradul. but failed due to lossing zlib.
So,I copy zlib from msvc2013 to msvc2013_debug.finally,build OK!
when run it:
PS D:\phantomjs\phantomjs> .\bin\phantomjs.exe .\examples\hello.js
Hello, world!
LEAK: 12 WebCoreNode

what is LEAK: 12 WebCoreNode???

**Comment by codeliving** [comment]
@pixiuPL thank you! I want build PJS with debug option on windows. I have built PJS with release successfully on linux and windows.But I want to study PJS source code,need debug.
For more,could you tell me how to build a VS project file,build PJS with VS-IDE?

**Comment by pixiuPL** [comment]
Unfortunately I cannot tell you how to build PJS on windows as Im Unix user a and have no access to Windows.

**Comment by codeliving** [comment]
@pixiuPL OK,thank you ! I just want to stduy PJS source code,so need debug,best to have graphical IDE.
OS does not matter，windows or linux，all is OK.
1.Could you tell how to build debug on Unix? debug!
2.Which Unix system do you use? What is the Unix version?
3.Which graphical IDE can debug PHJ code?

**Comment by pixiuPL** [comment]
@codeliving I use Ubuntu Server 16.4 without graphical interface (console only).
As of IDE, you can try MonoDevelop or Netbeans (Eclipse sucks so forget about it).

**Comment by codeliving** [comment]
@pixiuPL OK,thank you very much.
