### ISSUE TITLE
Build PJS debug with Vs2015!

### ISSUE THREAD

**Issue by codeliving** [ariya/phantomjs#15234]
similar to #15232
I build debug PJS with Vs2015 on win10.
I git msvc2015-debug from 3rdparty. follow is error
![image](https://user-images.githubusercontent.com/9834687/34633966-bcb31d5e-f2ba-11e7-9e1e-88259fc3d8ae.png)

 I just want to stduy PJS source code,so need debug,best to have graphical IDE.
OS does not matter，windows or linux，all is OK.

**Comment by pixiuPL** [comment]
@codeliving just use pure shell in Linux with vim :)

**Comment by pixiuPL** [comment]
#15232
