### ISSUE TITLE
Multiple merge conflict code blocks

### ISSUE THREAD

**Issue by guessi** [ariya/phantomjs#15235]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
v2.1.2 (>2.1.1), current master branch

2. What steps will reproduce the problem?
Simple grep "<<<<<<< HEAD" across the repository

3. Which operating system are you using?
Not related

4. Did you use binary PhantomJS or did you compile it from source?
Compile from source

5. Please provide any additional information below.
Multiple merge conflict code blocks could be found in current master, listed as follow

`./src/config`
- https://github.com/ariya/phantomjs/blob/master/src/config.h#L40-L71
- https://github.com/ariya/phantomjs/blob/master/src/config.h#L89-L247

`./src/network/networkaccessmanager.cpp`
- https://github.com/ariya/phantomjs/blob/master/src/network/networkaccessmanager.cpp#L326-L345

`./src/webpage.h`
- https://github.com/ariya/phantomjs/blob/master/src/webpage.h#L35-L41
- https://github.com/ariya/phantomjs/blob/master/src/webpage.h#L261-L285
- https://github.com/ariya/phantomjs/blob/master/src/webpage.h#L563-L567

`./test/module/webpage/render-base64.js`
- https://github.com/ariya/phantomjs/blob/master/test/module/webpage/render-base64.js#L6-L37
- https://github.com/ariya/phantomjs/blob/master/test/module/webpage/render-base64.js#L45-L118

**Comment by pixiuPL** [comment]
All is known and is being worked on. But it takes time....

**Comment by onlyjob** [comment]
This is still a problem in 2.1.3 tarball...

**Comment by pixiuPL** [comment]
@onlyjob All due to some buggy mechanism sitting somewhere deep inside `Online fixer`of GitHub itself. This mechanism adds those strange lines everytime we fix broken commit online (by the means of online form). When we delete those lines traditionally (via CLI) and push changes, there are no strange lines. So its important for commiters to use CLI only.

**Comment by onlyjob** [comment]
Thanks, it is better but not completely fixed yet -- there is (at least) _unterminated #ifdef_ in https://github.com/ariya/phantomjs/blob/master/src/config.h#L32

Please don't just close bugs without confirmation that the problem is resolved... I can't re-open and the problem is still there...

**Comment by guessi** [comment]
@onlyjob can't reopen the issue.

@pixiuPL Pin your name for visibility

**Comment by onlyjob** [comment]
Another merge conflict leftover: https://github.com/ariya/phantomjs/blob/master/src/webpagerenderer.h#L41
