### ISSUE TITLE
Bug: Contrary to the HTML spec, inputs of type "submit" are not sent during forms submission

### ISSUE THREAD

**Issue by Lucas-C** [ariya/phantomjs#15236]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  - create the `index.html`, `bug_repro.phantom.js` and `dump_post_data_and_redirect.js` files as specified below
  - run `node dump_post_data_and_redirect.js` to launch a basic server able to answer POST requests
  - run `phantomjs bug_repro.phantom.js` to witness the issue

3. Which operating system are you using?
Windows 10

4. Did you use binary PhantomJS or did you compile it from source?
Binary from https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-windows.zip

5. Please provide any additional information below.

### The files needed to reproduce the bug

- `index.html` : contains a simple `form` with a single `input` of type `submit` and of value `Connexion`:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
    </head>
    <body>
        <form method="post">
            <input name="login" type="submit" value="Connexion">
        </form>
    </body>
</html>
```

- `bug_repro.phantom.js` : a PhantomJS script that simply submit the first form in the page, and then wait 1 second
```
const page = require('webpage').create()
page.onResourceRequested = function (requestData) {
    console.log('resourceRequested:', JSON.stringify(requestData))
};
page.open('http://localhost:8000', function () {
    page.evaluate(function () {
        document.forms[0].submit()
    })
    window.setTimeout(function () {
        phantom.exit()
    }, 1000)
})
```

- `dump_post_data_and_redirect.js` : a basic HTTP server that serves `index.html` on a **GET**, and dump the request body and redirect to `index.html` on a **POST**
```
const fs = require('fs'),
      http = require('http'),
      path = require('path'),
      qs = require('querystring'),
      url = require('url');
http.createServer((request, response) => {
    console.log(request.method, request.url)
    let uri = url.parse(request.url).pathname
    if (!uri || uri === '/') uri = '/index.html'
    if (request.method === 'POST') {
        let body = ''
        request.on('data', data => body += data)
        request.on('end', function () {
            console.log('-> body:', qs.parse(body))
            response.writeHead(302, {'Location': uri})
            response.write('302 Found\n')
            response.end()
        })
    } else {
        let filename = path.join(process.cwd(), uri)
        if (!fs.existsSync(filename)) {
            response.writeHead(404)
            response.write('404 Not Found\n')
            response.end()
            return
        }
        response.writeHead(200)
        fs.createReadStream(filename).pipe(response)
    }
}).listen(8000)
```

### The behaviour expected
The POST body sent to the server should contain `login=Connexion`.

This is what happens with Firefox 57 and Chrome 63.

The HTML standard is quite clear on the [form submission](https://www.w3.org/TR/html401/interact/forms.html#h-17.13) process, that consist of 4 steps:
1. Identify the _successful controls_: given the [definition](https://www.w3.org/TR/html401/interact/forms.html#successful-controls), our `input` is valid
2. Build a form data set: a sequence of control-name/current-value
3. Encode the form data set
4. Submit the encoded form data set

### The behaviour observed
The POST body sent to the server **does not** contain the `login` key.

### Additional note
I initially stumbled on this bug while trying to use CasperJS.
There is the equivalent `bug_repro.casper.js` :
```
const casper = require('casper').create({
    verbose: true,
    logLevel: 'debug'
})
casper.start('http://localhost:8000')
casper.then(function () {
    casper.fill('form', {}, /*submit=*/true)
})
casper.run()
```

**Comment by Lucas-C** [comment]
Seems to be already tracked in https://github.com/ariya/phantomjs/issues/10972

**Comment by pixiuPL** [comment]
@Lucas-C Ive deleted your previous comment as you've referenced an old, unmantaimed issue.
Ive tested the one from CasperJS and it also refuses to work. Will pay close attention to CJS repo and will update accordingly.

**Comment by Lucas-C** [comment]
What do you mean by "it refuses to work" ? Were you able to reproduce the bug using the PhantomJS script provided ?
My explanation was maybe too long, but this is a PhantomJS bug, not a CasperJS bug. The way POST data is sent by PhantomJS does not match neither Chrome/Firefox behaviour nor the W3C spec.

**Comment by pixiuPL** [comment]
It means that (at least first thing that comes to my mind) its **not PJS specific** bug. Thats why I created issue on CJS github repo. Let them investigate as well.

**Comment by pixiuPL** [comment]
Insted of `bug_repro.phantom.js` you should have `bug_repro_phantom_js`

**Comment by pixiuPL** [comment]
It feels like PJS has some issue with sending/receing data as it prints `QT_QPA_PLATFORM=offscreen phantomjs bug_repro_phantom.js 
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:
resourceRequested:`

**Comment by Lucas-C** [comment]
How was it resolved in the end ?

**Comment by pixiuPL** [comment]
@Lucas-C it wasn't.......
Don;t know why GH automated movement occured. Reversing it.
