### ISSUE TITLE
Using PhantomJS I'm unable to click() on save button to move forward in the application. Works well with Chrome driver. 

### ISSUE THREAD

**Issue by mythilikp** [ariya/phantomjs#15233]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`. 2.1.1

2. What steps will reproduce the problem?
  1.
  2.
  3.

3. Which operating system are you using? windows

4. Did you use binary PhantomJS or did you compile it from source? binary

5. Please provide any additional information below.

Used javascript executor and mouseOverscript also.

 ****WebElement button =driver.findElement(By.cssSelector("#steptabtab > div.tab-content > div > div > div.edit-actions > a.btn.padleftright.greenbtn"));	
 button.click();****

The HTML consists of [a ng-click="$ctrl.save()" class="btn padleftright greenbtn">SAVE]

After clicking the save button in the application it should be saved in the sql database. But when using Phantomjs after clicking save button it is not saving in the database.
Using chrome the output I'm getting is good to go.
But i need to use phantomjs only.
Need solution for this.
Trying to find solution since three days.

**Comment by pixiuPL** [comment]
@mythilikp please provide more information on this. Especially steps to reproduce it.

**Comment by mythilikp** [comment]
@pixiuPL  I had written a selenium test case using phantomjs for login into URL and entering into the dashboard of the web application. I need to create an organization and save it. When I press the save button, the organization created should be saved in S3 bucket of amazon and SQL database.

With the chrome driver it is getting saved
but with phantom, the save button is getting displayed but the organization is not getting saved in the sql and S3 bucket.

**Comment by pixiuPL** [comment]
@mythilikp your answer isnt clear enough Im affraid....
What app is this that you want to log in to its dashboard with PJS? Also what kind of organisation are you trying to create and where? If possible, please be more specific and include some logs from debugging as well as the scenario of this Selenium test case you have written. Thanks

**Comment by mythilikp** [comment]
I have written a test case to enter organization name, code,description,country,etc in the organization creation page in web application of my company. Once the organization is created, it should be saved in the Sql database automatically. With phantomjs when I click save the organization created with the details given is not getting saved in the sql database

**Comment by mythilikp** [comment]
@pixiuPL I have written a test case to enter organization name, code,description,country,etc in the organization creation page in web application of my company. Once the organization is created, it should be saved in the Sql database automatically. With phantomjs when I click save the organization created with the details given is not getting saved in the sql database

**Comment by mythilikp** [comment]
@pixiuPL  the save button is getting selected but the organization is not getting saved in the sql database.

**Comment by pixiuPL** [comment]
@mythilikp Could you please show me the body of function `$ctrl.save()` please?

**Comment by mythilikp** [comment]
@pixiuPL sorry I didnt get you

**Comment by pixiuPL** [comment]
@mythilikp what you have inside `$ctrl.save()` function? In other words => whats this function's source code?

**Comment by mythilikp** [comment]
<a ng-click="$ctrl.save()" class="btn padleftright greenbtn">SAVE</a> @pixiuPL
