### ISSUE TITLE
Using sqlite

### ISSUE THREAD

**Issue by StasToken** [ariya/phantomjs#15238]
Hello - PhantomJS 2.1.1, I apologize in advance if not there asked the question, could you tell me if you have the opportunity to work with SQLite if so then show how or give suggestive links, I need some information during the test to save in SQLite

**Comment by pixiuPL** [comment]
@StasToken To be completely honest I have not tried this. I suppose its enough to write standard `INSERT` statement in plain SQL and run it from within your testcase(s)....

**Comment by StasToken** [comment]
@pixiuPL hello - I stumbled upon just this question: https://stackoverflow.com/questions/28540173/how-to-implement-a-fast-queryable-and-persistant-database-in-phantomjs 

I was trying to use sql.js as they suggest there, but for some reason I get errors:

> Assertion failed: this is a legacy browser, build with LEGACY_VM_SUPPORT
> Assertion failed: this is a legacy browser, build with LEGACY_VM_SUPPORT
> abort("Assertion failed: this is a legacy browser, build with LEGACY_VM_SUPPORT") at >jsStackTrace@phantomjs://platform/sql.js:4:13765
> stackTrace@phantomjs://platform/sql.js:4:13901
> abort@phantomjs://platform/sql.js:21:8479
> assert@phantomjs://platform/sql.js:4:6517
> phantomjs://platform/sql.js:4:17856
> phantomjs://platform/sql.js:27:3
> global code@phantomjs://platform/sql.js:31:7
> loadModule@[native code]
> _compile@phantomjs://platform/bootstrap.js:282:27
> .js@phantomjs://platform/bootstrap.js:126:28
> _load@phantomjs://platform/bootstrap.js:278:24
> require@phantomjs://platform/bootstrap.js:311:21
> require@phantomjs://platform/bootstrap.js:263:32
> global code@phantomjs://code/hello.js:2:18
> If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
> 
>   phantomjs://platform/sql.js:21 in abort
>   phantomjs://platform/sql.js:4 in assert
>   phantomjs://platform/sql.js:4
>   phantomjs://platform/sql.js:27
> TypeError: undefined is not a constructor (evaluating 'new sql.Database()')
> 
>   phantomjs://code/hello.js:4 in global code

Maybe tell me what could be the problem? I guess this is because of the difference versions of phantomjs

**Comment by pixiuPL** [comment]
@StasToken Ive tested this and indeed its due to PJS. Try with 2.1.3 (newest)
