### ISSUE TITLE
The attached binary for 2.1.3 doesn't match the provided source code

### ISSUE THREAD

**Issue by raipc** [ariya/phantomjs#15247]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
??

2. What steps will reproduce the problem?
   1. Download binary for phantomjs 2.1.3 dev release
   2. Run `phantomjs --version`
   3. Get `2.1.1`

3. Which operating system are you using?
Ubuntu 16.04

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
The `phantomjs --version` command returns 2.1.1, while the attached source code archives contain code from master branch. Was the release planned to be prepared from branch 2.1, or was it occasional branch miss?

**Comment by pixiuPL** [comment]
Hey, thanks for letting us know, will correct this.....

**Comment by pixiuPL** [comment]
DONE
