### ISSUE TITLE
Windsong.ttf: undocumented license and origin

### ISSUE THREAD

**Issue by onlyjob** [ariya/phantomjs#15249]
Please document the license and origin of `test/lib/www/regression/pjs-10690/Windsong.ttf`.

**Comment by onlyjob** [comment]
That's not good enough, sorry.

"Free for personal use" is non-free not _open source_ license. Let's not incorporate any proprietary components please.

Even so, _where_ did you get "license" text from?
What is the origin of the font?

"Free for personal use" is in conflict with GPL-3 so one of the statements is blatantly not true.

I strongly suspect that GPL-3 does not applies to Windsong.ttf as it would be an unusual license for the font.

Please reopen.

**Comment by pixiuPL** [comment]
@onlyjob reopened. So please suggest a change (just open a PR) and we will review it. Thanks

**Comment by onlyjob** [comment]
Why did you close this issue again? That did not make the problem go away...

As for suggested changes it would be nice to undo your changes first...

Then maybe remove `test/lib/www/regression/pjs-10690/Windsong.ttf` (unless its license can be clarified) or replace it with free font.

I could not find sources or license of `Windsong.ttf` anywhere... :(
