### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by FalconEagleTest** [ariya/phantomjs#15244]
hi,
this is agreat software solves alot of problems, so THANKS.

is there any chance for android support?

**Comment by pixiuPL** [comment]
@FalconEagleTest Thank you for your warm words :)
As of Android (and mobile in general) support => there are plans to introduce it. But its not set yet.
BTW: feel free to code and make PR :)

**Comment by ariya** [comment]
For the foreseeable future, anything other than a desktop OS will not beyond the scope of the project.
