### ISSUE TITLE
Download links not working

### ISSUE THREAD

**Issue by fillmorejd** [ariya/phantomjs#15246]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. Go to http://phantomjs.org/download.html
  2. Click download link
  3. Get this error "Repository unavailable This repository is currently unavailable."

3. Which operating system are you using?
OSX 10.13.2

4. Did you use binary PhantomJS or did you compile it from source?
Trying to get the binary

5. Please provide any additional information below.

**Comment by senorsmile** [comment]
Came here to report this as well.  I have a few dozen new web nodes that are all failing downloading the archive via automation.

**Comment by adrianwebb** [comment]
Looks like the Bitbucket user is hidden: https://bitbucket.org/ariya/

I get this error message when trying to view the user:

      You were never here
      This user has requested we keep their identity a mystery. Let's never speak of this again.

Don't know if this is related, but the repository does seem to be unavailable from Bitbucket.

**Comment by ryanaslett** [comment]
Same issue. We rebuild our CI docker containers daily to keep up with PHP HEAD branches, and thus download phantomjs every day.

**Comment by ryanaslett** [comment]
Oh, this may not be related to phantomjs, and instead be a bitbucket issue: https://status.bitbucket.org/ shows 

```Update - The team is continuing to investigate possible network and/or storage layer issues, thank you for your patience. Next update in an hour. 
Jan 9, 16:58 UTC
Update - We are continuing to investigate and test potential fixes for this service degradation, thank you for your patience. Next update in 60 minutes or if there is a notable change in status. 
Jan 9, 15:51 UTC
Update - We are continuing to investigate the service degradation and are testing out potential fixes. Thank you for your patience, the next update will be in 60 minutes. 
Jan 9, 14:50 UTC
Investigating - We are presently investigating service issues with Bitbucket resulting in degraded performance on the website and via SSH & Git via HTTPS. Next update in 60 minutes 
Jan 9, 13:47 UTC```

**Comment by senorsmile** [comment]
> Don't know if this is related, but the repository does seem to be unavailable from Bitbucket.
It was definitely available yesterday as our CICD system shows successful tests yesterday.

**Comment by fillmorejd** [comment]
Looks like bitbucket is working again.  Closing the issue.
