### ISSUE TITLE
Phantomjs 2.1.1 not working on Centos6.5

### ISSUE THREAD

**Issue by anukriti-chawla** [ariya/phantomjs#15243]
1) Phantomdriver 1.4.3
2) Phantomjs2.1.1
3) Selenium 3.4
4) OS: CENTOS6.5
5) Java 1.8.0_151

Try to run the following code :
File file = new File("PHANTOM_PATH");               
System.setProperty("phantomjs.binary.path", file.getAbsolutePath());        
WebDriver driver = new PhantomJSDriver();
driver.get(<Url>);
System.out.println(driver.getTitle());

Works fine in windows but doesn't loads URL on Linux(CENTOS) . Returns empty page title and doesn't finds the further elements.

**Comment by pixiuPL** [comment]
@anukriti-chawla Doesnt work on Linux as its Windows-specific code. If you want run it on Linux, either rewrite it in (say) Python, or install MonoDevelop and run from there.

**Comment by pixiuPL** [comment]
@anukriti-chawla We do not support CentOS 6.5. We only support 7.x
