### ISSUE TITLE
2.1.3: mongoose.c please clarify license

### ISSUE THREAD

**Issue by onlyjob** [ariya/phantomjs#15248]
https://github.com/ariya/phantomjs/blob/master/src/mongoose/mongoose.c#L6-L7

> Copyright (c) 2014 Cesanta Software Limited
> All rights reserved

`mongoose.c` have no license grant which usually non-free (i.e. proprietary) but Mongoose appears to be GPL-2 licensed.

Please document the license.

**Comment by onlyjob** [comment]
That's not good as you've introduced incorrect text of license grant (GPL-2+ instead of GPL-2).

It would be sufficient to add `README` or `LICENSE` file to `src/mongoose` documenting licensing situation for borrowed 3rd party component.

Please reopen.

**Comment by pixiuPL** [comment]
@onlyjob So please suggest change by opening PR and we will discuss it.

**Comment by onlyjob** [comment]
We are discussing it here. Since you've taken responsibility to work on the problem you should be able to address it without my PR. You've committed the wrong license grant and therefore it is up to you to correct your mistake.

I wish I had time to help with PR but at least I'm helping with feedback.

Please stop closing unfixed bugs. You did not solve this problem yet...

**Comment by pixiuPL** [comment]
Since we are discussing it only, and you think there is something wrong with this software, if you think it deserves the change, than suggest it by opening a PR. Thats what OS is all about.

**Comment by onlyjob** [comment]
Please have a courtesy to finish the job. You've started working on this bug, made a change, make situation worse and now asking me to fix the mess??

After all I've found the problem, reported it, gave you straightforward hint how to fix it, checked the change that you've made and provided feedback -- isn't that enough?

Once you've done working on the bug it is usually worth checking with reporter if the problem is properly fixed. Just closing the bug is not only impolite but also incorrect because the problem is still there. This is very discouraging.

Anyway, if you believe that you've used correct license (which is _not the same_ license of `mongoose.h`) then could you please provide some evidence of license such as URL where you found the license grant? I strongly suspect that you've made a mistake in which case license grant in `mongoose.c` is a lie...

**Comment by pixiuPL** [comment]
@onlyjob While I really do understand your anger, could you please calm down a bit? I'll look into the case tomorrow.

**Comment by pixiuPL** [comment]
@onlyjob thank for this.

> Perhaps it would be even better to update mongoose to current upstream version and use unmodified files if possible.

This is not bad idea in fact. And - to be honest - I have done this (in my test env) and guess what? There is **one** minor (I think its minor) issue with upstream of Mongoose thats conflicting with PJS. I even opened an issue at Mongoose and will incorporate latest version as soon as that issue gets solved. So stay tuned :)

**Comment by pixiuPL** [comment]
@onlyjob updated PR is waiting for you.

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.
