### ISSUE TITLE
Sometimes phantomjs does not respect css while rendering png

### ISSUE THREAD

**Issue by kvelaro** [ariya/phantomjs#15254]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
**1.9.7**

2. What steps will reproduce the problem?
  1. **I don't know**
  2.
  3.

3. Which operating system are you using?
**CentOS 6**

4. Did you use binary PhantomJS or did you compile it from source?
**binary**

5. Please provide any additional information below.

**We have system which renders png from html. Process of rendering png is the same everytime.
But sometimes rendered image seems broken with fonts. I can't figure it out. Spent more than 10 hours in experimenting, but without success.
Guessed that phantom opens and captures the page, while it just loading css. Tried to simulate this on chrome with dev tools. But it's seems that this process is ok. Bad side is that I can't figure out what is the name of the font I seeing? Where it comes from?**
Additional details is the screenshots
![1](https://user-images.githubusercontent.com/8030568/34778560-b20024b6-f62e-11e7-8305-33bb394a7a03.PNG)
![2](https://user-images.githubusercontent.com/8030568/34778561-b224b52e-f62e-11e7-9758-c2f6b717d2cc.PNG)

**Comment by pixiuPL** [comment]
@kvelaro why are you using PJS version thats that old? Use latest (2.1.3).As of fonts => look for the name in page source (ctrl+U) and download it manually as PJS doen not do this for you (as default).
