### ISSUE TITLE
Python: Doesn't pick up correct element count after AJAX 'load more' option is clicked

### ISSUE THREAD

**Issue by tallona** [ariya/phantomjs#15259]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
- From a Python script load a webpage that loads an AJAX response on the webpage and has a 'load more' option on it
- Count how many elements on the page after a click on the 'load more ' option
- Do it using Firefox driver and then the PhantomJS driver, PhantomJS driver doesn't count any elements loaded after the click on the 'load more' option whereas Firefox driver does.

3. Which operating system are you using?
Windows 10

4. Did you use binary PhantomJS or did you compile it from source?
Downloaded as a ZIP

5. Please provide any additional information below.
I've tested using chrome, firefox and phantomjs drivers. chrome and firefox work as expected but phantomjs doesn't I'm developing on Windows but the script will run on CentOS which has PhantomJS installed.

**Comment by tallona** [comment]
Why was this closed with no comment, it's a genuine issue with PhantomJS, I can replicate it every time and it only happens with PhantomJS, Firefox and Chrome drivers both work fine!?

**Comment by pixiuPL** [comment]
@tallona We had some issues with spammers recently and I thought you were another one of them. Sorry for this.
It seems like counting mechanism is, somewhat, buggy. Will investigate.
