### ISSUE TITLE
Latest Mac download file is not a zip

### ISSUE THREAD

**Issue by jaydee18** [ariya/phantomjs#15279]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

can't download latest mac version

2. What steps will reproduce the problem?
  1. click on the Mac download link. It downloads a file with no extension
  2.
  3.

3. Which operating system are you using?

Mac

4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.

**Comment by dawesi** [comment]
does renaming the file to .zip help? #got to ask

**Comment by pixiuPL** [comment]
@dawesi is right. Renaming should help.

**Comment by Manbearpixel** [comment]
Renaming the file to a `.zip` does *not* help.

**Comment by Manbearpixel** [comment]
![screen shot 2018-01-22 at 2 49 24 pm](https://user-images.githubusercontent.com/6686750/35243704-7b92fe5e-ff83-11e7-9799-a93cbb803fdb.png)

**Comment by jaydee18** [comment]
Renaming was the first thing I did - but as mentioned, doesn't help.

**Comment by deadh4nd** [comment]
The phantomjs file is a linux ELF.  Here's the info when running file against the download: 

phantomjs: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=adfe92b525b58d9698596f882789a3af960b0196, not stripped

Seems like we're getting the linux version from the macOSX link.

**Comment by pixiuPL** [comment]
@deadh4nd Indeed. Will fix it now

**Comment by Manbearpixel** [comment]
Found this workaround for now. Involves installing through NPM
https://stackoverflow.com/questions/40528895/cliver-and-phantomjs-error-with-update-to-macos-sierra/40528897#40528897

**Comment by pixiuPL** [comment]
@Manbearpixel thanks for pointing this out.

**Comment by PrzemekCh** [comment]
@Manbearpixel
That doesn't work with the latest version

**Comment by pixiuPL** [comment]
@PrzemekCh what is your arch => 32 or 64?

**Comment by PrzemekCh** [comment]
Hi @pixiuPL mac os is 64 bit only.

installing latest via npm gets the 2.1.1 version

**Comment by pixiuPL** [comment]
@PrzemekCh Thanks. Not a Mac user so I didnt know.
As of `npm`  -> will investigate.

**Comment by ariya** [comment]
Any plan beyond 2.1.1 is currently abandoned, see #15344 for more details.
