### ISSUE TITLE
PhantomJS gather the onNavigationRequested callbacks to array

### ISSUE THREAD

**Issue by Bahad001** [ariya/phantomjs#15277]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
i am not able to gather the onNavigationRequested but it's not working every tim it's pnly get the first request as if the whole script is running again.

`var page = require('webpage').create();
var sys = require('system');
var fs = require('fs');
var response = {};
var arrayOfResponses = [];
var pageUrl = 'http://example.com/redirect/r1.php';

phantom.onError = function (msg, trace) {
    phantom.exit(1);
};

function forceExit(){
    phantom.exit(0);
}

page.onNavigationRequested = function(url, type, willNavigate, main) {
    arrayOfResponses.push(url) ;
}

response.content = arrayOfResponses;

page.open(pageUrl, function(status) {
    if ( status !== 'success' ) {
        phantom.exit( 1 );
    } else {
        phantom.exit( 0 );
    }
}, 100);

setTimeout(forceExit,2000);

console.log(JSON.stringify(response));`

3. Which operating system are you using?
Windows/CentOS
4. Did you use binary PhantomJS or did you compile it from source?
Binary PhantomJS

Can you please advice
Thank you

**Comment by pixiuPL** [comment]
This is intended as thats how it should be.
