### ISSUE TITLE
What exactly is the status of PhantomJS?

### ISSUE THREAD

**Issue by admosity** [ariya/phantomjs#15275]
Looks like there was a release recently on Jan 10 and looks like @pixiuPL made the bulk of the changes... So what exactly is PhantomJS's current status? There was a large stir that PhantomJS was no longer being maintained during the mid of last year: #15105.

There has been much talk about moving off of PhantomJS because of its deprecation/maintenance status, but if there's some degree of maintenance, we may not need to do that all. 

Edit: Sorry if this is bloating the already long issue list. I just haven't seen/heard any notice about PhantomJS being maintained again.

**Comment by pixiuPL** [comment]
@admosity Hello and thanks for this issue. 
Yes, Ive made some changes recently, most notable being release of new version of PJS (2.1.3).

Truth is - I spoke with @ariya on Skype some time ago (month or so) and he gave me push access to this repo. So Im doing my best for PJS to stay alive. I can see that ones who was once with flag Contributor are (pretty much) no longer active. So, to be completely honest, as its now, Im the only one contributor thats active (meaning working with PJS & its repo **daily**).

**Comment by jesg** [comment]
@SebP77 to be fair you are not running the current release `2.1.3`.

**Comment by pixiuPL** [comment]
@SebP77 doing my best for this community to live again..... no worries :)
We are well aware of #14650, so let me investigate it and get back as soon as I find solution. I mean -> from #14650 you see its been merged, so there shouldnt be causing troubles, but will look into it.

**Comment by SebP77** [comment]
On the Site: http://phantomjs.org/download.html, we have 2.1.1, where can I find this version 2.1.3? Do I have to change the version of CasperJS too?
thk

**Comment by pixiuPL** [comment]
@SebP77 Will fix that now and report back

**Comment by SebP77** [comment]
thk

I just saw this in: https://github.com/casperjs/casperjs/pull/1857

I see that there are versions of PhantomJS in CasperJS.
Is it possible to provide me a Zip that contains the right version of PhantomJS and CasperJS compiled (Win 64b or Win 32b) that works well together.
If I have to replace them in my tests, I would need the last and good version to not break anything.
What is important for me is to be able to manage the Const and the last functionality of the Browser IE11 and Edge.
Thank you in advance for your help.

**Comment by pixiuPL** [comment]
@SebP77 yes thats possible. You just have to wait. Im prepairing my Windows 2016 dev/test enviroment. Will re-build, package, test and upload ZIP for Windows today and update this issue. So just be patient please.

**Comment by SebP77** [comment]
ok, no problem, thk ;-)

**Comment by pixiuPL** [comment]
@SebP77 This issue is taking more time than I suspected it'd take. Please be patient

**Comment by SebP77** [comment]
no problem i'm patient ;-)

**Comment by PrzemekCh** [comment]
hi @pixiuPL what about the osx 2.1.3 package - I'm trying to download the latest version but instead phantomjs-2.1.3-macosx.zip I'm getting a DMS file? What is this DMS file anyway?

**Comment by pixiuPL** [comment]
I've no idea. I'm not on Mac and it wasn't me who packed it
