### ISSUE TITLE
x32 version not work

### ISSUE THREAD

**Issue by nleo** [ariya/phantomjs#15278]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

```
$ phantomjs --version
bash: /bin/phantomjs: cannot execute binary file: Exec format error
```

2. What steps will reproduce the problem?
  1. wget https://github.com/ariya/phantomjs/releases/download/2.1.3/phantomjs
  2. chmod +x phantomjs
  3. sudo mv phantomjs /bin

3. Which operating system are you using?

Linux netbook 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:14:44 UTC 2017 i686 i686 i686 GNU/Linux

4. Did you use binary PhantomJS or did you compile it from source?

binary

**Comment by pixiuPL** [comment]
@nleo thats strange.... Can you provide debug info? Also can anyone else confirm?

**Comment by pixiuPL** [comment]
OK, so now please tell me your `gcc` version?

**Comment by nleo** [comment]
```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Arnie97** [comment]
That is the binary release for the `amd64` platform, and you will not be able to run it on an `i686` machine.

```
$ wget https://github.com/ariya/phantomjs/releases/download/2.1.3/phantomjs

$ readelf -h phantomjs
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 03 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - GNU
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x42ee60
  Start of program headers:          64 (bytes into file)
  Start of section headers:          57784584 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         10
  Size of section headers:           64 (bytes)
  Number of section headers:         35
  Section header string table index: 32
```

**Comment by nleo** [comment]
http://phantomjs.org/download.html here only one download link without architecture specifications in section named "Linux 64-bit && and 32-bit" so...

**Comment by pixiuPL** [comment]
@nleo Thats how it should be. 32bit arch is being slowly pushed out.
