### ISSUE TITLE
when will the 2.1.3 of windows version be released, the current version is 2.1.1, only the linux and mac has the 2.1.3 version for this moment?

### ISSUE THREAD

**Issue by deboy** [ariya/phantomjs#15282]
when will the 2.1.3 of windows version be released, the current version is 2.1.1, only the linux and mac has the 2.1.3 version for this moment?

**Comment by pixiuPL** [comment]
@deboy Issue with Windows version is that we observed that Windows hangs while trying to build latest from source. The process of build failing is under heavy investigation, so please be patient....
Sorry for any inconvienence.

**Comment by ariya** [comment]
Any plan beyond 2.1.1 is currently abandoned, see #15344 for more details.
