### ISSUE TITLE
When PhantomJS will be support ES6?

### ISSUE THREAD

**Issue by ProgrammingLife** [ariya/phantomjs#15287]
When PhantomJS will be support ES6?

**Comment by pixiuPL** [comment]
@ProgrammingLife Thank you for opening an issue.
Introducing ECMA will require nearly-complete rewrite and - keeping in m8ind I seem to be the only active dev of PJS now - will need to wait till other - more urgent - issues are solved.

In the meantime, if you feel skilled enough - feel free to start working on it, but **on the separate branch.**

**Comment by annulen** [comment]
Use phantomjs 2.5.0-beta2 to get most of ES6 working

https://bitbucket.org/ariya/phantomjs/downloads/

**Comment by pixiuPL** [comment]
@annulen Its not advised to use it as its been awhile since it was last updated

**Comment by ariya** [comment]
ES > 5.1 will be only supported through an updated QtWebKit. From now on, please track #15342.
