### ISSUE TITLE
http://phantomjs.org/download.html has wrong resource linked for osx version

### ISSUE THREAD

**Issue by oneeyedziggy** [ariya/phantomjs#15288]
at http://phantomjs.org/download.html
the link "phantomjs-2.1.3-macosx.zip" leads to resource "https://github.com/ariya/phantomjs/releases/download/2.1.3/phantomjs" 
which is the same listed under Linux 64-bit && and 32-bit

Also "https://bitbucket.org/ariya/phantomjs/downloads/" doesn't list any 2.1.3 release artifacts anyways, even if the link were pointing there.

**Comment by pixiuPL** [comment]
@oneeyedziggy Repo at BitBucket is **deprecated** and **will not* be updated.
We will restructure things to reflect current state pretty soon....

As of macOS (and Windows) compatibility -> Im **thinking** of either making PJS Linux-only or inviting someone as a developer. Time will tell.

**Comment by ariya** [comment]
Any plan beyond 2.1.1 is currently abandoned, see #15344 for more details.
