### ISSUE TITLE
Object iterator is not working

### ISSUE THREAD

**Issue by yaitskov** [ariya/phantomjs#15285]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  
```
var page = require("webpage").create();
var homePage = "http://cloud-sport.org/";
page.open(homePage);
page.onLoadFinished = function(status) {
  var url = page.url;
  console.log("Status:  " + status);
  console.log("Loaded:  " + url);
  page.render("localhost.png");
  phantom.exit();
};
```

```
phantomjs s.js 
TypeError: undefined is not an object (evaluating 'space.props.alpha = {
		idx: 3,
		type: "percent",
		def: 1
	}')

  http://cloud-sport.org/bundle.js:39400
  http://cloud-sport.org/bundle.js:5163 in each
  http://cloud-sport.org/bundle.js:39398
  http://cloud-sport.org/bundle.js:39930
  http://cloud-sport.org/bundle.js:37934
  http://cloud-sport.org/bundle.js:37941
  http://cloud-sport.org/bundle.js:20 in __webpack_require__
  http://cloud-sport.org/bundle.js:37803
  http://cloud-sport.org/bundle.js:20 in __webpack_require__
  http://cloud-sport.org/bundle.js:32930
  http://cloud-sport.org/bundle.js:20 in __webpack_require__
  http://cloud-sport.org/bundle.js:63
Status:  success
Loaded:  http://cloud-sport.org/
```
3. Which operating system are you using?
ubuntu 14.10

4. Did you use binary PhantomJS or did you compile it from source?
npm install 

5. Please provide any additional information below.

Problem disappears if I remove the code blow. It is used to provide syntax for looping over objects.
```
Object.prototype[Symbol.iterator] =
    function () {
    var self = this;
    var values = Object.keys(this);
    var i = 0;
    return {
        next: function () {
            return {
                value: [values[i], self[values[i++]]],
                done: i > values.length
            }
        }
    }
};
```

I know it's hack but other browsers swallow this without complains.

**Comment by pixiuPL** [comment]
@yaitskov Thanks for this, but its pretty unclear whats the problem here. Please elaborate and clarify.

**Comment by yaitskov** [comment]
Problem is not in s.js itself. It's is fine. It makes PhantomJs render a web page. It works well for google.com for example.

What's wrong is not clear. It looks like js libraries tries to access uninitalized variables but it's not true.

```
Object.prototype[Symbol.iterator] =
    function () {
    var self = this;
    var values = Object.keys(this);
    var i = 0;
    return {
        next: function () {
            return {
                value: [values[i], self[values[i++]]],
                done: i > values.length
            }
        }
    }
};
```

The snippet above together with jquery-ui blows up the browser.

**Comment by yaitskov** [comment]
I've already fell back to Object.entries() and remove custom default iterator, but I am just curious about the problem, because it outlines some deep and subtle difference between PhantomJS and main stream browsers for humans.

**Comment by pixiuPL** [comment]
@yaitskov I fuly understand your inquisitiveness. I do the same thing :)
I will investigate the case as its worth it.
Thanks.

**Comment by ariya** [comment]
ES > 5.1 will be only supported through an updated QtWebKit. From now on, please track #15342.
