### ISSUE TITLE
Some pages not rendering correctly the body.backgroundColor

### ISSUE THREAD

**Issue by mzachariadis** [ariya/phantomjs#15289]
1. Which version of PhantomJS are you using? **2.1.1**

------------------------------------------

2. What steps will reproduce the problem?

- Check for example this page -> https://www.w3schools.com
- Render and save it as jpg 
- You will see the body background color is different than the original. This is happening when the background-color of body is not set so it has the default transparent value **rgba(0, 0, 0, 0)**. 
- I used evaluate method to change the body backgroundColor to white and the rendering was fine, but the pages that I have to render in my implementation are unknown, so it's not possible to set the body.backgroundColor to white for ALL the pages I have to render. 
- If you try to render the page in PDF format you will see different rendering too. 

------------------------------------------

3. Which operating system are you using?
macOS Siera 10.12.6

4. Did you use binary PhantomJS or did you compile it from source?
I used the binary

5. Please provide any additional information below.
N/A

**Comment by pixiuPL** [comment]
Can anyone else confirm?

**Comment by annulen** [comment]
Use 2.5.0 to get most of ES6 working
