### ISSUE TITLE
Process 5029 (phantomjs) of user 0 killed by SIGSEGV - dumping core

### ISSUE THREAD

**Issue by HassyMasa** [ariya/phantomjs#15293]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1.Process 5029 (phantomjs) of user 0 killed by SIGSEGV - dumping core
  2.
  3.

3. Which operating system are you using?
Linux x86_64 CENTOS7 
4. Did you use binary PhantomJS or did you compile it from source?
npm phatomJS
5. Please provide any additional information below.
[phantomjs_core.zip](https://github.com/ariya/phantomjs/files/1663046/phantomjs_core.zip)

**Comment by pixiuPL** [comment]
@HassyMasa its unclear what your issue is about. Please clarify

**Comment by HassyMasa** [comment]
Run the scraping to 12:00 every day in the background of Node.js. 
But not running in standby when the SIGSEGV occurred.

Node.jsのバックグランドで毎日12:00にスクレーピングを実行します。
しかしSIGSEGV発生したときは待機中で実行していません。

**Comment by HassyMasa** [comment]
Node.jsのバックグランドで毎日12:00にスクレーピングを実行します。
しかしSIGSEGV発生したときは待機中で実行していません。

**Comment by HassyMasa** [comment]
Run the scraping to 12:00 every day in the background of Node.js. 
But not running in standby when the SIGSEGV occurred.

Node.jsのバックグランドで毎日12:00にスクレーピングを実行します。
しかしSIGSEGV発生したときは待機中で実行していません。

**Comment by HassyMasa** [comment]
Operating Miss

**Comment by pixiuPL** [comment]
@HassyMasa Im affraid Im still unable to see the point of this issue....

**Comment by HassyMasa** [comment]
PhatomJS a background using the node-cron daily 12: 00 to.
When you encounter a SIGSEGV was waiting.
Beyond that I don't know to me.

PhatomJSはnode-cronを使ってバックグランドで毎日12:00に実行します。
SIGSEGVが発生したときは待機中でした。
それ以上のことは私にも分かりません。

**Comment by pixiuPL** [comment]
@HassyMasa what are these Chinese signs supposed to mean?

**Comment by HassyMasa** [comment]
Japan language
Please check attached coredump & core_backtrace

**Comment by pixiuPL** [comment]
@HassyMasa I wouldnt use our repo on BitBucket as its **deprecated** and no longer maintened (at least no official builds go there)
Try latest stable version from Github or from our homepage and see if problem still exist.

**Comment by HassyMasa** [comment]
OK.
I will try using the following binary files.
https://github.com/ariya/phantomjs/releases/download/2.1.3/phantomjs

**Comment by HassyMasa** [comment]
So too have a difference in environment we couldn't try
```
./phantomjs: /lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./phantomjs)
./phantomjs: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./phantomjs)
./phantomjs: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./phantomjs)
./phantomjs: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.2' not found (required by ./phantomjs)
./phantomjs: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./phantomjs)
```

**Comment by pixiuPL** [comment]
@HassyMasa All these are in CentOS's repos;so just install them as you would any other software.

**Comment by HassyMasa** [comment]
Sorry,We were unable to update the environment.

**Comment by pixiuPL** [comment]
> Sorry,We were unable to update the environment.
why is that?

**Comment by HassyMasa** [comment]
Have impact on other software
