### ISSUE TITLE
Load jQuery only if a webpage is not using jQuery

### ISSUE THREAD

**Issue by mzachariadis** [ariya/phantomjs#15290]
Is it possible to include jQuery lib using includeJS, but only if jQuery is not loaded on a specific website? I would like to avoid conflicts between possible different versions. 

Thank you !!

**Comment by pixiuPL** [comment]
What do you mean by 
> I would like to avoid conflicts between possible different versions

?

**Comment by mzachariadis** [comment]
I mean that if a website/webapp uses jQuery 1.x and someone tries to include jQuery 2.x, maybe something will go wrong in the webpage javascript execution. So in this case it's better to load the lib, only if it's not already loaded by the requested website. 

I made some tests and I ended up to use page.evaluate method to check if lib the is loaded. 
This can be achieved by calling evaluate method until DOM is loaded and then call one last time the page.evaluate to check if the lib is defined. If it's not, I use injectJs to include the js lib. 

I don't know if it's better to implement this natively in the phantomjs plugin. What is your opinion?

**Comment by ariya** [comment]
Thanks for the suggestion @mzachariadis! This is rather specific and I'm not sure how that would fit that into PhantomJS core (the general use(. Beside, there is a workaround as you mentioned (using `evaluate`).
A good solution: tweak the documentation to mention this is a trick.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
