### ISSUE TITLE
version 2.1.3 and 2.5-beta

### ISSUE THREAD

**Issue by oscaroxy** [ariya/phantomjs#15294]
I tried to install the versions 2.1.3 and 2.5-beta from binary not source, but both required old library, openssl in primis.

I have openssl 1.1.0, do exist a new version for the new openssl?
thanks

**Comment by pixiuPL** [comment]
Ive no idea of their release cycle.
As of [this page](https://github.com/openssl/openssl/releases), latest release is 1.0.2.n (from 7th of December 2017)

**Comment by oscaroxy** [comment]
thanks fo reply, I downloaded this openssl:

5278 | 2017-Nov-02 14:51:59 | openssl-1.1.0g.tar.gz (SHA256) (PGP sign) (SHA1)

from:

https://www.openssl.org/source/

(Note: The latest stable version is the 1.1.0 series. The 1.0.2 series is our Long Term Support (LTS) release, supported until 31st December 2019. The 0.9.8, 1.0.0 and 1.0.1 versions are now out of support and should not be used.)

while phantomjs 2.5-beta:

https://bitbucket.org/ariya/phantomjs/downloads/

**Comment by pixiuPL** [comment]
**Dont**use our BitBucket! Its **deprecated and no longer maintained**

**Comment by oscaroxy** [comment]
ok for BitBucket!, but do phantomjs'll work with openssl 1.1.0?
now the 2.1.3 require specific openssl version in order to work fine, else it don't run.
thanks

**Comment by pixiuPL** [comment]
yes its how was intended - to require exact specific version of openssl, just to avoid having to deal with possible regression(s)....

**Comment by oscaroxy** [comment]
Do how I do in order to run phantomjs with openssl 1.1.0?
thanks

**Comment by pixiuPL** [comment]
@oscaroxy Am affraid I dont clearly understand you. What was your question?

**Comment by oscaroxy** [comment]
I would to run phantomjs 2.1.3, but when I download the binary and try to run it, I receive an error like "phantomjs require libssl 1.0.1", while I have into my centos 7 openssl 1.1.0.
thanks

**Comment by oscaroxy** [comment]
in particolar, when I download phantomjs (2.1.3) from site (http://phantomjs.org/download.html), after I run it: ./phantomjs -v
I receive:
./phantomjs: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

I have libssl.so.1.1 into /usr/local/lib64/ 
and libssl.so.1.0.2k into /usr/lib64/

**Comment by HouzuoGuo** [comment]
I've been using PhantomJS 2.1.1 for a while and it is absolutely capable of browsing all kinds of TLS-enabled sites, despite that the executable itself is not linked against libssl/libcrypto:

        linux-vdso.so.1 (0x00007ffd354d1000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fbb1ff38000)
        libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1 (0x00007fbb1fcf3000)
        libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007fbb1fa55000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fbb1f851000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fbb1f649000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fbb1f42b000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fbb1f0a3000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fbb1ed58000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fbb1eb41000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fbb1e787000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbb2014f000)
        libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007fbb1e555000)
        libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007fbb1e338000)
        libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007fbb1e0f5000)

With the latest release 2.1.3 however, the executable is now dynamically linked against libssl and libcrypto:

        ./phantomjs: /usr/lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./phantomjs)
        ./phantomjs: /usr/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./phantomjs)

Just out of curiosity - is there a way to avoid linking against openssl at all like in the older versions?

**Comment by HouzuoGuo** [comment]
forgot to mention.. I'm really glad to see PhantomJS coming back to life, good job!

**Comment by silkcom** [comment]
ya, trying to install on centos and this is killing our ability to upgrade to see if the latest version fixes our flexbox issues

**Comment by oscaroxy** [comment]
I don't understand, sorrry
thanks

**Comment by pixiuPL** [comment]
@oscaroxy @silkcom I do not understand either.....

**Comment by oscaroxy** [comment]
Excuse me for my bed english... but my problem is like 

> HouzuoGuo

**Comment by pixiuPL** [comment]
@oscaroxy @HouzuoGuo [This](http://phantomjs.org/api/command-line.html) may be of great help for you.

**Comment by oscaroxy** [comment]
unfortunately no, when I type:
`./phantomjs -v`
I receive

> ./phantomjs: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by pixiuPL** [comment]
@oscaroxy as I said earlier, **its not** PJS specific error... many other software in Unix world is affected by this. As the above, there is not much I (as a PJS dev) can do about.

**Comment by haroon-sheikh** [comment]
@pixiuPL are there any instructions for building current master somewhere? Also, if we're not using bitbucket anymore, where and when would the binaries be added for latest tags.

**Comment by haroon-sheikh** [comment]
I've just read your comment on https://github.com/ariya/phantomjs/issues/15291. Is this still in progress?

**Comment by silkcom** [comment]
The issue that i'm having is that it's directly linked to an older version of openssl, and centos comes with a later version.  So there's not a great way to install the older version (that i've been able to find on google).  There's also no updated instructions on how to build phantomjs ourselves which blocks that avenue as well.

**Comment by rstahl** [comment]
Is a statically linked 2.1.3 version coming soon (as was the case with 2.1.1)?  Seems like that would solve a lot of problems.  Thanks

**Comment by pixiuPL** [comment]
@haroon-sheikh yes; its in progress, but its taking more time than I suspected it to take, so be patient.
As of build instructions :: [read this](http://phantomjs.org/build.html) please

**Comment by rstahl** [comment]
@pixiuPL Thanks so much, it's appreciated.

**Comment by silkcom** [comment]
@pixiuPL Any update on the statically linked 2.1.3?  We're waiting patiently :) but I haven't seen anything on the link you gave above.

**Comment by ariya** [comment]
This plan is now abandoned, see #15344.
