### ISSUE TITLE
Merge Conflict Markers included with source files

### ISSUE THREAD

**Issue by pruy** [ariya/phantomjs#15297]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
Fresh download of 2.1.3

2. What steps will reproduce the problem?
  1. Download source from github 
     (e.g. using: https://codeload.github.com/ariya/phantomjs/tar.gz/2.1.3)
  2. Extract tar file
  3. look for merge conflict markers

You will detect the following corruptions using   find . -type f -print0 | xargs -0 fgrep '<<<<<<'

./work/phantomjs-2.1.3/src/config.cpp:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/config.cpp:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/config.cpp:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/config.cpp:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/config.cpp:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/config.cpp:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/config.h:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/config.h:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/network/networkaccessmanager.cpp:<<<<<<< HEAD:src/network/networkaccessmanager.cpp
./work/phantomjs-2.1.3/src/networkaccessmanager.cpp:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/webpage.h:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/webpage.h:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/webpage.h:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/webpage.h:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/webpage.h:<<<<<<< HEAD
./work/phantomjs-2.1.3/src/webpagerenderer.h:<<<<<<< HEAD:src/webpagerenderer.h
./work/phantomjs-2.1.3/src/webpagerenderer.h:<<<<<<< HEAD:src/webpagerenderer.h
./work/phantomjs-2.1.3/test/module/webpage/render-base64.js:<<<<<<< HEAD
./work/phantomjs-2.1.3/test/module/webpage/render-base64.js:<<<<<<< HEAD
./work/phantomjs-2.1.3/test/webpage-spec.js:<<<<<<< HEAD

3. Which operating system are you using?
NetBSD (but should not be relevant)

4. Did you use binary PhantomJS or did you compile it from source?
About to prepare compiling from source

5. Please provide any additional information below.

Also checked HEAD and the following files show up:

./work/phantomjs-bccce40c9aad9dda5040342f72c4d6be90e0d446/src/config.cpp
./work/phantomjs-bccce40c9aad9dda5040342f72c4d6be90e0d446/src/webpagerenderer.h
./work/phantomjs-bccce40c9aad9dda5040342f72c4d6be90e0d446/test/webpage-spec.js

**Comment by deba12** [comment]
@pixiuPL please compile test every commit before pushing upstream!

**Comment by pixiuPL** [comment]
@pruy Thanks for noticing this. Queuing this, and will fix it ASAP.

**Comment by pixiuPL** [comment]
@pruy Done
