### ISSUE TITLE
Failed to build from source ?

### ISSUE THREAD

**Issue by KnoooW** [ariya/phantomjs#15291]
I tried to build phantomjs following http://phantomjs.org/build.html ,
but i find there's no build.py in git repo after I clone it.
Is the instructions for compiling is old ?
And how to build the latest release version such as 2.1.3 now ?
by the way I tried to download the linux binary, but there are missing libraries,
I prefer build from source.
thanks!

**Comment by Arnie97** [comment]
Please refer to [deploy/README.md](https://github.com/ariya/phantomjs/blob/master/deploy/README.md) before the documentation is updated.

**Comment by KnoooW** [comment]
./build-and-package.sh: line 5: ./build.py: No such file or directory

**Comment by pixiuPL** [comment]
@KnoooW we (ok ok = I) am thinking of making use of some other build method. Im currently testing online building tools (OBTs) like [this one](appveyor.com).
Ive tested Jenkins also, but its implementastion is out of question as we'd need to enlarge our downloadable file _at least 10x_ as Jenkins requires its own deployment.

**Comment by MichaelWestUX** [comment]
Can confirm KnoooW's issue, I'm getting the same output of `./deploy/build-and-package.sh: line 5: ./build.py: No such file or directory`

**Comment by pixiuPL** [comment]
@MichaelWestUX Thank for this. Will go down deep into it on Monday

**Comment by daniel-lucio** [comment]
+1, I was about to build the RPM and I got this issue as well

**Comment by pixiuPL** [comment]
@daniel-lucio (and everyone having this issue):: If you need to build package, please dont do this till I resolve this issue. Thanks.

**Comment by Aaahh** [comment]
qmake & make

**Comment by ariya** [comment]
Any plan beyond 2.1.1 is currently abandoned, see #15344 for more details.
