### ISSUE TITLE
phantomjs.page.blacklist not working

### ISSUE THREAD

**Issue by adiohana** [ariya/phantomjs#15309]
1. Version 2.1.1

2. What steps will reproduce the problem?
1. create Remote web driver using selenium grid with the following capability:
List<String> urlFilters = new ArrayList<>();
urlFilters.add(".*\\.css");
urlFilters.add(".*\\.css?.*");
capabilities.setCapability("phantomjs.page.blacklist", Collections.singletonList(urlFilters));
2. blacklist is not populated to "negotiatedCapabilities" (can't see it in debug logs)
3. CSS is loading when hitting "http://apache.org"

3. OS: MAC, Linux

4. PhantomJS Binary

5. Please provide any additional information below.

**Comment by jesg** [comment]
@adiohana that feature requires ghostdriver `2.0.0`.  it is a "best effort" approach that does not guarantee that the resource will not be requested.

**Comment by adiohana** [comment]
@jesg 

so you're saying that i cannot use this capability without ghostdriver?

is there any other option to filter/block urls in phantomjs (without using ghostdriver)?

**Comment by pixiuPL** [comment]
@adiohana @jesg This is to be fixed in 2.1.4. Be patient
@adiohana In order to filter out/block address, instruct your firewall to do it (construct rule)

**Comment by adiohana** [comment]
@pixiuPL 

thanks. just to confirm, it will work ion 2.1.4 without ghostdriver, right?

P.S - I wish a firewall rule will solve my problem, it is more complicated as I have many use cases within the same subnet require different rules and url filtering.

**Comment by pixiuPL** [comment]
@adiohana yes, working on this :)
As of your PS. Thats why its crucial to **plan your network well** with burstability in mind.....

**Comment by adiohana** [comment]
@pixiuPL 

is there an ETA for 2.1.4 release?

**Comment by pixiuPL** [comment]
@adiohana Its **planned** to release 2.1.4 public beta in the middle of March, but exact date will be posted on our webpage, so pay attention to it.

**Comment by adiohana** [comment]
Hi @ariya 

is this fix still planned for V2.1.4?

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
