### ISSUE TITLE
Font type behaviour

### ISSUE THREAD

**Issue by NTurchi** [ariya/phantomjs#15319]
Hi, 

1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
**1.9.8**

2. What steps will reproduce the problem?
  **Generate a PDF with phantom-html-library (https://github.com/pofider/phantom-html-to-pdf).** 

3. Which operating system are you using?
**Linux**

4. Did you use binary PhantomJS or did you compile it from source?
**Binary** 

5. Please provide any additional information below.
Actually, when i generate PDF with phantomJs i get trueType (CID) Font type in my document (See image below) but i don't want this kind of font type.
How i can change this behaviour in phantomJs ?
 
![image](https://user-images.githubusercontent.com/16674693/36094152-6b3bd7ea-0fed-11e8-8dfe-47703df7828f.png)

Thanks for your help

**Comment by pixiuPL** [comment]
@NTurchi I **will not** support PJS version thats that old. Sorry :)
