### ISSUE TITLE
how install phantomjs beta 2.5 ubuntu 16.04

### ISSUE THREAD

**Issue by xaiborweb** [ariya/phantomjs#15312]
hello thank you very much for your great work but I am not a programmer and I would appreciate if you share the script to install phantomjs beta 2.5 on ubuntu 16.04 from scratch with all the dependencies you need.

since it had installed phantomjs 2.1.1 in this way but intenete install the 2.5 in the same way and can not install it, thanks.

sudo apt-get install build-essential chrpath libssl-dev libxft-dev libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev 
cd ~ 
sudo wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.5.0-beta-linux-ubuntu-xenial-x86_64.tar.gz 
sudo tar xvf phantomjs-2.5.0-beta-linux-ubuntu-xenial-x86_64.tar.gz -C /usr/local/share/ sudo ln -s /usr/local/share/phantomjs-2.5.0-beta-ubuntu-xenial/bin/phantomjs /usr/local/bin/ 
phantomjs --version

**Comment by manlix** [comment]
```
manlix@6c9a12c8124e:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

```
manlix@6c9a12c8124e:~$ wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.5.0-beta-linux-ubuntu-xenial-x86_64.tar.gz
manlix@6c9a12c8124e:~$ tar xf ./phantomjs-2.5.0-beta-linux-ubuntu-xenial-x86_64.tar.gz
manlix@6c9a12c8124e:~$ chmod +x ./phantomjs-2.5.0-beta-ubuntu-xenial/bin/phantomjs
manlix@6c9a12c8124e:~$ sudo apt install -y libfontconfig libjpeg8 libicu55 libxml2 libxslt1.1 libhyphen0
manlix@6c9a12c8124e:~$ ./phantomjs-2.5.0-beta-ubuntu-xenial/bin/phantomjs --version
2.5.0-development
```

**Comment by pixiuPL** [comment]
@manlix First, and most important note :: **do not** use our repo at Bitbucket. Its **deprecated** (see our homepage).... **No** support whatsoever......

**Comment by xaiborweb** [comment]
@manlix and @pixiuPL
thanks for your answer I could install it perfect now could you please share the installation in centos? Would it be the same script?

**Comment by pixiuPL** [comment]
@xaiborweb by **it** you refer to PJS _2.1.1_ or _2.5_?

**Comment by xaiborweb** [comment]
@pixiuPL 2.5

**Comment by pixiuPL** [comment]
@xaiborweb See above => **not supported** version. Use at your own risk
