### ISSUE TITLE
Version 2.1.3 does not work on Ubuntu 17.10 (Artful) due to shared libraries

### ISSUE THREAD

**Issue by manlix** [ariya/phantomjs#15310]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

- 2.1.3

2. What steps will reproduce the problem?

- Download binary 2.1.3 for Linux from [GitHub](https://github.com/ariya/phantomjs/releases/download/2.1.3/phantomjs)
- Run `phantomjs -v`:

```
manlix@vm8697:~$ /tmp/phantomjs -v
/tmp/phantomjs: error while loading shared libraries: libicui18n.so.55: cannot open shared object file: No such file or directory
```

3. Which operating system are you using?

- Ubuntu 17.10 (Artful):

```
manlix@vm8697:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

4. Did you use binary PhantomJS or did you compile it from source?

- Binary version 2.1.3 for Linux downloaded from [GitHub](https://github.com/ariya/phantomjs/releases/download/2.1.3/phantomjs)

5. Please provide any additional information below.

```
manlix@vm8697:~$ ldd /tmp/phantomjs 
	linux-vdso.so.1 =>  (0x00007ffe3d994000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2cab297000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f2caaf8f000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f2caad4c000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f2caaa99000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f2caa831000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f2caa3f0000)
	libicui18n.so.55 => not found
	libicuuc.so.55 => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2caa1ec000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2ca9fe4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2ca9dc5000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2ca9a3f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2ca96e9000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2ca94d2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2ca90f2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2cab4b4000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f2ca8ec7000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f2ca8c95000)
```

- I have installed latest version of **libicu** for Ubuntu 17.10 from official repository:

```
manlix@vm8697:~$ apt-cache policy libicu57
libicu57:
  Installed: 57.1-6ubuntu0.2
  Candidate: 57.1-6ubuntu0.2
  Version table:
 *** 57.1-6ubuntu0.2 500
        500 http://de.archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu artful-security/main amd64 Packages
        100 /var/lib/dpkg/status
     57.1-6 500
        500 http://de.archive.ubuntu.com/ubuntu artful/main amd64 Packages
```

- And have only **libicui18n.so.57.1** & **libicuuc.so.57.1** instead of **libicui18n.so.55** & **libicuuc.so.55**:

```
manlix@vm8697:~$ dpkg -L libicu57
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libicudata.so.57.1
/usr/lib/x86_64-linux-gnu/libicui18n.so.57.1
/usr/lib/x86_64-linux-gnu/libicuio.so.57.1
/usr/lib/x86_64-linux-gnu/libicule.so.57.1
/usr/lib/x86_64-linux-gnu/libiculx.so.57.1
/usr/lib/x86_64-linux-gnu/libicutest.so.57.1
/usr/lib/x86_64-linux-gnu/libicutu.so.57.1
/usr/lib/x86_64-linux-gnu/libicuuc.so.57.1
/usr/share
/usr/share/doc
/usr/share/doc/libicu57
/usr/share/doc/libicu57/NEWS.Debian.gz
/usr/share/doc/libicu57/changelog.Debian.gz
/usr/share/doc/libicu57/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/libicu57
/usr/lib/x86_64-linux-gnu/libicudata.so.57
/usr/lib/x86_64-linux-gnu/libicui18n.so.57
/usr/lib/x86_64-linux-gnu/libicuio.so.57
/usr/lib/x86_64-linux-gnu/libicule.so.57
/usr/lib/x86_64-linux-gnu/libiculx.so.57
/usr/lib/x86_64-linux-gnu/libicutest.so.57
/usr/lib/x86_64-linux-gnu/libicutu.so.57
/usr/lib/x86_64-linux-gnu/libicuuc.so.57
```

- There are not **libicui18n.so.55** & **libicuuc.so.55**  in Ubuntu 17.10 (Artful, non-LTS) but are in Ubuntu 16.04 (Xenial, LTS) with installed package **libicu55** and works fine.

**Comment by pixiuPL** [comment]
@manlix 2.1.3 is linked dynamically and this is how **its supposed to be.**
Starting from 2.1.3 wel **do not support** statically linking.

**Comment by manlix** [comment]
@pixiuPL thank you for response but there is not information about changing linking type in [ChangeLog](http://phantomjs.org/release-2.1.3.html) for 2.1.3. It was not expected news for me.

I think will good if changes will added to ChangeLog or created section **System requirements** because using binary is recommended method to use PhantomJS as said on Official build page (see screenshot):

![screenshot from 2018-02-07 21-38-41](https://user-images.githubusercontent.com/16971147/35934696-5108c78a-0c4f-11e8-8da3-e25bd137a79c.png)

**Comment by pixiuPL** [comment]
@manlix you're right. Will add this now and report back....

**Comment by pixiuPL** [comment]
@manlix Done

**Comment by manlix** [comment]
@pixiuPL I am very sorry but where can I found changes?

**Comment by pixiuPL** [comment]
@manlix Look at main page. Its written in red

**Comment by s3rj1k** [comment]
@pixiuPL So what is the point in releasing compiled ELF binary that no one sanely can run in any distro except your build environment?

**Comment by pixiuPL** [comment]
@s3rj1k good question, but Im affraid that you directed it in wrong direction as Im not the onew that have ability nor knowledge to answer.
As a PJS dev, there is not much I can do about it. The best option for me (and any other wisely-thinking dev) now is to halt releasing ELFs, report bug whenever (and wherever) it appears and **wait patiently** till devs of respective software fix it.

**Comment by s3rj1k** [comment]
@pixiuPL 
On main page:
`Important: Since version 2.1.3 we do not support dynamic linking
Important: PJS version 2.5 is not supported.`

shoud be fixed

**Comment by pixiuPL** [comment]
> On main page:
Important: Since version 2.1.3 we do not support dynamic linking Important: PJS version 2.5 is not supported.

shoud be fixed

If you think so, correct it **in your own branch,** open PR and we will see....

**Comment by manlix** [comment]
> Look at main page. Its written in red

@pixiuPL I see it. Thanks.

**Comment by lkol** [comment]
Works on Ubuntu 16.04 but the release page still says 2.1.3 is "pre-release" and "NOT for use in production": https://github.com/ariya/phantomjs/releases

Also the version information prints "dev-release"
```
$ ./phantomjs -v
2.1.3-dev-release
```

**Comment by pixiuPL** [comment]
@lkol yes, thats exactly how things are and were meant to be.....

**Comment by lkol** [comment]
@pixiuPL Ok, good. I was just wondering, because http://phantomjs.org/ already pushes v2.1.3 on frontpage and points to same github release, although it's not production ready.

**Comment by pixiuPL** [comment]
@lkol I see what you mean now......

**Comment by pixiuPL** [comment]
@lkol is it ok now?

**Comment by lkol** [comment]
@pixiuPL Yes, great! Thank you.

**Comment by s3rj1k** [comment]
@pixiuPL you said that static linking will not be supported until upstream fixes some compilation bugs.
In main web page you state that
`we will not support dynamic linking`

so what will not be supported static or dynamic linking?

**Comment by pixiuPL** [comment]
@s3rj1k good catch. Will correct ASAP

**Comment by pixiuPL** [comment]
@s3rj1k Corrected

**Comment by ylavoie** [comment]
The compiled proposed version was linked against libicui18n.so.55, which, restricts its use on a very narrow set of Ubtuntu releases. Either link it against libicui18n.so or mention in the read me that it is destined to work on Ubuntu Xenial.

**Comment by jgeorgeson** [comment]
Just wanted to expand on what @ylavoie was saying about linking against libicui18n.so (but as a CentOS user, am assuming the same general statement would apply to Ubuntu).

The way RHEL/CentOS have their libraries they have a generic SONAME so that anything linked against them properly has wide range of package versions against which it will run. CentOS 6 ships OpenSSL 1.0.1e and CentOS 7 ships 1.0.2k, and for both versions the libraries only indicate the major.minor version in the SONAME (ie libssl.so.10 and libcrypto.so.10). So if I link an executable on CentOS 6 using `-lssl` so that the linker uses the `libssl.so` symlink and reads the SONAME, the executable will resolve it's runtime dependency on either CentOS 6 or 7, with any 1.0.x OpenSSL installed.

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.
