### ISSUE TITLE
loss file build.py

### ISSUE THREAD

**Issue by linfeng2gh** [ariya/phantomjs#15315]
where is build.py? are you sure the file exists?

**Comment by manskx** [comment]
it seems build.py is missing

**Comment by pixiuPL** [comment]
@linfeng2gh @manskx Its not missing, but its available in/as **submodule**.
Have you both followed [build manual](http://phantomjs.org/build.html) closely?

**Comment by manskx** [comment]
@pixiuPL 
I followed build manual. build.py is missing.

**Comment by pixiuPL** [comment]
@manskx Thanks, will take care of this

**Comment by ariya** [comment]
This is resolved now, see #15344 for details. Thanks!

**Comment by liger1978** [comment]
Can we have a final working relase (with `build.py` included) as I can't package from 2.1.3 release...
