### ISSUE TITLE
android version

### ISSUE THREAD

**Issue by ebs111** [ariya/phantomjs#15328]
hi,
i already asked will there be an android version, and the answer was yes and it was transfered to WIP.
now i cannot find it
was it canceled?
thanks

**Comment by pixiuPL** [comment]
@ebs111  no it wasnt cancelled however it was decided to put it down a list little bit as there are more important things to do. That doesnt mean I forgot.... I remember about it.

**Comment by ariya** [comment]
For the foreseeable future, anything other than a desktop OS will not beyond the scope of the project.

**Comment by MoRaafat32** [comment]
I was wondering if phantomJS is available on android.
