### ISSUE TITLE
Cannot render "faz.net" phantomjs crashed/Unexpected Error/ Segmentation fault: 11

### ISSUE THREAD

**Issue by manskx** [ariya/phantomjs#15321]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
I am using 2.1.1 in production, also tried 2.1.3-dev-release

2. What steps will reproduce the problem?
  1. Render "http://www.faz.net/aktuell/" using selenium ghostdriver or using the binary itself.
ex:
  `page.open('http://www.faz.net/aktuell/', function() {
  page.render('faz.png');
  phantom.exit();
});`

3. Which operating system are you using?
 mac/ linux

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
- I assumed the problem with webfonts, then I disabled fonts loading using "page.onResourceRequested" but still it is not working, also used different  user_agent to load different fonts

**Comment by pixiuPL** [comment]
@manskx Whats exact problem here?
