### ISSUE TITLE
Problem with build process

### ISSUE THREAD

**Issue by misagogit** [ariya/phantomjs#15320]
Hi. I'm trying to build the last stable version, 2.1.3 in a CentOs 7.4 but I receive an error message because the build.py file doesn't exist. 

To do it,I have tried to build the tool following the build instructions (http://phantomjs.org/build.html):

$ git clone git://github.com/ariya/phantomjs.git
Cloning into 'phantomjs'...
remote: Counting objects: 65948, done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 65948 (delta 28), reused 62 (delta 18), pack-reused 65871
Receiving objects: 100% (65948/65948), 161.23 MiB | 19.25 MiB/s, done.
Resolving deltas: 100% (28101/28101), done.
$ cd phantomjs
$ git checkout 2.1.3
Note: checking out '2.1.3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

git checkout -b new_branch_name

HEAD is now at ca5a6c3... Fix #12090
$ git submodule init
$ git submodule update
$ python build.py
python: can't open file 'build.py': [Errno 2] No such file or directory

I'm using a normal user, not as a root user. Am I doing someting wrong? Thanks a lot.

**Comment by pixiuPL** [comment]
@misagogit please see #14585

**Comment by misagogit** [comment]
Thanks for your reply, it seems that doing the checkout of the 2.1.0 version the build process works fine, but it could be good idea to have the buils instructions for the 2.1.3 updated in the website. Thanks.

**Comment by pixiuPL** [comment]
@misagogit The thing with website is that there is not much sense to update it, since I will update it once new version (2.1.4) is ready (pretty soon). Once 2.1.4 is out (and stable), 2.1.3 will enter first pre-EOL, and finally EOL phase (after 2 months of being in preEOL).

**Comment by vielmetti** [comment]
OK, so I understand that 2.1.1 is EOL and 2.1.3 does not build from source.

**Comment by pixiuPL** [comment]
@vielmetti yes: 2.1.1. is long EOL. 2.1.4 will (hopefully) build without making fuss....

**Comment by jan--f** [comment]
Any update on this? 2.1.1 is EOL as of today and there is no updated build instructions.

**Comment by ariya** [comment]
Any plan beyond 2.1.1 is currently abandoned, see #15344 for more details.
