### ISSUE TITLE
[tracking] build notes for build on arm64

### ISSUE THREAD

**Issue by vielmetti** [ariya/phantomjs#15322]
Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

Attempting to build PhantomJS 2.1.1 from source on arm64. (I wanted to build "master" but no build instructions were available).

Build works without any issues.

What steps will reproduce the problem?
  1. `git checkout 2.1.1`
  2. `python ./build.py`

Which operating system are you using?

Ubuntu 16.04 LTS on Packet "Type 2A" 96-core Cavium ThunderX arm64

Did you use binary PhantomJS or did you compile it from source?

Attempt to build from source.

Please provide any additional information below.

* build process does not use any appreciable parallelism, this slows the build down substantially on a 96-core machine with each core relatively slow.

**Comment by pixiuPL** [comment]
@vielmetti Please tak a look [here](http://phantomjs.org) (green anouncement right in front of your eyes. Thanks

**Comment by vielmetti** [comment]
> Info: We are slowly phasing out support of PJS 2.1.1. EOL for 2.1.1 is 01-03-2018

Got it.
