### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Service phantomjs unexpectedly exited. Status code was: -6

### ISSUE THREAD

**Issue by mariniertje** [ariya/phantomjs#15327]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
Version 2.1.1 
But running `phantomjs --version` results in the following:

> QXcbConnection: Could not connect to display
> PhantomJS has crashed. Please read the bug reporting guide at
> <http://phantomjs.org/bug-reporting.html> and file a bug report.
> Aborted

2. What steps will reproduce the problem?
  - I'm using the python myusps module for home-assistant ([https://github.com/happyleavesaoc/python-myusps])
  - This worked fine until i ran `sudo apt-get update`, `sudo apt-get upgrade` and `sudo apt-get dist-upgrade`. where phantomjs was upgraded to version 2.1.1+dfsg2. Ever since it returns this error.

3. Which operating system are you using?
Raspbian Stretch

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
Full error log:

> Error handling request
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.5/site-packages/myusps/__init__.py", line 207, in wrapped
>     return function(*args)
>   File "/srv/homeassistant/lib/python3.5/site-packages/myusps/__init__.py", line 237, in get_packages
>     response = _get_dashboard(session)
>   File "/srv/homeassistant/lib/python3.5/site-packages/myusps/__init__.py", line 198, in _get_dashboard
>     raise USPSError('expired session')
> myusps.USPSError: expired session
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.5/site-packages/myusps/__init__.py", line 170, in _login
>     driver = _get_driver(session.auth.driver)
>   File "/srv/homeassistant/lib/python3.5/site-packages/myusps/__init__.py", line 144, in _get_driver
>     return webdriver.PhantomJS(service_log_path=os.path.devnull)
>   File "/srv/homeassistant/lib/python3.5/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
>     self.service.start()
>   File "/srv/homeassistant/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 86, in start
>     self.assert_process_still_running()
>   File "/srv/homeassistant/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 99, in assert_process_still_running
>     % (self.path, return_code)
> selenium.common.exceptions.WebDriverException: Message: Service phantomjs unexpectedly exited. Status code was: -6
>

**Comment by pixiuPL** [comment]
@mariniertje please see #15217
