### ISSUE TITLE
phantomjs: Permission denied shell_exec('phantomjs hi.js 2>&1');

### ISSUE THREAD

**Issue by xaiborweb** [ariya/phantomjs#15337]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`. 2.1.3-dev-release

2. What steps will reproduce the problem?
install phantomjs 2.1.3 as follows
```
sudo wget https://github.com/ariya/phantomjs/releases/download/2.1.3/phantomjs
sudo chmod +x ./phantomjs
sudo ln -sf /root/phantomjs /usr/local/bin
phantomjs --version
```
when running phantomjs 2.1.3 from the console it works perfect, but when I run pantomjs from PHP with shell_exec or exec it does not print anything I add 2> & 1 and it is printing me the following message.
`sh: 1: phantomjs: Permission denied`

3. Which operating system are you using? ubuntu 16.04 64bits

4. Please provide any additional information below.
I used phantomjs 2.1.1 from php with the same command shell_exec and it worked perfect but currently 2.1.1 has a bug that did not execute some jquery and javascripts for this reason I was trying to try with 2.1.3 to see if this version does not have that bug.

please any help would be appreciated

**Comment by ariya** [comment]
Any plan for version > 2.1.1 is effectively abandoned. Please see #15344 for more details.
