### ISSUE TITLE
Stop location.href redirect

### ISSUE THREAD

**Issue by sup3rgiu** [ariya/phantomjs#15336]
Hi,
I need to perform some actions after page.evaluate on a URL, however this URL immediatly call <script>location.href='http://abc.com'</script> and so I'm not able to take the HTML code of the original URL.

I was wondering if is possibile to disable location.href to load the first page without the redirect

Thanks in advance!

**Comment by ariya** [comment]
Implementing this is a major undertaking and currently beyond the scope of the project.
You are however free to work on it on your own or sponsor someone to implement it. Once it is in a state where we can consider it for inclusion, please reopen this issue and submit a pull request of the implementation. Thank you!
