### ISSUE TITLE
Windows build 2.3?

### ISSUE THREAD

**Issue by kerray** [ariya/phantomjs#15338]
Hi, is there any place I could download a built .exe of PhantomJS 2.3? 

I started having problems with my screenshot generator, which worked for years, perhaps after some Windows updates, and wanted to try a new version, but I could only find a build for Linux.

Thanks!

**Comment by vlada-dudr** [comment]
Hi, actually the new version doesn't run anywhere else except of Ubuntu 16.04... And there is NO WORKING AND DOCUMENTED way to build it myself...

**Comment by kerray** [comment]
Thanks for the info!
