### ISSUE TITLE
Can not ectract a local website

### ISSUE THREAD

**Issue by chrizmc** [ariya/phantomjs#15335]
Hi,

I want to label content of a webpage before I extract it with phantomjs. For that reason I saved the website with google chrome completly on my pc. Then I started phantomjs in commandline like this:

phantomjs.exe extractorscript.js c:/savedlocalwebsite/www.living.com

I only are interested in text and css.

Problem: phantomjs hangs, because it searches for some links in the web but as file type:
"url": "file://tpc.googlesyndication.com/sodar/V6zvOIoD.js"

1. question: how can i avoid searching for these links?
2. question: if i can not avoid it: how can I change the file-type back to a real URL?

Thanks in advance

**Comment by pixiuPL** [comment]
@chrizmc Please specify full path to selected file/s and you will be good.

**Comment by chrizmc** [comment]
But how to do it? :-) I need an http// instead of file//

Can i configure phantomjs in this way?

I think problem is that I use a local stored website and the phantomjs thinks that everythin is local. But all the links are not stored locally
