### ISSUE TITLE
What is the current production version?

### ISSUE THREAD

**Issue by jan--f** [ariya/phantomjs#15339]
[The phantomjs website](http://phantomjs.org/download.html) links to 2.1.3 for Linux. The [github relases page](https://github.com/ariya/phantomjs/releases) however lists 2.1.3 not suitable for production. What's the current recommend version to run (considering 2.1.1 is EOL soon)?

**Comment by ariya** [comment]
Use 2.1.1, any other plan is now abandoned, see #15344.
