### ISSUE TITLE
Segmentation Fault (Qt5Core)

### ISSUE THREAD

**Issue by Quacky2200** [ariya/phantomjs#15330]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  - Used gdb
  - Launched phantomjs with small script to load YouTube video
  - Waited for crash during video playback

3. Which operating system are you using?
Ubuntu 16.04

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
Was testing with PhantomJS, kept getting 'Segmentation Fault'. Couldn't find much about it anywhere. I did a `gdb /usr/lib/phantomjs` and received this:

```
2018-02-22T15:26:04 [DEBUG] CookieJar - Saved "PREF=f1=50000000&f5=30; expires=Sat, 22-Feb-2020 15:26:04 GMT; domain=.youtube.com; path=/"
[Thread 0x7fff7f921700 (LWP 9794) exited]
[Thread 0x7fff51884700 (LWP 9820) exited]
[Thread 0x7fff51083700 (LWP 9821) exited]
[New Thread 0x7fff51083700 (LWP 9829)]
[New Thread 0x7fff51884700 (LWP 9830)]
[New Thread 0x7fff7f921700 (LWP 9831)]
2018-02-22T15:26:10 [DEBUG] WebPage - setupFrame "<!--framePath //<!--frame1-->-->"
2018-02-22T15:26:10 [DEBUG] WebPage - updateLoadingProgress: 10
2018-02-22T15:26:10 [DEBUG] WebPage - updateLoadingProgress: 100

Thread 1 "phantomjs" received signal SIGSEGV, Segmentation fault.
0x00007ffff4732390 in QIODevice::openMode() const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```

**More specifically the last line might be important?**
`0x00007ffff4732390 in QIODevice::openMode() const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5`

Would this be an error due to PhantomJS or Qt 5?

**Comment by pixiuPL** [comment]
@Quacky2200 Update your PJS. 2.1.1 is long EOL. Closing
