### ISSUE TITLE
The PDF is producted without visible text - blank PDF

### ISSUE THREAD

**Issue by rodnikosh** [ariya/phantomjs#15333]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
phantomjs-2.1.1-linux-x86_64.tar.bz2
2. What steps will reproduce the problem?
  1.presenting a PDF
  2.
  3.

3. Which operating system are you using?
centos 6.4 (64 bit)
4. Did you use binary PhantomJS or did you compile it from source?
i did not compile it.
5. Please provide any additional information below.
When rendering the PDF it is presented without text in table. the table show.
although changing the font size of the invisible text changes the table size so the text is there but invisible. could it be the font family problem? i control the HTML code . so any tip will do...
thanks!

**Comment by pixiuPL** [comment]
Can anyone confirm?

**Comment by negativalpha** [comment]
I'm facing a similar problem trying to capture an image from a html document. PhantomJS 2.1.1, Win10x64. In my case - it's clear that the issue is caused by a custom truetype font-face
