### ISSUE TITLE
clip picture lose content

### ISSUE THREAD

**Issue by shatle** [ariya/phantomjs#15346]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

phantomjs: stable 2.1.1 (bottled)
Headless WebKit scriptable with a JavaScript API
http://phantomjs.org/
/usr/local/Cellar/phantomjs/2.1.1 (49 files, 50.5MB) *
  Poured from bottle on 2018-02-26 at 17:13:28
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/phantomjs.rb
==> Dependencies
Required: openssl ✔
==> Requirements
Build: xcode ✔
Required: macOS >= 10.7 ✔

2. What steps will reproduce the problem?

A long report-html page

* set viewportSize
```
page.viewportSize = { width: 414 * zoomFactor, height: 40000 * zoomFactor };
page.open(url, function (status) {
        if (status !== "success") {
            console.log('Unable to load url');
            phantom.exit();
        } else {
            forcedRenderTimeout = setTimeout(function () {
                console.log(count);
                getBodyAndExit(false);
            }, maxRenderWait);
        }
});
```
* get clip area
```
clipRect = page.evaluate(function () {
            return document.querySelector(element).getBoundingClientRect();
 })
page.clipRect = {
                top: clipRect.top,
                left: clipRect.left,
                width: clipRect.width * zoomFactor,
                height: clipRect.height * zoomFactor
};
page.render(filename);
phantom.exit();
```
  3. Then, i set zoomFactor=1.5 and get result 

![image](https://user-images.githubusercontent.com/1129872/36960375-b995e40e-2081-11e8-8c81-e99467d1951a.png)

the picture lose some content on the bottom

3. Which operating system are you using?

mac 10.12.6

4. Did you use binary PhantomJS or did you compile it from source?

brew install phantomjs

Question:

Why i only get 32769px content, but not 41105px? Is it has max renderHeight or anything?

Thanks.

**Comment by ariya** [comment]
Hi @shatle, thanks for the report! Unfortunately this seems to be the limitation of the software renderer (in Qt which PhantomJS uses).

Possible workaround: do a multiple render with different offset, and then stitches the output manually.

There is no easy way to fix this, it will be a huge undertaking for our small team. We will close this issue for now and will reopen it again if we revisit the topic in the future. Thank you!

**Comment by shatle** [comment]
@ariya Thanks,  anyway.
