### ISSUE TITLE
My open letter

### ISSUE THREAD

**Issue by pixiuPL** [ariya/phantomjs#15345]
As I have **no possibility** to change anything on the website, I will post link to my open letter here. [My open letter to the community of PhantomJS](https://docs.google.com/document/d/1egB4CarmBN3HfntWJ7n1ETB-uDQBAwS5taPbKtxMloQ/edit?usp=sharing).
As I said on Skype yesterday @ariya - I have edited it.

Many thanks,

**Comment by pixiuPL** [comment]
@NickolasBoyer: what are you confused with?

**Comment by ariya** [comment]
After a while, it is clear that @pixiuPL (=he) and I could not work together.

My side on the story:

* He was _never_ hampered to perform the usual tasks: committing code changes, triaging issues, reviewing and merging pull requests, and even making releases. Various access which he demanded was not a show-stopper, consequently I did not attend to that right away. I planned to address that at some point, just not right away (due to other life commitments).
* Such unfulfilled demands were then blown up out of proportion, culminating in the open letter linked from the main landing page of phantomjs.org. From my perspective, this is passive aggressiveness. It indicated lack of trust and the ability to navigate and resolve conflicts, and it demonstrated a poor social skill, all of which are important (beyond just the technical prowess) in running a community project.

This is not my first rodeo in the open-source community nor my first time dealing with a team dysfunction.
As much as I tried to be as reasonable as possible, I do not believe that the situation sets a good precedent for any future healthy collaboration. Past great collaborators of this project, including @Vitallium who made an enormous, significant progress to PhantomJS for years and years, always put forth the great emphasis on helping each other, vs insisting on the claim of _vanity_, symbolic rights (repository transfer, forum admin, etc).

In all cases, considering our differences in the way we imagine the project must be handled, the case is **solved** amicably: I will archive this repository (#15344), he will continue working on a fork. I thank him for his contribution and wish him all the best.

Thank you for your understanding!

**Comment by pixiuPL** [comment]
@ariya 

As of my inability to lead:: please look at PR's. When I stepped in there was circa 50 of them; now there is **none**. What that suggests? That I have an ability to solve puzzles (oh yes, some of them were quite tricky)..... and I was serious about my contributions (I helped many users here as much as I could). But **I have been blocked** by lack of permissions you gave me (collaborator role is very limited in fact).  **I have also mentioned that in Skype msgs as well as mails**

I was never hampered to commit code changes? Seriously? Just look at commits list to find out how much code I commited, **before** trying to defame me!!

As of admin rights on forum.... I asked you for them, because I saw **many spam posts** across forums and **I was not able** to clean them as standard user. Thats it - nothing more...

You say you did not attend right away as you were busy with real-life.... OK I understand two, three days of latency, or even everything up-to-week isacceptable for me..... you say you wanted to give yourself time - OK, but you should have replied this, Instead **there was no reply from you**. And thats why I sent another Skype msg/mail.... I thought you miscathed it or sth alike......

**Comment by NickolasBoyer** [comment]
@pixiuPL I'm not really a fan of using the Github issue system as social media or any other form of unnecessary discourse but I'll bite. I don't know anything about this situation but why is this necessary? This open letter seems almost solely aimed at portraying Ariya as a incompetent lazy lozer while facilitating your own ego trip, "it just needs good, devoted leader." what even is this, we're not building a sandcastle in 4th grade. Again don't know much about this situation but a bit more professionalism and tact would be nice.

**Comment by pixiuPL** [comment]
@NickolasBoyer Im tactful, but (with all respect I have for Ariya) I think he is misunderstanding sth greatly here. As he said above:: we have two different conceptions of how we would go with PJS, thats it.....

And he started to defame me, its not professional nor tactful

**Comment by kensoh** [comment]
PhantomJS is the reason I got into open-source in 2015. At that time I think Vitaly is maintaining the project. What Ariya created is so ahead of its time that so many years on, huge numbers of production systems are still running PJS scripts / code.

What I really really like about PJS is you just unzip and run, all dependencies are packaged into the binaries. When this monolithic effort is no longer maintainable by Vitaly, imagine how many people (including me), are pleasantly surprised when Pixiu started committing code intensively.

It looks like a resolution has been reached, and both gentlemen have my deep respect - the level of intensity simply shows how much they care about PhantomJS project!

**Comment by thedward** [comment]
@pixiuPL 

I think you misunderstood what he wrote.

The word 'hamper' means restrict, so "never hampered" means "never restricted". He was saying that you were *always able to* "perform the usual tasks: committing code changes, triaging issues, reviewing and merging pull requests, and even making releases". He was **not** saying you failed to do those things.

**Comment by rizqme** [comment]
@pixiuPL you joined github december 2017. Haven't done much in the open source world either. No one can find your profile in the internet. You have no right to make such accusation, have respect towards original creator. And please earn your respect first before making a rant like this.

**Comment by jmenglis** [comment]
Not to add additional banter here but I find it funny that you (@pixiuPL) added this [commit](https://github.com/ariya/phantomjs/commit/938a364e7380b467871bf9d7919c08b0d64bd11a).  Yet you would open an [issue](https://github.com/composer/composer/issues/7016) with this kind of language.  

I would consider the way you communicate to the OSS community as it goes a long way.

**Comment by adityapurwa** [comment]
This kind of things should be done in private @pixiuPL . Can't just bash people for being unresponsive, they have their own life too. If you can't continue maintaining the project, just apologize to the community and provides some positive feedback, no need to bash @ariya for not giving you power. I hope we all learn something from this issue.

**Comment by ahinkle** [comment]
@pixiuPL Oh, get off your high horse..  you just joined, [clearly you are toxic to the community](https://github.com/composer/composer/issues/7016), and now you are demanding things? Looking at your "Open Letter" you close with:

> Stay tuned for more....

You are just looking for attention to to start drama.. give it a break.  This type of actions should not be welcome in any time of open source community.

**Comment by Flowkap** [comment]
This letter is a shame. Sorry but such tone is unacceptable in general between human beings. @ahinkle post shows it's not the first time.. I understand why you're not getting the ownership. A pity for the project though.

**Comment by tvvignesh** [comment]
@ariya Are you abandoning this project just because of @pixiuPL or is there any personal reason as well? Asking this cause if it is because of him, then you should just ignore/ditch him and continue your good work with the project. 

Not all people in the open source community might be like him and you may find someone better if you stick to the project or reach out by may be posting in repos like this: https://github.com/pickhardt/maintainers-wanted

All the best.

**Comment by RumbleFrog** [comment]
> I really did care about PhantomJS

What you care about is your recognition, your fame, and your stats

https://github.com/ariya/phantomjs/commits?author=pixiuPL

Delete/Readd (Boosted you to # 4 contributor):
- https://github.com/ariya/phantomjs/commit/a242fb8d605d9aa4afe5bf8d1267c1ded15f157c
- https://github.com/ariya/phantomjs/commit/ddaaa09785d453e41554fd6133a2054c659a317f

Deleting/Adding PR's (Stat Boost):
- https://github.com/ariya/phantomjs/pull/13660 https://github.com/ariya/phantomjs/commit/40699ec4d645265144036263de3ea98481257939 https://github.com/ariya/phantomjs/commit/fcbc946e66b6ee53da69bd7c7d9f76e9601e7911

"PR Fixes" (Literally Stealing):
- https://github.com/ariya/phantomjs/pull/12090 https://github.com/ariya/phantomjs/commit/bad3237b1120405efddac759a71a46dde0d3936f https://github.com/ariya/phantomjs/commit/ca5a6c377d408366d0d4b8ecf4539b628420c8f1
- https://github.com/ariya/phantomjs/pull/11373 https://github.com/ariya/phantomjs/commit/cc7f94909421d97742d2aeaf1e2fdbb365f5a028 https://github.com/ariya/phantomjs/commit/695c3c0b3d0a8b4be33a59e44d087fffc420c127
- https://github.com/ariya/phantomjs/pull/13834 https://github.com/ariya/phantomjs/commit/8d971000d84ae8ea9bfcde98a8b1b0e3f180075a https://github.com/ariya/phantomjs/commit/af89fbd125476dc82e86a4056e53a20e430b8bc8

Commits "Refactoring" (Some of these made it even harder to read):
- https://github.com/ariya/phantomjs/commit/2c162ceb22ce35158bcc2a34e40c33a703eab1e7
- https://github.com/ariya/phantomjs/commit/a81a38ffabe2cea715ff1c6ab9425f006c3eb166
- https://github.com/ariya/phantomjs/commit/a81a38ffabe2cea715ff1c6ab9425f006c3eb166
- https://github.com/ariya/phantomjs/commit/970edb9b683175a6b1f22fb77bff4fbbda957a19
- https://github.com/ariya/phantomjs/commit/6250e772a49383af869cb31f2a5a9e185c26a7a8
- https://github.com/ariya/phantomjs/commit/811593a4d4c6ace5184a744eab1cf43999dad2f0
- https://github.com/ariya/phantomjs/commit/52e4849a36c68b15c6f08c6a8f74a9bd2f134722
- https://github.com/ariya/phantomjs/commit/b586cf21e3cf667cfd35d87093946a4b0f9a1bb3

Broken Commits:
- https://github.com/ariya/phantomjs/commit/f94b7e52c569ca04d0d350a02f7b7b0e926e7c1c
- https://github.com/ariya/phantomjs/commit/f5ba2434fd3b718286be9051aef026be55f7066c

There are so much bullshit that I got tired of looking for them

**Comment by MichaelErmer** [comment]
Wow, thats wrong on so many levels, I feel bad for @ariya having to deal with all of this.

https://github.com/ariya/phantomjs/blob/master/package.json

https://github.com/ariya/phantomjs/pull/15316

https://github.com/ariya/phantomjs/pull/15299/files

Most PR's are Markdown only...

**Comment by interatir** [comment]
@pixiupl wez sie ogarnij. Przynosisz wstyd narodowi swoim spierdoleniem umyslowym. Twoje commity sa bezuzyteczne insprowadzaja sie do dodawania spacji/ spierdalania kodu pseudofaktoringiem. Usun konto gita i przestan sie osmieszac.

**Comment by mkarnicki** [comment]
Along what @interatir said - @pixiuPL I wish that `PL` in your username wasn't an indication of my home country, cose you're a disgrace, politely put.

**Comment by Zopieux** [comment]
@ariya, as @tvvignesh put it, please do *not* archive this project *just because* of a random contributor's mental meltdown. Given its popularity, I am sure it is possible for phantomjs to find a new team of core contributors if you can't take it anymore.

Props to you for staying exceptionally professional despite the situation. You have the support of the OSS community! :ok_hand:

**Comment by seirl** [comment]
Hi everyone,

Instead of starting a flamewar against @pixiuPL , it would be a lot more productive to just [report him](https://github.com/contact/report-abuse) for breaching the [terms of service of GitHub](https://help.github.com/articles/github-terms-of-service/#3-conduct-restrictions), most notably:

> harass, abuse, threaten, or incite violence towards any individual or group, including GitHub employees, officers, and agents, or other GitHub Users;

> violate the privacy of any third party, such as by posting another person's personal information without consent.

Instead of taunting him, we should just collectively make sure he can never harrass open source contributors from now on.

**Comment by paritoshmmmec** [comment]
This is the saddest thing I have ever seen in my whole life , damn you @pixiuPL

**Comment by marcosroriz** [comment]
Just reported this @pixiuPL guy. I hope that github will ban him.

**Comment by prima101112** [comment]
@ariya please don't close this project i'm not good open source contributors but please don't close phantomJS just because this. please

**Comment by neilhighley** [comment]
Well, Pixel seems like he thinks a couple of months of removing carriage returns makes him lead developer.
This should have been resolved with a swift removal of rights, let him vent all over reddit, he'll just be roundly mocked.
Part and parcel of internet comms in OSS though. Attract all sorts.

**Comment by mkarnicki** [comment]
<img width="390" alt="screen shot 2018-03-05 at 10 55 49" src="https://user-images.githubusercontent.com/2966794/36968795-e823d196-2063-11e8-89fe-5879b41e655d.png">

**Comment by revmischa** [comment]
come at the king you best not miss

**Comment by johnsnook** [comment]
Well we've reached the point in the drama where people are talking like Omar from "The Wire," so thanks everyone.

**Comment by HouzuoGuo** [comment]
Well, there vanishes my hope of seeing PhantomJS coming back to life with full steam ahead. A sincere thanks to all that are involved in the project, and hopefully we'll see positive development soon.

**Comment by enitihas** [comment]
I think there is an important lesson to be learnt here for open source projects and communities, that commit rights to the repo should not be given to people without any prior record of contribution. I mean I still do not understand how someone making a PR like this (https://github.com/twigphp/Twig/pull/2607) did manage to get contributor access to the repo. It shows what havoc a person in the hunt of building github stats can create at the cost of something valued by many.

**Comment by jomo** [comment]
> @pixiuPL you joined github december 2017. Haven't done much in the open source world either. No one can find your profile in the internet. You have no right to make such accusation, have respect towards original creator. And please earn your respect first before making a rant like this.

@pixiuPL's commit 66102e5326244c12b08dc4c573d47184ac100e6b shows the committer email as `nwolfe[ā]aptrinsic.com` (see [.patch](https://github.com/ariya/phantomjs/commit/66102e5326244c12b08dc4c573d47184ac100e6b.patch)).

His previous account seems to be @nwolfe-xx. For some reason he is not being as impolite on that account.

Quite interesting, he opened #13772, was asked to make changes and then merged the PR with his second account – without the changes he was asked for. (63cd19ad2c2760616f7742fca94b1b5dad3e0892 was also authored by @nwolfe-xx but commited by @pixiuPL)

**Comment by 3stadt** [comment]
@jomo I would disagree, this seems to be a forgotten commit from 2015 that was merged this january.
The commit 66102e5 you are referencing is a merge commit, made by pixi, with the changes from nwolfe.

Apart from that, I would suggest to not try doxxing pixiuPL, event though it is just digging for other online identities.
It's none of our business and it doesn't help in this situation. Just imaginge you are wrong and nwolfe-xx has nothing to do with this, it still will show up in his history and may look shady to people looking him up.

**Comment by MichaelErmer** [comment]
@3stadt I agree, also if you look at the commit quality, its quite questionable that it is the same person.

**Comment by abdilahrf** [comment]
Report this guy, useless commit!

**Comment by jomo** [comment]
@3stadt you're right, I was a little confused by how GitHub displays these things.

**Comment by nwolfe-xx** [comment]
@jomo: sorry for being so quiet on this, had no idea that my PR from 2015 was involved in this flame war.  It looks to me like pixiuPL merged it since I never responded to the requests for changes (various excuses for that...) . I used that original code change at my last job, it did exactly what we needed it to do, but if it's not needed by the community, I'm fine with that.

**Comment by phanan** [comment]
How did this guy become a collaborator in the first place? Almost all of his [commits](https://github.com/ariya/phantomjs/commits?author=pixiuPL) are either simplest changes (removing random empty lines WTF?) or bad merges, and then _fixes for his bad merges_. Just… wow. I'd say @ariya asked for this by granting this moron the write access to such an important repository.

**Comment by revmischa** [comment]
I think "such an important repository" might be overstating the case a little, given the rapid decline in popularity of PhantomJS thanks to chrome-headless, jest, enzyme and recent evolutions in frontend testing.

**Comment by phanan** [comment]
AFAIK, PhantomJS is the one to start and inspire the rest, which sounds pretty important to me, but this is off-topic anyway.

**Comment by revmischa** [comment]
Selenium might have that distinction

**Comment by kid-icarus** [comment]
Hello any plans phantomjs support async/await. Please.

**Comment by MichaelErmer** [comment]
@revmischa you are right, most new stuff is/should be developed using headless chrome and the like, however *A LOT* of old projects like screenshot tools, ssl checks etc. are still done using old phantomjs implementations, so its still an important repository. 

https://www.npmjs.com/package/phanton
```
Stats
5.339 downloads in the last day
26.717 downloads in the last week
146.731 downloads in the last month
```

**Comment by kensoh** [comment]
Second what you said @MichaelErmer - this is the other PJS package by Medium

https://www.npmjs.com/package/phantomjs-prebuilt

```
Stats
106,885 downloads in the last day
595,314 downloads in the last week
2,470,571 downloads in the last month
```

**Comment by jomo** [comment]
@nwolfe-xx all good! Please ignore my original comment, I was mistaken and have already deleted it.

**Comment by ariya** [comment]
@kid-icarus Try to follow #15342 instead. While at it, please also read #14541.

**Comment by ariya** [comment]
> I'd say @ariya asked for this by granting this moron the write access to such an important repository.

@phanan It doesn't mean that I didn't learn my lesson, but remember: hindsight is 20/20.

**Comment by MichaelErmer** [comment]
@ariya I think you should to reset the master branch to an earlier release as it and its commit history seems to be entirely broken, just look at stuff like this: 
https://github.com/ariya/phantomjs/commits/master/src/config.cpp
https://github.com/ariya/phantomjs/commit/a242fb8d605d9aa4afe5bf8d1267c1ded15f157c#diff-498d06653ad4a59db94a430cfa6f3937
https://github.com/ariya/phantomjs/pull/15347

**Comment by ariya** [comment]
@MichaelErmer Already planned, please follow #15344.

**Comment by ariya** [comment]
@dabrowt1 Check ##15344 (releases are removed, master branch will be reverted).

**Comment by tvvignesh** [comment]
@ariya Close this thread dude. Or wait, never mind. I will grab a popcorn.

**Comment by ariya** [comment]
The resolution has been reached. I'm closing this issue for now. Thanks everyone for your help!
