### ISSUE TITLE
Chinese character GBK code does not display

### ISSUE THREAD

**Issue by py151** [ariya/phantomjs#15353]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  1. phantomjs png.js http://kx.cq.gov.cn/zfxx/gsgg/2017-9/37423.html tu.png
  2.
  3.

3. Which operating system are you using?
windows7
4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.

**Comment by py151** [comment]
png.js： 

"use strict"
var page = require('webpage').create();
var args = require('system').args;
var url =  args[1];
var filename = args[2];


page.open(url, function (status) {
    if (status !== 'success') {
        phantom.outputEncoding="gbk";
        console.log('Unable to load ' + url + ' !');
        phantom.exit();
    } else {
        window.setTimeout(function () {
            phantom.outputEncoding="gbk";
            page.render(filename);
            phantom.outputEncoding="gbk";
            console.log('finish:', filename);
            phantom.exit();
        }, 1000);
    }

});

**Comment by ariya** [comment]
Thanks for the report! Unfortunately, the test URL doesn't work anywhere, hence it is impossible to troubleshoot the issue.
