### ISSUE TITLE
How to inject the scripts which downloaded from page 

### ISSUE THREAD

**Issue by HTKT** [ariya/phantomjs#15358]
The HTML page has the script as below:

```
<script src="/_res/js/jquery.js" type="text/javascript"></script>
<script src="/WebResource.axd?d=5At4BVuSsWGYDY9lb87tCvy" type="text/javascript"></script>

```

On `onResourceRecevied` function, i can see above script downloaded successful.
Then i inject them to `page` :

```
page.injectJs('/_res/js/jquery.js').then(async function(res) {
          console.log("injectJs")
        page.injectJs('/WebResource.axd?d=5At4BVuSsWGYDY9lb87tCvy').then(async function(res) {
            console.log("injectJs")
        })
})
```

The console logged "injectJs" but i can not call the any function on that script files.
I inject wrong path file or i have to use `includeJs` instead?

Thanks

**Comment by ariya** [comment]
Modern JavaScript features (from ES6/ES2015 or later, like `async`) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
