### ISSUE TITLE
Using let will lock up the progam

### ISSUE THREAD

**Issue by meepingsnesroms** [ariya/phantomjs#15355]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  1. Try to run my included js file.
  2. Rename let to var.
  3. Try it again.

3. Which operating system are you using?
Windows

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.
[proof.zip](https://github.com/ariya/phantomjs/files/1822290/proof.zip)

[let example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let)

**Comment by ariya** [comment]
Modern JavaScript features (from ES6/ES2015 or later) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
