### ISSUE TITLE
ReferenceError: Can't find variable: Set

### ISSUE THREAD

**Issue by putuoka** [ariya/phantomjs#15352]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
I'm using phantomjs 2.1.1 downloaded from official site link http://phantomjs.org/download.html

2. What steps will reproduce the problem?
  ```
a. copy the example screen capture code provided by this official example http://phantomjs.org/screen-capture.html or from this one https://github.com/ariya/phantomjs/blob/master/examples/responsive-screenshot.js

  b. run that file you created on step 1 with phantom js
  c. profit

```
3. Which operating system are you using?
Linux Ubuntu 14.04 (64 bit)

4. Did you use binary PhantomJS or did you compile it from source?
i use file from download link in official site https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2

5. Please provide any additional information below.
https://i.imgur.com/cPgZ7lS.png

**Comment by ariya** [comment]
Modern JavaScript features (from ES6/ES2015 or later) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
