### ISSUE TITLE
Error running tests using Karma

### ISSUE THREAD

**Issue by buddyackerman** [ariya/phantomjs#15351]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

    **2.1.1**

2. What steps will reproduce the problem?
  1. using it from karma via the karma-phantomjs-launcher
  2. 
  3.

3. Which operating system are you using?

    **Windows**

4. Did you use binary PhantomJS or did you compile it from source?

    **Binary**

5. Please provide any additional information below.

This is an Angular 5 project.

This is the error I'm getting.  I have no idea what it means so I can't troubleshoot the issue.  Just need to know what this means so I know where to look to fix it.

    PhantomJS 2.1.1 (Windows 8.0.0) ERROR
      {
        "message": "TypeError: pre,template,textarea,script,style is not iterable!\nat http://localhost:9876/_karma_webpack_/polyfills.bundle.js:792:83",
        "str": "TypeError: pre,template,textarea,script,style is not iterable!\nat http://localhost:9876/_karma_webpack_/polyfills.bundle.js:792:83"
      }

**Comment by tray2002** [comment]
It looks like it is the problem in your polyfills.bundle.js file - not phantomjs related issue.

Maybe you should change import section in polyfills typescript files :)

**Comment by ariya** [comment]
Like @tray2002 wrote, the problem seems to lie somewhere else. Try to strictly target ES5 as PhantomJS doesn't support ES6 yet until #15342 is implemented. Thank you!

**Comment by buddyackerman** [comment]
Just follow up, I switched to using ChromeHeadless as the browser.
