### ISSUE TITLE
Is phantomjs dead?

### ISSUE THREAD

**Issue by nirpeled** [ariya/phantomjs#15361]
I'm having some issues with version 2.1.1 and I understand that there is a new 2.5 beta but I can't get to install... so, is this dead?

I also found this on https://github.com/takuhii/PhantomJS-25_Beta:

![image](https://user-images.githubusercontent.com/6830805/38035318-d33cc5fc-32ac-11e8-9aee-419d1117e00a.png)

**Comment by admosity** [comment]
There was a maintainer, but their account is now deleted? #15275

**Comment by marksteward** [comment]
See #15344

(and #15345 if you're interested in what happened to the "maintainer")

**Comment by nirpeled** [comment]
😞

**Comment by ariya** [comment]
Please read #15344. Thank you!

**Comment by cloudenv** [comment]
@nirpeled @admosity I was that maintainer. Ive deleted my account here due to unhealthy atmosphere around me created by both @ariya and his "supporters".....

**Comment by snow212-cn** [comment]
I can see a 2.1.3 zip file in the releases.Is it executable?If not,how can we get it used..
