### ISSUE TITLE
Navigation in PDF report

### ISSUE THREAD

**Issue by vaibhav15s** [ariya/phantomjs#15365]
I am using 2.1.1 version.
I am generating pdf report using phantomjs.
I use config.js to configure the page settings and HTML file to generate pdf.
I am not able to navigate in pdf. I created Sections in HTML file. When I click on a particular section it is not jumping to that particular section instead it tries to open the browser.
I have used <a href="#section1" >Section1</a> in html.
Please let me know how this can be done. Do I need add anything in config.js and html?

**Comment by Maekchu** [comment]
I don't think you can navigate a pdf.

Do you have some code with what you are trying to do?

**Comment by vaibhav15s** [comment]
Yes, this is not possible with phantomjs. I used https://github.com/westy92/html-pdf-chrome . This works well.
