### ISSUE TITLE
textcontent of queryselector resulting Bad data

### ISSUE THREAD

**Issue by yashwanth2804** [ariya/phantomjs#15367]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
   Run this script
```
var page = require('webpage').create();
console.log('The default user agent is ' + page.settings.userAgent);
 

page.settings.encoding = "utf8";
page.settings.userAgent = 'SpecialAgent';

page.open('https://openload.co/f/5GyL0zb1X0k', function(status) {
  if (status !== 'success') {
    console.log('Unable to access network');
  } else {
    var ua = page.evaluate(function() {
  
var j= document.querySelector('p#DtsBlkVFQx').textContent;
      return j;
    });

console.log(ua);
   
  }
  phantom.exit();
});
```
    
3. Which operating system are you using?
Windows 7 
4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.

-  I want the element content with that particular id "DtsBlkVFQx" from that url 
-     But what I am getting is some random asciis

> I can able to get it from Puppeteer ,but I want it in Phantomjs .

**Comment by t4style** [comment]
I follow your question. I have a same problem ..

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
