### ISSUE TITLE
Build Script for phantomJS on Raspbian Squeeze

### ISSUE THREAD

**Issue by jonathan-annett** [ariya/phantomjs#15364]
need some help building on a raspberry pi 3

with a clean install of 2018-03-13-raspbian-stretch-lite.img 

i suspect there are some libs missing 

(note this is the lite version of raspbian not the graphical desktop version)

this is the script i wrote to formalize the build:
-----------------------
    #!/bin/bash

    sudo apt-get update  -y
    sudo apt-get upgrade -y
    sudo apt-get autoremove -y

    sudo apt-get install build-essential g++ flex bison gperf ruby perl \
    libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
    libpng-dev libjpeg-dev python libx11-dev libxext-dev autoconf \
     ttf-mscorefonts-installer git \
     -y

    if [[ ! -f ~/phantomjs/bin/phantomjs ]] ; then
	
	cd ~

	[[ -d ./phantomjs ]] && rm -rf phantomjs
        git clone git://github.com/ariya/phantomjs.git

	cd phantomjs

	git checkout 2.1.1
	git submodule init
	git submodule update
	python build.py --jobs 4

    fi

    phantomjs --version
-------------------------------------

issue is the compile crashes after some time with:

/moc_qclipboard.o .obj/moc_qdrag.o .obj/moc_qdnd_p.o .obj/moc_qevent.o .obj/moc_qkeysequence.o .obj/moc_qkeymapper_p.o .obj/moc_qpalette.o .obj/moc_qsessionmanager.o .obj/moc_qscreen.o .obj/moc_qstylehints.o .obj/moc_qtouchdevice.o .obj/moc_qplatformsharedgraphicscache.o .obj/moc_qplatformdialoghelper.o .obj/moc_qpaintdevicewindow.o .obj/moc_qrasterwindow.o .obj/moc_qplatformgraphicsbuffer.o .obj/moc_qinputdevicemanager_p.o .obj/moc_qimageiohandler.o .obj/moc_qpictureformatplugin.o .obj/moc_qiconengineplugin.o .obj/moc_qfont.o .obj/moc_qfontdatabase.o .obj/moc_qtextformat.o .obj/moc_qtextobject.o .obj/moc_qtextdocument.o .obj/moc_qtextimagehandler_p.o .obj/moc_qtexttable.o .obj/moc_qtextlist.o .obj/moc_qbrush.o .obj/moc_qpainter.o .obj/moc_qpdfwriter.o .obj/moc_qplatformbackingstore.o .obj/moc_qvalidator.o
rm -f ../../lib/libQt5Gui.a
mv -f libQt5Gui.a ../../lib/ 
make[2]: Leaving directory '/home/pi/phantomjs/src/qt/qtbase/src/gui'
make[1]: Leaving directory '/home/pi/phantomjs/src/qt/qtbase/src'
Makefile:44: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2

ERROR: Failed to build PhantomJS! Building Qt Base failed.

**Comment by jonathan-annett** [comment]
update - i have since increased swap space on the device (forgot to do that after the fresh install)
it now gets much further but is now aborting when it attempts to buiild openssl support

collect2: error: ld returned 1 exit status
Makefile:194: recipe for target '../../../bin/uic' failed
make[2]: *** [../../../bin/uic] Error 1
make[2]: Leaving directory '/home/pi/phantomjs/src/qt/qtbase/src/tools/uic'
Makefile:444: recipe for target 'sub-uic-make_first' failed
make[1]: *** [sub-uic-make_first] Error 2
In file included from ../../include/QtNetwork/5.5.1/QtNetwork/private/qsslsocket_openssl_symbols_p.h:1:0,
                 from ssl/qsslcontext_openssl.cpp:44:
ssl/qsslcontext_openssl.cpp: In static member function ‘static QSslContext* QSslContext::fromConfiguration(QSslSocket::SslMode, const QSslConfiguration&, bool)’:
../../include/QtNetwork/5.5.1/QtNetwork/private/../../../../../src/network/ssl/qsslsocket_openssl_symbols_p.h:488:60: error: ‘SSL_CTRL_OPTIONS’ was not declared in this scope
 #define q_SSL_CTX_set_options(ctx,op) q_SSL_CTX_ctrl((ctx),SSL_CTRL_OPTIONS,(op),NULL)
                                                            ^
ssl/qsslcontext_openssl.cpp:189:5: note: in expansion of macro ‘q_SSL_CTX_set_options’
     q_SSL_CTX_set_options(sslContext->ctx, options);
     ^~~~~~~~~~~~~~~~~~~~~
ssl/qsslcontext_openssl.cpp:327:41: error: ‘SSL_CTRL_SET_ECDH_AUTO’ was not declared in this scope
         q_SSL_CTX_ctrl(sslContext->ctx, SSL_CTRL_SET_ECDH_AUTO, 1, NULL);
                                         ^~~~~~~~~~~~~~~~~~~~~~
ssl/qsslcontext_openssl.cpp: In member function ‘bool QSslContext::cacheSession(SSL*)’:
ssl/qsslcontext_openssl.cpp:471:50: error: invalid use of incomplete type ‘SSL_SESSION {aka struct ssl_session_st}’
             m_sessionTicketLifeTimeHint = session->tlsext_tick_lifetime_hint;
                                                  ^~
In file included from ../../include/QtNetwork/5.5.1/QtNetwork/private/../../../../../src/network/ssl/qsslcontext_openssl_p.h:53:0,
                 from ../../include/QtNetwork/5.5.1/QtNetwork/private/qsslcontext_openssl_p.h:1,
                 from ssl/qsslcontext_openssl.cpp:41:
/usr/include/openssl/ssl.h:228:16: note: forward declaration of ‘SSL_SESSION {aka struct ssl_session_st}’
 typedef struct ssl_session_st SSL_SESSION;
                ^~~~~~~~~~~~~~
Makefile:22102: recipe for target '.obj/qsslcontext_openssl.o' failed
make[2]: *** [.obj/qsslcontext_openssl.o] Error 1
make[2]: Leaving directory '/home/pi/phantomjs/src/qt/qtbase/src/network'
Makefile:213: recipe for target 'sub-network-make_first' failed
make[1]: *** [sub-network-make_first] Error 2
make[1]: Leaving directory '/home/pi/phantomjs/src/qt/qtbase/src'
Makefile:44: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2

ERROR: Failed to build PhantomJS! Building Qt Base failed.

**Comment by jonathan-annett** [comment]
discovered an informal prebuilt deb that seems to work satisfactorily:
---------------------------------------
#!/bin/bash

sudo apt-get update  -y

sudo apt-get install ttf-mscorefonts-installer \
libfreetype6 fontconfig-config fonts-dejavu-core libexpat1 \
fontconfig-config fonts-dejavu-core libexpat1 libfontconfig1 libfreetype6 -y

cd ~

[[ ! -f ./phantomjs_2.1.1_armhf.deb ]] || wget https://github.com/fg2it/phantomjs-on-raspberry/releases/download/v2.1.1-wheezy-jessie-armv6/phantomjs_2.1.1_armhf.deb

[[ -f ./phantomjs_2.1.1_armhf.deb ]] && sudo dpkg -i ./phantomjs_2.1.1_armhf.deb

which phantomjs && phantomjs --version

**Comment by ariya** [comment]
Supporting other architectures (than x86) is a major undertaking and currently beyond the scope of the project.
You are however free to work on it on your own or sponsor someone to implement it. Once it is in a state where we can consider it for inclusion, please reopen this issue and submit a pull request of the implementation. Thank you!

**Comment by jonathan-annett** [comment]
I found a working solution here

Github fg2it

Here's a script similar to what I use to roll it out

https://pastebin.com/7gNAx2X7

BTW,  have you ever thought of adding a framebuffer option for Linux
installs?

Eg in render() a filename of /dev/fb0 would convert the image to a format
suitable to display on that device.

You'd need to make sure the resolution matches the monitor

See the Linux fibida source for details on how to construct a buffer

I currently do it by running a (patched) version of fbida which I setup to
loop a continous slideshow displaying /dev/shm/live.png, which reloads the
image from virtual disk in response to a usr1 signal instead of a key
press. Works but there is an obvious delay as the file gets compressed
saved loaded compressed and displayed

Using it for a non-x display widget on Pi zero w hardware, so users can
distribute signage in a low cost way
