### ISSUE TITLE
PhantomJS does not work with non-ASCII query URLs

### ISSUE THREAD

**Issue by apaksoy** [ariya/phantomjs#15379]
Hello!

I am trying to scrape data from a weather site in Turkish which sometimes requires non-ASCII query URLs. I use beautifulsoup4, PhantomJS, and Selenium with Python on macOS. 

The code works fine when the query includes only ASCII characters. Otherwise, it fails to fetch the correct data (web page). Here is an example:

```
#!/usr/bin/env python3

import bs4
from selenium import webdriver

browser = webdriver.PhantomJS(executable_path='/usr/local/Cellar/phantomjs211/bin/phantomjs')

url = 'https://www.mgm.gov.tr/?il=Istanbul&ilce=Adalar'
browser.get(url)
html = browser.page_source

soup = bs4.BeautifulSoup(html, 'lxml')

elems_il = soup.select('ziko.ng-binding')
elems_ilce = soup.select('span.ng-binding')
print(elems_il[0].getText() + ', ' + elems_ilce[0].getText())

elems_tahmin = soup.select('div.tahminHadise.ng-binding')
print(elems_tahmin[0].getText())
```

correctly returns

> İstanbul, Adalar
> Az Bulutlu 

but when the url is changed as follows (note the non-ASCII "Ü" in the URL)

```
url = 'https://www.mgm.gov.tr/?il=Istanbul&ilce=Ümraniye'
```

one gets the default web page and, therefore,

> Ankara,
> Az Bulutlu 

instead of

> İstanbul, Ümraniye
> Az Bulutlu

When I paste the query URL manually into a browser (Safari, Firefox), I get the correct web page even when the URL includes non-ASCII characters. 

Hopefully, the weather is pretty much the same in both locations nowadays but this may change soon! 

I am using PhantomJS v2.1.1 for macOS on High Sierra (v10.13.4) with Python v3.6.5 / Selenium 3.6.0 / beautifulsoup4 4.6.0. I guess I am using the binary PhantomJS as I downloaded it from http://phantomjs.org/download.html. 

Any suggestions? Thank you!

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
