### ISSUE TITLE
How to compile the phantomjs of version 2.1.3 on windows 10

### ISSUE THREAD

**Issue by whu-luojian** [ariya/phantomjs#15377]
The  stable release of phantomjs is version 2.1.1, which can be downloaded from http://phantomjs.org/release-2.1.html, but it was released on January 23, 2016. It not supported many css properties when using it to screen capture. And i have tried phantomjs-2.5-beta-windows downloaded from https://bitbucket.org/ariya/phantomjs/downloads/, but it has many bugs, for example, it can only print one page.
      So i want to know how to compile the phantomjs of version 2.1.3 on windows 10 which can be downloaded from https://github.com/ariya/phantomjs/releases, or someone else can share me the compiled one. Thank you very much.

**Comment by ariya** [comment]
That version is not supported, see #15344 for details.
