### ISSUE TITLE
Can not find module webpage and phantom js function not working.

### ISSUE THREAD

**Issue by vishnusinghchauhan** [ariya/phantomjs#15373]
const phantom = require('phantom');

	var page = require('webpage').create();
	page.onConsoleMessage = function (msg) {
		console.log(msg);
	};
	page.open('./index.html', function(status) {
		phantom.exit();
	});

  "dependencies": {
    "phantom": "^4.0.12"
  }

**Comment by lydiali9** [comment]
I have meet this issue, How to resolve the issue????

**Comment by Jeevan-kumar-Raj** [comment]
**_var page = new WebPage();_**
**Example Here**
**You can Simple Write Like This  **

> var page = new WebPage();
page.open('http://example.com', function(status) {
  console.log("Status: " + status);
  if(status === "success") {
    page.render('example.png');
  }
  phantom.exit();
});
