### ISSUE TITLE
phantomjs 2.1.1 sometimes sends corrupt post data (when the server is busy)

### ISSUE THREAD

**Issue by divdavem** [ariya/phantomjs#15378]
**Which version of PhantomJS are you using?**

Version 2.1.1

**What steps will reproduce the problem?**

- Make sure you have nodejs >= 8 installed:
```
node --version
```
- Clone my repository which contains the code to reproduce the issue:
```
git clone https://github.com/divdavem/phantomjs_nodejs_post_corrupted_data.git
```
- In one terminal, start the server (with nodejs):
```
node server.js
````
- In another terminal, start the client:
```
phantomjs phantomjs.js
```

After some time the server displays `KO` and exits, which means the data received in a POST request is corrupt.
Before restarting the server, make sure to close any client because the reference data (to be sent in the POST request) is set randomly server-side when the server starts.

**Which operating system are you using?**

Windows 10

**Did you use binary PhantomJS or did you compile it from source?**

I used the binary PhantomJS from http://phantomjs.org/download.html

**Please provide any additional information below.**

The issue only happens with phantomjs (it does not happen with Chrome, Firefox...).
It does not seem to happen with nodejs 6.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
