### ISSUE TITLE
Targetted css selectors in chrome browser differs from phantomJS

### ISSUE THREAD

**Issue by r8w9a5k** [ariya/phantomjs#15371]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1.0

2. What steps will reproduce the problem?
  1. Targeted css selectors differs from browser and phantomJS.

3. Which operating system are you using?
Win10
4. Did you use binary PhantomJS or did you compile it from source?
Binary
5. Please provide any additional information below.
When I run this simple js code in browser, it is fetching data every second and it's just fine. But when I try to run this in phantomJS, it logs different cell (and I still don't know how to set interval in phantom like I did in this simple code):

```
function scrape(){
var table = document.querySelectorAll(".mb-market__runners")[0]; //first table
var row = table.querySelectorAll(".mb-runner")[0]; //first row
var cell= row.querySelectorAll(".mb-price")[0]; //first cell
console.log(bunka.textContent); //value from first cell
}
setInterval(scrape, 1000); //repeat after 1 second
```

You can run this script in browser's console. Chrome >> https://www.matchbook.com >> F12 >> insert this code.

If someone knows how to push my code to something that phantomJS would understand I would be really grateful.

My phantomJS try was something like:

```
 var webPage = require('webpage');
 var page = webPage.create();
 var url = "https://matchbook.com"
 
 page.open(url, function(status) {
 
   var x = page.evaluate(function() {
   	var bunka = document.querySelectorAll(".mb-price")[0];
     return bunka.textContent;
   });

  console.log(x);
  phantom.exit();

});
```

but it doesn't work as expected + it skips two cells :/

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
