### ISSUE TITLE
phantomjs is stuck in a specific web page

### ISSUE THREAD

**Issue by neo0000** [ariya/phantomjs#15372]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
**1.9.8**
2. What steps will reproduce the problem?
 - by moving to this url: https://outlook.live.com/owa 
 - but the problem phantomjs was stuck from this url: https://account.microsoft.com/?lang=zh-CN&refd=account.live.com&refp=landing.

- Here is the sample code.
- This is how I initialize phantomJS driver:
_phantomoptions = new PhantomJSOptions();
_phantomservice = PhantomJSDriverService.CreateDefaultService();
_phantomservice.HideCommandPromptWindow = true;
_phantomdriver = new PhantomJSDriver(_phantomservice);
_phantomdriver.Manage().Window.Size = new Size(1024, 768);

private void tmr_Tick(object sender, EventArgs e)
        {
            tmr.Stop();
            string _msg = "";
            try
            {
                if (_phantomdriver.Url.Contains("refd=account.live.com&refp=landing"))
                {
                    
                    if (LANG == "CN")
                        _msg = "重定向到收件箱页面：";
                    else if (LANG == "EN")
                        _msg = "Redirecting to inbox page: ";

                    _msg = _msg + "https://outlook.live.com/owa";
                    
                    if (LANG == "CN")
						_msg = "尝试3中的" + _landingCnt + "重定向到收件箱页面...";
					else if (LANG == "EN")
						_msg = "Attempt " + _landingCnt + " out of 3 to redirect to inbox page...";

                    _phantomdriver.Navigate().GoToUrl("https://outlook.live.com/owa");		
					Invoke(new MethodInvoker(tmr.Start));
                }
                else if (_phantomdriver.Url.Contains("https://outlook.live.com/owa"))
                {
                    //Check emails here...
                }
            }
            catch (Exception ex)
            {
                //error...
            }
        }  

3. Which operating system are you using?
Vmware Windows XP SP3(Chinese)
4. Did you use binary PhantomJS or did you compile it from source?
No
5. Please provide any additional information below.
Tested it with Windows XP SP3(US) working well.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
