### ISSUE TITLE
phantomjs version 2.1.1 produces shrinked pdf.

### ISSUE THREAD

**Issue by Shailendre** [ariya/phantomjs#15384]
1. **Which version of PhantomJS are you using? Tip: run `phantomjs --version`.**
2.1.1

2. **What steps will reproduce the problem?**
  - Use the html template to create a pdf version
  - When html template is printed directly using the `webEngine.print(PrinterJob job)` the pdf is as expected. But saving the html as pdf and then printing it, a shrinked version is printed. Difference observed in pdfs

3. **Which operating system are you using?**
Windows 7 enterprise edition

4. **Did you use binary PhantomJS or did you compile it from source?**
Binary

5. **Please provide any additional information below.**
It is observed that different platform are actually producing slightly different pdf version. Tested on Mac El-Caption and Windows 7 enterprise. But since target environment is always Windows, hence output on Mac ignored.

6. **Sample phantomjs file used:**

```
/**
 * Create page object
 */
var page = require('webpage').create(),
    system = require('system');

/**
 * Check for required parameters*/

if (system.args.length < 2) {
    console.log('Usage: report.js <some URL> <output path/filename>');
    phantom.exit();
}
page.onConsoleMessage = function (msg) {
    console.log(msg);
};

/**
 * Grab the page and output it to specified target
 */
page.paperSize = {
    format: "A4",
    footer: {
        height: "0.9cm",
        contents: phantom.callback(function (pageNum, numPages) {
            return "<div style='text-align:center;'><small></small></div>";
        })
    }
};
/**
 * Set background according to accredited or obsolute
 */
page.open(system.args[1], function (status) {
        if (status === "success") {
            // business logic 
            window.setTimeout(function () {
               /**
               * tried scaling the page before rendering
               */
                page.render(system.args[2]);
                phantom.exit();
            }, 200);
        } else {
            console.log("error occured");
            phantom.exit();
        }

    }
);
```

7. **Queries**:

- Can different printer settings produce this kind of variance in pdf versions? But since same printer / printer setting is used in both pdf versions. Does phantomjs depends on default printer settings?

8. **Attachment**
![imageedit_32_3162487369](https://user-images.githubusercontent.com/6144715/39758494-a8101b52-52ed-11e8-8269-dcf2a4c21022.jpg)

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
