### ISSUE TITLE
WebPages with Swedish Fonts are not rendered properly to PDF

### ISSUE THREAD

**Issue by jnaresh19** [ariya/phantomjs#15388]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
phantomjs-2.1.1-windows

2. What steps will reproduce the problem?
   ->Have any web page containing a mix of english + swedish characters
  ->try to generate a pdf file using phantom js 
  ->in pdf file we can observe english characters are displayed properly, but swedish characters
are not displayed at all (totally removed from the pdf itself)

3. Which operating system are you using?
Windows 2012 Server

4. Did you use binary PhantomJS or did you compile it from source?
binary

5. Please provide any additional information below.
we did installed few fonts in windows os , but still it didn't work. Please let me know if I am missing something here... (installing additional font modules etc... like in linux)

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
