### ISSUE TITLE
PhantomJS error in files when I declare let

### ISSUE THREAD

**Issue by ArmandoAA** [ariya/phantomjs#15385]
1. Which version of PhantomJS are you using?
2.1.1

2. What steps will reproduce the problem?
  1. Declare let in file
  2. Get errors
![image](https://user-images.githubusercontent.com/37708752/40246558-973e44c0-5a9f-11e8-958e-52a7a07ca04a.png)

3. Which operating system are you using?
Windows 10

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.
A piece of my code
```
	ctrl.$parsers.unshift(function(viewValue) {

		let value = viewValue.replace(/\D/g,'');

		if(value.length != 0){
			ctrl.$setValidity("cep", false);
			if(value.length == 8){
				ctrl.$setValidity("cep", true);
				return value;
			}
			return undefined;
		}else{
			ctrl.$setValidity("cep", true);
			return value;
		}
	});
```

**Comment by ariya** [comment]
Modern JavaScript features (from ES6/ES2015 or later) will be only supported via an updated QtWebKit.
From now on, please track #15342. Thank you!
