### ISSUE TITLE
Shouldn't the project's status be more apparent?

### ISSUE THREAD

**Issue by teo-tsirpanis** [ariya/phantomjs#15381]
As only #15344 indicated, PhantomJS is dead. However, the project's site does not even hint about its status. On the contrary, the README does even state about the Contribution Guide.

Given the issue's obscurity, users might [be unaware of its status](https://github.com/lefthandedgoat/canopy/issues/436), or even worse, use it in new projects.

I suggest adding a header at the README and the website that also suggests alternatives like [Puppeteer](https://github.com/GoogleChrome/puppeteer).

**Comment by jimrandomh** [comment]
Here because I tried to use it in a new project. Ran into a bit of blatant brokenness (child_process.spawn does nothing rather than invoke any process-creation-related system calls, verified by strace). Would have really appreciated a warning that the project was dead, before I wasted a day on it.

**Comment by ariya** [comment]
README has been updated.
