### ISSUE TITLE
Margin is ignored in flexbox element children.

### ISSUE THREAD

**Issue by itsacorn** [ariya/phantomjs#15386]
1. Which version of PhantomJS are you using? 2.1.1 (latest on NPM)

2. What steps will reproduce the problem?
  1. Create an HTML flexbox element.
  2. Have children in it which have margins.

3. Which operating system are you using? Windows 10 64-bit

4. Did you use binary PhantomJS or did you compile it from source? I used the prebuilt binaries.

5. Please provide any additional information below.

This is how it looks: <img src="https://rlme.is-a-me.me/89e1807c.png">

This is how it should look: <img src="https://rlme.is-a-me.me/b2b35e34.png">

(logo has `margin: auto`, navbar element "Support" has `margin-left: auto`, title has `margin-bottom`)

_The size difference should be ignored, my monitor is 1920x1080 but it is at 125% scaling, while Phantom is at 1920x1080 at 100%_

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
