### ISSUE TITLE
terminate called without an active exception PhantomJS has crashed

### ISSUE THREAD

**Issue by kvelaro** [ariya/phantomjs#15380]
We have phantomjs autocalculating products. Sometimes it crushes. I look script, screenshots and cannot figure out whats going on, why it crushes. We cannot migrate to newer version now. According to your docs, I have decoded dump, so below it is.
It would be nice, if some useful information provided

1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
**1.9.7**
2. Which operating system are you using?
**centos 6**

3. Did you use binary PhantomJS or did you compile it from source?
**binary**

4. Please provide any additional information below.
Operating system: Linux
                  0.0.0 Linux 2.6.32-642.15.1.el6.x86_64 #1 SMP Fri Feb 24 14:31:22 UTC 2017 x86_64
CPU: amd64
     family 6 model 45 stepping 7
     12 CPUs

Crash reason:  SIGABRT
Crash address: 0x4e69

Thread 0 (crashed)
 0  libc-2.12.so + 0x325e5
    rbx = 0x00000000041d31b8   r12 = 0x0000000000000000
    r13 = 0x0000000004254930   r14 = 0x0000000004135e80
    r15 = 0x0000000002765f80   rip = 0x00007f65b82125e5
    rsp = 0x00007fffa56607d8   rbp = 0x00000000041d3170
    Found by: given as instruction pointer in context
 1  libc-2.12.so + 0x33dc4
    rip = 0x00007f65b8213dc5   rsp = 0x00007fffa56607e0
    Found by: stack scanning
 2  ld-2.12.so + 0x55f
    rip = 0x00007f65b9810560   rsp = 0x00007fffa5660800
    Found by: stack scanning
 3  libc-2.12.so + 0x6b57
    rip = 0x00007f65b81e6b58   rsp = 0x00007fffa5660818
    Found by: stack scanning
 4  libm-2.12.so + 0x283fff
    rip = 0x00007f65b8a0e000   rsp = 0x00007fffa5660868
    Found by: stack scanning
 5  ld-2.12.so + 0xe19f
    rip = 0x00007f65b981e1a0   rsp = 0x00007fffa5660870
    Found by: stack scanning
 6  libstdc++.so.6.0.13 + 0xbea7c
    rip = 0x00007f65b8acca7d   rsp = 0x00007fffa5660910
    Found by: stack scanning
 7  ld-2.12.so + 0x149d4
    rip = 0x00007f65b98249d5   rsp = 0x00007fffa5660920
    Found by: stack scanning
 8  libpthread-2.12.so + 0xe7cc
    rip = 0x00007f65b8d227cd   rsp = 0x00007fffa5660930
    Found by: stack scanning
 9  libstdc++.so.6.0.13 + 0xbcbd5
    rip = 0x00007f65b8acabd6   rsp = 0x00007fffa5660950
    Found by: stack scanning
10  libstdc++.so.6.0.13 + 0xbcc02
    rip = 0x00007f65b8acac03   rsp = 0x00007fffa5660960
    Found by: stack scanning
11  libstdc++.so.6.0.13 + 0xbd55e
    rip = 0x00007f65b8acb55f   rsp = 0x00007fffa5660970
    Found by: stack scanning
12  phantomjs + 0x159cf02
    rip = 0x000000000199cf03   rsp = 0x00007fffa5660980
    Found by: stack scanning
13  libc-2.12.so + 0x38e11f
    rip = 0x00007f65b856e120   rsp = 0x00007fffa56609a0
    Found by: stack scanning
14  phantomjs + 0x15ad5fc
    rip = 0x00000000019ad5fd   rsp = 0x00007fffa56609d0
    Found by: stack scanning
15  phantomjs + 0x15b0653
    rip = 0x00000000019b0654   rsp = 0x00007fffa5660a10
    Found by: stack scanning
16  phantomjs + 0x15ad9f3
    rip = 0x00000000019ad9f4   rsp = 0x00007fffa5660ac0
    Found by: stack scanning
17  phantomjs + 0x15afc9e
    rip = 0x00000000019afc9f   rsp = 0x00007fffa5660b00
    Found by: stack scanning
18  phantomjs + 0x1406db8
    rip = 0x0000000001806db9   rsp = 0x00007fffa5660b60
    Found by: stack scanning
19  libc-2.12.so + 0x38e11f
    rip = 0x00007f65b856e120   rsp = 0x00007fffa5660bc0
    Found by: stack scanning
20  libc-2.12.so + 0x38e11f
    rip = 0x00007f65b856e120   rsp = 0x00007fffa5660be0
    Found by: stack scanning
21  libc-2.12.so + 0x7aaff
    rip = 0x00007f65b825ab00   rsp = 0x00007fffa5660c10
    Found by: stack scanning
22  phantomjs + 0x1449d66
    rip = 0x0000000001849d67   rsp = 0x00007fffa5660cb0
    Found by: stack scanning
23  libc-2.12.so + 0x38e11f
    rip = 0x00007f65b856e120   rsp = 0x00007fffa5660cc0
    Found by: stack scanning
24  libc-2.12.so + 0x7abfb
    rip = 0x00007f65b825abfc   rsp = 0x00007fffa5660cf0
    Found by: stack scanning
25  phantomjs + 0x1e689
    rip = 0x000000000041e68a   rsp = 0x00007fffa5660d20
    Found by: stack scanning
26  phantomjs + 0x14fd8f2
    rip = 0x00000000018fd8f3   rsp = 0x00007fffa5660d60
    Found by: stack scanning
27  libstdc++.so.6.0.13 + 0xbd0bc
    rip = 0x00007f65b8acb0bd   rsp = 0x00007fffa5660e10
    Found by: stack scanning
28  phantomjs + 0x13fa4a1
    rip = 0x00000000017fa4a2   rsp = 0x00007fffa5660e30
    Found by: stack scanning
29  phantomjs + 0x1441bfc
    rip = 0x0000000001841bfd   rsp = 0x00007fffa5660e50
    Found by: stack scanning
30  phantomjs + 0x1443506
    rip = 0x0000000001843507   rsp = 0x00007fffa5660e90
    Found by: stack scanning
31  phantomjs + 0x143bf1c
    rip = 0x000000000183bf1d   rsp = 0x00007fffa5660ef0
    Found by: stack scanning
32  phantomjs + 0x1442114
    rip = 0x0000000001842115   rsp = 0x00007fffa5660f10
    Found by: stack scanning
33  libc-2.12.so + 0x569f9
    rip = 0x00007f65b82369fa   rsp = 0x00007fffa5660f80
    Found by: stack scanning
34  libpthread-2.12.so + 0xf78f
    rip = 0x00007f65b8d23790   rsp = 0x00007fffa5660fa8
    Found by: stack scanning
35  phantomjs + 0xf07a5b
    rip = 0x0000000001307a5c   rsp = 0x00007fffa5660ff0
    Found by: stack scanning
36  phantomjs + 0x1a6326e
    rip = 0x0000000001e6326f   rsp = 0x00007fffa5660ff8
    Found by: stack scanning
37  phantomjs + 0xf0c5db
    rip = 0x000000000130c5dc   rsp = 0x00007fffa5661020
    Found by: stack scanning
38  phantomjs + 0x14424d7
    rip = 0x00000000018424d8   rsp = 0x00007fffa5661090
    Found by: stack scanning
39  phantomjs + 0xf0c5db
    rip = 0x000000000130c5dc   rsp = 0x00007fffa56610a0
    Found by: stack scanning
40  libc-2.12.so + 0x156d25
    rip = 0x00007f65b8336d26   rsp = 0x00007fffa56610a8
    Found by: stack scanning
41  libc-2.12.so + 0x69684
    rip = 0x00007f65b8249685   rsp = 0x00007fffa56610b0
    Found by: stack scanning
42  libc-2.12.so + 0x38e11f
    rip = 0x00007f65b856e120   rsp = 0x00007fffa56610e0
    Found by: stack scanning
43  phantomjs + 0x160bb4c
    rip = 0x0000000001a0bb4d   rsp = 0x00007fffa5661118
    Found by: stack scanning
44  phantomjs + 0x13f7595
    rip = 0x00000000017f7596   rsp = 0x00007fffa5661120
    Found by: stack scanning
45  libstdc++.so.6.0.13 + 0xbd0bc
    rip = 0x00007f65b8acb0bd   rsp = 0x00007fffa5661130
    Found by: stack scanning
46  phantomjs + 0x1440fd8
    rip = 0x0000000001840fd9   rsp = 0x00007fffa5661150
    Found by: stack scanning
47  phantomjs + 0x13fd0dc
    rip = 0x00000000017fd0dd   rsp = 0x00007fffa56611b0
    Found by: stack scanning
48  libc-2.12.so + 0x7a458
    rip = 0x00007f65b825a459   rsp = 0x00007fffa56611d0
    Found by: stack scanning
49  libc-2.12.so + 0x7a458
    rip = 0x00007f65b825a459   rsp = 0x00007fffa56611e0
    Found by: stack scanning
50  phantomjs + 0xf07a5b
    rip = 0x0000000001307a5c   rsp = 0x00007fffa56611f0
    Found by: stack scanning
51  libc-2.12.so + 0x38e11f
    rip = 0x00007f65b856e120   rsp = 0x00007fffa5661270
    Found by: stack scanning
52  libc-2.12.so + 0x7bd5f
    rip = 0x00007f65b825bd60   rsp = 0x00007fffa5661290
    Found by: stack scanning
53  libc-2.12.so + 0x38e11f
    rip = 0x00007f65b856e120   rsp = 0x00007fffa56612c8
    Found by: stack scanning
54  libc-2.12.so + 0x7c057
    rip = 0x00007f65b825c058   rsp = 0x00007fffa56612d0
    Found by: stack scanning
55  phantomjs + 0x141861f
    rip = 0x0000000001818620   rsp = 0x00007fffa5661310
    Found by: stack scanning
56  phantomjs + 0x14d4a95
    rip = 0x00000000018d4a96   rsp = 0x00007fffa5661320
    Found by: stack scanning
57  phantomjs + 0x14d4c8f
    rip = 0x00000000018d4c90   rsp = 0x00007fffa5661340
    Found by: stack scanning
58  phantomjs + 0x12cf0d9
    rip = 0x00000000016cf0da   rsp = 0x00007fffa5661370
    Found by: stack scanning
59  phantomjs + 0x141a2fc
    rip = 0x000000000181a2fd   rsp = 0x00007fffa56613a0
    Found by: stack scanning
60  libc-2.12.so + 0x38e11f
    rip = 0x00007f65b856e120   rsp = 0x00007fffa56613c0
    Found by: stack scanning
61  libc-2.12.so + 0x7a458
    rip = 0x00007f65b825a459   rsp = 0x00007fffa56613f0
    Found by: stack scanning
62  libc-2.12.so + 0x38e11f
    rip = 0x00007f65b856e120   rsp = 0x00007fffa5661470
    Found by: stack scanning
63  libc-2.12.so + 0x38e11f
    rip = 0x00007f65b856e120   rsp = 0x00007fffa56614a0
    Found by: stack scanning
64  libc-2.12.so + 0x7abfb
    rip = 0x00007f65b825abfc   rsp = 0x00007fffa56614d0
    Found by: stack scanning
65  libc-2.12.so + 0x38e11f
    rip = 0x00007f65b856e120   rsp = 0x00007fffa56614f0
    Found by: stack scanning
66  phantomjs + 0x15ed28f
    rip = 0x00000000019ed290   rsp = 0x00007fffa5661540
    Found by: stack scanning
67  phantomjs + 0x1415346
    rip = 0x0000000001815347   rsp = 0x00007fffa5661550
    Found by: stack scanning
68  phantomjs + 0x1419d18
    rip = 0x0000000001819d19   rsp = 0x00007fffa5661570
    Found by: stack scanning
69  phantomjs + 0x1a61540
    rip = 0x0000000001e61541   rsp = 0x00007fffa5661578
    Found by: stack scanning
70  phantomjs + 0x141466f
    rip = 0x0000000001814670   rsp = 0x00007fffa56615d0
    Found by: stack scanning
71  phantomjs + 0x13f97e5
    rip = 0x00000000017f97e6   rsp = 0x00007fffa5661620
    Found by: stack scanning

Thread 1
 0  libpthread-2.12.so + 0xb68c
    rbx = 0x00007f6550d0e4e0   r12 = 0x0000000000000001
    r13 = 0x00000000000000ff   r14 = 0x0000000000000001
    r15 = 0x0000000002770160   rip = 0x00007f65b8d1f68c
    rsp = 0x00007f65b071ade0   rbp = 0x0000000002770130
    Found by: given as instruction pointer in context
 1  phantomjs + 0xc7a2b
    rip = 0x00000000004c7a2c   rsp = 0x00007f65b071ae10
    Found by: stack scanning
 2  ld-2.12.so + 0x149d4
    rip = 0x00007f65b98249d5   rsp = 0x00007f65b071ae50
    Found by: stack scanning
 3  phantomjs + 0xc7b68
    rip = 0x00000000004c7b69   rsp = 0x00007f65b071ae90
    Found by: stack scanning
 4  libpthread-2.12.so + 0x7aa0
    rip = 0x00007f65b8d1baa1   rsp = 0x00007f65b071aea0
    Found by: stack scanning

Thread 2
 0  libc-2.12.so + 0xe1523
    rbx = 0x00007f65a8000d30   r12 = 0x0000000000000000
    r13 = 0x00007f65a8000a98   r14 = 0x0000000000000008
    r15 = 0x00007f65a8000a98   rip = 0x00007f65b82c1523
    rsp = 0x00007f65afd19b80   rbp = 0x00007f65a8000fc8
    Found by: given as instruction pointer in context
 1  phantomjs + 0x15c1a65
    rip = 0x00000000019c1a66   rsp = 0x00007f65afd19b90
    Found by: stack scanning
 2  phantomjs + 0x150d5a3
    rip = 0x000000000190d5a4   rsp = 0x00007f65afd19bb0
    Found by: stack scanning
 3  phantomjs + 0x15c2df1
    rip = 0x00000000019c2df2   rsp = 0x00007f65afd19c30
    Found by: stack scanning
 4  librt-2.12.so + 0x3ea5
    rip = 0x00007f65b8f34ea6   rsp = 0x00007f65afd19c50
    Found by: stack scanning
 5  phantomjs + 0x150d5a3
    rip = 0x000000000190d5a4   rsp = 0x00007f65afd19c70
    Found by: stack scanning
 6  phantomjs + 0x15a09e3
    rip = 0x00000000019a09e4   rsp = 0x00007f65afd19ca0
    Found by: stack scanning
 7  phantomjs + 0x150d628
    rip = 0x000000000190d629   rsp = 0x00007f65afd19cb0
    Found by: stack scanning
 8  phantomjs + 0x15c2795
    rip = 0x00000000019c2796   rsp = 0x00007f65afd19cc0
    Found by: stack scanning
 9  phantomjs + 0x15c2835
    rip = 0x00000000019c2836   rsp = 0x00007f65afd19cf0
    Found by: stack scanning
10  phantomjs + 0x15c3f6a
    rip = 0x00000000019c3f6b   rsp = 0x00007f65afd19d40
    Found by: stack scanning
11  phantomjs + 0x159bdc1
    rip = 0x000000000199bdc2   rsp = 0x00007f65afd19d90
    Found by: stack scanning
12  phantomjs + 0x159c123
    rip = 0x000000000199c124   rsp = 0x00007f65afd19dc0
    Found by: stack scanning
13  libstdc++.so.6.0.13 + 0xbd0bc
    rip = 0x00007f65b8acb0bd   rsp = 0x00007f65afd19dd0
    Found by: stack scanning
14  phantomjs + 0x14b59ee
    rip = 0x00000000018b59ef   rsp = 0x00007f65afd19e10
    Found by: stack scanning
15  phantomjs + 0x14b8291
    rip = 0x00000000018b8292   rsp = 0x00007f65afd19e60
    Found by: stack scanning
16  libpthread-2.12.so + 0x7aa0
    rip = 0x00007f65b8d1baa1   rsp = 0x00007f65afd19ea0
    Found by: stack scanning

Thread 3
 0  libc-2.12.so + 0xe1523
    rbx = 0x00007f6560000d30   r12 = 0x00007f65ae372d40
    r13 = 0x00007f6560000a98   r14 = 0x000000000000000a
    r15 = 0x000000000000a686   rip = 0x00007f65b82c1523
    rsp = 0x00007f65ae372b80   rbp = 0x00007f6560000fc8
    Found by: given as instruction pointer in context
 1  phantomjs + 0x15c1a19
    rip = 0x00000000019c1a1a   rsp = 0x00007f65ae372b90
    Found by: stack scanning
 2  phantomjs + 0x15c2df1
    rip = 0x00000000019c2df2   rsp = 0x00007f65ae372c30
    Found by: stack scanning
 3  librt-2.12.so + 0x3ea5
    rip = 0x00007f65b8f34ea6   rsp = 0x00007f65ae372c50
    Found by: stack scanning
 4  phantomjs + 0x150d5a3
    rip = 0x000000000190d5a4   rsp = 0x00007f65ae372c70
    Found by: stack scanning
 5  phantomjs + 0x15a09e3
    rip = 0x00000000019a09e4   rsp = 0x00007f65ae372ca0
    Found by: stack scanning
 6  phantomjs + 0x150d628
    rip = 0x000000000190d629   rsp = 0x00007f65ae372cb0
    Found by: stack scanning
 7  phantomjs + 0x15c2795
    rip = 0x00000000019c2796   rsp = 0x00007f65ae372cc0
    Found by: stack scanning
 8  phantomjs + 0x15c2835
    rip = 0x00000000019c2836   rsp = 0x00007f65ae372cf0
    Found by: stack scanning
 9  phantomjs + 0x15c3f6a
    rip = 0x00000000019c3f6b   rsp = 0x00007f65ae372d40
    Found by: stack scanning
10  phantomjs + 0x159bdc1
    rip = 0x000000000199bdc2   rsp = 0x00007f65ae372d90
    Found by: stack scanning
11  phantomjs + 0x159c123
    rip = 0x000000000199c124   rsp = 0x00007f65ae372dc0
    Found by: stack scanning
12  libstdc++.so.6.0.13 + 0xbd0bc
    rip = 0x00007f65b8acb0bd   rsp = 0x00007f65ae372dd0
    Found by: stack scanning
13  phantomjs + 0x14b59ee
    rip = 0x00000000018b59ef   rsp = 0x00007f65ae372e10
    Found by: stack scanning
14  phantomjs + 0x14b8291
    rip = 0x00000000018b8292   rsp = 0x00007f65ae372e60
    Found by: stack scanning
15  libpthread-2.12.so + 0x7aa0
    rip = 0x00007f65b8d1baa1   rsp = 0x00007f65ae372ea0
    Found by: stack scanning

Thread 4
 0  libpthread-2.12.so + 0xb68c
    rbx = 0x000000000398d3e0   r12 = 0xffffffffffffffff
    r13 = 0x004189374bc6a7ef   r14 = 0x0000000000000000
    r15 = 0x000000000398d408   rip = 0x00007f65b8d1f68c
    rsp = 0x00007f65acc16d40   rbp = 0x0000000003784760
    Found by: given as instruction pointer in context
 1  phantomjs + 0x14b8a9a
    rip = 0x00000000018b8a9b   rsp = 0x00007f65acc16d70
    Found by: stack scanning
 2  linux-gate.so + 0x8bb
    rip = 0x00007fffa56c58bc   rsp = 0x00007f65acc16da0
    Found by: stack scanning
 3  phantomjs + 0xd3402
    rip = 0x00000000004d3403   rsp = 0x00007f65acc16df0
    Found by: stack scanning
 4  phantomjs + 0xb13a4e
    rip = 0x0000000000f13a4f   rsp = 0x00007f65acc16e20
    Found by: stack scanning
 5  phantomjs + 0xd2eaa
    rip = 0x00000000004d2eab   rsp = 0x00007f65acc16e50
    Found by: stack scanning
 6  phantomjs + 0x14b8291
    rip = 0x00000000018b8292   rsp = 0x00007f65acc16e60
    Found by: stack scanning
 7  libpthread-2.12.so + 0x7aa0
    rip = 0x00007f65b8d1baa1   rsp = 0x00007f65acc16ea0
    Found by: stack scanning

Thread 5
 0  libc-2.12.so + 0xe1523
    rbx = 0x00007f6558000d30   r12 = 0x00007f6565445d40
    r13 = 0x00007f6558000a98   r14 = 0x0000000000000011
    r15 = 0x000000000000a6a7   rip = 0x00007f65b82c1523
    rsp = 0x00007f6565445b80   rbp = 0x00007f6558000fc8
    Found by: given as instruction pointer in context
 1  phantomjs + 0x15c1a19
    rip = 0x00000000019c1a1a   rsp = 0x00007f6565445b90
    Found by: stack scanning
 2  phantomjs + 0x15c2df1
    rip = 0x00000000019c2df2   rsp = 0x00007f6565445c30
    Found by: stack scanning
 3  librt-2.12.so + 0x3ea5
    rip = 0x00007f65b8f34ea6   rsp = 0x00007f6565445c50
    Found by: stack scanning
 4  phantomjs + 0x150d5a3
    rip = 0x000000000190d5a4   rsp = 0x00007f6565445c70
    Found by: stack scanning
 5  phantomjs + 0x15a09e3
    rip = 0x00000000019a09e4   rsp = 0x00007f6565445ca0
    Found by: stack scanning
 6  phantomjs + 0x150d628
    rip = 0x000000000190d629   rsp = 0x00007f6565445cb0
    Found by: stack scanning
 7  phantomjs + 0x15c2795
    rip = 0x00000000019c2796   rsp = 0x00007f6565445cc0
    Found by: stack scanning
 8  phantomjs + 0x15c2835
    rip = 0x00000000019c2836   rsp = 0x00007f6565445cf0
    Found by: stack scanning
 9  phantomjs + 0x15c3f6a
    rip = 0x00000000019c3f6b   rsp = 0x00007f6565445d40
    Found by: stack scanning
10  phantomjs + 0x159bdc1
    rip = 0x000000000199bdc2   rsp = 0x00007f6565445d90
    Found by: stack scanning
11  phantomjs + 0x159c123
    rip = 0x000000000199c124   rsp = 0x00007f6565445dc0
    Found by: stack scanning
12  libstdc++.so.6.0.13 + 0xbd0bc
    rip = 0x00007f65b8acb0bd   rsp = 0x00007f6565445dd0
    Found by: stack scanning
13  phantomjs + 0x14b59ee
    rip = 0x00000000018b59ef   rsp = 0x00007f6565445e10
    Found by: stack scanning
14  phantomjs + 0x14b8291
    rip = 0x00000000018b8292   rsp = 0x00007f6565445e60
    Found by: stack scanning
15  libpthread-2.12.so + 0x7aa0
    rip = 0x00007f65b8d1baa1   rsp = 0x00007f6565445ea0
    Found by: stack scanning

Thread 6
 0  libc-2.12.so + 0xe1523
    rbx = 0x00007f655c000d10   r12 = 0x00007f6567ffe220
    r13 = 0x00007f655c000a78   r14 = 0x0000000000000013
    r15 = 0x000000000000a6a7   rip = 0x00007f65b82c1523
    rsp = 0x00007f6567ffe060   rbp = 0x00007f655c000fa8
    Found by: given as instruction pointer in context
 1  phantomjs + 0x15c1a19
    rip = 0x00000000019c1a1a   rsp = 0x00007f6567ffe070
    Found by: stack scanning
 2  phantomjs + 0x15c2df1
    rip = 0x00000000019c2df2   rsp = 0x00007f6567ffe110
    Found by: stack scanning
 3  librt-2.12.so + 0x3ea5
    rip = 0x00007f65b8f34ea6   rsp = 0x00007f6567ffe130
    Found by: stack scanning
 4  phantomjs + 0x150d5a3
    rip = 0x000000000190d5a4   rsp = 0x00007f6567ffe150
    Found by: stack scanning
 5  phantomjs + 0x15a09e3
    rip = 0x00000000019a09e4   rsp = 0x00007f6567ffe180
    Found by: stack scanning
 6  phantomjs + 0x150d628
    rip = 0x000000000190d629   rsp = 0x00007f6567ffe190
    Found by: stack scanning
 7  phantomjs + 0x15c2795
    rip = 0x00000000019c2796   rsp = 0x00007f6567ffe1a0
    Found by: stack scanning
 8  phantomjs + 0x14294ef
    rip = 0x00000000018294f0   rsp = 0x00007f6567ffe1b0
    Found by: stack scanning
 9  phantomjs + 0x15c2835
    rip = 0x00000000019c2836   rsp = 0x00007f6567ffe1d0
    Found by: stack scanning
10  phantomjs + 0x15c3f6a
    rip = 0x00000000019c3f6b   rsp = 0x00007f6567ffe220
    Found by: stack scanning
11  phantomjs + 0x159bdc1
    rip = 0x000000000199bdc2   rsp = 0x00007f6567ffe270
    Found by: stack scanning
12  phantomjs + 0x159c123
    rip = 0x000000000199c124   rsp = 0x00007f6567ffe2a0
    Found by: stack scanning
13  libstdc++.so.6.0.13 + 0xbd0bc
    rip = 0x00007f65b8acb0bd   rsp = 0x00007f6567ffe2b0
    Found by: stack scanning
14  phantomjs + 0x14263ca
    rip = 0x00000000018263cb   rsp = 0x00007f6567ffe2f0
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x02388fff  phantomjs  ???  (main)
0x7f6565547000 - 0x7f65675fefff  ukai.ttc  ???
0x7f65ac18f000 - 0x7f65ac1a0fff  n019004l.pfb  ???
0x7f65ac1a1000 - 0x7f65ac1b4fff  n019003l.pfb  ???
0x7f65ad555000 - 0x7f65ad75afff  libnss_dns-2.12.so  ???
0x7f65ad75b000 - 0x7f65ad968fff  libnss_files-2.12.so  ???
0x7f65b071c000 - 0x7f65b0939fff  libselinux.so.1  ???
0x7f65b093b000 - 0x7f65b0b52fff  libresolv-2.12.so  ???
0x7f65b0b55000 - 0x7f65b0d57fff  libkeyutils.so.1.3  ???
0x7f65b0d58000 - 0x7f65b0f62fff  libkrb5support.so.0.1  ???
0x7f65b0f63000 - 0x7f65b118dfff  libk5crypto.so.3.1  ???
0x7f65b118f000 - 0x7f65b1392fff  libcom_err.so.2.1  ???
0x7f65b1393000 - 0x7f65b1679fff  libkrb5.so.3.3  ???
0x7f65b167a000 - 0x7f65b18bdfff  libgssapi_krb5.so.2.2  ???
0x7f65b18be000 - 0x7f65b1b2afff  libssl.so.1.0.1e  ???
0x7f65b1b2b000 - 0x7f65b1d40fff  libz.so.1.2.3  ???
0x7f65b1d41000 - 0x7f65b2120fff  libcrypto.so.1.0.1e  ???
0x7f65b2125000 - 0x7f65b7fb7fff  locale-archive  ???
0x7f65b7fb8000 - 0x7f65b81dffff  libexpat.so.1.5.2  ???
0x7f65b81e0000 - 0x7f65b856ffff  libc-2.12.so  ???
0x7f65b8574000 - 0x7f65b8789fff  libgcc_s-4.4.7-20120601.so.1  ???
0x7f65b878a000 - 0x7f65b8a0dfff  libm-2.12.so  ???
0x7f65b8a0e000 - 0x7f65b8cfefff  libstdc++.so.6.0.13  ???
0x7f65b8d14000 - 0x7f65b8f2cfff  libpthread-2.12.so  ???
0x7f65b8f31000 - 0x7f65b9138fff  librt-2.12.so  ???
0x7f65b9139000 - 0x7f65b933cfff  libdl-2.12.so  ???
0x7f65b933d000 - 0x7f65b9572fff  libfontconfig.so.1.4.4  ???
0x7f65b9573000 - 0x7f65b980ffff  libfreetype.so.6.3.22  ???
0x7f65b9810000 - 0x7f65b982ffff  ld-2.12.so  ???
0x7f65b9a06000 - 0x7f65b9a08fff  87f5e051180a7a75f16eb6fe7dbd3749-le64.cache-3  ???
0x7f65b9a09000 - 0x7f65b9a11fff  b79f3aaa7d385a141ab53ec885cc22a8-le64.cache-3  ???
0x7f65b9a12000 - 0x7f65b9a14fff  0b1bcc92b4d25cc154d77dafe3bceaa0-le64.cache-3  ???
0x7f65b9a15000 - 0x7f65b9a1bfff  928306c3ad40271d946e41014a49fc28-le64.cache-3  ???
0x7f65b9a25000 - 0x7f65b9a2bfff  fa1582dab13e7e8e44e5a9424d309f0e-le64.cache-3  ???
0x7f65b9a2c000 - 0x7f65b9a2dfff  1330cd86dad428eb4f844a6851ce1545-le64.cache-3  ???
0x7fffa56c5000 - 0x7fffa56c5fff  linux-gate.so  ???

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
