### ISSUE TITLE
X-Frame-Options

### ISSUE THREAD

**Issue by shenlanchenwei** [ariya/phantomjs#15382]
How to make him not report this error?

Invalid 'X-Frame-Options' header encountered when loading 'https://idmsa.apple.com/1': 'ALLOW-FROM https://appleid.apple.com' is not a recognized directive. The header will be ignored. 

Unrecognized Content-Security-Policy directive 'frame-ancestors'.

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
