### ISSUE TITLE
Focus on Linux only for the time being

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#15398]
Most of the typical use cases of PhantomJS are very natural on Linux OS. As long as there is a limited amount of maintenance capacity (#14541) and not enough help on other platforms, let's just focus on making sure that the Linux experience is top notch.

Note that this is a matter of priority, not anything related to philosophical.

A possible workaround for Windows: use [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl). For macOS? Another workaround idea is to use Docker.

**Comment by kensoh** [comment]
Hi Ariya, welcome back to action on PhantomJS, this is exciting! :heart:

We exchanged over email before, just want you to know that though PJS was  not actively maintained for a while, I'm still using PJS as the execution engine for an open-source [process automation tool](https://github.com/kelaberetiv/TagUI) I created and the [Python version of it](https://github.com/tebelorg/TagUI-Python).

Not trying to shamelessly plug here, but to feedback on the impact of your work. Collectively there are 10k users for the tools now. I can't imagine the extend of the entire userbase from other tools built on PJS and direct PJS deployments. Fyi Nicholas 👋 @n1k0

**Comment by ariya** [comment]
Thank you for your kind words @kensoh!

**Comment by ByronAP** [comment]
just wanted to say I am very excited to see you here again 👏 🙇

**Comment by drmrbrewer** [comment]
Great to see you here @ariya, your work on this project is very much valued and appreciated.  Focusing on Linux seems to be a good compromise if time and resources are limited.

**Comment by MirLach** [comment]
I am using old version of PhantomJS on FreeBSD. I would like to try something newer from the current state of your repository. Are you willing to incorporate some patches (if I will create some) to make it build and run on FreeBSD?

**Comment by ariya** [comment]
> I am using old version of PhantomJS on FreeBSD. I would like to try something newer from the current state of your repository. Are you willing to incorporate some patches (if I will create some) to make it build and run on FreeBSD?

Yes, please file pull requests! Thank you very much 👍
