### ISSUE TITLE
[python] throws “ No connection could be made because the target machine actively refused it” error without using quit 

### ISSUE THREAD

**Issue by Sreyas-Sreelal** [ariya/phantomjs#15394]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1
2. What steps will reproduce the problem?
  Use following code to reproduce the problem
```Python
from selenium import webdriver
import time
import os

class Account:
    def __init__(self,client):
        self.client = client
        self.foo()

    def foo(self):
        self.client.get("https://google.com")

class User:
    def __init__(self,id):
        self.id = id

    def search(self,account):
        account.client.get("https://wwww.google.com")


client = webdriver.PhantomJS()
a = Account(client)
a.foo()

while True:
    someid = input("Input id : ")
    u = User(someid)
    u.search(a)
    while True:
        try:
            u.search(a)
            os.system("cls")
            print("Started.... press ctrl+c to stop")
            time.sleep(1)
        except KeyboardInterrupt:
            break
    if input("Search more? (y/n)").lower() == "n":
        break
```

3. Which operating system are you using?
 Windows 10
4. Did you use binary PhantomJS or did you compile it from source?
  Binary
5. Please provide any additional information below.
Run the minimal repro i provided.
The error :
  

>  No connection could be made because the target machine actively refused it

is been thrown in the second iteration of first while (when i stops inside loop and allow continuation of first loop)

Python version is 3.5

**Log :** - [ghostdriver.log](https://github.com/ariya/phantomjs/files/2064631/ghostdriver.log)

**Comment by ariya** [comment]
Thank you for the report!
From the problem, it may require some troubleshooting on the webdriver side. Care to move the report to https://github.com/detro/ghostdriver?
