### ISSUE TITLE
Wait for pending Ajax requests

### ISSUE THREAD

**Issue by omarsafwany** [ariya/phantomjs#15390]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
I am using the node package
https://www.npmjs.com/package/phantom

2. Which operating system are you using?
Mac OSX

5. Please provide any additional information below.

I am saving a url as PDF after loading completely but there are some Ajax requests that continue to work after the page is loaded. This is results in a file with incomplete pages.

Is there a way to wait for the pending Ajax requests to complete before saving the file? I am currently using a timeout but it is not the best case scenario as this mainly depends on the network.

**Comment by DanielRuf** [comment]
Why not try Puppeteer / Chrome headless?

**Comment by omarsafwany** [comment]
@DanielRuf Puppeteer looks good but needs to download many packages when using it with docker. I am trying to see if there is any other available way with PhantomJS and then decide if the timeout would be my solution or just switch to Puppeteer.

**Comment by DanielRuf** [comment]
> @DanielRuf Puppeteer looks good but needs to download many packages when using it with docker. I am trying to see if there is any other available way with PhantomJS and then decide if the timeout would be my solution or just switch to Puppeteer.

There are also Docker images with Chrome (headless) preinstalled and Puppeteer can use an existing Chrome version instead of downloading Chromium.

**Comment by omarsafwany** [comment]
@DanielRuf and this would not require any further configuration?

**Comment by ariya** [comment]
Thank you for the question!
You can watch the network resposenses and determine yourself if all traffic is reasonably completed.
See e.g. http://phantomjs.org/network-monitoring.html.
