### ISSUE TITLE
useragent example uses outdated selector

### ISSUE THREAD

**Issue by Zajn** [ariya/phantomjs#15392]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
  - Run `phantomjs examples/useragent.js`
  -  Observe JavaScript error output

3. Which operating system are you using?
macOS 10.12.6

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.
When running the `useragent.js` example, I encountered some unexpected output:

```
The default user agent is Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1
TypeError: null is not an object (evaluating 'document.getElementById('myagent').innerText')

  undefined:2
  :3
null
```

It seems that the DOM structure of www.httpuseragent.org has changed since this example was last updated.

**Comment by ariya** [comment]
Thanks for the pull request @Zajn! This should be fixed now.
