### ISSUE TITLE
Best-effort basis: Support building for macOS

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#15406]
Although the current priority is to focus on macOS (#15398), there is no harm in making sure that building for Windows is supported or partially supported, with no 100% guarantee.
At least, this serves as a good stepping stone for any external contribution.

**Comment by ariya** [comment]
The bad news: Homebrew [does not support](https://github.com/Homebrew/homebrew-core/pull/19438) community QtWebKit 5.212.

**Comment by vitallium** [comment]
I have been working on a Homebrew formula for it.

**Comment by kensoh** [comment]
Hi Ariya and Vitaly, adding for your info and you might be aware already. There is some OS changes around its SSL dependency that can be crippling for PhantomJS users.

macOS has switched away from OpenSSL to LibreSSL, thus users will get the following message when trying to run PhantomJS and execution halts -

```
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
```

This issue could be fixed until recently by simply using Homebrew `brew install openssl`, that will get OpenSSL installed on macOS to fulfil that dependency. However in a recent Homebrew release, it has upgraded to using OpenSSL v1.1, thus reintroducing back the error message.

The workaround I use now is by running custom formula by retrieving an old one from commit instead and updating with the new SHA values of the current one, and hosting the formula - 

```
brew install https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb
```

The context for use is an automation tool I developed using PhantomJS as the JS execution engine, and I tracked details of this through the issue - https://github.com/kelaberetiv/TagUI/issues/86

**Comment by kensoh** [comment]
Fyi too, this OpenSSL issue impacts many other apps as well, so there's like a couple of thousand people visiting above issue every week, most of which are users of other apps inc PyTorch and nothing to do with my project, but it's just that the result popup first on google.

![Screenshot 2020-01-04 at 4 48 23 AM](https://user-images.githubusercontent.com/10379601/71748815-b4c1ac00-2eae-11ea-95bf-d766234cf22e.png)

**Comment by ariya** [comment]
Thanks @kensoh for bringing up the awareness! Let's keep an eye on this issue.
