### ISSUE TITLE
Add tests for ES2015 syntax and run-time features

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#15402]
In addition to prevent any future regressions, this is also useful to demonstrated what is currently being supported.

**Comment by vitallium** [comment]
Some time ago, while I was preparing a 2.5 binary I used https://kangax.github.io/compat-table/es2016plus/ to test supported features. [The old screenshot](https://twitter.com/Vitalliumm/status/709479319786147840) needs an update
