### ISSUE TITLE
Best-effort basis: Support building for Windows

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#15405]
Although the current priority is to focus on Linux (#15398), there is no harm in making sure that building for Windows is supported or partially supported, with no 100% guarantee.
At least, this serves as a good stepping stone for any external contribution.

**Comment by ariya** [comment]
The good news: the community QtWebKit 5.212 is available as [MinGW package](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-qtwebkit) for MSYS2.

**Comment by ariya** [comment]
The bad news: the package seems to currently broken (see https://github.com/msys2/MINGW-packages/issues/5934 or https://github.com/msys2/MINGW-packages/issues/6020), perhaps even due to a new GCC.

**Comment by annulen** [comment]
It's possible to build static Conan packages of QtWebKit (all dependencies are already packaged) and use them for building of binaries of PhantomJS for all platforms in some CI service. The only trouble is building QtWebKit, of course, but GitHub Actions should be able to manage that

**Comment by safrizal** [comment]
tapi saya disuruh harus pakai ini :  
cmake . -G "MSYS Makefiles", 
bukan ini : 
cmake . -G "MinGW Makefiles"

**Comment by annulen** [comment]
"MSYS Makefiles" should be used when running in MSYS shell, "MinGW Makefiles" - when using cmd.exe and mingw32-make

**Comment by ariya** [comment]
Thanks to the combination of MSYS2, updated qtwebkit package for MSYS2, GCC and Clang, as well as the infrastructure of GitHub Actions, finally we have the CI system running the build of the latest master branch on Windows, for both GCC and Clang!

![image](https://user-images.githubusercontent.com/7288/83570588-2d1eae80-a4db-11ea-8e8a-e4b989306c4a.png)


Check the log for more details: https://github.com/ariya/phantomjs/actions.

Currently Windows build with MSYS2 is bit longer, around 7 minutes, compared to the Linux build (typically finishes in 2 minutes) because of the need to install various packages through Pacman. We'll find some ways to cache those packages and to optimized the bulild time.

**Comment by SuperPat45** [comment]
I try to compile the master branch, but the executable I obtain is compiled with shared library linkage mode.

How can I compile in static library linkage mode, allowing redistribution of a single executable without any dependancy ?
