### ISSUE TITLE
Azure Pipelines for CI

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#15403]
[Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) is a managed CI offering unlimited build minutes for open-source projects.

It also supports building for all popular desktop platforms: Linux, macOS, and Windows.

**Comment by annulen** [comment]
It seems like GitHub Action provide much more interesting conditions for public repositories, see my analysis of their docs at https://github.com/qtwebkit/qtwebkit/issues/948

**Comment by ariya** [comment]
> It seems like GitHub Action provide much more interesting conditions for public repositories, see my analysis of their docs at [qtwebkit/qtwebkit#948](https://github.com/qtwebkit/qtwebkit/issues/948)

It's interesting, since I believe GitHub Actions is based on Azure Pipelines anyway ([source](https://twitter.com/natfriedman/status/1159526215658561536)), so might as well use Azure Pipelines directly. It would be insightful to check if the same "free" (more like fair usage) policy applies.

**Comment by ariya** [comment]
Note that the CI is now GitHub Actions, due to the better integration with the rest of GitHub.
