### ISSUE TITLE
Check and enforce C++ coding style

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#15404]
Use [clang-format](https://clang.llvm.org/docs/ClangFormat.html) to ensure consistent C++ coding style.

Let's also run this as part of the CI system (#15403) so that PR can be checked for coding style consistency.

**Comment by HouzuoGuo** [comment]
@ariya Welcome back to PhantomJS! Thanks for resuming its development, looking forward to the first phantomjs 3 release :)

**Comment by vitallium** [comment]
@ariya [Qt's coding style](https://code.qt.io/cgit/qt/qt5.git/tree/_clang-format) may I assume?

**Comment by vitallium** [comment]
* [ ] Remove `astyle` from [sources](./tools/check-style.sh)

**Comment by ariya** [comment]
> @ariya [Qt's coding style](https://code.qt.io/cgit/qt/qt5.git/tree/_clang-format) may I assume?

IMO we might as well use (the built-in) WebKit style, hence no further tweak is necessary.

**Comment by ariya** [comment]
This is now in effect, yay!

**Comment by alex-kovalchuk** [comment]
Thank you!!!
