### ISSUE TITLE
Switch to WPEWebKit?

### ISSUE THREAD

**Issue by philn** [ariya/phantomjs#15413]
QtWebKit is no longer really maintained and most likely by now has a significant amount of unpatched security issues, compared to the upstream WebKit ports. Would you consider accepting a port of PhantomJS to [WPEWebKit](https://wpewebkit.org)?

There's a few limitations in the main WPE rendering backend (WPEBackend-FDO), mostly lack of headless (mesa surfaceless) support and NVIDIA GPU. Those issues are known and probably will be fixed in the future :)

Anyway, let us know if you're interested in collaborating on this :) And feel free to close the issue if you're not.

Thanks for PhantomJS, I think it's a great project and I'm happy that maintenance activities are happening again :)

**Comment by ariya** [comment]
Hi @philn, I'm always happy to explore various alternatives! If you have a variant/fork that is using WPE WebKit, let me know and I'd be very keen to take a look. Thank you very much!

**Comment by philn** [comment]
Alright, I'll probably get started on a fork then, when I have enough free time :)
