### ISSUE TITLE
API website suffers from failed mixed content

### ISSUE THREAD

**Issue by michael-o** [ariya/phantomjs#15419]
Going to https://phantomjs.org/api/phantom/ Firefox blocks mixed content, neither Droid font nor `main.css` are loaded. Please change `http://` to `https:` or use something protocol-relative, e.g., `//example.com/...`.

**Comment by HolgerJeromin** [comment]
The issue has been solved.

**Comment by ariya** [comment]
Thank you @michael-o and @HolgerJeromin!
