### ISSUE TITLE
Upgraded QTWebkit5

### ISSUE THREAD

**Issue by SuperPat45** [ariya/phantomjs#15429]
I use PhantomJS to make some screenshots automatically.

My website now use heavily standard CSS variables who is not supported by the last released version of PhantomJS.
Version 2.1 use a WebKit version equivalent to Safari 8 and CSS variables was introduced in Safari 9

Does the latest dev branch of this repository have an updated QTWebkit5 ?

**Comment by ariya** [comment]
Hi @SuperPat45, you can try building from the master branch. Hope it works for your case.
