### ISSUE TITLE
How to add content page 

### ISSUE THREAD

**Issue by AnanthGopal** [ariya/phantomjs#15422]
I need to add a content page like below sample, is it possible phantomjs ?
![image](https://user-images.githubusercontent.com/13050426/77291713-cd4e9f00-6d04-11ea-952c-6d889733db26.png)

**Comment by HolgerJeromin** [comment]
This looks like an integrated PDF viewer as included in some modern browsers. 
phantomjs does not include a PDF viewer and it is disputable if it should have.

**Comment by AnanthGopal** [comment]
can you give me any idea to implement this option?

**Comment by HolgerJeromin** [comment]
> can you give me any idea to implement this option?

How much coding experience do you have?

**Comment by AnanthGopal** [comment]
I have near 5-year experience .net

**Comment by AnanthGopal** [comment]
Sorry, i am not asking about PDF viewer option, I asked Content page like 
                                           Table Content
1. User Details                                                                                1
2. Role Details                                                                                5

When i click user details, it will navigate into 1 page, when I click Role Details, it will navigate into 5 page.

I can create the above table  content  by using HTML but i can't add page number like 1,  5, because of all the details i get from database, sometimes user details have 4 pages, sometimes it will be reduced or increased so that i need your help
