### ISSUE TITLE
Caan´t send arguments to evaluateJavaScript

### ISSUE THREAD

**Issue by tuxrick** [ariya/phantomjs#15433]
**Describe the problem**
Data sent over evaluateJavasScript is null 

**Versions**
phantom for node "phantom": "^6.3.0",

**Steps to Reproduce**
1. After call page.open 
2.
let email = "tuxrick@gmail.com"; 
			_page.evaluateJavaScript(function(){
				alert(email);
				document.querySelector("._50f6").appendChild(document.createTextNode(email));
	            document.querySelector("input[name='email']").value =  "pp";
	            document.querySelector("input[name='pass']").value = "rickpingu182";
	            //document.querySelector("#login_form").submit();				  
	        }, email);	        

The email is undefined or [object HTMLinput]

I also tried
			_page.evaluateJavaScript(function(){
	             document.querySelector("._50f6").appendChild(document.createTextNode(email));
	            document.querySelector("input[name='email']").value =  "pp";
	            document.querySelector("input[name='pass']").value = "rickpingu182";
	            //document.querySelector("#login_form").submit();				  
	        });

**Expected behavior**
email should be tuxrick@gmail.com

**Additional context**
I only need to pass arguments to the DOM

**Comment by theighost** [comment]
Try to pass the JS function to be called in the browser, as a string, inside the string you can add whatever server-side variables you like: 

```
let functionToCall = "function(){console.info('"+someVariable+"');}"
let result = await page.evaluateJavaScript(functionToCall);
```
