### ISSUE TITLE
Phantomjs for ppc64

### ISSUE THREAD

**Issue by madscientist159** [ariya/phantomjs#15432]
This is reopening auto-closed (ignored) issue #14421.  OpenPOWER is a mature, stable, high performance open ISA with server, desktop, and embedded class machines available, and we need support added for ppc64le.  The lack of support makes building e.g. ONLYOFFICE needlessly difficult (thankfully distros have prebuilt packages, but versions do not match what is desired), and as the prior issue noted the sources do in fact build on POWER.

What do we need to have happen to get a POWER binary added for download?

**Comment by ariya** [comment]
Hi @madscientist159, thanks for the report! If you want to contribute the POWER binary, just fork this repository, prepare a build script to produce such a binary, report back and we'll see what we can do about it.
Please note that nobody is actively working on version 2.1 anymore.

**Comment by AGSaidi** [comment]
@madscientist159 I imagine #15442  will get you most of the way there just by fixing the openssl architecture and building in a ubuntu ppc64le container

**Comment by ariya** [comment]
Closing this for now. Thank you!
