### ISSUE TITLE
Please don't discontinue development on this.

### ISSUE THREAD

**Issue by acidhorse1972** [ariya/phantomjs#15436]
I see potential use for your code when writing tools that can help eliminate Russian Lotto spambots that are circulating on Instagram. Instagram utilizes javascript and wouldn't possibly proceed down an allowable path for logging in and maintaining a user's credentials which is necessary. Also when web scraping "followers" and "following" it maybe necessary to handle the javascript.
If I'm not aware of another solution that supersedes this then please inform me.
Preferably a solution that doesn't require writing the bulk of the code from scratch or taking an exhaustive long path to accomplish this as in contrast to a single night with a minimum amount of code.
I'm "_ _ _l_o_n_e_w_o_l_f_ _ _" on Instagram

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mileserickson** [comment]
@acidhorse1972 You can use `selenium.webdriver` with either Firefox or Chrome in headless mode.
