### ISSUE TITLE
how to improve the quality of thumbnail generated

### ISSUE THREAD

**Issue by programmerarunkumar** [ariya/phantomjs#15444]
**Describe the problem**
How to improve the quality of thumbnail generated using rasterize.js
Thumbnail size
1.300x170 
2.200x170

PhantomJS version : 2.1.1
OS: Linux

In My rasterize.js
1.used viewport size 
2.used quality in page.render

**Actual behavior**
Quality of the thumbnail is not good 

**Expected behavior**
Need a high quality thumbnail generation

**Comment by ariya** [comment]
Hi @programmerarunkumar, we need an example to show the expected quality that you want. Thanks!

**Comment by programmerarunkumar** [comment]
> Hi @programmerarunkumar, we need an example to show the expected quality that you want. Thanks!

what are the possible ways to improve the qauality of thumbnail image generated using rasterize.js  . Thanks!

**Comment by programmerarunkumar** [comment]
> Hi @programmerarunkumar, we need an example to show the expected quality that you want. Thanks!

---OriginalImage(960x540)--

![OriginalImage](https://user-images.githubusercontent.com/58946415/88186772-49290b80-cc53-11ea-8316-b4120391a41f.png)

--Thumbnail Image(300x170)---

![ThumbnailImages](https://user-images.githubusercontent.com/58946415/88186941-82617b80-cc53-11ea-9622-f61981454b0e.png)


Need to increase the resolution of the ThumbnailImage.
Used page.render(fileName, { format: 'png' ,quality: '100'}) , still not getting high resolution Thumbnail Image 
How to achive that ?

**Comment by ariya** [comment]
PhantomJS isn't intended to be a full-featured image processing tool. I recommend taking the original image and create the thumbnail with a dedicated utility such as ImageMagick.
Thank you very much!
