### ISSUE TITLE
TypeError: When babel-polyfill.js and custom-elements.js are used.

### ISSUE THREAD

**Issue by vbrin27** [ariya/phantomjs#15446]
I am using babel polyfill && custom-elements.min.js for my website and I have concatenated both the polyfills in a single file. 

When I try to run the testcases in PhantomJS(v 2.1.1) headless browser by loading this file in Karma testrunner, some errors are thrown which are not reproduced in other browsers.

The above issue is thrown in babel polyfill and if babel polyfill alone is used without custom-elements polyfill, there are no errors.

Error thrown:
[![with][2]][2]

The code which causes the error: (Line No: 5345)
[![enter image description here][3]][3]

Is there a way to solve this issue?

  [1]: https://www.npmjs.com/package/@webcomponents/custom-elements
  [2]: https://i.stack.imgur.com/u11KP.png
  [3]: https://i.stack.imgur.com/f7CU3.png

**Comment by jgonggrijp** [comment]
@vbrin27 The 2.x branch is no longer supported. See #15344. You may want to try whether the master branch works for you (future version 3). It has [installation instructions](https://github.com/ariya/phantomjs/blob/master/INSTALL).
