### ISSUE TITLE
Insert annotations into PDF

### ISSUE THREAD

**Issue by trannhutle** [ariya/phantomjs#15452]
Hi @ariya !

I am currently using the phantomJS to convert the HTML+CSS to PDF file by using this library : `https://github.com/marcbachmann/node-html-pdf`

Right now I can see the Anchor tag <a/> in my pdf document, how could I insert another kind of annotations in the PDF document.

If we could, would you mind giving me the example how to use it by using HTML and CSS.

![image](https://user-images.githubusercontent.com/14163032/108061688-c82cd800-70ac-11eb-926c-64a20ef74af1.png).

Thank you very much.
I am looking forward to hearing from you!

**Comment by HolgerJeromin** [comment]
I would ask marcbachmann or on stackoverflow.

**Comment by trannhutle** [comment]
@HolgerJeromin 

The `https://github.com/marcbachmann/node-html-pdf` is just a wrapper, they just call the PhamtomJS apis to do the conversion.

I would like to know the HTML tags or CSS class that I could render other kinds of annotation.
