### ISSUE TITLE
OFF TOPIC Request to open #15344

### ISSUE THREAD

**Issue by GreenLunar** [ariya/phantomjs#15451]
Hello, I think it would be a good idea to open #15344 for discussion.

-----

This is the comment that I want to write:

Hello,

With all due respect, I find it biased and unfair to call for the suspension of development:
1) as if there is only one authority to develop this project;
2) as if there's nothing else to do.

this is not a good attitude.

Moreover, announcing suspension of development in the first lines for the documentation and lean the homepage of phantomjs.org is too blatant and, at most, not helpful whatsoever.

Call it whatever you like, people are too shallow to read or, any person in the "information age" is overwhelmed with so much information from all-over, so much so __potential contributors and developers__ will read the suspension of development note and immediately go elsewhere.

Please,
1. Reopen issue #15344
2. Get rid of the suspension of development note
3. Restore the website.

_Always remember, [Ubiquity](http://web.archive.org/web/20081206110541/http://ubiquity.mozilla.com/) was killed by a so-called "centralized" source, not suspended for lack of contributors or audience._

Thank you.

**Comment by GreenLunar** [comment]
This is the comment that I want to write:

Hello,

With all due respect, I find it biased and unfair to call for the suspension of development:
1) as if there is only one authority to develop this project.
2) as if there's nothing else to do.
This is not a good attitude.
Moreover, announcing suspension of development in the first lines for the documentation and lean the homepage of phantomjs.org is at most not helpful whatsoever.

Call it whatever you like, people are too shallow to read or any person in the "information age" is overwhelmed with so much information, so much so potential contributors and developers will read the suspension of development note and immediately go elsewhere.

Please,
1. Reopen issue #15344
2. Get rid of the suspension of development note
3. Restore the website.

__Always remember, [Ubiquity](http://web.archive.org/web/20081206110541/http://ubiquity.mozilla.com/) was killed by a so-called "centralized" source, not suspended for lack of contributors.__

Thank you.

**Comment by jgonggrijp** [comment]
@GreenLunar For any unpaid open source project, maintenance work tends to land predominantly on the shoulders of a single person (or at most a few). This is probably one of the many examples of a [Pareto distribution](https://en.wikipedia.org/wiki/Pareto_distribution) and [PhantomJS is no exception](https://github.com/ariya/phantomjs/graphs/contributors).

Maintaining a project is much more than just fixing bugs and adding features. It means deciding on long-term goals, setting priorities and triaging issues. It means being the person who ensures that contributions meet a minimum level of quality. It means supporting users and fixing urgent issues when nobody else does it. It means ensuring that releases are published, that users are notified and that the website and the documentation are up-to-date. It means taking responsibility and making hard decisions. It's a heavy weight to lift and it tends to be done by someone who is very passionate about the project.

Closing the project (temporarily) was probably a very hard decision for @ariya, which I'm sure he didn't take lightly. Your post above doesn't acknowledge this side of the equation at all. Please show a bit more respect. As it is, your post is only illustrating how the discussion in #15344 was (or would be) "too heated".

**Comment by desbest** [comment]
My concern is that the ex-project lead admits that the current documentation isn't sufficient. So if it's lacking, that will prevent future programmers from contributing to the project, as they won't know what all the features are, what they do and how they work.

So #15343 **seriously** needs to be finished before any future programming happens, by anyone new who wishes to maintain the project. Software without good documentation is as good as dead.

Hypothetically, if I wanted to maintain this project so it would no longer be unmaintained, I wouldn't be able to due to the lack of good and efficient documentation.

PS. Ariya has a link on his profile asking for people to sponsor him. So if it's not expensive for people, someone could pay him to create an updated documentation, fix all the bugs and create a newer version. But I would ask you email him first, as he might not resume this project for a mere $5 a month.

**Comment by jgonggrijp** [comment]
@desbest Did Ariya state anywhere that he wasn't the maintainer anymore? I don't recall reading that anywhere, but I might have missed it.

In any case, the project is not archived anymore and Ariya made new commits to master after reopening (even if the most recent public commit was five months ago). So I would say that the project is no longer unmaintained, if it ever was. He seems to have been focusing on making the project more approachable for outside contributors as well, both before and after archiving.

Donating and contributing documentation etcetera definitely is a good idea for everyone wanting to help.

**Comment by desbest** [comment]
> @desbest Did Ariya state anywhere that he wasn't the maintainer anymore? I don't recall reading that anywhere, but I might have missed it.

Yes he did.

> #15344

> Due to the lack of active contribution, I am going to archive this project soon.
> At some point in the future, if we pick up the development again (such as #15341, #15342, #15343), the project will be unarchived.

He said he's not working on the project any more, and he was the lead developer and no one else has taken his place. So you should consider the project to be unmaintained. Whether he owns this git repository and the Phantom JS website is irrelevant, because no work is being done on the project.

**Comment by jgonggrijp** [comment]
@desbest I'm not reading "I'm not the maintainer of this project anymore" anywhere in that statement. In fact, I'm reading that he's still taking full responsibility, even if development is temporarily paused. Development is only a subset of maintenance. Archiving and unarchiving a project is also the job of a maintainer. If Ariya didn't consider himself the maintainer anymore, he wouldn't have unarchived the repository.

**Comment by ariya** [comment]
The project has been unarchived.

@GreenLunar what's your alternative proposal to the "suspension note" on the website? It can't be removed completely (otherwise, it gives an unrealistic expectation).

**Comment by GreenLunar** [comment]
> @GreenLunar For any unpaid open source project, maintenance work tends to land predominantly on the shoulders of a single person (or at most a few). This is probably one of the many examples of a Pareto distribution and PhantomJS is no exception.

I know. I know. It's not easy. I've dropped dozens of projects I've contributed to with translations, QA etc.


> @GreenLunar what's your alternative proposal to the "suspension note" on the website? It can't be removed completely (otherwise, it gives an unrealistic expectation).

Restore the website as it was when the project was more active and more popular, with the following exception:

Add a new bar says "New Maintainers" or "Maintainers Are Needed" or "Developers, PhantomJS Needs You" or WHATEVER YOU DECIDE.

How much hosting costs?
I'm willing to participate in some hosting expenses only as long as project is inactive.

**Comment by ariya** [comment]
> Restore the website as it was when the project was more active and more popular

Please submit a PR to the `gh-pages` branch.

**Comment by hcancelik** [comment]
@ariya Can you at least allow downloads to be downloaded from outside of US?

I'm currently in Turkey and cannot download this `https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2` file because the amazon URL(s3 bucket) is not accessible from here.

**Comment by wagnerpv** [comment]
> @ariya Can you at least allow downloads to be downloaded from outside of US?
> 
> I'm currently in Turkey and cannot download this `https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2` file because the amazon URL(s3 bucket) is not accessible from here.

@hcancelik if I upload this file here in ".zip" format would this resolve your issue?

**Comment by hcancelik** [comment]
Unfortunately, I cannot update the URL where it's being used (in a company docker file) otherwise I would copy it to any storage service. Thanks for the offer though.

**Comment by wagnerpv** [comment]
I'm not sure if my proposal was clear, I've meant this:

[phantomjs-2.1.1-linux-x86_64.zip](https://github.com/ariya/phantomjs/files/5895382/phantomjs-2.1.1-linux-x86_64.zip)

**Comment by wagnerpv** [comment]
> Unfortunately, I cannot update the URL where it's being used (in a company docker file) otherwise I would copy it to any storage service. Thanks for the offer though.

Oh! I think I've understood your point now... Sorry ~)
