### ISSUE TITLE
Deploy phantomjs to docker and take a screenshot

### ISSUE THREAD

**Issue by wangfan0524** [ariya/phantomjs#15461]
I deploy phantomjs in docker, and then call its interface through API to take screen shots. But the effect is not ideal. I want to use my own JS file to take a screenshot when calling the API, instead of the default JS in phantom JS.

Thank you very mych

**Comment by jgonggrijp** [comment]
@wangfan0524 Could [bind mounts](https://docs.docker.com/storage/bind-mounts/) possibly address your needs?

**Comment by wangfan0524** [comment]
Please be more detailed. I didn't understand it, or do you have any relevant examples for me to refer to? Thank you very much

**Comment by wangfan0524** [comment]
> @ wangfan0524能[绑定安装](https://docs.docker.com/storage/bind-mounts/)可能满足您的需求？

Please be more detailed. I didn't understand it, or do you have any relevant examples for me to refer to? Thank you very much

**Comment by jgonggrijp** [comment]
@wangfan0524 If I understood your question correctly, you want to use your own JavaScript script instead of one that is included in the Docker image by default. Bind mounts let you do that. I can't really get more specific, because your question is not very specific, either.
