### ISSUE TITLE
Trying to use PhantomJS on Ubuntu with CircleCI

### ISSUE THREAD

**Issue by safetypins** [ariya/phantomjs#15460]
I'm trying to use PhantomJS on an Ubuntu CircleCI image, but I'm getting the following error:

`phantomjs: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory`

I found an older issue related to this error, but there wasn't a solution posted there, just that on a clean install the problem went away. But when I run `ldd phantomjs` it says "not a dynamic executable". This error happens when I run `phantomjs -v`. Any ideas of how I can isolate what is causing this? I'm using Wraith with PhantomJS to do visual regression tests, but this error is occurring when I run `phantomjs -v` in the container, so I don't think it's related to Wraith. I'm downloading PhantomJS directly from `https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.5.0-beta-linux-ubuntu-xenial-x86_64.tar.gz`. Could it be because I'm trying to use a xenial release with Ubuntu 18.04 (bionic)? A version of the libjpeg library is installed; maybe i need to build it from source?

**Comment by hexydec** [comment]
Development on this project has been [suspended and it has been archived](https://github.com/ariya/phantomjs/issues/15344). Use [Puppeteer and Headless Chrome](https://github.com/puppeteer/puppeteer) instead.

**Comment by safetypins** [comment]
Thanks!
