### ISSUE TITLE
Why does the IMG tag in PDF footer not work?

### ISSUE THREAD

**Issue by ArronSun** [ariya/phantomjs#15462]
**Summary**
the img tag in PDF footer not work.
**Test cases**
![图片](https://user-images.githubusercontent.com/33828400/130775938-ba41833f-9a8c-4b9e-894a-6138142a0187.png)

I used footer like this ,I've tried many times , but the img tag in PDF footer not work, 
phantomjs  version 2.1.1

Is that a bug or I'm not using the right method, please answer me.

**Comment by Xiong-qi** [comment]
@ArronSun How do you deal with this problem?I had the same    @ariya 
![1](https://user-images.githubusercontent.com/34997642/207630997-494ef28c-f35b-4077-bbcf-0a276e3aeeee.PNG)
![2](https://user-images.githubusercontent.com/34997642/207631010-ad5b5ed6-8e98-45b2-8f37-ab898a419e7a.PNG)
![3](https://user-images.githubusercontent.com/34997642/207632101-cf177c82-641f-46b1-8c30-3b1b17f0e13c.PNG)
