### ISSUE TITLE
does it have golang api

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#15476]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jgonggrijp** [comment]
@aswallz The answer is no, PhantomJS does not have a Go API.

Next time you submit a ticket, please actually fill out all the sections in the issue template. Leaving the standard text in place does not help anyone to understand your issue.
