### ISSUE TITLE
Output of phantomjs with current git master is different to 2.1.1

### ISSUE THREAD

**Issue by the-me1988** [ariya/phantomjs#15485]
**Describe the problem**
Because of another issue we wanted to upgrade to the current git master version. But the output of our pdf script is completly different.

**Versions**
2.1.1: works
Current git master: works not
Tested on: Debian Buster (10) and Debian Bullseye (11)

**Steps to Reproduce**
phantomjs pdf_script

**Actual behavior**
The rendered page is completly different to the 2.1.1 behavior

**Expected behavior**
Same behavior as with 2.1.1 :-)

**Comment by the-me1988** [comment]
[test_211.pdf](https://github.com/ariya/phantomjs/files/9468502/test_211.pdf)
[test_git.pdf](https://github.com/ariya/phantomjs/files/
[pdf_script.txt](https://github.com/ariya/phantomjs/files/9468507/pdf_script.txt)
9468503/test_git.pdf)

**Comment by the-me1988** [comment]
Our script:
[pdf_script.txt](https://github.com/ariya/phantomjs/files/9468512/pdf_script.txt)

Output with 2.1.1:
[test_211.pdf](https://github.com/ariya/phantomjs/files/9468516/test_211.pdf)

Output with git master (broken):
[test_git.pdf](https://github.com/ariya/phantomjs/files/9468517/test_git.pdf)

**Comment by jgonggrijp** [comment]
@the-me1988 The `master` branch is progressing towards a 3.x release, so it is not necessarily expected to be compatible with the 2.x interface.

https://github.com/ariya/phantomjs/blob/0a0b0facb16acfbabb7804822ecaf4f4b9dce3d2/src/consts.h#L38

**Comment by the-me1988** [comment]
So this is not a bug but a wanted behavior? Do you have a migration guide or something like that so we can adopt it to the new "format" and when will 3.0 be finished? :)

**Comment by jgonggrijp** [comment]
I should clarify that I'm not involved in PhantomJS development myself. I just noticed a commit which mentioned the 3.x release series.

> So this is not a bug but a wanted behavior?

I don't think breaking that pdf script is intended per se. It's just that incompatible changes are considered permissible when upgrading the major version.

> Do you have a migration guide or something like that so we can adopt it to the new "format" and when will 3.0 be finished? :)

I don't know the answers to these questions, sorry. To speed things up, you can donate and/or contribute code and/or encourage other people to do those things.
